### ISSUE TITLE
vertical:true and vertical mouse scroll

### ISSUE THREAD

**Issue by carlosrberto** [kenwheeler/slick#1001]
when I set vertical:true, vertical mouse scroll doesn't work, the slide scroll vertically but only if mouse scroll horizontal

**Comment by simeydotme** [comment]
do you mean "___drag___" ?

**Comment by gborbonus** [comment]
I'm not sure that really applies. 

Scenario 1: The scroller is full width, and can take up the entire webpage.
 The scollability of the website will only be affected in Mobile case usage, but slick has responsive design built in to compensate for that.

Scenario 2: The scroller is the full page. Not really an issue as the scroller IS THE FULL PAGE.

Scenario 3: The scroller is only part of the webpage, in which case the vertical scroll event only exists in the space that scroller does, the making it not a problem.

Well, I don't really care about the response, I can code it out anyway. Just wanted to add my 2 cents.

**Comment by simeydotme** [comment]
hey @gborbonus :) If you can modify the slick prototypes to enable the vertical scrolling and then post the code here it would really help all the people who created the issues raised above... I will try to keep this updated and redirect everyone who creates a vertical scroll issue to here, so you'd be doing a favor for them all. ^_^;

Best, Simon.

**Comment by kenwheeler** [comment]
You know what. I'm tired of this. Slick 1.5, vertical swiping, its happening.

**Comment by simeydotme** [comment]
:+1: haha sorry, Bro!

**Comment by gborbonus** [comment]
Behind you 100%. you will make the rest of us VERY happy.

**Comment by kenwheeler** [comment]
Now available on master using the verticalScrolling: true option

**Comment by mhulse** [comment]
> `verticalScrolling: true`

Thank you for this!

I'm working on a Kiosk, and the scrollable area is a small portion of screen. Slick Carousel has been a life saver!!! :octocat: Many thanks for this feature addition. :smiley:

**Comment by Grawl** [comment]
@kenwheeler in last version, it's not available anymore. What version are you using in 2015?

**Comment by keremcankaya0** [comment]
After an hour of waste due to inertia and vertical options, here is the code 

HTML
```

<div class="container-fluid" style="height: 3000px">

    <div class="row">
        <div class="your-class js-listen-gestures">
            <div style="height: 600px;" class="bg-danger slide" ><h3>1</h3></div>
            <div style="height: 600px;" class="bg-danger slide" ><h3>2</h3></div>
            <div style="height: 600px;" class="bg-danger slide" ><h3>3</h3></div>
        </div>
    </div>


</div>

```
JS
```
$(function () {
    var SLIDER = (function () {

        var slider = {};

        slider.build = function ($selector) {

            var $currentSlider = $selector.slick({
                vertical: true,
                verticalSwiping: true,
                infinite: false,
                dots: true
            });

            //https://github.com/Promo/wheel-indicator
            // Indicates when user makes swipe gesture on a trackpad or mouse wheel.
            //And prevents inertia
            new WheelIndicator({
                //Zone to attach event listeners
                elem: document.querySelector('.js-listen-gestures'),
                callback: function (e) {
                    //Checking if last slide
                    if ($currentSlider.slick('slickCurrentSlide') == $currentSlider.find('.slide').length - 1) {
                        //Prevents mouse to let user slide down
                        this.setOptions({
                            preventMouse: false
                        });
                    }else{
                        this.setOptions({
                            preventMouse: true
                        });
                    }

                    //Slide direction
                    e.direction === 'up' ? $currentSlider.slick('slickPrev') : $currentSlider.slick('slickNext');

                }

            });

        };

        return slider;

    }());

    SLIDER.build($('.your-class'));
});
```

**Comment by Grawl** [comment]
@keremcankaya0 this plugin works bad in Safari 10.1.2 😞

**Comment by Grawl** [comment]
so, here's my simple solution: https://codepen.io/Grawl/pen/mMLQQb

**Comment by keremcankaya0** [comment]
@Grawl I have Safari 10.1.1 it works great, i'll test against 10.1.2. Your solution is not solving inertia which is causing trackpad to scroll twice.

**Comment by Grawl** [comment]
@keremcankaya0 I know about inertia problem and it's hard to solve I think.

**Comment by phellipelins** [comment]
@Grawl @keremcankaya0 
Changing `delta` conditional to require more intense scroll to exec `slickPrev` and `slickNext` methods solve the problem.

[https://codepen.io/Grawl/pen/mMLQQb](https://codepen.io/Grawl/pen/mMLQQb)

```
if(delta < -200) {
  $slider.slick('slickPrev')
}
else if(delta > 200) {
  $slider.slick('slickNext')
}
```

**Comment by Grawl** [comment]
@phellipelins works bad for me. Apparently we want to recognise a swipe from touch input device, not "mouse wheel" scroll events.
