### ISSUE TITLE
Can I slide to a specific slide on click from a certain slide

### ISSUE THREAD

**Issue by 416serg** [kenwheeler/slick#1002]
I have the slider used as an on-boarding feature and users may slide from one slide to another one, skipping certain ones. is that possible?

**Comment by kenwheeler** [comment]
What do you mean skipping? You can use $('selector').slick('slickGoTo', 3, true) to navigate to a slide without animating its path.

**Comment by simeydotme** [comment]
or you could `$('selector').slick('slickRemove', 2 );` to remove a slide if you're setting a specific flow for specific user based on specific options/selection during the on-boarding :)

**Comment by 416serg** [comment]
Well for example there are 6 slides, and on the third one, a user can either go to the forth, or skip it and go to the 6th. will `$('selector').slick('slickGoTo', 3, true)` work, with `3` being the number of the slide? does it count from 0 or 1?

**Comment by simeydotme** [comment]
The best part of web development is figuring things out yourself :D, but i
the spirit of open source: the index starts at 0, so 6th slide equals index
`5` .. But you'll need a custom link to trigger... Else you can use
`onAfterChange` event to remove slide 4 and 5 with `slickRemove`

Simon.
