### ISSUE TITLE
Width=0 After Resizing Window While display:none

### ISSUE THREAD

**Issue by rivdiv** [kenwheeler/slick#1004]
I have a panel in which I initiate a slick slider. This panel is initially *hidden* with display:none.

Because it is hidden, I call the resize() method after the user expands the panel, so the widths can be recalculated. This works fine.

However, if I expand the panel, then collapse it, then resize my browser window, and finally expand the panel again, the slides have width: 0px.

See this jsfiddle: http://jsfiddle.net/6z1Lc245/ 

Steps are:
1. expand panel
2. collapse panel
3. resize window
4. expand panel
5. widths are 0px

Is there a work-around for this behavior?

**Comment by kenwheeler** [comment]
I would wager to say you might need to call setDimensions on show.

**Comment by rivdiv** [comment]
DIdn't seem to do it? http://jsfiddle.net/6z1Lc245/1/
(Plus any code after that line doesn't get executed.)

**Comment by kenwheeler** [comment]
http://jsfiddle.net/Lp1gaL1e/

**Comment by KrisOlszewski** [comment]
@kenwheeler This still seems to be an issue if you have autoplay enabled with fade. After you open, then close, and open again the width is 0, then on next slide it updates to proper width causing a jump. No matter what I do it doesn't update until next slide fades in.

See here: http://jsfiddle.net/p4adf2s9/
