### ISSUE TITLE
1.4.x callback methods - on init event not working

### ISSUE THREAD

**Issue by me3design** [kenwheeler/slick#1005]
# New callback events

Is anyone else having an issue with the init event?  I'm having trouble getting init to work at all.

With the following code the beforeChange and afterChange events work, but the init event doesn't fire at all. I have tried version 1.4.0 and 1.4.1

My code looks like this:
```javascript
	$('.slider')
		.on('init', function(event, slick){
			// let's do this after we init the banner slider
			...
			console.log('slider was initialized');
		})
		.on('beforeChange', function(event, slick, currentSlide, nextSlide){
			// then let's do this before changing slides
			...
			console.log('before change');
		})
		.on('afterChange', function(event, slick, currentSlide, nextSlide){
			// finally let's do this after changing slides
			...
			console.log('after change');
		});
```
Using 1.3.9 and the older callback method the onInit works
```javascript
	$('.slider').slick({
		autoplay: true,
		autoplaySpeed: 5000,
		slidesToShow: 1,
		slidesToScroll: 1,
		dots: true,
		lazyLoad: 'ondemand',
		onInit: function() {
			// let's do this after we init the banner slider
			...
			console.log('slider was initialized');
		},
		onBeforeChange: function() {
			// then let's do this before changing slides
			...
			console.log('before change');
		},
		onAfterChange: function() {
			// finally let's do this after changing slides
			...
			console.log('after change');
		}
	});
```

**Comment by kenwheeler** [comment]
You need to bind it before calling slick on the element

**Comment by me3design** [comment]
Hi Ken, thanks for the quick reply.  I realize my code above made it look like I didn't bind slick before the calling the events but I was doing that.
I was doing this:
```javascript
    $('.slider').slick({
	autoplay: true,
	autoplaySpeed: 5000,
	dots: true,
	lazyLoad: 'ondemand'
    });
    $('.slider')
        .on('init', function(event, slick){
            // let's do this after we init the banner slider
            ...
            console.log('slider was initialized');
        })
        .on('beforeChange', function(event, slick, currentSlide, nextSlide){
            // then let's do this before changing slides
            ...
            console.log('before change');
        })
        .on('afterChange', function(event, slick, currentSlide, nextSlide){
            // finally let's do this after changing slides
            ...
            console.log('after change');
        });
```
And also tried this: 
```javascript
	$('.slider').slick({
		autoplay: true,
		autoplaySpeed: 5000,
		dots: true,
		lazyLoad: 'ondemand'
		})
		.on('init', function(event, slick){
			// let's do this after we init the banner slider
			...
			console.log('slider was initialized');
		})
		.on('beforeChange', function(event, slick, currentSlide, nextSlide){
			// then let's do this before changing slides
			...
			console.log('before change');
		})
		.on('afterChange', function(event, slick, currentSlide, nextSlide){
			// finally let's do this after changing slides
			...
			console.log('after change');
		});
```
I'm still unable to get the on init event to work at all.  The beforeChange and afterChange events work perfectly.  I appreciate you looking into it and for making such a great slider.  I have used it on numerous sites and think it is the best one out there.

**Comment by kenwheeler** [comment]
You're still binding the event after initializing slick. It needs to happen prior.

**Comment by me3design** [comment]
Got it!  Dang, sorry I was so thick on this issue.  Appreciate your help.

**Comment by kenwheeler** [comment]
It's all good homie. Happy slickin

**Comment by edyken77** [comment]
Can you provide a working example?  I can't seem to set an on int function because 'slick' is not defined yet.

**Comment by woodpig07** [comment]
@edyken77  you need to bind init function before 'slick' object initialization .
For example
     $('.slider').on('init', function(event, slick){
            console.log('slider was initialized');
     });
    $('.slider').slick({
        autoplay: true,
        autoplaySpeed: 5000,
        dots: true,
        lazyLoad: 'ondemand'
        });

**Comment by edyken77** [comment]
I see, I did have it bound before the object but my issue was the .on init function had been trying to reference .slick to do something (which will return undefined).  Thanks!

**Comment by oliverbenns** [comment]
This caught me out too - thanks!

**Comment by adbatista** [comment]
I'm having a similar problem, this is my script;

```js
var $carousel = $("[data-carousel]");

$carousel.on('edge', function(event, slick, direction){
  console.log("edge");
});

$carousel.slick({
  slidesToShow: 4,
  slidesToScroll: 4,
  accessibility: false,
  draggable: false,
  infinite: false,
  prevArrow: $("[data-carousel-prev]"),
  nextArrow: $("[data-carousel-next]"),
  responsive: [
    {
      breakpoint: 1370,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3
      }
    }
  ]
});
```

but I'm getting nothing, when reaching the edge

**Comment by chadhost** [comment]
@adbatista Did you figure out your issue with the edge? I'm also having this problem.

**Comment by mrjacobfisher** [comment]
+1 for "edge" event not firing.

**Comment by masi** [comment]
Ok, got it. A hint on how to use the init event in the documentation is appreciated.

**Comment by tlg-chris-stgermain** [comment]
Looking at the code, it appears that "edge" only works with swiping, and not when you use buttons.

**Comment by daslicht** [comment]
is there an event after slick is ready ?

**Comment by bux23** [comment]
Yes, an event after slick has finished initializing would be wonderful. I am having dynamic height of slides set by js and have a problem on initial load. Such event would resolve it.

**Comment by sandeep2244** [comment]
@tlg-chris-stgermain how to add event on button for edge and direction ??

**Comment by zdimaz** [comment]
Init *not work

**Comment by GGget** [comment]
the similar issue to me ,some code:
$('.slick').on('init', function (el, slick, currentSlide) {
    console.log(el)  // => Object     :)
    console.log(currentSlide)  // =>undefined   爻(
})
$('.slick').slick()
my init event work success for The first two parameters, but i can‘t get the currentSlide ,it shows "undefined"

**Comment by febdao** [comment]
@GGget 
There is no `currentSlide` argument with the `init` event, so you can't get it.
<img width="590" alt="Screen Shot 2019-12-30 at 10 57 25" src="https://user-images.githubusercontent.com/7425119/71567648-33a39700-2af3-11ea-9a21-0617347dd05b.png">

**Comment by belai87** [comment]
@me3design 
You can initialize it like this

$('.slider').slick({
infinite: true,
......
**init: InitSlider()**
});

function **initSlider**(){
console.log('INITIALIZE');
}

**Comment by thiagocanudo** [comment]
SImple:

```
if($(".NAME-YOU-SLICK.slick-initialized").length == 1){
console.log('INITIALIZE');
}
```
