### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by theolampert** [kenwheeler/slick#1010]
Do you need to use the browserify shim with this?. Requiring it will work with data-attributes but return undefined if you try to access it directly.

**Comment by im4aLL** [comment]
I also had the same problem with using slick with browserify but none of solutions worked for me. Then i take a took into slick.js and changed - 

Before: 
```javascript
(function(factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else if (typeof exports !== 'undefined') {
        module.exports = factory(require('jquery'));
    } else {
        factory(jQuery);
    }

}(function($) {
```

After:
```javascript
;(function ( $, window, document, undefined ) {
```

add the last line - 

Before:
```javascript
}));
```

After:
```javascript
})( jQuery, window, document );
```
