### ISSUE TITLE
Custom arrows removed in responsive context

### ISSUE THREAD

**Issue by nlemoine** [kenwheeler/slick#1011]
Thanks for this wonderful slider, it's a great work. 

However, I noticed a bug when using custom arrows. If you pass a jQuery selector to the `prevArrow` and `nextArrow` settings (which seems allowed according the docs), the arrows will be removed when resizing your window. See the fiddle below:
http://jsfiddle.net/hellonico/oh0ax8tg/1/

After a quick look at the source code, it seems that this issue happens because the script test arrows elements against `object` type:
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2068

I solved the problem using jQuery objects instead of selectors. 
http://jsfiddle.net/hellonico/j15dqq34/1/

But it would be nice to have this issue fixed, whether by removing the selector option in the docs or making it work with a custom selector.

**Comment by Webtransformer** [comment]
I have a similar problem. In a responsive setting they aren´t renderedl.
If a removing the breakpoints then they are visible again.

**Comment by cansozeri** [comment]
Same here .. Is tehere a patch for it ??

**Comment by nlemoine** [comment]
Use objects instead of selectors, it will solve the issue for now:
```
$(".slider").slick({
  prevArrow: $('.prev'),
  nextArrow: $('.next'),
});
```

**Comment by simeydotme** [comment]
but the lines of code you reference (the `object` type check) should always pass as true because when the arrows are build it wraps them in a jQuery object...
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L426-L427

**Comment by nlemoine** [comment]
You're right, I have not checked all the code base but for some reason, it fails when using selectors. See the fiddle above.

**Comment by elpollitodiablo** [comment]
same here. got it fixed with the query-objects but I'd prefere a more clean version

**Comment by mathetos** [comment]
Thanks @nlemoine for that workaround, was bugging me forever until I finally found this ticket. Would be nice for it to handle selectors correctly, or update the docs to say objects only.

**Comment by leggomuhgreggo** [comment]
Looks like this got resolved. Closing, but if anyone is still having issues feel free to circle back with a fresh test case. Thanks!
