### ISSUE TITLE
slickGoTo does not seem to be correctly available to calling code

### ISSUE THREAD

**Issue by alexbfree** [kenwheeler/slick#1013]
Hi

I cannot seem to get anything except an "Uncaught TypeError: undefined is not a function" when I try and use the slickToGo function. Here is a JSfiddle: http://jsfiddle.net/alexbfree/6w5pakaj/

You will notice the top nav links highlight correctly when changing tab with the dots - but when you try to use the nav links, we get an undefined error in the console.

I have looked at examples so I don't think this is a usage error, but maybe it is. Or maybe it's a bug in latest code?

Please advise how to get this working. I am using jQuery 2.1.0 and slick 1.4.1

**Comment by lmcorreia** [comment]
Try this:
```javascript
$('.carousel').slick('slickGoTo', slideNo);
```
> Methods are called on slick instances through the slick method itself in version 1.4

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/releases/tag/1.4.0
:smiley:

**Comment by lmcorreia** [comment]
Well, I thought slick followed semantic versioning and so these changes should have made it a major iteration rather than a minor (1.3.15 to 2.0.0, instead of 1.3.15 to 1.4.0).

But as always it's just a matter of taking a quick look at the documentation or the release notes, no big deal. ;)
