### ISSUE TITLE
Enable swipe on custom arrows placed over carousel

### ISSUE THREAD

**Issue by badtant** [kenwheeler/slick#1014]
Hi,
I have a carousel with custom prevArrow and nextArrow.
They are placed on to of the carousel and when a user swiper and hits the button when they start the swipe the swipe in the carousel doesn't happen. I know this is correct behavior but I'm wondering if there is some way to make it swipe the carousel anyway?

Thanks

**Comment by simeydotme** [comment]
Thanks for contributing @badtant  :)

You'd have to create your own swipe event handler on the arrows respectively and apply a "next" or "prev" call to the slider when that swipe event is triggered :)

This is not an issue with the plugin, though, if you want to follow up on www.stackoverflow.com , please paste the link here and I'll see if I can help you with a working example :)

Simon.
