### ISSUE TITLE
Accessing product attributes from slide 

### ISSUE THREAD

**Issue by AmerPandzo** [kenwheeler/slick#1018]
Hi . 

I have slides that are my products , so i slide product images and on click i go to my product show method and that is OK . Now i need to access my product id based on slide which is focused , because i am doing some json and ajax calls . I dont know how to do that . 

In basic I need to get currentSlide.product.id or something :D ... i saw thread Accessing Current Slide Attributes in onAfterChange ... but "slide" method does not work any more and i dont know is that really what i need .

**Comment by lmcorreia** [comment]
The problem you describe about not being able to access methods may be related to this:
> https://github.com/kenwheeler/slick/issues/1013

**Comment by lmcorreia** [comment]
I think what you want is something like this:
http://jsfiddle.net/lcorreia/ej9udewh/

**Comment by simeydotme** [comment]
Thanks @lmcorreia ! :)
Thanks @AmerPandzo for contributing, but this is a general javascript-support question, not a problem with Slick. @lmcorreia has given you the information you need to write your own application... if you are still stuck with your app I suggest searching for help on www.stackoverflow.com

**Comment by AmerPandzo** [comment]
Yeah . Ty . I thought that it got to do something with incompatibility of Slick . Now i know i was wrong . I made it work . Thanks guys :)
