### ISSUE TITLE
autoscroll on hover over arrows

### ISSUE THREAD

**Issue by elubin** [kenwheeler/slick#1019]
instead of clicking the arrow, is there a way to autoscroll while the user hovers over the arrow?

or do i write it myself on hover over the arrow control, start a timer and tell the slider to scroll.

thanks!

**Comment by elubin** [comment]
this code gets me halfway there... i can scroll the prev arrow correctly... but the next arrow still scrolls left. how do i get it to scroll right?

                $( document ).on({
                    mouseenter: function() {
                        var $slick = $(this).parents('.my-slick');
                        $slick.slickPlay();
                    },
                    mouseleave: function() {
                        var $slick = $(this).parents('.my-slick');
                        $slick.slickPause();
                    }
                }, '.slick-next');

**Comment by simeydotme** [comment]
```js

$(function(){
    
    var $slider = $(".my-slick").slick();
    
    var scroll,
        speed = 1000;
    
    var stop = function() {
      clearInterval( scroll );
    }
    
    var rw = function() {
      stop();
      $slider.slick("slickPrev");
      scroll = setInterval( function() {
         $slider.slick("slickPrev");
      }, speed );
    };
    
    var fw = function() {
      stop();
      $slider.slick("slickNext");
      scroll = setInterval( function() {
         $slider.slick("slickNext");
      }, speed );
    }
    
    $("body").on("mouseenter", ".slick-next", fw);
    $("body").on("mouseenter", ".slick-prev", rw);
    $("body").on("mouseleave", ".slick-next, .slick-prev", stop);

}());

```

http://jsfiddle.net/jgwgkw0n/


----

Please; in future ask these kind of questions (where you need help with your own code) in www.stackoverflow.com :) __this is not a support forum__, it is for keeping track of real problems with Slick. :smile:
