### ISSUE TITLE
Add alternate pager (thumbs) / synchronized carousels

### ISSUE THREAD

**Issue by jasonday** [kenwheeler/slick#102]
Feature request. 

Alternate pager - thumbnails, etc. 
http://jquery.malsup.com/cycle2/demo/pager.php

Would allow for the ability to create synchronized carousels (using thumbs for pager):http://jquery.malsup.com/cycle2/demo/caro-pager.php

I'll take a look at this as well.

**Comment by marteb** [comment]
Hey wjthomas9, maybe you can share your code how you got the custom pager (first screenshot) working?

**Comment by toredahl** [comment]
No help there apparently, but here it is working with numbers: 

http://bouvet-toredahl.herokuapp.com/bouvet/diakonhjemmet/master.html?page=karusell

**Comment by jennybeaumont** [comment]
hey toredahl, any chance you could share how you accomplished that paging system with numbers? :)

**Comment by goslingcools** [comment]
Can we also choose where the ul.slick-dots is located in our html? 
For example: outside the div.slick-slider

**Comment by kenwheeler** [comment]
@jennybeaumont you do that with the `customPaging` option, @goslingcools you do that with the `appendDots` option

**Comment by goslingcools** [comment]
Aha I see..! Your documentation on https://github.com/kenwheeler/slick/ is more complete than on  http://kenwheeler.github.io/slick/ :-)

**Comment by vitamine** [comment]
Hi! Awesome slider, the best! 
One feature request: 
any element on the page could be an alternate pager like this http://bxslider.com/examples/thumbnail-pager-1
It would be very helpfull, this feature alows acting slider like tabs. And it's not the same as 'thumbs' feature. 
Thank you!

**Comment by adrien-be** [comment]
@jasonday wrote in the first post:
> Would allow for the ability to create synchronized carousels (using thumbs for pager): http://jquery.malsup.com/cycle2/demo/caro-pager.php

@kenwheeler Did you also add this feature? thx

**Comment by nickfmc** [comment]
I've used this method to setup a custom pager, http://codepen.io/anon/pen/NPeLrd as well with some jquery to add an active class the navigation it works like a charm.  The one restriction is if you click really fast, before the slides transition has finished it doesnt update the slide in time however I just set a very fast fade speed and it fixes the issue. I suppose you could apply a CSS transition in there too on slick-current to simulate a slower fade if you wanted.

**Comment by stratboy** [comment]
The following author's example is wrong:

```
customPaging: function(slick,index) {
    return slick.$slides.eq(i).find('img').prop('outerHTML');
}
```

should be:

```
customPaging: function(slick,index) {
    return slick.$slides.eq(index).find('img').prop('outerHTML');
}
```
