### ISSUE TITLE
Stop autoplay

### ISSUE THREAD

**Issue by DavidZidar** [kenwheeler/slick#1021]
I'd like to stop autoplay on swipe with mouse. It is currently not possible if `pauseOnHover` is enabled since any pause issued while hovering will be undone once hovering stops.

Setting `pauseOnHover` to `false` with `slickSetOption` is also ineffectual since the hover events are only bound on startup.

I propose to separate a temporary pause and a complete stop of autoplay into separate values or check the state of `pauseOnHover` in `mouseenter.slick` and `mouseleave.slick` before pausing/unpausing.

**Comment by fredkingham** [comment]
Hit this today, if you pause the carousel with slick pause and then mouse out, the pause is undone by the mouse out.

**Comment by simeydotme** [comment]
@DavidZidar there were some bugs with autoplay , but they are fixed in `master` now, hang tight for a release and you'll have more luck with your task :)
