### ISSUE TITLE
Going from last slide, to first slide there is a delay.

### ISSUE THREAD

**Issue by jjharrity** [kenwheeler/slick#1022]
When I slide from the last slide to the first slide, the first slide take a second to load in it seems like, then appears after a short delay.  So instead of sliding in like the other transitions, it pops in after a delay.  

I wonder if its due to the CSS animations being used to transition slides

Any thoughts?

**Comment by tomaszpoliszuk** [comment]
Yes - it's hard to tell without any example... ;)

**Comment by tomaszpoliszuk** [comment]
Probably you should check if it is related to cloned element.
First & last elements are cloned - if .slick-slide element has some css transition it might be it...

**Comment by mcashley** [comment]
Closing this as it is a bit old and there is no JSFiddle to test case.
Please see the contribution rules: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
