### ISSUE TITLE
Simetimes no animation when triggering slickNext or slickPrev on iPad

### ISSUE THREAD

**Issue by badtant** [kenwheeler/slick#1026]
I'm calling slickNext and slickPrev through some outside custom buttons. My slideSpeed is set to 300.
Most of the times the transition as made instant and not with my speed set. It's very random.

Though when swiping and clicking on the next and prev buttons I always get the nice transition. Any ideas on whats wrong here?

Slick version: 1.4.0
iPad IOS: 7.1.2

**Comment by simeydotme** [comment]
hi @badtant  :)
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

Please provide a JSFiddle.

**Comment by mcashley** [comment]
Fiddle requested and not received. Closing this issue.
