### ISSUE TITLE
Swiping with vertical Mode does not work

### ISSUE THREAD

**Issue by apetrakow** [kenwheeler/slick#1030]
I've got this bug on an current dev-site. While swiping on horizontal mode works as planed, the vertical mode seems to have some bugs:

http://jsfiddle.net/schnubb/yukyt9so/1/

It looks like the draggable Div does not move at all.

**Comment by kenwheeler** [comment]
Please describe what bug you are seeing?

**Comment by apetrakow** [comment]
The first (upper) slideshow has vertical: false settings and ist swipable.
When I swipe left or right it's ok.

The second slideshow has vertical: true an isn't swipable.
When I swipe up / down nothing happens.

Here's an updated fiddle: http://jsfiddle.net/schnubb/yukyt9so/2/

**Comment by kenwheeler** [comment]
Slick doesn't swipe up and down

**Comment by apetrakow** [comment]
that's too bad, ok, thanks!

**Comment by kenwheeler** [comment]
It's not terribly difficult to add by swapping some variables around

**Comment by gborbonus** [comment]
Hi,
Can this be done soon? 
I'm working on a project that I use slick slider for and I need it to vertically swipe when set to vertical mode, sort of makes sense, doesn't it?

Btw, great product, I'm using it in about 3 other places.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/1001
