### ISSUE TITLE
unslick method doesn't seem to clear autoplay interval entirely

### ISSUE THREAD

**Issue by alpracka** [kenwheeler/slick#1031]
Hello,

I had problem when using slick and turbolinks (https://github.com/rails/turbolinks) where 2 synced sliders were partially unsynced after the page reloading via turbolinks. I haven't been able to reproduce it 100% yet, but I've created this fiddle http://jsfiddle.net/h2fewevv/5/ where the button "Unslick and slick again" does the similar things what turbolinks do when the page is reloading and I found a strange behaviour which might be causing the problem with turbolinks.

**Scenario:**
1) Visit http://jsfiddle.net/h2fewevv/5/
2) Everything works fine
3) Click the button "Unslick and slick again" exactly when slider transitions are in progress
4) Sliders are now partially unsynced in the way .slider_2 listen to some autoplay interval and change its slides regardless to .slider - e.g. hover mouse to .slider and you will see .slider_2 is changing its slides independently.

**[Demo screen record] (http://n1dev.com/system/data/slick_demo.mov)**

**Comment by alpracka** [comment]
It would be also nice to have some 'global' slick destroyer. E.g.:

1) Page was loaded and `$('.slider').slick({autoplay: true});` was fired
2) Page change it's DOM via AJAX and .slider div was removed
3) Now you get errors during the time, because slick instance can't find $('.slider') and you can't remove unslick also. Your only chance is to unslick before DOM is changed I guess.

http://jsfiddle.net/alpracka/7aL0hp6a/1/

**Comment by Lisoph** [comment]
Hey alpracka, I'm having the same issue. Did you find a workaround?

**Comment by simeydotme** [comment]
Great Fiddle, @alpracka ... sorry this was not actioned earlier.
I will see about fixing this.

**Comment by simeydotme** [comment]
Check out the commit for the fix, @alpracka ... its live on master, needs a release. Please hang tight.
