### ISSUE TITLE
WebKit not lazy loading cached images on first slide

### ISSUE THREAD

**Issue by croxton** [kenwheeler/slick#1032]
The opacity of the images remains at 0 because the image.load() is never called. Why is explained here
https://code.google.com/p/chromium/issues/detail?id=7731#c12

This fixes it for me

        function loadImages(imagesScope) {
            $('img[data-lazy]', imagesScope).each(function() {

                var image = $(this),
                    imageSource = image.attr('data-lazy'),
                    imageToLoad = new Image();

                imageToLoad.onload = function() { 
                    image.animate({ opacity: 1 }, 200); 
                }
                imageToLoad.src = imageSource;

                image.css({ opacity: 0 })
                  .attr('src', imageSource)
                  .removeAttr('data-lazy')
                  .removeClass('slick-loading');
            });
        }

**Comment by cansozeri** [comment]
This is solved my problem, wyh didn't you merge this code ???
