### ISSUE TITLE
Changing Scroll Direction on the Fly

### ISSUE THREAD

**Issue by joelcdoyle** [kenwheeler/slick#1033]
I'm having trouble with 'slickSetOption' as it relates to 'rtl' option.

I've set my carousel up so that it starts autoplay when the mouse is hovering over any slide other than the center slide. It works great, but I'm unable to change direction based on whether the mouse is on the right side or the left side of the center slide.

When I hover over the left portion, instead of changing direction, all the slides scroll over the the right and disappear permanently.

```
$(function(){
    var $slider = $('.slides-container').slick({
      centerMode: true,
      slidesToShow: 5,
      variableWidth: true,
      arrows: false,
      autoplaySpeed: 100
    });
    $('.slides-container .slick-slide img').hover(
      //on mouse enter
      function(event){
        var centerIndex = $('.slick-center').data('slick-index');
        var hoverIndex = $(event.target).parent().data('slick-index');
        if(hoverIndex > centerIndex){
          $slider.slick('slickSetOption', 'rtl', true ,false);
          $slider.slick('slickPlay');
        }
        else if(hoverIndex < centerIndex){
          $slider.slick('slickSetOption', 'rtl', false ,false);
          $slider.slick('slickPlay');
        }
        else {
        }
      },
      //on mouse leave
      function(){
        $slider.slick('slickPause');
      }
    );
  });
```

I also notice that if I have the rtl option set to true at the beginning, I have the same issue. The slides all disappear to the right immediately:
```
var $slider = $('.slides-container').slick({
      centerMode: true,
      slidesToShow: 5,
      variableWidth: true,
      arrows: false,
      autoplaySpeed: 100,
      rtl: true
    });
```

**Comment by pipeTM** [comment]
try setting **slidesToScroll** to a positive or negative value

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m gonna close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
