### ISSUE TITLE
left aligning images

### ISSUE THREAD

**Issue by mla** [kenwheeler/slick#1035]
Hi. I'm using slick 1.4.1 with Foundation 5 on Chrome. I'm using the default slick-theme.css.

I have a slider with only two images. Settings are:

```javascript
lazyLoad: 'ondemand',
slidesToShow: 3,
slidesToScroll: 3,
dots: true
```

At certain page widths, the slider elements expand. For example, see this:

![thumbs](https://cloud.githubusercontent.com/assets/44186/6201673/15995e46-b46c-11e4-87d1-360b4f7e7206.png)

I'd like those two images to be left justified. The images themselves are 100x100 px.

Markup is very simple:

```html
<div class="thumb-slider">
  <div class="slider-thumb"><img src="..."></div>
  ...
</div>
```

What's the proper way to accomplish that?

Thanks.

**Comment by JodiWarren** [comment]
@mla Did you find a solution to this?
