### ISSUE TITLE
Horizontal scrolling oh hover - bug?

### ISSUE THREAD

**Issue by dghez** [kenwheeler/slick#1037]
Hi everyone!
I'm using this plugin and it's real good but I can't understand why on hover appear the horizontal scrollbar and my entire page move left when the slide "sliding".
Was one of my problem or it's common? Maybe it's a bug.

I solved that adding `overflow-x: hidden` to the entire body.
Any idea?
Thanks!

![schermata 2015-02-16 alle 10 03](https://cloud.githubusercontent.com/assets/6367879/6209252/da4a1d9a-b5c3-11e4-9512-76c1734830e1.png)

**Comment by tomaszpoliszuk** [comment]
Yup, probably you did something wrong.

**Comment by tomaszpoliszuk** [comment]
Ok, now of real:
probably this (or similar) is the issue
<pre>
.slick-slider:hover .slick-prev{right: -25px;}
</pre>
if not - give us example ;)

**Comment by simeydotme** [comment]
hi @dghez  - this is a support issue for your own code/website, please seek support from a suitable source. In the Github issue tracker we are here to help solve issues with the plugin; not your website :grinning: 

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by julianmatz** [comment]
I'm having the same, or similar, problem. The same behavior also appears on one of the demos on your site. If you hover the mouse over the images on the "Lazy Loading" demo, a horizontal scrollbar appears.

**Comment by julianmatz** [comment]
I think the issue with images and the horizontal scrollbar that appears when hovering over them has to do with Pinterest buttons. If this is the issue, you can add the "data-pin-nopin" attribute to your thumbnails.

**Comment by tomhicz** [comment]
Well spotted Julian. Spent ages trying to work out what was causing that, but disabling the pinterest extension on chrome seems to have fixed it. Hopefully the data attribute you mention will be a better fix.

**Comment by marianbida** [comment]
Yes, me too, it seems that Pinterest is the bad boy.

**Comment by LucianoHernandez** [comment]
Buffer extension does the same.
I solved the issue adding pointer-events:none to the images.
It's difficult to add exeptions to all possible extensions out there.
