### ISSUE TITLE
Website missing slick-theme.css

### ISSUE THREAD

**Issue by RadGH** [kenwheeler/slick#1040]
The website for slick, under "Get It Now", is missing a link to slick-theme.css. http://kenwheeler.github.io/slick/#go-get-it

(For the CDN section, anyway, not the github source)

This was quite confusing as a previous version of slick I do not believe needed the theme file. The theme is probably optional, but without it the demos won't work correctly. I think it should be included in the "Get it here" section. Maybe with an HTML comment explaining that it is optional?

**Comment by kianlavi** [comment]
+1 this @kenwheeler. I got confused as well, and was working without the theme for a while... now I have to redo all my styling :(

**Comment by TheJaredWilcurt** [comment]
Clearly there are other things missing as well, I supplied all required items (including the theme) and the carousel still doesn't look right in jsfiddle or codepen:

* http://codepen.io/anon/pen/vNRYwW
