### ISSUE TITLE
Bizarre behavior after stopping autoplay and removing hover, when pauseOnHover is true

### ISSUE THREAD

**Issue by OAGr** [kenwheeler/slick#1041]
It seems like when autoplay is set to true, and later is set to false, when a slide is then hovered over and away from, autoplay turns on again.  I originally did this with ```infinite: false```, which led to some particularly strange behavior as the slider got into a loop going back and forth between the 2nd and 3rd slides continuously.

I think this may be particularly important because ```pauseOnHover``` is set to true as the default.

### To replicate
https://jsfiddle.net/ozziegooen/6o9c7qok/3/
**Move your cursor on, then off of the slide**

It should start 'autoplaying', even though
A. This shouldn't happen
B.  Even if it starts, the afterChange handler should pause it again

Setting pauseOnHover to false in the example above fixes the issue.

**Comment by ergec** [comment]
My quick fix, check it out
http://jsfiddle.net/ergec/5z9v6Lfr/

    Slick.prototype.autoPlay = function() {
        var _ = this;
        if (_.options.autoplay) {
            if (_.autoPlayTimer) {
                clearInterval(_.autoPlayTimer);
            }  
            if (_.slideCount > _.options.slidesToShow && _.paused !== true) {
                _.autoPlayTimer = setInterval(_.autoPlayIterator,
                    _.options.autoplaySpeed);
            }
        }
    };

**Comment by ergec** [comment]
My quick fix http://jsfiddle.net/ergec/5z9v6Lfr/

    Slick.prototype.autoPlay = function() {

        var _ = this;
        if (_.options.autoplay) {
            if (_.autoPlayTimer) {
                clearInterval(_.autoPlayTimer);
            }
    
            if (_.slideCount > _.options.slidesToShow && _.paused !== true) {
                _.autoPlayTimer = setInterval(_.autoPlayIterator,
                    _.options.autoplaySpeed);
            }
        }
    };

**Comment by simeydotme** [comment]
this shouldnt happen any more on teh `master` branch, revamped the autoplay feature. wait for next release :)
