### ISSUE TITLE
Absolute position elements within a slide relative to entire slider

### ISSUE THREAD

**Issue by CFXd** [kenwheeler/slick#1046]
Here is my working demo: https://jsfiddle.net/silb3r/afaztv2t/7/embedded/result/

Below each slide and to the right is a small image contained within `div.gallery-pin`. It's correctly aligned to the right, but I want it aligned to the bottom of the entire `.gallery-main` (bordered in red).

I realize that each `.slick-slide` gets `position: relative` and I've tried overriding it with `position: static !important`, unfortunately that breaks Slick (and the `div.gallery-pin` ends up being positioned relative to `.slick-track` and therefore ends up way offscreen to the right, although correctly on the bottom where I want it).

Any help would be much appreciated!

**Comment by CFXd** [comment]
For now I have solved this with:

```javascript
$(document).on('init', '.gallery-main', function(slick) {
  $(this).find('.slick-slide').css('height', $(this).height());
});
```

...but I would still love a CSS solution if it's possible!

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
