### ISSUE TITLE
Provide callback option for lazyload'ed images

### ISSUE THREAD

**Issue by david-nguyen** [kenwheeler/slick#1047]
Not sure if this would be useful enough to include in your script but I think it would be helpful to include a callback function option for lazy loaded images to do some extra legwork with a passed element. If it would be helpful I can write the PR.

Line 1154
Line 1284

**Comment by michaltowilk** [comment]
Agreed... I need this callback right now

**Comment by designbureau** [comment]
+1

**Comment by stefanoortisi** [comment]
+1

**Comment by SiamKreative** [comment]
+1

**Comment by thulakawasaki** [comment]
+1

**Comment by simeydotme** [comment]
there's an event fired in `master` branch on load.
