### ISSUE TITLE
[Firefox] difference in margin length between slider and prev/next buttons

### ISSUE THREAD

**Issue by alipman88** [kenwheeler/slick#1048]
I'm experiencing a very minor issue where the margin between the slider and the prev/next buttons is slightly off:

![screen shot 2015-02-16 at 11 49 07 pm](https://cloud.githubusercontent.com/assets/3922511/6223417/c9a7eac6-b636-11e4-9642-9beda977b861.png)

(I hope a jsFiddle isn't necessary in this case, 'cause I'm able to observe this when visiting the project's home page, at http://kenwheeler.github.io/slick/. I've tested current versions of Firefox running on Mac OS, Windows & Ubuntu.)

I fixed this in my project by removing the `width: 20px;` rule from `.slick-prev, .slick-next` in slick-theme.css. (Alternatively, the width could be set to 26px.)

But, I'm not sure what the underlying cause of the discrepancy is, or if removing/changing the width is the correct solution.

**Comment by leggomuhgreggo** [comment]
Apologies for the lack of response. Looks like this has been resolved. Thanks!
