### ISSUE TITLE
Update Docs for v 1.4

### ISSUE THREAD

**Issue by sbussard** [kenwheeler/slick#1050]
The website should be updated to include the following changes: 

https://github.com/kenwheeler/slick/releases/tag/1.4.0

**Comment by kenwheeler** [comment]
The website is updated

**Comment by sbussard** [comment]
You're awesome! Thanks! :+1:  :)

**Comment by sbussard** [comment]
Sorry about that. Long story. But thanks for keeping it up to date.

**Comment by sbussard** [comment]
There's still a few details to update. The arguments of beforeUpdate have changed

![screen shot 2015-02-19 at 9 48 54 am](https://cloud.githubusercontent.com/assets/345018/6270019/9f1d59a2-b81c-11e4-89cb-4d108144bf0e.png)

**Comment by klihelp** [comment]
Thank you for the update:) #997
