### ISSUE TITLE
Multiple slides, single transition?

### ISSUE THREAD

**Issue by LukeAskew** [kenwheeler/slick#1052]
Is there currently a way to make a carousel with multiple slides to transition to a slide as if it is adjacent?

For instance, on a carousel with 5 slides, if I'm on slide 1 and click on the dot for slide 5, the carousel slides through all the slides in between - 4 slides fly by.

I'd like the ability for a carousel to slide from slide 1 to 5 in a single animation, as if 5 was adjacent (no slides in between).

Happy to do a PR if the functionality doesn't already exist.

**Comment by LukeAskew** [comment]
Not super elegant, but I put this together in a pinch: https://github.com/LukeAskew/slick/compare/kenwheeler:master...master

**Comment by simeydotme** [comment]
You don't need a carousel to achieve this :)
