### ISSUE TITLE
Can't get the src of the current slide

### ISSUE THREAD

**Issue by JcDenton86** [kenwheeler/slick#1054]
Hi,
I am using slick in a list of images and in some point I want to get the src of the current slide. From the functions I've seen I can only get the index of the current slide (0,1,2 ..). Is there a way to do that from the library? or it is not supported yet? Otherwise I have to do it using other ways.

Thank you in advance.

**Comment by kenwheeler** [comment]
you can do something on the base slick object like

$('myelement')[0].slick.$slides[currentSlide]
