### ISSUE TITLE
Can't navigate clicking on items

### ISSUE THREAD

**Issue by bruno-barros** [kenwheeler/slick#1055]
I'm using the `focusOnSelect: true` as well as `asNavFor`, but I can't click on images to center the carroussel.
I already did it on version 1.3.15, but can't do the same with 1.4.1.
Any idea?

**Comment by simeydotme** [comment]
JS Fiddle, please mate, we can help if we see the problem :)

**Comment by oskarrough** [comment]
Here you go: http://jsfiddle.net/phLc4ox4/1/ — you can't click the slides in the bottom slider.

**Comment by kenwheeler** [comment]
@oskarrough unfortunately you need to add a child element to those divs, it wont work on text content alone. try wrapping your text in p or span

**Comment by oskarrough** [comment]
@kenwheeler that worked, thank you! Would be great to either fix this or document it somehow. Took me hours of debugging :1234:

**Comment by kenwheeler** [comment]
@oskarrough I'll look into it, so sorry about that!

**Comment by kenwheeler** [comment]
Fixed on master
