### ISSUE TITLE
Init event not being triggered.

### ISSUE THREAD

**Issue by tutuca** [kenwheeler/slick#1057]
Required fiddle: http://jsfiddle.net/q3yc3gap/ reproduced here for clarity:

    /**
       init event not being triggered
    **/
    
    function algo(message) {alert(message)}
    algo('works')
    
    $(".slider").on('init', function(){algo("doesn't")});
    $(".slider").slick();
    
    /* Alternative cases */
    
    // $(".slider").slick().on('init', function(){algo("doesn't")});
    // slide = $(".slider").slick();
    // slide.on('init', function(){algo("doesn't")});*/

**Comment by JohnRamboTSQ** [comment]
The "reInit" event also

**Comment by gausarts** [comment]
The fiddle complains about http over https, and the scripts are blocked:
Blocked loading mixed active content "http://cdn.jsdelivr.net/jquery.slick/latest/slick.min.js"

Also you seem to have wrong syntax in the example.

This should work, without https and proper syntax:
http://jsfiddle.net/1yvr86yp/

**Comment by tutuca** [comment]
@gausarts you are right. Shared the wrong fiddle.
The code pasted in the report is right though.
Your fiddle doesn't work too.

**Comment by gausarts** [comment]
Hmm, perhaps you are seeing it while logged-in?
Try logging out of the fiddle site, or see it in another browser as anonymous. 
It is a matter of slick script is being blocked as the  above error says, you are using HTTP inside HTTPS.

NOT WORK:
https://jsfiddle.net/1yvr86yp/

WORKS:
http://jsfiddle.net/1yvr86yp/

Or better you change the loaded slick.min.js to use HTTPS, and vice versa.

**Comment by tutuca** [comment]
Maybe I wasn't clear. Slick works, as in: the slide loads correctly. The callback for the init event just isn't triggered.

**Comment by tutuca** [comment]
No caca.

**Comment by gausarts** [comment]
Strange, I see "caca". Perhaps your browser blocks the alert message, then?

**Comment by gausarts** [comment]
![caca](https://cloud.githubusercontent.com/assets/431948/6310853/c9b86e50-b98d-11e4-93ae-d97353d8a89a.jpg)

**Comment by tutuca** [comment]
Weird then... Nothing blocking the alert since this shows *coca* http://jsfiddle.net/0dnn51tn/ but not *caca*... weeird.

**Comment by gausarts** [comment]
I see both coca and caca respectively.
Perhaps you'd better use console.log(), or do other useful function?

**Comment by tutuca** [comment]
Well... this is the demo. I have tried actual code on the project I'm using slick in.

I'll try another browser in a moment and see what happens. Thanks for the time anyway.

**Comment by tonioMtl** [comment]
Hi !
I've the same problem. With jQuery v1.11.1
Can't fire/listen init event.

**Comment by simeydotme** [comment]
@tutuca - Your JSFiddle works fine ( see picture below )
@tonioMtl - JSFiddle please?
@gausarts JSFiddle is working fine ( http://jsfiddle.net/1yvr86yp/ )

I'm going to close this unless someone can provide a JSFiddle and clear evidence of the init event not firing... even in one specific browser or scenario... currently I see none :confused: 

![screen shot 2015-03-02 at 11 45 12 am](https://cloud.githubusercontent.com/assets/2817396/6435122/a8fd9e92-c0d1-11e4-91f5-4d09cade80e8.png)

**Comment by nikolowry** [comment]
Please add to the docs that the init listener has to be defined BEFORE the slick object.

**Comment by yves-s** [comment]
Thanks @nikolowry and +1

**Comment by danodm** [comment]
@nikolowry thanks! this was my issue. Syntax was spot on, but the order of my JS was incorrect.

@simeydotme it would be great to get this added to the documentation to help others.

**Comment by foaly-nr1** [comment]
Thanks @nikolowry and +1

**Comment by ghettosoak** [comment]
PLEASE put this in the documentation. This caused quite the headache for me, too.

&& massive thanks to @nikolowry. :)

**Comment by neilmonroe** [comment]
Also giving my +1 to @nikolowry for his heads-up answer.

Perhaps an alternate way to handle lessening the confusion of when this and the 'reInit' handlers need to be defined would be to pass the handler functions into the settings object (maybe in an 'events' container object).

**Comment by Mango-Design** [comment]
I've found a solution to this problem, just call the on('init') function before the slick function

**Comment by lukeheath** [comment]
This got me too. If the docs showed the event listeners in the context of the slick function it would remove a lot of confusion.

**Comment by Luneya** [comment]
Thank you @nikolowry ! 
I was bumping my head for ages to get something to work on init, never thinking it should be put before the object itself. Thanks again!

**Comment by brianpittvps** [comment]
3 and a half friggin years, still no mention of proper order of operations in the documentation.  Does no one care about clarity and detail anymore?  I started on Bootstrap's carousel and that is so full of errors it's not even usable.  This one's way better, but how about listening to feedback and making improvements.

**Comment by jawinn** [comment]
It looks like the docs are updated on the repo's README to clarify this issue, but not on https://github.com/kenwheeler/slick

#3289
