### ISSUE TITLE
Cannot use securely in MediaWiki

### ISSUE THREAD

**Issue by dantman** [kenwheeler/slick#1058]
I was trying to integrate slick into MediaWiki to use sliders on a wiki. However I discovered that I cannot do it securely.

A number of data-slick params accept raw html and slick includes this in its code:
```js
$(function(){
  $('[data-slick]').slick();
});
```
MediaWiki allows pages to output arbitrary data-* attributes into pages (presumed safe, and up till now, fine).

However together this means that simply including Slick in MediaWiki would allow someone to output a div with data-slick and introduce an XSS vector.

**Comment by kenwheeler** [comment]
I'm not sure how I would begin to resolve this issue without seeing it in use or having a code sample.

**Comment by dantman** [comment]
I'm not sure how I can make it any clearer.

MediaWiki lets normal users write `<div data-slick="{ ... }">...</div>`.

Slick options such as `prevArrow` accept raw HTML and accepts options from `data-slick`.

Slick automatically runs on anything that has a `data-slick` attribute.

----

I can write JS that whitelists slick options and runs slick with just the known safe ones (and drops any data-slick argument).

But that won't work if simply including slick.js means any `[data-slick]` in user content will be handled by slick automatically before I can intervene.

**Comment by kenwheeler** [comment]
So if I were to handle this in core, did you have a recommended solution? Strip script includes if found in a value?

**Comment by kenwheeler** [comment]
Further, jQuery should be stripping out script tags. So can you actually hack an instance of slick, so I can see it happening, and then we can talk about approaches to fixing it?

**Comment by dantman** [comment]
The only acceptable fix would be to not automatically `$(function(){ $('[data-slick]').slick(); });` so I could do that myself after whitelisting all the safe parameters.

Anything else would be playing whack a mole with the [hundreds of known tricks](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet ) for evading XSS blacklists. Only whitelisting works.

I'm not sure whether you want to do this as a new major release or as an alternate build that excludes the implicit handling.

----

Also there are two things you need to keep in mind about XSS.
1. jQuery does **not** strip out script tags. It strips them out and then executes them. (jQuery isn't doing security, all it is doing is making sure that script tags aren't accidentally re-executed when the html is messed with)
2. You do not even need a script tag to do XSS. As long as you can find a hole that'll let you stick an on* attribute into something you can find a way to inject an XSS attack. For example you could insert an `onmouseover` that'll execute something malicious as soon as the user tries to use it. And as a bonus it would be trivial to make this worse by including a `style=""` attribute that makes the element cover the entire viewport (so the moment your mouse enters the website to do anything, the XSS attack runs.

----

Usually I like to avoid publishing client staging sites, but here's a test page with a working XSS demo where I've included slick. See the XSS alert on page view (using a `<script>` injected through nextArrow) and also another XSS alert on mouseover of one of the arrows (injected through the `onmouseover`):
http://tobaccotactics.jade.redwerks.org/wiki/SecurityTest

**Comment by kenwheeler** [comment]
Fair enough. You can pull that link down. Look for the auto slicking to be removed in 1.4.2

**Comment by dantman** [comment]
Technically this would be a breaking change so by semver it shouldn't be a point release (unless you make it an alternate file to include)

**Comment by kenwheeler** [comment]
Fixed on master
