### ISSUE TITLE
Enable dragging out of the slider container

### ISSUE THREAD

**Issue by gbggit** [kenwheeler/slick#1065]
Hi,
I really like slick slider, but it has one anoying thing that other drag support sliders don't have - if I drag out/leave out of the slider container it will call the swipe end action.

What I want is to continue dragging until I relise the mouse button. Take this slider for example - http://www.owlcarousel.owlgraphic.com/.

Any help to implement the above would be greatly appreciated :)

p.s. sorry for my bad english

**Comment by desandro** [comment]
You might want to try [Flickity](http://flickity.metafizzy.co). Flickity completely supports touch events, so you can touch down, then drag outside the carousel and it works fine.

Possibly related to #1082

**Comment by gbggit** [comment]
Nevermind... I already modified owlCarousel for my project's purposes.

Flickity is looking good, but it's not free :(

**Comment by gbggit** [comment]
Nevermind... I already modified owlCarousel for my project's purposes.

Flickity is looking good, but it's not free :(

Closing, because of similar ticket here - #1082

**Comment by saurabh-pathak94** [comment]
Hey! How did you fix this issue?!

**Comment by bjorn-ali-goransson** [comment]
@kenwheeler is this by design?

**Comment by bjorn-ali-goransson** [comment]
It seems it is, judging by @kenwheeler's post [here](https://news.ycombinator.com/item?id=7508541), but that he changed it? ... It must be reverted these days.

**Comment by kenwheeler** [comment]
@bjorn-ali-goransson dragging outside will end the swipe action. If you have traversed enough distance inside the slider, the slide will change. Can you show me an example of expected behavior?

**Comment by bjorn-ali-goransson** [comment]
In desktop, this does not improve the user experience, IMO, and should at least be opt-out.

Although @desandro's something-less plug has the desired effect on its front page, the difference will hardly be noticeable on full-width sliders.

My example of this is http://om.clasohlson.com/en/ . I actually didn't notice this behavior (the cancelling) before I made a non-full-width slider.

(But note that in the full-width slick slider, the dragging is cancelled upon hovering over the slick-arrows!)

On the slick demo page where the sliders are not full-width, scrolling through the images one might keep the mouse button down and just keep moving the mouse left to scroll through a variable number of slides at ones leisure. But the self-paced scrolling is abruptly cancelled for the user, I'd say surprinsingly.

Not everyone flicks...!
