### ISSUE TITLE
how to get 'div-tag'

### ISSUE THREAD

**Issue by sau-152mm** [kenwheeler/slick#1066]
How to get 'div-tag'  that has a class - slick-active?

**Comment by simeydotme** [comment]
This really feels like a troll.....

@sau-152mm ... please try: https://www.codeschool.com/courses/try-jquery :bow: Good luck and happy coding. :smile: 

Simon.

**Comment by sau-152mm** [comment]
you do not understand. object slick returns many methods and properties but I do not see how to get the target div with the class -slick-active. for example slickCurrentSlide -method returns the index and I need the object div I understand that I can make it through jquery but would like to get it from the inside. thank you for codeshool.

**Comment by simeydotme** [comment]
ah right, sorry about that :smile: 
here, check out: https://github.com/kenwheeler/slick/issues/1067 - I think it has what you're looking for :bow:

**Comment by sau-152mm** [comment]
yes, thank you
