### ISSUE TITLE
currentSlide - can it return object?

### ISSUE THREAD

**Issue by mor-b** [kenwheeler/slick#1067]
it only returns index.
is there an easyier way to get the slide obj after changed?

**Comment by simeydotme** [comment]
```js
$(".slider").slick("getSlick").$slides.eq( index );
```
or
```js
$("[data-slick-index="+ index +"]");
```

**Comment by mor-b** [comment]
both of the options dosent work.  i use it inside an afterChange function:
```
    $('.your-class').on('afterChange', function(event, slick, currentSlide){
      console.log( $(".slider").slick("getSlick").$slides.eq( currentSlide) ); //undifined got no index.
      console.log($slides); //undifined
      console.log($(".slick-slide[data-slick-index="+ currentSlide +"]"));  //not the current slide
    });

```

**Comment by simeydotme** [comment]
really, @mor-b -- I think you should do some basic Javascript and jQuery training before you go any further :smiley: You're missing some fundamental knowledge which would allow you to solve this issue. - stackoverflow.com is your best bet to resolve your problem. 

Regards, Simon. :bow:

**Comment by sau-152mm** [comment]
maybe it will help you:
    $('.your-class').on('afterChange', function(event, slick, currentSlide){
      console.log( $(".your-class").slick("getSlick").$slides ); 
    });
see console.
