### ISSUE TITLE
Continuous sliding ?

### ISSUE THREAD

**Issue by ierpe** [kenwheeler/slick#1068]
Hi, I was wondering if there is a way to achieve continuous sliding with Slick?

Something like that : http://coolcarousels.frebsite.nl/c/23/ 

If there is a way, I could not find it in the documentation sorry!

**Comment by simeydotme** [comment]
hey, I think you _might_ be able to achieve something similar by setting the `cssEase` to `linear` and the `speed` to the same value as the `autoplaySpeed` ... if this doesn't make sense then create a JSFiddle and I'll try to edit it for you :smile: 

Simon

**Comment by ierpe** [comment]
That does makes sense, I will try and let you know how it went!

Thanks

**Comment by klihelp** [comment]
The [continuous scrolling example above](http://coolcarousels.frebsite.nl/c/23/) built with [carouFredSel version <= 6.2.1]
(https://github.com/gilbitron/carouFredSel) uses very high CPU

**Comment by ierpe** [comment]
After some testing, it works with a linear easing, a very low auto play speed (I used 1ms), and then a high transition speed (like 10000ms).

Thanks for the insight!

**Comment by klihelp** [comment]
@ierpe can you post an example?

**Comment by ierpe** [comment]
http://jsfiddle.net/ierpe/qrL0vor8/4/

You can just change the transition speed to get the desired speed

**Comment by klihelp** [comment]
Thank you @ierpe looks very nice

**Comment by rossthedevigner** [comment]
Is there a good way to pause this while hovering? I can call, 'slickPause', but it will only stop after the transition speed is complete.

**Comment by simeydotme** [comment]
sorry, @rossthedevigner  ... I cannot think of a way that would be possible... 
only theory I have is that you calculate which slide is closest when hover (ie, has it scrolled past 50%? maybe u can check the interval for that}, then change the options so that
`waitForAnimate` is `false`
`speed` is `100`
and then use `.slick("goTo")` method to go to the closest slide ?

it's not really going to pause it where it currently is, but honestly you could create your own mini-plugin to do a continuous-scrolling div that pauses on hover with not much effort :smile: 

Si.

**Comment by rossthedevigner** [comment]
@Simeydotme It's a bit of an edge case really for much larger views > 1200px, instead of the intended usage. 

I haven't taken a solid look myself, but from what I did see I was going to try `$.stop()` on `.slick-track` or use `animation-play-state: paused`

**Comment by gina3five** [comment]
Anyone using this hack have an issue with the slider running really fast at first? It looks like the slider is doing some initial 'correction' and then it's fine.

**Comment by shahinur** [comment]
Continuous sliding? Anyone have any update on that. The feature is really needed. We can use some tricks but it’s not smooth as like e.g http://coolcarousels.frebsite.nl/c/23/

**Comment by cannanso** [comment]
Just in case someone is still looking for this solution...
Disable _autoplaySpeed_ and add a high _speed_ instead. And set _cssEase_ 'linear'. If you're using responsive settings, use this for your larger breakpoints: 

          ```
autoplaySpeed: 0,
          cssEase: 'linear',          
          speed: 20000,
```

**Comment by shamaleyte** [comment]
Any updates here for the best practice?  The given samples are not working well when there are more than 15 images and showing 6 images per round.

**Comment by architchandra** [comment]
I'm also looking for a solution for the continous infinite scroll problem. In my case, the speed of the carousel is changing everytime the speed duration hits even through cssEase is set to 'linear'.

**Comment by urbi15** [comment]
Hi, I stucked, any ideas how to fix it? 
There's problem after last slide, another loop doasn't start immediately but first slide is delayed.
https://codepen.io/urbi/pen/zbjeWz

**Comment by BB-000** [comment]
The suggested 'linear + speed' solution does a weird back and forward loop when it gets to the end of the slides 😭
https://codepen.io/bananafarma00/pen/OJLOpxG

**Comment by bootleg-icarus** [comment]
@BB-000 You wanna add centerMode:true, that'll fix that wierd jerk at the end. Not really sure why it happens though

**Comment by Narayanaash** [comment]
> @BB-000 You wanna add centerMode:true, that'll fix that weird jerk at the end. Not really sure why it happens though

Man! thanks a lot, magic!

**Comment by adam7hansen7** [comment]
> Anyone using this hack have an issue with the slider running really fast at first? It looks like the slider is doing some initial 'correction' and then it's fine.

Did you ever find a solution to this? @gina-gregory

**Comment by erralb** [comment]
Personally, I ended up switching to [Embla Carousel](https://www.embla-carousel.com/) for my needs, as I could never fix all issues with Slick, and I think the development has stopped for this plugin.
