### ISSUE TITLE
slickGoTo breaks on non-infinite slick

### ISSUE THREAD

**Issue by erinleighbeal** [kenwheeler/slick#1074]
When there is an item in the last group of slides that does not contain the number of slides specified in slidesToScroll, slick will navigate to the group before that slide, even if the slide is already in view.

Example:
Slick is initiated with slidesToScroll: 4, infinite: false.
There are 11 slides in the slider, numbered 1-11.
slickGoTo index 8, 9, or 10 will bring slides 5-8 in view instead of slides 8-11.

Here is a jsfiddle demonstrating this:
https://jsfiddle.net/6ubLpfwx/9/

**Comment by leggomuhgreggo** [comment]
Apologies for the lack of responsiveness. Looks like this got fixed as some point.

[Updated fork](https://jsfiddle.net/leggomuhgreggo/o41e3mxn/)

Thanks.
