### ISSUE TITLE
LTR support is broken

### ISSUE THREAD

**Issue by SunboX** [kenwheeler/slick#1075]
See Demo at: http://jsfiddle.net/SunboX/j1fvz4mh/

If you comment out `ltr: true` all works as expected.

**Comment by boynet** [comment]
this will work:
http://jsfiddle.net/pzvmv0nm/
rtl only work with direction:rtl

**Comment by SunboX** [comment]
Oh, nice! Thanks a lot! :+1:

**Comment by avconsbn** [comment]
Hi,
Slick 1.7.1.
LTR support is broken. **Does not work.**
Please add the opportunity (option) to choose a direction.
Thank you
