### ISSUE TITLE
After calling "refresh" click events won't fire anymore

### ISSUE THREAD

**Issue by SunboX** [kenwheeler/slick#1079]
See Demo at: http://jsfiddle.net/SunboX/j1fvz4mh/4/

**Comment by nickmelville** [comment]
The issue is actually with the destroy method.  Refresh essentially calls 'destroy' and then 'init'.

Updated example: http://jsfiddle.net/q8ejbaga/1/ (click "unslick" and the events stop working).

I believe this is duplicating #999.

**Comment by webdesignberlin** [comment]
Same Problem. looks like all event handler will be deleted.
![Image Event Listener](http://s1.postimg.org/rf7bmsbm7/unslick_before_after.png)

**Comment by itrupti** [comment]
I have declared click method as windows method and tried to call it from slide. I have updated nick's jsfiddle. This is just workaround. 

http://jsfiddle.net/itrupti/woL708Lz/3/

**Comment by simeydotme** [comment]
This appears to be working with the latest version.
