### ISSUE TITLE
Unslick doesn't work

### ISSUE THREAD

**Issue by xiaoxiachen** [kenwheeler/slick#1084]
I saw this ticket closed earlier #965. The solution was not to use 1.4 yet.

However I have tried with latest version (1.41 release after this ticket was closed) and it seems that unslick still causes undefined error in the console. http://jsfiddle.net/un7z1avr/ This uses the latest slick and jquery.

Thanks in advance for helping!

**Comment by kenwheeler** [comment]
You would need to use the new method API as shown here:

http://jsfiddle.net/s9tkg8vf/

**Comment by xiaoxiachen** [comment]
Working now. Awesome! Thank you!

**Comment by webdesignberlin** [comment]
Hi, but all jqeury or angular code doesnt work after unslick. take a look @ http://jsfiddle.net/s9tkg8vf/1/ click before unslick to slide4 and after again. some idea?
