### ISSUE TITLE
totaly custom customPaging 

### ISSUE THREAD

**Issue by erthi16** [kenwheeler/slick#1087]
hello!
I would like to know if it is possible to change de markup of the slick-dots? I would like to surround the total "ul" list with a new div container... I can use the customPaging but it only affects the buttons inside the list!
What I want is to have a markup like this:
&lt;div class="container_dots"&gt;
   &lt;ul class="slick-dots" style="display: block;"&gt;
        &lt;li class="slick-active"&gt;
            &lt;button data-role="none" type="button"&gt;1&lt;/button&gt;
        &lt;/li&gt;
        &lt;li&gt;...
        &lt;li&gt;...
    &lt;/ul&gt;
&lt;/div&gt;
Is it possible? Do I have to do something during the init event?
Thanks for everything!

**Comment by simeydotme** [comment]
```js

$(".slider").slick({ dots: true });
$(".slick-dots").wrap("<div class='rapper'></div>");

```

http://jsfiddle.net/qfyw3dz9/
