### ISSUE TITLE
slick not rendered for dynamically generated html?

### ISSUE THREAD

**Issue by cynosureabu** [kenwheeler/slick#1089]
I might miss something obvious. I use ajax to retrieve the html , and append to slick container:
$.get('/candidates',function(data){
     $('#container').append(data.html);
    $('#container').slick('unslick');
   $('#container).slick();
 
})

The slick does not reload at all. what I should do to fix this?
Thanks,

**Comment by johnyoonh** [comment]
What was the solution to this?
