### ISSUE TITLE
after slickRemove slick should remain at the same slide

### ISSUE THREAD

**Issue by boynet** [kenwheeler/slick#1090]
here exmaple of bug:
http://jsfiddle.net/kke2f10y/

after 2 sec excepted to stay on "slide2"
what happend:
slick reposition itself at  "slide3".

**Comment by simeydotme** [comment]
not sure if this is a feature or not... I'll leave it open, but here's a solution for you:
http://jsfiddle.net/kke2f10y/1/

**Comment by boynet** [comment]
thanks it workd in dekstop will test it in low mobile, I still think its a bug :) maybe its my poing of view, like if action saying it doing x and it does x+y(remove and slide to different slide) so or it should be fixed or maybe redocumented

**Comment by desandro** [comment]
You might want to try [Flickity](http://flickity.metafizzy.co). Flickity supports removing cells, with [its remove method](http://flickity.metafizzy.co/api.html#remove). When you remove an adjacent cell, the selected cell remains in the same place. See the demo: http://codepen.io/desandro/pen/WbMRgv

**Comment by boynet** [comment]
@desandro thank I know  Flickity, i cant use it right now because it not support group sliding

**Comment by kenwheeler** [comment]
This is actually expected behavior. You are on slide index 1. When you remove slide index 0, slide 3 is now at the first index.

**Comment by shaungupta** [comment]
I get that this is expected behaviour, but is there some way to stop this? I am removing slides as part of my lazy loading algorithm, and to get around it I am manually readjusting the slide number. The only issue is this creates a flicker as the current slide is readjusted, which I'd like to avoid...

**Comment by boynet** [comment]
@shaungupta I "solved" it by replacing the slide with empty div instead of removing it

**Comment by shaungupta** [comment]
I'd like to avoid keeping the slides in slick tbh as I use the slide indexes to decide when to load new data from the server. Also as I lazy load in both directions and have a maximum of around 15 slides loaded at a time, it will become pretty painful to keep empty slides around.
