### ISSUE TITLE
.slick-active is activating all visible in the asNavFor, not the one showing

### ISSUE THREAD

**Issue by carasmo** [kenwheeler/slick#1091]
The "1" should have the red border, but the rest should not. I am not understanding how to correct this.

![screen shot 2015-03-02 at 1 00 27 pm](https://cloud.githubusercontent.com/assets/1124594/6446896/28967188-c0dc-11e4-892e-de21f0d7f83e.png)

https://jsbin.com/mevaga/1/edit?html,js,output

```
$(document).ready(function() {

    $('.portfolio-thumb-slider').slick({
        slidesToShow: 4,
        slidesToScroll: 1,
        asNavFor: '.portfolio-item-slider',
        dots: false,
        arrows: false,
        focusOnSelect: true
    });

  
    $('.portfolio-item-slider').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        asNavFor: '.portfolio-thumb-slider'
    });
  

});
```

Reference to part of: https://github.com/kenwheeler/slick/issues/897

**Comment by carasmo** [comment]
Someone helped me on StackedOverflow:

https://jsbin.com/yifivi/1/edit?css,js,output

http://stackoverflow.com/a/28817146/1004312

**Comment by MikeMcNuke** [comment]
Hi, great. But the fixes only work with onAfterChange. Is this behaviour intended marking all items in the visible area as active, even if they are not the selected slide?

**Comment by kenwheeler** [comment]
@MikeMcNuke I probably need to refactor into .active and .visible classes

**Comment by shrkey** [comment]
May not be of use, but I've just come across this and the following removes the rogue class for me, and then after that the correct item is the only one selected. Put this in the init prior to calling slick on the element - from my example the navigation element is .gallery-navigation and the individual items are divs within it:

    $('.gallery-navigation').on('init', function(event, slick, currentSlide, nextSlide){
			$(".gallery-navigation div.slick-active").not(":first").removeClass( 'slick-active' );
		});
