### ISSUE TITLE
Sync Slider: navigate to first slide

### ISSUE THREAD

**Issue by shabith** [kenwheeler/slick#1092]
Hi,

In sync slider if you click navigation background it start to navigate to first slide.

you can see that issue in below fiddle.
http://jsfiddle.net/shabith/jg00v3ue/

1. navigate to 4th slider
2. click on that navigation background(sky-blue or teal color)

Any idea why this is happening?

**Comment by desandro** [comment]
You might want to take a look at [Flickity](http://flickity.metafizzy.co). Flickity supports [asNavFor](http://flickity.metafizzy.co/options.html#asnavfor) as well and this problem does not persist, althought, it does not not support `slidesToShow` or `slidesToScroll` yet.

**Comment by shabith** [comment]
@desandro Thanks :+1: But I need something with `slidesToShow` option.
Hi @kenwheeler Any idea about this issue?

**Comment by kenwheeler** [comment]
@shabith This should be fixed on master

**Comment by shabith** [comment]
Thanks @kenwheeler :+1: I can confirmed that It has been fixed.
