### ISSUE TITLE
Change swipe state on input focus event

### ISSUE THREAD

**Issue by estevanmaito** [kenwheeler/slick#1093]
Hi there.

I'm trying to disable swipe (or draggable) when I enter in an input field (focusin) (so I can select text without changing the slide) and enable it again on focusout.

What I've tried by now:

```javascript
$('.slider').slick({
    infinite: false,
    speed: 300,
    slidesToShow: 1,
    adaptiveHeight: true,
    asNavFor: '#menu-mobile',
    // tried to create a method this way
    stopSwipe: function () {
       slick.swipe = false;
    },
    // and this way, with 'this'
    startSwipe: function () {
       $(this).swipe = true;
    }
});
// tried calling those methods from outside but returned undefined
$('input').focusin(function () {
  $('.slider').slick.stopSwipe();
}).focusout(function () {
    $('.slider').slick.startSwipe();
});
```

Is there a way of getting/setting a property (like swipe or draggable) from an event? Please, let me know if you need more info.

Thank you.

**Comment by simeydotme** [comment]
hi @estevanmaito  - please read https://github.com/kenwheeler/slick/blob/master/README.markdown#methods :)

There's a `slickSetOption` method. This is not a slider bug/issue, so I'm closing :)

Best, Simon

**Comment by simeydotme** [comment]
It really looks like you're lacking some fundamental JS knowledge... if you create a topic on www.stackoverflow.com and paste the link here I'll try to help you on stackoverflow :)

**Comment by estevanmaito** [comment]
@simeydotme , thanks for your response.
I've tried to put all that I tried in one example code, maybe it wasn't the best choice.

I would be glad if you could show me the way I should take here: http://stackoverflow.com/questions/28862528/slick-slider-change-draggable-state-on-input-focus-event

Thank you again.

**Comment by simeydotme** [comment]
Glad you got some help on Stackoverflow! :smile: 
Sorry I wasn't fast enough to do it!! haha.
Happy coding.
