### ISSUE TITLE
Text appears after slide function (chrome)

### ISSUE THREAD

**Issue by lexbi** [kenwheeler/slick#1094]
Hey guys,

Sorry if this have been an issue, I couldn't find one that looked the same.

The text within my banner appears shortly after the slide in, I don't have any sort of css transform on the text.

Any ideas?

Chrome:
http://cl.ly/0Y1S2a1f0V43

Firefox:
http://cl.ly/2A1a04233V1q

**Comment by simeydotme** [comment]
can you create a JSFiddle please (best is if you provide one with just your JS and HTML)... we can't debug a movie :)

Here's a http://jsfiddle.net/nemh9nzk/ to get you started.

**Comment by lexbi** [comment]
Hey,

I made the movie because I can't replicate it with a fiddle :(

Thought you might be aware of some webkit issue.

**Comment by simeydotme** [comment]
have a read through this: 
https://github.com/kenwheeler/slick/issues/1020

:smile:

**Comment by lexbi** [comment]
Found it. it needs `backface-visibility:hidden;`, on my header text elements.

Just realised that this only happens when you use the dots too, not the arrows.

Cheers for the help.

**Comment by simeydotme** [comment]
My Pleasure.
