### ISSUE TITLE
Lock scroll direction

### ISSUE THREAD

**Issue by benmarinic** [kenwheeler/slick#1095]
Great component.  

Is there a way to lock scroll direction; i.e. if I start to scroll my mobile webpage (vertically) and the start touch occurred on the slick carousel, I can't seem to prevent the carousel side scroll.  In UIKit in iOS it's possible to lock the scroll direction which means if vertical scrolling starts then horizontal scrolling is ignored and vice versa.  I've started experimenting with listening for a window scroll events and disabling Slick, though with my limited JS knowledge I don't know how to do this either .  Many thanks.

**Comment by simeydotme** [comment]
hi @benmarinic - firstly thanks for contributing ! :) - but unfortunately you have not raised an issue with the plugin.... I would advise you seek coding help on a forum like www.stackoverflow.com :) - go ahead and leave a link to your stackoverflow topic here, once u have created it :)

Best of luck, Simon.
