### ISSUE TITLE
[Question] draggable with content div on top of slide

### ISSUE THREAD

**Issue by richardsengers** [kenwheeler/slick#1097]
Is it possible to add a content div (or caption) on top of a slide and still be able to drag the slide to the left and right?

**Comment by kenwheeler** [comment]
Sure. Is it inside the slide? Does it slide with the slide?

**Comment by richardsengers** [comment]
No it's on top of the slide and doesn't slide with the images.

Actually, the same happens when the arrows are on top of the slides and you want to drag the slides.

I'll provide you an url with an example soon.

Thnx for the quick reply

**Comment by kenwheeler** [comment]
I would personally put that in the div that wraps slick. Make that div pos relative, and make the caption pos absolute.

**Comment by richardsengers** [comment]
Here's an example
(Please check in Firefox, since chrome has a bug with translate and background-attachment fixed :-) have to check that one some other time)

http://tickr.marcomprocloud.eu/site/test

When I paste, for example, the nav between .draggable and .slick-track
Like this example, I get it working, but I can't imagine that's the way to do it :-)
![nav](https://cloud.githubusercontent.com/assets/810038/6488035/0fffde38-c295-11e4-87f9-437a4d1833bd.PNG)

**Comment by simeydotme** [comment]
`pointer-events: none;` on the overlay div.
http://caniuse.com/#feat=pointer-events

**Comment by richardsengers** [comment]
OMG that's sick dude :-) :
Never heard of that propertie before.

Many many thanks. 
Hope this was helpfull to others as well :+1:

**Comment by richardsengers** [comment]
One minor detail ... I can't find a suitable event to add a classname when a drag / swipe event starts.
The swipe event triggers even after the beforechange event.

dragStart and dragEnd would be perfect to add a custom classname to the container so I can add the pointer-events propertie only when a drag event takes place.

**Comment by simeydotme** [comment]
I think the point is: If you do not have `pointer-events`set, then you will never be able to trigger an event on the carousel as the text-div will absorb the event. `pointer-events` allows the text-div essentially to be invisible to the cursor so you can then touch the carousel behind.

Simon.l

**Comment by richardsengers** [comment]
Thank's for the reply,
I've noticed you can add pointer-events: auto to all click elements like buttons or anchors, so the basic behaviour still applies for those elements ...very nice feature :-)

"“If you add a click event listener to an element, then remove the pointer-events style (or change its value to auto, the click event will fire the designated functionality. Basically, the click event respects the pointer-events value.”"
