### ISSUE TITLE
slidesToShow greater than 1 causes arrows to not activate?

### ISSUE THREAD

**Issue by devonmather** [kenwheeler/slick#1098]
The following displays arrows in the markup
```
$('#slider').slick({
arrows: true,
slidesToShow: 1,
});
```
The following displays no arrows in the markup
```
$('#slider').slick({
arrows: true,
slidesToShow: 3,
});
```

Using Chrome and Slick 1.4.1

Thanks

**Comment by kenwheeler** [comment]
Slick won't activate unless you have enough slides to slide.

**Comment by devonmather** [comment]
Ok, interesting... I've added a fourth slide and the arrows have now appeared!

However if I have 3 slides in centerMode, how can you scroll through them without arrows?

**Comment by kenwheeler** [comment]
what do you mean?

**Comment by leggomuhgreggo** [comment]
This is being tracked in several other issues. Closing.
