### ISSUE TITLE
slickGoTo - Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Worstkaes** [kenwheeler/slick#1099]
Hi,

I am trying to realize a simple button with the "slickGoTo" method to slide to another slide, but all time I get the error "Uncaught TypeError: undefined is not a function". 

Do you have an idea, where I am wrong?

Here my Fiddle: http://jsfiddle.net/N6wfG/99/

**Comment by evalunamain** [comment]
The way you call methods has changed. You now need to call slick first and pass it the name of the method you want to call, like this:

slider.slick('slickGoTo', 1)

**Comment by Worstkaes** [comment]
Oh yeah, this works fine. Thanks for that!

**Comment by Barrytron** [comment]
Thanks you babe

**Comment by jay7134** [comment]
Thank you @evalunamain

**Comment by EdgarSalazar** [comment]
Why don't they changed it on the docs already? Geez.

**Comment by cupojoe** [comment]
just out of curiosity @evalunamain what was the reason for this change?

**Comment by novitalia28** [comment]
Thank you so much @evalunamain..
It's very help for me.. :+1:

**Comment by flaviort** [comment]
Awesome @evalunamain 
Finally got my slick to work with that!
Thank u =)

**Comment by gauravmewara** [comment]
i am getting  this error
uncaught TypeError: $(...).slick is not a function at interval ((index):807)

at this line
$('.single-item').slick('slickNext');
and also on this line
$('.single-item').slick('slickGoTo', goToThisIndex, false);

**Comment by Narendra-Rathore** [comment]
i am getting  this error
uncaught TypeError: $(...).slick is not a function at interval ((index):807)

at this line
$('.single-item').slick('slickNext');
and also on this line
$('.single-item').slick('slickGoTo', goToThisIndex, false);

**Comment by soufian250** [comment]
I don't think this solution is working anymore 
Try using 
`$('.slide').slick(
            slidesToShow: 1,
            centerMode: true,
            variableWidth: true,
            arrows: true,
).slick('slickGoTo', 1);`

credit: https://stackoverflow.com/a/54787822
