### ISSUE TITLE
Multiple carousels on one page with one next prev function

### ISSUE THREAD

**Issue by colinory** [kenwheeler/slick#1103]
I've a dynamic portfolio page which can have different amounts of carousels (defined through in wordpress). To go to the next & prev item I've 2 functions. At this moment a click on a next button changes all carousels on the page. 

How can I identify which next button has been click and only change this carousel?

http://jsfiddle.net/cv9zpypr/31/

**Comment by simeydotme** [comment]
1) You can only use an id once in a page: `#arrows` -> `.arrows`
2) You need to find the index of the arrow you press.

```js
$(function () {
    
    var $arrows = $('.arrows');
    var $next = $arrows.children(".slick-next");    
    var $prev = $arrows.children(".slick-prev");
    
    var slick = $('.your-class').slick({
        appendArrows: $arrows
    });

    $('.slick-next').on('click', function (e) {
        var i = $next.index( this )
        slick.eq(i).slickNext();
    });

    $('.slick-prev').on('click', function (e) {
        var i = $prev.index( this )
        slick.eq(i).slickPrev();
    });

});
```

http://jsfiddle.net/qx05juco/

You should really give more info: like that you're using `1.3.6` ;)
Also, this kind of question is help with your project, please in future ask on Stackoverflow. This is not a bug or Feature for Slick , it's your own code's feature :)

Regards, Simon.

**Comment by abithyzis** [comment]
Hi @simeydotme,

1.5.0 seems to break your solution.

`slick.eq(i).slickPrev()` throws an `Uncaught TypeError: undefined is not a function` Exception

Updated fiddle http://jsfiddle.net/qx05juco/2/

Regards,
Alexandros

**Comment by abithyzis** [comment]
Hi @simeydotme ,

1.5.0 seems to break your solution.

slick.eq(i).slickPrev() throws an Uncaught TypeError: undefined is not a function Exception

Updated fiddle http://jsfiddle.net/qx05juco/2/

It appears to work if I do `slick.eq(i).slick("slickPrev")`

Regards,
Alexandros

**Comment by simeydotme** [comment]
That is correct, but you updated the slick version after I explicitly told you the answer for an older version haha 😂

**Comment by abithyzis** [comment]
I tried using this code with 1.5.0 thinking it would work. You don't mention somewhere that this would only work on that version only. Is there a different way for 1.5.0?

**Comment by simeydotme** [comment]
The code you wrote is correct for 1.5.0, but really you don't need it:
http://jsfiddle.net/qx05juco/5/

:smile:

**Comment by jespermenting** [comment]
Hi @simeydotme,
I'm facing the same problem right now, I believe your code would work but I don't know where to implement it in my HTML. Could you help me out with this?

<html>

    <head>
        <title>Slick Carousel</title>
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.7/slick.css"/>
    </head>

    <body>

        <div class="wrapper">
            <div class="carousel">
                <div class="photodiv"><img src="images/image_1.png" class="photo"></div>
                <div class="photodiv"><img src="images/image_2.png" class="photo"></div>
                <div class="photodiv"><img src="images/image_3.png" class="photo"></div>        
            </div>
            <div class="arrows">
                <img src="images/arrowleft.png" class="arrowleft">
                <img src="images/arrowright.png" class="arrowright">
            </div>
        </div>

        <div class="wrapper">
            <div class="carousel">
                <div class="photodiv"><img src="images/image_1.png" class="photo"></div>
                <div class="photodiv"><img src="images/image_2.png" class="photo"></div>
                <div class="photodiv"><img src="images/image_3.png" class="photo"></div>
            </div>
            <div class="arrows">
                <img src="images/arrowleft.png" class="arrowleft">
                <img src="images/arrowright.png" class="arrowright">
            </div>
        </div>

        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.3.7/slick.min.js"></script>
        
        <script type="text/javascript">
            $(document).ready(function(){

                $('.carousel').slick({
                    dots: true,
                    speed: 300,
                    slidesToShow: 1,
                    centerMode: false,
                    prevArrow:".arrowleft",
                    nextArrow:".arrowright"
                });

            });
        </script>
        
    </body>

</html>

**Comment by saturday1** [comment]
I had the problem with this. I have custom aarrow buttons since I wanted dem at the navigation/dots of the slider. But when I added two (or more) sliders on the same page the buttons did control all sliders when which wasn't wanted. I wanted the arrows to just control the slider they were _connected_ to.

But these parts solved it:

`jQuery('.horizontal-list.normal .horizontal-list-container').each(function(index){});`

`prevArrow: jQuery('.custom-slick-prev')[index],`
`nextArrow: jQuery('.custom-slick-next')[index],`

And here is the whole script for those who want to see _the full_ solution:
``` javascript
// Add custom prev/next buttons so they exist
jQuery('.horizontal-list').each(function(){
  jQuery(this).append('<button type="button" class="custom-slick-prev" style="display: none;"><span>Previous</span></button>');
  jQuery(this).append('<button type="button" class="custom-slick-next" style="display: none;"><span>Next</span></button>');
});

jQuery('.horizontal-list.normal .horizontal-list-container').each(function(index){
  jQuery(this).slick({
    dots: true,
    slide: ".arena-record-container",
    slidesToShow: 4,
    slidesToScroll: 4,
    prevArrow: jQuery('.custom-slick-prev')[index],
    nextArrow: jQuery('.custom-slick-next')[index],
    infinite: false,
    responsive: [{
        breakpoint: 320,
        settings: {
            slidesToShow: 1,
            slidesToScroll: 1
        }
    }, {
        breakpoint: 500,
        settings: {
            slidesToShow: 2,
            slidesToScroll: 2
        }
    }, {
        breakpoint: 960,
        settings: {
            slidesToShow: 3,
            slidesToScroll: 3
        }
    },  {
        breakpoint: 1100,
        settings: {
            slidesToShow: 4,
            slidesToScroll: 4
        }
    }]
  });
});

jQuery(document).ready(function () {
  jQuery('.horizontal-list').each(function(){

    // Move custom prev/next buttons
    jQuery(this).children('.custom-slick-prev').insertBefore(jQuery(this).find('.slick-dots'));
    jQuery(this).children('.custom-slick-next').insertAfter(jQuery(this).find('.slick-dots'));
    
    // Do it when breakpoint as well so they do not fall away
    jQuery('.horizontal-list.normal .horizontal-list-container').on('breakpoint', function(){
      jQuery(this).children('.custom-slick-prev').insertBefore(jQuery(this).find('.slick-dots'));
    jQuery(this).children('.custom-slick-next').insertAfter(jQuery(this).find('.slick-dots'));
    });
  });
});
```

**Comment by ahmedohadi** [comment]
How would we accomplish same thing on Angular?

Thanks!
