### ISSUE TITLE
Cloned Slide Jump

### ISSUE THREAD

**Issue by leggomuhgreggo** [kenwheeler/slick#1105]
I'm making a slider, applying classes to the neighbors of currentSlide, so that it will have a staged effect. Here's a pen: http://codepen.io/anon/pen/VYGjJK

I'd like to get it so that there's no jump when the slider cycles through, and the clones are replaced. I was wondering if there was a method that would make that possible.

I know this is a customization, and understand if slick can't offer support, but I would appreciate any guidance.

Thanks!

**Comment by jamesckemp** [comment]
Hey @leggomuhgreggo 

Did you manage to solve this?

**Comment by leggomuhgreggo** [comment]
Nah, not yet.
