### ISSUE TITLE
beforeChange

### ISSUE THREAD

**Issue by ujwaldhakal** [kenwheeler/slick#1106]
How do i change the css or class of currentSlide how to access it?

```
 jQuery('.testimonialslides').on('beforeChange', function(event, slick, currentSlide, nextSlide){
    jQuery(this).find(currentSlide).addClass('testimonial-activeblock');
 jQuery(this).find('.testimonial-block').addClass('testimonial-activeblock');
 jQuery(this).find('child:testimonial-image').addClass('testimonial-activeimage');
 jQuery(this).find('.testimonial-detail').addClass('testimonial-activedetail');
})```

**Comment by simeydotme** [comment]
Sorry, @ujwaldhakal but this is not a good issue/bug report... I even doubt there is a bug to report :tired_face: ... please read: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown :smile: 

Feel free to re-open when you've fixed everything. :)

Simon.

**Comment by ujwaldhakal** [comment]
http://jsfiddle.net/nemh9nzk/#fork heres the link now i want to pass the that active class to upcoming slide and remove the class from previous slide
