### ISSUE TITLE
add class to currentSlide and remove class of previous slides

### ISSUE THREAD

**Issue by ujwaldhakal** [kenwheeler/slick#1108]
http://jsfiddle.net/nemh9nzk/#fork  How do i add the class to the current slides and remove the class of previous slides. 

Thank You

**Comment by jamesckemp** [comment]
It already has a "slick-active" class on the active slick slide - or do you want to add your own?

**Comment by ujwaldhakal** [comment]
i finally resolved the issue on my own but you guyz response was too slow :)

**Comment by jamesckemp** [comment]
It's not my script ;)

**Comment by ujwaldhakal** [comment]
anyway thanks bro you contacted me happy for that :)
