### ISSUE TITLE
Image glitch

### ISSUE THREAD

**Issue by aosmichenko** [kenwheeler/slick#1109]
I have used this js Lib in one of my projects and it has graphic glitch here is what I am talking about:
https://space.zeo.net/g/5as12/AXYG5BRPWLMTH5P4XTGTRXEXDT5AFUAX
can be found here http://www.inklab.com.au/project/sub-urban/
I am using Mac OS 10.10 Chrome latest/ other browsers has same issue!

**Comment by simeydotme** [comment]
Please read: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
:smile_cat:
