### ISSUE TITLE
slick dots wierd looking in Google Chrome

### ISSUE THREAD

**Issue by DesignMitZweiS** [kenwheeler/slick#1115]
hi ken,

i have a strange problem with the slick dots after using the CSS and JS from CDN (1.4).
It's not always happening but often when I refresh the page in Google Chrome.

I made a screenshot for you. heres a link to my site: http://design-mit-zwei-s.de

![slick-dots-broken](https://cloud.githubusercontent.com/assets/4666041/6564154/b97fa0e6-c6a6-11e4-8d16-3c28209abcda.gif)

maybe you can look into this.

thanx
Sven

**Comment by DesignMitZweiS** [comment]
Maybe it's my Chrome causing the issue itself. Will try a reinstall.

**Comment by DesignMitZweiS** [comment]
I think the bug is gone. Must have been Chrome.

**Comment by DesignMitZweiS** [comment]
hmm it still happens from time to time when I click through links on my tob-bar and get back to 'Startseite'

**Comment by DesignMitZweiS** [comment]
It's not happening on an other machin @work. same chrome version here. I think it's really a local issue on my pc @home. so .. closed.

**Comment by jayrav13** [comment]
Is this just an issue of browser, nothing more? Attaching a screenshot of what I'm seeing. Thanks in advance!


![screen shot 2015-04-20 at 11 15 38 pm](https://cloud.githubusercontent.com/assets/6322967/7245184/d0f6aed4-e7b4-11e4-9dff-05e2fd9effa0.png)

**Comment by Eschon** [comment]
I had a similar issue when I was testing my page from the file system without having it on a server. After I put it on a server and loaded it from there it looked like it should.
