### ISSUE TITLE
slick in table

### ISSUE THREAD

**Issue by voam** [kenwheeler/slick#1117]
putting slick in a table creates problems with the width as this fiddle demonstrates.

http://jsfiddle.net/03LL3fpw/1/

In another closed issue with same title as this one it is stated that this css will fix this problem. 
table {
    table-width: fixed;
}
However the problem persists even with this css.

We are using slick inside a CMS that uses tables for layout so we do not control the container slick is in.

**Comment by petebarr** [comment]
I've got the same issue. When using table css for responsive matched height blocks that contain slick, the width bursts out.

**Comment by scottbedard** [comment]
I've hit this problem too, I was trying to use the slider with CSS tables. A work-around I've found is to create a container for the slider, then measure the width of the container's parent and explicitly defining the container width. It's not pretty, but it gets the job done...

```js
$(window).on('load resize', function() {
    var parent   = $('.page'),
        wrapper = $home.find('.slider');
    wrapper.css('width', parent.width());
})
```

Hopefully this bug will be fixed in future versions

**Comment by lxndrrl** [comment]
**Hello everyone!**

I have same problem.

I use:
```html
<div class="table">
    <div class="table-cell">
        <!-- slick -->
    </div>
</div>
```

I tried wrapper proposed **Scottbedard**:
```html
<div class="table parent">
    <div class="table-cell wrapper">
        <!-- slick -->
    </div>
</div>
```
and

```html
<div class="table">
    <div class="table-cell">
        <div class="parent">
            <div class="wrapper">
                <!-- slick -->
            </div>
        </div>
    </div>
</div>
```
The examples given above do not work.

I probably do something wrong?

Thank You!

**Comment by petebarr** [comment]
I had to bin using CSS tables. Maybe use another method for equalising heights e.g. the :before method, or use matchheight.js.

**Comment by lxndrrl** [comment]
**petebarr**, thank You!

**Comment by michaeljpowell** [comment]
Yea I have the same issue

**Comment by olets** [comment]
Same here. @kenwheeler this came up because I'm using synched sliders side by side, and I want to center their contents vertically (I may try combining slick with matchheight and see what happens)

**Comment by wstoettinger** [comment]
I came across the same problem when I wanted to implement a responsive sticky footer as suggested here: http://galengidman.com/2014/03/25/responsive-flexible-height-sticky-footers-in-css/

unfortunately, slick messes everything up after that.

**Comment by kenwheeler** [comment]
You want to use table-layout: fixed

**Comment by gmclelland** [comment]
Thank you!
Adding table-layout:fixed worked for me.

**Comment by lxndrrl** [comment]
Thank you!

**Comment by CaspianRoach** [comment]
>You want to use table-layout: fixed

This solution works, but couldn't this be fixed somewhere on the plugin level? display: table; elements are still useful for design these days, until display: flex; incapable browser still exist

**Comment by neilmonroe** [comment]
I did not get it to work properly until I also added `width: 100%` to the fixed table element. Otherwise, the size is just set as the initial load size and does not change. In some situations, that may still be desirable, but to get the slider to fill the resizable container, the width needs to be specified.

**Comment by leggomuhgreggo** [comment]
Looks like this issue has run its course. Closing. Thanks everyone.

**Comment by dangelion** [comment]
@kenwheeler oh my god, `table-layout: fixed` saved me from a serious nervous breakdown.

**Comment by rlamarra** [comment]
Thank you ! table-layout: fixed; ...

**Comment by DishanTD** [comment]
Thanks!
table-layout:fixed , also worked for me.

**Comment by SSPai123** [comment]
Thanks!
 table-layout:fixed worked for me too. but upon resizing the browser size, the table gets all messed up. Please suggest what to do
