### ISSUE TITLE
Mobile - HTC One Android (Native Browser) - Drag/ Touchmove Issue

### ISSUE THREAD

**Issue by Padshiro** [kenwheeler/slick#1118]
Hey,

I noticed an issue on the HTC One phone (native browser).

The slide starts to drag but stops at around 50 pixels.

I have heard e.preventDefault() on the touchmove event will fix the issue.

I am not sure as I am not in possession of this Android device.

Cheers

**Comment by simeydotme** [comment]
Please read [contributing.md](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) , @Padshiro ... 

Really; telling us about some folk-story you've heard on someone else's phone with no evidence or proof, and no way to recreate the problem... _and then_ telling us you can't even create or test the problem yourself.... yeh, not a great issue :confused: -- Personally I have access to the device, but I need you to provide the circumstances (and software version) so I can test and debug... 

Please feel free to re-open this issue (using the re-open issue button below) if you can provide a better set of circumstances :smile: 

Best, Simon.
