### ISSUE TITLE
Can I add a carousel dynamically and initialize it after page load?

### ISSUE THREAD

**Issue by jon34560** [kenwheeler/slick#1119]
I would like to use document.createElement('div') to add a new carousel on demand but can't figure out how I would initialize it. Is this possible?

**Comment by befreestudios** [comment]
Try something like this...

<code><pre>(function($) {
var myCarousel = $(document.createElement('div'));
myCarousel.attr('id', 'myCarousel');
myCarousel.slick({});
})(jQuery);</pre></code>

**Comment by jon34560** [comment]
slick() in myCarousel is undefined.

**Comment by jon34560** [comment]
That worked. Thanks!
