### ISSUE TITLE
 -moz-box-sizing: border-box can be removed

### ISSUE THREAD

**Issue by coliff** [kenwheeler/slick#1121]
Suggest ' -moz-box-sizing: border-box;' to be removed from the CSS now. That vendor prefixed attribute was only required up until Firefox 28 (and we're now on Firefox 36 - and it auto updates so I think no need to support such an old version).

REF: http://caniuse.com/#search=box-sizing

**Comment by leggomuhgreggo** [comment]
Nice! I know this is ~8 months since, but would you care to make a PR?
