### ISSUE TITLE
 is this a bug?

### ISSUE THREAD

**Issue by Tokyodays** [kenwheeler/slick#1125]
hello. I try to test of slick 1.4.1
6th div tag. and option is this.
{
slidesToShow: 4,
slidesToScroll: 4,
dots: true
} 

sample is here
http://jsfiddle.net/takeshi/jdyq757x/5/

first. default position is this.
A.
[1][2][3][4]
○●

and push the right of dot button. 
B.
[3][4][5][6]
●●

and push the left dot button. i wish return to position A. but, it can not return. is this a bug?

**Comment by drogina** [comment]
I have the same problem.

Dots do not work unless the number of slides is a multiple of the number of slides to show. This is actually broken on the home page under 'Responsive Display' when there are only 3 slides showing.

**Comment by kenwheeler** [comment]
It's fixed on master
