### ISSUE TITLE
Unable to fiddle to allow only mobile screen to show slider

### ISSUE THREAD

**Issue by josleow** [kenwheeler/slick#1126]
1. On desktop screen there would be static layer with 18 different thumbnails a row by a row, using Bootstrap 3. In other word, it is no-slider.
2. When resize in smaller screen size, the slick starts with responsive slider showing 9 thumbnails in each slide. 

Wonder how to make it work?

**Comment by simeydotme** [comment]
hi @josleow ... please read: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown -- I think you'll agree this is not an issue with the plugin and so doesn't require a issue-tracker to be raised. :smile: 

Good luck with your project,
Best, Simon.

**Comment by josleow** [comment]
@simeydotme oops thanks and sorry

**Comment by simeydotme** [comment]
NP, if u make a post on stackoverflow, paste the link here and I'll take a look :)

**Comment by josleow** [comment]
@simeydotme here is post on stackoverflow: http://stackoverflow.com/questions/29036248/possible-to-make-the-slider-responsive-according-to-browser-size

Help appreciated :)
