### ISSUE TITLE
init event and get current slide do not work

### ISSUE THREAD

**Issue by mdunbavan** [kenwheeler/slick#1128]
Hi,

I am using the init callback which works but I am currently trying to get that first slides object data when you first load the slider (on init). Does anyone know how this can be done?

**Comment by adamcbrewer** [comment]
Same here, I can't get the `init`event to fire.

```js
$(slider).on('init', function (evt, slick, direction) {
    // nothing
});
```

**Comment by mhulse** [comment]
Not sure if this will help, but I've read that the `.on('init` must come before instantiating slick. See https://github.com/kenwheeler/slick/issues/1057#issuecomment-85200882

**Comment by simeydotme** [comment]
@mhulse is correct. This is just general JS knowledge :)

**Comment by gavin310** [comment]
This should not have been closed. The problem the OP is talking about is that $('.your-element').slick('slickCurrentSlide'); does not work when used in the init event.
