### ISSUE TITLE
Unslick method remove my navigation

### ISSUE THREAD

**Issue by bluepioupiou** [kenwheeler/slick#1130]
Hi all, this library seems perfect for me but I went into trouble :

I've got one div where I will put my items, and two div for the navigation with prevArrow and nextArrow config options. I use backbone and Marionette to populate my item, I 'slick' --> everything's going fine.

I want to filter my items, so I refresh my list of childs. When I 'unslick', it remove my navigation as well, so when I 'slick' again, I can't navigate anymore.

Is it the wrong way ? or can we detect that there is a custom navigation and not remove it ?

Thanks in advance

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by bluepioupiou** [comment]
http://jsfiddle.net/89hm43hm/

**Comment by simeydotme** [comment]
I think it's a known bug, but I fixed your issue:
http://jsfiddle.net/89hm43hm/1/

**Comment by bluepioupiou** [comment]
Wow, indeed, it's fixed. Thanks a lot
