### ISSUE TITLE
autoplay is working after window focus on autoplay: false in responsive options

### ISSUE THREAD

**Issue by wilkor** [kenwheeler/slick#1131]
Hey, 
autoplay is working after you switch to another tab and then switch back. 

my options look like this:
```javascript
var options = {
			autoplay: true,
			autoplaySpeed: 4000,
			arrows: false,
			dots: true,
			responsive: [
				{
					breakpoint: 768,
					settings: {
						autoplay: false
					}
				}
			]
		     }
```

**Comment by kenwheeler** [comment]
wat?

**Comment by wilkor** [comment]
If you set autoplay to true and then in responsive options you'll set it to
false on some breakpoint it works only on window load and resize, after
switching tabs in browser it starts playing even if window width is lower
than breakpoint.

Disabling autoplay via breakpoint doesnt work at all in IceWeasel - it's
 just autoplaying

2015-03-12 19:42 GMT+01:00 Ken Wheeler <notifications@github.com>:

**Comment by simeydotme** [comment]
Actually I saw this; it's regarding the `visibilityChange` event... it needs to check `autoplay` inside of it, currently it binds inside a check for `autoplay`, and if that value changes it'll start playing again after change :)

I can make a patch.
