### ISSUE TITLE
Feature Request: Handle Content Before Fade

### ISSUE THREAD

**Issue by nathanaelphilip** [kenwheeler/slick#1134]
Would it be possible to be able to animate the content inside the slide before the slide transitions? Maybe be able to set a delay before the change of the slide. 

One use case would be to fade out content before the background image faded.

**Comment by salunet** [comment]
This is possible with the beforeChange and AfterChange. Look at the code below...

<addr>
$('.masterCover').slick({
		autoplay: true,
  		autoplaySpeed: 5000,
		infinite: true,
  		speed: 800,
		fade: true,
		cssEase: 'linear',
		useCSS: true,
		swipe: false,
		touchMove: false,
		arrows: false
	});
	$('.masterCover').on('beforeChange', function(event, slick, currentSlide, nextSlide){
		$('.eclipse.item01').animate({'opacity': '0', 'left': '-100%'}, 0);
		$('.eclipse.item02').animate({'opacity': '0', 'left': '-100%'}, 0);
		$('.eclipse.item03').animate({'opacity': '0', 'left': '-100%'}, 0);
	});
	$('.masterCover').on('afterChange', function(event, slick, currentSlide){
		$('.eclipse.item01').animate({'opacity': '1', left: ''}, 2400);
		$('.eclipse.item02').animate({'opacity': '1', left: ''}, 1600);
		$('.eclipse.item03').animate({'opacity': '1', left: ''}, 800);
	});
</addr>
