### ISSUE TITLE
respondTo, fails when nested on element that width is resized with css

### ISSUE THREAD

**Issue by heldrida** [kenwheeler/slick#1137]
Hi,

I'm working on a project where I need to add a sidebar when expanded (expands Column Sidebar width, shrinks Column Content width where the slickjs carousel is.

```javascript

		&.sidebar-expanded {
			.wrapper-column {
				&.wrapper-column-sidebar {
					width: 25%;				
				}
				&.wrapper-column-content {
					width: 75%;
				}
			}
		}

		.wrapper-column {
			float: left;
			@include transition(width 0.4s cubic-bezier(0, 0, 0, 0.98));
			&.wrapper-column-sidebar {
				width: 0%;				
			}
			&.wrapper-column-content {
				width: 100%;
			}
		}

```

Unfortunately the elements inside the carousel are not positioned properly when expanding the sidebar. I'll TIAS using javascript animate element width instead of toggling a class name, but if someone knows what I should do, a better practice, please let me know!

```javascript

<div class="expanded">

			<!-- start: wrapper-column-content -->
			<div class="wrapper-column wrapper-column-sidebar">

				<!-- start: sidebar -->
				<div class="sidebar">
					// todo: sidebar
				</div>
				<!-- end: sidebar -->

			</div>
			<!-- end: wrapper-column-content -->

			<!-- start: wrapper-column-content -->
			<div class="wrapper-column wrapper-column-content">

				// carousel slick js here

			</div>


</div>

```

At the moment I'm tempted in, listening each expand/shrink animation step and toggle the resize.slick.slick-uid, but this sounds like such a bad practice ?

* I've end up using setPosition and solved the issue, but if someone knows what is the best practice let me know 

Thank you!

**Comment by simeydotme** [comment]
just do `$("window").trigger("resize");` whenever you expand / contract the column.

**Comment by ca-dsgn** [comment]
I am facing the same problem at the moment and would like to animate the width of the slideshow with a css transition (from a sidebar to the full content width and back). Is there any possibility to get slick with a real responsive behaviour?

**Comment by metallidevils** [comment]
> just do `$("window").trigger("resize");` whenever you expand / contract the column.

This doesn't seem to work. I'm not sure what the difference is between triggering this event manually and actually resizing the window.

The only workaround I've come across is listening for resize events, and manually calling carousel.$instance.slick('refresh');
