### ISSUE TITLE
about auto play with dot active

### ISSUE THREAD

**Issue by zewait** [kenwheeler/slick#1140]
I see some android phone,e.g **samsung s3**,**meizu**.The **li** element's attributes is changed,but the view look like same.I fixed your code to support my need.  
your code
```javascript
_.$dots.find('li').removeClass('slick-active').attr("aria-hidden", "true");
_.$dots.find('li').eq(Math.floor(_.currentSlide / _.options.slidesToScroll)).addClass('slick-active').attr("aria-hidden", "false");
```
change to
```javascript
_.$dots.find('li').removeClass('slick-active').attr("aria-hidden", "true").css('opacity', '0.25');
_.$dots.find('li').eq(Math.floor(_.currentSlide / _.options.slidesToScroll)).addClass('slick-active').attr("aria-hidden", "false").css('opacity', '0.75');
```
I think the browser inform view to update.
How can I inform view to update to replace this hard code?

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. Honestly, Im having trouble understanding the issue. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
