### ISSUE TITLE
Change slick-slide width in percentages (question)

### ISSUE THREAD

**Issue by peterboorsma** [kenwheeler/slick#1141]
Is it somehow possible to adjust the size of slides so you can show the active slide 100% and get a X% preview of the next slide? (see screenshot for example). It seems the Javascript is overriding the width to the exact pixels (100% of window width).

![screen shot 2015-03-16 at 11 20 58](https://cloud.githubusercontent.com/assets/2750653/6664283/9c70b648-cbce-11e4-91ba-f529329f2fb1.png)

**Comment by wearehyphen** [comment]
I was looking into the same, but only needed pixels. With a little modification, I think you could use my code to work with percentages. The code can be found here;

https://gist.github.com/wearehyphen/d9cbe84331e9c32d5e27

**Comment by leggomuhgreggo** [comment]
Hey sorry that this has gone so long without being addressed. I think center mode more or less addresses this. I'm gonna close but feel free to circle back if you're still having issues. Thanks
