### ISSUE TITLE
Carousel not showing up unless i resize the window

### ISSUE THREAD

**Issue by MohamedMehrez** [kenwheeler/slick#1142]
Hi,great plugin,i only have one problem tho,the carousel isn't showing up unless i resize the navigator(i'm testing on chrome PC btw),the gallery is initially hidden,the second i start resizing the navigator it shows up just perfect.
I tested on mobile and it's technically the same issue only with tapping instead of re sizing.

I would appreciate any help. Thanks!

**Comment by simeydotme** [comment]
Please read: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown, @MohamedMehrez  :)
