### ISSUE TITLE
Disable the use of css transforms

### ISSUE THREAD

**Issue by rikkertkoppes** [kenwheeler/slick#1143]
Since `position:fixed` breaks when using css transforms (<https://code.google.com/p/chromium/issues/detail?id=20574>), a feature to disable it altogether would be nice (and live with left / top transitions).

Since there is already `transformsEnabled` internally, this would be a rather minimal adjustment.

Proposed changes:

- add an option `useTransform`, default to false
- change [this line](https://github.com/theapsgroup/slick/blob/master/slick/slick.js#L1654) to 

        _.transformsEnabled = _.options.useTransform && (_.animType !== null && _.animType !== false);

- add a class if transforms are enabled:

        if (_.transformsEnabled) {
            _.$slider.addClass('use-transform');
        }

- only use transforms for that class

        .slick-slider.use-transform .slick-track,
        .slick-slider.use-transform .slick-list {
            -webkit-transform: translate3d(0, 0, 0);
            -moz-transform: translate3d(0, 0, 0);
            -ms-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
        }

**Comment by simeydotme** [comment]
which element is `position: fixed;` ?

**Comment by electerious** [comment]
Looks like this issue has already been fixed: https://github.com/kenwheeler/slick/pull/1632

**Comment by vlrprbttst** [comment]
even though i use usetransform: false, i still get the transform on my slick carousel
