### ISSUE TITLE
Set a number of slides to open when page loads

### ISSUE THREAD

**Issue by brunoDegaspare** [kenwheeler/slick#1147]
Hi,

First of all I apologise if my question is already answered here as I searched and couldn't find anything.

Ok so I have a 2 rows carousel with 8 slides and my issue is that slick loads all slides first then hides them showing only one slide per time.

Is there a way to set slick to load only one slide per time instead of loading all of them?

**Comment by simeydotme** [comment]
JSFiddle, please.

If you're tlaking about a flash of unstyled content (__FOUC__) then the solution is to set `display:none;` on your slides by default, and then set `display: block;` on slides with `.slick-initialised` class and to `.slick-slide::first-child` :smile:

**Comment by damarusama** [comment]
I got FOUC syndrome too, would you put the slick-initialise style in the static css, or would you have to load it in the js?

**Comment by mhulse** [comment]
> If you're talking about a flash of unstyled content (**FOUC**) then the solution is to set display:none; on your slides by default, and then set display: block; on slides with `.slick-initialised` class and to `.slick-slide::first-child`

Thanks for tip @simeydotme! :+1: 

Not a big deal, but here's a slight correction to your code suggestions:

```css
.slick-initialized,
.slick-slide:first-child { display: block; }
```

Note spelling, and `first-child` as pseudo-class.

Thanks again!

**Comment by simeydotme** [comment]
:+1:

**Comment by mhulse** [comment]
> silly Americani~z~sed mistake ;) snigger

Ah, right! Lol. Funny. :laughing:
