### ISSUE TITLE
Discrepancy in :before content - dot • gets encoded as â€¢

### ISSUE THREAD

**Issue by stefek99** [kenwheeler/slick#1148]
Source on github: 
* https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.scss#L13 ```$slick-dot-character: "•" !default;```
* https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.css#L188 ```content: '•';```

CDN:
https://cdn.jsdelivr.net/jquery.slick/1.4.1/slick-theme.css
![https___cdn_jsdelivr_net_jquery_slick_1_4_1_slick-theme_css](https://cloud.githubusercontent.com/assets/249703/6672332/af8dfbd4-cc03-11e4-96e0-6fec3237a580.jpg)

**Comment by fpm5022** [comment]
+1

**Comment by austinsamsel** [comment]
same. had to replace these by hand, otherwise my sass wasn't compiling.

```
$slick-prev-character: "&#8592;" !default;
$slick-next-character: "&#8594;" !default;
$slick-dot-character: "&#8226;" !default;
```

**Comment by simeydotme** [comment]
I think this PR should fix the issue: https://github.com/kenwheeler/slick/pull/1045 ?

**Comment by tipodisimmia** [comment]
+1
