### ISSUE TITLE
Issues Using Slick inside a Polymer Custom Element

### ISSUE THREAD

**Issue by eriklharper** [kenwheeler/slick#115]
I'm running into issues using Slick inside of a Polymer custom element to create a Video Carousel of Youtube video embeds.  Reference this SO question I created that goes into much more detail:
http://stackoverflow.com/questions/22923956/use-external-scripts-inside-a-polymer-element

I've also tried using slickAdd with no success, both on a plain-jane html page with static slide markup and inside of my Polymer element.  I thought maybe if I constructed the slides in javascript code using slickAdd, and passing in the 'template' for each slide as html with the dynamic video IDs passed in, but it doesn't work, and no console errors.

Here's my plain-jane code attempting to add slides dynamically from code (slickRemove also doesn't work, let me know if I'm doing that part right):

```
<div class="your-class">
      <div><iframe width="420" height="315" src="//www.youtube.com/embed/Fp1wPwszF9M" frameborder="0" allowfullscreen></iframe></div>
      <div><iframe width="420" height="315" src="//www.youtube.com/embed/Fp1wPwszF9M" frameborder="0" allowfullscreen></iframe></div>
      <div><iframe width="420" height="315" src="//www.youtube.com/embed/Fp1wPwszF9M" frameborder="0" allowfullscreen></iframe></div>
    </div>



    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="bower_components/slick-carousel/slick/slick.js"></script>

    <script>
    $(document).ready(function(){
        $('.your-class').slick({             
          //autoplay: true,
          arrows: true,
          centerPadding: '50',
          dots: true,
          infinite: 'true',
        });
        $('your-class').slickAdd('<div><iframe width="420" height="315" src="//www.youtube.com/embed/Fp1wPwszF9M" frameborder="0" allowfullscreen></iframe></div>');
        $('your-class').slickRemove(1);
        $('your-class').slickAdd('&lt;div&gt;&lt;h3&gt;new slide&lt;/h3&gt;&lt;/div&gt;');
    });
    document.addEventListener('WebComponentsReady', function() {
        // Perform some behaviour


          // $(this.$.carousel).slickAdd('&lt;div&gt;&lt;iframe width=&quot;420&quot; height=&quot;315&quot; src=&quot;//www.youtube.com/embed/' + element.id + '&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;&lt;/div&gt;');

    });
    </script>
```

**Comment by domenicop** [comment]
I had it working with Polymer 0.5, but it's completely broken on 1.0.
It seems to replicate an instance of the generic non-computed element for some reason.
For example, if I have an element that is <div><a href="{{ url }}"><img src="{{ imgSrc }}"/>{{ text }}</a></div>, every element will literally be <div><a href="{{ url }}"><img src="undefined"/></a></div> instead of  <div><a href="http://blabla.com"><img src="http://blala.com"/>Hello!</a></div> etc...

**Comment by jdmagic21** [comment]
@eriklharper I am not really sure how you have reached a solution with this problem. Is there a way that I can see your polymer code and your html template that you are using? I am still struggling with trying to get this to work.

**Comment by jonnybot0** [comment]
For some example code with an alternate implementation, check out my [answer to Erik's question on SO](http://stackoverflow.com/a/22969392/1524502). Here's the code without too much context:

I had a very similar use case. What I did was create a template for the slide, a template for the slider, and then initialized slick in my base page. In the Slider template's constructor, I use a `factoryImpl` function to add the individual slides in

<h1>Slide template</h1>
    <dom-module id="slide">
        <template>
            <div>
                
            </div>
        </template>
        <script>
            Slide = Polymer({
                is: 'slide',
                factoryImpl: function(slide) {
                    //Assume slide is a JS object that I use to set any {{properties}} I'll need
                    this.property = slide.analagousProperty;
                    this.otherProperty = someFunction(slide.analagousProperty);
                },
                properties: {
                    //Properties defined here
                }
            });
        </script>
    </dom-module>

<h1>Slider template</h1>
    <dom-module id="slider">
        <template>
            <div id="slider">
            </div>
            <div class="controlHolder">
            </div>
        </template>
        <script>
            Slider = Polymer({
                is: 'slider',
                factoryImpl: function(slides) {
                    var destination = Polymer.dom(this.$.slider);
                    for (i = 0; i < slides.length; i++) {
                        var slide = new Slide(slides[i]).querySelector('div');
                        destination.appendChild(slide);
                    }
                    Polymer.dom.flush();
                },
                ready: function() {
                    $('#slider').on('afterChange', 
                        function(event, slick, currentSlide) {
                            $('.slick-center .play-button').click(function() {
                            });
                    });
                }
            });
        </script>
    </dom-module>

<h1>Actual page</h1>
    <head>
        <script src="../bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <script src="../bower_components/jquery/dist/jquery.min.js"></script>
        <script src="../bower_components/slick-carousel/slick/slick.min.js"></script>
        <link rel="import" href="../bower_components/polymer/polymer.html">
        <link rel="import" href="../base_slide.html">
        <link rel="import" href="../base_slider.html">
        <link rel="stylesheet" type="text/css" href="../bower_components/slick-carousel/slick/slick.css" />
        <link rel="stylesheet" type="text/css" href="../bower_components/slick-carousel/slick/slick-theme.css" />
        <link rel="stylesheet" type="text/css" href="../myCustomStyleSheet.css">
    </head>
    <body>
        <div class="mainContent"> 
            <h1>Some heading</h1>
        </div>
        <div id="slideContent">
        </div>

        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var slides = [
                    {
                        sourceImage: '1.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '2.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '3.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '4.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '5.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '6.jpg',
                        caption: 'A kindly person'
                    },
                    {
                        sourceImage: '7.jpg',
                        caption: 'A kindly person'
                    }
                ];
                var slider = new Slider(slides);
                document.getElementById('slideContent').appendChild(slider);
                $('#slider').slick({
                    arrows: true,
                    initialSlide: 4,
                    dots: true,
                    infinite: true,
                    cssEase: 'ease',
                    accessibility: true,
                    swipeToSlide: true,
                    focusOnSelect: true,
                    centerMode: true, //Requires odd number of slides to show
                    slidesToShow: 5,
                    centerPadding: '60px',
                    adaptiveHeight: true
                });
            });
        </script>
    </body>
