### ISSUE TITLE
Incorrect behaviour of 'slickGoTo' method

### ISSUE THREAD

**Issue by al-v-in** [kenwheeler/slick#1153]
JSFiddle: [http://jsfiddle.net/al_v_in/zv5zqbdg/3/](http://jsfiddle.net/al_v_in/zv5zqbdg/3/)

Conditions:
slidesToShow > 1 
And slidesToShow = slidesToScroll
And numberOfSlides % slidesToShow != 0

Then the slickGoTo method doesn't always go to the correct slide.

Example: we want to show 2 slides at a time (slidesToShow = 2), when scrolling we want to scroll both (slidesToScroll = 2) and we have 7 slides. Using slickGoTo(0), goes to slide 6 (index 5) repeatedly (and more weird behaviour, see jsfiddle)

**Comment by gsjen** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Looks like this has been resolved in the master. Thanks!
