### ISSUE TITLE
Slick somehow generates an error in jQuery on mouseout movement from carousel element

### ISSUE THREAD

**Issue by wzup** [kenwheeler/slick#1155]
When I attach Slick to an element (markup is correct) and then open Chrome console and do mouseout from the carousel element an error is thrown - Paused in debugger. And it shows that the error is in `jquery-1.11.1.min.js` file.

Here is how I call Slick.
```
    $("#teaser").slick({
        dots: true,
        dotsClass: 'slick-dots',
        draggable: false,
        infinite: false,
        pauseOnDotsHover: true,
        arrows: false
    });
```

Here is screenshot of console:

![slisk error](https://cloud.githubusercontent.com/assets/3880497/6715849/71658b86-cdc7-11e4-8e80-93a7a9e6c1d3.png)

Here is a markup of the carousel element:

```
<section id="teaser">
    <div><img src="/assets/img/teaser.png"></div>
    <div><img src="/assets/img/teaser.png"></div>
    <div><img src="/assets/img/teaser.png"></div>
    <div><img src="/assets/img/teaser.png"></div>
</section>
```

Here is how Slick is attached on a page. After jQuery:

```
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick.css"/>

        <script type="text/javascript" src="/assets/js/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/assets/js/modal.js"></script>
        <script type="text/javascript" src="/assets/js/main.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.4.1/slick.min.js"></script> 
```

What is wrong with Slick? Why it generates an error and runs debugger? Without calling Slick on the element all works fine.

**Comment by simeydotme** [comment]
JSFiddle, please.

**Comment by wzup** [comment]
False alarm, sorry.
The issue was that a `mouseout` eventlistener breakpoint was accidentally checked in Chrome Dev Console. So any `mouseout` events triggered. I unchecked that and now all works fine.

![javascript bootstrap - google chrome 2015-03-19 16 11 13](https://cloud.githubusercontent.com/assets/3880497/6728834/ff3b2bb0-ce52-11e4-857a-9cf95581f864.png)
