### ISSUE TITLE
.slick-cloned causes issues when ID's are contained

### ISSUE THREAD

**Issue by georgephillips** [kenwheeler/slick#116]
When there are id's within a slide the id's also get duplicated. The one used as the clone on the end is not the original. This could be solved by removing id's and ensuring the originals are not the ones used as clones. It could be solved by removing the cloning and using the original every time so that the slides support accordions and other more complicated elements.

**Comment by theknightsky** [comment]
Man TT this is sort of a fundamental flaw of this amazing plugin. Has anyone found a way around this?? In my case, I must use IDs, and therefore I can't find a work around for the problem.

If anyone has a solution, please let me know.

**Comment by ArakelyanEdgar** [comment]
Yea this is causing a huge issue for me as well.

**Comment by Hostuniverse** [comment]
Not sure if this helps but I had the same issue and what worked for me was to use data tags instead of ID's. you could also use those data tags then to set the missing ID's accordingly.
