### ISSUE TITLE
??Bootstrap!! 

### ISSUE THREAD

**Issue by federicoscudeler** [kenwheeler/slick#1162]
Hello Hello!

I've try to integrate Slick in bootstrap 3, and I encounter a really bizzarre issue!
Yesterday afetr setting up scripts in my doc everything was working really fine, 
but today the script of slick.min.js has beginned to cause conflicts with the controls of "modal-carousel" a package of .js+.css (by noreiller https://noreiller.github.io/bootstrap-modal-carousel/modal-fullscreen.html)

take a look at this!

here's with slick script at the end of the file: http://thisurliswaytoolongtobewellindexedongoogle.com/deve/

here's without: 
http://thisurliswaytoolongtobewellindexedongoogle.com/deve/index_2.html

Can someone tell me what's happening?

**Comment by leggomuhgreggo** [comment]
I know this is months later, but I'm trying to sort through old issues. Looks like your demo links are out of date. Gonna close, but if you want to circle back with a fresh test case, please feel free. Also there're a number of bootstrap related issues if you search; so, perhaps one of those would be helpful. Thanks!
