### ISSUE TITLE
Reverse Autoplay Direction

### ISSUE THREAD

**Issue by greaveselliott** [kenwheeler/slick#1163]
Is there a way to reverse the slides autoplay direction?

**Comment by simeydotme** [comment]
change RTL property? :) (but you might have to move arrows around, then...)

**Comment by greaveselliott** [comment]
I tried this, but the slider has major display errors when set to RTL.

**Comment by simeydotme** [comment]
hmm, in that case, the answer is: __No.__ so I think it's a valid feature request, you can find out how to request a feature in the [contributing.md](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) file.

**Comment by simeydotme** [comment]
Oh, and if you can provide a JSFiddle showing the "major display issues" it would really help us fix them :)

**Comment by greaveselliott** [comment]
Apologies for my “major display issue” description - thinking about the bug now - its most likely a conflict with external scripts/styles. Unfortunately I can’t copy paste the project because it can’t go live just yet, If you give me you email address, I’m happy to share you a temporary link to the project on my virtual server?

Cheers,

- Elliott

**Comment by pipeTM** [comment]
Set slidesToScroll to -1

**Comment by mazzaker** [comment]
"Set slidesToScroll to -1"
did not work for me, but with rtl and dir="rtl" direct on the slider it work well - just have to add a float: left to the slide content because i have 3 sliders with images and only the 2nd one with rtl.

**Comment by greaveselliott** [comment]
I never did find a solution to this one.

**Comment by DaveData** [comment]
Same for me, `slidesToScroll: -1`, `rtl`nothing worked, so I did it by hand. This also pauses play on hover.
```javascript
var autoplaySpeed = 2000;
var autoplayOn    = true;

var $slickRoot = $('#your-selector');

$slickRoot.on('init', function() {
    var $slickList = $slickRoot.find('.slick-list');

    $slickList.mouseenter(function() {
        autoplayOn = false;
    });
    $slickList.mouseleave(function() {
        autoplayOn = true;
    });

    window.setInterval(function() {
        if (!autoplayOn) return;
        $slickRoot.slick('slickPrev');
    }, autoplaySpeed);
});

$slickRoot.slick({
    infinite: true,
    autoplay: false
    // ...
});
```

**Comment by mazzaker** [comment]
Here is my solution. As mentioned there are three sliders all of them display user pictures with an overlay on hover/on mobile.

js:
    
    $(document).ready(function() {
        var sliderRandom = $('.slider-random');
        var sliderOnline = $('.slider-online');
        sliderOnline.attr('dir', 'rtl');
        var sliderVisits = $('.slider-visits');
        // next line I needed for my responsive layout: calculate the maxItems by parents width
        var maxItems = Math.round(sliderRandom.parent('div').width() / 195);
        sliderRandom.slick({
            lazyLoad: 'ondemand',
            slidesToShow: maxItems,
            slidesToScroll: 1,
            swipeToSlide: true,
            centerMode: false,
            autoplay: true,
            autoplaySpeed: 3000,
            arrows: false,
        });
        sliderOnline.slick({
            lazyLoad: 'ondemand',
            slidesToShow: maxItems,
            slidesToScroll: 1,
            rtl: true,
            swipeToSlide: true,
            centerMode: false,
            autoplay: true,
            autoplaySpeed: 3000,
            arrows: false,
        });
        sliderVisits.slick({
            lazyLoad: 'ondemand',
            slidesToShow: maxItems,
            slidesToScroll: 1,
            swipeToSlide: true,
            centerMode: false,
            autoplay: true,
            autoplaySpeed: 3000,
            arrows: false,
        });
    });

HTML:
```
    <div class="columns small-12">
        <h2 class="title">My title</h2>
        <div class="gallery rows-1 slider-online">
            <div class="slick-slide">
                <div>
                    <a href="/community/profile/show/username/XXX" class="profile-link">
                        <img class="profile-image" src="/images/gallery/XXX.jpg">
                        <div class="imageInfo" style="direction: ltr;">
                            <div>XXX,&nbsp;</div>
                            <div>41 Years,&nbsp;</div>
                            <div>County: Cornwall</div>
                        </div>
                    </a>
                </div>
                // next item
            </div>
        </div>
    </div>
```

CSS:
This one I need to change for scroll. Default is float right!

    [dir='rtl'] .slick-slide {
        float: left;
    }

**Comment by talbenbasat** [comment]
+1

**Comment by engelfrost** [comment]
Does this demonstrate the same issue? http://jsfiddle.net/3mak6rv5/1/

**Comment by mazzaker** [comment]
No only a missing css/attribute:
dir="rtl"
or
direction = rtl;

**Comment by leggomuhgreggo** [comment]
Hey I know this is months later, but I'm sorting through old issues. Are people still having this issue? RTL seems to be working on the demo page. Make sure you're using `dir="rtl"`

Gonna close, but if you anyone thinks there's still a bug and want to circle back with a fresh test case, please feel free. Thanks!

**Comment by fayazrehmani** [comment]
engelfrost js fiddle is the same issue I am facing when i add dir: rtl. In Ltr the slider seems to be working excellent. leggomuhgreggo kindly help me out as I have used slick on some site and its in development.
Would really appreciate ur help.
When I turn infinite false my first slide or first chuck if slidesToShow is set to 5 will display. the slider also moves in rtl direction but slides are all in ltr still.

**Comment by sbcmeg** [comment]
I'm still having this issue, tried using the dir: rtl, with the same setup on the demos. I've also tried the slidesToScroll to -1 and I'm still having the issues.

**Comment by cmy868** [comment]
Just find a way that you don't have to do with rtl! ( rtl for me also not works...

In **slick.js**, find '**Slick.prototype.autoPlayIterator = function()**' 

Change '**+**' to '**-**' in the '**slideTo = _.currentSlide + _.options.slidesToScroll;**'

This works for me!

**Comment by madhurijawadekar-16** [comment]
"Set slidesToScroll to -1"
did work for me, but its not working for responsive view Please suggest me something about this if anyone have an idea
