### ISSUE TITLE
slick-dots and custom encapsulating div

### ISSUE THREAD

**Issue by erthi16** [kenwheeler/slick#1167]
I have an issue... after my slick carrousel initialisation, I add a custom div around the ul slick-dots.  Everything works fine up to the point when I resize my browser... the dots are regenerated and I lose my custom div! Is there a way to tell when the slick carrousel is regenerating the slick-dots? I could then add my custom div again!
In my investigations, I tried to use the reInit event by adding it before (and even after) the initialisation of my carrousel but it simply would not fire!
Thanks for your help!

**Comment by simeydotme** [comment]
Please refer to: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown :smile:

**Comment by erthi16** [comment]
I've done an exemple here: http://jsfiddle.net/m4yuqcnx/1/
I've put a div around the dot list and if your recise the viewport to less than 300px, the carrousel goes from 3 to 1 slides... and the dot list is automaticaly rewritten... thus my custom div around it dissapears! So the break points are the key to all this! Is there a way that the slick code could tell when it occurs so I can reinsert my custom div?
Thanks a milion times!

**Comment by simeydotme** [comment]
http://jsfiddle.net/m4yuqcnx/2/

**Comment by coding-killer** [comment]
Check this once: https://codepen.io/martindubenet/pen/KrQWJq
