### ISSUE TITLE
Vertical mode uses horizontal scrolling

### ISSUE THREAD

**Issue by Seanom** [kenwheeler/slick#1171]
When set to vertical mode the scrolling/touch/draggable is still done horizontally.

I would expect to be able to scroll/touch-move up or down and have the slider respond. 

See the following fiddle
https://jsfiddle.net/nemh9nzk/29/

**Comment by simeydotme** [comment]
Hey, thanks for contributing @Seanom ... but you could have done a very simple search to find this :)
https://github.com/kenwheeler/slick/issues/1001

Regards, Simon.

**Comment by Seanom** [comment]
ahh, my mistake I ran a search but only on open tickets. Nice to see its in progress. 

Thanks

**Comment by simeydotme** [comment]
No sweat :smile: - the default search is kinda icky, always gotta delete that "is: issue, is: open" :/
