### ISSUE TITLE
Vertical swipe for slick in verical mode

### ISSUE THREAD

**Issue by mpa3b** [kenwheeler/slick#1173]
Is it possible? 
It there an implementation?

**Comment by mhulse** [comment]
I'd like to know this as well. When I switch on vertical mode, the swipe is left/right; generally speaking, how tricky would it be to make the swipe up/down? Anyone out there make this work?

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/1001
:)

**Comment by mhulse** [comment]
> #1001
> :)

Doh! Thanks! :+1:
