### ISSUE TITLE
Display animation when slider initially loads?

### ISSUE THREAD

**Issue by nickpish** [kenwheeler/slick#1178]
I have a slider configured with a large amount of (lazy-loaded) images, and upon initially loading the page, for a brief moment I can see the slide divs that compose the slider stacked upon one another. I'm assuming this derives from the fact that I'm loading the scripts-- i.e. jquery and slick slider-- at the bottom of the page, so the markup/css is rendered briefly before the script is run, but I'm wondering if there's a way via jQuery to initially show a loading animation in place of the slider-- and thus hide the slides-- until it's fully loaded and ready to run; is this relatively simple to accomplish?

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. If you're still interested there's been several issue threads on this subject. I’m going to close this. Thanks!
