### ISSUE TITLE
jQuery Easing Plugin

### ISSUE THREAD

**Issue by lionel-m** [kenwheeler/slick#118]
Hi,

Can we use [jQuery Easing Plugin](http://gsgd.co.uk/sandbox/jquery/easing/) ?

I added the script : 

``` HTML
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
```

And added `easing`

``` JS
$(document).ready(function() {
    $('.fade').slick({
        dots: true,
        infinite: true,
        speed: 800,
        fade: false,
        slide: 'div',
        easing: 'easeInOutBack'
    });
});
```

But it does not work. Should I add or change something?

Thanks

**Comment by routy** [comment]
Is this no longer functional? It seem whenever I place something in the cssEase param, it doesn't look any different.

**Comment by kenwheeler** [comment]
What are you putting in?

**Comment by routy** [comment]
Hey @kenwheeler I just found another github issue that resolved the confusion, the current version of the plugin requires useTransform: true. It is now working. #1950 

Thanks for this plugin, it is awesome!

**Comment by kenwheeler** [comment]
No prob, glad you enjoy it!
