### ISSUE TITLE
Incorrect width

### ISSUE THREAD

**Issue by pramodx** [kenwheeler/slick#1180]
Hi Ken

Ive implemented teh slick slider here ; http://rag2015.snau.com.au. If you keep scrolling to the right there is quite a bit of blank space appearing. Any pointers on what could be causing this. My code block is:

```js
s.slick({
				dots: false,				
				infinite: true,
				speed: 300,				
				responsive: [
					{
						breakpoint: 1024,
						settings: {
							slidesToShow: 3,
							slidesToScroll: 3							
						}
					},
					{
						breakpoint: 800,
						settings: {
							slidesToShow: 2,
							slidesToScroll: 2
						}
					},
					{
						breakpoint: 600,
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1
						}
					},
					{
						breakpoint: 480,
						settings: 'unslick'
					}
			    // You can unslick at a given breakpoint now by adding:
			    // settings: "unslick"
			    // instead of a settings object
			    ]

			})
```

where s is the slider object.

Thanks
Pramod

**Comment by simeydotme** [comment]
Hi @pramodx , please refer to https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown to help improve your issue log :)

Simon

**Comment by tomatau** [comment]
Having a look at your website @pramodx and it looks fine from here - I have the same issue however. When I run slick locally the images get inlined with the correct width (for a NDA demo I'm building). However when I open the same files in a gh-pages environment to share with my colleagues, the inline styles are set to have a much larger width (in-fact the width of the parent div).

```
        <div class="col-xs-10 col-md-10">
          <div class="slider"
            data-slick='{
              "slidesToShow": 5,
              "autoplay": true,
              "respondTo": "min",
              "slidesToScroll": 2
            }'
          {{#each first-images.urls}}
            <div>
              <img src="{{this}}">
            </div>
          {{/each}}
          </div>
        </div>
```

I feel that attempts to recreate this would be inconsistent as it already works perfectly fine locally. Seems the environment is causing problems.

**Comment by tomatau** [comment]
After further investigation... The data doesn't play well with handlebars. HTML generally expects attribute values to be contained in `"` rather than `'`. So handlebars parses the data attribute incorrectly.

When swapping the inline object to be wrapped inside double quotes and using single quotes around property names in the object, slick seems to not function correctly.

Have tried with :

```
data-slick="{
              'slidesToShow': 5,
              'autoplay': true,
              'respondTo': "min",
              'slidesToScroll': 2
            }"
```
,
```
data-slick="{
              slidesToShow: 5,
              autoplay: true,
              respondTo: "min",
              slidesToScroll: 2
            }"
```

and

```
data-slick="{
              \"slidesToShow\": 5,
              \"autoplay\": true,
              \"respondTo\": \"min\",
              \"slidesToScroll\": 2
            }"
```

The only format that works is: 

```
data-slick='{
              "slidesToShow": 5,
              "autoplay": true,
              "respondTo": "min",
              "slidesToScroll": 2
            }'
```

But this breaks with handlebars.

**Comment by kenwheeler** [comment]
I'll see if I can address this for 1.5.1

**Comment by pramodx** [comment]
For the time being this is fixed for me. I noticed that it appears fine if
I set centerMode to false.

On 30 March 2015 at 06:27, Ken Wheeler <notifications@github.com> wrote:

> I'll see if I can address this for 1.5.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kenwheeler/slick/issues/1180#issuecomment-87460460>.
>



-- 
Best Regards
Pramod

----------------------------------

**Comment by tomatau** [comment]
Same - just using the JS API instead of data-attributes and all is fine.

**Comment by Rrrapture** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Hey looks like this issue is out of date. If anyone is still having issues feel free to holler back. Thanks!
