### ISSUE TITLE
Stop Right

### ISSUE THREAD

**Issue by caioavila-arvore** [kenwheeler/slick#1182]
http://jsfiddle.net/zkpwqcqh/
width:100%;
slidesToScroll: 1

Is there anychance to create a rightMode? I don’t want empty spaces after the last item. Thanks!

**Comment by petebarr** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Hey looks like the fiddle is out of date. Im going to close this but if you want to circle back with a fresh test case, please feel free. Thanks!
