### ISSUE TITLE
Uneven sets don't slide with dot navigation

### ISSUE THREAD

**Issue by emRae** [kenwheeler/slick#1183]
<a href="http://www.jqueryscript.net/demo/Fully-Responsive-Flexible-jQuery-Carousel-Plugin-slick/" target="_blank"> Like this older demo</a> , I'd like to be able to have an uneven number of slides and the dot navigation still slide to the next sets.

The old demo is using version 1.0 of slick.js. <b>Any idea what has changed between 1.0 and 1.5 to make the dot navigation no longer work for uneven slides?</b>

Here is a JS Fiddle showing what I mean: https://jsfiddle.net/englerae/yapyLgsx/

**Comment by al-v-in** [comment]
Hi @emRae, that JS Fiddle isn't quite working because it is https - changing to http works fine.

Just as an aside: I think the issue causing this is the same thing that may be causing this: https://github.com/kenwheeler/slick/issues/1153

**Comment by leggomuhgreggo** [comment]
Looks like this got fixed in the maser at some point. Closing. Thanks!
