### ISSUE TITLE
Reinit slider when leaving a breakpoint with settings: 'unslick'

### ISSUE THREAD

**Issue by alexej-d** [kenwheeler/slick#1190]
Hey there,
really love your plugin, I use it in nearly every project – thanks for the great work.
I observed a counter-intuitive behaviour with the following init code:

		var slickBaseSettings = {
			infinite: false,
			slide: '.is-slide',
			adaptiveHeight: true,
			dots: false,
			slidesToShow: 4, 
			arrows: true
		};
		$('.is-slider').slick( $.extend({
			responsive: [{
				breakpoint: 640,
				settings: 'unslick'
			}]
		}, slickBaseSettings) );

One would expect that once leaving the breakpoint the slider reinitializes but it is not the case. Am I missing something?

**Comment by aldidas** [comment]
In my recent project, I was facing this issue and ended up to assign the slick() initialization inside another function. So we can listen to jQuery's $(window).resize(), and re-init the slick when the window's width reach the breakpoint. Here is my code :
```
    // function and variables, 'unslick' while window size reach maximum width (641px)
    var maxWidth = 641,
      slickVar = {
        lazyLoad: 'ondemand',
        dots: false,
        infinite: false,
        slidesToShow: 2,
        slidesToScroll: 1,
        mobileFirst: true,
        responsive: [
          {
            breakpoint: maxWidth,
            settings: 'unslick'
          }
        ]
      },
      runSlick = function() {
        $('#front-products').slick(slickVar);
        $('#front-recipes').slick(slickVar);
        $('#front-gallery').slick(slickVar);
        $('#front-blog').slick(slickVar);
      };

      // slick initialization while document ready
      runSlick();

      // listen to jQuery's window resize
      $(window).on('resize', function(){
        var width = $(window).width();
        if(width < maxWidth) {
          // reinit slick while window's width is less than maximum width (641px)
          runSlick();
        }
      });
```
Suggestions open for any better solution :)

**Comment by simeydotme** [comment]
It's _dubiously_ documented here: https://github.com/kenwheeler/slick/releases/tag/1.4.0 - No current plans to change this. Better to use the `window.resize` event if you plan on removing carousels :)

**Comment by andreasvirkus** [comment]
For anyone finding @aldidas's solution useful, Slick now also comes with a `breakpoint` event, which is less taxing than listening for every resize.

**Comment by stevegrunwell** [comment]
For those who stumble across this issue through Google, [I did a writeup on my company's blog demonstrating how to cleanly re-initialize Slick carousel in a responsive setting](https://engineering.growella.com/reinit-slick-carousel/), after destroying it via `unslick`.

Hopefully this helps someone else :)

**Comment by Grawl** [comment]
my dirty try on this:

```js
function slick() {
	$('[data-slick]').each(function(index, element) {
		if($(element).hasClass('slick-initialized')) return
		$(element).slick()
	})
}
if(window.innerWidth > 640) {
	slick()
}
$(window).on('resize', function(event) {
	console.log(event)
	if(event.target.innerWidth > 640) {
		slick()
	}
	else {
		$('[data-slick]').slick('unslick')
	}
})
```

**Comment by romannikiforov** [comment]
https://github.com/kenwheeler/slick/issues/2123#issuecomment-445291254

**Comment by romannikiforov** [comment]
```javascript
const settings = {
     // default settings
    responsive: [
        {
            breakpoint: 900,
            settings: { slidesToShow: 3 }
        },
        {
            breakpoint: 600,
            settings: { slidesToShow: 2 }
        },
        {
            breakpoint: 420,
            settings: "unslick"
        }
    ]
};

const sl =  $('.slider').slick(settings);
      
$(window).on('resize', function() {
   if( $(window).width() > 420 &&  !sl.hasClass('slick-initialized')) {
         $('.slider').slick(settings);
    }
});
```

**Comment by CornerstoneII** [comment]
> For those who stumble across this issue through Google, [I did a writeup on my company's blog demonstrating how to cleanly re-initialize Slick carousel in a responsive setting](https://engineering.growella.com/reinit-slick-carousel/), after destroying it via `unslick`.
> 
> Hopefully this helps someone else :)

Error on this page

**Comment by stevegrunwell** [comment]
Oh no! I left the company several years ago, they must have taken down the engineering blog 😢. I'll reach out to the CEO and see if it can get reinstated (or if I can get copies of the posts to put elsewhere).

Thanks for the heads up!

**Comment by dalaranunion** [comment]
Heya I was looking for a solution to this and I thought I should paste one here.

Assuming you 'unslick' slideshow(s) because you would like to save browser resources and then "slick" them once the size of the window increases, I think 'resize' events should be throttled. But anyway here is a nasty implementation.

```
$(function () {
  // This variable is used later
  let unslicked;

  // Wrap the the slideshow creation in a function
  function runSlick() {
    $(".slideshows").slick({
      dots: true,
      arrows: true,
      infinite: false,
      speed: 300,
      slidesToShow: 3,
      slidesToScroll: 3,
      responsive: [
        {
          breakpoint: 550,
          settings: "unslick",
        },
      ],
    });
    // Set the unslicked into false: meaning, slideshows are not unslicked
    unslicked = false;
  }
  // Create slideshow(s) on dom ready
  runSlick();

  // Create a function which handle things after the slideshows are unslicked
  function afterUnslick() {
    // if the slideshows are unslicked then run the script
    if (unslicked === false) {
      // Immediately set this to true to avoid the function run more than once
      // Because ON 'breakpoint' event triggers per slideshows in HTML document like:
      // if one slick slideshow then breakpoint will fire once
      // if two or more slick slideshows then breakpoint will fire twice or more
      unslicked = true;

      // The Script bellow is similar to a scroll throttle
      let resizing = false;
      function isResizing() {
        resizing = true;
      }
      // Add event listener for browser resize
      window.addEventListener("resize", isResizing);

      // Set interval to throttle resize events
      const intervalScript = setInterval(function () {
        if (resizing) {
          resizing = false;
          // Run Code
          if (window.innerWidth >= 550) {
            runSlick();
            window.removeEventListener("resize", isResizing);
            clearInterval(intervalScript);
          }
        }
      }, 1000);
    }
  }

  // When a Slideshow will hit a "breakpoint" then "breakpoint" event will fire
  $(document).on("breakpoint", function (event, slick, breakpoint) {
    // If the breakpoint is 550 - the one we unslick the slidshow then run the after unslick
    if (breakpoint == "550") afterUnslick();
  });
});
```
