### ISSUE TITLE
Last slide not available by slidesToScroll: 3 with 7 slides

### ISSUE THREAD

**Issue by Worstkaes** [kenwheeler/slick#1194]
Hey guys,

I'm trying to implement a slick-slider with the options slidesToShow: 3 and slidesToScroll: 3 with 7 slides. Now the last slide is only available by pushing the "next-button", which is not available at my slider or by swiping the slider. 
It would be nice, if the seventh slide would get an extra navigation-dot and after clicking the slider only slides one slide. 
Has anyone an idea for implementing this?

Here my fiddle for this:
http://jsfiddle.net/00u43mLn/1/

**Comment by gyduxa** [comment]
If you use variableWidth: true and define the same width on CSS you can see the last element
http://jsfiddle.net/00u43mLn/3/
Not sure if you want to use widths in the CSS.

**Comment by leggomuhgreggo** [comment]
Looks like this got fixed at some point in the master. [Here's a fork demoing](http://jsfiddle.net/leggomuhgreggo/5r1qxzn4/). Apologies for the dormancy. Thanks!
