### ISSUE TITLE
'slick-active' and 'slick-center' not applied on page load?

### ISSUE THREAD

**Issue by Accomp** [kenwheeler/slick#1198]
Using 'centerMode', nested inside another carousel, it appears that the 'slick-active' and 'slick-center' classes are not being applied on page load. They are applied after you interact with the carousel (next/previous), but non-existent on page load.

Anyone have a quick work around for this or a confirmed fix? Unable to find any documentation on this particular issue, as it's an unusual case. Thank you.

**Comment by Accomp** [comment]
Created a workaround in the mean time. Using Slick to handle steps in a wizard, also had a carousel inside of one of the steps. Was about to run '$('.list--cards').slick('slickGoTo', 0);' on one of the slide transitions to push to first step after it had been initialized. Not a fix, but a patch that will suffice for now.

**Comment by leggomuhgreggo** [comment]
Real quick: when reporting issues, whip up some kind of a fiddle, por favor

[I made this one](http://codepen.io/gwst/pen/wBVGEM), which I think is what you're describing, but it looks like the classes are getting applied.

**Comment by pixHel512** [comment]
Hello, i've got the same problem here.

the codepen from leggomuhgreggo is good to show the problem: 
http://codepen.io/gwst/pen/wBVGEM 

The red border applied on elemetn with class slick-center, that's logical but in fact that's not ok every time. 

3 case :
- number of element > number to display
=> ok border on selected element

- number of element < number to display
=> ok border on selected element

- number of element = number to display
=> NOK. every element except the one we need has the center class. so every element except the one we need are in red -_-

Have a trick to fix that ?

**Comment by Nesvet** [comment]
Got the same trouble. Any ideas?

**Comment by leggomuhgreggo** [comment]
Ahh this is about the slidesToShow >= slideCount. Several other threads on it so Im going to close this. Thanks!
