### ISSUE TITLE
Autoplay Dots

### ISSUE THREAD

**Issue by MichaelBarb** [kenwheeler/slick#1203]
If you select a dot it goes dark and the selected slide appears all just as it should.  When the slide loses focus and the Autoplay resumes the black dot on the selected display stays behind.  I think this is a bug.

Kind of funky but not a bug is that once selected and the dots still have focus that the autoplay continues to run.  I would think as long as the dots still have hover the autoplay would be paused kind of like hover on a slide.  To be clear hover pause would only be in effect after the dots are selected.  Hover before selection would not cause a pause.

**Comment by kenwheeler** [comment]
Thats the focus styling. You can override that with css.
