### ISSUE TITLE
custom pagination not work 1.5

### ISSUE THREAD

**Issue by cansozeri** [kenwheeler/slick#1204]
After updated to 1.5 my custom paging is not working anymore. What has changed ?? 

It is working with 1.4.

Here is my settings.

```
$('#slider_main').slick({
    slide: '.slider_img',
    arrows: false,
    dots: true,
    autoplay: true,
    autoplaySpeed: 5000,
    appendDots: '#slider_main .slider_pagination',
    customPaging: function(slider, i) {
        return '<a href="javascript:void(0)">' + (i + 1) + '</a>';
    }
});
```

You can see here http://jsfiddle.net/2mmcqc2m/13/

pagination div should not be loaded as a slide.... Because it has not got "slider_img" class..

I have found it, I don't know why but on this function ".options.slide" has removed, so slide option is not working. 

```
//current one

_.$slides = _.$slider.children(
            ':not(.slick-cloned)').addClass(
            'slick-slide');

//It should be

 _.$slides = _.$slider.children(_.options.slide +
            ':not(.slick-cloned)').addClass(
            'slick-slide');
```

**Comment by leggomuhgreggo** [comment]
Looks like this is out of date, and I think it's been fixed. Apologies for the dormancy. Thanks
