### ISSUE TITLE
Text overlapping on Fade transitions.

### ISSUE THREAD

**Issue by deepaksbutola** [kenwheeler/slick#1205]
Hi,
I am making a carousel for a ticker which contains some text. But When I try to add fading effect to that carousel, text get overlap on fade transition.So Can You please help me to make it run smoothly or is there any way that I can delay the fade in until that slide fade out.

http://jsfiddle.net/deepaksbutola/mt4jdy6o/

**Comment by simeydotme** [comment]
http://jsfiddle.net/mt4jdy6o/1/ :)

**Comment by deepaksbutola** [comment]
Hey thanks @simeydotme , it works fine for me.

**Comment by ConneXNL** [comment]
What if you don't have a background?

I recently upgraded slick and now I can't get the animations to run smooth for text without a background.

**Comment by shivansp** [comment]
Hello,
Can anyone tell me why fade affect  is not working for this code,
wen i try the fade:true; its showing only one item and wen i remove fade:true; its showing two items.
i want items to fade and display at a time but its changing to one item wen i include fade:true;
can anyone help me with this


http://jsfiddle.net/mt4jdy6o/5/
