### ISSUE TITLE
Grid Mode + asNavFor not working

### ISSUE THREAD

**Issue by compunode** [kenwheeler/slick#1206]
The grid option is a real welcome change considering that just yesterday I was trying to hack together something for grid support.

My use-case is that instead of having a slides as a navFor parent, I would prefer to have a grid instead. This makes sense, since all thumbnails are immediately visible, doesn't require any finger gymnastics (swiping or prev/next arrows), tracking slider context, grokking infinite cycling logic, etc. So usability wise, grids are great for navigating the parent slideshow.

However, I think it's either buggy or I may be missing something. Fiddle is at http://jsfiddle.net/pxLksn8c/

```
<div class="slick  slider-parent" data-slick='{"arrows": false}'>
    <img src="http://placehold.it/350x150&text=1" />
    <img src="http://placehold.it/350x150&text=2" />
    <img src="http://placehold.it/350x150&text=3" />
    <img src="http://placehold.it/350x150&text=4" />
    <img src="http://placehold.it/350x150&text=5" />
    <img src="http://placehold.it/350x150&text=6" />
</div>

<div class="slick green" data-slick='{"slidesPerRow": 3, "rows":2, "focusOnSelect": true, "asNavFor": ".slider-parent"}'>
    <img src="http://placehold.it/350x150&text=1" />
    <img src="http://placehold.it/350x150&text=2" />
    <img src="http://placehold.it/350x150&text=3" />
    <img src="http://placehold.it/350x150&text=4" />
    <img src="http://placehold.it/350x150&text=5" />
    <img src="http://placehold.it/350x150&text=6" />
</div>
```

**Comment by compunode** [comment]
For what it's worth, prior to the grid support, I was attempting to hack this together (yesterday) as according to the fiddle at http://jsfiddle.net/0Lq6v8ph/

You'll notice that it works for clicking slides 1, 5, 6. Clicking 2, 3, 4 throws off the grid. I am not sure how it is implemented in the latest release but this solution isn't too far off either. All that would be needed to fix it would be to disable the grid from moving around via a simple JS option.

**Comment by simeydotme** [comment]
I think you've misunderstood the use-case for Grids :)
The Grids mode is just a way of laying out slides inside the parent container, it doesn't create a connection as you desire because the second slider "technically" has only 1 slide. And because it is only 1 slide it's "asForNav" sets it to the first slide on the first slider.

I think you just need to write your own jQuery to add a click-handler to each image in that slider :)

http://jsfiddle.net/pxLksn8c/2/

There you go :)

**Comment by compunode** [comment]
Ah, misunderstood that. I will add that a grid nav has awesome usability for desktop compared to a slider nav.

Feel free to close this if full-on grid support is not on the cards in the future.
