### ISSUE TITLE
Infinite autoplay stops after some time

### ISSUE THREAD

**Issue by dimir** [kenwheeler/slick#1208]
I'm using infinite autoplay of about 7 slides, one slide per view, 5 seconds delay. Each slide is just a jpg image. When page is loaded autoplay starts automatically. I leave the page open in my browser tab. But then after few minutes (or hours) I get back to the page to discover that autoplay has stopped. Would there be any hints on how to debug this problem, where could it be coming from?

Tried in different browsers (Firefox, Chrome). I'm using slick 1.3.15 with next settings:

    <head>
    <link rel="stylesheet" type="text/css" href="css/slick.css"/>
    [...]
    </head>
    <body>
    <div class="show-class">
    <div><img ...></div>
    </div>
    <script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="js/slick.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
                var delay = 5000;
                $('.show-class').slick({
                        infinite: true,
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        autoplay: true,
                        autoplaySpeed: delay,
                        speed: 1000
                });
        });
    </script>
    </body>
    [...]

**Comment by simeydotme** [comment]
Can you produce a JSFiddle and describe exactly how to reproduce this issue? :smile: 
I have a feeling it's related to the `pageVisibility` feature, but need you to help me out here with some real information :)

**Comment by dimir** [comment]
I think the problem was the pauseOnHover setting which by default is enabled. I have disabled it and so far so good. Will see if that completely solves the problem.

**Comment by simeydotme** [comment]
but @dimir the slides should continue to rotate after you hover-out the slider...

**Comment by dimir** [comment]
Yep, seems it was because pauseOnHover was enabled. We disabled it and it works perfectly now. Thing is we are running browser in full-screen mode without mouse in production, so we definitely do not need no pause.

Closing the issue, thanks!

**Comment by simeydotme** [comment]
riiiiight.
"FullScreen" ... that would mean the mouse-pointer is ALWAYS hovering the slider? ;D

**Comment by dimir** [comment]
I guess so. :-D

**Comment by wallgravve** [comment]
i have quite similar problem, when i switch on other bookmark, slick slider stop running.
