### ISSUE TITLE
Disable click event while dragging

### ISSUE THREAD

**Issue by kreker92** [kenwheeler/slick#1210]
When I drag slider and mouse staying on slide where I was on start call click event
Slider looks like:
div
button onclick="alert('1')">1/button
button onclick="alert('2')">2/button
/div

options:
infinite: false,
slidesToShow: 2,
variableWidth: true,
arrows: false

**Comment by Skinwalker** [comment]
same problem here - using lastest version 1.5.8

**Comment by simeydotme** [comment]
please read the contribution guideliens and provide a JSFIddle with instructions on how to recreate and expected behaviour, and we can investigate. Thanks; Simon.

**Comment by joshmoto** [comment]
Here is an example. When I try and drag, it launches my light gallery. https://jsfiddle.net/joshmoto/u5mh3a8x/

**Comment by Nincha** [comment]
Also interrested in a solution for this ; unlike @joshmoto I'm not triggering a gallery but I'm using links on the whole slide area, so it's triggering accidental navigations. :)

**Comment by fslone** [comment]
Can confirm this is still happening, and the issue is shown in the Fiddle from @joshmoto. When a user drags a carousel item with a link, the click event is fired on mouse up. This doesn't happen while panning on touchscreen devices.

Can you reopen this @simeydotme?

**Comment by Nincha** [comment]
> Can confirm this is still happening, and the issue is shown in the Fiddle from @joshmoto. When a user drags a carousel item with a link, the click event is fired on mouse up. This doesn't happen while panning on touchscreen devices.
> 
> Can you reopen this @simeydotme?

Hi! Just in case that can help, I solved the problem that way on my side:
```
      $('body').on('mousedown', '.slick-slide', function(e){

          $(this).one('mousemove', function(e){
            that.navBlocked = true;

            $('body').one('mouseup', function(e){
              setTimeout(()=>{
                that.navBlocked = false;
              },1);
            });
          });
      });
```

Not ideal, but you sure can adapt it to your project until it's fixed. :)

**Comment by fslone** [comment]
@Nincha thanks for the response, I'll try to figure out how to adapt that for Angular.

**Comment by fslone** [comment]
Also just to note the severity and reach of this bug, the Disney+ site is using Slick for their swimlanes with this bug present, so dragging with a mouse is broken on their entire site.

**Comment by rastapopougros** [comment]
This issue is closed but not solved at all (but herr… 1200 issues).

Anyway I can't make the @Nincha code work for me sadly… if anyone has another workaround.
