### ISSUE TITLE
Navigation buttons (dots and arrows) no longer work in Chrome 44.0.2358.0 canary

### ISSUE THREAD

**Issue by motopete** [kenwheeler/slick#1211]
Can replicate by testing the sliders on http://kenwheeler.github.io/slick/ using Chrome 44.0.2358.0 canary.

**Comment by eakroko** [comment]
+1 same here

**Comment by leggomuhgreggo** [comment]
I don't see the issue in most recent canary 44.0.2362.0

**Comment by motopete** [comment]
Confirmed, it works with latest canary 44.0.2362.0.
