### ISSUE TITLE
Stripping out ids on cloned slides causes problems when using video on carousels

### ISSUE THREAD

**Issue by tslatt** [kenwheeler/slick#1212]
Currently, ids are stripped from everything inside a cloned slide, which makes some sense, because ids must be unique. (See https://github.com/kenwheeler/slick/issues/116). 

This seems to be ok for slideshows, since once a cloned slide is slid to, the slider shifts so it immediately gets replaced by its 'real' version, where anything triggered by ids is still functional. However, for carousels that show more than one object at a time, when you are toward the end of the carousel, you see the clones on screen, and they are not immediately replaced.

I have videos in the slides that use JWPlayer and require an id. With the ids stripped, videos in the cloned slides do not work. Since its in a carousel, users can see the broken video players on screen until they scroll far enough that the carousel shifts back to start.

I've tried to change slick.js to not strip the ids, but to just append the word 'clone' to the id, so it stays unique, but I must be doing something wrong because it keeps breaking.

**Can someone tell me how to change the script slick.js to not strip the ids, but to just append text to them to make them unique?**

Any assistance would be greatly appreciated.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1791-L1806
Edit these lines to replace with your desired ID :)

**Comment by simeydotme** [comment]
__on lines 1794 & 1800__
```js
$(_.$slides[slideIndex]).clone(true).attr('id', '')
```
change to:
```js
$(_.$slides[slideIndex]).clone(true).attr('id', $(_.$slides[slideIndex]).attr('id') + slideIndex )
```
===  
  
===  
__on lines 1804-1806 change:__
```js
_.$slideTrack.find('.slick-cloned').find('[id]').each(function() {
    $(this).attr('id', '');
});
```
to:
```js
_.$slideTrack.find('.slick-cloned').find('[id]').each(function(k) {
    $(this).attr('id', $(this).attr('id') + k);
});
```

**Comment by tslatt** [comment]
Thanks!

**Comment by elalemanyo** [comment]
Can you show me how you use jwplayer inside the slick slider? i am having some problems...

Thanks

**Comment by kevinlg** [comment]
I had the same problem to put reviews coming from a Shopify theme into a carrousel. The fix mentioned by worked for it as well.

**Comment by stevejwojcik** [comment]
Why not have a poster frame image with baked in play button on top of each video and once clicked it hides and plays the video? This way the image is always available in the carousel and you're not messing around with source code.

**Comment by drewbeta** [comment]
I came across this issue. I'm using Scene7 video player in Slick, which requires ids. I tried to modify the lines of code to modify ids on clones, and that worked initially, but if you resize the browser slick modifies the ids again.
