### ISSUE TITLE
Autoplay Dots stuck in the active opacity setting on Chrome after you click it

### ISSUE THREAD

**Issue by TechFounder** [kenwheeler/slick#1213]
Hi, I don't know what the exact problem is, but on chrome the dots will stay stuck on active opacity after you click on it. Here's fiddle that reproduces the problem. Click on any dot and when it autoplays, you can see that it's stuck. This doesn't seem to occur on Safari.

http://jsfiddle.net/N6wfG/111/

**Comment by kyleatfine** [comment]
Saw this problem today with 1.5.7

**Comment by kenwheeler** [comment]
thats the focus css class

**Comment by kyleatfine** [comment]
Was just about to update with that same answer. Perhaps focus should have a different style than the active slide in the default theme.

**Comment by simeydotme** [comment]
noted for 2.0, @kyleatfine  :+1:
