### ISSUE TITLE
Need to append data from ajax to end of slider when click on right arrow

### ISSUE THREAD

**Issue by mpkumar87** [kenwheeler/slick#1216]
Hi,
Need to append data from ajax to end of slider when click on right arrow with no more content to show.
I used like this,
$('.responsive-slider').on('beforeChange', function(event, slick, currentSlide, nextSlide){
$('.responsive-slider').slick('slickAdd','ajax content');
});

But, it also trigger when click on left arrow. Please guide me to solve this issue.

**Comment by mpkumar87** [comment]
Hi,
Any reply for my previous comment.. Pls guide me to solve the above issue..

Thanks,
Premkumar

**Comment by simeydotme** [comment]
@mpkumar87, I'm sorry to say this, but it is a simple logic issue on your part. The `beforeChange` event correctly triggers any time the slider should change slide. It is up to you to figure out your specific logic for your specific scenario to satisfy your project brief.

A good place to start your thought process is that if you're going `right` then the next slide should have a higher `index` than the previous slide (unless it's an infinite slider and on the last slide). 

Hope that helps, and good luck!
Simon.
