### ISSUE TITLE
The 'init' event isn't firing

### ISSUE THREAD

**Issue by al-v-in** [kenwheeler/slick#1218]
See http://jsfiddle.net/al_v_in/nemh9nzk/36/ 

Some events are working fine (eg the 'beforeChange'), but 'init' doesn't seem to be working

**Comment by gausarts** [comment]
You may want to place it before slick as the doc says "Use them before the initialization of slick":
http://jsfiddle.net/nemh9nzk/37/

**Comment by simeydotme** [comment]
THanks, @gausarts

**Comment by al-v-in** [comment]
Ahh right, thanks a lot. I was going off the docs here: http://kenwheeler.github.io/slick/ that don't seem to say that.

**Comment by lexbi** [comment]
Yup docs do not say that.

Also what if you want to fire the same function for both events? I can't really get dynamic stuff before slick is called in my current situation...
