### ISSUE TITLE
Feature Request: Mouse wheel support

### ISSUE THREAD

**Issue by dubcanada** [kenwheeler/slick#122]
It would be awesome if we would get mouse wheel support, so you can mouse over the element and scroll with the mouse wheel.

**Comment by sajanmullappally** [comment]
For 1.5.9 version
Include https://github.com/jquery/jquery-mousewheel

var myCarousel= $('#myDiv');

      myCarousel.slick({
       /*Options Here*/
      });

      myCarousel.mousewheel(function(e) {
        e.preventDefault();

        if (e.deltaY < 0) {
          $(this).slick('slickNext');
        }
        else {
          $(this).slick('slickPrev');
        }
      });

**Comment by Ansif** [comment]
@sajanmullappally Super! :+1:

**Comment by chiraggmodi** [comment]
I have applied above solution for mousewheel and it working nicely, but the issue i am facing is, when slider reach to last slide, it is not scroll page to down, so there is no way to scroll down from slider. 
I have kept option to infinite:false and if i put this to true it goes to 1 slide.

Any help will be appreciated.

**Comment by simeydotme** [comment]
@sajanmullappally can you help @chiraggmodi out, just do a check for `infinite` , if true, and `currentSlide === slideCount` then don't prevent default (also opposite for scrolling up)

**Comment by chiraggmodi** [comment]
@simeydotme  this is code where currently i am working on

```
var slickCarousel= $('.serviceSlider');
    slickCarousel.slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        fade: true,
        autoplay: false,
        dots:true,
        infinite:false,
        adaptiveHeight: true,
    });
    

    slickCarousel.mousewheel(function(e) {
e.preventDefault();
        if (e.deltaY < 0) {
            $(this).slick('slickNext'); 
        }
        else {
            $(this).slick('slickPrev');
        }
    });
```

**Comment by oktav777** [comment]
A bit changed the code from top, will scroll up/down when reaching first/last slide.  

Settings: 
```javascript
$('.your-slick').slick({
  infinite: false,
  vertical: true
})
```
Code: 
```javascript
$('.your-slick').mousewheel(function(e) {
  if (e.deltaY < 0) {
    if($(this).slick('slickCurrentSlide') == $(this).find('.slide').length - 1) {
      return
    }

    e.preventDefault()
    $(this).slick('slickNext')
  } else {
    if($(this).slick('slickCurrentSlide') == 0) {
      return
    }
    
    e.preventDefault()
    $(this).slick('slickPrev')
  }
});
```

**Comment by Grawl** [comment]
`slick.mousewheel()` is not available anymore. Any workarounds?

**Comment by Grawl** [comment]
Okay I just find [an answer](https://stackoverflow.com/a/32757060/766307) on StackOverflow that allows me to change slides on “desktop” mouse “wheel” scrolling (currently my MacBook trackpad).

Here's a working demo using fresh Slick: https://codepen.io/Grawl/pen/mMLQQb

**Comment by Grawl** [comment]
@kenwheeler why not to include this as an option?

**Comment by GregJacoby** [comment]
@oktav777 hi Octavian, thanks so much for your code there. It works perfectly except when getting to the bottom it stops and doesn't scroll past that - I've been playing with it a bit and can't seem to get it to work. any ideas?

**Comment by vitorluis** [comment]
You can use it without mousewheel plugin.
https://stackoverflow.com/questions/46508975/how-to-use-mouse-scroll-instead-of-drag-in-slick-js

**Comment by alexromeo** [comment]
I've added some lines to @oktav777 code in order to continue scrolling up/down only once the first/last slide has finished its animation. I think it feels more comfortable to the user.

```javascript
let swiping = false;

$('.your-slick').on('beforeChange', function(){
    swiping = true;
});

$('.your-slick').on('afterChange', function(){
    swiping = false;
});

$('.your-slick').mousewheel(function(e) {
  if (e.deltaY < 0) {
    if($(this).slick('slickCurrentSlide') == $(this).find('.slick-slide').length - 1 && !swiping) {
      return
    }

    e.preventDefault()
    $(this).slick('slickNext')
  } else {
    if($(this).slick('slickCurrentSlide') == 0 && !swiping) {
      return
    }
    
    e.preventDefault()
    $(this).slick('slickPrev')
  }
});
```
