### ISSUE TITLE
Autoplay not working on load

### ISSUE THREAD

**Issue by felipeandres254** [kenwheeler/slick#1220]
Hi,

I want the <i>autoplay</i> option to start on page load but is not working. It works only when I interact with the Slick and when I change tabs.
This is my options object:
```javascript
var options = {
  autoplay:true,
  autoplaySpeed:1500,
  arrows:true,
  prevArrow:'<button type="button" class="slick-prev"></button>',
  nextArrow:'<button type="button" class="slick-next"></button>',
  centerMode:true,
  slidesToShow:3,
  slidesToScroll:1
}
```

**Comment by simeydotme** [comment]
Could you please create a JSFiddle to help us debug? :)

**Comment by ethanclevenger91** [comment]
Seconded - see http://freakyfreshmarketing.com/

Top slider

**Comment by leggomuhgreggo** [comment]
@ethanclevenger91 @felipeandres254 it's really helpful to make an actual fiddle of some sort when reporting an issue.

I went ahead and whipped one up [here](http://codepen.io/gwst/pen/dPxMbm) and it seems to be auto playing.

**Comment by ethanclevenger91** [comment]
@leggomuhgreggo Thanks for that, really should have taken the time myself.

Needed to put the call into `onload` instead of just `ready` - I don't remember this being an issue before, but understandable. Seems to be freezing if I'm hopping between tabs, but I can't currently replicate it in a fiddle, so I'll follow up if it's really an issue. Thanks for your time.

**Comment by simeydotme** [comment]
pausing the slider on tab/browser change is intended functionality :) - if the user cannot see the slider they do not want it running... also it causes a big problem with queued animations upon coming back to the tab :)

**Comment by ethanclevenger91** [comment]
I should have been more clear - it thought it was staying frozen when I came back. Of course, this morning, either I was crazy yesterday or it's behaving differently, but I have managed to get a fiddle together that demonstrates my issue: http://codepen.io/ethanclevenger91/pen/MYNGrN

If you hover over the current slide, it freezes as expected, but when you hover out, it doesn't resume.

**Comment by sbn111** [comment]
Autoplay not working after changed by clicking th arrows
'
