### ISSUE TITLE
afterChange function always fires even when you havent changed slide

### ISSUE THREAD

**Issue by saunders1989** [kenwheeler/slick#1223]
Hi,

I really like your plugin but I can't seem to find a fix / work around for the issue I am having. When I create a slider and have the event afterChange setup, if you drag the slider slightly in either direction but don't actually change slide the event fires when i only expect this event to fire once the slide has changed.

Is there a way to only fire this event when the slide has finished its transition?

I have setup a jsfiddle  - https://jsfiddle.net/427f9uLk/ to show you what i mean.

thanks

**Comment by leggomuhgreggo** [comment]
Interesting quirk.

There might be a better way, but if you make a var and define it as being the beforeChange method's currentSlide, you can compare to the afterChange method's current slide to test to see if there's been an actual slide change. 

Here's a fiddle: https://jsfiddle.net/427f9uLk/3/

**Comment by saunders1989** [comment]
Hi,

Thanks for getting back and giving me a work around which works :+1: Will there be a fix in the code behind?

**Comment by leggomuhgreggo** [comment]
Happy to help! I can't speak to any code fixes, though; I'm just a citizen

**Comment by kenwheeler** [comment]
Looking into this

**Comment by saunders1989** [comment]
@kenwheeler nice one :+1:

**Comment by leggomuhgreggo** [comment]
Making #2294 the tracking issue. Closing. Thanks
