### ISSUE TITLE
Autoplay interval (between each slide)

### ISSUE THREAD

**Issue by SiamKreative** [kenwheeler/slick#1226]
Hi there,

Slick quickly became my favorite slider / carousel because it's flexible, light and well coded/maintained. But... I went through the documentation and Github issues and I can't find the option to set the time interval between each slide.

The `autoplaySpeed` seems to be the time before the slider starts. The `speed` option is the transition time (slide / fade). But how to set the time interval between each slide, for instance **3 seconds**?

Please let me know :+1:

**Comment by funkybudda** [comment]
similar to this question, if it's possible to set time interval in between slides, is it possible to set unique values from slide to slide?

**Comment by simeydotme** [comment]
Here, try this :)
http://jsfiddle.net/dkj3hrqk/1/ 
(the time is not 3 seconds here, its set super fast to show you you can change the speed.)

Simon.
