### ISSUE TITLE
Feature: Timer to show remaining time before next slide

### ISSUE THREAD

**Issue by numediaweb** [kenwheeler/slick#1228]
It would be a nice addition if we have a timer that shows how many time is left before next slide. An example would be something like in: [Orbit by Zurb Foundation](http://foundation.zurb.com/docs/components/orbit.html) or in [Revo Slider](http://revolution.themepunch.com/)

**Comment by eballeste** [comment]
why was this closed?

**Comment by kangabell** [comment]
@simeydotme why was this closed? Is there a resolution for it somewhere? please link!
