### ISSUE TITLE
Get current swipeLength and swipeDirection

### ISSUE THREAD

**Issue by stuarteaton** [kenwheeler/slick#1229]
Is there any way to get the current swipeLength and direction as the user is dragging?

I have tried variations on:

```javascript
$('#scroll-area').on('swipeMove', function(event, slick, swipeDirection, swipeLength){
  console.log('swipeDirection: '+swipeDirection);
  console.log('swipeLength: '+swipeLength);
});
```

But no joy. I can add console.log's into the slick.js file. Ideally I need some kind of event listener to get the values whenever the carousel is being dragged.

Any ideas? Please excuse my lack of programming knowledge here!

**Comment by stuarteaton** [comment]
Following on from this...
Is there any way to control one slick from another? I am aware of `asNavFor` but i have 3 slicks that i would like to sync with each other (change one and the other 2 change) and anyway what I am after is this: As you drag one slick the other move at the same time (rather than just updating when the dragging stops).

I currently have it working using something like this:

```javascript
 $('#scroll-area').on('beforeChange', function(event, slick, currentSlide, nextSlide){
    $('#top-scroll-area').slick('slickGoTo',nextSlide);
    $('#header-nav').slick('slickGoTo',nextSlide);
  });

  $('#top-scroll-area').on('beforeChange', function(event, slick, currentSlide, nextSlide){
    $('#croll-area').slick('slickGoTo',nextSlide);
    $('#header-nav').slick('slickGoTo',nextSlide);
  });

  $('#header-nav').on('beforeChange', function(event, slick, currentSlide, nextSlide){
    $('#top-scroll-area').slick('slickGoTo',nextSlide);
    $('#scroll-area').slick('slickGoTo',nextSlide);
  });
```

Change one and the other 2 update but not all at the same time, only after the dragged Slick updates. If you see what i mean!?

**Comment by simeydotme** [comment]
Why not try using a grid-slider (grid options), if they are always synced then really you just have 3 slides stacked (or a grid) sliding ? :)

**Comment by simeydotme** [comment]
Why not try using a grid-slider (grid options), if they are always synced then really you just have 3 slides stacked (or a grid) sliding ? :)

**Comment by stuarteaton** [comment]
Aye. That’s an option but I could really do with getting the swipeLength value - Some other things I want to use that value for as the user moves the carousel.

**Comment by simeydotme** [comment]
You'll have to write your own swipe-detection, to handle this, I'm afraid. :)
Simon.
