### ISSUE TITLE
Callback onAfterChange not being called?

### ISSUE THREAD

**Issue by pgtaboada** [kenwheeler/slick#1231]
I moved to version 1.5.0 and my code stopped working.

https://jsfiddle.net/yutqqexo/

Any ideas?

**Comment by leggomuhgreggo** [comment]
https://github.com/kenwheeler/slick/releases/tag/1.4.0

Read about the methods

**Comment by pgtaboada** [comment]
Thanks. 
Sure that this applies to "init" as well?

**Comment by pgtaboada** [comment]
Thanks - I have overseen the 1.4 changes...
