### ISSUE TITLE
Slideshow restarts whenever i leave the window and come back.

### ISSUE THREAD

**Issue by matgargano** [kenwheeler/slick#1233]
It appears that this code is forcing the slideshow to restart if I toggle to another window and come back - is this something that can be controlled? I spent about an hour looking into this to no avail.

```
    Slick.prototype.visibility = function() {

        var _ = this;

        if( document[ _.hidden ] ) {
            _.paused = true;
            _.autoPlayClear();
        } else {
            _.paused = false;
            _.autoPlay();
        }

    };
```

**Comment by kenwheeler** [comment]
@simeydotme ?

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/pull/1133 :)
This is because the initial option sets the bindings, instead of checking the current option upon trigger :) - the PR can still be auto-merged.

Apologies.

**Comment by kenwheeler** [comment]
@Simeydotme is it merged?

**Comment by simeydotme** [comment]
nah bro, I didn't want to tread on your toes... so gonna leave the merging to you :)

**Comment by kenwheeler** [comment]
@Simeydotme you have God mode, strike the lighting homie

**Comment by simeydotme** [comment]
:zap::sparkles:  KERCHOW!! :sparkles::zap: 
https://github.com/kenwheeler/slick/pull/1133 - Merged.
