### ISSUE TITLE
Grid problems (slick.js 1.5.0)

### ISSUE THREAD

**Issue by mrtonyhuynh** [kenwheeler/slick#1236]
## Problem 1

I have a code like this (using bootstrap 3):
``` HTML
<div role="tabpanel" class="row tab-pane active" id="branding">
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-1.jpg" class="img-thumbnail">
    </div>
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-2.jpg" class="img-thumbnail">
    </div>
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-3.jpg" class="img-thumbnail">
    </div>
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-4.jpg" class="img-thumbnail">
    </div>
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-5.jpg" class="img-thumbnail">
    </div>
    <div class="col-sm-6 col-md-3">
        <img data-lazy="images/portfolio-6.jpg" class="img-thumbnail">
    </div>
</div>
```

With these parameters:
> rows: 2,
> slidesPerRow: 4,

The problem is as follows:
```
<div class="col-sm-6 col-md-3" style="width:55%; display: inline-block;">
```

Results width 55% is wrong though: 
(slick.js line:555)
```
console.log((100 / _.options.slidesPerRow)+ "%"); // return 25%;
```

## Problem 2

```javascript
$('#portfolio .tab-pane').slick({
        infinite: false,
        dots: false,
        speed: 500,
        rows: 2,
        slidesPerRow: 4,
        responsive: [
            {
                breakpoint: 980,
                settings: {
                    rows: 2,
                    slidesPerRow: 2,
                }
            },
                {
                    breakpoint: 480,
                    settings: {
                        rows: 1,
                        slidesPerRow: 1,
                        slidesToShow: 1
                    }
            }
          ]
    });
```

I cannot reset default style (1x1) with this code with mobile viewport (width 320px) In fact it displays 1x6 =.=! 
 Please tell me how I should do? Thank you!

**Comment by kenwheeler** [comment]
Problem 1: is the 55% bootstrap overriding slick?
Problem 2: can you create a jsfiddle?

**Comment by mrtonyhuynh** [comment]
http://jsfiddle.net/9ate9fyd/1/

Problem 1: It is inline-css and added by slick.js (not bootstrap) as I have described above.

**Comment by qburns** [comment]
MrTony,

This is not necessarily the solution the the problem, but a bandaid:

If you set .col-sm-6 in the css to be 'width:50%!important;' and the same for .col-md-3 as 'width:25%!important;' it will override the inline styles being set by slick and properly display how you'd like.

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
