### ISSUE TITLE
'slide' option not respecting setting

### ISSUE THREAD

**Issue by zslabs** [kenwheeler/slick#1238]
Hi all,
Noticed something a bit odd around the change done with slick automatically detects child elements (believe that was 1.5.0). If I set the `slide` option, it is not respecting my value: http://codepen.io/zslabs/pen/WbVgBB

**Comment by boynet** [comment]
@zslabs take a look here: https://github.com/kenwheeler/slick/issues/1281

**Comment by zslabs** [comment]
Appreciate you pointing me to that, will close this and watch that thread.
