### ISSUE TITLE
.slick-disabled class is not added to arrows when there's nothing to slide

### ISSUE THREAD

**Issue by herrschuessler** [kenwheeler/slick#1244]
When the total number of slides matches the number of slides to display at the same time, and looping is disabled, the arrows should receive the CSS class .slick-disabled, but that class is not applied.

Example: The slider is showing 3 slides simultaneously. There are only 3 slides in the slider. Arrows should be disabled, because scrolling is impossible.

**Comment by simeydotme** [comment]
Arrows are not rendered, so no class can be applied.
http://jsfiddle.net/simeydotme/aj7ftgmt/

**Comment by herrschuessler** [comment]
You are right - when using the generated arrows, no class can be applied.

When using custom arrows (via the `prevArrow` / `nextArrow` setting), the issue still exists.
https://jsfiddle.net/twpyfyoy/7/

**Comment by simeydotme** [comment]
Aha. Touché!
Well, I will investigate if this is simple or not, in the mean-time you could always use the `breakpoint` event to detect if `slidesToShow` === `$slides.length` :)

**Comment by herrschuessler** [comment]
Thanks! For now I'll just take advantage of the fact that slick adds an inline declaration of `display:block` to the arrows and hide them by default, so that no arrows are shown when there's nothing to slide.

**Comment by owndann** [comment]
so you can now hide the custom arrows?

**Comment by goodpixels** [comment]
You can hide them with CSS by adding `display: none !important` or `visibility: hidden`, however there *should* be an option in the Slick settings to hide them.

**Comment by majomartinez** [comment]
I added some id for the specific div where I will show the arrow and set the slick-arrow style to be `visibility: visible` and then I set the default the of the slick arrow to `visibility: hidden` .

Here's my code: 

**slick default style:** 

```
.slick-arrow.slick-prev,
.slick-arrow.slick-next  {
    visibility: hidden;
}
```

**my speficic div style**

```
 #category-carousel .slick-arrow.slick-prev,
 #category-carousel .slick-arrow.slick-next  {
    visibility: visible;
 }
```


this solution worked for me.
