### ISSUE TITLE
Click on free space in slick-dots li jumping to wrong page

### ISSUE THREAD

**Issue by UksusoFF** [kenwheeler/slick#1250]
Hi!
I'm using slick with some css tweaks and can't understand whats wrong.
Look at example:
http://jsfiddle.net/6dambjrz/1/
When i click to near dots then slide go to wrong page:
![click](https://cloud.githubusercontent.com/assets/1931442/7214496/e2fd34d2-e5bf-11e4-8b37-77f6b05cbc37.png)

**Comment by simeydotme** [comment]
http://jsfiddle.net/xs87r5La/1/
Please check the fiddle, and confirm it's ___working___ as you expect, @UksusoFF.
If so I'll merge in to `master` and it will be on `1.5.3` whenever it's ready :smile:

**Comment by UksusoFF** [comment]
Yes, works as expect! Thanks!

**Comment by simeydotme** [comment]
Cool, it's merged in to `master`, you can grab that for now, or wait for `1.5.3` and the minified version :)
