### ISSUE TITLE
Prevent Carousel Sliding while drag-scrolling vertically on a touch device

### ISSUE THREAD

**Issue by Defcon0** [kenwheeler/slick#1252]
Hello,

the title says it all: This should be possible. Is it a bug or already a feature?

Thanks in advance.

Bye Defcon0

**Comment by j-kwon** [comment]
+1 I have the same issue.

**Comment by simeydotme** [comment]
set option: `verticalSwiping` to `false` ... although I'm super confused, because it defaults to `false` ;)

**Comment by Defcon0** [comment]
I think, you didn't quite get the issue ;-) When I *first* scroll down in order to get to the stuff at the bottom of the page, and *then* swipe to the left or the right, it's then possible to scroll *and* swipe to left and right at the same time, which is ugly.

**Comment by simeydotme** [comment]
Nice Video! very clear.

**Comment by levymetal** [comment]
I just started using Slick and I have the same issue. Apart from that, it's incredible!

**Comment by levymetal** [comment]
I've patched this in my own fork, but I've only tested it in my own personal project. If I get time, I'll try and test out all variations and submit a PR. 

Anyway, in the meantime, for anyone who wants a quick fix you can view my changes here: https://github.com/levymetal/slick/commit/36fee6b5ddb51081658e1aa4195a249793f77ddf

**Comment by Rrrapture** [comment]
+1

**Comment by Defcon0** [comment]
@levymetal: Awesome job :+1: I just integrated your code and it works like a charm. Hopefully, kenwheeler adds this in no time.

**Comment by simeydotme** [comment]
@levymetal is it possible for you to create a JSFiddle with your source for me to play with ? :)

**Comment by adg29** [comment]
+1

**Comment by ansman** [comment]
Any news on this, it's really annoying when using a mobile device.

**Comment by levymetal** [comment]
@ansman Try using my fork here: https://github.com/levymetal/slick.

This works fine for me, but I've not had the time to create a JSFiddle with all possible variations, so I don't wish to submit a PR unless I know it won't break anything.

**Comment by colorfool-me** [comment]
+1

**Comment by hyeyoungkang** [comment]
:+1: 
Awesome!!
It's a difficult problem to me.. :(
Thank you!!

**Comment by jhpmatos** [comment]
+1

**Comment by floriancapelle** [comment]
+1

**Comment by jansson** [comment]
+1

**Comment by leonelcbraz** [comment]
+1

**Comment by theexplay** [comment]
+1

**Comment by marcelombc** [comment]
+1

**Comment by ravigkp** [comment]
@kenwheeler Please add this fix , it is so helpful for mobile devices. and this is working like a >kinG-< 👍

**Comment by kenwheeler** [comment]
Is there a PR open for this?

**Comment by ravigkp** [comment]
Hey,

Did not got you, come again?

__________
Thanks
Ravi

**Comment by marcelombc** [comment]
@levymetal, could you please open a PR?

**Comment by leggomuhgreggo** [comment]
@kenwheeler looks like PR #862 addresses it.

**Comment by levymetal** [comment]
@marcelombc It would probably take me 3 weeks or so to get onto it. I wrote that 18 months ago and I'm not sure what's changed in Slick since then, so I'd need to re-assess the fix to ensure it's still compatible. Also, building test cases using each variation/mode can take some time. However, if you'd like to open your own PR, you're more than welcome to use my fix as a base.

**Comment by marcelombc** [comment]
@levymetal, I open a pull request using your fix.
@kenwheeler could you please review this [PR](https://github.com/kenwheeler/slick/pull/2521)

**Comment by webegguk** [comment]
Having just included Slick (which I've used on many projects) in a predominantly mobile app environment, this is a huge issue. The slick slider is a really robust flexible carousel other than this callback issue on mobile so I don't mean to put it down in any way.
Many thanks @levymetal for the fix, it works great for my situation though it is difficult to see the exact changes as I am using version 1.6 of the plugin which has many changes since your forked version.
I hope this fix gets merged into a new release soon.

**Comment by semenets** [comment]
+1

**Comment by thasmo** [comment]
@kenwheeler Please review and merge. :) Thank you!

**Comment by thiagocoelho** [comment]
I have the same issue, for mobile devices when scrolling up or down. So far the best slider I've found. Praying to see this PR merged soon.. :)

**Comment by FullstackJack** [comment]
Introduced two years ago and still not merged? Can we please merge this already. It's a major pain.

+100

**Comment by leggomuhgreggo** [comment]
@FullstackJack looks like you figured it out, but the fix was merged a couple days ago. Gonna close this issue. Thanks everyone.

**Comment by m11z** [comment]
@leggomuhgreggo slick.min.js file does not include the following fix (#1252), but the source file includes it (not minified slick.js).

**Comment by leggomuhgreggo** [comment]
The minified file generates with releases, the next one of which will be later this week.

**Comment by yasin749** [comment]
Awesome css3  

.owl-carousel{
  -ms-touch-action: pan-y;
  touch-action: pan-y;
}

**Comment by yasin749** [comment]
Awesome css3 :)

.owl-carousel
{
    -ms-touch-action: pan-y;
    touch-action: pan-y;
}

**Comment by yasin749** [comment]
Awesome css3 :)

.owl-carousel
{
-ms-touch-action: pan-y;
touch-action: pan-y;
}

**Comment by Amitshaale** [comment]
ngx slick carousel touch scroll is not working.
Can anyone help here how to enable touchScroll?
