### ISSUE TITLE
onHover not playing onMouseleave

### ISSUE THREAD

**Issue by bravo14** [kenwheeler/slick#1254]
Using version 1.5.0 of plugin

I have the carousel pausing on hover but won't play when mouse leaves carousel

**Comment by simeydotme** [comment]
I guess related to #1220 ... Bossman says I'll take a look soon. ;D

**Comment by ethanclevenger91** [comment]
:thumbsup: thanks all!

**Comment by ethanclevenger91** [comment]
Can we confirm this has been resolved with 1.5.1? http://codepen.io/ethanclevenger91/pen/MYNGrN

I'm not sure the fix made it into the minified version

**Comment by simeydotme** [comment]
Nah, it isn't in there; checking up with Ken to find out what happened :)
Thanks for spotting this!! :bow:
