### ISSUE TITLE
Lazy load options

### ISSUE THREAD

**Issue by nathanhornby** [kenwheeler/slick#1257]
The issue I'm having with the lazy load option is that for large images (where it has most value) it inevitably results in blank slides moving about while images are loading in.

Could a setting be added to allow the lazy load to be 'offset' by 1 or more slides? i.e. so the slideshow loads in the next slide while viewing the current one, thereby reducing the chance the user ever has to see the actual loading?

Or if not a setting, does anyone have an idea of how to hack this in?

**Comment by jan1980** [comment]
+1 I think this is a must...

**Comment by simeydotme** [comment]
have you tried the `progressive` option?

**Comment by bramwillemse** [comment]
I also have some issues loading with large images (retina etc.). The progressive is not an option, because it would load a large collection of images (10+ sometimes) resulting in a 8+mb page load.

**Comment by kimek** [comment]
'progressive' doesn't work for all Safari browser. Checked on Mac and Win on http and https. Please help. ps. (IE 9+, Firefox and Chrome support progressive)

**Comment by nathanhornby** [comment]
@simeydotme What does the `progressive` option do? The docs are pretty sparse:

"Set lazy loading technique. Accepts 'ondemand' or 'progressive'"

With no explanation.

Unfortunately I haven't used the plugin in quite some time so I can't say for sure whether I've tried this option or not, or if it were available when I last used it. But if you think it's likely to solve this issue then I'd be happy to check it out.

**Comment by nathanhornby** [comment]
Ah explanation here, seems I wasn't the only one confused by the lack of explanation! https://stackoverflow.com/questions/25726554/lazy-loading-progressive-vs-on-demand

That is a valid alternative for some situations, but one of the advantages of lazyload is that it bypasses downloading files unnecessarily - this would still download them, just later. So a mobile user would still be downloading all of the assets (even if they never few them), the order might just change.

Good option to know about though!
