### ISSUE TITLE
Exclude last margin from slick-track calculation

### ISSUE THREAD

**Issue by n3liu5** [kenwheeler/slick#1259]
Hey Ken!

Thank you for writing this awesome plugin, its a charm!

The question I have for you regards the calculation of the width of .slick-track.
I'm using non-infinite, and non-variableWidth, and after the last slide in slick-track there is a margin-right, just like for all the other slides. In my case that looks just stupid, because I want this little 'preview' on the right side as long as I'm sliding right, and on the last page I want the 'preview' to be left.

Is there a possibility to alter the calculation of slick-track's width?

Here is a fiddle explaining little bit better what I mean, just slide to the last page.
http://jsfiddle.net/18vf5d12/1/
It would be great if you would take a look, I thank you a lot in advance.

All the best,
Cornelius

**Comment by simeydotme** [comment]
Hey @n3liu5 , thanks for contributing :)
I've fixed your fiddle for you; http://jsfiddle.net/18vf5d12/2/

Regards, Simon.

**Comment by n3liu5** [comment]
Dear Simon, thank you so much. In my original code I use this only on tablet screen and didn't think of the margin-right that was attached since desktop-layout. Even when I had to put the margin-right in manually in my fiddle I didn't realize that. 
Thank's a lot! <3

**Comment by n3liu5** [comment]
After the first enthusiasm for your good solution, I saw that with now the last element gets (of course) wider than the other ones.. I can't think of a solution to solve this at the moment.

**Comment by simeydotme** [comment]
Oh, I actually think I must have mis-read your original query :confounded: - i can see what your use-case is now, and it is really an interesting, but difficult one. I really don't think it is something that should make it in to the core of the plugin (personally) but I will see if I can come up with a solution using the current API :)

**Comment by simeydotme** [comment]
Here, I believe I have it :ok_woman: 
http://jsfiddle.net/18vf5d12/4/

The key thing is the class-change and the transition. Without the transition effect, the slider will seem "jerky" at the last slide. I changed teh colours just so it's easier to see the "margin"s :)

**Comment by n3liu5** [comment]
Hey Simon,

thank you very much for your time!
I just built this into my script and it works like a charm.

✨
