### ISSUE TITLE
slickGoTo documentation badly worded on main site

### ISSUE THREAD

**Issue by hfaulds** [kenwheeler/slick#1261]
![image](https://cloud.githubusercontent.com/assets/645812/7256782/27e99aaa-e849-11e4-83cc-87ddf454a403.png)

In the github README it's clear that the second argument is `dontAnimate: bool` but on the main site it reads as being `shouldAnimate` (the inverse).

This tripped me up for a while and I assumed that second argument was broken until I saw the README here by chance.

**Comment by jamesckemp** [comment]
I also faced this issue! I ended up delving into the js file and figuring it out

**Comment by R2D221** [comment]
This gave me a headache for a moment, too. Should be an easy change on the documentation.

**Comment by sidonaldson** [comment]
:+1:  this is just a doc amend! Please fast track it :)

**Comment by kenwheeler** [comment]
Just pushed this, sorry guys

**Comment by sidonaldson** [comment]
:fireworks:
