### ISSUE TITLE
Issue with slow clones when showing multiple slides

### ISSUE THREAD

**Issue by jamesckemp** [kenwheeler/slick#1264]
Hi Ken,

First of all, great work! The one issue I am having, is when I show multiple slides, and also allow the user to click the slide to navigate through them; If the user continuously clicks the last slides, there aren't enough clones to keep up with it, and you can see them "flick" into place. See example: https://jsfiddle.net/jckemp/rLz4pe7u/

Just keep clicking on the fourth item and you will see the issue I am referring to after a few slides.

Thanks in advance.

**Comment by jamesckemp** [comment]
After testing on a slider using just text, it seems that the issue is actually the load time of the images. It'd be great if there was a setting to choose how many slides are preloaded?

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
