### ISSUE TITLE
RSS feed input option

### ISSUE THREAD

**Issue by tidg** [kenwheeler/slick#1265]
Hi, 

I would like to know, if it would be possible to include in the settings, the option to pull in an RSS feed, and apply the slider above, with callback management..

It would be a great update :)

Regards, Dji.

**Comment by simeydotme** [comment]
Hey @tidg , thanks for contributing.

Slick's API allows you to add slides. 
You'll have to write your own methods for collecting RSS data and feeding it in to your slider.

Regards,
Simon.
