### ISSUE TITLE
Autoplay does not begin again after mouseleave event when using pauseOnHover or pauseOnDotsHover

### ISSUE THREAD

**Issue by bkoranda** [kenwheeler/slick#1266]
Looking at the "Autoplay" demo on http://kenwheeler.github.io/slick/

pauseOnHover is true (by default)
If you mouseover a slide, the carousel pauses (as intended).
When you mouseleave the slide, autoplay does not begin again (user has to manually click an arrow or dot to start autoplay again). 

After mouseleave shouldn't the carousel start autoplay again?

**Comment by simeydotme** [comment]
Think this should be fixed by: https://github.com/kenwheeler/slick/pull/1258 - waiting for build in to next deployment :)
