### ISSUE TITLE
Unslick event

### ISSUE THREAD

**Issue by wfendler** [kenwheeler/slick#1267]
Is there a way to attach some functionality to the `unslick` event?

I was looking to add/remove some classes as the carousel was built/destroyed. It shouldn't be a problem to write my own function to handle the changes but it would be great to be able to pass a function to `.unslick()` or better yet, the `settings` inside the responsive breakpoints.

**Comment by simeydotme** [comment]
Tomorrow when 1.5.2 is released there are events triggered at each breakpoint, you use these events to check if slick is "unslicked" or not, then run your logic :)
