### ISSUE TITLE
Not displaying current slide when chaging from mobile view to desktop view.

### ISSUE THREAD

**Issue by mpkumar87** [kenwheeler/slick#1268]
Hi,
Currently, my slide contain 8 items.. In mobile view, i am seeing 8th item(one item per view) and when switching to desktop view, it reseting to initial item. Please guide me solve this issue.

Thanks,
Premkumar

**Comment by mpkumar87** [comment]
Hi,
Any feedback for above post..

Thanks,
Premkumar.

**Comment by simeydotme** [comment]
Hey @mpkumar87 , please read https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown for some help, if you can satisfy the contribution guidelines we'll do our best to help you :)

**Comment by simeydotme** [comment]
fixed on master.
