### ISSUE TITLE
Fading text on none/transparent background.

### ISSUE THREAD

**Issue by ConneXNL** [kenwheeler/slick#1269]
I just upgraded from 1.3.15 and now fading text on a transparent background is no longer working as can be seen here:
http://jsfiddle.net/mt4jdy6o/1/

The commit might be: https://github.com/kenwheeler/slick/commit/0bb54c0b05c3cdfe4179299092158095143b01d2 

Copying the Slick.prototype.fadeSlide function from 1.3.15 and passing in the oldSlide as the first parameter seems to fix this.

This issue was incorrectly closed imo:
https://github.com/kenwheeler/slick/issues/1205

**Comment by lemoslincoln** [comment]
I'm still having problems...
Look here http://bigodegoiano.com.br/unyt
