### ISSUE TITLE
Arrows not working and dots on image not below

### ISSUE THREAD

**Issue by dc34** [kenwheeler/slick#1271]
hi the arrows aren't showing, my background is white perhaps this is why, please what do I change?
The dots are on the image rather than below the image
Many thanks

**Comment by leggomuhgreggo** [comment]
There are default and theme styles that, in addition to other things, set the color of the arrow. You can override them with your own styles. The arrow symbols are actually from a font icon being applied to the slick-next and slick-prev before pseudo element.

The css that will help you is:
.slick-prev:before, .slick-next:before{color: black;}

**Comment by simeydotme** [comment]
thanks, @leggomuhgreggo
