### ISSUE TITLE
Add class when slider is being dragged

### ISSUE THREAD

**Issue by JTLR** [kenwheeler/slick#1274]
Will attempt a pull request when I have time, just put this here in case someone else wants it, does it quicker.

suggested class names:
.dragging
.is-being-dragged

**Comment by Harry-Harrison** [comment]
I'd also like to see this.

**Comment by AntoineBoulanger** [comment]
The same question has already been asked https://github.com/kenwheeler/slick/issues/967 but i would like to see this too, as an option. 
My class suggestion is: `is-dragging`.
Meanwhile, check the same issue above, you can just add 2 lines to make it work.
