### ISSUE TITLE
Synchronised carousels: JS error when page renders on responsive environment with responsive settings 

### ISSUE THREAD

**Issue by kakt00c** [kenwheeler/slick#1276]
Hello! 
I have found an issue in this beautiful carousel, which crashes all the beauty on responsive environment. 

Steps to reproduce: 
1. go to http://codepen.io/anon/pen/MwWddy
2. render it in browser with width more than 900px: carousels works perfect in pair. 
3. make window smaller than 900px without reload: carousel still works super good
4. reload page in browser with width less than 900px: BAM! carousels are broken with error in console "Uncaught TypeError: Cannot read property 'getSlick' of undefined" 

Please please help me to fix it i need synchronised carousel with responsive settings soooo much!

**Comment by kenwheeler** [comment]
Nice bug report. Looking into this.

**Comment by Ian-Wright1979** [comment]
I'm having the exact same issue. I realise it's only recently been reported but any idea on when a fix will be released?

I also noticed that it wasn't an issue with version 1.3.15 as I do have a site up and running which has the synchronised carousels and is fine. I am using 1.4.1 for this current site and it does have the issue.

**Comment by TonySpegel** [comment]
1.5.2 seems to fix this - at least for me. Had 1.5.0  prior to this and got sth. pretty similiar to @kakt00c

**Comment by simeydotme** [comment]
yep @TonySpegel is correct,
This was fixed with the commit: https://github.com/simeydotme/slick/commit/0d4339d5ad3ff25ad85863d8f548775b17ee9162 :bow:

**Comment by kakt00c** [comment]
That is really helpful! Thank you a lot! :dancers:
