### ISSUE TITLE
Add slide behind current slide without changing current slide that is being shown

### ISSUE THREAD

**Issue by saunders1989** [kenwheeler/slick#1277]
if you add a slide behind the current slide the slider position has now become the slide you've just added. is there a way to add a slide before your current slide but still stay on the current slide?

here is a jsfiddle of it happening - https://jsfiddle.net/ovacntgy/5/

I understand this is normal behavior as a lot of other sliders do this. I did see flickity does this nicely but doesnt have as much / nice features your plugin does

**Comment by simeydotme** [comment]
Just change your code to add the slide, then navigate to slide+1 using the `slickGoTo` method :)
