### ISSUE TITLE
slickGoTo doesn't do as expected when filtering is ON

### ISSUE THREAD

**Issue by jeanrnewyyz** [kenwheeler/slick#1280]
I hope this isn't a duplicate...
I'm using slick to contain edit panels.  When a panel gets focus, I'd like it to become the active slick panel. So on 'focusin', I take the slick-index value in the attribute and use as the index in slickGoTo.
But... Some of the panels may be filtered. Even though I say "goto panel with index = 5" I end up on panel w/ index = 7 (because 3 & 4 are filtered out).  5 is visible, but GoTo is moving by delta instead of by actual recorded index...  How could I get around that?

I though I could loop slickNext (or slickPrev) and reflect on slick-index, but that requires a whole async rig to work it out. 

Ideas?

**Comment by leggomuhgreggo** [comment]
You got a fiddle? Thanks!

**Comment by jeanrnewyyz** [comment]
I don't got a fiddle, yet...

**Comment by jeanrnewyyz** [comment]
Woohoo!  My first plunker!  

http://plnkr.co/edit/4IrzvkzMNueRB33l7zKy?p=preview

I learned a lot just doing it, about plnkr and about slick.  I may fix my problem differently. I think you still have one though.

Thanks for a superb component.  We're it in angular via angular-slick.
Cheers.

**Comment by simeydotme** [comment]
It seems like it doesn't work as __you__ expect. Personally it makes sense to me; because when you filter out a slide, you have "removed" it, and so what you used to call "Slide 7" (an arbitrary name) is actually the 5th index in the slider, now.

I understand your confusion, but seems like it would be a breaking change, and also very confusing if you expect it to work the other way :confused:

**Comment by jeanrnewyyz** [comment]
Gotcha!.  I think the docs should be clarified then, because I proceeded w/ my assumption and got lost for a while.  After all, **you** do call it [data-slick-index] and you use the word "index" throughout the docs; **you** don't change [data-slick-index] from "7" to "5" if 2 slides disappear in the middle.  You have a GoTo "index" method.  The names, the names!

And/or there could be another method to navigate to data-slick-index.

FYI, I use slick for an editor, where changing values on slide 3, say, filters slides 5-6 or 7 out.  Because there's 2-way navigation between the slides and an external control, I need random access to the slides.  I was using the index to get there, 

Wanting to make slide MY_ID active, I do this:

```
$slide = $('.slick-slider [my-id=MY_ID]');
```
I thought I could then do this:
```
$('.slick-slider').slick('slickGoTo', $slide.attr('data-slick-index'));
```
Working on the plunker taught me I could do this instead:
```
$('.slick-slider').slick('slickGoTo', $slide.prevAll().length);
```
Thanks.

Jean

**Comment by simeydotme** [comment]
Agreed, the `slick-index` data attributes muddy things a little, and I would imagine they were added much before the `filter` method was introduced :confused: - anyway, I've gone ahead and forked your __plnkr__ here: http://plnkr.co/edit/LYiKUTpQkIfg9eSyriC7?p=preview (fun code playground, few niggles but I can see it being really nice on giant monitors! :smiley: )

The main thing you'll notice is I'm calling up `slick`'s internal filtered-slide-list and matching that up with your expected indexes... it almost feels like this is a deliberate thing and possible _why_ the `data-slick-index`s are different :yum: 

anyway, here's the pasted code, too:

```js
$('#my-index').change(function(ev) {
    // get the index from select-box
    var i = $(this).val();
    // get the pre-filtered slide-list
    var $slides = $slick.slick('getSlick').$slides;
    // filter the slide-list again to find our desired data-index slide
    var $tar = $slides.filter('[data-slick-index='+i+']');
    // now find which index of the list that desired slide is in
    var idx = $slides.index( $tar );
    // and finally go to that new, adjusted, index :)
    $slick.slick('slickGoTo', idx );
  });
```

obviously there's a few ways to improve it, but I'm assuming your real application is a lot different to the plnkr so I'll leave that to you. Hope the logic helps, though :bow: 

Regards, Simon.

**Comment by jeanrnewyyz** [comment]
Hey, thanks for this Simon.
I get it now, that data-slick-index exists so you can splice filtered slides back in the right spot.
I'll look at the code behind these constructs you show here and will learn further.
You're right that my app is not the same as the plunkr.
And for now, I'm happy w/ the transparency of the $().prevAll().length cheat to find the index of interest (less lines than your "legit" method  :)

J
