### ISSUE TITLE
slide option doesnt work in 1.5.2

### ISSUE THREAD

**Issue by saunders1989** [kenwheeler/slick#1281]
I see someone raised an issue #1238 for this but was never answered. I was trying to have different slides depending on device. for example gallery-slide on desktop and mobile-slide on mobile.

if i use version 1.4 it removes mobile slides from the track correctly but need the responsive feature as well.

As this isnt fixed is there a work around with filtering I could use?

i have a js fiddle outlining the issue - https://jsfiddle.net/ovacntgy/13/

**Comment by boynet** [comment]
what the lastest to known version that works?

**Comment by saunders1989** [comment]
I was able to use the 'slide' option in 1.4.1 for a simple slider but doesn't work when i use responsive as well as per my fiddle

**Comment by boynet** [comment]
found the bug.. its because of this commit: https://github.com/kenwheeler/slick/commit/9d13d6abc4ab4e05948b5bab47b2574fad9c9c64#diff-eaaa72f2e5f1d4974e4f1ae902717908L476 as you can see they remove this option... for tempry solution edit this line in you fork from: "_.$slides = _.$slider.children(" to: "_.$slides = _.$slider.children(_.options.slide +"

**Comment by saunders1989** [comment]
Hi @boynet cheers for finding that commit that broke it. I'm not sure it was supposed to go as the option is still there in the readme. I have found another issue but will open a new ticket as it is a different issue to using the slide option

**Comment by boynet** [comment]
@saunders1989  ofcourse that its not ment to be remobed, I think you should keep this issue open has this bug not resolve.. the problem is this slider became to big with too much of options, so every change in the code break something

**Comment by kenwheeler** [comment]
@boynet actually I'm deprecating the slide option. I just haven't had time to properly document it.

**Comment by boynet** [comment]
@kenwheeler ok so my mistake :) sorry

**Comment by saunders1989** [comment]
@kenwheeler ah okay. so i guess my question #1287 isn't possible and wont be possible?

**Comment by kenwheeler** [comment]
@saunders1989 let me understand what you're trying to do here. You want to have different slides shown for different breakpoints?

**Comment by saunders1989** [comment]
@kenwheeler thats correct. so for example i have desktop slides on desktop and add mobile adds to the gallery when on tablet screens - this gives you an example of it - https://jsfiddle.net/ovacntgy/15/

**Comment by kenwheeler** [comment]
hold on, is it a wholesale switch out, or do the mobile slides just get added and removed

**Comment by saunders1989** [comment]
the mobile slides would just get added and removed but in the order they were when the dom was sent down. so if mobile slide was slide 5 on desktop that isn't in the gallery. but below 1024 it is slide 5 because at the moment it adds it the front

**Comment by saunders1989** [comment]
@kenwheeler Did you think of a solution?

**Comment by vsxed** [comment]
@kenwheeler why would you deprecate it? Will there be an alternative/better option?
