### ISSUE TITLE
Lazy load complete event?

### ISSUE THREAD

**Issue by owlyowl** [kenwheeler/slick#1283]
Hi just wondering if there's a way to get when lazy load has completed so I can show some text that appears on top of the image.

The reason being is that if the image / height of the slide isn't known to css the text can't be vertically aligned middle

**Comment by gordielachance** [comment]
Would like to know too !

**Comment by ScottKriegerPD** [comment]
I could use this event as well.

**Comment by kenwheeler** [comment]
you could do `$('.slick-slide img').on('load', fn)` if i'm not mistaken

**Comment by ScottKriegerPD** [comment]
You're right. I'm staring at this wrong. Appreciated.

**Comment by shubh911** [comment]
This really helped.. Thanks.

**Comment by bscheshirwork** [comment]
$('.slick-slide img').on('load', fn) not work at cloned items
