### ISSUE TITLE
Multiple carousels in page - dots navigation stops working

### ISSUE THREAD

**Issue by bogdandanila** [kenwheeler/slick#1284]
I am trying to place 4 carousels in the same page, each with a different number of items inside it. 

I'm using version 1.5.2 and the following options for all 4 carousels:
            {
                dots: true,
                touchThreshold: 8,
                infinite: true,
                rtl: false,
                autoplay: true,
                autoplayspeed: 4000,
                speed: 600,
                responsive: [
                    {
                        breakpoint: 9200,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4
                        }
                    },
                    {
                        breakpoint: 1200,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3
                        }
                    },
                    {
                        breakpoint: 1000,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            arrows: false,
                            dots: false
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1,
                            arrows: false,
                            dots: false
                        }
                    }
                ]
            };

Number of items:
    carousel 1 (c1): 10 items
    carousel 2 (c2):   6 items
    carousel 3 (c3):   4 items
    carousel 4 (c4):   5 items

When viewing the page at full width (~1900px) the carousels display and work fine, but when resizing the browser window to between 1000px and 1200px (when only 3 items are displayed per carousel page) the dots navigation is initialized and displayed for c3 (and working as expected), but the dots nav for c1 and c2 stop working, while the ones for c4 continue to work fine.

I have also tested this on lower screen widths and less items in the carousels, but the result is the same. It seems that when one of the carousels initializes its dots nav (on window resize), itself and the carousels below it work fine, while the ones above break.

Also tested in v1.5.1, v1.5.0 and v1.4.1 (doesn't happen in this one)
Note: I use the 9200px breakpoint because if I don't, the above behavior will also happen on page refresh (when the width is between 1000 and 1200 pixels).

I want to know if this is a known issue, or if it's something I did wrong. Please help!

Thank you

**Comment by bogdandanila** [comment]
I managed to find a workaround for this:

I realized that the dots' click events are not reinitialized after the carousel is resized from desktop view (4 items, >1200px) to tablet view (3 items, <1200px, >1000px) and after the dots themselves are (re)initialized.

So I wrote this:

var carouselInstance = carousel.slick(options);

carouselInstance.on('afterChange', function () {

    carouselInstance.slick('getSlick').initDotEvents();

});

which solves everything pretty nicely. Although, I think you should take a look at this problem. 

Keep up the good work!

**Comment by nbankzy** [comment]
I have the same issue but mine breaks on resizing and sometimes doesn't even work on page load. Page load seems to have an issue with the container being 1100-1200px.

Used the above code to fix the issue

    jQuery('.image-container').slick('getSlick').initDotEvents(); // Fire on page load to start the events

    jQuery('.image-container').on('afterChange', function () {
	    jQuery('.image-container').slick('getSlick').initDotEvents();
	});

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
