### ISSUE TITLE
using 'slide' option and responsive doesn't place slides in order that was before slick initialized 

### ISSUE THREAD

**Issue by saunders1989** [kenwheeler/slick#1287]
Hi i am wondering if anyone has experienced this / has a fix for this:

I had a ticket #1281 which asked about the 'slide' option not working and was pointed towards a commit that removed it. I have added it in but was wondering if this is possible?

If i have a large screen and set the slide option to a group of elements and then shrink the window down and on say 1024px i want to add mobile slides slick adds them to the front of the carousel and not in the order the dom was before slick was initialized.

I have a fiddle showing my issue - https://jsfiddle.net/ovacntgy/15/

**Comment by leggomuhgreggo** [comment]
Hey I think this got fixed! Im going to close, but feel free to circle back if you're still having issues. Thanks
