### ISSUE TITLE
Feature Request: Click to progress

### ISSUE THREAD

**Issue by rnichael** [kenwheeler/slick#1293]
Is it possible to slide to the next slide when using .single-item?

Basically I want to be able to move to the next slide when I click the current slide.

**Comment by ethanclevenger91** [comment]
You might write your own JS to do this, since it's three new lines:

```
var $slideshow = $('.slider').slick();
$('.slide').click(function() {
    $slideshow.slick('slickGoTo', $slideshow.slick('slickCurrentSlide')+1);
});
```

**Comment by PratikBali** [comment]
This feature is auto enables in my case I want to disable this 
Basically I dont want to be move to the next slide when I click the current slide.
Stuck
