### ISSUE TITLE
Slider suddenly loses structure and gets broken

### ISSUE THREAD

**Issue by Binternet** [kenwheeler/slick#1297]
Check out http://37.bdev.co.il/

There is a slick instance in the middle of the page with one navigation button [on the picture itself, you need to really look for it] if you click 7 times on it, everything gets broken...

**Comment by simeydotme** [comment]
Your container has `display: table;` on it, removing this seems to relieve/fix your problem. Sorry I don't believe you've created a sufficient bug report for further invesgitation. 

Please refer to the [contributing.md](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) file in future.

Regards, Simon.

**Comment by Binternet** [comment]
Sorry, didn't know `display: table;` can cause that. my bad.
