### ISSUE TITLE
Feature Request: Free dragging

### ISSUE THREAD

**Issue by dude2511** [kenwheeler/slick#1299]
A lot ouf product carousels on mobile sites (see amazon for example) allow free dragging, so that on touch move (swipe) the position won't be adjusted afterwards. I realize that with "half items" shown on the left or right border it is hard to define which position/slide is currently active. On the other hand, it seems that for usability reasons and/or a native swipe feeling the "free mode" is preferred.

**Comment by subversve** [comment]
+1 This would be helpful to me as well.

**Comment by jasonLogicSpot** [comment]
+1 we have a project that we would like to use this on.

**Comment by shahafabileah** [comment]
+1

Note that there's a related issue: https://github.com/kenwheeler/slick/issues/1409

**Comment by luchomatic** [comment]
+1 I had to rebuild a whole microsite using Swiper instead of Slick because the client wanted free draging and scrolling.

**Comment by rulloliver** [comment]
+1

**Comment by PatrykPaziewski** [comment]
+1

**Comment by branng** [comment]
+1 Its a good idea.

**Comment by carljustineoyales** [comment]
any update on this feature?

**Comment by rastapopougros** [comment]
Why is this closed without any PR or commit related to adding this feature ? Is there an option for that or not ?

**Comment by Ospish** [comment]
This is still a wanted and seemingly unimplemented feature.
