### ISSUE TITLE
Unslicking in Responsive Breakpoint doesn't deactivate the adding of slick-active slick-center

### ISSUE THREAD

**Issue by nightbook** [kenwheeler/slick#1304]
Hello,

This is a branched issue from #1303 
That issue outlines the issue with reslicking after it's been unslicked by the responsive breakpoint.

This issue is related but seperate. If you unslick at certain breakpoints this works fine, however if you leave it for a little bit of time you'll find the individual elements start getting the 'slick-active slick-center' classes applied to them one at a time.  So it seems the unslick didn't cancel the timer for the addition of those classes.

Thank you

**Comment by simeydotme** [comment]
Here's a fiddle to show it happening.
:sparkles: http://jsfiddle.net/odoqefdq/ :sparkles:
