### ISSUE TITLE
slick() is giving an error

### ISSUE THREAD

**Issue by awadheshroy10** [kenwheeler/slick#1307]
Hi,
am new to coding and am using the slick for a carousel but is showing an error in console

<html>
  <head>
  <title>My Now Amazing Webpage</title>
  <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
  <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.2/slick.min.js"></script>
  

 </head>
  <body>
	 <div data-slick='{"slidesToShow": 4, "slidesToScroll": 4}' class = "fin">
  <div><h3>1</h3></div>
  <div><h3>2</h3></div>
  <div><h3>3</h3></div>
  <div><h3>4</h3></div>
  <div><h3>5</h3></div>
  <div><h3>6</h3></div>
</div>
	  
	  <script type="text/javascript">
    $(document).ready(function(){
	alert("hi");
	 $(".fin").slick();
	});
  </script>
  </body>
</html>

**Comment by boynet** [comment]
can you show the error? and upload jsfiddle of the problem
