### ISSUE TITLE
How to set no of slides between breakpoints eg 200-320

### ISSUE THREAD

**Issue by techagesite** [kenwheeler/slick#1309]
A lot of my sites visitors come from unusual browser sizes and i would like to keep my site responsive to all visitors by having slick be responsive between defined breakpoints rather than create rules for thousands of breakpoints. Also what about slick auto resizing to its container and detecting how many slides to show automatically? Another issue im having is slick isnt resizing with the rest of my site so im ending up with horizontal scrollbars breaking my sites responsiveness.

**Comment by carlesjove** [comment]
@techagesite I think you should ask for help at StackOverflow, and maybe provide some of your current code so people can have a look and help. Github issues are usually for bug reports.

However, I think what you are looking for is the `responsive` argument. Check [the docs](http://kenwheeler.github.io/slick/) and look for "Responsive Display" ;-)

**Comment by techagesite** [comment]
Ive checked and no matter what i do i cant get slick to size to its container. The people at SO arent too willing to help with the harder issues.

**Comment by carlesjove** [comment]
@techagesite Maybe you can ask at some of the resources listed at the [Support](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#support) section

**Comment by techagesite** [comment]
@carlesjove cheers
