### ISSUE TITLE
Dots not working correctly

### ISSUE THREAD

**Issue by Lugat** [kenwheeler/slick#1310]
Hi there,

I have the issue, that the dot navigation is not working correctly when infinite = false and the total items are not a multiple of itemsToShow.

You can find an example here:
http://jsfiddle.net/fL0mw6dg/1/

Greetings, Lukas

**Comment by Lugat** [comment]
It worked for me to change "getNavigableIndexes" in the lines 1054 & 1055.
```js
//max = _.slideCount - _.options.slidesToShow + 1;
//if (_.options.centerMode === true) max = _.slideCount;
max = _.slideCount;
```
Unfortunately I have no idea if it will affect other parts of the plugin.

**Comment by kenwheeler** [comment]
Fixed on master
