### ISSUE TITLE
[bug] asNavFor in combination with Responsive

### ISSUE THREAD

**Issue by tatof** [kenwheeler/slick#1311]
Hello,

I use your plugin a lot and i'm always happy with the result.
But this time its working against me...

I've got two sliders and one of them uses the arrows for navigating both.
Also there is a responsive breakpoint at 1024 but the hole script broke down when i added that.

When I delete the "asNavFor" the slider is fixed and responsive works.
When I delete "responsive" the slider is fixed and the asNavFor works.

But I can't get them to work together.
Here is the script:

jsFiddle: http://jsfiddle.net/tatof/kxw0x3hm/
websites: http://www.tatof.nl/test2/   (bottom slider)

EDIT: i found out that when the slick loads in 1920px and resizes to small screen it works. but when i press f5 and reload the page in small screen its brokan again.

EDIT2: I found out that i cant make both sliders responsive, but its posible to make the bottom one responsive.

**Comment by simeydotme** [comment]
here's an update to the fiddle with the raw master-branch slick, makes it easier to debug.
http://jsfiddle.net/kxw0x3hm/3/

I'm having al oko, but it seems pretty nuts, I think there's atleast 4 open issues about this! :confounded:

**Comment by simeydotme** [comment]
@tatof could you quickly test: http://jsfiddle.net/kxw0x3hm/4/ ... I have linked in the raw file from my branch, if you're happy it fixes your issue, I'll merge and close :smiling_imp:  

-----
Found a tiny bug; It was forcing a refresh when the carousel initialised inside a breakpoint. That refresh would try to `getSlick()` on the `asNavFor` target... but that target was not even initialised yet. So it crashed. - __Resolved__.

**Comment by tatof** [comment]
Yes this works! :) used the 1.5.2 script and its fixed:
http://www.tatof.nl/test2/

Thank you! you made my day.
