### ISSUE TITLE
bug with setting fade: true with responsive 'unslick'

### ISSUE THREAD

**Issue by javsalazar** [kenwheeler/slick#1313]
With setting **fade : true** and unslick at a certain viewport only image that was visible prior to reaching viewport value is visible.  It appears that all other images get opacity = 0 (along with other css settings).

for example, if breakpoint is set to 800 and setting is 'unslick':
http://codepen.io/javsalazar/pen/NqGpjN

1. On slider with **fade: true** if start below 800 works as expected, no slider, and can see all images.  Can then move up above 800 and get slider  as expected. If move back down below 800 bug appears.

2. On slider with **fade: true** If start above 800 works as expected, get slider. If move below 800 will only see image that was viewable prior to moving below setting, all others have opacity=0.

3. Bug appears on version 1.5.0 - 1.5.2.  1.5.2 has the additional bug that if I start at a viewport that is below 800 it will not be responsive.  If start above 800, will get slider and once I go below 800 it does 'unslick' but from that point on is no longer responsive.

**Comment by simeydotme** [comment]
Please try your codepen with the new trunk :) - issue should be fixed.
