### ISSUE TITLE
Navigation arrows hover state not reverting until click outside

### ISSUE THREAD

**Issue by josefulander** [kenwheeler/slick#1314]
The hover state of the navigation arrows works as expected until you click one of them. The arrow then gets stuck on its hover state until you click somewhere else on the screen. This is barely noticable until you have a design with big arrows. Is there a way to get the hover state to revert when moving the pointer of the arrow even if you have clicked on it?

**Comment by saunders1989** [comment]
can you not add the style button.slick-next:focus to the same css as default?

**Comment by simeydotme** [comment]
ya @josefulander i think you mean the default arrows (they are buttons) have a `:focus` effect you don't desire (this is accessibility feature) ... as @saunders1989 says; you can change the CSS to suit your application.

Regards, Simon
