### ISSUE TITLE
Multiple responsive sliders break when new dots event fired

### ISSUE THREAD

**Issue by nbankzy** [kenwheeler/slick#1315]
I was able to replicate this with the latest version (1.5.2), 1.4.1 doesn't seem to have an issue with the bug though, where as 1.5.0 does.

If you have multiple sliders on a page which some by default have dots enabled and others don't, if a new breakpoint happens and dots are set to true where they previously weren't then it will kill other sliders dot interactions. One way to restore the behaviour back to the dots is to either use arrows or swipe action to move to the next pane, after this the behaviour is back until the next breakpoint.

I've setup an external demo to show, if you reduce the page width to where the bottom slider has dots appear you'll notice the top slider dot interaction stops working. Same happens if you have dots enabled by default and remove them at a later breakpoint, when you scale back up the dot event being fired breaks other image sliders.
http://jsfiddle.net/rr0zxoeL/

    $('.responsive').slick({
      dots: true,
      infinite: true,
      speed: 300,
      slidesToShow: 2,
      slidesToScroll: 2
    });

    $('.responsive2').slick({
      infinite: false,
      speed: 300,
      slidesToShow: 1,
      slidesToScroll: 1,
      responsive: [
        {
          breakpoint: 500, // this breakpoint kills .response dots
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1,
            infinite: true,
            dots: true
          }
        }
      ]
    });

**Comment by MatthiasPeltzer** [comment]
great slider so far! this is really one of the best. I am having the same problem with multiple sliders and breakpoints/dots. purely i can´t fix it by myself. :(

**Comment by simeydotme** [comment]
I can see the bug, thanks for the description and the JSFiddle. - ___helps a lot!___ :+1: 
Think I already have a patch for it, gonna test a little more and then push to my branch :wink: :sparkling_heart:

Si.

**Comment by nbankzy** [comment]
@simeydotme There still seems to be some issues, it's generally when scaling back up. I've updated the jsfiddle with the latest code source and added a few more breakpoints, where it removes and adds.

I believe the issue is happening when the dots are set to false and then back to true. http://jsfiddle.net/rr0zxoeL/1/

New response code

    responsive: [
      {
        breakpoint: 500,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          infinite: true,
          dots: true
        }
      },
      {
        breakpoint: 400,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
          dots: false
        }
      },
      {
        breakpoint: 300,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1
        }
      }
    ]

**Comment by simeydotme** [comment]
Really @nbankzy ? 😱 Jeez, let me see... Would imagine this is unrelated, though, as logically the patch I did was solid and oobvious... Thats for the effort of creating the fiddle and contributing 🙇 I'll see what I can find.

Si.

**Comment by simeydotme** [comment]
haha, sorry @nbankzy ... you had not taken the current master branch.
http://jsfiddle.net/simeydotme/rr0zxoeL/2/

I updated the `slick.js` file to the current, unminified, `master` branch. __it works fine?__ - I'm afraid you'll have to wait for @kenwheeler the plugin author to collate the recent changes into a tag-release, or minify that file yourself. :smiley: 

Simon.

**Comment by nbankzy** [comment]
@simeydotme looks like your solution was solid, sorry about that! was sure I had selected the newest code release, oh well. Thanks for the fix!
