### ISSUE TITLE
Styles being applied during dragging

### ISSUE THREAD

**Issue by anteksiler** [kenwheeler/slick#1317]
Please check the demo here: http://thevoux.fuelthemes.net/

If you resize your browser, there are no problems, but when viewed on mobile, the line-height of the title changes with each swipe of the carousel.

**Comment by simeydotme** [comment]
hi @antesiler. I had a quick look on your website (pretty!) in ___Chrome Desktop emulating iPhone6___, ___Chrome on Android___ _and_ ___Native Browser on Android___ (LG G3, Android 5.0) ... there is no issue that you describe.

If there were an issue with your website's CSS; then unless you can reproduce it in a cut-down jsfiddle and we can see that Slick is causing some CSS conflict I think what you're looking for is support on your coding and device :smile: 

Regards, Simon.

P.S - Closing issue, but you may continue discussion. :)

**Comment by anteksiler** [comment]
Hi @simeydotme I cannot debug it cause it only happens on a device. Emulating it on a browser does not re-create the issue.

**Comment by saunders1989** [comment]
if this happens on a android you can download the sdk and use a cable to inspect the css etc and debug it. also the same with a mac for iphone. Have you tried stripping out all of your styles apart from the slick styles? I had a quick look and you have a transform on the slide. that may be the issue. have you just removed it to see if it stops it?

**Comment by simeydotme** [comment]
As I say, I did a quick test on my device and nothing... You need to
provide at least some information. Which browser on which device and which
OS version.

:)

**Comment by anteksiler** [comment]
@saunders1989 Thanks, I never debugged mobile using the inspector, will try that. Found this tutorial for anyone interested: http://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

@simeydotme I am using Chrome on iPhone 5S. I'll try the above method and share my findings on this ticket.

**Comment by anteksiler** [comment]
@simeydotme I solved this by adding ```-webkit-text-size-adjust: 100%;``` to the styles. Interesting how this affected only during swiping.

**Comment by simeydotme** [comment]
:yellow_heart: nice work! which styles you applied to? your headers? - Mobile Webkit is known to have some funky text rendering bugs related to 3d transforms.

Thanks for posting your findings,
Si.
