### ISSUE TITLE
slickGoTo will not goto end slide if remainder exists

### ISSUE THREAD

**Issue by googabeast** [kenwheeler/slick#1319]
In the event of the slick slider having a remainder, when attempting to goto the last slide slick only goes to the last "full" slide.

The slider is designed to scroll by 4's. In the crude diagram below this would be one slide with a single remainder "item9". Because I want the selected item to always be shown on screen when the user tabs over to it again the slickGoTo only loads the first 4 items.

[ item1 ]   [ item3 ]   [ item5 ]   [ item7 ]   [ item9 ]   
[ item2 ]   [ item4 ]   [ item6 ]   [ item8 ]   

Config and example below.

Slick config:
$(".colorItems").slick({
	infinite: false,
	lazyLoad: "ondemand",
	prevArrow: $(".prevBtn.color"),
	nextArrow: $(".nextBtn.color")
});

HTML Rendered:

<div class="colorsWrap scrollableProducts">
	<a class="scrollLeft prevBtn browse left color slick-disabled" style="display: inline;">&nbsp;</a> <a class="scrollRight nextBtn browse right color" style="display: inline;">&nbsp;</a>

	<div class="colorItems totalCount slick-initialized slick-slider" data-slick="{&quot;slidesToShow&quot;: 4, &quot;slidesToScroll&quot;: 4}" style="">
		<div class="slick-list draggable" style="" tabindex="0">
			<div class="slick-track" style="opacity: 1; width: 550px; transform: translate3d(0px, 0px, 0px);">
				<div class="items slick-slide slick-active" data-slick-index="0" style="width: 110px;">
					<div class="isofaColor" id="coFL-12145694_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Slate">
						<img alt="Slate" class="" data-index="44" src="//images2.myDomain.com/is/image/myDomain/fabric_slate?$iSofa_Fabric_40x40$" style="opacity: 1;">Slate
					</div>

					<div class="isofaColor" id="coFL-12148690_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Vanilla">
						<img alt="Vanilla" class="" data-index="45" src="//images2.myDomain.com/is/image/myDomain/fabric_vanilla?$iSofa_Fabric_40x40$" style="opacity: 1;">Vanilla
					</div>
				</div>

				<div class="items slick-slide slick-active" data-slick-index="1" style="width: 110px;">
					<div class="isofaColor" id="coFL-12147698_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Wasabi">
						<img alt="Wasabi" class="" data-index="46" src="//images2.myDomain.com/is/image/myDomain/fabric_wasabi?$iSofa_Fabric_40x40$" style="opacity: 1;">Wasabi
					</div>

					<div class="isofaColor" id="coFL-12144692_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Hydra">
						<img alt="Hydra" class="" data-index="47" src="//images2.myDomain.com/is/image/myDomain/fabric_hydra?$iSofa_Fabric_40x40$" style="opacity: 1;">Hydra
					</div>
				</div>

				<div class="items slick-slide slick-active" data-slick-index="2" style="width: 110px;">
					<div class="isofaColor" id="coFL-12141684_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Cardinal">
						<img alt="Cardinal" class="" data-index="48" src="//images2.myDomain.com/is/image/myDomain/fabric_cardinal?$iSofa_Fabric_40x40$" style="opacity: 1;">Cardinal
					</div>

					<div class="isofaColor" id="coFL-12140694_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Indigo">
						<img alt="Active" class="activeCheck" src="/static/img/svg/greenCheck.svg"><img alt="Indigo" class="" data-index="49" src="//images2.myDomain.com/is/image/myDomain/fabric_indigo?$iSofa_Fabric_40x40$" style="opacity: 1;">Indigo
					</div>
				</div>

				<div class="items slick-slide slick-active" data-slick-index="3" style="width: 110px;">
					<div class="isofaColor" id="coFL-12146696_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Copper">
						<img alt="Copper" class="" data-index="50" src="//images2.myDomain.com/is/image/myDomain/fabric_copper?$iSofa_Fabric_40x40$" style="opacity: 1;">Copper
					</div>

					<div class="isofaColor" id="coFL-12143690_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Peat">
						<img alt="Peat" class="" data-index="51" src="//images2.myDomain.com/is/image/myDomain/fabric_peat?$iSofa_Fabric_40x40$" style="opacity: 1;">Peat
					</div>
				</div>

				<div class="items slick-slide" data-slick-index="4" style="width: 110px;">
					<div class="isofaColor" id="coFL-12142698_FL-1104969PDiv" style="width: 86px; padding: 0px 6.5px;" title="Espresso">
						<img alt="Espresso" class="slick-loading" data-index="52" data-lazy="//images2.myDomain.com/is/image/myDomain/fabric_espresso?$iSofa_Fabric_40x40$">Espresso
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

**Comment by kenwheeler** [comment]
which version
