### ISSUE TITLE
Add <picture> support to lazyLoad functionality

### ISSUE THREAD

**Issue by donum** [kenwheeler/slick#1321]
Hi,

I like the lazyLoad functionality a lot. Do you plan adding support for the [HTML5 picture element](http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-picture-element)?

Thanks,
Daniel

**Comment by kenwheeler** [comment]
I do not.

**Comment by evromalarkey** [comment]
Why not? Nowadays is picture a lot supported and this is important feature for mobile devices.

**Comment by evromalarkey** [comment]
nevermind, I found an alternative with http://afarkas.github.io/lazysizes/#examples works splendid
