### ISSUE TITLE
Swipe animation not fluid

### ISSUE THREAD

**Issue by ceehaupt** [kenwheeler/slick#1322]
Hi,

I use the slider for items, with an bg-image, headline and some text. If I want to swipe on touch devices, the animation isn't fluid. It stops a short time and slides then to the next.
Slick is on default settings. Do I have to add anything? I tried everything expained in the documentation.

Cheers.

**Comment by kenwheeler** [comment]
jsfiddle please

**Comment by ceehaupt** [comment]
http://jsfiddle.net/ceehaupt/tdcbs2jx/

**Comment by vml-rschooley** [comment]
Having a similar issue. @ceehaupt did you ever find a resolution?

**Comment by ceehaupt** [comment]
Sadly not.

**Comment by kenwheeler** [comment]
It's your easing

**Comment by ceehaupt** [comment]
No, it isn't. I removed the easing variables and the problem still exists.

**Comment by vml-rschooley** [comment]
I switched to using js animations temporarily and it works fine (useCSS:false). It's not ideal but it works now. I think I had a css transition that was conflicting with the swipe transition. It would be nice to move back to the css transitions though.
