### ISSUE TITLE
Syntax error: missing : after property id

### ISSUE THREAD

**Issue by JenniferMadden** [kenwheeler/slick#1323]
http://jsfiddle.net/zvsq2qsm/

**Comment by JenniferMadden** [comment]
http://jsfiddle.net/zvsq2qsm/

**Comment by kenwheeler** [comment]
What?

**Comment by JenniferMadden** [comment]
I'm getting a syntax error (missing : after property id) that points to setting-name: setting-value.  I can't figure out what is wrong.  The jsfiddle has my code.

**Comment by kenwheeler** [comment]
setting-name: setting-value are placeholders. Like if you want to put a setting there. Such as:
```
$('.myclass').slick({
   slidesToShow: 3
// ^ setting name ^ setting value
});
```

**Comment by kenwheeler** [comment]
http://jsfiddle.net/zvsq2qsm/1/
