### ISSUE TITLE
Suspected infinite loop on responsive

### ISSUE THREAD

**Issue by Bloafer** [kenwheeler/slick#1326]
This bug affects all browsers (Chrome crashes) and is more a user error than a code error. The error is caused by setting `slidesToScroll: 0`. Setting this to `slidesToScroll: 1` fixes the issue (obviously).

To recreate the Chrome crash you need to make browser wider, going from the responsive 640px width to any width larger than 640px.

I suspect it is realated to this section of the code:

https://github.com/kenwheeler/slick/blob/1.5.3/slick/slick.js#L1063-L1067

Where the breakpoint is never incremented.

JSFiddle: https://jsfiddle.net/3kh7zgx8/

**Comment by simeydotme** [comment]
Hehe. Yeh, kinda silly to have a slider scroll `0` slides... but also there _should_ probably be a check for dummies :confounded: - I think, maybe, during `init()` or `refresh()` that the plugin detects `slidesToScroll` is `0`; then just `unslick()` ?

**Comment by Bloafer** [comment]
Was this fixed?

**Comment by kenwheeler** [comment]
Dont set slidesToScroll to 0

**Comment by Bloafer** [comment]
I know how to stop it happening, but I think that preventing a user from causing this fail state would be much more helpful. Would you not agree?
