### ISSUE TITLE
instant animation from slide to slide

### ISSUE THREAD

**Issue by PankovAlxndr** [kenwheeler/slick#1329]
Please add the following option:

When the slider member, such as the elements(slides) 7, and as seen navigation dots ..

For example, the active second dot (second slide), and when I'm clicking on dot 6 (6 slide).

The slider must show animation from 2 to 6 immediately, that is, I should NOT see an animation of 2 - 3 - 4 - 5 - 6. I should get just 2 - 6 as example from the last to the first slide, but the opportunity to make any slide number.

Thank you.
Add this option, or tell me how to do

Sorry for my English!

**Comment by simeydotme** [comment]
That's not _really_ how a carousel works... you can kind-of get this feature by using the `fade: true` option.
