### ISSUE TITLE
Responsive settings (dots, vertical) issues when initialise on responsive environment 

### ISSUE THREAD

**Issue by kakt00c** [kenwheeler/slick#1332]
Hello! 
After issue https://github.com/kenwheeler/slick/issues/1276 was fixed, i found out some more issues on responsive settings.. 

Steps to reproduce: 
1. go to http://codepen.io/anon/pen/GJoBxx
2. render it in browser with width more than 900px: vertical carousel works perfect
3. make window smaller than 900px without reload: carousel becomes horizontal and got dots as expected, so still works super good
4. reload page in browser with width less than 900px: carousel is not visible, when slide via arrows it is strangely appears and disappears... no dots are presented

Additional info: 
when init page on less than 900px screen, and than resize to wider screen and resize back to small -- issue  disappears...
Maybe i configure something in a wrong way? i have used 1.4 version previously, and only asNavFor issue appeared to me, maybe API for 1.5.3 has been changed somehow? 

thank you

**Comment by simeydotme** [comment]
Hi @kakt00c , Please refer to this:
http://jsfiddle.net/simeydotme/yxq5bumc/3/

I noticed this too, it was a silly oversight with the responsive checkoutpoints.
https://github.com/simeydotme/slick/commit/82700f4b6eef0fd042b61089ed32cfbfefa344e7

If you [take the ___unminified___ code from master branch](https://raw.githubusercontent.com/kenwheeler/slick/master/slick/slick.js), it fixes the issue. I am very sorry! :bow: - @kenwheeler is super busy and I don't have the ability to release 1.5.4.

Simon.

**Comment by kakt00c** [comment]
That works good for me! Thank you so much! 
You are amazing.
