### ISSUE TITLE
centerMode w/ infinite issue

### ISSUE THREAD

**Issue by jaalahr** [kenwheeler/slick#1333]
1. Will there be an option added for removing left padding for first slide when using "centerPadding" for those who are using `infinite: false`?
2. When setting `slidesToShow: 2` with `slidesToScroll: 1`, the translate3d increases as if there's an extra slide, any way around this?
https://jsfiddle.net/syixlol/fmo50w7n/2/

**Comment by ctotogo** [comment]
I'm having exactly the same issue as jaalahr's point #2 above, except my slidesToShow is 3 and what appear to be 2 empty slides appear at the end.

**Comment by balajigumpena** [comment]
I am facing the same problem, does any have solution for this ?

**Comment by kenwheeler** [comment]
this is a core issue. If you have slidesToScroll 1, it is going to make sure you can reach that index.
