### ISSUE TITLE
Not Loading Responsive Settings After Page Refresh in Ember.js

### ISSUE THREAD

**Issue by corinnekunze** [kenwheeler/slick#1335]
This seems like basic functionality and I can't imagine the single page-ness of Ember is causing this to happen. Things are working perfectly upon page browser resize. 

```
// Ember code
export default Ember.Component.extend({
  didInsertElement: function() {

// slick
    this.$('.carousel').slick({
      centerMode: true,
      centerPadding: '0px',
      slidesToShow: 5,
      slidesToScroll: 1,
      focusOnSelect: true,
      responsive: [
        {
          breakpoint: 1199,
          settings: {
            slidesToShow:4,
            slidesToScroll: 1,
            centerMode: false
          },
        },
        {
          breakpoint: 991,
          settings: {
            slidesToShow:3,
            centerMode: false
          }
        },
        {
          breakpoint: 757,
          settings: {
            slidesToShow:1,
            centerMode: true,
            centerPadding: '40px',
            arrows: false
          }
        },
      ]
    });

  }
});
```

What are my options here? This seems like an issue if it's not detecting the window is less than these breakpoints and using those settings. It is currently loading the default options then will load the responsive settings when I resize or click the next or previous slide buttons.

**A possible solution:** If I could use an init callback to call whatever is happening in those resize or next methods that could be a solution here.

**Comment by simeydotme** [comment]
Hi, which version of Slick are you using? :)
https://jsfiddle.net/simeydotme/r0em93vx/1/ - this fiddle is working fine (latest unminified-code on master) ... if you could try to plug in a little bit of your ember code in there, we can see what is up :)

Simon.

**Comment by corinnekunze** [comment]
@simeydotme Thanks for the support. I rewrote everything in a jsBin - I fear it's something to do with our environment because everything looks to be working correctly in the jsBin. 
I'll share the jsBin here in case anyone wants to see how to get this plugin working in Ember -
http://emberjs.jsbin.com/bepadiniwi/1/edit?html,css,js,output

Thanks!

**Comment by corinnekunze** [comment]
To anyone who is coming across this problem in Ember, this was because the carousel wasn't rendered initially because it was wrapped in an if statement. For whatever reason, that caused it not to resize correctly on refresh.

I was able to follow my possible solution above by adding a callback on init to resize the carousel. Like so:

```
export default Ember.Component.extend({
  didInsertElement: function() {
  // init callback to resize when didInsertElement
    this.$().on('init', function(event, slick) {
      slick.resize();
    });

    this.$().slick({
      // slick settings here
    });
  }
});
```

**Comment by simeydotme** [comment]
Thanks @corinnekunze -- it looks a little hacky, and I've seen other issues with this kind of thing happening in backbone, too... seems these MV* frameworks do interesting things to make rendering fast, but it doesn't help when you have very complex box-model calculations like in Slick :(

Hope it works out OK for you!
Si.
