### ISSUE TITLE
Responsive slides with slidesToShow is not working properly.

### ISSUE THREAD

**Issue by dev-tomrain** [kenwheeler/slick#1336]
I have a scenario where I will showing 5 items on single slide. So totally two slides with 10 items. Inorder to show properly I wrote few breakpoints as below. But when I view in width of **768px** my li's width is **30125px** and it is completely breaking the slider. How to fix this?

$('.featured-slide').slick({
                slide : 'li',
                dots: false,
                infinite: true,
                slideshow : 5,
                swipe : true,
                slidesToScroll: 1,
                slidesToShow: 5,
                responsive: [
                {
                    breakpoint: 1200,
                    settings: {
                        slidesToShow: 5,
                        slidesToScroll: 5,
                    }
                },
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 4,
                    }
                },
                {
                    breakpoint: 800,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                    }
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2,
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                    }
                }]
            });

**Comment by simeydotme** [comment]
Please read the https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown and create a JSFiddle to reproduce your error.

Simon.
