### ISSUE TITLE
On load/refresh flicker/positioning bug.

### ISSUE THREAD

**Issue by zhrance** [kenwheeler/slick#1338]
When you load or refersh http://kenwheeler.github.io/slick/ you see the sliders flicker/positioning. How can you prevent this? It's kinda ugly. I tried to fix it with lazy loading or with CSS (overflow:hidden). But I don't get a satisfying result. 

Kind regards, Niels

**Comment by simeydotme** [comment]
Set your CSS to hide slides until the container gets `slick-initialized`. Your own implementation is advised.

https://github.com/kenwheeler/slick/issues/779 <-- see here for a solution.
