### ISSUE TITLE
Add Slides-title to dots instead of numbering

### ISSUE THREAD

**Issue by luxmedia** [kenwheeler/slick#1340]
I am planning to style the dots-navigation in block-elements with small titles of the slides in it. 
So the slide-navigation is less random and more predictable for the user.

But currently the text inside of the dots-nav is just a simple numbering. I think it would be more accessible to display semantic text (if there is text provided in the slides). The text could be fetched from the slides "title" attribute or something else.
This would be an enhancement and the text could also be used as an aria-attribute for the dots.

regards
Volker

**Comment by simeydotme** [comment]
http://jsfiddle.net/simeydotme/9nm4ctv9/
Please check this fiddle out for some inspiration on how you might achieve your goal! :)
As for screen-readers, I think that's covered and actually the "paging" is not "content" that should be read, anyway :)

Simon.
