### ISSUE TITLE
What is the best way to implement multiple sliders with custom styles in a single page app?

### ISSUE THREAD

**Issue by alexduan** [kenwheeler/slick#1341]
Have PageA with CarouselA that overrides a number of slick styles (slick-slider, slick-list, etc.)

PageB with CarouselB also overrides a number of slick styles.

What's the best way to actually have those styles applied without conflicting with each other?

**Comment by simeydotme** [comment]
this is a pretty general web-dev question, not a issue with the slider :)
thanks for contributing, and please read https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown for hints on how you can contribute further! :)

Try this:

> __Javacsript__
```js
  $(".carouselA").slick({});
  $(".carouselB").slick({});
```  

> __Styles__
```css
/* Carousel A */
  .carouselA.slick-slider { }
  .carouselA.slick-list { }
  .carouselA.slick-slide { }
/* Carousel B */
  .carouselB.slick-slider { }
  .carouselB.slick-list { }
  .carouselB.slick-slide { }
```

or if you're using SCSS

> __Styles__
```scss
/* Carousel A */
  .carouselA {
    > .slick-slider { }
    > .slick-list { }
    > .slick-slide { } 
}
/* Carousel B */
  .carouselB {
    > .slick-slider { }
    > .slick-list { }
    > .slick-slide { } 
}
```

Best of luck :wink: ,
Simon.

**Comment by ivan-vilches** [comment]
Check this hope help, when are multiples instances take the advantage of $(this)  .
http://jsfiddle.net/81t4pkfa/2/
