### ISSUE TITLE
Fade option buggy when content is different sizes

### ISSUE THREAD

**Issue by danieldunderfelt** [kenwheeler/slick#1342]
Hi!

I came across this when trying to use slick on a bunch of images with different sizes without their own slide background:

http://jsfiddle.net/s43ybj7x/4/

When the fade option is enabled and some slides' content is smaller than the previous, the previous content stays in the background and disappears after a split second without a transition. Basically only the new content has the fade effect, while the old content disappears once the fade is complete.

Would it be possible to enable the fade effect for the outgoing slide as well?

Thanks!

**Comment by ethanclevenger91** [comment]
Was running into this issue today as well with items that don't have a background image and are rather just text.

http://codepen.io/ethanclevenger91/pen/bdpmLg

Created a pull request

**Comment by ethanclevenger91** [comment]
This wasn't in the latest hotfix (or at least not in the minified version) - any way we can get a new build? I don't know what the procedure is for this so figured I'd just petition.

**Comment by walpek** [comment]
+1 Would love to see this issue fixed

**Comment by kenwheeler** [comment]
Getting a release pushed soon, sorry guys
