### ISSUE TITLE
pauseOnHover never resumes

### ISSUE THREAD

**Issue by chrisnicholson** [kenwheeler/slick#1345]
A carousel which is set to autoplay and default pauseOnHover (true), after mousing over and then off the animation doesn't resume. This is actually reproducible on the 'autoplay' example on the [demo page](http://kenwheeler.github.io/slick/). Chrome 42 Win 8.1.

Sample code:

    $('#header-carousel').slick({
        autoplay: true,
        autoplaySpeed: 6500,
        dots: true,
        slidesToShow: 1,
        infinite: true,
        pauseOnHover: true,
    });

**Comment by chrisnicholson** [comment]
I see the update history now, fixed by grabbing the latest version.

**Comment by simeydotme** [comment]
:+1: sorry for the confusion! :)
