### ISSUE TITLE
On page load slider is minaturized

### ISSUE THREAD

**Issue by MAGPerficient** [kenwheeler/slick#1346]
For some reason the slider is in miniature on my page load. Then as the images slide it bumps up in size until it is the correct size. Not sure what is going on here has anyone else experienced this?

I've attached two images
1) The slider going through the size changes as the images rotate
2) The slider once it has reached full size which is how it should show up on the page

If I click refresh it eventually seems to correct itself. It's like something is going wrong in the load of the slider.

Thanks in advance for any help.

Mike

1)
![slide1](https://cloud.githubusercontent.com/assets/5198179/7634136/e676e380-fa26-11e4-9515-d190bc228bd8.jpg)

2)
![slidecorrect](https://cloud.githubusercontent.com/assets/5198179/7634157/00926924-fa27-11e4-9920-862023be7c9b.png)

**Comment by simeydotme** [comment]
That's very strange, @MAGPerficient ... can you try to reproduce this in a JSFiddle (as mentioned in the https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown ) :smile: - once you do that I can inspect the code and see what's happening.

Si.

**Comment by MAGPerficient** [comment]
Thanks Si,

Thanks for getting back to me. I'm still trying to duplicate it in JSFiddle BUT if this helps...I noticed in the Dev tools that the values in the "slick-track" div and the "slick-slide" divs recalculate their sizes as the control slides from image to image (again until it's the correct size). I screen capped this and have 3 images (all in one) and the elements and sizes are in the red rectangles. Maybe that'll help until I get JSFiddle to reproduce the error.


Cheers, 

Mike

![slickissues](https://cloud.githubusercontent.com/assets/5198179/7639027/10e6202a-fa47-11e4-8d41-685734a81a95.png)

**Comment by ClaudioGraciolli** [comment]
Hi guys, was there a solution for that? I bumped into the same issue and I don't seem to be finding the glitch...

**Comment by MAGPerficient** [comment]
Hi Claudio,

I switched over to another slider and experienced the same issue. I then noticed that a <div> higher up the chain had "position:absolute;" applied to it. I changed that to "position:relative;" and I believe that fixed the issue for me. Hopefully you'll find something similar in your markup.

Cheers,

Mike

**Comment by ClaudioGraciolli** [comment]
Thanks for the tip, Mike. I have played with positions before but no happy ending just yet. Will check them over again.

Cheers,

Claudio
