### ISSUE TITLE
Slight overflow in single image mode

### ISSUE THREAD

**Issue by aendrew** [kenwheeler/slick#1347]
I'm using Slick for a full-screen carousel, with differently-sized (but fairly high-res) images scaled down via CSS to fit within a certain area. Alas, for some reason, Slick isn't sizing the track properly, and occasionally there's a pixel or two of overhang on one of the sides, particularly if the current image is smaller than the previous. See screenshot:

![screen shot 2015-05-14 at 17 51 14](https://cloud.githubusercontent.com/assets/185041/7636891/eb77e4b6-fa61-11e4-96af-222ced89dc86.png)

I've fixed this somewhat by adding 15px padding to .slick-slide, but now it cuts off part of the image.

Any thoughts? Thanks!

**Comment by simeydotme** [comment]
Are you viewing this on a retina screen, or a retina emulator (in chrome, for example) ? -- Also there's not enough information here for this to be considered a bug report, please feel free to read the contribution guidelines and reopen, or check out one of the support channels.

Simon.

**Comment by aendrew** [comment]
@simeydotme Ah, apologies, totally missed the CONTRIBUTING.md file. I've built a test-case at http://jsfiddle.net/aendrew/67wdcy3q/3/, but it's working as expected, so it has to be something else I've done wrong. Thanks for getting back to me!

**Comment by simeydotme** [comment]
No Problem, @aendrew  -- I'm sorry you've got an errant bug, it could still be a conflict with your code and Slick and still require an API update to accomodate, so please let us know if/when you find the issue! :) ... possible scaling/zooming/retina if you ask me... because it doens't look like a pixel in your screenshot, more like a sub-pixel

**Comment by aendrew** [comment]
@simeydotme Interesting, will take a closer look next chance I get. 

It should be noted I'm using Slick for like 6 ft x 3 ft tall displays in the lift lobbies at The Sunday Times here in London, and it looks *crazy* good on them (which is why the pixel dimensions in that Fiddle are like 1452px by 932px lulz). :smile:

**Comment by simeydotme** [comment]
ahhh, pretty sweet! ... even more chance of there being some scaling / pixel muffing going on. It happens to me all the time when viewing on a retina-emulator. (it's a browser-rendering issue).
You can always add a 1/2 pixel padding to the slide-wrapper :smile:
