### ISSUE TITLE
Image caption

### ISSUE THREAD

**Issue by pfitz** [kenwheeler/slick#1351]
I am a fresh switcher from Foundations orbit to slick.js. I am trying to add captions to my slides. Is this possible with slick?

**Comment by simeydotme** [comment]
Yes.

**Comment by liamreoch** [comment]
... how?

**Comment by nominalaeon** [comment]
Slick works like this, you've got a parent container with a bunch of child containers. When you run Slick on the parent, all of the children become the slides. So you can have whatever you want inside of each child. If you want captions for images, just put that in the child's markup.

    <div class="parent">
        <div class="child">
            <img/>
            <caption></caption>
        </div>
        <div class="child">
            <img/>
            <caption></caption>
        </div>
        <div class="child">
            <img/>
            <caption></caption>
        </div>
    </div>
