### ISSUE TITLE
Not limiting Slick children to visible tags.

### ISSUE THREAD

**Issue by andrew-rival** [kenwheeler/slick#1353]
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L491-L493 is checking against slick-cloned, but it's ignoring the options.slide setting.

Fixed in https://jsfiddle.net/simeydotme/50kp465g/2/ but not regression tested.

**Comment by simeydotme** [comment]
Hmmm, here's the commit where it happened:
https://github.com/kenwheeler/slick/commit/9d13d6abc4ab4e05948b5bab47b2574fad9c9c64#diff-eaaa72f2e5f1d4974e4f1ae902717908L476

.. @kenwheeler was this a mistake, or do you remember why the `_.options.slide` was removed from the `buildOut` method (the highlighted line) ? :confused:

**Comment by cansozeri** [comment]
If you remove _.options.slide + the custom arrows are not work as expected .. 
https://github.com/kenwheeler/slick/issues/1204

**Comment by simeydotme** [comment]
:+1: thanks for adding your issue for reference, @cansozeri ! :)
