### ISSUE TITLE
Lazy loading opacity problem

### ISSUE THREAD

**Issue by colorfool-me** [kenwheeler/slick#1354]
When you show more than one image e.g. by using "slidesToShow: 2" and also activate lazy loading "lazyLoad: 'ondemand'", then the inline opacity value of the first image is not adapted and stays 0. The image itself is loaded.

Example setting:
```js
$('#xyz').slick({
	infinite: true,
	slidesToShow: 1,
	slidesToScroll: 1,
	arrows: false,
	lazyLoad: 'ondemand',
	responsive: [
	    {
	        breakpoint: 420,
		settings: {
		centerPadding: '40px',
		slidesToShow: 1
	    }
	 },
	 {
		breakpoint: 1025,
		settings: {
		centerPadding: '40px',
		slidesToShow: 2
	 }
	}
      ]
});```

**Comment by victorserpac** [comment]
Same Issue here

**Comment by simeydotme** [comment]
Might affect #1349 :disappointed_relieved:

**Comment by colorfool-me** [comment]
@simeydotme sorry, I didn't see that! My fault! And since I didn't mention it yet, slick is by far the best slider I found so far, great work!
I created a JS fiddle here:
https://jsfiddle.net/h1p4d3m5/9/
When you move back & forth some images stay just on opacity: 0 when having 2 slides shown at the same time. Thank you in advance. If you need more information, just let me know!

**Comment by simeydotme** [comment]
@colorfool-me , please check out this Fiddle... does it work OK for you?
I noticed that there seemed to be a race-condition for cloned-slides in the lazy-load function. 

https://jsfiddle.net/simeydotme/h1p4d3m5/10/

**Comment by colorfool-me** [comment]
@simeydotme Looks great!

**Comment by simeydotme** [comment]
Can you do me a favour and test it on all the browsers/devices you have available, and let me know the results? :smiley: 

I will do the same, and if it works OK (I'll test a bunch of responsive options, too) I'll merge it in. :+1:

**Comment by colorfool-me** [comment]
I checked it on latest Safari, Chrome & Firefox on Mac

**Comment by colorfool-me** [comment]
And latest Safari on iOS8. All looks fine!

**Comment by simeydotme** [comment]
OK, nice.
I checked on Windows:
- Chrome
- FF
- Safari
- IE 8-11

and Android
- Chrome

All looks good. I'll get to merging :)

**Comment by colorfool-me** [comment]
Great! Thanks for the quick fix! Keep up the great work!

**Comment by simeydotme** [comment]
Applied on master, unminified file.
You'll have to wait for @kenwheeler to bump next version to get the minified files :)
