### ISSUE TITLE
Sliders with distinct arrows colors

### ISSUE THREAD

**Issue by henriquechehad** [kenwheeler/slick#1355]
Hello,

How can I use two sliders with distinct arrows colors? 

Example: 
First slider: white arrows; 
Second slider: black arrows.

I found a way to change a color of all arrows, overwriting the CSS, but in this case don't resolve my need. I would set a color to each slider.

**Comment by simeydotme** [comment]
Please read: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown , Someone will be willing to help you in the chatroom, or on Stackoverflow :)

Simon.
