### ISSUE TITLE
adapt animation speed when swiping

### ISSUE THREAD

**Issue by gerritvanaaken** [kenwheeler/slick#1359]
If a slide animation is very slow, like 1500ms, you cannot properly swipe it on mobile. Once your finger is off the screen, the animation gets really slow, and quickly doing more than one swipe (quickly flipping through a gallery) is not satisfying. See the last slider at the bottom here: http://scouter.de

What would be useful:

1) Measure the speed of the user’s swipe
2) apply this speed to the animation speed, overwriting the "speed" given in options

Alternatively:

– make two different speed options: 
1) "speed", which will be triggered by automatic slide change.
2) "swipeSpeed", which is the speed of the anination when triggered by user interaction.

Do you see my point? Thanks!!

**Comment by ralfger** [comment]
+1

**Comment by nicklocicero** [comment]
+2

**Comment by ihorhranetskyi** [comment]
Can smb tell me if this feature was added?
