### ISSUE TITLE
Change arrow colors?

### ISSUE THREAD

**Issue by benjino** [kenwheeler/slick#1362]
How do you change the colors of the prev/next arrows?

**Comment by simeydotme** [comment]
css.

**Comment by benjino** [comment]
Yah, I tried that with .slick-prev and .slick-next and even added !important and it didn't work.

**Comment by simeydotme** [comment]
if you inspect the code, I believe the color needs to be added for `.slick-prev:before` :) - the icon is added via psuedo-element. :bow:

**Comment by benjino** [comment]
Thanks. When I inspected it, it wasn't indicating ":before" and I had to add !important as well. Thanks again!

**Comment by buck3000** [comment]
.slick-prev:before {
      color: some-color;
    }
    .slick-next:before {
      color: some-color;
    }

**Comment by hari03** [comment]
Wonder why this isn't mentioned in the documentation!

**Comment by Hamza-developer** [comment]
> ```
> .slick-prev:before {
>   color: some-color;
> }
> .slick-next:before {
>   color: some-color;
> }
> ```

color isn't applying. background-color applying though

**Comment by robwent** [comment]
I think the icon/arrow is actually the circle with a transparent part cut out of the center. So the only way to change it would be to change the background which would then show as a square behind the circle.

I think it's easiest to add your own arrow html and then use the prevArrow and nextArrow options to use the custom ones.

**Comment by vihar** [comment]
This one will work :)

`.slick-prev:before {
  color: red !important;
  background-color: #eee;
}
.slick-next:before {
  color: red !important;
  background-color: #eee;
}`

**Comment by carloslederman** [comment]
> I have included these lines into my style.css file, and have not worked. My inclusion was 

`/*.slick-prev:before {color: red !important;background-color: #eee;}
/*.slick-next:before {color: red !important;background-color: #eee;}`

Have I made any mistake?

Thank you!

**Comment by AlbertoPaulPopescu** [comment]
<template>
  <div>
    <VueSlickCarousel v-bind="settings">
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <template #prevArrow="arrowOption">
        <div class="custom-arrow">
          {{ arrowOption.currentSlide }}/{{ arrowOption.slideCount }}
        </div>
      </template>
      <template #nextArrow="arrowOption">
        <div class="custom-arrow">
          {{ arrowOption.currentSlide }}/{{ arrowOption.slideCount }}
        </div>
      </template>
    </VueSlickCarousel>
  </div>
</template>

<script>
import VueSlickCarousel from "vue-slick-carousel";
import "vue-slick-carousel/dist/vue-slick-carousel.css";
// optional style for arrows & dots
import "vue-slick-carousel/dist/vue-slick-carousel-theme.css";

export default {
  name: "MyComponent",
  components: { VueSlickCarousel },
  data() {
    return {
      settings: {
        dots: true,
        infinite: true,
        initialSlide: 2,
        speed: 500,
        slidesToShow: 3,
        slidesToScroll: 1,
        swipeToSlide: true
      }
    };
  }
};
</script>

<style scoped>
.slick-prev:before {
  color: red !important;
  background-color: rgb(9, 185, 177);
}
.slick-next:before {
  color: red !important;
  background-color: rgb(9, 185, 177);
}
</style>

**Comment by AlbertoPaulPopescu** [comment]
`<template>
  <div>
    <VueSlickCarousel v-bind="settings">
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
      <template #prevArrow="arrowOption">
        <div class="custom-arrow">
          {{ arrowOption.currentSlide }}/{{ arrowOption.slideCount }}
        </div>
      </template>
      <template #nextArrow="arrowOption">
        <div class="custom-arrow">
          {{ arrowOption.currentSlide }}/{{ arrowOption.slideCount }}
        </div>
      </template>
    </VueSlickCarousel>
  </div>
</template>

<script>
import VueSlickCarousel from "vue-slick-carousel";
import "vue-slick-carousel/dist/vue-slick-carousel.css";
// optional style for arrows & dots
import "vue-slick-carousel/dist/vue-slick-carousel-theme.css";

export default {
  name: "MyComponent",
  components: { VueSlickCarousel },
  data() {
    return {
      settings: {
        dots: true,
        infinite: true,
        initialSlide: 2,
        speed: 500,
        slidesToShow: 3,
        slidesToScroll: 1,
        swipeToSlide: true
      }
    };
  }
};
</script>

<style scoped>
.slick-prev:before {
  color: red !important;
  background-color: rgb(9, 185, 177);
}
.slick-next:before {
  color: red !important;
  background-color: rgb(9, 185, 177);
}
</style>`

**Comment by AlbertoPaulPopescu** [comment]
![image](https://user-images.githubusercontent.com/63293696/129988556-a06a3de7-32fb-4f83-a634-f78ab122d62a.png)

**Comment by Gretchen5** [comment]
We're using two slick sliders on a single site so we needed to be able to have two sets of arrows with different colors - one set is black and one white. We added our own svg images (black color). And for the white, we copied the svg images, changed the color within the svg file, and then used this code in the css file: 

`.component--past-trips .slick-prev:before {
	content: url("../css/images/left_arrow_white.svg") !important;
}

.component--past-trips .slick-next:before {
	content: url("../css/images/right_arrow_white.svg") !important;
}`

**Comment by rafatali786** [comment]
> .slick-prev:before {
>   color: some-color;
> }
> .slick-next:before {
>   color: some-color;
> }

Correct thanks <3

**Comment by rafatali786** [comment]
> 

Yes Excatly what was missing on my slick, Thanks !

**Comment by rafatali786** [comment]
<link rel="stylesheet" type="text/css" href="http://kenwheeler.github.io/slick/slick/slick-theme.css"/>
try including this and then try
