### ISSUE TITLE
Disable swiping on element

### ISSUE THREAD

**Issue by anteksiler** [kenwheeler/slick#1363]
I am using a range slider inside one of the carousel element.

Of course, swiping causes both elements to slide :) I would like to prevent sliding on a certain element inside the carousel.

**Comment by simeydotme** [comment]
This is not a bug with Slick :)
Please read the contribution guidelines.

Simon

**Comment by anteksiler** [comment]
@simeydotme This was more like a feature request :)

**Comment by simeydotme** [comment]
I understand, but there's many avenues to explore for your scenario.. it's best to read the contribution guidelines, and also spend some time to search for other issues like this :smile: -- im alsmot certain it's been asked multiple times before. :smiley:

**Comment by apoorva-shah** [comment]
Hello @anteksiler, so do you find any solution for disable swipe on some element?

Because i am using amcharts in slick slider and i want to disable swipe on chart div. thanks!
