### ISSUE TITLE
samsung galaxy note 4 s-pen swipe issue

### ISSUE THREAD

**Issue by ergec** [kenwheeler/slick#1366]
I'm not sure if this is a bug or by it's design but galaxy note 4 s-pen swipe gesture makes slides to stuck in the middle of the slider. Doing swipe using fingers works as expected.

![screenshot_2015-05-19-21-06-59](https://cloud.githubusercontent.com/assets/422056/7710328/c68fa752-fe6b-11e4-8b13-b224a8b2adc6.png)

**Comment by kenwheeler** [comment]
Thats odd. I don't have the hardware to test this. Let me know if you figure anything out.
