### ISSUE TITLE
Does not work on Opera Mini

### ISSUE THREAD

**Issue by rileyjshaw** [kenwheeler/slick#1368]
On Opera Mini, the carousel pins to the last slide(s) and won't move. Swiping, clicking the indicator dots, & next / previous buttons don't work.

**Comment by kenwheeler** [comment]
Are you getting any console errors?

**Comment by rileyjshaw** [comment]
Not sure how to check, sorry!

**Comment by leggomuhgreggo** [comment]
I think to get console info on opera mini you might have to get [micro emulator.](https://stackoverflow.com/questions/2594450/how-to-debug-on-opera-mini)

Opera mini [doesn't support certain events](https://dev.opera.com/articles/opera-mini-and-javascript/#unsupporteddom); so I wonder if it's related to that.

**Comment by kenwheeler** [comment]
@leggomuhgreggo after looking at that list, does ANYTHING work on opera mini?

**Comment by leggomuhgreggo** [comment]
Opera mini is nuts. So, opera mini loads all page data through a proxy server that compresses it into a custom binary to increase speed (I think google is trying something similar, actually). What I didn't know is that something about the way they're doing it causes all these weird [curtailments on JS execution.](https://en.wikipedia.org/wiki/Opera_Mini#JavaScript_support)

>When browsing the Web in Opera Mini mode, JavaScript is processed by the proxy server, and is merely rendered on the device. This limits interactivity. Scripts cannot be run in the background on the device. If a script is paused (on the server), the browser must communicate with the server to unpause it. JavaScript will only run for a couple of seconds on the Mini server before pausing, due to resource constraints.[53]

>According to the documentation for Opera Mini 4, before the page is sent to the mobile device, its onLoad events are fired and all scripts are allowed a maximum of two seconds to execute. The setInterval and setTimeout functions are disabled, so scripts designed to wait a certain amount of time before executing will not execute at all.[54] After the scripts have finished or the timeout is reached, all scripts are stopped and the page is compressed and sent to the mobile device. Once on the device, only a handful of events are allowed to trigger scripts

**Comment by rileyjshaw** [comment]
@kenwheeler lol, didn't look into this enough when creating the ticket. I think that it's fine to close this, though defensively applying the plugin might be something worth looking into.
