### ISSUE TITLE
adaptiveHeight + container animation

### ISSUE THREAD

**Issue by devolkpl** [kenwheeler/slick#1369]
Hi everyone,

is there any chance to disable height animation when adaptiveHeight is set to true? I figured out that is not css animation but jquery animate() or something. Any ideas?

**Comment by aliciaj** [comment]
I have adaptiveHeight set to true and it doesn't animate, I was hoping to figure out how. It just jumps up and down.

**Comment by michaltowilk** [comment]
Maybe with speed set to "0"? 
Anyway I solved my problem in slick core. AdaptiveHeight uses animate({ },speed) to change container height. I just replaced .animate() with .height()

**Comment by aliciaj** [comment]
Thats weird because setting to 0 does the same thing mine does already with a speed setting, no animation. It just flickers to the new height.

**Comment by kenwheeler** [comment]
Adding as a feature

**Comment by pimschaaf** [comment]
+1

In the meantime, I think @michaltowilk suggests the following:

```
Slick.prototype.animateHeight = function() {
        var _ = this;
        if (_.options.slidesToShow === 1 && _.options.adaptiveHeight === true && _.options.vertical === false) {
            var targetHeight = _.$slides.eq(_.currentSlide).outerHeight(true);
            _.$list.height(targetHeight); //set height, instead of animate
        }
    };
```

On https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L235

**Comment by xhuljan123** [comment]
Try this css 
`
.slick-list {
        transition: all 0.5s ease-in-out;
}
`
