### ISSUE TITLE
Unslick in responsive settings doesn't re-initialise when condition doesn't match anymore

### ISSUE THREAD

**Issue by joebeaver89** [kenwheeler/slick#1372]
See http://jsfiddle.net/fu85qbqL/1/

Resize result window above 700px, unslick happens, resize back below 700px and I would expect it to reinitialise the slider. Should this be the case?

**Comment by axten** [comment]
some probleme here

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/releases/tag/1.4.0
:)

**Comment by joebeaver89** [comment]
Shame. Guess I'll have to figure out a different way of doing it. Thanks for the pointer @simeydotme

**Comment by mvg21** [comment]
This solution worked for me:


```
var mq = window.matchMedia( "(min-width: 992px)" );
var slider = $('.slick-projekte');

function initSlider(){
	if (mq.matches) {
		if(!slider.hasClass('slick-initialized')) {
			console.log('slick start init');
			slider.slick({
				lazyLoad: 'ondemand',
				slidesToShow: 1,
				slidesToScroll: 1,
				speed: 1200,
				pauseOnHover: false,
				autoplay: false,
				appendArrows: 'footer',
				prevArrow: '<a href="##" class="slick-prev hidden-xs"></a>',
				nextArrow: '<a href="##" class="slick-next hidden-xs"></a>',
			});
	  	}
	}
	else{
		if(slider.hasClass('slick-initialized')){
			slider.slick('unslick');
		}

	}
}

//delay for calling initSlider only when resize is finished
var delay = (function(){
 	var timer = 0;
 	return function(callback, ms){
   	clearTimeout (timer);
   	timer = setTimeout(callback, ms);
 	};
})();

//call initSlider after window resize
$( window ).resize(function() {
	delay(function(){
		initSlider();
   }, 200);
});
```

**Comment by romannikiforov** [comment]
`const settings = {
        
        responsive: [
            {
                breakpoint: 900,
                settings: {
                    slidesToShow: 3
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2
                }
            },
            {
                breakpoint: 420,
                settings: "unslick"
            }
        ]

    };

    
const sl =  $('.slider').slick(settings);
      
$(window).on('resize', function() {
   if( $(window).width() > 420 &&  !sl.hasClass('slick-initialized')) {
         $('.slider').slick(settings);
    }
})`
