### ISSUE TITLE
Bug when I have the slider in the accordion with Display:none the slider doesn't initiate the image height

### ISSUE THREAD

**Issue by xtianus79** [kenwheeler/slick#1373]
So, looking for a solution but hard to find.

We have figured out that it is the display none of the slider when the slider is in the accordion. so what happens is that the slider height or image doesn't commence the correct height. what happens is the image is basically hidden and the dots and arrows are left behind. After the first slider is selected, via the dots or arrows, then it pops into place.

Any help is appreciated.

**Comment by nominalaeon** [comment]
Could you make a Codepen of the issue? Without seeing the accordion code it's hard to say, but display: none elements have a height of 0. Is it possible to use visibility: hidden instead? Hidden elements still have their dimensions.

**Comment by xtianus79** [comment]
well that is how the jquery animation works is by toggling display none to display block... I believe it is slidetoggle we are using.

**Comment by xtianus79** [comment]
here is site live... we have another carousel in place now until we get a fix.

**Comment by simeydotme** [comment]
@nominalaeon is correct, you cannot initialise the carousel inside a hidden parent and expect it to calculate heights/widths correctly/at all.

You just need to use the accordion's event system to initialise the slider after it expands :)

**Comment by nominalaeon** [comment]
Also, that's a lot of content for one page. My phone has a really hard time, and ie8 may timeout on you all together

**Comment by nominalaeon** [comment]
...it's very beautiful on my desktop though!

**Comment by xtianus79** [comment]
@nominalaeon thank you.... our team worked hard on it.

**Comment by xtianus79** [comment]
Oh and lol hence the accordion with the sliders wrapped in there. bootstrap carousel works but it is not touch out of the box like your slider is.

**Comment by xtianus79** [comment]
I don't know. Bootstrap carousel works without this issue. Are you able to come up with anything else?

**Comment by nominalaeon** [comment]
Slick can't size items that are set to display: none. You need to initialize each carousel as the accordion brings it into view. http://getbootstrap.com/javascript/#collapse-events

**Comment by xtianus79** [comment]
@nominalaeon so I tried your method of initializing when the accordion is brought into view.  It works at first but then upon opening and closing it reverts back to the same issue of the initial slide being collapsed on itself. lol I can't think of anything else.

**Comment by nominalaeon** [comment]
You'll want to destroy the sliders when the accordion event hides them from view, then run init every time they're shown. Check out the "unslick" method

**Comment by Ark74** [comment]
I'm kind of new with CSS/jQuery but I wonder if the parent id could set to heigh:0px/1px; then hide slider id with overflow:hidden in order to maintain its size while disappearing from sight later with .click (jquery) change the parent div to height:auto/100%, for the slider to reveal on its size.

Am I talking nonsense?

**Comment by jafaruddeen** [comment]
Use
$('.your-class').slick('setPosition');

Example:- https://codepen.io/dmondma/pen/WNbJGdj
