### ISSUE TITLE
Dots and Arrow showing up without slick font

### ISSUE THREAD

**Issue by panchohinojosa** [kenwheeler/slick#1374]
The arrows and dots didn´t work, just plain text vas displayed.

Fixed it by changing the content in the theme.css in the prev, next and dot clasess. Instead of the arrow/dot in the content property I used the unicode value .

Dont know if this is a bug, beacuse its only happenig in some sites which are in spanish, so I concluded it had to do with the charset or something used to ensure accents are being displayed correctly. So I here is what i did to fix it:

.slick-prev:before
{
    content: '\2190';
}
[dir='rtl'] .slick-prev:before
{
    content: '\2192';
}

.slick-next:before
{
    content: '\2192';
}
[dir='rtl'] .slick-next:before
{
    content: '\2190';
}

/* Dots */
.slick-dots li button:before
{
    content: '\2022';
}

I have tested it on other sites without the charset/accent thing going on...  it still works! So I guess it makes it more compatible to use the unicode instead.

**Comment by simeydotme** [comment]
Please use `utf-8` and also please read the contribution guidelines in the repository. :)
