### ISSUE TITLE
Grab object div id attributes on cloning

### ISSUE THREAD

**Issue by gognoos** [kenwheeler/slick#1378]
line 1897 .appendTo(_.$slideTrack).addClass('slick-cloned').attr('id', $(_.$slides[slideIndex]).attr('id'));

**Comment by simeydotme** [comment]
what is your issue?

**Comment by gognoos** [comment]
In one of my project i have a carousel with slick settings `infinite: true`. And every slide content have class and id attributes for some styling. But slick don't grab id attributes when cloning div for do infinite. I added the above line code and every thing is fine. I think this is better to get id attributes too.

**Comment by nominalaeon** [comment]
It would be less invasive for the slide to act as a wrapper for the id'ed content, but I don't know how you're needing it. Could you whip up a Codepen? I'm interested to see what you're doing with the ids

**Comment by simeydotme** [comment]
Not gonna happen, ID's are supposed to be unique, that's why they are purposefully removed from clones.
You'll have to change your CSS to target classes (as is best practise) instead of IDs :grinning:
