### ISSUE TITLE
Constrain slider to a given height

### ISSUE THREAD

**Issue by pgtaboada** [kenwheeler/slick#1379]
Hi,

is there any way to constrain a slider to a given height?

I have a jsfiddle that shows what I want, but for some reason it is broken, but it pretty much shows what I would like to do.

broken:

   - I would like the upper image to fit in height, not width
   - if you navigate the any slider, the lower ones images increase

http://jsfiddle.net/z9mecgq2/1/

The upper mail area does resize, and I would like to habe the images of the mainSlider to have the height matching the surrounding main section.

How can I accomplish that?
Can someone tell me what is wrong with my jsfiddle?

brgds,

Papick

**Comment by nominalaeon** [comment]
If I'm understanding your issue correctly, you'll need to adjust the height of the image containers after Slick has initialized. However, Slick can init before the page has loaded all of your images, so if you're using JavaScript to like grab the tallest image height and size the siblings to that height, if an image isn't loaded, you'll get a height of 0.

You need to use the imagesLoaded plug-in to make sure you're not initializing Slick until after all the images of the container you're Slick'ifying have loaded.

    $slickFrame.imagesLoaded(slickInit);

    slickInit = function () {
        $slickFrame.on('init', $.proxy(this.slickPostInit, this));
        $slickFrame.slick(this.getSlickOptions());
    }

    slickPostInit: function () {
        someSizingFunctions();
    }
