### ISSUE TITLE
Centering vertical images

### ISSUE THREAD

**Issue by pdkaizer** [kenwheeler/slick#1381]
I am using Slick carousel and am trying to get vertical images to center in their div. Here is the site: http://gba.dreamhosters.com/annapolis-federal-bank/.

I am using Wordpress: the first image gets pulled form the featured image in WP and then the other images are custom fields. It all works great except I wan tth evertical images to center in the parent slider div. My mark up is:
	<?php if ( have_posts() ) while ( have_posts() ) : the_post(); ?>
      <div class="project">
        <div class="project-photo"><?php the_post_thumbnail('', array('class' => 'project-image')); ?>
        </div>
<?php if( have_rows('project_images') ): ?>
	<?php while( have_rows('project_images') ): the_row(); 
		// vars
		$image = get_sub_field('image');
		?>
		<div class="project-photo">
				<img src="<?php echo $image['url']; ?>" alt="<?php echo $image['alt'] ?>" class="iproject-image" />
		</div>
	<?php endwhile; ?>
<?php endif; ?>
      </div>

Any ideas how to get the vertical images to center?

**Comment by nominalaeon** [comment]
.project-photo img {
        margin: 0 auto;
    }

should do the trick

**Comment by pdkaizer** [comment]
Worked like a charm. Thanks!
