### ISSUE TITLE
Have title and images both as carousels but change title slower [Responsive Issue]

### ISSUE THREAD

**Issue by muddie20** [kenwheeler/slick#1382]
So I have 2 carousels one for a title and another to show images, meant to be titles as "Week of the month" and then images relating to days in that week, was wondering if there is a way to make it so when responsive the title only changes when it passes the threshold for that week?

Here's an image for a clearer view of what I mean:http://gyazo.com/61a305cd03abec4e4ec66c8d8b0ab282

Thanks in Advance,
Muddie20

**Comment by simeydotme** [comment]
You'll have to use your own brain for your own project's logic... but you might be looking for the `.on("breakpoint")` event which was added in `1.5.2` (https://github.com/kenwheeler/slick#events) :smile:

**Comment by nominalaeon** [comment]
You want the Day Slider's data-week attribute (or some other identifier) to control the Week Slider, so use Slick Events to analyze which slide Day Slider is showing or is about to show.

    $('.day-slider').on('beforeChange', function(event, slick, currentSlide, nextSlide){
        if (currentSlide.data('week') !== nextSlide.data('week')) {
            $('.week-slider').slickNext();
        }
    });

Or something like that.
