### ISSUE TITLE
slide: 'div', does not work with fade

### ISSUE THREAD

**Issue by creativeslice** [kenwheeler/slick#1383]
When `fade: true,` is set, the ability to only target a specific type of element (like `slide: 'div'`) does not work. I have a H2 element before the first slide but it becomes part of the slideshow even though I'm trying to target only the div's.

This was not an issue with version 1.3.15 (which I'm reverting back to for now)

**Comment by simeydotme** [comment]
Related to #1353 and #1357 ?
