### ISSUE TITLE
Key event die after click button next/prev

### ISSUE THREAD

**Issue by chinhphan099** [kenwheeler/slick#1384]
Click Next/Prev button on slider, than hit next/prev on keyboard. Slider don't work.

**Comment by simeydotme** [comment]
Because the event listener is bound to the carousel slides, not the arrows. Of you focus a left arrow and press `right` it makes little sense that the slider would react. Use `space` or `enter` to trigger the arrow you have focuse, and `tab` to navigate arrows :)
