### ISSUE TITLE
Slick initial slide contents changes on responsive

### ISSUE THREAD

**Issue by muddie20** [kenwheeler/slick#1385]
I've not been able to reproduce this in a fiddle... seems to work in there, but on chrome inspector and actual tablet/phone this fiddle : https://jsfiddle.net/asu2c626/ Will give as the initial load screen the images labelled 14 and 15, and none of the indexes change. On mobile the contents shift so initial load is image labelled 13.

**Comment by simeydotme** [comment]
Loads as Zero on Mine...

**Comment by muddie20** [comment]
The fiddle does but whenever I load it up in chrome it alters the order of the divs...

**Comment by simeydotme** [comment]
You mean when you run this outside of JSFiddle? -- then it's an environment issue with your project... But if you can link it I can take a look and see why :)

**Comment by muddie20** [comment]
Yeah outside of the fiddle here:
http://151.224.165.127:8080/GigglyPig/markets.html

**Comment by simeydotme** [comment]
Fix your JS error, then I'll take another look.

![image](https://cloud.githubusercontent.com/assets/2817396/7791070/fbd03c74-02cb-11e5-9c67-76b05750fad3.png)

**Comment by muddie20** [comment]
Just sorted it, was changed nothing... Just a script import that shouldn't have been on that page

**Comment by simeydotme** [comment]
Please change your Slick file to be the latest, unminified one from MASTER branch, I will then be able to debug where the errors are occurring (if they are) :)

**Comment by muddie20** [comment]
Aha that fixed it, no idea what could have caused that but changing to unminified version fixed it, Thanks for the help :)

**Comment by simeydotme** [comment]
It's more likely that one of the recent commits fixed it, but hasn't been minified in to a release tag yet :)
Keep an eye out for 1.5.6 :)
