### ISSUE TITLE
need help on Vertical flag

### ISSUE THREAD

**Issue by balajigumpena** [kenwheeler/slick#1387]
I have an issue with vertical alignment.

js fiddle :http://jsfiddle.net/Bala123/ks6j627n/4/

In this fiddle, gallery container size is fixed, but the images are overflown. I have tried 

inside  setheight function of the plugin i tried adding this code,

if (_.options.vertical === true) {
	 _.$list.css('max-height', "100%")
	_.$slideTrack.children('.slick-slide').height(_.$list.outerHeight()/_.options.slidesToShow);
 }

This fits my images to the container, but since the image height and width are fixed, my image gets stretched. 

In case of horizontal we maintain the image aspect-ratio with respect to width of the image container provided by slick, this doesn't happen in case of vertical where it should maintain aspect-ratio with respect to the image container slick provides.

**Comment by kenwheeler** [comment]
you need to set your image width to 100%
