### ISSUE TITLE
Bad infinite behaviour

### ISSUE THREAD

**Issue by cedriccharles4** [kenwheeler/slick#1388]
Hello !

Thank you for your nice slider :) 

I have a list of items that has to be a slick slider. It also has to be infinite and circular. Unfortunately, I can't get this work... When I arrive on the last element of the list, I don't have the first one next to it. Instead, I have a white space.

Also, the .slick-active is outside of my wrapper, I don't understand why...

What's wrong ? Thank you very much !

Here is the code : http://codepen.io/anon/pen/yNVzPO

Thank you for your help !

**Comment by evalunamain** [comment]
This seems to be a known bug if you look at other issues. If showing half slides if an option, than a hack is to set *centerMode* to true and *slidesToShow* to at least half of your number of slides. For your example, that would be the following:

> $('#productsNav').slick({
  variableWidth: true,
  infinite: true,
  centerMode: true,
  slidesToShow: 7,
 });
