### ISSUE TITLE
Show Dots for One Slide

### ISSUE THREAD

**Issue by merlihan** [kenwheeler/slick#1391]
Hi there,

I have implemented this great slider for a client who has the requirement to show 1-4 slides. I am using the dots:true option and have customized the dots with custom paging. The problem is that when there is only one slide, the dots (now buttons) do not get rendered. I absolutely understand the reasoning behind this since there shouldn't be a need for the dot when there is only one slide, however since we have text on the buttons, we're using it as a bit of a description for the slide.

Just wondering if there is an option to show dots when there is only one slide?

Cheers
kathryn

**Comment by kenwheeler** [comment]
Slick doesn't initialize if there aren't enough slides to slide.

**Comment by Addisonbean** [comment]
Why was this closed? I see that slick doesn't initialize if there aren't enough slides to slide, but that's basically the issue brought up here. I've found that a lot of people want to use features of slick like the dots and prev/next arrows even when there aren't enough slides to slide that it may be worth initializing it anyway.
