### ISSUE TITLE
Event binding and responsiveness

### ISSUE THREAD

**Issue by japalo** [kenwheeler/slick#1396]
Hello!
I've encountered a problem that many other also encountered. When you add event bindings, such as a button, the event bindings are destroyed when a breakpint is triggered. 

This issue is also described in https://github.com/kenwheeler/slick/issues/1227. 

I've inserted a fix for this in my local version of Slick by adding a new setting called ```reconstruct``` (which defaults to true) and added this code snippet:
```javascript
//Set reconstruct to false to avoid problems with event bindings in responsive
if(_.options.reconstruct) {
   _.refresh();
} else {
   _.unfilterSlides();
}
```

I saw in the previously mentioned post that you have closed the issue, but i don't think youv'e added it or it has disappeared in a merge or something.

Thx for an awesome plugin,
/J.

**Comment by nominalaeon** [comment]
Could you write up a codepen or fiddle please, or paste in your JavaScript. I've never experienced this issue but I may be doing the Slick init and binds differently.

**Comment by japalo** [comment]
Not sure how to do that in a good way, so i'll just paste my code here. I am using Angular, with Angluar-Slick that i found here: https://github.com/vasyabigi/angular-slick.

My html-code is the following:

      <div class="className">
        <div data-slick centerMode="false" reconstruct="false" center-padding="40px" slides-to-show="5" infinite="false" init-onload="true" data="availableTypes.typesList"
        responsive="[
          {
            breakpoint: 1024,
            settings: {
              arrows: true,
              centerMode: false,
              centerPadding: '40px',
              slidesToShow: 3
            }
          },
          {
            breakpoint: 704,
            settings: {
              arrows: true,
              centerMode: false,
              centerPadding: '40px',
              slidesToShow: 3
            }
          },
          {
            breakpoint: 496,
            settings: {
              arrows: true,
              centerMode: true,
              centerPadding: '40px',
              slidesToShow: 1
            }
          }
          ]" >
            <div class="tsSubscription tsAlign--center" data-ng-repeat="type in availableTypes.typesList">
              <div class="wrapper" data-ng-style="{'height': type.height + '%'}">
                <div class="wrapper__container">
                  <div class="className">
                    {{type.name}}
                  </div>
                  <span data-ng-if="type.item > 0">{{type.item }}</span>
                  <button class="btn" data-ng-click="chooseItemType(type)">Choose</button>
                </div>
              </div>
            </div>
        </div>
      </div>

If you need anything else, just ask and i will proivde. :)
/J.

**Comment by leggomuhgreggo** [comment]
Hmm, why couldn't you make a fiddle/pen? [Here's a template](http://codepen.io/gwst/pen/yNMgzg) I use.

Most of the responsive issues I've seen are the result of options only being defined at certain breakpoints and then not being redefined at others, including init. It looks like you're using that `data-slick` jonx, which I wouldn't think would throw a wrench in things, but it might.

**Comment by japalo** [comment]
Hi again! 
First of all, I am sorry for my delayed answer.
I kinda converted my angular version so that it can play nicely on CodePen. I am far away from an expert user at CodePen, so forgive me if something is weird. You can find it here: http://codepen.io/anon/pen/WvOvRz

It doesn't use angular at all as of right now, but i kept the data-ng-click property on the buttons because it's that event atachment that disappears in responsive handling. I tried to recreate the issue with jQuery .click(), but it seems that this works as it should. 

Could the issue be that when slick recreates the DOM-elements that it can't recreate angular events? 

Ps. I guess my CopePen is more a way to show you what i have done and how it should beahve rather than the code itself. I am not sure how to use CodePen with angular and also include angular-slick in order to show you exactly how my code works. Hope this is okay as well.

Cheers!
/J.
