### ISSUE TITLE
Slider remains hidden after DOM is loaded

### ISSUE THREAD

**Issue by awernick** [kenwheeler/slick#1399]
I've been trying to use Slick as the main slider for a landing page that uses Bootstrap. Unfortunately, for some reason Slick does not setup up appropriately, and the slider stays hidden even after the DOM has loaded. I have verified that jQuery is loaded before hand, and also that Slick is being called correctly. 

I tried isolating the problem by implementing the slider in a new file, without including anything else but the required dependencies. Despite my attempts, Sick is still not displayed in the DOM and remains hidden. By using the inspector, I can see that Slick correctly identifies my desired slider element, but the css styling for the slider is set to `visibility: none`.
```html
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.css"/>
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.min.js"></script>
  </head>
  <body>
    <div class="slick-slide">
        <div class="image"><img class="slick-slider-img" src="image1-2.png"  /></div>
        <div class="image"> <img class="slick-slider-img"  src="image1-2.png"  /></div>
        <div class="image"><img class="slick-slider-img"  src="image1-2.png"  /></div>
    </div>

    <script type="text/javascript">
        alert('hello!');
        $(document).ready(function(){
          alert('loaded');
          $('.slick-slide').slick({
              infinite: true,
              slidesToShow: 3,
              slidesToScroll: 3
            });
        });
    </script>
  </body>
</html>
```

JSFiddle:
https://jsfiddle.net/namzavpf/

I also tried loading slick and jQuery locally and through a CDN, but the change did not make a difference.
Both of the alert's in my example are fired, which means that jQuery is working correctly as well.

I am unsure if I am missing something to appropriately display Slick, or if there is a problem somewhere i my implementation. 

Slick Version 1.5.0
jQuery 1.11.0

Tested in Safari, and Chrome

**Comment by nominalaeon** [comment]
.slick-slide must be a reserved namespace. Use a different class name for your container and it should work

**Comment by awernick** [comment]
That fixed the problem. haha two hours spent for a really easy fix. I never thought of that.
