### ISSUE TITLE
When infinite is off arrows go past boundaries - fix documented

### ISSUE THREAD

**Issue by jimmackinlt** [kenwheeler/slick#1400]
In Slick.prototype.slideHandler = function(index, sync, dontAnimate)
    ...
    if (sync === false) {
        _.asNavFor(index);
    }

    // Add this to fix arrows past the edge ~ line 1929
    if (_.options.infinite === false) {
        if (index < 0) index = 0;
        else if (index >= _.slideCount) index = _.slideCount - 1;
    }

**Comment by jimmackinlt** [comment]
Slick.prototype.changeSlide = function(event, dontAnimate) {

        ...
        // If target is a link, prevent default action.
        if($target.is('a')) {
            event.preventDefault();
        }

        // Fix - Disabled prev/next turned off
        if ($($target).hasClass('slick-disabled')) return;

**Comment by simeydotme** [comment]
Please read the contribution guidelines
