### ISSUE TITLE
Embedding slick in reveal.js

### ISSUE THREAD

**Issue by schodge** [kenwheeler/slick#1401]
Is it possible to embed a slick carousel in a reveal.js presentation?  I'm trying to, but I just get an empty set of UI elements in a tab:

![capture](https://cloud.githubusercontent.com/assets/4616123/7892325/573575cc-0608-11e5-8d8d-03eb908c6cf2.JPG)

It's basically a slide made like this:

    <section>
        <div class="slider-fade">
            <div><div class="image"><img src="img/tableaudashboard2.jpg"></div></div>
            <div><div class="image"><img src="img/atombi-dashboard-screenshot2.png"></div></div>
            <div><div class="image"><img src="img/tableu.png"></div></div>
            <div><div class="image"><img src="img/Healthcare-performance-dashboard.png"></div></div>
            <div><div class="image"><img src="img/fisheye-source-crucible-code-review-dashboard.png"></div></div>
        </div>
    </section>

With the slider-fade code from the example at the bottom (along w/jQuery).  It more or less works if I create a blank page with it, but not in the reveal.  thanks.

**Comment by simeydotme** [comment]
Please read the contribution guidelines
