### ISSUE TITLE
[Question] How to hide arrows if I have only one item in slider

### ISSUE THREAD

**Issue by Shalimov** [kenwheeler/slick#1403]
How can I hide arrows if my slide show consists of only one item?

**Comment by R4NSS** [comment]
I have this issue too and also come across a slightly wider issue where what happens if you have two items in the list, so on desktop there is no slide function as there is nothing to slide to - the buttons need to disappear but they dont. Also, then when you move the browser size down to mobile portrait  view where only 1 list item is visible at a time, the buttons should now show. 

Im guessing there needs to be some sort of logic here where the buttons are hidden

list items are equal to or less than the number of slides visible

**Comment by leggomuhgreggo** [comment]
Hey please make a fiddle/pen when asking for help.

I've never seen the arrows apply when there's only one slide. 

[Here's a codepen](http://codepen.io/gwst/pen/mJWRZd) illustrating them not showing when there's one slide.

**Comment by Shalimov** [comment]
I've found a problem.
Pls look at the first <a href="http://codepen.io/anon/pen/gpmWjj">Example 1</a>:
Here you can see that I use custom theme for **prevArrow** and **nextArrow**(markup inside). It works great.
But if I want to use css selector as a pointer to my custom markup it will not work:
<a href="http://codepen.io/anon/pen/xGqdJg">Example 2</a>

**Comment by leggomuhgreggo** [comment]
Ah I see. Yeah, so I guess in a perfect world the library would hide the selector-defined arrows if there's only one slide, but because they're existing elements in the markup I can see how an argument can be made for leaving them. 

Luckily [the fix](http://codepen.io/gwst/pen/WvjGVM) is pretty easy; just test for slide length on init, and if it's 1 then hide the arrows.

**Comment by Shalimov** [comment]
Ok, it works, thx.

**Comment by simeydotme** [comment]
would be fixed by https://github.com/kenwheeler/slick/pull/1331 :)

**Comment by HiimF** [comment]
@leggomuhgreggo how do i test it?

**Comment by swillis93** [comment]
@HiimF You need to place the init event code before you intialize the slider, and then create an if statement that will count the amount of slides on load, and then hide the arrows if necessary. The following code should work for you, or at least point you in the right direction:

```
// the event needs to be run before slick is initialized
$('.slider').on('init', function (event, slick, direction) {

    // check to see if there are one or less slides
    if (!($('.slider .slick-slide').length > 1)) {

        // remove arrows
        $('.slider__arrow').hide();

    }

});
$('.slider').slick({
    YOUR SETTINGS: HERE
});
```

**Comment by omarel1** [comment]
Just figured this out!

Add anywhere after you call swiper js

if using looped slides:

//dont show navigation arrows on one slide if using looped slides
        var swiper__slidecount = mySwiper.slides.length - 2;
        if (swiper__slidecount < 2) {
          $('.swiper-button-prev,.swiper-button-next').remove();
        }
or if not using looped slides:

//dont show navigation arrows on one slide if not using looped slides
        var swiper__slidecount = mySwiper.slides.length;
        if (swiper__slidecount < 2) {
          $('.swiper-button-prev,.swiper-button-next').remove();
        }
.swiper-button-prev and .swiper-button-next would be the class names of the arrows
mySwiper should be whatever you named your swiper object.

**Comment by iamkeir** [comment]
It might also be wise to only init the slider if there is more than 1 slide:
```
if ($('.slider .slick-slide').length > 1) {
  $('.slider').slick({
    YOUR SETTINGS: HERE
  });
}
```

**Comment by andypimlett** [comment]
@iamkeir Isn't .slick-slide added during init though, so the above condition fails always?

**Comment by iamkeir** [comment]
@andypimlett sounds likely - best to count the pre-Slicked elements instead.

**Comment by justinmueller** [comment]
Came across this when trying to see how others did this. This solution should work better though:
```
$('.slider').each(function() {
	var $this = $(this);
	if ($this.children().length > 1) {
		$this.slick({
			YOUR SETTINGS: HERE
		});
	}
});
```

**Comment by bridgetwes** [comment]
See this issue: https://github.com/kenwheeler/slick/issues/1403  -- dots are hidden automatically when only one slide if you use slick.js and not slick.min.js.

**Comment by jonasedemalm** [comment]
Just had this issue, switched to .min.js for production and dots appered on single item slides. Why is it different code in the minified version? Very confusing.

**Comment by amoralesdesign** [comment]
Please fix this....

**Comment by iamkeir** [comment]
@amoralesdesign the above comment fixes it - count children, if larger than 1, init slider:
https://github.com/kenwheeler/slick/issues/1403#issuecomment-378432037
