### ISSUE TITLE
Slider Syncing - slider-current disappears if there are no arrows

### ISSUE THREAD

**Issue by gyduxa** [kenwheeler/slick#1404]
Hello
Using slider syncing and when all the nav items are visible, the arrows disappears (that's ok) but the slider-current doesn't update in the nav when we change the for list (slide with the mouse on the pink area on the bottom test)

EDIT: this is the fork jsfiddle: http://jsfiddle.net/gyduxa/g4pcn3tq/1/

Thank you

**Comment by leggomuhgreggo** [comment]
Hey can you clarify what you're trying to do here? 

BTW the reason the arrows aren't visible is because the slider is full width and the arrows are positioned to the left and right. If you add something like: 

`body{padding20px;background:#ebebeb}`

you can see them.

**Comment by gyduxa** [comment]
Sure, I can clarify.
The arrows are ok.

I've put two examples in the jsfiddle. 
The first one is correct, when you change the slides in the top slider, using the arrows or changing by swipe, the "nav" slider updates and the .slider-current goes to the next or prev item.

The second example, when you swipe the top slider, the "nav" slider doesn't update. So, the .slider-current is always in the same item, and it shouldn't.

Thank you

**Comment by gyduxa** [comment]
I've made a fix outside the plugin. In case someone needs this fixed, I'll say it here.

	$('.gallery.fixslick').on('beforeChange', function(event, slick, currentSlide, nextSlide){
		$('.gallery-nav .slick-slide').removeClass('slick-current');
		$('.gallery-nav .slick-slide:eq('+nextSlide+')').addClass('slick-current');
	});
