### ISSUE TITLE
'centerMode' behavior in 'responsive'

### ISSUE THREAD

**Issue by ejwaibel** [kenwheeler/slick#1405]
I'm trying to use the 'centerMode' option, but only in 'responsive' setting. I want centerMode to be enabled on small screen, but disabled on tablet and above. Unfortunately it seems that slick is not respecting the centerMode option within 'responsive' and causes the slides to break on all screen sizes. 

I've created a jsFiddle to show the problem.

Example: https://jsfiddle.net/ejwaibel/hkep3b8m/1/

**Comment by leggomuhgreggo** [comment]
For many slick options you have to have them at every break point you'd like them modified at. I think if you add `center-mode: false` to the initial options, it will work.

**Comment by ejwaibel** [comment]
I thought so too, and I thought my jsFiddle had shown that, but it is missing. Adding it to the initial options does not fix it.

**Comment by leggomuhgreggo** [comment]
Try some of the other options.

**Comment by ejwaibel** [comment]
It seems that I was using the "mobileFirst" property incorrectly! That's why centerMode was being enabled by default. Thanks for the help!
