### ISSUE TITLE
[Question] Possibility to stop on beforeChange event

### ISSUE THREAD

**Issue by LukasVice** [kenwheeler/slick#1410]
hi,
is it possible to prevent sliding in the beforeChange event (or is there a workaround)? i have to load some other contents before the slide should start. on click, i want the slide to stop, load other contents and then call slickNext or slickPrev.
thanks for your great work!

**Comment by kenwheeler** [comment]
Not at this time.

**Comment by krautnerds** [comment]
+1 it would be awesome to have such functionality, in my case I have to wait until some layer animations are finished and then call SlickNext

**Comment by marits** [comment]
+1

**Comment by sascha-hendel** [comment]
+1, same problem as krautnerds: Need to finish an animation before change should start.

**Comment by sascha-hendel** [comment]
Example: http://www.archinform.net/projekte/36064.htm
image carousel in the right column, active image can be zoomed (animated) in and out by click
if active image is zoomed and user navigates to other image (by left/right keys or by clicking the icons), it would be nice to first scale down the zoomed image and than switch to next image. this is not possible right now with animation

**Comment by simeydotme** [comment]
there's an open PR for this, but it proves to have some disagreements with the API.
I am looking in to getting it merged. In the meantime, you can go to the PR's tab and search for "beforechange" ... I'm sure you'll find it. You could borrow that code yourselves if you can't wait.

**Comment by sascha-hendel** [comment]
Looks, good! Will wait for the next release...

2016-02-26 6:59 GMT+01:00 Simon Goellner <notifications@github.com>:

> there's an open PR for this, but it proves to have some disagreements with
> the API.
> I am looking in to getting it merged. In the meantime, you can go to the
> PR's tab and search for "beforechange" ... I'm sure you'll find it. You
> could borrow that code yourselves if you can't wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kenwheeler/slick/issues/1410#issuecomment-189125412>.
>



-- 
www.archINFORM.net
Postfach 540103
D-10042 Berlin
archinf@archINFORM.de

**Comment by sascha-hendel** [comment]
Found the related issue #2104 
Now I use (in the example mentioned above) the slick fork from cfoehrdes and it works good! Hopefully this fork/PR will merged into the next release.

**Comment by mdominguez** [comment]
@sascha-hendel: A bit late to the game but was wondering how did you manage to continue slickslider after you event.preventDefault()'ed it until the the animation ended?
