### ISSUE TITLE
Rendering issue with bootstrap tabs

### ISSUE THREAD

**Issue by damonkilcawley** [kenwheeler/slick#1413]
I have two sliders, one in each tab. When switching tabs the second slider is not rendered, and I notice its slides widths are set to 0px. If I re-size the window it corrects itself. See fiddle here: https://jsfiddle.net/qfu04dvn/8/

I tried correcting the issue using refresh, but it did not work as expected. See fiddle here: https://jsfiddle.net/qfu04dvn/9/

The first slider works after a slight delay, but the second one does not render correctly still. The second slider does not have enough slides to exceed its "slideToShow" option, perhaps this is a clue.

A quick fix might be to call the same method called when the window is resized, does anyone know how I might go about doing that?

Thanks

**Comment by MaxKorz** [comment]
You should initialize your carousel on bootstrap shown.bs.tab event

**Comment by damonkilcawley** [comment]
Hi Ken,
Any chance I could get this reopened? Still having no luck.
Thanks

**Comment by htkcodes** [comment]
If anybody still having issues i used


` $('.nav-tabs a').click(function(){
    $(this).tab('show');
  $('.gallery').slick({
    dots: true,
    speed: 300,
    slidesToShow: 4,
    adaptiveHeight: true,
    arrows:true,
    responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
        // You can unslick at a given breakpoint now by adding:
        // settings: "unslick"
        // instead of a settings object
      ]
});

})`

**Comment by htkcodes** [comment]
If anybody still having this issue

css fix for bs4

.tab-content > .tab-pane, .pill-content > .pill-pane {
    display: block;    
    height: 0;       
    overflow: hidden; 
}
.tab-content > .active, .pill-content > .active {
    height: auto;    
}
