### ISSUE TITLE
IE8 Dots animation

### ISSUE THREAD

**Issue by hyperTwitch** [kenwheeler/slick#1415]
I have an autoplay setup that also includes dots. I need this to work in IE8, but while the image animation does in fact work, the dots don't consistently animate with the images. At this point I have not been able to determine why they do animate sometimes and other times don't, but they also have the issue described in https://github.com/kenwheeler/slick/issues/1140 ~~https://github.com/kenwheeler/slick/issues/1157~~. After adding the fix listed, I'm no longer seeing the issue in Chrome, but it still persists in IE8. I'm seeing the following error in the console: Object doesn't support this property or method  slick-1.5.0.js, line 1154 character 13

For reference my setup is currently as follows:
```
$('.slider').slick({
	dots: true,
	infinite: true,
	speed: 500,
	centerMode: true,
	variableWidth: true,
	arrows: false,
	autoplay: true,
	autoplaySpeed: 5000,
	accessibility: false,
	draggable: false,
	pauseOnHover: false,
	swipe: false,
	touchMove: false,
	useCSS: false
})
.on('focus', '.slick-dots button', function() {
	$('.slider').find('.slick-dots button').trigger('blur');
});
```

**Comment by hyperTwitch** [comment]
Okay, I found the issue. Apparently IE8 does not like repainting :before elements unless the content itself changes. To fix this you will need to update the css such that the style for .slick-dots li.slick-active button:before alters the content to be the actual character entity value instead of the character symbol. Something like this.

```
.slick-dots li button:before {
	content: '•';
}

.slick-dots li.slick-active button:before {
    content: '\2022';
}
```

**Comment by warrenparsons** [comment]
Thanks for posting your solution. This was exactly what I needed.
