### ISSUE TITLE
Question: Remove padding from first/last scroller-item in 'centerMode'?

### ISSUE THREAD

**Issue by ejwaibel** [kenwheeler/slick#1416]
I noticed when centerMode enabled, there is a 50px padding adding to the right and left side of the 'slick-list' element. However, this causes unnecessary extra white space on the left side of the first scroller-item element and the right side of the last scroller-item element. Is there a way to remove this extra whitespace?

**Comment by ejwaibel** [comment]
Here's an example:

http://jsfiddle.net/ejwaibel/fjg17efL/3/

Notice the extra white space on the left side of the first slide and right side of the last slide.

**Comment by kenwheeler** [comment]
You can set negative margins on the container to fix this.

**Comment by carloschneider** [comment]
Does anyone have an elegant solution?

**Comment by kucharzgotuje** [comment]
Nope, I've been dealing with it for quite some time & didn't found any good solution, 
I guess only transform: scale(1.01) does the "trick" but this is nasty..

**Comment by ckleo** [comment]
Setting centerPadding to '0px' fixed my problem.

**Comment by krishnadev-experion** [comment]
> Setting centerPadding to '0px' fixed my problem.

Disappeared when centerPadding set to 0px and solved using centerPadding set to 1px

**Comment by aquibyazdani** [comment]
Setting centerPadding to 0px will solve this issue.

**Comment by seonggookang** [comment]
> Setting centerPadding to '0px' fixed my problem.

Then what's the point of using centerMode?
