### ISSUE TITLE
slickGoTo method is ignored when called on "afterChange"

### ISSUE THREAD

**Issue by Fernify** [kenwheeler/slick#1417]
Hi there,
I'm using two carousels, one large image only carousel (with one slide to show and scroll, no dots or arrows, and not draggable) and another content carousel (with 2-4 slides to show and 1 to scroll, no dots or arrows, and not draggable) which acts as it's navigation.

Basically, due to the animations and transition speeds that I've used there's a second or two during the transtition between two slides that if you click on another slide during the transition it would disrupt the animations, so I locked the change on "beforeChange" and "afterChange". 

I wanted to queue the clicked locked slide by calling $("contentCarousel").slick("slickGoTo", clickedIndex, false) in the "afterChange" event but this method is ignored. Is there a way around this?

**Comment by ed-parry** [comment]
I'm having a similar issue - I can't appear to change the carousel from within the `afterChange` event - is it still doing something in the background at this point?

**Comment by simeydotme** [comment]
use the `waitForAnimate` option to `false`.

**Comment by Fernify** [comment]
Legend. Thank you very much, works great.
