### ISSUE TITLE
Slider Stopped Working

### ISSUE THREAD

**Issue by Ryeboflaven** [kenwheeler/slick#1419]
This is for a client site but the slider just stopped working and it is showing all the images stacked on top of each other. As far as I can see there is no code issues and I cant see anything that has changed. I have the js and css files being called in the header as instructed. Here is the relevant code (with image links removed)

-----Body-----

div class="new-slider"
   pic 1
   pic 2
/div

------Javascript in footer-----

$(document).ready(function(){

    $('.new-slider').slick({
        autoplay: true,
        speed: 800,
	autoplaySpeed: 5000
    });

	$('a').each(function() {
		var a = new RegExp('/' + window.location.host + '/');
		if(!a.test(this.href)) {
		    $(this).click(function(event) {
		        event.preventDefault();
		        event.stopPropagation();
		        window.open(this.href, '_blank');
		    });
		}
	});

	$(document).ready(function(){ 
	  $('.top-right').find(".search-field").each(function(ev)
		  {
		    if(!$(this).val()) { 
		    $(this).attr("placeholder", "quick search");
		  }
	  });
	});		

}); // $(document).ready

$(document).foundation(); 
 

------Other CSS added by previous IT------
/*
Hacks to prevent all images showing before JS initializes
*/
.new-slider div {
	/* display:none; */
}
.new-slider div:first-child {
	display:block;
}
.customize-support .new-slider div {
	display:block;
}
/*
 End Hacks 
*/

**Comment by simeydotme** [comment]
Please read the contribution guidelines, @Ryeboflaven , then you can re-open the issue if you think you've satisfied them :)


_hint: your code needs to be executed after the DOM is ready. __
