### ISSUE TITLE
Feature request: Removing slide by #id

### ISSUE THREAD

**Issue by FrostBy** [kenwheeler/slick#142]
Hi! Can you implement this feature?
I use slick with image manager on my project and I find it difficult to control indexes to remove slides

**Comment by samjonesigd** [comment]
@kenwheeler could you help remove a slick by class name with up to date slick syntax please? tried this `$('.js-banner').slick('slickRemove',$('.js-banner')[0].indexOf('.removeSlick'));` but get an error of:

indexOf is not a function error
