### ISSUE TITLE
Cloned slide class is changed after arrow is clicked.

### ISSUE THREAD

**Issue by julians300** [kenwheeler/slick#1420]
I'm having an issue where I have a Centered slider on infinite loop and I am using CSS transitions for styling during slider transition. It all works great until i loop the slides. The first slide on the next loop adds the 'slick-active' class after the transition, where as during the loop, this class is added before.

**Comment by kenwheeler** [comment]
Aware of this issue, but I don't have a fix at this time. Infinite sliding will be re-engineered in the near future to fix this.
