### ISSUE TITLE
Dynamically added slides break internal index counter

### ISSUE THREAD

**Issue by MaxKorz** [kenwheeler/slick#1421]
##### Steps to Reproduce:
1. Go to JSBin http://jsbin.com/mademegize/3/edit?html,js,output
2. Click Next

##### Expected Results: 
* .slick-active stays .slick-active

##### Actual Results:
* Green (.slick-active) turns red (.slick)

##### What caused this:
* New slide was added when currentSlide != 0

**Comment by kenwheeler** [comment]
Noted, closing pending PR merge
