### ISSUE TITLE
centerMode is showing cropped slides in the left and the right sides

### ISSUE THREAD

**Issue by pear1** [kenwheeler/slick#1423]
Hello, 

As I understand this isn't a bug, but mostly functionality issue.

I want to show just 3 items in carousel, but when centerMode is set to true, in the left and the right sides there are shown half cropped slides.

How to hide them?

**Comment by nominalaeon** [comment]
slidesToShow: 3,
    centerPadding: 0

> OR

    var slideWidth = $('.slide').outerWidth()

    slidesToShow: 1,
    centerPadding: slideWidth

> The slideWidth variable is pseudo-code. $('.slide') is not the real class name and, even if it was, it would be an array of all slides which would return the first (or is it last?) width of all the slides, which is only useful if your slides are all the same width

**Comment by pear1** [comment]
Thank you so much it worked.

One last question - is it possible to achieve some 3D slide animations like in this page (http://cu3ox.com)?

**Comment by nominalaeon** [comment]
Not as is, but the code base is pretty straight forward, if you make a cool transition option you should submit it your code to get the ball rollin.

**Comment by lucasprogamer** [comment]
Perfect

**Comment by shilpa-tcs** [comment]
Thank you nominalaeon It worked for me
