### ISSUE TITLE
Slick becomes unpaused

### ISSUE THREAD

**Issue by swinggraphics** [kenwheeler/slick#1424]
A paused slider with resume playing when switching from or closing another tab, minimizing and then restoring the window, or hiding and then unhiding the web browser. (tested in Chrome and Firefox on Mac)

**Comment by simeydotme** [comment]
Thanks for contributing;

https://github.com/kenwheeler/slick/pull/1133
Please update to newer version of Slick, and please do a simple search on open/closed issues in future.
And please read the contribution guidelines :)

Best,
Simon.
