### ISSUE TITLE
Responsive setting kills jQuery click on resize

### ISSUE THREAD

**Issue by Favitalegur** [kenwheeler/slick#1426]
I have some slides that are interactive. 
$('.slide-class').click(function(){
    //doWhateverINeed;
});
After resizing the window the slides don't respond to the jQuery click. 
The problem is in the responsive setting of the slider.
I've made a workaroud by removing the responsive setting and manually setting the width of the slides, but it would be cool if it wouldn't kill the jQuery click.

**Comment by kenwheeler** [comment]
It shouldn't anymore. Use the latest version.
