### ISSUE TITLE
RTL and Center - wrong currentSlide

### ISSUE THREAD

**Issue by maxkudla** [kenwheeler/slick#1427]
There are two examples:

LTR (correct) http://jsfiddle.net/maxkudla/zx6hLpth/
RTL (incorrect) http://jsfiddle.net/maxkudla/avfwqrwf/

the problem is in the direction of the current slide. in RTL next slide should be -1 (instead of +1)

**Comment by khall100** [comment]
If you set the dir attribute on the parent to rtl it should work.

**Comment by christianseel** [comment]
Confirming that if you set the `dir="rtl"` attribute on the container/parent it works as expected!

**Comment by leggomuhgreggo** [comment]
Awesome thankyou @christianseel. Closing.
