### ISSUE TITLE
Breakpoints implementation changes with mobileFirst setting

### ISSUE THREAD

**Issue by imcnally** [kenwheeler/slick#1429]
Hi Ken et al,

Great work on Slick. I've been using it with great success on some projects.

I'm making use of the `responsive` settings, and noticed an inconsistency. In the demo on the github page, the breakpoints act as you expect – at less than the resolution specified, the settings change. With the `mobileFirst` key set to true, that logic reverses. The breakpoint becomes, effectively, a min width. I believe the relevant lines of code are [here](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L161-L167) .

If it's by design, I believe the documentation should be updated to reflect that. If it's a bug, well, surprise!

I'd be happy to help if a fix is needed. I was looking to see what the direction you all wanted to take with it was.

As a test case, you can take the base JSFiddle and add or subtract `mobileFirst: true` from the settings.

- Ian

**Comment by kenwheeler** [comment]
No thats correct. The website needs a doc update, and that's coming soon. Thanks!
