### ISSUE TITLE
Is there a possibility to use 'centerPadding' without using 'centerMode' in a specific way?

### ISSUE THREAD

**Issue by lukaskoeller** [kenwheeler/slick#1431]
What I imagine is a slideshow with `slidesToShow: 3` and a partly hidden fourth slide just at the right corner (because its `infinite: false`).
Normally I would use `centerMode: true` with `centerPadding`. The big problem is, that when I'm using it and `infinite` is set to `false` there is big space on the left in the beginning and after some slides the slide on the left ist also partly hidden.

Here visualized:
https://drive.google.com/file/d/0B29r8zKyWhW-WEdpYWJZUHNTUTQ/view?usp=sharing
Ignore the arrow on the left?

reason why:
Slideshow is though for news. Left newest to right older (thats why not infinite)

**Comment by kenwheeler** [comment]
If you want partials, a sneaky way to do that is to set slidesToShow to a decimal. like 3.5
