### ISSUE TITLE
Lazy loading slider class - suggestion

### ISSUE THREAD

**Issue by entozoon** [kenwheeler/slick#1436]
Hi, I think it would be useful to apply a class to the slider during the time lazy load loads in the images (particularly for lazyLoad: 'ondemand').
I've whipped up a little fork to do such a thing - https://github.com/entozoon/slick/blob/master/slick/slick.js

It's useful because that way, the ajax loading gif can be applied centrally to the gallery itself and to hide the broken unloaded images.. by way of:
```
.lazy-loading {
	background-image: url('../img/ajax-loader.gif');
	background-repeat: no-repeat;
	background-position: center;
}
/* hide images while loading */
.slick-loading { display: none!important; }
```

**Comment by kenwheeler** [comment]
This is coming soon.
