### ISSUE TITLE
Problem with navigation and centerMode

### ISSUE THREAD

**Issue by Lugat** [kenwheeler/slick#1437]
Hey there,

we have a problem when using slick slider with a navigation.
http://jsfiddle.net/cmac1fo3/8/

The problem is, that the navigation does not center when there are 4 elements and centerMode is true.
If there are 3 or 5 elements it works perfectly.

Do we use wrong settings or is this a bug?

Greetings, Lukas

**Comment by kenwheeler** [comment]
Can you recreate this issue using the base fiddle in contributing.md? It looks like the demo is broken.
