### ISSUE TITLE
Full width background HTML5 video bugs?

### ISSUE THREAD

**Issue by OllyFreeman85** [kenwheeler/slick#1440]
Hi @kenwheeler congratulations on a near perfect slider, you're a genius! 

I'm having problems with creating a slider with divs containing full width HTML5/CSS3 video backgrounds, in theory I thought it would work as its a slider with any kind of content, it actually works on Firefox find of, but has issues on Chrome and Safari.

It seems to be a possible css display issue, have you encountered this?

All the best,

Olly Freeman

**Comment by kenwheeler** [comment]
Video is a little dicey. Often, I will put an image placeholder until its time to actually play the video. HTML5 video is tricky almost anywhere you put it. If you can reproduce the issue in a jsFiddle I can take a closer look.

**Comment by leggomuhgreggo** [comment]
Ran into this issue too. Here's an example [pen](http://codepen.io/leggomuhgreggo/pen/EVXOJO/)

I hope I won't have to hate HTML5 video by the end of this.
