### ISSUE TITLE
Is it possivle that 'slickNext' is also fired when rate of calling this method ist very high?

### ISSUE THREAD

**Issue by lukaskoeller** [kenwheeler/slick#1441]
Im using `$('.nav-slider').slick('slickNext');` in compination with waypoints. So everytime the users scrolls very fast this event will be fired very often. 

For example: When you scroll and pass three sections (waypoint function is called three times), the slider just slides onces.

Is there a possibility to prevent that?

**Comment by kenwheeler** [comment]
slickNext won't fire if an animation is already taking place. I would throttle your event to fix this.
