### ISSUE TITLE
Inline Arrows > #577

### ISSUE THREAD

**Issue by knightkiddo** [kenwheeler/slick#1442]
Hi,
https://github.com/kenwheeler/slick/issues/577

I was looking for this solution but it doesn't work anymore with slick 1.5 and slick 1.5.5.
It's ok with 1.4 but I need last version for my project... someone can help ?
regards

**Comment by saunders1989** [comment]
If i understand your problem. you basically just want to create custom selectors for your arrows.

https://jsfiddle.net/u1ofr9gy/

that fiddle creates custom content for arrows. if you read the issue 577 it says to build the html and use append dots and append arrows option to put the dots/arrows where you want them to be to create the desired effect

**Comment by knightkiddo** [comment]
That's right, your jsfiddle seems to match !

What i meant was that in the #577 it's that the example it's ok with slick 1.4 but in 1.5 or 1.5.5, the slider-nav became a slick-slide... it's really weird. just to see what i mean, change slick 1.4 in 1.5, and it doesn't work

but forget it, your example is my solution ! thanks dude !

**Comment by saunders1989** [comment]
I never used version 1.4 but I can only guess that from what I remember events where changed in 1.5 and I'd guess that that option changed name. maybe. 

Glad i could get a fix for you

**Comment by christianmagill** [comment]
If you want a simpler solution that makes use of the default components

`
$('.boats').slick({
          arrows: true,
          appendArrows: '.slick-nav',
          dots: true,
          appendDots: '.slick-nav'
});
`

`
<div class="slick-nav-wrap"><div class="slick-nav"></div></div>
`

`
.slick-nav-wrap{
  text-align: center;
}

.slick-nav{
  position: relative;
  display: inline-block;
  .slick-dots{
    position: static;
  }
}
`
