### ISSUE TITLE
Breaks on single image in center mode

### ISSUE THREAD

**Issue by meggers** [kenwheeler/slick#1443]
It appears as though Slick breaks on a single image in center mode, in that it doesn't center the single image. Here is a screenshot of the initialized Slick container, demonstrating the issue:

![slick-init](https://cloud.githubusercontent.com/assets/2888003/8117485/0c4f7c92-104e-11e5-9bde-72f9dfc3b580.png)

Here is my setup:

```javascript
      $carousel.slick({
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        centerMode: true,
        variableWidth: true
      });
```

Has anyone else experienced this?

**Comment by ejwaibel** [comment]
+1 I've had this issue as well. Had to add Javascript to check if there is only 1 item and not enable centerMode.

**Comment by kenwheeler** [comment]
Yeah slick doesn't initialize unless there is enough slides to actually slide.

**Comment by kushalcoder** [comment]
variableWidth: true,
 variableHeight: true


use this. I'will work
