### ISSUE TITLE
Multiple items feature turns into single item

### ISSUE THREAD

**Issue by jacopo-nosto** [kenwheeler/slick#1445]
Hi Ken,

first of all thank you for having created this component: it is very useful and solid, as well as totally customizable.
I have an issue with the carousel though: I set it up for working with 4 slides and a couple of breakpoints 

![__users_jacopo_dropbox_urban_industry_slick-1_5_0_slick_index_html__erste_schritte__ _brackets_und_multiple_items_feature_turns_into_single_item_ _issue__1445_ _kenwheeler_slick](https://cloud.githubusercontent.com/assets/12861611/8134151/313e0c28-112d-11e5-8d65-4ea25ea91023.png)

and it works like a charm, with four elements in a row and also the breakpoints are perfectly working.
Then I have injected the carousel inside a website (an ecommerce) I am working on and the carousel turns from 4 items into single items full width (the parent container's width) and, in addiction, the responsiveness does not work on resize.
I thought that maybe there were some conflicts with some jQuery libraries but actually everything works (also the swipe feature) so maybe the problem is not in the jQuery.

Is this something you have already bumped into? Or a new issue? I guess someone else had the same problem but actually, after having browsed the whole "Issues" section I was not able to find a solution to this.
If you have a fix for this solution that'd be awesome! I can also provide some screenshots if needed but what I have described above is what happens as-is :)

Thanks to all who want to give a help ;)

Jacopo

**Comment by kenwheeler** [comment]
Try using the `respondTo` feature and see if that fixes it.

**Comment by jacopo-nosto** [comment]
Hey Ken,

first of all thank you for your reply!

I have just added respondTo: slider (with the correct syntax, of course) but it does not do the trick: the effect is the same I had when I've tried "adaptiveWidth: true".
As I wrote above, if I resize the window it does not adapt to the width of the slider (so not behaving responsive) but something I have spotted is that if I resize the window and I swipe, when the "sliding" animation is completed, then they automatically resize to the width of the container: this will not be working as expected but I would accept it working like this, but still the breakpoints do not function).

![madison_island](https://cloud.githubusercontent.com/assets/12861611/8184616/b595e51c-143f-11e5-9ee7-c308db228574.png)

in this image you can see where is the slider, how it behaves (the orange arrows point to the slider's border, just to show you how it cuts some of the items instead of fitting them within the slider).
If you think this is something fixable, would be AWESOME :)

Thanks a lot

**Comment by kenwheeler** [comment]
first, adaptiveWidth isn't an option. second, have you tried * {box-sizing: border-box}

**Comment by jacopo-nosto** [comment]
Thanks!

With box-sizing I can now fit all the elements within the container but still it is not responsive.
It was working like a charm on my "local" project, then when I've injected it into the website it stopped to work.

I hope it is not something related to some jQuery reasons, in this website I am using jQuery 1.10.2.

**Comment by erlendvo** [comment]
Adding the source of the this problem in case anyone else have it. With Nosto the js is run inside an iframe with width 0px, therefore this problem will occur. The solution is to change the slick.js file to get the width from the parent window instead. Ive tested this on my own, and it works fine

from 
`var windowWidth = window.innerWidth || $(window).width();`

to
`var windowWidth = window.parent.innerWidth || $(window,window.parent.document).width();`
