### ISSUE TITLE
Pause on mouseOver doesn't work when autoplay initiated via slickPlay

### ISSUE THREAD

**Issue by terraling** [kenwheeler/slick#1446]
Normally, during autoplay, if you hover over an image it causes the autoplay to pause. Nice touch.

But if you set up slick with autoplay: false and then later initiate the autoplay via `$('.slider').slick('slickPlay')` then that pause effect no longer works, the slides keep on autoplaying regardless.

See jsfiddle [here](http://jsfiddle.net/kceqkmqu/1/) where I initiate autoplay after a delay.

(My actual use case is that I'm using scroll detection to only initiate autoplay once the slider comes into view, so that I know that the user will always see the slides from the beginning.)

Needless to say this is not a deal-breaker that will stop me using what is otherwise a great utility.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1203-L1207
The check for autoplay needs to be inside the event, not wrapping it :)

**Comment by simeydotme** [comment]
Technically this is a bug, but you can circumvent it for now by using: `slick('setOption', 'autoplay', true, true)` :)

**Comment by terraling** [comment]
That's great. Tested it in the fiddle and, yes, it works. Thanks.

**Comment by iSimonWeb** [comment]
Guys, additionally, if we initialize slick with autoplay: true; it will pause onHover and via.slick('pause') but it will re-autoplay manually changing slides. The autoplay restarts onMouseLeave.

**Comment by simeydotme** [comment]
I'm gonna try to crush the autoplay crap tomorrow :)

**Comment by drastick** [comment]
+1

**Comment by myconcretelab** [comment]
:+1:
