### ISSUE TITLE
Variable speed according to slide

### ISSUE THREAD

**Issue by tomhclark** [kenwheeler/slick#1448]
Hi,

I've about 5 slides on a slick carousel. I'd like some to stay up for longer (say 4s) and some shorter (say 1s), to allow for people to read more content on some slides without others becoming mega boring.

I'm a newbie to javascript I'm afraid but have a carousel working nicely as:

        <script type="text/javascript">
            $(document).ready(function() {

    $carousel = $('.one-time');

    $carousel
        .slick({
            dots: true,
            infinite: true,
            pauseOnHover: false,
            pauseOnDotsHover: true,
            speed: 300,
            slidesToShow: 1,
            adaptiveHeight: true,
            autoplay: true,
            autoplaySpeed: 10000
        })
        .on('focus', '.slick-dots button', function() { // Fixes blur issue via touch Chrome/Windows.
            $carousel
                .find('.slick-dots button')
                .trigger('blur');
        });}); </script>

I'd really appreciate any pointers that might help me and other newbies implement this. Thanks in advance!

Tom

**Comment by kenwheeler** [comment]
I dont think this feature merits inclusion in core, but you could manually change the slide using methods.

For example, on each slide, set a data-time and timeout off of it.

```
function changeSlide(slide) {
   var nextSlideTime = $('.slick-slide').get(slide + 1).data('time');
   setTimeout(changeSlide(slide + 1), nextSlideTime);
}
```

**Comment by erobwen** [comment]
I think that neat to have one speed for automatic sliding, and another one for manual. When the user is passive, it would be nice with a slow calm movement. However, when the user presses a slide button, it is nice with instant & quick response.

**Comment by juancpgo** [comment]
@erobwen, have you found a way of achieving that (different transition speeds for autoplay and pressing a slide) ? I opened and issue addressing that, but maybe you found some way..
