### ISSUE TITLE
Carousel collapses to right on Firefox

### ISSUE THREAD

**Issue by irahularora** [kenwheeler/slick#1449]
Hi there!

Slick is awesome. Thanks a lot for the efforts you put in making and maintaining it.

I've used Slick in some of my projects but I've not seen the issue I've been experiencing right now with it. I'm using Slick to work as a Full-screen content slider. The problem is the carousel becomes very narrow and sticks to the right side (as in the attached image) but it comes back to normal on a different screen resolution. This problem occurs in the Firefox (38.0.5) browser only.

I've looked into the existing issues but nothing helped so far. Please help me.
![Uploading slick-bug.PNG…]()

**Comment by kenwheeler** [comment]
Please create a jsfiddle of the bug
