### ISSUE TITLE
Pause on hover .. .not restarting when mouse moves away.

### ISSUE THREAD

**Issue by Upland** [kenwheeler/slick#1453]
Ver: 1.5
Jq: 2.1.4

Starting with:
      autoplay: true,
      arrows: false,
      slidesToShow: 9
		
The scrolling stops on mouse hover as it should - but when the mouse is moved away again it doesn't restart the scrolling ... unless it is kickstarted with a drag.

**Comment by simeydotme** [comment]
Please read the contribution guidelines :)

**Comment by Upland** [comment]
Sorry  :\

[jsFiddle](http://jsfiddle.net/Upland/Lak18ur6/5/)

**Comment by Upland** [comment]
Closed? Did I miss something?

**Comment by simeydotme** [comment]
Yep, a few things.
Pretty sure it has been fixed in the latest version :)

**Comment by Upland** [comment]
What other things did I miss? 
My jsFiddle is using 1.5.0 ... which I understand is the latest version.

**Comment by simeydotme** [comment]
You were including a minified version of slick. Also it was out of date.
https://github.com/kenwheeler/slick/releases

But regardless, I think it's fixed; I tested on the latest version, please upgrade if possible.

Best, Si.

**Comment by Upland** [comment]
Yes it is indeed fixed! 
Thanks for your help :)
Cheers, Chris

**Comment by NickToye** [comment]
This doesn't look like it's working again.

See my Codepen.

http://codepen.io/NickToye/pen/rVYRvb

Takes a while to actually pause, but doesn't restart.

**Comment by 1127** [comment]
I too am having this same issue as Nick's codepen shows. - it pauses and never resumes.
