### ISSUE TITLE
Graphic glitches in background-image (Chrome) because of Slick

### ISSUE THREAD

**Issue by dj-hedgehog** [kenwheeler/slick#1454]
I'm using it on this homepage http://ec2-52-28-27-0.eu-central-1.compute.amazonaws.com/ (in the middle of the page) but I experience graphic glitches in the image below when changing the caroussel-page or resizing the window. This problem doesn't occur in Firefox or Chrome.

Do you know what could cause this problem?
![image](https://cloud.githubusercontent.com/assets/7140800/8240211/441b6092-1601-11e5-8bb8-69e376f561ac.png)

**Comment by saunders1989** [comment]
I can't get onto your url to test this but in your question headline you say (chrome) but in the text you say it doesnt happen in firefox or chrome?

I'm guessing it only happens in chrome:

could you try this css `-webkit-transform: translate3d(0, 0, 0)` on maybe the slick slide element.
