### ISSUE TITLE
Not positioning last slide in proper place when using image interchange

### ISSUE THREAD

**Issue by symball** [kenwheeler/slick#1458]
For some reason, whenever the final slide is reached the positioning is way off. See the style attribute below for where this issue occurs:

transform: translate3d(THIS_ONE, 0px, 0px);

Example: coolstreams.ionic-web.com
On final slide: translate3d(-4914px, 0px, 0px);
Expected: transform: translate3d(0px, 0px, 0px);

As a result, when moving to the slide in question, everything works fine but, once the animation has stopped the image disappears; the text however stays visible. This can be worked around by resizing the browser window until it hits one of the image changing breakpoints. If reloading the page whilst it is "working" the bug begins anew

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, please feel free. Thanks!
