### ISSUE TITLE
Slick Slider not working in mobile

### ISSUE THREAD

**Issue by dels-baby** [kenwheeler/slick#1461]
I am currently using this on a theme for my shopify store: http://ourstorypaperco.com

It seems that when on mobile, the javascript for some reason will change the width to an insane number like 34000 px, which results in a blank image. The slider dots also disappear. I am not 100% sure what is going on.

Check out: http://ourstorypaperco.com/products/gray-chevron-modern-baby-book

This is the html that it changes it when its on a smaller screen, notice the width at 14350 px?
```<div class="product-single__photo-wrapper slick-slide slick-active" style="width: 14350px;" index="0">
          <img class="product-single__photo" id="ProductPhotoImg" src="//cdn.shopify.com/s/files/1/0836/5807/products/download_grande.png?v=1432427889" data-mfp-src="//cdn.shopify.com/s/files/1/0836/5807/products/download_1024x1024.png?v=1432427889" alt="Gray Chevron Modern Baby Book">
        </div>```

**Comment by guruwanabe** [comment]
Same issue

**Comment by ahmadalfy** [comment]
@guruwanabe please create another issue and post the URL to your problem or create a jsfiddle

**Comment by guruwanabe** [comment]
Solved! 
<code>
.slick-slider {
  display: table;
  table-layout: fixed;
  width: 100%;
}
</code>

**Comment by mikeacre** [comment]
That is the incorrect solution. There is a @media min width with a display: none !important in the slick .css there for the correct solution is:

`.slick-slider {
    display: block !important;
    }`

**Comment by mikeacre** [comment]
Also this may be useful:
` $('#product-list').slick({
                                infinite: true,
                                slidesToShow: $(window).width() >  600 ? 5 : 3,
                                slidesToScroll: 3,
                                dots: true
                            })`

**Comment by MatthewCawley** [comment]
This is what fixed it for me:

```
.slick-slider {
	display: table !important;
	table-layout: fixed !important;
	width: 100% !important;
}
```

It wouldn't work without the important.

**Comment by jonathanrace77** [comment]
Thanks for that! lifesaver :D

**Comment by haris-wpbrigade** [comment]
> This is what fixed it for me:
> 
> ```
> .slick-slider {
> 	display: table !important;
> 	table-layout: fixed !important;
> 	width: 100% !important;
> }
> ```
> 
> It wouldn't work without the important.

Thanks Man, it works!!!

**Comment by bilalnaseer** [comment]
> Solved! ` .slick-slider { display: table; table-layout: fixed; width: 100%; } `

Thanks it worked for me

**Comment by m-talha-amjad** [comment]
I was also running into this issue but with my own mistake, 

In CSS  I have set   `.slider-class.slick-slider { display: flex; } `

However, It should be  { display: block; } 

Use ` .slider-class:not(.slick-slider) { display: flex; } `

It will set display flex only when the slick slider is not initialized.

**Comment by sameerjagtap99** [comment]
I am having issue with the slider . The slider is not working on mobile view. 
You can check the issue on the website https://astreca.com . At the bottom there is a pic-slider which is not working for mobile view.
Thanks in advance!

**Comment by m-talha-amjad** [comment]
Sameer I have looked into it but issue is not appearing on desktop in
chrome dev tools in mobile view.

So unfortunately can't do anything about it.

**Comment by m-talha-amjad** [comment]
You can try adaptiveHeight true

**Comment by sameerjagtap99** [comment]
Hi Muhammad,
I have resolved the issue. Probably that's why it was not showing on website.
I had to add some JavaScript addition to the above CSS solution. I will put the JavaScript code below.

<script type="text/javascript">
    $(document).ready(function(){
      $('.slick-list').slick({
          draggable: true,
          autoplay: true, 
          autoplaySpeed: 2000,
          infinite: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          touchThreshold: 100,
      });
    });
</script>
