### ISSUE TITLE
No way to stop someone from tabbing away and reach new slide.

### ISSUE THREAD

**Issue by mkagenius** [kenwheeler/slick#1463]
My first slide contains two input boxes. I only display next button if the user fills the boxes.
My second slide also contains an input box.

But a user can easily press tabs and get to the second slide.

Couldn't find this in issues. 

Of course I don't want to disable tabbing due to accessibility reasons.

**Comment by simeydotme** [comment]
Accessibility reasons are invalid when you have a form inside a carousel, IMO :)

**Comment by simeydotme** [comment]
As for th issue, I think you'll need to write your own code to intercept the tab key

**Comment by mkagenius** [comment]
> As for th issue, I think you'll need to write your own code to intercept the tab key
cool :)
