### ISSUE TITLE
How to make slick "scale with its container"?

### ISSUE THREAD

**Issue by terraling** [kenwheeler/slick#1464]
I have a slider up and running with a mix of portrait and landscape photos, which I have made all the same height so that the slider row size doesn't keep expanding and contracting.

See a simple fork of your basic jsfiddle: http://jsfiddle.net/x66vpu84/1/

The size (height) of the row seems to be solely determined by the size of the source images. In the example, the images are all 300px high. But in the CSS I have tried to set the height of the container to be 150px and tried to set the height of the images in CSS to 150px.
Neither of these has any effect - the slider height is still 300px.

How is it possible to adjust the height of the slider without having to resize all of the images to the required height (which may be different on different pages of the same website)?

**Comment by simeydotme** [comment]
your CSS is wrong.

```css
.slider img { ... }
```
no `>` :)

**Comment by terraling** [comment]
That seems to do the trick, thanks for the help.

I'd just say that the documentation might want changing, as "scales with its container" is inaccurate and misleading.
