### ISSUE TITLE
Incorrect amount of dots

### ISSUE THREAD

**Issue by danielpuglisi** [kenwheeler/slick#1466]
When using `centerMode: true` and anything higher than `slidesToShow: 1` the amount of dots displayed is wrong.

Here is a fiddle: http://jsfiddle.net/4u4rvehe/5/

Any ideas on how to fix this?

**Comment by timonf** [comment]
Same or similar issue appears on slick demo page (https://kenwheeler.github.io/slick/):

*  See "Autoplay" when 5, 6, 1 or 6, 1, 2 are visible.
*  See "Slider Syncing" when 3, 4, 5 or 4, 5, 1 are visible.

A "workaround" could be to set number of slidesToShow to the same as slidesToScroll.

**Comment by leggomuhgreggo** [comment]
Been fixed in the master. [Here's a fork with the updated js](http://jsfiddle.net/leggomuhgreggo/ztd7zhLa/). Thanks!
