### ISSUE TITLE
Unslick removes all other javascript functions on the slick items

### ISSUE THREAD

**Issue by huijing** [kenwheeler/slick#1468]
The functionality of the carousel works perfectly. I'm setting the unslick option for mobile breakpoints, but if unslick is triggered by resizing the window, my other onclick functions are removed as well. Is this supposed to happen?

**Comment by simeydotme** [comment]
You have no information about your code, your version of Slick, or anything that could make this an Issue. [There's a chatroom for shooting the shit :)](https://gitter.im/kenwheeler/slick)
