### ISSUE TITLE
Slick doesn't stop loading called in an iframe (iPad)

### ISSUE THREAD

**Issue by knightkiddo** [kenwheeler/slick#1470]
Hi,

I have an html file with slick.js inside (html, js, css),
I put this html file in the "src" attribute of an iframe.
This iframe is called in a page in my project.
When page loading, slick doesn't stop loading. It slides, slides, slides, forever :D

Only on iPad (Portrait or landscape)

Any ideas, guys ?

**Comment by Khrystyna** [comment]
Hi,

I have the same issue. It loads normally, but then slick slides become really very wide. It brokes iframe width.

**Comment by simeydotme** [comment]
Please could either of you produce a JSFiddle to reproduce this? 
It's very very very edge case, and probably a safari bug (there's so many. jeez, safari!) but in case it isnt we'd need to see it in action.

Thanks, Simon

_( ps, please read: ​[contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) )_
​

**Comment by Khrystyna** [comment]
Yes, sorry, you are right. Quick note for @knightkiddo, it seems ios Safari ignores width attribute of iframe (if set to 100%). Try to set width of container where you have slick gallery to 100vw instead of 100%. It helped me. Works OK now.

**Comment by simeydotme** [comment]
Thanks for the reaponse, helpful comment! :D

**Comment by knightkiddo** [comment]
Hi guys

To solve this problem, I used this :
http://www.spacevatican.org/2015/4/7/on-mobile-safari-and-iframes/

Hope it will help

2016-01-26 11:24 GMT+01:00 Simon Goellner <notifications@github.com>:

**Comment by maenda** [comment]
Thanks @Khrystyna, worked like a charm :)

**Comment by vmvargas** [comment]
Worked!

**Comment by LuciaLil** [comment]
Thanks a lot @Khrystyna it saved our day!

**Comment by Helene-Expertime** [comment]
Thanks @Khrystyna!
