### ISSUE TITLE
Targeting nth slide with slick-nav?

### ISSUE THREAD

**Issue by philow3n** [kenwheeler/slick#1476]
Hi, 

I'm building a new site which has a slider made up of 4 slides visible in one go - a super slider if you will - and have the following:
    slidesToShow: 4,
    slidesToScroll: 4,

...which works great on both desktop and mobile (via responsive breakpoints).  I have one main slide panel with 4 slides inside. 

I now need to build in a nav underneath linked to the main slider via asNavFor.  It works, but the trouble is, I need to target every 5th slide to show the fresh pane of 4 slides. 

Currently, every nav item moves the slider by 1 slide, but I need to target: 1st, 5th, 9th etc

Has anyone every managed to do this? I guess it's some kind of math needed? In CSS, I can do it via .slide:nth-child(4n+4) but can I add a likewise to Slicks nav?

Any help would be appreciated!  My current JS is:

    $('.slick-slider').slick({
                  dots: false,
                  infinite: true,
                  speed: 300,
                  autoplay: true,
                  autoplaySpeed: 5000,
                  arrows: true,
                  slidesToShow: 4,
                  slidesToScroll: 4,
                  variableWidth: false,
                  onAfterChange:function(slickSlider,i){
                      $('.slick-nav .slick-slide').removeClass('slick-active');
                      $('.slick-nav .slick-slide').eq(i).addClass('slick-active');         
                  },
                  responsive: [
                        {
                          breakpoint: 1024,
                          settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4,
                            infinite: true,
                            dots: true
                          }
                        },
                        {
                          breakpoint: 768,
                          settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                          }
                        },
                        {
                          breakpoint: 480,
                          settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                          }
                        }
                  ]
        });

        $('.slick-nav').slick({
                slidesToShow: 7,
                slidesToScroll: 7,
                asNavFor: '.slick-slider',
                dots: false,
                arrows: false,
                focusOnSelect: true,
                variableWidth: true
        });

        $('.slick-nav .slick-slide').eq(0).addClass('slick-active');

**Comment by simeydotme** [comment]
Just need to separate the two sliders (no `asNavFor`) and set custom logic on click for the navigation slider, and custom logic `onAfterSlide` for the main slider to handle.

I don't consider this a bug / feature :)
