### ISSUE TITLE
Offset/height issues with lazy-loading and vertical alignment (1.5.5 / master)

### ISSUE THREAD

**Issue by blueyed** [kenwheeler/slick#1478]
Given the following example (which can be served from a local `file://` URL), you can see that the lazy-loading of images with a vertical setup causes offset issues.

This is (mainly) because of the "1px border" with:

    .slick-slide {
        …

        .slick-vertical & {
            display: block;
            height: auto;
            border: 1px solid transparent;
        }
    }

But there appear to be more generic issues with this test case, e.g. the slides are off when using the next/prev buttons (until you've been through all slides for once).

It's even more an issue with "master": the slides appear to have (nearly) no height at all (`.slick-list` gets a height of `3px`).
This happens via `setProps`:

    if (_.positionProp === 'top') {
        _.$slider.addClass('slick-vertical');
    } else {

With 1.5.5, I've noticed that the `aria-hidden` attribute on `.slick-slide` is
`true` on the first slide in this case (which it's false when not using
lazy-loading, i.e. when using the `src` attribute instead of `data-lazy`).

TEST CASE:

    <html>
      <head>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.5.5/slick.css"/>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.5.5/slick-theme.css"/>
      </head>

      <body>
        <div id="slick" style="border:1px solid blue">
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=1" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=2" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=3" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=4" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=5" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=6" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=7" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=8" /></div>
          <div><img data-lazy="http://dummyimage.com/300.png/09f/fff?text=9" /></div>
        </div>

        <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.5/slick.min.js"></script>

        <script type="text/javascript" charset="utf-8">
          $(document).ready(function(){
            $("#slick").slick({
              vertical: true,
              // verticalSwiping: true,
            });
          });
        </script>
      </body>
    </html>

**Comment by leggomuhgreggo** [comment]
Hey, I know this is months later, but I'm sorting through old issues. I’m going to close this, but if you want to circle back with a fresh test case, in a fiddle or codepen please, feel free. [There's one you can fork in the Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) Thanks!
