### ISSUE TITLE
Add user action on changes events

### ISSUE THREAD

**Issue by brunoskonrad** [kenwheeler/slick#1479]
What do you think about add the user action on changes events, e.g:

```javascript
mySlick.on('beforeChange', function(e, slick, currentSlide, nextSlide) {
  if (e.action === 'swipe') {
    // do something when the action was triggered by the carousel swipe
  }

  if (e.action === 'dots-click') {
    // do something when the action was triggered by click in dots
  }
});
```

Or something else.
Thanks!

**Comment by szimek** [comment]
+1. We're using slick (which is really awesome!) and we need a way to track user's behavior - if the slide change was caused by auto play, or by user interaction - clicking a dot, using arrow keys, swipe gesture etc. Adding `action` param to event looks like a clean way to do it.

**Comment by itstueben** [comment]
Plz add the Event Action Params. Or could i do this with another Param/Key to track user Actions?
