### ISSUE TITLE
lazyload ondemand does not work with "fade: true"

### ISSUE THREAD

**Issue by reywright** [kenwheeler/slick#1481]
If fade: true is being used, all the images load progressively, even if you specifically put "lazyLoad: ondemand"

**Comment by ptrwllrd** [comment]
Confirmed, doesn't work for me either

**Comment by frazerfindlater** [comment]
+1

**Comment by ptrwllrd** [comment]
another error raport: https://github.com/kenwheeler/slick/issues/1583

**Comment by mpowroznik** [comment]
+1 I too have encountered this problem.

**Comment by maxfarseer** [comment]
@mpowroznik thx, man! It's works!
