### ISSUE TITLE
Readme says use unslick but slick('unslick') is what's needed

### ISSUE THREAD

**Issue by anselmbradford** [kenwheeler/slick#1485]
[Example in readme](https://github.com/kenwheeler/slick#example) says to use `unslick`, but it appears the more recent syntax uses `slick('unslick')`.

**Comment by Immuzov** [comment]
@anselmbradford Thank you so much! You saved my time! +1

**Comment by paulmolluzzo** [comment]
IMO this issue should stay opened until the README is changed.

**Comment by simeydotme** [comment]
Oops, sorry I didn't ready it properly, thought that @Immuzov was claiming saying it was fixed! :P
Anyone want to do it and submit PR I will merge :)

**Comment by Immuzov** [comment]
@simeydotme Sorry :P
