### ISSUE TITLE
Slick Slider Syncing - Thumbnail Spacing

### ISSUE THREAD

**Issue by mblankinship** [kenwheeler/slick#1486]
I want to reduce the thumbnail spacing when using Slider Syncing.  I have looked through the CSS and am unable to get the spacing changed.

Please advise.

Thank you!

**Comment by leggomuhgreggo** [comment]
Hey sorry for the delayed response. I'm going to close this because there's no test case, [per the contribution guidelines and it's a support request.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) Best of Luck!
