### ISSUE TITLE
how to get the index of the slide clicked?

### ISSUE THREAD

**Issue by JBusch** [kenwheeler/slick#149]
i'm trying for hours now :-/

**Comment by yupit-github** [comment]
$(".yur-slider-selector .slick-list .slick-track .slick-slide").on("click", function(e) {
        slickClickedItemNumber = $(e.currentTarget).attr("data-slick-index");
    });

**Comment by sarBolt** [comment]
A bit of an old post, but I hit the same problem.
Looking at @kenwheeler solution above re. slick.$slides, it makes perfect sense. The actual index is an array index and not data-slick-index attribute.

**Comment by 63kans** [comment]
<div class="slider">
  <div class="a_slide"><img src="product_1.png"/></div>
  <div class="a_slide"><img src="product_2.png"/></div>
  <div class="a_slide"><img src="product_3.png"/></div>
  <div class="a_slide"><img src="product_4.png"/></div>
</div>

$('.a_class').click(function(e) {
  var clickedIndex = $(this).data("slick-index");
});

**Comment by 63kans** [comment]
`<div class="slider">
  <div class="a_slide"><img src="product_1.png"/></div>
  <div class="a_slide"><img src="product_2.png"/></div>
  <div class="a_slide"><img src="product_3.png"/></div>
  <div class="a_slide"><img src="product_4.png"/></div>
</div>

$('.a_class').click(function(e) {
  var clickedIndex = $(this).data("slick-index");
});`

**Comment by 63kans** [comment]
```
<div class="slider">
  <div class="a_slide"><img src="product_1.png"/></div>
  <div class="a_slide"><img src="product_2.png"/></div>
  <div class="a_slide"><img src="product_3.png"/></div>
  <div class="a_slide"><img src="product_4.png"/></div>
</div>

$('.a_class').click(function(e) {
  var clickedIndex = $(this).data("slick-index");
});

**Comment by tossapholchin** [comment]
Good for you.

`var currentIndex = $('.slick-current').attr('data-slick-index');`

Ex.
```
$('.next').on('click', function(e) {
    var currentIndex = $('.slick-current').attr('data-slick-index');
    currentIndex++;
    $('.caption').html('Slide number: ' + currentIndex);
  });
```

**Comment by muddasirawan** [comment]
jQuery( ".ul-slider-nav li a" ).on('click', function(){
		slide_active = jQuery(this).data("slide-num");
		jQuery('.pt-slick-carousel__slides').slick('slickGoTo', slide_active);	

	});

	jQuery('.pt-slick-carousel__slides').on('beforeChange', function(event, slick, currentSlide, nextSlide){		
		jQuery( ".ul-slider-nav li a" ).each(function( index ) {		  	
		  	jQuery('.ul-slider-nav li a').removeClass('active');
		  	jQuery('.ul-slider-nav li a').eq( nextSlide ).addClass('active');
		});

	});

**Comment by muddasirawan** [comment]
```
jQuery( ".ul-slider-nav li a" ).on('click', function(){
		slide_active = jQuery(this).data("slide-num");
		jQuery('.pt-slick-carousel__slides').slick('slickGoTo', slide_active);	

	});

	jQuery('.pt-slick-carousel__slides').on('beforeChange', function(event, slick, currentSlide, nextSlide){		
		jQuery( ".ul-slider-nav li a" ).each(function( index ) {		  	
		  	jQuery('.ul-slider-nav li a').removeClass('active');
		  	jQuery('.ul-slider-nav li a').eq( nextSlide ).addClass('active');
		});

	});
```

**Comment by richt222** [comment]
None of this worked for me unfortunately. I couldn't manage to access the `slick.$slides` array at all to get at the index of the clicked slide.

Referencing the `slick-index` attribute of the slide in the HTML is possible. However, if you perform manipulations such as removing a slide, this throws the HTML attribute index out of sync with Slick's internal index of slides. The `slick-index` attributes therefore can't be relied upon if you're making changes to Slick's content.

The only way I found to do it was to get the frame's index dynamically, by inspecting the DOM to get frame's position amongst the active slides, like so...

```
<div class="slider">
  <div class="a-frame">your content</div>
  <div class="a-frame">your content</div>
  <div class="a-frame">your content</div>
</div>
```
...

```
$('.a-frame').on('click', function() {
  clickedIndex = $('.a-frame').not(".slick-cloned").index(this);
  // do something with clickedIndex
});
```
