### ISSUE TITLE
Using sliders in bootstrap tabs

### ISSUE THREAD

**Issue by damonkilcawley** [kenwheeler/slick#1490]
I have two sliders, one in each tab. When switching tabs the second slider is not rendered, and I notice its slides widths are set to 0px. If I re-size the window it corrects itself. See fiddle here: https://jsfiddle.net/qfu04dvn/8/

I tried correcting the issue using refresh, but it did not work as expected. See fiddle here: https://jsfiddle.net/qfu04dvn/9/

The first slider works after a slight delay, but the second one does not render correctly still. The second slider does not have enough slides to exceed its "slideToShow" option, perhaps this is a clue.

A quick fix might be to call the same method called when the window is resized, does anyone know how I might go about doing that?

Ps. I realize I have already posted this, but the topic was closed while I was on holiday. Still trying to overcome this issue as it's vital for my website.

Thanks

**Comment by leggomuhgreggo** [comment]
Hey, sorry for the delay in attending to this issue. I think your issue stems from bootstrap tabs use of display none. There's been several issue reports about this subject; [here's one](https://github.com/kenwheeler/slick/issues/619#issuecomment-67228390) that I hope will be helpful. Thanks.
