### ISSUE TITLE
Images loading one by one.

### ISSUE THREAD

**Issue by muratrl** [kenwheeler/slick#1491]
Here is the problem that I am facing. http://g.recordit.co/giZacSFRNc.gif
Any help is appreciated!

thanks

Here is my html and javascript
HTML-
<div id="variable-width" class="show-for-medium-up imageContainer carousel-for">
              <% @medias.each_with_index do | media,index | %>
              <div>
                img src="<%= "http://#{media["path"]}/#{media["key"]}.jpg?w=10000&h=600&fit=clip" %>"
              <div class="imageCaption">
                <%= index+1 %>/<%=@medias.length%>: <%=media["caption"]%>
              </div>
            </div>
          <%end%>
      </div>
JS-

$('#variable-width').slick({
      dots: false,
      infinite: true,
      speed: 300,
      slidesToShow: 1,
      variableWidth: true,
      arrows:true,
      centerMode: true,
      centerPadding: '2px',
      slidesToShow: 3,
      asNavFor: '.slider-nav',
    });

**Comment by ShrmnK** [comment]
You could perhaps take a look at using lazyloading.

**Comment by muratrl** [comment]
I did try that also , but no luck~
