### ISSUE TITLE
How can I get focus (control) of the carousel programmatically?

### ISSUE THREAD

**Issue by kuc2477** [kenwheeler/slick#1493]
Although I usually get control over the carousel by clicking them, I need to get it done by javascript code to provide more flexible UX in my project. Is there any way to do this?

I've tried ` $('#my-slick-carousel').focus() ` but it doesn't seems to be working.

**Comment by nevace** [comment]
I did this...

 if (e.which == 37) {
                      $('.gallery').slick('slickPrev')
                      return false;
                    }

                    if (e.which == 39) {
                      $('.gallery').slick('slickNext')
                      return false;
                    }
                  });

**Comment by simeydotme** [comment]
Please use the contribution guidelines to find the correct course of action to get support :)
