### ISSUE TITLE
slickRemove overwrites _.$slidesCache with current slides, so also removing filtered slides

### ISSUE THREAD

**Issue by MrSkippy** [kenwheeler/slick#1497]
If you filter slides, the _.$slidesCache will still have them, but when you do 'slickRemove', it will overwrite it with the shown items after the removal and thus also removing filtered slides from the cache.

In method Slick.prototype.removeSlide / Slick.prototype.slickRemove
line 1599: `_.$slidesCache = _.$slides;`

Imho the deletion should be done on the _.$slidesCache and then rerendered with the current filter.

**Comment by simeydotme** [comment]
Thanks for the comment, we will look at implementing this in the next major release :)
