### ISSUE TITLE
slick ignores max-height resulting in squashed images

### ISSUE THREAD

**Issue by terraling** [kenwheeler/slick#1502]
The height of the slider is determined by the native height of the <img>'s, and can be changed, for example, via

    .slick img {
        height: 300px;
    }

But if you need to use max-height such as

    .slick img {
        max-height: 100vh;
    }

the browser respects the max-height, but slick ignores it, resulting in squashed/distorted images.

See http://jsfiddle.net/x66vpu84/2/ for a simple example.

**Comment by ShrmnK** [comment]
Try 

    .slick-slide img {
        max-height: 100vh;
    }

**Comment by leggomuhgreggo** [comment]
Hey, sorry for the delayed response. I'm going to close this because this is a support request, but slick will add inline width values, which is whats stretching your images. I suggest you nest images in a slide div. Thanks!
