### ISSUE TITLE
Manipulate initial Slide to be the image clicked

### ISSUE THREAD

**Issue by daviddsr** [kenwheeler/slick#1503]
Hi, I have to say that I'm a newby and maybe I'm asking something obvius. But I've searched everywhere and I haven't succeed. Maybe you can help me. I've built an awesome slider with Slick. But I need a feature to finish it.

My slider opens up inside a modal that is fired up when I click in an image static gallery. What I need is that slider opens up right by the image just been clicked. I've read all the docs and I think the setting InitialSlide is what I need. But I dont know how to do it. I need to store the id of the image somehow at the same time the slider is initialized. I hope someone has done this before, because is the only thing I have left. I show you my code to be more precise

This is how I initialize the slider

     $(document).ready(function(){
      $('.slider-gallery').slick({
        lazyLoad: 'ondemand',
        slidesToShow: 1,
        slidesToScroll: 1
      });
      $(".slick-prev").hide();
      $(".slick-next").hide();
     });

     $('#prev').click(function(){
       $(".slider-gallery").slick('slickNext');
     });

     $('#next').click(function(){
       $(".slider-gallery").slick('slickPrev');
     });

**Comment by ethanclevenger91** [comment]
Correct me if I'm wrong, but you have a gallery of images. When one gets clicked, a lightbox opens featuring that image and buttons that allow you to click through the images in the same order they were in on the page itself?

FIrst off, you're reinventing the wheel a bit, as a slew of libraries exist to do specifically this. But let's say you do need to use slick and do it yourself for one reason or another. You want something like this:

```
$('.img-in-gallery').click(function(e) {
    var initialSlideIndex = $(this).index(); //or some variation of this should get you the clicked image's index relative to its siblings
    $('.slider-gallery').slick({
        lazyLoad: 'ondemand',
        initialSlide: initialSlideIndex
    });
});

**Comment by daviddsr** [comment]
You may be right about I'm reinventig the wheel. But this happens when is the first time you try to do something. The approach you gave me didn't succed because the images are just wrapped in simple divs, so every index is 0. But that made me think that I could get the src of every image "assets/images/1.png" After a few lines I've got the number of the image and stored in a var number. So what I've tried is var initialSlide = number -1 ; because the index of the images in slider is the number of the image - 1. But it just works the first time and is very unestable. If I close the slider and I open back it doesn't work this time. 

If you know a library that already do this. Please, let me know it.

**Comment by ethanclevenger91** [comment]
So you want to do

```$(this).parent().index()```

instead.

Look into lightbox, as well.

**Comment by ethanclevenger91** [comment]
Ugh, mobile. I'll fix that in a few minutes

**Comment by daviddsr** [comment]
Ok I wait four your answer

**Comment by ethanclevenger91** [comment]
Updated answer

**Comment by daviddsr** [comment]
Ok. I think it will be better that I look for another slider library that gives me what I need mora precisely. Thanks a lot ethanclevenger91

**Comment by ShrmnK** [comment]
If you are still keen on getting it to work, the above logic in the code written by ethanclevenger91 is correct. You just need to figure out the index of the image.

It might be interesting to note that slick assigns a data attribute auto-incrementing zero-indexed "data-slick-index" for each of the divs it manipulates. That should help you figure it out :)

**Comment by daviddsr** [comment]
Thanks a lot four your help. Finally I've chosen to use Slidesjs with
multiple sliders and that solved my problem with the initial slider because
I can create 4 sliders. One for each image on the static gallery. May be is
not the best way but is what I've found.

2015-07-03 13:46 GMT+02:00 ShrmnK <notifications@github.com>:

**Comment by gausarts** [comment]
> If you know a library that already do this. Please, let me know it.

The above is if yo would like to code it yourself. Otherwise http://mreq.github.io/slick-lightbox/ may help.
