### ISSUE TITLE
Slide option not working

### ISSUE THREAD

**Issue by kumiau** [kenwheeler/slick#1505]
The 'slide' option should specify which elements in a container will be slides.  In this fiddle you can see the problem:
http://jsfiddle.net/kumiau/w1c82yLz/3

I fixed this by adding `this.options.slide` to the buildOut prototype function in slick.js, line 491
```javascript
    _.$slides = _.$slider.children(
       this.options.slide+':not(.slick-cloned)').addClass(
       'slick-slide');
```

**Comment by simeydotme** [comment]
should be fixed by: https://github.com/simeydotme/slick/commit/22b75a2efc0943d24870a0e940f738463676729b .. can you try this with the latest master-branch `slick.js` file, please? :)
