### ISSUE TITLE
Link to new page with slickGoto ? (pass variable) 

### ISSUE THREAD

**Issue by n0xx** [kenwheeler/slick#1506]
Hi, i have a question, am i able to have menu on one site and whole slick on second. 
And when i click link from 1st it will open 2nd page with current slick number from 1st page ?

Am i somehow able to pass variable between two sites ?

**Comment by ShrmnK** [comment]
You could use query strings to achieve this. Your second site would read the query string upon page load to set the initial slide.

**Comment by n0xx** [comment]
Ok, thanks for answer but how am i suppose to do it ?
I should use somehow initialSlide ?
Something like : xxx.html?initialSlide=2 for example  ?
if yes, its not working

**Comment by ShrmnK** [comment]
Yes you could do that. The second page you are navigating to would need to retrieve the initialSlide value from your query string.

This is a very basic example: http://codepen.io/anon/pen/XbZLgq?initialslide=3

The initialslide = 3 is the ID of the slick item. slick items are zero-indexed so in the example above, initialslide=3 would present Slide 4 first.

**Comment by n0xx** [comment]
Wow, thanks a lot ShrmnK, that is exacly what i wanted - thank your so much man, you made my day!

**Comment by n0xx** [comment]
Sorry for double post but i do not know if edit's are updating as new post so im writing second one.
There is a problem in slider-nav:
.slick-current  and .slick-center are not updating to specific slick (in your demo to slick number 4.

**Comment by ShrmnK** [comment]
I believe that issue should be filed as a bug. I can reproduce it on my end as well: slick-current and slick-center are not assigned to the initialSlide. Does not work even when calling a setPosition after init.

**Comment by simeydotme** [comment]
Please check if it already exists , there's pl;enty of bugs to do with `centermode` :)

**Comment by n0xx** [comment]
My bad, it's working great, my fault - i somehow missed those two bastards:
$('.slider-for').on('init', refreshSlick);
$('.slider-nav').on('init', refreshSlick);

Thanks again ShrmnK, this script is great, so many options  !

**Comment by iparr** [comment]
I have the same problem as above.

When I go 'prev' the 'next' I can carry on fine, but if I go 'next' after the 'intialslide' is loaded, then it gets very confused.
