### ISSUE TITLE
Slick kills click events and drag events

### ISSUE THREAD

**Issue by badzster** [kenwheeler/slick#1507]
Hi,
Hopefully this is an easy one.  

I have a Slick Carousel of images.  For each image I have a link that opens the image using Colorbox.  When clicking on the image, the Colorbox modal no longer opens, nor can I get any code to fire.  

Also, with each image, I need to able to drag the image out of the carousel into a div.

Both these work with jCarousel.  Except with jCarousel, I can't get variable widths.

Please direct me where to look for a solution...

Many thanks.
Baden

<div style="background-image:url(images/Film.jpg);background-repeat: repeat-x;background-size:200px;padding-top:15px;width:100%;height:200px;">
<div class="imagestrip">
        
            <ul id="mycarousel" class="slider responsive" style="margin-left:50px;margin-right:50px;">

        <asp:Repeater ID="rptImages" runat="server" DataSourceID="SQLPhotos">
            <ItemTemplate><li style="height:100%; margin-left:10px; margin-top:3px";>
                <div class="imagestrip" onmouseover="CopyID('<%#DataBinder.Eval(Container.DataItem, "ITEM_ID")%>')">
                    <a class='inline' href="#inline_content">
                            <asp:Image CssClass="PhotoStrip" ID="Image1" runat="server" ImageUrl='<%# String.Format("PhotoHandlerItem.ashx?ITEM_ID={0}", Eval("ITEM_ID"))%>' height="94px" draggable="true" ondragstart="drag(event)" ondragend="noDrop(event)" ondragleave="noDrop(event)"/></a>
                        <label><h20><span><%#Eval("DATE", "{0:yyyy}")%></h20></span></label>                    
                    
            </div></li>
            </ItemTemplate>
        </asp:Repeater>

                <li style="height:100%; width:200px; text-align:center;color:white;cursor:pointer;padding-top:22px;";>
                    <a data-target="#mapmodals" data-toggle="modal" data-backdrop="static" class="btn btn-primary btn-small" onclick="ClearAddPhotoModal()" style="text-align:center;background-color:black;margin-right:10px;height:78px;width:120px;padding-top:20px;"><img src="Images/add1-32.png" style="cursor:pointer;margin-left:10px;padding-left:30px;padding-bottom:5px;background-color:black;border-color:white;"/><label style="color:white;font-family:Museo-Sans-500;cursor:pointer;text-align:center;"> Add a Photo</label></a>
                    
                </li>
    </ul>
                            <asp:updatepanel ID="Updatepanel13" runat="server">
                        <ContentTemplate>
                            <asp:Textbox ID="txtSERIESID" runat="server" style="display:none;visibility: hidden;"></asp:Textbox>
                        </ContentTemplate>
                    </asp:updatepanel>
        
            </div>
    </div>

            <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <%--<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>--%>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<%--<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>--%>
<script type="text/javascript" src="slick/slick.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){

            $('.responsive').slick({
                dots: true,
                infinite: false,
                speed: 600,
                slidesToShow: 10,
                slidesToScroll: 4,
                variableWidth: true,
                arrows: true,
                draggable:true,
                //focusOnSelect:true,
                
            });
        });
        </script>

**Comment by badzster** [comment]
<asp:Repeater ID="rptImages" runat="server" DataSourceID="SQLPhotos">
            <ItemTemplate><li style="height:100%; margin-left:10px; margin-top:3px";>
                <div class="imagestrip" onmouseover="CopyID('<%#DataBinder.Eval(Container.DataItem, "ITEM_ID")%>')">
                    <a class='inline' href="#inline_content">
                            <asp:Image CssClass="PhotoStrip" ID="Image1" runat="server" ImageUrl='<%# String.Format("PhotoHandlerItem.ashx?ITEM_ID={0}", Eval("ITEM_ID"))%>' height="94px" draggable="true" ondragstart="drag(event)" ondragend="noDrop(event)" ondragleave="noDrop(event)"/></a>
                        <label><h20><span><%#Eval("DATE", "{0:yyyy}")%></h20></span></label>                    
                    
            </div></li>
            </ItemTemplate>
        </asp:Repeater>

**Comment by leggomuhgreggo** [comment]
Hey, my apologies that for the delay in attending to this issue. I'm going to close it because it doesn't include a test case, [per the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). If you care to create fiddle to demo the issue, we can reexamine! Thanks!
