### ISSUE TITLE
Next / Prev links don't apply preventDefault if they have sub-elements

### ISSUE THREAD

**Issue by localpcguy** [kenwheeler/slick#1508]
Using the following markup for the next/prev buttons causes the page to jump when the next/prev buttons are clicked because it skips over the `event.preventDefault();` code since the target element is not an `a` tag.

    nextArrow: '<a href="#" class="slick-next"><i class="sprite rightArrowIcon"></i></a>',
    prevArrow: '<a href="#" class="slick-prev"><i class="sprite leftArrowIcon"></i></a>',

The issue can be seen here at the following JSFiddle (note: due to the nature of the issue, I have to link to the iframe code directly, rather than to the fiddle itself. Note that the URL gets a `#` in it when clicking next/prev.) 

Bugged JSFiddle:
https://fiddle.jshell.net/localpcguy/vbyg5wxx/1/show/light/
original: http://jsfiddle.net/localpcguy/vbyg5wxx/1/

Will shortly have an incoming fix that was used to solve this by using `event.currentTarget` rather than `event.target`. 

Fixed JSFiddle:
https://fiddle.jshell.net/localpcguy/vbyg5wxx/2/show/light/
original: http://jsfiddle.net/localpcguy/vbyg5wxx/2/

**Comment by leggomuhgreggo** [comment]
Hey, apologies that this has gone so long without attention. It appears the fiddles are no longer working; so I am going to close the issue, but if you'd care to update them, I'd be happy to reexamine! Thanks!

**Comment by localpcguy** [comment]
The fiddles both appear to be working as intended. The first one demonstrates the issue (see error in console), and the second is after the referenced fix is applied.

**Comment by localpcguy** [comment]
Updated the jsfiddles to reference the JSFiddle from the time period when this bug/PR was submitted. The code that was changed by PR #1509 was not changed during the updates from 1.5.5 to 1.5.9, so the issue should still exist and also be fixed by the updates I made.

Here are the updated Fiddles:

Bugged JSFiddle:
https://fiddle.jshell.net/localpcguy/vbyg5wxx/3/show/light/
original: http://jsfiddle.net/localpcguy/vbyg5wxx/3/

Fixed JSFiddle:
https://fiddle.jshell.net/localpcguy/vbyg5wxx/4/show/light/
original: http://jsfiddle.net/localpcguy/vbyg5wxx/4/

**Comment by localpcguy** [comment]
Note: to see the issue, you need to escape the iframe

**Comment by leggomuhgreggo** [comment]
My apologies for the hasty look. Reopening

**Comment by simeydotme** [comment]
believe this should be fixed by: https://github.com/kenwheeler/slick/pull/1586 ?
