### ISSUE TITLE
slow initial load

### ISSUE THREAD

**Issue by kmichaela** [kenwheeler/slick#1511]
The Javascript loads too slowly that the images/blocks become a vertical stack until everything loads.  This is less than a second but does bounce the page.  Tried to add the classes required by slick to initialize slider and didn't work.  Is there a way that you can have the slider load horizontally first so that the page does not bounce

**Comment by ShrmnK** [comment]
Try lazyloading.

**Comment by nominalaeon** [comment]
Lazyloading's the right answer. A hack I've used in the past is to toggle visibility using the init callback.

<pre>
.slick-frame {
  visibility: hidden;
}

$slickFrame.on('init', function () {
  $slickFrame.css({visibility: 'visible'});
});
$slickFrame.slick();
</pre>

Don't use display: none, Slick won't be given a height value for the slides if'n you do.

**Comment by tomaszbujnowicz** [comment]
@nominalaeon thanks for the solution, it did the trick ;) Although it's not the most stylish solution as there is a blank space when the page loads (in the place where carousel will appear). Would be nice to have a preload with the spinner as default feature. Actually, ideally would be to see it in the core version of the plugin ;)

**Comment by rphelan** [comment]
You can also do this in pure CSS using the `.slick-initialized` class.

```css
.slick-frame {
    visibility: hidden;
}
.slick-frame.slick-initialized {
    visibility: visible;
}

**Comment by bunderwood** [comment]
@rphelan did the trick for me!  I spent HOURS trying other hacks to delay loading with js timers, etc.  Thanks a bunch.

**Comment by s2501** [comment]
@rphelan thanks a ton, probably would have spent hours, before figuring out which approach is best.
Your solutions further tweaked.
.slick-frame {

    background: #fff url('../img/carousel-loader/ajax-loader.gif') center center no-repeat;
    height: 300px;
    overflow: hidden;

    & > .generic-item-wrap-class {
        visibility: hidden;
    }

    &.slick-initialized {
        background: none;
        height: auto;
        overflow: auto;

        & > .generic-item-wrap-class {
            visibility: visible;
        }
    }
}

**Comment by samdoidge** [comment]
Thanks! @rphelan's fix worked for me, replacing ```.slick-frame``` with the class of my carousel.

**Comment by GuitarKat** [comment]
@rphelan's fix also worked for me. Simple and effective. Another thing to note is to look in the stack of how the script is loading on the waterfall in the network tab or if it's combined with other scripts in any fashion.

**Comment by liburanjogja** [comment]
for those who are still looking to solve this (and using slick slider on getwid blocks like I do), I've managed to solve my problems with this:

```
.top-slider {
	animation-name: fade;
  animation-duration: 3s;
	will-change: transform, opacity;
}
@keyframes fade {
  from {
    opacity: 0!important;
    height: 0!important;
    overflow: hidden;
    position: absolute!important;
    display: none!important; 
  }
  to {opacity: 1!important;
    height: auto; overflow:
    visible; position:
    relative!important;
    display: block!important;
  }
}
```

note: 
- top-slider is a class that I added to my parent wrapper, change it to yours.
- you can remove the "!important" rule if you don't need them.
