### ISSUE TITLE
When in 'accessibility' mode and input field has focus, slick should not move

### ISSUE THREAD

**Issue by jandersonBB** [kenwheeler/slick#1513]
Slick uses arrow keys to allow the user to navigate the carousel which is great, but, this functionality shouldn't obstruct navigating an input field.

When the user's focus is on an input field, the right/left keys should not invoke the transition of the slick panels.  This, I believe, goes against general accessibility principles.

Here's what I could find that I think applies to this situation...

From WCAG:

3.2.1 On Focus: When any component receives focus, it does not initiate a change of context. (Level A)
How to Meet 3.2.1 | Understanding 3.2.1
3.2.2 On Input: Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior before using the component. (Level A)

I've created a PR https://github.com/kenwheeler/slick/pull/1492 , that contains an example of a fix.

**Comment by leggomuhgreggo** [comment]
Resolved in the master. Thanks!
