### ISSUE TITLE
Does slick require the jQuery migrate plugin?

### ISSUE THREAD

**Issue by devinrhode2** [kenwheeler/slick#1514]

**Comment by ShrmnK** [comment]
Not that I know of. Recently completed a simple single-page site using only jquery and slick.

**Comment by mcashley** [comment]
Slick requires jQuery not the jQuery migrate plugin.
Closing.

**Comment by aude** [comment]
The project page kind of implies that jQuery migrate is required: http://kenwheeler.github.io/slick
Could that be changed?
