### ISSUE TITLE
Slide Option Not Working

### ISSUE THREAD

**Issue by leggomuhgreggo** [kenwheeler/slick#1517]
Looks like any direct descendant of the slick is considered a slide, even when a jquery string is specified for the slide option.

[Here's a pen demonstrating the issue.](http://codepen.io/gwst/pen/WvjGVM?editors=101)

Might be related to #1505 

Im guessing broke when the slide option changed to defaulting to child elements

Thanks as always to you guys for all your efforts in making such an awesome carousel.

**Comment by nominalaeon** [comment]
Who put that footer in the slider!?

I've always assumed that slick'ing all descendants was just how it worked. @simeydotme or @kenwheeler, is this supposed to be an option, like a user can send in a selector (array of selectors?) as an argument and have them be ignored? The concept is interesting, I'd like to look into it but I wanted to know if this is pre-existing and borked or if it would be a new feature?

**Comment by leggomuhgreggo** [comment]
@nominalaeon I totally agree it's a silly use-case. I just noticed it when I was working with some legacy markup and thought I'd alert the authorities #ifyouseesomethingsaysomething ;)

**Comment by simeydotme** [comment]
I think it's related to my PR: https://github.com/kenwheeler/slick/pull/1357 ... I'll be rebasing an merging all my PRs today, so I'd love it if you could test once I'm done, @leggomuhgreggo and 
@nominalaeon :smile: xx

**Comment by simeydotme** [comment]
Can you have a quick test with the master-branch `slick.js` file? :)

**Comment by leggomuhgreggo** [comment]
The slide option is working great! Thanks @simeydotme. One thing I noticed is the slide gets an outline now, because of default user agent styles for the new tabindex attribute, on chromium at least. Easy enough to at outline: 0 on but I wanted to give you a heads up. [Here's a related doc](https://developer.chrome.com/extensions/a11y#htmlcontrols)

**Comment by simeydotme** [comment]
Ah, that's from another dude's PR... https://github.com/kenwheeler/slick/pull/1467 -- is it possible you can give him a heads-up with the before/after screenshots? (i know its asking a lot) eek.

**Comment by simeydotme** [comment]
also: thanks for testing!! xxx

**Comment by leggomuhgreggo** [comment]
@simeydotme Happy to help!
