### ISSUE TITLE
applyTransition should also be applied to current slide before transition

### ISSUE THREAD

**Issue by kyleatfine** [kenwheeler/slick#1518]
I was working with a set of differently heighted texts when I came across this. Using `fade: true`, the current slide doesn't become transparent (opacity: 0) until after the next slide has transitioned in. I believe a nice feature would be to apply transition to the current slide before putting the transition in motion. Currently, applyTransition is only set on the slideIndex, if it was applied to both, then the now-previous slide would also transition/fade out.

**Comment by ethanclevenger91** [comment]
This should have been fixed by #1349 - are you running the latest build? (1.5.6)
