### ISSUE TITLE
Autoplay pauses on hover but doesn't resume

### ISSUE THREAD

**Issue by 1127** [kenwheeler/slick#1519]
This is from another user Nick who posted in a closed topic - not sure if you are seeing it so I'm repeating it here as I'm having the same issue.

This doesn't look like it's working again.

See my Codepen.

[http://codepen.io/NickToye/pen/rVYRvb] (http://codepen.io/NickToye/pen/rVYRvb)

Takes a while to actually pause, but doesn't restart.

My example is at:
[http://new.graphicdisplayusa.com/] (http://new.graphicdisplayusa.com/)
The scroller on the right (in white) is slick.

**Comment by stevecove** [comment]
Having the same issue (see http://clubsaway.co.uk/hotel/the-k-club-5-resort/ ).
The only way to restart the slider is to visit another browser tab, or swipe/click-drag to a new slide

**Comment by 1127** [comment]
What a ding dong I am. I should have checked the download here. On the [demo site] (http://kenwheeler.github.io/slick/) it is still 1.5. I'll close this issue.

**Comment by cassini-mohsin** [comment]
yeah that problem was with the 1.5.0 users.
