### ISSUE TITLE
Background images on mobile not showing

### ISSUE THREAD

**Issue by mparker11** [kenwheeler/slick#1522]
A few months ago I used version 1.3.15 and used background images instead of the normal img tag to fill the slider. This worked fine on mobile. Today I'm building a new site using version 1.5.6 and using background images does not render the images on mobile. It works fine for desktop though. The difference I'm seeing is that the slick track's width is set to zero as oppose to version 1.3.15. I'm trying to go through the code to figure it out but do you have any thoughts on this?

Thanks

**Comment by mparker11** [comment]
@kenwheeler If you see this, I figured out what the problem is but not exactly what lines. If you deem it worthy, maybe it can be fixed in the code but if not I understand.

For those who run into this same problem, I found out that the ".slick-list" width was not being set. For me, CSS fixes it easily where I can set width to be 100% on mobile. It seems like this is always the case, but I don't know the slider's code well enough to say.

**Comment by kenwheeler** [comment]
It's being set to 0 when?

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because it doesn't have a test case [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you can recreate it in a fiddle, we can look at reopening. Thanks!
