### ISSUE TITLE
Method 'refresh' throws a Javascript error when arrows:false

### ISSUE THREAD

**Issue by julianxhokaxhiu** [kenwheeler/slick#1524]
Hi,

I just updated this morning to Slick 1.5.6 and I tested it on my current project where I found this weird behavior. Before this was not happening ( so 1.5.5 or lower ).

Here you can find a demo where it throws the error ( look in the Console ): http://jsbin.com/cisahagica/edit?html,css,js,output

Thanks in advance and keep up this awesome project!

**Comment by leggomuhgreggo** [comment]
Also odd that there's only 3 dots, and 5 slides.
