### ISSUE TITLE
different settings on device

### ISSUE THREAD

**Issue by magdazelena** [kenwheeler/slick#1525]
Hey, I have a question: I need to have a slightly different plugin settings on mobile and desktop.
In detail, I want mobile to have adaptive height of slides and on desktop fixed.
I tried set it via window.resize, but it breaks my events on slides change.
Is there any way to do that you suggest?
Thanks in advance

**Comment by leggomuhgreggo** [comment]
Check out the docs, there's an option called "responsive" where you can define options at different break points. [There's an example](http://kenwheeler.github.io/slick/) implementation on the demo page. Make sure you define any option that will change at every breakpoint.

Also see [this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) about issue submission. I find it's helpful to search old issues to see if there's ever been a question about it.

Hope that helps. Thanks

**Comment by magdazelena** [comment]
Sure, sorry :)
The problem was that the responsive crashed the animations. I uploaded version 1.5.5 and it works great now.
