### ISSUE TITLE
Items in carousel are being removed on resize

### ISSUE THREAD

**Issue by jessepinuelas** [kenwheeler/slick#1526]
Came across a weird issue when resizing the browser and using the responsive option.

$('.carousel-name').slick({
                slidesToShow: 3,
                slidesToScroll: 3,
                speed: 500,
                dots: true,
                arrows: true,
                mobileFirst: true,
                responsive: [
                    {
                        breakpoint: 1025,
                        settings: {
                            centerMode: true,
                            centerPadding: '25%',
                            slidesToShow: 1
                        }
                    }
                ]
});

If you have 6 items in your carousel and you resize and hit the breakpoint it removes the last three items not in view.

**Comment by leggomuhgreggo** [comment]
Check [this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) out, bro

**Comment by jessepinuelas** [comment]
@leggomuhgreggo I will have to post something later this evening as I am a little under the gun with a deadline. But what appears to be happening is the cloned items added to carousels + one additional item is being removed when you hit the break point specified. I think i've narrowed the issue down to slick/handlebars. Will post a fiddle as soon as I can.

**Comment by leggomuhgreggo** [comment]
Word. I made [this](http://codepen.io/gwst/pen/waXWYB?editors=011) with your settings and it seems to be working. Hope that helps.
