### ISSUE TITLE
Centermode, remove the partial prev/next slides?

### ISSUE THREAD

**Issue by kkashou** [kenwheeler/slick#1527]
I was wondering, if there is a way to remove the partial prev/next slides when viewing centermode? 

I tried this approach with afterChange/beforeChange you add a class name (not-active) class name and with css {visibility: hidden}. But with afterChange, the slider comes in late and beforeChange doesn't get the right slide to attach the class name. 

Any other solutions?

Thanks

**Comment by nominalaeon** [comment]
Try this:

    var slideWidth = this.$slickFrame.width() / 3;
    var centerPadding = (slideWidth / 4) * 3;

    var slickOptions = {
        centerMode: true,
        centerPadding: centerPadding + 'px'
        slidesToShow: 1
    };

We used that to accomplish a mobile view for some sliders where only a portion of the prev/next slides were visible. Just change the centerPadding formula for however much of the siblings you want visible.

**Comment by kkashou** [comment]
Where is the "this" referencing to? 

THis is my current code: 

<pre>
            $('.tab-slider-thumbs__list').slick({
                asNavFor: '.tab-slider__list',
                dots: false,
                arrows: false,
                infinite: true,
                speed: 600,
                focusOnSelect: true,
                centerMode: true,
                slidesToShow: 5,
                slidesToScroll: 1,

                responsive: [{
                    breakpoint: 960,
                    settings: {
                        slidesToShow: 3
                    }
                }, {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 1
                    }
                }]
            });
</pre>

**Comment by nominalaeon** [comment]
Changed my code to reflect yours. Make slidesToShow 1 and set the centerPadding and you're there. Instead of doing the responsive args, I'd do an if/else when I set my centerPadding to be either the partial view or the fullview: `centerPadding = slideWidth`

**Comment by kkashou** [comment]
hmm I want to always show 5 slides and the center always being active. But I don't want the prev/next slides to show partial of it. This doesn't seems like it is doing that affect. :/

**Comment by nominalaeon** [comment]
Ooohhhh, sorry, I misread. You **don't** want to see the partials. Then yeah keep your slidesToShow as is and set centerPadding to 0px maybe? Seems like it should be 0 by default but maybe it's not

**Comment by kkashou** [comment]
No worries! :) That worked! Thanks

**Comment by idubinets** [comment]
> Try this:
> 
> ```
> var $slickFrame = $('.tab-slider-thumbs__list');
> 
> var slideWidth = $slickFrame.width() / 3;
> var centerPadding = (slideWidth / 4) * 3;
> 
> var slickOptions = {
>     centerMode: true,
>     centerPadding: centerPadding + 'px'
>     slidesToShow: 1
> };
> ```
> 
> We used that to accomplish a mobile view for some sliders where only a portion of the prev/next slides were visible. Just change the centerPadding formula for however much of the siblings you want visible.

it is possible to avoid this magic and use use just some slick plugin parameter? I think it must be built in feature
