### ISSUE TITLE
After Update to 1.5.6 - All Carousles Broken (TypeError: _.$prevArrow is null)

### ISSUE THREAD

**Issue by DerekFoulk** [kenwheeler/slick#1528]
I receive the following error in my console (in both Chrome and Firefox on Linux Mint 17.2):
> TypeError: _.$prevArrow is null (slick.js:830:0)

I have tried both the bower 1.5.6 version and the version that you can download directly from your github.io page: [https://github.com/kenwheeler/slick/archive/1.5.6.zip](https://github.com/kenwheeler/slick/archive/1.5.6.zip)... Both are not working properly and are throwing the same error.

I reverted back to 1.5.5 and all is working fine. I'd love to utilize the most recent update, but it simply is broken.

Thanks for this awesome plugin, and thanks in adavnce for any assitance in fixing this error!

**Comment by leggomuhgreggo** [comment]
Guessing it's something with the implementation; can you recreate in a fiddle ([see this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)).

**Comment by DerekFoulk** [comment]
https://jsfiddle.net/derekfoulk/y2Lgmns7/

**Comment by DerekFoulk** [comment]
I updated the link to the Fiddle with the correct URL...

**Comment by leggomuhgreggo** [comment]
I see what you mean. Looks like its related to this issue to #1524

**Comment by DerekFoulk** [comment]
Definitely related. I will take a look after work and see if I can patch this...

**Comment by kenwheeler** [comment]
@simeydotme This got introduced here https://github.com/kenwheeler/slick/pull/1331/files

![http://th01.deviantart.net/fs70/PRE/i/2013/202/f/6/dicdave_by_spring_heel_jackie-d6ei1sh.png](http://th01.deviantart.net/fs70/PRE/i/2013/202/f/6/dicdave_by_spring_heel_jackie-d6ei1sh.png)

**Comment by simeydotme** [comment]
I'll take a look... Apologies for any inconvenience, it was working 👌 locally!

**Comment by julianxhokaxhiu** [comment]
Any bower release in plan?
