### ISSUE TITLE
slickRemove does not renumber data-slick-index in right way

### ISSUE THREAD

**Issue by bsv89** [kenwheeler/slick#1531]
The problem occurs when we deleting item from the middle, or more precisely <strong> when we deleting item that is not last item</strong> of carouse. As a consequence of this we have two different elements with the same data-slick-index.  Here is my  <a href="http://jsfiddle.net/1m2erc3f/"> JSFiddle </a> example, where we have two duplicate indeces.

Now it turns out that the problem locates in setupInfinite() method :
<pre>
<code>
for (i = 0; i < infiniteCount; i += 1) { 
                    slideIndex = i;
                    $(_.$slides[slideIndex]).clone(true).attr('id', '')
                        .attr('data-slick-index', slideIndex + _.slideCount)                                                                                        
                        .appendTo(_.$slideTrack).addClass('slick-cloned');
}
</code>
</pre>

When some element, <strong>that is not last</strong>, was removed the data-slick-index of the <strong>last 'real'</strong> element did not changes, but the _.slideCount decreases by 1, and hence we have following math:

Before deletion:
<em>data-slick-index (of the last 'real' carousel element) = _.$slides.length - 1</em>
and the data-slick-index of additional clone elements starts with 
<em> slideIndex + _.slideCount which in fact is equal to _.$slides.length</em>

After deletion: 
<em>data-slick-index (of the last 'real' carousel element) is still the same as it was before i.e equals to <strong> _.$slides.length - 1</strong></em>
but now data-slick-index of additional clone elements starts with 
<em> slideIndex + _.slideCount =  <strong>_.$slides.length - 1</strong></em>

That is how duplicates occurs.

**Comment by JonathanAquino** [comment]
I am seeing this issue as well.

**Comment by leggomuhgreggo** [comment]
Hey, it looks like this might have been resolved at some point in the master. I'm going to close, but if you want to circle back with a fresh test case, please feel free. Thanks!

**Comment by Davidkulpe** [comment]
still an issue
