### ISSUE TITLE
Prev Arrow doesn't show

### ISSUE THREAD

**Issue by dirkbartels14050** [kenwheeler/slick#1532]
Just upgraded to the latest version 1.56, now the prev arrow is not showing anymore. The next arrow works just fine The CSS code is unchanged:

/* config for the slick carousel arrows etc. */
.slick-prev,
.slick-next
{
    top: 45%;
    width: 35px;
    height: 100px;
}

.slick-prev:before,
.slick-next:before
{
    opacity: .50;
    color: white;
}

.slick-prev:hover:before,
.slick-prev:focus:before,
.slick-next:hover:before,
.slick-next:focus:before
{
    opacity: 0.75;
}

.slick-prev:before
{
    content: url("Pfeil_Navi_links_solid.svg") no-repeat; 

}

[dir='rtl'] .slick-prev:before
{
    content: url("Pfeil_Navi_rechts_solid.svg") no-repeat;

}

.slick-next:before
{
        content: url("Pfeil_Navi_rechts_solid.svg") no-repeat;

}

[dir='rtl'] .slick-next:before
{
    content: url("Pfeil_Navi_links_solid.svg") no-repeat; 
}

.slick-prev {
  left: 20px;
}

.slick-next {
  right: 20px;
}

**Comment by leggomuhgreggo** [comment]
Hey bro can you whip up a fiddle with your implementation? See [this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).
Thanks!

**Comment by dirkbartels14050** [comment]
@leggomuhgreggo okay, will do this later, need to isolate the code

**Comment by dirkbartels14050** [comment]
here you go:

https://jsfiddle.net/9bxe6tgL/1/

**Comment by leggomuhgreggo** [comment]
Ah yeah the order changed in the DOM; I think so that tab sequence would be more natural for accessibility. If you add a z-index to .slick-prev you'll see it.

**Comment by dirkbartels14050** [comment]
I'll check it out later. Thanks

Dirk

**Comment by dirkbartels14050** [comment]
z-index: 1 does the trick. Thanks again for your help

**Comment by Davron-Gafurov** [comment]
trtrrttrtrtr
