### ISSUE TITLE
layout is really broken when items inside use % widths

### ISSUE THREAD

**Issue by Alex-Nabu** [kenwheeler/slick#1533]
Yeah..

**Comment by leggomuhgreggo** [comment]
So--real quick--make sure when you're submitting an issue that you follow the [slick contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), and creating a fiddle to demonstrate the problem. 

Now with regard to slide widths, Slick.js actually calculates the slide width based on the options and the container dimensions. Unless it's being overridden, the slide width will recalculate responsively to the container, without any additional styles. Holler back with a fiddle if that's not twerkin for you.

**Comment by Alex-Nabu** [comment]
@leggomuhgreggo Thanks for your help so much. I was using this other carousel plugin and it had foobared my html and I didnt notice
