### ISSUE TITLE
Problem with using methods inside 'init' event

### ISSUE THREAD

**Issue by mciastek** [kenwheeler/slick#1535]
Hey,

using random method inside 'init' event callback throws an error. See fiddle: http://jsfiddle.net/pvywh08c/

If you wrap it into ```setTimeout()```, there's no error.

```
setTimeout(function() {
  console.log(slider.slick('slickCurrentSlide'));
}, 0);
```

Is that a bug?

**Comment by leggomuhgreggo** [comment]
Can't holler at init event after the actual init--looks like that's the issue. I'm going to close, but if that doesn't clarify we can look at reopening. Thanks!
