### ISSUE TITLE
Respo crashes when arrows: false 

### ISSUE THREAD

**Issue by michalsnik** [kenwheeler/slick#1536]
{
arrows: false,
responsive: [...]
}

Slick crashes and there is error in console "Uncaught TypeError: Cannot read property 'length' of null",
but when arrows is set to "true" everything is fine.

**Comment by michalsnik** [comment]
This problem occures only in 1.5.6 version, previous 1.5.5 is fine, and so master branch is ok.

This line is wrong in 1.5.6:
https://github.com/kenwheeler/slick/blob/1.5.6/slick/slick.js#L830

And this is correct (master branch)
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L832

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/1528
Sorry for the inconvenience.

**Comment by TwentyOverTen** [comment]
Is this fixed? I'm still seeing this error in my console. Whole thing breaks when I go down to my responsive breakpoint...

````
Cannot read property 'length' of null
````

**Comment by ndimatteo** [comment]
Don't forget to apply to the minified js file. I grabbed that and still saw the error, realized it wasn't updated.

**Comment by david-06studio** [comment]
i confirm : 
- version 1.5.6 (minified) doesnt work.
- version 1.5.6 (normal) doesnt work.
- version 1.5.5 (minified) working.
- version 1.5.6 (normal) working.

**Comment by wjthomas9** [comment]
Ah! Just ran in to this and have been baffled. If arrows: false then I get the same error.

**Comment by PeanutButterCo** [comment]
Same over here. Thanks for the best carousel ever by the way...

**Comment by simeydotme** [comment]
Sorted with 1.5.7 :)

**Comment by wjthomas9** [comment]
Sweet! Thank you. :-)

On Jul 23, 2015, at 6:55 PM, Simon Goellner <notifications@github.com>
wrote:

Sorted with 1.5.7 :)

—
Reply to this email directly or view it on GitHub
<https://github.com/kenwheeler/slick/issues/1536#issuecomment-124272126>.

**Comment by wjthomas9** [comment]
Still no luck with 1.5.7. When I re-size the browser from large to small, the arrows still don't disappear. 1.5.5 works fine.

**Comment by simeydotme** [comment]
Please can you make a JSFIDDLE (like the one in contributing.md) please, and describe your issue properly

**Comment by wjthomas9** [comment]
Sure. This fiddle has the JS code I’m using.

https://jsfiddle.net/82da8L77/ <https://jsfiddle.net/82da8L77/>

Thanks!

**Comment by simeydotme** [comment]
Thanks so much @wjthomas9 !! 
That helped me find the root cause! -- your problem is actually different to the original topic.

Such a disaster :cry: when you think you've covered every damn scenario... you havent.

**Comment by wjthomas9** [comment]
Oops, I thought it was a similar issue. Sorry about that! Glad you found the root cause though.

**Comment by simeydotme** [comment]
@wjthomas9 please check your fiddle again, and do a hard-refresh to clear your cache... the fille is working now, right? (using the master-branch code)

**Comment by wjthomas9** [comment]
Yep! Looks like the arrows get removed and re-added again depending on the breakpoint. I think we’re good!

--
Jon Thomas
AnalyticL Inc.
217-638-2636
www.analyticl.com
