### ISSUE TITLE
How to create double carousel slider

### ISSUE THREAD

**Issue by DJviolin** [kenwheeler/slick#1539]
Is it possible to create a double carousel with "slick" slider like on [this](http://www.elizabethmessina.com/#/images/love/gallery/27) site?

The bottom slider has less SlideToScroll speed than the upper that is rotating one by one?

How to connect both slider to mirror the same images (but maybe not the same files - highres, lowres)?

Can you show a possible solution?

**Comment by simeydotme** [comment]
Yup.
Sorry, this is for tracking problems, not solving yours :) -- please read the contributing.md file for more info.

Simon.
