### ISSUE TITLE
slickUnfilter method causes problems with nested slick lists.

### ISSUE THREAD

**Issue by tosaha** [kenwheeler/slick#1541]
I've been using Slick to help me deal with the minimal-ui issues with iPhone Safari browsing. Basically my whole page is built around Slick. Something like this:

    <div class="slick">
        <div class="slide">[page content]</div>
        <div class="slide">[menu panel]</div>
        <div class="slide">[menu panel]</div>
        <div class="slide">[menu panel]</div>
    </div>

As you can see, I insert all my page's content into the first slide. Using the magic of Slick, I slickFilter all but the first slide and then slickUnfilter when someone clicks on the menu trigger. Works great.

Unfortunately, if I have another slick list nested in this one things get a bit fakakta. The slickUnfilter method calls unload that removes the dynamic element .slick-cloned. This ends up removing all nested .slick-cloned elements too which offsets nested lists.

I changed lined 2215 on slick.js 1.5.0 from:

    $('.slick-cloned', _.$slider).remove();

to:

    $('> .slick-list > .slick-track > .slick-cloned', _.$slider).remove();

Not the most elegant solution, but it works for me. Just thought I'd bring this up in case anyone else had the same issue.

**Comment by leggomuhgreggo** [comment]
Hey @tosaha sorry such a long time has gone without this being attended to. Looks like this is related to #1846 and #2009. Hopefully it gets ironed out in the 2.0 release.

Definitely appreciate you taking the time to make the bug report. As a heads up for future, there're some helpful [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). Thanks!
