### ISSUE TITLE
Variable widths by percentage

### ISSUE THREAD

**Issue by yougotashovel** [kenwheeler/slick#1542]
Is it possible to have adaptive and responsive widths?

For example:
1. I have a slider that shows 4 panels at one time.
2. Each panel width is 25%, total width is 100%.
3. Then i want to change one of the panel widths to 50% and push one of the 25% panels out of view. 
4. So the total width is now 125%, but the screen still only shows 100%: 3 panels, one with 50% and two with 25%.

Also, a side question: how would this work using something like a css grid within the slider, so i could give all panels classes like '1of4' and change it to '1of2'.

Does anybody have an idea of how this could be accomplished?  I've been trying for a while but can't figure it out.

Thanks

**Comment by yougotashovel** [comment]
I realise the question above isn't so clear.  Here's a simpler one:

Is it possible to have slides with variable percentage widths?
E.g. 25% 50% 75% 100%

If not, what are the potential issues with this?

**Comment by rgblab** [comment]
i would like to know this too. experimenting with grid elements under slider, but, as I can see, if variable width is set to true, width of carousel items is calculated from parent element - slick-track - which is way wider than its parent.

**Comment by ejwaibel** [comment]
The way we "solved" this, was by having multiple individual slide items (outside of a grid) and then setting "slidesToShow" to the number of slides that need to be displayed at a time. This would then automatically calculate the slides based on how many are being shown at once.

**Comment by rgblab** [comment]
yes, this is what i'we been using too. but... all items do have same width, otherwise, possible scenario is to have "hero" slide that is 100% wide, and other slides smaller.

**Comment by leggomuhgreggo** [comment]
Hey I know this issue was created a while ago, but if you’re still interested can you recreate in a [fiddle with the master](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
)? Apologies for the dormancy.

Closing pending fiddle
