### ISSUE TITLE
'accessibility' is set to false, still seeing ARIA related attributes inside each slide.

### ISSUE THREAD

**Issue by qbunt** [kenwheeler/slick#1544]
http://jsfiddle.net/2o124dvb/

The accessibility values inside the carousel are getting set even if they're disabled. We have to fix very specific accessibility requirements that do not fall inline with the current accessibility implementation. When 'accessibility' is set to false, the plugin should not even render any aria related roles or tags.

Currently, there's no way to remove aria attributes outside of stripping them out manually.

**Comment by surfbird0713** [comment]
This is causing an issue for me too. When I have dots set to false, the aria-describedby attribute is still being added to the slides even though there is not a corresponding element with that ID (since dots are turned off).

**Comment by qbunt** [comment]
I've stripped the ARIA attributes of the plugin inside my own fork, but it's unclear what is going to happen with this issue or the ARIA features that were initially implemented. Any update?

**Comment by leggomuhgreggo** [comment]
No update that I'm aware of, but if all we're talking about is testing the accessibility option for aria attributes, that seems pretty doable.

**Comment by qbunt** [comment]
Sadly there's more involved than just checking to see if those attributes are present. The trouble is dropping them completely if accessibility is set to false. We had major issues with this simply because we had to comply with WCAG 2.0 AA standards and screen readers would simply choke on the plugin. This has been cited by [other users here](https://github.com/kenwheeler/slick/issues/1820), so maybe I should close this and keep this in one issue? Thoughts?

**Comment by leggomuhgreggo** [comment]
Yes sounds good! Thanks for finding that other issue!
