### ISSUE TITLE
slickGoTo method goes clockwise

### ISSUE THREAD

**Issue by CHEWX** [kenwheeler/slick#1550]
Hi,

Found an issue where linking together a couple of sliders and using the method 'slickGoTo'.

The count is 20.

When clicking the goTo handler at the start of the slider and requesting to go to 20, instead of going backwards from 1 in will go all the way round to 20.

Thanks.

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because there is no test case, [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you make one we can look at reopening. Thanks
