### ISSUE TITLE
Responsivness on and off VPN

### ISSUE THREAD

**Issue by erthi16** [kenwheeler/slick#1552]
Hello to all!
I have an issue since my website is behind a new proxy server... Before that, my carrousel was presenting 1 slide 100% width at a time without problems in or out of my network... but now, the same carrousel is presenting 2 cut slides when I'm visiting my site from home but at work or via VPN everything is OK! I was wandering if the responsive section of the code uses some external script or ressources that the proxy could refuse from the outside world?
It's a wild guest by I'm totaly lost here!
Thanks a million times for any clue!

**Comment by leggomuhgreggo** [comment]
Hey, apologies for so long a time without this getting attention. I'm closing this because it's a support request--seems like a local networking issue. Good luck!
