### ISSUE TITLE
Responsive slider problem since 1.5.6

### ISSUE THREAD

**Issue by CHEWX** [kenwheeler/slick#1554]
Hi,

The slider isn't generating the correct width since the update when dragging the browser width in. Upon refresh the same issue occurs.

Video before:
http://quick.as/aZQAHarnx

Video after:
http://quick.as/6aGriQLor

Thanks.

**Comment by simeydotme** [comment]
Can you try with 1.5.7 please :)

**Comment by simeydotme** [comment]
And create a JSFiddlenif the problem still eXISTS

**Comment by CHEWX** [comment]
Still hasn't fixed the problem. Same problem as above still.

Will try and set-up a JSFiddle.

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because there is no fiddle. If you make one we can look at reopening. Thanks!
