### ISSUE TITLE
Slide filter fadeIn effect

### ISSUE THREAD

**Issue by devang-patel** [kenwheeler/slick#1555]
Hi,

First of all, Thanks for the awesome plugin.

Can we fadeIn slide when filter method is used?
When i filter slides, its jumps directly without any fade effects, How can I fadeIn slide on filter?

Thanks in advance.

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because there is no test case, [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you make one we can look at reopening. Thanks

**Comment by andywells** [comment]
Here is a JSFiddle with a test case: http://jsfiddle.net/qgxw98jn/

When filtering to a single slide (or collection of slides), if `fade == true`, I would expect the transition from the current slide to the filtered slide(s) to fade.
