### ISSUE TITLE
Destroy function error

### ISSUE THREAD

**Issue by FDiskas** [kenwheeler/slick#1557]
```TypeError: Cannot read property 'length' of null```
error points to the line of code: at Slick.destroy
```if ( _.$prevArrow.length ) {```
and at Slick.unslick
```
Latest version: 1.5.6

**Comment by timhettler** [comment]
Should check for existence of _.$prevArrow, not length, since that object only gets defined if arrows are true.

**Comment by FDiskas** [comment]
Yes you are right. I made some changes ti skip that error but still waiting
for official release

Vytenis Kučiauskas

**Comment by timhettler** [comment]
Pull request button is :arrow_right:

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/commit/4f8adffddb949cddb8a447f18dc3ccb182c7ac3e
