### ISSUE TITLE
Nested Sliders

### ISSUE THREAD

**Issue by binaryben1010** [kenwheeler/slick#1559]
We use nested slick sliders (slider in slider) which can behave erratically as the inner slider can be affected by outer slider operation.  In looking through the code there are a number of places where the slick-slider finds slides with a jQuery  .find(".slick-slide") this is weak in that it will also find a child slider's slide . This technique is also done for '.slick-cloned'  and others.  Could these all please be replaced with a more precise targeting as all the elements between a slick-slider and the slide are predictable as they are inserted by the slick code itself.
A replacement could be:
.children().children().children(".slick-slide")
OR   .find(".slick-list>.slick-track>.slick-slide")       using the direct children '>'
But I expect there is a faster more elegant way to achieve this.  

jsfiddle:  http://jsfiddle.net/binaryben/vdgs4v1x/

**Comment by simeydotme** [comment]
related to #1846
