### ISSUE TITLE
"HUUUUUUUGE-ass update" shouldn't be a patch version

### ISSUE THREAD

**Issue by timhettler** [kenwheeler/slick#1561]
Package managers automatically upgrade for patches, so if you're pushing anything other than bug fixes, it should really be at least a minor (1.X) version update. 

Love this library, but the 1.5.6 update caused a production error for a client. (Will report the bug separately.)

Please be more responsible about tagging releases.

http://semver.org/

**Comment by leggomuhgreggo** [comment]
I'd say this is a fair request to honor, but you know what they say about appeasing Hettler

**Comment by timhettler** [comment]
No, what do they say?

**Comment by leggomuhgreggo** [comment]
Hettler had a point, and brought forth 1000 years of proper versioning practices.

**Comment by kenwheeler** [comment]
You are right and I'm sorry. If you are ever in the tri state area, you get to punch me once.

**Comment by kenwheeler** [comment]
I actually hadn't realized how many PRs were in the update until after I pushed it, I just wanted to land the new accessibility stuff.

**Comment by simeydotme** [comment]
The accessibility enhancement unfortunately has had so many questions surrounding it, especially the stuff about focussing/highlighting the slides :(

@timhettler can you share your production problem, so we can help anyone else who might have this issue, and try to smooth out the damage :) x

**Comment by timhettler** [comment]
The problem is defined in #1557. I've reverted the production code to use v1.5.5 of Slick in the meantime.

Thanks for responding, guys!

P.S. @kenwheeler I live in Brooklyn – I'll start stretching my punching arm :muscle:

**Comment by kenwheeler** [comment]
@timhettler released 1.5.7 this morning

**Comment by simeydotme** [comment]
I need a video of the pumch in slo-mo-4k !

**Comment by azz0r** [comment]
Hello,

I agree completely. We had an IE8 Issue with 1.5.6, so we are using 1.5.7

However when new developers are installing they are getting 1.5.6 even though our package JSON specifies 1.5.7; forcing us to communicate that they must install slick separately.

Not ideal for large development teams.

**Comment by kenwheeler** [comment]
Why are they getting 1.5.6?

**Comment by azz0r** [comment]
Package JSON is set to:

    "slick-carousel": "^1.5.7",

If we run npm install its installing 1.5.6

**Comment by kenwheeler** [comment]
You should be on 1.5.8

**Comment by azz0r** [comment]
If I do an npm install with my package JSON set to 1.5.8, it still servers me 1.5.6

slick-carousel@1.5.6 node_modules/slick-carousel

**Comment by kenwheeler** [comment]
Noted, but you should bump your dep to 1.5.8

**Comment by kenwheeler** [comment]
npm install slick-carousel@1.5.8 -save

**Comment by azz0r** [comment]
Dependancy is set to 1.5.8, it still serves 1.5.6, this is why I've come to the issue tracker and found this issue. 

(Thought I was set on 5.7 on my initial commit, this has been corrected but remains an issue).

**Comment by kenwheeler** [comment]
It's because you're using the `^` modifier.

**Comment by kenwheeler** [comment]
If you aren't using that modifier, are you using the central registry or an enterprise registry?

**Comment by azz0r** [comment]
central repo. Removing ^ changes nothing, 1.5.6 is served

**Comment by kenwheeler** [comment]
You might need to clean your npm cache
