### ISSUE TITLE
Blue border on click in Chrome

### ISSUE THREAD

**Issue by daveyjones** [kenwheeler/slick#1562]
I'm getting blue outlines around each slide when clicking on a carousel in Chrome.

<img width="971" alt="outlines" src="https://cloud.githubusercontent.com/assets/2852617/8833576/50977798-3064-11e5-8796-58b3068aff44.png">

The fix is very easy:

```
.slick-list {
    outline: none;
}
```

Or possibly this, if there is risk of this getting overwritten:

```
.slick-list {
    outline: none !important;
}
```

I'm not familiar with the organization of this project, so I'll let someone more involved decide where to make this change (or whether it should be changed at all).

**Comment by simeydotme** [comment]
:weary: 


It's been noted/raised many times.
Thanks for contributing! :) -- hope it didn't cause you too much trouble.

**Comment by pesh2000** [comment]
On a current project I actually needed

.slick-slide {
    outline: none !important;
}

to get rid of the blue border.

**Comment by asadkn** [comment]
Seems like it is back. But this fixes it:

`.slick-slide:focus { 
    outline: none; 
}`

**Comment by dhstack** [comment]
I had links inside my slides, so this worked for me:
```
.slick-slide {
  &:focus, a {
    outline: none;
  }
}
```
(by the way this is LESS, not CSS so it looks slightly different)

**Comment by dinglestein** [comment]
Thanks @dhstack :)

**Comment by Jtmichel** [comment]
I obliterated this using:

`.slick-slide, .slick-slide *{
outline: none !important;
}`

**Comment by swillis93** [comment]
Brilliant, thanks @Jtmichel I was pullin gmy hair out with this one.

**Comment by Sitronik** [comment]
@Jtmichel thanks I fixed.

**Comment by fahimiali** [comment]
thanks... it worked for me in another project ...

**Comment by bengalamx** [comment]
Easy: `.slick-slider * { outline: none; }`

**Comment by Perezo123** [comment]
please where should i put this code...

**Comment by Jtmichel** [comment]
@Perezo123 can you send a URL or screenshot to example?

**Comment by Perezo123** [comment]
[http://adelek.sk/telgart/brezno.html](url) for example here ..

**Comment by Jtmichel** [comment]
The atomic solution is .slick-slide, .slick-slide *{ outline: none !important; }, but if you can send me a URL to this I can take a closer look.

**Comment by Perezo123** [comment]
here is url: http://adelek.sk/telgart/brezno.html

**Comment by Jtmichel** [comment]
@Perezo123 I navigated to the page but I don't see a slider, just a list of lightboxed items. I tried to call slick in the console but it doesn't seem to think it's a function. Is this the same as what you're seeing?

<img width="1064" alt="screen shot 2017-10-25 at 6 29 04 pm" src="https://user-images.githubusercontent.com/4700591/32026436-6cab711c-b9b2-11e7-86a4-345b0ff0eb76.png">

**Comment by Perezo123** [comment]
yes it is the same ... but like i said before i had this problem after closing img lightbox ... not with carousel :P  i use here fancybox plugin but after closing image i had still that annoying blue outline all over <a> and <img>

**Comment by Jtmichel** [comment]
`.container a { outline: 0; }` will do the trick.

**Comment by Perezo123** [comment]
thanks this works perfect :P

**Comment by prasannajathan** [comment]
This should do the fix,  
`.slick-slide>div:focus {
  outline: none;
}`

**Comment by mehnich** [comment]
.slick-slide {
   div {
    outline: none;
  }
}

**Comment by avinashmishra26** [comment]
I'm using angular 8 and ng-bootstrap 5.
You can apply this:

.carousel:focus {
	outline: none; 
}

**Comment by Vince-vegas** [comment]
Write this to your css file
`
.slick-slide div {
outline: none;
}

`
