### ISSUE TITLE
Rows and then revert to one row on mobile

### ISSUE THREAD

**Issue by padjodev** [kenwheeler/slick#1564]
I have a slider which shows 2 rows of slides on desktop but when you go down to mobile i want just one row, or basically to revert to just a standard slick slider.. I have tried using the responsive breakpoints but to no avail... is this possible to do with slick.. check out my current markup where i try to go from 2 rows to just one:

$('.prod-slider').slick({
        infinite: true,
        rows: 2,
        slidesPerRow: 2,
        dots: true,
        infinite: true,
        speed: 300,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        infinite: true,
        rows: 1,
        slidesPerRow: 1,
        dots: true,
        infinite: true,
        speed: 300,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
        }
    },
    {
      breakpoint: 767,
      settings: {
        infinite: true,
        rows: 1,
        slidesPerRow: 1,
        dots: true,
        infinite: true,
        speed: 300,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
      }
    }
  ]
});

**Comment by Bartlomiejsz** [comment]
Check my pull request: https://github.com/kenwheeler/slick/pull/1660
Use this code and add 'activateRows': true option when using 1 row :)

**Comment by leggomuhgreggo** [comment]
Hey, apologies for the considerable delay in addressing this issue! Im closing this because it lacks a test case, [per the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), but hopefully @Bartlomiejsz's branch will suffice until the issue gets addressed in the master. Thanks!

**Comment by Qasim240** [comment]
**/* Note: Using this style ensures proper spacing between slides. However, it will result in the slider scrolling two slides at a time, so use it only if you're okay with this compromise. */**

.slick-slide {
    display: flex;
    gap: 10px;
}
