### ISSUE TITLE
responsive/breakpoint unslick problem

### ISSUE THREAD

**Issue by bw1984** [kenwheeler/slick#1565]
I have set 'unslick' on my widest breakpoint (as per docs) with a view to display my items in a grid at larger device sizes. this works as expected when 'entering' the breakpoint that unslick is set on (i.e. the carousel gets destroyed/deactivated), but when resizing the window back down into the narrower breakpoints the carousel never reinitializes.

is this intended functionality, a bug or do i have to add a specific argument to my settings in the other breakpoints in order to reinitialize it somehow?

**Comment by simeydotme** [comment]
Its the design of the method :)

**Comment by sthzg** [comment]
@simeydotme do you consider extending the features to provide `reslick` behavior out of the box? As I understand, to make it behave that way we would have to set a listener on `window.resize` and then reinitiate when appropriate. However, when we already have the listener in place then the `unslick` in the responsive settings isn't of that much use. Not that it's so big a deal, just curious.

**Comment by jackbarham** [comment]
I second this - I'm working on a project now where I need to `unslick` and `reslick` without having to refresh the page to reinitiate it.

**Comment by ibanjo** [comment]
Old issue, yet important, at least to me. Would be a nice feature the possibility to unslick and reslick responsively.
