### ISSUE TITLE
Delay before render

### ISSUE THREAD

**Issue by robhadfield** [kenwheeler/slick#1568]
Hi - I wonder if anyone can help with this one...

I have an issue where the slider is initialising but is taking a while to render correctly after initialisation....

If you head here : http://bit.ly/1MLerPa and click the thumbnail under the years you will see that 10 small images appear (and the slick init fires) but takes a few seconds before the slider renders...

Any ideas?
Cheers in advance!
Rob

**Comment by robhadfield** [comment]
This my config for that slider:

            slider.on('init', function(slick){
                slider.show();
            })
            .slick({
                dots: false,
                arrows: false,
                infinite: true,
                autoplaySpeed: 4000,
                draggable: true,
                slidesToShow: 5,
                centerMode: true,
                autoplay: true,
                cssEase: 'ease-in-out',
                variableWidth: true
            });

**Comment by leggomuhgreggo** [comment]
Hey, sorry that this didn't get any attention for so long. Trying to diagnose issues from a production-ready environment like the test case link you provided is difficult--too many variables, but if you are still interested, you can make a fiddle. Judging by what I'm reading this is another issue regarding slide layout prior to initialization. There're several ways to approach this issue, primarily having to do with matching pre and post init layouts or using a class added by the slick init to achieve some layout goal. I do this.

`slideElement:not(.slick-slide):not(:first-child){display:none}`

Hope that helps
