### ISSUE TITLE
carousel navigation and arrows

### ISSUE THREAD

**Issue by dhenriet** [kenwheeler/slick#1570]
Hi thanks for this great plugin :) 
I am having issue with 
- the next and prev arrows, sometimes they are missing so we can't use carousel to go to the end or beginning slides. 
- after a click current big image index is not the good, it's different from carousel image index 
- onclick on thumb 2, carousel slide to the right and goes to thumb 6, I can't go to thumb 0.

https://jsfiddle.net/fxLcucoq/1/

```js
jQuery(document).ready(function($) {
            $('.vs-img-slider').slick({
                infinite: false,
                slidesToShow: 1,
                slidesToScroll: 1,
                arrows: false,
                fade: true,
                asNavFor: '.vs-img-pager'
            });
            $('.vs-img-pager').slick({
                infinite: false,
                mobileFirst: true,
                slidesToShow: 5,
                slidesToScroll: 1,
                asNavFor: '.vs-img-slider',
                dots: false,                
                variableWidth: true,
                focusOnSelect: true
            });
            $('.slick-slide:first-child').addClass('active');
            $('.vs-img-pager').on('click', '.slick-slide', function(event) {
                $('.vs-img-pager .slick-slide').removeClass('active');
                $(this).addClass('active');
            });
 });  
```

![screenshot_1](https://cloud.githubusercontent.com/assets/4640027/8902008/de179002-344d-11e5-993e-b56813b62b2c.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4640027/8902009/de1b39c8-344d-11e5-9b89-b45cb4539d91.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/4640027/8902010/de21c5fe-344d-11e5-94bb-5e586244ea67.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/4640027/8902011/de2369f4-344d-11e5-80dd-9dd3fd26927e.png)

**Comment by simeydotme** [comment]
hey thanks @dhenriet but please can you follow the contribution guidelines in the repository and make a JSfiddle that I can debug?

Your codepen has both minified versions of jQuery and Slick, and the Codepen interface is not very productive for debugging code. Go ahead and make a JSFiddle based off the master branch, and I'll look in to this.

Also a proper description of your issue would help... I don't see what is wrong with your current picture :)

**Comment by danb-cws** [comment]
For anyone having issues with the arrows and dots not immediately showing in chrome, I found I had to add the following (in my scenario, the design called for them to be on top of the slides, they would only show once you clicked/scrolled the slider):

.slick-prev, .slick-next {
  transform: translate3d(0, 0, 0);/* fix for chrome not rendering*/
}
.slick-dots {
  transform: translate3d(0, 0, 0);/* fix for chrome not rendering*/
}

**Comment by dhenriet** [comment]
@simeydotme Hi thanks, this is a jsFiddle https://jsfiddle.net/fxLcucoq/ and I've updated issue

**Comment by dhenriet** [comment]
@danb-cws thanks
In this case (see JS Fiddle) I can't see next or prev arrows because they have class `.slick-disabled`

**Comment by danb-cws** [comment]
.vs-img-pager .slick-prev.slick-disabled, .vs-img-pager .slick-next.slick-disabled {
  display: none !important;
}

Not sure what your vs-image-pager class is for? But the above rule is the issue

**Comment by dhenriet** [comment]
yes I remove the "display: none" and let "opacity : .25", but carousel navigation still having issue

**Comment by dhenriet** [comment]
@simeydotme did you see the JSfiddle ? What am I doing wrong ?

**Comment by simeydotme** [comment]
nothing really, the arrows are perfectly fine.... but it seems like `variableWidth` is messed up... if you turn it off, and set your images to be `width: 100%` (in css) it is working perfectly.... seems an error with `variableWidth`

**Comment by AndrewSepic** [comment]
I've had issues with arrows & dots displaying as they should in Chrome as well. @danb-cws I tried you 3dtransform to no avail.  In the end I've just re-rigged the whole CSS using images that look like the nav buttons that ship with slick-theme.css  

Everything looked as it should in Safari, but Chrome pooped out.  

Macbook Pro running Yosemite and Chrome Version 44.0.2403.157

**Comment by leggomuhgreggo** [comment]
Hey I know this issue was created a while ago, but if you’re still interested can you recreate in a fiddle with the master? Apologies for the dormancy.

Closing pending fiddle

**Comment by octavioamu** [comment]
This one still happening, when the slider is controlled by a carousel with infinite: false; when the index is in the last group of the carousel the class is added, also some times when carousel pictures are clicked the index is wrong. I will try to open a new Issue with a fiddle ASAP
