### ISSUE TITLE
Overriding defaults.

### ISSUE THREAD

**Issue by jovilog** [kenwheeler/slick#1572]
Probably a very silly question, but I'm a bit slow on the uptake today.
How would I best change the defaults, so I don't have to repeat them for every call to `slick()`?
I'm thinking of something like the following, but that's not quite right:

```javascript
$.extend( true, $.slick.defaults, {
...
});
```

I don't get what "`$.slick.defaults`" should be instead.
I've found this approach, but I'd prefer a way like above:

```javascript
var $settings = { ... };
$(".slider").slick( $.extend({
...
}, $settings ) );
```

Thanks.

**Comment by simeydotme** [comment]
```js
var $settings = { ... };
$(".slider").slick( settings );
$(".slider").slick( settings );
$(".slider").slick( settings );
```

I don't know of, or think it's possible, or extend the defaults, currently :)

**Comment by jovilog** [comment]
Well, yeah, but I have additional settings that are different in each call. So, I suppose my 2nd example is the way to go?
