### ISSUE TITLE
troubleshooting 'dots' in Chrome on Android

### ISSUE THREAD

**Issue by naoyawada** [kenwheeler/slick#1576]
Running into an issue where a page using slick won't load in the latest release of Chrome on Android. It only occurs when I specify the 'dots' feature to be true. Not sure if this is a Chrome issue or a slick issue, but thought I would bring it up. 

Running:
Android 5.1.1
Chrome 43.0.2357.93

Thanks!

**Comment by naoyawada** [comment]
Test URL of the page that I realized this on: http://beta.neverwithout.net

**Comment by antokara** [comment]
confirmed, even the demo page http://kenwheeler.github.io/slick/ crashes Google Chrome on Android.

Chrome version: 43.0.2357.93 (32 bit)
Blink: 537.36
OS: Android 5.0.0
Device: LG-D855 (LG G3)


If I turn off the dots, it works properly.
Mind you the CSS of the dots is not altered at any way, it must be a JS issue.

**Comment by antokara** [comment]
Firefox crashes as well but default android browser does not.
using 1.5.8 version

**Comment by kenwheeler** [comment]
Are you guys seeing anything in the console? I'd like to get this sorted out immediately.

**Comment by antokara** [comment]
changing line 472:
dotString += '<li>' + _.options.customPaging.call(this, _, i) + '</li>';

with the function's contents:
dotString += '<button type="button" data-role="none" role="button" aria-required="false" tabindex="0">' + (i + 1) + '</button>';

fixes the issue, although that's not a solution, we are getting there.
I don't think I cant get console output, the tab crashes but I'll try...

**Comment by antokara** [comment]
it is very strange.
the actual problem was not the function but the <li></li>
once removed:
```
dotString += '' + _.options.customPaging.call(this, _, i) + '';
```
it works properly.

**Comment by antokara** [comment]
yeap, cannot get any console output. tab crashes and remove debugging gets disconnected.
just tried
```
dotString += '<span>' + _.options.customPaging.call(this, _, i) + '</span>';
```
and it works

however:

```
dotString = '<ol class="' + _.options.dotsClass + '">';

            for (i = 0; i <= _.getDotCount(); i += 1) {
                dotString += '<li>' + _.options.customPaging.call(this, _, i) + '</li>';
            }

            dotString += '</ol>';
```


this does not work

**Comment by antokara** [comment]
I start to believe that this is not the exact location of the problem, it probably has to do with another call such as the one https://github.com/kenwheeler/slick/blob/1.5.8/slick/slick.js#L743

**Comment by antokara** [comment]
closer now,

https://github.com/kenwheeler/slick/blob/1.5.8/slick/slick.js#L2534

if we remove or comment out the
```
.attr('aria-hidden', 'false');
```

it works

**Comment by kenwheeler** [comment]
Aria-hidden is crashing it?

**Comment by antokara** [comment]
not directly, if I set a debug there and wait a few seconds, it works.
something that is affected IF run immediately does the crash...

**Comment by antokara** [comment]
It appears as if it runs out of memory or something, its behavior is somewhat erratic.

Without making any changes, everything works up to line 
https://github.com/kenwheeler/slick/blob/1.5.8/slick/slick.js#L2575

the code ```$(this).attr({``` is executed twice.
on the first executing we are good, however on the second, the app crashes right there.

What's worse is that if we add right between line L2574 - L2575 a breakpoint (debugger;) and "resume script execution" twice (one for each), even doing it very fast, it works.

But, if we replace the breakpoint/debugger with lets say, an alert. it does not work. it crashes on the second execution.

Any ideas @kenwheeler ?

**Comment by kenwheeler** [comment]
How many slides do you have? What do your settings options look like?

**Comment by antokara** [comment]
two sliders, nothing fancy. some divs with text.
```
        autoplay: false,
        autoplaySpeed: 5000,
        arrows: false,
        dots: true,
        fade: false,
        pauseOnHover: false
```

**Comment by kenwheeler** [comment]
can you throw `console.log(i)` inside of that each and let me know the results

**Comment by antokara** [comment]
0
1

without crash and

0

with crash...

**Comment by naoyawada** [comment]
@kenwheeler - Didn't know if a solution to this was still in the works. I would love to help troubleshoot if I can. Thanks!

**Comment by antokara** [comment]
just tested https://github.com/kenwheeler/slick/
on Chrome 44.0.2403.128
OS: Android 5.0.0
Device: LG-D855 (LG G3)

and no crashes so far. will also test my demo and report the results with firefox as well.

@naoyawada are you still having crashes? you could try closing all apps, restarting Android and share your results...

**Comment by naoyawada** [comment]
@antokara Just checked it out on my devices:

having issues on:

Chrome: 43.0.2357.93
OS: Android 5.1.1
Device: Nexus 5

Works on:

Chrome: 44.0.2403.133
OS: Android 5.1.1
Device: Sony Xperia Z3 Compact

Works on:

Chrome: 44.0.2403.133
OS: Android 5.1.1
Device: Nexus 5


Maybe it was just a bug in Chrome? Nonetheless, upgrading Chrome seems to resolve the issue.

Thanks!

Naoya

**Comment by antokara** [comment]
also tested my demo on latest chrome/firefox and android. no problems any more.
I believe this issue can be considered resolved and was probably a peculiar browser bug...

**Comment by stgermaniac** [comment]
I am having a similar issue, still. I've isolated it down to "dots." (I can't begin to know how to isolate the issue beyond what's been written here already.)
