### ISSUE TITLE
Error in Safari 5.1.3

### ISSUE THREAD

**Issue by luansemensatoribeiro** [kenwheeler/slick#1577]
`TypeError: 'undefined' is not a function (evaluating 'b.setPaused.bind(b,!0)')`

**Comment by kenwheeler** [comment]
What version are you using?

**Comment by luansemensatoribeiro** [comment]
Safari 5.1.3

**Comment by kenwheeler** [comment]
no I mean slick

**Comment by luansemensatoribeiro** [comment]
Sorry! Slick 1.5.0

**Comment by luansemensatoribeiro** [comment]
@kenwheeler, the error was corrected in the latest version of the Slick. Thank you!
