### ISSUE TITLE
Hide slides before slick initialization

### ISSUE THREAD

**Issue by fizerkhan** [kenwheeler/slick#158]
I have 4 slides. before slick initialisation,  it shows everything. 
I want to display only first slide before slick initialisation. How do i do it?

**Comment by maxgittelman** [comment]
I set my carousel wrapper to visibility: hidden in my css file. And my script currently looks like this

    $(document).ready(function(){
            $(#carousel).on('init', function () {
                visibility: visible;
            });
            $('#carousel').slick({
                speed: 300,
                slidesToShow: 1,
                centerMode: true,
                variableWidth: true,
                prevArrow: $('.prev_box'),
                nextArrow: $('.next_box'),
                infinite: true,
            });
        });

However, upon initializing the carousel does not become visible. Please help!

**Comment by iamricky** [comment]
@maxgittelman Did you find the answer to your problem?

**Comment by jeroenhouben** [comment]
You should invoke jQuery's css() function, which you're not doing at the moment.

**Comment by MohammadDayeh** [comment]
add class "slick-slide" to each slide wrapper in your HTML

`<div id="your-slider" class="slick-slider">
    <div class="slick-slide">
        your content
    </div>
    <div class="slick-slide">
        your content
    </div>
    <div class="slick-slide">
        your content
    </div>
</div>`

**Comment by danyj** [comment]
this worked for me and there is no flashing from display property switch and no need for opacity, your slider looks like first slide on load until initiation and if there are any script issue your layout is not stretched. 


	.slick-slider .slick-slide{
		position:absolute;
	}
	 .slick-slider .slick-slide:first-child{
		position:relative;
	}
	.slick-initialized.slick-slider .slick-slide,
	.slick-initialized.slick-slider .slick-slide:first-child{
		position:relative;
	}

**Comment by timatima** [comment]
Only CSS version :)

.slick-slide:not(:first-child) {
display: none;
}
.slick-initialized .slick-slide:not(:first-child) {
display: block;
}

**Comment by pfar54** [comment]
I am running into this issue. Does anyone see what I am doing wrong? My issue I believe comes from the wrapper being set to display: none from the start https://jsfiddle.net/ndzf7gx6/1/

**Comment by jarfer** [comment]
Hi all,

Does anyone have an actual solution to this? All those posted in this thread fail for various reasons - the core one being that Slick Carousel will actually not work at all if in elements set to display:none it computes width of the visible element, as a result these widths end up being 0.

None of the solutions posted here would work for this reason - to save anyone else the time messing about

But I am keen to know how to solve this issue as it looks horrendous when loading - especially if this is in a CMS and the client has included a lot of large images

**Comment by jarfer** [comment]
Second, there is no event 'init' if I'm wrong, naturally someone will correct me, or else just eat humble pie and shut up.

**Comment by steveinatorx** [comment]
none of these solutions worked for me i was still getting the initial flash of my img slides on load - to fix this i had to add a class to each subsequent slide img after the first one that had visibility:hidden (i called this class .hidden) (i added a class called carouselImg to all the img slides after the first for the selector)

and then :

```
$("#slick").on('init', function () {
            $(".carouselImg").removeClass('hidden');
 }); 
```
that did the trick.

**Comment by adcosta118** [comment]
If you want to display only the first `n` slides until slick is loaded, you can use this:

```
.slick-init-1:not(.slick-initialized) > :nth-child(n+2),
.slick-init-2:not(.slick-initialized) > :nth-child(n+3),
.slick-init-3:not(.slick-initialized) > :nth-child(n+4) {
  display: none;
}
```
And add the corresponding slick-init class to your container.

The obvious downside to this approach is that you need one rule for each initial `n` that your wish to declare.

**Comment by maofree** [comment]
solved using display: none; instead of visible: hidden

#myslider {display: none;}
#myslider.slick-initialized {display: block;}

**Comment by Marycka9** [comment]
.slider-slick:not(.slick-initialized) > .slick-slide:not(.slick-active){
  display: none
}

.slider-slick - parent class slider

**Comment by Luneya** [comment]
Took me a while, but I found another topic explaining that the 'on init' event needs to called on BEFORE the js to load the slider itself.

So for me, the answer of @steveinatorx worked, provided to you load the on init js first.

**Comment by alefwebstore** [comment]
I don't think that visibility:hidden is a 100% solution because you got a blank space until the slider is initialized. Using display:none fails because slick can't get the wrapper size.

My own solution:

```
#slider{
    height: 1px;
    overflow: hidden;
    visibility: hidden;
    transition: height 0.2s linear;
}

$('#slider').on('init', function () {
  $('#slider').css({
    height: 'auto',
    visibility: 'visible'
  });
});

```

**Comment by beifler** [comment]
I tried all of the above, nothing stopped the un-initialized slides from showing. 

This is an imperfect solution, but it stops the un-initialized slides from showing below the slider frame:
#slider {
  height: 200px;
  overflow: hidden;
}

**Comment by anikaabreu** [comment]
hey guys.

The only thing I found that worked for me is adding the class .slick-slide to the slides I want hidden and then adding the visibility to the active slides, like so:

.slick-slide {
  visibility: hidden;
}

.slick-active { 
  visibility: visible;
 }

**Comment by Glideh** [comment]
@MohammadDayeh's solution remains the cleanest for me (applying the `slick-slide` class to the elements)

To shorten the delay of display, I'd also load the script right after the markup

```html
<div id="your-slider" class="slick-slider">
    <div class="slick-slide">Slide 1</div>
    <div class="slick-slide">Slide 2</div>
    <div class="slick-slide">Slide 3</div>
</div>
<script>
$('#your-slider').slick({
// ...
})
</script>
```

_Make sure jQuery & Slick are loaded before_

**Comment by HaulyShit** [comment]
This was works for me:
```
.slick-slider {
	> div {
        display : none;

        &:first-child {
            display: block;
        }
    }

    &.slick-initialized {
        > div {
            display: block;
        }
    }
}
```

**Comment by malasaad82** [comment]
Thanks @HaulyShit , Very nice 👍

**Comment by andyvu92** [comment]
In case someone will need it, I got a solution that working great without using any scripts.

First, set the carousel wrapper default in css as follow:
.wrapper{
    height: 0;
    overflow: hidden;
}

On visible, set height to auto
.wrapper.active{
      height: auto;
      padding-bottom: 65px;
}

Remember to set the dots:
.slick-dots {
    position: absolute;
    **bottom: 0px;**
    list-style: none;
    display: block;
    text-align: center;
    padding: 0;
    margin: 0;
    width: 100%;
}

If you need s smooth fade in, you will need to use jquery to handle it.

**Comment by punjabimundaaa** [comment]
the solution form @MohammadDayeh worked for me. simply add slick-slide to the individual slider divs

**Comment by sdconnors2019** [comment]
Agreed:  The solution from MohammadDayeh  worked for me also, add the "slick-slide" to each slider "<div>" element, which seems to prevent all the pics in the div from "preloading" and flickering briefly before disappearing.

However, then I noticed a new type of flicker - the first pic was not loading immediately either, and therefore not taking up space - so the elements below it were briefly up top, then pushed down once the first pic loaded, causing a brief flicker.

FIX:  On your first slide div, simply leave the "slick-slide" class off and it loads right away correctly, this prevents that other flicker.

**Comment by DoopsDesigns** [comment]
I achieved this after a little bit of bother by manually setting the classes .slick-slider & .slick-slide, then using this css:

	.slick-slider {
		overflow: hidden;
		visibility: hidden;
	}
	.slick-slider.slick-initialized {
		visibility: visible;
	}
	.slick-slider .slick-slide {
		overflow: hidden;
		visibility: hidden;
	}
	.slick-slider .slick-slide:first-of-type {
		visibility: visible;
	}
	.slick-slider.slick-initialized .slick-slide {
		visibility: visible;
	}

Hopefully someone else can confirm this works for them?

**Comment by mahmoudelkhadragy** [comment]
> this worked for me and there is no flashing from display property switch and no need for opacity, your slider looks like first slide on load until initiation and if there are any script issues your layout is not stretched.
> 
> ```
> .slick-slider .slick-slide{
>     position:absolute;
> }
>  .slick-slider .slick-slide:first-child{
>     position:relative;
> }
> .slick-initialized.slick-slider .slick-slide,
> .slick-initialized.slick-slider .slick-slide:first-child{
>     position:relative;
> }
> ```
> 
> just tested and this works also
> 
> ```
> .slick-slider .slick-slide{
>     display: none;
> }
>  .slick-slider .slick-slide:first-child{
>     display: block;
> }
> .slick-initialized.slick-slider .slick-slide,
> .slick-initialized.slick-slider .slick-slide:first-child{
>     display: block;
> }
> ```

thanks it works for me

**Comment by awaishub** [comment]
@digitaljhelms thank you man...it's also worked for me..

**Comment by PouriaDiesel** [comment]
my problem was `dir="rtl"` on body and when I swipe the slider my slider became invisible.then I add `dir: rtl` to settings and my problem solved.

**Comment by devrasel** [comment]
add class "slick-slide" to each slide wrapper in your HTML and it is solved :)

#your-slider .slick-slide { display: none; }  and #your-slider .slick-initialized .slick-slide{ display: block; }  

```
<div id="your-slider" class="slick-slider">
    <div class="slick-slide">
        your content
    </div>
    <div class="slick-slide">
        your content
    </div>
    <div class="slick-slide">
        your content
    </div>
</div>
```

**Comment by itisyb** [comment]
![image](https://user-images.githubusercontent.com/42640264/151756339-b579496e-f014-4f84-99e4-ceae405e24a6.png)
![image](https://user-images.githubusercontent.com/42640264/151756369-9f8c3bd0-679a-4494-a027-4f98a7c38949.png)

I see sometimes this I am using slick slider I have to refresh than it shows fine but it's a major issue for customers
