### ISSUE TITLE
Inaccessible first items resizing with short responsive columns

### ISSUE THREAD

**Issue by evan-king** [kenwheeler/slick#1581]
If you have a slick carousel with N columns (single row, grid, arrows, no dots, no infinite) and M <= N items in it, plus responsive rules to bring it down to P < M rows, then starting items can become inaccessible in the following manner:

 - Start with browser sized for N columns - there will be no navigation arrows
 - Resize the browser to P columns - navigation arrows will appear
 - Click the right arrow until carousel reaches far right
 - Resize the browser back to N columns - navigation arrows will disappear

The extra columns will be left blank, with only the last P items shown from the left, and the first M - P rows will be unreachable.  Not only are the arrows gone, but also the items cannot be dragged to the right.

This does not occur if the carousel contains > N items, so that cycling is always enabled.

JSFiddle: http://jsfiddle.net/L7qcvxyb/

Tested on 1.5.6 and 1.5.8.

**Comment by evan-king** [comment]
Expected behavior: returning to N-column grid pulls carousel to the right until all columns are full or no items remain to the left (whether there are enough items to enable moving around or not).

**Comment by simeydotme** [comment]
I think line 1518 requires a check like this:
```js
        if (_.slideCount <= _.options.slidesToShow) {
            _.currentSlide = 0;
        }
```

I'll see if I get time to add it today! :)

**Comment by simeydotme** [comment]
Please try: http://jsfiddle.net/simeydotme/6qo284k3/ and confirm it's working as you expect :)

**Comment by evan-king** [comment]
Fix confirmed. :)

**Comment by simeydotme** [comment]
can you edit hte fiddle to show? -- do you mean add one programmatically, or before init?

**Comment by evan-king** [comment]
Just having it there before init is all it takes.
http://jsfiddle.net/40j4qgbg/

**Comment by simeydotme** [comment]
Ok, it's been tested and fixed now, @evan-king :) you can revisit your latest fiddle: http://jsfiddle.net/40j4qgbg/ and see :)

**Comment by evan-king** [comment]
Fix confirmed :+1: 

I'll keep an eye out for a stable release with the fix.
