### ISSUE TITLE
Weird Transform on slick track

### ISSUE THREAD

**Issue by robinbrakel** [kenwheeler/slick#1582]
I have a problem with my slick slider. There are 5 items in my slider. The slidesToShow property = 5. But there are only 4 items visible. This is because there is a transform: translate3d(205px, 0px, 0px); on my slide-track. If I override 205 by 0, I see all my items. But when I add a sixt item scrolling doesn't work.

When I don't override the transform, and I add extra items in my slider it works fine. But it also has to work when 5 slides are in my slider.

Is there a way to fix this?

![schermafbeelding 2015-07-28 om 14 11 51](https://cloud.githubusercontent.com/assets/9657185/8930933/a42a06aa-3532-11e5-8b5b-cd6e64903560.png)

**Comment by kenwheeler** [comment]
do you have sample settings or a jsfiddle I can look at to diagnose?

**Comment by robinbrakel** [comment]
You can see the slider right here : http://pietpulles.develop.pietpulles.nl/expertises/fotografie/ 
 
Options:

partSlickSlider.CssClassExtra = "slider-nav";
                partSlickSlider.SlidesToShow = 5;
                partSlickSlider.SlidesToScroll = 1;
                partSlickSlider.AsNavFor = ".slider-for";
                partSlickSlider.Dots = false;
                partSlickSlider.CenterMode = false;
                partSlickSlider.Arrows = true;
                partSlickSlider.FocusOnSelect = true;
                partSlickSlider.Infinite = true;
                partSlickSlider.Speed = 300;

**Comment by leggomuhgreggo** [comment]
Hey, can you reproduce in a fiddle? Trying to diagnose issues from a production ready site is messy--too many variables. I'm going to close this for the time being, but if you make a suitable test case, we can look at reopening. Thanks!
