### ISSUE TITLE
Horizontal scroll bar shown on smaller devices

### ISSUE THREAD

**Issue by ihabovich** [kenwheeler/slick#1584]
slick carousel cause appearance of horizontal scroll bar cannot fixed after tried hardly through css.
![untitled-1](https://cloud.githubusercontent.com/assets/13511260/8937741/bbe256f8-355a-11e5-947a-7998eddd36e0.jpg)

Is me only having such issue?, any suggestion to fix?

**Comment by simeydotme** [comment]
Please create a JS Fiddle, and describe accurately the size of the screen needed to reproduce your issue :) -- you can find a base-fiddle for use in the contribution guidelines, which you should also read :)

I'll re-open issue when it complies.

Thanks.

**Comment by ihabovich** [comment]
@simeydotme Thanks for reply, I did creat JS Fiddle http://jsfiddle.net/dhfpbs32
The issue can be reproduced on any screen <768px

**Comment by simeydotme** [comment]
http://jsfiddle.net/dhfpbs32/1/

:)

You had a full-width carousel, but there were "arrows" set at -20px off the screen.. this forced the page to scroll... settings `arrows: false` fixes it... but you can also change the CSS instead if you prefer so your `.slick-next` arrow is back inside the container.

Si.

**Comment by ihabovich** [comment]
@simeydotme Thanks for help. I did update JS Fiddle http://jsfiddle.net/dhfpbs32/3/ to match an example to how I use on my project which looks fine on JS Fiddle but got actual issue on being used in project http://ihabovich.ga/demo/waseela/

As you see the second carousel goes wrong on responsive <1200px. Chrome console shows error "Uncaught TypeError: Cannot read property 'length' of null".

**Comment by simeydotme** [comment]
1. **Please update** to 1.5.8 , there was a bug in 1.5.6 (sorry) :confounded: 

2. I am **not** going to be **inspecting minified code** on your server, too troublesome :smile: 
3. If it works in the fiddle, it's **your environment which is the problem**... but I really think if you update to 1.5.8 it'll be OK :bow: 


Simon.

**Comment by ihabovich** [comment]
Update fixed the issue, while I managed to make horizontal scroll bar invisible using overflow-x: hidden; in CSS

**Comment by simeydotme** [comment]
probably not the best option... but glad it's fixed! :)
