### ISSUE TITLE
The focal point should not be move to side slide when use tab key

### ISSUE THREAD

**Issue by benjaminliugang** [kenwheeler/slick#1587]
When I try to use tab key to loop all the buttons in center slide, the focal point can move to side slide. It not reasonable.

How can I disable side slide or how can I set side slide's `tabindex = -1`?
Like below snapshot, the tab key should only work in `1` slide.

![image](https://cloud.githubusercontent.com/assets/1411188/8951376/c59ba208-35ff-11e5-8e26-12f72377a744.png)

**Comment by simeydotme** [comment]
Please read the contribution guidelines :)
