### ISSUE TITLE
Responsive by default

### ISSUE THREAD

**Issue by ttbarnes** [kenwheeler/slick#1588]
I'm having a nightmare configuring [angular-slick](https://github.com/vasyabigi/angular-slick) to work nicely on smaller screen sizes. I'm not the only one.

The main reason is because each item gains a width, for example 225280px and therefore destroys 'mobile friendliness'.

I've tried several approaches suggested in the docs, SO questions, github issues - nothing seems to work, so i'm going to use something else instead now.

I think the slider should 'just work' on mobiles as default, instead of an option.. I imagine that the majority of users will be supporting mobile. In other words, it's probably an edge case to have a non-responsive slider.

**Comment by simeydotme** [comment]
thanks, but it does.

**Comment by ttbarnes** [comment]
hmm ok - thanks. I haven't actually tried out slick, only angular-slick. Must be an issue with the angular port of it; default settings cause the issue described.

**Comment by simeydotme** [comment]
http://jsfiddle.net/simeydotme/fmo50w7n/

Thats taken from teh contribution-guidelines base-fiddle, you can remove the "responsive" options, and resize the view-frame.

By default slick allows dragging/swiping the screen with a touch-device, also it scales by default to your container. If you have width issues I'd hazard a gues syou've got it running inside a table, or an element with `display: table` .. that or you're trying to render the carousel in a hidden element (JS cannot get widths of `display: none` ... but really, it is responsive out of the box :) -- its the core feature.
