### ISSUE TITLE
Remove style attribute on slick-dots

### ISSUE THREAD

**Issue by LeG3nDz** [kenwheeler/slick#1591]
Hi,

Do you now if i can drop the "style" attribute on slick-dots element ? For display: flex, he creat bug on iOS :(

Thank you,

**Comment by simeydotme** [comment]
Please create a JS Fiddle according to the contribution guidelines :)

**Comment by leggomuhgreggo** [comment]
Hey, I'm closing because there's no test-case, [per the contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), but if you make one we could possibly reopen. Thanks!
