### ISSUE TITLE
slidesToScroll only on next/prev press

### ISSUE THREAD

**Issue by leads** [kenwheeler/slick#1592]
Hello. Apologies if this is a feature and I've missed the option for it but...
The slidesToScroll works lovely when pressing prev/next button when when dragging the container, it snaps/bounces awkwardly. Is it possible to disable the snapping when dragging?

Cheers

**Comment by MissFerrety** [comment]
Have you looked into modifying the `touchThreshold` [setting](http://kenwheeler.github.io/slick/#settings)?

**Comment by leads** [comment]
It was swipeToSlide that I needed to enable, along with messing about with touchThreshold. Thanks
