### ISSUE TITLE
Responsive not working after breakpoint

### ISSUE THREAD

**Issue by gillchristian** [kenwheeler/slick#1594]
The plugin is awesome :smile: thanks!
I'm trying to set up an slider, but I'm having trouble with the responsive option.
When I load with a wider with than the breakpoint it works well until I resize below the breakpoint and the slider disappears.
If I load the screen with a smaller width than the breakpoint the slider never shows up, even when I resize pass the breakpoint.
[Codepen here!](http://codepen.io/gillchristian/pen/oXQyPO)
I've tryed adding ``` mobileFirst: true``` and switching the settings, and things get even worse.
Starting from mobile looks ok, but after the breakpoint the slides overlay.
[Codepen here too!](http://codepen.io/gillchristian/pen/GJwGzp)

**Comment by ethanclevenger91** [comment]
Could be related to #1300 ?

**Comment by gillchristian** [comment]
Yes! I think so. Could not your codepen because I'm on the phone, but looks to be the same problem.
Kenwheeler mentioned today in Scotch.io slack it is not working properly atm.

**Comment by Bartlomiejsz** [comment]
I have added Pull request for this error: https://github.com/kenwheeler/slick/pull/1660
Works just great in my case :)

**Comment by simeydotme** [comment]
Sorry for the problems with grids/rows.
We will do our best to sort these out in a major update.

**Comment by maksimsvoitkevics** [comment]
I don't if this will help anyone, but what fixed this for me, was adding user-scalable=no into viewport meta tag.
