### ISSUE TITLE
Don't work "Slider Syncing" and "variableWidth" together

### ISSUE THREAD

**Issue by Kikoma** [kenwheeler/slick#1596]
Thank you for your slider, 
I use several foto with different orientation. And I've got one problem: when I use "Slider Syncing" and "variableWidth: true" ( 'variableWidth' propertie in both classes '.slider-for' and 'slider-nav') in '.slider-for' shows only first picture. The 'left' propertie don't change in 'slider-for' after 'nav' changed.

**Comment by simeydotme** [comment]
You must provide some kind of test case, as mentioned in the contribution guidelines.
