### ISSUE TITLE
variableWidth leaves blank space with small images

### ISSUE THREAD

**Issue by Andergraw** [kenwheeler/slick#1597]
Hi @kenwheeler!
First of all, congratulations and thanks for such a great slider. It really rocks.
So, something I was trying in my page is a wide slider with small images. The thing is, when I set variableWidth, some blank space is left after the first round. Until it matches the number of visible slides. 
I think you will get me with the [JSFiddle](https://jsfiddle.net/e39kD/23/). Look after the orange for the second time. 
Now I know how to avoid it calculating visible images related with the total number of them, but...is there anything I am dong wrong or it's a bug?

Thanks a lot!

**Comment by alexweb** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Hmm, this fiddle looks like it's [broken](http://i.imgur.com/EZnV95z.png) for me, but in a way that doesn't relate to the issue description. @alexweb or @Andergraw are you able to verify and possibly whip up a new example from [this template](http://jsfiddle.net/simeydotme/fmo50w7n/)?

**Comment by alexweb** [comment]
I think it's the same issue as discussing here: https://github.com/kenwheeler/slick/issues/1207

**Comment by leggomuhgreggo** [comment]
Ah sweet. Closing this then. Thanks!
