### ISSUE TITLE
Init event should be invoked, when slick is attached to the element

### ISSUE THREAD

**Issue by gustavpursche** [kenwheeler/slick#1600]
The documentation mentions, that there is an init event, which can be used like all the other callbacks. So the following should work: http://jsfiddle.net/fmo50w7n/38/

Unfortunately it doesn't. Instead it must be attached, before calling slick (metioned in #1128).

```js
$('.slider').on('init', function() {
    console.log('init called');
});

$(".slider").slick();
```
The init event should be invoked immediately, when defining the event after slick was attached to the element (monkey-patch `.on()`). An easiert and from my view preferred solution would be, to allow the `init` property in the slick-options (again) as a special case.

Otherwise there should be at least a note in the documentation.

**Comment by simeydotme** [comment]
Gustava, how do you expect that you can trigger an event which wasn't even bound _yet_ ... aside from going back to the future ;) -- this is just general Javascript knowledge, and I don't think we should be documenting all the nuances of programming in an interpreted language for a plugin designed for it.

Sorry for your confusion. :)
Simon.
