### ISSUE TITLE
Manually change slide

### ISSUE THREAD

**Issue by Tarang** [kenwheeler/slick#1601]
Hi!

We're using this plugin as a part of meteor ionic.

How do we manually change a slide's index once the slidebox has been instantiated?

This is what the component file looks like if that's of any interest: https://github.com/meteoric/meteor-ionic/blob/master/components/ionSlideBox/ionSlideBox.js

But I couldn't find a method in the docs that lets us change it.

**Comment by simeydotme** [comment]
the documentation is in the README :)
