### ISSUE TITLE
Sporadically, the "slick-initialized" class is added but the "init" event isn't triggered

### ISSUE THREAD

**Issue by annorax** [kenwheeler/slick#1602]
I think this has to do with the fact that in Slick.prototype.init, the $slider jQuery element is for some reason being used to construct a new jQuery element, as follows:

`$(_.$slider)`

I assume this is meant to perform a new jQuery lookup using the same selector.

However, when triggering the event, we're triggering it on the "old" jQuery lookup results, i.e.:

`_.$slider.trigger('init', [_]);`

I believe this should be changed to:

`$(_.$slider).trigger('init', [_]);`

**Comment by simeydotme** [comment]
Go ahead and provide some tests/examples to demonstrate, and submit a pull-request with the fix and an example showing it being fixed :) I can merge after reviewing.

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because there's no test case, [per the contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but if you'd like to make one we could reopen. Thanks!
