### ISSUE TITLE
Shouldn't the dots list be marked as a ordered list?

### ISSUE THREAD

**Issue by jnylin** [kenwheeler/slick#1603]
First of all: what a lovely plugin! I've just started to try it out. One thing. The slide are displayed in a specified order, I therefore think that the dots list should be ```<ol>```:
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L469

**Comment by simeydotme** [comment]
not really necessary since they have no semantic value, anyway. Purely presentational markup generated by the script, which has no value out of the carousel context.
