### ISSUE TITLE
Overlapping divs on slideToggle

### ISSUE THREAD

**Issue by nehalist** [kenwheeler/slick#1607]
My subheader can be collapsed / expanded and works with jQuery's `slideToggle` function:

```
$('#toggle-subhead').click(function() {
        $('.subhead-collapsed').slideToggle();
        $('.subhead-expanded').slideToggle();
});
```

The collapsed version uses Slick, but the div containers are overlapping until the first slide:
![slick](https://cloud.githubusercontent.com/assets/1016497/9046244/94563720-3a29-11e5-8f10-213694a08497.gif)

**Comment by sameeparora** [comment]
Did you figure out a solution yet?

Same problem here when using materialize collapsible.

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because there's no test case, [per the contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but it seems like an interesting issue so if you want to whip it up in a fiddle, might be able to take a look.

**Comment by nehalist** [comment]
Hey, sorry, nearly forgot about this issue. Here's the fiddle: https://jsfiddle.net/4rrmz07b/

**Comment by leggomuhgreggo** [comment]
Cool. I added the setPosition method which looks like it caught the positioning up.

[fiddle](https://jsfiddle.net/leggomuhgreggo/qe9LLomh/1/)

**Comment by sameeparora** [comment]
Thanks. That solves it.

**Comment by nehalist** [comment]
Solved it on desktop, yes, but mobile still behaves weird.
