### ISSUE TITLE
Specifying prev and next arrows relative to the slider currently being initialised.

### ISSUE THREAD

**Issue by philwastell** [kenwheeler/slick#1608]
In a scenario where there are multiple sliders on one page that are all initialised via a common jQuery classname selector, is it possible to specify 'prevArrow' and 'nextArrow' relative to the slider currently in scope?

For example, where the arrows are defined in the html as children of $('.common-classname .slideset') -

$('.common-classname .slideset').slick({
    arrows: true,
    nextArrow: $(this).find('.next-arrow-classname'),
    prevArrow: $(this).find('.prev-arrow-classname')
    slidesToShow: 4,
    slidesToScroll: 4
});

**Comment by simeydotme** [comment]
nope. But you can use a `$.each` loop to init the sliders like that.

**Comment by klick** [comment]
Is this till supported?
