### ISSUE TITLE
Random initial slide 

### ISSUE THREAD

**Issue by t3easy** [kenwheeler/slick#1609]
A random initial slide would be a nice feature.
Maybe extend the initialSlide setting with the keyword "random".

**Comment by simeydotme** [comment]
its incredibly easy to do it yourself :)

**Comment by t3easy** [comment]
Not if you pass the setting per data-slick / JSON

**Comment by t3easy** [comment]
@simeydotme Do you have an example how to do this with JSON?

**Comment by simeydotme** [comment]
Ah, I see what you mean, yeh I guess if you don't generate on the server with php/something, then it will be tough to do with data-attrs... hmmm

**Comment by t3easy** [comment]
Thanks for reopen and investigating!
