### ISSUE TITLE
Load More while keeping existing elements in place.

### ISSUE THREAD

**Issue by kidequinox** [kenwheeler/slick#1610]
It would be awesome if I could use slick in lazy load mode,  and have a load more button that will load more elements/slides with out removing the existing elements/slides. is this possible ?

**Comment by simeydotme** [comment]
`.slick("slickAdd")` from the readme :)

**Comment by kidequinox** [comment]
Awesome, 

I have two rows of 6 visible elements (grid layout)
When I click, load more I would like 2 more rows to show up underneath, and so on

$('.thebooks').slick({
lazyLoad: 'ondemand',
rows:2,
slidesPerRow:6,
slidesToScroll: 1,
});

![screen shot 2015-08-05 at 11 32 31 am](https://cloud.githubusercontent.com/assets/8398576/9094278/b8c3ab64-3b65-11e5-8169-380eba59f029.png)

can you share any insight on achieving this with slick ? In my case the slides are already loaded in a carousel form.
