### ISSUE TITLE
Youtube iframe red play button moving slide away.

### ISSUE THREAD

**Issue by tonhaoln** [kenwheeler/slick#1611]
I used the plugin to build a slider containing images, Vimeo and Youtube embedded iframe. 
The only issue I noticed is with the Youtube red play button in Chrome. If I use the red play button to start the video, the slide slides away back to the first slide. However if I click on the iframe to start the video there is no problem.
Here is my site: http://www.designerdirectory.com.au/portfolio/marcelo-d2/
Youtube video in the third slide. 

As I said, it seams like this is just happening in Chrome...
Thanks,
Antonio

**Comment by iamstarkov** [comment]
@tonhaoln cannot see any slick slider on your site

**Comment by tonhaoln** [comment]
@iamstarkov sorry, I unpublished the page by mistake. Please check again:
http://www.designerdirectory.com.au/portfolio/marcelo-d2/

**Comment by iamstarkov** [comment]
reproducable in chrome, firefox is fine

**Comment by yakhinvadim** [comment]
Antonio, hi!
I faced the same issue yesterday. I didn't know how to fix it, so that's what i did.

1) I replaced iframe with div with background-image taken from youtube thumbnails
html:

```html
<div class="slick">
  <div class="image" style="background-image: url(...)">
  <div class="image" style="background-image: url(...)">
  <div class="video" style="background-image: url(http://img.youtube.com/vi/YOUR_YOUTUBE_ID/maxresdefault.jpg)">
</div>
```

2) I appended iframe on click on this image
javascript:

```javascript
$(document).on('click', '.video', function() {
  $(this).append('<iframe style="width:100%; height: 100%;" src="https://www.youtube.com/embed/YOUR-YOUTUBE-ID?rel=0&amp;controls=1&amp;showinfo=0;autoplay=1" frameBorder="0" allowfullscreen></iframe>');
});
```

3) I also added custom play button, by using pseudo-elements on div.video

It doesn't fix the problem with iframe actually, but it could help

**Comment by iamstarkov** [comment]
@kenwheeler can you help us?

**Comment by jpagano** [comment]
@tonhaoln you can use this plugin https://github.com/tylerpearson/lazyYT

**Comment by kenwheeler** [comment]
Can you create a JSFiddle to isolate the issue?

**Comment by tonhaoln** [comment]
Sorry, didn't have time to create a JSFiddle... Will do it soon. Thanks!

**Comment by jpotterm** [comment]
A workaround that seemed to work for me is the following settings:

```javascript
{
    draggable: false,
    swipe: false,
    touchMove: false,
}
```

But it would be really nice if this were fixed.

**Comment by chadpeppers** [comment]
i can confirm this also is broke.  It appears to play the next video or go to the next slide when clicking only the red button.  I cant imagine the issue being the "iframe" as the guy above stated because this is from youtube and works on pretty much any other slider plugin.

**Comment by chadpeppers** [comment]
Update.  This seems to be an issue isolated to chrome.  If anyone comes here the fix is to set slick slider useCSS: false.  This also seems to be isolated when you are using another slick slider to as navigation for the slider OR you use slickGoTo function.  I'm not sure how this differs from the arrow but for some reason using the arrows work perfectly fine.  After 6 hours I figured this out.

**Comment by tonhaoln** [comment]
Hi,
What do you mean by "set slick slider useCSS: false"?
Thanks,
A

**Comment by chadpeppers** [comment]
When you initialize slick slider:

$('.slick').slick(function(){
 useCSS: false
});

However I was incorrect as it still did not work.  This is isolated and works if you are not using another slider to slide slider or using slickGoTo function.  I did finally get this to work by using the YouTube API to load the iframe after the transition.  I believe this is a combination of slick slider and chrome.  In the end we ended up changing the transition to use a fade instead.  But like I said if you want it to work you should use YouTube API that loads the iframe on transition instead.

**Comment by tonhaoln** [comment]
Sounds good!
Will give it a go. Thanks

**Comment by m2004** [comment]
i can confirm this bug. if i set lazyload option to true it work fine. 
@kenweehler can u please help me. 

I found the same bug in react slick too.
