### ISSUE TITLE
When initializing slick by json dots is not respected

### ISSUE THREAD

**Issue by hultberg** [kenwheeler/slick#1612]
Hey

When initializing slick by json the dots parameter is not respected.
JsFiddle: http://jsfiddle.net/22cexdpk/

Using chrome 44 on windows 10

**Comment by hultberg** [comment]
Looks like this JSON string:  data-slick="{"autoplay":true,"autoplaySpeed":5000,"dots":true,"fade":false,"adaptiveHeight":true}" is not valid. Should it be documentet specifically how this string should be.

**Comment by simeydotme** [comment]
http://jsfiddle.net/simeydotme/22cexdpk/4/
```html
data-slick='{"autoplay":true,"autoplaySpeed":5000,"dots":true,"fade":false,"adaptiveHeight":true}'
```

You were not escaping the `"` characters :)

**Comment by hultberg** [comment]
@simeydotme That should be documented even if it's self explanatory (which it wasn't for me)

**Comment by simeydotme** [comment]
@hultberg we'll consider your recommendation; however it is actually just a common feature of HTML and Software development in general. :) quotemarks inside Strings  either need to be escaped or written with different quote marks :)

`<a title=
