### ISSUE TITLE
slickNext is not a function

### ISSUE THREAD

**Issue by LeG3nDz** [kenwheeler/slick#1613]
Hi :)

By using $('#carousel').slickNext(); i've error in my console : slickNext is not a function (width Slick v1.5.8).

If i use my ex file (Slick v1.3.15), slickNext will work.

Do you now if it's bug on last version ?

Thank you ! :)

**Comment by simeydotme** [comment]
Nope :smile: 
since `1.4.0` the API changed, please read the `readme.md` again to familiarise yourself with the new syntax :)

```js
$carousel.slick("next");
```

**Comment by alxvallejo** [comment]
Can you refresh what that documentation is? $carousel is not in the readme

**Comment by jon-athan-hall** [comment]
@alxvallejo $carousel is the variable name that's storing the slider element. It's up to you what variable name you use. The README might be using a different variable name.

Assuming you have the slider initialized, you can grab the slider element from the DOM and store like so
`var $whateverNameYouWant = $('.slick-slider');`
