### ISSUE TITLE
slick-dots slick-active class

### ISSUE THREAD

**Issue by trinzia** [kenwheeler/slick#1614]
The dot indicators sometimes have no "slick-active" class, when slidesToShow = 3.
Also, some of the dot indicators appear to be missing.  6 slides should be 6 dots?

Fiddle: http://jsfiddle.net/5xnjxmqy/3/

...

Aside (separate issue):  I was unable to combine fade mode, so I tried to do css transition ease-in-out on class='slick-current'.  When large images are present, you can see that it fails on slide one repeatedly during cycle, although it works fine on the other slides.

**Comment by davorpeic** [comment]
I'm having the same issue as OP, this happens when I use 'appendDots', the first one has it once the slick is loaded, but after clicking on other dot or swiping, the dots looses active class.

thanks

**Comment by davorpeic** [comment]
Ok, my issue is related that I was injecting dots on each slide, so this function didn't worked correctly https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2545, I resolved my issue by not injecting dots in each slide and managed to work with it.

davor

**Comment by simeydotme** [comment]
Dots / Paging needs an overhaul :(

**Comment by Dreamfish19** [comment]
Hi,

everyone with the same problem:

I used this jQuery code to workaround the problem:

$('.your-slider').on('beforeChange', function(event, slick, currentSlide, nextSlide){
  var activeSlide = nextSlide + 1;
  var slide_child = ':nth-child('+ activeSlide +')';
  $('.your-slider .hero-slide'+ slide_child + '').find('.slick-dots li'+ slide_child +'').css("background-color" , "#9e958f"));  
});
