### ISSUE TITLE
wrong currentSlide calculation

### ISSUE THREAD

**Issue by felixmosh** [kenwheeler/slick#1625]
***Didn`t saved the previous fiddle. now its the updated***
With this setup:
http://jsfiddle.net/vmqhaw8m/3/
The currentSlide parameter is a pointer to the first item in the view...
As a result item 4,5,6 in the example can not be active.
If you set centerMode=true, the value is right.

My suspicion is on that line https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2129

That condition is wrong in case sidesToScroll equals 1.
```javascript
index > _.getDotCount() * _.options.slidesToScroll
```

When I changed the condition to: 
```javascript
index > _.getDotCount() * _.options.slidesToShow
```
It worked for me

**Comment by simeydotme** [comment]
You didn't provide a fiddle with the updated Slick... if you did you'd have realised it was broken :disappointed: 
I think the dots need an overhaul, closing this PR. apologies for the late response.
