### ISSUE TITLE
Slider jumping issue on Laravel 5?

### ISSUE THREAD

**Issue by lanthanoider** [kenwheeler/slick#1626]
Hi,

just wondering, has anyone ever used Slick on a website that uses Laravel? I'm currently using Laravel 5 with Foundation as the framework, and I sort of experience weird behaviours from the sliders. If I set the infinite loop to true, once the slider reaches the last slide, it jumps weirdly to the first slide, then continues to slide normally to the next ones. The jumping just occurs when the last slide loops back to the first slide - or when the first slide moves to the last slide. This doesn't happen when I set fade to true, but I need to show 3 at a time and fade doesn't do that.

I'm actually not sure whether it's Laravel that's causing the problem. If I reproduce the code without the Laravel skeleton, the jumping doesn't occur though. Foundation doesn't seem to be the problem, so could it be that Laravel that's induced it? If anybody could help me out/has some experience using Laravel, that would be much appreciated! 

Cheers!

**Comment by wilirius** [comment]
Check your HTML, CSS, and JS for differences between when it is jumping and when it isn't. slick has nothing to do with PHP.

**Comment by lanthanoider** [comment]
yeah, solved it, basically any css3 transitions set on * will break the sliding effect. Cheers, anyway!

**Comment by RhanCandia** [comment]
Hi. Sorry to revive this issue but I am facing the same problem.
I don't have any transition set on * tho.

**Comment by lanthanoider** [comment]
Have you got any css3 transitions at all maybe? try removing all of them and see what happens... the issue should be the transitions I guess...
