### ISSUE TITLE
Disable swipe

### ISSUE THREAD

**Issue by kychd** [kenwheeler/slick#1627]
Hello! I do step by step form and you want to disable swipe. Tell me, please, what I need to do?

**Comment by simeydotme** [comment]
You need to read the contribution guidelines :)

**Comment by kychd** [comment]
Yes, I have read. But it did not help me. Swipe still works.
		$step.slick({
			slidesToShow: 1,
			dots: !0,
			infinite: !1,
			speed: 500,
			adaptiveHeight: !0,
			draggable: 'false',
			swipe: 'false',
			swipeToSlide: 'false',
			touchMove: 'false',
			draggable: 'false',
			accessibility: 'false',
			arrows: 'false'
		})

**Comment by simeydotme** [comment]
there should not be `'` quotes around true/false values.
Please read the contribution guidlines, also :)

**Comment by kychd** [comment]
Thank you!
