### ISSUE TITLE
Issue when reach last carousel item

### ISSUE THREAD

**Issue by ippiel** [kenwheeler/slick#1635]
Hello,
When mij carousel reach the last carousel item i see the first item on the right, but when this item scrolls to the center the carousel scrolls to the left.
I search this forum but don't see a solution.

It's look like the loop stops at the last carousel item, when loading the first item, the carousel scrolls back to the begin...

Does anyone know a solution?

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
