### ISSUE TITLE
Div class .slick-track has width 0px when slider loaded within collapsed content

### ISSUE THREAD

**Issue by mEdensky** [kenwheeler/slick#1638]
When loading slick slider in collapsed content (angular-bootstrap collapse plugin in this case) the .slick-track div gets 0px width, resulting in the slider trying to fit all slides on top of eachother. When pressing arrow to see next slide, the slides go back to normal.

Please check this example:
http://plnkr.co/edit/iw9f2alEnK0HFkv1eq16?p=preview

**Comment by simeydotme** [comment]
Please refer to stackoverflow for a solution :)

**Comment by adg29** [comment]
For posterity: here is the stackoverflow thread being referred to http://stackoverflow.com/a/32107099

**Comment by PouriaDiesel** [comment]
you can use below code:
`$("ul.slick-slider").slick("refresh");`

**Comment by krizza143** [comment]
You're a genius @PouriaDiesel !! saved me a lot of timeeeee
