### ISSUE TITLE
How to enable slick-loading class... 

### ISSUE THREAD

**Issue by jeremyswright** [kenwheeler/slick#1640]
Hello,

I'm not seeing the slick-loading class pop up anywhere on my sliders so I've been unable to get a loading icon working.  I've seen this line in the js which is what would cause it to work but I don't really understand what it does so I can't really work back from it.

 $('img[data-lazy]', _.$slider).not('[src]').addClass('slick-loading');

Which bit of the slider should I expect to see the slick-loading class appear on?

What's it dependant on?  For example, I'm using a background-image rather than an <img> as it was the only way I could think of to get the cropping behaviour that the client wanted.  Would that be an issue?

Many thanks.

http://www.form.uk.com

**Comment by odie2** [comment]
Hi,

`$('img[data-lazy]', _.$slider).not('[src]').addClass('slick-loading');` says:
> Search for images in `<img>` tag, which have `data-lazy` attribute set and have no `src` attribute set (aren't loaded yet by LazyLoad) and if statements met, add class `slick-loading`

So it will work only for LazyLoading `<img>` tag, no background-image.
Check demo "Lazy Loading" on [Slick website](http://kenwheeler.github.io/slick/).
