### ISSUE TITLE
No margin in some browsers

### ISSUE THREAD

**Issue by lspoor** [kenwheeler/slick#1641]
I've been mainly testing in Chrome and have gotten what I want perfectly, you can see the working result in the first image. But in any other browser( e.g. firefox & IE) the padding isn't working. I have also pasted the markup I'm using. I have margin:0 15px; to space them out but it isn't doing what it should be in these other browsers..see the second image.

```css
    <div class="carousel">
	    <div>
		    <a href="broadband.html" style="padding:0 15px;"> // I'm applying this within a css file but have placed it here just so you know what styles i'm using
			    <img src="images/carousel/broadband.jpg" alt="">

			    <h6 class="title">
				    Broadband
			    </h6>
		    </a>
	    </div>
    </div>
```

![screen shot 2015-08-14 at 17 10 13](https://cloud.githubusercontent.com/assets/1685176/9278273/ade3ff98-42a7-11e5-9456-573613b584b0.png)

![screen shot 2015-08-14 at 17 12 32](https://cloud.githubusercontent.com/assets/1685176/9278277/b1d4ee8c-42a7-11e5-94e5-5b5f4d182084.png)

**Comment by lspoor** [comment]
Anybody?

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
