### ISSUE TITLE
Doc Issue: slickGoTo bool arg usage

### ISSUE THREAD

**Issue by wdews** [kenwheeler/slick#1642]
Ken,

First off, thanks for making such a great carousel. I use it in nearly every project.

The verbiage explaining 'slickGoTo' args seems incorrect. "int : slide number, boolean: should animate". I get from this that, to prevent from animating, I'd put 'false' for the bool argument. Might change verbiage to:

"int : slide number, boolean: should not animate"

Thanks!

**Comment by kenwheeler** [comment]
Closing as a duplicate, fixing soon
