### ISSUE TITLE
'arrows' settings controlled by responsive breakpoint creates empty slides

### ISSUE THREAD

**Issue by reverie** [kenwheeler/slick#1643]
If you have a responsive breakpoint that sets 'arrows' to false, crossing that window-width threshold adds 2 empty slides to the carousel. You can resize the window repeatedly to keep adding new blank frames.

**Comment by simeydotme** [comment]
@reverie as per the contribution guidelines, can you create a JSFiddle, please... also can you qiuckly test with the lastest code in MASTER branch (not hte released / minified code) and see if it is still occuring? :)
