### ISSUE TITLE
Responsive option doesn't work on mobile

### ISSUE THREAD

**Issue by giathinh910** [kenwheeler/slick#1648]
Here is my responsive setting:

```javascript
responsive: [
	{
		breakpoint: 1200,
		settings: {
			slidesToShow: 3,
		}
	},
	{
		breakpoint: 768,
		settings: {
			slidesToShow: 2,
		}
	},
	{
		breakpoint: 320,
		settings: {
			slidesToShow: 1,
		}
	}
]
```

This responsive option does work on computer with different screen size. However it does not work on real mobile. On an Iphone, slide even not initialize at all. Could you please help me? Thanks.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
