### ISSUE TITLE
Can't put background for a div over the slider.

### ISSUE THREAD

**Issue by SalahAdDin** [kenwheeler/slick#1651]
Well, i try to put more elegant the slider and i try put a caption for the slider elements, 
I want to emphasize putting a dark color for the background but this fund lags behind when it should be in front, what do I do?
![background wrong](https://cloud.githubusercontent.com/assets/5034215/9322703/bc3c25ba-453c-11e5-9152-a4b950c190c3.png)

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
