### ISSUE TITLE
Center all slider's elements

### ISSUE THREAD

**Issue by SalahAdDin** [kenwheeler/slick#1652]
I want to show all the elements within the slider centered, but I try to put more classes to center, only the first element centered me, what do I do?
![no centra](https://cloud.githubusercontent.com/assets/5034215/9322912/dcb71874-453f-11e5-8d10-ee97d4e2079a.png)
![no centra2](https://cloud.githubusercontent.com/assets/5034215/9322914/defd8b40-453f-11e5-948b-4dea7ad48d8b.png)

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
