### ISSUE TITLE
Unfilter loses functionality after breakpoint 

### ISSUE THREAD

**Issue by Worstkaes** [kenwheeler/slick#1655]
Hi,

I'm using the fantastic "slickFilter"-Function to hide some slides and later get all visible again with unfilter, but I could observe that after a breakpoint, the unfilter loses his functionality, if I used "slickFilter" before the breakpoint.
Had anyone else the same issue?

Here the fiddle:
https://jsfiddle.net/v6a2nLds/

Best regards,
Moe

**Comment by mstmustisnt** [comment]
Hi!
I faced the same issue.. Unfilter doesn't work after a breakpoint...

**Comment by kenwheeler** [comment]
Closing as a dupe, fixing this soon
