### ISSUE TITLE
Slick Carousel Blank Slides

### ISSUE THREAD

**Issue by mgtelford** [kenwheeler/slick#1657]
I set up an overlay slick carousel, so when you click on the image a larger carousel appears with the selected image as the initialSlide. However, Slick carousel is adding several blank slides after the initialSlide. Does anyone know why? Also, how can I restart the overlay carousel upon close?

  $("#sync1 .item").on("click", function() {

        var index = $(this).attr("data-slick-index");
        $(".overlay-carousel-container").css("display", "block");
        $("body").css("overflow", "hidden");
        $("#overlayCarousel").slick({
          slidesToShow: 1,
            fade: true,
            initialSlide: index,
            focusOnSelect: true
        }); 
    })
<div class="overlay-carousel-container">
    <a class="close">&nbsp;</a>
        <div class="overlay-wrapper">
                <div class="overlay-img-wrapper"> 
                    <div class="overlay-carousel-nav" id="overlayCarousel">

                        <div class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>
                        <div  class="overlay-slider-img"><img src=""></div>

                    </div>  
                </div>
        </div>  
</div>

**Comment by mgtelford** [comment]
I tested a few more things and found that the previous button on the overlay carousel does not contain the blank slides. I only see the blank slides when I click on next.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
