### ISSUE TITLE
Unable to filter by class

### ISSUE THREAD

**Issue by avi8tor81** [kenwheeler/slick#1658]
Unable to filter by class. Works fine when filtering by ID. Five slides with the .TN class
$('#slider').slick('slickFilter',$('.TN'));

**Comment by btpoe** [comment]
did you try `$('#slider').slick('slickFilter','.TN');` ?

**Comment by svelazqu** [comment]
Did anyone solve this?

**Comment by St3f4NS** [comment]
For me it just removes all slides. Tested with ID and class, it does not work. Is this even posible or I'm just doing it wrong.

`    $('.filter_products').on('click', function(){
        var clickedCategory = this.id;
        console.log(clickedCategory);
       $('.list_products').slick('slickUnfilter');
       $('.list_products').slick('slickFilter', '#filter-' + clickedCategory);
    });`

**Comment by oninross** [comment]
Has this issue been solved?
