### ISSUE TITLE
Can't disable specific slide based on breakpoint

### ISSUE THREAD

**Issue by BEECHBOY707** [kenwheeler/slick#1659]
Hello!

Firstly, great slider, thank you so much.

I have almost completed it, but am trying to remove a specific slide (it is one at the end, used as a spacer) when the slider is being viewed from a mobile.

I first tried using CSS the @media method to display: none the slide at a certain screen width - this does not help however due to how Slick is set up, meaning instead it just displays a blank slide instead.

I then tried to add some jQuery and manipulate the following using the Slick 'Method: slickRemove

    $('.myslider').on("click", ".slide_to_be_removed", function () {
        var index = $(".myslider .slide_to_be_removed:not(.slick-cloned)").index(this);
        console.log(index);
        $('.myslider').slick('slickRemove', index);
    });

This worked for removing the slide on click, but I want to remove it without a click, just at a certain width.

How would I do this please?

Many thanks

Max

**Comment by lolmako** [comment]
Instead of using on('click'), try detecting the browser width and based on that apply what you need.

See http://stackoverflow.com/questions/16144187/how-to-detect-browser-size-using-javascript

This might help you.
