### ISSUE TITLE
window scroll after ending change slide

### ISSUE THREAD

**Issue by kameas** [kenwheeler/slick#1662]
if the slider is outside the screen, and change the slide using the arrows - scroll the window to the scope of the slider

example -
https://i.gyazo.com/12167ed07ed2b1f45338059dbcb5ba0c.gif

p.s. browser - chrome 44.0.2403.157 m

**Comment by fglukhov** [comment]
In slick.min.js comment this piece: ,b&&a.$slideTrack.find(".slick-active").focus()

**Comment by bdimaggio** [comment]
Hey, thanks fglukhov--we were having this problem too, and your fix did the trick.

**Comment by mattweb** [comment]
Yeah, thanks fglukhov. Ran into this because I had to position the arrows outside the slider.

**Comment by ackidri** [comment]
It has been fixed in 1.5.9.

**Comment by bradr29** [comment]
kk
