### ISSUE TITLE
YouTube API video not playing in slider at given breakpoint

### ISSUE THREAD

**Issue by yorkshiredev** [kenwheeler/slick#1663]
Hello!

I have managed to integrate YouTube API videos within the Slick slider, which work fine and as expected until I start using breakpoints. When I hit a breakpoint e.g. 1280 pixels, clicking the YouTube play button/trigger no longer plays the video. Instead, the browser picks up the click event like an anchor click event e.g. http://website.com/product#youtubeapi-player-my83619-gsg . There are no Javascript errors in the browser console.

I am using the YouTube Javascript API: https://developers.google.com/youtube/iframe_api_reference

Any ideas? Code below:

Thanks!

                         $('.js-slider-for').slick({
                          slidesToShow: 1,
                          slidesToScroll: 1,
                          arrows: false,
                          draggable: false,
                          infinite: false,
                          fade: true,
                          asNavFor: '.js-slider-nav',
                          responsive: [
                            {
                              breakpoint: 1280,
                              settings: {
                                arrows: true,
                                draggable: true,
                                infinite: true,
                              }
                            },
                          ]
                        });

                        $('.js-slider-nav').slick({
                          slidesToShow: 3,
                          slidesToScroll: 1,
                          asNavFor: '.js-slider-for',
                          dots: false,
                          centerMode: false,
                          draggable: false,
                          vertical: true,
                          focusOnSelect: true,
                          infinite: false,
                          slidesToScroll: 1,
                        });

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by kenwheeler** [comment]
Can you please provide an isolated demo?
