### ISSUE TITLE
Does not react on data-slick attribute

### ISSUE THREAD

**Issue by derwaldgeist** [kenwheeler/slick#1664]
I'm trying to set the options with the data-slick attribute like this:

```html
<div class="slick-carousel" data-slick="{'slidesToShow': 1, 'slidesToScroll': 1, 'dots': true, 'arrows': false}">
```

However, the carousel ignores these values.

The carousel is initialized with:

```js
$('.slick-carousel').slick();
```

and in principle it works, but it still shows the arrows instead of dots as expected.

It only works if I change the JavaScript to this:

```js
$('.slick-carousel').slick({
    dots: true,
    arrows: false
});
```

**Comment by btpoe** [comment]
single quotes are not valid in JSON, try swapping your single and double quotes.

**Comment by kenwheeler** [comment]
^ Indeed
