### ISSUE TITLE
Smooth Scrolling instead of snapping to images

### ISSUE THREAD

**Issue by ljmarkham** [kenwheeler/slick#1665]
I love this slider but I am wondering if it's possible to have smooth scrolling where the slider stops wherever you stop scrolling at, rather than it snapping to certain images.  I have tried playing around with the 'SlidesToShow' and 'SlidesToScroll' settings but on mobile devices it still seems to skip or cut off images with the snap function based on the format of images in each slider (I have a bunch of sliders with different format/size images).  Is there any way to edit the code so it functions similar to this example - http://www.xtcdesign.com/pages/serenity-kitchen.php - where it's just a smooth scroll based on the mouse/touch scroll.
Thank you.

**Comment by cseeger** [comment]
+1

**Comment by mindmelting** [comment]
+1

**Comment by ljmarkham** [comment]
Thanks cseeger but I need my slider to start at the left so center-mode doesn't work for me.

**Comment by ljmarkham** [comment]
Thank you for a great slider @kenwheeler but just wondering if there is a solution for smooth scrolling rather than the slider snapping to each image?  It seems a few people are interested in knowing how to do this.  Thank you.

**Comment by kenwheeler** [comment]
There isn't a way to do this right now, although I could add it.

**Comment by cseeger** [comment]
It would certainly be a nice feature. 😀

**Comment by ljmarkham** [comment]
Is it difficult to add?  I wasn't sure if there's code that could be added for it. Not well-versed in jquery.  Otherwise love the slider.

**Comment by kenwheeler** [comment]
Well, it's tough. Slick uses duration based animation. So it's like you swipe and it animates in 300ms. Free scroll would be physics based, where you have friction and spring, so you swipe and the velocity decrements and subtracts your left position over time on a requestAnimationFrame loop. Basically, they are different set ups. I plan to switch to the second for slick 2.0. In the meantime, Flickity has a great free scroll feature.

**Comment by ljmarkham** [comment]
Thanks for the info @kenwheeler. How do I get an update when slick 2.0 comes out?

**Comment by kenwheeler** [comment]
@ljmarkham I'll ping you

**Comment by timothywisdom** [comment]
Please "ping" me as well. I love Slick but would like Free Scrolling

**Comment by kodie** [comment]
+1!

**Comment by zslabs** [comment]
This would be great!

**Comment by dirkbartels14050** [comment]
definitely wanted

**Comment by jeffpannone** [comment]
#+Many# 

Agreed, this would be an awesome feature.

**Comment by f1nality** [comment]
+1

**Comment by kenwheeler** [comment]
This is coming in 2.0. The branch is up now if you wanna look. Modernizing everything, and this issue will be possible when I refactor how slide display and movement works.

**Comment by visualjazz-sbrunno** [comment]
+1

**Comment by BrianJLennon** [comment]
+1 - just started using slick and LOVE it .... smooth scrolling defo necessary alright. Thanks

**Comment by PiotrChr** [comment]
Hi, just one quick question. How is the progress with this particular feature or 2.0 release? My team is using your pretty Slick carousel, and we're really hoping for this feature. For now we have to stick to 2 libraries :( (swiper & slick)

**Comment by akashnigam010** [comment]
In dire need of this feature.

**Comment by lopugit** [comment]
+1 on this too! Please really need it, if slick had this, my word.

**Comment by jncampbell** [comment]
Any update on when this will be added?

**Comment by warapitiya** [comment]
Must need feature

**Comment by jeanjordan** [comment]
+1

**Comment by EstDiaz** [comment]
+1

**Comment by kenning** [comment]
+2, i'm very tall

**Comment by kenwheeler** [comment]
@kenning noted. This has been in progress for a while, I just need to find the time to finish it. Namely, doing it without breaking the existing API, functionality or introducing new bugs, which has proven challenging.

**Comment by underlircs** [comment]
+1

**Comment by lopugit** [comment]
do you need any help? I'd love to see it soooooooon

**Comment by melneff** [comment]
+1

**Comment by imiMike** [comment]
+1

**Comment by taraskhvyl** [comment]
+1

**Comment by erenbertr** [comment]
+1

**Comment by alexburgos** [comment]
+1

**Comment by johnylaravel** [comment]
+3, my two girlfriends want it too! Love your slider, thanks

**Comment by poetamuerto** [comment]
While looking for a solucion found this [1] (not mine).  Maybe useful for someone.

[1] https://jsfiddle.net/esedic/g0vn3bfg/

**Comment by jbugel** [comment]
Love Slick
would be very glad with this option

+1

**Comment by argofgra** [comment]
+1 Also looking for this feature. Might have to pick a different slider because of it.

**Comment by cigar9** [comment]
+1

**Comment by alexandraleigh** [comment]
+1

**Comment by pucalennetta** [comment]
+1
I cannot find any physics based carousel.
Seems like Slick is the most complete, still lacks this functionality.

**Comment by trevorwhealy** [comment]
+1

**Comment by ChristopherMortensen** [comment]
+1

**Comment by navinweb** [comment]
Sorry, 3 years and this is not complete?

**Comment by kristiansp** [comment]
From what I've heard, Slick is not really actively developed anymore. I've tried using some alternatives, like Flickity and Swiper, but they each have their limitations (as Slick does for this issue). It's a shame, because I really liked it.

**Comment by amoralesdesign** [comment]
I NEED THIS

**Comment by AurelianSpodarec** [comment]
I guess we need to abandon Slick and use Flickity or Swiper then.

**Comment by kristiansp** [comment]
@AurelianSpodarec FWIW, I've been using TinySlider after giving up on Slick, and have been pretty happy with it.

**Comment by Jtzuya** [comment]
Snapping unresolved?

**Comment by entryword** [comment]
Anyone knows any update or solutions?

**Comment by QgAnhDo** [comment]
So no updating?

**Comment by giretyu** [comment]
since 2015? surely not

**Comment by Hassanshah12-del** [comment]
**loloilloiloil***

**Comment by ballanarthur** [comment]
+1

**Comment by LaptrinhvaCuocsong** [comment]
I think we can fixed it if we set this when scrolling
{
speed: 0.0,
autoplaySpeed: 0.0,
}

**Comment by Aberratio** [comment]
To get a smooth effect in the slider, the css styles must **not contain** `tranistion` and `transform` effects. 

I give an example of settings that will set smooth autoscroll, as long as the slider styles do not contain the above mentioned functions. 

```
{
  arrows: false,
  dots: false,
  infinite: true,
  centerMode: true,
  slidesToShow: 1,
  autoplay: true,
  autoplaySpeed: 5000,
  speed: 5000,
  swipeToSlide: false,
  cssEase: "linear",
  variableWidth: true
};
  ```
