### ISSUE TITLE
variableWidth and centerMode not working.

### ISSUE THREAD

**Issue by Bolandish** [kenwheeler/slick#1666]
Hi!
I got a problem with using variableWidth and centerMode at the same time. 
The image is not positioned in the middle .
![image](https://cloud.githubusercontent.com/assets/7235443/9460958/c229c1b6-4b0a-11e5-8464-80273a0fa355.png)

**jQuery**

    $('#slider').slick({
            arrows: false,
            dots: false,
            speed: 300,
            centerMode: true,
            variableWidth : true
    });

**HTML**

    <div id="slider">
        <img height="330px" width="960px" src="0294c5a1bb05aa7745e60f5cdb896d41.jpg">
        <img height="330px" width="960px" src="d850978a186b7f0d51611af464e2ef0f.jpg">
        <img height="330px" width="960px" src="b2be59d92abf905a7ee614963e182934.jpg">
        <img height="330px" width="960px" src="b0e37549bbbc168c32cf23d9d99e73ff.jpg">
        <img height="330px" width="960px" src="08ad856a9015a381aeafcf171b6f6ec2.jpg">
        <img height="330px" width="960px" src="cf638bffc47688edc06d26985f26faed.jpg">
        <img height="330px" width="960px" src="c4e3e03c933415766f88cec06b770262.jpg">
        <img height="330px" width="960px" src="/6d2ec25fe13d431581bc3f5b966b4746.jpg">
    </div>

Check the page out http://vrigsted.dev.companyoung.com/

**Comment by isellsoap** [comment]
Why are you using `variableWidth` in the first place?

**Comment by Bolandish** [comment]
@isellsoap Because the width is not always the same :)

**Comment by Bolandish** [comment]
embarrassing ... I forgot the css ..
