### ISSUE TITLE
Gallery dragging/sliding problems with allot optenet security proxy

### ISSUE THREAD

**Issue by FieserKiller** [kenwheeler/slick#1667]
Hi,
Vodafone Germany (along other opcos world wide) uses Allot's Optenet Service (http://www.allot.com/allot-optenet-security-solutions/) for safe browsing. It's basically a big packet inspecting proxy which scans your traffic for malware and injects javascript into web pages for users to feel secure.
I made a screencast to illustrate the problem:
https://www.youtube.com/watch?v=fqUOXN2G9hw
On top you see the injected "you are secure" banderole with its tiny shield icon. This icon is draggable in case of the user wants to click anywhere below it on page. When I drag the shield, all carousels on page are dragged as well. When I release the shield, gallerys stay attached to the mouse movements.
This happens on every page using slick carousel I visited.

**Comment by kenwheeler** [comment]
Whoah thats nuts. What exactly does that shield do?

**Comment by FieserKiller** [comment]
It sits there and gives you the warm feeling of safety. 
You can drag it left and right in case it overlaps anything of importance on the page so that you can move it away and then click on whatever was beneath.  Btw, that is why I'm investigating. That shield overlays the menu hamburger button on our page and when the user drags it away, all carousels move as well...
Additionally the shield catches onclick() events, on which a bigger banderole unrolls displaying this sites security status (you can see it in my video, sec 27). Everything but the dragging works fine.

**Comment by kenwheeler** [comment]
I'm not sure this is a slick issue. The drag on that banderole thing shouldn't be so intrusive.
