### ISSUE TITLE
swipeToSlide backwards

### ISSUE THREAD

**Issue by rigoz** [kenwheeler/slick#1671]
With the option "infinite" and the option "swipeToSlide" set to true it appears that swiping backwards beyond the first slide with a length greater than "slidesToShow" value does not make the slider generate the previous slides to simulate the loop.
Swiping forward after last slide makes the slider generate the correct slides so i believe this is not intentional, and it would be cool to make it behave the same in both directions

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
