### ISSUE TITLE
Fails without error when slides are less than slidesToShow

### ISSUE THREAD

**Issue by rafgeekee** [kenwheeler/slick#1672]
I have implemented Slick in an AngularJS app showing images from an AJAX request.
This is triggered manually by user interaction.

For business reasons I have edited the code slightly, But I'm sure this is enough to see the issue.
Assume ```result``` contains the correct JSON data.
Assume ```#strip-carousel``` exists on the page
```
var stripOptions = {
        arrows: false,
        centerMode: true,
        infinite: false,
        focusOnSelect: true,
        lazyLoad: 'ondemand',
        centerPadding: '60px',
        mobileFirst: true,
        slidesToShow: 10,
        responsive: [
          {
            breakpoint: 768,
            settings: {
              centerPadding: '40px',
              slidesToShow: 10
            }
          },
          {
            breakpoint: 480,
            settings: {
              centerPadding: '40px',
              slidesToShow:  5
            }
          }
        ]
      };

scope.carousel = jQuery('#strip-carousel');
scope.carousel.slick(stripOptions);

var i = 0;
while(result[i]) {
  scope.carousel.slick('slickAdd', '<div class="strip-main"><div class="item"><img data-lazy="'+ result[i].image.url + '"></div></div>');
  i++;
}
```
When I receive more than 10 results, The carousel looks perfect and works as expected.

When I receive less than 10 results, The carousel looks broken (i.e stacked images, sometimes will not render). The controls also fail to work (i.e ```slickNext```, ```slickPrev```). I have checked the console, No error or output is shown.

I hope I have provided enough information for a debug. If you require more, Please let me know

**Comment by kenwheeler** [comment]
If you have slideToShow 10 and you have less than 10 results, why would the arrows appear? You can't slide anything.

**Comment by rafgeekee** [comment]
Hi @kenwheeler,

Thanks for your response. I do however believe you have misunderstood the issue I am facing.
The is not related to the arrows appearing. This is regarding the overall layout and behaviour of the carousel when results are less than slideToShow.

When results are less than slideToShow, The lazyLoad images fail to load. The slick items are also not correctly laid out (i.e, Instead of items being side by side, They are stacked on top of each other) - This is caused by slick classes not being applied in the Dom.

Regarding the next/prev behaviour, regardless of the number of items I'm showing, I would expect the active slide index to de/increment.

I hope this helps - When I get back to the office, I will try and demonstrate with a JSFiddle.

Thanks
