### ISSUE TITLE
Can't scroll vertically on iPhone 6 (and all other touch devices)

### ISSUE THREAD

**Issue by daviddelusenet** [kenwheeler/slick#1673]
Hi all,

I'm using multiple slick-sliders on this website: http://www.cosmiccowboys.nl/

When I'm using the website on mobile, I can't scroll when I try to scroll on the slider. I'm using the latest version (1.5.8) and the latest scss. This is my slider code:

	$('.homeSlider').slick({
		autoplay: true,
		arrows: false,
		dots: true
	});

Am I missing some code or css to make this work? Thanks in advance!

**Comment by JensFonsVanHerck** [comment]
I have the same problem. I'm working on a mobile registration form. The slider is being used fullscreen. I started with the 1.5.0 and upgraded to the latest version of Slick.
I even tried other solutions: messing around with 'pan-y' and other stuff but nothing seems to work. I can't scroll down when Slick is initialized.

I checked you site @daviddelusenet and the good thing is that your slider isn't fullscreen. You can still scroll through your website. 

I'm still searching for a solution aswel.

**Comment by daviddelusenet** [comment]
@JensFonsVanHerck thanks for your response. It's true that you can still scroll when you just try to scroll underneath the slider, only this just isn't a very good solution. Not all screens are big enough that you can still see the content underneath the slider, so then scrolling is impossible.

Anybody else already fixed this problem?

**Comment by JensFonsVanHerck** [comment]
@daviddelusenet still no solution here.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by kenwheeler** [comment]
But if you can isolate the issue I would be happy to try and fix it.

**Comment by JensFonsVanHerck** [comment]
@kenwheeler I will make a JSFiddle right away.

**Comment by JensFonsVanHerck** [comment]
Hi @kenwheeler 

Here you have the JSFiddle.
From the moment I enabled the slider I can't scroll on any mobile device. I double checked to make sure I was using the newest version and I even tried solutions from issue #449 

Nothing worked.

I am also using external CSS files, disabled them one by one to check if nothing was causing trouble but still no success.

Maybe I messed up something in the slick-theme.css, I really have no idea.

I hope you can help me, otherwise I have to start thinking about using another slider. 

If you have any more questions do ask!

Thanks in advance.

http://jsfiddle.net/fmo50w7n/70/

**Comment by kenwheeler** [comment]
Does removing the swipe and touchMove options fix this?

**Comment by JensFonsVanHerck** [comment]
No, I tried enabling and disabling all the options that could have something to do with swipe or scrolling motions. The funny thing is, when I go to the fiddle on my mobile device I can scroll vertically but not horizontally. So I'm really guessing that there is a mistake in my project.

I even used the .js file that is being used on the slick.js demo site ( older version ) and that also didn't fix the problem.

**Comment by kenwheeler** [comment]
If you want to send me a zip of your project I can take a look. It could be a lot of things.

**Comment by JensFonsVanHerck** [comment]
I will see what I can do because I am a trainee in a company and I can't give away any source code.

**Comment by JensFonsVanHerck** [comment]
Found something else: when I try to scroll I am selecting HTML elements ( I'm using an emulator to test mobile things on my desktop ).

**Comment by JensFonsVanHerck** [comment]
![problem](https://cloud.githubusercontent.com/assets/14109478/9731760/37361bac-561f-11e5-954e-7fcaf63bfe8a.PNG)

Here you can see what is happening when I simulate a touch scroll movement on the slider.

**Comment by JensFonsVanHerck** [comment]
You can close it, it has nothing to do with your slider.
Sorry for the inconvenience

**Comment by daviddelusenet** [comment]
What was the problem? Maybe I've a same kind of issue..

**Comment by JensFonsVanHerck** [comment]
I am using another library, a signature pad. And that library is disabling the scrolling motion.
