### ISSUE TITLE
Lazy Load Ondemand Threshold parameter

### ISSUE THREAD

**Issue by jan1980** [kenwheeler/slick#1674]
Hello guys, is there a way to implement a threshold parameter for the ondemand Lazyload?

This way, a given image could start being downloaded earlier than it appears on the screen, so we make sure there are no empty frames sliding in.

If I'm missing something please tell!

Here's a link to a jQuery script where threshold is used, if this gave some ideas:
- http://www.appelsiini.net/projects/lazyload

Thanks for any input on this,

**Comment by kenwheeler** [comment]
Not in the current implementation. I would experiment with some 3rd party lazy load libs to see if you can make it happen with them instead of the built in.
