### ISSUE TITLE
slick.activeBreakpoint - object correct / output not

### ISSUE THREAD

**Issue by coxrichuk** [kenwheeler/slick#1675]
When I am listening inside `init` and trying to find out the current breakpoint settings I am being returned `null` from `slick.activeBreakpoint`

Example below:

                `var sliderAPI = $('> .slider-inner');

                sliderAPI.on('init.slick', function(event, slick){                   
                   
                    console.log(slick.activeBreakpoint); // returns as null
                });`

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
