### ISSUE TITLE
Could the script be initialized on the <head> section instead?

### ISSUE THREAD

**Issue by jan1980** [kenwheeler/slick#1676]
We are recommended to initialize Slick right before the ending body tag.

However, for some sites with (unfortunately) lots of javascript, it takes a lot before the slider kicks in at the end of the document, so if we are using the lazyload option, the data-lazy attribute will be filled pretty late, giving some empty frames until everything is loaded.

I'm going to test it out but, are you aware guys of any caveats concerning an earlier initialization of the script?

Cautionary note: my interpretation could be wrong, please correct if needed.

**Comment by kenwheeler** [comment]
You can if you want, as long as it is after jQuery sequentially. That said, you might be better off hiding it until init.
