### ISSUE TITLE
Initialization on Elements with more than one ID does not work

### ISSUE THREAD

**Issue by assiprinz** [kenwheeler/slick#1684]
If I initialize slick on an element which has multiple ids, initialization will not work, no error will be thrown. Switching around the ids to other positions within the attribute in HTML does not help.

It would be extremely helpful to support multiple ids on an element. Especially for bigger projects, where one would potentially separate styling from functionality ids.

**Comment by aicarlson** [comment]
According to the HTML spec it's invalid HTML to have two `id` attributes on a single element:

>In XML, fragment identifiers are of type ID, and there can only be a single attribute of type ID per element. Therefore, in XHTML 1.0 the id attribute is defined to be of type ID. In order to ensure that XHTML 1.0 documents are well-structured XML documents, XHTML 1.0 documents MUST use the id attribute when defining fragment identifiers on the elements listed above. See the HTML Compatibility Guidelines for information on ensuring such anchors are backward compatible when serving XHTML documents as media type text/html.
http://www.w3.org/TR/xhtml1/#h-4.10

I'm not sure if that's the reason it doesn't work, but it seems likely.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
