### ISSUE TITLE
Slick init to make loading smooth (invisible to visible div)

### ISSUE THREAD

**Issue by maxgittelman** [kenwheeler/slick#1685]
I am trying to have my carousel not flicker upon loading so what I've done is set the carousel wrapper to  { visibility: hidden } in my css file. And upon loading the carousel I change the visibility to visible but the code below doesn't seem to be changing the carousel's visibility to visible? Am I using the 'init' function incorrectly or is there something I simply don't understand about javascript. Thanks in advance.

    $(document).ready(function(){
        $(#carousel).on('init', function () {
            visibility: visible;
        });
        $('#carousel').slick({
            speed: 300,
            slidesToShow: 1,
            centerMode: true,
            variableWidth: true,
            prevArrow: $('.prev_box'),
            nextArrow: $('.next_box'),
            infinite: true,
        });
    });

**Comment by odie2** [comment]
I am not JQuery spec, but I think it should looks like this:
```
$( '#carousel' ).on('init', function (event, slick) {
    $( '#carousel' ).css( 'visibility', 'visible' );
});
```

Or maybe even simpler, but I am not sure what `slick` arg is:

```
$( '#carousel' ).on('init', function (event, slick) {
    $( slick ).css( 'visibility', 'visible' );
});
```

**Comment by maxgittelman** [comment]
Thank you for the help, but adding in the function doesn't seem to be doing anything. Regardless of the 'init' the photos flickr upon loading. Here's a link to the problem(s):
http://www.lourdesgabrielainteriors.com/index.html
http://www.lourdesgabrielainteriors.com/Projects.html
http://www.lourdesgabrielainteriors.com/Artwork.html

**Comment by odie2** [comment]
You have no transition set and also seems like CSS transition doesn't work for `visibility`.

Replace `visibility: hidden;` with `opacity: 0;` and `visibility: visible;` with `opacity: 1;`

And add following CSS:
```
#carousel {
    -webkit-transition: 0.3s linear;
    -moz-transition: 0.3s linear;
    -ms-transition: 0.3s linear;
    -o-transition: 0.3s linear;
    transition: 0.3s linear;
    -webkit-transition-property: opacity;
    -moz-transition-property: opacity;
    -ms-transition-property: opacity;
    -o-transition-property: opacity;
    transition-property: opacity;
}
```

It should works smootly.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
