### ISSUE TITLE
Browser crash on resize with slidesToScroll: -1

### ISSUE THREAD

**Issue by camskene** [kenwheeler/slick#1686]
The browser will crash when slidesToScroll is set to -1 with the following settings:

```
$("#slideshow").slick({
  responsive: [{
        breakpoint: 760,
        settings: {
          slidesToScroll: -1,
        }
      }
]
});
```

**Comment by kenwheeler** [comment]
Why would slidesToScroll ever be negative 1?

**Comment by camskene** [comment]
I was using autoplay and was using -1 to auto increment slides in the 'previous' direction.

**Comment by kenwheeler** [comment]
You could do that by calling slickPrev on a setInterval

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
