### ISSUE TITLE
browser crash if infinite false and slideToShow 0

### ISSUE THREAD

**Issue by ignasio** [kenwheeler/slick#1687]
Scenario:
```
$('.slider').slick({
  slide: '.list-item',
  slidesToShow: 0,
  infinite: false,
  arrows: false,
    responsive: [
               {
			    breakpoint: 752,
			      settings: {
			        slidesToShow: 2,
			        arrows: false
			      }
			   },
			   {
			     breakpoint: 440,
			       settings: {
			         slidesToShow: 1,
				 arrows: false
			       }
			   }
			    ]
});
```
Here I have infinite false and slideToShow 0. I use slideToShow 0 cause I dont want to show my elemens as a slider when width > 752. I use them as a simple list, but when it`s <= 752 I want to show them as a slider

This settings causes annoying error. Browser crashes because of infinite loop here https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1009
In my case described above - I always have counter eq 0

Could you fix it asap? Btw, temporarily my case can be fixed by chaging infinite to true and function getDotCount won`t invoke here https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2397

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
