### ISSUE TITLE
Slick slider activation with arrow keys

### ISSUE THREAD

**Issue by AlfonsA** [kenwheeler/slick#1688]
Thanks for the awesome slider plugin!

I'm building a page which has multiple slick sliders inside fullpage.js (https://github.com/alvarotrigo/fullPage.js) slides. (1 slick slider inside one fullpage slide.). Both of them work with arrow keys (slick with right & left keys, fullpage with up & down keys), but there is an issue in changing the focus from one slick slider to another. Is there any ways to change the focus when navigating the fullpage slider with arrow keys? Now the focus changes only with mouse clicking each slick slider after navigating up/down in fullpage.js. It would be superb to have an access to the whole site content with just arrow keys.

Hope you guys can help me! Thanks already.

**Comment by AlfonsA** [comment]
Anyone?

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
