### ISSUE TITLE
Navigation breaks when slidesToShow and slidesToScroll are not equal values

### ISSUE THREAD

**Issue by FreznoSmooth** [kenwheeler/slick#1689]
I would like to be able to scroll by 1 slide throughout all breakpoints no mater how many slides I have set to show. This currently breaks the carousels navigation.

To re-create the issue:
Please use this most basic example I have set up to test and demonstrate the bug.
http://jsfiddle.net/FreznoSmooth/wnp8up64/

Test uses the "responsive display" example http://kenwheeler.github.io/slick/

1. Set slidesToShow to be different for all 3 breakpoints
2. Set slidesToScroll to be the same (1) for all 3 breakpoints
3. Resize window so that only 1 slide is being shown.
4. Select the last slide.
5. Resize window so that 2 slides are being shown
6. The current slide index seems to be incorrect now and the carousel navigation (button and swipe) is broken. In this instance you can click the prev navigation button twice and it will come right (not ideal).
7. Refresh and restart the test from step 3, however this time at step 5 resize your browser larger so that 3 slides are being shown. Now the carousel navigation (button and swipe) is completely broken.

Seems the current slide index may not be re calculating correctly on resize?
Would be great to get this issue resolved as otherwise slick is a great plugin!

**Comment by mazzaker** [comment]
This can be fixed with #2152
[Fiddle with #2152](http://jsfiddle.net/36raavxe/1/)

**Comment by leggomuhgreggo** [comment]
Looks like this got fixed when #2152 got merged. Closing.
