### ISSUE TITLE
slickGoTo animate boolean backwards

### ISSUE THREAD

**Issue by doZennn** [kenwheeler/slick#1691]
For example:
```javascript
slider.slick('slickGoTo', 2, true);
```
will not animate

and
```javascript
slider.slick('slickGoTo', 2, false);
```
will animate

The docs say:
>int : slide number, boolean: should animate

**Comment by kenwheeler** [comment]
This is a duplicate, but is getting fixed soon

**Comment by vishnusomanus** [comment]
How to slide to particular slide, without sliding animation,setting 3rd parameter to false not working

**Comment by groe** [comment]
@vishnusomanus Set it to `true` to disable the animation. Not sure why, but it works.

I guess the docs should actually say:

> int : slide number, boolean: skip animation
