### ISSUE TITLE
Suppress the outline caused by tabindex

### ISSUE THREAD

**Issue by bit-seq** [kenwheeler/slick#1692]
I've updated slick-slider to the current version and was bothered by an outline around my slick-slides that I could't recognize in style. Even the browsers dev-tools suppressed the declaration and the computed style.
It's hard to troubleshoot a style that's not listed, however, by removing attributes and declaring `style="border:none;outline:none;"` I found the attribute `tabindex` to cause the outline during selection as the browsers define it.

For more accessibility I appreciate this attribute's introduction. However, I don't think that a visual outline is desired around some carousel's slides, also because the outline is moving with the dragged slides. To access an element by tabbing and at that don't see anything highlighted is another bad behaviour, maybe it's good to have an option enabling or disabling tabindexes.

For the moment, I added the following rule to my stylesheet
```css
.slick-slide[tabindex] {
  outline: none;
}
```

**Comment by alistairholt** [comment]
+1

**Comment by kenwheeler** [comment]
Does anyone else want to chime in on removing this a11y feature?

**Comment by sethrubenstein** [comment]
This was driving me crazy. Thanks for the fix.

**Comment by hrhenals** [comment]
+1 Thanks for the fix

**Comment by jesusjjf** [comment]
+1 Worked

**Comment by jerrylau** [comment]
+1

**Comment by leggomuhgreggo** [comment]
This is fixed in the master
