### ISSUE TITLE
Bug with filtering on responsive

### ISSUE THREAD

**Issue by pauliusg** [kenwheeler/slick#1693]
Hi,

I have the same issue as in https://github.com/kenwheeler/slick/issues/1402 which was closed and not resolved.

Link to code with issue: http://codepen.io/anon/pen/ZbYQWz?editors=101

Steps to replicate issue:
1. You have to load a code in one breakpoint
2. Use slickFilter
3. Then change breakpoint 
4. Use slickFilter again (only elements from last filter are passed instead of all elements

Video how to replicate the issue: http://screencast-o-matic.com/watch/coQejcfEhk

**Comment by VaclovasV** [comment]
+1

**Comment by mantas-kunsmanas** [comment]
+1

**Comment by kestas-devbridge** [comment]
+1

**Comment by ginmot** [comment]
+1

**Comment by kokssuo** [comment]
+1

**Comment by linasmatakas** [comment]
+1

**Comment by ktkaushik** [comment]
+1

**Comment by kenwheeler** [comment]
This will be fixed soon

**Comment by tsbilguun7167** [comment]
Hello. Sorry for bad english. I really cant understand this issue. 
1. You have to load a code in one breakpoint
2. Use slickFilter
3. Then change breakpoint 
4. Use slickFilter again (only elements from last filter are passed instead of all elements

1 and 3 sentences cant understand help me @pauliusg

**Comment by kenwheeler** [comment]
It is basically saying that the original elements are lost after a breakpoint change.

**Comment by tsbilguun7167** [comment]
var filtered = false;
$('.product-button').on('click', function () {
    var filtername = $(this).attr('id');
    var currentclass = $(this).attr('class');
    if (filtered === false) {
        $('.product-carousel').slick('slickUnfilter');
        $('.product-carousel').slick('slickFilter', '.filter-' + filtername);
        $(this).attr('class', filtername + ' product-button');
    } else {
        $('.product-carousel').slick('slickUnfilter');
        $('.product-carousel').slick('slickFilter', '.filter-' + filtername);
        $('.product-carousel').slickGoTo(0);
        $(this).attr('class', filtername + ' product-button');
        filtered = false;
    }
});
What should i change here? Sorry for asking bad things.

**Comment by kenwheeler** [comment]
It's not your code, I need to fix it.

**Comment by tsbilguun7167** [comment]
Okay thank you for attention. I will try :)

**Comment by kenwheeler** [comment]
If you wanna give it a shot, look at the filter method where the current slides get saved. You'll want to store them on the instance, rather than on the mutable current options object.

**Comment by tomsarduy** [comment]
Still an issue :/

**Comment by microcipcip** [comment]
+1

**Comment by kenwheeler** [comment]
Working on it

**Comment by bblaha** [comment]
+1

**Comment by slr1979** [comment]
Any update on this @kenwheeler ?

**Comment by BenMGilman** [comment]
+1

**Comment by slr1979** [comment]
Sorry, but even after updating to 1.5.8 I am still having issues when using slick filter with breakpoints. Fine when not in breakpoints. See https://github.com/kenwheeler/slick/issues/1701#issuecomment-138279616 for my current code.

**Comment by kenwheeler** [comment]
@slr1979 The fix is on master, it will be released in 1.5.9. You can grab slick.js right off of github and the fix is there.

**Comment by slr1979** [comment]
@kenwheeler Sorry, admittedly I was using slick.min.js. However, even using the master slick.js did not resolve the issue. In fact the filter has stopped working even when not within a breakpoint? It's like it does not reinitialise when I click another filter?

**Comment by kenwheeler** [comment]
@slr1979 are you not unfiltering before filtering again?

**Comment by slr1979** [comment]
@kenwheeler.....if you are referring to ''slickUnfilter'' I don't think I am actually. I didn't think of that  as it worked without it outside the breakpoints.  Would you be able to advise me on how I would use ''slickUnfilter'' in my existing click code?

`var $optionSets = $('#filters'),
			$optionLinks = $optionSets.find('a');
		$optionLinks.click(function() {
			var $this = $(this);
			if ($this.hasClass('selected')) {
				return false;
			}
			var $optionSet = $this.parents('#filters');
			$optionSets.find('.selected').removeClass('selected');
			$this.addClass('selected');
			var selector = $(this).attr('data-filter');
			container_slick.slick('slickFilter', selector);
			return false;
		});`

My apologies for being a bit thick.

**Comment by kenwheeler** [comment]
You could just call container_slick.slick('slickUnfilter'); right before you call filter.

**Comment by slr1979** [comment]
Bingo! All fixed in conjunction with updated slick.js. No problems with breakpoint now either. Thanks so much @kenwheeler

**Comment by kenwheeler** [comment]
anytime! @slr1979

**Comment by skinnynet** [comment]
Yes! It steel doesnt works!!!

**Comment by yanike** [comment]
I have an issue with breakpoints where the carousel disappears when filtering.

**Comment by mayankagrawal10198** [comment]
+1

**Comment by shereewalker** [comment]
@kenwheeler 

Hi Ken,

Firstly, amazing plugin, I've used it so many times, but this is the first time I have tried to do this.

Has the bug with responsive and filtering been fixed?

I have tried a few versions of slick including the latest but it doesn't seem to work - specifically it does not work on window resize, but does if you refresh the window. I also tried adding 'rows:0' to the breakpoints (a suggested fix) but no joy.

Am I missing something? I have been at it for three full days and I can't seem to get it to work. I would be really grateful for any help.

```
	
( function( $ ) {
	class SlickCarousel {
		constructor() {
		  this.initiateCarousel();
		}
	
		initiateCarousel() {
		 $('.pm-slider').slick({
		   autoplay: false,
		   slidesToShow: 3,
		   slidesToScroll: 1,
		   arrows: false,
		   infinite: false,
		   variableWidth: true,
		   dots: false,
		   
		   responsive: [
				{
			   	breakpoint: 1001,
				    settings: {
					slidesToShow: 2,
					slidesToScroll: 1
					}
				},
			
				{
				breakpoint: 768,
					settings: {
					slidesToShow: 1,
					slidesToScroll: 1
				}
			 }
			]
	
		 });
		 
		var filtered = false;
		 
		$(document).ready(function () {
		let filtered = false;
		
		// Function to apply filtering based on screen width
		function applyFilters() {
		const screenWidth = window.innerWidth;
		
			if (screenWidth >= 768) {
			  
			  	if (filtered) {
					$('.pm-slider').slick('slickUnfilter');
					filtered = false;
			  	}
			  	
			} else {
			  	if (!filtered) {
					$('.pm-slider').slick('slickFilter', $('.desktop-content-pm').parent().parent());
					filtered = true;	 
				}
			}
		}
		
		// Initial check and on resize
		applyFilters();
		
		$(window).resize(function () {
			applyFilters();
		});
		
		});
		 
		 $('.slide-prev').click(function(e){ 
				 //e.preventDefault(); 
			 $('.pm-slider').slick('slickPrev');
		 } );
		   
		 $('.slide-next').click(function(e){
			   //e.preventDefault(); 
			 $('.pm-slider').slick('slickNext');
		 } );  
		 
		
	  }
	}
	
	new SlickCarousel();
	
} )( jQuery );	
```
