### ISSUE TITLE
Mobile UX for autoplay

### ISSUE THREAD

**Issue by aleemb** [kenwheeler/slick#1694]
PauseOnHover is handy for desktops to allow readers to pause the slideshow. This is desirable for example when images have captions or infographics, etc. However, it doesn't work on mobiles since hover isn't a legitimate action there and has been annoying a number of our users on mobile.

It would be nice if the sildeshow were paused while the user has his finger pressed on the slideshow (without registering a click in case the slideshow has linked images). It's not ideal since the user might not think to pause the slideshow by keeping their fingers pressed.

Another approach would be to disable autoplay for X seconds immediately after a manual swipe since it implies the user has expressed the desire to switch from auto to manual (by swiping). Autoplay can resume after X seconds of no interaction since the user has most likely moved on and it's safe to resume autoplay. I know this can be done manually fairly easily but it would be nice if the framework provided a solution for the mobile autoplay UX problem, improve the UX for all slideshows out there.

**Comment by simeydotme** [comment]
I've addressed this on `master` by interrupting the slider on touch-start and uninterrupting  on touch-end. Please wait for a release.
