### ISSUE TITLE
Anyway to mix and match row layouts?

### ISSUE THREAD

**Issue by tr33m4n** [kenwheeler/slick#1695]
Hi there,

I'm just wondering if there's a way of having a large image as slide one, followed by 2 rows of smaller slides, followed by a large slide again? I guess kind of like allowing variable width slides, but having multiple rows for certain sections

Cheers,
Dan

**Comment by kenwheeler** [comment]
Not at this time

**Comment by bagusflyer** [comment]
I have exactly the same question. Although it doesn't support natively but can I do some thing like this:

    <div class="slider">
         <div>
              <div class="bigcell">
              </div>
         </div>
         <div>
              <div class="smallcell"></div>
              <div class="smallcell"></div>
         </div>
         <div>
              <div class="smallcell"></div>
              <div class="smallcell"></div>
         </div>
         <div>
              <div class="smallcell"></div>
              <div class="smallcell"></div>
         </div>
    </div>

Is this possible? Thanks
