### ISSUE TITLE
Potential Issue with Jquery Mobile Navigation

### ISSUE THREAD

**Issue by navar45000** [kenwheeler/slick#1696]
I am using slick in several pages as container/bucket for storing images (Page A).  I have a separate page that serves as a custom gallery (Page B).  I open the separate page from a button on/near the carousel and wait  for images to be selected, some localStorage variables to be set, window.history.back is invoked and these images are set in slick carousel. 
This all works fine if I arrive on (Page A) using window.location to navigate there.

If I use Jquery mobile $.mobile.pageContainer.pagecontainer "change" to arrive at Page A, the carousel works, but when images are selected in (Page B) and now returning to page A, the carousel doesn't get updated or refreshed.  I've tried using (resize) or initializing the slick but it doesn't work. Also if there were images in the slick before going to Page B, they disappear when returning to Page A.  The code that's waiting for the images is still running and it looks like everything is set but slick doesn't refresh.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
