### ISSUE TITLE
Click on dots prompts abrupt jump not slide up

### ISSUE THREAD

**Issue by emilyvu** [kenwheeler/slick#1698]
Can't find location in code that specifies the abrupt jump when clicking on dots, would prefer animated sliding up, something like 

$('html,body').animate({
      scrollTop: $( '.carousel' ).offset().top },
      'fast');

**Comment by kyleshevlin** [comment]
Or no jump at all, would be a nice option. I'm gonna look through the code today see if I can find what's doing this.

**Comment by kenwheeler** [comment]
Closing pending edit of this issue to conform to guidelines detailed in https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
