### ISSUE TITLE
Can't scroll vertically on iPhone 6 (and all other touch devices)

### ISSUE THREAD

**Issue by daviddelusenet** [kenwheeler/slick#1702]
Hi all,

I'm using multiple slick-sliders on this website: http://www.cosmiccowboys.nl/

When I'm using the website on mobile, I can't scroll when I try to scroll on the slider. I'm using the latest version (1.5.8) and the latest scss. This is my slider code:

```
$('.homeSlider').slick({
     autoplay: true,
    arrows: false,
    dots: true
});
```

Am I missing some code or css to make this work? Thanks in advance!

@kenwheeler you closed the previous topic due to 'conform to guidelines', while if you just visit the website I mention above on your mobile phone (http://www.cosmiccowboys.nl/), you'll experience the issue. You can't scroll when on the slider, which makes the website not usable on small screens and annoying to use on bigger screens.

**Comment by kenwheeler** [comment]
Can you go to http://kenwheeler.github.io/slick and let me know if you can scroll on those sliders?

**Comment by daviddelusenet** [comment]
@kenwheeler I can! Very confused now.

This is my html:

```
<div class="homeSlider">
   	<div>
		<a href="https://www.cosmiccowboys.nl/ugg"><img src="http://cdn.cosmiccowboys.nl/homepage/slider/225"></a>
	</div>
	<div>
		<a href="https://www.cosmiccowboys.nl/sale"><img src="http://cdn.cosmiccowboys.nl/homepage/slider/222"></a>
	</div>
	<div>
		<a href="http://cosmiccowboys.nl/ugg-australia-isla-heathered-grey"><img src="http://cdn.cosmiccowboys.nl/homepage/slider/224"></a>
	</div>
</div>	
```

JS:

```
$('.homeSlider').slick({
     autoplay: true,
    arrows: false,
    dots: true
});
```

CSS is just the standard (latest version) css.

**Comment by daviddelusenet** [comment]
Is it possible you use other CSS/JS on your website than on Github?

**Comment by kenwheeler** [comment]
No. Have you tried removing all CSS but the slick CSS from your page?

**Comment by daviddelusenet** [comment]
@kenwheeler I'll be at work wednesday and then I'll try to fix this. Can you leave this open till then? Thanks so far!

**Comment by JensFonsVanHerck** [comment]
@daviddelusenet I will try to help you tomorrow.

**Comment by daviddelusenet** [comment]
lol?

**Comment by daviddelusenet** [comment]
I'm working on another website where I use a same kind of slider where scrolling DOES work. So its probably my own fault it doesn't work on Cosmiccowboys. Will try to fix it myself, thanks for all the help so far!

**Comment by JensFonsVanHerck** [comment]
Yeah I think the library is kinda bulletproof now when it comes to the scrolling. Good luck!

**Comment by pufinek** [comment]
@daviddelusenet I have the same problem, but only on iPhone, other devices are ok, do you already know, where the problem was?
