### ISSUE TITLE
Width issue at start

### ISSUE THREAD

**Issue by mrfrancescomoro** [kenwheeler/slick#1703]
Hello everyone,
really great plugin!!!
However, I'm having issues when i load the page, all the slides are superimposed on the left!
I just need to click inside the slider area and everything goes at the right place.
How can I fix this?

Thanks in advance
F.

**Comment by michielvoo** [comment]
I can confirm this can happen. After inspecting the DOM I noticed that the width on each individual image, as well as on the slick-track element is 0. As soon as the viewport is resized, or the slider is interacted with, the widths are calculated and everything snaps into place.

Using 1.5.8

**Comment by mrfrancescomoro** [comment]
It works! Thanks you so much!!!

**Comment by michielvoo** [comment]
@mrfrancescomoro What did you do to fix it?

**Comment by mrfrancescomoro** [comment]
The slider was inside a container that change width because of an animation i needed to do. So I just make it "appear" right after the animation ended so it doesn't have to load with a dimension and then change it. Don't know if this is the smartest solution but hey...it worked, so why not? :smile:
