### ISSUE TITLE
Slick init transition from opaque 0 to 1 not working

### ISSUE THREAD

**Issue by maxgittelman** [kenwheeler/slick#1704]
I am trying to prevent my website from flickering the carousel div when loading the images, how the init function doesn't seem to be functioning properly. Before the website is cached, upon loading for the first time you can clearly see the carousel flickers onto the page instead of smoothly transitioning.

This happens on all of these pages:
http://www.lourdesgabrielainteriors.com/
http://www.lourdesgabrielainteriors.com/Artwork.html
http://www.lourdesgabrielainteriors.com/Projects.html

I included the following code into my css file:

    #carousel {
        opacity: 0;
        -webkit-transition: opacity 0.3s ease-in;
        -moz-transition: opacity 0.3s ease-in;
        -ms-transition: opacity 0.3s ease-in;
        -o-transition: opacity 0.3s ease-in;
        transition: opacity 0.3s ease-in;  
    }

And I included this simple init function into the html file:

    $(document).ready(function(){
            $('#carousel').on('init', function (event, slick) {
                $('#carousel').css( 'opacity', '1' );
            });
            $('#carousel').slick({
                //variables here
            });
        });

Any help as to why the images don't load smoothly would be appreciated! Thanks!

**Comment by kenwheeler** [comment]
Its because your images aren't loaded yet, if you want it smooth, run that on window.load

**Comment by maxgittelman** [comment]
Could you please be more specific? I'm sorry but I'm quite new to front end programming. Where do I add or replace window.load() with what I have right now?

**Comment by kenwheeler** [comment]
instead of `$(document).ready` write `$(window).load(`

**Comment by maxgittelman** [comment]
thanks so much!!

**Comment by kenwheeler** [comment]
Glad I could help
