### ISSUE TITLE
Not registering click events

### ISSUE THREAD

**Issue by laoyulong** [kenwheeler/slick#1705]
The idea is simple -- when you click on a tile from the carousel, you stop the autoplay, centre the clicked element, enlarge it and disable pointer events on every other tile, so as to use the clicked element as an entry point in a navigation menu.
The problem is -- when I start the carousel and try to click on an item that is to the left of the centre element -- it doesn't register my clicks, at all. I tried going to the right, i.e. from the other side of the element, and clicked on it -- everything's fine, but clicking on the element after the problematic one, again, did not register my clicks. There's some kind of an invisible wall between those breakpoints and you shift the focus from one part to the other. My question is: Is it possible work around this limitation (from my point of view) ? If so, how ?

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) and it's a support request.
