### ISSUE TITLE
Last slide has wrong items when total slides % slidesToShow !=0 in infinite mode

### ISSUE THREAD

**Issue by amit1911** [kenwheeler/slick#1706]
hi i have 11 slides in the slider and i am showing 3 slides per slide. when i scroll to the last slide it shows a slide from the second last slide. This happens only when (total slides % slidesToShow !=0). 
So the flow is like
slide 1 - 0,1,2
slide 2 - 3,4,5
slide 3 - 6,7,8
slide 4 - 8,9,10 --> should be 9,10,0
slide 5 - 0, 1, 2
please have a look at the jsfiddle https://jsfiddle.net/amit1911/1db30w01/

**Comment by leggomuhgreggo** [comment]
Hey I know this is many months later, but I tried to recreate [here](http://jsfiddle.net/oebt4p5d/) and it looks like it's resolved? I'm going to close but if there's any other issue feel free to holler back. Thanks
