### ISSUE TITLE
Transition not smooth for last slide when variableWidth: true and infinite: true

### ISSUE THREAD

**Issue by amit1911** [kenwheeler/slick#1707]
Hi all, basically i want to show 3 slides and some part of 4th one. The only way i could find was to set variableWidth to true. So now i can see the part of 4th slide but when i move from last slide to 1st slide, the transition is not smooth.
please have a look at http://jsfiddle.net/amit1911/ar4awofc/1/

This issue is when slidesToScroll > 1
if slidesToScroll = 1, the the issue is not there. have a look at http://jsfiddle.net/amit1911/ar4awofc/2/

**Comment by leggomuhgreggo** [comment]
Hey I think this is a duplicate of #1207. Tricky issue that variableWidth plus infinite.
