### ISSUE TITLE
Can i use slick with MixItUp which filtering plugin

### ISSUE THREAD

**Issue by tsbilguun7167** [kenwheeler/slick#1708]
I've been trying to use MixItUp and Slick together to accomplish this. But they aren't playing well together. MixItUp hides the items, but Slick seems to unhide them almost immediately. What should i configure from slick?

**Comment by tsbilguun7167** [comment]
@kenwheeler

**Comment by tsbilguun7167** [comment]
.slick-initialized .slick-slide
{
    display: block;
}

change display to none

**Comment by mauriciord** [comment]
Didn't work for me. Same problem here

**Comment by voiceoffriends** [comment]
It's a bit tricky but it can be done. Take a look at the example at that I shared on the post for adaptive height issue.  https://github.com/kenwheeler/slick/issues/771
The live example where both Mixit and Slick is working after ajax request can be found here: https://app.voiceoffriends.com

Important: You need to call mixit first and then initiate slick. Hope that helps.

Considering that this is not a bug I wouldn't expect Ken to answer :)
