### ISSUE TITLE
Dynamic autoplaySpeed

### ISSUE THREAD

**Issue by pfrmachado** [kenwheeler/slick#1713]
Only for share this.

To get a dynamic autoplaySpeed, just change "_.options.autoplaySpeed" to the value of each delay.

In this case, i have a attribute "delay" on each image.
In the method "Slick.prototype.autoPlayIterator" and in the method "Slick.prototype.slideHandler", in the final of both, i put the code "_.options.autoplaySpeed = $(_.$slides[_.currentSlide]).find('img').attr('delay');" and each image got it's own delay to slide.

Sorry for my bad english :D

That's all, guys!

**Comment by mcashley** [comment]
Closing in that this is just some helpful information and not an issue
