### ISSUE TITLE
Slider with carousel and Slickgoto dontAnimate not for both?

### ISSUE THREAD

**Issue by cannect** [kenwheeler/slick#1716]
Hi,

I have the following setup, tested on 1.5.0 which I currently use and 1.5.8. 

```javascript
    var $carousel = $( "div.slick-carousel" );
    var $slider = $( "div.slick-slider" );

    // Carousel with 5 smal images above the slider
    $carousel.slick({
        asNavFor: '#slider .slick-slider',
        slidesToShow: 5,
        slidesToScroll: 1,
        centerMode: true,
        focusOnSelect: true,
        prevArrow: '#carousel .prev-arrow',
        nextArrow: '#carousel .next-arrow'
    });
    // Big slider
    $slider.slick({
        asNavFor: '#carousel .slick-carousel',
        slidesToShow: 1,
        slidesToScroll: 1,
        prevArrow: '#slider .prev-arrow',
        nextArrow: '#slider .next-arrow'
    });

    // The last `true` argument is for dontAnimate
    $slider.slick( 'slickGoTo', 3, true );
```

What it does is the following:
- does indeed not animate the $slider
- **but does animate the $carousel** `// that seems to be a bug?`

Maybe I use this fuction wrong?

**Comment by godot882** [comment]
Maybe a little late. But in case anybody have problems with this.
The method is as follows: <code>$(your-element).slick('slickGoTo',index,dontAnimate);</code>
So if you want it to animate: <code>$(your-element).slick('slickGoTo',0,false);</code>

**Comment by cannect** [comment]
@godot882 Its a while ago, but thanks for your comment.

However, what I wanted is that they both **do not** animate when doing a `slickGoto`. The issue is, if you have a slider and a connected carousel you can't do a `slickGoTo` with both not animating. I think this issue is not fixed yet.

**Comment by godot882** [comment]
@cannect

Oh I see. I misunderstood your question.

If you want to add this behavior only when the page loads with your slider(s) then you could just use the "initialSlide" option. Alternately you could set the $carousel to fade: true, and override the css to opacity: 1 !important; on your slider items if you don't want to animate it at all.

Or you could use the beforeChange event on your $slider object to add a class to your $carousel and with afterChange remove the class.

Hope I could help.

**Comment by leggomuhgreggo** [comment]
This looks settled. Closing.
