### ISSUE TITLE
direct link support

### ISSUE THREAD

**Issue by fabiocaccamo** [kenwheeler/slick#1717]
It would be nice to have hash-change using custom slugs (without changing the history) to direct linking a precise slide. Is it in your todo?

**Comment by qwertydude** [comment]
+1

**Comment by simeydotme** [comment]
You can write this code yourself :)
It's been discussed at great length, before.

**Comment by chrishowardau** [comment]
Or just use different slider that already does it, since not all users are that good a coder... ;)

Also, do you have links to those discussions, Simon?

**Comment by simeydotme** [comment]
The discussion goes something like:

It would be nice to have....
But you can do it yourself...
But I personally cant...
But Slick shouldnt be defining website behaviour...
But maybe we can make it configurable...
But that could break other things...
But most users dont want it ootb...
...

...

But +1 ...
Oh Yeah, lets open this again...
But its been discussed before...

...

😞

---

If you can't code it yourself, thats why theres people who code for money... We don't all just code fully-featured carousels and end-to-end websites for free; to put ouraelves out of jobs ;)

Keep an eye on 2.0 for a real conclusion.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/152

Also, as a bonus, if u look half way through the thread, i've pre-coded the solution for you, but it uses query-strings instead of #hash -- which in my opinion is better as it wont highjack your anchor system and works with multiple carousels
