### ISSUE TITLE
#anchors jumping after slick loads

### ISSUE THREAD

**Issue by blazer380** [kenwheeler/slick#1718]
I have several slick carousels on the page and when the page loads initially, the carousels adjust in height (starting out large and then shrinking to fit the window). 

I also have various #anchors [a name="anchorname"]
If I'm on another page on the site and click on a link that takes me to an anchor on the page with the carousels, the browser jumps to the anchor first, THEN the carousels resize(shrinks in height) and the page shifts away from the anchor. The more carousels I have on a page, the more the page shifts away from the anchor.

Is there a setting or anything I can do to either delay the browser from going to the anchor until the carousels finished resizing or have a set height for the carousel so it doesn't shift?

**Comment by theLazyVince** [comment]
can confirm this problem! using the latest stable version of slick.

**Comment by kenwheeler** [comment]
The fix is on master I just need to cut a release, getting some other stuff in first

**Comment by blazer380** [comment]
Thank you Ken. Any idea on the ETA for that release? Just working on a project and would be helpful to know that approximate timing.

Thanks for the excellent work on this script btw!

**Comment by blazer380** [comment]
Any chance getting the fix pushed out soon?

**Comment by leggomuhgreggo** [comment]
Hey there's been a release since this issue was created. Do you think you [recreate in a fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) for issue verification purposes?

**Comment by blazer380** [comment]
We pushed the latest files live, but the issue is still there.
Here's a link to a page that uses several slick carousels.
http://provasicapital.com/resources/#insights

When the page loads, all the tiles in the carousels start out huge, then shrink to correct size. If you click the link above, it is supposed to take you to a section in the middle of that page. And it does, but as soon as the carousels finish loading, you end up on the bottom of the page in the events section. So we were wondering if there is a way to force slick to load without resizing or pre-load a certain max height.

As far as creating a fiddle, it is a little more involved than I thought (I'm not a developer).

**Comment by blazer380** [comment]
I've capture a screenshot of what happens while the carousel is loading.

https://i.imgsafe.org/613483b.png

What you see is each card in the carousel starts out 100% width of the page. This makes all the cards stack one on top of another until the slider is loaded and then the cards go side by side. When this happens, the total height of the page changes. If I link to an #anchor on this page, the location of the anchor is moved once all the cards are done loading.

**Comment by leggomuhgreggo** [comment]
Hey Im going to close pending a test case. Thanks!
