### ISSUE TITLE
#anchors Slick control gets misplaced from its container when receiving anchor from an external page with *adaptiveHeight*

### ISSUE THREAD

**Issue by trettet** [kenwheeler/slick#1719]
Here's my website: http://villamorapharmacy.com/vince/links/journals.html#art1 as you can see when clicking the link above the slick is too close to the jumbotron when I refresh it, it comes back to normal. And it's not an issue with bootstrap either since I tried removing/unslicking the article there is no issue with padding/margin.

**Comment by kenwheeler** [comment]
Can you reproduce this in the JSFiddle link in CONTRIBUTING.markdown? I need it isolated to properly debug.

**Comment by theLazyVince** [comment]
[This](http://jsfiddle.net/L812qqdf/1/) should be the exact code I'm using now IDK how to reproduce it when loading the code with an anchor...

**Comment by theLazyVince** [comment]
It seems like the *adaptiveHeight* feature is causing slick to offshoot from the container, I've tried removing it and it seems to work normally.

**Comment by leggomuhgreggo** [comment]
Hey I know this issue is super old, but it looks like it's working in [this example](http://codepen.io/leggomuhgreggo/live/LNgGVd#art1), even with the adaptive height. 

I'm going to go ahead an close, but if you see any issue we can look at reopening. Thanks!
