### ISSUE TITLE
CSS transform delayed by class change?

### ISSUE THREAD

**Issue by odie2** [kenwheeler/slick#1720]
Hi,

I have (right now) 3 slides of the main slider on http://zschocianow.pl/

I am using css' `transform` property to get result as current active slide is normal size and slide before and after are only 80% of height:
![zespol szkol w chocianowie strona internetowa zespolu szkol w chocianowie informacje z zycia szkoly osiagniecia i prace uczniow aktualnosci i wydarzenia oferta edukacyjna plan lekcji galeria zdjec](https://cloud.githubusercontent.com/assets/9401878/9834494/bbd0969a-59bb-11e5-9417-226502f70c24.jpeg)

Problem is that when it switch from last slide to first, there are no `transition`, just "jump effect". I don't know how classes are changed (I think the problem is delay in that action) - in loop, for every call or something else, but I am pretty sure that it could be fixed easy from script/CSS side.

Main slider's settings:
```
$('#main-slider').slick({
	infinite: true,
	dots: true,
	autoplay: true,
	centerMode: true,
	slidesToShow: 1,
	slidesToScroll: 1,
	centerPadding: '100px',
	prevArrow: '<button type="button" class="slick-prev box-shadow">Previous</button>',
	nextArrow: '<button type="button" class="slick-next box-shadow">Next</button>',
	responsive: [
		{
			breakpoint: 700,
			settings: {
				centerMode: false,
			}
		},
		{
			breakpoint: 550,
			settings: {
				dots: false,
				centerMode: false,
			}
		},
	]
});
```

My CSS are with vendor prefixes: `-webkit, -moz, -ms, -o`, but I skipped them below for clean. You could see source code on live.

CSS for each slide is:
```
#main-slider .slick-slide {
	height: auto;

	transform: scale(1, 0.8);

	transition-property: transform;
}
```

Inferited `transition` effect:
```
	transition: 0.3s linear;
```

Current slide:
```
#main-slider .slick-active {
	transform: none;

	position: relative;
	z-index: 2;
}
```

My browser in Opera Developer 33 (latest Chromium).
_Note_: I just tested it in Opera 12.17 (very old version) and saw that it going back to first slide by scrolling extremaly fast in left. So can I "fix" this bevahiour in that case? Maybe another transition time for last/first slide (done by CSS' child selector)?

Let me know if I should provide more info.

Thanks in advance for help!
Greetings

**Comment by swaincreates** [comment]
Figure anything out? I have similar issue where once the carousel comes back to the first slide it applies css and it kind of jumps. Haven't investigated too much just started looking through these issues. I'll post something if I figure it out.

**Comment by odie2** [comment]
Nope, I haven't time to take a look into it.
However as I remember I had similar issue sometime ago with another slider and as I remember, I fixed it, but I need more time to search in my old localhost's files.

**Comment by swaincreates** [comment]
Looks like because of the way Slick clones slides without id/class. I'll have to look into it tomorrow morning.

**Comment by swaincreates** [comment]
Looks like Slick's cloned slides will clone classes but not IDs. So if you are targeting css with the ID it will jump because the cloned slide that becomes slide 1 will have to add the ID. I changed to classes and it works as expected.

**Comment by odie2** [comment]
However I am targeting to `#main-slider .slick-slide` and `#main-slider .slick-active`, but will try mess with it and let know.
Or you mean something else that I didn't understood?

**Comment by odie2** [comment]
Oh, `#main-slider .slick-slide` in my case resolved issue, as original and cloned slides in my `centerMode` have this class :)

As we both resolved issues I am closing this report and maybe it will be helpful for someone else who will be in trouble with `transition`s.

Thanks @swaincreates for your involved :)

**Comment by swaincreates** [comment]
Awesome! Glad it helped, thanks for opening issue.

**Comment by SOTL** [comment]
Im not using any IDs whatsoever yet still got this issues. any insights?

**Comment by shaunroot** [comment]
I have the same issue as SOTL. It has nothing to do with ID's. The class that center mode add would work, but center mode is not an option in this case.
