### ISSUE TITLE
Load image based on screen size using Lazy Loading

### ISSUE THREAD

**Issue by lukaswojnar** [kenwheeler/slick#1721]
Hi, first let me thank you for a great slider. I'm using it on a few websites and it rocks!

I have a feature request to enhance the lazy loading function. I'm using the slider to display a full screen width carousel of images across the screen. Because of the carousel size, the images must have a big resolution (1900 x 600 px). As a result even with compression each image size is >150 KB. Having 7 images in carousel it results in 1 MB of data the user needs to download. This currently applies even at situations when he is displaying the images on a mobile display that is 360 x 640 px. 

It would be great if the lazy-loading is able to choose image based on the screen size. You could have than 2 or 3 image sizes that you would serve based on users's screen size.

The idea and markup is borrowed from Foundation's Interchange function: http://foundation.zurb.com/docs/components/interchange.html

    <img src="img/1x1.gif" data-lazy="[img/big.jpg, (default)], [img/small.jpg, (small)]">

Thank you for consideration.

**Comment by leggomuhgreggo** [comment]
Hey I know this is from a while back but I think this issue got answered in #1321. Thanks!
