### ISSUE TITLE
When swipeToSlide is true slidesToScroll is fixed to 1

### ISSUE THREAD

**Issue by paradnox** [kenwheeler/slick#1724]
Thank you for slick, its great!

When swipeToSlide is true slidesToScroll is fixed to 1, will create a JSfiddle and edit the post in a few hours.

**Comment by kenwheeler** [comment]
That's on purpose.

**Comment by Razmanroxx** [comment]
Hey!

Im a fan of Slick.

Im currently working on a project where i need to use SwipeToSlide: true.
At the same time i need to use SlidesToScroll: 3.

And with what i read here its not working that way.

Anyway to bypass?

**Comment by ramirezcgn** [comment]
I need it also, so, I have to modify the library for my project, I don't know why is not allowed :(
