### ISSUE TITLE
How do I restart the autoplay if the items number was reached?

### ISSUE THREAD

**Issue by castrojr913** [kenwheeler/slick#1727]
The idea is if carousel reaches the number of items to show with *autoplay*, it can come back to the initial position or index 0. This feature is with **infinite = false**. In this moment, carousel comes back to the previous item in regard to current item. For example, I have 3 items to show, so  if the carousel reaches up to the index 2, then, my idea is that carousel goes to the item 0 inmediately, in order to keep counting up to reach the index 2 again. is this feature possible?

**Comment by castrojr913** [comment]
In other words, It's to make the same thing when it's pressed the first indicator of the carousel. Nevertheless, the idea is that this performance comes up when Carousel reaches the last item, It re-starting to index 0 as the next item to show. Either way, I will try to do this with the available documentation

**Comment by leggomuhgreggo** [comment]
Hey, I'm closing this because [there's no test case](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) and it's a support request.
