### ISSUE TITLE
How can I monkey patch Slick ?

### ISSUE THREAD

**Issue by dorian-marchal** [kenwheeler/slick#1729]
When loaded as a module, `window.Slick` isn't accessible.
How can I change the prototype of Slick without editing the lib ?

**Comment by leggomuhgreggo** [comment]
Hey I'm closing this because it's a support request but I've done stuff like  $(element)[0].slick.changeSlide = function(a){...yada...} which might be in the ballpark of what you're looking for.

**Comment by DarrylD** [comment]
@leggomuhgreggo do you have a working way to do handle this? `$(element)[0].slick.changeSlide = function(a){...yada...}` isn't working, also don't understand how it would work.

**Comment by leggomuhgreggo** [comment]
Depends on what you're trying to do; that was just an example, the full version of which can be found [here](http://codepen.io/leggomuhgreggo/pen/vGLzgP?editors=0010).

**Comment by DarrylD** [comment]
Trying to manually change the slide of the slider outside of clicking the dots, arrows, etc... Is that possible?

**Comment by leggomuhgreggo** [comment]
Check out the [public methods](https://github.com/kenwheeler/slick#methods)
