### ISSUE TITLE
Slick is never reenabled after "unslicked" at breakpoint

### ISSUE THREAD

**Issue by nwellnhof** [kenwheeler/slick#1730]
I use `settings: 'unslick'` to disable Slick at certain breakpoints. But as soon as Slick is disabled (either by resizing or at page load), it will never be reenabled when resizing. Example:

    $('.my-class').slick({
        mobileFirst: true,
        slidesToShow: 2,
        slidesToScroll: 2,
        responsive: [ {
            breakpoint: 768,
            settings: 'unslick'
        } ]
    });

Loading the page with a viewport narrower than 768px enables Slick, resizing beyond 768px disables Slick, but resizing back below 768px keeps Slick disabled.

**Comment by compact** [comment]
I'm encountering the same problem, so I added a window resize handler to manually slick/unslick depending on window width.

**Comment by ejwaibel** [comment]
+1 This should be a bug, and officially fixed.

**Comment by farinspace** [comment]
+1 .. here is an external solution to breakpoints, letting you slick an unslick .. https://www.lullabot.com/articles/importing-css-breakpoints-into-javascript

**Comment by CamdenSegal** [comment]
+1 the unslick responsive setting isn't automatically reversed when resizing to a screen size that should have slick enabled.

**Comment by dsteinel** [comment]
+1

**Comment by denisbouquet** [comment]
+1

**Comment by j-greig** [comment]
+1

**Comment by VykintasZaboras** [comment]
+1

**Comment by johnteakdigital** [comment]
same

**Comment by memoclic** [comment]
+1

**Comment by vfonic** [comment]
+1

The way I solved both issues is with these couple of extra lines of code:
```js
$(window).resize(function() {
  $('.js-slider').slick('resize');
});

$(window).on('orientationchange', function() {
  $('.js-slider').slick('resize');
});
```

**Comment by stratboy** [comment]
+1.

And docs should mention this issue and should not feature unslick on the responsive part, since it simply doesn't work as expected, as really a lot of threads and developers are reporting. So much threads definitely make this one an issue and a bug.

**Comment by phelippe** [comment]
+1

**Comment by klierik** [comment]
+1

**Comment by ADavidLiu** [comment]
+1

**Comment by oanaalex** [comment]
what about react-slick?

**Comment by changalanggg** [comment]
So this is possibly the strangest thing, but I originally just hastily cut and pasted the above

`$(window).on('resize orientationchange', function() {
  $('.js-slider').slick('resize');
});`

and somehow missed the ");" at the end of the argument. Lo and behold, the resize event worked and the slides were resizing as expected. I then realized I was missing the ");", added it in, and all of a sudden the resize event stopped working. I'm at a complete loss as to why this might be the case, as I've debugged the rest of my jQuery code and it's a-okay.

**Comment by carloschneider** [comment]
+1

**Comment by zschuessler** [comment]
@kenwheeler how can the community help on this? I see it has been an issue for a while now, let me know if there's anything we can do to get a fix in :-)

**Comment by vgavrilovikj** [comment]
Still not fixed...!!
