### ISSUE TITLE
Issue with centre mode

### ISSUE THREAD

**Issue by designinsist** [kenwheeler/slick#1733]
Hey bro :)
Here is the issue I am facing with the slider. I am using variable width slider with a lot of custom code.
The issue is that when i have only one image in slider that does not centre aligned its let or a little bit right aligned.I am posting my link here you can check this out and can suggest the possible solution if you have. Thanks in advance.

This screen shot is with issue.

![image](https://cloud.githubusercontent.com/assets/10362590/9902243/510b2d3e-5c86-11e5-9e12-fa57bd343b32.png)

and if I select slider with two image from the filter then i have this layout and this is perfect.

![image](https://cloud.githubusercontent.com/assets/10362590/9902258/720e8882-5c86-11e5-9922-c59d0bed9fa1.png)

have you got my point ?

you can check here :)

http://www.redsignal.net/clients/helden/projects.php?name=Industrie

**Comment by designinsist** [comment]
Hey bro..!!
you can close this issue i have sort out this issue by applying php code.
actually here is what i did.

when there are only one image in slider i render that image as static html rather then slider so it center align with width and margin auto.

Thanks for such grate work :+1:

**Comment by leggomuhgreggo** [comment]
Sweet! Closing
