### ISSUE TITLE
Infinite and slidesToShow

### ISSUE THREAD

**Issue by leads** [kenwheeler/slick#1734]
Hello. More of a question than an issue, and apologies if I've missed the setting if one exists.

Say I have an infinite slide and slidesToShow: 5, but in the HTML there are only 4. Should infinite not duplicate the necessary amount of slides?

**Comment by salunet** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Interesting. I think the more likely use case is no slide effect unless the requisite number of slides are present. There's also the question of which slides to duplicate, and, wouldn't the duplication look funny?

All that said you can write your own duplication script using the init event callback, if you'd like.
