### ISSUE TITLE
Graceful loading of slides?

### ISSUE THREAD

**Issue by kavonatsalv** [kenwheeler/slick#1741]
Is there a way to hide Slick until its page has finished loading?

http://nowrongdoorsws.com.au/

Slick shows the slides beside each other while loading (a hard refresh should show this) and I would like to hide the area completely until everything has loaded for a more graceful result.

Is this possible?

Thanks. And sorry – I'm a bit rusty when it comes to JS.

:)

**Comment by dodotdot** [comment]
yes i have the same issue, on mobile web page is always block render css 

even in demo page the slide is load vertically,
![blocking](https://cloud.githubusercontent.com/assets/367159/9956757/6ddc6eb4-5e25-11e5-8c6c-01d2097fe92e.png)

its really annoying. is there any solution how to solve this
Thanks

**Comment by vramana** [comment]
@kavonatsalv You can try considering the `<template>` tag. It doesn't render anything upon the initial load. May be you can consider that.

**Comment by vfonic** [comment]
+1

`<template>` is not supported in IE

**Comment by kenwheeler** [comment]
This is really easy to do. Put a class on your slider, in your css set it to display none, and then add .slick-initialized: display block, and it shows up when slick is loaded. You may want to wrap your .slick() call in a window.load too if you're still seeing problems.

**Comment by vfonic** [comment]
Thanks for quick reply @kenwheeler!

I fixed this by using `visibility: hidden` and then doing:
```
setTimeout(function() {
		slides.hide().css('visibility','visible').fadeIn('slow');
	}, 200);
```

`display: none` didn't work because _slick_ couldn't calculate the slide height correctly.

**Comment by adamlapczynski** [comment]
`This is really easy to do. Put a class on your slider, in your css set it to display none, and then add .slick-initialized: display block, and it shows up when slick is loaded. You may want to wrap your .slick() call in a window.load too if you're still seeing problems.`

Another option is to hide all the slides except the first one (`:first-child`). Similar to what @kenwheeler suggested, when the .slick-initialized class appears, set the other slides to display: block. I haven't tried this myself, but if at least the first slide is visible, it should be able to calculate the slight height, and you it should prevent the flash of stacked slides on load.

**Comment by masi** [comment]
You can avoid flash of unstyled content completely in CSS. Perhaps worth adding to the "get started" section of the site.

```
<html>
  <head>
  <title>My Webpage Without FOUC</title>
  <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
  <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
  <style>
    .your-carousel .your-item {
      display: none;
    }
    .your-carousel .your-item:first-child {
      display: block;
    }
    .your-carousel.slick-initialized .your-item {
      display: block;
    }
  </style>
  </head>
  <body>

  <div class="your-carousel">
    <div class="your-item">your content</div>
    <div class="your-item">your content</div>
    <div class="your-item">your content</div>
  </div>

  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="slick/slick.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function(){
      $('.your-class').slick({
        setting-name: setting-value
      });
    });
  </script>

  </body>
</html>
```

**Comment by ahmadalfy** [comment]
@masi 's solution is perfect. Slick add a class `slick-initialized` once the slider is constructed. You can do:

```css
.slider { display: none; }
.slider.slick-initialized { display: block; }
```

**Comment by timatima** [comment]
.slick-slide:not(:first-child) {
	display: none;
}
.slick-initialized .slick-slide:not(:first-child) {
	display: block;
}

**Comment by chris-griffin** [comment]
@masi 

It might be worth changing your css to use visibility instead of display to avoid issues with sizing child elements.

   `.your-carousel .your-item {
      visibility: hidden;
    }
    .your-carousel .your-item:first-child {
      visibility: visible;
    }
    .your-carousel.slick-initialized .your-item {
      visibility: visible;
    }`

**Comment by neilgee** [comment]
I was having issues taming FOUC on the Slider Syncing usage with _slider-nav_ and _slider-for_, in particular for the _slider-nav_

Initially displaying the slider container to `none` and using the `.slick-initialised` class to display `block` fixes it and also setting a height on the slider container can fix the layout.

```
.slider-for-container {
        min-height: xx px;
}

.slider-nav-container {
        min-height: xx px;
}

.slider-for-container .slider-for,
.slider-nav-container .slider-nav {
	display: none;
}

.slider-for-container .slick-initialized,
.slider-for-container .slick-initialized {
	display: block;
}
```

**Comment by RedlingshoeferUndHofmann** [comment]
Using the ideas above, I found a pleasing (not perfect) solution for the problem, i guess:
```
.your-carousel{
	 visibility:hidden;
	 opacity:0;	 
	 transition: opacity 1s;
}

.your-carousel.slick-initialized{
	visibility:visible;
	opacity:1;
}

.your-carousel .your-item{
	display:none ;
}

.your-carousel .your-item:first-child{
	display:block; visibility:hidden;
} 

.your-carousel.slick-initialized .your-item{
	display:block;visibility:visible!important;
}
```

**Comment by Ogeh-Ezeonu** [comment]
@ahmadalfy I found your fix to be the perfect solution to the slick vertical loading issue.

**Comment by justcookin** [comment]
@RedlingshoeferUndHofmann 's answer is what I ended up using, worked great

**Comment by CrispySinger** [comment]
@RedlingshoeferUndHofmann 's answer is a nice solution for this, pretty handy. Cheers!

**Comment by BenSpace48** [comment]
Great workarounds, thanks!

To shorten the code a bit you can use the `:not` selector, it works with both `display: none;` and `visiblity: hidden;` methods.

```css
.your-class:not(:first-child) {
    visibility: hidden;
}

.slick-initialized.your-class {
    visibility: visible;
}
```

**Comment by roeeyossef** [comment]
using @RedlingshoeferUndHofmann - great answer!

**Comment by Dari4sho** [comment]
Thanks all and @RedlingshoeferUndHofmann, works like a charm. Only thing I did was replacing `.your-item` with `.slick-slide`.

**Comment by lesliekirk** [comment]
Nothing I try seems to help with this. All these solutions leave me with a temporary empty white expanding space while the slider waits for the javascript to finish loading. Is there any way to display the first slide while waiting for the javascript to load? You can see the issue [here](https://www.kheopsinternational.com/).

**Comment by BenSpace48** [comment]
@lesliekirk - Have you tried to use `display: none;` on all slides except the first one, and then once initialised overwrite that with `display: block;` or whatever value works best for you.

You can also throw `height` in there if required.

**Comment by adampatterson** [comment]
@BenSpace48 that worked for me, Display none on all of them was causing some of the slides not to load properly with lazyloading.

**Comment by ChristianoBourguignon** [comment]
I managed to solve this problem with the help of some here in this comment, I hope it helps!

I used the following JS and CSS requirements

```
// CSS
<link rel = "stylesheet" type = "text / css" href = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick-theme.css" />

<link rel = "stylesheet" type = "text / css" href = "// cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

// JS
<script src = "https://code.jquery.com/jquery-1.12.0.min.js"> </script>

<script type = "text / javascript" src = "// cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"> </script>
```

And I made the following JS settings (in my case it was a banner, so 1 slide for everyone)

```
<script>
$ (document) .ready (function () {
    $ ('. carousel'). slick ({
infinite: true,
    points: truth,
arrows: false,
   autoplay: true,
    autoplaySpeed: 6000,
arrows: false,
  });
});
</script>
```

Now, in order not to "flash the sliders" and show more grandiose I put the following CSS.

> Note: I put a slick-slider class for all sliders, except the
> first!

```
.carousel.slick-initialized {
visibility: visible;
opacity: 1;
}

.carossel .slick-slider {
Show none;
}

.carossel .slick-slider: first child {
display: block; visibility: hidden;
}

.carousel.slick-initialized .slick-slider {
display: block; visibility: visible! important;
}
```

So, during loading the first slide will be visible, and the others will be hidden, just when they become active they will be in `display: block;`, so I solved my problem and I hope it helps more people too!

Attention, Christiano.

**Comment by adampatterson** [comment]
Thanks @ChristianoBourguignon I will give this a try later on!

**Comment by ateufel** [comment]
my version, if anyone needs it:
`
.slick-slider:not(.slick-initialized) .slick-slide:not(:first-of-type) {
	display: none;
}

.slick-slider:not(.slick-initialized) .slick-slide:first-of-type {
	visibility: hidden;
}
`

**Comment by Aldair05** [comment]
A mi me sirvio esto con less: 

`	.slick-carousel-home{
						visibility: hidden;
						opacity: 0;
						transition: opacity 0.3s;
					}
					.slick-carousel-home.slick-initialized{
						visibility: visible;
						opacity: 1;
						.slick-slide{
							display: block;
							visibility: visible !important;
						}
					}

					.slick-carousel-home {
						.slick-slide{
							display: none;
							&:first-child{
								display: block;
								visibility: hidden;
							}
						}
					}`

**Comment by graphicz** [comment]
Solution of @RedlingshoeferUndHofmann works a charm but I still have a little jump of the page content as the dots appear. I have tried display:block on ul.slick-dots and giving them a height to no avail.
I am afraid I do not understand where to place @sasanikolic90 's addition.
Please can anyone advise?
Thank you

**Comment by Jamoliddin610** [comment]
YOU NEED USE ANOTHER SLIDER AS SWIPER

**Comment by mrccariolato** [comment]
Hi Guys, let me cheer you up a bit, I think I found a solution to make this pretty.

Perhaps you noticed `slide` setting in slick settings documentation. Well that option let you decide which elements go inside slick-track element.

Let's consider my initial html:
```
<div class="wrapper">
                        <div class="type-list">
                            <div class="placeholders loading row">
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                            </div>
                            <div class="slide"></div>
                            <div class="slide"></div>
                            <div class="slide"></div>
                            <div class="slide"></div>
                        </div>
                    </div>
```

Set `slide` option to `.slide` will catch all `div.slide` elements and put them into `.slick-track` leaving outside unwanted elements. 

Resultant html:
```
<div class="wrapper">
                        <div class="type-list slick-slider slick-initialized">
                            <div class="placeholders loading row">
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                                <div class="col-md-6 col-lg-3"><div class="placeholder placeholder-wishlist"></div></div>
                            </div>
                            <div class="slick-list">
                                <div class="slick-track">
                                    <div class="slide"></div>
                                    <div class="slide"></div>
                                    <div class="slide"></div>
                                    <div class="slide"></div>
                                  </div>
                            </div>
                        </div>
                    </div>
```

This was you can play with CSS to show/hide placeholders (or loading gif) and slider.

```
.wrapper .slick-initialized .placeholders{
    display: none!important;
}
.wrapper .type-list .slide{
    display: none;
}
.wrapper .type-list.slick-initialized .slide{
    display: block;
}
```

**Comment by bcolflesh** [comment]
[RedlingshoeferUndHofmann](https://github.com/RedlingshoeferUndHofmann)

Thanks very much, 9 years later your code is the perfect answer for me.
