### ISSUE TITLE
Arrows behave as slides in responsive slider

### ISSUE THREAD

**Issue by janakadombawela** [kenwheeler/slick#1744]
Hi, I have added the slick carousel to twitter bootstrap site and I have an weird issue with it. In responsive mode it shows the arrows as slides. In responsive mode the slider goes all wrong and slides are duplicating and the arrows(they are customized as next and previous buttons) are shown as slides. When I remove the responsive parameters it works all right. I want to remove the arrows in small screen sizes. I have modified the arrow HTML via slick function call and edited the slick theme. I replaced them to original states but the problem is still there. But when I remove the responsive feature from the function call it works all right. Sadly my attempt to replicate it in jsfiddle is unsuccessful so I have opened a stackoverflow question with all relevant code and working demo.
LInk: http://stackoverflow.com/questions/32645386/slick-slider-arrows-behave-as-slides-in-resposnsive-mode
If you can help me with this issue that would be great. Thanks in advance.

Update: I'm using version 1.5.7 of slick slider. Replacing the version 1.5.7 JavaScript file with version 1.3.15 JavaScript file fixed the issue.

PS: The edited slick-theme.css file's code is at the bottom of the css section of the code snippet.
PS: Finally I managed to replicate the issue in jsfiddle! 
Link: http://jsfiddle.net/e8bfszc4/

**Comment by janakadombawela** [comment]
Update: I'm using version 1.5.7 of slick slider. Replacing the version 1.5.7 JavaScript file with version 1.3.15 JavaScript file fixed the issue.

**Comment by marcpt** [comment]
+1 I have the same issue

**Comment by janakadombawela** [comment]
Recent update 1.5.9 fixed the issue.

**Comment by ahmadalfy** [comment]
Confirmed, fixed in 1.5.9 http://jsfiddle.net/ahmad/e8bfszc4/2/
