### ISSUE TITLE
Slick need browser (or window) resize to show up

### ISSUE THREAD

**Issue by cazzoo** [kenwheeler/slick#1750]
Hello.
I have installed slick to my page that contains elements that hide or show on buttons, these elements that show up and hide up contains slick instances but, when showing an instance after clicking a button, the slider (slick) height is equal to 0.
To make the slider work, I need to resize window / browser. After that, the slider works as expected.

Any ideas?

**Comment by cazzoo** [comment]
Here is an example of my issue : http://jsfiddle.net/cazsan/sxuLmtk0/1/

You can play with buttons, change panel size to get it broken.
Using Chrome lastest

**Comment by cazzoo** [comment]
Ok, the only solution I Found is to trigger each time I change tab (click on left or right blue button) the following code : 
```
$('.slick-initialized').each(function() {
        $(this).slick('unslick');
    });
```

**Comment by cazzoo** [comment]
Or even smarter on slick activate : 
```
$('mySlickShow').parent().find('.slick-initialized').slick('unslick');
```

**Comment by simeydotme** [comment]
Please refer to: https://github.com/kenwheeler/slick#methods

```// Manually refresh positioning of slick
$('.your-element').slick('setPosition');```

:smile:
