### ISSUE TITLE
Prevent swipe events from propogating

### ISSUE THREAD

**Issue by adamj88** [kenwheeler/slick#1751]
The `swipeHandler` function does not stop the swipe event from propagating, which causes problems if you have swipe events on a parent element.

Can provide a test if needed.

**Comment by leggomuhgreggo** [comment]
Hey @adamj88 I'm going to close this [because there's no test case](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but if you want to whip one up me can reexamine. [Here's a fiddle you can fork](http://jsfiddle.net/simeydotme/fmo50w7n/). Thanks!
