### ISSUE TITLE
Navigation Arrows appear when needed?

### ISSUE THREAD

**Issue by takuhii** [kenwheeler/slick#1752]
Is it possible to only have the arrow navigation when it is required. I have some scenarios where I am using SLICK, but I only have three images in a carousel (due to templating), so don't need the arrows to display.

Any help would be greatly appreciated
Darren

**Comment by kenwheeler** [comment]
thats how it works now

**Comment by takuhii** [comment]
My version isn't doing that. Is there a specific switch I should be looking for, or is this default behaviour?

**Comment by kenwheeler** [comment]
do you have slidesToShow set to 3?

**Comment by takuhii** [comment]
Hi,
slidesToShow is set to 1

**Comment by kenwheeler** [comment]
well then you have 3 available sliding indexes so the arrows are valid

**Comment by takuhii** [comment]
My slideshows are configured to display 4 images, scrolling 1 at a time, LTR. Sometimes I have slideshows that only display 2 images, but the arrows also show up. Are you saying I may have misconfigured SLICK?

**Comment by takuhii** [comment]
I am something of a layman at this, any help would be appreciated

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because it's a support request. If you are still grappling with this you could try throwing this in a fiddle and commenting here--might be able to take a look. [Here's one to fork](http://jsfiddle.net/simeydotme/fmo50w7n/).
