### ISSUE TITLE
npm version needs update

### ISSUE THREAD

**Issue by julia-rose** [kenwheeler/slick#1753]
My team and I are using Slick 1.5.8 in our project via npm. We have been seeing some odd scrolling behavior in our carousels, and it's fixed when we manually use the latest slick.js version from Github. We were wondering if the updates could be published to npm so that we can use them while staying in line with our work process.

Here's a diff showing the current npm version of slick.js on the left, and the most up-to-date version of slick.js from Github on the right: https://www.diffchecker.com/4o0hridn

**Comment by chipcullen** [comment]
+1 :)

**Comment by Danieler** [comment]
+1 
http://glebbahmutov.com/blog/automatically-publish-to-npm/

**Comment by leggomuhgreggo** [comment]
This looks like its been fixed! Closing
