### ISSUE TITLE
Slick Slide Click Event Forcing Carousel to Scroll to Original Slide

### ISSUE THREAD

**Issue by jtulk** [kenwheeler/slick#1754]
Video demonstration of bug: https://vimeo.com/140009783
Live site with bug: http://wowinc.net/
Gist of Javascript configuration code: https://gist.github.com/jtulk/b2aba8b48e034b46f0e6

Somehow a click event in the slick slide is triggering some event that forces the entire carousel to scroll back to the first slide. I can't figure out what's triggering it (or how to interrupt it).

**Comment by leggomuhgreggo** [comment]
Can you replicate in a fiddle? [Here's a handy one for you to fork](http://jsfiddle.net/simeydotme/fmo50w7n/) if you'd like. I'm going to close this for the time being.
