### ISSUE TITLE
Lazy load and adaptive height issue

### ISSUE THREAD

**Issue by darksist** [kenwheeler/slick#1755]
When i am using lazy load and adaptive height options, slide item's adaptive height calculated as "0px". Script will recalculate after image load finish. Thank you :)

**Comment by mlorenzutti** [comment]
unfortunately i have the same issue :)

**Comment by rapito** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Hey, apologies that this issue has gone so long without any attention. Would any of you be willing to make a [fiddle to demo the issue](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)? Thanks!

**Comment by leggomuhgreggo** [comment]
Oh you know what there's this one #947 already, but the fiddle is kind of out of date.

**Comment by rapito** [comment]
@leggomuhgreggo In my case I fixed it using adaptive height + progressive lazyload.

**Comment by leggomuhgreggo** [comment]
@rapito sweet thanks for sharing the intel :+1:
