### ISSUE TITLE
When reaching end of carousel, slick doesn't cycle images 

### ISSUE THREAD

**Issue by Anruin** [kenwheeler/slick#1758]
Greetings, I've got issue with slider that goes beyond the main content (960px) by width.

Issue is that when I'm scrolling images, and reaching end, it shows only last and first one in the cycle, and doesn't show next images after first.

So I see only last and first image, and only after I scroll again, suddenly rest of images appear after first one.

Here is my setup:
```javascript
$slider.slick({
	infinite: true,
	variableWidth: true,
	arrows: true,
	prevArrow: null,
	draggable: false
});
```

I have tried to change slides to scroll, and slides to show, but on different screen sizes they lead to bad behavior, when it skips slides.

Here is the page with slider: http://mag.verstak.ru/index_en.html

Is there any solution for my case? Thanks.

**Comment by Watex** [comment]
+1 Having the same issue.

**Comment by leggomuhgreggo** [comment]
Hey I know its been a while without any attention to this issue, but my first thought was that it might have to do with the tab focus. If you whip up a fiddle I'd be interested to check it out, but in the mean time I'm going to close it. [Here's one to fork](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) if you're interested.

**Comment by yahyazini** [comment]
+1 having the same problem here
