### ISSUE TITLE
Extra container within carousel breaks it.

### ISSUE THREAD

**Issue by orvn** [kenwheeler/slick#1760]
I'm trying to insert an extra element to wrap around the carousel within the `<ul>` element. The reason for this is that I'd like to hide the overflow in that element and visually cut off the right side of the carousel.

Can this be accomplished with any settings? Nothing stood out to me.

I've posted more detailed information along with a screenshot of the desired effect here http://stackoverflow.com/questions/32730187/container-within-slider-breaks-slider-slick-js

**Comment by orvn** [comment]
I've also tried applying this to the parent element. See the gif below with how the overflow works at first, but then the entire element resizes to match the new parent width.

I guess this is a responsive design feature.. and I want to keep this carousel's great responsive functionality. I just want there to be a little bit of a hidden overflow on the right.
![sslick-resize](https://cloud.githubusercontent.com/assets/3689720/10230522/802f5312-684b-11e5-9131-74c94b99441b.gif)

**Comment by kenwheeler** [comment]
slidesToShow: 2.5?

**Comment by orvn** [comment]
That _almost_ works. But the displacement is from the opposite side (left instead of right).
And applying `margin-left:` to sub child doesn't seem to work well.

Any other settings that might help with this?
(thank you for the reply)

<img width="1049" alt="opposite" src="https://cloud.githubusercontent.com/assets/3689720/10233569/2f6f64aa-685d-11e5-8ea8-ae77779f091c.png">

**Comment by kenwheeler** [comment]
settings?

**Comment by orvn** [comment]
Current settings attached
      $('.slider').slick({
          // dots: true,
          // accessibility: true,
          autoplay: true,
          autoplaySpeed: 5000,
          adaptiveHeight: false,
          arrows: false,
          infinite: true,
          fade: true,
          cssEase: 'ease',
          speed: 750,
          slidesToShow: 1,
          slidesToScroll: 1
      });


      $('.cards-carousel').slick({
          // dots: true,
          // accessibility: true,
          autoplay: true,
          autoplaySpeed: 5000,
          adaptiveHeight: false,
          arrows: true,
          infinite: true,
          fade: false,
          cssEase: 'ease',
          speed: 750,
          slidesToShow: 2.5,
          slidesToScroll: 1,
          responsive: [
      {
        breakpoint: 1200,
        settings: {
          slidesToShow: 2.5,
          slidesToScroll: 1,
          infinite: true,
          dots: false
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2.5,
          slidesToScroll: 1,
        }
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 2.5,
          slidesToScroll: 1
        }
      }
    ]
      });
    
  });

**Comment by leggomuhgreggo** [comment]
Hey I know this issue has been dormant for a while, but if you're still interested feel free to circle back with a test case. Im going to close for the time being. Thanks.
