### ISSUE TITLE
AJAX Refreshed items braking the carousel

### ISSUE THREAD

**Issue by merianos** [kenwheeler/slick#1762]
Hello,

as mentioned here : http://stackoverflow.com/questions/32759673/slick-after-refresing-content-with-ajax-it-brakes the carousel it is braking after refresh the contents with AJAX.

To become more specific, I have create a carousel that the content is inserted wirh AJAX. The first time I load the content with AJAX the carousel works fine.

A few seconds later that I remove any item from the carousel and I reload the items via AJAX, the carousel totaly brakes, and I don't get any issue in my console.

Note that before I clear the items I run the :

`
$live_carousel.slick('unslick');
`

and after I append all the new items in the carousel container I re-initiate the carousel.

**Comment by leggomuhgreggo** [comment]
Hey I know this is super old, but looking at that stackoverflow code, I'm wondering if the problem could be solved using the `slickAdd` method.

I'm going to close this, assuming it might be out of date, but holler back if you want to look at reopening.
