### ISSUE TITLE
Added possibility to mark slide if slideCount is equal to slidesToShow!

### ISSUE THREAD

**Issue by andreb07** [kenwheeler/slick#1766]
Hello and first of all thank you for this plugin witch is great!

As i was developing a project, my navigation slider had exactly the same number of slides and the number of slidesToShowthat that I've determined.

I understand that in that occasion the slider show not slide, so in the slideHandler function you have this piece of code (line 2116):

if (_.slideCount <= _.options.slidesToShow) {
     return;
} 

This prevents the slider to slide because there are no more slides. That's OK but it is also preventing to mark the current slide. Despite the fact that the number of slides are smaller or equal, it should always mark the current slide with the "slick-current" class.

So, my 2 cents is to add this line in the code above:

if (_.slideCount <= _.options.slidesToShow) {
     _.setSlideClasses(index);
     return;
} 

This way the slide is being marked has current and the slider stays fixed.

I didn't do and extensive research on how would this affect ALL aspects of the plugin, and if this makes any conflict with some other feature, please think about adding this feature another way.

Thank you and regards
André bernardes

**Comment by cvince** [comment]
+1 Thanks André

**Comment by luxmedia** [comment]
Vielen Dank für Ihre Email!

Das Büro ist in der Zeit vom 16.01.2016 bis zum 23.01.2016 wegen Betriebsferien nicht besetzt. Anschließend wird Ihre Anfrage schnellstmöglich bearbeitet.

**Comment by leggomuhgreggo** [comment]
Hey @andreb07 thanks for the issue. [Check out the Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown); we ask that you provide a test case to demonstrate the issue your describing.

I think this is resolved by PR #2118 

Thanks

**Comment by luxmedia** [comment]
Lieber Kunde, vielen Dank für die Email!

Das Büro ist in der Zeit vom 05.09.2016 bis zum 16.09.2016 wegen Betriebsferien nicht besetzt. Anschließend wird Ihre Anfrage schnellstmöglich bearbeitet.
