### ISSUE TITLE
iOs Address Bar Causing Not needed reinit

### ISSUE THREAD

**Issue by IMBAmcDuffs** [kenwheeler/slick#1767]
Great slider by the way! 
I am however having a slight issue that I could use some assistance with as hacking on it just hasn't allowed me to fix the issue. Can you possibly let me know what the fix is or if this is a bug within slick?

http://skilaketahoe.staging.wpengine.com/ <-- the url to the example
If you open this up on iOs in Safari and slide the page down (scroll) then the address bar of course hides itself within the browser as it does. Then the slider reinitializes itself and there is nothing I can do to stop it. 
The client is giving me pressure to get this issue fixed as it should not rebuild the slider when the height of the page changes. 

Thanks in advance!

**Comment by leggomuhgreggo** [comment]
Hey sorry this hasn't gotten any attention. If it's still something you're trying to chase down, you can whip it up in a fiddle to investigate further. Closing for now. Thanks!
