### ISSUE TITLE
jQuery not recognized in version 1.5.7...$ not recognized as jQuery 1.11.x

### ISSUE THREAD

**Issue by jfouts1979** [kenwheeler/slick#1768]
Slick slider will not work with Slick version 1.5.7 and jQuery 1.11.0 or 1.11.3.

Worked with several developers to attempt to resolve issue unsuccessfully.  

Here is link to the JS FIddle...

https://jsfiddle.net/jfouts1979/duyn0q2e/12/

Images simply stack on top of one another and Slick is not initialized.  In Microsoft Edge and Google Chrome (2 browsers tested) same result occurred as in JS Fiddle....images simply stacked on top of one another with no JavaScript functionality.

It appears the JavaScript is broken.  The $ of jQuery was not recognized.  

After downgrading to a lower version of Slick, the issue was resolved.  If you need further information to address the issue please feel free to contact me.

**Comment by kenwheeler** [comment]
Your image tags aren't closed

**Comment by kenwheeler** [comment]
https://jsfiddle.net/a0ecq9jq/
