### ISSUE TITLE
is it possible to have carousel in a flex layout with slides & carousel changing heights dynamically.

### ISSUE THREAD

**Issue by vaidehichhajer** [kenwheeler/slick#1769]
Using window.resize events causes a lag while setting fixed heights.

**Comment by leggomuhgreggo** [comment]
I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but I will say that, if you're talking about display flexbox, it can get reallllllll tricky.
