### ISSUE TITLE
Reinit - duplicates buttons and dots after every call

### ISSUE THREAD

**Issue by RsD0p9BK** [kenwheeler/slick#1772]
Reinit - duplicates buttons and dots after every call.

![](http://snappyimages.nextwavesrl.netdna-cdn.com/img/21bfe47aa2ca905fd4fe074c3a58849f.png)

```
$("#slick01").slick('reinit');
```

**Comment by miscbits** [comment]
@kenwheeler is this issue being looked at?

**Comment by kenwheeler** [comment]
Under what conditions does this occur? Is destroy not being called?

**Comment by miscbits** [comment]
Dont call destroy and just reinit. If destory is supposed to be called before reinit, it seems that the function is named in an ambiguous way since reinitializing sounds like it should destroy the slider anyway. 

I would suggest checking to see if a slider is currently initialized so that the error doesn't persist.

**Comment by miscbits** [comment]
Hey so I don't know if Im missing it but I don't see reinit anywhere in documentation. I think when you call it, it feels like it should be refresh if it is initialized. 

I threw in a quick check in my version here. `if (_.$slider.hasClass('slick-initialized'))` and when that is true, it calls refresh and then returns nothing. correct me if that isn't the way the functionality is supposed to work.

**Comment by RsD0p9BK** [comment]
$('.single-item').slick('reinit');

**Comment by kenwheeler** [comment]
Reinit is an internal function that you are choosing to call. It is typically preceded by a destroy.

**Comment by RsD0p9BK** [comment]
Can I call destroy then init, for **refresh**? That seems ok.
```
$('.single-item').slick('destroy');
$('.single-item').slick('init');
```

**Comment by miscbits** [comment]
even if its an internal function just having the check can't hurt if people come into this glitch. 

@RsD0p9BK: you can call `$('.single-item').slick('refresh');` for refresh.

**Comment by miscbits** [comment]
What exactly is reinit supposed to do?

**Comment by kenwheeler** [comment]
It's used to reinitialize the slider after apply option sets in between breakpoints

**Comment by leggomuhgreggo** [comment]
Looks like this got settled. Closing.

**Comment by kohut-denis** [comment]
else Try this variant:
```
$('.your-slider').on('reInit', function(event, slick) {
   $('.your-slider').slick('slickSetOption', {arrows: false});
});
