### ISSUE TITLE
Animate each carousel item when sliding

### ISSUE THREAD

**Issue by baoagency** [kenwheeler/slick#1774]
This is more of a question than an issue.

When you click the left or right buttons OR if it autoplays OR if you touch swipe I'd like to play a animation on each carousel item. How do I do this?

**Comment by odie2** [comment]
This should be helpful - #1720

**Comment by jakech** [comment]
You can listen to [Events](https://github.com/kenwheeler/slick#events) if you use js for animation.
If you use CSS,  just use classes to do that, slick will add `slick-current slick-active` classes to the active slide.

**Comment by leggomuhgreggo** [comment]
Thanks @odie2 and @jakech! Closing
