### ISSUE TITLE
Slick Carousel Scroll

### ISSUE THREAD

**Issue by JosephSKh** [kenwheeler/slick#1777]
The slick carousel slides up or down if it's not within the view-port
![screenshot - 09282015 - 02 07 57 pm](https://cloud.githubusercontent.com/assets/5305408/10135134/17c588a4-65f4-11e5-8215-3453f6be2ab9.png)
becomes
![screenshot - 09282015 - 02 08 17 pm](https://cloud.githubusercontent.com/assets/5305408/10135138/1bc619a0-65f4-11e5-8f27-c8832dfa14d4.png)
the page just jumps up inorder to show the entire displayed div, I don't want that to happen, any solutions? Thank You,

**Comment by leggomuhgreggo** [comment]
If I'm understanding you correctly, it sounds like it has to do with the accessibility enhancement that added tab focus. #1537 talks about it more, but the quick fix is to turn accessibility off.
