### ISSUE TITLE
Feature Request: Thumbnails for paging

### ISSUE THREAD

**Issue by aykutcan** [kenwheeler/slick#1780]
We use slick slider pretty much everywhere that needs slider. its great.

i think there is a built-in feature must be should there.

Mini thumbnail image of slide for paging. Which i made it with

```
    customPaging: function(slick,index) {
		return '<button style="background:url('+$(slick.$slides[index]).data('thumb')+') center center;"></button>';
		}
```

**Comment by rafcontreras** [comment]
Hi @aykutcan Where do you ad this?

Cheers

**Comment by aykutcan** [comment]
Hi @rafcontreras 

i gave each slide a data-thumb attribute that contains thumbnail image of slide.

```
<div class="item" data-thumb="a-thumbnail.jpg">
    <a href="#">
        <h2> item1 </h2>
        <img src="a.jpg" alt="Image Description" />
    </a>
</div>
```

when initializing slick slider add this at in slick() function at as a parameter 
```
$('.sport-slider').slick({
		dots:true,
		autoplay:false,
		customPaging: function(slick,index) {
		return '<button style="background:url('+$(slick.$slides[index]).data('thumb')+') center center;"></button>';
		}
	});
```

**Comment by rafcontreras** [comment]
Awesome!

Thank you @aykutcan

**Comment by ahmadalfy** [comment]
I abused the `customPaging` and data attributes with the `fade` option to build tabs using slick few weeks ago :)

**Comment by virtual** [comment]
Just for another example, I have a basic jsfiddle using the centered slider and thumbnails at http://jsfiddle.net/Virtual/webyrb9d/

**Comment by leggomuhgreggo** [comment]
Hey [I think this is what the custom paging options was developed for](https://www.reddit.com/r/web_design/comments/21bcv0/slick_the_last_carousel_youll_ever_need/cgdg3e8)--donno if we need something more focused in the core. Thanks!
