### ISSUE TITLE
Horizontal Mouse Scrolling the gallery only goes in one direction.

### ISSUE THREAD

**Issue by trosage** [kenwheeler/slick#1783]
I'm trying to load a carousel that only uses basic horizontal mouse scrolling for navigation. The issue I'm running into is when you anchor to a photo somewhere in the middle of the gallery, only subsequent photos are accessible via horizontal scroll. I'm able to drag to previous photos but that's not really an ideal work around. **Here's a [demo](http://keena.wpengine.com/galleries/overview/) of the issue.**

*Click on any image other than the first and the carousel will appear with the issue I'm experiencing.*

I know I've kind of hacked Slick beyond it's intended design but I was hoping someone could help me wrestle this into submission.

**Comment by leggomuhgreggo** [comment]
Hey, might be that the demo you provided has changed since September, but I wasn't able to see anything obvious. I'm gonna close this, but if you're still trying to chase this issue down you can make a fiddle. [Here's one you can fork](http://jsfiddle.net/simeydotme/fmo50w7n/).
