### ISSUE TITLE
Autoplay setting doens't work with responsive breakpoint

### ISSUE THREAD

**Issue by geosenna** [kenwheeler/slick#1787]
I initialize my carousel with an autoplay set to true by default. Then in a breakpoint i put the autoplay to false. The behavior I expect is to stop the autoplay when user is on mobile version. Here my code:

```
elemBannerCarousel.slick({
    autoplay: true,
    responsive: [
      {
        breakpoint: 480,
        settings: {
          autoplay: false
        }
      }
    ]
 });
```

The thing is, with this code the autoplay is by default at false. The false argument in the breakpoint overide the true by default and the carousel never start its autoplay.

**Comment by ahmadalfy** [comment]
It works as expected on this fiddle: http://jsfiddle.net/t0h6jr5c/

By default it is set to true ... when resizing the window and make it smaller than the breakpoint it stop working. Resizing it to make it larger than the breakpoint makes it work again.

**Comment by rgfx** [comment]
I too have the same issue

**Comment by leggomuhgreggo** [comment]
Looks like it's working the fiddle @ahmadalfy made (cheers dude!), but if either of you want to whip up a test case to illustrate the problem you're encountering, we can reopen. [Here's a handy fiddle](http://jsfiddle.net/simeydotme/fmo50w7n/) to fork. Thanks!
