### ISSUE TITLE
Equal height slides

### ISSUE THREAD

**Issue by LMBE** [kenwheeler/slick#179]
Be nice to have the option to set smaller slides to the height of the tallest.

**Comment by phylaxis** [comment]
@akrawchyk I am attempting to use your solution, but get this error: 

`ReferenceError: Can't find variable: throttle`

Do you have a throttle function you created, but is missing from your sample here?

**Comment by akrawchyk** [comment]
@phylaxis I think you can remove the throttle part and use `$window.on('DOMContentLoaded load resize', equalizeHeights);` instead if you don't need it. Regardless, here is the throttle function:

```
// performant throttle implementation http://jsperf.com/throttle
function throttle(fn, frequency) {
  'use strict';

  frequency = frequency || 100;
  var timeout = false;

  return function() {
    if (timeout) {
      return;
    }

    timeout = setTimeout(function() {
      timeout = false;
    }, frequency);

    fn.apply(this, arguments);
  };
}``` 

Hope that helps :)

**Comment by bitlinguist** [comment]
@LMBE Its not table positioning, it is table display properties, and its not bad, its not bulking up markup its only presentation.

**Comment by lschneiderman** [comment]
I do it this way:

var stHeight = $('.slick-track').height();
$('.slick-slide').css('height',stHeight + 'px' );

**Comment by jdmagic21** [comment]
@lschneiderman +1

**Comment by nickfmc** [comment]
@lschneiderman +1 Thanks for that simple solution, one limitation unless inside a function checking for change in the .slick-track height is that is will only size your height on page load not on mobile screen rotation for example.

**Comment by ramonleenders** [comment]
As said, that will only work on page load. I've used the "setPosition" event from Slick slider here.

`$('.your-selector.').on('setPosition', function () {
    $(this).find('.slick-slide').height('auto');
    var slickTrack = $(this).find('.slick-track');
    var slickTrackHeight = $(slickTrack).height();
    $(this).find('.slick-slide').css('height', slickTrackHeight + 'px');
    $(window).trigger('resize');
});`

**Comment by mateuspaulino** [comment]
Thanks a lot @ramonleenders and @lschneiderman

**Comment by Jakobud** [comment]
This should be included in the core code as an option. `equalizeHeight: true/false` or something like that.

**Comment by JamesIves** [comment]
Completely agreed @Jakobud

**Comment by leggomuhgreggo** [comment]
I know foIks have mentioned this already, but here's how to get it done with flexbox:

```
.slick-track{
	display: flex;
	
	.slick-slide{
		display: flex;
		height: auto;
		align-items: center; //optional
		justify-content: center; //optional
	}
}
```

[pen](http://codepen.io/leggomuhgreggo/pen/mEmzGN?editors=1100)

Alternatively, the JS @ramonleenders wrote will do the trick.

**Comment by shaynestatzell** [comment]
Thanks @leggomuhgreggo additionally add `flex-direction: column;` to .slick-slide if slides contain multiple elements, this will stack them vertically.

**Comment by rabelBB** [comment]
Thanks @ramonleenders saved me lots of stress with that solution!

**Comment by kmax1940** [comment]
Hello, is there a solution for this yet?  
 I am trying to make all my slides adjust height as needed. 

Slides with more content are taller than the others when the window size is more narrow

I tried flexbox on slick-slide and slick-track but it does not work for me.

Any tips?


.slick-track{
    display: flex;
}
    .slick-slide{
        display: flex;
        height: auto;
        align-items: center; //optional
        justify-content: center; //optional
    }

**Comment by leggomuhgreggo** [comment]
fiddle?

**Comment by kmax1940** [comment]
Sorry, I could not get it to work in a fiddle.
Here is my test page though.
http://www.videolinktech.com/work/test/

If you make the window small and click to the red slide you see how much taller it is than the others.

I tried the following css with no luck

.slick-track{
    display: flex;
}

    .slick-slide{
      display: flex;
  }

  .slick-list {
    display: flex;
  }

**Comment by kmax1940** [comment]
Here is the fiddle I am working with.. just in case I get it to work.
https://jsfiddle.net/mkxd6gqy/

**Comment by kmax1940** [comment]
OK, I got the fiddle to work.... and guess what... all the slide divs are the same height!
BUT if you look at my test page... and make your window small...
You will see that the red div is much taller than the others

works on this fiddle
https://jsfiddle.net/mkxd6gqy/

but not on this page with the same files
http://www.videolinktech.com/work/test/

**Comment by ramonleenders** [comment]
Use my Javascript variant instead (posted 2 Apr), and drop the Flexbox code?

**Comment by kmax1940** [comment]
Thanks... would that javascript go in the html page where you hook up your jquery?
$(document).ready(function....    ?

**Comment by wking-io** [comment]
You can have the function reload on page resize using this function. (Only runs when resize stops so it is not pushing a ton of JS calls)

`var stHeight = $('.slick-track').height(),
	timeout = false, // holder for timeout id
	delay = 250; // delay after event is "complete" to run callback

function refreshSlickHeight() {
	$('.slick-slide').css('height', stHeight + 'px' );
}

// window.resize event listener
window.addEventListener('resize', function() {
        // clear the timeout
        clearTimeout(timeout);
        // start timing for event "completion"
        timeout = setTimeout(refreshSlickHeight, delay);
});`

**Comment by SunnyPuma** [comment]
front-end, finding job qq group: 365563094

**Comment by artursopelnik** [comment]
@ramonleenders if you use it with adaptive-height together
`
// adaptiveHeight enough if only one slide
            if (slickSlide.filter('.slick-active').length > 1) {
                slickSlide.css('height', 'auto').css('height', this.options.el.find('.slick-track').height() + 'px');
            }
`

**Comment by ramonleenders** [comment]
Would be nice if a JS solution will be provided within the plugin itself. That way we don't need to search for workarounds NOR write the CSS. Only a boolean in the config and done.

@artursopelnik: the code you provide is working or it isn't? Not sure if you are asking or just suggesting code here haha. And if it does work, it also still works when adaptiveHeight is set to false?

**Comment by giovannibr** [comment]
Cmon @kenwheeler , it could be done just adding:
`_.$slideTrack.height(_.$slideTrack.outerHeight());`
Inside your Slick.prototype.setDimensions function.
Once the parent (track) has a defined height, the children (slides) already have the property height to 100%, and it works like charm.
Maybe you can create a property "fixedHeight" that only works with "adaptativeHeight" false.

**Comment by drducmanh** [comment]
I use litle css to equal height.
"align-items:stretch" property apply to parent

.slick-track{
    display: flex;
     align-items: stretch; 
     justify-content: center;
    .slick-slide{
        height: auto;       
    }
}

readmore about flexbox here https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by pjatx** [comment]
@ramonleenders Thanks! Using a complex flexbox layout and the pure CSS solutions just blowup my slides.

**Comment by verybigelephants** [comment]
so will there be an option for this or no?

this is definitely a real word scenario that appears over and over

**Comment by LMBE** [comment]
Hi all, it's me, the [okay guy](https://github.com/kenwheeler/slick/issues/179#issuecomment-41771027) from 2014 and original poster.

After years of using this great plugin and seeing people revisit this post I thought I'd chime back in.

The reality is that Ken adding an equalize heights option to the plugin is an overhead that could be better integrated elsewhere in your code. Instead, setup a global function you can use umpteen times over on different modules and save yourselves some kb's. If you're using foundation use the data-equalize attributes, if you want something more custom try something [like this](https://github.com/mattbanks/jQuery.equalHeights).

After that add a little flexbox spice to your content to vertically align anything you might have inside your banner and the jobs a gooden.

Keep up the great work @kenwheeler I've used this hundreds of times now and it's never let me down

**Comment by UnionDesign** [comment]
Does this not work?

`	.slick-track {
		display: flex;
		align-items: center;
	}
`

**Comment by raffi-ecomz** [comment]
i'm using adaptive height and have a bootstrap collapse element inside a slide.
when the element expands the slick isn't changing its height to the new one so only a part of the element is visible.
how can i make the whole element be visible?

**Comment by Preen** [comment]
I used https://www.npmjs.com/package/jquery-match-height and solved it with the help of @ramonleenders code:

```  
$(el).on('setPosition', function () {
    $(el).find('.slick-slide').matchHeight();
})
```

**Comment by karbecker** [comment]
Hi @Preen could you help me out where to insert https://www.npmjs.com/package/jquery-match-height and @ramonleenders code? I’m trying to archive equal height for all slides using SlickSlider in Wordpress (https://de.wordpress.org/plugins/slick-slider/).

Thanks for your help!

**Comment by flewid-cd** [comment]
@karbecker You need to write the above code but I guess that if you use a plugin it might have its own actions on when/where to trigger and initialize slick-slider. So I would ditch that plugin and just use slick manually with jquery match height.

**Comment by karbecker** [comment]
Thanks @flewid-cd! That’s true, the plugin acts as a wrapper to load slick-slider. Will try to use it manually.

**Comment by jschaefer-workmatrix** [comment]
If you are using **griddy** slick slider (I am using a responsive setup w/ variable grids calculated by slide count via `slidesPerRow`) the following may help:

```
$.fn.equalHeightSlickSlider = function() {
	var
		$slider = $(this),
		$slides = $('.slick-slide', $slider),
		$slideitems = $('> div', $slides),
		slideCount = $slides.first().find('> div').length,
		slideHeight = 0
	;

	console.log(slideHeight);

	$slides.each(function(){
		slideHeight = Math.max($(this).outerHeight(), slideHeight); 
		slideCount = Math.max(slideCount, $(this).children().length);
	});

	$slideitems.height(slideHeight / slideCount);		

	return $(this);
}

var $slider = $('.slick-slider');

var equalizeSliderHeights = function(){

  var
  frequency = 250,
  	timeout = false
  	;

  return function() {
    if (timeout) {
      return;
    }

    timeout = setTimeout(function() {
      timeout = false;
    }, frequency);

    $slider.equalHeightSlickSlider();
  };
};

$(window).on('DOMContentLoaded load resize', equalizeSliderHeights());	
```

Inspired by @akrawchyk (thanks).

Can also by found here: https://gist.github.com/jschaefer-workmatrix/346ec9f1c6fae6e12408b060a5ed0eb1

**Comment by JurajVajda** [comment]
The flexbox solution doesn't work in Edge, also some vanilla JS solution would be nice - if still anyone knows what that is :)

**Comment by mikemfleming** [comment]
@JurajVajda this is the vanilla solution I'm currently using.

```
    var productCarousel = document.getElementById('productCarousel')
    var productCarouselHeight = productCarousel.offsetHeight
    var productCarouselSlides = Array.prototype.slice.call(
        document.getElementsByClassName('productCarousel-slide')
    )

    productCarouselSlides.forEach(makeEqualHeight)

    function makeEqualHeight (element) {
        element.style.height = `${productCarouselHeight/2}px`
    }
```

**Comment by mikemfleming** [comment]
@JurajVajda here is the vanilla solution I am using:

```
    var productCarousel = document.getElementById('productCarousel')
    var productCarouselHeight = productCarousel.offsetHeight
    var productCarouselSlides = Array.prototype.slice.call(
        document.getElementsByClassName('productCarousel-slide')
    )

    productCarouselSlides.forEach(makeEqualHeight)

    function makeEqualHeight (element) {
        element.style.height = `${productCarouselHeight/2}px` // the carousel seems to resize asynchronously
    }
```

**Comment by JurajVajda** [comment]
Thanks..ended up using Es6 Js class for it in the end.

**Comment by aronmoshe-m** [comment]
> I used https://www.npmjs.com/package/jquery-match-height and solved it with the help of @ramonleenders code:
> 
> ```
> $(el).on('setPosition', function () {
>     $(el).find('.slick-slide').matchHeight();
> })
> ```

Thanks, @Preen. This was exactly what I needed.

**Comment by abstractpenguin** [comment]
Updating @leggomuhgreggo's code with `.slick-initialized` got it to work for me:

> ```
> .slick-initialized .slick-track{
>     display: flex;
> 
>     .slick-slide {
>         display: flex;
>         height: auto;
>         align-items: center; //optional
>         justify-content: center; //optional
>     }
> }
> ```
> 
> [pen](http://codepen.io/leggomuhgreggo/pen/mEmzGN?editors=1100)

**Comment by yyanmak** [comment]
.slick-initialized .slick-track{
    display: flex;

    .slick-slide {
        display: flex;
        height: auto;
        align-items: center; //optional
        justify-content: center; //optional
    }
}

Somehow this one not working for me, after I added in, the height is equal now, but the width become not 100%

**Comment by peterlockhart** [comment]
`
.slick-track{
  display: flex !important;
}

.slick-slide {
  height: inherit !important;
}
`
This did the trick for me.

**Comment by andrewhawkes** [comment]
I've worked around this loads of times with Flexbox but I've run into an issue today again and my usual fix didn't work. 

This SCSS ended up being enough for me:

```
  .slick-track{
    display: flex;

    .slick-slide {
      height: auto;

      > div {
        height: 100%;
      }

    }
  }
```

**Comment by csakiistvan** [comment]
@andrewhawkes thank you, it is works.

**Comment by ff-marcos** [comment]
@andrewhawkes Thank you!

**Comment by smotzart** [comment]
`$('.your-slider').on('setPosition', function (event, slick) {
$(slick.$slides).height('auto').css('height', $(slick.$slideTrack).height() + 'px');
});`

**Comment by jinch** [comment]
@leggomuhgreggo or @abstractpenguin - Do you know the CSS version of this? I am not setup to adjust SCSS and the other solution do not seem to work for me? When I apply felxbox rule directly my images scale gets wonky.

`.slick-initialized .slick-track{
    display: flex;

    .slick-slide {
        display: flex;
        height: auto;
        align-items: center; //optional
        justify-content: center; //optional
    }
}`

**Comment by Pawelek55** [comment]
Recommend: 
.slick-initialized .slick-slide {
    display: block;
    max-height: 300px;
}

.slide_elem .img_cont {
    position: relative;
    height: 230px;
    margin-bottom: 14px;
    background: #f5f5f5;
    display: flex;
    border: 1px solid #000;
}

**Comment by cjpdee** [comment]
This was such a journey

**Comment by ouw-devs** [comment]
> 
> 
> This was such a journey

I hate this script so much. it's on every single ancient, poorly coded abomination of a website that I have dealt with lately.

seeing this thread rekindled my hatred

**Comment by thanh90** [comment]
in my case
1. set adaptiveHeight to false
2. .slick-slide div {
          height: 100%;
     }
3. add height: 100% for children items inside Slider
It works even if you have background for the children items

**Comment by verybigelephants** [comment]
> > This was such a journey
> 
> I hate this script so much. it's on every single ancient, poorly coded abomination of a website that I have dealt with lately.
> 
> seeing this thread rekindled my hatred

i don't know if you've ever implemented something with other slider libraries, but believe me, this is one of the better ones. (although this not being as a configurable option is really a bad decision)

**Comment by timcutting-gfm** [comment]
> I know foIks have mentioned this already, but here's how to get it done with flexbox:
> 
> ```
> .slick-track{
>     display: flex;
> 
>     .slick-slide{
>         display: flex;
>         height: auto;
>         align-items: center; //optional
>         justify-content: center; //optional
>     }
> }
> ```
> 
> [pen](http://codepen.io/leggomuhgreggo/pen/mEmzGN?editors=1100)
> 
> Alternatively, the JS @ramonleenders [wrote](https://github.com/kenwheeler/slick/issues/179#issuecomment-204768021) will do the trick.
> 
> Hope this is helpful

Great solution, thanks for posting!  For some, a small change to `align-items` might be a better fit.

```
 .slick-track{
     display: flex;
 
     .slick-slide{
         display: flex;
         height: auto;
         align-items: stretch;
         justify-content: center; //optional
     }
 }
 ```

**Comment by MaxChabanenko** [comment]
Have you noticed, that there is an additional <div> in slide that breaks the equal height workarounds?
For example:
https://github.com/kenwheeler/slick/issues/3207
https://github.com/akiran/react-slick/pull/1848
https://github.com/kenwheeler/slick/issues/3110

For this same height issue for me helped this css piece of code:

.slick-slide div:not([class]):not([id]) {
    height: 100%;
}

**Comment by verybigelephants** [comment]
lol i love how this issue gets ressurected once in a while for 10 years straight

amazing how we now have an ai that is about to take on our programming job positions, but there is no way to set equal height slides in slick.js

**Comment by Navjeet** [comment]
Use below css to have same height images

.abc-wrapper .slick-initialized .slick-slide { display: flex; }

.abc-wrapper .slick-slide { height: 310px; align-items: center; justify-content: center; }

.abc-wrapper  .slick-list { height: unset !important; }

Thank you

**Comment by Ahmaadkhader** [comment]
If you are using a vertical slider, this library may be useful: https://github.com/liabru/jquery-match-height . Note: Ensure to set `byRow: false` in the options.

**Comment by hasib-devs** [comment]
> I know foIks have mentioned this already, but here's how to get it done with flexbox:
> 
> ```
> .slick-track{
>     display: flex;
> 
>     .slick-slide{
>         display: flex;
>         height: auto;
>         align-items: center; //optional
>         justify-content: center; //optional
>     }
> }
> ```
> 
> [pen](http://codepen.io/leggomuhgreggo/pen/mEmzGN?editors=1100)
> 
> Alternatively, the JS @ramonleenders [wrote](https://github.com/kenwheeler/slick/issues/179#issuecomment-204768021) will do the trick.
> 
> Hope this is helpful

It will not work if you have more then 1 row

**Comment by Qasim240** [comment]
Thanks me later...
 just replace your parent class name with **networksSlider**


function equalizeHeights() {
  const cards = document.querySelectorAll('.pcos-card');
  let maxHeight = 0;

  // Reset heights
  cards.forEach(card => {
    card.style.height = 'auto';
  });

  // Find max height
  cards.forEach(card => {
    const height = card.offsetHeight;
    if (height > maxHeight) {
      maxHeight = height;
    }
  });

  // Apply max height
  cards.forEach(card => {
    card.style.height = maxHeight + 'px';
  });
}

// Call the function after the slider is initialized
$(document).ready(function () {
  $('.networksSlider').on('setPosition', function () {
    equalizeHeights();
  });
});

**Comment by Yoast-modern-day** [comment]
> [@phylaxis](https://github.com/phylaxis) I think you can remove the throttle part and use `$window.on('DOMContentLoaded load resize', equalizeHeights);` instead if you don't need it. Regardless, here is the throttle function:
> 
> ```
> // performant throttle implementation http://jsperf.com/throttle
> function throttle(fn, frequency) {
>   'use strict';
> 
>   frequency = frequency || 100;
>   var timeout = false;
> 
>   return function() {
>     if (timeout) {
>       return;
>     }
> 
>     timeout = setTimeout(function() {
>       timeout = false;
>     }, frequency);
> 
>     fn.apply(this, arguments);
>   };
> }
> ```
> 
> Hope that helps :)





https://lnkr.fun/8a225fe
