### ISSUE TITLE
Disable select/ focus (annoying blue lines) 

### ISSUE THREAD

**Issue by dnicloud** [kenwheeler/slick#1796]
Can you somehow get rid of these blue lines? I tried on the div

```css
-webkit-user-select: none;
       -moz-user-select: -moz-none;
        -ms-user-select: none;
            user-select: none;
```
But that seems not to work. Thanks!
<img width="670" alt="screenshot 2015-10-05 07 21 57" src="https://cloud.githubusercontent.com/assets/8103258/10273532/3f0a5d20-6b32-11e5-87fa-2b6ae9f7dc96.png">

**Comment by geosenna** [comment]
try to add     
```css
outline: 0;
```

on focus state

**Comment by dnicloud** [comment]
Wow. So easy fix. I cannot believe, I didn't figure this out. Thanks !

**Comment by mcashley** [comment]
Answered support question... Closing

**Comment by joachimdoerr** [comment]
``` scss
div.slick-slide {
    *:focus,
    &:focus {
      outline: 0;
    }
}
```
