### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by ivolnov** [kenwheeler/slick#1800]
Hi!

I've been testing my web app with those google chrome iphone ipad and etc simulators and faced the issue of JQuery warning messages "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted". When you scroll the slider horizontally it prevents the vertical touch scroll and the issue doesn't appear. When you touch-scroll slider vertically (with the whole page) and then move left or right in the same motion you can see those messages in the log. 
The root cause is this line that tries to prevent the default event (its line 2370 from 1.5.7 version of slick.js)

 if (event.originalEvent !== undefined && _.touchObject.swipeLength > 4) {
            event.preventDefault();
 }

By commenting it out the issue doen't reproduce.

Thx.

**Comment by leggomuhgreggo** [comment]
Hey I'm gonna close this because there's [no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). [Here's a fiddle for you to fork](http://jsfiddle.net/simeydotme/fmo50w7n/) if you'd like to pursue it further. Thanks @ivolnov.

**Comment by zhumanasyrov** [comment]
if horizontally scroll write this overflow-scroll="false" , vertically  overflow-scroll="true"
this is work for me...

**Comment by ravo10** [comment]
Hello. Add `event.cancelable` to your logic. Try this:

`if (event.originalEvent !== undefined && _.touchObject.swipeLength > 4 && event.cancelable) {
   event.preventDefault();
}`

**Comment by saimali9** [comment]
@ravo10  where do we put 
if (event.originalEvent !== undefined && _.touchObject.swipeLength > 4 && event.cancelable) { event.preventDefault(); }

**Comment by ravo10** [comment]
You need to put it at the very top before any other code is executed, so that you are sure that `event.preventDefault()` is fired before it is to late. fredag, 22 juni 2018, 01:53p.m. +02:00 from saimali9  notifications@github.com :

**Comment by vitorpegas95** [comment]
> if horizontally scroll write this overflow-scroll="false" , vertically overflow-scroll="true"
> this is work for me...

Where do you put this?
