### ISSUE TITLE
 prevArrow, nextArrow behave differently when responsive

### ISSUE THREAD

**Issue by 756gzdz5** [kenwheeler/slick#1801]
If a breakpoint is reached, prevArrow and nextArrow behave differently in comparison to non-responsive use.
I have multiple sliders on one page, which all have the same classes and are all initialized alike. So, if I press one arbitrary nextArrow on that page, all sliders change to the next slide. But if the window is so small, that a breakpoint is hit, only the last slider on the page changes to the next slide.

**Comment by ahmadalfy** [comment]
Can you replicate in a fiddle?

**Comment by 756gzdz5** [comment]
Here you go: http://jsfiddle.net/o9c6r4zy/

**Comment by ahmadalfy** [comment]
Ohh ... I tried adding more sliders, it seems that after the breakpoint the arrows works only on the last slider. Also, when adding `prevArrow` and `nextArrow` to the settings inside the breakpoint it doesn't work neither.

**Comment by leggomuhgreggo** [comment]
I know this is many months later now, but I forked your example and updated to the master now the behavior is consistent between breakpoints, but only applies to the last slider by the same class. Probably would be better if it worked with both instances, but easy work around is to just distinguish them.
