### ISSUE TITLE
Slick Slider issue on IE 11 with Break points

### ISSUE THREAD

**Issue by Sanctuarymg** [kenwheeler/slick#1804]
Hi. I am using slick slider v 1.5.7 and this is working well on all browsers but on IE. This is how it looks on Google Chrome. http://screencast.com/t/fTITxR6sFZ. On IE 11 it seems to ignore the JS and never add the divs that create the slider. This is how it looks on IE 11- http://screencast.com/t/WI7VHkGq2

The url to the page in question is http://www.areatrend.com/blog/2015/09/01/how-to-match-accessories-to-your-outfit

The script is the following: Jsfiddle: https://jsfiddle.net/wf7fmhb8/

**Comment by ahmadalfy** [comment]
There is a JavaScript error on your page preventing slick from being initialized relater do a jQuery plugin you are using called `popover`. I am not sure why it is hapenning only on IE but I suggest you disable that `popover` plugin and see if slick works.

**Comment by leggomuhgreggo** [comment]
Hey looks like this was an issue with the popover js with IE and not the slider; so, I'm going to close this issue, but feel free to holler back if it proves otherwise. Thanks.
