### ISSUE TITLE
Responsive / browser resize issue

### ISSUE THREAD

**Issue by rorysmorris** [kenwheeler/slick#1808]
I have mocked up this problem/bug into a jsfiddle so you can see what I mean.

First, resize the window so the arrows/dots navigation appears. Use them, so you are no longer on "slide 1".  Now, resize the window back up so the arrows/dots navigation disappears. The slider should reset itself back to slide 1, but it doesn't.

Example: http://jsfiddle.net/7vh2j6k8/
Video of problem: https://www.youtube.com/watch?v=aBOoN6efcyc

**Comment by kitestudio** [comment]
+1

**Comment by bagusflyer** [comment]
Same question here.

**Comment by cheehung89** [comment]
same question here but no one able to answer...

**Comment by rorysmorris** [comment]
Would be good to get a fix for this. 

Cheers

**Comment by mihaiari** [comment]
This  is how I managed to fix it, hope it helps
````javascript
const $slider = $('.your-element'); // my slider

$(window).resize(function() {
  clearTimeout(timeout);
  timeout = setTimeout(() => {
    $slider.slick('slickGoTo', 0);
  }, 100);
});
````

**Comment by subtirelumihail** [comment]
This  is how I managed to fix it, hope it helps
````javascript
const $slider = $('.your-element'); // my slider

$(window).resize(function() {
  clearTimeout(timeout);
  timeout = setTimeout(() => {
    $slider.slick('slickGoTo', 0);
  }, 100);
});
````

**Comment by cheehung89** [comment]
@subtirelumihail  can i know where should i put this code? just direct copy the same code like your posted? or i need add function myself?

**Comment by subtirelumihail** [comment]
@cheehung89 just copy/paste the code after you initialise your carousel and change `.your-element` with your slick carousel  class or id

**Comment by subtirelumihail** [comment]
This is the solution in es5
````javascript
var $slider = $('.your-element'); // my slider

$(window).resize(function() {
  clearTimeout(timeout);
  timeout = setTimeout(function() {
    $slider.slick('slickGoTo', 0);
  }, 100);
});
````

**Comment by cheehung89** [comment]
ok, but some error occur after i put in the code. When i resize from bigger screen to smaller screen, the arrow didnt come out. Example i have 5 slide, when on desktop view, i can show all slide and no arrow occur because max can fit 6 slide, when i resize to smaller screen, arrow should occur because max slide for smaller screen is 3 slide but then the arrow didnt appear.

**Comment by dangelojesse** [comment]
Here is how I decided to go about fixing the issue.

$(element).on('setPosition', function(event, slick, currentSlide, nextSlide) {
  var slidesShown = $(element).slick('slickGetOption', 'slidesToShow');
  var numberOfSlides = $(element).find('.slick-slide').length;

  if (slidesShown === numberOfSlides) {
    $(element).find('.slick-track').css('transform', 'translate3d(0px, 0px, 0px)');
  }
});

**Comment by jnachtigall** [comment]
I simply _destroy_ and _recreate_ the slick gallery as a workaround for this bug:
```
$window.resizeDimension('width',
  _.debounce(function() {
    $gallery.slick('unslick');
    $gallery.slick({
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 3,
      arrows: false,
      dots: true,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 767,
          settings: 'unslick'
        }
      ]
    });      
  }, 300)
);
`

**Comment by simeydotme** [comment]
Fixed on Master:
http://jsfiddle.net/simeydotme/w67erjrk/

https://github.com/kenwheeler/slick/pull/2068 <-- commit that fixes.

**Comment by gumennii** [comment]
Thank you for fixing this
