### ISSUE TITLE
reInit don't work properly when infinite is set to true

### ISSUE THREAD

**Issue by evromalarkey** [kenwheeler/slick#1809]
When I reInit slider which has infinite is set to true, on reInit it will move the slider on previous slide, not on the current one.

http://jsfiddle.net/fmo50w7n/95/

**Comment by leggomuhgreggo** [comment]
Ohhh you know what? I don't think `reinit` is even a supported method. You'll see that it's not in the docs as a method, but rather an event. It's used internally in the library for certain functions, always following another undocumented function called `unload` and some contextual logic. I think if you call `unload` first on your click function it does what you need. Hope that helps
