### ISSUE TITLE
Way to set attribute on each slide to control direction?

### ISSUE THREAD

**Issue by freonirons409** [kenwheeler/slick#1812]
I have a client who wants to be able to make the slides slide in from different directions (i.e. first slide in from left, second in from right, and so forth).  Is this possible with the current settings or via a callback on the slide to switch the rtl property?

**Comment by elamprator** [comment]
you can do that by Css3 Animations Simply 
here in that pen http://codepen.io/EngCode/full/PPOWwB/
Change The animation time and well give you what you want

 ---------------------- This CSS Will Give You What You Want -------------------
.Modern-Slider .item:nth-child(odd){animation:slideOutRight 0.5s both;}
.Modern-Slider .item.slick-active:nth-child(odd){animation:slideInLeft 1s both;}
.Modern-Slider .item:nth-child(even){animation:slideOutLeft 0.5s both;}
.Modern-Slider .item.slick-active:nth-child(even){ animation:slideInRight 1s both;}

**Comment by leggomuhgreggo** [comment]
Very nice @elamprator! Closing!

**Comment by simeydotme** [comment]
Yeah,  very nice. Let me tidy up the code-style for future viewers :)
