### ISSUE TITLE
Slider Items at 100% width stacked below each other, rather than sliding inline. IE8

### ISSUE THREAD

**Issue by es88** [kenwheeler/slick#1813]
Hi,

I have used Slick Slider on several sites now and currently am struggling with a problem in IE8.
The slider works perfectly in all other browsers and instances, but on IE8 the slider items are shown below each other rather than inline within the wrapper-div as it is supposed to be. 

Is this a common issue? 
Any suggestions? 

![dashboard](https://cloud.githubusercontent.com/assets/7325049/10458760/52d43180-71c4-11e5-8ee3-c6027067f717.png)

Logos should sit in the same row as "Sponsors"

Thanks in advance.

**Comment by GonzaloCalandria** [comment]
Can you post some HTML and CSS of your code?

**Comment by es88** [comment]
Hi Gonzalo.

Here a Pen with my code http://codepen.io/anon/pen/EVwVXw

Thanks

**Comment by leggomuhgreggo** [comment]
Dang, this is a bit of a catch22 because neither CodePen or JSFiddle support IE8 anymore, so getting a solid demo for ie8 is hard. If you whip up a workable test case it's possible that this issue might get some attention, but in the mean time I'm going to close it. Thanks @es88.
