### ISSUE TITLE
Not working AT ALL on ipad?

### ISSUE THREAD

**Issue by nathanhornby** [kenwheeler/slick#1814]
I've just encountered an issue I haven't seen before when using this plugin, hoping someone can steer me in the right direction.

Basically the plugin doesn't seem to be working at all on ipad (simulator and physical ipad 2) in a build I'm working on.

The click events revert to standard anchor links (so just refresh the page) and all of the content stacks. It's as if the plugin hasn't loaded at all.

Works fine on other devices…

Anyone seen this issue before? I appreciate this is unlikely an issue with the plugin itself, but other than intentionally stopping it from loading on this device (which would require a concerted effort) I can't think of what might cause this issue.

**Comment by ahmadalfy** [comment]
What do you mean it doesn't work? Does it initialize or not? Did you try to debug and check the console for potential JavaScript errors? Did you try the examples on the demo?

**Comment by nathanhornby** [comment]
> Did you try to debug and check the console for potential JavaScript errors?

If you can show me where the console is on an iPad I'd gladly check :)

Actually this is looking like a more general javascript issue, I've just spotted another related bug - unusual issue but definitely not isolated to slick so closing.

**Comment by nathanhornby** [comment]
For the sake of closure it turned out there was a trivial typo in my Javascript that for some reason only Safari cared about (it transpired that it was an issue on desktop as well as mobile devices). All sorted. :+1:

**Comment by ahmadalfy** [comment]
Good! You can debug Safari on iPad and iPhone by enabling remote debugging. Check this out http://moduscreate.com/enable-remote-web-inspector-in-ios-6/

**Comment by nathanhornby** [comment]
Ah cheers, good to know!
