### ISSUE TITLE
Slider with thumbnail slider

### ISSUE THREAD

**Issue by DezTheme** [kenwheeler/slick#1818]
I Love Slick! Can I use Slick like this??
http://flexslider.woothemes.com/thumbnail-slider.html

**Comment by SRTM** [comment]
Looks very similar to the "Slider Syncing" Example:
http://kenwheeler.github.io/slick/

Just remove the center mode option, and set dots to false.

**Comment by mcashley** [comment]
This issue is getting closed as it looks like an answered support question.
For future support please read:
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#support
