### ISSUE TITLE
slick populating next items only when carousel end is visible

### ISSUE THREAD

**Issue by aaronharding** [kenwheeler/slick#1819]
Here's a visual demonstration: http://webm.host/803f5/

I'm running jquery 2.1.4, and slick 1.5.7. And as you may see from 0:10 in the above video, what is happening is that I get to the end of the carousel, I can continue to click forward until almost all the items have disappeared, and then slick repopulates itself. What I hope to see is that slick will populate the next items before this happens so I get the 'infinite' effect.

I've tried changing `slidesToShow` but that doesn't seem to have any effect. My settings at the moment are:

```
var slickProps = {
	dots: false,
	infinite: true,
	slidesToShow: 1,
	speed: 350,
	variableWidth: true,
	autoplaySpeed: 2000,
	autoplay: true
};
```

Is there something I am missing?

**Comment by elamprator** [comment]
its maybe some css compatibility
here is slick options for infinite carousel 

--------------------  jQuery Slick Options  -------------------
$(".SlickCarousel").slick({
    rtl:false, // If RTL Make it true & .slick-slide{float:right;}
    autoplay:true, 
    autoplaySpeed:5000, //  Slide Delay
    speed:800, // Transition Speed
    slidesToShow:4, // Number Of Carousel
    slidesToScroll:1, // Slide To Move 
    pauseOnHover:false,
    easing:"linear",
    responsive:[
      {breakpoint:801,settings:{
        slidesToShow:3, // Number Of Carousel Tablet
      }},
      {breakpoint:641,settings:{
        slidesToShow:3, // Number Of Carousel iPhone
      }},
      {breakpoint:481,settings:{
        slidesToShow:1, // Number Of Carousel // Number Of Carousel Smart Phone
      }},
    ],
})

--------------------  Slick Css Ruls  -------------------
.slick-slider{position:relative;display:block;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-touch-callout:none;-khtml-user-select:none;-ms-touch-action:pan-y;touch-action:pan-y;-webkit-tap-highlight-color:transparent}
.slick-list{position:relative;display:block;overflow:hidden;margin:0;padding:0}
.slick-list:focus{outline:none}.slick-list.dragging{cursor:hand}
.slick-slider .slick-track,.slick-slider .slick-list{-webkit-transform:translate3d(0,0,0);-ms-transform:translate3d(0,0,0);transform:translate3d(0,0,0)}
.slick-track{position:relative;top:0;left:0;display:block}
.slick-track:before,.slick-track:after{display:table;content:''}.slick-track:after{clear:both}
.slick-loading .slick-track{visibility:hidden}
.slick-slide{display:none;float:left /* If RTL Make This Right */ ;height:100%;min-height:1px}
.slick-slide.dragging img{pointer-events:none}
.slick-initialized .slick-slide{display:block}
.slick-loading .slick-slide{visibility:hidden}
.slick-vertical .slick-slide{display:block;height:auto;border:1px solid transparent}

--------------------  Carousel HTML  -------------------

  <div class="SlickCarousel">
    
    <div class="GridBlock">
      <div class="Content">
       content or images
      </div>
    </div>
    
  </div>
  

--------------------  Custom CSS Grid Ruls  -------------------
.SlickCarousel{margin:0 -7.5px;}
.SlickCarousel .GridBlock{padding:0 7.5px;float:left /* RTL = Right */ }

.SlickCarousel = .slick-slider
.GridBlock = .slick-slide


see it here in  live action 
http://codepen.io/EngCode/pen/Vvppdy?editors=100

**Comment by aaronharding** [comment]
Yes all my css is included. Here, my new settings are:

```
var slickProps = {
	dots: false,
	infinite: true,
	slidesToShow: 6,
	speed: 350,
	autoplaySpeed: 2000,
	autoplay: true,
	slidesToScroll: 3
};
```

and this is the new video: http://webm.host/e2c82/ with more items so it's clearer to see what's happening.

**Comment by elamprator** [comment]
remove the include css and try commented css
or jsfiddle your code i want to see it live

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required) from OP, and it's kind of a support request but if you still feel like it's an actual bug you can whip it up in a fiddle. [Here's a boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/) for you to fork. For implementation help stackoverflow is a safer bet. Thanks @aaronharding and @elamprator
