### ISSUE TITLE
How to adjust slidesToShow by slide

### ISSUE THREAD

**Issue by cheekygit** [kenwheeler/slick#1821]
My first slide is panoramic and I want to show it at full width (slidesToShow = 1) while showing two slides at once for all subsequent slides (slidesToShow = 2).

I cannot figure out how to do this with the available options and since it says slick is the last slider I'll ever need, I am filing an issue ;)

**Comment by ahmadalfy** [comment]
Without hacking slick, I think this can be achieved by creating a wrapper for the 2 slides that you want to show as one ... like

```
<div class="slider">
  <div class="slide">Slide content goes here</div>
  <div class="slide">
    <div class="internal-slide">Slide content goes here</div>
    <div class="internal-slide">Slide content goes here</div>
  </div>
  .....
</div>
```

You can even add the wrappers automatically by using the before initalization event using jQuery. Not the best way but this is what's available now :)

**Comment by cheekygit** [comment]
Oh, that's very clever! Your solution works nicely on wide viewports. However, on smartphones I want to show only one slide at a time in all cases. That's something I already had working using the responsive parameter in slick. This is of course broken now that I am using div wrappers for slides. My idea now is to use visibility classes on the wrappers depending on break points or is there perhaps a more elegant way using slick/jquery?

**Comment by ahmadalfy** [comment]
wow I misssed that point.

**Comment by cheekygit** [comment]
I finally got it to work by hiding each second slide in the wrapper on small screens while re-injecting the otherwise missing second slides without wrappers on small screens at the right position using the slickAdd method... then listening to width changes in order to remove or inject them as necessary. How tedious! My feature suggestion would be to introduce slidesToShow and slidesToScroll as a parameter at the slide level. It seems like a fairly common use case to want to optimize the number of slides in view within the same slider as a result of using images of varying width, especially when they contain text that shouldn't get too small to read. Thanks again for your help!

**Comment by ahmadalfy** [comment]
That's a very interesting approach! Good job
