### ISSUE TITLE
empty space after breakpoint

### ISSUE THREAD

**Issue by sebastianpothe** [kenwheeler/slick#1824]
Hi, I have this problem
http://codepen.io/sebastianpothe/pen/VvrjQd

I resized the viewport to show only one slide, then I swiped (or click on dots) to see slide 4, but, when I resized again to show the 4 slides, the slider stays on the left, showing only 1 slide.

I tried with 'slickGoTo' on 'setPosition' but nothing happens

**Comment by sebastianpothe** [comment]
Hi, I have tried this and seems to work:
this script checks if all the slides are visibles, then resets the transform property of the slider track/

$('.slider').on('setPosition', function(slider){
			var slick = slider.currentTarget.slick;
			var currentBreakpoint = slick.breakpointSettings[slick.activeBreakpoint];
			var originalSettings = slick.originalSettings;
			slick.currentSettings = undefined !== currentBreakpoint ? currentBreakpoint : originalSettings;
			if ((slick.slideCount * slick.rowCount) >= slick.currentSettings.slidesToShow) {
				slick.$slideTrack.css('transform', 'initial');
			};
			
		})

**Comment by leggomuhgreggo** [comment]
Glad you found a solution! Closing.
