### ISSUE TITLE
After using slickPause, the slider continues to play if you click elsewhere.

### ISSUE THREAD

**Issue by deckchairuk** [kenwheeler/slick#1829]
I am using slick 'slickElement.slick('slickPause');' to pause my slider, which works great. When I then proceed to click anywhere else on the page the slider continues to play, is anyone else having this issue?

Here's the code I'm using for the slider;

  slickElement.slick({
      slide: '.gallery__item',
      autoplay: true,
      arrows: false
  });

  // Custom Navigation Events
  $(".control__next").click(function(){
    slickElement.slick('slickNext');
  })
  $(".control__prev").click(function(){
    slickElement.slick('slickPrev');
  })
  // Play/Pause button
  $(".control__play").click(function(){
    slickElement.slick('slickPlay');
    $(this).hide();
    $('.control__pause').show();
  })
  $(".control__pause").click(function(){
    slickElement.slick('slickPause');
    $(this).hide();
    $('.control__play').show();
  })

Everything else seems to work okay and I'm fairly sure I'm doing it correctly, any help would be appreciated, thanks.

**Comment by jniziol** [comment]
I was having a possibly related issue. I pause the slick carousel, then moved my mouse over the carousel area then out again, and magically,  the slides would start autoplaying - against my wishes. I attributed it to the setting `pauseOnHover`, which defaults to `true`. I assume there is likely an event being fired `onmouseout` that restarts the autoplay. Setting `pauseOnHover` to `false` fixed it.

**Comment by ahmadalfy** [comment]
@jniziol I was going to say the same thing. @deckchairuk can you please create a jsfiddle showing the issue using [this template](http://jsfiddle.net/simeydotme/fmo50w7n/)

**Comment by aaaa0441** [comment]
@jniziol @ahmadalfy Another workaround is by changing the 'autoplay' setting when calling 'slickPause' & 'slickPlay'. E.g.

  * `$('.carousel').slick('slickSetOption', 'autoplay', false).slick('slickPause');`
  * `$('.carousel').slick('slickSetOption', 'autoplay', true).slick('slickPlay');`

**Comment by egauderman** [comment]
@aaaa0441's fix works great for me!
