### ISSUE TITLE
Mixing upright and landscape images

### ISSUE THREAD

**Issue by Verdemis** [kenwheeler/slick#1832]
Slick is a really nice slider. But i have a problem when i want to show upright images and landscape images in the same slider. I want to show only one image at a time. The most images are landscape and are displayed correct. My problem is when an image is upright it becomes huge, because the slider sets it to full width of the slider box. but what i want is to limit the image to a height and center it in the middle of the sliderbox, without showing other slider elements left and right.

Until now i could force the image to right size with max-height and width:auto. My problem is now to get it centred and to not show other slider elements. Here is how it looks at the moment...

![upright wrong](http://s65.imgup.net/Unbenannt-4730.jpg)
![landscape correct](http://g15.imgup.net/Unbenannt2d07c.jpg)

Thx,
Sascha

**Comment by ahmadalfy** [comment]
You need to explicitly set the values of `slidesToShow` and `slidesToScroll` to 1.

Also, slick sets the display property of the images to `block` that will made the images appears as if they are floated to left. To fix this you need to set the property using CSS to be `inline-block`

I have created a jsfiddle with the effect you want, check it [here](http://jsfiddle.net/hgkantL4/)
