### ISSUE TITLE
autoplay=true/false > change browsertab, responsive behaviour

### ISSUE THREAD

**Issue by MatthiasPeltzer** [kenwheeler/slick#1833]
hi there... 

there is a problem with autoplay in all slider versions in firefox, chrome and safari browsers but not in ie11

if you have responsive settings set for autoplay like:
```
$('.slider').slick({
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 500,
    adaptiveHeight: false,
    responsive: [
        {
            breakpoint: 1024,
            settings: {
                slidesToShow: 2,
                autoplay: false,
                adaptiveHeight: true
            }
        },
        {
            breakpoint: 768,
            settings: {
                slidesToShow: 1,
                autoplay: false,
                adaptiveHeight: true
            }
        }
    ]
});
```
so if the browser window is <= 1024px autoplay starts working again if you change the tab to another page you have opened and go back to the tab with the slider and also with iOS 8/9 you only have to touch into the window to make it start autoplay again. Maybe it has something to do with the browserevent $(window).blur or $(window).focus wich is fired when you focus a tab again?

**Comment by ahmadalfy** [comment]
I have just tried that by creating this [jsfiddle](http://jsfiddle.net/htu6z9Lq/)
Steps I took to reproduce the bug
- Resize the window so that the slider match <= 1024px
- Changed the tab
- Returned back to the slider
Nothing happened. I tried to go beyond 1024 so that autoplay can start then go back again but nothing happened. I was testing using Chrome. Can you please specify a scenario where that issue happen? Or perhapse post a jsfiddle or URL to where you encountered that issue?

**Comment by Jhony0311** [comment]
Hi guys, just to contribute to document this bug, I'm having the issue in a current project with a slider with auto play settings, I was able to confirm this behavior on Chrome, Firefox.

**Comment by Jhony0311** [comment]
The problem is here, there is no check if the slider is paused to set auto play again
```javascript
   Slick.prototype.visibility = function() {

        var _ = this;

        if (document[_.hidden]) {
            _.paused = true;
            _.autoPlayClear();
        } else {
            if (_.options.autoplay === true) {
                _.paused = false;
                _.autoPlay();
            }
        }

    };
```

Maybe the simpler solution would be avoid to pause when the screen change

**Comment by simeydotme** [comment]
should be fixed in the revamp just applied to `master` , please hang tight for a release :)
