### ISSUE TITLE
Right click on iframe breaks the slider!!

### ISSUE THREAD

**Issue by k-lusine** [kenwheeler/slick#1834]
Hi, Thanks for a great slider!
I've a slider, that contains both images and youtube iframes, 
Everything seems to work Ok, only one problem. 
In chrome, when I right click on the iframe, it jumps to the next slide and breaks the slider (changing its positions ). but it's okay in firefox.

Does anyone have an idea what I can do?

Thanks

**Comment by k-lusine** [comment]
And also it jumps to next/previous slide when clicking on youtube play button

**Comment by k-lusine** [comment]
@kenwheeler it turned out to be because of mausedragging was enabled. When I set draggable to false, it works Ok, Can anything be done with it? I'd prefer to keep mousedragging

**Comment by ahmadalfy** [comment]
I just created a slider using YouTube videos and the behaviors you are mentionning aren't happening. Check [this out](http://jsfiddle.net/y5g9fkjr/)
