### ISSUE TITLE
It's possible responsive video?

### ISSUE THREAD

**Issue by jdmoliner** [kenwheeler/slick#1835]
Hi,

I test with this css with bad results:

html:

`<div class="slider">
    <div class="item><iframe src="https://www.youtube.com/embed/7WgYmnwO-Pw" frameborder="0" allowfullscreen></iframe></div>
    <div class="item><img src="image1.jpg"></div>
    <div class="item><img src="image1.jpg"></div> 
</div>`

css:

`embed-container { 
 position: relative; 
 padding-bottom: 56.25%;
 height: 0;
 overflow: hidden;
 max-width: 100%;
 height: auto;
 margin:1em 0 1.5em 0;
} 
.embed-container iframe,
.embed-container object,
.embed-container embed { 
position: absolute;
top: 0;
left: 0;
width: 100%;
height: 100%;
}`

**Comment by ahmadalfy** [comment]
First of all, the HTML you are providing is missing closing quotes for the class names and the CSS you are providing does not match it. I think you are using a JavaScript plugin that wraps the iframe in a div with the class `embed-container` that does all the magic.

Anyway, I recreated your slider using videos and it's perfectly responsive.  Check [this](http://jsfiddle.net/y5g9fkjr/)

**Comment by ZizzyZizzy** [comment]
> First of all, the HTML you are providing is missing closing quotes for the class names and the CSS you are providing does not match it. I think you are using a JavaScript plugin that wraps the iframe in a div with the class `embed-container` that does all the magic.
> 
> Anyway, I recreated your slider using videos and it's perfectly responsive. Check [this](http://jsfiddle.net/y5g9fkjr/)

Sheesh, I've been fighting with this same issue (iframe not responsive) for 2 hours and finally found this 4 year old post. The JS Fiddle was still active, and the CSS you provided works perfectly! Thanks!
