### ISSUE TITLE
swipeToSlide in vertical mode

### ISSUE THREAD

**Issue by mhlozek** [kenwheeler/slick#1837]
It seems swipeToSlide in vertical mode doesn't work.

**Comment by ahmadalfy** [comment]
dragging or swiping in vertical mode works if you drag horizontally ... `swipeToSlide` in vertical mode works on [this fiddle](http://jsfiddle.net/p6wmt1ga/). The problem isn't `swipteToSlide` it's the direction.

**Comment by mhlozek** [comment]
I set verticalSwiping to true - so direction is not problem, but swipeToSlide is not reflected.

**Comment by ahmadalfy** [comment]
Did you try to drag horizontally?

**Comment by stephane-tessier** [comment]
+1, doesn't work with `verticalSwiping: true`

**Comment by oomarsmanoo** [comment]
+1, still doesn't work
