### ISSUE TITLE
Missing dots if using multiple slides to show

### ISSUE THREAD

**Issue by ethanclevenger91** [kenwheeler/slick#1838]
http://codepen.io/ethanclevenger91/pen/xwYERX

You'll notice there are 7 slides, but only 5 dots. If you use the arrows to get to slides 6 or 7, no dot is highlighted. Seems unlikely this is intentional. I'll work on a patch unless you've got something in mind.

**Comment by janh92** [comment]
Will this be fixed soon?

**Comment by kenwheeler** [comment]
Yes

**Comment by codysatellite** [comment]
Any progress on this?

**Comment by codysatellite** [comment]
To anyone it may concern, this issue seems to be fixed on version 1.5.9. Thanks Ken.
