### ISSUE TITLE
Center mode without partial prev/next slides

### ISSUE THREAD

**Issue by DFSko** [kenwheeler/slick#1841]
Center mode without partial prev/next slides
Can i do this?

**Comment by ahmadalfy** [comment]
Why not configuring the slider to show a single slide everytime? What's the difference?

**Comment by DFSko** [comment]
i need responsive slider with 5 slides on large screen, 3 slides on tablet and 1 slide on mobile
PSD without partial slides

**Comment by ahmadalfy** [comment]
Like [this](http://jsfiddle.net/sk3d21b3/)?

**Comment by Secretmapper** [comment]
I have the same question, but my usecase is needing custom styles for the `slick-center` class (I need the 'middle' slide).

So currently, my only option is to use center mode, which gives me a slick-center class, but it has partial slides which I do not want.
