### ISSUE TITLE
Callback function for slickAdd/slickRemove

### ISSUE THREAD

**Issue by pdee999** [kenwheeler/slick#1858]
As there is no callback function for slickAdd or slickRemove, how would I execute a function after a slide has been added?  What I'm trying to do is go to a new slide once it's been added.  I'm currently working around this with a setTimeout but was wondering if there's a better way?

See fiddle:
http://jsfiddle.net/pdee999/7jsj6es4/

**Comment by ahmadalfy** [comment]
Seems like no other way to do it till we get a `slickAdd` slide event.

**Comment by nboliver** [comment]
+1. Trying to do the same thing.

**Comment by leggomuhgreggo** [comment]
Saw this and was curious. The `reInit` event is the way to go. Got it working [here](http://codepen.io/leggomuhgreggo/pen/MyPVWx?editors=0010). Hope that helps.
