### ISSUE TITLE
Autoplay without a pause on items

### ISSUE THREAD

**Issue by Libig** [kenwheeler/slick#1862]
Hi,

At first - good job, slick is fantastic!
I don't know how to manage to use slick defined as:

variableWidth: true
autoplay: true

But without stopping on each item. I'd like to have a smooth carousel. Is that possible now?

**Comment by JordanSayner** [comment]
Try something like this.

$(function(){
    $('.slider').slick({
        speed: 10000,
        autoplay: true,
        autoplaySpeed: 0,
        cssEase: 'linear',
        slidesToShow: 1,
        slidesToScroll: 1,
        variableWidth: true
    });
});

**Comment by Libig** [comment]
Seems that 

```
cssEase: 'linear' 
```

did the trick, thanks!

**Comment by AlexandrGerasimenko** [comment]
Thanks, but what about  pauseOnHover ?
