### ISSUE TITLE
SSR breaks because of window

### ISSUE THREAD

**Issue by paulwehner** [kenwheeler/slick#1863]
I get the following when trying to incorporate this component into my project:

      var Slick = window.Slick || {};
	                ^
      ReferenceError: window is not defined

I know its because window is not defined when trying to do SSR, but don't know what the best strategy is to not have this cause an error.

**Comment by ahmadalfy** [comment]
The `window` object is the global object within the browser and it shouldn't give you undefined. What's the SSR ?

**Comment by kenwheeler** [comment]
@paulwehner what are you SSR'ing with? React? This project is pretty heavily dependent upon the dom, so no dimension calcs would even take place on the server.

**Comment by kenwheeler** [comment]
@ahmadalfy server side rendering
