### ISSUE TITLE
Top Nav bar is jumpy when Slick is on

### ISSUE THREAD

**Issue by grjkz** [kenwheeler/slick#1865]
So I have this problem where my `fixed top: 0` `<nav>` bar moves away from top: 0 and goes to something like top: 20px for an instant then returns to 0. This only happens when slick is started.

Here's a sample of the structure:
## HTML
```
<nav> Content here </nav>

<div id='section1' style='height: 100%'> 
   This is used to just make the next section further down the page
</div>


<div id='#section2' style='height: 100%'> 

   <div class='articles'> 
      
      <div class='article'>
         <div class='image'> 
            <img src='image.jpg'></img>
         </div>
         <div class='description'>
            <div> <p> Lorem </p> </div>
            <div> <button> Button </button> </div>
         </div>
      </div>
      
      <div class='article'>
         <div class='image'> 
            <img src='image.jpg'></img>
         </div>
         <div class='description'>
            <div> <p> Lorem </p> </div>
            <div> <button> Button </button> </div>
         </div>
      </div>

   </div>

</div>
```
## JS
```
$('.articles').slick({
     arrows: false,
     swipe: true,
});
```
Here are some details about the problem:
1. Slick is targeting `.articles`
2. When scrolling up from the bottom of the page, the `<nav>` bar "jumps" from `top: 0` to a small random positive number. `console.log( $('nav').css('top')` always says `0` though.
3. The jumping problem can be reproduced by scrolling `up` past the `bottom` of `#section1` at a fast pace.

My code reproduces this problem EVERY time I scroll up. However with a simple design like the above example, it happens rarely. If someone knows what I'm talking about and might be able to solve it, tell me and I'll try to give a more robust example.

**Comment by ahmadalfy** [comment]
Can you create a jsfiddle with that problem?

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
