### ISSUE TITLE
Slider sync with thumb

### ISSUE THREAD

**Issue by Colir** [kenwheeler/slick#1866]
Hi.
I would like to know if there a way to have the same behavior than the RoyalSlider (http://dimsemenov.com/plugins/royal-slider/gallery/) when sync two slider : one main and a thumbnail's one.

Actually, my thumb slider slide to left (and overflow) even if this slider as a smallest width than his container.

It result that we can't go back by clicking on a previous thumb

The idea will be to scroll the thumb only when the active slide is outside of the container

http://codepen.io/Colir/pen/VvGLVx?editors=101

thank you and also a big thank for this amazing plugin

**Comment by ahmadalfy** [comment]
The exact same effect cannot be replicated using slick. You can create something similar by using `centerMode` and `infinite` and limit the max width of the nav container like this

http://codepen.io/anon/pen/gaBbEW

**Comment by Colir** [comment]
Thanks for the help. i code my own strip thumb.
