### ISSUE TITLE
Parent Container Set to display:table Causes Massive Width of Slider

### ISSUE THREAD

**Issue by Huebris** [kenwheeler/slick#1867]
When you are working on a fluid width website, if the parent container of \<div class='your-class'> is set to display:table, the width of the parent container and slider becomes massively large (millions of pixels for a slider with 1920 pixel images inside).

**Comment by ahmadalfy** [comment]
By default table layout makes its element expand to display all its content. To fix that issue, you need to define a definite width to the element and apply `table-layout: fixed;`

Check this out http://jsfiddle.net/fmo50w7n/134/
