### ISSUE TITLE
Changed the dots to numbers. Now want to slide the dots...?

### ISSUE THREAD

**Issue by lanthanoider** [kenwheeler/slick#1869]
Hi all, need some little help here...

At this point I've managed to change the dots into numbers which tells how many slides there are and  which slide number is active. Is it actually possible to make the dots slide as well? I mean, if there are 10 slides, it should show 1 2 3 4 5 and once it reaches slide 6, the dots change to 6 7 8 9 10. Anyone has ever done this before?

Any help would be appreciated :)
Thanks in advance!

**Comment by JordanSayner** [comment]
you could try creating a custom navigation 

```javascript
 $('.slider-for').slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  arrows: false,
  fade: true,
  asNavFor: '.slider-nav'
});
$('.slider-nav').slick({
  slidesToShow: 3,
  slidesToScroll: 1,
  asNavFor: '.slider-for',
  dots: true,
  centerMode: true,
  focusOnSelect: true
}); 
```

see http://kenwheeler.github.io/slick/ - Slider Syncing

**Comment by lanthanoider** [comment]
Thanks for this, but still need some help here...

in the .slider-nav, I need the dots to be the numbers, not have the numbers and then the dots at the bottom. So far I've got 10 slides and I'm using this:
```
$('.slider-for').slick({
				slidesToShow: 1,
				slidesToScroll: 1,
				arrows: false,	
				fade: true,
				asNavFor: '.slider-nav'
			});
$('.slider-nav').slick({
				slidesToShow: 5, 
				slidesToScroll: 5,
				asNavFor: '.slider-for',
				dots: false,
				centerMode: false,
				focusOnSelect: true,
				draggable: false,
				infinite: false
			});
```

I'm not allowed to enable centerMode, because it needs to be a non-infinite loop and I don't need the slide inside .slider-nav to center  when it's selected, but this causes focusOnSelect to act a bit weird - the slides don't scroll back to the left once it reaches the end. I was thinking of using 2 carousels and do an onclick thing by getting the index of the first carousel and do slickGoTo to the second, but I don't have much luck with it... any takes on this?
