### ISSUE TITLE
If content is hidden during Slick bootstrap, Slick refuses to play ball

### ISSUE THREAD

**Issue by alexrussell** [kenwheeler/slick#187]
I'm not sure that this is easily fixable but I'm implementing Slick on a Bootstrap website and I have a Slick-based gallery in a set of Bootstrap tabs. If the gallery tab is the active one on page load, the Slick carousel works fine, but if the gallery tab is not the one that's active on page load the Slick carousel seems to break (the tab basically looks empty).

At a guess this is due to the items being hidden as Slick is set up against the items and so Slick can't calculate the dimensions of the slides, etc.

A possible non-Slick-based fix is to hook into BS tab event system and only call `$.fx.slick()` when the tab is first switched to. Of course this only works for JavaScript components that allow a developer to hook into this kind of event system, so maybe there's a way for Slick to get round this limitation without requiring developers to do these hackish bits of code (which they sometimes may not be able to do).

**Comment by Jastos** [comment]
The CSS solution above worked great for me.  Slick inside of Foundation Tabs was giving me a hard time.  Thanks!

**Comment by beingtree** [comment]
thanks, @alexrussell: your solution worked for me using slick inside a Foundation 5 accordion.

**Comment by leecollings** [comment]
@alexrussell , sorry to ask, but would you be able to shed some light on how your code would be used with responsiveTabs? I've looked at their docs and some 'Events', but it doesn't seem to match up with Bootstraps. So far I've got:

    $('[href="#before-after"]').on('shown.bs.tab', function (e) {
        $('.slick-carousel-responsive').resize();
    });

The only thing I haven't changed so far is the `shown.bs.tab`. The docs for ResponsiveTabs is here: https://github.com/jellekralt/Responsive-Tabs#events

But I'm not sure if I simply have to replace `shown.bs.tab` with `tabs-activate` or another event shown.

Essentially, I believe I'm having hte same issues as everyone else, when the page loads with another tab being shown, the slick width is displaying as 0, even when the tab is selected.

Can you or anyone else help?

**Comment by alexrussell** [comment]
@leecollings sorry for the delay getting back to you, I kept forgetting to come and read this properly after seeing it in my emails. I haven't tested this but from [the demo](http://jellekralt.github.io/Responsive-Tabs/demo/demo.html) given by the repo itself something like this will work:

``` js
$('#tabContainer').responsiveTabs({
    // ...
    activate: function(e, tab) {
        if (tab.selector == '#carousel') {
            $('.slick-carousel-responsive').resize();
        }
    },
    // ...
});
```

The `if (tab.{something} == {something})` part can be any kind of check you want. In the example they give, if simply looks at `tab.id`, which gives you the 0-based tab index. In my book that's not safe to rely on, hence using `tab.selector` looking for a given id above. Looks like the tab object itself has a few things you can use to check whether or not your tab is the one selected (`tab.id`, `tab.selector`, `tab.panel`, `tab.anchor` to name the four most handy).

Also, instead of passing this function to the bootstrapping of responsiveTabs you could also use jQuery event binding as you suggest above:

``` js
$('#tabContainer').responsiveTabs({
    // ...
});

// ...

$('#tabContainer').on('tabs-activate', function(e, tab) {
    if (tab.selector == '#carousel') {
        $('#slick-carousel-responsive').resize();
    }
});
```

**Comment by Lynda333** [comment]
I ran into this issue recently and saw [an answer on StackOverflow](http://stackoverflow.com/a/26680322/825757) that worked great for me. The code: 

    $('.slick-slider').get(0).slick.setPosition();

IE:

    $( ".news-link" ).on( "click", function() {
	  $( ".news-container" ).slideToggle( "slow" );
	  $('.news-items').get(0).slick.setPosition() //.news-items is class for the slider.
	  return false;
    });

**Comment by mufaddalmw** [comment]
@patrickvaillancourt solution is tricky and worked for me, Thanks :)

**Comment by yangkennyk** [comment]
@Lynda333 

worked wonderfully for me. thanks mucho!

**Comment by Marionovello** [comment]
This worked for me (directly from Slick site)
*// Manually refresh positioning of slick*
$('.your-element').slick('setPosition');

**Comment by jamesonnuss** [comment]
I am using JQuery UI Tabs and was struggling with this issue all day. Thank you!! @JensNielsen81 The CSS works perfectly.

**Comment by moog16** [comment]
@Marionovello that worked perfectly for me! `.resize()` was working for me on Chrome/Firefox, but not on IE9. `setPosition` did the trick.

**Comment by camiloperezv** [comment]
i solved in this way (coffeescript)
<javascript>
angular.element('#new-report').show( "slow",()->
      angular.element('#slider-report').get(0).slick.setPosition();
    );
</javascript>

**Comment by mickvandijk** [comment]
I think the best solution is the way @Marionovello mentioned!
$('.your-element').slick('setPosition');

**Comment by painreign** [comment]
Took ages to figure out:

```javascript
$('.slick-slider').each(function() {
    $(this).slick("getSlick").refresh();
});
```

**Comment by leggomuhgreggo** [comment]
This worked for me:
```
.tab-content>.tab-pane {display: block;visibility: hidden;}
.tab-content>.tab-pane.active {visibility: visible;}
```

[codepen](http://codepen.io/leggomuhgreggo/pen/mPbeee)

**Comment by leizmonk** [comment]
@Lynda333 your solution worked perfectly for me, was trying to implement slick inside a modal, and just added the line you suggested to the click handler that opens the modal. Thanks a ton.

**Comment by hiepdd91** [comment]
```
.tab-content > .tab-pane,
.pill-content > .pill-pane {
    display: block;
    height: 0px;
    opacity: 0;
}
.tab-content > .active,
.pill-content > .active {
    opacity: 1;
    height: auto;
}
```

**Comment by efflux** [comment]
@Lynda333 you are a gem.. thank you!

**Comment by chiss22** [comment]
@painreign solution also worked for me! Thanks!

**Comment by daniel4567** [comment]
I did something like this. It works but it's a bit twitchy. Let me know if you figure out a smoother version. 

function resizeOnPanelCollapse() {
    $('.collapsible').on('shown.bs.collapse', function (e) {
        $('.slick-slider').each(function() {
          $(this).slick("getSlick").refresh();
        });
    });

    $('.collapsible').on('hidden.bs.collapse', function (e) {
        $('.slick-slider').each(function() {
          $(this).slick("getSlick").refresh();
        });
    });
}

**Comment by proweb** [comment]
@patrickvaillancourt thanks man, you saved me hours. It's fixed my landing.

**Comment by TimmyDodd** [comment]
thanks @patrickvaillancourt !
I used this code to make it work in a modal:

```
.modal {
    display: block;
    visibility: hidden;
    overflow-y: hidden;
}
.modal.in {
    visibility: visible;
}
```

**Comment by clauz** [comment]
After playing with js to set min widths for the content and getting very very close but always having an issue with the transitions, I came across this and the resize() did it for me....thank you!!!!!!!!!!!!!

**Comment by Myrkotyn** [comment]
@patrickvaillancourt thank you, man

**Comment by JeremyLopez** [comment]
I didn't use bootstrap and wrote my own equivalent to bootstrap tabs, but when I try to fire `$(this).slick("getSlick").refresh()` when they click the tab, it doesn't work.  Is there anything else I can do?

**Comment by mariovalney** [comment]
@JeremyLopez try @alexrussell suggestion:

```
$('.your-tab-trigger').on('click', function (e) {
    $('.your-slick').resize();
});
```

**Comment by samjonesigd** [comment]
`$('.your-slick').slick("getSlick").refresh();`

this works great on click and a few other suggestions worked too on opening and closing tabs, but if i resize the page then open a tab my slick is broke until it goes to the next slide. This could be an issue when people are changing orientation on devices. Any suggestions?

**Comment by hot-Whiskey** [comment]
i was having issues and none of the above would work. i had to change my event handler from 'show.bs.modal' to 'shown.bs.modal'

**Comment by gety9** [comment]
patrickvaillancourt, thanks!

Your solution worked for me!

**Comment by tijanmdr** [comment]
Thanks to @painreign.. The solution works
```
$('.slick-div-holder').each(function() {
     $(this).slick("getSlick").refresh();
});
```
But this flickers alot

**Comment by AbdallahNasser** [comment]
unfortunately, I tried all the solutions above, but none of them worked correctly with me
In my case, I have 2 tab containers in the same page, so when I try the bootstrap hack, it works for the slick, but it results an overflow within the other tab container (tab panes are overflowing each other)
is there any thing else to do ?

**Comment by leggomuhgreggo** [comment]
@AbdallahNasser  So the reason it breaks is because by default the content in a non-active tab is hidden with `display: none`, which prevents  the slick JS from getting the dimensions properly.

So you can used visibility hidden, which hides things without taking them out of the document flow, and position absolute the `.tab-panes` in `.tab-content` so they don't stack.

```
.tab-content>.tab-pane {display: block;visibility: hidden;}
.tab-content>.tab-pane.active {visibility: visible;}
.tab-content{position: relative;}
.tab-pane{position: absolute;width: 100%;height: 100%;top: 0;left: 0;}
```

[Example](https://codepen.io/leggomuhgreggo/pen/zdroGy?editors=0100)

**Comment by tibelchior** [comment]
None of the above worked in my case, I had to set a timeout to execute the refresh.
<pre>
$('.depos').on('click', function () {
	setTimeout(function() {
	   $('.slider-nav').slick("getSlick").refresh();
	   $('.slider-for').slick("getSlick").refresh();
	},300);
});
</pre>

**Comment by tijanmdr** [comment]
@tibelchior Yeah, to work with slick with AJAX requests, u always have to set timeouts. 

Better to use other sliders rather than slick.

**Comment by tibelchior** [comment]
@tijanmdr which one do you recommend that is as good as Slick?
I'm having special problem to execute Animate.css. It just works in the 1st slide

**Comment by tijanmdr** [comment]
I think Owl Carousel is also a good one. Try that one out.

**Comment by kabelo38** [comment]
this worked for me .nav-item its a class found on tabs menu
           
           $('.nav-item').click(function() {

                $('.slick-disabled').trigger('click');
            })

**Comment by mladimatija** [comment]
If anyone is still having this issue - seems like if you change the .slick-active slide in any way via JS after initialization of slick slider it will work as expected.

So, after you initialize your slider just add for example yourSlider.find('.slick-active').css('z-index', 1); and it will will work :)

**Comment by kstratis** [comment]
@patrickvaillancourt @JensNielsen81 Thanks for the elegant solution!
I spent half a day of frustration and experimentation with tens of slick suggestions to no avail.
Your pure css solution was the only one that truly worked for me the way I wanted it to.

**Comment by TwelveLabours** [comment]
**SIMPLE SOLUTION**  Thanks @LDigital84 

I have a site where 'slick' is within a hidden div, and then shown during a transition. Slick's parent div is set to 'hidden' with initial CSS, and shown later with JQuery. Slick wouldn't appear, even though during initial formatting and testing (with the parent div NOT hidden) Slick had been performing as expected. 

I simply use a hacky function call:

function slickFix(){
$('.yourSlickClass').get(0).slick.setPosition();
}

and then call that function after I show the parent div.

Works a charm.....thanks, this was driving me crazy!

**Comment by magicjoef** [comment]
I wasn't getting very far with the setPosition or triggering resize approaches, maybe because I had a slightly different context. Just in case this helps anyone...

I needed to switch between a few different slick sliders, meaning I wanted a couple of hidden sliders on load that I swapped in on a button click. However, using display none leads to the cited problem of Slick not being able to get dimensions.

I thought about flashing them in on load and then hiding them, as they are near the bottom of my page, that way Slick could init them. However, that's not tidy and still left the issue of what happened if someone resized the browser. All the hidden sliders wouldn't be resized correctly.

In the end I decided to create Slick everytime I needed it. Using a combination of a jQuery fadeIn followed by initialising slick worked well. I thought it might flash content, but it hasn't in the browsers I've tested.

When I swap to a new slick carousel, I hide the existing one and unslick it. Then for the incoming carousel I use the combination of fadeIn and initialising. Kind of a just in time approach. Something to consider depending where and how you're using Slick.

It seems stable on what I've tested, but if anyone can see any pitfalls to this approach I haven't spotted please let me know.

**Comment by codacopia** [comment]
@painreign solution was the only thing that would work for me with multiple slide modals on a page.

**Comment by bomzj** [comment]
I implemented universal code for all type of containers: tabs, modals, collapsible's and etc that finds hidden parent container where slick is in and updates slick position each time parent container is displayed (display: block).

```
function isHidden(el) {
	var style = window.getComputedStyle(el);
	return style.display === 'none';
}

function findHiddenParent(el) {
	while (el) {
		el = el.parentElement;
		if (el && isHidden(el)) return el;
	}
}

function onParentChanged(slickSlider) {
	if (this.style.display != 'none') {
		$(slickSlider).slick('setPosition');
	}
}


var slickSlider = $(".slick").slick({...});

// Slick can not calculate its dimension while being placed in hidden modals, tabs, collapsibles and etc(display: none)
// When hidden parent gets visible, we should do slick resize() to display it appropriately
var hiddenParent = findHiddenParent(slickSlider);
if (hiddenParent) {
	var observer = new MutationObserver(onParentChanged.bind(hiddenParent, slickSlider));
	observer.observe(hiddenParent, { attributes: true });
}
```

**Comment by saxsax1995** [comment]
Okay so i was stuck in this sitution just like you guys and i found the reason it cause the issue, it simple because when you use slick in tabs, it gonna set your unused tab to `display: none`, and when they did, the width in that unused tab become 0, and slick need a width to run correctly, and this solution worked for me:
```
.tab-content>.tab-pane{
  display: flex !important;
  height: 0px;
  overflow: hidden;
}

.widget-tab.mixed-tab .tab-pane.active{
  height: auto;
}
```

Set non-active tab to `display: flex !important;` and `overflow: hidden;` will do the same thing as `display: none`, but for some reason, it will set your width automatic, so the slick will works perfectly.

**Comment by bassm** [comment]
.tab-content>.tab-pane{ display: block; height: 0px; overflow: hidden; }
.tab-content>.active{ height: auto;}

**Comment by Arashz22** [comment]
I solved my problem with **slick** after showing bootstrap modal :

```
$("#Modal").on('shown.bs.modal', function(){
    $('#Slider').slick();
})

$('#Button').click(function(){
    $('#Modal').modal('show');
});
```

maybe it helps.

**Comment by bbwstar** [comment]
In my side above solutions are not working.
settimeout option ( @tibelchior ) is only  working. Are there a better way without settimout function?

**Comment by khatrn** [comment]
@Arashz22  your code worked for me! Thank you! :+1:

**Comment by Arashz22** [comment]
> @Arashz22 your code worked for me! Thank you! 👍

Happy to hear that, you are always welcome😍

**Comment by bnikkhah** [comment]
> The .resize() option didn't work for me. I experienced a similar problem attempting to render an embedded google map inside a bootstrap tab as well. To my surprise both problems were resolved by changing how bootstrap handles hidden tabs:
> 
> /* bootstrap hack: fix content width inside hidden tabs */
> .tab-content > .tab-pane, .pill-content > .pill-pane {
>     display: block;    /* undo display:none          */
>     height: 0;         /* height:0 is also invisible */ 
>     overflow: hidden;  /* no-overflow                */
> }
> .tab-content > .active, .pill-content > .active {
>     height: auto;      /* let the content decide it  */
> } /* bootstrap hack end */
> more here: https://groups.google.com/forum/#!topic/twitter-bootstrap-stackoverflow/0Aqzs5s_hEY

I was spending about 4 hours figuring this out and I cried for joy when I found this code. Thank you so MUCH!
