### ISSUE TITLE
Bug in DOTS when using asNavFor

### ISSUE THREAD

**Issue by MehdiDehghani** [kenwheeler/slick#1877]
Hello,
First, thanks for your great plugin, it is awesome.

I want to report a bug, if you have a look on **asNavFor** example in your site, you can see, when I clicked on last DOT, still I have some more item/page and there is no more DOT. (in fact number of dots is not correct, because we have more than 3 pages).

Hope I could tell the bug correctly, sorry for my bad English.

Cheers,
Mehdi

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
