### ISSUE TITLE
webkit-box-reflect effect will disappear if the slidesToShow number equals to the total number of images.

### ISSUE THREAD

**Issue by lorentzyip** [kenwheeler/slick#1878]
Hi, I have an html which shows four images below

![html](https://cloud.githubusercontent.com/assets/1384476/11037177/5e3ceea8-8737-11e5-90a6-f61dea9e6a00.jpg)

style.css:
-------------------------------------------------------------------------------------------------------
body {
    background-color: gray;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #333;
    overflow: hidden;
}

#content-promotions {
    text-align: center;
    width: 100%;
    height: 100%;
    padding: 10px;
}

#content-promotion {
    width: 1024px;
    height: 768px;
}

#promotions-slider-container {
    position: absolute;
    top: 180px;
    left: 0px;
    width: 1920px;
}

.promotion-container img {
    width: 366px;
    height: 549px;
    margin: 10px auto;
    -webkit-box-shadow: 0 0 10px rgba(0,0,0,0.6);
    box-shadow: 0 0 10px rgba(0,0,0,0.6);
}

.reflect {
    -webkit-box-reflect : below 0 -webkit-gradient(linear, left bottom, left top, from(rgba(255,255,255,0.3)), color-stop(0.3, transparent));
}
-------------------------------------------------------------------------------------------------------

if I set the slidesToShow < 4, the reflection effect can be shown below each image. However, if I set it to four, the reflection effect gone. But if I open chrome's style inspector and toggle the "reflect" class on the image manually, the reflection effects appear again. Is it a bug and do somebody know how to fix it? Thanks.

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
