### ISSUE TITLE
No Transition Option?

### ISSUE THREAD

**Issue by jhned** [kenwheeler/slick#1880]
Just wanted to toss this out there-- not sure if it has been suggested before. Would it be possible to include an option for no transitions, via CSS or jQuery? To put it another way, all the JavaScript would be responsible for is setting which slide is active.

This way, the carousel animation can be completely customized by the developer, rather than having to wrestle control away from inline CSS.

**Comment by ahmadalfy** [comment]
OK so instead of ... sliding or fading, you want the developer to take control. right?

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
