### ISSUE TITLE
Jquery Dependency

### ISSUE THREAD

**Issue by ccorcos** [kenwheeler/slick#1881]
Why isnt jquery specified as a dependency in the package.json?

**Comment by ahmadalfy** [comment]
jQuery is defined as a dependency in `bower.json`. I believe the npm package is meant to include only the dependencies required to build the package from the source.

**Comment by ccorcos** [comment]
Hmm. But then you can have version issues in the global scope. If you did `var $ = require('jquery')` wherever you needed it, then you can set version constraints in your package.json. If this package required a specific version of jquery that collides with another package, then both version have live harmoniously without using the global namespace.

**Comment by StreetStrider** [comment]
Declaring dep from jquery sounds correct but it's bad for browserify builds.
Looks like the dep [was added](https://github.com/kenwheeler/slick/commit/96ab6811b302a35f82b2128e350ee25c583df408) as a reacton on this issue. Sad to see it, this is a wrong thing to do.

**Comment by StreetStrider** [comment]
I'm for reverting this.

**Comment by kenwheeler** [comment]
So how should this be handled in your opinion?

**Comment by StreetStrider** [comment]
@kenwheeler, I don't know how this should be handled «properly». I've tried to look for publications on this today, there's no concent on this. Many guys just leave their `dependencies` empty, including jQuery UI guys. So they just do not manifest dep from jQuery. Others do manifest. Maybe `peerDependepcies` is a way to manifest such stuff.

Now I'm working on my build, and it seems like some deduping works in `npm@2`, so when I have:
```
$ npm ls
…
├── jquery@2.2.0 # ← top level jQuery
├── jquery-circle-progress@1.1.3
├── jquery-ui@1.10.5
├── jquery.scrollto@2.1.2
├── slick-carousel@1.5.9
```
looks like plugins do not install their local copy of jQuery (when npm sees jquery on the top level). So my build don't bloat luckily.

**Comment by StreetStrider** [comment]
After some investigations I think it is ok to keep explicit dep. Looks like npm v2 soft deduping works fine and v3 will have more agressive deduping.

For v2 users it is important to install jQuery at the top level **first** and then install plugins to it. In that case deduping works OK.
