### ISSUE TITLE
On variableWidth slideWidth is null

### ISSUE THREAD

**Issue by pgarciaf** [kenwheeler/slick#1883]
Im working on set different width and height depending on certain variables. But i found a problem when i set the width to image.

I resolve setting _.slideWidth when _.options.variableWidth === true, this is the final mod

Slick.prototype.setDimensions = function() {

        var _ = this;

        if (_.options.vertical === false) {
            if (_.options.centerMode === true) {
                _.$list.css({
                    padding: ('0px ' + _.options.centerPadding)
                });
            }
        } else {
            _.$list.height(_.$slides.first().outerHeight(true) * _.options.slidesToShow);
            if (_.options.centerMode === true) {
                _.$list.css({
                    padding: (_.options.centerPadding + ' 0px')
                });
            }
        }

        _.listWidth = _.$list.width();
        _.listHeight = _.$list.height();
        //console.log(Math.ceil(_.listWidth / _.options.slidesToShow));

        if (_.options.vertical === false && _.options.variableWidth === false) {
            _.slideWidth = Math.ceil(_.listWidth / _.options.slidesToShow);
            _.$slideTrack.width(Math.ceil((_.slideWidth * _.$slideTrack.children('.slick-slide').length)));

        } else if (_.options.variableWidth === true) {
            _.$slideTrack.width(5000 * _.slideCount);
            _.slideWidth = Math.ceil(_.listWidth / _.options.slidesToShow);
           //console.log(' the slidewidth is set')
        } else {
            _.slideWidth = Math.ceil(_.listWidth);
            _.$slideTrack.height(Math.ceil((_.$slides.first().outerHeight(true) * _.$slideTrack.children('.slick-slide').length)));
        }

        var offset = _.$slides.first().outerWidth(true) - _.$slides.first().width();
        if (_.options.variableWidth === false) _.$slideTrack.children('.slick-slide').width(_.slideWidth - offset);

    };

**Comment by ahmadalfy** [comment]
Can you recreate the problem using jsfiddle and create another jsfiddle with your proposed solution? Currently you are saying you found a problem when you set the width to image. What's the problem? And how does your modification fix it?

**Comment by pgarciaf** [comment]
Lo hare este fin de semana, pero no he tenido el tiempo de hacerlo.

----

I'm gonna do it this weekend, but i dont have time to do it right now.

2015-11-15 16:02 GMT-03:00 Ahmad Alfy <notifications@github.com>:

> Can you recreate the problem using jsfiddle and create another jsfiddle
> with your proposed solution? Currently you are saying you found a problem
> when you set the width to image. What's the problem? And how does your
> modification fix it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kenwheeler/slick/issues/1883#issuecomment-156843500>.
>



-- 
<información>
<nombre>*Pablo García Fernández*</nombre>
<celular>*+56966468601*</celular>
</información>

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
