### ISSUE TITLE
Chrome bugg: Click on next/prev or dots with autoplay

### ISSUE THREAD

**Issue by eckelarsson** [kenwheeler/slick#1884]
If i click on the next/prev or dots once or twice (dosen't matter) and then scroll up or down, when the autoplay start changing slides i automatically scroll back (jumps) to the slick container.

I figure it has someting to do with the "active" state the slick sets on the current item. If i click the next/prev or dots then click anywhere else on the page this behavior will not occur.

I guess that i remove the state of "active" or "focus" on the current slide item.

**Comment by kenwheeler** [comment]
This will be fixed in the next release

**Comment by eckelarsson** [comment]
Thank you! Do you guys have an ETA for the next release?

**Comment by kenwheeler** [comment]
It's sitting in a local commit ready to go, wanted to figure out this variable width bug, but I guess I'll just push this out
