### ISSUE TITLE
CSS3111: @font-face encountered unknown error

### ISSUE THREAD

**Issue by TechFounder** [kenwheeler/slick#1887]
Hi I'm getting an
```CSS3111: @font-face encountered unknown error```
     ```slick.eot?#iefix```
on the IE9 console which completely blocks the site from rendering. When I remove the slick-theme that error goes away but of course I don't have the default theme. Any idea how to fix the problem?

**Comment by TechFounder** [comment]
Seems that in the theme file this line: 
``` src: url(<%= asset_path('slick.eot?#iefix') %>) format('embedded-opentype'),``` the source of he error.

**Comment by ahmadalfy** [comment]
Are you trying to load the scss file into the browser? You're meant to load the css version not the scss.

**Comment by TechFounder** [comment]
Hum, I'm using it within Rails assets and I'm utilizing SASS but that suppose to convert it into CSS. Even if were to require it from application.css, it still shows the error if I include the theme file.

**Comment by ahmadalfy** [comment]
uhm,  I've found these discussions on Stackoverflow regarding the error you're getting in the console

http://stackoverflow.com/questions/11559592/ie9-css3111-font-face-encountered-unknown-error
http://stackoverflow.com/questions/15974104/ie9-font-face-encountered-unknown-error

Can you check and see the proposed solution? I have used slick on IE before without troubles. Try to download slick again and extract the fonts to your assets directory and see what happens.

**Comment by TechFounder** [comment]
Thanks, I'm traveling this week and will take another crack at it when I return next week. I'll let you know then...

**Comment by TechFounder** [comment]
Hi, I played around with this some more and it looks like the error is definitely from the theme file and this: ```src: url(<%= asset_path('slick.eot?#iefix') %>) format('embedded-opentype')```
The error seems to be generated from the dots option. Any ideas on my IE9 doesn't like the eot of those dots or how to fix it?

**Comment by ahmadalfy** [comment]
I suggest you check the other repo. The font is working fine on IE9 and the latest commit on the ruby gem says "Version 1.5.8.1. Save fonts files in UTF-8."

Perhapse that's the issue .I suggest you download the fonts from slick's original repository and replace the gem's assets if thats possible and see if the error still happenning. If not, open a ticket there.

**Comment by TechFounder** [comment]
ok, let me take this up with the gem author. Thanks.

**Comment by Sri8361** [comment]
I am working on ie11 . and getting the same error font face encountered error while running webcam on it . not getting solution Why is it so ??
