### ISSUE TITLE
Slick making images 0 width

### ISSUE THREAD

**Issue by Petah** [kenwheeler/slick#1888]
I am trying to get slick to work but it is making all my images 0 width.

This is the code I tried:

	console.log($('.p-top-screen-shots-images img').width());
	$('.p-top-screen-shots-images').slick({
		infinite: true,
		arrows: false,
		autoplay: true,
		autoplaySpeed: 5000,
	});
	console.log($('.p-top-screen-shots-images img').width());

The console output shows `350` then `0`.

I have tried putting it in a document ready callback, and even putting it in a timeout. Neither work, in fact in the timeout I can see then images, then they disappear. 

My markup is simple a div with img tags inside. There is no styling out the image or wrapper. 

I am testing this on a small screen (350px).

**Comment by nstanard** [comment]
Please create an example/demo with the markup/styles you are using. I am going to start trying to contribute to this project and this sounds like a good first issue to look at. If you can isolate this issue in a demo I will take a look at it.

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
