### ISSUE TITLE
Can't move to items when centerMode is enabled and the slide count is less than slidesToShow

### ISSUE THREAD

**Issue by rickdmer** [kenwheeler/slick#1891]
See an example of this here:
http://jsfiddle.net/rickdmer/hrc9tn7k/

This used to work in an older version (1.3):
http://jsfiddle.net/rickdmer/n4axgh4a/

**Comment by ahmadalfy** [comment]
What do you mean by "Can't move to items when centerMode is enabled"? The first example seems to work perfectly

**Comment by rickdmer** [comment]
Hi Ahmad, sorry for the poor wording. What I meant is, when you have less items (4 in this case) than the "slidesToShow" value (5 in this case), the slider is completely stationary and ignores slickNext/slickPrev/etc. There is no way to see the 4th item.

It appears that at some point in the development of Slick, there was a change to make it so some functionality is disabled (slickNext, slickPrev, etc) when the slide count is less than "slidesToShow" option. I can see cases where this would be ideal, but when using centerMode (as in the first example), it prevents you from moving to items.

**Comment by ahmadalfy** [comment]
paging @kenwheeler

**Comment by slavicd** [comment]
This is related to #1245 and seems to be related to #2244 . It's all due to the fact that the slider incorrectly handles cases of slidesToShow > {actual-number-of-slides} .

**Comment by leggomuhgreggo** [comment]
Dup of #1189
