### ISSUE TITLE
Position: fixed bug?

### ISSUE THREAD

**Issue by darrensw** [kenwheeler/slick#1894]
I'm trying to use the slider at the bottom of a page but when I set it's container to position: fixed, it breaks everything. Each cell seems to double in size on interaction with the slider.

Is there a workaround for this?

Here's a fiddle to show the problem: http://jsfiddle.net/3893s80b/4/

**Comment by ahmadalfy** [comment]
You need to explicitly state the `left` and `right` value. Otherwise it will expand to fill the whole width.

Check this out: http://jsfiddle.net/3893s80b/6/

**Comment by darrensw** [comment]
Not entirely true - I added `width: 100%` and it fixed the issue too
