### ISSUE TITLE
Package for Meteor

### ISSUE THREAD

**Issue by newswim** [kenwheeler/slick#1897]
Is it okay if I fork this and make an official smart package for Meteor? It's really just an additional package.js file and I'll set it up for auto-updating whenever you publish new releases -- wuddaya say?

**Comment by newswim** [comment]
There's a few other instances of this already being made, even though the latest is ~50 commits behind develop, i'm going to close this. Ty!

**Comment by ahmadalfy** [comment]
Why not you send a PR with that additional package.js ? I didn't use Meteor before so I don't really know.
