### ISSUE TITLE
Wrong slide order on vertical

### ISSUE THREAD

**Issue by numediaweb** [kenwheeler/slick#1899]
As you can see on the image bellow, I gave the same images for two different slides, the first one (in the left) shows the images in the exact order, but the second one (on the right), shows the 1st images in the 3rd row instead of the first row.

I use
```
 // Assign the main slider
 $($mainSlides).slick({
 	fade: true,
 	arrows: true,
 	dots: true,
 	infinite: true,
 	prevArrow: '<div class="nw-arrow nw-nav-prev"></div>',
 	nextArrow: '<div class="nw-arrow nw-nav-next"></div>'
 });

 // Assign the thumbs slider
 $($thumbSlides).slick({
 	arrows: false,
 	infinite: true,
 	touchMove: false,
 	vertical: true,
 	rows: 4,
 	slidesPerRow: 3,
 });
```

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
