### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined 

### ISSUE THREAD

**Issue by tylerpepper** [kenwheeler/slick#19]
Recently I've tried using Slick on a Drupal site, and it throws this JS error because the code assumes that $ is defined.

Wrapping slick.js in `(function($){ ... })(jQuery);` seems to fix the problem.

**Comment by jashwant** [comment]
Still not fixed. Same error in wordpress website.

**Comment by jashwant** [comment]
Ignore my last comment. It works fine. I was using babel, so it was being wrapped in factory wrapper twice. Once, I removed the file from babel compilation, it works.
