### ISSUE TITLE
clear example of how to markup the slider

### ISSUE THREAD

**Issue by ericmcgregor** [kenwheeler/slick#1900]
Was trying to put together an example of your slider, but your documentation is really lacking on some clear examples of how to markup a slider that uses your css.

```
<div class="your-class">
  <div>your content</div>
  <div>your content</div>
  <div>your content</div>
</div>
```

This is a remarkably poor example.  I've been trying to copy the source from your example page, but it just seems like it would be so much easier to provide some clear markup examples that show how to get the buttons and everything else implemented properly.  This would be really helpful.  are there any existing examples of this that i missed in the documentation?  thank you.

**Comment by ahmadalfy** [comment]
This is all the markup you need. Buttons and bullets are added automatically if you are setting them in the options, the documentations state that clearly.
