### ISSUE TITLE
Disable prev and next controls and slider on 1st and last slide

### ISSUE THREAD

**Issue by gward35** [kenwheeler/slick#1902]
Hi I am using slick for a multi row slider. Its there a feature I can use that disables the slick arrow and Prev controls on landing and reenables them once the user starts scrolling through the slider? Additionally is there a way to disable the next arrow and control once the user reached the last slide?

My slider does not use an auto play feature fyi but the link to the below site is what I am trying to accomplish http://www.asla.org/sustainablelandscapes/index.html 

Any help is appreciated thanks!

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
