### ISSUE TITLE
There will be some errors if slideCount % slidesToScroll !== 0

### ISSUE THREAD

**Issue by XieShangxu** [kenwheeler/slick#1903]
There will be some errors in the following case:

slideCount % slidesToScroll !== 0

For example:
slideCount  = 10
slidesToScroll = 3

Could you please help to check this?

Thanks,
Daniel

**Comment by ahmadalfy** [comment]
Can you check this please? https://github.com/kenwheeler/slick/pull/1882

Isn't it the same issue?

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md

**Comment by XieShangxu** [comment]
I think this issue is different with #1882.

In my case, there will be a flash when you slide to the end.
