### ISSUE TITLE
Slide height percentage of parent e.g. 100%

### ISSUE THREAD

**Issue by McGern** [kenwheeler/slick#1905]
Hi,

Sorry couldn't find any other issues relating to this. Great plugin BTW.

What is the correct way to have 100% height on slides? The parent container has a height that is a relative and the slide is relative to the container e.g. 100%

Slick adds many internal elements between the parent and the slides so the slide is no longer relative to the parent. Without hacking a height onto the slide or having knowledge of the internal workings of Slick and the additional containers it produces, what is the best way around this issue?

I was having the same issue with slides that had no content, only background images that covered the area - this was to be used as a non-interactive enhancement piece in the background of another slide, but I couldn't get it working with 100% height so had to use another technique.

Thanks,
Jarrod

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md

**Comment by lunow** [comment]
works great for me with this additional css: 
```
.slick-list,
.slick-track {
	height: 100%;
}

**Comment by KhaledMohamedP** [comment]
I tried the above solution and didn't work, but this does work! 


```css
.slick-track {
  display: flex;
}
.slick-track .slick-slide {
  display: flex;
  height: auto;
}

```

**Comment by MsMatki** [comment]
> I tried the above solution and didn't work, but this does work!
> 
> ```css
> .slick-track {
>   display: flex;
> }
> .slick-track .slick-slide {
>   display: flex;
>   height: auto;
> }
> ```

Wow so glad that I found this!
Thanks!

**Comment by rudestewing** [comment]
> ```css
> .slick-track {
>   display: flex;
> }
> .slick-track .slick-slide {
>   display: flex;
>   height: auto;
> }
> ```

thanks

**Comment by vasilzhigilei** [comment]
If anyone is experiencing weird slick height (very tall), the following should work (the other solutions weren't what I was looking for):
```
.slick-slide{
    height: auto;
}
```

**Comment by frankstepanski** [comment]
None of the above solutions work for me.
