### ISSUE TITLE
Trying to use title slide to change slider image directory

### ISSUE THREAD

**Issue by roylling** [kenwheeler/slick#1909]
Hi, first of all thanks for this awsome work.
I'm trying to use a 'afterChange' to change file dir for diferrent slides but I've been having this error in console:
slick.min.js:18 Uncaught TypeError: Cannot read property 'add' of null
I'm also using removeall to delete all slides then call them again but it does not seem to work, any ideas?
This is my script:

    $(document).ready(function() {
	
        var num = "1";
        var dir = "images/img/" + num+"/";
        
		
		$('#slidertittle').on('afterChange', function(event,slick,i){
          if (slick.$slides[i].id =="tittle1"){
          num="1";
          }
          else if (slick.$slides[i].id =="tittle2"){
          num="2";
          }
          else if (slick.$slides[i].id =="tittle3"){
          num="3";
          }
          (function(){
          ('.slider-for','.slider-nav').slick(null,null,true);
          });
          dir = "images/img/" + num+"/";
        loadimg()
        });
		
		
        $('#slidertittle').slick({
        slidesToShow:1,
        arrows: true,
        fade: true,
        appendArrows: $("#slidertittle"),
        prevArrow: '<img class="slick-prev" src="images/left-arrow.png">',
        nextArrow: '<img class="slick-prev" src="images/right-arrow.png">',
        });
        
   
        
        function loadimg(){
        $.ajax({
        //This will retrieve the contents of the folder if the folder is configured as 'browsable'
        url: dir,
        success: function (data) {
        //Lsit all png file names in the page
        $(data).find("a").attr("href", function (i, val) {
          if( val.match(/\.jpg|\.png/) ) { 
              $(".slider-for").append( "<div><img src='"+ dir + val +"'></div>" );
              $(".slider-nav").append( "<div><img src='"+ dir + val +"'></div>" );
          } 
        })
        }
        }).done(function (){
              $('.slider-for').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        fade: true,
        asNavFor: '.slider-nav'
        });
        $('.slider-nav').slick({
        slidesToShow: 4,
        slidesToScroll: 1,
        asNavFor: '.slider-for',
        dots: false,
        centerMode: true,
        focusOnSelect: true,
        autoplay: true,
        autoplaySpeed: 4000,
        centerMode: true,
        arrows:false,
        variableWidth: true,
        centerPadding: '5px',
        responsive: [
        {
        breakpoint: 1024,
        settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
        infinite: true,
        dots: true
        }
        },
        {
        breakpoint: 600,
        settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        }
        },
        {
        breakpoint: 480,
        settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        }
        }
        ]
        
        });
          
          });
        
        
        };
        });
    
Thanks, hope you  could  undestand.

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
