### ISSUE TITLE
Add a print breakpoint

### ISSUE THREAD

**Issue by dominikwilkowski** [kenwheeler/slick#1912]
In the responsive object you could add a print breakpoint to disable slick on the print view. That way we could print the content. This is useful when we use slick as a content explorer and would like to stack the content boxes on print view.

```js
$('.js-slick').slick({
	slidesToShow: 4,
	responsive: [
		{
			breakpoint: 1050,
			settings: {
				slidesToShow: 4,
			}
		},
		{
			breakpoint: 'print',
			settings: unslick,
		},
	],
});
```

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
