### ISSUE TITLE
Event while dragging

### ISSUE THREAD

**Issue by nilssolanki** [kenwheeler/slick#1913]
Is there an event that is called *during* dragging?

`on('swipe')` seems to be called only when the dragging is released. I'm trying to do a few things while dragging already: Changing the background-color of the page *while dragging* and dragging another slider along *simultaneously* with `asNavFor` (as opposed to only when I let go of the first slider).

Is there an event for this or any other way to do this?

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
