### ISSUE TITLE
Troubles with hidden carousel

### ISSUE THREAD

**Issue by lamartire** [kenwheeler/slick#1915]
Hello!
If I place slick into hidden container and open it after page loading, elements positions are incorrect. After click on navigation arrows they take normal position.
What am I doing wrong?
After loading slick-list have "slick-initialized" class.
![ttcds5i](https://cloud.githubusercontent.com/assets/13414205/11369494/512e6774-92d0-11e5-8749-364428fca4bd.png)

**Comment by kenwheeler** [comment]
Theres like a billion issues on this, closing as a dupe, do a search and you'll see a detailed way to fix this
