### ISSUE TITLE
Had to add code to fix carousel spacing bug

### ISSUE THREAD

**Issue by cannect** [kenwheeler/slick#1917]
Hi,

I have a carousel which is linked to a slider. The bug appears only when using `centerMode : true`.
When my carousel has less than 6 items, the carousel `.slick-track` div will have added an inline added css property `left` with in my case a value of 'left: 132px;'. This causes my last carousel item to be invisible.

So I added a single if statement to the following code to slick.js:

```
if (_.options.centerMode === true && _.options.infinite === true) {
            if( _.slideCount > 5 ) { // <<<======= my if statement 
                _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2) - _.slideWidth;
            }
        } else if (_.options.centerMode === true) {
            _.slideOffset = 0;
            _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2);
        }
```

And the bug is fixed in my case.

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
