### ISSUE TITLE
Using slick with filtering

### ISSUE THREAD

**Issue by rreifman** [kenwheeler/slick#1918]
I am trying to create jquery functions that hide/show elements based on a filter/search.
I thought that if i disable the visibility of an object, it would not be included in the slick slider, but slick includes then and just shows empty space...
I also tried getting the index of each element that i want to remove and removing it with the slick functions, but that wasn't working well.
How can i maybe reload the slick with just visible objects?

**Comment by rreifman** [comment]
I solved this using jquery's detach function and reloading slick

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
