### ISSUE TITLE
Get responsive slidesToShow option on 'init'

### ISSUE THREAD

**Issue by jdmoliner** [kenwheeler/slick#1920]
Hi,

I need to get responsive slidesToShow option on init because I'm showing pagination with slick. But I get always slidesToShow main option:

    $(document).ready(function(){ 

     $('.slider').on('init', function(event,slick){ 
        var total = $('.container'+' .slick-slide:not(.slick-cloned)').length;
        var items = slick.slickGetOption('slidesToShow');
        console.log (items); // here in responsive mode shows 5 (NOT CORRECT)
     });

      $('.slider').slick({
	    slidesToShow: 5,
	    responsive: [
			{
			  breakpoint: 768,
			  settings: {
				slidesToShow: 2				
			  }
		  ]    
      }); 

      var items = $('.slider').slick('slickGetOption','slidesToShow');
      console.log(items); // here in responsive mode shows 2 (CORRECT)

    });

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md
