### ISSUE TITLE
using ajax to load slider .. but error arise cannot read property 'add' of null

### ISSUE THREAD

**Issue by mohdamir451** [kenwheeler/slick#1922]
I am using Ajax page loader with that i want to load slick slider every time image Gallery is shown .. but the problem is first content and slick slider load properly .but second time onward slick slider shows 

Error :Uncaught TypeError: Cannot read property 'add' of null

**Comment by ahmadalfy** [comment]
Are you tryint to initalize slick on the a slider that has been initalized already?

**Comment by mohdamir451** [comment]
yes

**Comment by mohdamir451** [comment]
if i am not initalize slick  slider everytime then slick slider load for first time after that gallery are shown as shown :http://www.eventfaqs.com/news/ef-11407/iifa-utsavam-in-hyderabad-re-scheduled-for-january-to-include-a-fund-raiser-to-support-chennai

**Comment by mohdamir451** [comment]
ias.extension(new IASSpinnerExtension({
            src: '/images/loaderGif.gif', // optionally
        }));
     
        ias.on('rendered', function (items) {
            var $items = $(items);            
            console.log('Rendered ' + $items + ' items from server');
            var el = document.body;
            if (typeof gapi !== "undefined") { gapi.plusone.go(el); }
            if (typeof FB !== "undefined") { FB.XFBML.parse(el); }
            if (typeof twttr !== "undefined") { twttr.widgets.load(); }

            if (typeof (IN) != "undefined") { IN.parse(); }
            $('img').each(function () {
                $(this).removeAttr('style');
             });
            
            /* $('.slider-for').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            fade: true,
            slide: 'li',
            adaptiveHeight: true});*/
        })
     
        ias.extension(new IASTriggerExtension({ offset: 1000 }));
        ias.extension(new IASNoneLeftExtension({ text: 'No more results to display' }));
        ias.extension(new IASPagingExtension());
        ias.extension(new IASHistoryExtension({ prev: '.prev a' }));
        $.ias().on('pageChange', function(pageNum, scrollOffset, url) {
     });

**Comment by mohdamir451** [comment]
var ias = $.ias({
            container: "#content_2",
            item: ".blgitem",
            pagination: "#pagination",
            next: ".next",
            negativeMargin: 750,
            delay: 500
        });

        ias.extension(new IASSpinnerExtension({
            src: '/images/loaderGif.gif', // optionally
        }));
     
        ias.on('rendered', function (items) {
            var $items = $(items);            
            console.log('Rendered ' + $items + ' items from server');
            var el = document.body;
            if (typeof gapi !== "undefined") { gapi.plusone.go(el); }
            if (typeof FB !== "undefined") { FB.XFBML.parse(el); }
            if (typeof twttr !== "undefined") { twttr.widgets.load(); }

            if (typeof (IN) != "undefined") { IN.parse(); }
            $('img').each(function () {
                $(this).removeAttr('style');
             });
            
            /* $('.slider-for').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            fade: true,
            slide: 'li',
            adaptiveHeight: true});*/
        })
     
        ias.extension(new IASTriggerExtension({ offset: 1000 }));
        ias.extension(new IASNoneLeftExtension({ text: 'No more results to display' }));
        ias.extension(new IASPagingExtension());
        ias.extension(new IASHistoryExtension({ prev: '.prev a' }));
        $.ias().on('pageChange', function(pageNum, scrollOffset, url) {
     });

**Comment by ahmadalfy** [comment]
This is because in your code everytime new content is added you try to add initalize slick again on all sliders on the page as I mentioned. You have to change this selector `$('.slider-for')` so select only the new sliders being added to the page. I don't know I didn't use infiniteAjaxScroll before so this code might not work:

```
$items.find('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      fade: true,
      slide: 'li',
      adaptiveHeight: true
});
```

**Comment by mohdamir451** [comment]
thanx ahmadalfy ...it work
