### ISSUE TITLE
Browser Compatibility Info

### ISSUE THREAD

**Issue by JarolinVargas** [kenwheeler/slick#1923]
Lately I've been encountering many plugins that don't include browser compatibility info anywhere. Can you please include the browsers Slick is compatible with somewhere in the description. Thank you.

Also would this plugin work well as a fullscreen slider? something similar to the apple.com website slider?

Does the plugin slide any HTML content?

**Comment by ahmadalfy** [comment]
:+1: 

This should have been mentioned before. Slick works with IE8+ and the rest of the modern browsers.

Regarding your question, I have seen people doing mysterious shit using slick with CSS. So yes it can be used like a fullscreen slider you will have to craft the CSS.

And yes, the slider doesn't just slide images. It slides any HTML content within
