### ISSUE TITLE
Filtering several classes.

### ISSUE THREAD

**Issue by Olexiy665** [kenwheeler/slick#1926]
Hello, how I can show several classes, by filtering? 
When I do this "$('.hotel').slick('slickFilter', '.room-2', '.room-3')" it' s show only '.room-2' class. 
Help me please.

**Comment by ahmadalfy** [comment]
If you check the documentation, you will find that the arguments that `slickFilter` accepts is a *selector* or a *function*. This jsfiddle demonstrate how to achieve what you are trying to achieve: http://jsfiddle.net/ahmad/fmo50w7n/148/

Using jQuery you can return elements with different selectors like this `$('.filter-1').add('.filter-2')`

You can also use a function to perform more sophistacted operations.
