### ISSUE TITLE
Toggle Off Responsive

### ISSUE THREAD

**Issue by seansean11** [kenwheeler/slick#193]
I'm looking for a way to toggle off the carousels responsiveness, so that the children don't get their width set by the plugin.  I'd like to have my images maintain their original width and height (they are all the same size) and let them get cut off by the right side of the browser window, naturally (no need to center).

I attempted to achieve this by setting `infinite` to `false` and setting `width: auto !important;` to the carousel items in my CSS, but this causes issues with the `slidesToShow` setting.  Am I missing something here, or is this just not a possibility?

**Comment by rasmuscnielsen** [comment]
Hi !

I encounter this problem as well - I'm not sure how variableWidth solves it. Could you please post a code example? Simply adding the line does not solve anything for me.

![udklip](https://cloud.githubusercontent.com/assets/8465957/5802261/8b819b24-9ff3-11e4-9b9d-d1625a499614.PNG)
![udklip](https://cloud.githubusercontent.com/assets/8465957/5802275/ab3b0ba8-9ff3-11e4-9806-26c1560a00e5.PNG)

Thank you so much in advance!
