### ISSUE TITLE
delay afterchange events

### ISSUE THREAD

**Issue by krizz07** [kenwheeler/slick#1934]
hello, i've been using slick for awhile and currently i want to animate some divs after the slide changed with delay, here is my current code:

     $('.slides').on('afterChange', function(event, slick, currentSlide, nextSlide){
        
        $('.display').delay( 2000 ).slideDown(700);
    });

apparently the delay function starts right after the slides initialized,not after the slide change. I wonder if my code is wrong somewhere, thanks

**Comment by ahmadalfy** [comment]
Please create a jsfiddle showing what you are trying to acheive
