### ISSUE TITLE
Slick gallery does not load when called on infinite scrolling page

### ISSUE THREAD

**Issue by yamhaihum** [kenwheeler/slick#1935]
Hi Everyone

Basically I have implement slick earlier too but this time there was new challenge. The client wanted infinite scroll of pages and in some page the slick slider is there. 

When the page is loaded for the first time then the slider is fine it loads properly but if in the subsequent page if there is a gallery then it gives me an error. 

You can check the page on this url http://www.eventfaqs.com/news/ef-11381/toast-events-launches-first-ever-store-of-one-friday-with-harshali-malhotra--rajiv-makhni (as of now i have removed the code of initializing the slick slider but the moment i add that code then it gives me an error as "Uncaught TypeError: Cannot read property 'add' of null"

Can you please let me know what is the issue.

**Comment by ahmadalfy** [comment]
Did you remove the whole slider component or just the part that initalize slick? If you can add post here the code required to initialize slick that would be help us try it.

**Comment by Lindsayanng** [comment]
You have to re-initialize slickslider on the elements because they did not exist in the DOM when it was first initialized. Basically you will want to hook into the infinite scroll script and destroy and initialize slick slider the same way you do in a (document).ready() but inside the infinite scroll action.

**Comment by yamhaihum** [comment]
Thanks Lindsayanng, your tip was pretty helpful, earlier in our infinite scroll on rendered event we use to initialize the slider every time, now we are using the below code to find the slider and initialize the same slider again.
like below

$items.find('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      fade: true,
      slide: 'li',
      adaptiveHeight: true
});
