### ISSUE TITLE
Clicking slide in nav does not refresh the sync

### ISSUE THREAD

**Issue by kurdt94** [kenwheeler/slick#1938]
I have an issue with slides not showing when using the navigation slide. This occurs when i have less images than specified in the slidestoshow setting. The slideshow is behaving correctly when the navigation buttons show. ( the slideshow has enough images ) 

[markup.txt](https://github.com/kenwheeler/slick/files/49577/markup.txt)

**Comment by ahmadalfy** [comment]
Please create a jsfiddle demonstrating the problem
