### ISSUE TITLE
useTransform option in docs - please merge #1714

### ISSUE THREAD

**Issue by nevace** [kenwheeler/slick#1939]
<del>I was wondering why I couldn't see any difference between JS or CSS animation and couldn't see and CSS animation in the DOM. I looked through the source and saw that useTransform is set to false by default and useCSS is only set to true if useTransform is also true.</del>

<del>Is this a recent change? Either it needs to be in the docs or set to true by default. Or have I got the complete wrong end of the stick? I only noticed it because the CSS easing wasn't making a difference. What a performance increase when it's on though!</del>

Scrap all the above, I just saw #1632 and can see that the docs have been updated #1714 but not merged yet.

**Comment by ahmadalfy** [comment]
@kenwheeler check this out
