### ISSUE TITLE
Setting slidesToShow: 0 freezes chrome tab.

### ISSUE THREAD

**Issue by JarolinVargas** [kenwheeler/slick#1942]
setting  "slidesToShow: 0" freezes Google Chrome.

**Comment by ahmadalfy** [comment]
Working fine on Google Chrome here
http://jsfiddle.net/ahmad/fmo50w7n/160/

Why would anyone set `slidesToShow` to 0 ?

**Comment by JarolinVargas** [comment]
When setting the option using data-attribute, for example http://jsfiddle.net/fmo50w7n/167/

set the attribute value to 0 on the slider element.

No one will set it to 0, but is it weird that it freezes the entire site when it is 0?

**Comment by ahmadalfy** [comment]
It doesn't make any sense setting it to 0 ... You are selecting the number of the slides to show. Isn't it weird if you set it to `lizzard` ? The same is with `0`.

**Comment by JarolinVargas** [comment]
I know it's an issue no one will ever encounter. But why does the tab freeze to the point where it can't even be closed? It may not be worth fixing, just wanted to point it out. Still can't close the jsfiddle tab. It's just stuck reloading.
