### ISSUE TITLE
Center calculation is wrong when window has an almost square aspect ratio

### ISSUE THREAD

**Issue by Lindsayanng** [kenwheeler/slick#1943]
I am finding that when my window or container is almost square in size (or generally taller in height than the slide's height) that the slider loads with the starting image off centered. 

Here are the screenshots 
http://cl.ly/image/2z153O32331C
http://cl.ly/image/3R023k3s0x2D
http://cl.ly/image/0l0Q1n2j2s0t

here is my slick code: 
```javascript
function slick(){
jQuery('.variable-width').slick({
  dots: false,
// to account for single-slide sliders
  infinite: (jQuery('.variable-width').children().length < 2) ? false : true,
  speed: 500,
  slidesToShow: 1,
  centerMode: true,
  variableWidth:  true
});

}
```
I am working out an example now but wanted to get this issue up and raised to see if anyone can replicate

**Comment by Lindsayanng** [comment]
Ah I figured it out. You have to have the width of your slide (or the image contained within it) set to a specific width before allowing .slick() to apply to your slide items. Rearranging my code that sets the width on each image fixed my issue.

**Comment by mcashley** [comment]
Closing ... sounds like problem solved
