### ISSUE TITLE
Variable width and no infinite issue align left

### ISSUE THREAD

**Issue by mushberry** [kenwheeler/slick#1944]
Hello.

I'm using Slick on a variable width list with infinite and centerMode false, the thing is that when I'm navigating to the last items on the slider a white space is appearing on the right, so, when my current slide is the last one I only see it, aligned on the left instead of stoping at the right end.

Can you help?

**Comment by mcashley** [comment]
Closing for now... Please add a JSFiddle and request to re-open or refer to support materials if you just have a question.
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#support
