### ISSUE TITLE
how to set the initialslide as the last item in an array? help!

### ISSUE THREAD

**Issue by edmundcwm** [kenwheeler/slick#1947]
I'm aware of the 'initialSlide' setting but my slides are stored in an array and I would like to display the last item as the first slide.

Here is the markup:

             <?php 
                $tags = get_terms(array('award_accolade_tag'), array('hide_empty' => true, 'order' => 'ASC'));
                //echo '<pre>'; print_r($tags);
                $counttags = count($tags);
                foreach ($tags as $tag) {
            ?>
            <div class="col-md-12">
                <div class="col-md-12">
                    <h4 style="margin-top:2px;"><i><?php echo $tag->name;?></i></h4>
                </div>
           </div>

Javascript:

        <script>

          $(document).ready(function () {
	
			$('#awarrds-slider').on('init', function (event, slick) {
                       //currentSlide is undefined on init -- set it to 0 in this case (currentSlide is 0 based)
                       var totalslides = slick.slideCount-2; //this is the value i want to display as the initialslide
	               
                        });
          $('#awarrds-slider').slick({
            //dots: true,
            infinite: false,
            speed: 300,
            slidesToShow: 1,
            slidesToScroll: 1,
            initialSlide: //i want the variable totalslides to be the initialslide but the 'initialslide' argument only    
             accepts integers
            });

             });
         </script>

**Comment by DumboJetEngine** [comment]
It would be nice to have initialSlide accept values outside the available range and move the real index inside the range and as close as possible to the provided index.
I would like that too.
I think it is not supported though...

**Comment by DumboJetEngine** [comment]
What I did was to get the number of rendered divs inside my slider (before making it a slider and after the document was ready) and then put the `length-1` in `initialSlide`.
Worked! :)

**Comment by leggomuhgreggo** [comment]
Hey, looks like @DumboJetEngine has found a solution. Thanks! Closing.
