### ISSUE TITLE
cssEase option not working

### ISSUE THREAD

**Issue by x6ax6b** [kenwheeler/slick#1950]
Why current version(1.5.9) is default option 'useTransfrom: false'?
So I set 'useTransform: true', and ease working.

**Comment by sergiop** [comment]
Thanks @x6ax6b, you saved my day! :-)

**Comment by bensagardoy** [comment]
You saved my day too :)
Thanks

**Comment by mcashley** [comment]
This does not seem to be an issue more than a helpful hint. Maybe need some documentation on useTransform option

Closing as it has a duplication in #1997.
