### ISSUE TITLE
A 100% width carousel overflows horizontally.

### ISSUE THREAD

**Issue by grjkz** [kenwheeler/slick#1954]
I initialized slick with no options on a 100% width div and it caused a slight overflow-x. I couldn't figure out what was causing this so I ended up using overflow: hidden on the slick target. Everything looks like it has the same width as the window except for `div.slick-track` which is necessary.

This happens on both Chrome and Firefox.

If you look at the bottom-right of the viewport, you'll see that the footer (which is width:100%) has whitespace to the right of it which is caused by the carousel.
![screen shot](https://cloud.githubusercontent.com/assets/13038470/11708297/b420d530-9edb-11e5-917e-597e1c59757f.png)

Is there a way to avoid having to use overflow:hidden on the target or is that supposed to be the accepted fix?

**Comment by mcashley** [comment]
Closing as this is a support question.
For support see: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#support

**Comment by twairball** [comment]
Hi - I think this is a bug?

With `width: 100%;` the carousel target causes `overflow-x`, which includes the `dots`. Setting `overflow: hidden;` will conceal the `dots`.
