### ISSUE TITLE
variableWidth=true and images getting extra big

### ISSUE THREAD

**Issue by yrguner** [kenwheeler/slick#1956]
Hi there. Thx for your great coding. We have bought kalium theme from themeforest for our web site. they use your code as carousel portfolio template. here is their example (http://demo.kaliumtheme.com/main/portfolio/bergenfield/). by default variableWidth=false in this theme. and carousel fix all images to equal widht(so portraitse will extend vertically) but we want the images have all the same height cause we have lots of portrait mode photos of building(as an architectural firm).

so when i set the variableWidth=true we have another problem as you may see in our exapmle page.

http://iskurtinsaat.com/portfolio/panorama-salacak/

any idea how to set things? thx

**Comment by mcashley** [comment]
Closing as this is a support issue versus a code issue.
Please see: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#support
