### ISSUE TITLE
variableWidth and Infinite gives a white space issue

### ISSUE THREAD

**Issue by tenold** [kenwheeler/slick#1959]
View Fiddle here: http://jsfiddle.net/tenold/t8apgqt9/

Basically when you keep clicking next, once it gets to the end there is a white space before you hit next again.

Is there anyway to get rid of this extra spacing that causes an odd experience?

Screenshot:

![Screenshot](http://i.imgur.com/wztIdYR.png)

**Comment by foued611** [comment]
i have the same Problem.

**Comment by Mikorinnn** [comment]
That issue is already considered as a bug [here](https://github.com/kenwheeler/slick/issues/1207).

**Comment by mcashley** [comment]
Closing this issue as it is a duplicate. Please follow this issue: https://github.com/kenwheeler/slick/issues/1207
