### ISSUE TITLE
Slide flickers when going from last to first slide

### ISSUE THREAD

**Issue by yangkennyk** [kenwheeler/slick#1961]
Have been researching possible fixes for this and just cannot figure out what's wrong. 

The issue seems to only be in chrome. But it doesn't happen in Chrome Canary.

http://jsfiddle.net/de2yzzds/6/ (use arrow keys to navigate and I also need the html this way)

The slide flickers when it goes from the last slide to the first slide

I'm on a mac using Chrome Version 47.0.2526.80 (64-bit)

Saw this solution https://github.com/kenwheeler/slick/issues/1890 but it doesn't seem to work.

Can anyone else recreate the issue?

![sliderblink](https://cloud.githubusercontent.com/assets/6680040/11733964/5469ecae-9f70-11e5-97d1-ab306aaed43d.gif)

**Comment by ninjaonsafari** [comment]
@yangkennyk have you investigated on this issue?

**Comment by ninjaonsafari** [comment]
If you go in the different direction it happens on the last slide and on the other side from the slide.

**Comment by yangkennyk** [comment]
@ninjaonsafari yep. it seems to happen when it goes from first to last/last to first. 

I haven't found a solution yet.

**Comment by yikman** [comment]
@yangkennyk, I had a similar issue and i got mine fixed

.slick-track,
.slick-list {
      -webkit-perspective: 2000;
      -webkit-backface-visibility: hidden;
}

**Comment by simeydotme** [comment]
@yikman ! great comment, can @yangkennyk try and confirm if it works? -- if so, I've love to merge a PR for this in the slick css file, @yikman -- if you're up for it?

**Comment by yikman** [comment]
@yangkennyk, just awaiting for confirmation whether code above fixes your issue. 

My bug was: Latest version Chrome - Mac/Windows. First to last / last to first slide, flicker white background appearing. 

@simeydotme, yeah that will be cool, once @yangkennyk confirms this is a fix for him.

**Comment by polarbirke** [comment]
Quick heads-up: I had the same issue and @yikman's fix worked for me.

**Comment by yikman** [comment]
@polarbirke, only down side for using (-webkit-perspective: 2000;), all IOS devices - it will become blur.

**Comment by damianwajer** [comment]
`-webkit-perspective: 2000px` fixes this issue (note the unit which is required according to docs: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective), [W3C](https://www.w3.org/TR/css3-values/#lengths)).

**Comment by krozola** [comment]
@yikman your solution fixed it for me too.

**Comment by DoubleMarv** [comment]
@yikman worked for me too - thanks

**Comment by eugeneAamplify** [comment]
Im still having this problem. Especially when I have SVGs in the container that are animated. Just shows black SVGs!

**Comment by Yonn-Trimoreau** [comment]
@yikman Your solution works, thank you.
But fix is currently not available/not working in latest Slick release..

**Comment by wpcoderca** [comment]
I'm also experiencing the same issue. I've tried multiple fixes but nothing seems to solve it.

**Comment by puigandrew1** [comment]
Also not working for me.

**Comment by amearini** [comment]
None of the above solutions worked for me. However I noticed one thing. I'm working with a MacBook retina with a standard HD second screen. The flickering seems to happen only with Chrome on the retina screen but not on the other one. Latest versions of Safari/Firefox/Opera for mac are not presenting the issue. I'm no expert and can't figure a solution. But maybe this might help in finding a solution.

**Comment by Danoweb** [comment]
Hello, I'm working on a project which runs on a google Chromecast (Chrome Browser).  When looping back to the first slide in autoplay, I am seeing this `flicker` issue as well, even after applying the mentioned hack above by @yikman .  Is there a planned fix for this in Chrome browsers? Thank You!

**Comment by Danoweb** [comment]
Just a quick update I found from another issue #1890 --- the use of `useTransform: false` will prevent this flickering effect on Google Chrome (and Chromecast).

**Comment by nikotomad** [comment]
@Danoweb 's fix worked for me! Mad props to you buddy.

**Comment by yayMark** [comment]
I found this to work for my case. Same fix as someone else, different class.

.slick-slide { -webkit-backface-visibility: hidden; }

**Comment by amichel86** [comment]
Thanks @yayMark for your solution.

Will this be fixed eventually or it's a Chrome bug?

**Comment by AdamColton8** [comment]
it helped me

```
.slick-slide,
.slick-slider .slick-track,
.slick-slider .slick-list
{
  -webkit-transform: translate3d(0, 0, 0);
  -moz-transform: translate3d(0, 0, 0);
  -ms-transform: translate3d(0, 0, 0);
  -o-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);

  -webkit-transform: translateZ(0);
  -moz-transform: translateZ(0);
  -ms-transform: translateZ(0);
  -o-transform: translateZ(0);
  transform: translateZ(0);

  -webkit-perspective: 1000;
  -moz-perspective: 1000;
  -ms-perspective: 1000;
  perspective: 1000;
  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  -ms-backface-visibility: hidden;
  backface-visibility: hidden;
}
```

**Comment by pablogiralt** [comment]
Thanks @yayMark. Your solution fixed it for me:

.slick-slide { -webkit-backface-visibility: hidden; } .

**Comment by sirgru** [comment]
I have tried the solutions from this page and only Danoweb's fix worked for me. However, it makes the sliding slower. `.slick-slide { -webkit-backface-visibility: hidden; }` fix makes the flicker full width on my end, which makes it subjectively worse.

**Comment by css3coder** [comment]
> Just a quick update I found from another issue #1890 --- the use of slick option: `useTransform: false` will prevent this flickering effect on Google Chrome (and Chromecast).

Thanks @Danoweb for your solution. Only it defeated this bug.
I still recommend adding an option: easing: 'swing', to return smoothness.

**Comment by audi0slave** [comment]
Hello everyone, just mentioning that what it worked better for me was binding a `init` event before initializing slick as described in the ReadMe.

Basically I used CSS to hide the container and after slick initializes I show the container back. Something like this should do the trick:

```
// css
.myContainer { display: none; }

// .js script
$(".myContainer").on("init", function() { $(this).show(); }).slick({options});;
```

Hope it helps future readers.

**Comment by chicong065** [comment]
This one works for me:

```
.slick-list,
.slick-track {
  transition-delay: 10ms;
}
```

**Comment by Corina-s15** [comment]
> This one works for me:
> 
> ```
> .slick-list,
> .slick-track {
>   transition-delay: 10ms;
> }
> ```


@chicong065  You are sure? This doesn't work...

**Comment by amichel86** [comment]
@Corina-s15 unless you still support a site with Slick, I would suggest Swiper or Flickity that are still maintained ;)

**Comment by DynamicVishvaGIT** [comment]
> This one works for me:
> 
> ```
> .slick-list,
> .slick-track {
>   transition-delay: 10ms;
> }
> ```

thanks

**Comment by DynamicVishvaGIT** [comment]
> This one works for me:
> 
> ```
> .slick-list,
> .slick-track {
>   transition-delay: 10ms;
> }
> ```

It is working

**Comment by Xuanwinnie** [comment]
> 這對我有用：
> 
> ```
> .slick-list,
> .slick-track {
>   transition-delay: 10ms;
> }
> ```

[chicon065](https://github.com/chicong065) worked for me too - thanks

**Comment by kripalser** [comment]
> This one works for me:
> 
> ```
> .slick-list,
> .slick-track {
>   transition-delay: 10ms;
> }
> ```

Nothing else helped in my case, but I had to change the delay from `10ms` to `50ms` to make it work (Mac, Chrome, Slick 1.8.0).
