### ISSUE TITLE
Add class if "slidesToShow" is more/less than slide count

### ISSUE THREAD

**Issue by lsterling03** [kenwheeler/slick#1966]
I think it would be helpful to add a class to the .slick-slider div to indicate when the slide functionality is activated -- as dictated by the number of slides versus the slidesToShow number.

For example, if I've set the carousel to show 3 slides at a time, but I only have 2 slides, then I want to style the overall carousel differently than when it's got more than 3 slides and thus showing the prev/next buttons. Unfortunately, there is no class change on the main carousel div to indicate any difference between the two states.

I tried adding a class on the "init" event by determining if the prev/next buttons exist, but that didn't work because the prev/next buttons are created after init, I guess. So I got it to work by editing slick.js here (see where I added the class 'foo' below). 

Would you consider adding something like this in a future update? Or tell me if there's a better way for me to get this class on the .slick-slider div? Thank you!

    if( _.slideCount > _.options.slidesToShow ) {
				
	          $('.slick-slider').addClass('foo');

                _.$prevArrow.removeClass('slick-hidden').removeAttr('aria-hidden tabindex');
                _.$nextArrow.removeClass('slick-hidden').removeAttr('aria-hidden tabindex');

                /* other code removed for brevity */
                }

            } else {
				
		      $('.slick-slider').removeClass('foo');

                _.$prevArrow.add( _.$nextArrow )

                    .addClass('slick-hidden')
                    .attr({
                        'aria-disabled': 'true',
                        'tabindex': '-1'
                    });

            }

**Comment by lsterling03** [comment]
As I think about, I think it would be more helpful to do the reverse of what I did. That is, to add the "foo" class when prev/next are disabled, and remove it when they're enabled. I would imagine the main use-case for this would be when the slider is not functioning, and you want to style it differently to account for that.

**Comment by simeydotme** [comment]
http://jsfiddle.net/jhkcyzz1/2/
I appreciate that you were a little confused if this was possible or not, but better to ask in the correct support forum first before raising an issue. Please read the contribution guidelines for help.

Best, Simon.

**Comment by BryanBarrera** [comment]
@simeydotme your fiddle helped me! Thanks man

**Comment by BryanBarrera** [comment]
The way it works is it gets the option of SlideToShow. Which is cool. But what if the slideToShow equals 3 but the content editor just has 2 'slides' - the counter will say something like 3 of 2 slides - which makes no sense. How can we get the actual value of the total "visible slides" rather than getting the option? @simeydotme
