### ISSUE TITLE
Stop last slide at the right end side when infinite: false and variableWidth: true.

### ISSUE THREAD

**Issue by alrdytaken** [kenwheeler/slick#1968]
At the moment with each next-click a slide will be positioned to the left end side.
This leads to whitespace on the right when the last slide is moved in which is shorter then the slider itself.

Having an option to stop the last slider at the right end side would be great.

**Comment by alexweb** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Similar to #1207.

**Comment by rrubbico** [comment]
Hitting this problem now with my project. Any progress made?

**Comment by leggomuhgreggo** [comment]
My feeling is that this is covered by #1207, which is the primary tracking task.

It's a tricky issue with cloning. Check out the discussion in #1207.

**Comment by RafaelRumpel** [comment]
Same problem here.

**Comment by foysalremon** [comment]
@kenwheeler may not have solved this issue yet. I have made a quick jQuery solution for my current project. This may help you for now[https://codepen.io/foysalremon/pen/KoWjLg](url)

**Comment by topnotchbiz** [comment]
The only way to do is to slide back the current to prev slide. Here is code:
  slickSlider.on('afterChange', function(e, slick) {
    var lElRect = slick.$slides[slick.slideCount - 1].getBoundingClientRect();
    var rOffset = lElRect.x + lElRect.width * 2;
    var wraRect = $wgSlider[0].getBoundingClientRect();

    if (rOffset < (wraRect.x + wraRect.width)) {
      slick.slickPrev();
    }
  });

**Comment by belendura** [comment]
>
Trying to implement your solution @yinjinit, what is $wgSlider[0]?

**Comment by Morjebote** [comment]
You can check
`if ($('.slick-slide:last-child').hasClass('slick-current'))`
than add class to the elements you want to change (all slides or just couple of last ones),
and then add to that class 
`transform: translateX(*whatever you need*)`

**Comment by belendura** [comment]
Thanks for your answer :)
