### ISSUE TITLE
CSS rules doesnt seem to get copied to the clone elements when slick is configured with infinite:true

### ISSUE THREAD

**Issue by Grahnz** [kenwheeler/slick#1969]
CSS rules doesnt seem to get copied to the clone elements when slick is configured with infinite:true

**Comment by AndQuizi** [comment]
The cloned elements don't get assigned ID's, which is to prevent any problems with having a duplicate ID. The only solution that I know of is to use class selectors rather then ID selectors for your CSS elements.

**Comment by simeydotme** [comment]
please refer to the [contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)
​ to have your issue reopened :smile: 

Best, Simon.
