### ISSUE TITLE
Add onClick callback for slides

### ISSUE THREAD

**Issue by cdtweb** [kenwheeler/slick#197]
Add onClick callback (optional) for when individual slides are clicked.. 

I'm basically achieving this right now by registering a click handler for each slide in the `onInit` callback:

``` js

onInit: function(slick){
    slick.$slides.each(function(index, slide){
        console.log('slide #' + index + ' has been clicked!');
    });
}

```

This seems to work, but it would be nice if there was an easier way to achieve this..

**Comment by dharmeshparekh** [comment]
how can i get index of clicked side? i am able to get click event when i click on slide

**Comment by antipenko** [comment]
@dharmeshparekh , sure. Lile this 

$('.your-slider').on('click', function (e){
        let slideClicked = $(e.currentTarget).attr("data-slick-index");
        console.log(slideClicked);
    });

**Comment by Yolito** [comment]
$('.banner').click(function (e) { alert($('.banner .slick-active').attr('data-slick-index')); }); 

This solved the problem for me. Where .banner must be the class name of your slider.

**Comment by stla** [comment]
I do as follows:

```
$("#my_slick").on("click", function(e){ 
    var slideClicked = $(this).find(".slick-active").attr("data-slick-index"); 
    console.log(slideClicked); 
});
```

**Comment by sagive** [comment]
nothing of the methods here work... if you have a one frame slider you can listen to click on the parent but not on the slide itself.

**Comment by coderNik** [comment]
This works well
$('#slider_co .slick-slide').on('click', function (e){ let slideClicked = $(e.currentTarget).attr("data-slick-index"); console.log(slideClicked); });
