### ISSUE TITLE
Keep source files and compiled files in different folders

### ISSUE THREAD

**Issue by yangm97** [kenwheeler/slick#1974]
Preventing errors like this one
![screen shot 2015-12-16 at 18 55 33](https://cloud.githubusercontent.com/assets/4412002/11853697/a11cc8b8-a426-11e5-9289-96dea735cc31.png)
(I know one can work around this error by adding .scss to the import, but it's not ideal)

Ideally, "compiled" files like .css files, .min.js etc, should go into a folder (like /dist/) while the original source files could go into folders like /js/, /scss/, etc.

**Comment by matzke** [comment]
+1 (improves sw architecture)
