### ISSUE TITLE
Slider Syncing bug

### ISSUE THREAD

**Issue by rhodesman** [kenwheeler/slick#1975]
When you setup two sliders (one to control the other) and set the sliders to not infinite, the controlled slider will move one place more than the controller slider at the ends when using the arrows.  So if you have 5 slides the controller will have slide 5 selected and the controlled slider will be showing slide 4 or slide 1.  This is with using the arrows on the controller.  if you manually click on slide 5 in the controller, the controlled slider will show slide 5 properly.  

My slick slider JS settings are as follows:
$('.desktop-content').slick({
  slidesToShow: 1,
  slidesToScroll: 1,
  arrows: false,
  fade: true,
  asNavFor: '.desktop-solutions'
});

$('.desktop-solutions').slick({
infinite: false,
slidesToShow: 4,
slidesToScroll: 1,
asNavFor: '.desktop-content',
centerMode: false,
focusOnSelect: true
});

**Comment by ariona** [comment]
have you tried my approarch to solve syncing issue? https://github.com/kenwheeler/slick/issues/1971#issuecomment-165313300

**Comment by mpy-pixum** [comment]
I have  actually the same problem that die nav-for ist not syncing with the closest stage slider.

**Comment by mpy-pixum** [comment]
any ideas how to solve and not to modify the slick.js

**Comment by ariona** [comment]
Hi @mpy-pixum in my case, i have solved it by adding afterChange function. maybe that can help you too https://github.com/kenwheeler/slick/issues/1971#issuecomment-165313300

**Comment by aaron-nls** [comment]
https://codepen.io/athemix/pen/RwNVYmw

It happens on this demo...if you press next on the last slide, the other slide overshoots what slide it should be on.
