### ISSUE TITLE
Error on gulp

### ISSUE THREAD

**Issue by sankaran8** [kenwheeler/slick#1978]
I get following error on gulp. 

{ type: 'Parse',
  filename: '/bower_components/slick-carousel/slick/slick-theme.css',
  index: 686,
  line: 33,
  callLine: NaN,
  callExtract: undefined,
  column: 21,
  extract: 
   [ '    padding: 0;',
     '    margin-top: -10px\\9; /*lte IE 8*/',
     '    -webkit-transform: translate(0, -50%);' ],
  message: 'Unrecognised input in file bower_components/slick-carousel/slick/slick-theme.css line no. 33',
  stack: undefined,
  lineNumber: 33,
  fileName: 'bower_components/slick-carousel/slick/slick-theme.css',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function] } }

Line 33 in slick-carousel/slick/slick-theme.css

margin-top: -10px\9; /*lte IE 8*/

**Comment by mcashley** [comment]
No JSFiddle - closing

**Comment by thasmo** [comment]
Happens for me too. The less-compiler has problems parsing `margin-top: -10px\9; /*lte IE 8*/`.

**Comment by leggomuhgreggo** [comment]
There's a [PR to remove the style](https://github.com/kenwheeler/slick/pull/2071). It's there as a fallback for IE8. 

The LESS versions of the styles use the LESS string escaping syntax, which should fix the exception.
