### ISSUE TITLE
slide width calculation error on ios chrome ( real device only )

### ISSUE THREAD

**Issue by danielt69** [kenwheeler/slick#1979]
Hi guys, I have a frustrating bug only on ios device (iphone 6) on chrome browser - all updated to the latest version. using slick version 1.5.8.  the slider width is way too much - overflowing the body's width.

Link for the page: http://www.onlinecasino-austria.at/mr-green/
Tmage is attached!
Thanks in advance

![img_0003](https://cloud.githubusercontent.com/assets/3322065/11919681/effc81a6-a761-11e5-86c8-9657a077fdbb.PNG)

**Comment by kenwheeler** [comment]
Have you tried applying box-sizing: border-box?

**Comment by kenwheeler** [comment]
Also, is the container set to 100% width

**Comment by danielt69** [comment]
Tried it. It's still not working...  any ideas?

**Comment by danielt69** [comment]
I managed to fix it! my slider width should be 100% - 15px padding on each side, so I gave the main slider "width:calc(100vw - 30px);" and it fixed it.
