### ISSUE TITLE
Bug when using decimal points for slidesToShow(e.g. slidesToShow: 4.4)

### ISSUE THREAD

**Issue by CharlieGreenman** [kenwheeler/slick#1983]
When using decimal points for slick slider(e.g. slidesToShow: 4.4), and one goes to the last slide in
non-infinite mode, and one changes from landscape to 
portrait, or vice versa, slick slider disappears(does not
initiate properly).

**Comment by mcashley** [comment]
No JSFiddle - closing

**Comment by CharlieGreenman** [comment]
I have created a (jsfiddle)[https://jsfiddle.net/o8ga52nn/4/]. Feel free to re-open issue.

**Comment by simeydotme** [comment]
I can't debug minified files... can you please make sure you're using the latest unminified version from Master Branch :)

**Comment by CharlieGreenman** [comment]
My apologies, I do hope this suffices: https://jsfiddle.net/o8ga52nn/8/
