### ISSUE TITLE
possible to integrate with jQuery UI Sortable?

### ISSUE THREAD

**Issue by r3wt** [kenwheeler/slick#1988]
I've tried and it doesn't play nice:

code so far:

```html
	<div class="row">
		<label><strong>Meeting Keynotes:</strong>
			<div class="columns">
				<label>Drag to select:
					<div class="columns no-pad" id="slick-select">
						<div class="button warning">Tax</div>
						<div class="button warning">Hedge Funds</div>
						<div class="button warning">Financial Analysis</div>
						<div class="button warning">CPA Exam</div>
						<div class="button warning">Wealth Management</div>
						<div class="button warning">Auditing</div>
						<div class="button warning">Microsoft Products</div>
						<div class="button warning">Quick Books</div>
						<div class="button warning">Legal</div>
					</div>
				</label>
			</div>
			<div class="columns">
				<label>Drop Here:
					<div class="columns no-pad c-sort" id="slick-drop">
					
					</div>
				</label>
			</div>
		</label>
	</div>
```

```js
	//setup slick/jqui interaction
	$.jqMVC.bindOnce(function(){
		$('#slick-select').on('init',function(){
			$('#slick-select .slick-track').addClass('c-sort');
			$('#slick-select .slick-track, #slick-drop').sortable({
			  connectWith: ".c-sort"
			}).disableSelection();
		}).slick({
			dots: false,
			infinite: true,
			speed: 300,
			slidesToShow: 1,
			centerMode: true,
			variableWidth: true,
			draggable: false
		});
	});
```

the problem is that slick swallows the elements (ie element dissapears at bottom of div) when trying to drag to the target preventing from dragging to that list. very annoying.

![img](http://puu.sh/m9J7x/35e14dc712.png)

**Comment by simeydotme** [comment]
that is not a good interface to start with... it looks like you're trying to make things easy for your user... but hiding items inside a carousel is just making it much more difficult :(

As for swallowing, it's because of overflow issues, I think. Not much you can do without destroying the carousel.

**Comment by r3wt** [comment]
The carousel is a permanent, necessary fixture for the application, which is an android app. a user may list as many skills as they like, so scrolling through and selecting from that list could be potential very tedious without the carousel.

I did modify the app's code to remove jQuery UI, but that revealed additional bugs with slick that are a deal breaker for our app. For now we have elected to remove slick. hopefully the issues present will soon be resolved.

![img](http://puu.sh/mbZWK/410592a52f.png)

**Comment by simeydotme** [comment]
If it's a mobile app with no desktop support, you're better off using a
scrolling div :)

**Comment by r3wt** [comment]
@simeydotme thanks for the tips simey. i think i'll try it.

**Comment by kenwheeler** [comment]
@r3wt interesting application. can you add overflow-y: auto? does it help this?

**Comment by r3wt** [comment]
@kenwheeler  i've already abandoned slick. using simeys advice, i built my own carousel last night.
