### ISSUE TITLE
Getting dotted line border around current slide

### ISSUE THREAD

**Issue by chassq** [kenwheeler/slick#1992]
I am seeing a dotted line border around the current slide when scrolling through. Any way to shut this off?

**Comment by mcashley** [comment]
No JSFiddle - closing

**Comment by chassq** [comment]
No brains... Not using your stupid control...

**Comment by marvinosswald** [comment]
That did it for me:

```css
.slick-slide { 
  outline: none;
}
```

**Comment by chassq** [comment]
Wow.. That was awesome! See how easy this is @mcashley. Instead of being a jerk and closing the issue without even asking me to provide a jsfiddle this kind person (i.e. @marvinosswald) has provided a solution to the problem. Ashely, you should take a lesson from Marvin on being helpful.

Thanks again Marvin!

**Comment by simeydotme** [comment]
Thanks @marvinosswald :grin: 

@chassq could you direct support queries to the appropriate channels in future, please. Also; You _were_ asked to provide a fiddle when opening the issue. You just missed/ignored it :+1: 

@mcashley is trying to help close non-issues; and when there (was) over 400 of them (mostly support / questions / not-bugs), it becomes difficult to repeatedly explain something that is clearly stated in the [contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), so please forgive him, maybe don't insult/attack him, and hop on [___Gitter___](https://gitter.im/kenwheeler/slick) if you have any future queries. :smile:  I notice all your Github contributions are support questions in bug-tracking software, so I'll assume nobody ever told you the difference between bug-tracking and support. I also note that Github is terrible at distiguishing the difference, too. So you have the benefit of the doubt. :wink: 

Best, Simon.

**Comment by chassq** [comment]
If its too hard to reply "send us a js fiddle" vs. "No JS Fiddle - Closing" then maybe you should consider not building on or participating in the product. Just a thought. Also, nothing in my statement was an attack. Just pointing out how bad that kind of interaction is. It had every bit the tone of a jerk. If you need more samples of how to do this properly then look at what @marcellscarlett sent. You should learn closing an issue does not solve an issue. Your canned reply in this situation should be "Send us a js fiddle". Really, how hard is that...

**Comment by leggomuhgreggo** [comment]
@chassq I'm am absolutely certain there was no offense intended.

Please consider that we have to prioritize our time--we're all doing this for free--and can't individually address every issue. It's more likely that we make efforts to give individual attention to issues, when the issue's submitter has made an effort.

In future, I recommend searching through old issues to see if there was a solution--this one has a healthy amount of predecessors--and consulting the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).

**Comment by chassq** [comment]
@leggomuhgreggo Thanks for the nice reply. In the future, I recommend remembering that anyone who makes the effort to download the product, use it and ask for assistiance is making a contribution.

**Comment by chassq** [comment]
To add on to that I fully appreciate your efforts but remember you guys are not the only busy ones in the world. The folks who use the products (and some of us also do work for free) have to download, read, assess, find samples and implement. When a question is raised any product dev team should look at that as contribution and not just support. We have taking our time to essentially test your product just by the act of using it. By the way, I did look through the repository prior to asking but found nothing at the time. If there are predecessors please point them out.

**Comment by leggomuhgreggo** [comment]
@chassq  [Here are previous issues addressing your question](https://github.com/kenwheeler/slick/search?utf8=%E2%9C%93&q=outline&type=Issues). I can appreciate that sometimes it's difficult to find the right terminology when searching.

We have contribution guidelines for the sake of everyone's busy schedules, and they help avoid unnecessary dramas. Obviously, there's no obligation to use this resource, and, since it's free, there's no entitlement to support. 

We all like helping people out here, which is why we spend our time doing it, but it's definitely better when communications are kept professional, without name calling and the like. I appreciate that the intent was to address a perceived issue with the library, and I hope we can continue forward, respectfully, with that shared purpose.

Just so there's no unpleasant surprises in future, we close issues without test cases to demo the issue, and we also close support requests. It's not meant to be personal; just a practical necessity. Even so more often than not, someone will take the time to answer a question, even when closed.

Thanks for your understanding.

**Comment by kenwheeler** [comment]
hey @chassq perhaps you should consider keeping your mouth shut. you haven't contributed shit to this repo. If you are gonna come on here and talk shit to my collaborators, go write your own slider.

**Comment by chassq** [comment]
Well I had accepted what @leggomuhgreggo had last written. He was polite and laid out his reasoning well. I may not agree but I respected what he had to say. Now this abuse.. You are sad Ken.. Plenty of other sliders to choose from... I hope your parents were nice to you...

**Comment by kenwheeler** [comment]
Shut up and get off my damn repo

**Comment by kenwheeler** [comment]
@chassq this is abuse? seems like you started off by using abusive language towards @mcashley . Dont show up here, with no open source projects of your own, talking shit with your participation trophy entitlement bullshit. How about you shut your mouth and go build something, then we can talk? And if you'd like to take it any further than that, come see me. In person. You entitled loudmouth.

**Comment by simeydotme** [comment]
:+1: +1 :fire: 




:popcorn:
