### ISSUE TITLE
Synced sliders autoplay not cycling in right order

### ISSUE THREAD

**Issue by matthewrobertluke** [kenwheeler/slick#1993]
Hi, 

Found an issue where two synced sliders aren't cycling through on autoplay in order correctly. After the first loop it rotates back to the middle slider and then changes direction.

You can see the issue in action here;

https://thisistap.com/

Thanks,

Matt

**Comment by mazzaker** [comment]
change line 52 in script.js to infinite: true and remove lines 61 65 67

**Comment by matthewrobertluke** [comment]
Thanks so much @mazzaker. Really appreciate the help!
