### ISSUE TITLE
Responsive issue: slides disappear 

### ISSUE THREAD

**Issue by virgiliud** [kenwheeler/slick#1995]
I'm using responsive breakpoints in my slide. On small screens i'm showing 1 slide at a time. 

If I navigate slides forward on a small screen and make the screen large again, the slides before that don't show and you cannot navigate back to them. 

Detailed example: I have breakpoints set to show 1 slide at a time on small screens and show more slides on big screens. I have 8 slides. If on a small screen I  navigate to slide 6 and make the screen large again,  the slides before 6 disappear.

**Comment by mcashley** [comment]
No JSFiddle - closing
