### ISSUE TITLE
images not showing

### ISSUE THREAD

**Issue by bcorber** [kenwheeler/slick#1996]
Hello,

First off thanks for the great slider! It's working 100% correctly on one of my sites.
I am encountering a weird problem where my images are being resized to a width of 0px and therefore the images are not showing up in the slider... 
Any help would be greatly appreciated

**Comment by guddu1315** [comment]
+ 1 same issue

**Comment by mcashley** [comment]
There is not way to determine what kind of problem you are having without a JSFiddle.
Please refer to this document before submitting issues: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required

Closing until more info received
