### ISSUE TITLE
cssEase not working

### ISSUE THREAD

**Issue by GijsGoudzwaard** [kenwheeler/slick#1997]
The cssEase from the docs does not work.

I've tried it with this piece of code on the latest build:
```
$(document).ready(function() {
    $('.fade').slick({
        dots: true,
        infinite: true,
        speed: 800,
        fade: false,
        slide: 'div',
        cssEase: 'cubic-bezier(0.950, 0.050, 0.795, 0.035)'
    });
});
```

It's exactly the same as using it without the cssEase.

**Comment by Michkkael** [comment]
Hello ! 
I had the same issue so I came back to v1.8.5 and it's working well.
I think it's related to last commits involving cssTransform property

**Comment by GijsGoudzwaard** [comment]
The latest version is 1.5.9, how are you on 1.8.5?

**Comment by Michkkael** [comment]
Oops! I meant 1.5.8

**Comment by GijsGoudzwaard** [comment]
I tried it with 1.5.8 and it still didn't work.

**Comment by Michkkael** [comment]
I use bower to get slick : "slick-carousel": "1.5.8"

And then, I call slick by this lines : 

var slider = $('#slider'),
      params = {};

params.cssEase = 'cubic-bezier(0.18, 0.89, 0.32, 1.28)';
slider.slick(params);

Be sure you have the right version !

**Comment by GijsGoudzwaard** [comment]
I got it working with 1.5.8, hopefully they'll update the plugin so it will work in the latest stable version.

**Comment by Michkkael** [comment]
Cool ! You can stay at this version until they fix that issue ;)

**Comment by mcashley** [comment]
Related to #1950 
might be fixed with useTransform defaulting to true now

**Comment by ugrupp** [comment]
Just to let you know that on your website download package, this bug remains - no css3 transitions by default: https://github.com/kenwheeler/slick/archive/1.5.9.zip

**Comment by lexbi** [comment]
Same issue with bower, I had 1.5.9. though transitions weren't working using this fix above.

Downloading straight from the master branch here worked for me.

**Comment by Hozeee** [comment]
Hello!

I've found, that on the 1885 line, there is this block:

if (bodyStyle.WebkitTransition !== undefined ||
		bodyStyle.MozTransition !== undefined ||
		bodyStyle.msTransition !== undefined) {
		if (_.options.useCSS === true) {
			_.cssTransitions = true;
		}
	}

But chrome has dropped the prefix, so it is Transition now without Webkit.

**Comment by leggomuhgreggo** [comment]
@Hozeee somewhat commonly used older versions of android mobile still need the prefix:
http://caniuse.com/#search=transform

@GijsGoudzwaard @Michkkael did you check the `useTransform: true`  fix? I'm going to close this for the time being, since it seems like it's a dup, but if that still doesn't work after that fix it'd be great to get it recreated in a fiddle.Thanks!
