### ISSUE TITLE
useTransform doesn't work in Safari 9.0.2

### ISSUE THREAD

**Issue by mreq** [kenwheeler/slick#1998]
[This line](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1929) seems to cause the problem.

```
 _.transformsEnabled = _.options.useTransform && (_.animType !== null && _.animType !== false);
```

The code's not commented there, so I can't provide a fix in fear of breaking other stuff. The problem is that `_.animType` gets set to `false` (why?), which leads to `_.transformsEnabled` being `false` as well in spite of `_.options.useTransform == true`.

**Comment by gitsilvan** [comment]
I think this is the same issue causing #1986.

**Comment by kenwheeler** [comment]
Interesting. Is there something in Safari that doesn't play well with this https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1912 ?

**Comment by mreq** [comment]
@kenwheeler Safari has both `bodyStyle.webkitTransform` and `bodyStyle.transform`. Why is there the `&& _.animType !== false` in https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1924?

**Comment by kenwheeler** [comment]
Ok, I accepted a PR that sets useTransform to false. That was an error.

**Comment by kenwheeler** [comment]
checking animType was to see if translate was useable at all
