### ISSUE TITLE
Slider is breakdown when resize the window

### ISSUE THREAD

**Issue by guddu1315** [kenwheeler/slick#2000]
I have a slider in slider.
I have main outer slider and there are multiple slides in inner slider.

https://jsfiddle.net/x10n5262/1/

When i resize the window all inner slider are breaddown except the current slide.
You can check the issues by pressing 'cntrl' + '-' to resize window and check the first slider is not working.
Can any one help please

**Comment by kenwheeler** [comment]
There is no javascript in the example?
