### ISSUE TITLE
1.5.9 disables translate3d animations

### ISSUE THREAD

**Issue by swinggraphics** [kenwheeler/slick#2003]
I installed slick 1.5.9 on a new site and noticed the animations were jerky. I looked back at a previous site where they're smooth and found the old site is using 1.5.7. In the inspector, I see 1.5.9 animates `left` while 1.5.7 animates `transform: translate3d`.

**Comment by kenwheeler** [comment]
Can you elaborate on this? What browser? JSFiddle?

**Comment by swinggraphics** [comment]
Poking through the code, I found `useTransform` and saw it is false by default. I added `useTransform: true` to my settings, and it works as expected now.

**Comment by jdahdah** [comment]
This one caught me off guard as well. My initial reaction was to downgrade, but I got it working again thanks to you posting this issue. Cheers!

**Comment by simeydotme** [comment]
@swinggraphics  and @jdahdah ... was this a breaking change from 1.5.7 to 1.5.9 ? -- was it set to true as default before?

**Comment by jdahdah** [comment]
@simeydotme I upgraded from 1.3.15, so I'm afraid I can't really help you pinpoint which version it started with. All I can tell you is that I didn't need to use the option beforehand, since apparently CSS transitions were active by default.

**Comment by swinggraphics** [comment]
@simeydotme `useTransform` was added in 1.5.9 and set to `false` by default. Before that, transforms were on by default without checking for this property.

**Comment by kenwheeler** [comment]
yeah this was a huge screw up
