### ISSUE TITLE
Using "rows" and "centerMode" at the same time: Slides shifted at certain breakpoint

### ISSUE THREAD

**Issue by tyrann0us** [kenwheeler/slick#2004]
https://jsfiddle.net/8p49du8d/

When you resize the viewport greater than 1200px the slides get shifted out of the window to left.

Am I doing something wrong or is this a bug?

Thanks.

**Comment by kenwheeler** [comment]
I don't see the issue. Can you reproudce with this fiddle? http://jsfiddle.net/simeydotme/fmo50w7n/

**Comment by tyrann0us** [comment]
Hi,
thanks for getting back to me. Please see this fiddle: http://jsfiddle.net/sppqz0c2/4/

If the viewport is wider than 1200px the slides get shifted to left. Tested on latest Chrome, Firefox and Safari on Mac OS 10.11.2 and latest Chrome on Windows 7.

**Comment by tyrann0us** [comment]
Hi @kenwheeler,
do you have any news regarding this issue? Were you able to see the bug in the fiddle?
Thanks!

**Comment by tyrann0us** [comment]
Hi @kenwheeler and @simeydotme,
we are still facing this issue. Any chance to get attention on this one?
Thank you very much!

**Comment by tyrann0us** [comment]
I created #2238 to draq some more attention to the problem.
