### ISSUE TITLE
background-image:cover, single slide, on iPhone = blank panes

### ISSUE THREAD

**Issue by ksavoie** [kenwheeler/slick#2005]
>> Running this simple layout
```
<div class="slick">
   <div>
      <div class="bgimg" style="background-image:url('urltoimage1.jpg');"></div>
   </div>
   <div>
      <div class="bgimg" style="background-image:url('urltoimage2.jpg');"></div>
   </div>
   <div>
      <div class="bgimg" style="background-image:url('urltoimage3.jpg');"></div>
   </div>
</div>
```
>> CSS
```
.slick {
        width: 100%;
}
.slick .bgimg {
  	background-position: center center;
	background-repeat: no-repeat;
	background-color: #b3c6cd;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
        height: 300px;
}
```
>> JS
```
$('.slick').slick({
		dots: false,
		arrows: false,
		pauseOnHover: true,
		swipeToSlide: true
});
```
>> Problem:
Desktop and iPad work flawlessly, iPhone=rotating but blank panes.
If I add in for slick to display > 1 images (slidesToShow: 2,), then the 2 images show/rotate correctly. It's only when configured for a single image does this occur.
Any assistance appreciated!

**Comment by simeydotme** [comment]
Please try applying the background images from a `<style>` tag or in a `.css` file... I think it's because Slcik is cloning your slide, and removing the `style` attribute... although... i thought I fixed that a long time ago.

**Comment by simeydotme** [comment]
make a JSFiddle like the `contributing guidelines` suggest, and we can help more :)

**Comment by beanmatt** [comment]
I seem to be having this same issue...but on an iPad.  Works great on desktops, but when viewing on iPad (4th generation, iOS 9.3.1) it does the flickering/blank thing.  Background images are styled in an external stylesheet.  Using current version of slick.  Example at http://codepen.io/anon/pen/yOrpvG
