### ISSUE TITLE
feature request: full screen expansion

### ISSUE THREAD

**Issue by KariCowan** [kenwheeler/slick#2007]
I don't see this in the docs, is there a way to expand a slideshow to full-screen?

**Comment by kenwheeler** [comment]
Not built in. People typically do it using two instances of Slick, adding the full screen version wrapped in a full height/width element that shows on click.

**Comment by kenwheeler** [comment]
I don't want to sound dismissive of the feature request here either, but this repo needs some love and my first step is going to be a feature freeze. I want to actually reduce the number of options you can supply this plugin, and add additional modes or features via a plugin system.

**Comment by KariCowan** [comment]
Not dismissive at all.  Thanks for the double-up suggestion. 

Also, a plugin system sounds like a good idea. One could be more selective which features they want.

**Comment by kenwheeler** [comment]
One gotcha to look out for, if a container that you call slick on is hidden, it can't get dimensions, so make sure after you show the modal version to call $('your-element').slick('setPosition')

**Comment by KariCowan** [comment]
Thanks. Do appreciate it.
