### ISSUE TITLE
Slick dots question

### ISSUE THREAD

**Issue by joebeaver89** [kenwheeler/slick#201]
Hi,

Is there a way to have the slick dots show but not be clickable to change the slide?

Thanks

**Comment by elizabethyalkut** [comment]
Note for future people trying to do this, line 738 is ```_.initDotEvents(); ``` in ```Slick.prototype.initializeEvents```

**Comment by julianxhokaxhiu** [comment]
Why not adding an option for that? It would be really useful. Any other "hackish" way to accomplish this without modifying the source code?

**Comment by black-snow** [comment]
+1 for option
