### ISSUE TITLE
I want to fix thumbnails position (first on left align and second on right align)

### ISSUE THREAD

**Issue by Waseem-Jutt** [kenwheeler/slick#2012]
![sliderview](https://cloud.githubusercontent.com/assets/8005637/12256051/0c121150-b91c-11e5-8991-9487c6061536.jpg)
![original slide](https://cloud.githubusercontent.com/assets/8005637/12256052/0c143368-b91c-11e5-8514-6a969012660c.jpg)

slider thumbnails not  showing exact poistion that is want

My code for slider is

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css"/>

					<div class="row">
						<div class="slider-for">
							<div class="slide">
								<div class="col-md-5 col-sm-5">
									<img src="images/projects/project-image-1.jpg" alt="project-image-1" class="img-responsive" />
								</div>
								<div class="col-md-3 col-sm-3">
									<img src="images/projects/project-image-2.jpg" alt="project-image-2" class="img-responsive" />
								</div>
								<div class="col-md-4 col-sm-4">
									<img src="images/projects/project-image-3.jpg" alt="project-image-3" class="img-responsive" />
								</div>
								<div class="col-md-7 col-sm-7">
									<div class="project-description pad-top-49 pad-bottom-49">
										<h5 class="project-inner-heading mr-bottom-5">hellway pool villa</h5>
										<p>Ldque Caesaris facere voluntate liceret: sese habere. Mercedem aut nummos unde unde 
											extricat, amaras. Prima luce, cum quibus mons aliud consensu.</p>
									</div>
								</div>
								<div class="col-md-7 col-sm-7">
									<img src="images/projects/project-image-4.jpg" alt="project-image-4" class="img-responsive" />
								</div>
							</div> 
							<div class="slide">
								<div class="col-md-5 col-sm-5">
									<img src="images/projects/project-image-1.jpg" alt="project-image-1" class="img-responsive" />
								</div>
								<div class="col-md-3 col-sm-3">
									<img src="images/projects/project-image-2.jpg" alt="project-image-2" class="img-responsive" />
								</div>
								<div class="col-md-4 col-sm-4">
									<img src="images/projects/project-image-3.jpg" alt="project-image-3" class="img-responsive" />
								</div>
								<div class="col-md-7 col-sm-7">
									<div class="project-description pad-top-49 pad-bottom-49">
										<h5 class="project-inner-heading mr-bottom-5">hellway pool villa</h5>
										<p>Ldque Caesaris facere voluntate liceret: sese habere. Mercedem aut nummos unde unde 
											extricat, amaras. Prima luce, cum quibus mons aliud consensu.</p>
									</div>
								</div>
								<div class="col-md-7 col-sm-7">
									<img src="images/projects/project-image-4.jpg" alt="project-image-4" class="img-responsive" />
								</div>
							</div> 
							<div class="slide">
								<div class="col-md-5 col-sm-5">
									<img src="images/projects/project-image-1.jpg" alt="project-image-1" class="img-responsive" />
								</div>
								<div class="col-md-3 col-sm-3">
									<img src="images/projects/project-image-2.jpg" alt="project-image-2" class="img-responsive" />
								</div>
								<div class="col-md-4 col-sm-4">
									<img src="images/projects/project-image-3.jpg" alt="project-image-3" class="img-responsive" />
								</div>
								<div class="col-md-7 col-sm-7">
									<div class="project-description pad-top-49 pad-bottom-49">
										<h5 class="project-inner-heading mr-bottom-5">hellway pool villa</h5>
										<p>Ldque Caesaris facere voluntate liceret: sese habere. Mercedem aut nummos unde unde 
											extricat, amaras. Prima luce, cum quibus mons aliud consensu.</p>
									</div>
								</div>
								<div class="col-md-7 col-sm-7">
									<img src="images/projects/project-image-4.jpg" alt="project-image-4" class="img-responsive" />
								</div>
							</div> 
							<div class="slide">
								<div class="col-md-5 col-sm-5">
									<img src="images/projects/project-image-1.jpg" alt="project-image-1" class="img-responsive" />
								</div>
								<div class="col-md-3 col-sm-3">
									<img src="images/projects/project-image-2.jpg" alt="project-image-2" class="img-responsive" />
								</div>
								<div class="col-md-4 col-sm-4">
									<img src="images/projects/project-image-3.jpg" alt="project-image-3" class="img-responsive" />
								</div>
								<div class="col-md-7 col-sm-7">
									<div class="project-description pad-top-49 pad-bottom-49">
										<h5 class="project-inner-heading mr-bottom-5">hellway pool villa</h5>
										<p>Ldque Caesaris facere voluntate liceret: sese habere. Mercedem aut nummos unde unde 
											extricat, amaras. Prima luce, cum quibus mons aliud consensu.</p>
									</div>
								</div>
								<div class="col-md-7 col-sm-7">
									<img src="images/projects/project-image-4.jpg" alt="project-image-4" class="img-responsive" />
								</div>
							</div> 
						</div>
						<div class="col-md-12 col-sm-12 pad-top-50 slider-nav">
							<span class="text-left previ-post post-link">
								<a>
									 spring greek project
								</a>
							</span> 
							<span class="text-right next-post post-link">
								<a>
									orchard hanry villa 
								</a>
							</span> 
							<span class="text-left previ-post post-link">
								<a >
									spring greek project
								</a>
							</span> 
							<span class="text-right next-post post-link">
								<a >
									orchard hanry villa
								</a>
							</span> 
						</div>
					</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
	$(document).ready(function() {
                            $('.slider-for').slick({
			  slidesToShow: 1,
			  slidesToScroll: 1,
			  arrows: false,
			  autoplay: true,
			  pauseOnHover:true,
			  autoplaySpeed: 8000,
			  asNavFor: '.slider-nav'
			});
			$('.slider-nav').slick({
			  slidesToScroll: 1,
			  asNavFor: '.slider-for',
			  dots: false,
			  autoplay: true,
				fade: true,
			  pauseOnHover:true,
			  nextArrow: '<i class="fa fa-caret-right pad-left-8 pull-right"></i>',
			  prevArrow: '<i class="fa fa-caret-left pad-right-8 pull-left"></i>',
			  autoplaySpeed: 8000,
			  variableWidth: true
			});
	});

**Comment by mcashley** [comment]
No JSFiddle - closing

**Comment by Waseem-Jutt** [comment]
okay I'm adding i will update post after add js fiddle
