### ISSUE TITLE
Inline Width Calculation Incorrect

### ISSUE THREAD

**Issue by SmboBeast** [kenwheeler/slick#2015]
There seems to be an intermittent bug with the inline width calculations for the slick elements.  

You can sometimes reproduce on this page: http://mossstudio.com/ProductDetail.aspx?pId=175 if you do a hard refresh (Ctrl + R on a PC).  Maybe it takes too long for the image to load before the JS width calculation runs?

I'm getting multiple reports of this:

![untitled](https://cloud.githubusercontent.com/assets/287007/12276487/dd41732a-b92a-11e5-9eb3-b0e328813cfc.png)

**Comment by mcashley** [comment]
No JSFiddle - closing
