### ISSUE TITLE
1.5.9 gets initialized but somehow it doesn't work, wraps some extra divs

### ISSUE THREAD

**Issue by Stiropor** [kenwheeler/slick#2016]
Slider worked fine with 1.5.7. I updated to 1.5.9, slider wrapper gets the slick-initialized and slick-slider class, all slides somehow get wrapped with two divs, slides are shown one below the other. Console log displays no error, I tried with both jQuery 2.1.4 and 2.2.0, no difference. I'm using this basic html:
```
<div class="cars-featured">
	<article>
		<div class="slide-background" data-background="/path/to/image.jpg"></div>
	</article>
	<article>
		<div class="slide-background" data-background="/path/to/image.jpg"></div>
	</article>
	<article>
		<div class="slide-background" data-background="/path/to/image.jpg"></div>
	</article>
</div>
```
and running it with:
```javascript
$('.cars-featured').slick({
	infinite: true,
	slidesToShow: 1,
	slide: 'article',
	arrows: false,
	speed: 300,
	autoplay: true,
	autoplaySpeed: 4000
});
```

This is the code it creates, no idea where those wrapped divs come from.
<img width="1051" alt="screen shot 2016-01-12 at 21 47 39" src="https://cloud.githubusercontent.com/assets/365876/12276467/36c4c046-b976-11e5-9471-15722c4cfabf.png">

No other script is involved for this case.

**Comment by mcashley** [comment]
No JSFiddle - closing

**Comment by Stiropor** [comment]
Oh wow, closing the issue fixed it, huh. Amazing, you have the the code and html, JSFiddle, really? Too lazy to open it yourself? How about I write you a 20 page report or even better, let me buy a plane ticket, fly to you and explain it to you in person, ok? What an ignorance. It's your script not working, not mine. Moving on to other scripts where authors are not complete f*cktards. Bye.

**Comment by kenwheeler** [comment]
Wait @Stiropor, you want me to take time out of my day, to diagnose and fix your issue, for free, and you can't give a fraction of that time to show a reduced test case in jsfiddle to help me do that quicker? Give me 10 minutes and I'll gladly process your refund.

**Comment by danielbachhuber** [comment]
@kenwheeler I appreciate the work you do maintaining Slick. I've used it on dozens of projects, and it has saved me tons of time and headaches. Thanks!

**Comment by kenwheeler** [comment]
@danielbachhuber thanks homie

**Comment by vakhtang** [comment]
@Stiropor The requirements are laid out in [CONTRIBUTING](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). Don't get defensive, just follow the rules.

**Comment by Stiropor** [comment]
Maybe asking for a JSFiddle would be even better not just closing with "No JSFiddle - closing". I don't know what kind of requests you have. I know this project is free, so far it worked great, I appreciate the work and all, but if you want something ask, just closing the issue doesn't help anything (and yeah, my attitude doesn't either, maybe it's time to leave the office after 15 hours). Posting JSFiddle asap. Thanks.

**Comment by kenwheeler** [comment]
@Stiropor 
![screen shot 2016-01-14 at 2 48 07 pm](https://cloud.githubusercontent.com/assets/286616/12335574/e62689fe-bacd-11e5-84df-7125610d324d.png)

**Comment by joshmanders** [comment]
:disappointed:

**Comment by senoff** [comment]
Maybe we could say

Closing -  please add a JSFiddle to reopen

Might have a softer touch with our valued community.

**Comment by mcashley** [comment]
Noted.
sorry, its my first time contributing like this, so I was treating it like work. 

I did not realize the community was so sensitive
-ashley

**Comment by kenwheeler** [comment]
@senoff agreed, but normally folks don't respond like this

@mcashley don't sweat it, let's go with a will reopen clause

**Comment by Stiropor** [comment]
@kenwheeler and @mcashley Bad timing and my very bad reply, I know. It wasn't right and I apologize, it was a pretty retarded reaction. I know there are many issues you have to work with and all, but the goal should be to fix your script if problem is found and just closing it doesn't help. I also cannot read guidelines for every project (and never had any problems before), but yeah, posing JSFiddle is the right way.

Anyway, here is what I figured out: the problem is version on master, 1.5.9 (if downloaded from website) works, master (it says 1.5.9 of course) doesn't. I will be careful about this in the future and am using the website's version now. And here are the examples:

1.5.9 (working): https://jsfiddle.net/oa893ss1/18/
1.5.9 from github (nonworking): https://jsfiddle.net/oa893ss1/16/

Tested in Chrome.

Hope this helps.

**Comment by kenwheeler** [comment]
@Stiropor thanks man, don't sweat it

**Comment by mcashley** [comment]
I actually had a problem with the code in master as well. The last check in checking for 
```
_.options.rows >= 1 
```
doesn't jive for me

**Comment by kenwheeler** [comment]
@mcashley can you show me a line number for that? whats going on there?

**Comment by kenwheeler** [comment]
@mcashley yeah its the rows

**Comment by kenwheeler** [comment]
Reverted, master should be fine now
