### ISSUE TITLE
CenterMode with CSS scale transition without padding at all.

### ISSUE THREAD

**Issue by ninetienne** [kenwheeler/slick#2019]
Thanks for the greatest slider ever. 

I can't make it look like this however:

![center-mode](https://cloud.githubusercontent.com/assets/1227877/12293463/bf697e4e-ba04-11e5-84cd-fd867c687327.png)

I'd like to have the css ease effect, fixed number of slides, `centerMode` and no padding between images. 

The thing is that if it's not `variableWidth`, the widths are the same for all slides, therefore it can't be both: center slide is larger and there are no paddings.

Could you please advise if I could anyhow get the layout I'd like?

Thanks a lot again.

**Comment by mcashley** [comment]
No fiddle, looks like support request closing
