### ISSUE TITLE
Can I know if the slickNext is fired or not?

### ISSUE THREAD

**Issue by newpen** [kenwheeler/slick#2023]
I noticed that slickNext will not be fired while animating. I have tried waitForAnimate but it makes it jumpy. So I just want to know if the slickNext is fired or not when the user perform the click event. So that when I know that it is not fired, I can notify the users about it, or do other actions. Thanks!

**Comment by kenwheeler** [comment]
You can listen to the beforeChange event. Sidenote, this is a place for issues, not a support forum.
