### ISSUE TITLE
Want autoplay to play the slides once and stop

### ISSUE THREAD

**Issue by imransilvake** [kenwheeler/slick#2029]
http://foundation.zurb.com/forum/posts/19196-want-autoplay-to-play-the-slides-once-and-stop

Basically I changed the line of code (382 in mine) :

 _.slideHandler(_.currentSlide - _.options.slidesToScroll);
to:
 _.slideHandler(_.currentSlide);

Hope this helps you out.

Version: 1.5.8

**Comment by kenwheeler** [comment]
This fixes the particular need but breaks other implementations. Thanks though.

**Comment by imransilvake** [comment]
yes. do you know any better way?

**Comment by kenwheeler** [comment]
something like if currentSlide >= slidesLength - slidesToShow then pause, in the afterChange event

**Comment by imransilvake** [comment]
but will it affect autoplay? or not?

**Comment by kenwheeler** [comment]
if the slider is autoplaying, after each slide sequence it will call onAfterChange. In that callback, you can say hey, if this is the last slideable index before the end, then pause autoplay so that it doesn't continue.

**Comment by imransilvake** [comment]
ok. thanks alot
