### ISSUE TITLE
any way to restrict draggable element inside the slides?

### ISSUE THREAD

**Issue by zsitro** [kenwheeler/slick#2041]
What I mean is to make possible that only a child element inside the slide can make the slide drag. Thanks.

**Comment by simeydotme** [comment]
Please read the contribution guidelines :)

**Comment by simeydotme** [comment]
Not possible with current API, and probably never. 
Slick is a carousel, not an abstract UI widget :) -- feel free to try and hack it to your whim, but we don't support that. Try Stackoverflow.

Best, Si.

**Comment by zsitro** [comment]
All right, ty  :)
