### ISSUE TITLE
ID stripe option for cloned divs

### ISSUE THREAD

**Issue by osmanorhan** [kenwheeler/slick#2042]
Hi,
Is it possible(or ok) to have initial id attributes for cloned divs in infinite mod? If so, I will make a pull request to get this feature.

Even the idea behind cleaning id fields from cloned elements is logical, in some frameworks, such as Ember, we need id fields to trigger events. Otherwise, we are not able to get proper actions from related buttons.

**Comment by simeydotme** [comment]
If you want to submit a PR with a use-case, please go ahead :) 
Reopen when you feel necesary.

**Comment by kenwheeler** [comment]
Clones are going bye byes real soon.
