### ISSUE TITLE
customPaging has slide items link ?

### ISSUE THREAD

**Issue by baykorhan** [kenwheeler/slick#2046]
Hi,

https://jsfiddle.net/baykorhan/h0s02moq/1/ 

I have a custompaging and each dots get the link from slide items. But it is not clickable.. How can I click to dots for external link ?

Thx.

**Comment by kenwheeler** [comment]
I can't imagine this is even close to supported out of the box. If I were to implement this, I would do a custom jquery script to generate these links. Generally, custom paging anchors are used to navigate to certain slides.

**Comment by leggomuhgreggo** [comment]
Another alternative is to "restore defaults" by unbinding click events for your dots. Wouldn't swear to it's stability, but adding this will make the links work:

`$('.slider .slick-dots li').unbind('click');`

[fiddle](https://jsfiddle.net/leggomuhgreggo/cm8Lusqa/2/)

**Comment by baykorhan** [comment]
@kenwheeler I agree with you..yes I can accept this is a strange request but this is a customer request and It is difficult to solve the people.(especially customers) we are looking forward to responding to requests.

@leggomuhgreggo  This solves my problem. thank you.
