### ISSUE TITLE
afterChange event is being fired on Chrome Android when touching the slide and scrolling down

### ISSUE THREAD

**Issue by marb19** [kenwheeler/slick#2051]
Hey, I am building a site that requires to load specific content depending on the current slide. It is working nicely but found an issue while working with Android devices and Chrome.

I am refreshing the content by doing a jquery load every time the afterChange event is fired. The thing is that the event is fired in Android Chrome when you touch the slider and scroll down, even if you didn't change slide.

**Comment by leggomuhgreggo** [comment]
I'm going to close this because there's [no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), but I think this issue has been reported in issue #1223 so you might find some guidance there. Thanks!

**Comment by marb19** [comment]
The workaround solved the problem. Nevertheless I think it's a bug.
