### ISSUE TITLE
background image disappears when using id for style

### ISSUE THREAD

**Issue by Mikorinnn** [kenwheeler/slick#2052]
Hi! I would like to ask why is it that when I use ID to style one of the div adding background image, the slider ends in the last slide and the background image disappears on the first slide. Also when clicking the back button from the first slide the background image only appear in the last slide. I have replicate my problem here in [jsfiddle](http://jsfiddle.net/hsshfozb/1/). Its a bit weird because when I change the ID to Class it works fine here in [jsfiddle](http://jsfiddle.net/uwx1Lpru/1/).

**Comment by leggomuhgreggo** [comment]
The way infinite slides work is by cloning a slide. IDs are only supposed to exist once. My guess is that there's a browser paint latency issue related to the ID duplication being invalid and therefore not optimized for. 

Interesting issue, but doesn't seem like a bug with the slider; so, I'm going to close it.

**Comment by Mikorinnn** [comment]
But there is no duplication in the IDs and as for the example I have given I only used same pictures. Here is another example in [jsfiddle](http://jsfiddle.net/hsshfozb/2/). In case you haven't notice, the funny part here is that when the slider clones a slide it doesn't get the id of the div only the class. Why only the class and not the IDs?

**Comment by leggomuhgreggo** [comment]
My apologies for my hasty read. I think that's your answer though. It won't dup the IDs in accordance with HTML validation and wont swap until the slide is fully active. IDs are cumbersome that way--I try to avoid them in general.

**Comment by Mikorinnn** [comment]
So there's no other way to get around that and just use class? IDs make the object unique that's why I use it whenever there are only few things to adjust from the class itself. You can't always avoid using them imo.

**Comment by leggomuhgreggo** [comment]
This is somewhat of a controversy, so I'll let you investigate and come to your own conclusions, but I find the arguments against using IDs at all pretty compelling. [This wasn't the article](http://oli.jp/2011/ids/) I was looking for, but it seems to cover the anti-ID side pretty well. I just use a unique string as a class and it serves the same purpose, although I'm sympathetic to the slightly more ordered feel of a separate attribute.

**Comment by Mikorinnn** [comment]
After reading the article, I think it has a point but in my project I still need to use IDs because since I already have universal class on my divs I use IDs for background images since it should be unique. So I guess in the end it will depend on our beliefs. Thank you for enlightening me. (๑ᴖ◡ᴖ๑)

**Comment by HugoHeneault** [comment]
Thanks for the tips. I knew for the Ids but I wouldn't have guessed that the issue would come from there. I got it fixed by replacing the ids by some classes! 👏
