### ISSUE TITLE
Is there something wrong with  slick.js & slick.min.js ? 

### ISSUE THREAD

**Issue by YUFENGWANG** [kenwheeler/slick#2053]
In my demo ,when I try slick.min.js , at the time I click the slick dots ,the slider works well, but after finishing slide ,the scroll bar of my browser moves down automaticly. Then I tried slick.js , this case doesn't exist anymore ? so I don't know why...

**Comment by kenwheeler** [comment]
Update to the latest version. That functionality was accessibility centric and removed.

**Comment by YUFENGWANG** [comment]
ok.
