### ISSUE TITLE
Lazyload callback

### ISSUE THREAD

**Issue by rubenvincenten** [kenwheeler/slick#2054]
Could we get a way to set a callback for when an image loads? I want to apply a special class to images when slick carousel loads them.

**Comment by naveen4854** [comment]
Just a thought. 
how about we get to provide a event on lazy load which returns the tile to be added.

**Comment by simeydotme** [comment]
@rubenvincenten ... you think you can submit a PR for it? I'd be happy to review and merge :)

**Comment by simeydotme** [comment]
closed by https://github.com/kenwheeler/slick/commit/7abc8d946dc3375f9461a908cf529e9d912b8e73
