### ISSUE TITLE
My divs container go crazy

### ISSUE THREAD

**Issue by moisesnandres** [kenwheeler/slick#2056]
I have 3 different slides, each slide have different items. Here's my problem: when the first slide's items move, the others slides move vertically and I don't know why, is it a bug?

**Comment by leggomuhgreggo** [comment]
Hey, I'm going to close this, because there is no test case, per the [contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). My guess without seeing it is that there might be overlap in the selector used for the slicks

**Comment by moisesnandres** [comment]
sorry, here is http://jsfiddle.net/moisesnandres/vyz5593d/ 
it's run normally but when I use images , the divs crash

**Comment by leggomuhgreggo** [comment]
Hmm, I don't see any issue.

**Comment by moisesnandres** [comment]
In jsfiddle not, but in my project does, but I fix it, well I just remove padding in section

**Comment by leggomuhgreggo** [comment]
Okay. Yeah the idea behind asking for the fiddle was to recreate the issue.
Good luck!

**Comment by moisesnandres** [comment]
I've never used fiddle for issues, sorry if I didn't kwow the rules before asking

**Comment by leggomuhgreggo** [comment]
All good, brother!
