### ISSUE TITLE
Images not showing up when fading in

### ISSUE THREAD

**Issue by inversiondk** [kenwheeler/slick#2059]
I'm initalizing multiple slick's on my page. Each carousel shows different images and I need to be able to fade between the different carousels when clicking on some navigational buttons (note that all carousels are hidden at first). 

The setup works great - however - when I first fade in the Slick carousel, no images are visible. It's only when I press the "previous" or "next" button that the images show up. Same story if I fade over to a new slider. 
After I've gotten the images to show up then everything works perfect. 

I can see that the width of the slides are set to 0px after fading in the carousel - if I change this then the images shows up. 

Example: https://jsfiddle.net/kefjjLhL/1/

Is there a better way of loading multiple Slicks without them showing up and then fading between them? 

Thanks.

**Comment by simeydotme** [comment]
http://stackoverflow.com/questions/26677649/slick-slider-loaded-with-displaynone-creates-bad-initiation/26680322#26680322
