### ISSUE TITLE
Disapearing absolute positioned element inside slides

### ISSUE THREAD

**Issue by erthi16** [kenwheeler/slick#206]
I have images with caption inside each of my slides. Each caption is positioned absolute above it's image.  When I view in Chrome (version 34...) and use the arrows, the captions disapeare! They only reapeare when the carrousel returns to it's original position... When I remove the position absolute config in my CSS, everything is OK by I do need to place captions on top of the images... It is not possible to include the caption inside the images... my clients dont want to manipulate images!
Thanks a milion times!

**Comment by rassokhin-s** [comment]
@zlove `-webkit-transform: translate3d(0,0,0);` fixes the issue on mobile Safari. Thank you!

**Comment by aosmichenko** [comment]
IT"S not working! bondagefetishstore.com bottom most popular slider in safari

**Comment by kenwheeler** [comment]
@Aosmichenko looks like it's working to me

**Comment by aosmichenko** [comment]
I am using latest safari, you?

Best regards,
Alex Osmichenko | WordPress/Web developer | skype:alex_osmichenko | mob:+38
(093) 474-24-31

**Comment by aosmichenko** [comment]
Here is how I see it https://space.zeo.net/g/1vs0g/AVUDJ5FJK5DT5Q575S7TIE77CAQ7OEJ4 , sorry for such adult content..

**Comment by simeydotme** [comment]
AHAHAHAHHAHAHAHAHAHHAHAAAAA

**Comment by simeydotme** [comment]
on a serious note; the slider and its labels look fine to me, but I do have experience with Safari being a twat about z-indexing and even implements the z-index / 3d-translate poorly/wrongly
https://bugs.webkit.org/show_bug.cgi?id=61824

**Comment by nguyenj** [comment]
@kenwheeler thanks man! `-webkit-backface-visibility: hidden;` worked like a charm.

**Comment by yves-s** [comment]
Worked, thanks @kenwheeler

**Comment by manmohan-bisht** [comment]
@kenwheeler This work like charms..Thanks a lot

**Comment by yqz0203** [comment]
@zlove great! #

**Comment by cheestudio** [comment]
@kenwheeler YOU ROCK. How did you find this out even? I never would have thought to do this, but it makes so much sense because I am using transforms on the element. Learn something new everyday in this industry!

**Comment by rajeshgrgdesign** [comment]
-webkit-backface-visibility: hidden; on absolute div worked for me as well on mobile safari.
