### ISSUE TITLE
Delay when go from last slide to first.

### ISSUE THREAD

**Issue by Prefu** [kenwheeler/slick#2061]
Hi 
I've got a slider with 3 slider-slide. And when I use arrows to srcoll from last slide to the first there is a delay that continue for about 2 sec. What can i do with that. Is there possibility that the problem is my no super good computer ?

**Comment by simeydotme** [comment]
hi @Prefu , thanks for taking the time to write a comment, but we simply cannot help you until you've read the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) :smile: 

Si.
