### ISSUE TITLE
Slick in the collapsed section

### ISSUE THREAD

**Issue by GinoPane** [kenwheeler/slick#2067]
Is there any way to initialise slick correctly in the collapsed section? 
When I load some pages in mobile view, then some sections on the page are collapsed, but can be expanded by clicking on them. Inside one of such sections I have a slick gallery. And when I expand the section, slick gallery inside appears to be completely broken, but it restores when I click on navigation arrows or dots: http://prntscr.com/9un0rb. If I do not use collpased section ,then everything works fine. But is there any way to deal with collpase?

**Comment by simeydotme** [comment]
http://stackoverflow.com/questions/26677649/slick-slider-loaded-with-displaynone-creates-bad-initiation

**Comment by GinoPane** [comment]
Thanks! With slight modifications works as expected.
