### ISSUE TITLE
Multi filter

### ISSUE THREAD

**Issue by lucilecollignon** [kenwheeler/slick#2076]
Hi, 
I'm a newbee in jQuery and I can't find how to have multiple filters for Slick.
Based on the demo website, I have tried differents methods but it's not working.

Is it possible to unfilter only the slides which have been hidden ?

Could you help me please ?

Thanks a lot for Slick, it's very useful !

**Comment by simeydotme** [comment]
@lucilecollignon ... This is a bug-reporting forum... I don't think you've found a bug :disappointed: 
Please feel free to pop in to: https://gitter.im/kenwheeler/slick and ask us there... it's a support forum.

**Comment by simeydotme** [comment]
I helped @lucilecollignon  in Gitter.
http://jsfiddle.net/simeydotme/os5ktzgu/3/
It was a very interesting scenario and I hope the solution can help others, too.
Regarding dynamic additive filtering.

However, that fiddle also seems to have a bug (non-infinite not scrolling to 4th slide) but it's part of another bug report I believe exists.
