### ISSUE TITLE
Center mode question

### ISSUE THREAD

**Issue by mi32dogs** [kenwheeler/slick#2077]
First of all, thank you for this great scripts.

I have a question, is it possible to make the center image bigger than scale(1.08) let’s say scale(1.15) without top and bottom being cut off, to due overlay hidden on .slick-list?

Thanks Rob

**Comment by simeydotme** [comment]
Try adding some top/bottom padding to the `.slick-track` ... and in future ask questions in the correct forum, please :) -- this is a bug-tracker. -- The contribution Guidelines can help with that confusion.

Best, Simon.
