### ISSUE TITLE
kenwheeler.github.io/slick/  sliders are animating css 'left' instead of 'transform'

### ISSUE THREAD

**Issue by rorysmorris** [kenwheeler/slick#2078]
Why is this? It degrades the user experience a great deal.

Can confirm this is happening on the latest versions of Chrome, Firefox and Safari on OSX Yosemite.

**Comment by simeydotme** [comment]
Thanks for the question.
I believe there was a mistake commit in 1.5.9 when making css-transforms optional.

`useTransforms: true`

**Comment by adrianparr** [comment]
Ah, this is just what I was looking for. Thanks.
By the way, it looks like the parameter is ...

useTransform: true

(singular, not plural)
