### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null - line 2590

### ISSUE THREAD

**Issue by brunomarks** [kenwheeler/slick#2080]
I have error message:

```
Uncaught TypeError: Cannot read property 'add' of null
slick.js line 2590
```

My code

![screenshot 2016-01-28 19 16 44](https://cloud.githubusercontent.com/assets/311003/12659031/aebea254-c5f3-11e5-8f1a-7ca0b526d618.png)

Does anyone have any idea about this error?

Tks a lot!

**Comment by simeydotme** [comment]
Please take a look at the Contribution Guidelines and update your issue, and we'll attempt to help you out thenceforth. :)
