### ISSUE TITLE
Event triggers all slideshow if more than one on a page 

### ISSUE THREAD

**Issue by ktmcburney** [kenwheeler/slick#2081]
If you have more than on slideshow on a page and you want to trigger an event 

        $('.slider').on('afterChange', function (event, slick, currentSlide) {
            // do stuff
        });

This is triggered on every slideshow. Regardless if they have different class names. I even tried using id's and when you log $(this) it displays the details of the wrong slide.

**Comment by leggomuhgreggo** [comment]
Hey @ktmcburney can you make a fiddle? 

Related: [Contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)
