### ISSUE TITLE
Vertically center navigation arrows

### ISSUE THREAD

**Issue by Madeirense** [kenwheeler/slick#2082]
Love this slider, thanks.

Just one thing though. I have a carousel where I have images and a caption. If captions are short and in one line the navigation arrows are perfectly aligned vertically. However, if captions take up more that one line the navigation arrows comes down and it looks a bit strange.  

The issue here is that the arrows have a css top: 50% and they get aligned with the container. But in my situation I would like them to be vertically aligned only with the images not with the images+caption. So, independently of how much content I would have bellow each image on each slide the arrows would always be vertically aligned with only the image. Is this possible at all?

**Comment by leggomuhgreggo** [comment]
Hey @Madeirense, your question is a support request; so, Im going to close it. This is really just where we track bugs with the library. Check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).

That said, I think what you want to do is absolutely position the caption to be below the the slide so its out of the document flow and slider height calculation, or alternatively have two sliders joined by the asNavFor method.

Thanks!
