### ISSUE TITLE
Prevent loading "hidden" slides over the network until they are in view.

### ISSUE THREAD

**Issue by ccurtin** [kenwheeler/slick#2084]
I apologize for the length of this in advance! Just want to be as clear as possible.

The breakpoints are a great feature, but when the page loads, all images defined in the immediate `slidesToShow` slick settings, _not_ the `responsive` object settings, are loaded over the network, somewhat defeating the purpose of lazy-loading images.

To make things a little more clear, say there is a desktop view, which shows 6 slides, but then there is also a breakpoint for mobile devices under 520px to show only 1 slide. If the user on the mobile device loads the page up, all 6 images will be loaded over the network instead of just 1 image at a time, which could be an issue for mobile users loading larger images or who are on slower networks.

I've found 2 ways to combat this, by either placing everything within the `responsive` object, and setting the first responsive view to something crazy like anything under 9000px, which seems a little hackish, _or_ by setting the `slidesToShow` attribute as a variable, and running checks on the window size before initializing slick.

If you open up Dev Tools > Network and take a look at the fiddle below and make sure the window width is less than 520px you will see that all 6 images are loaded over the network, despite the settings `lazyLoad:'ondemand'` and `slidesToShow:1` being set for views under 520px.

http://jsfiddle.net/fmo50w7n/231/
![image](https://cloud.githubusercontent.com/assets/8930794/12703105/21d41542-c808-11e5-8425-4eb826eb16a1.png)

**_But_**, if everything is placed within the `responsive` object, the behavior acts accordingly, and when the document loads with the window being < 520px, only 1 single image is loaded at a time.

http://jsfiddle.net/fmo50w7n/230/
![image](https://cloud.githubusercontent.com/assets/8930794/12703108/41187768-c808-11e5-94d0-679a8bb1aa12.png)

I would image that a solution to this would be to first check if the `responsive` object exists, and to then check what the value of the highest `responsive` attribute is. In the fiddle example, that would be anything above 1400px.  So any window size above that, load the immediate `slidesToShow` value, otherwise use the  responsive `slidesToShow` value...

Not exactly sure how this would be best implemented, I think it may be better left to someone with more expertise than myself.

**Comment by simeydotme** [comment]
what's wrong with this?
http://jsfiddle.net/simeydotme/0rpshw9a/

`mobileFirst` ... looks fine for me?

**Comment by ccurtin** [comment]
Wow, I completely overlooked that! :flushed: 

Perfect, thanks!

**Comment by simeydotme** [comment]
No problem, I feel sorry you spent so much time on your post :(

**Comment by ccurtin** [comment]
Haha, live and learn. Now I know to _fully_ read docs for something next time.
