### ISSUE TITLE
Support for Semantic UI grid system

### ISSUE THREAD

**Issue by abdelouahabb** [kenwheeler/slick#2085]
When using grid system in Semantic UI, a grid of 16 (default) is more than the size of the page.

First slide:
![sans titre](https://cloud.githubusercontent.com/assets/2527234/12715785/95825588-c8dc-11e5-8b51-035175ce1ca7.png)

Second slide:
![sans titre](https://cloud.githubusercontent.com/assets/2527234/12715824/c5b602a4-c8dc-11e5-9855-d41d7ea60321.png)

    <div class="project">
      <div class="ui grid">
        <div class="eight wide teal column"></div>
        <div class="eight wide yellow column"></div>
      </div>
      <div>your content</div>
      <div>your content</div>
   </div>

**Comment by simeydotme** [comment]
I think you have the wrong repository, mate?

**Comment by abdelouahabb** [comment]
@simeydotme no, I think my question was mal formed!

I am talking about using Slick when every slide is made from a div that uses semantic UI grid system.

**Comment by simeydotme** [comment]
oh right, in that case I'll ask you to create a JSFiddle from then [contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) and explain clearly what the matter is :) (seems your grid over-flows the slider?)

**Comment by abdelouahabb** [comment]
Here is it, the first slide went beyond the first page to the second one (I desactivated autoplay)
http://jsfiddle.net/fmo50w7n/232/

**Comment by simeydotme** [comment]
Please read your documentation (for slick and/or semantic ui) a little more carefully :) -- in future try to ask questions for support in Gitter/Stackoverflow.

http://jsfiddle.net/simeydotme/9uckx6d8/

Best, Simon.

**Comment by abdelouahabb** [comment]
ah! now i see, the css is applied for the first child of the main slider, that's why you wrapped it in an empty div, thank you ^_^
