### ISSUE TITLE
Vertical align

### ISSUE THREAD

**Issue by wider2** [kenwheeler/slick#2086]
Good day
I am working with slick ver. 1.5.9
Problem occurs with center vertical align of big div on the screen
when I use infinite loop.... everything are moving outside screen -  to the right - until loop is finished
after that he return to default point to left part of the screen

is there is a simple function in Slick slider to define vertical alignment?

**Comment by wider2** [comment]
Problem code

<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="robots" content="noindex, nofollow">
  <meta name="googlebot" content="noindex, nofollow">
    
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
      <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
      <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css">

  <style type="text/css">
    html, body {
    height: 100%;
}
.parent {
    width: 100%;
    height: 100%;
    display: table;
    text-align: center;
}
.parent > .child {
    display: table-cell;
    vertical-align: middle;
}
.slider {
    width: 50%;
    height: 10%;
    margin: 0 auto;
}
.slick-prev:before, .slick-next:before {
    color:#808080;
}
.centerHorizontally {
    display: table;
    margin: 0 auto;
}
.halfWidth {
    width: 50%;
}
  </style>

  <title>centerverticalhorizontal</title>

<script type='text/javascript'>//<![CDATA[
window.onload=function(){
$('.multiple-items').slick({
    infinite: true,
    slidesToShow: 5,
    slidesToScroll: 5,
    dots: true,
    autoplay: true, speed: 300
});
}//]]> 

</script>
</head>
<body>
  <div class="centerHorizontally parent">
    <div class="halfWidth child">
        <div class="slider multiple-items">
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
            <div>
                <div class="centerHorizontally">
                    <img src="http://placehold.it/50x50" />
                </div>
            </div>
        </div>
    </div>
</div>
  
</body>
</html>

**Comment by simeydotme** [comment]
Please create a JSFiddle with your issue, and try to explain it a little better :)

**Comment by wider2** [comment]
http://jsfiddle.net/4qpejg98/2/

**Comment by simeydotme** [comment]
Slick doesn't support `display: table;` :)
