### ISSUE TITLE
Issue with Firefox 44.0 and chrome 48 - slick 1.5.9

### ISSUE THREAD

**Issue by nOograss** [kenwheeler/slick#2087]
I have encountered a weird issue with these two browsers.
each slide of the sliders is taking the full width and sometime more. 
Even with the slidesToShow set to one , the slides are not correclty resized.

With Safari and Opera there is no issue, working perfectly.

I've adde screenshot of firefox showing the extravagant width of the slider
<img width="1415" alt="screen shot 2016-02-01 at 16 31 48" src="https://cloud.githubusercontent.com/assets/8310240/12721705/5e1143dc-c901-11e5-9123-f424a44aa8c2.png">

safari: 
<img width="1392" alt="screen shot 2016-02-01 at 16 32 44" src="https://cloud.githubusercontent.com/assets/8310240/12721726/770fce62-c901-11e5-8a34-a27df732d6e0.png">

Anyone having that issue ?

**Comment by simeydotme** [comment]
related to: https://github.com/kenwheeler/slick/issues/1195 ?
You should post a fiddle with your issue, please.
Check the contribution guidelines.

**Comment by nOograss** [comment]
Well the fiddle would have been a simple slider but my bad :)

and indeed it was related to #1195  thanks
