### ISSUE TITLE
Dots removal does not remove space

### ISSUE THREAD

**Issue by sipi41** [kenwheeler/slick#2088]
Hi, first of all, thank you for this amazing script!

I'm having some problems, I'm a newbie.  When I use the option **dots: false**, the dots are removed  BUT a blank space or line remains under the content... how can I get rid of this space when not using dots? 

thank you and please advise.

**Comment by leggomuhgreggo** [comment]
I'm closing this because its a support request and it lacks a test case, per the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). That said, there's a style on the slider for the dot spacing that has to be manually removed
`.slick-slider{margin-bottom: 30px;}`

Thanks!

**Comment by sipi41** [comment]
Thanks for you help but even if I put 0px it does not remove the space at the bottom...

**Comment by leggomuhgreggo** [comment]
If you refer to the contribution guideline there is a jsfiddle you can fork
to make a test case that for debugging purposes. Have you used the
inspector to try to identify which element/style is causing a space?

**Comment by sipi41** [comment]
![problemaweb](https://cloud.githubusercontent.com/assets/688562/12727466/d810afde-c8e2-11e5-8121-9ffc8228e21b.png)

First of all, thanks for helping me! PLEASE check the attached file.

**Comment by leggomuhgreggo** [comment]
Hmm, I see margin bottom 30 in that screenshot, so it's getting applied. I
think if you remove that style, you should solve your problem.

**Comment by sipi41** [comment]
Thank you very much... I see it.  It would be nice if they do not include it automatically... :-)

**Comment by leggomuhgreggo** [comment]
It's been talked about: #984 Maybe someday soon :)
