### ISSUE TITLE
Height option for vertical mode

### ISSUE THREAD

**Issue by ryanwalters** [kenwheeler/slick#2089]
Is it possible to specify the height of the vertical container versus determining the height based on `slidesToShow`?

```
// Currently in 1.5.9
_.$list.height(_.$slides.first().outerHeight(true) * _.options.slidesToShow);

// Possibly
_.$list.height(_.options.height || (_.$slides.first().outerHeight(true) * _.options.slidesToShow));

// Plus a calculation on the arrow click
```

**Comment by simeydotme** [comment]
try using `centermode` :)

**Comment by ryanwalters** [comment]
`centerMode` didn't seem to change anything, other than add padding. I'll try to explain the issue a little better.

Here is a fiddle:
http://jsfiddle.net/ytLkbv4y/1/

**Expected result**
Clicking the "next" arrow should slide the track the height of the container, 300px in this case, and not the height of a single item. The "next" arrow should become disabled as soon as slide 6 comes into view and aligns with the bottom of the container.

**Actual result**
Clicking the "next" arrow slides the track the height of a single item, ~116px in this case. The "next" arrow does not become disabled when slide 6 comes into view, but continues to be clickable until slide 6 is at the top of the container.

**Comment by simeydotme** [comment]
I'm very confused , @ryanwalters  :confused: 
you want margins between the slides?
like: http://jsfiddle.net/simeydotme/ytLkbv4y/3/

**Comment by ryanwalters** [comment]
Sorry, not the margins.

I want to be able to set the height of the slider container; in the fiddle, this is 300px. Now, every time I click "next", it should scroll vertically 300px until the last slide comes into view.

Any number of slides can be within that 300px height. I want to scroll the height of the container vs the height of the slide.

Does that make more sense?

**Comment by simeydotme** [comment]
@ryanwalters ... it kind of makes sense, but not in a carousel context...

you can accomplish that easily with a scrolling div, and a tiny bit of jQuery...
hop on https://gitter.im/kenwheeler/slick if you want to find out how :)
