### ISSUE TITLE
Internet Explorer randomly crashes when there are multiple slick sliders with a progressive lazyload on a single page

### ISSUE THREAD

**Issue by pwetosaurus** [kenwheeler/slick#2091]
All my apologies for this quite long title, but cannot figure how to reduce it…

Well, on some websites with homepage featuring multiple slick sliders implementations on the same page, if there are more than one slick that use a progressive lazyload, Internet Explorer could sometimes make a high memory usage that make it crash.

This is totally random, Internet Explorer could either handle the sliders, or simply crash for memory overflow.

That's not really a solution but at least we could make or way through this issue with a lazyload method override in the config : we need to put a Lazyload: ondemand in our config file for sliders after the first one (and for whom the blinking effect of the image loading is less critical than on the big home slider).

The slick slider version is 1.5.9
And the internet explorer version that I bullied for this issue is the 11.0.9600.17420 (update versions 11.0.14) (on a virtualbox running a Microsoft Windows 7 image, one of those provided by Microsoft for IE testing).

For debugging, I worked on this website : [http://preview.tinyurl.com/gnysuro](http://preview.tinyurl.com/gnysuro)

**Comment by simeydotme** [comment]
@pwetosaurus , I would like to investigate this, would you mind fixing me up a JSFiddle (as mentioned [in the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) with the amount of sliders needed to reproduce the crash?

Thanks.

**Comment by pwetosaurus** [comment]
I was lacking time this morning to create the fiddle, but you can consider have one really soon (in a couple of hours I guess).

**Comment by pwetosaurus** [comment]
Well, I made a fiddle and after some unsuccessful attempts to make Internet Explorer crash, it finally happen and the browser crash.

[https://jsfiddle.net/pwetosaurus/0mmdy71y/](https://jsfiddle.net/pwetosaurus/0mmdy71y/)

You can find as an attachment the way IE crash after around 10 «Run» button hits.

![slick](https://cloud.githubusercontent.com/assets/2870717/12752429/d15a47fa-c9c2-11e5-9a70-261b8097d2fd.png

**Comment by simeydotme** [comment]
woah, shit...
It seems to be going in to an infinite loop... @kenwheeler , any experience on this before?

**Comment by simeydotme** [comment]
it pretty much happens every time i view that fiddle in IE10, and occasionally in IE11

**Comment by simeydotme** [comment]
clearly... we don't need sherlock... look at this:

![screenshot 160204 222048](https://cloud.githubusercontent.com/assets/2817396/12817559/96cdf52e-cb8d-11e5-800a-a904c5de531b.png)

I'll see about fixing this !

**Comment by kenwheeler** [comment]
lol thanks @simeydotme

**Comment by simeydotme** [comment]
#### Please can you test these fiddles with your IE, @pwetosaurus ... 
I've created a bugfix, and want your test results before I merge it :)

===

`Slick 1.5.9` `jQuery edge`
http://jsfiddle.net/o9jryph5/
:x: `chrome`  |  :x:  `ie`

---
`Slick 1.5.9` `jQuery 2.1.0`
http://jsfiddle.net/p0asxvs7/
:heavy_check_mark: `chrome`  | :heavy_check_mark: `ie`

---
`Slick 1.5.9` `jQuery 1.12.0` 
http://jsfiddle.net/pfn4r7tg/
:heavy_check_mark: `chrome`  | :x: `ie`

*This is the one @pwetosaurus is using*

---
`My Bugfix` `jQuery 2.1.0`
http://jsfiddle.net/t2mtf150/
:heavy_check_mark: `chrome`  | :heavy_check_mark: `ie`

---
`My Bugfix` `jQuery 1.12.0`
http://jsfiddle.net/07gauzc7/
:heavy_check_mark: `chrome`  | :heavy_check_mark: `ie`

---
`My Bugfix` `jQuery edge`
http://jsfiddle.net/n18nc3zp/
:heavy_check_mark: `chrome`  | :heavy_check_mark: `ie`

**Comment by simeydotme** [comment]
@kenwheeler ... for posterity, it appears the `.load()` and `.error()` methods are 

- firstly; deprecated since `1.8`
- secondly; a pile of dog shit x-browser

**Comment by pwetosaurus** [comment]
The fiddles cannot reproduce the issue until I add a second slick with a different class, and I made ~50 attempts with Internet Explorer on each fiddle to see if the issue is still here.

**Fiddle 1** Internet Explorer did not crash, but the second slide wasn't working (it wasn't working on Firefox on Ubuntu neither).
**Fiddle 2** Internet Explorer did not crash, everything worked as expected.
**Fiddle 3** Internet Explorer crash, no surprise on this fiddle.
**Fiddle 4** Internet Explorer didn't crash.
**Fiddle 5** Internet Explorer didn't crash.
**Fiddle 6** Internet Explorer didn't crash.

**Comment by simeydotme** [comment]
Cool @pwetosaurus ... so you confirm my findings? :grin: 
I'll clean up and merge this in if so.

**Comment by pwetosaurus** [comment]
Well I can't figure if you're right, but at least, it does't crash anymore !

More seriously, i don't know enough how slick slider work to approve of
disapprove your corrections, but I bet that if i don't know what you fix,
at least, you know what you are doing. (i would say that my first approach
if slick was a ticket by a customer saying "it crash on IE" but I will
really soon work with it !).

And thanks to you, i had no more reason not to use Internet Explorer, and i
think i will really soon switch to it ! (Just kidding, i'm not enough
nihilist to to such a thing).

Thanks again for your time, your knowledge, and the quick fix.

Cheers.

**Comment by jakeoblivion** [comment]
The slick slider is amazing, but I had similar problems. You may not have realised, but this bug actually crashed/hung mozilla firefox aswell. 

It took around 20 seconds to load a normal page, but once cached, it is difficult to discover that there is an underlying problem. The main trouble was was loading images for the first time before they are cached and it would go into some sort of recursive loop. The more images you had, the longer it would take. 

I spent hours trying to figure it out, but I tried your bugfix branch and it works like a charm! Thank you so much for fixing this! 

Cheers.

**Comment by simeydotme** [comment]
thanks @jakeoblivion ,,, sounds like a good push for @kenwheeler to get a release sorted :smile: :wave:

**Comment by Gaetan-dc** [comment]
Had the same exact problem, and your bug fix fixed it for me also. Thank you.

**Comment by marcopanichi** [comment]
I had a similar problem and I solved.

On Chrome (72.0.3626) and Firefox (61.0.2), the tab with the slick carousel freezed (lots of request on the Network tab)

The problem was the rule `.slick-list { overflow: inherit; }`

I removed this rule and the problem gone away.
