### ISSUE TITLE
How I quick fixed my lazyload issue

### ISSUE THREAD

**Issue by cannect** [kenwheeler/slick#2092]
Hi guys,

Just to let you know, I just quick fixed my lazyload issue. 
- I have an carousel running, connected with a slider. 
- They have 180 images in it
- I use the data-lazy attribute
- Initiating the slider with `lazyLoad: 'ondemand'`

And that fails working. It just loads 92 images at once when opening the page. What I did is adding this piece of code **after** the line `loadRange = _.$slider.find('.slick-slide').slice(rangeStart, rangeEnd);`.

I added:
```
        if( loadRange.length >  10 ) {
            return;
        }
```

And that just prevent Slick to load so much images at once. After that it works fine! 

Thanks for this awesome slider!

**Comment by leggomuhgreggo** [comment]
Good intel, thanks @cannect!
