### ISSUE TITLE
position of active slide when in vertical mode

### ISSUE THREAD

**Issue by rmi7** [kenwheeler/slick#2095]
So I have this vertical slideshow.

Currently the active slide is always at the top of the window.

Is there any way to put the active slide in the vertical center of the window.
So that you can see previous slides above the current slide, and next slides below the current slide.

My slick config:

```
slick({
      infinite: false,
      focusOnSelect: true,
      centerMode: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      vertical: true,
      verticalSwiping: true
});
```

if you could just point me to the css class where I should change this within slick.css

**Comment by simeydotme** [comment]
This is a support query and better suited to support channels (check the contributing guidelines.

I'm closing. :)

set your slidesToShow to 1, and add centerPadding: 30 (read the docs, or get on Gitter)
