### ISSUE TITLE
next and prev

### ISSUE THREAD

**Issue by soccerKevin** [kenwheeler/slick#2096]
I'm using 2 carousels on 1 page (not linked together).  the first carousel works great.
the second carousel will only advance once, then won't go forwards or backwards.
my options
      prevArrow: "my button selector"
      nextArrow: "my button selector"
      infinite: false
      respondTo: 'my container selector'
      slidesToShow: 6
      slidesToScroll: 6

I have even tried setting jquery handlers on the buttons and calling slickNext and slickPrev with them.
any suggestions would be awesome!

**Comment by leggomuhgreggo** [comment]
Hey @soccerKevin Can you make a fiddle. Can't diagnose potential bugs without a test-case. Please check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). Im going to close, but if you make a fiddle we can look at reopening. Thanks!
