### ISSUE TITLE
Add option to prioritise attributes `data-slick` settings

### ISSUE THREAD

**Issue by garygreen** [kenwheeler/slick#2097]
At the moment the below will still show 3 slides, even though on your data tag you have explicity set to show 2. Maybe there should be an option to 'prioritise' the data attribute settings? The data-slick setting has always been useful for overriding certain settings...

```javascript
$('.carousel').slick({
	slidesToShow: 3,
});
```

```html
<div class="carousel" data-slick='{"slidesToShow": 2}'>
	<img...>
	<img..>
</div>
```

**Comment by kenwheeler** [comment]
This is on master, I need to push a major version bump, as this func is breaking.

**Comment by garygreen** [comment]
Haha I just cloned to do a PR but saw it was already prioritising the data settings. Looking forward to new release :+1:

**Comment by garygreen** [comment]
It is breaking but no need for major release... you could add a `prioritizeDataSettings` setting and have it false by default. That is what my PR would have been.

**Comment by kenwheeler** [comment]
I'm really trying to reduce the surface of the current API rather than add to it, so major bump it is.

**Comment by garygreen** [comment]
Sounds good.
