### ISSUE TITLE
Setting slider to scroll only when it reaches the right most slide

### ISSUE THREAD

**Issue by craigkg** [kenwheeler/slick#2098]
In this fiddle https://jsfiddle.net/craigkg/p9xntqdo/1/ I'd like for the scroll affect to only activate once `.slick-current` is the right most displayed slide rather than `.slick-current` always being the left most displayed slide. When the right arrow key is pressed, I want the slides to remain stationary while `.slick-current` moves to the next item, thus requiring the right arrow to be pressed 4 times before the scrolling reveals slide5. Is this possible?

**Comment by simeydotme** [comment]
this doesn't make much sense from a user's point of view...
why would they click "next" 4 times, with no actual effect ?

**Comment by craigkg** [comment]
It is part of a navigational menu system. Each slide contains a different menu set that can be navigated up and down when that slide is the `.slider-current` slide, so using the right arrow goes to the next menu set to the right making it the new `.slider-current`. When the edge is reached, we want the slider to move one at a time to reveal the additional menu sets. Setting `slidesToScroll: 4` makes `.slider-current` skip over three menus making only every 4th menu accessible. There is no "clicking" in this system as it has to be completely arrow key accessible.

**Comment by leggomuhgreggo** [comment]
@craigkg Seems to me you could accomplish that with `slidesToScroll: 4`, custom prev/next elements with an onClick counter triggering the slickNext and slickPrev menthos, and a little custom jquery to advance active states of the menu items. Hope that helps

**Comment by craigkg** [comment]
Thanks for trying, but that won't work unfortunately. There are no prev/next elements. There is no mouse. There is no "click" so to speak. This is for a system that has 5 button navigation: four arrow directions and a select button. Each time the right arrow is pressed the next horizontal slide is selected. Within each horizontal slide is a category header and a vertical slider with the top slide/link selected. Up and down arrows navigate the vertical menu. When the user gets to the item they want, they hit the middle/fifth button, so there is no way to "click" any other element like prev and next. This is sort of like a grid system, but with each column's vertical navigation being independent of the others.

**Comment by leggomuhgreggo** [comment]
Interesting. Might that I'm not totally following but I think you can still accomplish what you want with custom jquery and methods, in a way similar to what I described, just swapping out the dummy next/prev with arrows assigning their events to the respective method. Good luck

**Comment by simeydotme** [comment]
@leggomuhgreggo has given you the mental-tools needed to get this done :)

Anyway, unfortunately we have a lot of feature requests which are useful across a wide range of use-cases. When you seem to have a completely unique system .. it's time to consider you need to write the code yourself :) -- hacking an existing thing to suit your very unusual use-case is not a good way to go about software development.

Best of luck, Simon

**Comment by Vizz85** [comment]
@craigkg wanted the same effect and this codepen https://codepen.io/dolce/pen/QarQde made my day
