### ISSUE TITLE
Why is mobileFirst defaulted to false?

### ISSUE THREAD

**Issue by mike3run** [kenwheeler/slick#2102]
That took me a while to figure out, lol mobieFirst should an obvious choice given that all of the major frameworks work the same way :cry:

**Comment by leggomuhgreggo** [comment]
I think the way it was originally written was not mobile first, and the mobileFirst option was added subsequently, but setting it to true would have been a breaking change. I can see the sense in defaulting to mobileFirst: true, but I think implementing it would need to be done carefully. That's just my guess though, Im not 100 sure.

**Comment by mike3run** [comment]
I kind of get it but c'mon what year are we on? They could deprecate the non-mobile first and make mobile first the default. 

Just sayin'

**Comment by leggomuhgreggo** [comment]
Hah, yes, well, perhaps so! I think this is the original issue for reference: #951

**Comment by mike3run** [comment]
Thank you very much @simeydotme :grinning: for the coming soon label!
Have a wonderful day!
