### ISSUE TITLE
Remove slides based on dynamic values

### ISSUE THREAD

**Issue by simoncreative** [kenwheeler/slick#2103]
I'm using Slick to showcase a schedule of events. Each slide is one event. I'm using Moment JS along with Timestamp JS to compare the current date/time to the date/time shown on each slide. If the current date/time > then the slide's event/time, the slide will display a custom message such as "event ended". 

However, I would simply prefer to remove the slide all together. The following is my afterChange function:

```
$('.slider').on('afterChange', function (event, slick, currentSlide, nextSlide) {
	if ($(currentSlide).find('.timedate em:contains("ended")')) {
                $('.slider').slick('slickRemove',slideIndex - 1);
		if (slideIndex !== 0) {
		        slideIndex--;
	        }
	}
});
```

The issue that I'm having is that only the first slide is effected i.e gets removed. The carousel continues to cycle without effecting any of the other slides even those those slides also met the same criteria.

**Comment by leggomuhgreggo** [comment]
Hey @simoncreative, I'm closing this because there is no reduced test-case, and it's more of a support request than a bug. [Check out the contribution guidelines here](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown); there are other forums for this type of question. Thanks!
