### ISSUE TITLE
Pause carousel without clearing the interval.

### ISSUE THREAD

**Issue by erwinsmit** [kenwheeler/slick#2105]
Currently calling slick('slickPause') also clears the interval. It would be great if there it's also an option to pause the carousel without having to start the interval again when un-pausing. 

I know this is awkward to achieve, because it needs some type of real time tracking on the interval function.

**Comment by erwinsmit** [comment]
Not a bug, will raise this as a feature request on the reddit or gitter channel.

**Comment by simeydotme** [comment]
Please check out https://github.com/kenwheeler/slick/pull/2060 :)

**Comment by erwinsmit** [comment]
@simeydotme, cool thanks.

When I click the pause button to pause the carousel, and than click resume. It is still re-starting the interval with the original autoplaySpeed.

What I have to achieve for a project I'm working on is that let's say the autoplaySpeed is 5000. 

When the user clicks pause after 2.5 seconds, when the user unpauses the carousel should only show the slide for an additional 2.5 seconds. 

I got this working on my fork.
See: http://jsfiddle.net/erwinsmit/wsrvtwL4/4/
The code: https://github.com/erwinsmit/slick/commit/57546cf986be2234cd7a40f8562830ccf46d3d76

I could submit this as a PR if you think it will add value to the project.

**Comment by simeydotme** [comment]
@erwinsmit I see what you've attempted to do, but it's a little messy right now.
I believe it would add value to allow pause/resume from the same time , but there's another feature request for a "time remaining" count-down. This should probably be bundled with that, and thought about differently.

Also your current fork doesn't cater for the hover interrupts.
and there's no need for binding to `_.initials` :)

Thanks for your suggestion, we'll try to get this sorted!

**Comment by erwinsmit** [comment]
I know, it was more of a suggestion than a proper PR. It does the job for our project though, because pauseOnHover is switched off. 

Working with timing functions in intervals is always going to be messy I think, so I'm looking forward seeing the proper fix for this.

**Comment by simeydotme** [comment]
yup, it should eventually probably be handled by it's own internal method, instead of being snuck in to Autoplay methods :)
