### ISSUE TITLE
Should use jQuery object instead of $ so it doesn't conflict with others libs.

### ISSUE THREAD

**Issue by mavenforphp** [kenwheeler/slick#2106]
Slick uses code like $('.anyelement').somethin()g. You know $ can be conflicting at a times. Like my site uses prototype with jQuery. Prototype also uses $. Now slick adds "$.fn.slick =  " in prototype, but not in jQuery.

You should instead use jQuery instances directly 
`jQuery('.anyElement').something();`

or you should pass jQuery to the function and then use as $ e.g.
```
(function($) {
  // Code goes here
})(jQuery);
``

Here is the JS Fiddle which is breaking when I have added prototype.js :- 
http://jsfiddle.net/fmo50w7n/234/
Above JsFiddle is noting but copy of one you have one website except that I have included prototype.js

**Comment by mavenforphp** [comment]
By mistake issue was closed. Re-opened again

**Comment by simeydotme** [comment]
Thanks @mavenforphp ... we'll look at this for version 2, although I think that it's already working in this manner:

https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L18-L28
