### ISSUE TITLE
Show slide in the center

### ISSUE THREAD

**Issue by LoaiBassam** [kenwheeler/slick#2108]
How can I always show the slide with class .active in the centre? every time the page loads, the slide with class .active appears in the centre. 
![capture](https://cloud.githubusercontent.com/assets/4785390/12916953/2dbefab6-cf2e-11e5-8671-854df8c9a2a5.JPG)
![2](https://cloud.githubusercontent.com/assets/4785390/12916954/2e87fd76-cf2e-11e5-9253-911c9919e27d.JPG)

**Comment by simeydotme** [comment]
Please read the contribution guidelines :)
