### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by wider2** [kenwheeler/slick#2113]
is there a simple method to make ** vertical alignment ** of carousel in the center of the page?
Does slick slider provide such function?

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/2086

@wider2 ... I appreciate you need help with your web development... however, if you really needed help with your problem... you could have asked for it in your identical issue I closed a week ago.

This is a place for tracking bugs/problems with Slick, not for helping you with the age-old CSS problem. - Please read carefully the contribution guidelines https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown and get the help you need in a more appropriate manner :)

Best, Simon.
