### ISSUE TITLE
Wrong direction value on vertical swipe

### ISSUE THREAD

**Issue by netil** [kenwheeler/slick#2114]
When setting to swipe vertically, the direction argument value on custom event is left or right.
IMO direction value should be up/down.

Check out [jsfiddle](http://jsfiddle.net/hfn8gjc1/1/) to reproduce the issue.

```js
$(".slider").slick({
	vertical: true,
	verticalSwiping: true
}).on("swipe", function(event, slick, direction) {
	$("#direction").html(direction);  // it returns left or right
});
```

**Comment by simeydotme** [comment]
fixed on master
