### ISSUE TITLE
data-slick settings cant overwrite original settings set in js

### ISSUE THREAD

**Issue by Andree3d** [kenwheeler/slick#2116]
Currently when you set any data-slick settings in html they can't overwrite original settings in js file.
Line 143: _.options = $.extend({}, _.defaults, dataSettings, settings);

in my opinion it should be : _.options = $.extend({}, _.defaults, settings, dataSettings);
since its rather normal to overwrite original settings with data in html not the other way around.

**Comment by simeydotme** [comment]
Thanks.
Please read the contribution guidelines, and search for existing issues before posting in future :)

Best, Si.
