### ISSUE TITLE
Framerate drops, laggy transition

### ISSUE THREAD

**Issue by ldwg** [kenwheeler/slick#2122]
I noticed that the framerate drops when the transition just started. The small lag is visible in the official [demo](https://kenwheeler.github.io/slick/), it becomes more obvious with a fps counter in your browser (e.g. `chrome://flags/#show-fps-counter`). 

The animation itself does not seem to be the problem, as a comparable hardware-accelerated css transformation runs on 60fps. I could not find the reason for the framerate-drop. Hopefully this documentation is helpful:

- CSS: https://jsfiddle.net/ldwg/38p2qamL/
- Slick: https://jsfiddle.net/ldwg/2Le9hhue/
- Demo-Video: https://vimeo.com/155395783

Big thanks for slick!

**Comment by leggomuhgreggo** [comment]
Hey @ldwg, I appreciate the thorough report! I think this issue is probably related to [this one](https://github.com/kenwheeler/slick/issues/2003), which includes the work around--should be addressed in the next release. Thanks!

**Comment by ldwg** [comment]
@leggomuhgreggo `useTransform: true` indeed fixed the framerate. Thanks!
