### ISSUE TITLE
slider does not reinitialize on resize if "unslick" is used in breakpoints

### ISSUE THREAD

**Issue by FilipIA** [kenwheeler/slick#2123]
When you configure the slider to destroy on a certain breakpoint, it is not reinitialized after resizing the browser because the "resize" event is detached when you perform "unslick".

```javascript
$('.slider').slick({
        dots: false,
        infinite: true,
        arrows: false,
        speed: 200,
        slidesToShow: 1,
        mobileFirst: true,
        responsive: [
            {
                breakpoint: 768,
                settings: 'unslick'
            }
        ]
});
```

Demo can be found here: https://jsfiddle.net/v5c755kp/

**Comment by mazzaker** [comment]
I don't think this is a bug, because unslick removes the complete slick-slider there will be issues when unslicked sliders still fireing events...

Maybe reinit is an option:

`  $(window).on('resize orientationChange', function(event) {
    //check window.width()...
  	$('.slider').slick('reinit');  
	});`

**Comment by Emiya0306** [comment]
@mazzaker @simeydotme Yes, it is not a bug, but I think it is not a good choice for user to reinit it by userself. Slick should have its own instance props to log its breakpoint which causes unslick event, and next time to reinit by slick self.

If there are many slickers in one page, user should not reinit slick one by one. It causes a big trouble in my case. I think the best idea is slick can reinit by itself.

**Comment by kulahin** [comment]
Try this code (using jQuery).

`var slickInitialized = false;

$().ready(function(){
	...
	slickReinit();
	...
});

// Debounce-function:
function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		if (callNow) func.apply(context, args);
	};
};

var slickReinit = debounce(function() {
    if (!slickInitialized && $(window).width() > 768) {
        slickSettings = {
            slidesToShow: 3,
            // ... or other settings ...
            responsive: [{
                breakpoint: 768,
                settings: "unslick"
        }]};
        $('#mySlider').slick(slickSettings);
        slickInitialized = true;
        $('#mySlider').on('destroy', function() {
            slickInitialized = false;
        });
        $(window).off('resize.slickReinit');
    }
    $(window).on('resize.slickReinit', slickReinit);
}, 250);`

**Comment by romannikiforov** [comment]
```javascript
const settings = {
     // default settings
    responsive: [
        {
            breakpoint: 900,
            settings: { slidesToShow: 3 }
        },
        {
            breakpoint: 600,
            settings: { slidesToShow: 2 }
        },
        {
            breakpoint: 420,
            settings: "unslick"
        }
    ]
};

const sl =  $('.slider').slick(settings);
      
$(window).on('resize', function() {
   if( $(window).width() > 420 &&  !sl.hasClass('slick-initialized')) {
         $('.slider').slick(settings);
    }
});
```

**Comment by kindofbigelephants** [comment]
This is a bad design, because you provide such an option to behave differently when the browser window resizes. Yet only one directio of resize is provided? When i move my mouse to the left it should work and when i move it to the right it shouldn't? This doesn't make any sense.

A correct design would be to either handle reinitialization natively on resize or do not provide "unslick" option at all.

**Comment by br4nnigan** [comment]
Once unslicked, there is no chance of reinitializing it apparently. So you better not resize your browser window, or slick will break.

**Comment by OleksandrKovalc** [comment]
use you head :)
(document).ready(function () {
  $(".slide-price-section").slick({
    responsive: [
      {
        breakpoint: 4000,
        settings: "unslick",
      },
      {
        breakpoint: 767,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          // arrows: false,
          // centerMode: true,
          variableWidth: true,
          prevArrow: $(".prev"),
          nextArrow: $(".next"),
        },
      },
    ],
  });
});

**Comment by treckstar** [comment]
[Added on to the code from above](https://github.com/kenwheeler/slick/issues/2123#issuecomment-445291254)

Used this logic in a Bootstrap 4 project at the medium break point. Made a few tweaks and additions so that the browser window can be resized back and forth like how project managers and clients love to do. Well done, thanks.

```js
let ssContainer = $(".o-carousel")
, ssDots = $(".m-carousel-controls__dots")
, ssNext = $(".m-carousel-controls__next")
, ssPrev = $(".m-carousel-controls__prev");

const SLICK_SETTINGS = {
    appendDots: ssDots,
    arrows: !0,
    dots: !0,
    lazyLoad: "ondemand",
    mobileFirst: !0,
    nextArrow: ssNext,
    prevArrow: ssPrev,
    responsive: [{
        breakpoint: 767,  // unslick when greater than 767 pixel width
        settings: "unslick"
    }]
};

// check in a condition, similar to a debounce
const ss = $(ssContainer).slick(SLICK_SETTINGS);
  
$(window).on('resize', function() {
    // on resize, if the width is less than 768, and has no init class, re initialize.
    if( $(window).width() < 768 &&  !ss.hasClass('slick-initialized')) {
        $(ssContainer).slick(SLICK_SETTINGS);
    }
});
```

**Comment by Prasanna-naik-97** [comment]
> I don't think this is a bug, because unslick removes the complete slick-slider there will be issues when unslicked sliders still fireing events...
> 
> Maybe reinit is an option:
> 
> `$(window).on('resize orientationChange', function(event) { //check window.width()... $('.slider').slick('reinit'); });`

But how does it automatically reinitialize slick after unclick? There must be some event which makes slick re triggered
