### ISSUE TITLE
Slider inside section with jQuery slideToggle

### ISSUE THREAD

**Issue by codiceovvio** [kenwheeler/slick#2124]
Hi, and first of all **thanks a lot** for all that work! Slick is really amazing.

I have a page with different sections which open and close with native jQuery `slideToggle()`.
I use Slick inside one of these sections. I am surely missing something obvious, for there is one thing I am not able to fix with my current setup, and is the first slide being "unstyled" for the time it needs to switch to the second (slider is set to autoplay).

Also, this happens if you first open and close another section before the one with the slider in it. It does not happen always though, but kind of randomly.
I apologize for my bad english...

I have a [fiddle](http://jsfiddle.net/codiceovvio/zfvzyfuf/) here with this set

**Comment by mazzaker** [comment]
[Check this fiddle](http://jsfiddle.net/074ncsxa/)

You can not set the slider section to display: none; at the start, slick will not init.
Trick is to stop autoplay when display is set to none.

**Comment by simeydotme** [comment]
Please refer to:
http://stackoverflow.com/questions/26677649/slick-slider-loaded-with-displaynone-creates-bad-initiation/26680322#26680322

**Comment by codiceovvio** [comment]
@mazzaker , @simeydotme thanks a lot to you both!!
I was stuck on where to apply those methods, both solutions work great, I really appreciate your kind help and time spent...thanks again guys!!
