### ISSUE TITLE
Consider making index normalization optional

### ISSUE THREAD

**Issue by bardo** [kenwheeler/slick#2125]
As mentioned in https://github.com/kenwheeler/slick/issues/961#issuecomment-72324561 slide indexes are normalized, so with `slidesToShow: 3, slidesToScroll: 3` navigation only works with multiples of 3.

I understand the reason behind this choice, however for my use case this is a bit of a problem: I'm using Slick as a calendar which shows three months, and should center on the month of the event selected by the user while still navigating months three by three. With the current behavior this is not possible, and I can only ensure that the month is visible, not that it's centered.

The behavior I'm proposing doesn't seem too unreasonable to me because it's true that the slider wouldn't be aligned to the first slide, however the same already happens with the last slide if the total number of slides is not divisible by the `slidesToShow`/`slidesToScroll` value.

Given these reasons, would you consider making index normalization optional?

(Side note: I think this behavior should be documented, it took quite a while to debug why using a native method (`slickGoTo`) would sometimes, but not always, brick the slider.)

**Comment by simeydotme** [comment]
you could set `slidesToScroll` to `1` and use your own code to interrupt and move 3 months at a time when users click on a certain arrow, or swipe the carousel.
