### ISSUE TITLE
Disable sliding when selecting a slide

### ISSUE THREAD

**Issue by paulsmithtester** [kenwheeler/slick#2127]
I am using syncing sliders
"fullslide" - 1 slide at a time
"thumbslide" - 5 slides at a time

when selecting 1 slide from thumbslide i want it to become active **without** sliding to the left or to the center. Is there a way to achieve this?

Thank you

**Comment by mazzaker** [comment]
Maybe writing the events for your needs...

First set ``focusOnSelect: false`` for the nav
Second the main should not have ``asNavFor`` or more events will be needed

```
$('.gallery-nav .slick-slide').on('click', function (event) {
    $('.gallery-main').slick('slickGoTo', $(this).data('slickIndex'));
});
```

If you provide a jsfiddle it will be easy to help you.

**Comment by simeydotme** [comment]
Thanks, @mazzaker  :)
