### ISSUE TITLE
variableWidth:true + centerMode: false need more cloned slides to fill white space

### ISSUE THREAD

**Issue by gtso86** [kenwheeler/slick#2128]
Example 1: (bug) http://jsfiddle.net/avumhxg4/1/
Example 2: (working) http://jsfiddle.net/avumhxg4/2/

Hey there, i just found a bug, when I use:

`{
centerMode: false,
variableWidth: true
}`

the slider show a white space after the last slide. But if I use `centerMode: true` the number of cloned slides increase and the problem don't happen anymore.

Is possible create a **param** to control how many cloned slides we need to fill all white space?

**Comment by leggomuhgreggo** [comment]
Hey @gtso86 check out the discussion in #1207 that's the active issue for this particular bug. I'm going to close this to avoid duplication, but thanks for the bug report!
