### ISSUE TITLE
slide animation jerky on all devices / browsers

### ISSUE THREAD

**Issue by v3nt** [kenwheeler/slick#2129]
Is there a way to make the animation smoother?
ie http://dmfkdev.jynk.net/projects/body-and-soul/  feels jerky and laggy

But a 7 year old slideshow is much smoother even with opacity animations http://dmfk.co.uk/projects/load/19-eastbourne-terrace

**Comment by leggomuhgreggo** [comment]
Hey @v3nt check out this: #2003 Just need to set `useTransform: true` It should be resolved in the next release. 

If you haven't already, check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)--it's much easier to address issues when they have a reduced test case, and searching old issues can sometimes help too. Thanks!
