### ISSUE TITLE
Circular Dependency: Responsive / asNavFor issue with Slick 1.5.2

### ISSUE THREAD

**Issue by alycda** [kenwheeler/slick#2132]
Hi,

I have recreated my issue here: http://jsfiddle.net/alyda/ufbmfdg8/3/ . The issue only occurs when the preview window is below 600px wide. Starting at a larger breakpoint and scaling down will not reproduce the issue, the preview window must be smaller than 600px wide when you click 'run'.

My issue is with the following settings:

````
    slick: {
            slidesToShow: 1,
            slidesToScroll: 1,
            infinite: true,
            speed: 300,

            dots: false,
            asNavFor: "#description-carousel"

            responsive: [{
                breakpoint: 600,
                settings: {
                    arrows: false
                }
            }]
        }
````

When the slider is initialized and the viewport window is less than 600px, I get an error from `Slick.prototype.asNavFor()`: `Uncaught TypeError: Cannot read property 'getSlick' of undefined`. From what I can understand, when I have the responsive setting enabled, somehow `Slick.prototype.asNavFor()` gets called and expects the other slider to already be initialized. In the following line:

````
asNavFor = _.options.asNavFor !== null ? $(_.options.asNavFor).slick('getSlick') : null;
````

`_.options.asNavFor` is equal to `"#description-carousel"` so when it tries to execute `$(_.options.asNavFor).slick('getSlick')` it fails because the second slider (#description-carousel) has not yet been initialized as a slick slider.

This only happens when I have the responsive setting. if I remove that, the sliders initialize no problem. With this setting, and above the 600px breakpoint `Slick.prototype.asNavFor()` is not called upon slider initialization and therefore does not have a circular dependency.

**Comment by leggomuhgreggo** [comment]
Looks like you're using version 1.5.2, which has [this error](https://github.com/kenwheeler/slick/issues/1276)

[Recreated](http://codepen.io/leggomuhgreggo/pen/MKRPdR) with the master js (and different images placekitten was 404ing for me) and it works--should be able to use any version after 1.5.2 

Hope that helps

**Comment by alycda** [comment]
Thanks, I tried searching the open & closed issues for 'asNavFor' but did not see this one.
