### ISSUE TITLE
inserting slick into magento.

### ISSUE THREAD

**Issue by parmvir25** [kenwheeler/slick#2133]
hi there, i get this error. 

uncaught TypeError: _.JqueryprevArrow.on is not a function

Slick.initArrowEvents @ slick.js:1226
Slick.initializeEvents @ slick.js:1258
Slick.init @ slick.js:1205
Slick @ slick.js:178
Jquery.fn.slick @ slick.js:2663
(anonymous function) @ (index):1407
e.resolveWith @ init.js:2
e.extend.ready @ init.js:2
c.addEventListener.B @ init.js:2

please do help..

**Comment by passion4code** [comment]
Here's a demo of slick in magento https://na.merch.riotgames.com/en/

**Comment by parmvir25** [comment]
thank you but i need some help to fix those errors.. it works fine outside magento but when i put in magento it doesnt work like it should work. the jquery magento using is 1.7

**Comment by simeydotme** [comment]
looks like you have a rewrite-rule on the "$" character, meaning it will fuck up all references to "$" hinted at by: `_.JqueryprevArrow.on` which should be: `_.$prevArrow.on` ... this is not an issue :)

**Comment by parmvir25** [comment]
i did not changed anything.. downloaded and conntected it to magento..
