### ISSUE TITLE
show slide indicator dots even if only one slide

### ISSUE THREAD

**Issue by adrien-be** [kenwheeler/slick#2134]
I have implemented a custom pagination using the "slide indicator dots" such as in this example https://jsfiddle.net/AdrienBe/L0v2s26t/

However, when there is only one slide, the "slide indicator dots" are removed. See example on https://jsfiddle.net/AdrienBe/m35n3qcj/

Is there a way to "fix" this (still show the relevant custom pagination) without forking the repo?

Thanks in advance

**Comment by mazzaker** [comment]
sure:

[Fiddle](https://jsfiddle.net/f54hje5e/1/)

You can add an item, the js check the items and only change the slider if count(items) == 1

In the fiddle there is a little issue. You have set a border so the width is calculated in css and will not change if the viewport width changes...
If you can remove the border set the item width to 100% and all will be fine.

**Comment by adrien-be** [comment]
Does the job... but that's a pretty dirty hack :/

Adding the relevant HTML after the slider might be a simpler/cleaner solution even though not what I was hoping for.

**Comment by simeydotme** [comment]
@adrien-be .. when you have dirty ui, you need dirty hacks :wink:  ... I think you meant to say something like:

> "WOW!! :tada: :astonished: 
> Thanks @mazzaker for taking your time to solve my problem!!, and even describing extra how to overcome an additional problem with my ui... Really appreciate your help. Good day! :bow:"

Cheers, Si.

**Comment by simeydotme** [comment]
and: if you really want a border, nest a box inside the slider with the border... `no hacky the box-model`

**Comment by adrien-be** [comment]
@simeydotme answer edited. Still, I disagree that dirty hacks are always needed. Anyhow, not a big deal.
