### ISSUE TITLE
init event fired before responsive finished

### ISSUE THREAD

**Issue by vkollin** [kenwheeler/slick#2135]
Hi,

I discovered some weird behavior when I initialize slick (version: 1.5.9).

My slick config
```js
{
    mobileFirst: true,
    slidesToShow: 2,
    slidesToScroll: 2,
    responsive: [{
        breakpoint: 992,
        settings: {
            slidesToShow: 6,
            slidesToScroll: 6
        }
    },{
        breakpoint: 768,
        settings: {
            slidesToShow: 4,
            slidesToScroll: 4
        }
    },{
        breakpoint: 480,
        settings: {
            slidesToShow: 3,
            slidesToScroll: 3
        }
    }]
}
```
The problem is that I need to track when the slider was initialized and decided how many items it'll show depending on the breakpoints and doing some stuff with only that items that have ".slick-active" class.

Lets assume we have a document width where 4 items should be active. So when I listen to the init event and stop the code from running it only shows me the default value of 2 items and after it, it calculates the right numbers of active items from `checkResponsive()` but it's too late and I cant listen to it (cause there is no event).

So now we come to the weird part. 

I tried to re-create this feature/bug in http://jsfiddle.net/simeydotme/fmo50w7n/

Doing there the same stuff (same config) and added an event listener and listen on init and printing the number of active items... and ... I get the expected number of 4 active items ... 

I tried to find the difference for some hours now and didn't find anything that would lead to this behavior and ended up with adding a new trigger in `checkResponsive()`:

```
// only trigger breakpoints during an actual break. not on initialize.
if( !initial && triggerBreakpoint !== false ) {
        _.$slider.trigger('breakpoint', [_, triggerBreakpoint]);
} else {
        // Added this trigger as workaround
        _.$slider.trigger('initBreakpoint');
}
```

Is there someone who can help me with this? What could be the cause for this behavior? Moreover, why is the breakpoint event excluded on initialize or why is there no event after fully finished the constructor?

Many thanks for any help

Best
 Vincent

**Comment by mazzaker** [comment]
Your fiddle is not right one.

[Working fiddle](http://jsfiddle.net/xp6yd7tc/)

Seems to work for me.

**Comment by vkollin** [comment]
Thanks for the reply.

Sorry, I meant I used the linked fiddle as a point of start, but couldn't recreate the problem.

My question is more, if anyone knows of a situation (because of any side effects or something else) where the init event is triggered as long as there are still the default amount of slides, based on the default value (2 slides, in my example above) active. After the init event was triggered there is the correct amount of active slides (e.g. 4 slides, because the width of the window is 800px). 

Besides that slick is working as expected.

So maybe someone had the same behavior and solved it ...

**Comment by simeydotme** [comment]
```js
$(document).on( "ready" , function() {
  if( slides >= 4 ) {
    $(element).slick();
  }
});```

**Comment by bobbzorzen** [comment]
Had the same problem, was running slick 1.5.7, upgraded to 1.6.0 and it seems to be fixed
