### ISSUE TITLE
When infinite="false" can't Show last-one Item.

### ISSUE THREAD

**Issue by misak1** [kenwheeler/slick#2136]
Look at this

<table cellspacing="0" cellpadding="0" border="1">
  <col width="77" span="7">
  <tr>
    <td width="77">dots</td>
    <td width="77">infinite</td>
    <td width="77">slideItem</td>
    <td width="77">slidesToShow</td>
    <td width="77">slidesToScroll</td>
    <td width="77">dots</td>
    <td width="77">result</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">7</td>
    <td align="right">2</td>
    <td align="right">2</td>
    <td align="right">3</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">7</td>
    <td align="right">2</td>
    <td align="right">1</td>
    <td align="right">6</td>
    <td>OK</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">7</td>
    <td align="right">3</td>
    <td align="right">3</td>
    <td align="right">2</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">7</td>
    <td align="right">3</td>
    <td align="right">2</td>
    <td align="right">3</td>
    <td>OK</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">7</td>
    <td align="right">4</td>
    <td align="right">4</td>
    <td align="right">2</td>
    <td>OK</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">5</td>
    <td align="right">2</td>
    <td align="right">2</td>
    <td align="right">2</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">5</td>
    <td align="right">4</td>
    <td align="right">4</td>
    <td align="right">1</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">9</td>
    <td align="right">3</td>
    <td align="right">3</td>
    <td align="right">3</td>
    <td>OK</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">9</td>
    <td align="right">2</td>
    <td align="right">2</td>
    <td align="right">4</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">9</td>
    <td align="right">2</td>
    <td align="right">1</td>
    <td align="right">8</td>
    <td>OK</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">9</td>
    <td align="right">4</td>
    <td align="right">4</td>
    <td align="right">2</td>
    <td>NG</td>
  </tr>
  <tr>
    <td align="center">TRUE</td>
    <td align="center">FALSE</td>
    <td align="right">9</td>
    <td align="right">5</td>
    <td align="right">5</td>
    <td align="right">2</td>
    <td>OK</td>
  </tr>
</table>

**Comment by simeydotme** [comment]
Interesting... could you give a little more information and consider using http://jsfiddle.net/simeydotme/fmo50w7n/ a fork of this fiddle to show your issue? :)

**Comment by misak1** [comment]
I have been waiting since making code to reproduce .

First you paste the image .
slick.js is not changed.

![slick-issue](https://cloud.githubusercontent.com/assets/1531196/13164713/d0fc7464-d6fa-11e5-8228-b7af17d1f2a4.gif)

**Comment by misak1** [comment]
Is this buggy version.

http://jsfiddle.net/misak1/0sdfxw8s/2/

**Comment by mazzaker** [comment]
Why you so not use the current version from master?

I cannot see any issues with the current version.

**Comment by misak1** [comment]
I downloaded from the Demo site.
http://kenwheeler.github.io/slick/

ex.
```
$ wget http://kenwheeler.github.io/slick/slick/slick.js
```

**Comment by simeydotme** [comment]
@mazzaker is correct, appears fixed on `master`, please await a release :)

**Comment by misak1** [comment]
This was happened by the download of ZIP.
