### ISSUE TITLE
Bitdefender warns me not to visit the demo page?

### ISSUE THREAD

**Issue by G4MR** [kenwheeler/slick#2137]
I'm not sure why that is the case, but wondering if you guys would know why bitdefender would warn me from visiting the demo page?

**Comment by leggomuhgreggo** [comment]
What's the warning?

**Comment by leggomuhgreggo** [comment]
[Heres the results](https://sitecheck.sucuri.net/results/kenwheeler.github.io/slick/) from a sucuri scan. Nothing seems troubling. Anything DNS related would be in github control, I'm pretty sure. None of the scripts included are particularly menacing, although I think the CDNs use cookies; so perhaps bitdefender is being sensitive to that.
