### ISSUE TITLE
beforeChange and afterChange do not fire on swipe

### ISSUE THREAD

**Issue by danyj** [kenwheeler/slick#2138]
I am stooping videos from playing on beforeChange  and this works fine if I click on dots or arrows, but if I swipe the event is not triggered. 
Any help is appreciated!

**Comment by leggomuhgreggo** [comment]
Hey @danyj when reporting issues, it's crucial to have a reduced test case in a jsfiddle or a codepen--check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

I'm going to close this for now, but can look at reopening if you get that test case.

Thanks

**Comment by danyj** [comment]
sorry bud , will do

**Comment by danyj** [comment]
nope , must be on my end , looks ok 
http://jsfiddle.net/Lf1wvdvx/

**Comment by leggomuhgreggo** [comment]
Thanks. Good luck!
