### ISSUE TITLE
Something wrong with arrows in vertical mode

### ISSUE THREAD

**Issue by inferusvv** [kenwheeler/slick#2146]
This bug is reproducable in vertical mode with `infinite: false`

1. Open jsFiddle below.
2. Click on "Next" many times (for example 3 times)
3. Click "Prev".

"Prev" is clickable after N times you clicked "Next"

====================================================================

use this jsfiddle to reproduce your bug: 
https://jsfiddle.net/cx5jLnae/

**Comment by leggomuhgreggo** [comment]
[Confirmed with the master](https://jsfiddle.net/4djkfavz/)

**Comment by mazzaker** [comment]
Same behavior when not in vertical mode...

**Comment by simeydotme** [comment]
its not "n times" it's a total of 3 times in @leggomuhgreggo fiddle, even if I press next 40+ times, still 3rd time on prev. :)

**Comment by inferusvv** [comment]
@simeydotme Yes! You are write :)

**Comment by simeydotme** [comment]
(edited previous comment, after trying with `slidesToShow: 5`

**Comment by johannesdold** [comment]
Any updates here? We have several clients that are waiting for a patch for this bug. An update would be great. Any way we can help with that?

**Comment by simeydotme** [comment]
closed by #2152 , please take the master branch, or wait for @kenwheeler to release the next version.

**Comment by shivika** [comment]
+1
