### ISSUE TITLE
The slider will not work on iPads.  the pictures stacks on top of each other.  It also want work on older version of vision of windows.

### ISSUE THREAD

**Issue by Smart9110** [kenwheeler/slick#2147]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by simeydotme** [comment]
I thought the `issue_template.md` might help... at least a little....

#nope.

![nope](http://memesvault.com/wp-content/uploads/Nope-Meme-Gif-06.jpg)

**Comment by simeydotme** [comment]
![](https://slack-imgs.com/?url=http%3A%2F%2Fi0.kym-cdn.com%2Fphotos%2Fimages%2Ffacebook%2F000%2F365%2F479%2F477.gif&width=400&height=314)

**Comment by simeydotme** [comment]
![](http://2.bp.blogspot.com/-M_vXmMr2gm0/UUObnUI0uDI/AAAAAAAAAE4/g6B9lqvGyqs/s1600/facepalm.jpg)
