### ISSUE TITLE
When swiping slick carousel click event is fired

### ISSUE THREAD

**Issue by xtatanx** [kenwheeler/slick#2150]
Hello guys, I am using Slick carousel with lightcase.js and the problem I am facing is that when I am swiping slick the click event is triggered and the pop up is showed immediately. Sometimes the click event is not fired but this just happen when you swiped all the slide, if you just swipe half the way the event is triggered. If someone else have faced that problem I appreciate if you could tell me of a possible workaround.

Thank you!

**Updated with the fiddle**
Here is the fiddle: [lightcase + slick fiddle](https://jsfiddle.net/zLk1otb3/)

**Comment by xtatanx** [comment]
@simeydotme I already updated the issue, is there a way we can re open it?

**Comment by simeydotme** [comment]
https://jsfiddle.net/o5pcjrpb/
:kiss:

**Comment by simeydotme** [comment]
it's technically a lightcase issue... but I helped you anyway ;) 
damn... think of the amount of rep I'd have on Stackoverflow with all these support issues... :disappointed:
