### ISSUE TITLE
on-init attribute not working (with fix)

### ISSUE THREAD

**Issue by rfaill** [kenwheeler/slick#2155]
The on-init attribute needs a bug fix - specifically, I think you need to move the event handler to before you initialize the slider to get it working, and change the first like on the function to "if(scope.onInit)". Like below:

`            //
            // Must be applied before initializing...
            slider.on('init', function (sl) {
              if (scope.onInit) {
                scope.onInit();
              }
              if (currentIndex != null) {
                return sl.slideHandler(currentIndex);
              }
            });
            slider.slick({
               .....
`

**Comment by leggomuhgreggo** [comment]
Hey @rfaill. Interesting bug. Can you make a fiddle to demo it? Here's the one from the [contribution guidelines ](http://jsfiddle.net/simeydotme/fmo50w7n/). Thanks!

**Comment by rfaill** [comment]
Well, this is embarrassing. I meant to drop this issue into the "angular-slick" repo. Sorry for the confusion!
