### ISSUE TITLE
Save images via long press on iOS?

### ISSUE THREAD

**Issue by ericestes** [kenwheeler/slick#2156]
On iOS, you can save images by pressing and holding on an image, which will bring up a menu to save and copy it. It seems that Slick prevents this behavior. Is there a way around this?

**Comment by leggomuhgreggo** [comment]
Hey, I was looking into this a little bit and found [a pretty comprehensive answer in a statckoverflow thread](http://stackoverflow.com/questions/5163831/uiwebview-enabling-action-sheets-on-img-tags/5607694#5607694) which might be helpful to you. Sounds like the feature is only in Safari, anymore. As far as the slick library goes, there are some preventDefaults being called which might be complicating things. Hope that helps!

**Comment by ericestes** [comment]
I found a solution to this: adding -webkit-touch-callout: default; to the images.

**Comment by leggomuhgreggo** [comment]
Nice, that's good intel
