### ISSUE TITLE
slickAdd fails to add item if index=n and addBefore = true

### ISSUE THREAD

**Issue by JonathanAquino** [kenwheeler/slick#2157]
slickAdd() fails to add an item if index = the number of elements and addBefore = true.

Logically, if index = the number of elements and addBefore = true, then the item should be added to the end.

====================================================================

http://jsfiddle.net/JonathanAquino/3naceufb/

====================================================================

#### Steps to reproduce the problem

1. Go to http://jsfiddle.net/JonathanAquino/3naceufb/
2. Click the button

====================================================================

#### What is the expected behaviour?

An item should be added to the end.

====================================================================

#### What is observed behaviour?

No items are added.

====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome.
- Which jQuery/Slick version are you using? 1.5.9
- Did this work before? No.

**Comment by simeydotme** [comment]
:clap: :clap: :clap: 

The first person to use the Issue Template !!

:tada: :tada: :tada: 

Congrats, @JonathanAquino  !!! :bow:  :tophat:

**Comment by simeydotme** [comment]
works fine, for me:
http://jsfiddle.net/3naceufb/1/

(ps, your fiddle was missing a few options to actually test properly.)

**Comment by JonathanAquino** [comment]
@simeydotme No, the issue is still there. You had index 1, but the problem happens if you make the index 2. If the index is 2 and beforeNext=true, then logically the new item should appear at the end. See http://jsfiddle.net/JonathanAquino/sc8o5bbb/1/

**Comment by simeydotme** [comment]
but how "logically" can you insert before something that doesn't exist... what do you expect to happen if you insert after `99` in a 3-slide slider? what about inserting after `mcMuffin` ? :confused: ... 

Why can't you use `slickAdd()` normally with the after being the last index?

**Comment by JonathanAquino** [comment]
In a 3-slide slider, if you try to insert something "before" index 3, it should appear after index 2, even though index 3 doesn't actually exist.

You mentioned the last index - how can I get the last index? Slick doesn't seem to provide a way to return the last index.

**Comment by simeydotme** [comment]
`lastIndex = $("#dashboard").getSlick().slideCount`
