### ISSUE TITLE
pauseOnHover not working on two linked sliders

### ISSUE THREAD

**Issue by linda6907** [kenwheeler/slick#2161]
How can I make pauseOnHover work on both two sliders when slider-one works as a big slider and slider-nav is linked to be slider-one's thumbnail slider. 

$('.slider-one').slick({

slidesToShow: 1,
slidesToScroll: 1,
...
asNavFor: '.slider-nav',
...
]

});
$('.slider-nav').slick({
autoplay: true,
pauseOnHover: true,
slidesToShow: 3,
slidesToScroll: 1,
asNavFor: '.slider-one',
...
]
});

I am assumed they should be linked on pauseOnHover.
I can only make one slider work on pauseOnHover, but not on both. 
It happens on chrome/firefox/safari and the version of the slick.js is 1.5.7.

**Comment by mazzaker** [comment]
Workaround:

    $('.slider-one').on('mouseenter', function(){
        $('.slider-nav').slick('slickPause');
    });
    $('.slider-one').on('mouseleave', function(){
        $('.slider-nav').slick('slickPlay');
    });

**Comment by leggomuhgreggo** [comment]
Thanks @mazzaker!

@linda6907 check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), generally we require a reduced test case in a fiddle or codepen--just a note for future. Thanks!

**Comment by rjft197** [comment]
I found this problem too, I have a code change to Slick.js that works for me.  I've also noted that you can't have pauseOnDotsHover without enabling pauseOnDots.  I've got a version that has the dots over the image and want to only pause it on hover of the dots.  So I've added this to my code too.  The code difference for what I've done is.

@@ -765,8 +765,10 @@
 
         $(document).off(_.visibilityChange, _.visibility);
 
-        _.$list.off('mouseenter.slick', $.proxy(_.setPaused, _, true));
-        _.$list.off('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        if (_.options.pauseOnHover === true && _.options.autoplay === true) {
+            _.$list.off('mouseenter.slick', $.proxy(_.setPaused, _, true));
+            _.$list.off('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        }
 
         if (_.options.accessibility === true) {
             _.$list.off('keydown.slick', _.keyHandler);
@@ -1275,8 +1277,10 @@
 
         $(document).on(_.visibilityChange, $.proxy(_.visibility, _));
 
-        _.$list.on('mouseenter.slick', $.proxy(_.setPaused, _, true));
-        _.$list.on('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        if (_.options.pauseOnHover === true && _.options.autoplay === true) {
+            _.$list.on('mouseenter.slick', $.proxy(_.setPaused, _, true));
+            _.$list.on('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        }
 
         if (_.options.accessibility === true) {
             _.$list.on('keydown.slick', _.keyHandler);
@@ -2078,16 +2082,39 @@
     };
 
     Slick.prototype.setPaused = function(paused) {
+        console.log('Checking Pause ' + paused)
+        var _ = this,
+            asNavFor = _.options.asNavFor;
 
-        var _ = this;
+        if ( asNavFor && asNavFor !== null ) {
+            asNavFor = $(asNavFor).not(_.$slider);
+        }
 
-        if (_.options.autoplay === true && _.options.pauseOnHover === true) {
-            _.paused = paused;
-            if (!paused) {
-                _.autoPlay();
-            } else {
-                _.autoPlayClear();
+        _.paused = paused;
+        if (!paused) {
+            _.autoPlay();
+            
+            if ( asNavFor !== null && typeof asNavFor === 'object' ) {
+                asNavFor.each(function() {
+                    var target = $(this).slick('getSlick');
+                    if(!target.unslicked) {
+                        target.autoPlay();
+                    }
+                });
+            }
+
+        } else {
+            _.autoPlayClear();
+
+            if ( asNavFor !== null && typeof asNavFor === 'object' ) {
+                asNavFor.each(function() {
+                    var target = $(this).slick('getSlick');
+                    if(!target.unslicked) {
+                        target.autoPlayClear();
+                    }
+                });
             }
+
         }
     };

**Comment by rjft197** [comment]
Actually that code should be...

```
@@ -765,8 +765,10 @@
 
         $(document).off(_.visibilityChange, _.visibility);
 
-        _.$list.off('mouseenter.slick', $.proxy(_.setPaused, _, true));
-        _.$list.off('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        if (_.options.pauseOnHover === true && _.options.autoplay === true) {
+            _.$list.off('mouseenter.slick', $.proxy(_.setPaused, _, true));
+            _.$list.off('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        }
 
         if (_.options.accessibility === true) {
             _.$list.off('keydown.slick', _.keyHandler);
@@ -1275,8 +1277,10 @@
 
         $(document).on(_.visibilityChange, $.proxy(_.visibility, _));
 
-        _.$list.on('mouseenter.slick', $.proxy(_.setPaused, _, true));
-        _.$list.on('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        if (_.options.pauseOnHover === true && _.options.autoplay === true) {
+            _.$list.on('mouseenter.slick', $.proxy(_.setPaused, _, true));
+            _.$list.on('mouseleave.slick', $.proxy(_.setPaused, _, false));
+        }
 
         if (_.options.accessibility === true) {
             _.$list.on('keydown.slick', _.keyHandler);
@@ -2077,17 +2081,34 @@
 
     };
 
+    Slick.prototype._setPaused = function(paused) {
+        var _ = this;
+
+        _.paused = paused;
+        if (!paused) {
+            _.autoPlay();
+        } else {
+            _.autoPlayClear();
+        }
+    };
+
     Slick.prototype.setPaused = function(paused) {
+        var _ = this,
+            asNavFor = _.options.asNavFor;
 
-        var _ = this;
+        _._setPaused(paused);
 
-        if (_.options.autoplay === true && _.options.pauseOnHover === true) {
-            _.paused = paused;
-            if (!paused) {
-                _.autoPlay();
-            } else {
-                _.autoPlayClear();
-            }
+        if ( asNavFor && asNavFor !== null ) {
+            asNavFor = $(asNavFor).not(_.$slider);
+        }
+
+        if ( asNavFor !== null && typeof asNavFor === 'object' ) {
+            asNavFor.each(function() {
+                var target = $(this).slick('getSlick');
+                if(!target.unslicked) {
+                    target._setPaused(paused);
+                }
+            });
         }
     };
```

**Comment by richardwiggins** [comment]
Has anyone got this actually working properly? @mazzaker's version seems a little inconsistent for me, especially as I need it to pause both ways.
