### ISSUE TITLE
initial slide not a multiple of slidesToScroll

### ISSUE THREAD

**Issue by Activee** [kenwheeler/slick#2162]
So when initialSlide is not a multiple of slidesToScroll problems happen.

The use case is something like the matchh section on this site http://www.mlssoccer.com/ . The slider should start at the upcoming match but it's not possible to do so atm.

**Comment by leggomuhgreggo** [comment]
Hey @Activee check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). Issues need a reduced test case, like a jsfiddle, for debugging. I'm gonna close this for the time being, but can definitely look at reopening if you spin somethin up--there's a template you can fork in the contribution guidelines. Thanks!
