### ISSUE TITLE
slidesToShow dynamically

### ISSUE THREAD

**Issue by Jurero123** [kenwheeler/slick#2163]
Hi,

first I would like to thank you for such an awesome product.

I have one small problem and I don't want to use some hack-ish solutions. I am using responsive with two different breakpoints. At start it is set to display 3 slides, but those slides are being added from WordPress backend as Custom Post Type - Team Members.

Theme is being made for small tour guides or large tour package agencies. If an agency has 3 or more employees everything is working perfectly, but if there is only one tour guide in a company there is a problem, since slide is still displaying 3 at start and that one team member is in first column on the left.

Is there any easy, non-hackish solution I can use? 

Thank you,
Jure

Here is code I am using:

jQuery(function($){

  $('.team-carousel').slick({
   dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 3,
  slidesToScroll: 3,
  responsive: [
    {
      breakpoint: 992,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
});
});

**Comment by mazzaker** [comment]
Here is the code I use for variable slidesToShow:

````var sliderNav = $('.slider-nav');
var maxItems = Math.round(sliderNav.parent('div').width() / 201);
    if(sliderNav.children('div').length < maxItems) {
        maxItems = sliderNav.children('div').length;
    }
    sliderNav.slick({
        slidesToShow: maxItems,
        slidesToScroll: 1,
        swipeToSlide: true,
        asNavFor: '.slider-for',
        dots: true,
        centerMode: false,
        focusOnSelect: true
    });````

Otherwise could you please provide a fiddle with your issue.

**Comment by Jurero123** [comment]
Thank you for your reply.

I may asked this question the wrong way. All I want to achieve is that if there is only one team member added as custom post type in WordPress for slidesToShow to be 1. If there are 2 members in query slidesToShow shoud be 2 and same for 3 added mambers. Maximum number I want to display is 3. If there are more, slider should be activated.

**Comment by mazzaker** [comment]
What do you mean by  "slider should be activated"?

    if(sliderNav.children('div').length >= 3) {
        sliderNav.slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            swipeToSlide: true,
            dots: true,
            centerMode: false,
            focusOnSelect: true
        });
    }

You can style your "not slider" with
    .slider-nav:not(.slick-initialized){
        ...
    }
    
Replace 'div' with the slide element (image, ...)

**Comment by simeydotme** [comment]
Thanks @mazzaker

**Comment by Jurero123** [comment]
Thank you @mazzaker, was taking some time off, this was a pleasant surprise after comeback :+1:

**Comment by Tebzamops** [comment]
I need help with the following implementation. 
I need to set all the options values dynamically. I'm allowing users to set their own values.
For instance,   dots: true/false from another javascript page,

How can I go about achieving this?

**Comment by Tebzamops** [comment]
Hi there,

I would also like to pass dynamic values to slick slider options. For instance, for dots: true.

I understand the value for dots option is a boolean where 1 is equal to true and zero false.
See my snippet below for my implementation. It does not seem to work
 
 var autoplay = "{{content.autoplay}}";
        var dots = "{{content.navdots}}";
        var navrrow = "{{content.navarrow}}";
        
      $.getScript("https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.4.0/slick.min.js", function() {
       $(document).ready(function(){
            $('.slides').slick({
             
               autoplay:autoplay,
               autoplaySpeed:4000,
               //speed:getSlideFrequencyValue,
               slidesToShow:1,
               slidesToScroll:1,
               infinite:true,
               adaptiveHeight: true,
               arrows:navrrow,
               prevArrow: '<span class="nav-arrow-prev fa fa-chevron-left  fa-2x" aria-hidden="true"></span>',
               nextArrow: '<span class="nav-arrow-next fa fa-chevron-right fa-2x" aria-hidden="true"></span>',
               dots:dots,
               speed:5000,
               mobileFirst:true,
              
          })
          
        });
    });
See how I pass dynamic values from mustache js based project I'm currently working on.

Let me know what I'm doing wrong implementation.

Regards,
Tebz

**Comment by smartlightning** [comment]
Is there an official way of using dynamic values in your code for the slides to scroll value? Interested to see what the solution for @Tebzamops  issue is (as I'm facing a similar one)
