### ISSUE TITLE
Android Chrome browser slight pause when swiping to next slide

### ISSUE THREAD

**Issue by tplusrex** [kenwheeler/slick#2170]
I wanted to know if anyone is experiencing swiping issues in Android Chrome. There's a slight delay after you lift up your finger after swiping. Works smooth in iOS Chrome or Safari browser. 

I've narrowed down the problem to what could be a css hardware acceleration issue with translate3d. There's a hard switch when the value changes in Android Chrome. Where iOS Chrome will increase/decrease the value one by one until it gets to the next slide. Providing a better experience.

This is an example of how the value changes after you lift up your finger from swiping.
Android Chrome
transform: translate3d(1800, 0, 0) -> translate3d(2200, 0, 0)

iOS Chrome
transform: translate3d(1800, 0, 0) -> translate3d(1801, 0, 0) -> translate3d(1802, 0, 0)...translate3d(2200, 0, 0)

I'm hoping someone can kind of lead me in the right direction as I've hit a wall trying to debug this thing.

**Comment by leggomuhgreggo** [comment]
Hey @tplusrex I used the [live view on a test codepen](http://codepen.io/leggomuhgreggo/live/EKaWBV) here and it seems pretty responsive on my android chrome. Didn't notice any delays, but I suppose its possible iphone behaves differently. I'm gonna close for now, but if the problem is persisting for you on that test case Ill dig up an iphone to test on, and can look at reopening. Thanks!

**Comment by mbritton** [comment]
I am also experiencing a major swipe slowdown on web pages inside a native Android application.

**Comment by kenwheeler** [comment]
@mbritton which application? what android version?

**Comment by mbritton** [comment]
The application is custom, made with Phonegap. The Android version is 4.9 ++, but could be greater.

**Comment by leggomuhgreggo** [comment]
What version of slick are you using? 1.5.9 uses left values to slide by default, but if you set `useTransform: true` it will swap to using transforms. In the current master useTransform is true by default.

**Comment by mbritton** [comment]
Slick version 1.5.8.

**Comment by leggomuhgreggo** [comment]
Ah in that case I think it's `transformsEnabled: true`. Here's the relevant code block from that version:

```
    Slick.prototype.setCSS = function(position) {

        var _ = this,
            positionProps = {},
            x, y;

        if (_.options.rtl === true) {
            position = -position;
        }
        x = _.positionProp == 'left' ? Math.ceil(position) + 'px' : '0px';
        y = _.positionProp == 'top' ? Math.ceil(position) + 'px' : '0px';

        positionProps[_.positionProp] = position;

        if (_.transformsEnabled === false) {
            _.$slideTrack.css(positionProps);
        } else {
            positionProps = {};
            if (_.cssTransitions === false) {
                positionProps[_.animType] = 'translate(' + x + ', ' + y + ')';
                _.$slideTrack.css(positionProps);
            } else {
                positionProps[_.animType] = 'translate3d(' + x + ', ' + y + ', 0px)';
                _.$slideTrack.css(positionProps);
            }
        }

    };
```

**Comment by mbritton** [comment]
This does seem to have improved performance. I'll post back soon and confirm.
