### ISSUE TITLE
Before next slide event

### ISSUE THREAD

**Issue by Timbioz** [kenwheeler/slick#2171]
Can i attach custom animation to slide current item before next slide is fired?
In other words, i need attach goOut animation to active slide.
How can i do this?
Thanks!

Example: like in this slideshow -- [link](http://htmlstream.com/preview/unify-v1.9.1/)

**Comment by v3nt** [comment]
`.on('beforeChange',function(){
jQuery(".slick-current").addClass('YOURCLASS');
    })`
