### ISSUE TITLE
Disabled "next" button still cycles slides, even though end is reached

### ISSUE THREAD

**Issue by jonscottclark** [kenwheeler/slick#2172]
When `slidesToShow` is greater than `1`, and `infinite` is `false`, clicking on the Next arrow continues to set the `slick-current` class on each successive slide, even if the Next arrow has class `slick-disabled`

====================================================================

###### http://jsfiddle.net/jonscottclark/etqegmxa/1/

====================================================================

#### Steps to reproduce the problem

1. Set `slidesToShow` to a value greater than `1`
2. Set `infinite` to `false`
3. Open up your debugger and inspect the `.slick-track` element, so that you can see each slide.
4. Click the Next arrow and notice how the `.slick-active` class gets placed on the left-most slide.
5. When the last slide is in the right position, and the Next arrow is `.slick-disabled`, click it again, and notice how the `.slick-current` class gets applied to each slide, until the last slide is reached.
6. Now, click the Previous button. Notice that the slides do not move, but the `.slick-current` class traverses backwards through the `.slick-slide` elements.

====================================================================

#### What is the expected behaviour?

When the Next arrow is disabled, no click behaviour should be executed.

====================================================================

#### What is observed behaviour?

See steps above.

The negative side effect of this is that you need to click the "Previous" button multiple times (depending on how many times you click the `.slick-disabled` Next button) before the slider moves backwards again, because slick has moved the `.slick-current` further ahead than it needs to be.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
  - latest Chrome
- Which jQuery/Slick version are you using?
  - Forked jsfiddle version
- Did this work before?
  - I initially noticed this issue on my fork of slick that was untouched since early January 2016, so the issue has likely existed since then.

**Comment by leggomuhgreggo** [comment]
Hey @jonscottclark the `slick-disabled` class is just for styling--it doesn't programmatically prevent sliding. To do that you have to hack the JS a bit. I have [an example](http://codepen.io/leggomuhgreggo/pen/gbVPpX) that I made a while back. No promises on it being compatible with the latest release though. There's an interesting discussion about this matter on #1138  Hope that helps!

**Comment by jonscottclark** [comment]
Hey @leggomuhgreggo,

Thanks for getting back so fast, and for your proposed solution.

However, I still think this is a bug, because it doesn't satisfy the expected behaviour of this plugin.

In my fiddle, http://jsfiddle.net/jonscottclark/etqegmxa/1/, click Next until the slides showing are **Slide 5** and **Slide 6**.

Then click the **Next** arrow again. (Expected behaviour is that slick should not do anything under the hood. The user doesn't see any behaviour).

Now click the **Previous** arrow. (Expected behaviour is that the slider should move the slides backwards on the first click). The slides do not scroll backwards on the first click. This is where I believe this is a legitimate bug.

This problem gets worse if you set `slidesToShow` to a higher value, like 4 or 5. You can then potentially click the disabled **Next** button many times, and it would take 3 or 4 clicks, respectively, on the **Previous** button before it actually shifted the slides backwards again.

The same mechanism that's preventing the set of slides from continuing to change their position after all of the slides are visible, and placing the "current" slide in the left-most position, should also ensure that the `.slick-current` class doesn't cycle.

**Comment by leggomuhgreggo** [comment]
Ahh okay my mistake, this is a duplicate of #2146 annnnnd here's the PR for it #2152

**Comment by jonscottclark** [comment]
Great! Sorry for the dupe.
