### ISSUE TITLE
Responsive Fade Transitions

### ISSUE THREAD

**Issue by activestylus** [kenwheeler/slick#2177]
I love the breakpoints in this slider - really nice work for making responsive design easier!

My only quibble is that this feature no longer works when I switch to "fade" transition:

`<div class='slide' data-slick='{"slidesToShow": 4, "fade": true}'>`

The slider loads just fine, the problem is that it now ignores the "slidesToShow" option and simply displays 1 slide, with a ton of space on the right.

**Comment by leggomuhgreggo** [comment]
Hey @activestylus I'm going to close this because there's no reduced test-case, like a jsfiddle, per the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but if you want to make one, we can check it out. Thanks!
