### ISSUE TITLE
slick adding style="display: block;" to .slick-dots

### ISSUE THREAD

**Issue by v3nt** [kenwheeler/slick#2178]
is this default behaviour and can it be prevented? Making it hard to control the navigation via breakpoints.

http://dmfkdev.jynk.net/projects/unit-9-tabard/

`<ul class="slick-dots" style="display: block;">
<li class="slick-active" aria-hidden="false"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">1</button></li><li aria-hidden="true"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">2</button></li><li aria-hidden="true"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">3</button></li><li aria-hidden="true"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">4</button></li><li aria-hidden="true"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">5</button></li><li aria-hidden="true"><button type="button" data-role="none" role="button" aria-required="false" tabindex="0">6</button></li></ul>`

thanks!

**Comment by leggomuhgreggo** [comment]
Hey @v3nt not sure what behavior you're describing. I'm going to close this because it doesn't conform to the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but if you want to clarify, might be able to point you in the right direction. Thanks!

**Comment by v3nt** [comment]
basically slick is adding the style="display: block;" to .slick-dots.

**Comment by leggomuhgreggo** [comment]
The addition of that style, inline, is not default. You can check out the demo, or the base fiddle from the contribution guidelines to confirm that or check on any other questions as to what's default in future.

**Comment by v3nt** [comment]
The whole element is created by slick so is it not coming from that somehow.

Source code.

`<div class="slider-nav"></div>`

slick js option
`... slick({ .. appendDots: '.slider-nav', ...`


outcome.
```
<div class="slider-nav" role="toolbar">
      <ul class="slick-dots" role="tablist" style="display: inline-block;">
<li class="slick-active" aria-hidden="false" role="presentation" aria-selected="true" aria-controls="navigation00" id="slick-slide00">...
```

**Comment by leggomuhgreggo** [comment]
To test, recreate in a reduced test case, like a jsfiddle. Here's one to fork:
http://jsfiddle.net/simeydotme/fmo50w7n/

**Comment by Fahad-droid** [comment]
Was facing the same issue, but inline display: block; on slick-dots wasn't the culprit.

I had ul > li elements as display: block; -- changing it to display: inline-block; worked for me.
