### ISSUE TITLE
Multiple sliders makes a problem with the navigation

### ISSUE THREAD

**Issue by quantafire** [kenwheeler/slick#2179]
I am using the Slick jQuery carousel and I have a problem whenever I use the "appendArrows" option:

```
    $(document).ready(function(){
      $('.post-slider').slick({
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 2,
        slidesToScroll: 1,
        appendArrows: '.button-container',
        centerMode: true
    });
    });
```

You see, I need to output multiple carousels and yet the number of carousels I display is also the number of times the appendArrows function seems to run inside each carousel. 

```
    <div id="slidersort">
    <div class="slider">
        <span class="drag-handle">☰</span>
        <div class="wrap_lined_header"><h2>News</h2><div class="button-container"></div></div>

        <div class="clr"></div>
        <div class="post-slider">
            <?php 
            $args = array('post_type' => 'news');
            $loop = new WP_Query( $args );
             
            while ( $loop->have_posts() ) : $loop->the_post();
            ?>
            <div>
                <a class="post-link" href="<?php the_permalink() ?>"> </a>
                <h2><?php the_title(); ?></h2>
                <div class="post-date"><?php the_date('d/m/Y') ?></div>
                <div class="entry-content">
                    <p><?php the_field('summary'); ?></p>
                </div>
            </div>
            <?php endwhile;?>
            
        </div>
    </div>

    <div class="slider">
        <span class="drag-handle">☰</span>
        <div class="wrap_lined_header"><h2>Weather</h2><div class="button-container"></div></div>

        <div class="clr"></div>
        <div class="post-slider">
            <?php 
            $args = array('post_type' => 'news');
            $loop = new WP_Query( $args );
             
            while ( $loop->have_posts() ) : $loop->the_post();
            ?>
            <div>
                <a class="post-link" href="<?php the_permalink() ?>"> </a>
                <h2><?php the_title(); ?></h2>
                <div class="post-date"><?php the_date('d/m/Y') ?></div>
                <div class="entry-content">
                    <p><?php the_field('summary'); ?></p>
                </div>
            </div>
            <?php endwhile;?>
            
        </div>
    </div>

    <div class="slider">
        <span class="drag-handle">☰</span>
        <div class="wrap_lined_header"><h2>Sports</h2><div class="button-container"></div></div>

        <div class="clr"></div>
        <div class="post-slider">
            <?php 
            $args = array('post_type' => 'news');
            $loop = new WP_Query( $args );
             
            while ( $loop->have_posts() ) : $loop->the_post();
            ?>
            <div>
                <a class="post-link" href="<?php the_permalink() ?>"> </a>
                <h2><?php the_title(); ?></h2>
                <div class="post-date"><?php the_date('d/m/Y') ?></div>
                <div class="entry-content">
                    <p><?php the_field('summary'); ?></p>
                </div>
            </div>
            <?php endwhile;?>
            
        </div>
    </div>
</div>
```

So let's say I have 3 carousels displaying (as above), whenever I display the page, it returns me 3 buttons like this in EACH carousel:

```
    <div class="button-container">
    <button type="button" data-role="none" class="slick-prev slick-arrow" aria-label="Previous" role="button">Previous</button>
    <button type="button" data-role="none" class="slick-prev slick-arrow" aria-label="Previous" role="button">Previous</button>
    <button type="button" data-role="none" class="slick-prev slick-arrow" aria-label="Previous" role="button">Previous</button>
    <button type="button" data-role="none" class="slick-next slick-arrow" aria-label="Next" role="button">Next</button>
    <button type="button" data-role="none" class="slick-next slick-arrow" aria-label="Next" role="button">Next</button>
    <button type="button" data-role="none" class="slick-next slick-arrow" aria-label="Next" role="button">Next</button>
    </div>
```

Any ideas on how I can alter the original jQuery call to play nice with 3 carousels? I was thinking how I could get the appendArrows option to display only the BEGINNING of a class name then I could run a simple PHP loop to add numerical values to each of them, but I'm afraid my jQuery isn't that up to scratch. 

Unless you have a better idea?

**Comment by leggomuhgreggo** [comment]
Hey @quantafire can you recreate in a reduced test case like a jsfiddle or codepen? See the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). Thanks

Closing pending test case

**Comment by ActionScripted** [comment]
@quantafire: I've been working around this issue by using a loop and passing selector context to `appendArrows` and `appendDots`:

```
    $('.slider).each(function() {
      $(this).slick({
        appendArrows: $('.slider__arrows', this),
        appendDots:   $('.slider__dots',   this),
        arrows: true,
        dots:   true
      });
    });
```

It looks like the arrows/dots append calls don't scope things to the current carousel so if you pass a general selector like `appendArrows: '.slider__arrows'` it'll append to all instances of `.slider__arrows` on the page and you'll see what you've reported.

It might make sense to scope selectors to within the parent carousel to make things more intuitive to folks trying to implement and customize the carousel.

**Comment by transbetacism** [comment]
_madalin ivascu_ solution on stackoverflow worked for me:
http://stackoverflow.com/questions/39508533/custom-next-button-for-slick-slider

http://codepen.io/anon/pen/vXGAxb

**Comment by jmelendev** [comment]
Late to the conversation but for anyone else looking for answers, This worked for me:

```
 var index = 0;

  $('.slider').each(function() {
      index++;
      $(this).attr('data-slider', index);

      $(this).slick({
        appendArrows: '.slider[data-slider="+ index +"] .slick-slide',
        appendDots:  '.slider[data-slider="+ index +"] .slick-slide',
        arrows: true,
        dots:   true
      });
    });
```
I had to add the arrows and dots into the slide for this particular design.

**Comment by projer** [comment]
@jmelendev thanks for this solution. You can even simplify it like this:

```
$('.slider').each(function( index ) {
      $(this).attr('data-slider', index);

      $(this).slick({
        appendArrows: '[data-slider="' + index + '"] .slick-slide',
        appendDots:  '[data-slider="' + index + '"] .slick-slide',
        arrows: true,
        dots:   true
      });
    });
```

**Comment by Sisanu** [comment]
Not all the slick configurations are appending the navigation as a child element of the carousel, some  are appending tihs as a sibling of the slides wrapper. In this case, you have to target the element differently.
```
$('.slider').each(function() {
	$(this).slick({
		...
		appendArrows: $(this).siblings('.slick-nav'),
		...
	});
});
```

**Comment by sadig2** [comment]
> @quantafire: I've been working around this issue by using a loop and passing selector context to `appendArrows` and `appendDots`:
> 
> ```
>     $('.slider).each(function() {
>       $(this).slick({
>         appendArrows: $('.slider__arrows', this),
>         appendDots:   $('.slider__dots',   this),
>         arrows: true,
>         dots:   true
>       });
>     });
> ```
> 
> It looks like the arrows/dots append calls don't scope things to the current carousel so if you pass a general selector like `appendArrows: '.slider__arrows'` it'll append to all instances of `.slider__arrows` on the page and you'll see what you've reported.
> 
> It might make sense to scope selectors to within the parent carousel to make things more intuitive to folks trying to implement and customize the carousel.

Thank you so much man

**Comment by CrazyNoodl** [comment]
> @quantafire: I've been working around this issue by using a loop and passing selector context to `appendArrows` and `appendDots`:
> 
> ```
>     $('.slider).each(function() {
>       $(this).slick({
>         appendArrows: $('.slider__arrows', this),
>         appendDots:   $('.slider__dots',   this),
>         arrows: true,
>         dots:   true
>       });
>     });
> ```
> 
> It looks like the arrows/dots append calls don't scope things to the current carousel so if you pass a general selector like `appendArrows: '.slider__arrows'` it'll append to all instances of `.slider__arrows` on the page and you'll see what you've reported.
> 
> It might make sense to scope selectors to within the parent carousel to make things more intuitive to folks trying to implement and customize the carousel.

Forgot ' in this line  $('.slider)

**Comment by devzom** [comment]
I've also used this pattern:

```
$(function () {
    $('.slider-for').each(function(num, elem) {
        elem = $(elem);
        elem.slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: false,
            draggable: false,
            fade: true,
            asNavFor: '.slider-nav'
        });

        elem.next('.slider-nav-thumbnails').slick({
            slidesToShow: 3,
            slidesToScroll: 1,
            asNavFor: '.slider-for',
            dots: false,
            arrows: false,
            vertical: true,
            draggable: false,
            centerMode: false,
            focusOnSelect: true,
            responsive: [
                {
                    breakpoint: 769,
                    settings: {
                        vertical: false
                    }
                }
            ]
        });
    });
});
```

**Comment by JoshuaHavilandCurtis** [comment]
`$('.col-slider').each(function () {
    $(this).slick({
      dots: true,
      appendDots: $(this).siblings('.two-col--dots').find('.two-col--dots-append'),
      infinite: false,
    });
  });`

**Comment by emont88** [comment]
I seem to be missing something here. I have switched to calling everything via IDs and even that is not working with multiple sliders. I am still getting both sets of dots in both sliders (so in this example, I'm seeing 6 dots in each slider--3 from each slider). I also tried using some of the above methods using an "each" function so that I could use $(this).siblings() to try to target the slider nav divs more specifically but that didn't make a difference. Here is my markup and code:

`<div id="my-first-slider">                    
  <div class="slide">...</div>
  <div class="slide">...</div>
  <div class="slide">...</div>
</div>
<div id="my-first-slider-nav"></div>


<div id="my-second-slider">                    
  <div class="slide">...</div>
  <div class="slide">...</div>
  <div class="slide">...</div>
</div>
<div id="my-second-slider-nav"></div>`

`$('#my-first-slider').slick({
  slidesToShow: 1,
  infinite: true,
  dots: true,
  appendArrows: $('#my-first-slider-nav'),
  appendDots: $('#my-first-slider-nav')
});

$('#my-second-slider').slick({
  slidesToShow: 2,
  infinite: true,
  dots: true,
  appendArrows: $('#my-second-slider-nav'),
  appendDots: $('#my-second-slider-nav')
});`
