### ISSUE TITLE
Responsive not smooth

### ISSUE THREAD

**Issue by llos** [kenwheeler/slick#2185]
Hi,

We've seen that slick JS fluid behavior is not smooth. When you scale the window the images make small jumps instead soft fluid scale. This doesn't happen in normal images or other slider plugins. For example, you can compare Flexslider with Slick here:
https://dl.dropboxusercontent.com/u/11189866/slick.mov
https://dl.dropboxusercontent.com/u/11189866/flex.mov

Do you know how can we improve this? I guess this is related to performance.

Thanks

**Comment by tomaszpoliszuk** [comment]
Please include jsfiddle examples for tests.

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
