### ISSUE TITLE
Anyway to have two speeds, one for touchend?

### ISSUE THREAD

**Issue by benbyford** [kenwheeler/slick#2186]
Anyway to have two speeds, one for touchend?

====================================================================

#### What is the expected behaviour?

slow transition speed globally (i.e. intended for desktop), but a fast trainsition speed if touchend is used so it is easy to swipe through lots of images without the traistion taking ages each time.

====================================================================

#### What is observed behaviour?

no easy way to implement this currently I've found and couldnt work out how to hijack the speed default on touch end

**Comment by benbyford** [comment]
any progress on this? could you direct me to the touch support functions and I can have a go at a changing the current speed relative to the amount of touch move incurred? (i.e. if the image has been dragged a num of pixels use the total num of pixels left to next slide to make a percentage of total speed left required to make move)

**Comment by simeydotme** [comment]
@benbyford sorry, this amounts to acceleration/physics and that's just simply not going to be achievable in this version of Slick :( .. we are planning to allow it in v2.
