### ISSUE TITLE
customWidth option

### ISSUE THREAD

**Issue by megaslug** [kenwheeler/slick#2190]
Original issue: https://github.com/kenwheeler/slick/issues/2149

Problem: http://jsfiddle.net/238598/drdydokx/1/
Solution: http://jsfiddle.net/drdydokx/2/

However, if I want my slider to be responsive, ie without fixed width (remove `width: 400px` in the second example), then slick calculates it for me on the fly.

What I would like is to have specific slide width across breakpoints. The cleanest way to implement that is to set your width in CSS with `!important` flag. For example: `width: 235px !important`.

In this instance, slideWidth and sliderWidth (see line 1935 in slick.js) values get calculated incorrectly.

What I propose is `customWidth` option:

1. Add `customWidth: false` to your `_.defaults`
2. Find `Slick.prototype.setDimensions` and replace

`if (_.options.vertical === false && _.options.variableWidth === false)`

with

`if (_.options.vertical === false && _.options.variableWidth === false && _.options.customWidth === false)`

3. Then add this below:

```
else if (_.options.customWidth === true) {
_.slideWidth = _.$slideTrack.children('.slick-slide').outerWidth(true);
_.$slideTrack.width(Math.ceil((_.slideWidth * _.$slideTrack.children('.slick-slide').length)));
}
```

What this does is it checks for the actual `.slide-slide` width, including margins. Then it uses that value to set the actual slideTrack width.

What are you ideas about this?

**Comment by leggomuhgreggo** [comment]
Interesting. If it were me I'd set the width of the slider (desired-slide-width * slidesToShow) at breakpoints using either media queries or via the slick breakpoint event.

**Comment by megaslug** [comment]
Well, I need the slider to always be 100% of the container. With every window resize event it recalculates both the slides and the container, unless the container has a fixed width.

**Comment by leggomuhgreggo** [comment]
Hmm, I'm not sure I'm fully understanding the goal here

>I need the slider to always be 100% of the container. With every window resize event it recalculates both the slides and the container, unless the container has a fixed width.

The slider does this already. It defaults to be 100% of the container, with the slide width being calculated as a percentage ( 100% / slidesToShow ). 

So right now its a function of the slider width, which is 100% unless specified with a fixed width. If you want the slides to be fixed width, I see two options:
1. set a fixed width on the slider (modified on breakpoints for responsivity) that equals the desired fixed slide width * slidesToShow. You could wrap the slider in another div so that's 100% of a container, if that was something you needed.
2. You could have a nested div within each slide, so that the slide width is the default percentage, but there's a fixed width set for the nested div.

Apologies, if I'm missing something.

**Comment by simeydotme** [comment]
sounds bonkers, there's "features"  ...
and then there's "asking someone else to write your client's weird request in to a publicly open source library".

**Comment by megaslug** [comment]
@leggomuhgreggo that's right, the slider calculates the width of each slide already. However, if your design is specific about dimensions of the slides across different breakpoints and your parent container has to stay fluid, then you need additional flexibility.

Your suggested idea sounds good in theory, but a fixed container within a fluid container will not solve the problem. That would introduce an issue where an item on the edge of container might become hidden at certain widths. Also, how would you then change the number of items scrolled per click. You could obviously create additional number of breakpoints, but that's not a great approach in my view.

The second approach would create overlapping content at specific viewport widths. It would be almost impossible to keep things nicely padded and for the slides to scroll without some visual regressions.

@simeydotme I don't think it's bonkers. What I'm suggesting is to allow user some additional flexibility. Perhaps such things could be approached by making the library modular, so that the core is very basic and the rest could be added with extensions, some of which could be custom. That would prevent the library from getting bloated with every possible feature and would also give a more advanced user the sort of flexibility they would expect.

**Comment by leggomuhgreggo** [comment]
@megaslug I'm confused on how your proposal differs. Wanna discuss on the Slick gitter?

https://gitter.im/kenwheeler/slick
