### ISSUE TITLE
"asNavFor" with UL/LI seems to not fully work

### ISSUE THREAD

**Issue by jomofcw** [kenwheeler/slick#2192]
Hello,

When using the "asNavFor" in a double UL/LI structure, it works when I click on the "navigation", but not when I drag the "container", "slick-current" doesn't change for the "navigation" in that case.

====================================================================

https://jsfiddle.net/h34o7zb7/

====================================================================

Click the "carrousel-navigation" elements, see that it work.
Drag the "carrousel-conteneur" elements, see it doesn't work.

====================================================================

In the demo, it work for both navigation and container.

====================================================================

#### More Details

- seems to happen in any browser, tester on chrome and firefox.
- latest stable jQuery (1.x) and Slick version
- can't get it work since start.

**Comment by leggomuhgreggo** [comment]
Hey, @jomofcw, the issue is that `carrousel-navigation` isn't getting slicked because slidesToShow = slideCount. 

I recommend using the `customPaging` option to generate the `carrousel-navigation` items as nav elements.

Hope that helps!
