### ISSUE TITLE
Slick slide width wrong when slider inside <fieldset> | Firefox

### ISSUE THREAD

**Issue by klierik** [kenwheeler/slick#2194]
Good day

Just found a problem: Firefox + Fieldset > slick slider

Example: https://jsfiddle.net/klierik/gnfe0oqd/1/
Desc: Slick count wrong slide width: http://take.ms/olGg6

Firefox: OSX Latest
Slick slider: latest

**Comment by leggomuhgreggo** [comment]
So `fieldset` is one of [the quirkiest HTML elements](http://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content/17863685#17863685). I don't trust it and I wouldn't recommend it, but if its important to use for some reason, I think you can get away with it through some resets. `min-height: 0` and `display: table-cell` [worked for me](http://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content/17863685#17863685). Hope that helps!

**Comment by simeydotme** [comment]
haha, yeh @leggomuhgreggo ... if he checked every JS plugin with fieldsets he'd be spending a long time on github raising issues ;)
