### ISSUE TITLE
Click the button, style does not disappear

### ISSUE THREAD

**Issue by chang0022** [kenwheeler/slick#2195]
我的英语不好，我的问题是：
1. 使用 autoplay: true,
2. 点击按钮，图片切换
3. 等待自动切换
4. 图片自动切换，上个按钮样式不消失
5. 一直保持不消失，直到我点击浏览器的任何部位
My English is not good, my issue is:
1. Use autoplay: true,
2. Click the button to switch the image
3. Wait for the autoplay
4. The image is automatically switched , but the previous button style does not disappear
5. The style not disappear until I click on any part of the browser

**Comment by leggomuhgreggo** [comment]
Hey @chang0022 please provide a test case in a fiddle or something per the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). Thanks!
