### ISSUE TITLE
Elements disappear during drag when absolute positioned to bottom of the page

### ISSUE THREAD

**Issue by rlloyd2001** [kenwheeler/slick#2198]
> short description of the bug / issue, provide more detail below.

====================================================================
I'd like to have a slider in a footer floating at the bottom of a container. Looks like it works, but when I slide back and forth elements disappear. 

###### `[ http://jsfiddle.net/rlloyd2001/0yt38r1t/1/,   https://jsfiddle.net/rlloyd2001/szkkgsj7/  ]`  

====================================================================

#### Steps to reproduce the problem

1. ...  http://jsfiddle.net/rlloyd2001/0yt38r1t/1/    Press run in JSFiddle
2. ...   https://jsfiddle.net/rlloyd2001/szkkgsj7/  Press run and slide back and forth items

====================================================================

#### What is the expected behaviour?

...  Items shouldn't disappear or display stretched.

====================================================================

#### What is observed behaviour?

...  Items disappear on drag and display wrong.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Google Chrome
- Which jQuery/Slick version are you using?
Latest on Master branch
- Did this work before?
First time I've used Slick so I don't know. I'm needing a slider that floats on the bottom of a container.

**Comment by leggomuhgreggo** [comment]
Hey @rlloyd2001 this looks like a CSS issue with absolute positioning. Gotta give it a defined width or else the recalc will go funny. Here's your fiddle with `width: 100%` applied to the `cont` div. Corrects the issue.

You might consider wrapping the slider div in a parent container whose role is to position it absolutely, and leave the slider as `position: relative;`

https://jsfiddle.net/hLsuxnv4/

**Comment by rlloyd2001** [comment]
@leggomuhgreggo  Maybe I'm missing something, but that didn't correct the issue when I pulled up JSFiddle in Chrome.

**Comment by rlloyd2001** [comment]
![snap 2016-03-15 at 21 23 18](https://cloud.githubusercontent.com/assets/4015110/13801070/2fa78f78-eaf4-11e5-8b7d-8ad83e5aa545.png)

**Comment by rlloyd2001** [comment]
Keeping the slider div relative and placing it inside a div moved using position: absolute also doesn't work. https://jsfiddle.net/zrom9p1r/3/

**Comment by rlloyd2001** [comment]
I was finally able to get it work by hard coding the width of the slider element. I still think this is a bug, but at least I have a work around.

**Comment by leggomuhgreggo** [comment]
https://jsfiddle.net/4mp848m1/1/

**Comment by leggomuhgreggo** [comment]
also this http://codepen.io/leggomuhgreggo/pen/mPOgqq
