### ISSUE TITLE
IE10 size of divs in carousel 1px

### ISSUE THREAD

**Issue by fraserjordan** [kenwheeler/slick#2201]
Have a standard slick carousel, nothing special, with some div's inside it which each have a background image and a standard size. Every other browser except IE10 will show the content fine, so seems to be IE10 specific.

**Comment by leggomuhgreggo** [comment]
Hey @fraserjordan please provide a test case, in a fildde or codepen or something, per the [conribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)

Im going to close pending the test case. Thanks!
