### ISSUE TITLE
Arrows missing in Mac and Chrome

### ISSUE THREAD

**Issue by Smart9110** [kenwheeler/slick#2207]
> short description of the bug / issue, provide more detail below.
The arrows to the carousel is missing in Mac and Chrome browser
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

		.slick-prev:before, 
		.slick-next:before{
   	 color: black;
   	 position: absolute;    
	}

$(document).ready(function(){     		
		$('.slider').slick({
   			 autoplay: true,
    		dots: true,
    		arrows: true,
        	responsive: [{ 
        	breakpoint: 500,
        	settings: {
            dots: true,
            arrows: true,
            infinite: true,
            slidesToShow: 1,
            slidesToScroll: 1,
            
        	}
    	}]
    });
});

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

These arrows should be present all the time.

...  

====================================================================

#### What is observed behaviour?

This is a distortion and the arrow are not present. But in other browsers, the arrows are present.

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

This only happen in Mac and Chrome.

The problem does not happen in FireFox or Explorer

**Comment by leggomuhgreggo** [comment]
Hey @Smart9110 the arrows *are* there in the fiddle, although they are set to turn off at a small window size based on the slider options.

I see there's a difference between the fiddle and the options you pasted, so I pasted them in and they're still there.

The arrows are positioned absolutely outside the slider so if you have overflow hidden, or if the slider is full width to a container that has overflow hidden, then you might now see them. Also could be a styling issue. I'd spend some time looking in the inspector just so you have a clearer picture.

Check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), and, in future, I suggest spending a little more time debugging yourself before registering an issue.
