### ISSUE TITLE
Unslick doesn't work correctly when resizing from breakpoint

### ISSUE THREAD

**Issue by k-lusine** [kenwheeler/slick#2209]
> short description of the bug / issue, provide more detail below.
Unslick doesn't work correctly when resizing from breakpoint. It works ok, if I resize from general settings area.
====================================================================

###### `[  http://jsfiddle.net/fmo50w7n/281/  ]`  
Link for preview [http://fiddle.jshell.net/fmo50w7n/281/show/]
====================================================================

#### Steps to reproduce the problem

1. Resize smoothly and you'll see that on greater than 992 slider is destroyed, 480-992 - 2slides, below 480 -1 slide
2. Problem appears if you resize slider not smoothly. 
a. Suppose your window is 483 and you resize it and it becomes 1200, everything is ok, slider is destroyed
b. Suppose your window is 478 and you resize it and it becomes 1200, slider isn't destroyed. The conditions work, console.log(works). Generally the unslick runs too, but it restarts slider again. I notice it in my website, but as code is simple here, it happens very quickly and you can't notice it

====================================================================

#### What is the expected behaviour?
Slider should be destroyed
====================================================================

#### What is observed behaviour?
Slider is destroyed but it reinits for unknown reason

====================================================================

#### More Details

- Which browsers/versions does it happen on? Not a browser compatibility issue, but I test it on Firefox
- Which jQuery/Slick version are you using? The one in the fiddle you provide
- Did this work before? I haven't tried

**Comment by leggomuhgreggo** [comment]
Hey @k-lusine this is a duplicate issue, but thanks for making it :smile:

**Comment by stratboy** [comment]
Then you should point to the original one.

**Comment by leggomuhgreggo** [comment]
Sounds like we're both busy people who don't want to search for things.
