### ISSUE TITLE
How to check was slide triggered automatically?

### ISSUE THREAD

**Issue by JILeXanDR1** [kenwheeler/slick#2212]
I'm using `afterChange `event for make some login in my application... Is there property like `isTriggeredAutomatically`?
For example:

```
            $('.slider').on('afterChange', function(event, slick, currentSlide) {
                if (slick.isTriggeredAutomatically) {
                    // if slider was run by timer, we don't do anything
                } else {
                    // do something
                }
            });
```

**Comment by leggomuhgreggo** [comment]
Hmm not without some serious hacking I don't think. It's an interesting idea.

Closing: support request

**Comment by JILeXanDR1** [comment]
@leggomuhgreggo 
I've added pull request https://github.com/kenwheeler/slick/pull/2327 to support this

**Comment by leggomuhgreggo** [comment]
@JILeXanDR1 cool, I'll check it out now
