### ISSUE TITLE
Slide Links Accessibility Issue

### ISSUE THREAD

**Issue by seantk421** [kenwheeler/slick#2213]
Hi,

I am having difficulty with accessibility on links in slick slides. When I use voiceover and tab to a link with role='button' it is reading back the full text of the slide, instead of the button text and button. Has anyone faced this issue before. I have tried toggeling the accessibility option of the slider to true/false, but have the same results.

Thanks!

**Comment by leggomuhgreggo** [comment]
Hey @seantk421 thanks for the report. I think this is similar as #2139. I spent part of an evening starting to dig into it but haven't circled back on it. My guess is that it might be related to tabindex, but I can't claim to be an expert on the matter. Any input you have would be welcome! Thanks.

Closing: duplicate
