### ISSUE TITLE
Add randomization function as here

### ISSUE THREAD

**Issue by Air-Sidney** [kenwheeler/slick#2215]
Add randomization function as here
http://stackoverflow.com/questions/31459832/randomise-and-order-divs-slick-js

**Comment by leggomuhgreggo** [comment]
Hmm, my feeling is that feature is neat, but might not be important enough to put into the core, especially since its relatively easy to to extend with the init method there. Thanks!

**Comment by Florencia007** [comment]
how do I implement this? what code and where do I place it? sorry, I'm not a developer. thanks for any help.
