### ISSUE TITLE
Dragging bounces back to current slide on autoplay

### ISSUE THREAD

**Issue by messinmotion** [kenwheeler/slick#2219]
>So if the user drags the current slide (ie 4 steps away ) when the dragging action is done, the slider bounces back to the intial (if no autoplay) or current (if autoplay) slide instead of staying when left.

====================================================================

###### `[ http://jsfiddle.net/fmo50w7n/287/  ]`  

====================================================================

#### Steps to reproduce the problem

1. Drag the slider
2. See how it just bounces back 

====================================================================

#### What is the expected behaviour?

...  As in 'multiple items' example on the slick homepage.

====================================================================

#### What is observed behaviour?

...  As described on the main issue.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
All
- Which jQuery/Slick version are you using?
jQ : 1.11.2
Slick : 1.5.9
- Did this work before?
It does on the homepage

**Comment by devinargenta** [comment]
Hey, wondering if you're looking for the option `swipeToSlide`?

**Comment by messinmotion** [comment]
No, im just looking for it to be exactly as the multiple items example on the slick homepage. See this fiddle (Sorry i didnt update the fiddle).

http://jsfiddle.net/fmo50w7n/287/

See how the slides bounce right back when swiping/dragging

**Comment by devinargenta** [comment]
I think this is because you have the slides set to scroll one at a time, compared to the demo which has it set to `slidesToScroll: 3`. not sure if this a bug or not, however swipeToSlide will scroll to whichever slide you selected.

**Comment by leggomuhgreggo** [comment]
Thanks @devinargenta!
