### ISSUE TITLE
Fullwidth slider

### ISSUE THREAD

**Issue by Redani** [kenwheeler/slick#2220]
Hi and thanks a lot for this lovely plugin :)

I didn't see in demo an example for a fullwidth slider. how can this be achieved?

Also in center mode, is it possibile to initially show only a part of next slide, and once we click on next, than we can also see a prt of the previous slide ?

Thanks
Regards

**Comment by balintd** [comment]
Make sure the div that is wrapping your slides is full width, the entire slider should be full width too.

For the second question I think you need `centerPadding` option which controls how much you can see of the next/previous slides. For an example check out Center Mode section in the documentation.

**Comment by leggomuhgreggo** [comment]
Thanks @balintd

**Comment by Redani** [comment]
Thanks balintd for your reply. I'll try soon the full width recommendations you gave me.

regarding the second question, maybe i didn't explain well what i need :)
when the page is loaded, i'll like to : 
1- see only the main slide number "1" in center + part of the next slide number "2" in the right
2- if i click on "next" button, then slide "2" moves to center and we see part of slide "1" in the left and part of slide "3" in the right

Hope you understand me better now.

Regards

**Comment by Redani** [comment]
UPDATE: I have just installed and tried slick and I have the following questions:
3- when the page loads, it shows all the slides and then only the first, is it possible to show a loader until the slides are fully loaded?
4- is it possible to use a css class instead of the ajax loader img?

thanks
