### ISSUE TITLE
Cannot read property 'add' of null

### ISSUE THREAD

**Issue by WebTerminator** [kenwheeler/slick#2221]
I have managed to disable/destroy the carousel under the conditions that I need and it works perfectly. However I still see the following in the console:

Uncaught TypeError: Cannot read property 'add' of null

What is causing that and how can I remove it?

Current URL: http://www.alessandrosantese.com/aldemair-productions/

**Comment by leggomuhgreggo** [comment]
Hey @WebTerminator search the repo for "unslick"

**Comment by naveenrk** [comment]
Check This , Call multiple times it will not break http://jsfiddle.net/fmo50w7n/372/

**Comment by sodbileg** [comment]
@naveenrk Thanks so much!

**Comment by jgraffin** [comment]
Thanks, man!

**Comment by MalindaWMD** [comment]
Another approach to make this work is use `unslick`

**Comment by IsaacHub** [comment]
> Check This , Call multiple times it will not break http://jsfiddle.net/fmo50w7n/372/

This is not working because it uses `jQuery edge`  
Change it to `jQuery 3.3.1` to make it work.

**Comment by ArmCM** [comment]
https://stackoverflow.com/questions/35884752/error-in-slick-js-uncaught-typeerror-cannot-read-property-add-of-null
