### ISSUE TITLE
CSS hickup on cloned element

### ISSUE THREAD

**Issue by vk011** [kenwheeler/slick#2222]
> transform:scale on all divs except current hickup when cloned element comes to focus

====================================================================

###### `[  paste your jsfiddle link here  ]`  

http://jsfiddle.net/fmv3huvo/

====================================================================

#### Steps to reproduce the problem

You can see it on fidde, the css line that makes all slides except the current one smaller is on line 9

====================================================================

#### What is the expected behaviour?

It should increase in size smoothly like all other slides, NOT abruptly.

====================================================================

#### What is observed behaviour?

The cloned element abruptly increases in size when it comes to focus.

====================================================================

#### More Details

- Chrome
- 1.5.9 
- First time I am trying this slider.

**Comment by simeydotme** [comment]
thanks , @vk011 for a decent issue report and a good fiddle :+1: :)
it seems like a decent compromise for this would be to try and set a "slick-cloned-current" class for cloned slides...

Until that's looked at, you might be able to use `onBeforeChange` event to compare the slides and set the correct clone to have the class you need :)

**Comment by vk011** [comment]
The css fix doesn't help, the cloned element gets proper styling even now, I think the problem is that the cloned element gets assigned the class of `slick-current` later than the other elements.

**Comment by leggomuhgreggo** [comment]
Hey @vk011 I think the class thing @simeydotme was talking about was in reference to a future enhancement to the master :smile:

Little while ago I hacked something together using the `beforeChange` event to deal with this issue. [Here's the codepen](http://codepen.io/leggomuhgreggo/pen/vGLzgP?editors=0010). Hope that helps!

**Comment by vk011** [comment]
@leggomuhgreggo Hello,

I added your function and then called `init` and `beforeChange` like so:
```
$('.first-gallery').on('init', function(event, slick) {slickTemplateFunc(slick);});
    $('.first-gallery').on('beforeChange', function(event, slick, currentSlide, nextSlide) {
        slickTemplateFunc(slick, nextSlide);
    });
```

However there is no difference, still acting the same.

**Comment by leggomuhgreggo** [comment]
@vk011 Hmm, well without seeing the case its hard to say where the inconsistency is. I should have mentioned that I decided to use a custom attribute on my slides. Make sure your defining the function too. Good luck!

**Comment by vk011** [comment]
@leggomuhgreggo Hello, I tried it with custom data attributes but still to no avail.

In case you're bothered you can check out the fiddle here http://jsfiddle.net/fmv3huvo/9/ , thanks regardless for trying to help.

**Comment by leggomuhgreggo** [comment]
Oh man, I gave you a way more complicated solution than you needed.

So the issue is slick clones and attribute identifies (classes). It's true that `slick-current` doesn't get applied to a clone before it appears, casuing that jump, but `slick-center` does get applied to the clone properly. If all you need is to consider the state of center vs not center then you can just change the selector and it should work. [Here's a fork of your fiddle](http://jsfiddle.net/tbdffr19/)

My solution was about position relative to the center and cloned slides, which was overkill in this case, but the thing that needed to change was the css selection in that instance too.

**Comment by vk011** [comment]
@leggomuhgreggo Wow man you're a genius, thank you so much!

**Comment by leggomuhgreggo** [comment]
Happy to help!
