### ISSUE TITLE
Problem in big display

### ISSUE THREAD

**Issue by javimata** [kenwheeler/slick#2223]
Hi, i use the 1.5.9 version in the site http://www.grupotrendy.com

but i have a problem, when i display the slider in a big monitor, more that 1024 the items are float to the right, for example in http://www.grupotrendy.com/vintage/producto/425/mesa-classic-rectangular

if resize the monitor to 1024 or - work fine :-S

		$('.carousel_products').slick({
		  dots: false,
		  infinite: false,
		  speed: 600,
		  slidesToShow: 5,
		  adaptiveHeight:false,
		  variableWidth: false,
		  slidesToScroll: 3,
		  arrows: true,
		  nextArrow: '<a href="javascript:void(0);" class="slickArrow slickNext"><i class="fa fa-angle-right"></i></a>',
		  prevArrow: '<a href="javascript:void(0);" class="slickArrow slickPrev"><i class="fa fa-angle-left"></i></a>',
		  responsive: [
		    {
		      breakpoint: 1024,
		      settings: {
		        slidesToShow: 4,
		        slidesToScroll: 1,
		        infinite: true
		      }
		    },
		    {
		      breakpoint: 600,
		      settings: {
		        slidesToShow: 3,
		        slidesToScroll: 1,
		        arrows:false
		      }
		    },
		    {
		      breakpoint: 480,
		      settings: {
		        slidesToShow: 2,
		        slidesToScroll: 1,
		        arrows:false
		      }
		    }
		    // You can unslick at a given breakpoint now by adding:
		    // settings: "unslick"
		    // instead of a settings object
		  ]
		});

**Comment by leggomuhgreggo** [comment]
@javimata hey can you recreate in a reduced test case like a jsfiddle? 

Closing pending fiddle
