### ISSUE TITLE
Infinite is still working even if 'infinite' is set to 'false'

### ISSUE THREAD

**Issue by elliottmangham** [kenwheeler/slick#2225]
Hello,

I'm having a similar issue to the issue #718. I need to disable infinite scroll for the carousel as I need the carousel to stop when you get to the end.

I set 'infinite' to 'false' within the slick.js file.

Thanks!
Elliott

**Comment by leggomuhgreggo** [comment]
Hey can you recreate in a fiddle?

Closing: no fiddle

**Comment by saurabhnanda** [comment]
FWIW, I'm on an old version of slick (1.5.9) and facing the same issue.
