### ISSUE TITLE
Event for multiple carousels on a page

### ISSUE THREAD

**Issue by mvinodpatil** [kenwheeler/slick#2232]
Hi there,
Hope you are doing good!

We have multiple carousels on a page with same class (We cannot have separate class for every carousel for some purpose). 

When we call event, it applies to all the carousels, how to overcome this issue? 

Thanks for your time!
Vinod Patil

**Comment by simeydotme** [comment]
```
var n = 0;
$(".slider").eq( n ).trigger("beforeChange");
```
Where "n" = slider number you want to affect.

**Comment by simeydotme** [comment]
https://api.jquery.com/eq/

**Comment by mvinodpatil** [comment]
-1

**Comment by mvinodpatil** [comment]
:-1:

**Comment by mvinodpatil** [comment]
Since we have many carousel this solution doesn't work for me. 
When I click on particular slider only that slider should have event called, is what I am looking for. 
https://jsfiddle.net/v815x7j2/2/
In the example we want to add active-image class to carousel which selected.

**Comment by mvinodpatil** [comment]
Solved it.    

$('slider').on('afterChange', function(event, slick, currentSlide) {
    $(this).addClass("active-slider");
});

**Comment by mvinodpatil** [comment]
Solved it.

```
$('slider').on('afterChange', function(event, slick, currentSlide) {
$(this).addClass("active-slider");
});
```
