### ISSUE TITLE
Breakpoints does not include the exact pixel width from the breakpoint

### ISSUE THREAD

**Issue by Floddy** [kenwheeler/slick#2233]
If you setup a slider, and use a breakpoint at for example 600px - the settings within that breakpoint won't be used until you're on 599px and below.

If you use mobileFirst and set a breakpoint of for example 1025px and up for large devices, the settings in that breakpoint won't be used until you're at 1026px or over.

If you look at css media queries, for example max-width: 600px includes 600px, and min-width: 1025px includes 1025px, so the way slick works is kind of confusing. IMO a 'breakpoint' is where something kicks in, not the 'last step before or after' something kicks in.

I think the change would be rather easy to do, just swap < and > to >= and <= when checking the breakpoints.

The bigger question though are if you agree with this and if it would have a too big effect on those who's upgrading. :)

**Comment by leggomuhgreggo** [comment]
Can you give a [test case](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)? I think this issue has come up before and might be resolved in the master.

Closing pending test case

**Comment by Floddy** [comment]
Test case:
http://jsfiddle.net/h0gzn6h9/4/

It's a bit tricky to show responsive stuff in jsfiddle because of iframes and such, but if you resize the window down, the text 'I am only shown at max-width:500px' will appear before the slider switches into two slides.
