### ISSUE TITLE
Slick-states wrong when click on next (infinite: false)

### ISSUE THREAD

**Issue by truefalse10** [kenwheeler/slick#2236]
The slick-states get not updated correctly when the user click on next-button when on last slide. (only with inifite: false)
# 
###### `[  http://jsfiddle.net/H66vv/25/  ]`

use this jsfiddle to reproduce your bug: 
[http://jsfiddle.net/H66vv/25/](http://jsfiddle.net/H66vv/25/)
# 
#### Steps to reproduce the problem

Pre-condition:
- infinite: false
- slidesToShow: 3
- slider is at last slide => the last 3 slides have the class slick-active

When i now click the next-button only the last slick-item has the class **slick-active**, the class gets removed from the other 2 slicks although they are still visible. Same goes for aria-hidden.
# 
#### What is the expected behaviour?

A click on next should not change anything when slick-slider is at the end
# 
#### What is observed behaviour?

status gets updated incorrectly

**Comment by mazzaker** [comment]
Fixed with last merge https://github.com/kenwheeler/slick/commit/85cae05b99a2f9262c445194dbc13df223773a1f

So master will work.
[Fiddle](http://jsfiddle.net/H66vv/27/)
