### ISSUE TITLE
Caption outside its container

### ISSUE THREAD

**Issue by Jorgewlf88** [kenwheeler/slick#2237]
How do I catch each caption and put outside of its .slick-slide container? I mean after of .slick-dots. Is it possible?

====================================================================
Here my jsfiddle
https://jsfiddle.net/Jorge_88/h62twv7k/8/

**Comment by leggomuhgreggo** [comment]
Hey @Jorgewlf88 Check out `asNavFor` Hope that helps!

Closing: support req, not a bug

**Comment by Jorgewlf88** [comment]
thanks @leggomuhgreggo I'll try
