### ISSUE TITLE
Next/Prev not work when use slickGoTo

### ISSUE THREAD

**Issue by ebadgh** [kenwheeler/slick#2240]
> Next/Prev button not work when use slickGoTo

====================================================================
When i use SlickGoTo, its work perfect but my next/prev button and also drag not work correctly.

        $(document).ready(function(){
            //run_top_slider();
            var selected_number = $('.calendar_slide .rail ul li a.selected').parent().index();
            $('.calendar_slide .rail ul').slick({
                dots: false,
                infinite: false,
                draggable: true,
                speed: 300,
                slidesToShow: 10,
                slidesToScroll: 1,
                waitForAnimate: false,
                nextArrow: '.arrow_prev',
                prevArrow: '.arrow_next',
                rtl: true
            });
            $('.calendar_slide .rail ul').slick('slickGoTo', selected_number);
        });

====================================================================

**Comment by leggomuhgreggo** [comment]
Can you recreate in a [test case](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)?

Closing pending test case
