### ISSUE TITLE
Draggable action on desktop increments slide position by just 1, not the amount you've dragged.

### ISSUE THREAD

**Issue by KingWebsites** [kenwheeler/slick#2241]
When I use the mouse to drag **multiple** slides on Desktop they seem to only scroll a **single** slide position, which it then rebounds back to. This creates a frustrating 'jumpy' effect if you're trying to speed drag through a large amount of slides.

http://jsfiddle.net/brightonconsumer/dfkvw6pc/

I'm using just the simple settings of:
slidesToShow: 5
slidesToScroll: 1

Example (see jsFiddle):
If I drag slide 5 to where slide 1 is the first slide will rebound back to slide 2, not slide 5. A drag only increments the slider by 1, not the amount you've dragged. 

What I would have expected to see is that slide 5 would now occupy the former position of slide 1. It would be the first visible slide because it has been dragged to that position.

I **know** I have set slidesToScroll to 1 (I still use left and right buttons either side of my slider) but shouldn't the 'draggable' functionaly be separate from that? Is there any way a new 'free' setting could be applied to the draggable on desktop component?

Thank you.

**Comment by leggomuhgreggo** [comment]
Agreed. Might be something coming in 2.0. If you felt interested enough, the you could grease the skids with a PR! Thanks @KingWebsites

**Comment by jakeoblivion** [comment]
I feel this is a really important feature and quite standard across most sliders.
If you could implement the feature by setting:

.slick({
slidesToScroll: auto

Which would temporarily disable an image from snapping to the middle when you drag.

**Comment by vovayatsyuk** [comment]
I don't think it's a good idea to change `slidesToScroll` option, to achieve the result. 

`slidesToScroll` is used by next/prev controls. Dragging shouldn't use it at all.

**Comment by simeydotme** [comment]
fixed your fiddle.
http://jsfiddle.net/dfkvw6pc/5/

**Comment by jakeoblivion** [comment]
Great thanks! Noticed a really small glitch with ** infinite: true**
At the moment it if you go from slides 3 to slide 12 it bounces back to 3. Not a huge problem though.

**Comment by simeydotme** [comment]
...?

![swipetoslideinfinite](https://cloud.githubusercontent.com/assets/2817396/14714219/c542f01a-0816-11e6-901d-e1488c563542.gif)

**Comment by KingWebsites** [comment]
Thanks for pointing out that config setting. It works like a charm.

I'm sure I went though the settings looking for options last week and couldn't see anything. My mistake.

**Comment by simeydotme** [comment]
@KingWebsites / @jakeoblivion  ... I have no doubt the readme is not explicit/clear enough :laughing:  -- if you would like to get some contribution action going, and help others who have trouble... go ahead and edit the **readme.md** file's `swipeToSlide` description to what you think would be easier to understand :smiley: -- I'll accept the pull request after a quick review :+1: 

https://github.com/kenwheeler/slick/edit/master/README.markdown

**Comment by jakeoblivion** [comment]
Thanks for the gif example, however you went form slide 3 (in the center) to 2, rather than 3 to 12.
Try swiping backwards where slide 1 is on the left (3 in the center), until slide 10 (12 in the center) is on the left (for example).

Not a huge issue, but something i noticed.

**Comment by simeydotme** [comment]
ah, yeh... i see :( looks like a bug ... possibly already raised.

**Comment by jakeoblivion** [comment]
Your documentation is really good, just didn't see the swipeToSlide. I think for one of the the features on the main demo page it should be set to true as this is a great feature.

Thanks again for your contributions to fixing everything! Great carousel slider!

**Comment by agzwt** [comment]
Hello @kenwheeler and @all Git users 

![image](https://user-images.githubusercontent.com/54792517/93087242-eafa3100-f6b5-11ea-840d-7d5e9cc3fff3.png)

I want a slider like that on my website 

Does anyone have any idea? How to set a slider on line drag and slick slider arrow click slider move?

**Comment by andrewst123** [comment]
Has this been solved? If so, where can I find the solution so mouse drags work more intuitively?

**Comment by agzwt** [comment]
No one can solve this. 
Also, I'm waiting for a replay from **@kenwheeler** so we clear that this is possible or not!

**Comment by BB-000** [comment]
I have set 

`swipeToSlide: true, touchThreshold: 100`

But it still 'snaps' back weirdly to previous slides, is there a way to make this nicer??

Thanks!

**Comment by tushalRaj** [comment]
@agzwt Did you find something? I am also looking for the same

**Comment by pixelkicks-b** [comment]
@tushalRaj 

I have used this JS https://swiperjs.com/demos#scrollbar

**Comment by agzwt** [comment]
@tushalRaj 

I have used this https://swiperjs.com/demos#scrollbar

**Comment by meeeet-dev** [comment]
👍Thanks `swipeToSlide: true` Solved my Problem ❤️
