### ISSUE TITLE
Use data attributes to overwrite predefined options?

### ISSUE THREAD

**Issue by krypsin** [kenwheeler/slick#2242]
Was just thinking about it now as I will be just adding a certain class to any element I want to use Slick on, but maybe some of these elements would need a few different options rather than the ones I've set in my JS file.

Worth a feature add?

#### What is the expected behaviour?

To prioritise options from data attributes over the ones that are set from first initialization.
e.g. `data-slick='{"slidesToShow": "4", "slidesToScroll": 4}'` should overwrite:
```
$('.gnd-carousel').slick({
	slidesToShow: 1,
	slidesToScroll: 1,
	prevArrow: '...',
	nextArrow: '...'
});
```

====================================================================

#### What is observed behaviour?

No change; still uses the options I have defined in my scriptname.js file.

====================================================================

#### More Details

- Which browsers/versions does it happen on? - All
- Which jQuery/Slick version are you using? - Latest as of 12/04/2016
- Did this work before? - Nope

**Comment by leggomuhgreggo** [comment]
[It's been discussed, actually!](https://github.com/kenwheeler/slick/issues/2011). Thanks for the feedback @krypsin
