### ISSUE TITLE
Suggestion about performance of infinite carousels

### ISSUE THREAD

**Issue by asadkn** [kenwheeler/slick#2243]
I have seen Slicker Slider and Owl Carousel being used commonly as large sliders rather than small carousels. The problem with this unintended usage is, with larger images, there are a few performance issues. 

On centered carousels that are also infinite, whenever you reach the end of the loop, there's a slight delay with displaying the first slide. This messes up any animation you may have. Pretty sure you're already aware of this. If not, check this out:

http://jsfiddle.net/ecpL2d71/1/  (let it loop and restart - the first slide won't animate. You can use the navigation arrows to make that faster).
Adding an animation delay fixes the above (as in commented CSS).

I am just wondering why did we get into all this cloning mess? I don't see that as being performant ever. And the only two carousels I have seen this cloning method is on Owl and Slick. Wouldn't it be much better to adjust left property or transform as necessary?

Examples of other sliders not using cloning and yet having infinite carousels + desktop dragging: 

http://codepen.io/desandro/pen/myXdej
http://dimsemenov.com/plugins/royal-slider/
https://iosscripts.com/iosslider/

**Comment by leggomuhgreggo** [comment]
Hey @asadkn you're totally right that the cloning invites a world of hurt. [Here's a use case](http://codepen.io/leggomuhgreggo/pen/qZoXQR) which indicates cloning. I can tell you that there's been serious discussing of abandoning cloning. It's a tough call. Appreciate your feedback!

**Comment by asadkn** [comment]
Just an update to this. There's no animation lag at all when using Owl Carousel. So this is not entirely to do with clones since Owlcarousel does cloning too. But it has something to do with the DOM manipulation. I will see if I can figure it out and update this later.
