### ISSUE TITLE
Flexible width w/ responsive, dynamic slidesToShow.

### ISSUE THREAD

**Issue by louiswalch** [kenwheeler/slick#2245]
Is it possible to define a desired width for each slide, and have the slidesToShow calculate automatically without defining a bunch of breakpoints? 

For example I want my slidesToShow to equal Math.floor( window_width / 250)

**Comment by leggomuhgreggo** [comment]
I think you're looking for `variableWidth: true`. Hope that helps!

Closing: Support Req, not a bug
