### ISSUE TITLE
Urgent: current version out of sync with Bower, update git tags

### ISSUE THREAD

**Issue by implico** [kenwheeler/slick#2246]
The git version tag 1.5.9 leads to a wrong point, take look at the [line 54 in the repo](https://github.com/kenwheeler/slick/blob/7a79c43f2864ba4087e2961849c2da7bdcfe2de8/slick/slick.js#L54), and then install with Bower. You will get the old way (returns string vs. jQuery object):
```
customPaging: function(slider, i) {
  return '<button type="button" data-role="none" role="button" aria-required="false" tabindex="0">' + (i + 1) + '</button>';
},
```

**Solution**
Please run:
```
git tag 1.5.9 -f
git push origin 1.5.9 -f
```

**Edit:** additionally, the current minified version contains the old way, [ctrl+f "customPaging"](https://github.com/kenwheeler/slick/blob/7a79c43f2864ba4087e2961849c2da7bdcfe2de8/slick/slick.min.js), needs rebuilding

**Comment by simeydotme** [comment]
@implico what are you talking about?
`customPaging` has been a string for a _long_ time (maybe always?) ... just taking a random tag like `1.3.9` you can see that it's been a string returned for ages: https://github.com/kenwheeler/slick/blob/9aaaf13cb6d7bb6162063fcfcd091bec6688fc0b/slick/slick.js#L58

I think what you're referring to is the `master` branch, which is the `HEAD` and hasn't been tagged for release yet. You're welcome to download the source from `master` until @kenwheeler has pushed a release

Please, also, don't spread bad practices by asking people to force a tag update... that could have all kinds of negative implications.

**Comment by implico** [comment]
@simeydotme: yes, I was referring to the `HEAD`, so it would have been better to point that this should not be changed in the `1.*` version to remain backward compatibility (or handle if the returned value is a string/object).

I wasn't asking people to update the tag, just @kenwheeler :)

Anyway, nevermind.
