### ISSUE TITLE
Nested slick - slickGoTo error

### ISSUE THREAD

**Issue by xyralothep** [kenwheeler/slick#2248]
Hi,

I currently have a nested Slick (one Slick within another).  I'm using slickFilter to filter the parent Slick, and then trying to reset the child slick to the first slide using slick('slickGoTo', 0).  However it is giving the following error and not resetting:

Uncaught TypeError: Cannot read property 'slickGoTo' of undefined

You can see this here - it's only on the mobile version so you will need to reduce the browser size.

http://pricegore.jamessui.co.uk/

To do this, slick on the menu icon bottom right and then select one of the categories from the menu.

Any ideas?

Thanks.

**Comment by leggomuhgreggo** [comment]
Hey can you recreate in a fiddle?

Closing pending filddle

**Comment by xyralothep** [comment]
Hi,

Here is it replicated in a fiddle:

http://jsfiddle.net/oxjr7454/

It is unslicking and restarting the slick on resize, as in my other example I need to apply the isotope plugin instead of slick on larger screens.

Thanks.
