### ISSUE TITLE
Initial transition on slider is screwy

### ISSUE THREAD

**Issue by jayharland** [kenwheeler/slick#2251]
When the slider loads, it appears fine, but navigating to another slide (either through the dots or swipe or whatever) the first transition seems real screwy. It only seems to happen for that initial transition, no matter which slide I'm going to.

The slider is part of a fairly large project and I am unable to recreate everything in a JSFiddle, but I captured it as a GIF in hopes that maybe someone has had a similar issue, recognizes it, and can help me out.

[Click here to see the GIF](http://gph.is/1W1gVzn)

As you can see in the gif, it loads, and as soon as I click a dot, it happens, then the rest of the transitions are fine.

It doesn't happen every time, just most of the time.

I'm only seeing it on Firefox so far

I'm using 1.5.9 of Slick

I realize isn't a well fleshed out issue, but I could really use some suggestions.

Thanks.

**Comment by leggomuhgreggo** [comment]
Might could try `useTransform: true`. Hope that helps.
