### ISSUE TITLE
Infinite loop and autoplay conflict 

### ISSUE THREAD

**Issue by amit-brainstormforce** [kenwheeler/slick#2252]
> When infiniteLoop is set to false and autoplay is set to true, carousel reverses order instead stopping at the last slide. If we click on next/prev buttons it worked well. 

====================================================================

###### `http://jsfiddle.net/fmo50w7n/304/`  

====================================================================

#### Steps to reproduce the problem

1. Set "infinite" option to false
2. Set "autoplay" option to true

====================================================================

#### What is the expected behaviour?

It should be stopped at the end of carousel.

====================================================================

#### What is observed behaviour?

It is starts reversing the order if "autoplay" is false.

====================================================================

**Comment by leggomuhgreggo** [comment]
Hey @amit-brainstormforce, interesting issue. Totally get your reasoning. I can see arguments for both behaviors. I did a search through the issue history, and found #1096 and #528 which should help clarify and #1096 even has a solution. Hope that helps. Thanks!
