### ISSUE TITLE
Documentation Addition

### ISSUE THREAD

**Issue by colinsanford** [kenwheeler/slick#2253]
Hi, I recently spent a few hours trying to debug an issue with the slider and ended up finding out that it's actually expected behaviour. I would like to request an addition to the documentation that mentions this combination of settings conflicting.

The code I was using had `fade` set to `true`. The slider needed to show several slides at once so I set the `slidesToShow` option to `2` and it wouldn't work. I eventually traced the problem to line `1860` in the `setPosition` method where I realized that if fade is `true` it doesn't set the left position as you can see below (which won't allow slidesToShow to work).

```js
if (_.options.fade === false) {
    _.setCSS(_.getLeft(_.currentSlide));
} else {
    _.setFade();
}
```

This is fine and I imagine there's a good reason for it, I just don't see anything in the docs about it (which would have saved me several hours of "debugging").

Would you please add a note under `slidesToShow` and `fade` that they are not compatible with each other?

**Comment by leggomuhgreggo** [comment]
Hey @colinsanford  sorry to hear about the goose change! We accept PRs to the readme if you'd like to make one. There's been talk of opening a wiki for this repo too, but I'm not sure if that'll be in the near term. Thanks for the comment!
