### ISSUE TITLE
3 columns in a row when having only three records.

### ISSUE THREAD

**Issue by subzerobears** [kenwheeler/slick#2256]
We want to show up to 6 images at a time. Basically two rows three columns. However in some cases we may only have 3 images. In that case I see two rows and two columns. I want to see just one row with three columns. What am I setting wrong? Looks like the width calculation is wrong. I have slidestoshow set to 3.

Thanks,

Rob

**Comment by giriprashaad** [comment]
Do you have fiddle we can see?

**Comment by subzerobears** [comment]
What is the best way to put one together? I haven't put one together before. Should I past the HTML and jquery libraries?

**Comment by subzerobears** [comment]
Here is my attempt at creating one. https://jsfiddle.net/subzerobears/jfgx6e2o/ I want all three items on one line. Not sure if I should paste the HTML code before the slick javascript runs against it.

**Comment by leggomuhgreggo** [comment]
Hey @subzerobears check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). 

Strictly speaking, we just track bugs here, and attention for support requests is limited. That said, sometimes people make time to help, but you're definitely going to want to make a functioning fiddle, and the one you linked doesn't seem to work. There's a demo one in the contribution guidelines that you can fork to try to recreate your issue. 

Based on your description, I'd recommend wrapping the every set of six images in a div and skip the row feature, that way you can get better customization with image presentation using CSS with each slide. I dont think you can adjust the rows based on remainder count. Row option is a little tricky even when not trying to do something like this.

Hope that helps!
