### ISSUE TITLE
Trying to combine slick and maginfic popup. Small help needed. 

### ISSUE THREAD

**Issue by danyj** [kenwheeler/slick#2257]
I am trying to combine Slick slider and Maginfic popup to add thumbnail navigation to magnific based on few users request.

https://github.com/dimsemenov/Magnific-Popup/issues/224

but  looks like slick fires to late if there are not enough images. 
http://jsfiddle.net/fh2pwv0e/1/

if I add more heavy load images than it works as it should 

http://jsfiddle.net/f93q3fqh/1/

but still bugs me as to why. 

It would be great if you could help us combine these two great scripts.

**Comment by leggomuhgreggo** [comment]
Hey I'm gonna close because this is a support request and not a bug. My guess is that its because there's maybe a display none before the popup is triggered. Could try something like this:

`$('.your-element').slick('setPosition');` 

to reset the slick when the popup goes.

**Comment by danyj** [comment]
@leggomuhgreggo 

no bud  it is a bug ,  just figured it out 
slickGoTo  does not work right if there are no hidden slides , look here ,http://jsfiddle.net/fh2pwv0e/2/

 I changed the number of `slidesToShow  `on nonworking example  and it fires properly since there are 2 hidden slides. If none are hidden `slickGoTo  `does not work.

**Comment by leggomuhgreggo** [comment]
If there are no hidden slides, where would it go to? There is an existing
enhancement request to allow slick to work when slidesToShow is >= to
slideCount, but there's some debate on what the expected behavior should
be--Is that maybe whats going on with your example?

**Comment by danyj** [comment]
my opinion is that slideGoTo should ad least  change the current slide , that is the problem I had , I managed it to change current within my own loop via index but like said slideGoTo  should do that.
