### ISSUE TITLE
swipeToSlide adds too many dots, prev button clicks don't work

### ISSUE THREAD

**Issue by MarBau** [kenwheeler/slick#2258]
Hi there,

i got a problem when i set _swipeToSlide: true_ with a fixed number of slides. It generates more "navigation dots" making it possible to go past the last slide and rendering multiple clicks on the prev button useless.

====================================================================

###### http://jsfiddle.net/fmo50w7n/306/

====================================================================

#### Steps to reproduce the problem

1. Swipe to Slide # 12 (or click dot # 8)
2. You can see 4 more dots on the right, click either next or one of those dots 
3. Now clicking on prev navigates the dots, but not the slides

====================================================================

#### What is the expected behaviour?
1. # of dots are rendered correctly
2. if at slide # 12 and clicking prev button that it would go to slide # 11

====================================================================

#### More Details

- Which browsers/versions does it happen on?
  _Chrome Version 49.0.2623.112 m_ 

- Which jQuery/Slick version are you using?
  _jQuery v2.2.3
  Slick 1.5.9_

- Did this work before?
  _No_

====================================================================

Hope you can help me with my problem.
Thanks for this great slider. 

Greetings,
Marcel

**Comment by heringsfilet** [comment]
I would love to see this fixed, too!

**Comment by simeydotme** [comment]
Could you please review your fiddle, again, and see if it's working as expected now?
there was a merge with #2152 just now... I have a feeling it fixed your issue?

**Comment by MarBau** [comment]
Working as expected now, thanks a lot.

Greetings,
Marcel
