### ISSUE TITLE
Feature request: jQuery free version

### ISSUE THREAD

**Issue by johannesjo** [kenwheeler/slick#2262]
The slick carousel would be truly the carousel I need, if it not were for the jQuery dependency. Is there any chance that there will be a release, which will be functioning independently from jQuery so it could be integrated with less overhead with angular and react?

**Comment by puresamari** [comment]
👍  what also could be considered is using ken 'cash' as lightweight-jquery alternative

**Comment by leggomuhgreggo** [comment]
There's a pretty nice discussion on this subject in #494. There's definitely pros and cons. I think if it were gonna happen, my guess is it would happen in the v2 branch, but doesn't look like that's the current direction. Would be @kenwheeler's call, but the likelihood would definitely increase with a PR 😃
