### ISSUE TITLE
Can't go backwards after reaching the last slide

### ISSUE THREAD

**Issue by ignaciodeele** [kenwheeler/slick#2263]
When 'infinite' is set to false, if you reach the last slide and keep clicking on "Next", the slider keeps incorrectly updating the states of the previous slides. So, if you then want to go backwards, you'll have to click on "Previous" as many times (more or less) as you clicked on "Next".

====================================================================
###### `https://jsfiddle.net/ignaciodeele/ojp9ktot/5/`  
====================================================================

#### Steps to reproduce the problem

1. Click on "Next" until you reach the last slide ("Nine").
2. Click on "Next" six more times.
3. Click on "Previous" five to seven times, until it works.

====================================================================

#### What is the expected behaviour?

After reaching the right end of the slider, if you keep clicking "Next" you should be able to go back just by clicking only once on "Previous". This is indeed how the left end works (if you are seeing the first slide and click on "Previous" many times, it only takes a single click on "Next" to move forwards).
By the way, it would be a nice feature to set the button as 'disabled' when there are no more slides to show.

====================================================================

#### What is observed behaviour?
You have to click on "Previous" many times, instead of just one, to see the previous slides.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Firefox 45.0.2, Chrome 49, IE 11
- Which jQuery/Slick version are you using?
jQuery 2.2.3, Slick 1.5.9

**Comment by leggomuhgreggo** [comment]
Hey @ignaciodeele Check this issue out: #2146 

Definitely a little confusing. Hope that helps.
