### ISSUE TITLE
Disable dots click

### ISSUE THREAD

**Issue by gabskoro** [kenwheeler/slick#2267]
Now when we click on the dots we move to the next slide, is there any option to disable this behavior?

Options: **swipe**, **touchMove** and **accessibility** didn't help.

P.s. don't need to add the example to jsfiddle, can test it on your [example](http://jsfiddle.net/simeydotme/fmo50w7n/).

**Comment by ahmadalfy** [comment]
This feature isn't availble on slick. I understand that you want to use the dots as a map so that the user know which slide is he currently trying.

I would suggest do it by using `pointer-events: none` with CSS. No matter when the user click, nothing will happen

**Comment by simeydotme** [comment]
you could also place an invisible `<div>` over the top of the dots to prevent interaction :)
