### ISSUE TITLE
centerMode not working with more than 1 slideToShow?

### ISSUE THREAD

**Issue by serealkiller** [kenwheeler/slick#2268]
I seem to have a problem with making centermode work when slidesToShow is set to anything other than 1. When i set it at 1 and centerMode true it will center the element and show parts of the other two on each side like it should but if i set it to 3 for example it will show all the elements (in this case 5). It will center the selected item but it wont show 3 items with halves on each side.
If i set centerMode to false it will behave as expected and only show 3 items.

## Steps to reproduce the problem

[JSFiddle](https://jsfiddle.net/sereal_killer/5mqabwfm/7/)
In the JSFiddle, change slidesToShow to 3 
Change or make sure that centerMode is set to true

## What is observed behaviour?

The slider will show 5 pictures instead of 3.

## More Details

Which browsers/versions does it happen on? i am using chrome
Which jQuery/Slick version are you using? Latest
Did this work before? Don't know this is the first time i am using slick

Any ideas why this is happening?

Thanks

**Comment by leggomuhgreggo** [comment]
Hey @serealkiller  Default for `centerMode` is `centerPadding: 20`. I think the idea is that you can have faded items in the wings. `centerPadding: 0` fixes. Hope that helps.
