### ISSUE TITLE
Lazy Load Images doesn't show until click next arrow

### ISSUE THREAD

**Issue by marcelc63** [kenwheeler/slick#2270]
I have slick slideshows featuring Instagram images. For few of the slideshows, the image doesn't load and will require clicking next arrow for it to load.

From my investigation, the images that fails to load did actually load but slick weren't able to convert them from using attribute data-lazy and class slick-loading to the actual attribute src with opacity 1.

====================================================================

I would like to reproduce the bug but I'm not sure how.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome and Safari
- Which jQuery/Slick version are you using?
1.5.9

**Comment by simeydotme** [comment]
To reproduce, @marcelc63 you can use the `jsfiddle` that is linked in the [ contribution guidelines ](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) ... just use placeholder images, the instagram images are not important :)

**Comment by simeydotme** [comment]
I'll reopen this if you can reproduce.
