### ISSUE TITLE
Can we also add CDNJS in readme?

### ISSUE THREAD

**Issue by PeterDaveHello** [kenwheeler/slick#2271]
Hi @kenwheeler,

I'm CDNJS maintainer, since we also host your awesome lib here: https://cdnjs.com/libraries/slick-carousel for a long time(since 15 May 2014 as you can see in https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/slick-carousel), I wonder if you can also add CDNJS info in your readme so that the users can know that? Thanks :smile: 

Best,
Peter

**Comment by kenwheeler** [comment]
Absolutely.

**Comment by PeterDaveHello** [comment]
Thanks, may I send a PR to add this? Or you will like to add it? I'm not sure the style you want to display it :smile:
