### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by kimwild02** [kenwheeler/slick#2273]
I cannot get this to work and I have no idea what I am missing.

====================================================================

https://jsfiddle.net/kimwild/9amy2fua/2/

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

To see a single item slider 

====================================================================

#### What is observed behaviour?

The slider is not working

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before? no

**Comment by simeydotme** [comment]
https://jsfiddle.net/9amy2fua/5/
1. You didn't have jQuery
2. Your JS file was not correct.

**Comment by kimwild02** [comment]
Great thank you. How can I get arrows and dots to show up?
