### ISSUE TITLE
Sidebar in Novello

### ISSUE THREAD

**Issue by karobson** [kenwheeler/slick#2274]
> short description of the bug / issue, provide more detail below.
How do i change the width of the sidebar in the Novello template?
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by simeydotme** [comment]
¯\_(ツ)_/¯
