### ISSUE TITLE
Does slick work with jQuery 2?

### ISSUE THREAD

**Issue by designweb** [kenwheeler/slick#2276]
> short description of the bug / issue, provide more detail below.

I am using FoundationPress for a new project and wanted to use Slick.
It says in the docs to use jQuery 1.7+, but I am having issues getting it to work with jQuery 2

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Yes! Definitely works with jQuery 2.0.0. Also, please try to recreate a problem you're having in a reduced test case before making an issue. There's a jsfiddle you can fork and apply whatever version of jquery you'd like. More on that in the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required).
