### ISSUE TITLE
can't set the slick element options on init

### ISSUE THREAD

**Issue by 440459012** [kenwheeler/slick#2277]
> can't get the slick element options on init

========================

i tried this:

`$(infinite_slider).on('init',function(event,slick_element,ele){
        if (slick_element.slideCount < 5){
            slick_element.slick('slickSetOption',{lazyLoad:'progressive',slidesToShow:2},false)
        } else{
            slick_element.slick('slickSetOption',{lazyLoad:'ondemand',slidesToShow:5},true)
        }
    });`

but this say:
Uncaught TypeError: slick_element.slick is not a function

how can i set options for specified element ?
P.S.
this won't work too...
`$(infinite_slider).on('init',function(event,slick_element,ele){
        if (slick_element.slideCount < 5){
            $(slick_element).slick('slickSetOption',{lazyLoad:'progressive',slidesToShow:2},false)
        } else{
            $(slick_element).slick('slickSetOption',{lazyLoad:'ondemand',slidesToShow:5},true)
        }
    });`

thanks, sorry for bad english

**Comment by leggomuhgreggo** [comment]
Hey @440459012 can you please recreate in a reduced test case like a jsfiddle or a codepen? There's one you can fork in the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). Thanks!

closing pending fiddle

**Comment by 440459012** [comment]
is it so hard to answer without jsfidle? question is simple, how to get object of slider on init event, and set some options for it, i have more sliders with same class

**Comment by leggomuhgreggo** [comment]
Is it so hard to make a fiddle?

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
