### ISSUE TITLE
Need an 'onAfterLazyLoad' event to rebind when new elements added to the DOM 

### ISSUE THREAD

**Issue by Lindsayanng** [kenwheeler/slick#2278]
I am having an issue where my sizing and positioning code is not being applied to slides that are added via lazy load (on demand). You can see in the pasted fiddle that the images added via lazyload are getting a top margin that is calculated based on a 0pixel height and not the actual image height which results in them being off centered. 

====================================================================

###### `[  JSFIDDLE  ]`  

You can see in the fiddle that I am using console.log() to output the heights as calculated by the script. The ones with 0 are always lazy-loaded: 
http://jsfiddle.net/fhj6dnfb/34/

====================================================================

#### Steps to reproduce the problem

1. setup your slick with the following settings: 
```
jQuery(".slider").slick({
    autoplay: false,
    dots: false,
    centerMode: true,
    slidesToShow: 1,
    variableWidth: true, 
    lazyLoad: "ondemand"
});
```
2. Apply some type of styling using jquery to all slides 
3. You will see that this style is only applied to slides that were loaded without lazy-loading. 

====================================================================

#### More Details

- Using slick version 1.5.9

**Comment by leggomuhgreggo** [comment]
Hey @Lindsayanng you probably want to tie the logic that runs on a lazy loaded image using the load event; something like `$('.slick-slide img').on('load', fn)`. Hope this helps!

Closing: support request.

**Comment by Lindsayanng** [comment]
@leggomuhgreggo  that was the first thing I did and it seems that it still does not trigger after the src is added to the img tag 

[http://jsfiddle.net/fhj6dnfb/42/](http://jsfiddle.net/fhj6dnfb/42/
)

**Comment by leggomuhgreggo** [comment]
Hmm only load event I see in the fiddle is tied to the slider element, not the image. Try [this](http://jsfiddle.net/ke13wrvf/) instead.
