### ISSUE TITLE
Featured Suggestion: comp screenshot attached

### ISSUE THREAD

**Issue by manuelparejas** [kenwheeler/slick#2279]
I need to set spacing on each slick item.
Sample Comp: http://prntscr.com/axbhfa
wrapper width is 1258px 

Currently the slick can only be setup in a way where all slick item are same width and close together --> http://prntscr.com/axbhrt

Is there a way to add spacing on each slick item.

Thanks in advanced.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey @manuelparejas just add padding on the slick slide, I recommend a nested div too. Good luck.

Closing: support request.
