### ISSUE TITLE
Clicking on disabled next arrow forces you to click as many times on prev arrow to slide

### ISSUE THREAD

**Issue by JonWallsten** [kenwheeler/slick#2280]
> short description of the bug / issue, provide more detail below.
When using infinite: false and you get to the end, but continue to press of the disabled arrow makes the slider behave incorrect. In order to go to the previous slide you need the click the same amount of times on the previous button.
====================================================================

###### `[  http://jsfiddle.net/189kpfvn/2/  ]`  

====================================================================

#### Steps to reproduce the problem

1. Click next arrow until the last item and see the arrow gets disabled.
2. Click the disabled arrow X times
3. Now try to click the prev arrow to slide

====================================================================

#### What is the expected behaviour?

It should slide the the previous slide on first click

====================================================================

#### What is observed behaviour?

You need to click X amount of times before it slides.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome
- Which jQuery/Slick version are you using?
Slick: 1.5.9
jQuery 1.9.1/3.0.0-pre

- Did this work before?
Don't know

**Comment by leggomuhgreggo** [comment]
Hey @JonWallsten this got fixed on the master with PR #2152. Thanks!

**Comment by JonWallsten** [comment]
Sorry, thought I searched enough. Maybe missed to search in closed issues. Thanks for the pointer. Just tested, and it works fine!

**Comment by leggomuhgreggo** [comment]
Awesome, glad it's working for you!
