### ISSUE TITLE
If slidesToShow is more than one, slide  width calc is incorect

### ISSUE THREAD

**Issue by danyj** [kenwheeler/slick#2281]
I am placing few divs inside slides and they come with a 1px border
I also used this approach to separate the slides 

```
.slick-slide {
    margin-left:40px;
}
/* the parent */
.slick-list {
    margin-left:-40px;
}
```
https://github.com/kenwheeler/slick/issues/582#issuecomment-61882540

now if slidesToShow  are set at odd number the width of the slides is wrong and is not taking in count the inside div border , so the last item border is not visible  and you can see this here , 

![screenshot_4](https://cloud.githubusercontent.com/assets/2340172/14856750/a464a65e-0c99-11e6-9682-2be32ff20cd5.jpg)

or live example   https://jsfiddle.net/fmo50w7n/346/

If I change the slidesToShow   to 2 
https://jsfiddle.net/fmo50w7n/347/

the division is ok and  last item border is visible. 

Now this is just an example of particular space between slides + border  but my slick is going to be used by multiple users and I cannot guess if they will have the border inside and what size that border will be. Looks to me like the width calc is not taking everything in count or it simply cannot divide odd number properly so it rounds it up., 

Any help is appreciated.

**Comment by leggomuhgreggo** [comment]
Hey @danyj, the workaround is use padding and a nested element, instead of margin, which I think isn't fully supported at this time.  

Margins are a bit of a sticky wicket where layout externalities are concerned. I think it'd be possible to accomplish, but the complications to the calculations, and the risk of augmented edge cases, strikes me as being a formidable undertaking.

I think as far as internal priorities go it's not very high on the ranking, but if you were up to taking a swing at a PR that'd be awesome. I think it'd start with a refactor for `outerHeight`, with a slough of test cases including adjacent elements inline, as well as top and bottom, with special attention paid to vertical mode and center mode. 

Hope that helps. Thanks!

**Comment by danyj** [comment]
@leggomuhgreggo   
>the workaround is use padding and a nested element,

I tried that also , and tested all possible grid layout combos with margin, padding , negative pulls and it just does not work for me 
this is exactly how I have my slick setup
https://jsfiddle.net/fmo50w7n/349/

and in my script I do 

					if($space > 0 && $slidesToShow > 1) {
						
						$this.find('.slick-slide').css({
							paddingLeft: $space + 'px',
							//paddingLeft: $space + 'px'
						});
			
						$this.css({
							marginLeft: -$space + 'px',
							//marginRight: -$space + 'px'
						});	
					}

**Comment by danyj** [comment]
@leggomuhgreggo 
>but if you were up to taking a swing at a PR that'd be awesome

can you point me to the method that does the calc ?

**Comment by leggomuhgreggo** [comment]
Check this: https://jsfiddle.net/bja34r13/

And here's the setDimensions method: https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1913

**Comment by danyj** [comment]
ok fund my bug but at the same time yours , it is not calc division 
I have the slider inside a container called related-container , and it has `overflow:hidden;`
I was forced to add overflow because slick goes over 

https://jsfiddle.net/bja34r13/1/

if I remove the overflow the slider goes over by few px  and the last item border shows up 
http://prnt.sc/axlhjn

**Comment by danyj** [comment]
@leggomuhgreggo  here , same on default slick 
container max-width : 600px;  no overflow  and slick goes over

https://jsfiddle.net/bja34r13/3/


![vdegwu0](https://cloud.githubusercontent.com/assets/2340172/14865232/f465f756-0cbd-11e6-8201-85058b8c114d.png)

**Comment by danyj** [comment]
the bigger the border of the inside element , the bigger the overflow  and slick goes crazy 
https://jsfiddle.net/bja34r13/5/

![screenshot_5](https://cloud.githubusercontent.com/assets/2340172/14865325/76c53068-0cbe-11e6-9905-a539b64aa5e1.jpg)


Sorry but this does not seem like enhancement but more like a bug and we should be able to style inner elements as we need.

**Comment by danyj** [comment]
@leggomuhgreggo   I tested as much as I can , changing display propertie , adding wrappers , anything but slick flows over by few px every time ,  look  http://prntscr.com/axmd8n
https://jsfiddle.net/bja34r13/5/

and if I add overflow to slick holder , the last item gets cut by few px , this where the issue with missing border comes from.

**Comment by leggomuhgreggo** [comment]
Ohhh you know what this is? It's the same as #2167.

I'm not 100% on the browser constraints related to this, but basically there's a discrepancy between `sildeWidth` * `slideCount` and `sliderWidth`. Logged to the console in a [modified version of your fiddle](http://jsfiddle.net/r3j64bcm/1/)

Gonna keep the other one as the primary for this issue. Thanks @danyj

**Comment by danyj** [comment]
Thank you , I thought I am going insane!

**Comment by danyj** [comment]
Hacky way but works for time being , @leggomuhgreggo   thnx for pointers, after initiation I added this 

```

						setTimeout ( function (){
							var w = $this.width();
							var ws = ($this.find('.slick-slide').outerWidth()) * $slidesToShow - $space;
							var $missing = ws - w;
							$this.find('.slick-track').css({
								marginLeft: - $missing + 'px',
							});
						},100);
```
