### ISSUE TITLE
Enabling accesibility with slickSetOption doesn't work

### ISSUE THREAD

**Issue by Karuma** [kenwheeler/slick#2283]
When i start slick with accesibility false and try set accesibility back to true its dosent work.
Draggable and swipe work perfectly but accesibility don`t want start working. 

$('#slickProjects').slick({
    accessibility: false,
    draggable: false,
    swipe: false,
    arrows: false,
});

function slickStart() {
  $('#slickProjects').slick("slickSetOption", "accessibility", true, true);
  $('#slickProjects').slick("slickSetOption", "draggable", true, true);
  $('#slickProjects').slick("slickSetOption", "swipe", true, true);
  $('#slickProjects').slick("slickSetOption", "arrows", true, true);
}

**Comment by leggomuhgreggo** [comment]
Hey @Karuma can you please recreate in a fiddle? Check out the [contribution guidleines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) for more details. Thanks!

Closing pending fiddle.
