### ISSUE TITLE
Peekaboo Text

### ISSUE THREAD

**Issue by mbritton** [kenwheeler/slick#2286]
> short description of the bug / issue, provide more detail below.

My client wants a carousel that displays one central slide, and allows adjacent slides on either side to display half of themselves. So you would see the middle slide, and half of either slide to the right and left. I'm wondering if there's a trick to this that won't require extensive customization of the JavaScript plugin.

#### What is the expected behaviour?

You would see the middle slide, and half of either slide to the right and left.

![subway_slides_mockup](https://cloud.githubusercontent.com/assets/130869/14894606/644946e8-0d42-11e6-92ac-3a3029327977.jpg)

**Comment by mbritton** [comment]
Here's a link to a ['JSFiddle'](https://jsfiddle.net/mbritton/hew6vbx8/13/#&togetherjs=jn1M6vMJdc)  I'm trying to get working to simulate what I'm doing on my workstation locally

**Comment by mbritton** [comment]
I guess what I need to know is the formula for calculating the centerPadding on resize in order to achieve this layout.

**Comment by leggomuhgreggo** [comment]
Hey @mbritton, check out `centerMode` and `centerPadding`.

**Comment by mbritton** [comment]
Yes, this is where I've been working. What I am trying to do is recalculate centerPadding for different window widths to achieve the aforementioned layout. It appears this will require a different approach in scaling the slides themselves.

I take it from your response that this is as much as you can offer in terms of direction?

**Comment by leggomuhgreggo** [comment]
I think centerPadding is the only baked in way to achieve what you want, and my impression is that it currently doesn't support percentages, or sizing functions. There may be other ways of doing it, but I can't think of any off the top of my head. Perhaps someone else has some ideas.

I closed because the idea is to use this as a bug tracker. Support requests are best directed to stackoverflow or the gitter chat. If you're feeling ambitious you could make a PR with an enhancement :)

Check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). 

Thanks!

**Comment by leggomuhgreggo** [comment]
I guess you could always set the px value of center mode based on the window size. If you needed to make it fluid, you could debounce a resize event function that fires the setOptions method with the new centerPadding

**Comment by mbritton** [comment]
Can you describe for me what centermode actually is? That is, what properties of the carousel does centermode impact? I think this will help me finish extending the component.

**Comment by leggomuhgreggo** [comment]
It adds a slick-center class to the centered slide, allows you to see inactive prev/next slides if centerPadding > 0, forces slidesToScroll to 1

**Comment by mbritton** [comment]
If this is what you mean, my layout isn't correct.

function onResize() {
    console.log('onResize');
    var slideSize = $('.slideContents').width(); // Content inside class is wrapped in a div 
    console.log('slideSize: '+slideSize);
    var centerPadding = $(window).width()-(slideSize/2);
    console.log('centerPadding: '+centerPadding);


    $('.' + slickClass).slick('slickSetOption','centerPadding',centerPadding+'px');
}

**Comment by leggomuhgreggo** [comment]
Yeah something like that. Would need a fiddle to debug.

**Comment by mbritton** [comment]
I tried to set up a fiddle with slick and was unable to get it running as I have it on my workstation. [https://jsfiddle.net/mbritton/hew6vbx8/23/](https://jsfiddle.net/mbritton/hew6vbx8/23/)

**Comment by leggomuhgreggo** [comment]
http://codepen.io/leggomuhgreggo/pen/LNgemg?editors=0011

**Comment by mbritton** [comment]
Why 30 for the divisor for w in getPadding()?

**Comment by leggomuhgreggo** [comment]
Well I'm not sure what you're going for. That's a placeholder. Cleaned it up a bit if you refresh.

**Comment by mbritton** [comment]
Cool, thanks so much. I will make a PR if / when I get it working.

**Comment by mbritton** [comment]
Thinking aloud a bit here, so please excuse the book.

OK, so I need to understand how to calculate the centerPadding. The logic is fine and was similar to what I was doing, with the exception of debouncing. It does work, but not fluidly.

I have n slides with content of equal width. The centerPadding needs to pin the adjacent slides' centers on the right and left sides of the carousel. This needs to happen on resize, so the carousel can scale out properly. My assumption is that centerPadding is therefore half of the slide width...but that isn't working properly.

**Comment by mbritton** [comment]
I wasn't able to make this functionality happen, so I used media queries and a div wrapper. I think this is a more appropriate approach. Thanks for the direction you gave in your previous posts.
