### ISSUE TITLE
Display issue when using slick near floating elements

### ISSUE THREAD

**Issue by ryanwalters** [kenwheeler/slick#2287]
> Display issue when using slick near floating elements

====================================================================
###### `http://jsfiddle.net/fmo50w7n/352/`  
====================================================================

#### Steps to reproduce the problem

1. Insert a carousel near a floated element

====================================================================

#### What is the expected behaviour?

Carousel is contained within the space available next to the floated element, similar to content flowing around a floated element.

====================================================================

#### What is observed behaviour?

Parts of the carousel extend into the floated element.  

====================================================================

#### More Details

- Browsers: Chrome, FF, IE11
- jQuery: 3.0.0-pre, 2.2.0; Slick: 1.5.9
- Did this work before? No idea

**Comment by leggomuhgreggo** [comment]
Hey @ryanwalters floating an element takes it out of the document flow. You can add `clear: both` to `.slider` or if you want them to sit inline, check out `display: inline-block`. Since this is how css is supposed to work, and not a bug with the repo, I'm going to close. Good luck.
