### ISSUE TITLE
Infinite:false fails and reverses when autoplay:true

### ISSUE THREAD

**Issue by qwertydude** [kenwheeler/slick#2288]
When infinite is set to false and autoplay is set to true, the slider reverses direction at the last slide, rather than stopping.

http://jsfiddle.net/chrishoward/fmo50w7n/353/

Tested: Opera, Chrome, Firefox.

For anyone looking for a workaround until this is fixed, add something like this to your js:

`
  $('.slider').on("afterChange", function(event, slick, currentSlide) {
    if (!$(this).slick("slickGetOption", "infinite") && $(this).slick("slickGetOption", "autoplay") && (currentSlide + 1) === slick.slideCount) {
      $(this).slick("slickSetOption", "autoplay", false, true);
    }
  });
`

**Comment by leggomuhgreggo** [comment]
Hey @qwertydude check out #2252 and the cited issues. Hope that helps.

**Comment by qwertydude** [comment]
Ah sorry! I searched, but must have still had "open" option on. Thanks
