### ISSUE TITLE
There is an empty element btw first and last slide on mobilefirst calculation

### ISSUE THREAD

**Issue by Vidit92** [kenwheeler/slick#2289]
> short description of the bug / issue, provide more detail below.
I get an empty slide between the first and last slides on responsive display infinite loop breakpoint 1024 and below
====================================================================

https://jsfiddle.net/512zw4cp/

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  Expect to work like a image carousel

====================================================================

#### What is observed behaviour?

...  Got it working but has an empty element after the last and before the first slide.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Tested on all browser and mobile.
- Which jQuery/Slick version are you using?
Slick v1.5.9
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey @Vidit92, looks like that fiddle isn't working. Can you recreate in a more reduced test case--perhaps forking the fiddle in the issue template? Thanks!

Closing pending fiddle update
