### ISSUE TITLE
Webpack - $(...).slick is not a function

### ISSUE THREAD

**Issue by umarmw** [kenwheeler/slick#2290]
Hello,

I'm trying to use webpack to bundle all my js files and libraries. So far it works well for other plugins but when calling and using slick, I'm getting a:
Uncaught TypeError: $(...).slick is not a function

====================================================================

Main JS file codes:

```
global.jQuery = require('./vendor/jquery/dist/jquery');
window.$ = global.$ = global.jQuery;

//Add bootstrap & libraries
require('./vendor/bootstrap/dist/js/bootstrap');
require('./vendor/slick-carousel/slick/slick');

$(document).ready(function(){

  $(".slider").slick({
    infinite: false
  });
});
```

ps: "vendor" is the custom name given for "bower_components"

my webpack config:

```
var config = {
  watch: false,
  output: {
    filename: 'app.js'
  },
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      mangle: {
        except: ['$super', '$', 'exports', 'require']
      },
      output: {
        comments: false
      }
    })
  ],
  devtool: 'source-map'
}
```

====================================================================

#### What is observed behaviour?

Slick carousel is not being executed.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome 49
Firefox 44.0.2
- Which jQuery/Slick version are you using?
jQuery 2.2.3/Slick 1.5.9
- Did this work before?
Yes, before webpack integration

**Comment by umarmw** [comment]
Hello, after some investigation I've found out that by commenting the first block of code and leaving the else part, fixed the issue, as below:

```
(function(factory) {
    'use strict';
    //if (typeof define === 'function' && define.amd) {
    //    define(['jquery'], factory);
    //} else if (typeof exports !== 'undefined') {
    //    module.exports = factory(require('jquery'));
    //} else {
        factory(jQuery);
    //}
}
```

I'll keep on digging, but if any of you have an idea, it would be appreciated.

Thanks,

:)

**Comment by leggomuhgreggo** [comment]
Hey @umarmw yeah looks like you got it. There's a couple threads about it: #1792 and #1170. Thanks for the contribution!

**Comment by umarmw** [comment]
Hello,

I've found the fix for the issue; it by declaring jquery as global in the webpack configuration:

http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack

Point 2:

```
var webpack = require("webpack");

    ...

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ]

```

Thanks

**Comment by noomz** [comment]
or just
```javascript
import $ from 'jquery';

import 'slick-carousel';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
```

**Comment by sw-double** [comment]
script-loader did the trick for me:

```js
window.$ = window.jQuery = require('jquery');
require('script!slick-carousel');

$(...).slick(...);
```

**Comment by Esslamb** [comment]
@sw-double Thanks for that it worked for me. I did a little digging and apparently the best way to provide global variables such as jquery to all modules is to use the provide plugin as suggested by @umarmw. However it took me a while to figure out that for the provide plugin to work the path for node_modules needs to be set. So for anyone struggling just add this to the webpack config.
```
resolve: {
    root: path.resolve('../node_modules'),
    extensions: ['', '.js'],
        alias: {
            jquery: "jquery/src/jquery"
        }
    }
```

**Comment by juukie** [comment]
Thanks @sw-double.
I had to use the script-loader as well.
```
import $ from 'jquery';
import 'script!slick-carousel';
import 'slick-carousel/slick/slick.scss';

$(function () {
    let elem = $('.references-slider');

    elem.slick({
        //
    });
});
```

My webpack config has
```
plugins: [
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
    }),

    //
],
```

**Comment by indapublic** [comment]
```
window.$ = window.jQuery = require('jquery'); // or import $ from 'jquery';

import 'script!slick-carousel';
```

> Uncaught ReferenceError: jQuery is not defined
>     at eval (eval at module.exports

**Comment by chbdetta** [comment]
I have the same error here,
> TypeError: $(...).slick is not a function
I install package with `npm`
And with expose-loader to expose jquery to window.$ and window.jQuery.
By debugging, I find out the slick has its own copy of jquery
```js
(function(factory) {
  "use strict";
  if (typeof define === "function" && define.amd) {
    define(["jquery"], factory);
  } else if (typeof exports !== "undefined") {
    module.exports = factory(require("jquery"));
  } else {
    factory(jQuery);
  }
})(function($) {

  // This yields false
  console.log($ === window.$, $, window.$);

  ("use strict");
  var Slick = window.Slick || {};
```
the $ in slick is at version 3.2.1, and the global jquery I expose is 1.10.x, so when I use `$().slick` in my code `.slick` is not found.

And when using `yarn` to install the package, no error.

**Comment by indapublic** [comment]
@chbdetta I'm using `slick-carousel-browserify` script instead of `slick-carousel`

**Comment by leggomuhgreggo** [comment]
Hey for anyone having trouble I whipped up a demo implementation using slick and webpack, with jquery via the expose-loader [here](https://github.com/leggomuhgreggo/slick-with-webpack).

Hope that's helpful

**Comment by chbdetta** [comment]
@leggomuhgreggo Thanks for the effort! I use `expose-loader` too. But the problem is my project uses a different version of `jquery` from `slick`. That make webpack include two instance of `jquery`. So slick's available in its own version of jquery but not in the project one.

You could reproduce the problem by changing jquery version to 1.x in the demo repo and reinstall all dependency with `npm` ( `yarn` seems to not trigering the problem, dont know why)

**Comment by leggomuhgreggo** [comment]
@chbdetta ahhhh hmmm, I think you're right. I installed with `yarn install --flat` and chose jQuery 1.7.2, and it worked.

**Comment by chbdetta** [comment]
Since not everyone in my team uses yarn, my workaround is to use the CDN distribution instead of npm package so slick won't install it's own jquery. Hope this issue will be fixed because I struggle even locating it.

**Comment by leggomuhgreggo** [comment]
updated in master

**Comment by leggomuhgreggo** [comment]
@chbdetta yeah makes sense

**Comment by mak633** [comment]
Hi. I found solution which works for me:

1. add to `js` file:

        import $ from 'jquery';
        import 'slick-carousel';


2. add to `scss` file:

        $slick-font-path: "/node_modules/slick-carousel/slick/fonts/" !default;
        $slick-font-family: "slick" !default;
        $slick-loader-path: "/node_modules/slick-carousel/slick-carousel/slick/" !default;
        $slick-arrow-color: black !default;
        @import "~slick-carousel/slick/slick.scss"; 
        @import "~slick-carousel/slick/slick-theme.scss";

**Comment by maximeaudy** [comment]
> script-loader did the trick for me:
> 
> ```js
> window.$ = window.jQuery = require('jquery');
> require('script!slick-carousel');
> 
> $(...).slick(...);
> ```

why i should use script! ?
