### ISSUE TITLE
Arrows not working

### ISSUE THREAD

**Issue by kimwild02** [kenwheeler/slick#2293]
> short description of the bug / issue, provide more detail below.
Next arrow is showing but not clickable. Prev arrow not even showing
====================================================================

###### `[  paste your jsfiddle link here  ]`  

Sorry I do not know what I am doing that this is not working in the fiddle. The slider itself works OK .

https://jsfiddle.net/kimwild/a1s5zxe9/3/

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  prev and next arrows to show up and work

====================================================================

#### What is observed behaviour?

...  next arrow shows but not clickable. Prev arrow not showing

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey @kimwild02 looks like your fiddle doesn't have jQuery, and the version of slick.js that you're linking isn't taking somehow. Good luck!
