### ISSUE TITLE
Arrow issue

### ISSUE THREAD

**Issue by kimwild02** [kenwheeler/slick#2295]
Cannot get arrows to show up

====================================================================

###### `[  paste your jsfiddle link here  ]`  

https://jsfiddle.net/kimwild/oq1gLdyu/

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  Prev and next arrows

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- I am linking to your js file (I am having an issue with viewing mine live for some reason) but I get the dots to show up but not the arrows.

Thanks!

**Comment by leggomuhgreggo** [comment]
Arrows are positioned absolutely to the left and right of the slider. If the slider is 100% widh of the window they are hidden outside the window. https://jsfiddle.net/sxed8p8m/

**Comment by kimwild02** [comment]
Thank! How can I get them to be inside the slider?

**Comment by leggomuhgreggo** [comment]
With CSS! `.slick-prev{left:0} .slick-next{right:0}`

**Comment by kimwild02** [comment]
https://jsfiddle.net/kimwild/oq1gLdyu/
Yes I did this and thought it was something else I was missing, but I can only get the next arrow to show up. Thanks for your help!

**Comment by kimwild02** [comment]
Oops, posted the wrong fiddle, this is the one where the next arrow is the only one showing up, prev arrow not showing: 
https://jsfiddle.net/kimwild/pk0j9gum/

**Comment by leggomuhgreggo** [comment]
Add zindex:
`.slick-arrow {z-index:1}`

**Comment by kimwild02** [comment]
Thank you!
