### ISSUE TITLE
adaptiveHeight with rtl, wrong height

### ISSUE THREAD

**Issue by nitsan-inmanage** [kenwheeler/slick#2299]
Trying to use adaptiveHeight in rtl slider, causes the slides to get the wrong height
====================================================================

https://jsfiddle.net/gk88n7h8/1/

====================================================================

the slider gets confused at the animateHeight() function.
_.$slides.eq(_.currentSlide) returns the wrong slide number
therefore one slide gets the height of another slide

====================================================================
chrome Version 50.0.2661.86 (64-bit)
jquery v2.2.3
Version: 1.5.9
it didn't work before

**Comment by mazzaker** [comment]
Here is my solution to a similar problem with rtl:
[Fiddle](https://jsfiddle.net/gk88n7h8/2/l)
rtl on slick seems to change only the way it rotates but not the elements in it to the new direction, so i added a float: right. 
Hope this helps you
