### ISSUE TITLE
Customizing colours and sizes of dots and arrows

### ISSUE THREAD

**Issue by cohix** [kenwheeler/slick#23]
There is no way that I can find to change the colours and sizes of the dots and arrows. If there is, please let me know, otherwise, feature request.

**Comment by PhilJolley** [comment]
I know this is old, but to help those that want to change the exact size of the dot. Follow everything @kenwheeler has said, and change the font-size in the .slick-dots li button:before

I hope this helps someone out there!!

**Comment by diffractometer** [comment]
@PhilJolley just helped me thanks!
