### ISSUE TITLE
Arrows won't show

### ISSUE THREAD

**Issue by skeffonics** [kenwheeler/slick#2300]
> short description of the bug / issue, provide more detail below.

For some reason the Previous and Next arrows will not show no matter what I do. I am using the slider and responsive class. The dots show. My background is white. In css I've tried color, z-indexing, eliminating hiding, etc.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by suture** [comment]
Make sure the arrows aren't white on white background. I think the default color for arrows in the supplied theme is white.
