### ISSUE TITLE
Question on OnChange

### ISSUE THREAD

**Issue by michellomp** [kenwheeler/slick#2301]
I've seen in #891 that  onchange have been added to 1.4 as events but no trace of it in [here](http://kenwheeler.github.io/slick/) 
Is the syntax something like that 
$('.your-element').on('onChange', function(event, slick, currentSlide, nextSlide){
  console.log(nextSlide);
});

**Comment by leggomuhgreggo** [comment]
Check out the events section of the docs. Probably want something like:
```
$('.your-element').on('beforeChange', function(event, slick, currentSlide, nextSlide){
console.log(nextSlide);
});
```

**Comment by michellomp** [comment]
@leggomuhgreggo Thanks for your reponse but in the #891 @kenwheeler  said that he has added OnChange support in 1.4 ( not onBeforeChange or onAfterChange ) as an event. I have seen beforeChange or onAfterChange in the docs but not the OnChange.

**Comment by leggomuhgreggo** [comment]
Ahh intersting, my guess is that onChange got split into those two, but I'm
not positive!

**Comment by michellomp** [comment]
@leggomuhgreggo In  #361 it seems like it is a new settings built after onBeforeChange and onAfterChange
