### ISSUE TITLE
Slider asNavfor  all slides are active 

### ISSUE THREAD

**Issue by danyj** [kenwheeler/slick#2304]
When using one slider as nav for the other , the second slider all alides are active . 

example 

https://jsfiddle.net/0zpL2htj/
check css 

`
.slidernav  slides have opacity:0.2;  and active 1`

**Comment by leggomuhgreggo** [comment]
Looks like only the active slides have slick-active. You might be thinking of slick-current, and if you use centerMode you might also find slick-center useful.

**Comment by danyj** [comment]
current it is , thnx!
