### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Redani** [kenwheeler/slick#2305]
Hi, sorry this is not really a bug but didn't know where to ask these questions:

1- is it possible to hide the navigation arrows and show them only when hover? I know i can tweek it by adding my custom code but i was wondering if it's native

2- and taking about the arrows, is it possible to display then without the slick font? it causes an additional HTTP request!

3- is it possible to add my loader animation with css insted of the .gif?

thanks

**Comment by leggomuhgreggo** [comment]
1. Probably want to use CSS, with hover states on slick-slider
2. Can mod the slick-theme.css or have custom arrows
3. Can also be accomplished by modifying the slick-theme.css
