### ISSUE TITLE
Hide external  slide on centerMode

### ISSUE THREAD

**Issue by KickinAss** [kenwheeler/slick#2308]
Hi,
I don't know if there is an option to do what I am asking for, I could not find  anything.

Using centerMode (like on the examples page http://kenwheeler.github.io/slick/ ), on the sides of the carousel appears a little slice of the other slide. 

There is a way to have only full slide showed?

Thanks
Alex

**Comment by DevMattLindsay** [comment]
Are you making the slider fullscreen? If so you can make the slick-slide width screen width, image width 100% and the other slides are hidden off screen.
