### ISSUE TITLE
Janky scrolling?

### ISSUE THREAD

**Issue by enjmusic** [kenwheeler/slick#2309]
This is less of a bug and more of a question - have you had other reports of janky/jumpy/not-quite-smooth scrolling? When I drag and release a slide or press the arrow, the way the centered slide moves (i'm doing images with no space in between, like a continuous reel navigated one at a time) isn't smooth and instead has some smooth bits and some jumpy bits, which is very jarring to the eye.

**Comment by leggomuhgreggo** [comment]
Hey do you have an example? I'm wondering if it might have to do with other
demands on page load. Mostly it's not to stuttered but another reason might
be if you're running 1.5.9 the default CSS positioning could be left
instead of translate which has performance implications. Hope that helps.

**Comment by enjmusic** [comment]
@leggomuhgreggo I don't think it would be other demands on page load, there's not much else demanding on the page. Where would I change this positioning parameter in the slick files?

**Comment by leggomuhgreggo** [comment]
UseTransform: true I think
