### ISSUE TITLE
Link to slide

### ISSUE THREAD

**Issue by RobertWalter83** [kenwheeler/slick#2310]
I try to have links pointing to individual slides in my slick and I want to understand why one of my solutions works, and the other (that seems more natural to me), doesn't.

I've read through this [feature request](https://github.com/kenwheeler/slick/issues/152) and studied the jsfiddle_s provided, but since I'm new to JS, I had trouble applying them to my use case.

====================================================================

This fiddle shows the behavior I want: http://jsfiddle.net/qa3muqrk/65/

I have links somewhere on my page that have a hash and a "postfix" formatted like this [hash]_[slideNumber]. I need the hash part to scroll to the offset where the slick is at and the slide number to navigate to the slide I want to see. 
I guess this is not the most elegant way to encode this information, but I tried to use a combination of hash and search string to follow the examples [here](http://jsfiddle.net/x6uo6c32/) and [here](http://jsfiddle.net/qa3muqrk/) more closely, but I could just not get it to work with my scrolling logic. Again, JavaScript is all new to me (and I hate it).

For simplicity, the whole "scroll to offset" part is not part of my jsfiddle, but just know it is in the same function I use for navigating to the correct slide.

Now, as you can see in my jsfiddle, I unslick the slick each time a link is clicked and "re-slick" it with the selected slide as "initialSlide". Seems to work fine, but I am really fishing in the dark here and I'm concerned about possible side effects of this whole "unslicking" / "re-slicking".

I wonder why my alternative solution (see as a comment or below), using slickGoTo doesn't work: http://jsfiddle.net/qa3muqrk/66/

I get the error: Uncaught TypeError: slider.slickGoTo is not a function

thanks

**Comment by leggomuhgreggo** [comment]
Hey, thanks for your interest in the slider. We track bugs here. For support stuff check out the gitter or stackoverflow. It's all in the [contribution guildelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

**Comment by RobertWalter83** [comment]
Well, from my understanding it is a bug that I cannot call the method slickGoTo on a slick in the context I'm trying to call it, or is this expected?
