### ISSUE TITLE
pauseOnHover doesn't work

### ISSUE THREAD

**Issue by robbisy** [kenwheeler/slick#2311]
Can't stop  this slick slider on hover click here for [jsfiddle](http://jsfiddle.net/qrL0vor8/84/)

**Comment by leggomuhgreggo** [comment]
Hold your mouse over it until the current animation completes. It pauses.

**Comment by robbisy** [comment]
@leggomuhgreggo  When hold my mouse on the first slide it pauses on the second one.
Is there a way to pause the slide immediately when we're hover it ?

**Comment by leggomuhgreggo** [comment]
Well in this case you're using a hack to get continuous sliding, that relies on the css animation speed being synced with the slide speed. Could use the css prop `animation-play-state: paused`, but you'd have to make sure it syncs right with the pause on hover of the slider, and I'm not sure if that will work exactly right.

**Comment by daslicht** [comment]
Do you modified the source code of slick or is the hack just based on settings ?

**Comment by robbisy** [comment]
@daslicht the hack is just based on settings no modification on source code

**Comment by daslicht** [comment]
thank you !
