### ISSUE TITLE
Click and swipe in mobile

### ISSUE THREAD

**Issue by llos** [kenwheeler/slick#2313]
Hi,

Any ideas of how to jump to next slide in mobile with a single click? I want swipe to keep working as it does, but I want also to let the user use click like this reference: http://mynameis.fr

Thanks!

**Comment by leggomuhgreggo** [comment]
Hey, thanks for your interest in the slider. We track bugs here. For support stuff check out the gitter or stackoverflow. It's all in the [contribution guildelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

Probably want something like on.('click', slickGoTo(yada)) Good luck
