### ISSUE TITLE
Make slider slide to the right when the user is on the last slide instead of sliding left. 

### ISSUE THREAD

**Issue by BryanBarrera** [kenwheeler/slick#2317]
As of now my slider when i click on the right arrow the slide, slides from right to left. Which is what I want. 

But when I am on the last slide I want it to slide left to right to display the first slide. Right now it looks like it has infinite slides. 

====================================================================
Here is how I have my JS set up.

```
function desktopTweet() { 
	$('#tweet-list .tweet-wrapper').slick({
		// slide: '',
		// variableWidth: true,
		// slidesToScroll: -1,
		slidesPerRow: 2,
		rows: 2,
		// autoplay: true,
		// dots: true,
		// infinite: true,
		// speed: 500,
		// fade: true,
		cssEase: 'linear',
		// mobileFirst: true,
		infinite: true,
		prevArrow: "<button class='prev'><i class='fa fa-angle-left' aria-hidden='true'></i></button>",
		nextArrow: "<button class='next'><i class='fa fa-angle-right' aria-hidden='true'></i></button>",
	 
	 

	});

}

```
Any help would be appreciated. Thanks

**Comment by leggomuhgreggo** [comment]
Hey can you make a reduced test case, say in a jsfiddle or codepen?

there's one to fork in the contribution guidelines.

closing pending test case.
