### ISSUE TITLE
Verical images in horizontal slider

### ISSUE THREAD

**Issue by Kubadegi** [kenwheeler/slick#2319]
Hello

Not sure, if this is the right place for a possibly simple question about slick slider.

How can I force my vertical images in my horizontal slider window to fit the screen? I have a set height and width via php for horizontal images and the vertical ones scale accordingly.
Is there some kind of max-height option?

Many thanks

Jakob

**Comment by leggomuhgreggo** [comment]
Hey @Kubadegi This is more of a CSS thing than an issue with the slider.

Might try a background image with `background-size: cover or contain`, or something like this: http://codepen.io/anon/pen/xVNyyg

Also check out the contribution guidelines
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#submitting-issues

Thanks
