### ISSUE TITLE
Linear Movement ?

### ISSUE THREAD

**Issue by daslicht** [kenwheeler/slick#2320]
Hi,
is there a way to animate the Carousel slides linear like this, please? (open in chome):

https://plnkr.co/edit/tkiRH8jpRNH7qFv8FM37?p=preview

**Comment by leggomuhgreggo** [comment]
Its a hack and its a bit buggy but check out #2311

**Comment by daslicht** [comment]
Thank you very much !will this be supported someday officially ? I also use another hacked (by myself) carousel, but it would be nice to have a official supported :) Makes sense for updates etc..

**Comment by IPradyumnaDebnath** [comment]
@daslicht Could you please share your fix

**Comment by IPradyumnaDebnath** [comment]
> Thank you very much !will this be supported someday officially ? I also use another hacked (by myself) carousel, but it would be nice to have a official supported :) Makes sense for updates etc..
@daslicht Could you please share your fix

**Comment by IPradyumnaDebnath** [comment]
@daslicht Could you please share your fix.
