### ISSUE TITLE
Image Resize Problem

### ISSUE THREAD

**Issue by onlyindia** [kenwheeler/slick#2322]
Keeping image size double is first requirement of retina displays. Your plugin doesn't auto resize image for slidesToShow: 5, settings. It force to show only  two slides because actual width and height of image 800 x 400. It should auto resize images to show 5 slides per row.

I tried  variableWidth:true but couldn't achieve what I want.

**Comment by leggomuhgreggo** [comment]
Hey @onlyindia please review the [contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#submitting-issues). Gonna need a fiddle to demo the issue. If I'm understanding you correctly though, you should be able to contain your images with `max-width: 100%`

Closing pending fiddle
