### ISSUE TITLE
animate.css support for slide changing

### ISSUE THREAD

**Issue by bcinternet** [kenwheeler/slick#2325]
Currently slides can only have fade or slide animations.
So, i propose support for animate.css animations - like owl carousel have.

**Comment by leggomuhgreggo** [comment]
Feel free! One of the nice things about Slick is that it's very extensible, and you can certainly tie to whatever animation you'd like.

**Comment by fingerprintweb** [comment]
Animate IN work, but add animation out it is inposible

**Comment by vaneves** [comment]
I tried use animate.css, but not work. I rename to animate2.css, it's work!
