### ISSUE TITLE
Slide item is dropping to the next line 

### ISSUE THREAD

**Issue by romeobleonor** [kenwheeler/slick#2329]
I have 8 slides on my carousel, in Chrome it works perfectly fine, but in IE9, when the browser is resized, one of the slides sometimes drop on the next line, sometimes not (intermittent). Same thing when you click the maximize window using IE9 browser in Windows environment, jquery-migrate-1.2.1.min / v2.1.1, slick 1.4.1, foundation 5.5.2. I don't have codepen or jsbin to show the code, but I can provide the screenshot. 

![image](https://cloud.githubusercontent.com/assets/2036634/15440106/39534cfa-1e99-11e6-90fd-7b290e12a6b0.png)

**Comment by romeobleonor** [comment]
// Load carousel
  $('.js-homepage-carousel').slick({
    prevArrow: '<span type="button" class="carousel-prev"><img src="../landing/images/Arrow-MainArticle-Carousel-Green-L.svg"></span>',
    nextArrow: '<span type="button" class="carousel-next"><img src="../landing/images/Arrow-MainArticle-Carousel-Green-R.svg"></span>',
    dots: true,
    infinite: false,
    mobileFirst: true,
    speed: 900,
    slidesToShow: 1,
    slidesToScroll: 1,
    fullwidth: true,
    responsive: [
      {
        breakpoint: 768,
        settings: {
          fade: true,
          slidesToShow: 1,
          speed: 900
        }
      },
      {
        breakpoint: 1023,
        settings: {
          arrow: false,
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: false,
          dots: true
        }
      },
      {
        breakpoint: 1440,
        settings: {
          arrow: false,
          slidesToShow: 2,
          slidesToScroll: 1,
          infinite: false,
          dots: true
        }
      }
      // You can unslick at a given breakpoint now by adding:
      // settings: "unslick"
      // instead of a settings object
    ]
  });

**Comment by leggomuhgreggo** [comment]
Seems like a CSS issue. Unfortunately, as an issue, it's not ringing any bells and there isn't a whole lot we can offer by way of support without a test case.

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
