### ISSUE TITLE
problem with opening slide alignment when slider is initially hidden

### ISSUE THREAD

**Issue by cbad-mvd** [kenwheeler/slick#2330]
Create a slider initially hidden. After making it visible, the slides are misaligned. This happens when using centerMode for slider. 

====================================================================

###### `[ http://jsfiddle.net/cbadmedia/u5tof6ew/2/  ]`  

====================================================================

#### Steps to reproduce the problem

1.There are two sliders, one is initially hidden. 

2. Click on the text "click to show" to make both sliders visible.

3. Compare the alignment of the two sliders. The one initially hidden is on top and has alignment problems.

4. Note also this exhibits the issues in ticket #2328 where slidesToScroll is ignored in centerMode

====================================================================

#### What is the expected behavior?

Expect the slides to be aligned correctly like when it isn't initially hidden.

====================================================================

#### What is observed behaviour?

please view jsfiddle

====================================================================

**Comment by leggomuhgreggo** [comment]
Hey this is a duplicate. If you search past issues, you'll find more on the subject, but basically display none steps on layout calculations for obvious reasons. I recommend visibility hidden, but you have to use position absolute on subsequent sliders meant to occupy a space. There's also the setPostion method.

Good luck.
