### ISSUE TITLE
variableWidth with only one slide to show?

### ISSUE THREAD

**Issue by Bondra** [kenwheeler/slick#2333]
Hi!

I want to only display one of the slides when using variableWidth. As it is now part of the following slide are visible as well. I think I'm asking for a variable width of the container?

Created a fiddle over here.
http://jsfiddle.net/simeydotme/fmo50w7n/

**Comment by leggomuhgreggo** [comment]
Hmm that fiddle doesn't seem to correspond to the issue you described. Either way it seems like the issue you've described is how variable width is supposed to work. 

My first thought as far as a solution would be to set `.slick-slide:not(.slick-current){visibility: hidden}`

I'm going to close, but if you think I've overlooked something feel free to holler back. Thanks.

**Comment by Bondra** [comment]
Thanks for your answer! It kind of did what I wanted. Well at least it didn't displayed decendents Though, clicking next slide the one that recently was "current" just dissapear. Looks more like a bug so to say.

Here's with your code:
http://jsfiddle.net/fmo50w7n/399/

Here's without:
http://jsfiddle.net/fmo50w7n/400

**Comment by leggomuhgreggo** [comment]
Can you clarify what isn't working as intended? I'm curious what the use case is for using variable width with a single slide, and not wanting to see other slides; seems like it's the same as non-variable width single slideToShow at that point.
