### ISSUE TITLE
delay when changing speed with slickSetOption

### ISSUE THREAD

**Issue by b0rt** [kenwheeler/slick#2334]
when calling .slick('slickSetOption', 'speed', $otherspeed, false);
there is a huge delay until the new Option is being used.

====================================================================

###### `[  https://jsfiddle.net/b0r7/tdfo1z0f/  ]`  

[Fiddle Link](https://jsfiddle.net/b0r7/tdfo1z0f/)

====================================================================

#### Steps to reproduce the problem

1. call .slick('slickSetOption', 'speed', $otherspeed, false);

where $otherspeed is a different speed than the original configured speed

====================================================================

#### What is the expected behaviour?

After calling slickSetOption have the new parameter be applied (almost) instantly

====================================================================

#### What is observed behaviour?

Huge Delay
![slick-js-faster-deley](https://cloud.githubusercontent.com/assets/122098/15549484/0792ff0e-22ad-11e6-80a0-20fd0491f4a0.gif)

====================================================================

##### Which browsers/versions does it happen on?

- Chromium Version 49.0.2598.0 (64-bit)

- PaleMoon Version: 26.2.2 (x64)

- Firefox Developer Edition 48.0a2 (2016-05-24)

##### Which jQuery/Slick version are you using?
latest (as of 2016-05-24)

**Comment by leggomuhgreggo** [comment]
Hey @b0rt thanks for making the issue. Correct me if I'm mistaken, but it seems like the delay just the time remaining on the transition of the current slide. Unfortunately, the library's support for linear continuous scrolling is not well developed, so there's no existing support for it. I wish you luck in trying to hack a solution together!
