### ISSUE TITLE
Full width slider, how to move arrows toward middle of screen?

### ISSUE THREAD

**Issue by Jakobud** [kenwheeler/slick#2336]
I have a full width slider. It stretches across the entire browser.

My arrows, I don't want them to be on the far left and right side of the slider. I need them closer to the middle, at a maximum of 1000px distance between them, centered.

Doing this is easy: make an absolutely positioned div (that sits next to the slider in the DOM), that contains the arrows. Center it and add a `max-width: 1000px;` to it. Perfect, now the arrows are where I need them.

BUT, the problem is now that this absolutely positioned div is on top of my slider. I cannot click through it to click content on the slider or drag to the next slide.

Is there a clear solution for how to accomplish this?

**Comment by leggomuhgreggo** [comment]
Well definitely skip the div. Center the arrows horizontally with an offset of half 1000px in the arrow's respective direction.

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by Jakobud** [comment]
Sorry, I'm redirecting this support request to https://www.reddit.com/r/slickcarousel/comments/4l7gbv/center_arrows_in_full_width_slider/. Still some questions about this regarding doing this in a responsive/fluid layout.

**Comment by Jakobud** [comment]
Any chance for some more support on this topic?

https://www.reddit.com/r/slickcarousel/comments/4l7gbv/center_arrows_in_full_width_slider/

**Comment by Jakobud** [comment]
Nevermind I finally figured it out.

**Comment by Dean-Wilson** [comment]
Good job. Thanks for sharing :|

**Comment by Jakobud** [comment]
@Dean-Wilson It was @leggomuhgreggo's suggestion that I used.
