### ISSUE TITLE
when using asNavFor or pagination main slider doesnt update if fade/slide isnt finished.

### ISSUE THREAD

**Issue by nickfmc** [kenwheeler/slick#2337]
====================================================================
If I have two sliders one main slider and one thumbnail slider say and I use asNavFor , everything works fine unless I click on one of the thumbnails and then quickly click another one, the thumbnail slider will update to the correct slide but the main slider it is controlling does NOT change . I slowed down the fade in the fiddle to emphasize the issue.

https://jsfiddle.net/qxyh0jp6/3/

- Click on one of the thumbnails 
- Click on another thumbnail quickly before the main slide has finished fading.

====================================================================
Note this also happens when using the pagination method, which can be seen in this fiddle
http://jsfiddle.net/Virtual/webyrb9d/

**Comment by leggomuhgreggo** [comment]
Hey @nickfmc interesting! I think you're right that this is not ideal, but I don't know how much support we can expect for a fix in the near term. Happens with dots too. I'll add it as an enhancement to consider, and perhaps it will be attended to in v2.

**Comment by nickfmc** [comment]
ya, I always crank up the speed as a workaround when using asNavFor but again not ideal when you want to have a slower transition.

**Comment by leggomuhgreggo** [comment]
Agreed. I'll definitely leave it open so we don't lose track of it. Thanks man.

**Comment by mazzaker** [comment]
Try out this fiddle:
[Fiddle](https://jsfiddle.net/qxyh0jp6/5/)

waitForAnimate: false,

Is this what you want?

**Comment by nickfmc** [comment]
Awesome @mazzaker exactly the problem I was having, updated my production sites.  Working like a charm, haha it was right there the whole time, Thanks!

**Comment by leggomuhgreggo** [comment]
YES @mazzaker, hell yes.
