### ISSUE TITLE
Is it possible to have two synced sliders with different 'slideToScroll' values?

### ISSUE THREAD

**Issue by balintd** [kenwheeler/slick#2342]
I have two sliders that are synced. The primary only shows one image, the secondary acts as a navigation and shows 5 thumbnails.

What I'd like to achieve is that when the user uses the arrows of the primary slider it shows the next one, but when the secondary slider arrows are used, then that would show the next 5 images.

Is this possible in any way with Slick.js?

Thank you.

**Comment by leggomuhgreggo** [comment]
I feel odd linking you to an example with a bug, but [this has a codepen that's pretty close to what you're describing](https://github.com/kenwheeler/slick/issues/2244). Bug is with non-infinite, so as long as you're cool with the slides being infinite it should work.

**Comment by balintd** [comment]
Thank you!
