### ISSUE TITLE
Question about slide navigation

### ISSUE THREAD

**Issue by mrky007** [kenwheeler/slick#2344]
I managed to style my slide navigation with using:
$('.next-button-slick').click(function(){
$('.accmd-slides').slick("slickNext");
});
 $('.prev-button-slick').click(function(){
  $('.accmd-slides').slick("slickPrev");
});

The idea is to customize the navigation using Font Awesome icons, but is there a way for me to disable / change the styling of navigation arrows is there is no Next or Previous slide in the slider?

Thank you for helping me out

**Comment by leggomuhgreggo** [comment]
[Try `prevArrow` & `nextArrow`](https://github.com/kenwheeler/slick#settings)
