### ISSUE TITLE
Mouse hover issue

### ISSUE THREAD

**Issue by nilesh-patil-pune** [kenwheeler/slick#2345]
When I set  speed: 1000,  pauseOnHover working fine but as soon as in set speed: 10000, then pauseOnHover will not work immediately it works after few seconds.

**Comment by nilesh-patil-pune** [comment]
$('#featured_credits').slick({
	  infinite: true,
	  arrows: true,
	  slidesToShow: 4,
	  slidesToScroll: 4,
      autoplay: true,
      autoplaySpeed: 0,
	  speed: 10000,
	  cssEase: 'linear',
      pauseOnHover: true,
      pauseOnFocus: true,
      focusOnSelect: true,
      accessibility: false,
      mobileFirst: true

    });

**Comment by nilesh-patil-pune** [comment]
https://jsfiddle.net/fmo50w7n/415/

**Comment by leggomuhgreggo** [comment]
See #2311
