### ISSUE TITLE
Autoplay <video> not working when inside slick slider

### ISSUE THREAD

**Issue by TartufoDAlba** [kenwheeler/slick#2347]
> autoplay videos not working when inside of slick slider.

====================================================================

 https://jsfiddle.net/TartufoDAlba/wr6vLw4s/

(example video thumbs may take extra time to load)

====================================================================

#### Steps to reproduce the problem

1. When using < video > tags with autoplay set inside of slick slider.

====================================================================

#### What is the expected behaviour?

Videos should autoplay on site load and loop.

====================================================================

#### What is observed behaviour?

Videos appear to be frozen, after a few slides a few seconds of the video plays then goes back to initial thumb.

**Comment by mazzaker** [comment]
[Fiddle](https://jsfiddle.net/5sa2k2ao/1/)

Starting the videos after init seems ok, but still the issue with the infinity loop when getting to the first element again...

**Comment by TartufoDAlba** [comment]
I think I'll be able to take it from here. Thank you for the help!
