### ISSUE TITLE
Freescroll

### ISSUE THREAD

**Issue by ghosydneyben** [kenwheeler/slick#2349]
Just a quick one, best slider I have used to date. However, I've been asked for one last request from my boss.

Is there a way to freescroll on a slider? without it bouncing back on to the current slide? This would be awesome for mobile, I'm using this as a navigation for another slider.

Heres my code for the slider

 $('.slider-nav').slick({
    slidesToShow: 1,
    slidesToScroll: -1,
    infinite: false,
    autoplay:false,
    variableWidth: true,
    touchMove: true,
    centerMode: true,
    focusOnSelect: true,
    touchThreshold: 0,
    mobileFirst: true,
    slide: '.slider-nav li',
    swipeToSlide: false,
    asNavFor: '.super-product-inner',
    useTransform: true,
    arrows: false,
});

**Comment by leggomuhgreggo** [comment]
Hey @ghosydneyben [I think this is what you're looking for](https://github.com/kenwheeler/slick/issues/553)

Hope that helps.
