### ISSUE TITLE
Vertical mode isn't working with responsive slider

### ISSUE THREAD

**Issue by justinbhayes** [kenwheeler/slick#2350]
After applying vertical true to my smallest breakpoint for my responsive slider, the slides don't move vertically.  

====================================================================

Slider is located at the bottom of this page: http://qa.hhglobal.threedeephost.com/category/creative (use 0-479 as your browser width)  

====================================================================

#### What is the expected behaviour?
Slides should stack and transition vertically between 0-479 browser width.

====================================================================

#### What is observed behaviour?
Slides transition right to left between 0-479 browser width.

====================================================================

#### More Details
- Which browsers/versions does it happen on?
- Latest Chrome, FF and Edge
- Which jQuery/Slick version are you using?
- The lates
- Did this work before?
- Yes

**Comment by leggomuhgreggo** [comment]
Hey @justinbhayes thanks for creating the issue. Can you [reproduce in a reduced test case](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) like a jsfiddle or a codepen? Crucial for debugging. Thanks!

Closing pending test case.

**Comment by justinbhayes** [comment]
Thanks for following up with me. Due to the poor UX of vertical scrolling, especially on a mobile phone, I was able to convince the client to use horizontal scrolling for all breakpoints. :) You can close this ticket.
