### ISSUE TITLE
Align Images vertical Centered ?

### ISSUE THREAD

**Issue by daslicht** [kenwheeler/slick#2351]
Hi,
is it possible to vertical align center images please?

see: 
http://jsfiddle.net/daslicht/bc5Lummt/

alignment should be like this:

http://jsbin.com/lovona/edit?html,css,js,output

**Comment by apetrakow** [comment]
you can vertical-align the slides, when you disable the floats and assign `display:inline-block;` to them.

Just add this one:

    
	.slick-slide.c {
		display: inline-block;
		vertical-align: middle;
		float:none;
	}

**Comment by daslicht** [comment]
Thank you very much !

**Comment by keshavk2910** [comment]
Thank you very much

**Comment by sanishashrestha** [comment]
ありがとうございます
