### ISSUE TITLE
How to get direction of slide change?

### ISSUE THREAD

**Issue by Skinwalker** [kenwheeler/slick#2352]
Im trying to get the direction of the slide change via beforeChange Event.

When I try to get the value from
**slick.direction**
or
**slick.currentDirection**
the value doesn't change when i click the slick arrows - currentDirection changes when i change the slide via touchmove.

Is this a bug? Or does anybody knows a better way to get the direction?

On the change i wanna add a class to the current and the prev / next slide for a custom effect.

Heres a Pen where you can see the issue on the console output ...
[http://codepen.io/anon/pen/qNdqLL](http://codepen.io/anon/pen/qNdqLL)

**Comment by leggomuhgreggo** [comment]
Hey @Skinwalker. Those keys are only used for swipe and if infinite is false and autoplay is true--I can see how it's a little confusing. The only way I know of is to compare the value of the previous slide to the next slide, with special attention paid to infinite transitions. Hope that helps!

**Comment by howtomake** [comment]
hey @Skinwalker look at this solution http://codepen.io/howtomake/pen/RVReKa
