### ISSUE TITLE
Only first slide works, after that slick stops working

### ISSUE THREAD

**Issue by valnub** [kenwheeler/slick#2353]
I applied slick on this DOM:

![bildschirmfoto 2016-06-04 um 00 25 23](https://cloud.githubusercontent.com/assets/3787662/15794453/188d9284-29eb-11e6-84ca-b27b48520a01.png)

Then, I call this:

```javascript
$('.hse-carousel.swiper-container .swiper-wrapper').slick({
  infinite: true
});
```

And the DOM changes to this:

![bildschirmfoto 2016-06-04 um 00 26 04](https://cloud.githubusercontent.com/assets/3787662/15794466/26fe1366-29eb-11e6-8260-885f940e7cef.png)

Then, I open the website on Google Chrome (OS X) and drag one of the slides from right to left. That works. But after that I cannot slide anymore. I can't even go back to the first slide. It's completely stuck! It's just as if slick suddenly stops working.

What's wrong?

**Comment by leggomuhgreggo** [comment]
Can you recreate in a test case?

https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

closing pending test cae

**Comment by valnub** [comment]
Hi, thanks for your reply. It's very hard for me to reduce the page to a fiddle since it's a major enterprise website. So, I tried to strip off as much as I could and uploaded a testpage here where the issue can be reproduced (all js files are not uglified):

http://www.timo-ernst.net/misc/files/tmp/hsetest/pages/home.html

Would this be ok?

**Comment by leggomuhgreggo** [comment]
Nah, something like a jsfiddle or codepen. There's a fiddle in the contribution guidelines you can fork to recreate the slick option set you're having trouble with.

**Comment by valnub** [comment]
Actually I didn't set any options at all =/

**Comment by leggomuhgreggo** [comment]
Ah, well then it's almost certainly something to do with your local environment. Good luck!

**Comment by valnub** [comment]
For anyone who's interested in the solution or may have the same issue:

After stripping down the code piece by piece to create a fiddle I found that I had overwritten the setInterval and setTimeout functions for debugging purposes:

```javascript
setInterval = function () {console.log("setInterval called")};
setTimeout = function () {console.log("setTimeout called")};
```

That's why Slick stopped working. Silly me. Sorry for taking your time.
