### ISSUE TITLE
Remove padding item when using centerMode

### ISSUE THREAD

**Issue by PhucPM** [kenwheeler/slick#2354]
Hi
I am having a problem is when choices centerMode the left and right of it is part of another item. I do not want that to happen.

You can view it here: [http://i.imgur.com/wrhtvr8.png](url)

====================================================================
Code it here
###### https://jsfiddle.net/7jqLctzu/ [](url) 

====================================================================

**Comment by leggomuhgreggo** [comment]
https://jsfiddle.net/qnwuxe6t/

`centerPadding: 0`
