### ISSUE TITLE
customization navigation arrow

### ISSUE THREAD

**Issue by sufiiiyan** [kenwheeler/slick#2357]
Can we apply our own css to the navigation arrows? To apply different colors and styles.

**Comment by leggomuhgreggo** [comment]
Sure can!

**Comment by sufiiiyan** [comment]
i want to use HTML content with navigation buttons

<div class="your-class">
  <div>your content</div>
  <div>your content</div>
  <div>your content</div>
</div>

<button class="slick-prev slick-arrow" role="button" aria-label="Previous">Previous</button>
<button class="slick-next slick-arrow" role="button" aria-label="Next">Next</button>
