### ISSUE TITLE
Possible Fade for CenterMode?

### ISSUE THREAD

**Issue by tenq** [kenwheeler/slick#2362]
Hi, (excuse the poor English)

I do not know if it's a problem or if you do not understand the documentation in relation to fade.

When I use centerMode to show specific services on my site when going to the next slide, the transition breaks the layout as move the items. I need to do as in situation B in the image below: Always Show 3 slides, and they change with fade only, not scroll, it is possible?

[http://mopadvogados.com.br/2016/images/slick-slide-solution.jpg](url)

I tried use 
```
$('#list-casos').on('beforeChange', function(event, slick, currentSlide, nextSlide){
  $('#list-casos [data-slick-index="' + (nextSlide + 1) + '"]').fadeTo('fast',0);
});
```

but more than one slide has faded...

====================================================================
Original idea is in:
[https://jsfiddle.net/k14e5bgu/](url)

**Comment by leggomuhgreggo** [comment]
You can add transition or animation properties to your CSS that will accomplish what you want.
