### ISSUE TITLE
Default arrow color is white

### ISSUE THREAD

**Issue by JeffMatthews2** [kenwheeler/slick#2363]
> short description of the bug / issue, provide more detail below.

Ha ha!  It seems almost a cruel joke.  I spent a good few hours thinking I couldn't get slick to work.  The arrows were white on a white background.

I recommend changing the default arrow color to something which is likely to be conspicuous.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Not a bad idea. Feel free to make a PR :smile:

**Comment by SevenCash** [comment]
.slick-prev:before,
.slick-next:before {
  color: black;
}

does't work for me, no matter I change the color, it always white...
