### ISSUE TITLE
A way to center multiple slides with margins

### ISSUE THREAD

**Issue by spencero91** [kenwheeler/slick#2364]
> There seems to be no way to center a responsive _n_ number of slides on a page and have them then transition 1 - _n_ slides off the side of the screen. Instead the slides just get cut off at your margin or they display too many slides at a time.

For more clarity and explanation I posted this stackoverflow question:

[http://stackoverflow.com/q/37311066/4059832]

====================================================================

Here is the jsfiddle I was supposed to reproduce the issue with:
[http://jsfiddle.net/ynjLy7k9/1/]

Here is a messy hack fix of what I kind of want the issue fixed with:
[https://jsfiddle.net/j6qwasoa/]  

====================================================================

#### Steps to reproduce the problem

1. Have a margin on the content of your page (just as every page that isn't fullscreen has)
2. Wish that you had that your slides could slide through that margin
3. Wish that you could center a responsive number of slides in that margin
4. Wish that your slides didn't get cut off at the margin line as they moved
5. Be disappointed as your centered multiple slide quickly disappear before reaching the side of the viewport

====================================================================

#### What is the expected behaviour?

...  Slides should during a transition should move all the way to the edge of the page while maintaining the proper content margin while stationary.

====================================================================

#### What is observed behaviour?

...  Slides during a transition move to the margin and disappear midscreen if while stationary they maintain the proper content margin.

====================================================================

#### More Details

- Which browsers/versions does it happen on? ALL
- Which jQuery/Slick version are you using? Latest
- Did this work before? Nope

**Comment by leggomuhgreggo** [comment]
Don't think anyone is opposed to adding an option for this, but [you can use CSS to accomplish](http://codepen.io/leggomuhgreggo/pen/YWqEYB?editors=1100) what you're talking about, so it's not a huge priority. Feel free to make a PR if you're interested.

**Comment by spencero91** [comment]
The only way to "accomplish" this currently with css is just make your site look stupid cutting off mid-page. Or use transitions on margins which is a terribly intensive cpu process that is sluggish and poor.

This feature missing is a blaring visual bug.

**Comment by spencero91** [comment]
Most current sites including this one use large margins.....
`          Page Width
_______________________
|        |                          |        |
|        |     content         |        |
|        |          width        |        |
|        |                          |        |
|        |                          |        |
|        |                          |        |
`
Slick slider can either fill the entire width of the page and have slides slide off the page or it can fill just the content width as it should, but slides simply disappear as they hit an invisible border or the content width.

They need to fit within the content width when stationary and slide all the way out of the viewport when they move.

**Comment by leggomuhgreggo** [comment]
[Updated the codepen](http://codepen.io/leggomuhgreggo/pen/YWqEYB?editors=0100)-that more what you were aiming for?

**Comment by spencero91** [comment]
That's basically what I did in my messy hack fix that I posted originally... but this doesn't allow for responsive design... It always displays 4 slides at a time. Specifically in my example using bootstrap breakpoints for responsiveness I wanted to display 4 at lg, 3 at md, 2 at sm, and 1 at xs...

**Comment by spencero91** [comment]
I modified your [codepen](http://codepen.io/spenceroreilly/pen/XKdEpa)to be almost exactly what I am looking for, but it is glitchy at best and using a margin transition is not perfomance friendly.
