### ISSUE TITLE
Bug with infinite scroll and clicking a slide to become active

### ISSUE THREAD

**Issue by vk011** [kenwheeler/slick#2367]
I want to click a slide and then to make that slide active, but for some reason it does not work with infinite scroll and when clicking the first visible slide on the left (it has number 9 in it in the fiddle).

If you click any other slide it works, but if you click the first from the left it does not. Why and how to remedy this?

====================================================================

#### fiddle

https://jsfiddle.net/0zkbvju6/2/

====================================================================

#### Steps to reproduce the problem

1. Cick slide with 9 in it, nothing happens. Click any other slide, works as expected.

====================================================================

#### What is the expected behaviour?

The clicked slide should become active.

====================================================================

#### What is observed behaviour?

The first from left does not work when clicked.

====================================================================

#### More Details

Slick version 1.6.0

**Comment by leggomuhgreggo** [comment]
`focusOnSelect: true`
