### ISSUE TITLE
Using Slick in Angular 2 SPA

### ISSUE THREAD

**Issue by padjodev** [kenwheeler/slick#2368]
Not sure if anyone has used the slider in an ng2 app yet but Im noticing that it works fine when you visit the page first but then on any subsequent visits the slider go a lot faster than they should

**Comment by VishalGulati** [comment]
Have you found out how to do it? I am also stuck with it. Any help shall be highly appreciated.

**Comment by REPTILEHAUS** [comment]
Yeah I couldnt get it to work with slick but I used Owl Carousel and it works pretty good.

**Comment by Disorrder** [comment]
@REPTILEHAUS lol thanks! Looks fine :)
