### ISSUE TITLE
svg icons inside slick are not visible in IE11

### ISSUE THREAD

**Issue by ROBsoer** [kenwheeler/slick#2371]
after slick initialization svg icons inside become invisible in IE11 browser
Other icons outside of slick still be visible.
svg-icon use via `<symbol>` sprite and include via `<use>` tag

[structure of my document](https://jsfiddle.net/xbzma8wu/)

**Comment by jasonalvis** [comment]
I'm facing the same problem, when I comment out position: relative on the slide-track the svg displays. Not sure if its a bug with slick or IE11.

Thanks,
Jason

**Comment by leggomuhgreggo** [comment]
Im on a mac right now, would one of you guys be willing to see if [this stackoverflow](http://stackoverflow.com/questions/27494296/svg-not-showing-in-ie11) suggestion works?

Thanks

**Comment by ROBsoer** [comment]
Doesn't work, i've tried different values of `http-equiv="X-UA-Compatible"`

**Comment by ROBsoer** [comment]
largo.siteimage.com.ua - site in our test server when you can play this situation
http://take.ms/WPve4 - screenshot where showed situation

**Comment by jasonalvis** [comment]
I've been debugging the issue and narrowed it down to the inline style for .slide-track, transform. Its doesn't seem to like either transform: translate or translate3d.

If you comment this style out it displays as normal. Obviously this isn't a solution as it requires this to move the carousel.

**Comment by leggomuhgreggo** [comment]
Interesting. As a workaround you could turn `useTrasform` to `false`, which uses left instead of transform

**Comment by jasonalvis** [comment]
Thanks for the tip, I just tried it however and its not resolved it, maybe its a couple of things causing it not to display very strange

**Comment by ROBsoer** [comment]
turning off transform didn't change situation

**Comment by holodoc** [comment]
SVG images require a `viewBox` attribute in order to maintain proportions which is essentially the reason why they are not properly displayed in Internet Explorer. Exporting an .svg either through Illustrator or Inkscape makes sure the files contain an appropriately calculated `viewBox` attribute.

In case Illustrator or Inkscape are not an option there is an excellent article on css-tricks.com explaining how to calculate and add a `viewBox` attribute.

https://css-tricks.com/scale-svg/

**Comment by ROBsoer** [comment]
@holodoc  when svg-sprite is builded via `<symbol>` attribute `viewBox` is set there, and `<svg>` doesn't require it [css-tricks](https://css-tricks.com/svg-symbol-good-choice-icons/)

But I checked your advice on practice. Didn't help, sadly.

I think key is in DOM rebuid and page re-rendering which **slick** started. Because icons disappear after this

**Comment by ROBsoer** [comment]
@quarkus I noticed that IE shows your svg correct after second and more reloadings. But when I've cleared cache your svg dessapeared in carousel

**Comment by quarkus** [comment]
@ROBsoer: my pen/sprite still uses the non symbol syntax of svgstore .. so i have a viewbox and no symbols. (althoug i have the symbol version in production and i am facing the same issues)
For me the behavoiur was pretty unpredictable .. sometimes the svgs showed up during slide changeing or while dragging but would dissapear once the transition was complete. 
I really couldn´t make out why this happens .. the "just transformed" box worked in all occasions ... and i couldn´t force the ie to redraw theses boxes ...

**Comment by leggomuhgreggo** [comment]
Appreciate the investigative work @quarkus and @ROBsoer. This feels more like a browser issue than an issue with slick, but if I'm missing something or if there are other sliders that handle SVGs better, please holler back and I will happily reopen. Thanks!

**Comment by stoykostanchev** [comment]
http://stackoverflow.com/questions/33040911/svg-icons-dissapears-in-windows-10-ie-11-using-jquery-sortable

This was related and is about to solve the problem for me, will juts need to hook accordingly.

**Comment by leggomuhgreggo** [comment]
Thanks @stoykostanchev
