### ISSUE TITLE
Any way to hide extra thumbnails when centerMode = true?

### ISSUE THREAD

**Issue by absalone** [kenwheeler/slick#2373]
Hi there, 

I'm willing to hide extra thumbnails that are shown when centerMode is set to true. 
You can see how it is at the moment on my website: (http://cezanne01.businesscatalyst.com/photographs.html)

I would prefer having only full sized thumbnails and no extra cropped ones. I could use centerMode: false, but the problem is that it doesn't allow you to scroll back as the selected thumbnail will jump on the left side as soon as it is selected.

I'm not sure that's possible, I've been trying different settings, but haven't found anything really.
Do you have any suggestion?
Thanks,
Matt

**Comment by simeydotme** [comment]
try `centerPadding` :)
