### ISSUE TITLE
whitespaces created when scroll automically

### ISSUE THREAD

**Issue by Ariex** [kenwheeler/slick#2374]
When one round finished, there are white gaps appears in the carousel container

i have created a demo for this issue: http://codepen.io/Ariex/pen/MejVva

when the 2nd red rect align to the blur rect (demo panel viewport width: 1506px), the gaps appears.

I think the problem is the plugin detected that one around finished and reset the position of elements for next around, but somehow create white gaps.

also gaps appear when the container is longer than contents.

**Comment by leggomuhgreggo** [comment]
[Tracking issue](https://github.com/kenwheeler/slick/issues/1207)
