### ISSUE TITLE
Jumping-bug transitioning from last to first

### ISSUE THREAD

**Issue by paleite** [kenwheeler/slick#2375]
There's a jumping-bug when transitioning from last to first item in an infinite slider
https://jsfiddle.net/paleite/s5uguo9s/

#### Steps to reproduce the problem

Click on next item, until you're back at the first item again.

====================================================================

#### What is the expected behaviour?

The same transition as everywhere else

====================================================================

#### What is observed behaviour?

Once you go from first to first, there's no initial transition, but then there is, causing the slider to jump

====================================================================

#### More Details

- Which browsers/versions does it happen on?
 - Chrome 51 Mac
- Which jQuery/Slick version are you using?
 - Slick 1.6
 - jQuery edge
- Did this work before?
 - Can't tell

**Comment by paleite** [comment]
@leggomuhgreggo Hey, could I kindly ask you to point me to the duplicate? Thank you :)

**Comment by leggomuhgreggo** [comment]
[Sure, here ya go](https://github.com/kenwheeler/slick/issues/1892)
