### ISSUE TITLE
Using slick inside of a flexbox element causes slick to grow exponentially

### ISSUE THREAD

**Issue by DerekFoulk** [kenwheeler/slick#2378]
If you initialize a slick carousel inside of a flexbox element, then the slick carousel increases it's width exponentially. The carousel ends up being extremely wide!

I know that flexbox is not quite ready for production, but Bootstrap 4 is shipping with the option to enable flexbox framework-wide. If this is something easy to fix, then perhaps it would be worthwhile to do so for us early adopters of Bootstrap 4 :)

====================================================================

###### http://jsfiddle.net/derekfoulk/x3Luhwqm/1/

====================================================================

#### Steps to reproduce the problem

1. Wrap your carousel element with an element
2. Set `display: flex;` on that element

====================================================================

#### What is the expected behaviour?

I expected the slick carousel to stay @ 100% width of the flexbox element.

====================================================================

#### What is observed behaviour?

The slider starts out much wider than the parent (flexbox) element, and continues to grow wider after each iteration of the carousel.

====================================================================

#### More Details

- I have verified this behavior on current & recent versions of Chrome, Firefox & Edge
- Using slick v1.6.0
- I'm unsure if this has worked as intended with previous versions of slick

**Comment by DerekFoulk** [comment]
Sounds like my issue is related to #1195.

**Comment by leggomuhgreggo** [comment]
I've been meaning on reading the [flex spec](https://www.w3.org/TR/2016/CR-css-flexbox-1-20160526/) at some point to learn the ins and outs of whats happening, but long story short, it looks like you need to a defined width somewhere in the parent heirarchy for normal dimention calculations. 

[Here's a non-slick example](http://codepen.io/leggomuhgreggo/pen/MejdKX) to illustrate what I mean. 

[Here's a fork of your fiddle](http://jsfiddle.net/neog86j4/1/) using the same principle.

Hope that helps.

**Comment by DerekFoulk** [comment]
Thanks for the info regarding this. I didn't realize flexbox inherited dims like tables. Our sliders are now looking great after adding `width: 100%;` to their container!

**Comment by leggomuhgreggo** [comment]
Glad to hear it!

**Comment by ShaggyDude** [comment]
I've been annoyed having to add 100% to my flexbox stuff. Now I understand why...

**Comment by artuska** [comment]
The same problem appears in `dispaly: table-cell` parent.

**Comment by darylknight** [comment]
This doesn't fix the issue for me - adding a container around it with `width: 100%` still makes `.slick` 168000px wide

**Comment by FloSugar** [comment]
Had the same problem, `align-items: center;` was causing the issue.

**Comment by alamowo** [comment]
So for me, I only have my flex container set to `display: flex;`. Inside there are two elements. Both only have the flex property. One is set to `flex: 1;`, which is the slider, and one has `flex: 0;`. With this setup the issue mentioned above occurred.
## Solution
For adding `overflow: hidden;` to the slider element (which gets the `slick-initialized slick-slider` classes) fixed the problem.
When I disable the property and use the slider, it happens again. When I activate it again, slick recalculates the correct width on the next interaction.

**Comment by CRYX2** [comment]
Adding:`flex-direction: column;` to container fixed for me

**Comment by anrananran** [comment]
@alamowo , In fact, "overflow:hidden;" add to the "flex:1" div fixed this bug In my case.

**Comment by lstanard** [comment]
@CRYX2 `flex-direction: column;` solved the issue for me in Chrome, but not Firefox (57.0.4 as of writing this).

**Comment by roberthenniger** [comment]
Had the same problem when slick was used in flexbox with justify-content:stretch. `overflow:hidden` solved it for me. I hope there are no side issues with that solution. Is this a bug in the size calculation of slick or a flexbox issue?

**Comment by monkemedia** [comment]
.slick-slider {
width: 100%
max-width: 720px // The widest it will go on a responsive website
}

Hope this helps

**Comment by optima-ben** [comment]
Any definitive answer on this?

**Comment by roberthenniger** [comment]
@optima-ben I was fixing it through adding overflow:hidden to all of the parent flex containers. Of course that also has some side effects like abosulte positioned elements which overlap do get cropped. But with this i can deal in the future.

**Comment by Oleksandr07** [comment]
for flexbox is solved by adding to the parent element { min-width: 0; }

**Comment by GaegeRoot** [comment]
I had similar problem:

Flex container with three children. Two end children were fixed width (nav for slider), center was `flex: 1`.

Attempting to slickify it blew it up.

Took @alamowo's suggestion and `overflow: hidden` on the slider container (middle div of my flex container) worked brilliantly.

So looking forward to moving away from slick slider soon..... 😏

**Comment by elky** [comment]
Adding `width: 100vw;` to a slider parent helped to me.

**Comment by Tanmccuin** [comment]
Here's the fix for anyone still looking 
https://github.com/kenwheeler/slick/issues/982#issuecomment-73517458

**Comment by Renrhaf** [comment]
This is still a very big issue for any design that implements flexbox from top element (body).

**Comment by MColl92** [comment]
Hey guys, just lost a day to this bug. Could it be added to documentation somewhere?

**Comment by animalonthedrum** [comment]
Making .slick-list display flex fixed my issue

**Comment by ahmadina** [comment]
WTF!!!!!

**Comment by esaulfarfan** [comment]
In case it helps someone else, I found out (after 1 day of tests and research) this is a problem with **flex** and not with **Slick**. 
Using `display: flex;` sets `flex-direction: row;` as default, but row is to organize items horizontally and with this Slick can't find the container's width.
Using `display: flex;` and setting `flex-direction: column;` solves the problem by organizing items vertically, so Slick can now find the container's width and adapt to it.
I'm attaching 3 little screenshots :)

![01](https://user-images.githubusercontent.com/37102622/76835979-a6b8d180-67f5-11ea-94b6-c8bad42a31d6.jpg)
![02](https://user-images.githubusercontent.com/37102622/76835981-a6b8d180-67f5-11ea-888d-8e7c5a00f8dc.jpg)
![03](https://user-images.githubusercontent.com/37102622/76835982-a7516800-67f5-11ea-8a83-94f15bf92217.jpg)

**Comment by sergiohardov** [comment]
Hi all, on first, sorry for my bad english. I fought with the slick slider bug in safari - when the slides are shifted out of the visible area, the reason for the incorrect rendering of the width. Centering did not work. In my case, the value helped me: centerPadding: 1, in the * .js file

**Comment by narendrapandey999** [comment]
> @alamowo , In fact, "overflow:hidden;" add to the "flex:1" div (not the "slick-slider" div) fixed this bug In my case.

thanks, that worked for me.

**Comment by NathaEEUD** [comment]
> Here's the fix for anyone still looking
> [#982 (comment)](https://github.com/kenwheeler/slick/issues/982#issuecomment-73517458)

This fix works for me!
```
* {
    min-width: 0;
    min-height: 0;
}
```

**Comment by mshahzaib101** [comment]
adding maxWidth works for me 
`  display: "flex",
                  flexDirection: "column",
                  width: "100%",
                  maxWidth: 500,`

**Comment by Felipelpk** [comment]
I found a solution, wrapping the Slider component by a flex and setting a max-width for it.

Example

`<Flex max-width="500px">
<Slider {...setings}>
</Slider>
</Flex>`

**Comment by arnofly** [comment]
I fixed this issue with `min-width: 0`, but that works also with `overflow: hidden`. In all cases, you need to apply the style on all hierarchy (every parents, but not slider's children), as mentioned by @optima-ben. Apply a size with "width" or "max-with" is not a solution to keep a responsive slider.

For example with the code bellow:
```
<div class="first-container">
    <div class="second-container">
        <div class="slick-container">
            <div><img src="image-1.jpg" /><p>Text 1</p></div>
            <div><img src="image-2.jpg" /><p>Text 2</p></div>
            <div><img src="image-3.jpg" /><p>Text 3</p></div>
        </div>
    </div>
</div>
```
```
.first-container,
.second-container {
    display: flex;
}

.first-container,
.second-container,
.slick-container {
    min-width: 0; /* can be replaced by overflow: hidden */
}
```
