### ISSUE TITLE
Stacking on mobile when loaded 

### ISSUE THREAD

**Issue by ghosydneyben** [kenwheeler/slick#2379]
We are using slick slider for a clients project and it has been working perfectly so far, however I have noticed something, I don't know whether it is a bug or something that I am missing something.

When the slider is loaded on mobile, just before you get the whole slider visible in the viewport it doesnt load properly and stacks on top of each with half of the slider of the page. Then when you scroll so the whole slider is visible in the viewport it jumps back to how it should, almost like it has re-slicked its self.

====================================================================

Here is my config/code for the slider:

    $('.alt-options-slider').slick({
        slidesToShow: 1,
        accessibility: true,
        centerMode: true,
        touchMove: true,
        slidesToScroll: 1,
        infinite: false,
        mobileFirst: true,
        centerPadding: '25px 30px',
        edgeFriction: 0.30,
        accessibility: true,
        arrows: false,
        prevArrow: $('.prev'),
        nextArrow: $('.next'),

        settings: "unslick",
        responsive: [{
                breakpoint: 767,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    centerMode: false,
                    centerPadding: '0px',
                }
            }, {
                breakpoint: 992,
                settings: {
                    slidesToShow: 5,
                    slidesToScroll: 1,
                    settings: "unslick",
                    centerMode: false,
                    centerPadding: '0px',
                }
            },
        ]
    });

Here are some screenshots to show the problem, as the project is not publicly available yet.

http://imgur.com/a/9hZFM

The 2nd one is before the whole slider is in the viewport.

Also very similar to this problem 

http://stackoverflow.com/questions/37446005/slick-js-loading-issue

**Comment by leggomuhgreggo** [comment]
That's how it would look if there were no slick. The browser has to load the JS. Once the JS is loaded it will apply the slick classes and styles. See #981 or #779.
