### ISSUE TITLE
Something we can access when reaching the end of the slider

### ISSUE THREAD

**Issue by phorxy** [kenwheeler/slick#2384]
I've been trying to do a slider that has special functions when at the beginning and end of a multi row slider. It has 5 slides per row but the number could be any where from 1 to 20 slides, as its being built dynamically.

I've found knowing when I'm at the beginning, I've tried looking at the current slide, but it doesn't give me the last slide number, just the number at the beginning of the row. 

It would be nice to have something that lets us know we've reached the end of the slider. It must trigger something as it has to know for the arrows and for the infinite slider. Making this a variable we can use would be awesome.

**Comment by leggomuhgreggo** [comment]
One way would be to tie into any of the events grab the slick object get the slides key and use the `.last()` method. Good luck!
