### ISSUE TITLE
CSS From CDN does not work

### ISSUE THREAD

**Issue by stevenmwade** [kenwheeler/slick#2387]
CSS from the provided CDN does not work. Missing dots styles and more.

https://jsfiddle.net/58duz9Lj/

**Comment by leggomuhgreggo** [comment]
There are two CSS files. Unopinionated base styles, which is what you're loading, and then slick-theme.css which is more stylistically robust

**Comment by stevenmwade** [comment]
Why isn't it mentioned that you have to use the theme.css?

**Comment by leggomuhgreggo** [comment]
Well technically you dont need to use both, but [it is mentioned](https://github.com/kenwheeler/slick#example-using-jsdelivr)

**Comment by leggomuhgreggo** [comment]
Wait it's also in the getting started section [here](http://kenwheeler.github.io/slick/). Where are you seeing it absent?

**Comment by stevenmwade** [comment]
Ok. That is not mentioned on "Git It Now" part of https://kenwheeler.github.io/slick/. Well, thanks for the quick response. I didn't even see the theme file existed since I used that page. To get the files I went straight to that section.
