### ISSUE TITLE
Background image on slide not expanding to parent element.

### ISSUE THREAD

**Issue by robmccart** [kenwheeler/slick#2388]
> I have  left and right elements within a parent. I'm using a clear fix on the left element so the background image expands to the height of the right element. When I make the left element a slide, the clear fix no longer works and the height is dictated by the content of the left element.

====================================================================

###### `[ http://jsfiddle.net/robmccart/8of6ztL1/2/ ]`  

====================================================================

#### Steps to reproduce the problem

1. Try without slider (http://jsfiddle.net/robmccart/ssu337aw/1/)  
2. Try with the slider (http://jsfiddle.net/robmccart/8of6ztL1/2/)

====================================================================

#### What is the expected behaviour?

The left side expands to the size of the right side element, 700px high.

====================================================================

#### What is observed behaviour?

The left side expands to the content (text + padding) of the slide

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome Version 51.0.2704.103 m, same behavior in FF and IE
- Which jQuery/Slick version are you using?
Latest
- Did this work before?
Don't know

**Comment by leggomuhgreggo** [comment]
Hey @robmccart this is a CSS issue, not a bug with slider. Good luck man!
