### ISSUE TITLE
Center Mode - Only 1 slide visible

### ISSUE THREAD

**Issue by undfnd** [kenwheeler/slick#2390]
http://jsfiddle.net/fmo50w7n/459/

I'm using the CenterMode and only one slide to be visible. What I'm looking for is that the Next and Previous slides, which are visible partially (like 50px) to be visible half of their widths. You can see in this picture what exactly I'm seeking for http://i.imgur.com/v7z0mN1.jpg

I looked into the js file and so far I've found this, I think is the appropriate script that calculates the offset:

`if (_.options.centerMode === true && _.options.infinite === true) {
            _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2) - _.slideWidth;
        } else if (_.options.centerMode === true) {
            _.slideOffset = 0;
            _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2);
        }`

I'm not very good at writing/modifying javascript and I was wondering if you can give me a hint on this.

Thank you very much for this wonderful plugin!

Daniel

**Comment by undfnd** [comment]
I just found a solution using some css:

`.slick-list {
    padding: 0 220px !important;
}`

I don't know if is the best solution but works as I wanted, so I can live with it for now :)

Thank you anyway

**Comment by undfnd** [comment]
Ohh, I'm such an Idiot.. just scrolling down in slick.js and I've found out that "centerPadding" does exactly what I was looking for .. doh. Sorry for the trouble :))

**Comment by freewings89** [comment]
@undfnd Hi, i know this issue was 4 years ago but i want the same display like your. Unfortunately set centerPadding not working as expected, the best result is 3 slides fully visible, i can't hide 2 others to the side (display 50% of their width). Can you show me your working code or guide me out. Thanks.

**Comment by nicostem** [comment]
@freewings89 Hi! did you find a solution? I want to do the same and I have the same issue.
