### ISSUE TITLE
Rounding errors in slideWidth accumulate, causing obscured slides

### ISSUE THREAD

**Issue by pdg137** [kenwheeler/slick#2394]
The width of slides is calculated using Math.ceil ([see code here](https://github.com/kenwheeler/slick/blob/1.6.0/slick/slick.js#L1937)), so it can easily be off by almost 1px per slide. Over a large number of visible slides, this can accumulate enough to shift a slide off the right edge of the carousel, causing it to be partially hidden.

====================================================================

[See this jsfiddle for an example](http://jsfiddle.net/pdg137/fmo50w7n/463/). In the example, I deliberately set it up with a carousel width of 201px and 10 visible slides, so that each would have a computed width of `Math.ceil(20.1) = 21`.  The last slide has an accumulated error of ~10px, causing half of it to be obscured.  [This version](http://jsfiddle.net/pdg137/fmo50w7n/464/) shows what happens when the width is changed to 200px, so that there is no rounding error - it works fine.

====================================================================

#### Steps to reproduce the problem

1. Set up a carousel with many visible small slides, little or no margin between slides, and fluid or manually-adjustable width.  
2. Resize browser or otherwise adjust the width of the carousel. At some widths slides will be partially obscured.

====================================================================

#### What is the expected behaviour?

All slides should be entirely visible.

====================================================================

#### What is observed behaviour?

At some widths slides are partially obscured.

====================================================================

#### More Details

This is a mathematical issue with slick.js version 1.6.0; it will happen on all browsers and with all versions of jQuery. I am new to slick.js and do not know whether it ever worked in the past. 

====================================================================

#### Workaround

As a workaround on a responsive page, one could add a zillion media queries that force the width of the carousel to resize in increments that are a whole multiple of the number of slides. Spacing the slides by > n pixels also prevents obscured slides, though they could end up looking off-center.

#### Suggested solution

I am not very familiar with the code, but I think a first step would be to change that `Math.ceil` to `Math.floor`.

The problem is that that would cause the next slide to become partially visible. So, I think that one of the divs (maybe `.slick-list`) should also have its width rounded down to crop the slides so that nothing else is shown.

**Comment by leggomuhgreggo** [comment]
Hey @pdg137, appreciate the issue. This bug is definitely a bit of a dagger. I can tell you [it's on the radar](https://github.com/kenwheeler/slick/issues/2167) and hopefully it gets resolved soon. Thanks!
