### ISSUE TITLE
getSlick on init

### ISSUE THREAD

**Issue by mphm** [kenwheeler/slick#2395]
====================================================================

###### `[  http://jsfiddle.net/f262t1ov/20/  ]`  

====================================================================

#### Steps to reproduce the problem

1. Initialize slick slick slider, and try to get $('.slider1').slick('getSlick'), 

====================================================================

#### What is the expected behaviour?

Should be able to get the getSlick object in the init event

====================================================================

#### What is observed behaviour?

Slick gets an error, which seems like the slick slider is not fully initialized.
Cannot read property 'getSlick' of undefined TypeError: Cannot read property 'getSlick' of undefined

====================================================================

#### More Details

- Did this work before?

This worked before on slick 1.3.5 with callbacks, before the new current slick events

onInit = function (obj) {
    $slider = obj.$slider;
}

The new init event returns an object, which is not the one I want.
I could get the getSlick object if call it outside of the init event, but I rather have it in there.

**Comment by leggomuhgreggo** [comment]
Hey @mphm thanks for making an issue. I dont see the method in the docs, but I do see it in the code. I wonder if method is full support for this method was deprecated. What are you trying to do--maybe there's a good alternative? I think the init event should take a slick argument which allows you to get the jquery selection object.

**Comment by pskrz** [comment]
I think the documentation is wrong, if you pass in two arguments to onInit 
<img width="968" alt="screen shot 2017-05-31 at 10 30 32 am" src="https://cloud.githubusercontent.com/assets/605522/26725465/ad999a90-476c-11e7-9200-6e43969864ce.png">
then you get an event and a slick instance available in the function

**Comment by leggomuhgreggo** [comment]
Every event has the `event` object as the first argument https://github.com/kenwheeler/slick

**Comment by pskrz** [comment]
OK, but the documentation on the website implies the only argument is the slick instance, but it's actually an event & the slick instance . This causes confusion when people are trying to use the slick instance by passing in one argument but they are actually getting the event. When I got bit by this I found a lot of similar cases on stackoverflow and elsewhere, thankfully I think it can be resolved with a simple documentation update.

I broke out a new issue here https://github.com/kenwheeler/slick/issues/2921
