### ISSUE TITLE
Autoplay reverse after `slickRemove` then `slickAdd`

### ISSUE THREAD

**Issue by monkeymonk** [kenwheeler/slick#2396]
After removing all slides using `$slider.slick('slickRemove', null, null, true);` then adding some slides using `$slider.slick('slickAdd', collection[i]);`.

The autoplay go backward... and doing `$slider.slick('slickGoTo', 0, true);` is followed by the autoplay.

====================================================================

http://jsfiddle.net/fmo50w7n/468/

====================================================================

#### Steps to reproduce the problem

1. wait for the async process (5 sec in fiddle)
2. when the last slide is reached, the async is executed again
3. look the mess

====================================================================

#### What is the expected behaviour?

Obviously, it have to follow the new elements added. And/or update the current slide correctly without reversing the autoplay.

====================================================================

#### What is observed behaviour?

When the second `updateSlider()` is executed, the slider go backward instead of continuing or stoping.
I've tried to `pause` then `play` also `$slider.slick('slickGoTo', 0, true)`... but nothing seems to work or modify the behaviour.

====================================================================

#### More Details

- Which browsers/versions does it happen on? all
- Which jQuery/Slick version are you using? slick.js#^1.6.0
- Did this work before? no

**Comment by leggomuhgreggo** [comment]
When autoplay is true and infinite is false, the slider will get to the last/first slide then reverse direction. Looks like that's whats going on here, but let me know if I'm missing something.

Thanks!
