### ISSUE TITLE
Why is Math.ceil used to calculate width - causes element width overflow

### ISSUE THREAD

**Issue by markogresak** [kenwheeler/slick#2398]
The element and parent width is calculated using `Math.ceil`, rounding the value up ([slick.js:1941](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1941-L1942)). In bootstrap v4, where the container at md (992px) < width < lg (1200px) is 940px wide, the `col-x-x` classes take away 15px padding on each side, reducing it to 910px. With 3 slides in this container, the width is calculated as `Math.ceil(910 / 3) = 304px` and the parent is set to be `304 * 3 = 912px` wide, in turn not fitting in the container and causing a warp. Is there a specific reason for this?

====================================================================

###### `[  http://jsfiddle.net/Losj26u0/2/ ]`  

use this jsfiddle to reproduce your bug: 

I can't reproduce the bug with wrapping, but this fiddle shows how the size of slick can be larger than it's wrapping element. Pay attention to the border on the right edge, which gets hidden because of `overflow: hidden` (can't remove this property w/o side effects) and this is still undesired.
http://jsfiddle.net/Losj26u0/2/

====================================================================

#### Steps to reproduce the problem

1. Use bootstrap v4
2. Create structure `.container > .row > .col-lg-12 > {slick slider}` with 3+ elements 
3. Set slick `responsive` config `breakpoint` to *992* and `slidesToShow` to *3*
4. View at screen size larger than 992px and smaller than 1200px

Alterantively, steps 1., 2. and 4. can be shortened by hardcoding slick slider wrapper to `910px`. 

====================================================================

#### What is the expected behaviour?

The elements should be few pixels smaller rather than larger to ensure content will always fit inside parent element. The width should be round down, sacrificing some pixels where integer division is not possible. 

====================================================================

#### What is observed behaviour?

Elements take more space than parent wrapper and can get cut off if overflow is hidden. 

====================================================================

#### More Details

- Which browsers/versions does it happen on?
 - Using Chrome 51. Although that is most likely irrelevant, since I've tried other browsers when I was debugging this and it was all the same.
- Which jQuery/Slick version are you using?
 - jQuery:  `~2.1.0` (via bower)
  - slick: `~1.6.0` (via bower)
- Did this work before? 
  - Probably not.

**Comment by leggomuhgreggo** [comment]
Hey @markogresak thanks for making the issue. It's something that's on the radar #2167

**Comment by ohabash** [comment]
???!!!!
