### ISSUE TITLE
web page scrolled too much on safari ipad

### ISSUE THREAD

**Issue by Mehrda** [kenwheeler/slick#2400]
I have multiple content tab and inside each of them is a slick carousel.
This page load correctly on iphone but on ipad the page scrolled too much and user should scroll to see the content.

Please see this web page on ipad (latest version of ios):

"http://hampar.com/page/show/delete%D9%BE%DB%8C-%D9%88%DB%8C-%D8%B3%DB%8C-%D9%86%D8%B1%D9%85/b3cc7159-9cf2-460a-9313-cb1f4a2a6da5"

Sincerely,
Mehrdad

**Comment by leggomuhgreggo** [comment]
Hey can you recreate in a reduced test case, like a jsfiddle or codepen? Thanks.
