### ISSUE TITLE
Jumpy transitions when using waitForAnimate: false

### ISSUE THREAD

**Issue by andycansdale** [kenwheeler/slick#2401]
When waitForAnimate is set to false, the resulting transition is jumpy and disorienting when advancing various slides. It would appear that the ease is not being executed property when advancing to another slide before the previous transition has finished.

Recommend it be smoothed out if possible as in this example: http://www.onefinestay.com/homes/london/goodwins-court/

**Comment by leggomuhgreggo** [comment]
Hey can you recreate in a reduced test case, like a jsfiddle or codepen? Thanks.

**Comment by AllainPL** [comment]
It looks like an old glitch is still not fixed.
https://codepen.io/anon/pen/WXEPvQ

Try clicking fast on next/prev or random dots (buttons with numbers in example).

**Comment by michaelCaleyWhaley** [comment]
This is still a problem
