### ISSUE TITLE
initialSlide should not be considered if there are less than slidesToShow slides

### ISSUE THREAD

**Issue by AlternateIf** [kenwheeler/slick#2402]
> The initialSlide property should not be considered if the list contains less than or equal slidesToShow items since the transformation of slick-track will move slides "out-of-view". Furthermore because there are less than or equal slidesToShow slides no arrows are being created. This makes it imposible to ever move the hidden slide(s) in view.

As observable in the fiddle, slidesToShow is set to 3 and initialSlide is set to the 1 (second item). Due to initialSlide and the transformations the first item is out of view.

====================================================================

###### `[  https://jsfiddle.net/9cx26rao/  ]`  

====================================================================

#### Steps to reproduce the problem

1. <= slidesToShow slides
2. initialSlide set to other value than default

====================================================================

#### What is the expected behaviour?

Expected behaviour in my opinion would be to have all slides visible if there are <= slidesToShow slides even though initialSlide is set

====================================================================

#### What is observed behaviour?

Slide(s) are hidden

====================================================================

#### More Details

- Chrome/Firefox/Others
- jquery 1.12.4, slick 1.6.0

**Comment by Cocola** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Hey thanks for reporting the issue. This is actually covered by a couple open issues and I think there's even a PR pending for it. Hope to get it into the next major release, but easy enough to create a test as a work around. Thanks again
