### ISSUE TITLE
getLeft improvement

### ISSUE THREAD

**Issue by dimitriadisg** [kenwheeler/slick#2403]
Hello,
I am using slick version 1.5.9
Thank you a lot for your effort and results. Here I will just recommend a small improvement, I am not sure if a newer version has fixed this already, sorry if it did.

In function Slick.prototype.getLeft = function(slideIndex) of line 1018 of slick.js I have added a simple case check after the declaration of var _ like this:
        
        Slick.prototype.getLeft = function(slideIndex) {
            var _ = this,
            targetLeft,
            verticalHeight,
            verticalOffset = 0,
            targetSlide;

        _.slideOffset = 0;
        verticalHeight = _.$slides.first().outerHeight(true);

        if(_.slideCount == 1) return 0; //This line is my addition, it just blocks the left moving in case of a single slide
        
        if (_.options.infinite === true) {
        //Rest code here ...

My problem was that in case of a single slide, it was moved left resulting to completely move away from my visible screen. Excuse my boredom for not providing example code, the fix itself is too small of a code that I believe you will be able to judge it yourself if you want this fix or not.

Kind regards,
George

**Comment by leggomuhgreggo** [comment]
Hey @dimitriadisg thanks for making the issue. I think I understand what you mean, but I thought there were other checks against activating the slick in the case of a single slide. Can you make a test case in a jsfiddle or codepen with the latest version of the master?

Closing pending test case.
