### ISSUE TITLE
Multiple instance events

### ISSUE THREAD

**Issue by CHEWX** [kenwheeler/slick#2406]
With multiple instances of slick on 1 page using the same class, the event `afterChange` fires for all. So using `slickGoTo` will apply to all.

====================================================================

 http://jsfiddle.net/hk8b85tc/2/

====================================================================

Without using unique class instances, would it be possible for them to be unique ? As the arrows are.

**Comment by leggomuhgreggo** [comment]
Hey thanks for filing the issue. There's an existing one covering this particular matter so I'm going to close this one. Thanks!

**Comment by CHEWX** [comment]
Any reference to the duplicate ?

**Comment by leggomuhgreggo** [comment]
Sorry, here: #2348
