### ISSUE TITLE
Swipe elasticity / threshhold issue

### ISSUE THREAD

**Issue by holodoc** [kenwheeler/slick#2408]
Recently I've received a couple of complaints about how much swipe length slick requires to initiate a slide change on mobile devices, especially phones. In order to verify a potential usability issue I've created an A/B test and offered it to a couple of people. The test consists of two separate carousel solutions, both displaying the same set of pictures and having the same set of initialization settings.

The first test case is made with slick.js 1.6.0 - http://codepen.io/holodoc/pen/OXjPNj.

The second test case is made with Owl Carousel (1.3.3) - http://codepen.io/holodoc/pen/XKaJyJ.

Nine out of ten people confirmed that changing slides on mobile phones felt much smoother and easier on Owl Carousel because slick required too much swipe length to initiate a slide change. As if the elasticity of the edge from which the swipe is initiated was too high.

According to the documentation and a really brief look at the code the so called `edgeFriction` value is supposed to control how much swiping is required in order to trigger a slide change. However, I was unable to see any difference in behavior no matter what number I used. Of course the `infinite` option was set to false.

Is this kind of behavior a bug? Is there a way to make swiping more smooth and relaxed like it's in the case of Owl Carousel? I personally like slick but this issue is definitely a huge "no go" if there is no way to fix it.

**Comment by wannesderoy** [comment]
I believe the option you are looking for is the `touchThreshold` option.
I'm quoting the docs here: 
> To advance slides, the user must swipe a length of (1/touchThreshold) * the width of the slider

This means for example if you set the option to `3`, and a user swipes to 1/3th of the next slide, Slick will advance to that slide.
If the swipe didn't reach the 1/3th mark, Slick will reverse to the current active slide.

I have used this option a couple of times in the past and confirm that this works.

Hope this helps

**Comment by holodoc** [comment]
I have **absolutely no idea** how I missed that option. And it even supports infinite loops. Thanks!

Since this is obviously a completely bogus request from me I am going to close it. Thanks again.
