### ISSUE TITLE
Div.slick-track slow width calculation

### ISSUE THREAD

**Issue by hieuhlc** [kenwheeler/slick#2412]
I put a carousel inside a bootstrap modal. The carousel's width is fixed. I use `init` event on slick element to show the modal whenever slick carousel inited.

But when the modal showed up, slick carousel has not finished the calculation on div.slick-track. A short moment later, whole carousel begins to change position.

I think the `init` event should fire when the calculation is finished right?

**Comment by hieuhlc** [comment]
I figured it out. Slick need the container to be visible to calculate size and set position. Solved this by set modal CSS not to `display: none`. Instead:

`
 .modal {
    display: block;
    visibility: hidden;
    pointer-events: none;
  }
`
And when the modal is shown:

`
 .modal.in {
    visibility: visible;
    pointer-events: auto;
  }
`

**Comment by MentalGear** [comment]
Thanks for the great tip helping me figuring out what my issue was.

Actually what I ended up doing, was initializing the slider after the modal is shown.
