### ISSUE TITLE
Can't change position of prev and next arrows

### ISSUE THREAD

**Issue by sparra1000** [kenwheeler/slick#2413]
> I am trying to make the prevArrow and nextArrow appear on top of the slides instead of to the right and left of them as in all the demos. I can change the left position of the prevArrow by using a pseudo CSS class like below but it goes under the slides. The z-index doesn't put the slick-prev element on top.

`.slick-prev:before{
    color:blue;
    left:10px;
    z-index:1000000000000;
}`

====================================================================

Here is the jsfiddle
http://jsfiddle.net/fmo50w7n/481/

**Comment by leggomuhgreggo** [comment]
positioning is on the arrow el not pseudo selector

http://jsfiddle.net/u8x2a2ss/
