### ISSUE TITLE
Hash url link -- onclick open new page sliderGoTO 

### ISSUE THREAD

**Issue by candyshien** [kenwheeler/slick#2414]
Any idea, how to work on the slick Slider Syncing add hash url.

For Example, If I at page 1/landing page onclick button "A", open up page 2/about us page slick Slider Syncing SlideGoTo "2" or "3" and ......

Need help, any idea how to work the  Function??

**Comment by leggomuhgreggo** [comment]
Check this issue:
https://github.com/kenwheeler/slick/issues/152
