### ISSUE TITLE
Using beforeChange to delay slide action until after async operation is completed

### ISSUE THREAD

**Issue by JavierPDev** [kenwheeler/slick#2417]
Is there a way to stop slick from sliding after a user clicks the next or previous button and then have it continue later? For example:

```javascript
function beforeChange(event, slick, currentSlide, nextSlide) {
  slick.pauseChange(); // example desired function call
  setTimeout(function() {
    slick.completeChange(); // example desired function call
  }, 2000);
}
```

**Comment by leggomuhgreggo** [comment]
Check out some of the options here: https://github.com/kenwheeler/slick/issues/1138

I think you might also be able to use a custom animation.
