### ISSUE TITLE
Setting `dots` to true disabled `swipeToSlide` functionality

### ISSUE THREAD

**Issue by patrickbjohnson** [kenwheeler/slick#2419]
When passing in the settings object and setting `dots` to `true` it disabled the swipe functionality to paginate through slides. 

Even with `swipeToSlide` set to `true` it still does not function properly. 

Here's the demo: [http://codepen.io/pbj/pen/bZYLmQ](http://codepen.io/pbj/pen/bZYLmQ)

**Comment by leggomuhgreggo** [comment]
You're dots element is obstructing the slide; so, no touch event can be registered to it.
