### ISSUE TITLE
How to output current slide index in html?

### ISSUE THREAD

**Issue by marflow** [kenwheeler/slick#242]
How would I use "slickCurrentSlide()" to output the index of the current slide in html? Thank you :)

I managed to get the index of the first slide output in my span ".current" with the code below, but it does not change as I go through the slides. Thanks a lot for some help with this.

```
  $(document).ready(function(){
    var currentSlide = $('.slides').slickCurrentSlide();
      $('.current').text(currentSlide+1);
  });
```

**Comment by eamonnkenny** [comment]
I've tried using two different sliders in the same page with the above code. One has a class="slides current" and the other with just class="slides". Do you need to include any special div, paragraph or other item within:

<div><img width="300px" src="http://kenwheeler.github.io/slick/img/fonz1.png" /> </div>

or do you just leave each div containing the image blank and then the text gets dropped into each class? I can't get the number to appear under each slide.
