### ISSUE TITLE
BUG: Images do not load properly on: Chrome/Firefox/Opera/Developer Tools/Mobile

### ISSUE THREAD

**Issue by peppies** [kenwheeler/slick#2421]
I've provided a barebones Plunker script that reproduces this problem with images not loading up: http://plnkr.co/edit/epsTwdFMMDZhDlB7ZXhL?p=preview . I am seeing this happen on Chrome v49, Firefox v45, Opera v36 and also the Chrome Developer Tools for Mobile view. My intention is to use Slick Slider for mobile users only. When a user clicks a thumbnail, a full-screen modal with Slick Slider is supposed to appear. Site uses Bootstrap 3.3.2. (In my example code, I have the modal open up automatically when the page loads. I've been trying different heights (height:auto), putting image tags within another div element, nothing works...)

Problem: When the modal opens and Slick gets triggered, Slick seems like it almost loads, but the images do not appear. I set a min-width:50px on the image tag itself to see that the images are in fact there (all piled on top of each other in a small 50px box), but Slick is improperly displaying them.

Inconsistent: It sometimes works and sometimes doesn't (on Chrome and Firefox), never works on Opera, seems like it always works on IE9. If you keep refreshing that page on Chrome for example, you'll see that a lot of times it does not load properly.

If it wasn't for that, the script would almost be ready for production and it looks MUCH better than the other 3 scripts I had to abandon this week because they don't work properly in the real world.

**Comment by leggomuhgreggo** [comment]
Looks like it's loading fine for me. My guess is you're having issues with bootstrap modal styles. If a slick's parent is display none then it cant get the calc. You can override bootstrap's default styles with visibility: hidden/visible. Watch out for the change in docuement flow; might need absolute positioning. Good luck.
