### ISSUE TITLE
slick.js crahses the app on iphone6+ and ipad mini

### ISSUE THREAD

**Issue by ezuniga** [kenwheeler/slick#2423]
slick.js crahses the app on iphone6+, but it works on iphone 6 and iphone 5

I have an array that I load dynamically the I use scope.apply to update the model and the app crashes.

`<slick id="slick-container">
						<div ng-repeat="slider in slide.data track by $index">
<slick>
`

**Comment by leggomuhgreggo** [comment]
Can you reproduce in a reduced test case like a jsfiddle or codepen? 

Closing pending test case.
