### ISSUE TITLE
Image jumping on page load

### ISSUE THREAD

**Issue by brakai295** [kenwheeler/slick#2424]
When I load the page with an image gallery slider on it, the images seem to be loading down the page for a split second before the slider 'kicks in' and puts them in place. 

Why is this happening? Can anyone suggest a solution?

**Comment by davim00** [comment]
I've noticed that too. I always thought it was loading the HTML before the javascript and maybe being a little slow about it?

**Comment by leggomuhgreggo** [comment]
@davim00 Yep! 

This is a pretty common issue. Should add it to the readme.md.

```
.my-slider-name:not(.slick-initialized){...pre initialized styles...}
```

Hope that helps.
