### ISSUE TITLE
Slick sans jQuery

### ISSUE THREAD

**Issue by controversial** [kenwheeler/slick#2433]
Is there an option, perhaps a fork, that would allow me to use Slick without jQuery? I'm pretty stubborn about not using jQuery in my project, but Slick is wonderful.

**Comment by leggomuhgreggo** [comment]
Nah, but maybe v2! Search old issues for more info.

**Comment by controversial** [comment]
Ok, it's fine. Are there any libs with similar functionality that I could
use?
