### ISSUE TITLE
slick.min.js:1279 Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by storytime** [kenwheeler/slick#2435]
#### Short description of the bug / issue, provide more detail below.

I've got an error on load. 
Slider is very simple.

Error: http://i.imgur.com/GOwxtkL.png
Init: http://i.imgur.com/SK84QNN.png

#### More Details

- Which browsers/versions does it happen on?
Chrome/FF

- Which jQuery/Slick version are you using?
jquery-1.11.3
slick - 1.6

**Comment by leggomuhgreggo** [comment]
Please provide a test case in a jsfiddle or codepen. Thanks!
