### ISSUE TITLE
RTL slider snaps out of alignment after zooming out on Chrome

### ISSUE THREAD

**Issue by tepez** [kenwheeler/slick#2436]
The slides of an RTL slider snap out of order when you zoom-out. This seems to happen only on Chrome.

At 100%, on init:
![image](https://cloud.githubusercontent.com/assets/3265649/17135328/f257a7b4-5337-11e6-9ca9-6060d50ac177.png)

At 90%:
![image](https://cloud.githubusercontent.com/assets/3265649/17135345/0659cf26-5338-11e6-89c4-e2af7b2a6aa6.png)

At 75%:
![image](https://cloud.githubusercontent.com/assets/3265649/17135554/096a0cc0-5339-11e6-8c77-a2053058f146.png)

At 110% (zoom-in works fine):
![image](https://cloud.githubusercontent.com/assets/3265649/17135361/226ab81a-5338-11e6-9fcc-00bc8d1c6be9.png)

### To reprodue
Open http://jsfiddle.net/o89u1foo/2/ with Chrome and zoom-out.

### Tested on
* Chrome 52.0.2743.82 - behavior as in above images
* IE 11 -works fine.
* Firefox 46.0.1 - works fine.

**Comment by leggomuhgreggo** [comment]
Interesting! Thanks for sharing your findings. Strikes me as being more a bug with chrome than with this repo, but, if you find a simple adjustment that will alleviate this, definitely holler back. If there's a zoom event in chrome, I guess you could listen for it and fire the setPostion method. Thanks!
