### ISSUE TITLE
Remove `outline: none` from dots

### ISSUE THREAD

**Issue by cshold** [kenwheeler/slick#2439]
By default, Slick sets `outline: none` on `.slick-dots li button`, making them invisible when receiving focus. This is bad for accessibility, but more importantly, **can't be re-enabled to browser defaults without editing the slick file**.

The same should be done on `.slick-prev` and `.slick-next` hover/focus states.

====================================================================

Demo on the Slick page http://kenwheeler.github.io/slick/

====================================================================

#### Steps to reproduce the problem

1. Tab through the slide dots and arrows.

====================================================================

#### What is the expected behaviour?

See the browser default outlines.

====================================================================

#### What is observed behaviour?

Opacity/color changes to the arrows and dots.

**Comment by leggomuhgreggo** [comment]
Yeah tough balance between design and accessibility, but in any case, you can edit the CSS. There's even two CSS files--one with base styles, and one with more opinionated styles--to encourage whatever customization you'd like. Even if you use the opinionated styles, it's very easy to override. Good luck.
