### ISSUE TITLE
Responsive breakpoints with automatic filter

### ISSUE THREAD

**Issue by ADTC** [kenwheeler/slick#2444]
Instead of using JavaScript to manually apply filters, is it possible to define filters in the responsive breakpoints?

I think I'll try using the `breakpoint()` callback method to do this _(how, though?)_, but it would be a lot cleaner to simply add it in the `responsive[]` block's `breakpoint, settings{}` section.

_(As it is a feature request, I removed the template. Hope that's okay.)_

**Comment by leggomuhgreggo** [comment]
Hey @ADTC Coincidentally there was another issue closely related enough that I think it can answer this one. Basically you want to listen for the breakpoint event. Check out #2434.

**Comment by ADTC** [comment]
But that's an issue, and I don't understand its relevance or relation to this feature request. Here I am asking about the possibility of having filter support in the JSON passed in to the Slick method:

```
$('.responsive').slick({
  dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 4,
  slidesToScroll: 4,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
        filter: ... //defining a filter here, instead of using breakpoint events
      }
    },
...
```

As mentioned before, I can use breakpoint events (I referred to it as callback method) but defining in JSON would be cleaner. I request a reopen.

**Comment by leggomuhgreggo** [comment]
Ah sorry for the misunderstanding. The library actually used to handle events that way, but switched, I think somewhere in version 1. Not exactly sure the reason, but I'm pretty sure there was one.

Definitely will take it under consideration. Thanks!
