### ISSUE TITLE
Carrousels won't resize

### ISSUE THREAD

**Issue by gabrielbonifacio** [kenwheeler/slick#2445]
Live example:
http://smart.trippple.com.br

====================================================================

#### Steps to reproduce the problem

1. Open the website
2. Resize the browser window so the width is narrower than the banner

====================================================================

#### What is the expected behaviour?

The sliders were supposed to be resized by the script (inline styles)

====================================================================

#### What is observed behaviour?

The sliders won't resize. If you inspect the element, you'll notice the inline styles won't update as you resize the browser, causing horizontal scrollbars to show up.

====================================================================

#### More Details

- jQuery version: 1.7.0
- Slick version: 1.6.0
- The issue occurs in all browsers
- Slick is being initiated in the main.js script (loaded on footer)
- The page has two carrousels: $('#slider-home .slider-session') and $('#seguradoras-carrousel .slider-session')
- I disabled all other scripts on the site (except for jQuery and Slick) to check if it was a conflict issue, no luck
- I tried different versions of jQuery, and also adding jQuery Migrate, no success
- I tried the following, but it didn't work:
$(window).resize(function() {
  $(selector).slick('resize');
})

**Comment by leggomuhgreggo** [comment]
Hey I think it's gotta be something to do with your environment. The slider definitely resizes. If you can recreate in a reduced test case like a jsfiddle (theres a base one in the contribution.md) or a codepen, I'd take a look, but smart money is it being some issue with your CSS.
