### ISSUE TITLE
Infinite loop when using slickFilter in breakpoint callback method

### ISSUE THREAD

**Issue by ADTC** [kenwheeler/slick#2447]
> Infinite loop when using slickFilter in breakpoint callback method

===============================================================

###### http://jsfiddle.net/fmo50w7n/515/

```
$(".slider").on('breakpoint', function(event, slick, breakpoint){
	if (breakpoint === 500) {
    console.log('NO');
  	slick.slickFilter(function(index){
    		return index > 1;
    });
  }
});
```

===============================================================

#### Steps to reproduce the problem

1. Use on to define an event callback method for breakpoint
2. At a certain breakpoint, call slickFilter and pass a function to it.
3. Test (use Chrome! Firefox MAY CRASH. In Chrome, call stack will overflow but browser remains responsive.)

===============================================================

#### What is the expected behaviour?

Filtering slides shouldn't trigger breakpoint callback, or there should be a way to control it.

===============================================================

#### What is observed behaviour?

Filtering slides triggers breakpoint callback, resulting in filtering slides again, thus an infinite loop. (Chrome console reports that after about a thousand such loops, there is "Uncaught RangeError: Maximum call stack size exceeded").

===============================================================

#### More Details

- Firefox 47.0.1, Chrome 51
- jQuery 1.12.0, Slick 1.6.0
- Did this work before? No. I could be doing this completely wrong.

_Related feedback: #2446_ 
_Related issue: #2434 (comment 3)_

**Comment by ADTC** [comment]
The stack trace from Chrome might be useful:

```
Uncaught RangeError: Maximum call stack size exceeded            VM156 jquery-git.js:5064
exec                 @ native regexp.js:136
test                 @ native regexp.js:267
remove               @ VM156 jquery-git.js:5064
(anonymous function) @ VM156 jquery-git.js:5536
each                 @ VM156 jquery-git.js:368
each                 @ VM156 jquery-git.js:157
off                  @ VM156 jquery-git.js:5535
Slick.cleanUpEvents  @ VM157 slick.js:771
Slick.destroy        @ VM157 slick.js:842
Slick.refresh        @ VM157 slick.js:1730
```

**Comment by leggomuhgreggo** [comment]
Hey this is a known issue; see #2434 and #1326. I haven't dug into it yet, but if you happen to track down the bug we'd definitely welcome the PR. Thanks!
