### ISSUE TITLE
Fullscreen API + Slick

### ISSUE THREAD

**Issue by daslicht** [kenwheeler/slick#2449]
> short description of the bug / issue, provide more detail below.
Slick Fullscreen unexpected behavior.
====================================================================

I am trying to invoke Fullscreen on a Slick Slideshow as the following:

http://jsfiddle.net/daslicht/3yet9tvw/11/

I don't know whey the fiddle is not working , but in my real project it is entering FullScreen mode but it looks like this:

![](http://i.imgur.com/3bbuw4L.png)

![](http://i.imgur.com/no52Xzt.jpg)

Any idea how to fix, please?

====================================================================

#### Steps to reproduce the problem

1. unclear

====================================================================

#### What is the expected behaviour?

Proper FullScreen View

====================================================================

#### What is observed behaviour?

Malformed Fullscreen view

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
    "jquery": "2.*",
    "slick-carousel": "^1.6.0",

- Did this work before?
nope

**Comment by daslicht** [comment]
I tried i call setPosition, but that doesn't help either:
```
$("#gallerySlideshow").slick('setPosition');
```

**Comment by leggomuhgreggo** [comment]
Hmm, your demo doesn't fullscreen for me. My loose guess is that the parent needs `position: relative`.

**Comment by daslicht** [comment]
Yeah , as mentioned above the demo did not work why ever but my real-world code, but it gets broken even tho I tried setPosition.
