### ISSUE TITLE
Vertical swipe on mobile devices with normal functionality

### ISSUE THREAD

**Issue by dkonopka** [kenwheeler/slick#2450]
On body start, I have slider with height:100% and under rest of other content.

On mobile devices is imposibble to scroll to content under slider, because vertical scrolling its not working, setting vertical for true its not helping.

**Comment by leggomuhgreggo** [comment]
Hey I think this might duplicate some of [these](https://github.com/kenwheeler/slick/search?utf8=%E2%9C%93&q=vertical+touch&type=Issues). Holler back if that's not the case. Thanks!
