### ISSUE TITLE
Google Places Autocomplete conflict

### ISSUE THREAD

**Issue by lizsterine** [kenwheeler/slick#2455]
I am implementing a step-by-step form with Slick.  Some of my fields are location entries which I hooked up with Google Places API to do the autocomplete suggestions.

[Google Places demo](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform)

There seems to be a conflict with Slick and Google's autocomplete list click event (when you click on a suggestion to fill the field).  When the field is INSIDE Slick, the click on Google's autocomplete list has no effect.  When the field is OUTSIDE slick, then all is normal.  

What's really confusing is that Google appends their list element to the body, so it's no even inside Slick.  :-/

My work-around is to use a proxy field outside of Slick that overlays my field inside Slick on the focus event, and that proxy is the one tied to auto suggestions.  

If you have any insight to the conflict, I'd love to hear about it!

**Comment by leggomuhgreggo** [comment]
I know there are some issues related to focus, but without a demo I couldn't say much more beyond that.

**Comment by tusharshuklaa** [comment]
I'm facing the same issue

**Comment by lizsterine** [comment]
> I'm facing the same issue. @lizsterine Did you fix this issue?

@tusharshuklaa I ended up copying the SlickSlider plugin and modifying it to remove some features that I didn't need for my particular form.  

I'm not sure what specific features had the conflict, but here's a list of the things I removed to help get you started:
- swipe related listeners and features
- autoplay / pausing related code
- dot navigation
- arrow navigation
- centerMode 
- as nav for
- some focus related listeners and settings

**Comment by tusharshuklaa** [comment]
Thanks a lot, will see if it fixes this issue.

**Comment by tusharshuklaa** [comment]
I have created a fiddle if a demo of the issue is needed. https://jsfiddle.net/tusharshuklaa/ptd8z0ew/28/

If slick code is removed from my js then google autocomplete works fine.
P.S.: CSS is broken but it should not be a problem to locate the input box.

**Comment by felipepassion** [comment]
same issue here. is it already solved?

**Comment by felipepassion** [comment]
Found the solution!
Just had to remove the following line: 
![image](https://user-images.githubusercontent.com/29386600/95699003-bd06fe80-0c19-11eb-9d28-b30922f1f3be.png)

I think this is because this line is stopping the proppagation to the google-autocomplete.
