### ISSUE TITLE
Chrome Shows Images 1px High intermittently

### ISSUE THREAD

**Issue by JeRoNZ** [kenwheeler/slick#2457]
> short description of the bug / issue, provide more detail below.

====================================================================
With google chrome, on the first uncached visit to a page, some but not all images appear as 1 pixel high. Forcing a reload with ctrl-f5 can reveal similar issues. This happens with the nav thumbnails and the main image (using synced images) Problem not observed with IE11 or Firefox, only with Chrome on Windows 7. 

###### `[  https://jsfiddle.net/jeronz/LjLcdw0k/  ]`  

====================================================================

#### Steps to reproduce the problem

Set up a synced image display - see above fiddle
====================================================================

#### What is the expected behaviour?
Image should always be their full height, not 1px

====================================================================

#### What is observed behaviour?

The problem only seems to happen with Chrome. FF/IE are OK. The problem doesn't seem to show up in the fiddle, but if you save the frame source as a new html file, it does. It may need a reload or two to show up, particularly if the images are already in your browser cache.

====================================================================

#### More Details

It seems that the rule in slick.css
```css
.slick-slide {
    min-height:1px;
}
```

is taken as the actual height. If I alter this rule using the developer console in chrome, the images resume their normal size. Reinstating the rule has no effect. Substituting min-height:auto seems to fix the problem completely.

Problem is only with Chrome.
Jquery version - I have tried sever, 1.91. and the 1.12.4 and the latest from github. All exhibit the same problem. I am also using jquery migrate 1.4

Slick version is 1.6

This is my first usage of slick (love it!) so I can't comment on whether it's happened before.

**Comment by leggomuhgreggo** [comment]
Having trouble recreating the issue. Might try to adding `img{width: 100%}` on your main slider. Good luck!

**Comment by brilnius** [comment]
For those with the same issue...
I had a similar issue, with Chrome but also with Safari.
The workaround I found so far: wait for 1 second before initializing the slider (embed slick() call in a setTimeout() function). This way all the images are hopefully loaded (and their dimensions known) when the slider is built.

**Comment by hellboy81** [comment]
my be problem can be solved with `jQuery.unveil`

**Comment by hellboy81** [comment]
issue should be reopened!
```
min-height:1px;
