### ISSUE TITLE
SlickGoTo on afterChange event doesn't work.

### ISSUE THREAD

**Issue by philgruneich** [kenwheeler/slick#2458]
I'm trying to design a carousel that skips a certain index, so, for example, when it is on the 3rd slide, it should skip to the fourth, but I can't figure out a way to make the `slickGoTo` method to work on the `afterChange` event.

http://jsfiddle.net/0s8fpmuj/

#### Steps to reproduce the problem

1. Hit the next slide button twice
2. You should arrive and remain at slide 3.

====================================================================

#### What is the expected behaviour?

After changing to slide 3, I expect the slide to go to slide 4 without user interaction.

====================================================================

#### What is observed behaviour?

After changing to slide 3, slider remains on slide 3.

====================================================================

#### More Details

Which browsers/versions does it happen on?
:    Chrome and Safari from my tests;
Which jQuery/Slick version are you using?
:    Slick: 1.6.0
:    jQuery: 3.1.1
Did this work before?
:    No, working on some new issue.

**Comment by leggomuhgreggo** [comment]
Check out #2264
