### ISSUE TITLE
Sliders too sensitive to normal page scrolling on mobile devices

### ISSUE THREAD

**Issue by davidsmith3652** [kenwheeler/slick#2462]
Our homepage has a number of sliders on it and on a mobile devices we have an issue with the sensitivity of the sliders. When you are just normally scrolling up and down the page (not intending to move any sliders) - the sliders treat this page scrolling as an attempt to swipe left or right on the slider and they start slightly moving in a jittery way. On a page with a lot of sliders - this effect can get quite off-putting.

You can see a video of what i'm describing here: https://drive.google.com/open?id=0B4AAbN1Uv8IWajVaWGxha0ZlOW8

Is there any settings which will help with this issue?

**Comment by leggomuhgreggo** [comment]
Hey @davidsmith3652, thanks for the report! This issue has been raised before. Give the repo a search and see if you can find it. If you can't feel free to holler back and I will try to track it down if I have time.
