### ISSUE TITLE
Infinite setting ignored when both variableWidth and slidesToScroll are set

### ISSUE THREAD

**Issue by depiction** [kenwheeler/slick#2464]
I've discovered a situation where the infinite setting is ignored. This occurs when variableWidth and slidesToScroll are both set.

http://codepen.io/depiction/pen/BzvddK

I'm showing two slides at a time and infinite is set to false. When slides 7 and 8 are visible and the next button is clicked, the user is taken back to slide 1. Nothing should happen because infinite scrolling is turned off. 

If I remove the 8th slide I get the expected result (nothing happens). slick.currentSlide returns the index of the left most slide and if it matches the last slide's index, infinite scrolling is correctly prevented. However if it doesn't match and the last slide is still visible due to the slidesToScroll setting, it fails to prevent infinite scrolling.

**Comment by leggomuhgreggo** [comment]
Hey @depiction thanks for the issue report. The same issue seemed to occur w/o variableWidth, so I think it's fundamental to infinite: False and `slides % slidesToScroll !== 0`

Same essential issue as these ones #2234 #2244 so I'm going to close this as a duplicate. Thanks again.
