### ISSUE TITLE
Slide on arrows hover/mouse over

### ISSUE THREAD

**Issue by grobishta** [kenwheeler/slick#2466]
I did read the topic https://github.com/kenwheeler/slick/issues/569
however I do not understand where to put the code to be able on arrow hover, to slide the slider

$('.slick-slide').on('mouseover',function(){
$('.your-slider-class').slickNext();
});

**Comment by evgenyshev** [comment]
Why is the topic closed? Does not work. You were asked, could you tell more about this?

**Comment by ejtipi** [comment]
This works for me:
```
$('.slick-next').on('mouseover',function(){
$(".slick-slider").slick('slickNext');
});
```

**Comment by fernandofas** [comment]
The best option I found is this one:

On the js file apply "arrows: true" and copy and paste the following css:
/*slick arrows on hover*/
.slick-arrow{ 
    opacity: 0; 
    transition: all .25s ease-in-out; 
    -moz-transition: all .25s ease-in-out; 
    -webkit-transition: all .25s ease-in-out; 
} 

.slick-arrow:hover{ 
    opacity: 1; 
} 

That works for me and I hope it works for you as well.

Cheers,

Fernando Fas

**Comment by Mtemizce** [comment]
Guys hi, i found it mouseover change slider items :)

`/*Manşet Horizontal Slider*/
        $('#mansetSlider').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: true,
            autoplay: true,
            infinite: true,
            autoplaySpeed: 4000,
            appendDots: '#mansetSliderDotsContainer',
            dotsClass: 'mansetSliderDots',
            nextArrow: '#mansetSliderNext',
            prevArrow: '#mansetSliderPrev',
        });`
`  const buttons = document.querySelectorAll(".mansetSliderDots > li > button");

        buttons.forEach((button, i) => button.addEventListener("mouseover", function() {
            console.log(i);
            $('#mansetSlider').slick('slickGoTo', i);

        }));`

Have o good day :)
