### ISSUE TITLE
customPaging with anchors do not prevent the default action

### ISSUE THREAD

**Issue by AndyOGo** [kenwheeler/slick#2468]
> short description of the bug / issue, provide more detail below.

Use the customPaging feature with an `<a href="#">foo</a>` tag, click it and it jumps to the top of the screen.
Default action of anchor is not prevented and the browser scroll to the top of the page.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/fmo50w7n/546/
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. specify customPaging option like:
````js
$(".slider").slick({
    customPaging: function (slider, i) {
        return '<a class="test-anchor" data-role="none" role="button" aria-required="false" href="#">Slide ' + i + '</a>'
      },
});
````
2. click one paging anchor

====================================================================

#### What is the expected behaviour?

Default action of anchor should be prevented.

====================================================================

#### What is observed behaviour?

Default action of anchor is not prevented

====================================================================

#### More Details

- Which browsers/versions does it happen on?
All browsers
- Which jQuery/Slick version are you using?
Does not matter
- Did this work before?
Don't think so

## Cause of bug

The bug is caused at this line: https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L687

You check the `currentTarget` of the event if it is an `<a>` tag, but if the delegated event bubbled up from an `<a>` tag below you want be able to catch it's default action with `currentTarget`. The correct property to check is `target`.

So instead of this:
```js
var _ = this,
            $target = $(event.currentTarget),
            indexOffset, slideOffset, unevenOffset;

        // If target is a link, prevent default action.
        if($target.is('a')) {
            event.preventDefault();
        }
```

You need something like this:
```js
var _ = this,
            $target = $(event.currentTarget),
            $realTarget = $(event.target),
            indexOffset, slideOffset, unevenOffset;

        // If target is a link, prevent default action.
        if($realTarget.is('a')) {
            event.preventDefault();
        }
```

**Comment by AndyOGo** [comment]
I thought more about this isseu:

1. Why should the default action only prevented if an `<a>` tag is clicked
2. To be generic, this wouldn't only need to check the target, instead it would need to traverse the DOM tree from `target` to `currentTarget` like when the `<a>` wraps a `<span>`. E.g.:
````js
$(".slider").slick({
    customPaging: function (slider, i) {
        return '<a class="test-anchor" data-role="none" role="button" aria-required="false" href="#"><span>Slide ' + i + '</span></a>'
      },
});
````

**Comment by leggomuhgreggo** [comment]
Hey @AndyOGo. The default paging uses the `button`. Since you're customizing it with an anchor element, it's on you to add the code to support it.

**Comment by AndyOGo** [comment]
@leggomuhgreggo 
Thanks for your reply.
I think you guys made a really cool tool.

Please check again, I'm really sure this is a bug.
Since slick's code at https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L682-L689 prevents already the default action for anchor tags, but is just checking the wrong prop.
I also think it is not necessary to check for any target, just call `event.preventDefault()` always.

In general I agree with you, and I know how to supply custom markup, but do you also provide hook-in functionality, that I could add the needed code?

Btw: I already provided a pull request which addresses this bug

**Comment by leggomuhgreggo** [comment]
@AndyOGo apologies for the hasty response. I appreciate the efforts you've made to address the issue.

I regret not yet having the chance to get deep on the issue. As a preliminary concern, I wonder how your adaptation would handle a scenario in which each paging item had a nested external link. The use case would be where most of a paging item would trigger the respective slide but a child anchor would link externally.

In general I do see your point and also appreciate your considerate response?

**Comment by AndyOGo** [comment]
@leggomuhgreggo Thank you for your quick answer.
Indeed, I did not think about external links. mhm in this case a generic solution would ne to check the href of the anchor too.
But then it would be still possible that someone wants an internal anchor pointing to a fragment of the page...

But then my PR is not complete...
