### ISSUE TITLE
How i can use vertical carousel with Up/Down arrow navigation

### ISSUE THREAD

**Issue by designersuresh** [kenwheeler/slick#247]
The current carousel is horizontal with left/right arrow. I would like to use carousel vertically with top and bottom arrow navigation. I couldn't see any solution inside the library/js. Please let me know if anyone has solution.

**Comment by tomamarius3** [comment]
@designersuresh Hey! I've stumbled upon this recently. The easiest way to do this is to assign the nextArrow and prevArrow having a definition for your slider like this:
$('.slider').slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        arrows: true,
        vertical: true,
        prevArrow: $('.top-arrow'),
        nextArrow: $('.bottom-arrow')
    });
