### ISSUE TITLE
Slick centerMode :  Wrong center position

### ISSUE THREAD

**Issue by l2aelba** [kenwheeler/slick#2475]
![ugxw06kn9h](https://cloud.githubusercontent.com/assets/983458/17739783/89857322-6496-11e6-860e-0d691589e262.gif)

You can see it moving too far and going back again , How can I fix that ?

**Demo :** http://jsfiddle.net/mbfu44o1/

**Comment by leggomuhgreggo** [comment]
Closing: Support Request
