### ISSUE TITLE
JQuery 3.1.0 compatibilities ?

### ISSUE THREAD

**Issue by vincent-guesnard** [kenwheeler/slick#2477]
Hello,

I have checked arround  if someone already launch a debug session on JQuery 3.X, and found nothing. If it has been already discuss, i apologize.

If not, did you encounter some king of bugs ? (I do but don't have time to launch a correct debug session this month, if someone got time, it would be greatly appreciated to get a return)

Thank you very much for this amazing lib.

Best regards,

V

**Comment by leggomuhgreggo** [comment]
Haven't heard of any bugs related to the new jQuery
