### ISSUE TITLE
slick 1.6.0 arrows not shown / touch events not working on chrome mobile & others

### ISSUE THREAD

**Issue by thunderger** [kenwheeler/slick#2479]
In some mobile browsers, e.g. Chrome, slick 1.6.0 doesn't work properly. In all mobile browsers touch events are missing, e.g. to stop automatic movement of images by clicking. In Chrome arrows are not shown. In desktop browser all functions are working as expected. 

====================================================================

###### `[  https://jsfiddle.net/pws0aqat/  ]`  

use this jsfiddle to reproduce your bug: 
https://jsfiddle.net/pws0aqat/
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1a. run demo website https://www.hom-ideenschmie.de/mrss-hochzeit-beta/#galerie in Chrome mobile
1b. run demo website https://www.hom-ideenschmie.de/mrss-hochzeit-beta/#galerie in any desktop browser
2. try to stop animation by clicking / try to find arrows

====================================================================

#### What is the expected behaviour?

in all browsers, mobile and desktop, slick gallery will show its arrows and touch events like clicking on image are working.

====================================================================

#### What is observed behaviour?

im mobile browsers, especially chrome, some functions are not working. Slick gallery is loaded by AJAX call, all images are shown and animation is working. But arrows are missing and touch events are ignored.

====================================================================

#### More Details

- Chrome 51.0.2704.81(Android 4.4, 5.0, 6.0)
- iOS integrated browser (iOS 8 & 9)
- jQuery 2.2.4
- never works on mobile without issues

**Comment by leggomuhgreggo** [comment]
Hmm I see the arrows. Not sure what you mean by stop animation by clicking? clicking where?

**Comment by c-man90** [comment]
Can confirm, I'm also not being able to drag/swipe one of the carousels on chrome, the other works...
