### ISSUE TITLE
"variableWidth: true" and slidesToScroll

### ISSUE THREAD

**Issue by vkirpa** [kenwheeler/slick#2482]
If "variableWidth: true"  then "slideToScroll"  not working/

**Comment by vkirpa** [comment]
http://manos.malihu.gr/repository/jquery-thumbnail-scroller/demo/examples/demo.html

**Comment by leggomuhgreggo** [comment]
Hey can you provide a *reduced* test-case? There’s a fiddle you can for in the [Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

**Comment by leggomuhgreggo** [comment]
Also I think this might be a dup of an existing; have you searched existing issues?

**Comment by vkirpa** [comment]
I would like to implementation of a variable width of the image work as well as in the following example. I love your slider. Often I am using the slider for scrolling banners, which always have a different width and height. Many people with this face. Can not you finish the code for this application?

**Comment by vkirpa** [comment]
When the page you want to display from two to five sliders, then use the same script for all the sliders are very comfortable and optimizes the code.
