### ISSUE TITLE
Как исключить пустое пространство при перелистывании

### ISSUE THREAD

**Issue by vkirpa** [kenwheeler/slick#2483]
![1](https://cloud.githubusercontent.com/assets/16415738/17834051/f389cefe-6738-11e6-942c-ec5aeb6e5998.jpg)
Как исключить ситуацию когда последний слайд продолжает двигаться, при нажатии стрелки "NEXT"   и появляется пустое пространство. 

     $(".variable").slick({
	slidesToScroll: 3,
	swipeToSlide: true,
        dots: false,
        infinite: false, 
        variableWidth: true
      });

**Comment by vkirpa** [comment]
спасибо за конструктивное решение.   Понял что при такой поддержке буду искать другие плагины. Спасибо.

**Comment by EvilWolf** [comment]
Аналогично не понял. Вроде вопрос достаточно наболевший. Чем всё решилось то пасаны?

**Comment by leggomuhgreggo** [comment]
Search the issues for variable width. There is a known issue.
