### ISSUE TITLE
Calculates width: Consider the margins

### ISSUE THREAD

**Issue by meneldil** [kenwheeler/slick#2485]
Hello,

I use the example "Syncing Slider" without the "centerMode" for a slider.
I wish the thumbnails take the entire width while having a margin.

Unfortunately, the calculated width does not take into account the margin (.slick-slide).
Here is a drawing to understand what I want:
![schema](https://cloud.githubusercontent.com/assets/8545547/17855896/43dc4db2-687b-11e6-89ec-3cb97f2a2699.jpg)

And here is the code I use:
https://jsfiddle.net/meneldil/scv15hh0/

Is it possible to have this?
Thanks in advance.

**Comment by meneldil** [comment]
@leggomuhgreggo Thank you, but where the original issue is?
I have searched before posting ... :(

**Comment by leggomuhgreggo** [comment]
Hey @meneldil there's a [hefty amount of them](https://github.com/kenwheeler/slick/search?q=margins&type=Issues&utf8=%E2%9C%93). Work around is to nest in a container that has padding, and then add negative margin on the parent container. Not perfect, but works pretty well.

**Comment by meneldil** [comment]
@leggomuhgreggo Thanks! Thank you for the solution.
I updated my jsFiddle. (https://jsfiddle.net/meneldil/scv15hh0/)
No problem to put the negative margin on the div "slick-list"? :o
