### ISSUE TITLE
Slider breaking page on resize

### ISSUE THREAD

**Issue by linzgroves** [kenwheeler/slick#2486]
I have two slick sliders that I'm running on a page in WordPress and when I resize the window to under 991px and then increase the window to a larger size again, it causes the page to freeze and then break. I thought it could be because of the second slider but I tried removing that and still had the page break issue on resizing the window.

I'm not necessarily seeing the break issue on the jsfiddle link below but you should be able to see the issue when resizing the codepen link below. 

I did see a few issues listed in regards to unslick and resizing issues, however, I'm not utilizing unslick so it didn't appear to be a related issue. However, if I'm totally missing something here, please let me know!

====================================================================

http://jsfiddle.net/linzerlion/41jpdzj6/1/
https://codepen.io/linzgroves/pen/KrLWWj

====================================================================

#### Steps to reproduce the problem

1. Decrease window size to below 991px
2. Increase window size until you see the slider freeze and not match the width of your window
3. Page should then break

====================================================================

#### What is the expected behaviour?

Assuming that the slider will be full width again and items will return to their original places at that viewport size. 

====================================================================

#### What is observed behaviour?

Page breaks on Chrome. On Safari, the page doesn't break immediately but the items that should be centered on the page don't return to centered and the page stops responding. See attached screenshot. 

https://cl.ly/3A0e1b2R1Z3e

====================================================================

#### More Details

- Both Safari and Chrome
- 1.6.0
- No

**Comment by leggomuhgreggo** [comment]
Pretty sure `slidesToScroll: 0` is the issue.
