### ISSUE TITLE
how to make three slides

### ISSUE THREAD

**Issue by ildarkhasanshin** [kenwheeler/slick#2487]
but to the extreme slides were narrow?
![img-2016-08-23-11-25-44](https://cloud.githubusercontent.com/assets/8765305/17882561/ea6fd62c-692e-11e6-97ef-c01fc098b8e0.png)

**Comment by leggomuhgreggo** [comment]
centerPadding with centerMode

**Comment by ildarkhasanshin** [comment]
four slides shows 
![img-2016-08-23-18-32-24](https://cloud.githubusercontent.com/assets/8765305/17893678/611b6ba4-6968-11e6-91e0-7cba2e25e21a.png)

$( '.gallery' ).slick( {
        'centerMode': true,
        'centerPadding': '0px',
        'slidesToShow': 3,
    } );

**Comment by ildarkhasanshin** [comment]
add variableWidth: true -> ok

**Comment by leggomuhgreggo** [comment]
Variable width can get tricky.

Please read [this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)
