### ISSUE TITLE
In auto play mode selected Carousel dot stays highlighted after displayed slide has moved on

### ISSUE THREAD

**Issue by thobbsinteractive** [kenwheeler/slick#2488]
> In auto play mode selected Carousel dot stays highlighted after displayed slide has moved on

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. Set a carousel of a few slides with dots showing in auto play mode with pause on hover set. 
2. On a desktop PC click a dot, then move the cursor out of the carousel 

====================================================================

#### What is the expected behaviour?

Carousel continues, when moving to the next slide after the dot you clicked, the dot is cleared/unfocused.

====================================================================

#### What is observed behaviour?

Carousel continues, but when moving to the next slide the dot you clicked is still highlighted. 

Simply changing the updatesDots method to blur the button fixes the problem:

Slick.prototype.updateDots = function() {

        var _ = this;

        if (_.$dots !== null) {
            _.$dots
                .find('li')
                .removeClass('slick-active')
                .attr('aria-hidden', 'true')
                .find('button').blur();
            _.$dots
                .find('li')
                .eq(Math.floor(_.currentSlide / _.options.slidesToScroll))
                .addClass('slick-active')
                .attr('aria-hidden', 'false');

        }
    };

====================================================================

#### More Details

- Which browsers/versions does it happen on?
IE and Chrome

- Which jQuery/Slick version are you using?
1.5.11

- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey this needs a reduced test case like a codepen or jsfiddle. Thanks
