### ISSUE TITLE
Delay displaying image on slide

### ISSUE THREAD

**Issue by niallobrien** [kenwheeler/slick#249]
Hi, I'm using Slick for an Expression Engine site, with the images being created server-side via ce_img. This works fine when using 'fade', but not when using 'slide' as can be seen below. The Slick slider on the left is fading (works fine). You'll notice that on the right, the slide completes before the image is shown.

![slick-bug](https://cloud.githubusercontent.com/assets/1525669/3054903/e0e9399c-e1bb-11e3-827b-7eb9832424ca.gif)

**Comment by kenwheeler** [comment]
Closing. @niallobrien let me know if this issue occurs again
