### ISSUE TITLE
Showing part of last item in infinite mode

### ISSUE THREAD

**Issue by mastrobardo** [kenwheeler/slick#2499]
Hi there, i was wondering how to display half of the las item on a slick carousel ( like asked already in issue #973 ). I can't find any example, just the code on referencing issue .. .but cannot find anywhere the " onSetPosition " function. 

My slick version is 1.5.8, jquery 3 .

Thank you

**Comment by leggomuhgreggo** [comment]
Like Ken said in the issue you're referencing, you probably want to use centerMode (an example of which is in the demo page), but I think that forces infinite; so, if you didn't want infinite, you'd have to modify the CSS a bit.  Good luck.
