### ISSUE TITLE
Mobile first breakpoint counting issue

### ISSUE THREAD

**Issue by inferusvv** [kenwheeler/slick#2503]
In CSS when create your layout with mobile first approach your write for example

```
@media (min-width: 768px) {
    /* styles from 768px */
}
```

It means that styles will be applied when width of screen is 768px inclusive and more

But in slick slider if set `mobileFirst: true` and  write

```
responsive: [
    breakpoint: 768,
    settings: {
        // settings
    }
]
```

settings will be applied only from **769px** breakpoint. Not **768**

**Comment by leggomuhgreggo** [comment]
Hey @inferusvv thanks for the issue. What you're saying makes sense; good catch. Would you mind making a fiddle to demo it there's one you can fork in the [Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). PR would be great too if you're feeling ambitious.

Thanks again.
