### ISSUE TITLE
how to center item and some

### ISSUE THREAD

**Issue by craigcosmo** [kenwheeler/slick#2508]
this is how I want it to be displayed

<img width="1038" alt="screen shot 2016-09-07 at 5 43 25 pm" src="https://cloud.githubusercontent.com/assets/538657/18309499/f86c2432-7523-11e6-8b66-2d59cf4ad854.png">

this is how I got so far

<img width="819" alt="screen_shot_2016-09-07_at_5_47_22_pm" src="https://cloud.githubusercontent.com/assets/538657/18309669/bed88dd6-7524-11e6-8970-1ac96c322da5.png">

What I want to do is show one center image, and half of the right and left images,

Problem: In my solution, I was able to show one center image, but the right and left image only show little, I want them to show more

Here is my code:

http://jsfiddle.net/fp1kcah6/

**Comment by leggomuhgreggo** [comment]
Check out centerPadding
