### ISSUE TITLE
Slider Syncing : Localized synchronization

### ISSUE THREAD

**Issue by meneldil** [kenwheeler/slick#2511]
Hello,

I have a new problem with the "Slider Syncing".
If I have two of them, the four sliders are synchronized (when clicking on the thumbnails for example):
https://jsfiddle.net/meneldil/5y4synv7/

How to ensure that synchronization is located?
Of course, it is imperative that these sliders share the same class, so I would like to avoid putting `slider-1`, `slider-nav-1` and `slider-2`, `slider-nav-2`.

I tried to put in `asNavFor`:
`$(this).siblings('.slider-nav')`
`$(this).siblings('.slider')`

... without success...

**Comment by meneldil** [comment]
I found a solution with `slickSetOption`! :)
https://jsfiddle.net/meneldil/63j9ypvL/

**Comment by leggomuhgreggo** [comment]
I think distinguishing the slider selectors should also work. Glad to hear you solved it!
