### ISSUE TITLE
slidesToShow option does not work when fade is enabled

### ISSUE THREAD

**Issue by GregOnNet** [kenwheeler/slick#2514]
Hi,

when I set `fade: true` and `slidesToShow: 4` only one slide is shown.

===

#### Steps to reproduce the problem
> [Plunkr - Reproducing the behavior](https://plnkr.co/edit/8aKFdXxtLHn9Wrj7dTpi?p=preview)

In slick's options:
1. Set `fade: true` 
2. Set `slidesToShow: 4` 

===

#### What is the expected behaviour?

- 4 slides should be displayed

===

#### What is observed behaviour?

- 1 slide is displayed

===

#### More Details

- Which browsers/versions does it happen on?
  - Chrome 52, Firefox 48
- Which jQuery/Slick version are you using?
   - jQuery 3, slick 1.6.0

Thanks in advance
Gregor

**Comment by leggomuhgreggo** [comment]
Hey @GregOnNet that's a deliberate limitation. Perhaps someday. Thanks!

**Comment by leggomuhgreggo** [comment]
Found the issue where this is discussed: #830
