### ISSUE TITLE
Use peer dependency for jquery

### ISSUE THREAD

**Issue by micha149** [kenwheeler/slick#2515]
I think it is a problem to have a dependency to jquery in this project. When installing `slick-carousel` and also a diffrent jquery version, I will have two diffrent jQueries bundled in my final Javascript file.

Npm already brings a feature called [peer dependencies](https://docs.npmjs.com/files/package.json#peerdependencies) which [resolves this problem](https://nodejs.org/en/blog/npm/peer-dependencies/). It would be great if we can patch the package.json and remove the hard dependency to jquery.

**Comment by leggomuhgreggo** [comment]
Hey @micha149 thanks for the issue. I appreciate your point; to me it's a question of which is the greater evil, undeclared dependency or potential dependency version overlap. My sense is that it's the former. The v2 branch drops jquery altogether, which is on its way.

**Comment by micha149** [comment]
A peerDependency is not an undeclared dependency. You will get a warning if you don't have jquery in your projects dependencies or in a wrong version. But you will not end in a mess of multiple jqueries in your project…

**Comment by leggomuhgreggo** [comment]
If there's a way to just declare a peer dependency and not lose the definitions for build systems that don't use NPM, then I think that'd be great.
