### ISSUE TITLE
How to create thumbnail carousel with image previews?

### ISSUE THREAD

**Issue by vanloc0301** [kenwheeler/slick#2518]
I want after the click to a thumbnail in a slideshow. It also appears image previews.

Like this:
                                  
![capture](https://cloud.githubusercontent.com/assets/4168981/18624476/3cf8ff4c-7e72-11e6-89a3-e1d5b8759477.PNG)

When a user clicks a thumbnail it will show this image previews.

I watch all demo of Slick but not found any example like this.

Thanks.

**Comment by leggomuhgreggo** [comment]
You'll probably want to use customPaging.

closing support request
