### ISSUE TITLE
Slick clear attr style after change options on the fly

### ISSUE THREAD

**Issue by verprox** [kenwheeler/slick#252]
I have this structure:

div class="slider"
  div class="slide" style="background-image:url(images/slide-1.jpg)"
  div class="slide" style="background-image:url(images/slide-2.jpg)"
  div class="slide" style="background-image:url(images/slide-3.jpg)"
/div

On first init everything ok, but after some time, I need to reinit and doing this:
$('.slider').slickSetOption('autoplay', false, true);

After this, slick remove my style="background-image:url(images/slide-1.jpg)"

**Comment by maLikiz** [comment]
The problem is reproduced again if set settings in responsive

My case:
```js
$('.slider').slick({
    prevArrow: '<div class="icon-arr-4-l"></div>',
    nextArrow: '<div class="icon-arr-4-r"></div>',
    dots: false,
    variableWidth: true,
    centerMode: true,
    responsive: [
      {
        breakpoint: 767,
        settings: {
          variableWidth: false,
          centerMode: false,
        }
      },
    ]
  })
```

```html
<div class="slider>
<div class="item" style="background-image: url(image1.png) />
<div class="item" style="background-image: url(image2.png) />
</div>
```
