### ISSUE TITLE
Goto on scroll

### ISSUE THREAD

**Issue by fr-olivier** [kenwheeler/slick#2522]
Hello,

This is rather a question than a bug report. Is it possible to go to prev or next slide when the user scrolls above the slider? I have no idea where to start, any idea welcome!

Thanks a lot,
François

**Comment by leggomuhgreggo** [comment]
Listen for scroll event (want to debounce), test for condition, use the slickNext/slickPrev methods to trigger a slide scroll. Hope that helps.

Closing: Support Request
