### ISSUE TITLE
How to show last slider when use it

### ISSUE THREAD

**Issue by godoakbrutal** [kenwheeler/slick#2525]
Hi I have a question.

Is slick slider can set it to show last slide when use it

Ex. I have 5 slides

In the normal way It's will show first slide (1)
1 -> 2 -> 3 -> 4 -> 5

But, I want to show last slide first (5)
The question is how to config it to show last slide for first slide
 Please help.

**Comment by leggomuhgreggo** [comment]
Probably something like this:

```
$('.my-slider').slick({
initialSlide: $('.my-slider > .my-slide').length - 1
});
```
