### ISSUE TITLE
 Clicking on the navigation buttons initiates vertical scrolling to slide in Crome

### ISSUE THREAD

**Issue by AndreyCursin** [kenwheeler/slick#2528]
>  Clicking on the navigation buttons initiates vertical scrolling to slide in Crome
====================================================================

#### Steps to reproduce the problem
en
1. I created a slide in full window size with the top margin for the floating main menu (margin-top: 80px) 
2. When the user clicks on the button "next/prev slide" window to scroll to the 80px! and a window is set on the border of the slide. 
3. Only in Chrome (Firefox is fine)
Sorry for my English.

rus
1. Я создал слайдер в полный размер окна с верхним отступом для плавающего главного меню(margin-top:80px) 
2. Когда пользователь нажимает на кнопку "следующий слайд" окно скролит на эти 80px! и окно устанавливается на границе слайда а не слайдера. 
3. Только в Chrome (Firefox работает отлично)

#### More Details

- Chrome  53.0.2785.116 m (64-bit)
- Slick Slider Version: 1.5.7

**Comment by AndreyCursin** [comment]
en
Or if you scroll below the upper edge of the slider and press the button "next/prev slide" - the window is raised to the top of the slide.

rus
Или если прокрутить ниже верхней границе слайдера и нажать на кнопку "следующий/предыдущий слайд" - окно поднимается до верха слайда.

example http://ra-germes.ru/about/customers/kc-meridian/

**Comment by leggomuhgreggo** [comment]
Hey I'm not able to recreate the issue on that site. For possible bugs, we ask that you recreate your issue in a reduced test-case environment like a jsfiddle or a codepen. There's one in the contributions markdown. Thanks!

Closing, pending test case
