### ISSUE TITLE
Carousel showing only last slide

### ISSUE THREAD

**Issue by MeenaSuna** [kenwheeler/slick#2529]
Primarily Carousel will be inside a hidden div(display:none). at that time i'll add all slides using your add or remove functionality. later when i click a button that div will show(display: block). but when slide shown it shows only last slide. after that if click next button it shows all slides. 

Is there way to fix this?

I have tried this in http://kenwheeler.github.io/slick/ by changing slick css to display none. and try adding slides in add or remove section. there also it showing last slide only.

Thank you

**Comment by leggomuhgreggo** [comment]
Hey can you provide a test-case? There’s a fiddle you can for in the [Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

Closing pending test case
