### ISSUE TITLE
Slides become blurry in WebKit browsers because of CSS transform: translate(......)

### ISSUE THREAD

**Issue by Ian-Y** [kenwheeler/slick#2531]
WebKit browsers are incorrectly rendering elements blurry if CSS `transform: translate(......)` is applied. This issue becomes even more obvious on text paragraph and on mobile devices.

Because Slick uses `transform: translate(......)` to achieve animation, that makes the aforementioned issue happens.

A workaround might be adding an option to let WebKit browsers use CSS `left` instead of CSS `transform: translate(......)` to achieve animation.

**Comment by leggomuhgreggo** [comment]
Hey I think this is covered in #2275

You can always set useTransforms to false

**Comment by Ian-Y** [comment]
@leggomuhgreggo Setting `useTransforms` to false does not solve the issue for me. And I also don't see an option called `useTransforms` in the documentation or in source code. Could you advise?

**Comment by leggomuhgreggo** [comment]
Sorry useTransform

**Comment by Ian-Y** [comment]
@leggomuhgreggo Thank you. That works.

By the way, currently [line 41-49 of slick.css](https://github.com/kenwheeler/slick/blob/master/slick/slick.css#L41-L49) still makes WebKit browsers blurry. Although we can manually overwrite that CSS rule, it would be more convenient if the plugin could do that for us when `useTransform` is set to false.

**Comment by exetico** [comment]
@Ian-Y - I have the same issues with line 41-49 (Chrome). Did you find any solution?

**Comment by Ian-Y** [comment]
@exetico Please try overwriting [line 41-49 of slick.css](https://github.com/kenwheeler/slick/blob/master/slick/slick.css#L41-L49) or setting `useTransform` to `false`.

**Comment by exetico** [comment]
@Ian-Y - What a reply time!:-D I just removed slick.css and going with .slick-slide{display:none;}
.slick-slide.slick-current{display:inherit;}.
I didn't use the pre-style.
`useTransform` didn't fix the problems :-)

**Comment by Ian-Y** [comment]
@exetico It's good to know that.
