### ISSUE TITLE
Slider Syncing: sticky footer

### ISSUE THREAD

**Issue by iddqdoom** [kenwheeler/slick#2532]
There's an issue with 'Slider Syncing' theme. Footer isnt sticking to the slider container (adaptive height).
http://codepen.io/iddqdoom/pen/ZpZOZO

**Comment by leggomuhgreggo** [comment]
That code pen doesn't work for me, but what you're describing doesn't sound like a bug with the repo; sounds like a CSS issue with your particular implementation. 

[Check out the Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

Closing: Support request, invalid test-case
