### ISSUE TITLE
Slick does not initialize properly with jquery mobile dynamic loaded pages

### ISSUE THREAD

**Issue by fatfantasma** [kenwheeler/slick#2533]
Hello,
Thanks for a great plugin.  However, I'm having issues with my jquery mobile app and Slick.  I am using dynamic (ajax loaded) pages and Slick fails to initialize properly.  I believe it has something to do with initializing the Slick element when the page is loaded but NOT shown (hidden).

I found this similar issue here:
https://github.com/kenwheeler/slick/issues/187

When I load the jquery mobile page BUT before it is shown I call 

        $(".mp-slick-slider")..slick({
              mobileFirst: true,
              arrows: false
            }
        );

This initializes my slick but the 'width's of the slides are set to 0.  Probably because the page was hidden when called.

I can call   $('.mp-slick-slider').slick("refresh");  after the page is shown and Slick will show my images correctly however it has a undesired effect of 'popping' in the slick images and adjusting the html down to make room initially.

I would like slick to be properly setup before I show the page so the jquery mobile fade page transition is nice and smooth. I have the same slick images on each page.

I was able to do a test hack to verify the problem and sort of got it to work by doing right after call the the initial slick setup as stated above:

        var w = $(window).width();
        $(".slick-slide.slick-current.slick-active").css({"width": w});

It works for the first slide but fails on the the second until your code refreshes all slick slides as I scroll through them..

I'm a noob at jquery/javascript and was wonder if it was possible to modify your plugin so it initializes the width of the slick slides based on the current window width that is shown and not the incoming dynamic html that is not show yet?

I hope I explained myself correctly and you  or somebody has an idea how to fix :)
thanks

**Comment by leggomuhgreggo** [comment]
I think you can do either `$slider.slick('setPosition')` or `$slider.slick('reInit')`

Hope that helps
