### ISSUE TITLE
How to refresh slick carousel with new option ?

### ISSUE THREAD

**Issue by jimmyphong** [kenwheeler/slick#2535]
Example we need load new mode when click an element 
`var slick = $('.myslick').slick({
    vertical : false
  });`

and when click a link 
`$('#changemod').on('click', function(e){
e.preventDefault();
slick = new slick({
vertical: true
})
})`

like this ! can i do it with slick !
Thanks

**Comment by leggomuhgreggo** [comment]
Check out the `slickSetOption` method. Best of luck!

Closing: Support Request. [See Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)
