### ISSUE TITLE
iPhone 6 plus Error

### ISSUE THREAD

**Issue by austinbenerdy** [kenwheeler/slick#2537]
> There is an issue with iPhone 6 Plus that prevents the page from loading. 
# 
###### `http://codepen.io/anon/pen/NRjpwA`

Using both of the example codes, as well your jsfiddle `http://jsfiddle.net/simeydotme/fmo50w7n/` , I was able to reproduce the issue inside of Browserstack. Whenever a page with Slick on it is opened on an iPhone 6 plus, it crashes whatever browser it is using.

**Comment by simeydotme** [comment]
6 plus has terrible memory management, possibly hardware failure...

**Comment by austin-codes** [comment]
If it is every iPhone 6 Plus, then does it still qualify as hardware failure? Are there no reasonable solutions to this issue?

**Comment by zanderwar** [comment]
Personally I couldn't replicate this issue (thankfully), my accomodation application where slick is used upwards of 20 times per page of results had no issues rendering, nor did it crash at any point using browserstack with **iPhone 6 plus**

**Comment by austin-codes** [comment]
Just an update: 

Turning off the fade option allows for it to work on the iPhone 6 plus.
