### ISSUE TITLE
Issue with slick-current CSS class

### ISSUE THREAD

**Issue by arrancscott** [kenwheeler/slick#2541]
I have an issue whereas every time I remove an image with slickRemove it sets .slick-current back to being the first slide in the slideshow.

eg. If i'm on the 5th image and I call slickRemove with the slide index I'd expect the slick-current class to be applied to the next/previous slide - instead it gets applied to the first element.

Here is the code I'm using to init slick.

```
$('.slideshow').slick({
 dots: true,
 infinite: true,
 speed: 500,
 fade: true,
 cssEase: 'linear',
 adaptiveHeight: true,
 mobileFirst: true
});
```

**Comment by leggomuhgreggo** [comment]
Hey, when you create issues, please make a test-case in a fiddle or a code pen. There's a jsfiddle you can fork from the [contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), which have some other neat tidbits.

My thoughts on your issue are that you can get slickCurrent, and use the slickGoTo method but I agree that's not ideal. If you make a test case, I can put some light on it. 

Thanks
