### ISSUE TITLE
Flickering/blank slide issue

### ISSUE THREAD

**Issue by pwavg** [kenwheeler/slick#2542]
When setting up a synced slick carousel I'm experiencing flickering/skipping slides when using more then 4 thumbnails.

Here's a [codepen ](http://codepen.io/pwavg/pen/vXmoXQ/) that shows the issue. (Click the fitch thumbnail a couple of times) I tried solving this with answers from the github repo but I can't seem to fix the issue myself. Any help will be appreciated.

This seems to happen on Chrome, Firefox & IE(10/11)

**Comment by zanderwar** [comment]
Click the **fifth** thumnail a couple of times*

Can reproduce this issue on chrome Version 53.0.2785.116 (64-bit)

**Comment by leggomuhgreggo** [comment]
Hunh, Im not able to reproduce on that codepen. A lot of times this happens because of styles applied to slick-active/slick-center and infinite clone transfer lag. Holler back if you think there's still a bug here.

Thanks

**Comment by pwavg** [comment]
I still believe it's a bug. In a updated codepen I applied no styles but the slick.min.css from the libs. It looks like it only happens when you go from any slide around all of the pictures to the second slide and beyond.

Example click on 5 > 3
