### ISSUE TITLE
How to disable swipeMove?

### ISSUE THREAD

**Issue by risker** [kenwheeler/slick#2543]
I'm running slick with some custom functionality built on top of it. I'd like to disable swipeMove (so that the slides would not move on swipe), but retain the swiping functionality (so I could still move between slides by swiping). Is there a way to do this? The swipe event is triggered too late to prevent that behavior.

Right now I'm leaning towards building a custom swipe handler for this but it seems like it could be an option in the settings.

**Comment by leggomuhgreggo** [comment]
Hey @risker, check out [the settings](https://github.com/kenwheeler/slick#settings)
