### ISSUE TITLE
item transition effect in infinite mode

### ISSUE THREAD

**Issue by mike623** [kenwheeler/slick#2544]
when using infinite mode. last item will be cloned. When we move to last item, slick will 'redirect'  us from last index to first index item. However this action will terminate item transition effect (e.g scale, opacity)

here is codepen
[http://codepen.io/mike623/pen/mArdAm](http://codepen.io/mike623/pen/mArdAm)

**Comment by leggomuhgreggo** [comment]
Yeah, the grouping of transforms bums me out. I think your best bet is to factor your scale in a nested element. Don't think there's much the library can do about transform overwrites.

Thanks!
