### ISSUE TITLE
Feature Request: Smart Arrows / Dots.

### ISSUE THREAD

**Issue by Ezence** [kenwheeler/slick#2545]
When using variable width slides in which multiple can fit within the carousel viewable width arrows /dots are redundant user interactions that could cause confusion. It would be preferable for arrows / dots to appear when slick has slides that require scrolling, thus require user interaction.

**Comment by leggomuhgreggo** [comment]
Hey @Ezence can you make a fiddle to demonstrate?

Thanks!

Closing pending test case.
