### ISSUE TITLE
Event when you have only 1 slide

### ISSUE THREAD

**Issue by dimir** [kenwheeler/slick#2546]
Hi,

First of all, thank you very much for your work, this is a great product and it works like a charm! Thanks!

This is a feature request. I'd like to get an event on a slide change. When event occurs I'm checking if there is a need to do something with the slides. "beforeChange" works perfectly fine for me. However, a problem occurs when I have just one slide in a show, there is no event in this case.

====================================================================

#### jsfiddle

http://jsfiddle.net/fmo50w7n/637/

====================================================================

#### Steps to reproduce the problem

1. Use the jsfiddle above.
2. Notice how alert is not happening.
3. Add another slide "<div>slide2</div>" and hit "Run".
4. Watch how alerts start to show.

====================================================================

#### What is expected behaviour?

Although I understand there is no slide change event when you have just one slide I'd like to somehow get an alert when slideshow is over, even when I have just one slide.

====================================================================

#### What is observed behaviour?

The observed behavior is correct, I think I'm just missing some feature here. :-)

====================================================================

#### More Details

- Chromium browser (on a Gnu/Linux)
- Slick Version: 1.3.1
- jQuery v1.11.0
- jQuery Migrate v1.2.1

**Comment by leggomuhgreggo** [comment]
Hey can you factor your fiddle to show it not working with `beforeChange`?

My initial reaction is "Why would you want to change when there's only 1 slide?" Even so, I'll try to get it on the radar for when we refactor that module.

Closing pending fiddle update

**Comment by dimir** [comment]
My slides are dynamic. They are added/removed during the run of the show by separate process. The slides are in the database. The workflow is the following:

- load the slides from the database and start the show
- on a slide change I use AJAX to check if some slide changed (added/removed) in the database
- if it is I reload the whole show

So I need any kind of show interruption even in case of 1 slide, in order to check the slides in the database. Do you know of anything that I could use?
