### ISSUE TITLE
Lazy loading doesn't work with responsive images ("srcset" attribute)

### ISSUE THREAD

**Issue by stephenjbell** [kenwheeler/slick#2547]
I love lazy loading in Slick Slider, but it doesn't work correctly if you're using responsive images with a "srcset" attribute, because modern browsers override the "src" with a value from "srcset".

Right now, Slick gets the value of "data-lazy" and puts it into "src" when the slide is navigated to. Would it be possible to load "data-lazysrcset" into the "srcset" attribute as well?

**Comment by leggomuhgreggo** [comment]
Hey @stephenjbell, It's in the works. Check out #1661.

Thanks!

Closing: duplicate
