### ISSUE TITLE
Conflicts with mootools

### ISSUE THREAD

**Issue by neonwired** [kenwheeler/slick#2550]
Running _.$slider.trigger('setPosition', [_]); causes mootools setPosition method to be called (http://mootools.net/core/docs/1.6.0/Element/Element.Dimensions#Element:setPosition)

====================================================================

Just add https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js as a source and run to see the error

#### More Details

- Which browsers/versions does it happen on? Chrome
- Which jQuery/Slick version are you using? 1.6.0
- Did this work before? before what?

**Comment by leggomuhgreggo** [comment]
My recollection is that `$slider.slick('setPosition')` is how that works, but it's been a minute since I've used it.

**Comment by tomothumb** [comment]
I've just faced same issue.
method unslick

**Comment by Knurg** [comment]
I have the same problem. As soon as you have slick and mootools both loaded the system crashes. Changing the line in slick to  $slider.slick('setPosition') does not work.

**Comment by sandros87** [comment]
I have the same issue, how can you solve this?

**Comment by Knurg** [comment]
I could not find any way :(

**Comment by sandros87** [comment]
I _"solved"_ it by changing the name of the function setPosition in mootools-core.js to setPosition1 (for example) so that it won't conflict with slick/jquery. Of course you have to be sure you're not using that function with mootools...

**Comment by Knurg** [comment]
This is not very convenient... :/

**Comment by irbian** [comment]
I found the same problem in Joomla. @sonosergio changed the name of the setPosition method inside slick on this issue https://github.com/kenwheeler/slick/pull/2191, but I still don´t understand why mootools triggers

**Comment by prashgv** [comment]
Worked out well for me after changing 'setPosition' to 'setPosition1' in all the places inside slick js file

**Comment by PenguiN560** [comment]
Is any other solution to solve this problem without hacks one of fw?
