### ISSUE TITLE
Connected sliders' last slide dropping down

### ISSUE THREAD

**Issue by maxbeech** [kenwheeler/slick#2552]
Great slider - thank you!
I'm having an issue that I assume is a bug. I have two connected slick sliders, but even though they have the same number of slides, the last slide on one of the sliders seems to just drop down and not show where it should. Any ideas please?

====================================================================

jsfiddle: https://jsfiddle.net/beech/kygsq6f2/3/

====================================================================

#### Steps to reproduce the problem

Go through the slider till the end.

====================================================================

#### More Details

- Which browsers/versions does it happen on? -> Chrome
- Which jQuery/Slick version are you using? -> Newset for both
- Did this work before? -> No

**Comment by leggomuhgreggo** [comment]
My guess is it's something to do with the custom styles you have. If you reduce the test case to where its just two sliders, joined with as nav for, and the bug still exists then holler back with the fiddle and we'll go from there. If it doesn't exist in the reduced case, I suggest incrementally adding the features of the one that's busted to see what's going on. Good luck.

**Comment by maxbeech** [comment]
Thanks very much for the response! I have looked into the CSS more closely and you're right! Looks like even an extra pixel of width caused by a border applied to the current slide (but not all other slides) causes the issue.
