### ISSUE TITLE
Arrows not showing

### ISSUE THREAD

**Issue by Noon2Dusk** [kenwheeler/slick#2554]
When I use slick for my slider this line is missing when I inspect my page:
<button type="button" data-role="none" class="slick-prev slick-arrow" aria-label="Previous" role="button" style="">Previous</button> as well as the line for Next

After checking previouse issuse I can say that it's not the problem of not giving slick enough space to show the arrows.

====================================================================

###### `[  http://jsfiddle.net/wkx84kjr/  ]`  

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?
I expected that when I set arrows: true, I'd get arrows
...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on? Current version of chrome
- Which jQuery/Slick version are you using? Slick 1.6.0 
- Did this work before? No

**Comment by leggomuhgreggo** [comment]
Hey this isn't a bug with the slider, it's just a byproduct of the default absolute positioning of arrows in the (non-required) slide-theme styles. Feel free to modify for your implementation. Thanks.
