### ISSUE TITLE
Return Slick class from source file

### ISSUE THREAD

**Issue by MikeDevice** [kenwheeler/slick#2559]
Now `Slick` class is instantiated in `$.fn.slick = function() {}`. So it's not possible add custom method to class, but if make `return Slick;` at the file end, this feature will be available.

#### What is the expected behaviour?

```
var Slick = require('slick-carousel');

Slick.prototype.doSomething = function() {
   console.log('doSomething');
};

var $slides = $('.slides').slick();
$slides.slick('doSomething');
```

**Comment by leggomuhgreggo** [comment]
Pretty sure you should be able to modify the prototype of the slick method on the window object. Hope that helps.

**Comment by MikeDevice** [comment]
@leggomuhgreggo I can't do this. Please check this [jsFiddle](https://jsfiddle.net/4eoe76zf/) out. 
Also I didn't find Slick assignment to window in source code, just only [this line](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L30)

**Comment by leggomuhgreggo** [comment]
Hey, my mistake. I messed around with it for a little bit. Interesting to learn about. Looks like it's pretty solidly enclosed, I assume for scoping/security, but pretty clearly deliberately. Don't see that changing. Best of luck.
