### ISSUE TITLE
pauseOnHover  take some time to pause 

### ISSUE THREAD

**Issue by jothikannan** [kenwheeler/slick#2560]
> autoplay slider with pauseOnHover is not working immediately, it taking until the animated image reaches the bound of the sliders

====================================================================

**Comment by leggomuhgreggo** [comment]
That fiddle doesn't appear to work. Sounds like you might be trying to get "smooth scrolling" like a marquee, which can only be accomplished through a linear transition speed hack the downside of which is that pause events wont register until after a cycle. Hope that helps.

Closing: Duplicate/Support Request
