### ISSUE TITLE
if slidesToShow is not a whole number the initial 

### ISSUE THREAD

**Issue by antonk52** [kenwheeler/slick#2561]
I am trying to create a slider much like on the slick demo with center mode, yet I need to fully display only the active slide while left and right ones are only peeking some of their parts on the sides. I've been trying to achieve this by setting slidesToShow to an integer between 1 and 2, however instead of a wanted result it would mess up the initial transition of the slider as the slider scrolls the correct length and the rest of the functionality behaves as expected.

====================================================================

##### [Js fiddle example](https://jsfiddle.net/7s3pnz10/)
Used scale to illustrate that active slide is always shifted to the right

====================================================================

#### Steps to reproduce the problem

1. Mark up a slider with a few same size images
2. Initiate a slick slider and pass a number between 1 and 2 as an option into the slidesToShow
3. SThe active slide is shifted to the right ie not centered

====================================================================

#### What is the expected behaviour?

To have active slide centered

====================================================================

#### What is observed behaviour?

Active slide is shifted to the right

====================================================================

#### More Details

- Which browsers/versions does it happen on?
-- chrome 52
-- firefox 49
-- safari 10

- Which jQuery/Slick version are you using?
jquery 3.1 or jquery 1.12, both with slick 1.6

- Did this work before?
Did not check. I would like to have this as a feature request

**Comment by leggomuhgreggo** [comment]
Hey I'm not sure I understand how what you're trying to accomplish is different than the center mode default, with center padding, like this: https://jsfiddle.net/Lnjvtf7j/
