### ISSUE TITLE
Customizing Slick JS

### ISSUE THREAD

**Issue by saadkhaan** [kenwheeler/slick#2562]
> Customizing the slick slider.

====================================================================

###### `https://goo.gl/KXi2gW`  Demo
![slick](https://cloud.githubusercontent.com/assets/14808194/19287930/476efabe-901d-11e6-8eaf-c9796cea2cbe.jpg)

====================================================================

I would like to add a rounded background to the arrows with a title bar.
My CSS code is:
`      .slick-prev, .slick-next{top: 79%; z-index: 999;}
       .slick-prev{left: 19.5%;}
       .slick-next{right: 75.5%;}
       .slick-prev:before, .slick-next:before {font-size: 30px; color: #fff;}
       .slick-prev:after {content: "|"; display: block; height: 30px; width: 2px; background: #222222;
       position: absolute; top: 0; right: -80%;}
      .slidecaption{
        background: #333;
        width: 420px;
        height: 40px;
        border-radius: 8px;
        position: relative;
        color: white;
        padding: 10px 50px;
        bottom: 115px;
        left: 300px;
        z-index: 9999;
        }`

HTML:
`      <div class="row slides" style="position: relative;">
        <div>
          <img data-lazy="images/car.jpg" class="img-responsive" title="My Title">
        </div>
        <div>
          <img data-lazy="images/car1.jpg" class="img-responsive"
      title="My Title">
        </div>
      </div>`

Javascript:
`         $(".slides").slick({
          lazyLoad: 'ondemand',
          cssEase: 'linear',
          dots: false,
          infinite: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          centerMode: false
          });
          $('.slides .slick-slide > img').each(function(){ 
          if ($(this).attr('title')){
            var slideCaption = $(this).attr('title');
            $(this).parent('.slick-slide').append('<div class="slidecaption">' + slideCaption + '</div>');
          }
        });`

Please see the attached image, this is what I would like to have as caption/title background.

Urgent help needed.

**Comment by leggomuhgreggo** [comment]
Hey @saadkhaan. Were volunteers here trying to make a neat open source slider and the use of our time is prioritized towards improving the slider code. I try to leave support requests open for a little while in case someone wants to be generous and assist, but, as a matter of policy, we use this forum to track bugs/enhancements, and close support requests. Please see the [contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) for more information. Thanks.
