### ISSUE TITLE
Problem with centermode and slidesToScroll

### ISSUE THREAD

**Issue by verbimus** [kenwheeler/slick#2563]
When I use the centerMode = true property, the carousel always moves of 1 to 1, even when I set slidesToScroll = 7, for example. Is it possible to use both properties?

**Comment by studentIvan** [comment]
You can try my fork https://github.com/studentIvan/slick and write some hacks but is not a good solution.

**Comment by leggomuhgreggo** [comment]
For now, this is a deliberate limitation, but it's definitely an enhancement that's being considered. Appreciate y'all's efforts on it.
