### ISSUE TITLE
Tabbing

### ISSUE THREAD

**Issue by theneujersey** [kenwheeler/slick#2564]
> short description of the bug / issue, provide more detail below.

We would like to make the slides accessible via tabbing. Would you be able to provide support for that, like making all visible slides on the page tabindex=0?

**Comment by leggomuhgreggo** [comment]
Hey, it's a feature that's tangled with a11y reqs. I have it in mind to organize those issues so to form a more comprehensive picture of our latitude, and will consider this in that evaluations. Thanks
