### ISSUE TITLE
Configuration object does not work because Boolean("false") produces true

### ISSUE THREAD

**Issue by draehal** [kenwheeler/slick#2565]
In Slick.js, you use Boolean(scope.arrows) with arrows declared as "@" on the scope. This produces a boolean literal of 'true' even when the string "false" is given as parameter.  I would suggest using a custom parser, or if you expect a modern browser JSON.parse(scope.arrows).   

The effect is that any configuration entry on the conf object that uses a Boolean will always be true

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean

**Comment by leggomuhgreggo** [comment]
Hey @draehal can you provide a test case where this is occurring. There's a fiddle you can fork in the contributions.md. Thanks.

Closing pending test case.

**Comment by draehal** [comment]
https://jsfiddle.net/TheCodeDawg/2eyz0yq1/

**Comment by leggomuhgreggo** [comment]
Haha, sorry to be unclear--didn't mean to ask you to demo strings being true--I was hoping for a demo showing the bug with a slick implementation so that we can test PRs against it. Definitely helpful in getting things resolved. Appreciate your creating the issue and taking the time.

Thanks

**Comment by draehal** [comment]
OH NO, How did I put a defect against this repository!  Im so sorry. I thought I was in the angular-slick repository.  You can just throw this one away!   <Devon sheepishly walks away with tail between legs>

**Comment by leggomuhgreggo** [comment]
No worries. Thanks
