### ISSUE TITLE
Part of next image display in a single slide on IE11 randomely

### ISSUE THREAD

**Issue by lvishal51** [kenwheeler/slick#2567]
After 2-3 clicks on next button part of next image display in a single slide on IE11 randomely which display properly on chrome & firefox.
====================================================================
====================================================================
====================================================================
It should display one slide at a time i.e one image at a time
====================================================================
It is displaying image with part of next image
====================================================================

It is coming randomly for the random images.It's displaying properly for the same image before which error comes.On IE-11 browser has the problem.I m using Version: 1.5.8.

**Comment by leggomuhgreggo** [comment]
Hey @lvishal51 please review the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). This needs a reduced test case. Thanks
