### ISSUE TITLE
problem with first transition inside active slide

### ISSUE THREAD

**Issue by kuzkokov** [kenwheeler/slick#2568]
hello, I have a problem with css transition that depends on activity of slide.
the problem is next: first active slide somehow created with class "slick-active" from the beginning. because of that, elements, that should be animated when slide becomes active, on the first slide take the final state right away.

example on fiddle `[  http://jsfiddle.net/fmo50w7n/663/  ]`  

====================================================================

so, i'm curious ‒ is there a way to do so that "slick-active" adds to slide after full page load? or maybe there is some other way to fix the problem.

btw, thank you for such a good slider, in everything else it's perfect

**Comment by leggomuhgreggo** [comment]
You could use `$(window).on('load', function(){...slick stuff...})`

Thanks :)

**Comment by kuzkokov** [comment]
well, as I understand (and can see), it's not helping, because the slick itself create new elements **after** its called.

**Comment by kuzkokov** [comment]
well, as I understand (and can see), it's not helping, because the slick itself create new elements **after** its called.
