### ISSUE TITLE
Only one slide

### ISSUE THREAD

**Issue by BlascoGonzalez** [kenwheeler/slick#2569]
I'm trying to implement an easy horizontal carousel, only one slide to show and scroll. What I'm doing wrong? If one image is thinner then 2 images are displayed.
Thanks very much

`      $(".variable").slick({
	slidesToShow: 1,
	centerMode: true,
        dots: true,
        infinite: true,
        variableWidth: true,
	autoplay: true,
	autoplaySpeed: 2000,
	speed: 300,
      });
`

**Comment by leggomuhgreggo** [comment]
Hey @BlascoGonzalez check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). There's a fiddle  in there that you can fork to mess around with. If your settings are working there then you might have a resource dependency issue where the JS/Styles aren't applying properly. Best of luck.

**Comment by typoworx-de** [comment]
For me there is also an issue with this. If the slider is only provided with a single item it is not visible due to the CSS transform3d moving it out of viewport.
