### ISSUE TITLE
How can i move slider in mouse scroll

### ISSUE THREAD

**Issue by rijosh** [kenwheeler/slick#2571]
Is there any way to moves the slide on mouse scroll not swipe, i want a vertical slider without autoplay and when i scroll the mouse the slides will move.

====================================================================

can u gimme a js fiddle link. advance thanks

**Comment by leggomuhgreggo** [comment]
Hey @rijosh there's a fiddle link in the contribution guidelines for you to play around with. Essentially you'll want to grab a scroll event when the mouse is over the slider and tie them to the slick methods for next/prev. Best of luck.

**Comment by rijosh** [comment]
Actually i want vertical slider with mouse scroll. when mouse scrolling on over the slider i need to move the slides depend on the mouse scroll. if i scroll mouse down the slide move to bottom and when i scroll the mouse up the slide should move on top direction. if u are provide a fiddle or codepen link that would be great.... thanks advance
