### ISSUE TITLE
Sample code for gradually loading thousands of slides

### ISSUE THREAD

**Issue by JonathanAquino** [kenwheeler/slick#2573]
I would like to use slick to display potentially thousands of slides. Obviously I do not want to load all of the slides at once. I would like to load, say, 10 at a time, as soon as the user nears the end of the current slides.

I have been looking for sample code to do this, but haven't had much luck finding any on the web. Surely other people have used Slick to display an album of several thousand photos?

Could you point me to some documentation or sample code on how to do this?

---

(I did find the function for adding a slide, but I haven't found code to add the slide when you are nearing the end of the current slides. Also, a performance detail: I would think that once a large number of slides have been loaded, you would want to remove the initial slides from the DOM to conserve memory.)

**Comment by leggomuhgreggo** [comment]
I'm not familiar with any off the top of my head, but I think it's possible, as you say, through add/remove slide features. There's a key in the slick object for cache, which you'll probably want to pay close attention to.
