### ISSUE TITLE
Changes for slick accesible

### ISSUE THREAD

**Issue by albertobase** [kenwheeler/slick#2574]
> Slick with list accesible

====================================================================

I'm sorry for my English

I made some changes to the slick to be accessible when we have a list, you can see in the following github repo.

###### `[ https://github.com/albertobase/slickAccessibleList  ]`  

https://github.com/albertobase/slickAccessibleList

====================================================================

#### By creating a list of html the result is not correct
<ul>
   <div>
   <li>
   <li>
   </div>
</ul>

we have a div inside that should not be

In the version that I can see the changes.

If you can change it in the plugin would be perfect  : D

**Comment by leggomuhgreggo** [comment]
Thanks, I'll make sure to consider this along with the other accessibility todos
