### ISSUE TITLE
Heratic dragging behavior on a centered, non-infinite carousel

### ISSUE THREAD

**Issue by MissonHxC** [kenwheeler/slick#2578]
> When dragging RTL (mouse movement, not slider movement), slider go to next slide or slide beneath click area. When dragging LTR (again, mouse movement), slider go freely depending on momentum given.

====================================================================

###### http://jsfiddle.net/204eb1fh/1/

====================================================================

#### Steps to reproduce the problem

1. On first slide, try to drag as far as you can (click & hold, drag to give momentum and release click), the slider will stop at next slide or slide beneath click area.
2. On last slide, try to drag as far as you can (click & hold, drag to give momentum and release the click), the slider will go freely and stop naturally.

====================================================================

#### What is the expected behaviour?

On both cases, slider should go freely when dragging.

====================================================================

#### What is observed behaviour?

Slider doesn't react as expected when dragging RTL.

====================================================================

#### More Details

- Firefox 49, Chrome 53.0.2785.101
- jQuery: master; Slick: master
- Did this work before? => I don't know

**Comment by leggomuhgreggo** [comment]
Hey @MissonHxC is it the same issue as what's described in #1872?

Thanks

**Comment by MissonHxC** [comment]
@leggomuhgreggo Yep, it is! Sorry for the duplicate.
#1872 seems open for a certain time, is there any lead to resolve this bug?

I'll look into it, but I'm afraid I ain't a JS warrior.

Thanks

**Comment by leggomuhgreggo** [comment]
Hard to say where it will land in terms of priority. Unfortunately the dev pace hasn't been very rapid for a while. Definitely on the radar. Thanks
