### ISSUE TITLE
Improve custom paging

### ISSUE THREAD

**Issue by decimoseptimo** [kenwheeler/slick#2579]
I think it'll be nice to change

```js
        dots: true,
        appendDots: ,
        dotsClass: ,
        customPaging: ,
```
to 

```js
        dots: true,
        appendDots: //'.slider',
        dotsClass: // 'ul.dots',
        dotsItemClass: //'li.dots-item',
        dotsItemActiveClass: //'active',
        customPaging: ///...
```

Custom paging is ok as of now, but it is not quite there. We still have to target 'li' and 'li.slick-active' and above changes would allow to be a bit less tied to slick css for custom pagination.

I do use slick exclusive classes like

```css
.slider.slick-initialized .slick-slide {
    display: block;
}
```

as event hooks to prevent FOUC, which is fine.

**Comment by leggomuhgreggo** [comment]
Hmm, sorry, I'm not sure I'm clear on your intent. Can you clarify?

**Comment by decimoseptimo** [comment]
Adding two js properties to further customize css classes (dotsItemClass for '.li' and dotsItemActiveClass for 'li.slick-active').

**Comment by leggomuhgreggo** [comment]
`.slick-dots li:not(.slick-active)` no good?

**Comment by decimoseptimo** [comment]
It is more about that you when you do custom paging. You are able to customize the classes for the ul (dotsClass), and the li contents (customPaging), but not for the li directly, nor its active state. hece I suggest dotsItemClass, dotsItemActiveClass.

**Comment by leggomuhgreggo** [comment]
I can see the way in which that adds some sanity, but I'm hesitant to add options on those grounds alone re:bloat/comprehensibility, but if there's more clammer for it the option is still open. Thanks.

**Comment by certainlyakey** [comment]
I follow this. Maybe we shouldn't add the paging li classes as a separate option, but it could be resolved instead with allowing us to customize the `<li>`'s via the `customPaging` option as well. Currently `customPaging` allows to customize only the tags inside each li (`button`s).
