### ISSUE TITLE
Where does ul.slick-dots inline style "display: block;" comes from?

### ISSUE THREAD

**Issue by decimoseptimo** [kenwheeler/slick#2580]
I know I'm supposed to add a test case, but oddly I dind't find the issue in the baseline Fiddle fork. Fortunately the issue is also present in your official demos.

In chrome latest, goto http://kenwheeler.github.io/slick/
on the first slick demo "Single Item" inspect ul.slick-dots
you'll see an inline "display: block;" style applied to it.

Were does it comes from?

I pressume that style is not in the html, as it is not in mine. I search for it in slick.js, but was unable to find it. It matters to me because I have my own resposive classes and at the beginning it should be set to none, but it's getting overwritten because of that inline style.

**Comment by leggomuhgreggo** [comment]
Here ya go:
https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.css#L127

**Comment by decimoseptimo** [comment]
That is not correct as what I am refering to is an inline style, not inherited from slick-theme.css, you can actually take that css file still get the inline style.

**Comment by leggomuhgreggo** [comment]
Gotcha, that'd be here then:
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1428

**Comment by decimoseptimo** [comment]
Inline styling, no good.
I feel the use of `show()` doesn't seem add value and it actually messes with the code as it'll make me will introduce `!important`'s in my code. You may consider removing it.

Thanks.

**Comment by leggomuhgreggo** [comment]
Fair point! Thanks @decimoseptimo

**Comment by obendev** [comment]
This is still a thing.
https://kenwheeler.github.io/slick/#slick-slide00
There is still an inline `display: block;` on `slick-dots`
`<ul class="slick-dots" style="display: block;" role="tablist">`

Will this be fixed in future?

**Comment by Fahad-droid** [comment]
Was facing the same issue, but inline `display: block;` on `slick-dots` wasn't the culprit.

I had ul > li elements as `display: block;` -- changing it to `display: inline-block;` worked for me.
