### ISSUE TITLE
everything turns bigger as the carousel slide

### ISSUE THREAD

**Issue by citra45abadi** [kenwheeler/slick#2581]
> short description of the bug / issue, provide more detail below.
using autoplay, everytime the carousel slides, the images got bigger, not just the image on carouse but everything on the page is scaling proportional to the carousel
====================================================================

###### Fiddle  `[  http://jsfiddle.net/2ox9zymo/ ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. make a div as container
2. make 3-5 child divs, inside of it, each has 1 img
3. include CSS, Jquery 2.1.4, and slick plugin
4. call the function with `autoplay` setting

====================================================================

#### What is the expected behaviour?

the same as in the example for Autoplay setting  

====================================================================

#### What is observed behaviour?

it is sliding automatically, but the images shown is 5, I set the image show to 2 but it's not working
each time the image slides, everything on the page scales and get bigger infinitely 

====================================================================

#### More Details

- Which browsers/versions does it happen on? Google Chrome version 49.0.2623.112 m
- Which jQuery/Slick version are you using? Jquery 2.1.4 and Slick latest from website
- Did this work before? nope, this is my first time

**Comment by leggomuhgreggo** [comment]
Hmm couldn't see the issue on that fiddle. Im gonna close this it doesn't strike me as a bug, but feel free to chime in with a clarification.

**Comment by Bodokh** [comment]
This just happened to me as well with version 1.6.
It happened when sliding to the next image with a slider with 28 images. 
Also, the div the slider was in was only 300px width, might be also a possible cause.
