### ISSUE TITLE
Clickable links as carousel element?

### ISSUE THREAD

**Issue by mcdoolz** [kenwheeler/slick#2582]
A simple question :  How can I let anchors be active?  As in clickable carousel elements?  Javascript on click?  Is it just a 'preventDefault' preventing anchors from firing?  I haven't looked for myself as yet.

**Comment by angelarted** [comment]
@leggomuhgreggo Please can you link the old issue you are talking about? I cannot find anything about this issue and I'm struggling with this... thank you!
