### ISSUE TITLE
Does not work with jquery 3

### ISSUE THREAD

**Issue by sssf90** [kenwheeler/slick#2583]
I am using bootstrap 4 and there is a problem with jquery version. I can't call some methods like 
> show.bs > 

because bootstrap 4 needs jquery 3. But if i load third jquery version slick can't be 
initialized. 

Somewhy bootstrap and slick worked if i called it like this:
`<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="./slick/slick.js" type="text/javascript" charset="utf-8"></script>`

But if i called 
`<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
<script src="./slick/slick.js" type="text/javascript" charset="utf-8"></script>`

**Comment by leggomuhgreggo** [comment]
Slick should work with jquery 3.

**Comment by sssf90** [comment]
It does not work on 3.1.1

**Comment by leggomuhgreggo** [comment]
Hmm can you recreate the issue in a fiddle? I'm pretty sure the fiddle we provide is set to use jquery@latest so I have my doubts, but if you can create it, I'll check it out.

**Comment by sssf90** [comment]
I found mistake. Close the topic

Thank you a lot

**Comment by sharanadla** [comment]
hi sssf90,

can you please share us with the solution. I am facing a similar problem. The plugin isn't working with "jquery 3.1.1". Do you want me to include both the versions using <noscript> tag?

**Comment by leggomuhgreggo** [comment]
@sharanadla if you grab the [current master](https://github.com/kenwheeler/slick/blob/master/slick/slick.js), the issue should be resolved.

**Comment by nestorrojas07** [comment]
es porque se esta usando la version slim que no provee el soporte por lo que se debe usar la version de jquery.min

**Comment by korenevskiy** [comment]
Please see, this don`t  work this plugin with jQyery 3.3.1 in https://explorer-office.ru/download/gdpr
