### ISSUE TITLE
Partial carousel

### ISSUE THREAD

**Issue by Crunky** [kenwheeler/slick#2584]
Hi,

i need a centred carousel with partial views of next/prev images like [here](http://www.jssor.com/demos/nearby-image-partial-visible-slider.slider)

So the main Image should have 80% and the partial images 10% 10% width. 

If yes, how can i do that and in addition how can i design partial images with css class (give a blur e.g.)

Thanks Marco

**Comment by leggomuhgreggo** [comment]
You'll want to use centerPadding, thought I'm not 100% it works with percentages, no pun intended 😄 

Closing support req
