### ISSUE TITLE
First image of a slider is not shown completely.

### ISSUE THREAD

**Issue by amorphine** [kenwheeler/slick#2586]
If a 'slicked' slider is replaced with jquery.replaceWith and another instance of Slick is created the first photo is not shown completely
# 

http://jsfiddle.net/0u2en6tq/1/
# 
#### Steps to reproduce the problem
1. Create slick slider with the given config
2. make replaceWith with the 'before slick' html
3.  Create slick slider again with the same config
4. See the first image is absent or shown half of its normal size
# 
#### What is the expected behaviour?

Normal first image
# 
#### What is observed behaviour?

Empty field or a part of image. Images appears after switching slides.
# 
#### More Details

'Hack' to fix: 

`$('.slider-for div.slick-list').css({height: ''});`

u see after Slick initialisation .slick-list height is not of the normal size. That's why image is not shown completely.

The fiddle example is a bit not good looking but rather functional. At a production of complete site I have the same result.

**Comment by leggomuhgreggo** [comment]
I think that'll be because slick can't calc dimensions when its display none. You might be able to use slick set position of visibility hidden. Good luck!

Closing: support request
