### ISSUE TITLE
Can't center items horizontally when width is bigger than container

### ISSUE THREAD

**Issue by tomyo** [kenwheeler/slick#2587]
I tried using flex in each item (wrapping them by another div), centering using align-content: center, but the next slide get's in the current one.
Has anyone succeeded doing this? I tried with flex, but I it breaks.
#### Steps to reproduce the problem
1. create a carousel with images with width bigger than container
2. center images using flex, applying justify-content: center to every parent of every image
- Chrome v.54  Ubuntu 64 bit
- Slick 1.6, jQuery v1.11.2
- Did this work before? No

**Comment by tomyo** [comment]
Problem resolution:
http://jsfiddle.net/tomyo/fmo50w7n/678/

**Comment by leggomuhgreggo** [comment]
Glad you got it resolved!

**Comment by tomyo** [comment]
Sorry, I meant, 'Problem reproduction', haha
