### ISSUE TITLE
Question about `setupInfinite`. updateInfinite / destroyInfinite.

### ISSUE THREAD

**Issue by vogdb** [kenwheeler/slick#2588]
Question about `setupInfinite` method. Functionality similar to `updateInfinite` / `destroyInfinite`.
# 

Hi! Thank you so much for this great library. We use slick to display a three-item gallery where we display only one item at the time. We use such gallery as buffer to display thousand-item collections. So, every time we receive an `afterChange` we load next item and dynamically replace the content of one slide with it. There is a problem with that. `slick-clone` elements are calculated during the initialisation of slick, so we have to update them every time we load a new item. Currently we hack it like this:

``` js
  this._$gallery.on('afterChange', function(event, slick, currentIndex) {
    $('.slick-cloned', slick.$slider).remove();
    slick.setupInfinite();
```

So, the question. Does it make sense in your opinion to have a method `updateInfinite()` where we recalculate `slick-clone` elements? `destroyInfinite()` where we destroy all `slick-clone`? What alternatives can you suggest to update `slick-clone` elements when slide's content is replaced?

**Comment by leggomuhgreggo** [comment]
Hmm have you tried the slickAdd and slickRemove methods?

**Comment by vogdb** [comment]
Thank you! It makes sense. I will try. Closing for now.
