### ISSUE TITLE
Slick creates its own width when hovering over the slider.

### ISSUE THREAD

**Issue by gamalielhere** [kenwheeler/slick#2592]
> short description of the bug / issue, provide more detail below.

For some reason slick creates an overflow on the body when the mouse is hovered over it.
====================================================================

###### `[  paste your jsfiddle link here  ]`  
Cant really reproduce it since it seems to only show itself in my boss's laptop on mozilla.

====================================================================

#### Steps to reproduce the problem

1. go to https://www.richhoneymonthly.com/pages/about-us
2. hover over the slider on the bottom of the page.
3. See as it creates an overflow.

====================================================================

#### What is the expected behaviour?

It shouldn't scroll over the side nav.

<img width="1280" alt="screen shot 2016-10-31 at 4 16 31 pm" src="https://cloud.githubusercontent.com/assets/16236741/19874956/2d40c47e-9f86-11e6-9108-7c239a7cf9f2.png">

====================================================================

#### What is observed behaviour?

it overflows to the side nave.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Mozilla Firefox v49.0.2
- Which jQuery/Slick version are you using?
First found in jQuery 2.2.4 upgraded jQuery 3.1.1
Slick version 1.6.0
- Did this work before?
Yes.

**Comment by gamalielhere** [comment]
It seems like `.slick-track` is creating it's own width and overflowing the parent instead of being constrained by the parent's width.

**Comment by leggomuhgreggo** [comment]
Hey can you recreate in a test case? [Check out the Contribution Guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)

Thanks

Closing: No fiddle
