### ISSUE TITLE
slickSetOption not working with responsive breakpoints

### ISSUE THREAD

**Issue by eSaner** [kenwheeler/slick#2593]
I have a carousel below the fold that inits with autoplay: false. Autoplay is set to true when the carousel is scrolled into view using slickSetOption. This works fine, but when responsive breakpoints are used it only works above the breakpoints. 

Seems related to [#327](https://github.com/kenwheeler/slick/issues/327), but also setting autoplay for the breakpoints doesn't seem to work (and #327 is closed, so it should be fixed):
`var bp = '[{breakpoint: 768, settings: {autoplay: true}}, {breakpoint: 425, settings: {autoplay: true}}]';
$('.slider').slick('slickSetOption', 'responsive', bp, true);`

codepen: [http://codepen.io/eSaner/pen/MbgVjB](http://codepen.io/eSaner/pen/MbgVjB)
Slick version: 1.6

Should I need to change autoplay separately for the breakpoints? Is my syntax for that wrong?

**Comment by Djules** [comment]
Your value for responsive option should be an array, not a string (remove quotes around).

```js
var bp = [{breakpoint: 768, settings: {autoplay: true}}, {breakpoint: 425, settings: {autoplay: true}}];
```

**Comment by eSaner** [comment]
@Djules That worked. Thanks!
