### ISSUE TITLE
onBeforeChange - determine if change is manual nav or autoplay

### ISSUE THREAD

**Issue by bbodien** [kenwheeler/slick#2595]
Is it possible to determine from within `onBeforeChange()` if the event was caused by user action (swipe, navigation/dots click etc) or an autoplay? 

What I'm trying to do is have the Slick slider initialised with autoplay enabled, but then turn it off as soon as there is some manual user navigation. If I pause it unconditionally in onBeforeChange, it will stop after the first autoplay slide advance.

**Comment by eSaner** [comment]
I've paused autoplay on click/swipe using:

'// stop autoplay on click
$('#your-carousel').on('click', function() {
  $('#your-carousel').slick('slickPause');
});
  
// stop autoplay on swipe
$('#your-carousel').on('swipe', function() {
  $('#your-carousel').slick('slickPause');
});'

**Comment by leggomuhgreggo** [comment]
Hey @bbodien definitely a sensible enhancement. Been on our radar and I think it will be in v2. Here's the tracking issue #2188. Thanks!

Closing dup

**Comment by bbodien** [comment]
Thanks @leggomuhgreggo . I implemented the functionality I was after by manually binding a click handler (which pauses the slider) to my nav elements via the init event in Slick, but it's a bit of a workaround. I'll keep an eye out for updates on #2188.
