### ISSUE TITLE
Image height and retina images

### ISSUE THREAD

**Issue by brakai295** [kenwheeler/slick#2598]
Sorry if this is a silly question, but how do I actually change the height of the images in the slider? 

Changing the height of the `img` element in the HTML page doesn't seem to do anything, and changing it through CSS doesn't work either.

On a related note, how do I use the plugin as an image slider in conjunction with non-retina and retina versions of the images? Any best-practice advice?

**Comment by simeydotme** [comment]
Please ask general web-dev questions on StackOverflow, @brakai295 :) ...this is a bug-tracking forum. Good luck, feel free to share the link to your question here.
