### ISSUE TITLE
Change the position of the PREV,NEXT arrow.

### ISSUE THREAD

**Issue by ricardo85x** [kenwheeler/slick#2599]
Using CenterMode = true, Are there any setting to change the location of the PREV,NEXt arrow?

I would like something like this:

IMAGE1 IMAGE2 < IMAGE_CENTER > IMAGE3 IMAGE 4

The default position is in the corner like:

< IMAGE1 IMAGE2 IMAGE_CENTER IMAGE3 IMAGE 4 >

**Comment by tyrann0us** [comment]
There's no setting for moving slider arrows as you can see by reading through all [available settings](https://github.com/kenwheeler/slick#settings).
You'll need to use CSS for this.
