### ISSUE TITLE
Autoscroll problem when touch not finished

### ISSUE THREAD

**Issue by FlashJunior** [kenwheeler/slick#260]
1) setup slick with "autoplay"

Example:
```
$('#carousel').slick({
	infinite: true,
	dots: false,
	autoplay: true,
	autoplaySpeed: 5000,
	draggable:false
});
```

2) use your mobile device and start dragging one slide
3) don't release your finger, so the slide is still dragging

after "autoplaySpeed" time is finished, it swiches to the next slide.
can that be fixed somehow?

**Comment by kenwheeler** [comment]
This is fixed via pauseOnHover
