### ISSUE TITLE
asNavFor not working when we swipe the sliderNav

### ISSUE THREAD

**Issue by thollander** [kenwheeler/slick#2606]
When we have a two sliders linked by one asNavFor, if you swipe the sliderNav and you swipe the sliderFor, it is not able to swipe again the sliderNav correctly. 

https://jsfiddle.net/thollander/50r0mcsx/10/

#### Steps to reproduce the problem

1. Slide the big slider to the last slide
2. Slide the little slider to the first slide
3. Slide the big slider to the left

#### What is the expected behaviour?

The sliderNav should slide to the selected slide in the big slider. 

#### What is observed behaviour?

The sliderNav doesn't follow the sliderFor in this case.

**Comment by GuilhermeHideki** [comment]
Maybe try this?
```js
sliderNav.slick({
  infinite: false,
  slidesToShow: 4,
  focusOnSelect: true,
  asNavFor: sliderFor
});
```
