### ISSUE TITLE
Slider doesn't scroll to the last slides when not in infinite mode and more than one slidesToShow using slickGoTo

### ISSUE THREAD

**Issue by thollander** [kenwheeler/slick#2607]
The slider doesn't want to scroll to the last slides when using slickGoTo. This is due to the fact that it won't be able to set the slick-current class if it is not the first on the left. 

====================================================================

###### https://jsfiddle.net/thollander/m6ohoodh/2

====================================================================

#### What is the expected behaviour?

The slider should slide until the slide is visible. 

====================================================================

#### What is observed behaviour?

It doesn't slide at all.

**Comment by jekelija** [comment]
Seeing this behavior as well. Put in a temporary patch that fixes it. In slick.js getDotCount:
Underneath `else if(!_.options.asNavFor) {`, Comment out: 
`pagerQty = 1 + Math.ceil((_.slideCount - _.options.slidesToShow) / _.options.slidesToScroll);`
And insert instead:
`pagerQty = Math.ceil(_.slideCount / _.options.slidesToScroll);`

**Comment by dxshindeo** [comment]
Seeing the same problem here
