### ISSUE TITLE
css not loading when using slick with event

### ISSUE THREAD

**Issue by ramielian** [kenwheeler/slick#2610]
am having a small problem in here, i added the slider to an event to show multiple sliders (simple hide and show on click), everything working but when navigating between the links, the slider does not load the css in time and waits until the transetion to get the css.
i tried the waitfortransion att, and lazyload but still having the same problem, anyone can help?
the slider is on http://marksman.me/wordpress

thanks

**Comment by philippenewman** [comment]
I'm not the wise one to give you the answer, but just a thought, would assigning classes to the element in the event call in the script perhaps make a difference?
