### ISSUE TITLE
Pagination outside parent container

### ISSUE THREAD

**Issue by sutuzari** [kenwheeler/slick#2615]
I am using 
`appendDots:$(this).siblings('.pag')`
to change the position of default pager. It works great if the .pag div is "next" to slider div, but in my case, it is 2 levels up and i cant get it to work no matter what i tried.
Was wondering is there any simple solution

https://jsfiddle.net/fmo50w7n/736/

**Comment by codyodell** [comment]
This question is more relevant to iquery than slick, but you could use the 'closest()'  method instead of 'siblings()' to get the nearest parent element
