### ISSUE TITLE
Function call when 'slickNext' hits end of slider in non-infinite mode

### ISSUE THREAD

**Issue by eddiemf** [kenwheeler/slick#2617]
Is there a simple way to call a function whenever I hit next button or use 'slickNext' if the slider has reached the end?

I want to call an AJAX after the slider ends. I tried the 'edge' event but it seem it doesn't work that way, only triggering when i try to swipe the last slide.

**Comment by leggomuhgreggo** [comment]
Should be testable with the events. Best of luck!
