### ISSUE TITLE
Center mode problem when there are few slides

### ISSUE THREAD

**Issue by sdornan** [kenwheeler/slick#262]
I am using slick in center mode to create a carousel where the user can make a selection by moving their desired choice to the center spot.

It works as expected when I have many items:
![screen shot 2014-05-28 at 1 26 38 pm](https://cloud.githubusercontent.com/assets/563517/3109010/a6a485e6-e695-11e3-9a3b-d0308f9e151f.png)

However, with fewer slides than the number of items to display, it doesn't quite work as I would expect:
![screen shot 2014-05-28 at 1 29 32 pm](https://cloud.githubusercontent.com/assets/563517/3109050/07829db2-e696-11e3-9433-c282001ec2ec.png)
![screen shot 2014-05-28 at 1 29 13 pm](https://cloud.githubusercontent.com/assets/563517/3109044/fa98f97a-e695-11e3-932c-6787aae74efb.png)

I would expect the user to be able to move an item to the center spot, even if there are less slides than the number set to display. In addition, in the three slide case, there seem to be two slides that have the center-slide class assigned to them, neither of them in the center spot, which doesn't make sense to me.

Is this working as intended or a bug(s)?

**Comment by jullermss** [comment]
Could you tell me which lines you comment from  slick.js? I have the same problem

**Comment by waltermacambira** [comment]
@jullermss, I am no longer using slick.js, it became unecessary for our needs. As code have changed the lines I mentionend are  no longer the same. I suggest you looking for the expressions I mentioned.

**Comment by blaiz** [comment]
Has this issue been fixed?

I'm looking at the current code at https://github.com/kenwheeler/slick/blob/master/slick/slick.js but it looks like the issue is still here. I tested this version in [a jsfiddle](http://jsfiddle.net/blaiz/ga1gg2qz/1/) and I could still reproduce it. In this jsfiddle, clicking on the arrows does nothing when there are 3 panels, but works properly when there are 4 panels (you need to manually add a panel to test this).

I'm currently having the issue on a project I'm working on. We want center mode to work the same way no matter how many slides we have, be it 2 or 200. We're using slick.js version 1.3.15 and I can get around it by patching slick.js like @waltermacambira did: https://gist.github.com/blaiz/4d0b29820c46661ed333

If I understand the logic correctly, when the number of slides is less than or equal to the slidesToShow setting, slick.js basically doesn't use the regular center-mode but instead just shows all slides at once. It seems like it shouldn't be difficult to add a new setting to disable this behavior. I could fork the repo and give it a try. What do you think?

**Comment by zerostatic** [comment]
I'm having the same issue. Any updates?

**Comment by yenkute** [comment]
![44cfc6d3becfe7da5cdd188ffe8f7bb3](https://cloud.githubusercontent.com/assets/8855734/12215192/adf9cfba-b6e4-11e5-96d5-b55facf4f667.png)
I've the same issue. With a few item, slider don't center.

**Comment by rcrisp** [comment]
I just ran into this as well.  If there are too few slides to be a carousel, I need to center the items on screen.

**Comment by rcrisp** [comment]
I just came up with a quick solution to suit my needs.  

In the `Slick.prototype.initUI` function, add the following:

        if( _.slideCount <= _.options.slidesToShow ) {
            _.$slider.addClass('slick-no-slide');
        }

This adds a `.slick-no-slide` class to the slick carousel if there are less slides than the `slidesToShow` option.  Then add the following CSS which will then override the width setting of `.slick-track` (it will be set to the width of the number of slides otherwise), switch the slides to display `inline-block` and not float, and center them.  This works for my scenario but you may need to alter the CSS to suit your needs.  

    .slick-no-slide .slick-track {
        width: 100% !important;
        text-align: center;
    }

    .slick-no-slide .slick-slide {
        float: none;
        display: inline-block;
    }

I think the good thing with this solution is it's CSS based, so it should be easily tailored to fit whatever the end case is rather than having JavaScript make assumptions for you.

I'm happy to create a PR with this if you'd like, just let me know.

**Comment by stha** [comment]
:+1: +1

**Comment by chinhphan099** [comment]
Up :)

**Comment by userlond** [comment]
Have the same issue.

**Comment by davidnoh** [comment]
@kenwheeler Are there some news? You wrote, that you're thinking about making it an option. That would be really nice. Furthermore it would be nice to have the option for centerMode, if length > 1 -> show arrows to center the active item. Thanks for your work.

**Comment by thijsdemaa** [comment]
+1, we are really struggling with this, in many projects. We need a fix

**Comment by thijsdemaa** [comment]
I fixed (read: hacked) it by using the following code:
```javascript
function Gallery__set_current() {
    slick = $('.Gallery__navigation ul').slick('getSlick');
    var slideCount = slick.slideCount;
    var slidesToShow = slick.options.slidesToShow;

    if(slideCount <= slidesToShow) {
        $('.Gallery__navigation ul .slick-slide').removeClass('slick-current')
            .eq(Gallery__current().data('slick-index')).addClass('slick-current');
    }
}
```

if the slideCount is less than or equal to the amount of slidesToShow, it will manually set the `slick-current` class.

`Gallery__current().data('slick-index')` <- This part of code gets the `data-slick-index` from the main slick slider.

**Comment by chinhphan099** [comment]
Optimized from @rcrisp 
----
function checkSlickNoSlide {
  var elm = $('.slick-nav'),
      getSlick = elm.slick('getSlick');

  if(getSlick.slideCount <= getSlick.options.slidesToShow) {
    elm.addClass('slick-no-slide');
  }
  else {
    elm.removeClass('slick-no-slide');
  }
}
**checkSlickNoSlide** is called on slick's event **afterChange**

CSS (Less):
.slick-no-slide {
  .slick-slide {
    float: none;
    display: inline-block;
  }
  .slick-track {
    width: 100% !important;
    text-align: center;
    .transform(~"inherit !important");
  }
}

**Comment by hoomersinpsom** [comment]
Up o/

**Comment by SharpEdgeMarshall** [comment]
+1

**Comment by rttmax** [comment]
+1

**Comment by ixisio** [comment]
@kenwheeler Any updates here?

**Comment by hoomersinpsom** [comment]
almost 2 years and nobody fixed this ?

**Comment by kenwheeler** [comment]
Is there a related stable PR somewhere?

**Comment by hoomersinpsom** [comment]
i found this https://github.com/kenwheeler/slick/pull/1901

**Comment by CheezeCoder** [comment]
I'm not quite sure I have the same issue as you guys, but I found another alternative if this is indeed a part of someone's troubles.

My issue is that I am using slick on a wordpress site and the number of slides is dynamic according to however many images the user adds to a wordpress ACF field.  So a slider on one page may have 8 slides or may have 2 slides.  

So to solve this I just query the amount of children of my slick slider:

    var numSlides = $('my-slider').children().length

And then I create a conditional based upon how many slides I want to show so in my case I want there to always be 3 slides showing using center mode.  To make this work I write:

    numSlides > 3 ? slides = 3 : slides--;

Then I can use this to init my slider:

    $('my-slider).slick({
        slidesToShow: numSlides,
        cetnerMode: true    
    })

Note this is only if you want to have infinite sliding. In the case where there is 2 slides the above example will show a duplicate slide where the center is unique and the 2 slides to the left and right are the same.

It's a pretty specific use case but it might help someone.  
Cheers

**Comment by hadnazzar** [comment]
Here is my solution same of some before. 

Add some if statements in  Slick.prototype.initUI = function () {
```

if (_.slideCount <= _.options.slidesToShow) {
            _.$slider.addClass('slick-no-slide');
        }
        else {
            _.$slider.removeClass('slick-no-slide');
        }

```
If you want to show more elements than you have slider will have no-slide class. 

Then add your css file. 
```

.slick-no-slide .slick-track {
    width: 100% !important ;
    text-align: center !important;
    transform: inherit !important;
}
.slick-no-slide .slick-slide {
    float: none !important;
    display: inline-block !important;
}

```

**Comment by SparrowSquire** [comment]
Similar kind of issue. It also appears to be adding "slick-center" to two slides at the same time. I want to highlight the central nav slide.
Fiddle here: https://jsfiddle.net/SparrowWoods/nu3psa1g/

**Comment by AlexMCoder** [comment]
@hadnazzar Thanks, here solved my problem.

**Comment by JikkuJose** [comment]
So no real solution for this?

**Comment by Pushplaybang** [comment]
doesn't seem that way.

**Comment by viovelros** [comment]
@yenkute 
![margin-auto](https://user-images.githubusercontent.com/34549335/36882034-16609254-1e04-11e8-9399-ecfe6de1f647.png)

Please try to add "margin: auto" like this picture.

**Comment by fparent** [comment]
Any news on this? Issue is still happening when using `centerMode: true` with the number slides <= than the attribute `slidesToShow`. 

Meanwhile I manually remove the "slick-center" class on each element after the plugin is initialized but it feels a bit... dirty :/

Thanks, keep up the good job!

**Comment by JikkuJose** [comment]
@fparent you mean to say that the removing the `slick-center` class gets the job done?

**Comment by fparent** [comment]
in my case yes because I'm using the class mainly for styling purpose

**Comment by gustavokrause** [comment]
Adds a custom CSS:

```
.slick-track {
    margin-left: 0;
    margin-right: 0;
}
```

**Comment by lukoie** [comment]
I had the same problem, and I've found out that the problem is in the #id's
So I've reassigned every slide to the class instead of id, and everythyng works fine now.

**Comment by Elurajnagare** [comment]
> 
> 
> Here is my solution same of some before.
> 
> Add some if statements in Slick.prototype.initUI = function () {
> 
> ```
> 
> if (_.slideCount <= _.options.slidesToShow) {
>             _.$slider.addClass('slick-no-slide');
>         }
>         else {
>             _.$slider.removeClass('slick-no-slide');
>         }
> ```
> 
> If you want to show more elements than you have slider will have no-slide class.
> 
> Then add your css file.
> 
> ```
> 
> .slick-no-slide .slick-track {
>     width: 100% !important ;
>     text-align: center !important;
>     transform: inherit !important;
> }
> .slick-no-slide .slick-slide {
>     float: none !important;
>     display: inline-block !important;
> }
> ```

Nice it's works

**Comment by JrZavaschi** [comment]
> I just came up with a quick solution to suit my needs.
> 
> In the `Slick.prototype.initUI` function, add the following:
> 
> ```
>     if( _.slideCount < _.options.slidesToShow ) {
>         _.$slider.addClass('slick-no-slide');
>     }
>     else {
>         _.$slider.removeClass('slick-no-slide');
>     }
> ```
> 
> This adds a `.slick-no-slide` class to the slick carousel if there are less slides than the `slidesToShow` option. It will remove the class if this changes (ie breakpoint settings change).
> 
> Then add the following CSS which will then override the width setting of `.slick-track` (it will be set to the width of the number of slides otherwise), switch the slides to display `inline-block` and not float, and center them. This works for my scenario but you may need to alter the CSS to suit your needs.
> 
> ```
> .slick-no-slide .slick-track {
>     width: 100% !important;
>     text-align: center;
> }
> 
> .slick-no-slide .slick-slide {
>     float: none;
>     display: inline-block;
> }
> ```
> 
> I think the good thing with this solution is it's CSS based, so it should be easily tailored to fit whatever the end case is rather than having JavaScript make assumptions for you.
> 
> I'm happy to create a PR with this if you'd like, just let me know.

Thanks  man :)
