### ISSUE TITLE
Disable center mode if only one item

### ISSUE THREAD

**Issue by rorc** [kenwheeler/slick#2623]
Hi)

Need disable padding if one item in slider for alignment his left (without padding-left).

**Comment by Nishantart** [comment]
Use this it will work perfectly :)
$(document).ready(function() {
  var slickOpts = {
    	dots: false,
		arrows: true,
		centerMode: true,
		//fade: true,
		centerPadding: '70px',
		slidesToShow: 1,
		pauseOnHover:false,
		speed: 1000,
		autoplay: true,
		infinite: true,
		 slidesToScroll: 1,
  };
  // Init slick carousel
  $('.photo-gallery').slick(slickOpts);
  
  if($('.item').length == 1){   
  	$('.photo-gallery').slick('slickSetOption', 'centerMode', false)
  }
});
