### ISSUE TITLE
Slider doesn't work in Firefox when inside link

### ISSUE THREAD

**Issue by thollander** [kenwheeler/slick#2624]
I need to use the slider inside a link. However, Firefox seems like it doesn't handle it. Works 100% on Chrome. 

====================================================================

http://jsfiddle.net/thollander/gha7qyfw/

====================================================================

#### Steps to reproduce the problem

Just try to slide in Firefox with and without the 'href' attribute of the link. 

====================================================================

#### What is observed behaviour?

The slider doesn't scroll due to the link (particularly due to the href attribute).

**Comment by tyrann0us** [comment]
Don't put the slider inside a link tag. Wrap the individual slides with links instead.

**Comment by thollander** [comment]
Thanks for your response tyrann0us but I need it to be wrapped with a link. There is other elements than the slider in the real case and the whole container should be clickable. Any other solution ?

**Comment by thollander** [comment]
I just found a possible solution. The problem is that Firefox permits drags on images and links by default. We can just prevent this behavior with : 

`$('#slider').on('dragstart', function(e){
	return false;
});`

Here is the updated jsfiddle with this solution : 

https://jsfiddle.net/thollander/gha7qyfw/
