### ISSUE TITLE
Vertical scroll on mobile registers as slide change

### ISSUE THREAD

**Issue by dingo-d** [kenwheeler/slick#2625]
> Vertical scroll on mobile registers as slide change

On mobile I need to hide prev/next buttons on the second slide, but enable it on all others. The second slide can be scrolled vertically, and that triggers the `beforeChange` event which removes the added classes.

====================================================================

###### `http://jsfiddle.net/fmo50w7n/747/`  

====================================================================

#### What is the expected behavior?

The hidden class should stay on the button all the while you're on the 2nd slide, no matter if you scroll up or down on it. 

====================================================================

#### What is observed behavior?

On mobile devices the vertical scroll will make the buttons appear on the second slide. The jsfiddle on desktop will work ok, even if you make the window width below 767px, so you might think that there is no bug, but try to open jsfiddle link on your mobile devices and this will happen (tested it).

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome mobile (54.0.2840.85), on Android  6.0.1, and Chrome on iPhone 7
- Which jQuery/Slick version are you using? 1.6.0
- Did this work before? I haven't tested it before, just tried it and it's not working so...

**Comment by AshConnolly** [comment]
+1

**Comment by igorbumba** [comment]
+1

**Comment by leggomuhgreggo** [comment]
Check my code pen on this ticket:
https://github.com/kenwheeler/slick/issues/1138

I almost want to make a label for team spam ;)
