### ISSUE TITLE
How can i manipulate slides with scrollbar

### ISSUE THREAD

**Issue by MateuszGrzy** [kenwheeler/slick#2627]
Hello, 
I created 2 slides 1 slides is 7000px long and second is 1px long. Both slides are infinite looping and i want to add feature to scroll them via scrollbar [picrel](http://imgur.com/a/ORMvN)

**Comment by leggomuhgreggo** [comment]
Thanks for your interest. This is the type of thing that would be nice, but ranks fairly low on the list of priorities and also has the benefit of being fairly easy to achieve through the browser's scroll position API. I've added the feature proposal label in case it makes the cut on v2, but I wouldn't think it'd be a near term enhancement.

Thanks!
