### ISSUE TITLE
$.animate should not be used if not available

### ISSUE THREAD

**Issue by pwnsdx** [kenwheeler/slick#2628]
Hello, jQuery Slim does not implement $.animate and is therefore not compatible with your plugin when animate is used (especially for lazy loading of slides). I think it would be good to implement a way to handle this (e.g. instant show/hide and/or permit the user to do a custom Promise so he can use a third-party library).

====================================================================

> Sometimes you don’t need ajax, or you prefer to use one of the many standalone libraries that focus on ajax requests. And often it is simpler to use a combination of CSS and class manipulation for all your web animations. Along with the regular version of jQuery that includes the ajax and effects modules, we’ve released a “slim” version that excludes these modules. All in all, it excludes ajax, effects, and currently deprecated code. The size of jQuery is very rarely a load performance concern these days, but the slim build is about 6k gzipped bytes smaller than the regular version – 23.6k vs 30k. These files are also available in the npm package and on the CDN:

https://blog.jquery.com/2016/09/22/jquery-3-1-1-released/

====================================================================

#### Affected code

https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L248
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L266
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L270
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L283
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L933
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L965
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L1470
https://github.com/kenwheeler/slick/blob/95e1be8c69ea63e9b957fb5e8f9e882edc63063f/slick/slick.js#L1473

====================================================================

#### What is the expected behaviour?

Animate should not be used if not available.

====================================================================

#### What is observed behaviour?

jQuery.animate is always used.

====================================================================

#### More Details

- Which browsers/versions does it happen on? All
- Which jQuery/Slick version are you using? 3.1.1 Slim / 1.6.0
- Did this work before? No

**Comment by leggomuhgreggo** [comment]
Next version wont have jquery as a dependency at all, but until then we're in the boat we're in.

**Comment by pwnsdx** [comment]
OK 👍

**Comment by Strongground** [comment]
So when is this next version coming?
