### ISSUE TITLE
Store the latest slide

### ISSUE THREAD

**Issue by oatto** [kenwheeler/slick#2630]
For example, we have post thumbnails as slider and slide to the third slide then we click to open that post(in the same window), when we finish reading that post and press browser back button, how could we start at the latest clicked slide (which is the third slide) ?

The only way that I could think of is to use cookie for storing that latest slide. Does anybody have a better idea ?

Thank you.

**Comment by tyrann0us** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by leggomuhgreggo** [comment]
@tyrann0us another good option in addition to cookie. Could also ajax the "open post" in and keep the local config. Could also url param.
