### ISSUE TITLE
more than one slick,how can speed up?

### ISSUE THREAD

**Issue by moahmn** [kenwheeler/slick#2631]
#### Steps to reproduce the problem

1. i have four slick in one page,and have lots of image need to show,it too slow to aceet.

====================================================================

#### What is the expected behaviour?

1.what can i do to speed up?

====================================================================

**Comment by leggomuhgreggo** [comment]
Hmmmmm? I'm not 100% sure what you mean but, there's an option for animation speed. The rest has to do with how you load resources on your page.
