### ISSUE TITLE
Dynamic Slides Break Grid

### ISSUE THREAD

**Issue by eddieparker** [kenwheeler/slick#2633]
> If you configure a grid slick carousel, and then try to use slickAdd to add to it, it never adheres to your grid layout.

====================================================================

###### `https://jsfiddle.net/sj57q074/9/`  

====================================================================

#### Steps to reproduce the problem

1.  See the jsFiddle, the implementation to dynamic_slider.
2.  Cry.

====================================================================

#### What is the expected behaviour?

That slideAdd would not make my grid disappear.

====================================================================

#### What is observed behaviour?

That it flattened my grid.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome.  i.e.,  
- Which jQuery/Slick version are you using?
The latest from the CDN as well as from the JSFiddle.
- Did this work before?
No idea, just tried Slick for the first time tonight.

**Comment by leggomuhgreggo** [comment]
Grid isn't all the way there yet. Unslick and reslick will probably get you there. I'm like 75% sure this has come up before though, so you might search on it to see if others have found a fix.
