### ISSUE TITLE
About css

### ISSUE THREAD

**Issue by stratboy** [kenwheeler/slick#2634]
I've already tried the gitter channel, but since I'm not receiving any answer, I'm just writing right here. Copy-paste:

Hi, I'm deciding to switch from flexslider to slick. First thing first: are its styles fully customisable? Are they mandatory? Can I fully override them if needed? I mean, without too much hassle: flexslider lets you not to load its css and setup basic functionality with really few lines of css (again, I mean to have the basic masking/changing images, and then one starts styling anything else). I thing that's mainly because in flexslider the really relevant styles are inline-written via javascript. Is Slick the same?

**Comment by tyrann0us** [comment]
Why don't you just test it?

**Comment by leggomuhgreggo** [comment]
Thanks for trying the gitter channel first. We've broken the slick styles into "base" and "theme". Obviously with code you can change everything/anything you want, and so in that sense they are customizable, but the base styles will give you the base functionality. Theme has button placement, arrow styles etc. Hope that helps. Give it a spin--there's a jsfiddle you can play with in the contributions.md
