### ISSUE TITLE
Image Ratio's

### ISSUE THREAD

**Issue by warlord0** [kenwheeler/slick#2637]
Using a "competitive" product I'm able to specify an image ratio such that if it is as wide as it is tall it can be made to take up a width of 2 images. This is handy when using a 3 image slider as I then have 2 images of the same height rather than 3 images where one is made much smaller to fit the width required to fit 3 images.

This is done using a data-merge attribute on the html

eg.
```html
<img data-merge="1" src="regular image.jpg">
<img data-merge="2" src="wide image.jpg">
<img data-merge="1" src="regular image.jpg">
<img data-merge="1" src="regular image.jpg">
...
```
Where regular image is 800x1200 and wide image is 1600x800

Is there a similar feature for slick.js?

**Comment by leggomuhgreggo** [comment]
Man, I think you'd have to test the img dimensions, which I've honestly never done, then use the slick setOptions method based on that. This is a tricky one. Post back here if you get it. Interesting!
