### ISSUE TITLE
Dots: aria-hidden true/false attr need to be inversed

### ISSUE THREAD

**Issue by koljakutschera** [kenwheeler/slick#2639]
In 1.6 the active-dot has aria-hidden="false" and the others aria-hidden="true". For screenreaders this means that they can not navigate by the dots.

====================================================================

Just inverse it:
- active dot: aria-hidden="true" + disabled on the button maybe good
- inactive dot: aria-hidden="false"

====================================================================

Thanks,
K

**Comment by leggomuhgreggo** [comment]
Duplicate. It's one of the highest priority things on the radar.

**Comment by keeganstreet** [comment]
I don't think this is a duplicate of any other tickets. It is calling out the accessibility defect in the dots specifically.
