### ISSUE TITLE
Feature Request: core CSS file

### ISSUE THREAD

**Issue by onlywei** [kenwheeler/slick#264]
Currently the slick.css file has dependencies on some additional font and image files that are inside this GitHub repository. Many applications will not use these fonts and images. Some application deploy processes don't even deploy vendor font and image files. These applications will get 404 not found errors when using slick.css.

I believe there should be another css file that these application developers can load that does not reference any additional font and image files. Maybe call it `slick.core.css`.

**Comment by mslemeri** [comment]
+1 Would love to have this

**Comment by tomaszpoliszuk** [comment]
Done ;)

**Comment by Renkas** [comment]
Now it would be great to get core CSS file as slick.scss also.

This is so we could import it in our application sass stack easily ;) As currently SASS does not support importing CSS files.

**Comment by kenwheeler** [comment]
Its in 1.4.1 , ready for release

**Comment by Renkas** [comment]
Nice :)

**Comment by tomaszpoliszuk** [comment]
You can include css into sass.
Just rename .css to .scss

**Comment by Renkas** [comment]
Why would I want to go and edit bower component code? That's not a solution.

But unfortunately I have had to do his before - hopefully these days are soon to be gone from most of projects.

**Comment by tomaszpoliszuk** [comment]
It's probably immpossible to make everyone happy with all this tools we have.
For example - my personal choice is autoprefixer & personal framework with many switches (for includes etc) - i don't expect everyone will follow this way ;)

**Comment by YoungElPaso** [comment]
It'd be good to have a 'dist' directory with the bare minimum in the bower package.  Handy for handling vendor packages without having to cherry pick the resources you want to copy/minify/uglify etc.
