### ISSUE TITLE
How to stop slick on a certain breakpoint and below?

### ISSUE THREAD

**Issue by stratboy** [kenwheeler/slick#2640]
Hi, yes you can pass 'unslick' to responsive settings. But it seems it unslicks only from there and up. I would need from there and down, instead. I want to unslick small and medium and have slick back on large. I think it's quite a common need.

How to?

**Comment by leggomuhgreggo** [comment]
Search existing issues on this subject. Unslick doesn't leave any listeners.

Closing: Dup, Support Req
