### ISSUE TITLE
How to left justify first images and right justify last images while using center mode

### ISSUE THREAD

**Issue by GeniusGo** [kenwheeler/slick#2642]
Hi All,
    I'm using slick slider 1.6.0 with AngularJS. I using center-mode in sync version of the slider. But in center mode, I don't want first and last images in thumbnail tray to be center aligned because it leaves unnecessary space to the left and right side of thumbnail tray. Instead, they should be left justified and right justified. Is there any way or hack to achieve this?

**Comment by leggomuhgreggo** [comment]
I would set centerPadding to zero and pad the slide as needed. Tricky but doable. Good luck.

Closing: Support request.

**Comment by GeniusGo** [comment]
Hi @leggomuhgreggo we tried to do it, but could not reach up to the point what we want. We have multiple sliders on the same page. And finding this really difficult to do. Will you please some code for same. It would not be appropriate to mess with slick.js.
