### ISSUE TITLE
Set different a transition speed for clicking/swiping and another for autoplay

### ISSUE THREAD

**Issue by juancpgo** [kenwheeler/slick#2643]
I realize that
- `autoplaySpeed` sets the pause time between slide transitions when in autoplay
- `speed` sets the duration of a transition

When slides are in autoplay, it’s usually desirable that they move slow so your design looks smooth and cool. But when you click on an arrow to get to the next slide, it’s frustrating to wait those slow transitions, now you want them to go quickly to move swiftly between slides.

Is it possible to have one transition speed when clicking/swiping, but another transition speed when slides move in autoplay?

**Comment by leggomuhgreggo** [comment]
You can always highjack the animation

Closing: Support request
