### ISSUE TITLE
Slides are blank (or maybe height:1px?) in Safari

### ISSUE THREAD

**Issue by akabaka** [kenwheeler/slick#2646]
I have a Slick carousel that uses proportional height slides (height:0; padding-bottom:60%;) with some slides using background images (with a transparent "spacer" gif of the same proportions that uses bootstrap class "img-responsive") and others with text that vertically centered. Please see here and scroll down to Sponsors:

http://bit.ly/2gYMiLR

It works as expected in Chrome, and in Safari on my MAMP localhost, but not in Safari on the remote site that is otherwise identical. Sometimes it shows up correctly on the first load in Safari, but after reloading it's blank. When I inspect the blank slides, they're showing the correct height (not 1px, which is what happened before I added the responsive transparent gif) but there's just nothing there.

This is how I'm invoking Slick:
	$('.slick-carousel').slick({
	  dots: false,
	  infinite: true,
	  autoplay: true,
	  speed: 300,
	  slidesToShow: 6,
	  slidesToScroll: 1,
	  arrows: false,
	  responsive: [
	    {
	      breakpoint: 1550,
	      settings: { slidesToShow: 5, slidesToScroll: 1, infinite: true, }
	    },  {
	      breakpoint: 1330,
	      settings: { slidesToShow: 4, slidesToScroll: 1, infinite: true, }
	    }, {
	      breakpoint: 1000,
	      settings: {  slidesToShow: 3, slidesToScroll: 1 }
	    }, {
	      breakpoint: 768,
	      settings: { slidesToShow: 2, slidesToScroll: 1 }
	    }
	  ]
	});

**Comment by leggomuhgreggo** [comment]
Hope ya got this sorted! If it's still a thorn and you think it's a bug, holler back with a fiddle/pen ala reduced test case, and we can dig into it.

Thanks
