### ISSUE TITLE
show multiple slide but scroll by one

### ISSUE THREAD

**Issue by kampiamodikuesto** [kenwheeler/slick#2648]
I wuold like to know if with some fix i can get this effect:
- one dot for each slide
- display/show multiple slide at once

my target is to get a slide as this 

https://www.gucci.com/it/it/pr/men/mens-shoes/mens-sneakers/ace-embroidered-low-top-sneaker-p-429446A38G01284?position=4&listName=CapsuleProductComponent_s63_global_m_new_ace&categoryPath=Men/Mens-Shoes/Mens-Sneakers

i try to change "slick-list draggable" element to 100% or 100vh but this involve a big offset of active image. 

i have to set slideToScroll and slideToShow to 1 otherwise i haven't match between slide and dost

**Comment by tomaszpoliszuk** [comment]
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown
