### ISSUE TITLE
Initial slick doesn't show correctly when initialize slick against hidden element

### ISSUE THREAD

**Issue by leomao10** [kenwheeler/slick#2650]
I found that slick is not showing correct result when I run the code like this:

```
$(document).ready(function(){
    $('.beta-widgets-slick').hide();
    $('.beta-widgets-slick').slick();
    $('.beta-widgets-slick').show();
});
```
The slick layout look like this in my app when I call `slick()` to a hidden element:
![screen shot 2016-12-06 at 12 16 37 pm](https://cloud.githubusercontent.com/assets/198821/20909101/ab3d0188-bbad-11e6-90f2-8d7ebb5d45a0.png)

Clicking the `next` button or call `slick.refresh` will make it looks normal again.

Here is the jsfiddle that reproduce the issue I encounter:
https://jsfiddle.net/5qyyhjq2/8/

**Comment by paulinetheitgirl** [comment]
Hi @leomao10 I had a similar issue, I tried hiding the slides using slick class "slick-slide" instead as suggested in [https://github.com/kenwheeler/slick/issues/158](https://github.com/kenwheeler/slick/issues/158) and it worked for me. I hope this helps.

**Comment by leggomuhgreggo** [comment]
Might also see if filter/remove methods satisfy your needs. I'm going to close because I'm not sure this is quite a bug, but I'll stay tuned in case there's no solution. 

Thanks

**Comment by mshah49** [comment]
I am having the same problem and I am unable to fix it. I am using http://jquerymodal.com/ and then putting in the slider on the modal.  I have tried adding classes to the divs like suggested in #158 but it didn't work.

**Comment by ZizzyZizzy** [comment]
This bug is still not fixed.

https://stackoverflow.com/questions/32371003/how-to-reload-slick-slider-carousel-jquery-plugin

The work-around is in this comment:
jQuery(".your-slick-div").slick('resize');
