### ISSUE TITLE
autoplay doesn't work in vertical mode

### ISSUE THREAD

**Issue by robbisy** [kenwheeler/slick#2658]
> short description of the bug / issue, provide more detail below.

autoplay doesn't work in vertical mode

I use codepen to make a demo 

[issue demo](http://codepen.io/anon/pen/VmGxWJ)

Thanks in advance for any help

**Comment by andrewnaumann** [comment]
Took a quick look at your pen, when passing the options to slick you have ```autoplay``` formatted wrong.

It should be ```autoplay: true``` all lower case, you have it written as ```autoPlay: true``` which is incorrect.  Fix that and your demo works fine.

**Comment by robbisy** [comment]
@andrewnaumann Thanks andrew I totally miss the point
