### ISSUE TITLE
One empty first slide in mobile...

### ISSUE THREAD

**Issue by JacquesGoudreau3000** [kenwheeler/slick#2665]
> short description of the bug / issue, provide more detail below.

Hello, I have an empty first slide on my carousel on mobile. 

Any idea why?

Thanks!

====================================================================

$(document).ready(function(){
	$('.home_services_slick').slick({
		dots: false,
		infinite: false,
		speed: 300,
		slidesToShow: 4,
		slidesToScroll: 4,
		swipeToSlide: true,
		responsive: [
		    {
		      	breakpoint: 1024,
		      	settings: {
		        	slidesToShow: 2,
		        	slidesToScroll: 2,
		      	}
		    },
		    {
		      	breakpoint: 600,
		      	settings: {
		        	slidesToShow: 2,
		        	slidesToScroll: 2
		      }
		    },
		    {
		      	breakpoint: 480,
		      	settings: {
		        	slidesToShow: 1,
		        	slidesToScroll: 1
		      }
		    }
	  	]
	});

**Comment by CHEWX** [comment]
Do you have a reduced test case in jsfiddle.com ?
