### ISSUE TITLE
afterChange fires even slide didn't changed

### ISSUE THREAD

**Issue by inferusvv** [kenwheeler/slick#2668]
`afterChange` event fires even slide didn't changed

====================================================================

###### [JSFiddle](http://jsfiddle.net/fmo50w7n/801/)

====================================================================

### Option 1 (using arrows)
1. Open JSFiddle above
2. slide1 should be visible
3. Click left

Slider didn't changed state, but `afterChange` event was fired.

### Option 2 (using drag event)
1. Open JSFiddle above
2. Drag with mouse slide a bit, so it don't scroll.

The same - slider didn't changed state, but `afterChange` event was fired.

====================================================================

#### What is the expected behaviour?

I think that this event should be fired only after slide was changed.

====================================================================

#### More Details

Locally:
- jQuery 2.2.3
- slick 1.6.0

**Comment by waqas-shahid-10p** [comment]
@inferusvv 
That event helped me in the case where I need to move to the first slide after the user reaches at the end of the slider.

If this issue is fixed then there should be an event which fires when the slider reaches the end. I know there is an event called 'edge' but that only fires when we're changing the slides by drag.

**Comment by camdagr8** [comment]
I also noticed that if you use 'slickGoTo', and supply a slide index, the afterChange will fire, but the currentSlide value is still the previous slide. It doesn't seem to change until you go to the next 'page' of slides. So if I have 4 slides visible and have slide 0 focused and do slick('slickGoTo', 1), the event tells me that slide 0 is the active slide, even though semantically, it should be 1. 

The direction value of slick.direction also doesn't track correctly. It always says 1. Shouldn't it be 0 if I'm going back a page and 1 if I go forward a page?

**Comment by 2pha** [comment]
I had this problem too...
So though I would track if an actual change occurred with some custom code in the beforeChange event...
But the beforeChange event only occurs when an actual change happened (the expected behavior I suppose)
