### ISSUE TITLE
$( document ).on( "ready", ... ) removed in jquery 3.0.0

### ISSUE THREAD

**Issue by KolyaKorruptis** [kenwheeler/slick#2676]
Slick Slider relies on the "ready" event on multiple occasions and is therefore not compatible with jQuery 3.0+.

https://jquery.com/upgrade-guide/3.0/#breaking-change-on-quot-ready-quot-fn-removed
https://api.jquery.com/ready#entry-longdesc
https://github.com/jquery/jquery-migrate/blob/1.x-stable/warnings.md#user-content-jqmigrate-ready-event-is-deprecated
https://github.com/jquery/jquery/issues/2264

**Comment by kenwheeler** [comment]
@leggomuhgreggo we should get a release cut for this

**Comment by programmer403** [comment]
now jquery 3.1.1 is released. Join for waiting for slick update ;)

**Comment by leggomuhgreggo** [comment]
@kenwheeler @programmer403 sure seems low impact, and straight forward

**Comment by leggomuhgreggo** [comment]
Closing. Thanks!

**Comment by zheoreh** [comment]
Which version of slick has this fix?

**Comment by DmitryGonchar** [comment]
@zheoreh  v1.7.1+
https://github.com/kenwheeler/slick/releases
