### ISSUE TITLE
Draggable feature not working in FireFox

### ISSUE THREAD

**Issue by seanforyou23** [kenwheeler/slick#268]
Using the slick slider, loving it so far. Works great in all browsers except one problem in FF. The draggable feature only triggers on mouseup, which then causes the carousel position to stick to the position of your cursor (as long as your mouse is inside of the carousel container). Once your cursor leaves the bounds of your carousel, the slider 'flicks' as if you swiped it on a tablet in the direction which your cursor exited. I've tried using event.preventDefault() on the '.slick-list' but no luck, maybe I'm applying that on the wrong element? I'm using a list item as the sliding element and they contain an anchor and an image if that helps. Thanks in advance!!

**Comment by AhmetFUsta** [comment]
@adigetr where do we add that code? Just anywhere?

**Comment by DuudeXX8** [comment]
Hey @adigetr  please help where do we add this code????

**Comment by sitefinitysteve** [comment]
@AhmetFUsta @DuudeXX8 add it here https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2755

I just had this issue with 1.8.1 today (chrome), event.preventDefault(); indeed seems to resolve it

Slides are all added after a callback, just a set of images
