### ISSUE TITLE
added a new buttons

### ISSUE THREAD

**Issue by martin-badin** [kenwheeler/slick#2686]
If I used `reinit` function, so slick added a new `prev` and `next` buttons, each time

![snimka obrazovky 2017-01-09 o 21 17 29](https://cloud.githubusercontent.com/assets/5845264/21781728/130edfca-d6b1-11e6-8a4f-df1563ea8b5a.png)

`$(container).find('.gallery').slick('reinit');
      $(container).find('.thumbs').slick('reinit');`

slick: 1.6.0
chrome: 55.0.2883.95 (64-bit)
jquery: 3.1.1

**Comment by andypillip** [comment]
I can confirm.
