### ISSUE TITLE
Sliders not displayed on applying the slick-theme.css

### ISSUE THREAD

**Issue by sadiq-mc** [kenwheeler/slick#2739]
1. While I provided the slick-theme.css in my page, the sliders are not displayed and if I remove it the sliders displays but the button wont be styled.

2. Do the number of 'slidesToShow' should be less than the number of slides to be displayed..? If the slides is less than the number mentioned in 'slidesToShow', then slides are not displayed.

Use the [Plunker code](https://plnkr.co/edit/hUP0WrZtJu9UP8ebOXdb?p=preview) to verify. Also when the preview is launched in separate window, the sliders are not displayed.

#### More Details
Tested on Google Chrome and Firefox.

**Comment by EvgeniyRRU** [comment]
I suppose, it's a normal behavior of slick widget. When I've decrease frame width, some pictures has been displayed. I suppose, you should to tune your widget config.
![screen](http://dl3.joxi.net/drive/2017/02/02/0018/2084/1234980/80/3a4582adcc.jpg)

**Comment by sadiq-mc** [comment]
Thanks @EvgeniyRRU .. 
But can you make it clear what i need to look into..

I see the div with class ```slick-track``` where the sliders are displayed has the style value as ```opacity: 1; width: 0px; transform: translate3d(0px, 0px, 0px);```

**Comment by sadiq-mc** [comment]
Oh shit.. the issue not displaying sliders was just because of the ```col-xs-12'' in the ```<div class="col-sm-12"><label>Sponsorships</label></div>``` . While I removed the ```col-xs-12``` it displayed the sliders..
