### ISSUE TITLE
angular ng-repeat shows all the images at once.

### ISSUE THREAD

**Issue by Vicky-Thakkar** [kenwheeler/slick#2743]
i have this view file where i have used slick.

```
<div>
  <slick infinite="true" slides-to-show="4" slides-to-scroll="1">
    <div ng-repeat="var in myArray" class="slick-item">
      <img src="image.png"></div>
    </div>
  </slick>
</div>

```
below is the output.
![slick](https://cloud.githubusercontent.com/assets/20662109/22509911/f236e1e6-e8b5-11e6-8e80-7ba4308edb09.png)

how can i use ng-repeat

**Comment by jinhuang12** [comment]
Try calling slick.reinit() after the ng-repeat has finished rendering. You can do this by using $timeout and using jQuery to get the slick object.
