### ISSUE TITLE
unslick breakpoint terminates other breakpoints once reached

### ISSUE THREAD

**Issue by ain** [kenwheeler/slick#2753]
> if first breakpoint has settings set to `unslick` and it is reached, the other breakpoints would not be considered when reversing to those breakpoints.

====================================================================

http://jsfiddle.net/tekkie/4a6o5w1d/

====================================================================

#### Steps to reproduce the problem

1. Create first breakpoint at 1000 with settings set to `unslick`
2. Create second breakpoint at 500 with settings set to show and scroll 2 slides
3. Resize up to 1000 till breakpoint is reached
4. Resize back to 500 

====================================================================

#### What is the expected behaviour?

One would expect `unslick` to be reversed and second breakpoint to take precedence.

====================================================================

#### What is observed behaviour?

First breakpoint with `unslick` irreversibly terminates all breakpoints.

====================================================================

#### More Details

```
Safari 10.0.3 (12602.4.8)
slick.js 1.6.0 (or 1.5.8)
jQuery Edge (3.1.2-pre)
```

**Comment by iclang** [comment]
I too am experiencing this behavior. Looking at the code, it appears that if you're not "unslicking" it for that breakpoint, there is a refresh that is called which I would think would re-initialize the carousel but I don't think it's triggered.

**Comment by cbloss** [comment]
I'm experiencing this as well. I was hoping to only call slick on mobile so I've called unslick for the desktop and the rest of the breakpoints never get called. Of course, if you set the setting to go for mobile first, it doesn't look right either.

**Comment by leggomuhgreggo** [comment]
Regret to say that there's no state persistence after unslick, and so subsequent breakpoints won't work. You can listen for the resize event and reinit as a work around. Hope that helps
