### ISSUE TITLE
Slick Slider - captions option

### ISSUE THREAD

**Issue by NozX18** [kenwheeler/slick#2755]
Hi everybody ! 

I have a question about slick slider.
In my website, I need to have the title of a picture slide as a html title. This options exists in bxslider -> 'caption : true'.

I know I can use html and php to resolve my problem but I just want to have your thoughts about it 
Is it possible to add this caption option in slider ?

Thank you all and have a good day !

**Comment by simeydotme** [comment]
are you referring to the `<title>` of the page, or the `title=''` of each slide?

if `<title>`; never going to happen
if `title=''`; that should be in your html code, and completely possible already :)

**Comment by lhpderckx** [comment]
I believe NozX18 is prompting for a way that Slick parses that title while generating the slick slides and creates markup elements for that, like this example (bxslider) does: http://bxslider.com/examples/image-slideshow-captions

I'm sure you can set title's on your slide-to-be elements, but there's no option to actually render the titles as markup elements.

**Comment by NozX18** [comment]
Exacly lhpderckx ! Yes I know this option not exist on this slider but I added code in slick.js to create this markup element, and it works ! Do you think that we can add this options on slider ? Do you think that could be useful ?
