### ISSUE TITLE
Swiping (seems to) honors "slidesToScroll" in stead of the amount that is swiped

### ISSUE THREAD

**Issue by lhpderckx** [kenwheeler/slick#2756]
Hi Ken,

Thanks for providing slick... it really is... slick :)

There's one thing that's bugging me though, especially because 'slick' is presented as responsive friendly due to some of its features you highlighted.

The thing is, when slick is configured to show multiple items in screen (like your 'lazy loading' demo), swiping only ever slides the amount that is configured by "slidesToScroll". Try that demo on your mobile device and you'll be able to reproduce.

In my opinion, this setting should be ignored when swiping (or dragging along with the mouse when enabled) and the number of items scrolled should snap at the closest item(s) that is/are in view right before the moment the finger or mouse is released.

While swiping / dragging along with the mouse, it almost appears like I can move the slides freely, but after releasing, it snaps to the slide that is one "slidesToScroll" step from the initial slide.

Do you consider this to be a bug? If 'yes', what would be your expected release window?

Thanks,

Luc

**Comment by simeydotme** [comment]
Thanks, Luc.
You're pretty much right; and it's something we'd like to do in the future :)
