### ISSUE TITLE
Home Page Elements not showing in Mobile like they do in desktop

### ISSUE THREAD

**Issue by oruta** [kenwheeler/slick#2766]
> Hello!

My Home page looks great and works as it should on desktop, but doesn't seem to be appearing correctly on mobile. Any way to fix this? Thanks for your help!

Respectfully,
Walter

(PS. Laborator Support crew suggested I come here to ask about the problem Hi Walter,

> It is weird how that happens! I have been checking about this about an hour and didn't find what is the problem. I have the same set of products and it was not happening! I suggest you to contact plugin author and ask if he could discover where the issue is coming from?
> https://github.com/kenwheeler/slick/issues Click New Issue and then describe your problem.
> Kind regards,
> Arlind
> 

====================================================================

###### `[  http://www.cabalcrafted.com/  ]`  

use this jsfiddle to reproduce your bug: 
http://www.cabalcrafted.com/
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  Go to http://cabalcrafted.com on a desktop
2. ...  Go to http://cabalcrafted.com on a mobile phone
3. ...  Observe how the mobile phone doesn't yield a viewable / usable home page as compared to the desktop version.

====================================================================

#### What is the expected behaviour?

...  The expected behaviour is for the product carousel, and the portfolio items beneath it to size itself and display appropriately for the mobile phone

====================================================================

#### What is observed behaviour?

...  The observed behavior is that the mobile device yields a home page that does not display product carousel, or portfolio items. Neither does it display the automated type (as shown Desktop screens.) Makes home page, unrecognizable, and prevents any interaction for user.

====================================================================

#### More Details

- Which browsers/versions does it happen on? iphone 6
- Which jQuery/Slick version are you using? - Not sure
- Did this work before? - This is the first time I'm using the product carousel feature \

**Comment by leggomuhgreggo** [comment]
closing support req
