### ISSUE TITLE
When changing breakpoints, if a swipe was executed just before and there's a diff # of slides, a touch after will cause a swipe

### ISSUE THREAD

**Issue by dmusicant** [kenwheeler/slick#2771]
The issue is that `checkResponsive' calls `refresh` which extends the "this" object with the current `this.initials` which (for some reason) holds the last swipe length in `_.initials.touchObject.swipeLength`.

As a result, on the next touch after the rotation (and thus the refresh), the `startSwipe` has a `swipeLength` greater than the `minSwipe`.

Why does initials even hold the touchObject at all? That is definitely a bug as the initials should never hold any touch event. The screen would have just changed size/orientation in some way, so touch events should be all gone.

**Comment by leggomuhgreggo** [comment]
Interesting, can you recreate in a reduced test case eg codepen jsfiddle? Im curious, and would appreciate it. Closing pending test case Thanks!
