### ISSUE TITLE
Get original one of cloned

### ISSUE THREAD

**Issue by ravitdx** [kenwheeler/slick#2772]
Hi,

I have one requirement where I have to get values from original slide when a cloned or original slide was clicked. So how can get a reference or object of original slide of cloned slide.

**Comment by leadream** [comment]
Slick clones the first and last slide, so you can check if the current slide has a 'slick-cloned' class and it's real index in 'slick-track'. Index 0 represent it's original slide is $('.your-container .slick-slide').eq(slideCount) and slideCount+1 represent $('.your-container .slick-slide').eq(1).

**Comment by ravitdx** [comment]
Thanks for the reply,
But my question itself is not necessary (sorry about that).The thing is,the the slots which are shown on the screen were always  original.so by the property "aria-describedby" I was able differentiate from clone.And since user won't be able to click a clone,my problem solved. Any way,I will look into your method.Thanks.
