### ISSUE TITLE
Dynamic number of slidesToShow and slidesToScroll

### ISSUE THREAD

**Issue by benjam1n** [kenwheeler/slick#2773]
Hi there! 

I'm trying to make a slider that has either 1 or 2 images on each slide. Single image when it's landscape format and two images when they're are portrait format. 

Any idea how could I do that?

I'll be using WP/PHP and probably could add classes depending on the format of the image (portrait, landscape).

![artboard](https://cloud.githubusercontent.com/assets/103969/23311621/0500d030-fab7-11e6-9aa9-2eb41b3ecc36.png)

**Comment by dmusicant** [comment]
You'll have to alter the code. See my fix here: https://github.com/kenwheeler/slick/issues/2767

And then, in your settings, you'll need to set each breakpoint as a media query for landscape vs portait.

Example:

```
{
            breakpoint: "(orientation: portrait)",
            settings: {
                dots: false,
                slidesToShow: 2,
                slidesToScroll: 2
            }
        }
```

**Comment by mattcdowning** [comment]
In case it helps anyone, the way to implement this functionality at specific breakpoints (after you've altered the code as described in #2767) is like so:

```
      responsive: [
        {
          breakpoint: '(max-width: 766px) and (orientation: portrait)',
          settings: {
            slidesToShow: 1
          }
        },
        {
          breakpoint: '(max-width: 766px) and (orientation: landscape)',
          settings: {
            slidesToShow: 1
          }
        },
        {
          breakpoint: '(min-width: 767px) and (orientation: portrait)',
          settings: {
            slidesToShow: 2
          }
        },
        {
          breakpoint: '(min-width: 767px) and (orientation: landscape)',
          settings: {
            slidesToShow: 3
          }
        }
      ]
```

Thanks @dmusicant!

**Comment by ConduciveMammal** [comment]
Has this been implemented in the master yet? I'd love to to use it but my Slick is served via a CDN.

**Comment by sarfrazhc** [comment]
I'm facing similar issue in Slick version 1.7.1 . Did this ever get resolved?
