### ISSUE TITLE
Dynamically set slideshow autoplay speed?

### ISSUE THREAD

**Issue by jamesinealing** [kenwheeler/slick#2775]
Hi,

I've just been setting up a test installation and have it working just fine - it's very easy, and just what I need.

I have a slightly odd scenario though in that I want to dynamically set the autoplaySpeed for each slide (or perhaps turn off autoplay and trigger the next slide with a custom delay another way?)

As an example, say I have ten images for today, five tomorrow, and four the next day. I want each day to run for ten seconds, so I want to put an autoplaySpeed: 1000 for the first ten images, then 2000, then 2500 and so on.

Can you give me any pointers as to whether this might be possible, and how?

Many thanks

**Comment by jamesinealing** [comment]
Apologies, I just found https://github.com/kenwheeler/slick/issues/1448 and that might be what I am after. I'll investigate tomorrow and if so, close this issue

**Comment by exetico** [comment]
Hi'

Did you manage to find the best solution?  I saw [this](https://github.com/kenwheeler/slick/issues/1448#issuecomment-112425549), but i must say that it's kinda a messy fix. Taking a look at http://jsfiddle.net/dkj3hrqk/1/, it does almost what i wanted to do, but the best will be, if i was able to follow a data-field like the first suggestion.

**Comment by leggomuhgreggo** [comment]
@exetico nice!

**Comment by exetico** [comment]
Did you just bump a issue from 2017? Well done 😁. I moved to Wordpress, many years ago.
