### ISSUE TITLE
Can we use an exsiting list of thumbnail as the pager?

### ISSUE THREAD

**Issue by Ian-Y** [kenwheeler/slick#2776]
Although we can use the `customPaging` option to dynamically create a list of thumbnail as the pager, that can result in [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) when the web page is long. In that case, I would rather write the list of thumbnail in the HTML in advance than create it dynamically. So is there a way to set an existing list of thumbnail as the pager?

**Comment by leggomuhgreggo** [comment]
You can probably do something with asNavFor, or just fix the FOUC with some conditioning around `.slick-initialized`
