### ISSUE TITLE
Need very fluid and free sliding.

### ISSUE THREAD

**Issue by webbipinpal** [kenwheeler/slick#2777]
Hi, 
I was wondering if there is a way to achieve very fluid and free sliding with Slick?

Something like that : https://www.dropbox.com/s/5xub2d34gle0pum/IMG_0710.MOV?dl=0

Is there a way or possibility of doing it with Slick library? because i could not find it in the documentation. Can you help me?

**Comment by andrzej-aa** [comment]
Looks more like iScroll

**Comment by webbipinpal** [comment]
Yes something like that. Thanks andrzej.

**Comment by leggomuhgreggo** [comment]
It's been talked about. There's an issue somewhere about it. Closing because duplicate, but it's a good idea, I think.

**Comment by varemenos** [comment]
Could you share the non-duplicate issue's id?

**Comment by leggomuhgreggo** [comment]
Apologies -- normally I would, but I'm trying to mow the lawn on these issues, and have elected to forgo that courtesy in favor of knocking as many of these out as possible. I will try to circle back at some point, but perhaps search free scroll? Thanks
