### ISSUE TITLE
slider inside slider drag/swipe problem

### ISSUE THREAD

**Issue by bungalobungalo** [kenwheeler/slick#2778]
I need to put a slider inside another slider. The dots navigation works and the arrow navigation works correctly on both sliders but if I try to drag/swipe the inner slider both sliders are affected.
 
Any idea how to fix this issue?

 https://jsfiddle.net/bungalobungalo/ndefzxz1/

**Comment by WALKMAN5** [comment]
Fixed you problem. 

Look example:
https://jsfiddle.net/WALKMAN5/0smp3kst/14/

**Comment by bungalobungalo** [comment]
Thanks a lot!
Works like a charm.

**Comment by gozo1985** [comment]
Be sure to add "touchstart" to the .on mousedown event aswell to make it work on mobile devices. Thank you @asimonok for the snippet +1
