### ISSUE TITLE
Responsive slides containing image adn text

### ISSUE THREAD

**Issue by siulca** [kenwheeler/slick#2780]
Is it possible to scale slides down responsively? So that the width is always 100% of the container while the height keeps the same ratio. The slides would contain any type of HTML. Usually some text over a background image. 

We have a bunch of JSSOR sliders that do this. But we're looking to replace them as JSSOR has a bunch of problems itself and Slick looks like the perfect candidate if only it supported the above. If it can do the above then it'll definitely be the "only slider we'll ever need" ; )

**Comment by leggomuhgreggo** [comment]
Check out "css intrinsic ratios"
