### ISSUE TITLE
Slick with Vue.js ( v-for )

### ISSUE THREAD

**Issue by JustPepper** [kenwheeler/slick#2786]
Hey, im working in a vue.js project, but i cant make it work properly with slick.js, here is my code 

`<ul class="slick_nav" tabindex="-1">
		<li v-for="color in colors">
									<a href="" @click.prevent="setTextureColors(texture.colors)" :style="{ backgroundColor: colors.hex }"></a>
								</li>
							</ul>`

This works initially but when i change the value in colors this just add the new ones instead of changing everything, i been trying to use unslick before then change the content in colors and slick again but this is not working too, any ideas about v-for and slick js?

**Comment by PatrLind** [comment]
@JustPepper did you solve this issue?

**Comment by jesalg** [comment]
Running into the same issue. @JustPepper did you figure out a solution?
