### ISSUE TITLE
Swipe To Slide right direction not working correctly

### ISSUE THREAD

**Issue by Tebzamops** [kenwheeler/slick#2787]
The SwipeToSlide option works perfect when swiping left to a specific slide but as soon as I swipe the  first item in the list to right it bounces back to its position.

Is this an error Or perhaps one cannot swipe right to a slide?

**Comment by leggomuhgreggo** [comment]
Hey, thanks for the issue. There's an open issue on this subject, possibly an open PR. If you wanted to breath some life into a fix, and chase those down, we could see about getting a fix merged. Thanks!

**Comment by NikolayKuznetsov** [comment]
Fix:
Slick.prototype.getNavigableIndexes = function () {

        var _ = this,
            breakPoint = 0,
            counter = 0,
            indexes = [],
            max;

        if (_.options.infinite === false) {
            max = _.slideCount;
        } else {
            breakPoint = _.options.swipeToSlide ? _.slideCount  * -1 : _.options.slidesToScroll * -1;
            counter = _.options.swipeToSlide ? _.slideCount  * -1 :_.options.slidesToScroll * -1;
            max = _.slideCount * 2;
        }

        while (breakPoint < max) {
            indexes.push(breakPoint);
            breakPoint = counter + _.options.slidesToScroll;
            counter += _.options.slidesToScroll <= _.options.slidesToShow ? _.options.slidesToScroll : _.options.slidesToShow;
        }

        return indexes;

    };
