### ISSUE TITLE
Stuck on first slide

### ISSUE THREAD

**Issue by dwinnbrown** [kenwheeler/slick#2788]
When using slick slider, it appears that it can take upto 1 minute for the second slide to be shown despite having set autoplay to true and the slide delay to 6 seconds.

It is behaving like this on the following site:
http://thamesideroofing.co.uk

#### What is the expected behaviour?

As previously mentioned the slider should slide after 6 seconds but gets stuck sometimes. 

Happens reportedly on Firefox and chrome.

**Comment by leggomuhgreggo** [comment]
Reduced test case please.
