### ISSUE TITLE
fade mode in carousel mode

### ISSUE THREAD

**Issue by ruudbwai** [kenwheeler/slick#279]
Hi, great plugin! small issue, when I apply fade to carousel with multiple items visible, then all other slides disappear except the leading one...so how can we apply fade to a carousel with multiple items visible? 

Thanks :) :+1:

**Comment by JanisOzolins** [comment]
The fade effect and multiple items carousel still doesn't seem to be supported in 1.7.1. Is it planned to implement this feature in one of the future releases?
