### ISSUE TITLE
Solved: jquery code to append query strings to URL upon clicking next, previous

### ISSUE THREAD

**Issue by creativearc** [kenwheeler/slick#2791]
// This code appends query strings to the browser URL history upon incrementing or deprecating the slides

	$('.carousel').on('afterChange', function(event, slick, currentSlide){
	window.history.pushState(null, null, '?slide=' + currentSlide);
	});

Courtesy of Greg Crane.

**Comment by leggomuhgreggo** [comment]
Cool thanks for sharing.
