### ISSUE TITLE
centerMode with whole slides. No halves.

### ISSUE THREAD

**Issue by Dennise89** [kenwheeler/slick#2792]
When I set centerMode to true, it does work. But it shows halve slides on both ends. I don't want this.
Can we set this to false or something?

====================================================================

###### `[  https://jsfiddle.net/cvkr6LLo/  ]`  

use this jsfiddle to reproduce your bug: 
https://jsfiddle.net/cvkr6LLo/

**Comment by Dennise89** [comment]
Already fixed it.

In CSS: .slick-list { padding: 0 !important; }

But maybe it's nice to make an option for this?

**Comment by leggomuhgreggo** [comment]
There's an option called centerPadding which does this.
