### ISSUE TITLE
Allow arrows with touch

### ISSUE THREAD

**Issue by efc** [kenwheeler/slick#2793]
With touch enabled on a touch device the arrows disappear. While this may make sense in many circumstances, this leaves my particular slick slider without any indication that there even are other slides. I would like to leave the arrows accessible so that (A) people can tap them even if they don't realize they can swipe and (B) people get a hint that swiping would reveal other information.

#### Steps to reproduce the problem

Create a slick slider with arrows. Open it on a mobile/touch device.

#### What is the expected behaviour?

I expected both arrows and swiping to be available to navigate to other slides.

I expected at least a setting to force the retention of arrow navigation even when swipe is possible.

#### What is observed behaviour?

The arrows disappear and there does not seem to be a setting to retain them on a touch device while still retaining the ability to swipe.

**Comment by efc** [comment]
Good news, I found a work-around.

It seems that when the "arrow" elements are `button`, then all works as I expected it should.

However, I was using `span` elements to hold my "arrow" links. These spans would disappear on the touch devices.

I still think the disappearing spans felt like a bug and should probably be fixed, but substituting `button` elements worked find for me.

Maybe at least suggest in the docs that arrows be attached to `button` elements?

**Comment by leggomuhgreggo** [comment]
Can you provide a reduced test case? Thanks!
