### ISSUE TITLE
slick-carousel webpack error

### ISSUE THREAD

**Issue by Macuzzin** [kenwheeler/slick#2794]
Hi, 

I'm trying to bundle my js into one document using webpack. I've installed slick-carousel with npm and when I require it into my development js file and run webpack I get the following error in my Terminal:

"You may need an appropriate loader to handle this file type."

===============================================
Here is the code in my Main.js file:
===============================================

var $ = require('jquery');
require('slick-carousel');

$(".feautured-products-carousel").slick({
  infinite: true;
});

===============================================
Here is my webpack.config
===============================================

module.exports = {
  entry: "./production/js/Main.js",
  output: {
    path: "./js",
    filename: "main.js"
  }
}

===============================================
Here is my package.json
===============================================

{
  "name": "decorama",
  "version": "1.0.0",
  "devDependencies": {
    "autoprefixer": "^6.7.7",
    "browser-sync": "^2.18.8",
    "gulp": "^3.9.1",
    "gulp-postcss": "^6.3.0",
    "gulp-watch": "^4.3.11",
    "postcss-import": "^9.1.0",
    "postcss-nested": "^1.0.0",
    "postcss-simple-vars": "^3.0.0"
  },
  "dependencies": {
    "jquery": "^3.1.1",
    "slick-carousel": "^1.6.0"
  }
}

**Comment by vikas-wadhwa** [comment]
FYI I needed 'script-loader' and then 

`require 'script!bower_components/slick-carousel/slick/slick'`

I think I also got it working with the umd-require-webpack-plugin as 

`var UmdRequirePlugin    = require("umd-require-webpack-plugin");

  plugins: [

    new UmdRequirePlugin(),

    new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        'window.jQuery': "jquery",
        _: "underscore"
    })
]
`

**Comment by leggomuhgreggo** [comment]
There's a few issues about this, where you can find solutions.
