### ISSUE TITLE
iFrame video won't autoplay on mobile in Slick

### ISSUE THREAD

**Issue by patrickbolle** [kenwheeler/slick#2798]
> I have an embedded iFrame in my Slick carousel.  It works great on desktop, the iFrame video autoplays, but as soon as  on mobile, the iFrame video no longer autostarts.

====================================================================

###### http://jsfiddle.net/w9cmunwh/1/  
(Not sure how I can fully replicate it within jsfiddle as it is  only issue -  on our live site here http://pastebin.com/1E2uwYQe - the video on the top left corner on desktop, not the one in the product description. )

====================================================================

#### Steps to reproduce 

1. Place an iFrame video (with autoplay video ON) within a Slick div item
2. Try on desktop, the video will autostart
3. Try on mobile, the video won't autostart

====================================================================

#### What is the expected behaviour?

Video should autoplay as it does on desktop.

====================================================================

#### What is observed behaviour?

Video does not autoplay on mobile, but does on desktop.

====================================================================

#### More Details

- Which browsers/versions does it happen on? **All**
- Which jQuery/Slick version are ? **Slick 1.6.0, Jquery 2.2.3**

**Comment by leggomuhgreggo** [comment]
Known issue. HTML5 Video API has weak browser support, but I assume there's a workaround -- just haven't had the time to dig. Closing because it's a duplicate but if you find a decent solution definitely chime back in.
