### ISSUE TITLE
Bootstrap dowpdown is always behing slick slider

### ISSUE THREAD

**Issue by claudneto** [kenwheeler/slick#2799]
I must show slider behind bootstrap dropdown.
I tried use zIndex propertie when initialize slick, but didn't work.

This is a test: https://club-app-reactjs.herokuapp.com/template/index.html

**Comment by shaneoliver** [comment]
style.css line 25, remove padding-top, margin-top, change z-index -1 to z-index 1000

**Comment by claudneto** [comment]
Wow! That worked!
I must learn how z-index works correctly! HAHAHAHA

Thanks!
