### ISSUE TITLE
Hidden slider doesn't initialize properly when made avaliable (like in a modal)

### ISSUE THREAD

**Issue by mshah49** [kenwheeler/slick#2800]
> short description of the bug / issue, provide more detail below.

if a slider is hidden (like in a modal), when it becomes visible the initial display consists of all of the slides overlapping each other. It is fixed when the slide is changed.
====================================================================

====================================================================

I am using http://jquerymodal.com/ and then putting in the slider on the modal. The initial display shows all slides (overlapping each other). This is similar to the issue #2650 but I was not able to fix it with the advice given.

#### Steps to reproduce the problem
1. Create modal by using jquerymodal plugin
2. Insert Slider as content of Modal
====================================================================

#### What is the expected behaviour?
The slider should act normally, and not display all slides at once.
====================================================================

#### What is observed behaviour?
The initial view overlaps all of the slides. It is fixed when the slide is changed.
====================================================================

#### More Details

- Which browsers/versions does it happen on?
I use Chrome
- Which jQuery/Slick version are you using?
I am using the newest versions of everything.

**Comment by paulinetheitgirl** [comment]
Interesting. Can you provide a full Gist or Codepen example?

**Comment by SSchnitzler** [comment]
Had the same issue in a couple of projects. 

When initializing your Slickslider - which in your case should be done on the modal:open event from your modal - pass setPosition:true into the options of slickslider.

I dont really know why it works but it does. (Documentation says that setPosition is just an event but passing it into the options makes a huge difference)

In one of my projects the slider wouldnt fully initialize unless a window.resize event gets triggered. Passing setPosition:true also helps in those cases. 

I will try to make a fiddle or codepen during the weekend to allow reproducing this bug.

**Comment by leggomuhgreggo** [comment]
You can find solutions by searching old issues; there's gotta be about 2 dozen of them. Best of luck.
