### ISSUE TITLE
Arrow key navigation not working after click

### ISSUE THREAD

**Issue by creativearc** [kenwheeler/slick#2802]
I have my slick slider working (with keyboard navigation) by following this thread, https://github.com/kenwheeler/slick/issues/901 and this code snippet in particular:

`$(document).find('.slick-list').attr('tabindex', 0).focus();`

A client noticed that even though the slideshow correctly works with arrowkeys, once you *click* a left/right arrow, the slider only accepts mouse input. (Unless you refocus the slideshow)

Perhaps this is default behavior.

Is there a way to have the best of both worlds?

**Comment by creativearc** [comment]
Oops. I see much of this has been covered:

https://github.com/kenwheeler/slick/issues/667

**Comment by creativearc** [comment]
@kenwheeler However, it would be worth clarifying if what I mention/link above is now an included feature? The prior threads were from 2014/2015.

**Comment by leggomuhgreggo** [comment]
This is related to the tab index issues. I'm going to close this because it's a duplicate, but be assured it's on the radar. Thanks
