### ISSUE TITLE
Custom arrow advances frame on youtube video play in chrome only

### ISSUE THREAD

**Issue by Luey00** [kenwheeler/slick#2803]
I am trying to implement a custom image for my arrows and when I do it has a weird action in google chrome when playing a youtube video.  It advances the frame when you hit play.  See fiddle in chrome.  I have not been able to reproduce this in other browsers. 
====================================================================

###### `[ http://jsfiddle.net/mxLp81k6/7/ ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. open the fiddle link in chrome (i am using version   49.0.2623.112)
2. Use the custom arrows to advance to the yt video.
3. Click play on the video.
4. Slide will advance and video will start playing.

**Comment by leggomuhgreggo** [comment]
The html5 video API support for browsers is weak. There are a couple open issues about this, and I haven't encountered a good solution. I'm going to close this as a duplicate, but if you find a solution, definitely chime back in. Thanks
