### ISSUE TITLE
get original data/slides

### ISSUE THREAD

**Issue by schmi85** [kenwheeler/slick#2807]
I am searching for a way to pull some data from all the slides, **BUT** as I found out, slick clones some slides, what makes it difficult.

so for instance, starting with this:

```
<div class="show">
  <div class="slide"><img src="…" /></div>
  …
  …
</div>
```
To get all images/slides 

```
$('.show div.slide img')
```
will do, **BUT** after `$('.show').slick()` there are more slides added, which also have a `slick-cloned` class. So my question, if I filter all the `.slide` which do have are not `.slick-cloned`, will I get all images, or will there be more or less to be expected?

**Comment by leggomuhgreggo** [comment]
How about `$('.show div.slide:not(.slick-clone) img')`?
