### ISSUE TITLE
slick generates the width of a slide

### ISSUE THREAD

**Issue by eele94** [kenwheeler/slick#2810]
I have created an carousel with dynamic slidesToShow and slidesToScroll based on the sliderWidth and a given itemWidth:
```
// slidesToShow and slidesToScroll
    itemsToShow() {
      if (this.slickWidth === 0) return this.defaultItemsToShow;

      return Math.floor(this.slickWidth / this.itemWidth);
    },
```

Slick generates the width of a slide.
The problem: when I am resizing the window I get different width's.
I want the elements keeping their own width, so it wont look different on different screens.

![width](https://cloud.githubusercontent.com/assets/8152346/24256862/94eafb34-0fe9-11e7-9b70-a89a57f700d8.PNG)
![width2](https://cloud.githubusercontent.com/assets/8152346/24256863/95052e0a-0fe9-11e7-8b4e-041c2990715b.PNG)

How to accomplishe this?

**Comment by leggomuhgreggo** [comment]
I think `variableWidth: true` is what you're looking for.
