### ISSUE TITLE
Need callback on responsive

### ISSUE THREAD

**Issue by thisYogesh** [kenwheeler/slick#2818]
Is there any callback after when slick carousel gets responsive _(not window resize)_

**Comment by leggomuhgreggo** [comment]
Minus ten points from yogeshendor for asking a question in the docs, jkjk. 

Check out the breakpoint event [here](https://github.com/kenwheeler/slick#events)

**Comment by thisYogesh** [comment]
@leggomuhgreggo I am just wondering this issue is closes with "Minus ten points from yogeshendor for asking a question in the docs"!! Ha Ha!! Sorry but I am not here to wast your time and mine time as well.

I just want a callback on when slick carousel fires its responsiveness logic then I require a callback/event _(As describe in doc callbacks are not supported in slick then you can consider event also finally its type of callback only!)_ which is presently not supported by slick itself.

I thought its better to ask this in the issues instead of editing the slick library.

CC : @kenwheeler 

Have Great Day !!

**Comment by leggomuhgreggo** [comment]
Haha, cheers. I think in a super early version of slick, you could define callbacks for some functions in the slick options. Now it's event driven, which will allow for the same level of functionality.

Best, Greg

**Comment by pieter-janDB** [comment]
```
$('.slick-slider').on('breakpoint', function(e){

});
```

**Comment by thisYogesh** [comment]
Thank you brother. will check!!

**Comment by mangowi** [comment]
Thank you @pieter-janDB  💯
