### ISSUE TITLE
Nav visual false active

### ISSUE THREAD

**Issue by karltaidev** [kenwheeler/slick#2819]
> short description of the bug / issue, provide more detail below.
When click nav when slick is animating, it ignored and produce visually false active temporary.
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://kenwheeler.github.io/slick/
I tested it on Chrome and Firefox and iphone safari.

====================================================================

#### Steps to reproduce the problem

1. click on one dot
2. click on another dot when it is animating

====================================================================

#### What is the expected behaviour?

One dot is black. And animate back to the second clicked dot.

====================================================================

#### What is observed behaviour?

Two black dots appear at the same time and stayed on the first click.

====================================================================

#### More Details

- Chrome, Firefox, Edge, iphone safari

**Comment by leggomuhgreggo** [comment]
I think this is a duplicate, but I've tagged it so when we review it will be considered. If you find an existing PR, you can chime in either here or there, or make one yourself, and we can try to get a fix in.
