### ISSUE TITLE
Take time to load first time

### ISSUE THREAD

**Issue by rahi-rajeev** [kenwheeler/slick#2823]
Hello Team,
I am using slick slider for banner display in my home page so i have one issues like 
when my page is load then content of slider section show little bit slow like u know
first time page is open then u show that nothings in this area after some time u saw that banner in this section  
see screen shot of first load page
![first_time_loadimg](https://cloud.githubusercontent.com/assets/15867058/24488436/856accac-1534-11e7-9093-9c490324a1d5.png)
After few time image
![after_few_time](https://cloud.githubusercontent.com/assets/15867058/24488474/b79309ce-1534-11e7-9378-4d46be216552.png)

**Comment by gavinlynch** [comment]
I don't feel that this is quite a slick issue, but something that could be solved via CSS. Have you examined any ways to optimize asset loading? Also, you could define a pre-set height for a container element for your banner assets, and have a `.loading` class indicating to the user that the banner is still loading/rendering. That way the page doesn't jump when new content is rendered.

**Comment by rahi-rajeev** [comment]
i have define pre set height of container and also using loader after that i am getting this issues 
basically i am using center mode also

**Comment by lasbrojen** [comment]
<meta itemprop="image" content="www.x.com/x.jpg"> in head?
