### ISSUE TITLE
slick-current class not applied to cloned slides

### ISSUE THREAD

**Issue by Toutouwai** [kenwheeler/slick#2825]
When 'infinite' is true, cloned slides are added before and after the real slides. When navigating from the last slide to the first (and similarly from the first to the last) the neighbouring slide is a clone until the change is complete and the slider resets. 

But because the 'slick-current' class is not applied to cloned slides any visual styling given to slick-current is not shown on the cloned slide and the effect is an abrupt jump to the slick-current style when navigating from last to first or first to last. The effect is especially noticeable if a CSS transition is used with slick-current styling.

====================================================================

See this jsfiddle for a demonstration:
http://jsfiddle.net/toutouwai/x1ovLj48/2/

Note the inconsistent transition when navigating from last slide to first slide and vice versa.

====================================================================

#### Steps to reproduce the problem

1. Create a slick slider with 'infinite' set to 'true'.  
2. Apply some visual styling to the 'slick-current' class.
3. Note how the change to slick-current styling is inconsistent when navigating from last slide to first slide.

====================================================================

#### What is the expected behaviour?

Consistent display of slick-current styling.

====================================================================

#### What is observed behaviour?

Inconsistent display of slick-current styling when navigating from last slide to first slide and vice versa.

====================================================================

#### More Details

- **Which browsers/versions does it happen on?** All browsers.
- **Which jQuery/Slick version are you using?** jQuery 1.12.4, Slick 1.6.0
- **Did this work before?** This has always been an issue in Slick as far as I know.

**Comment by shawnmaust** [comment]
I was experiencing the same problem. The way I worked around it was to use the 'slick-center' class for styling instead of the 'slick-current' class. This worked since the 'slick-center' class, unlike 'slick-current', is applied to the cloned slides.

**Comment by leggomuhgreggo** [comment]
Current and Active are meant to indicate visible slides; so that's why that is.

**Comment by Toutouwai** [comment]
Wow, closed just like that huh? @leggomuhgreggo, did you even look at the jsfiddle that demonstrates this issue? And what makes you think that cloned slides are not visible? If cloned slides were never visible there would be no reason to clone them in the first place.

@shawnmaust, thanks for the suggestion, I've used that workaround in the past myself but it's not a solution when you don't want your slides centered.

**Comment by leggomuhgreggo** [comment]
Sorry if that came off as brusque; I recognized the issue quickly from previous ones (this is a duplicate many times over), and there are a lot of issue to run through. My attempt to clean up the issues, sometimes makes a casualty of the little courtesies. 

It's true cloned slides are visible sometimes, and they get slick-active after they're visible. I appreciate it makes things cumbersome, and improving that is on the list of things to address. There might be a PR out there that tried to address this, and if not, feel free to make one and chime back in.

In future, you might find it useful to search existing open/closed issues. Anyway I appreciate the issue. Thanks.

**Comment by RaghulR7** [comment]
0
down vote
favorite
I need to implement a circular carousel with three slides displayed at a time. I am using angularjs slick carousel with centerMode and infinity as true for achieving circular carousel. And i want to apply css class on clicking the slide to show which slide is selected at the moment.

But I am facing issue while selecting a a cloned slide. (i.e) Initially, if i try to click on slide1 or slide2 it gets selected. But when i try to click on slide6(cloned slide), it is not applying the css property instead it is applying the css to the original slide6 which is not displayed at the moment.

Please check out the jsfiddle below:

https://jsfiddle.net/eq2gtgy6/4/

**Comment by Colir** [comment]
@Toutouwai @leggomuhgreggo @RaghulR7 hello. i've found a solution to this issue ? many thanks

**Comment by offirpeer** [comment]
@Colir 
Where is it?

**Comment by Colir** [comment]
Here is my solution:
During init, i extend the Slick object like this to refer to cloned slides

`$slick_slider.on('init', function(event, slick){
                $.extend(slick,{
                    clonedSlides : $(this).find('.slick-cloned')
                });
`

Then i toggle specific class to the cloned slides (could also use ".slick-current" class)

`$slick_slider.on('beforeChange', function(event, slick, currentSlide, nextSlide){
                slick.clonedSlides.addClass('slick-current-clone');
            });`

`$slick_slider.on('afterChange', function(event, slick, currentSlide){
                slick.clonedSlides.removeClass('slick-current-clone');
            });`

Hope this can be usefull for you.

Cheers
