### ISSUE TITLE
Slides missing until animation completes

### ISSUE THREAD

**Issue by danmasta** [kenwheeler/slick#2830]
> Slides appear to be missing when animating from end to beginning when `infinite = true`, animation is enabled, and `.slick-list` is set to `overflow: visible`.

We're trying to create a carousel that fades out the slides on the ends of the frame to show a 'preview' of which slide is previous/ next. We tried setting `.slick-list` to `overflow: visible` which gives us the desired effect, however, anytime we advance from the end of the carousel to the beginning again there is a flicker, as some of the slides are missing until the animation completes.

====================================================================

###### [http://jsfiddle.net/00bakyc0/1/](http://jsfiddle.net/00bakyc0/1/)  

====================================================================

#### Steps to reproduce the problem

1. Create a slider with the following options
```js
{
    speed: 1000,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1
}
```
2. Adjust the css slightly:
```css
.slick-list{
    overflow: visible;
}
.slick-prev, .slick-next{
    z-index: 99;
}
```
3. when slider is ready, click the left arrow to view the last slide
4. click the right arrow to return to the beginning, notice the empty space on the right end of the slider
5. when the animation completes, notice the slides pop back into place

====================================================================

#### What is the expected behaviour?

Slides will seamlessly toggle from beginning to end and vice versa

====================================================================

#### What is observed behaviour?

When moving from the end of the slider to the beginning a jitter occurs because slides appear to be missing until the animation completes.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
chrome/ 56
- Which jQuery/Slick version are you using?
jquery 3.1.1/ slick 1.6.0
- Did this work before?
No, never used slick carousel before

**Comment by mgoubert** [comment]
Got the exact same problem, i don't use slides to show, but center mode:

`  Drupal.behaviors.paragraph_reference_slider = {
    attach: function (context, settings) {
        // Init slider
        var $slider = $('.paragraph-reference-slider__slider .slider');
        $slider.slick({
            arrows: true,
            dots: false,
            swipe: true,
            infinite: true,
            centerMode: true,
            slidesToScroll: 1,
            slidesToShow: 1,
            variableWidth: true,
        });
    }
  };`

**Comment by leggomuhgreggo** [comment]
Thanks @mgoubert!

**Comment by AshwinSundar** [comment]
Was this ever resolved? I'm having the same issue.
