### ISSUE TITLE
How to add an option to an existing one initialized by the slider?

### ISSUE THREAD

**Issue by pashkes** [kenwheeler/slick#2831]
I want to add "autoplay" and "autoplaySpeed" under certain conditions 
if(slider.isOnScreen()) {
    slider.slick({
      //add option
    })
  }

**Comment by apsolut** [comment]
Maybe you need **slickSetOption**
    something like ` $('.carousel').slick('slickSetOption', 'fade', true, true);`
Check the issue: https://github.com/kenwheeler/slick/issues/2511
