### ISSUE TITLE
how can I using nth-child on slick-active class

### ISSUE THREAD

**Issue by umanga907** [kenwheeler/slick#2832]
Hi Ken, 
Great plugin, I have been using this carousel since last two years. However, I've got a issue here.
here is the jsfiddle, https://jsfiddle.net/kqL2x0hp/
I have my javascript setup as centerMode => true and variableWidth => true.
Displaying 3 slides, I wanted to increase the width of center slide **slick-center** so i increased the width.
How do i properly set width for the **slick-center** and other two **slick-active**. 
I tried using nth-child but it does not seems to work. The animation looks awful because i'd set with to all of those **slick-active** class.

**Comment by sl1rt** [comment]
Use HTML markup, because slick create clones of slides with an infinite sliding setting.

**Comment by leggomuhgreggo** [comment]
Yeah slick active won't apply to the clone. At one point I was thinking about adding a clone `.clone-active` class, which I'm still considering.
