### ISSUE TITLE
Width and height mismatch in angular Material design

### ISSUE THREAD

**Issue by pradeeptirmal** [kenwheeler/slick#2835]
When i use the slider in angular material and use flex 50 next to each other, once the slider is initialized, it exceeds the flex 50 container therefore increasing the width of the parent div.
If i use it next to a non slick element, there is a mismatch in height and the layout looks off
Heres a screenshot.
![screenshot from 2017 04 11 21 01 46 png 905x449](https://cloud.githubusercontent.com/assets/15630231/24917618/5f3535a6-1efb-11e7-97be-6c07b7675e21.png)

Both the images used are of the same dimension

Slick version: 1.6.0
Angular material: 1.1.1

**Comment by leggomuhgreggo** [comment]
No fiddle/codepen so I can't say, but I assume it's related to the flexbox grow/shrink API, where the content demands of one are being recognized as having a greater demand for horizontal space. I know you say the images are the same, but I see some toggles/set elements in the one that's wider, so I'd start there.

Sometimes you can solve this by explicitly setting flex children to have the same width--I generally set them to all have width: 100%, and they'll adjust their size to accommodate on one line evenly, provided flex-grow/shrink are the same.
