### ISSUE TITLE
Filter and focusOnSelect dont work (recalculate, reinit?)

### ISSUE THREAD

**Issue by apsolut** [kenwheeler/slick#2836]
> synced carousels with 3 filters - filter isnt working for filter2 and filter3, but its working after manual browser resize., even on codepen, did try different jQuery versions, but no changes
I guess its the same thing as: https://github.com/kenwheeler/slick/issues/2513

====================================================================
#### Steps to reproduce the problem
after click on filter [movie, sport] - focusOnSelect doesnt work anymore,
its working onLoad and for first filter (strange), to make it work we only need to resize Browser = when on  2nd and 3rd filter [movie, sport].

====================================================================
IF we resize browser - its working like it should, also I cant use slick(destroy) as its creating empty slick...
* onSwipe its synced and working good (at least it look like its working).. 
* onResize (browser resize) filters (filter2, filter3) its working, but need to do that manual when on 2nd and 3rd filter [movie, sport]...
...  

====================================================================
#### Strange that its working on jsfiddle without .refresh
http://jsfiddle.net/apsolut/b2mskt2L/10/
*its the same clone of (codepen) that dont work
...

#### `[  http://codepen.io/apsolut/pen/LyPmEL  ]`  
*working: `$('#slick').slick('slickFilter', key).slick('refresh');`
added **.slick('refresh');** at the end.
> Was thinkin` it should work without refresh from the start...

**Comment by apsolut** [comment]
Its late here, but It looks like if I add `slick('refresh')` to slickFilter, like this `$('#slick, #slick-thumbs').slick('slickFilter',key);`  then its working... Kill me, but shouldnt it work without it..

**Comment by leggomuhgreggo** [comment]
There's a known issue with slick index that I think is causing what you're seeing. Pretty sure there's even a PR for it. Might try to take a look and do some testing later. Good job on the work around.
