### ISSUE TITLE
Buttons screwed up randomly.

### ISSUE THREAD

**Issue by hifall** [kenwheeler/slick#2837]
I am seeing this issue when slick is integrated into a SPA (Single Page Application), and running on Chrome 56, macOS Sierra 10.12, jQuery 1.9.1, and Slick 1.6.0. It's a random issue, and I am not able to find a reliable reproduction, nor can I reduce it to a jsfiddle case. It happens like once out of 10 times.

The scenario is: I have two divs, with each one using d3js to render data. Then I use slick to turn them into a carousel.

When the issue happens, the prev/next buttons show up like weird characters, instead of nice-looking arrows. Like highlighted in rectangles in the image below:
<img width="1077" alt="screen_shot_2017-04-11_at_9_07_59_pm" src="https://cloud.githubusercontent.com/assets/5734293/24949798/7756b582-1fa1-11e7-9102-3f622bf7c87e.png">

Examining the next button in Chrome gives:
<img width="266" alt="screen shot 2017-04-11 at 9 17 35 pm" src="https://cloud.githubusercontent.com/assets/5734293/24911187/b2613b0c-1efc-11e7-9416-a3f28a51f791.png">

Feel free to let me know if you need more info.

**Comment by Rushdev94** [comment]
Yes even i faced the same.
Just open the sorce file in Normal Notepad [Windows Default] and save the same file without changing anything just make sure you save with Encoding: UTF-8 and that should fix it
