### ISSUE TITLE
Images in the slider shake when scrolling with mouse

### ISSUE THREAD

**Issue by listentoyoureyes** [kenwheeler/slick#2838]
Im using the slick slider on a website as a header on the startpage. Unfortunately the images shake when I scroll. The header slider has also a parallax effect så that the content under the slider scrolls on top of it. I could not find any issues before that had the same problem.

**Comment by sl1rt** [comment]
You can link your bug. Problems can be in your CSS code.
However, write the version of your browser in what you test.

**Comment by listentoyoureyes** [comment]
the bug is on  http://www.polarbrod.se in the topslider. Browser is Version 57.0.2987.133 (64-bit)
