### ISSUE TITLE
Adding images causes slick carousel to malfunction

### ISSUE THREAD

**Issue by pavel06081991** [kenwheeler/slick#2841]
the issue http://stackoverflow.com/questions/27781770/adding-images-causes-slick-carousel-to-malfunction still exists.

this helps:

`$('.container').on( 'dragstart', 'img', function() { return false; } );`

But I think it must be fixed inside slick plugin.

**Comment by leggomuhgreggo** [comment]
There's an open issue for this, but I think the answers in stackoverflow do as workaround
