### ISSUE TITLE
Hot! Slick centerMode infinite slickGoTo Bug

### ISSUE THREAD

**Issue by sl1rt** [kenwheeler/slick#2844]
Hi, I need an advice!
I change slides by click on the image previews on the carousel. 

Demonstration: https://jsfiddle.net/er712r5z/4/

With 5 visible slides doesn't work clicking on -2 index slide when 0 slide is active! 
But -1 slide click works fine and if I go to 1,2,3 and other slides, -2 index click slide works fine (ever click on the left slide). How do I need to correct my code to work negative -2 index?

`$("#setSlider .setSliderListOneImage").click(function(){
        var index = $(this).parent().data("slick-index");
        $(".setSliderList").slick("slickGoTo",index);
    });
       
    $('.setSliderList').slick({
        autoplay:false,
        infinite: true,
        arrows:true,
        dots: true,
        speed: 600,
        slidesToShow: 5,
        swipe: false,
        centerMode: true,
        initialSlide: 0,
        responsive: [
            {
                breakpoint: 1400,
                settings: {
                    slidesToShow: 3
                }
            },{
                breakpoint: 768,
                settings: {
                    slidesToShow: 1
                }
            }
        ]
    });`

**Comment by sl1rt** [comment]
One more bug I found. When I use centerMode carousel with 5 showed slides if I have only 5 slides, carousel doesn't show arrows and dots and I can't change any slide to Center - I think it is really  a shortage, because it may be needed for this configuration of carousel (centerMode)

**Comment by darcyvoutt** [comment]
@sl1rt I have recently found the same issue today. Have you been able to find any resolution yet?

**Comment by sl1rt** [comment]
No. I hope the developers of the plug-in will respond because this problem is very important for use it in projects.

**Comment by darcyvoutt** [comment]
@sl1rt agreed, it's a pretty big miss. I assume (without reading the libraries code) they were accounting for the scenario where you only have one slide and the code isn't dynamic enough to deal with multiple slides.

**Comment by leggomuhgreggo** [comment]
Yeah `centerMode` has [some issues](https://github.com/kenwheeler/slick/labels/Feature%3A%20Center%20Mode). It was one of the first major additional features added and it's heavy with side effects. There might be a PR in for this though. If you find one or make one yourself, I will work with you to get it into the master.

Fairly sure this is a duplicate, so I'm closing, and either way I tagged it so when we review centerMode I can make sure I've addressed it. Thanks!

**Comment by giacomocarra** [comment]
This bug is still present in the latest version (1.9.0). I have not found any other issue that talks about this.
Has anyone found a solution?

**Comment by giacomocarra** [comment]
> This bug is still present in the latest version (1.9.0). I have not found any other issue that talks about this.
> Has anyone found a solution?

Found a solution! Adding "focusOnSelect: true" fix the bug.
This il my initialization:

`$('.selettore--track').slick({
            centerMode: true,
            centerPadding: '0px',
            slidesToShow: 5,
            infinite: true,
            initialSlide: 0,
            focusOnSelect: true`

Hope this will help someone.
I'm using slick 1.9.0 and jquery 3.3.1
