### ISSUE TITLE
preload first n slides before show

### ISSUE THREAD

**Issue by dikey94** [kenwheeler/slick#2846]
Hi guys,
What I have is:

```
<div style="display: none;">
   <div class="gallery">
      <img src="..." alt="" />
      <img src="..." alt="" />
      <img src="..." alt="" />
  </div>
</div>
```

and

```

    $('.gallery').slick({
        autoplay: true,
        arrows: false,
        autoplaySpeed: 4000,
        lazyLoad: 'ondemand',
        fade: true,
        cssEase: 'linear',
        arrows: true,
    });

```
The problem is when the first div shows up all images are not ready yet. How can I preload for example first 2 images? Thanks!

**Comment by dikey94** [comment]
This is what I'm talking about: https://gyazo.com/af24e102dcb12d8ca00e9998d613bf65

**Comment by leggomuhgreggo** [comment]
This is more or less a browser/load-time issue. Unless the dimensions or ratio is defined, there's no way for the browser to anticipate the vertical space that will be required. I like using **CSS Intrinsic Ratios** if I have a standard height; you can either use CSS Background images to cover, or some JS to fill the area defined by the ratio.
