### ISSUE TITLE
Incompatibility with certain sources

### ISSUE THREAD

**Issue by stratboy** [kenwheeler/slick#2849]
I don't know if it can be useful, but anyway: I built a form validator, it always worked well, since years:

https://gist.github.com/stratboy/18c997e2f32dc4ee623cfe8a6cbc58ff

I usually include libraries via codekit app. Basically, just append more libraries one after the other. I've found out that, if I append Validator before Slick, I'm going to get a TypeError, targeted on Validator.prototype. That happens even if I comment out every method from the prototype and even if I don't instantiate/use Validator at all.

Instead, no problem if I append Validator after Slick. Strange.
Also, no problem with any other library (until now). So maybe it's something in Slick and thus Slick  could maybe be problematic for some other libraries as well.

**Comment by leggomuhgreggo** [comment]
This is just a guess, but I wonder if it's a semicolon issue. The code you linked to doesn't have one at the end of the wrapping statement, and slick starts with an IIFE, which is one of the most common cases where semicolon absence will eff things up. Hope this helps!

**Comment by leggomuhgreggo** [comment]
Made PR #2850 to alleviate with this issue, assuming that is the cause.

**Comment by stratboy** [comment]
Thank you

leggomuhgreggo ha scritto:
