### ISSUE TITLE
slick-active class not applied properly.

### ISSUE THREAD

**Issue by scanner0928** [kenwheeler/slick#2855]
Thanks for great script!

I set the property " centered: true, slidesToShow: 2",
then the next slide is also added the "slick-active" class, before showing up to the center.
(the third slide under the above setting)

when I set "slidesToShow: 3", it works properly.

====================================================================

#### What is the expected behaviour?

remove the "slick-active" class from slides not show up the center yet.

Thank you.

**Comment by leggomuhgreggo** [comment]
Hey can you make a reduced test case in a fiddle or codepen? There might be an preexisting issue or two on this subject, that might help clarify things

Closing pending test case
