### ISSUE TITLE
Images in the slider shake when scrolling with mouse

### ISSUE THREAD

**Issue by listentoyoureyes** [kenwheeler/slick#2857]
Im using the slick slider on a website as a header on the startpage http://www.polarbrod.se. Unfortunately the images shake when I scroll. The header slider has also a parallax effect så that the content under the slider scrolls on top of it. I could not find any issues before that had the same problem.

Browser is Version 57.0.2987.133 (64-bit)

**Comment by leggomuhgreggo** [comment]
Hey can you make a reduced test case in a fiddle or codepen?

Closing pending test case
