### ISSUE TITLE
Slider does not show item in it's correct position

### ISSUE THREAD

**Issue by balexandre** [kenwheeler/slick#2858]
using these options:

```
 options = {
                infinite: true,
                slidesToShow: 2,
                slidesToScroll: 2,
                vertical: true,
                verticalSwiping: true,
                nextArrow: "<div><img src='//s3.eu-central-1.amazonaws.com/sitecampaign/production/bonaparte/resources/arrow_down.gif' class='arrow arrow_down' /></div>",
                prevArrow: "<div><img src='//s3.eu-central-1.amazonaws.com/sitecampaign/production/bonaparte/resources/arrow_up.gif' class='arrow arrow_up' /></div>"
            };
```

I'm getting:
[![](http://s6.postimg.org/aju1cccgx/screenshot_7.png)](http://s6.postimg.org/aju1cccgx/screenshot_7.png)

the `transform: translate3d(0px, -454px, 0px);` line is wrongly created as it should be `-422px` so the items could be shown as:

[![](http://s6.postimg.org/tdfu9caox/screenshot_8.png)](http://s6.postimg.org/tdfu9caox/screenshot_8.png)

What am I doing wrong? how can I tell **slick** what the height of each item?
tried with CSS on my own `carousel-item` but it does not care that much about it :/

**Comment by leggomuhgreggo** [comment]
Hey can you make a reduced test case in a fiddle or codepen?

Closing pending test case
