### ISSUE TITLE
Load specific slide on load without the animation

### ISSUE THREAD

**Issue by drdiv** [kenwheeler/slick#287]
Thank you for such an excellent plugin. Is there way to default to a specific slide on initial load? Currently I'm using slickGoTo() method which produces an animation each time the page loads, but I would like to avoid the animation.

**Comment by kenwheeler** [comment]
Fixed

**Comment by red2678** [comment]
:+1:

**Comment by Elven11** [comment]
Thank you kenwheeler... I actually needed the animation and couldn't figure it out why it isn't working with true specified!
Docs surely need an update on that.
