### ISSUE TITLE
autoPlaySpeed Being Ignored?

### ISSUE THREAD

**Issue by PowrSlave** [kenwheeler/slick#2873]
#I am setting autoPlaySpeed to 5000 and it appears to be ignored since the slides are transitioning much faster. I've tried setting it it 15000 and it still has no effect. The other options I set are being honoured. 

Here is a link to an S3 bucket link illustrating the problem: https://s3.amazonaws.com/aws-website-asgctdatavisualizationdevelopment-p93i0/speed-test.html

Here are the settings I am currently using: 

`$("#slide-container").slick({`
`          dots: false,`
`          infinite: true,`
`         slidesToShow: 1,`
`        slidesToScroll: 1,`
`       speed: 1000,`
`      autoplay: true,`
`     autoPlaySpeed: 10000`
` });`

**Comment by PowrSlave** [comment]
Actually nevermind. There is clearly a plugin bug since changing autoPlaySpeed in the slick.js file fixes the problem.

**Comment by rondog** [comment]
the setting is `autoplaySpeed` not `autoPlaySpeed`
