### ISSUE TITLE
Feature request: Add non-anonymous slide selector default

### ISSUE THREAD

**Issue by gausarts** [kenwheeler/slick#289]
I play a lot with the plugin, thanks for the great one!
I am currently building a back-end for my CMS. I am facing a small issue:
I wonder if you can possibly change or add default slide selector from anonymous DIV to say more selective ".slide" (since ".slick-slide" is JS generated)?

The reason is efficiency on extending defaults, and avoiding conflict with custom added DIV selectors.

I want to add additional .slide__arrow DIV to wrap arrows. Also with responsive displays, I have to add each my own .slide selector overrides.

Since anonymous DIV is the default slide selector, slick wraps them all if I don't do override. I have to repeat adding ".slide" selector to every responsive display override. This is okay if you have one or two slides in a page, however having multiple slides, this becomes in-efficient in terms of overrides. Although my CMS makes it easy to add them, the overrides have added several duplicate .slide selector.

With the non-anonymous DIV, I am safe to just extend the necessary overrides.

What do you think?

Thanks,
gaus

**Comment by kenwheeler** [comment]
Closing as a dupe
