### ISSUE TITLE
adaptiveHeight not working on Responsive breakpoint

### ISSUE THREAD

**Issue by candyshien** [kenwheeler/slick#2896]
adaptiveHeight working great on " slidesToShow: 2" when it load and onClick on read more button.   

When on Responsive breakpoint 768 adaptiveHeight  not working on "slidesToShow: 1" when onClick ead more button. The adaptiveHeight not working.   

When on Responsive breakpoint 768, onClick ead more button; Only when try to resize the browser or drag the slider the adaptiveHeight work.

====================================================================

###### (http://jsfiddle.net/nzrgd8bc/30/)

**Comment by alina-holletzek** [comment]
Have you found a solution yet?

**Comment by candyshien** [comment]
Found solution, 

[http://jsfiddle.net/nzrgd8bc/31/](http://jsfiddle.net/nzrgd8bc/31/)
