### ISSUE TITLE
Focus blocked inside slider

### ISSUE THREAD

**Issue by Szymon-dziewonski** [kenwheeler/slick#2901]
Hello, I found out that jquery focus and blur functions doesnt work inside slick.js slider 

###### [JsFiddle](http://jsfiddle.net/zuvedht3/1/) : http://jsfiddle.net/zuvedht3/1/

====================================================================

#### Steps to reproduce the problem

1. Create slick working instance 
2. Add inside input 
3. Try to use focus on input 
```
$(document).on("focus", "input", function() {
  console.log("focus")
});
```
Its simple action but I cannot make input react on focus and blur

====================================================================

#### What is the expected behaviour?
Make focus and blur working :)

====================================================================

#### What is observed behaviour?
function doesn't work, for compare there is input outside initialized slick slider in example and the same function with delegation on input with focus works

====================================================================

#### More Details

- Which browsers/versions does it happen on? 
Every Each browser 
- Which jQuery/Slick version are you using?
Slick 1.6.0 , jQuery edge same as in your example
- Did this work before?
Didn't check it before

**Comment by raisen** [comment]
I noticed if you use addEventListener, it works: [JSFiddle](http://jsfiddle.net/6zz6kp15/).

**Comment by axebox** [comment]
This should still work with jQuery. I'm able to reproduce as well.

**Comment by SpeedyTechie** [comment]
+1. This is annoying.

**Comment by dariodev** [comment]
Agree. Annoying. It's because of `focusHandler` function which handles pauseOnFocus. As a quick solution I disabled this function by removing line `event.stopImmediatePropagation();` around L1021, as I don't use pause on focus. 
@kenwheeler could you add a setting to disable this behavior? In my example I'm using a from inside slider and I need focus and blur.

**Comment by davemacaulay** [comment]
`event.stopImmediatePropagation();` is used within the `focusHandler` to ensure if any child element takes the focus that the parent slider will still remain focussed, rather than the child item taking the focus. Working on a fix now.
