### ISSUE TITLE
Using slick with es6 and broswerfy

### ISSUE THREAD

**Issue by katawura** [kenwheeler/slick#2905]
Is there an easier way to use Using slick with es6 and broswerfy with broswerfy and es6?

**Comment by mike3run** [comment]
```js
import $ from 'jquery'
import 'slick-carousel'

$('.slider').slick()
```

**Comment by mike3run** [comment]
I don't see how thats not easy

**Comment by mishalrai** [comment]
I got this kind error 
 > Mismatched anonymous define() module: function($)

**Comment by shelldandy** [comment]
ok
