### ISSUE TITLE
RTL Mode Breaks A Carousel

### ISSUE THREAD

**Issue by stmalk** [kenwheeler/slick#2907]
I'm trying to use rtl:true, in a carousel but it breaks the whole thing completely, all the images just disappear, while the carousel keeps working. 

I saw that issue https://github.com/kenwheeler/slick/issues/483 and it's very similar but I don't think anything was fixed since then, and that last comment doesn't make any sense - where is that explicit option in settings, is it in slick.min.js or or in the settings I use to set up a carousel? But the syntax there is completely different from what the author suggests. 

Right now my options are set to:

		jQuery('.cs-slider_tier3 .slides').slick({
		slidesPerRow: 10,
    	rows: 2,
    	rtl:true,
		autoplay: true,		
		adaptiveHeight: false,
		dots:true, 
		autoplaySpeed: 5000
	});

If I remove rtl:true - everything works fine.

Thank you

**Comment by sharathdaniel** [comment]
Any updates on this? Having the same issue.

**Comment by xavortm** [comment]
If someone comes to this issue (which I still believe is a bug in the core) Add to the slider wrapper `dir="ltr"` and it will _fix it_. At least it worked out in my case

**Comment by GJihed** [comment]
@xavortm thanks ! it works fine for me !
