### ISSUE TITLE
slick-theme.css not working when using local files

### ISSUE THREAD

**Issue by zen0x90** [kenwheeler/slick#2908]
> short description of the bug / issue, provide more detail below.

====================================================================

I'm using everything local (so I download all external files) so I tried slick library and it works fine. But when using slick-theme.css its not working anymore (I had to download slick.ttf and slick.woff). Nothing appears except the first "<div>" (image or text).

http://jsfiddle.net/2dcrm8bu/1/

====================================================================

#### Steps to reproduce the problem

1.Use only local files (download slick files to use it without external links)
2.Then add add slick-theme.css

====================================================================

#### What is the expected behaviour?

Use the theme in the demo 

====================================================================

#### What is observed behaviour?

The content of the first "<div>" and nothing else.  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Mozilla Firefox 43.0.4
Opera 35.0.2066.37
Chromium 48.0.2564.82 

- Which jQuery/Slick version are you using?

1.6.0

- Did this work before?

Without slick-theme.css

**Comment by zen0x90** [comment]
Fixed ! By adding "arrows:true" (well I didn't even find this in the docs...)

**Comment by Asha-Varshney** [comment]
Where you added "arrows:true" ?
