### ISSUE TITLE
Slider disappear while drag to next slides

### ISSUE THREAD

**Issue by farookibrahim** [kenwheeler/slick#2915]
Hi Folks,

When i drag slider or click next dots will cause slider disappear. You can reproduce this issue from below link.

https://codepen.io/farookibrahim/pen/WjZgBX

Thanks,
Farook

**Comment by apsolut** [comment]
`$(".products").slick({
	"infinite":false,
  "slidesToShow":7,
  "dots":true,
  "arrows":true,
  "slidesToScroll":7,
 });`

- also use jQuery 1.x or 2.x

**Comment by leggomuhgreggo** [comment]
Interesting. I will add it to the list of things to look into. Thanks!

**Comment by farookibrahim** [comment]
Thank you @apsolut for the fix.

**Comment by farookibrahim** [comment]
Thank you @leggomuhgreggo.
