### ISSUE TITLE
Spacing issue on centerMode and Infinite with slideCount < slidesToShow

### ISSUE THREAD

**Issue by TonyShark19** [kenwheeler/slick#2917]
I was experiencing an issue when there are less slides available than to show with centerMode and Infinite both set to True. The transform3D was setting the value way too high and slides were being pushed off the screen without the arrows showing, since there aren't enough slides to trigger the arrows. Here are the settings on the JS i am using to init the slider:

```
$('.slickslider').slick({
	dots: true,
	infinite: true,
	speed: 300,
	adaptiveHeight: true,
	slidesToShow: 7,
	slidesToScroll: 1,
	centerMode: true,
	centerPadding: '40px',
	swipeToSlide: 1,
	prevArrow: '<button type="button" data-role="none" class="slick-prev slick-arrow" aria-label="Previous" role="button"><span class="glyphicon glyphicon-chevron-left" style="color: black;"></span></button>',
	nextArrow: '<button type="button" data-role="none" class="slick-next slick-arrow" aria-label="Next" role="button"><span class="glyphicon glyphicon-chevron-right" style="color: black;"></span></button>',
	responsive: [
		{
			breakpoint: 1200,
			settings: {
				slidesToShow: 5
			}
		},
		{
			breakpoint: 992,
			settings: {
				slidesToShow: 3
			}
		},
		{
			breakpoint: 768,
			settings: {
				slidesToShow: 2
			}
		}
	]
});
```

I corrected this issue with a small change to one of the functions. The fix for this on my end was to modify the getLeft function on line 1105 to:
```
       if (_.options.centerMode === true && _.options.infinite === true) {
            if (_.slideCount <= _.options.slidesToShow) {
                _.slideOffset += Math.floor(_.slideWidth * (_.options.slidesToShow - _.slideCount)) / 2;
            } else {
                _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2) - _.slideWidth;
            }
        }
```

Now it is spacing the slides properly and responsively! Hopefully this helps if anyone else is running into this issue!

PS. Including the js and min.js in case someone wants them :)
[slickjs.zip](https://github.com/kenwheeler/slick/files/1045242/slickjs.zip)

**Comment by orthes** [comment]
Same problem here. @TonyShark19 thanks. Your fix works. Can you submit a pull request instead of attaching a ZIP file?

**Comment by TonyShark19** [comment]
@orthes glad it worked! I'm new to GitHub, but I'll try!

**Comment by TonyShark19** [comment]
@orthes I went to submit a pull request and I saw there was already a change for this part of the code. I tested the new JS files and they are working for me with the committed changes instead of mine. Seems things are alright without this change. Can you test on your end to see if the new code solves it for you as well?
