### ISSUE TITLE
Event after init/init not work like i expected

### ISSUE THREAD

**Issue by andig89** [kenwheeler/slick#2918]
Problem is when I create swiper to new created element (document.createElement), add it to page and for example try add swiper to control in another swiper. If init's not end, control not work. Of course I can add timeout or interval but it's not good solution.

The same problem but in simpler case You can see below.
https://jsfiddle.net/andig89/1pnyk90n/

**Comment by leggomuhgreggo** [comment]
Wrong repo?

**Comment by andig89** [comment]
Yeap, sorry.
