### ISSUE TITLE
Issue with 1920px width slider

### ISSUE THREAD

**Issue by aslamdoctor** [kenwheeler/slick#2919]
I am trying to build a full width image slider using slick.
The thing is, all the images are **1920px** wide and they have max-width set to 100%. So they are responsive for smaller screen.

Below is the sample fiddle I have implemented. 
https://jsfiddle.net/wjjLyq3s/4/

I haven't added any image here but the issue is appearing same here. If you load for the first time, the slide on the right side is visible slightly. But once you move to next slide, everything is full width without any issues. 

So the fix is needed so the slide on right side is not visible at the first load.

Please note that I have used the divs with 1920px width here in fiddle but in my real slider code, I am not assigning any width to the images as those are alreaday 1920px and I have made their max-width to 100% to work responsively.

**Comment by leggomuhgreggo** [comment]
Sounds like maybe `overflow: hidden` on slick-slide would help
