### ISSUE TITLE
carousel next and previous highlight of arrow button isn't disappear - Chrome 

### ISSUE THREAD

**Issue by TanveerAliS** [kenwheeler/slick#2920]
> short description of the bug/issue, provide more detail below.

Once we click on Next/Prev arrow, active class will be remain applied on that element unless we click on other place on page. But in safari, It will be highlight only on Mouse hover.  

Can we provide the same behaviour on all broswers as safari ? 
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. Open Any Slick demo in Chrome browser, click on next/Prev arrow button.
2. observe that active class in applied on Next/Prev arrow button unless we click on other places. 

====================================================================

#### What is the expected behaviour?

The highlight should be only on mouse hover as same as Safari browser.

====================================================================

#### What is observed behaviour?

Highlight will remain active on Next/prev arrow on chrome browser.
====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome Latest 
- Which jQuery/Slick version are you using? jQuery - 2.0.3 and Slick - 1.3.15
- Did this work before? Nope

**Comment by flaviocysne** [comment]
@TanveerAliS hi, I saw the jsfiddle you provided and noticed that after click Prev or Next button it remains focused, as expected for a button after been clicked.

I tested the jsfiddle on Chrome 54.0.2840.100 (64-bit) and Firefox 45.3.0 and the results are the same: the button keeps focused after clicking.

This behavior is controlled by `slick-prev:hover, slick-next:hover, slick-prev:focus, slick-next:focus` styles, declared in slick-theme.css. Maybe you could override those `:focus` styles to mimic Safari's behavior, as I understand that the actual behavior in other browsers is consistent with the stylesheet code.

Hope I could be of any help. Best Regards.
