### ISSUE TITLE
documentation error for init

### ISSUE THREAD

**Issue by pskrz** [kenwheeler/slick#2921]
I think the documentation is wrong, if you pass in two arguments to onInit 
<img width="968" alt="screen shot 2017-05-31 at 10 30 32 am" src="https://cloud.githubusercontent.com/assets/605522/26725465/ad999a90-476c-11e7-9200-6e43969864ce.png">
then you get an event and a slick instance available in the function . There is a large class of questions and issues surrounding this around the internet, and they could all likely be resolved with a small documentation update.

If you only pass in 1 argument you get the event and not the slick slider instance, very misleading.

See https://github.com/kenwheeler/slick/issues/2395

**Comment by pskrz** [comment]
this is the documentation from http://kenwheeler.github.io/slick/  in the Events section 

If you dig in a bit you can see some of the functions explicitly state event as an argument, but some don't

**Comment by pskrz** [comment]
@leggomuhgreggo Are you going to fix the documentation or can you point me in the direction to do it? I'm not the first person to get bit by this

**Comment by pskrz** [comment]
@leggomuhgreggo I see it's correct in the README (https://github.com/kenwheeler/slick#events) , i'm not sure how to get the forward facing site corrected (http://kenwheeler.github.io/slick/).

**Comment by uid0gid0** [comment]
Going by the webdoc I completely missed the fact that there are two arguments to the init event. I found this a tad odd, so I went googling and stumbled upon this issue. Great heads up for anyone who are looking for the same info as I was. It gets very confusing as some events explicitly expresses usage of the `event` argument, while others doesn't.
