### ISSUE TITLE
Error with flexbox width or % width in Semantic-UI integration

### ISSUE THREAD

**Issue by bloodf** [kenwheeler/slick#2923]
When using the Slick Slide with Semantic-UI, if you use declare the slider to a grid with columns, or cards you have to use adaptivewidth and a large margin, the slick slider don't work well with % width and flexbox width that makes a complete mode.

**Comment by leggomuhgreggo** [comment]
Flexbox widths are a little tricky. Search previous issues for more info on issues and fixes.
