### ISSUE TITLE
Error when set initialSlide with specific value

### ISSUE THREAD

**Issue by samuelfr** [kenwheeler/slick#2927]
Error when set initialSlide with specific value

====================================================================

[http://jsfiddle.net/qdwtve60/](http://jsfiddle.net/qdwtve60/)

==============================`======================================

#### Steps to reproduce the problem

1. Init a Slick with 5 slides and options like this { slidesToShow: 3,    slidesToScroll: 2,    initialSlide: 1 }
2. And try to go to the 1st or the 5th slide

====================================================================

#### What is the expected behaviour?

Move to the wanted slide

====================================================================

#### What is observed behaviour?

Slick is block

====================================================================

#### More Details

- Which browsers/versions does it happen on? Test on Chrome and IE
- Which jQuery/Slick version are you using? 1.6.0
- Did this work before? no

**Comment by yaodingyd** [comment]
@samuelfr Because you set `infinite: false` so there is not enough slides to scroll, thus it's `blocked`.

**Comment by diegosomar** [comment]
Hello @yaodingyd , if the `infinite` must be `true`, this problem persists.
Look: http://jsfiddle.net/qmpn7aLb/

In this case, we see a calendar, which the initial slide is the current day. Day 25 is active (example).
After click left arrow, dots change, but slide don't. When it occours, the left edge is not reached.

I have a more detailed explanation in [this issue](https://github.com/kenwheeler/slick/issues/3580). I appreciate if you can help to clear my mind, I don't know more what I have to do.

Tks!
