### ISSUE TITLE
CustomPaging doesnt work with html snippet

### ISSUE THREAD

**Issue by alaknanda** [kenwheeler/slick#293]
I tried something like this :
<pre>
customPaging: function(slider, i) {
                  return '&lt;div&gt;&lt;p&gt;abcd&lt;/p&gt;&lt;p&gt;qwerty&lt;/p&gt;&lt;/div&gt;'
                },
</pre>
The slides dont change .
<pre>
 However, if the html is changed to &lt;div&gt;abcd&lt;/div&gt;, then the pagination works fine.
</pre>

**Comment by aaronstezycki** [comment]
Not sure if this has been fixed yet? Just gonna bump this so it gets noticed again. @kenwheeler

**Comment by gigi** [comment]
String 667
Slick 1.5.0
I think it has to be changed

event.data.index || $(event.target).parent().index() * _.options.slidesToScroll;
to
event.data.index || $(event.target).index() * _.options.slidesToScroll;

**Comment by simeydotme** [comment]
Recently fixed by: https://github.com/kenwheeler/slick/commit/f66ac9e155f249f8d034a81ed61793c6b56efbd7 :kissing_heart:

**Comment by daysable** [comment]
@simeydotme, thank you for that jsfiddle example. But how would add active states to the custom pagination? I'm having difficulty there.

**Comment by daysable** [comment]
Nevermind! I figured it out.

**Comment by rijosh** [comment]
@simeydotme  How can i append this custom pagination to a particular div. cause i need to one button near this pagination 
![image](https://user-images.githubusercontent.com/9720488/30023484-b189fa38-9180-11e7-805f-9856691e0b12.png)
