### ISSUE TITLE
It seems like mobile safari crashes when slick-track gets too large.

### ISSUE THREAD

**Issue by aagd** [kenwheeler/slick#295]
I have a large slider with 110 images (720x720px). I replaced the images with empty divs to be sure it's not the images that cause the crash. At around 67000px my iPad 3's Safari (latest iOS) crashes. The exact number seems to vary. My iPhone 3GS (iOS 6.1.6) seems to crash at similar values. Any ideas for a workaround? Or a different slider that doesn't use a giant div like slick-track?

Edit: Removed broken demo link

**Comment by garrying** [comment]
@kenwheeler I was experiencing this issue with the latest version, but adding `transform: translate3d(0, 0, 0);` to `img` resolved it. I think it would be a benefit to add it to core for anyone dealing with large sets.

**Comment by kenwheeler** [comment]
@garrying wanna PR?

**Comment by murielg** [comment]
@kenwheeler I have a slider with 66 images that keeps crashing after about 30~ slides. I used to have 2 sliders on the same page, each as a nav for the other, and the site would crash after scrolling about 18~ slides. I've removed the second slider, but I am still having issues, even after applying the transform: translate3d(0, 0, 0); fixes described earlier on this thread. Any thoughts/suggestions would be greatly appreciated.
Thanks!

**Comment by kenwheeler** [comment]
@murielg how big are the images?

**Comment by murielg** [comment]
They are big at all. In dimension they 600px wide or less, and no more than 400px tall. In size, the largest about 35 KB, but the majority of them are 10 KB or less.

**Comment by traummmaschine** [comment]
@kenwheeler @murielg I too am having issues on iOS (Safari and Chrome) crashing with a large full screen slider (above 15 / 20 large images it crashes) with 1.6.0.

I too tried the above transform3d additions, but no luck. However, when I commented out 'float:left;' under .slick-slide in the CSS, I found it no longer crashes – though I needed to add the following to .slick-active to ensure the current slide was still in view:

`.slick-slide {
    float: none;
}

.slick-active {
    left: 0 !important;
    position: absolute !important;
    top: 0 !important;
}`

I've yet to test this fully across browsers – but also important to note I'm using the fade transition. This wouldn't work when using the 'slide' transition.

**Comment by leggomuhgreggo** [comment]
@traummmaschine thanks for the intel.  I did some googling, and [some people are finding](http://stackoverflow.com/questions/11831429/mobile-safari-on-ios-crashes-on-big-pages) the use of 3d transforms to be the culprit. I guess the advantages in framerate from hardware acceleration come at the cost of increased memory consumption which appears to not be managed well by safari mobile.

Your approach is interesting, but I'm cant see how to incorporate something like that into the codebase. I'm wondering if doing the opposite of prior intuitions and setting `useTransform: false` might help. I don't know you're set up, but I can also see fade, with custom css for the animation possibly working. 

Thanks!

**Comment by 3zzy** [comment]
Sorry to dig up an old issue but I came here specifically looking for memory issues with large galleries. I'm looking to use slick for galleries (ebooks rather) with upto 1000 images and was wondering how it performs.

I currently use PhotoSwipe and it works well because:

>- PhotoSwipe keeps only three images in the DOM at once, because each “slide” is a composited layer, which consumes quite a lot of memory.
>- Almost no memory is consumed until the gallery is first opened.
>- The script has been tested for memory leaks. Navigating images back and forth and creating or deleting a gallery doesn’t leave a trace in memory.

>- RequestAnimationFrame is used wherever possible.
>- Only the transform and opacity properties are animated. Almost no paints occur during animation, making transitions as smooth as possible.

..but it lacks RTL support so I'm looking to switch. 

So I'm wondering if you already do the same with lazy loading enabled?

**Comment by TinyChou** [comment]
As @3zzy post.I encounter the same problem on some iPad tablets( which memory space only 1G).First, My images(50images and 300kb+- per image) loaded into the html Swiper. I try to zoom out/in and device crashed with memory issue: 
``shell
Message from debugger: Terminated due to memory issue
``
I will turn to try PhotoSwipe.

**Comment by yashbh** [comment]
any updates on this , i need to find a replacement because i am facing this issue , page crashes when too many slides

**Comment by zaderade** [comment]
After trying all of the fixes mentioned here, Safari still crashes on my iPhone 16 Pro when there are more than ~3 slick sliders on a page and I pinch to zoom out after zooming in. Can this issue be re-opened?
