### ISSUE TITLE
Inconsistency in usage docs

### ISSUE THREAD

**Issue by deedeethan** [kenwheeler/slick#2951]
> short description of the bug / issue, provide more detail below.

In the Usage section of the demo page (http://kenwheeler.github.io/slick/), this is the line for using slick.min.js:

`<script type="text/javascript" src="slick/slick.min.js"></script>`

In the README of the repo on GitHub, this is the line:

`<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>`

This inconsistency caused very confusing problems - would be great if the two could match.

**Comment by ahmadalfy** [comment]
The README version talks about using CDN to deliver the files. I think it is obvious that you can either download the plugin from the CDN or by downloading it.
