### ISSUE TITLE
** Feature request *** Margin option please!

### ISSUE THREAD

**Issue by zzseba78** [kenwheeler/slick#2963]
Awesome plugin, but please **add a margin option** to control the space between items!
Of course with visible items aligned at the slide container sides.

I see same feature request but long time ago and closed, with some css hacks that don´t work.

Please! Slick is super complete, I can´t believe It doesn´t have this option already.

![margin](https://user-images.githubusercontent.com/5558563/27735679-3e8e45d0-5d77-11e7-8898-c85a51eb97f9.png)

**Comment by leggomuhgreggo** [comment]
Although it's a little cumbersome, this can be accomplished with CSS, but I agree it's a worthy enhancement. There's another open issue about it somewhere so I'm gonna close this. PR's welcome! Thanks
