### ISSUE TITLE
rtl doesn't work

### ISSUE THREAD

**Issue by maofree** [kenwheeler/slick#2968]
> short description of the bug / issue, provide more detail below.

Slick doesn't show slides
when infinite is on true nothing is show instead when it is on false it is shown only the first slide

====================================================================

https://jsfiddle.net/maofree/z7eq6azg/3/

====================================================================

#### Steps to reproduce the problem

it happens on all examples

====================================================================

#### More Details

- Which browsers/versions does it happen on?  firefox 54.0.1 on linux
- Which jQuery/Slick version are you using? last slick.js 1.6 
- Did this work before?

thanks
bye

**Comment by makshh** [comment]
Did you add `dir="rtl"` to the slider parent o `html` element?

**Comment by maofree** [comment]
Hi
I don't know that, however I'll try it tomorrow
thanks

**Comment by maofree** [comment]
do you suggest like that?
<div dir="rtl">
<div class="slider">
    <div>slide1</div>
    <div>slide2</div>
    <div>slide3</div>
    <div>slide4</div>
    <div>slide5</div>
    <div>slide6</div>
</div>
</div>

I've updated the example on jsfiddle but I get the same error

**Comment by makshh** [comment]
Yes, but I think you have to change this attribute depending on your breakpoint

[JSFiddle](https://jsfiddle.net/maofree/z7eq6azg/3/)

**Comment by maofree** [comment]
Hi
thanks makshh
I've understood how it works
bye

**Comment by Ardeshir81** [comment]
Would you please share ? Thanks ! :)

**Comment by fayazrehmani** [comment]
Please help I have used dir = rtl the slides not working properly only first is showing
that also when infinite is turned off

**Comment by shevchenko1983** [comment]
> Please help I have used dir = rtl the slides not working properly only first is showing
> that also when infinite is turned off
> clicking next slides slider but slide seems to be in ltr direction empty slide sliding in.

Try used dir = ltr. For example add to
 .slick-slider .slick-track, .slick-slider .slick-list {
    direction: ltr;
}
It will works)

**Comment by mostafazs** [comment]
This works for me:
```
[dir='rtl'] .slick-slide
{
    float: left;
}
```
and
```
.slick-slider .slick-track, .slick-slider .slick-list {
direction: ltr;
}
```

**Comment by yelsayed** [comment]
@mostafazs thank you so much!!!!

**Comment by moamahfouz** [comment]
> This works for me:
> 
> ```
> [dir='rtl'] .slick-slide
> {
>     float: left;
> }
> ```
> 
> and
> 
> ```
> .slick-slider .slick-track, .slick-slider .slick-list {
> direction: ltr;
> }
> ```

Thanks a lot!
