### ISSUE TITLE
custom arrows

### ISSUE THREAD

**Issue by antokara** [kenwheeler/slick#297]
Hi,

It would be really helpful if we could have custom HTML snippet for the arrows, so all you would need is a property to replace the

```
<button type="button" class="slick-prev">Previous</button>
<button type="button" class="slick-next">Next</button>
```

Because some CSS frameworks have by default a ton of custom styling on button elements which I have to override and reset just for the arrows...

Another reason would be to give the ability to use SVG instead of font icon for arrows, etc.

Thanks!

**Comment by skybondsor** [comment]
What are the constraints on this? I'm trying to use the following and they don't work:

`<a class="slick-prev nav-icon" href="#" title="Previous Step"><span class="glyphicon glyphicon-circle-arrow-left"></span></a>`

**Comment by leggomuhgreggo** [comment]
Betting it's either CSS or the glyphicon isn't loading. slick-prev and slick-next has `font-size: 0` that could be giving you trouble. Hard to say without a fiddle--check out [the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)--there's a fiddle you can fork pretty easily.

**Comment by skybondsor** [comment]
Th icons show just fine – they look correct, etc. But when I click the link, it has no click event attached to it and just adds the has to the URL.

**Comment by leggomuhgreggo** [comment]
Can you recreate in a fiddle?

**Comment by skybondsor** [comment]
I ended up not being able to recreate the issue in a fiddle, which led me back to the real problem: The click wasn't returning false, so the link was firing and upsetting the slideshow functionality. Whether or not that's an issue with Slick, I can fix it on my end. 

Thanks for forcing me to be more diligent!
