### ISSUE TITLE
continuous scroll with horizontal scroll

### ISSUE THREAD

**Issue by fsabreu** [kenwheeler/slick#2971]
Hi guys, 

I'm using slick slide with continuous scroll settings. Like this [http://jsfiddle.net/ierpe/qrL0vor8/](http://jsfiddle.net/ierpe/qrL0vor8/).

But my client wants to use a horizontal scroll to access the latest images faster.  

I tried to force an overflow-x: scroll. But the slider does not recognize that I'm at the end and does not show the first images again. (Inifiniteloop: True).

Can you help me with that?

Thanks

**Comment by dmansof** [comment]
I've same problem too I think.
I want to be able to scroll with the mouse and swipe slides.

my settings:

                            arrows: false,
                            infinite: true,
                            centerMode: true,
                            speed: 100,
                            variableWidth: true,
                            swipeToSlide: true,

**Comment by fsabreu** [comment]
Nothing?

**Comment by t00ki** [comment]
Just disable arrows by adding this option:
`arrows: false`
and it become workable.

**Comment by leggomuhgreggo** [comment]
Hey continuous scrolling has a known issue where one slide change needs to complete before the next one can finish. I think you could technically move a nested element with CSS and set the speed to 0. Best of luck!

**Comment by KendallWeihe** [comment]
Any word as to if this is yet natively supported?

**Comment by RocketSolutions** [comment]
https://webisora.com/blog/implementing-mouse-scroll-slick-js/

**Comment by Baskina** [comment]
This is my simple solution:

`.slick-next {
    right: 0;
    z-index: 1;
  }
  .slick-prev {
    left: 0;
    z-index: 1;
  }`
