### ISSUE TITLE
centerMode/slidesToScroll issues

### ISSUE THREAD

**Issue by powerbuoy** [kenwheeler/slick#2972]
I know variations of this issue are all over your Github and I don't mean to repeat what others have already said.

But I'm trying to create a centered slideshow (`centerMode: true`), that is _not_ infinite (`infinite: false`), that shows 3 slides and _scrolls_ 3 slides as well.

Unless I'm mistaken that's impossible - correct? With `centerMode: true`, `slidesToScroll` is always set to 1 - right?

What's so puzzling about this is that if I look at this site: https://kinfolk.com/ (the slideshow beneath "SELECTED STORIES FROM ISSUE TWENTY-FOUR") somehow they've managed to show 6 slides _and_ scroll 6 slides. And I know they're using Slick.

Another thing they've managed to solve which I'm unable to solve is to show 6 slides on the "first page" and all subsequent pages. When I set `infinite: true` I get the same behavior (every page shows the same number of slides) but when I set `infinite: false` the first page doesn't show any slides to the left of the centered slide.

**How it should work - 3 pages of 6 slides each, every page shows 6 slides**

<img width="1415" alt="screen shot 2017-07-05 at 16 42 40" src="https://user-images.githubusercontent.com/1027780/27869749-2dc071fa-61a1-11e7-87fc-e55d21b68384.png">

**How it works for me - 6 pages with 1 slide each, first page only shows 2 slides**

<img width="1201" alt="screen shot 2017-07-05 at 16 42 50" src="https://user-images.githubusercontent.com/1027780/27869750-2dc381c4-61a1-11e7-8961-11861131d49f.png">

So my question is; How can I achieve what they've achieved at Kinfolk? I've checked their (minified) source and from what I can gather all they do is set `slidesToShow: 6`, `slidesToScroll: 6`. How come it works there but not for me?

I am using the latest version of Slick.

**Comment by yaodingyd** [comment]
@powerbuoy This website is not using `centerMode` at all.  It styles `slick-list`with ` overflow: initial` and make all `slick-slide` which is not active has some opacity style. like this:http://jsfiddle.net/fyj4e38s/

**Comment by powerbuoy** [comment]
Oh :P I didn't even realise that. Ok so that solves my issue, thanks :)
