### ISSUE TITLE
How is Lazy Load Progressive lazy loading?

### ISSUE THREAD

**Issue by Jakobud** [kenwheeler/slick#2973]
The lazy loading option "progressive" appears to load every single image in my carousel when Slick is initialized. How exactly is this "lazy loading" and how is it different than just not lazy loading? The same thing seems to happen when I'm not lazy loading. The whole idea behind lazy loading anything is loading something only when it's requested.

====================================================================

#### Steps to reproduce the problem

1. Make a slick slider that uses `lazyLoad: 'progress'`
2. Open up chrome dev tools network panel and watch every single slide image load in the background

====================================================================

#### What is the expected behaviour?

Seems like lazy loading should only load something when it's requested

====================================================================

#### What is observed behaviour?

It loads everything. Doesn't appear to be any different than not using lazy loading at all.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
All browsers
- Which jQuery/Slick version are you using?
The jQuery 2.x and the latest Slick
- Did this work before?
It's not broken. It just doesn't appear to be expected behavior

**Comment by leggomuhgreggo** [comment]
From the docs:
> 'ondemand' will load the image as soon as you slide to it, **'progressive' loads one image after the other when the page loads.**

instead of all at once, it throttles
