### ISSUE TITLE
Responsive settings via data-slick

### ISSUE THREAD

**Issue by elemis** [kenwheeler/slick#2974]
Isn't it possible to set responsive settings via data-slick? I can't seem to make it work. Please check jsfiddle I created: http://jsfiddle.net/trxfdznr/ (Works properly without the responsive setting)
Hope someone can help. This is really important for me.

**Comment by makshh** [comment]
http://jsfiddle.net/trxfdznr/1/

**Comment by elemis** [comment]
Thanks!
