### ISSUE TITLE
BACKGROUND IMAGE LOADING PROBLEM? 

### ISSUE THREAD

**Issue by manjhawar96** [kenwheeler/slick#2975]
Hey, I have encountered a problem while working with the carousel. 
The problem is that the background images of the first three elements of carousel don't load after a repetition. I am attaching screenshots to explain better. 

<img width="1377" alt="screen shot 2017-07-06 at 3 20 14 pm" src="https://user-images.githubusercontent.com/19519057/27905800-c4751714-625e-11e7-9964-e0f71a23a01a.png">
<img width="1391" alt="screen shot 2017-07-06 at 3 20 28 pm" src="https://user-images.githubusercontent.com/19519057/27905807-c8c530ba-625e-11e7-99f7-e5394284f0cb.png">
<img width="1406" alt="screen shot 2017-07-06 at 3 20 42 pm" src="https://user-images.githubusercontent.com/19519057/27905811-cb6e2880-625e-11e7-9d2e-c79589bd816b.png">

**Comment by manjhawar96** [comment]
Please let me know where the bug can be?

**Comment by leggomuhgreggo** [comment]
Can you reproduce in a jsfiddle or codepen?
