### ISSUE TITLE
Unslick and Lazy Load

### ISSUE THREAD

**Issue by jhegman** [kenwheeler/slick#2976]
Has anyone had issues with using "unslick" and ondemand lazy load.  My issue is that once the slider is unslicked, it only loads the first 4 images (because my 'slidesToShow' is set to 4).  

Is there a method I could call in the destroy event that would load all the images?

Thanks.

**Comment by leggomuhgreggo** [comment]
I think you'd need to turn the attributes with the src into images on unslick. Interesting issue.
