### ISSUE TITLE
Problem with touchTreshold. I want to get carousel less flexible

### ISSUE THREAD

**Issue by dmansof** [kenwheeler/slick#2977]
hi,
thanks for this carousel, is really amazing. ways to support it?
well, i want to customize it. I'm creating a js widget with actionable cards inside.
depending on the width of the page, the card container is responsible. cards are not responsible, fixed witdh. so the number of cards seen depends on the width of the page.

well, if im on mobile, ive no problem cause i can see just one slide and i can swipe well.
if im on desktop, and imagine... i have 5 cards displayed, -1 -2 0 (middle) 1 2 and i want the slide/card 2 be on the center i touch the carousel, drag and... how can i explain it... i need to drag more than the center to the left to get the card in the center.

i've tried everything, here mi cfg

                        arrows: false,
                        infinite: true,
                        centerMode: true,
                        variableWidth: true,
                        swipeToSlide: true,
                        edgeFriction: 0.80,
                        touchTreshold: 9, <<<<<<<< should work..

very thanks

**Comment by leggomuhgreggo** [comment]
Can you provide a reduced test case in a fiddle or codepen?
