### ISSUE TITLE
Fade to true, disable arrows.

### ISSUE THREAD

**Issue by Dennise89** [kenwheeler/slick#2979]
> short description of the bug / issue, provide more detail below.
I've got 2 sliders. 1 main slider, and 1 navigation slider. The navigation slider has the property `asNavFor: '.main-slider'`. So it will work as navigation for the main slider. But when I have `fade: true` on the main slider, and set the speed to 2500 or higher, it does not work as I want it to work. Because the animation is taking 2500ms, and you click on the arrow before the 2500ms has ended, it does not slide to that slide. It stays on the slide it was working on.

How can we fix this? See JSFiddle as example.
====================================================================

Fiddle: [https://jsfiddle.net/n8cp5n5L/](https://jsfiddle.net/n8cp5n5L/)

====================================================================

#### Steps to reproduce the problem

1. set speed to 2500 or higher, and set fade to true.

====================================================================

#### What is the expected behaviour?

Quit animation, and go to next slide.

====================================================================

#### What is observed behaviour?

Finishes the animation, and stays on that slide.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome, FF, IE, Safari, Opera, Edge

- Which jQuery/Slick version are you using?
Jquery Edge, Slick latest version

- Did this work before?
Nope

**Comment by leggomuhgreggo** [comment]
Yeah you hit the nail on the head--right now we don't have the ability to execute multiple slide changes before one completes. Definitely on the radar. Thanks!
