### ISSUE TITLE
Android WebView not supported

### ISSUE THREAD

**Issue by bluntspoon** [kenwheeler/slick#2986]
Trying to host a simple SlickJS webapp in an Android WebView native wrapper app.

**Issue:**
- Slick Tiles are not swiping left to right

**More Details**
- Which browsers/versions does it happen on? InApp
- Which jQuery/Slick version are you using? latest off your site 1.6

**Comment by yvonne6344** [comment]
same issues...

**Comment by bluntspoon** [comment]
Closing as I no longer use slick/
