### ISSUE TITLE
Mobile iframe crashes website when slick is loaded within

### ISSUE THREAD

**Issue by Cranavvo** [kenwheeler/slick#2991]
We've been experiencing a problem during development where when we load up an iframe which contains a slick slider and then we test it on a mobile, the website then crashes.

This happens when you navigate to the the page with the slick slider in the iframe.

We have intricately removed all plugins and styling which might've affected this but it is only when Slick.js is loaded it is then causing the crashes.

Our init:

```

    $('.centerSlick').slick({
      infinite: true,
      centerPadding: '50px',
      centerMode: true,
      slidesToShow: 3,
      autoplay: true,
      autoplaySpeed: 6000,
      responsive: [
        {
          breakpoint: 992,
          settings: {
            arrows: false,
            centerMode: false,
                    infinite: false,
            centerPadding: '40px',
            slidesToShow: 2,
                    dots: true
          }
        },


            {
          breakpoint: 550,
          settings: {
            arrows: false,
            centerMode: true,
                    infinite: false,
            centerPadding: '22px',
            slidesToShow: 1,
                    infinite: false,
                    dots: true
          }
        }
      ]
    });


```

**Comment by leggomuhgreggo** [comment]
Hmm, I don't know why that'd be happening. Imagine it's something to do with your implementation since slick is loaded into iframes all the time. Can you recreate it in a codepen or fiddle?

**Comment by cowai** [comment]
I have the same problem I think. If I remove the responsive options from slick, everything is okay. So it is definitely slick.

**Comment by fbring** [comment]
Maybe this is the same bug mentioned in #2834. 

I created a isolated demo of that bug over there.

**Comment by cesarmonzale** [comment]
Try this in settings:

{ speed: 0 }

Could this be the way it works?
