### ISSUE TITLE
Div order changes with resize

### ISSUE THREAD

**Issue by elemis** [kenwheeler/slick#2993]
When I resize the browser, or view the page from mobile, the navigation div and the slick div change places, which causes the dots and arrows to appear on top of the slick items. (Doesn't happen without the responsive settings.)
Here's the jsfiddle: http://jsfiddle.net/tuyxate7/
What is wrong with this setup? Or is this a bug?

**Comment by elemis** [comment]
Anyone?

**Comment by leggomuhgreggo** [comment]
If I understand the issue correctly, I'd say it's because the dot grouping and current slide recalcs based on the number of slides to show.
