### ISSUE TITLE
Sync Carousels: aria-describedby has no matching id

### ISSUE THREAD

**Issue by jackblackCH** [kenwheeler/slick#2994]
> short description of the bug / issue, provide more detail below.

If you sync two carousels, the `aria-describedby` attribute of the slides of the 'main' carousel without the dots will never find a corresponding 'id'.

====================================================================

#### Steps to reproduce the problem
Check the synced carousel here: http://kenwheeler.github.io/slick/

1. Inspect the `aria-describedby` attribute of the first carousel
2. There is nowhere an id that matches with the attributes value because the second sync carousel has its own instance and so generates a different numeration

====================================================================

#### What is the expected behaviour?

- If there is no corresponding id, don't print the aria-describedby attribute.
- Or print out the correct id in the thumbnails that match to the aria-described attributes.

#### More Details

- Which browsers/versions does it happen on?
Chrome
- Which jQuery/Slick version are you using?
1.6

**Comment by jackblackCH** [comment]
I just tested master, it's fixed there.

**Comment by jackblackCH** [comment]
A fiddle with 1.6.0
Inspect the elements, you will see:` aria-describedby="slick-slide00" ...`
http://jsfiddle.net/jackblackCH/coxbbe9s/2/

**Comment by leggomuhgreggo** [comment]
Should be fixed in new release. Thanks!
