### ISSUE TITLE
Slick Vertical not flush

### ISSUE THREAD

**Issue by CHEWX** [kenwheeler/slick#2997]
> short description of the bug / issue, provide more detail below.

Slick Vertical slideshows has gaps between slides.

====================================================================

Code at fault: https://github.com/kenwheeler/slick/blob/master/slick/slick.css#L113

Any particular reason for this?

Thanks,
Tom

**Comment by jamilalisgandarov** [comment]
Can you add fiddle or smthng?

**Comment by CHEWX** [comment]
@jamilalisgandarov Not really sure the point in the fiddle, the code shows exactly what is happening.

A vertical slideshow slides have transparent borders. 

But yes — https://jsfiddle.net/simeydotme/fmo50w7n/

Change settings to: `vertical: true`.

Done.

**Comment by CHEWX** [comment]
@leggomuhgreggo Hi, Has this been fixed, do not see a PR referenced?

**Comment by leggomuhgreggo** [comment]
I think so. Can you recreate in a reduced test case, using jsfiddle or codepen?

**Comment by CHEWX** [comment]
@leggomuhgreggo Erm, see https://github.com/kenwheeler/slick/issues/2997#issuecomment-317022807

**Comment by leggomuhgreggo** [comment]
That's the default demo.

**Comment by CHEWX** [comment]
@leggomuhgreggo Correct.

> Change settings to: `vertical: true.`

**Comment by leggomuhgreggo** [comment]
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required

**Comment by CHEWX** [comment]
@leggomuhgreggo https://jsfiddle.net/9p2cm0eo/2/

**Comment by leggomuhgreggo** [comment]
Hmm, I'm not seeing any gaps.

**Comment by CHEWX** [comment]
@leggomuhgreggo It's there because it's in the code.

I've updated the fiddle to show contrast — https://jsfiddle.net/9p2cm0eo/3/

Just drag the slide and you will see the black line inbetween.

**Comment by leggomuhgreggo** [comment]
Hmm, I see the focus outline. Is that what you mean? If so, Should be able to avoid with the following, but be forewarned it's bad a11y.

```css
.slick-slide:focus {outline: none}
```

**Comment by CHEWX** [comment]
@leggomuhgreggo No.

Basically, the question is, what is `border: 1px solid transparent;` doing to `.slick-slide`?

**Comment by leggomuhgreggo** [comment]
Seems to me it's doing nothing. I guess it could be preventing margin collapse. Since everything is `box-sizing: border-box` it shouldn't be doing anything to the outer dimensions of the slide. If you are seeing gaps, I wonder if it has to do with rounding issues, I've seen that happen if the slider width doesn't mod slideCount to zero.
