### ISSUE TITLE
Fade, white corner

### ISSUE THREAD

**Issue by lorraineS** [kenwheeler/slick#3005]
> During a slide change, the corners become white.

====================================================================

###### `[  https://codepen.io/anon/pen/vJOYGV  ]`

====================================================================

**What is the expected behaviour?**

Remove the white borders during the transition.

This  screenshot is the expected result. There is only one image overlay and no color  during the transition.

![capture d ecran 2017-07-26 a 13 12 24](https://user-images.githubusercontent.com/6030502/28618344-613df1b0-7204-11e7-869f-f4c92f06a82c.png)

====================================================================

#### More Details

- Which browsers/versions does it happen on? **All**
- Which jQuery/Slick version are you using? **Both latest (Slick 1.6.0)**

**Comment by leggomuhgreggo** [comment]
Hmm at first I thought you were talking abou the border, but that doesn't seem to be the issue in your demo. Let me know if I'm mistaken but my guess is you might be talking about the reduced color saturation resulting from the fade. I think that might be coming from the white background color of the HTML. Could try setting the bg color of the slider to black. Hope that helps.
