### ISSUE TITLE
Slick won't load after ajax call

### ISSUE THREAD

**Issue by mahassan** [kenwheeler/slick#3006]
> I am trying to unslick and then use it again, but it doesn't work. Part of my problem is when I make a ajax call, it removes slick from my DOM. So I need to slick() it. I tried using console in chrome and it does load and unload but not under my code.

https://codepen.io/codearts/pen/YxXXyZ

**Comment by leggomuhgreggo** [comment]
Codepen doesn't seem to work. I assume it's about sequence, but Im not sure. You might have luck searching existing issue for ajax related stuff. Good luck!
