### ISSUE TITLE
Text paired with Dot Navigation?

### ISSUE THREAD

**Issue by pierrerocket** [kenwheeler/slick#3007]
Is there a good/easy way to have the navigation dots to have text below each one?  I am supposed to put together a timeline feature, and they want each dot to have a year below it.

**Comment by leggomuhgreggo** [comment]
[customPaging](https://github.com/kenwheeler/slick#settings)

**Comment by pierrerocket** [comment]
@leggomuhgreggo the docs only mention using images for custom paging, if you could point me in the right direction it would be much appreciated.

Even in the link you provided it says:

> Custom paging templates. See source for use example.

What source?  If you download the package there is no demo or any source to inspect.  If you google it you dont get anything but the same codepen example of using pokemon images for the paging.

**Comment by leggomuhgreggo** [comment]
See: https//github.com/kenwheeler/slick/blob/master/slick/slick.js#L54
