### ISSUE TITLE
Reimplement Show dots only when needed

### ISSUE THREAD

**Issue by cbieser** [kenwheeler/slick#3009]
In 1.6.0 Dots where only inserted if needed

```
  Slick.prototype.buildDots = function() {
    var _ = this,
      i,
      dot;

    if (_.options.dots === true && _.slideCount > _.options.slidesToShow) {
      _.$slider.addClass('slick-dotted');
```

Please reimplemet this or make it configurable.

Version 1.7.0

**Comment by leggomuhgreggo** [comment]
Cool, would you like to make a PR?

**Comment by SRTM** [comment]
+1 Please re-implement this.

**Comment by cbieser** [comment]
@see #3080

**Comment by leggomuhgreggo** [comment]
Merged into master. Thanks!

**Comment by yangkennyk** [comment]
dots seem to show when there is only 1 slide again in 1.8

**Comment by juliussveikauskas** [comment]
I found there is that logic in slick.js. But if I use slick.min.js it doesn't work. So if you need this feature you can try to use slick.js instead of slick.min.js.

**Comment by octipus** [comment]
> I found there is that logic in slick.js. But if I use slick.min.js it doesn't work. So if you need this feature you can try to use slick.js instead of slick.min.js.

Thank you! This worked for me. I had to manually minifiy the .js file but that's fine
