### ISSUE TITLE
Adaptive slidesToScroll parameter

### ISSUE THREAD

**Issue by zendu** [kenwheeler/slick#3011]
This is more of a request than a bug/issue.
I am using jquery 3.2.1 and slick 1.6. Size of slide is fixed in our case, but not size of screen. If I set slidesToShow = 1, it shows appropriate number of slides that fit in available screen size. Let's say it shows 3 full and 1 partial slide on small screen and 5 on large screen. When user clicks on previous or next, carousel should scroll number of slides that are completely visible i.e. 3 on small screen and 5 on large. Is there any way to do this?

**Comment by leggomuhgreggo** [comment]
You could set a resize listener that measures the `slide-active`count and executes the `setOptions` method to update `slidesToScoll`

**Comment by hackel** [comment]
This is basic functionality that should be a part of Slick for sure.  There are very few cases where you wouldn't want this to be the default behaviour.
