### ISSUE TITLE
Looking for a way to center dots

### ISSUE THREAD

**Issue by samerkamel** [kenwheeler/slick#3013]
I am looking for a way to slide the dots with the slider, always have the active dot centered in the screen, is there an easy way to do it ? My slider came packaged with a wordpress theme and adding another synced slider for thumbnails didnt work, i am hoping for a quick way to "slide" the dots with the slider, or even after a set number of slides ... 

This is a question not a bug

**Comment by leggomuhgreggo** [comment]
Only way that comes to mind would be to use [this](http://lea.verou.me/2011/01/styling-children-based-on-their-number-with-css3/) methodology. Good luck!

Closing
