### ISSUE TITLE
vertical mode: next/prev controls is not changed to up/down

### ISSUE THREAD

**Issue by Grawl** [kenwheeler/slick#3014]
Vertical mode uses keyboard/drag/swipe controls from horizontal mode

https://codepen.io/Grawl/pen/qXbwQQ

#### Steps to reproduce the problem

1. Set `vertical: true`
2. Try to navigate through slides using swipes/dragging/keyboard

#### What is the expected behaviour?

If I drag a slide using mouse or touchscreen to the top, it should move to top and show new slide on bottom of a slide.

If I drag a slide using mouse or touchscreen to the bottom, it should move to top and show new slide on top of a slide.

If I press Down key, it should move to top and show new slide on bottom of a slide.

If I press Up key, it should move to bottom and show new slide on top of a slide.

#### What is observed behaviour?

When I press Up or Bottom key, nothing happens.

When I press Left key, slide moves up.

When I press Right key, slide moves down.

#### More Details

- **Which browsers/versions does it happen on?** Google Chrome 60
- **Which jQuery/Slick version are you using?** jQuery 3.2.1 & Slick 1.6.0
- **Did this work before?** I Don't know

**Comment by leggomuhgreggo** [comment]
Good catch. I'd say this is a priority. Wanna take a crack at a PR?

**Comment by Grawl** [comment]
@leggomuhgreggo sorry I am not have enough time for it. life, you know.

**Comment by leggomuhgreggo** [comment]
Jafeel. Thanks for submitting the issue.

**Comment by leggomuhgreggo** [comment]
Oh you just need to add `verticalSwiping: true`

**Comment by Grawl** [comment]
Okay, but what about to use up/down arrow keys instead of left/right on vertical mode?

**Comment by Abderezai** [comment]
I'm still seeing exact issue.
    $(document).ready(function(){
      $('.product-single__photos').slick({
		  slidesToShow: 1,
  		  slidesToScroll: 1,
  		  arrows: true,
  		  fade: true,
          swipe: false,
          asNavFor: '.slider-nav'
      });
      
      $('.slider-nav').slick({
          	vertical:true,
            verticalSwiping: true,
        swipe:true,
  			slidesToShow: 3,
  			slidesToScroll: 1,
  			asNavFor: '.product-single__photos',
  			dots: false,
            arrows: false,
  			focusOnSelect: false
	});
    });

**Comment by Grawl** [comment]
@Abderezai oh god why your code indented so random

**Comment by Grawl** [comment]
@leggomuhgreggo @kenwheeler so what about to use up/down arrow keys instead of left/right on vertical mode?

**Comment by elynegrao** [comment]
Yea guys... i need same here. Work around?

**Comment by elynegrao** [comment]
Ok! my work around here for a nested slick.

	$( ".vertical-slick" ).keydown(function( event ) {
	       event.stopImmediatePropagation(); // Stops listen the keydown on a vertical element
	});

	$( ".horizontal-nested-slick" ).keydown(function( event ) {		
		if(event.which == 38 ) { // UP / CIMA
			$("#vertical-slick-father").slick('slickPrev');
                        ...

	  	}		
		if(event.which == 40 ) { // DOWN / BAIXO
			$("#vertical-slick-father").slick('slickNext');
                        ...
	  	}
	});
