### ISSUE TITLE
Slick within slick events

### ISSUE THREAD

**Issue by datomas** [kenwheeler/slick#3017]
When you create a slick within slick, the parents events are fired instead of the selected event,

`<html>
<head>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js">
	</script>
	<script type="text/javascript" src="slick/slick.js"></script>
	<link rel="stylesheet" type="text/css" href="slick/slick.css" />
	<link rel="stylesheet" type="text/css" href="slick/slick-theme.css" />
</head>
<body>
	<div style="width:100%">
		<div class="slider">
			<div style="height:520px;width:100%;background-color:#000000">
				<div id="odd">
					<div style="height:150px;background-color:#ffffff"></div>
					<div style="height:150px;background-color:#ffff22"></div>
					<div style="height:150px;background-color:#ffff33"></div>
					<div style="height:150px;background-color:#ffff44"></div>
					<div style="height:150px;background-color:#ffff55"></div>
				</div>
			</div>
			<div style="height:520px;width:100%;background-color:#111111">
				<div id="even">
					<div style="height:150px;background-color:#ffffff"></div>
					<div style="height:150px;background-color:#ffff22"></div>
					<div style="height:150px;background-color:#ffff33"></div>
					<div style="height:150px;background-color:#ffff44"></div>
					<div style="height:150px;background-color:#ffff55"></div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
	$(document).ready(function(){
		$(".slider").on("beforeChange",function(){
			alert("Louie");
		});
		$("#odd").slick({
		  infinite: true,
		  dots: true,
		});
		$("#even").slick({
		  infinite: true,
		  dots: true,
		});
		$(".slider").slick({
		  infinite: false,
		  dots: true,
		});
	});
	</script>
</body>
</html>`

# What is the expected behaviour?

To not fire the parents events, or just include the id of the slider where the event originated,

**Comment by leggomuhgreggo** [comment]
Legit issue. Definitely worth a fix. I think in the meantime you can get around it by controlling for event [bubbling/capturing](https://javascript.info/bubbling-and-capturing) on your listener. Thanks!
