### ISSUE TITLE
1.7.1 in npm/yarn

### ISSUE THREAD

**Issue by yoyo837** [kenwheeler/slick#3019]
There is no 1.7.1 version in the package manager.
How can i get it.

**Comment by egel** [comment]
@yoyo837 We need to wait till authors publish v1.7.1 into npm's registries.

**Comment by leggomuhgreggo** [comment]
Yeah, regrets about the delay. It's on Ken's radar. In the meantime you can use:
`yarn add https://github.com/kenwheeler/slick.git`
or
` npm install https://github.com/kenwheeler/slick.git`

**Comment by kenwheeler** [comment]
Its pushed, sorry.

**Comment by yoyo837** [comment]
That's great.
