### ISSUE TITLE
How Can I use slick with html by installing with npm?

### ISSUE THREAD

**Issue by DanielTimLee** [kenwheeler/slick#3023]
In the description at Readme, there are two ways to install slick.
One is by Bower, and other is NPM.
Previously I've used bower to manage all the front-end packages, but for now trying to change this one to npm.

In this case, `npm install slick-carousel` just installs all the contents at `node_modules`.
When trying to load `slick` from `HTML`, it seems a bit improper way to import from `node_modules` at project root.

Bower, in-case uses `bower.json` to set the directory where I want to install.
But how can I get this to be done with using only NPM?

**Comment by leggomuhgreggo** [comment]
Usually with NPM you're using a bundler of some sort, but you can pull the files directly from
`/node_modules/slick-carousel/slick/slick.min.js` etc.
