### ISSUE TITLE
Forwarding to the slider

### ISSUE THREAD

**Issue by barbudour** [kenwheeler/slick#3029]
Good afternoon, faced such problem — when loading the page where is slider me from the beginning of the page redirects to the location of the slider (like when you click on the anchor). How can I fix this problem?

http://apriori.barbudour.ru/uslugi/proektirovanie.html

**Comment by leggomuhgreggo** [comment]
Hey @barbudour check out #3020. I'm closing in favor of that one, but I think this is likely going to require a PR. Thanks!
