### ISSUE TITLE
Multiple sliders on a page with different css?

### ISSUE THREAD

**Issue by OneSprague** [kenwheeler/slick#3031]
> short description of the bug / issue, provide more detail below.

Sorry, this is more of a question than a bug. Is it possible to have 2 sliders on a page using 2 different css style sheets?

Say one as a header image and the second as a responsive thumbnail version further down the page?

I just didn't know if you could pass the css name in for each slider or not. 

Thanks.

**Comment by leggomuhgreggo** [comment]
Sure. You can even target each by their own unique class name and have specific styles that apply only to them. 

Note: you can do this with an id too, but it's less performant and can cause selection prioritization issues. Class names are best practice

```css
// CSS
.slider{
  ...shared styles...
}

.slider-1{
  ...styles for slider-1...
}

.slider-2{
  ...styles for slider-2...
}
```
```html
// HTML
<div class="slider slider-1"> ...slides... </div>
<div class="slider slider-2"> ...slides... </div>
```

Best of luck!

**Comment by OneSprague** [comment]
Thanks!
