### ISSUE TITLE
Seems to be old verison via bower

### ISSUE THREAD

**Issue by JamesAnelay** [kenwheeler/slick#304]
When downloading this via bower "bower install slick-carousel" I seem to be getting an old version.

The fonts section is using imag-url instead fo font-url as below

//This is line 22 of slick.scss
@function slick-font-url($url) {
  @if function-exists(font-url) {
    @return imag-url($url);
  }
  @else  {  
    @return url($slick-font-path + $url);  
  }  
}

I am doing something wrong or is it just not updated?

Thanks - James

**Comment by talha-asad** [comment]
Never was updated, bower version still at 1.0.1
