### ISSUE TITLE
LTR support does not work.

### ISSUE THREAD

**Issue by avconsbn** [kenwheeler/slick#3045]
Hi,
Slick 1.7.1.
LTR support does not work.
Please add the opportunity (option) to choose a direction.
Thank you

[This solution does not work.](https://github.com/kenwheeler/slick/issues/1075)
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Make sure you're adding the attributed to the slider el. If it's still an issue, please make a demo illustrating the issue

**Comment by avconsbn** [comment]
slick v1.8.0
LTR support does not work.
Please add the opportunity (option) to choose a direction.
**Please create (show) a working LTR example.**
Thank you
