### ISSUE TITLE
TypeError: Cannot read property 'off' of null

### ISSUE THREAD

**Issue by markup-pro** [kenwheeler/slick#3053]
The slider settings:

slidesToShow: 3,
slidesToScroll: 1,
		dots: false,
		arrows: true,
		infinite: false,
		responsive: [
			{
				breakpoint: 767,
				settings: {
					arrows: false,
					dots: true,
					slidesToShow: 3,
					slidesToScroll: 3
				}
			}, {
				breakpoint: 600,
				settings: {
					arrows: false,
					dots: true,
					slidesToShow: 1,
					slidesToScroll: 1
				}
			}
		]

When resizing a browser window from a smaller resolution to a larger one, it gives an error and the arrows do not appear
TypeError: Cannot read property 'off' of null http://joxi.ru/5mdWv0LIv8jzJr
slick ver 1.7.1

**Comment by larslaade** [comment]
Having the same issue here. Seems to be already fixed in the master branch https://github.com/kenwheeler/slick/commit/a3cefec4398c5fd2026894ee3a39eb7ed0e73d16

so, i am waiting for a new release.

**Comment by kkellydesign** [comment]
I'm getting the same error on page load when there are two instances of slick on a page. The second instance doesn't load at all. The fix mentioned in the comment above fixed it for me too though, so the current master branch is good.

**Comment by DanielRuf** [comment]
I also see the issue.

**Comment by ricricucit** [comment]
Any idea on when the new release with this fix is coming up?

**Comment by DanielRuf** [comment]
Good question. A fork may be a good idea imho.

**Comment by leggomuhgreggo** [comment]
new release is out. thanks!

**Comment by ricricucit** [comment]
@leggomuhgreggo just a quick note...can you please publish on npmjs as well? thanks!

**Comment by leggomuhgreggo** [comment]
Ken's got the keys there, but it should be up soon.

**Comment by ricricucit** [comment]
Sorry to bother you @kenwheeler ...could you please could publish the latest release on npmjs? Thanks.
