### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slickAdd' of undefined

### ISSUE THREAD

**Issue by sookcha** [kenwheeler/slick#3057]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  http://jsfiddle.net/o78gcLuu/1  ]` 

====================================================================

#### Steps to reproduce the problem

tl;dr - See jsFiddle link above

1. Use `slickAdd` command for making carousel
2. Voila!   `Cannot read property 'slickAdd' of undefined`

====================================================================

#### What is the expected behaviour?

Carousel should work

====================================================================

#### What is observed behaviour?

An error. `Uncaught TypeError: Cannot read property 'slickAdd' of undefined`

====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome 60.0.3112.90
- Which jQuery/Slick version are you using? jQuery 3.1.1, Slick 1.6.0
- Did this work before? IDK.

**Comment by rvasoya** [comment]
I'm having same problem in my website.
When user click add i want to remove this slide and load other slide.
But got the same error and slide is added also but the behavior of slider changed.

**Comment by sookcha** [comment]
I have solved this problem by using ‘slickAdd()’ method.
Check this fiddle : slick.js test - JSFiddle
<http://jsfiddle.net/3naceufb/25/>

2017년 8월 31일 (목) 오후 10:56, Alyzer <notifications@github.com>님이 작성:

**Comment by Murphy1976** [comment]
@sookcha the version used in the original issue is 1.8.1 (in the jsfiddle), where you are using 1.3.13 in your 09/04/2017 response. I hardly call that a solution when you are regressing the version.  

I am also having the same issue, where I call the initial slick options, but my problems start after I call the slick init.  

[SEE FIDDLE HERE](https://jsfiddle.net/murphy1976/gjoux4v1/11/)

**Comment by Murphy1976** [comment]
I saw another issue where methods being called IN the init function were causing this Uncaught Error. Although, not a permanent fix, but a fix nonetheless, wrapping the called method in a setTimeout(method, 0) works.

I'm guessing it's just the timing of the init call that's just calling slick methods before everything is ACTUALLY initialized, and to wrap the function in a setTimeout was enough of a delay to resolve the issue.

**Comment by Daaizo** [comment]
SOLUTION : JUST KEEP OLD VERSION OF JQUERY ex. https://code.jquery.com/jquery-2.2.0.min.js
Whole situation :
I had the same problem. The situation is that I created a quite simple project for school and added a slider to it, but I downloaded all the resources from https://kenwheeler.github.io/slick/. Everything was fine. After some time I decided to upload this project to github, but I had to change the local folder with the slick-slider to the npm version, so I copied and pasted the whole code snippet from random site and then it stopped working and I got :
![image](https://user-images.githubusercontent.com/84875747/174457372-fe82a04a-06a1-49cb-96ec-893b535c0072.png)
After hour of randomly checking whats going on I jsut revert commit to previous version and I tried to add npm once again. And It WORKED !! THE ISUSE IS NOT THE CODE ITS JQUERY VERSION. At first I had old one :https://code.jquery.com/jquery-2.2.0.min.js but when I copied code with npm there was newest version 3. something and IT STOPPED WORKING !!!! 
FINAL WORKING code :
![image](https://user-images.githubusercontent.com/84875747/174457484-6e09cb1e-44e0-438f-9382-1b5ab814c9cf.png)
The last file is the initialization of the slider
