### ISSUE TITLE
Change current slide on hover

### ISSUE THREAD

**Issue by brutaltea** [kenwheeler/slick#3058]
When using "Slider Syncing" is it possible to change current slide in ".slider-for" element onHover without clicking on slide inside ".slider-nav" element

**Comment by brutaltea** [comment]
So it's been 17 days since I opened this issue and no answer so far. For now, I resolved this in such way:
$('.slick-slide').mouseover(function(){
         $(this).click();
});
Not the method I was hoping to found but it somehow works.

**Comment by nurullahnet** [comment]
thanks bro

**Comment by ndtmivn123** [comment]
i don't understand, can you demo to me?

**Comment by nurullahnet** [comment]
Which comment?

Can i see comment link again?

Saygılarımla,

İyi çalışmalar.


NURULLAH OKATAN
Genel Müdür
Cep: 0532 216 07 54
Tel: 0212 267 12 12

TÜRK BİLİŞİM
Telsizler M. Galata Deresi C.
Burhan S. Tutar Apt. No: 17/17
34410 Kağıthane / İstanbul


Hair <notifications@github.com>, 31 Tem 2018 Sal, 12:04 tarihinde şunu
yazdı:
