### ISSUE TITLE
1.7.1 (vs. 1.6.0) breaks autoplay demo

### ISSUE THREAD

**Issue by klaus101** [kenwheeler/slick#3065]
> short description of the bug / issue, provide more detail below.

The autoplay part of the demo page  http://kenwheeler.github.io/slick/
does no longer  really work using slick.js from 1.7.1.
Remark: the demo page obviously uses 1.6.0
Problem: when clicking next-arrow,  autoplay stops and will not reactivate

===============================================

###### `[  paste your jsfiddle link here  ]`  

Not really needed here - simiply try the autoplay part of the demo page with version 1.7.1

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

===============================================

#### Steps to reproduce the problem

1. ...  Create a slider using the autoplay script's settings  from the demo page, part "autoplay"
2. ...  Use  slick.js from 1.7.1 instead
Click on the next arrow. Autoplay will stop.
It might be reactivated by clicking onto external parts of the window or by task switching,
but this is not the exprected behaviour.

Remark: the usage of other options, ie. accessibility does not really help. For instance
accessibility leads to other problems, as described in
https://github.com/kenwheeler/slick/issues/3046

===============================================

#### What is the expected behaviour?
When having clicked next-arrow, autoplay should resume after some time

#### What is observed behaviour?
...   Autoplay stops and does not resume

#### More Details

- Which browsers/versions does it happen on?  firefox 54.0.1, windows
- Which jQuery/Slick version are you using?  Not relevant; jquery-1.7.1.min.js or upwards
- Did this work before? yes, with slick 1.6.0

**Comment by leggomuhgreggo** [comment]
Should be fixed now

**Comment by klaus101** [comment]
Unfortunately it is not the whole truth  :-(
Yes, obviously the autoplay part of the demo seems to work again with slick.js 1.8.0
No, i absolutely cannot get it to work not even with a totally shrinked test case ...
I could send a very minimalistic test case via zip file  Alternatively the html code below.
After i press arrow-next, autoplay stops (1.7.1 and 1.8.0).
Whereas it runs fine with slick.js 1.6.0!

```
<!DOCTYPE html>
<html lang="de-DE" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
		<title>Testme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <style>
       body { font-size:1.3em; width: 100%; color: #fff; background-color: #FFFFFF;  }
  </style>
</head>

<body>
    <section style="width: 100%; height: 300px; padding: 8% 5%;	text-align: center;">
        <div> </div>
    </section>
    <section style="margin-top:-300px; padding-left: 15%; background:gray">
      	<div>
          <div style="min-height:270px; padding-top: 2px;; padding-bottom:4px;">
                <div class="slider slider1" style="width:85%; padding:10%;">
                    <div>*Image 1*</div>
                    <div>*Image 2*</div>
                    <div>*Image 3*</div>
                    <div>*Image 4*</div>
                    <div>*Image 5*</div>
               </div>
           </div>
        </div>
    </section>
     <script src="https://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
     <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
     <link rel="stylesheet" href="slick_1.8.0/slick.css" type="text/css">
     <link rel="stylesheet" href="slick_1.8.0/slick-theme.css" type="text/css">
     <script src="slick_1.8.0/slick.js" type="text/javascript"></script>
      <script>
 		$(document).ready(function() {
  	          $(".slider1").slick({
                    dots: true,
                    infinite: true,
                    speed: 500,
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    autoplay: true,
                    autoplaySpeed: 2000
       		});
	    });
     	</script>
</body>
</html>

```

**Comment by klaus101** [comment]
Unfortunately it is not the whole truth  :-(
Yes, obviously the autoplay part of the demo seems to work again with slick.js 1.8.0
No, i absolutely cannot get it to work not even with a totally shrinked test case ...
I could send a very minimalistic test case via zip file  Alternatively the html code below.
After i press arrow-next, autoplay stops (1.7.1 and 1.8.0).
Whereas it runs fine with slick.js 1.6.0!

```
<!DOCTYPE html>
<html lang="de-DE" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
		<title>Testme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <style>
       body { font-size:1.3em; width: 100%; color: #fff; background-color: #FFFFFF;  }
  </style>
</head>

<body>
    <section style="width: 100%; height: 300px; padding: 8% 5%;	text-align: center;">
        <div> </div>
    </section>
    <section style="margin-top:-300px; padding-left: 15%; background:gray">
      	<div>
          <div style="min-height:270px; padding-top: 2px;; padding-bottom:4px;">
                <div class="slider slider1" style="width:85%; padding:10%;">
                    <div>*Image 1*</div>
                    <div>*Image 2*</div>
                    <div>*Image 3*</div>
                    <div>*Image 4*</div>
                    <div>*Image 5*</div>
               </div>
           </div>
        </div>
    </section>
     <script src="https://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript"></script>
     <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
     <link rel="stylesheet" href="slick_1.8.0/slick.css" type="text/css">
     <link rel="stylesheet" href="slick_1.8.0/slick-theme.css" type="text/css">
     <script src="slick_1.8.0/slick.js" type="text/javascript"></script>
      <script>
 		$(document).ready(function() {
  	          $(".slider1").slick({
                    dots: true,
                    infinite: true,
                    speed: 500,
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    autoplay: true,
                    autoplaySpeed: 2000
       		});
	    });
     	</script>
 #</body>
</html>

```

**Comment by klaus101** [comment]
@leggomuhgreggo , please, might you take a short look on it?

**Comment by leggomuhgreggo** [comment]
Hmm autoplay is working on the [test fiddle](https://jsfiddle.net/simeydotme/fmo50w7n/)

Are you copying the code from `http://kenwheeler.github.io/slick/` to your environment? The script/style dependencies are relative links -- so they wont work unless the files exist in your environment's filesystem at the same relative location.

```html
<link rel="stylesheet" href="slick_1.8.0/slick.css" type="text/css">
<link rel="stylesheet" href="slick_1.8.0/slick-theme.css" type="text/css">
<script src="slick_1.8.0/slick.js" type="text/javascript"></script>
```
vs 
```html
<link rel="stylesheet" href="http://some-other-location.com/slick_1.8.0/slick.css" type="text/css">
<link rel="stylesheet" href="http://some-other-location.com/slick_1.8.0/slick-theme.css"** type="text/css">
<script src="http://some-other-location.com/slick_1.8.0/slick.js" type="text/javascript"></script>
```

Alternatively, you could use the cdn per [the example](https://github.com/kenwheeler/slick#cdn) in the readme

**Comment by klaus101** [comment]
Many thanks for your attention!
Im my small testcase, all slick related settings are picked up
from the autoplay part of the demo page as of:		[](http://kenwheeler.github.io/slick/)
Here too, ehe script/style dependencies are relative links:
		<script type="text/javascript" src="./slick/slick.js"></script>
		<script type="text/javascript" src="js/scripts.js"></script>
and all is fine. Bormally i have no problem with these kind of links too.
Using it with slick_1.6.0.js works too. The entities are local in the environment and the html page do find them.
I could not attach that little test case here, so i will try it by mail reply (hopefully the mail gateway will accespt the javascript contents).

I tested on win 7 x64 firefox 55.0.2 (but chrome and IE 11 as well).
What do you think?
Maybe i did a mistake, but after having spent hours i cannot find the clue.
It's mysterious to me that the autoplay part of the demo obviously works and this small test case not.

**Comment by klaus101** [comment]
Hello Greg,

many thanks!
I updated #3065 <https://github.com/kenwheeler/slick/issues/3065>.   and 
try to attach the test case here.

Best Regards!
Klaus


Am 13.09.2017 00:38, schrieb Greg Westneat:

**Comment by klaus101** [comment]
@leggomuhgreggo 

Finally i got the clue.    ;:-)    There are two different versions of the slick.sj 1.8. !!!   :-/

1)  Instead of my local copy of the 1.8.0. i tried:
  `   <script src="http://kenwheeler.github.io/slick/slick/slick.js" type="text/javascript"></script>`
       And that worked, like in the demo!

2) I did have receive my 1.8.0 slick.js via zip download from github as slick-master.zip  at sept. 12th.
   Inside the slick.sh is labeled as "1.8.0"!

3) I now compared my local copy from the slick-master with the version on kenwheeler.. as above,
   which is labeled as 1.8.0 too, and saw that there are _noticeable_ dfferences!!

4) I tried the version from kenwheeler .... (as above)  by local copy and it worked too.

Why two different versions of the 1.8.0 do exist ???? 
Cannot rely on the master-zip as containing the recent version?

**Comment by klaus101** [comment]
@leggomuhgreggo 
Again. on github https://github.com/kenwheeler/slick there is an update of slick.js as of sept 14 which HAS this problem.
The problem (i did send a testcase about) is: when pressing a arrow button, autoplay stops and does not resume.
Whereas the kenwheeler version from the demo page (http://kenwheeler.github.io/slick/)  does NOT have this problem.
- Which one of the versions both labeled as 1.8.0 is the official one?
- How to assure that the version on github will work fine like as the version used in the demo page?

**Comment by leggomuhgreggo** [comment]
Can you recreate the issue you're having in a reduced test case? 
https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required

**Comment by klaus101** [comment]
In my email reply i attach a reduced test case that shows the different 
behaviour of the two different 1.8.0 versions:

- slick.js "1.8.0" as  picked up from the demo page 
http://kenwheeler.github.io/slick  :
        =  No problem: press arrow button - autoplay will resume 
afterwards :-)
     Remark: in the demo page, inspected the source code for to access 
the slick.js

- slick.js "1.8.0" as downloaded from github 
https://github.com/kenwheeler/slick :
       =  Problem: press arrow button - autoplay will _NOT_resume 
afterwards  :-(

Attached test case:  autoplay_problem_with_1.8.0.zip

If you compare the two 1.8.0 versions of slick.js (i'm using local 
copies of them) you will find significant differences.

My test case is using the same slick parameters as used in the autoplay 
part of the demo.


Am 17.09.2017 15:43, schrieb Greg Westneat:

**Comment by klaus101** [comment]
Additionally i uploaded the reduced test case here:  
http://www.filedropper.com/autoplayproblemwith180

**Comment by klaus101** [comment]
@leggomuhgreggo 

I found a difference in the two scripts that may cause the different behaviour. line 1019:

In the github version:
`on('focus.slick blur.slick', '*', function(event) {`

In the version from the demo page:```
```
on('focus.slick blur.slick',
                '*:not(.slick-arrow)', function(event) {
```
===> if we apply the latter lines from the demo page to the github version,
then autoplay will be reactivated again as expected!  <===

**Comment by klaus101** [comment]
@leggomuhgreggo 
I adapted the test case acccordingliy for to show the changed behaviour.
You can find it here:
http://www.filedropper.com/autoplayproblemwith180fixed

**Comment by klaus101** [comment]
As this issue is no longer concerning the demo page and the 1.7.1,
i feel it is better to open a new item concerning the 1.8.0.
