### ISSUE TITLE
Slick Slider not work in Chrome

### ISSUE THREAD

**Issue by dmitri-jurovski** [kenwheeler/slick#3071]
Dear colleagues,
I have very strange problem. I use wordpress and bootstrap v3 with slick slider. I create slider two time in one page using custom post type. In Safari and FireFox all work properly. But in Chrome it's not work. Not any reaction. Below you fine screenshot, who this look in inspector. Thank you for reading.

<img width="1280" alt="screen shot 2017-08-22 at 21 46 00" src="https://user-images.githubusercontent.com/13300890/29581957-a7b38fbc-8783-11e7-90a2-ee1da76f8b63.png">
<img width="1280" alt="screen shot 2017-08-22 at 21 46 24" src="https://user-images.githubusercontent.com/13300890/29581956-a7b3b82a-8783-11e7-977b-1f6ad38f1080.png">

**Comment by stljeff1** [comment]
are the IDs of both sliders the same? they should be unique.

**Comment by dmitri-jurovski** [comment]
# id diferent. One #Slider and second #mieterSlider

**Comment by dmitri-jurovski** [comment]
Problem Solve

**Comment by jhoansebastianlara** [comment]
@dmitri-jurovski can you tell us what did you do, I have exactly the same problem.

**Comment by Edwardtonnn** [comment]
@jhoansebastianlara  and @dmitri-jurovski  hi. just wondering if anyone solved this. i am having the same issue. thank you.

**Comment by Edwardtonnn** [comment]
# **Got it.** 

```css
.slick-slider .slick-track,
.slick-slider .slick-list
{
 transform: none!important;
}
```
