### ISSUE TITLE
Where is the 1.7.0 release?

### ISSUE THREAD

**Issue by DanielRuf** [kenwheeler/slick#3072]
The release 1.7.0 is not there anymore.

Also there were changes in 1.7.1 which changed the behavior.
@leggomuhgreggo 

Especially https://github.com/kenwheeler/slick/commit/ef8c742b8f6c7a6ceb7ca98865f5b53a25cca7ad

**Comment by leggomuhgreggo** [comment]
Ahh good points -- carelessness on my part.

**Comment by leggomuhgreggo** [comment]
@DanielRuf you running into any issues with the centering styles? I was hesitant to add it. 

Apologies if that threw a wrench into anything.

**Comment by DanielRuf** [comment]
Yes, this changed the default layouts and the needed version was gone.

**Comment by leggomuhgreggo** [comment]
Ahh sorry my dude. Would you be in favor of removing the style?

**Comment by DanielRuf** [comment]
I overwrote / reset it with an own stylesheet so we get the previous behavior. Such breaking changes should be in a 1.x.0 release.

It seems the wrong commits were tagged.

**Comment by leggomuhgreggo** [comment]
Fair point!

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Also 1.9.0 is missing as tagged release.
