### ISSUE TITLE
asnavfor causes an unwanted scroll

### ISSUE THREAD

**Issue by devozanges** [kenwheeler/slick#3084]
The problem I encounter is that every time the slide is done, the scroll page automatically returns to the top slides while I'm browsing the bottom of the page. when I remove asnavfor, nothing scrolls wrongly
====================================================================

use this jsfiddle to reproduce the bug. 
https://jsfiddle.net/ArnOz/g6jjfoww/

====================================================================
### Steps to reproduce the problem

1. ...  just run and scroll down for read the content of the page

====================================================================

#### What is the expected behaviour?

...  the two sliders works with asnavfor

====================================================================

#### What is observed behaviour?

...  the page is scrolling me to the top every time the slider scrolls

====================================================================

#### More Details

- Which browsers/versions does it happen on? 
observed on chrome and firefox, not tested others
- Which jQuery/Slick version are you using? 
current slick version
- Did this work before?
no

**Comment by devozanges** [comment]
Add the options ```accessibility: false``` on the second slider, target of the asnavfor seems to solve the problem temporary...

**Comment by leggomuhgreggo** [comment]
Should be fixed on latest release
