### ISSUE TITLE
Single-Item slide not working with Slick.

### ISSUE THREAD

**Issue by typoworx-de** [kenwheeler/slick#3088]
Situation:
If slick is only provided with one single-item slide, there seems to be a serous problem as the CSS on top moves it out of viewport (f.e. "transform: translate3d(-1690px, 0px, 0px);").

Expected:
The single-slide should be in viewport (visible) until another slide may be added dynamically. It is not correct that no slide is shown. Navigation also has no function.

Reproduce:
>         var $slickContainer = $(this),
>             options = {
>                 infinite: true,
>                 dots: false,
>                 slidesToShow: 1,
>                 speed: 300,
>                 initialSlide: 0,
>                 autoplay: true,
>                 arrows : false,
>                 variableWidth: false,
>                 mobileFirst: true,
>                 touchMove: true,
>                 swipe: true,
>                 swipeToSlide: false,
>                 autoplaySpeed: 7000
>             }
>         ;

Simply use HTML-Markup of Slick, but only with ONE slide-item!

**Comment by divyarajmasani** [comment]
@typoworx-de this happened when I used `1.6.0`. `1.7.1` works fine.

**Comment by mark-chief** [comment]
I am using v1.8.0 and have the same issue.

**Comment by iftkharhussain** [comment]
I am using v1.8.1 and have the same issue. Please fix it

**Comment by erralb** [comment]
Has anyone found a solution ?

**Comment by mrtk0y** [comment]
is this still open ?

**Comment by adeeb1201** [comment]
Did anyone find a solution for this?

**Comment by zakdma** [comment]
Hey @leggomuhgreggo, why did you close it? Its still here even in the latest version. One slide makes the carousel totally broken.
https://i.imgur.com/7nXWvZp.png

**Comment by dimadroog** [comment]
> Did anyone find a solution for this?

Just some crutch:
```js
/*js*/
const countOfSlides = mySlider.slick('getSlick').slideCount;
 if (countOfSlides == 1){
    mySlider.addClass('slick-onlyone');
 }
```
```css
/*css*/
.my-slider.slick-onlyone .slick-track{
	transform: none !important;
}
```
hope this can help
