### ISSUE TITLE
Form inside carousel does not work properly (c# mvc)

### ISSUE THREAD

**Issue by uniquelau** [kenwheeler/slick#3089]
> When `slidesToShow` is greater than 1, the input field values are not correctly posted from the other slides.

====================================================================

I am seeing this issue with a C# MVC4 form post. 

Although I do not expect help with this issue, I am posting, as it could save someone else hours of frustration. If I find a solution I will post here.

**Comment by leggomuhgreggo** [comment]
Are you wrapping all the elements in a single form?
