### ISSUE TITLE
Consider rewriting to es6

### ISSUE THREAD

**Issue by bonzzy** [kenwheeler/slick#3092]
Have you considered rewriting the plugin from scratch (maybe using es6)? At the current state it is difficult to contribute with a pull request. I would to be happy to help if there is enough interest in this.

I am planning to open a repository containing es6 rewrites of popular plugins and would like to start with slick slider with your permission and help.

**Comment by anthonygrignoux** [comment]
They've started writing a jquery-free version of it, I believe:  
https://github.com/kenwheeler/slick/issues/494  
https://github.com/kenwheeler/slick/tree/2.0

**Comment by krukru** [comment]
By the looks of it, there isn't much activity in the branch. We will be doing our own fork and rewriting it from scratch. 
We will try to do as much individually possible, but any help from the community would be great.
@bonzzy will paste the link to the repo once he finds time to set it up (sometime next week).

**Comment by leggomuhgreggo** [comment]
PRs to the 2.0 branch welcome!
