### ISSUE TITLE
Jumping at vertical mode

### ISSUE THREAD

**Issue by Dzeganovsky** [kenwheeler/slick#3096]
Conditions: carousel is used at vertical mode and top of carousel block is out of screen.
Bug: when you push next button - page jump to top after slide animation.
Reason:
`
if (!_.options.autoplay) {
    var $currentSlide = $(_.$slides.get(_.currentSlide));
    $currentSlide.attr('tabindex', 0).focus();
}
`
at `Slick.prototype.postSlide`

**Comment by kateika** [comment]
what is version of carousel?

**Comment by Dzeganovsky** [comment]
1.7.1.
Installed from bower 05.09.2017

**Comment by Dzeganovsky** [comment]
One more thing - autoplay: false

**Comment by JiveDig** [comment]
I'm seeing this as well. Didn't happen on 1.6, now is happening since updating to 1.7.1.

![screen recording 2017-09-08 at 12 55 pm](https://user-images.githubusercontent.com/540990/30222407-10846d7c-9495-11e7-8f4a-ab45adc0c411.gif)

**Comment by JiveDig** [comment]
Adding `scrollTo` fixes it for me.

from this (1.7.1);
```
var $currentSlide = $(_.$slides.get(_.currentSlide));
$currentSlide.attr('tabindex', 0).focus();
```

to this:
```
var $currentSlide = $(_.$slides.get(_.currentSlide));
var x = window.scrollX, y = window.scrollY;
$currentSlide.attr('tabindex', 0).focus();
window.scrollTo(x, y);
```

**Comment by leggomuhgreggo** [comment]
Should be fixed in new release

**Comment by JiveDig** [comment]
@leggomuhgreggo Thanks for the quick fix here. Since "focusOnChange" setting was "reluctantly" added, I'm wondering why not leave the focus in, and use the window.scrollTo method I posted above? Granted, JS is not my strength, so there very well may be a big downside, but that potentially could solve both issues at once.

**Comment by leggomuhgreggo** [comment]
Considered a scroll override but it would break the point of the focus scroll jump, which is accessibility -- granted we're also doing by disabling by default, but the scroll override option adds entropy and get's complicated with multiple sliders on page.

**Comment by JiveDig** [comment]
That makes sense. It's sad though, that we now have to compromise either accessibility or a jumpy slider.

**Comment by leggomuhgreggo** [comment]
Carousel a11y isn't so well defined, particularly as regards this issue, that I'd worry too much about it. That said you can always turn `focusOnChange` to true and factor for it however you'd like!
