### ISSUE TITLE
Add multiple elements with slickAdd

### ISSUE THREAD

**Issue by DiogoAfonso** [kenwheeler/slick#3098]
Hello all,

I'm using this amazing framework in a project and I'm trying to revamp the wheel by implementing my own lazy loading here.
Let's say I have a slick carousel with 3 rows and 5 columns and each time I swipe I will add more 3*5 elements to the slick, like this:

- $mosaicGallery.slick('slickAdd', stringHtml);
. $mosaicGallery is a jQuery reference for the element which was apply the slick on the first place;
. stringHtml is string html with the elements to be add to the new page.

What happens in my case is only one element is rendered like this

| x | x | x | x | x |
| x | x | x | x | x |
| x | x | x | x | x |

-> swipe left

| x |   |   |   |   |
|    |   |   |   |   |
|    |   |   |   |   |

Which leads me to think that slickAdd can only slick one new element at once no matter how much are supposed to be slick, right?
Is there any workaround for this?

Thank you for your help here :)

**Comment by leggomuhgreggo** [comment]
Demo? I think what you're saying makes sense, though. Rows are buggy and not what I'd call fully supported at this time. Open to PRs.

Closing pending demo
