### ISSUE TITLE
Swipe scrolling

### ISSUE THREAD

**Issue by fritzelly** [kenwheeler/slick#3099]
I've looked thru the code but cant see it
When swiping I cant see a way to just let it scroll i.e. if I do a quick swipe then it scrolls several items, like you would on a webpage swiping up and the page scrolls up quick

My current code
slidesToShow: 4,
  slidesToScroll: 1,infinite: true,speed: 300
	});

If I remove slidesToScroll it still scrolls just one at a time

(Admittedly this is on a desktop, testing area, so I may be seeing a different behaviour)

**Comment by leggomuhgreggo** [comment]
It's a feature on the roadmap, but it's not implemented yet. Thanks!
