### ISSUE TITLE
Slider isn't shown correctly

### ISSUE THREAD

**Issue by TimoKleinhout** [kenwheeler/slick#3102]
Issues with slick, sometimes the slider is shown correctly

====================================================================

#### What is the expected behaviour?

To show the slider full width as shown in attachment.

====================================================================

#### What is observed behaviour?

The slider is shown half, or not at all.

====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome, Safari
- Which jQuery/Slick version are you using? jQuery: 1.12.4, Slick: 1.7.1 (tried 1.6.0 as well)
- Did this work before? Not on this project

So it doesn't occur all the time, sometimes it's shown correctly other times not. I believe when the error occurs the width of the slider is 0. I tried to setPosition after window is loaded, but didn't work.

<img width="1438" alt="schermafbeelding 2017-09-10 om 11 39 58" src="https://user-images.githubusercontent.com/20295014/30247880-5c9b84fa-961d-11e7-9fd1-17d0a774f48b.png">
<img width="369" alt="schermafbeelding 2017-09-10 om 11 38 53" src="https://user-images.githubusercontent.com/20295014/30247881-5c9b7dd4-961d-11e7-8872-6cab591c586e.png">
<img width="368" alt="schermafbeelding 2017-09-10 om 11 38 21" src="https://user-images.githubusercontent.com/20295014/30247882-5c9b8252-961d-11e7-9ec2-f00afb30ef58.png">

**Comment by leggomuhgreggo** [comment]
Closing: support req
