### ISSUE TITLE
Slick-carousel and webpack - $(...).slick is not a function. The solution from other issues doesn't work.

### ISSUE THREAD

**Issue by testgit-1** [kenwheeler/slick#3115]
Hello.
I'm trying to use slick-carousel and webpack.

I use the solutions from [#2290](https://github.com/kenwheeler/slick/issues/2290#issuecomment-251023922) with ProvidePlupin and esplose-loader.  jQuery and Webpack work without error. 
But still got the error "$(...).slick is not a function".

Maybe the reason is in the package version in npm? 
In this repo last version is 1.8.0. In npmjs.com - 1.7.1 ([link](https://www.npmjs.com/package/slick-carousel))

Or I missed a working solution? What kind?

**Script code**
```
import $ from 'jquery';
import 'slick-carousel';
$(".slider-wrapper").slick();
```
**Dependencies**
```
  "devDependencies": {
    ...
    "webpack": "^2.7.0",
    "webpack-stream": "^4.0.0",
  },
  "dependencies": {
    ...
    "jquery": "2.2.4",
    "slick-carousel": "1.7.1",
  }
```
**Webpack config**
```
const path        = require('path'); //npm module for absolute path like  path.resolve(__dirname, './build')
const webpack = require('webpack');
const config     = require('./gulp/config.js');


module.exports = {
    entry: './'+ config.src.jsEntryPoint,   
    output: {
        filename: 'bundle.js', 
        path: path.resolve(__dirname, './' + config.dest.js),   
    },
    watch: true, //live-reloading
    devtool: 'source-map', 


    plugins: [
        // jQuery globally
        new webpack.ProvidePlugin({ 
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
    ],



    module: {
        loaders: [
			{
			  test: require.resolve("jquery"),
			  use: [
				{
				  loader: "expose-loader",
				  options: "$"
				}
			  ]
			}        
		],
    }

};
```

**Comment by testgit-1** [comment]
Problem solved. The conflict was in dependencies.

**Comment by lifeinchords** [comment]
@testgit-1 can you please explain a bit more about what you did to fix this?

**Comment by TheJediTinkiwinki** [comment]
@testgit-1 ping, pls explain more

**Comment by Gesparo** [comment]
This solution helped me to solve the problem:
```javascript
import $ from 'jquery';
window.$ = window.jQuery = $;
import 'slick-carousel'
```

**Comment by warslett** [comment]
there is a special place in hell for people who close github issues like this...

**Comment by Fomicha** [comment]
@Gesparo I loveu :DDD

**Comment by naczu** [comment]
why is this closed ?

**Comment by selim13** [comment]
> why is this closed ? still not working with laravel-mix
> Edit: owl-carousel worked well

For laravel-mix this worked well:
```javascript
mix.webpackConfig({
	externals: {
		jquery: 'jQuery',
	},
});

mix.autoload({
	jquery: ['$', 'window.jQuery'],
});
```

Here I'm using jQuery that comes externally. If you have it in your bundle you can omit `mix.webpackConfig` block.

**Comment by LABCAT** [comment]
This may or may not be related but I had same error message.

In my dependencies of my package.json I had this:
`
    "slick": "^1.12.2",
    "slick-carousel": "^1.6.0",`

Deleting the first slick resolved the issue for me

**Comment by BenceSzalai** [comment]
Another solution can be to wrap anything using `$` as a shorthand for `jQuery` as here:
```javascript
(function( $ ) {
    // Use $ as usual here, e.g.:
    $(".slider-wrapper").slick();
})( jQuery );
```

The benefit is we don't pollute `window.$` or global `$`, and this can be usefull when we need to operate in an environment where `$` may have a different meaning outside using Slick.

**Comment by SamX23** [comment]
I will try this solution on webpack 5
