### ISSUE TITLE
Slides 

### ISSUE THREAD

**Issue by stljeff1** [kenwheeler/slick#3134]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by jonasva** [comment]
I also have this problem of wrapper <div> elements generated around each slide on version 1.8 (works fine on 1.7 though).

**Comment by stljeff1** [comment]
huh, how did this happen? Very interesting....
