### ISSUE TITLE
CDN services do not have the 1.8 version

### ISSUE THREAD

**Issue by Ellf** [kenwheeler/slick#3138]
Documentation refers to using CDN services as detailed below:

CSS
```<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.8.0/slick.css"/>```

JS
```<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.8.0/slick.min.js"></script>```

However, the 1.8 versions are not available on jsdeliver.net nor cdnjs.com/libraries/slick-carousel.

Thanks.

**Comment by MartinKolarik** [comment]
There are working 1.8.0 links in the readme. jsDelivr website (and cdnjs too, I believe) doesn't list 1.8.0 because it isn't on npm. Related: https://github.com/kenwheeler/slick/pull/3093#issuecomment-328850045

**Comment by anik786** [comment]
+1. Please fix up the docs!

**Comment by PWaddict** [comment]
On https://cdnjs.com/libraries/slick-carousel the latest version is 1.7.1. Please upload the 1.8.0 version.

**Comment by kenwheeler** [comment]
Published, should propagate soon

**Comment by EvilJordan** [comment]
"Couldn't find the requested release version 1.8.0." Appearing as of 21 days after this issue was closed.

**Comment by MartinKolarik** [comment]
@EvilJordan what file/url were you trying to access?

**Comment by kukac7** [comment]
try: https://unpkg.com/slick-carousel

**Comment by MartinKolarik** [comment]
@kukac7 https://cdn.jsdelivr.net/npm/slick-carousel works too...

**Comment by EvilJordan** [comment]
Direct from the website "Get it now" section (http://kenwheeler.github.io/slick/#go-get-it), neither of these work:
cdn.jsdelivr.net/jquery.slick/1.8.0/slick.css
cdn.jsdelivr.net/jquery.slick/1.8.0/slick.min.js

**Comment by MartinKolarik** [comment]
@EvilJordan thanks, I'll send a PR to fix the website. The correct links are:
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css

**Comment by MartinKolarik** [comment]
>I'll send a PR to fix the website

Or not, as I can't find the correct repo. @kenwheeler ?

**Comment by ADTC** [comment]
What's happening? I am shocked that the CDN version doesn't work. I guess I have no choice but to download and install if CDN reliability cannot be guaranteed.

**Comment by MartinKolarik** [comment]
@ADTC the CDN works, this is just an issue with documentation. See my previous comment for correct links.

**Comment by ADTC** [comment]
Thank you! Yes, I used the npm links. Hopefully that doesn't change. The documentation is also not clear about the two css files. Is the main one required but the theme one optional?

**Comment by MartinKolarik** [comment]
I think you should use the theme, unless you want to provide custom styling.
