### ISSUE TITLE
Div wraps in the new version (v1.8.1)

### ISSUE THREAD

**Issue by rteamx** [kenwheeler/slick#3149]
In new version (1.8.1)

In this version slider building new html structure for slides: [jsfiddle 1.8.1](http://jsfiddle.net/simeydotme/fmo50w7n/)

Part of the code 1.8.1:
``` html
<div class="slick-track" style="opacity: 1; width: 5616px; transform: translate3d(-432px, 0px, 0px);">
  <div class="slick-slide slick-cloned" data-slick-index="-1" aria-hidden="true" tabindex="-1" style="width: 432px;">
    <div>
      <div style="width: 100%; display: inline-block;">slide6</div>
    </div>
  </div>
  <div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" role="tabpanel" id="slick-slide00"
    style="width: 432px;" aria-describedby="slick-slide-control00">
    <div>
      <div style="width: 100%; display: inline-block;">slide1</div>
    </div>
  </div>
</div>
```

In previos [version (1.8.0)](http://jsfiddle.net/rkbruct1/1/) is not.
Part of the code 1.8.0:
``` html
<div class="slick-track" style="opacity: 1; width: 5616px; transform: translate3d(-432px, 0px, 0px);">
  <div class="slick-slide slick-cloned" data-slick-index="-1" aria-hidden="true" tabindex="-1" style="width: 432px;">slide6</div>
  <div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" tabindex="0" role="tabpanel"
    id="slick-slide00" aria-describedby="slick-slide-control00" style="width: 432px;">slide1</div>
</div>
```

**Comment by js2017** [comment]
I have the same problem in 1.8.0. 1.7.1 is fine.

**Comment by kavasey** [comment]
@js2017 Check this issue, it has a fix [https://github.com/kenwheeler/slick/issues/3110](url)

**Comment by justMoritz** [comment]
Possible related, but I noticed that the `slick-slide` does not inherit the class from the original element on which `.slick()` was called anymore. Again, putting `rows: 0` in the method did fix this issue as well.

**Comment by DanielRuf** [comment]
Hm, here too. Do they even test before releases and prevent breaking changes by applying the previous behaviour by default?

**Comment by hartey11** [comment]
Any idea when this is going to get fixed?

**Comment by rteamx** [comment]
@hartey11, param `rows: 0` solved this.

**Comment by rosivanov** [comment]
Seems slick support is stopped

**Comment by DanielRuf** [comment]
> Seems slick support is stopped

Take a look at https://github.com/nolimits4web/Swiper

**Comment by rosivanov** [comment]
@DanielRuf thanks

**Comment by rteamx** [comment]
> Still a breaking change. `rows: 0` should be set by default.

I agree.

**Comment by rakshitpatel-it** [comment]
rows: 0, works for me, thanks
The default value is rows: 1 in slick-1.8.1 version
