### ISSUE TITLE
Hidding current slide in nav - slider sync

### ISSUE THREAD

**Issue by draszka** [kenwheeler/slick#3150]
Hello,

I would like to display slider with navigation, where main slider shows current slide, and nav slider display 2 of 3 next slides to show. The difference between slider syncing is that I don't need current slide to be displayed in navigation.

https://jsfiddle.net/vqoarbuo/5/

I was trying to set initial slide, but it works until first transition. 
I was trying filter slides with beforeChange, using current class, but it does not work too.  

Here are some pictures showing what result I was trying to set. 

First transition https://imgur.com/a/Lq1nn
Second transition https://imgur.com/a/ywL3D
Third transition https://imgur.com/a/SbBbf

Please help me, maybe somebody encounter same problem and could bring me relief!

Best regards!

**Comment by draszka** [comment]
Please, could somebody help me?

**Comment by kavasey** [comment]
Hello @draszka is the maximum number of slides always going to be 3? If yes, then use the slick prev and next to achieve what you're looking for. 
If not then you can try using a custom pager approach with "slickGoTo" method.

**Comment by draszka** [comment]
Hello :)

Thanks @kavasey for your replay :) Finally, I did like you said:

`    $main_topic_slider.on('beforeChange', function(event, slick, currentSlide, nextSlide){
        $main_topic_nav.slick('slickGoTo', nextSlide + 1);
    });`

**Comment by kavasey** [comment]
Hi @draszka did it work? your 'slickGoTo' method code seems to be called within the beforeChange method which might cause issues. I thought that might be within an on click event of the $main_topic_nav custom pager link like this:
` $('.main_topic_nav_pager a').click(function () {
            var toIndex = $(this).index(); // that is if needed or however you get your slide index
            $main_topic_slider.slick('slickGoTo', toIndex);
        });`
however if your issue seems to be solved, then ignore what I just said.

**Comment by draszka** [comment]
They way I did it is using those sliders separately, not as sync. Main slider is set on autoplay, navigation slider is static, set on infinite: true, to always show 2 slides in nav slider.    

I left brackets in the last post:

`$main_topic_slider.on('beforeChange', function(event, slick, currentSlide, nextSlide){
        $main_topic_nav.slick('slickGoTo', nextSlide + 1);
    });`

Thank you @kavasey for you interest :)

**Comment by kavasey** [comment]
I get it now and i'm glad it helped :) @draszka
