### ISSUE TITLE
Problem with scrolling on ios

### ISSUE THREAD

**Issue by SilencerWeb** [kenwheeler/slick#3153]
I have a problem with scrolling on ios on my website - http://silencer.website/tomatdesign-testing/ (Without init sliders - http://silencer.website/tomatdesign-testing-without-sliders/). It isn't because of header because it had started lagging before I created it.

On my website I use:
autosize.js
jquery.fileupload.js
jquery.validate.js
jquery.inputmask.bundle.js
masonry.pkgd.js(But it destroys on mobile(< 768))
retina.js
slick.js

Here are videos with bugs:
http://silencer.website/tomatdesign-testing/videos/bug1.mp4
http://silencer.website/tomatdesign-testing/videos/bug2.mp4
http://silencer.website/tomatdesign-testing/videos/bug3.mp4

Tested on iPhone 5S, 6S, 7 in Chrome and Safari.

jQuery version - 3.2.1
Slick version - 1.8.1

**Comment by notrealdev** [comment]
Same issue here, not fixed
