### ISSUE TITLE
Target the previous and next slide for css-styling ?

### ISSUE THREAD

**Issue by Serifenlos** [kenwheeler/slick#317]
Is it possible to speak via css with previous and next slide? 
I found `slickCurrentSlide();` but i couldn’t handle it to set new classes to the previous and next slide.
Do you have a quick hint for me?

**Comment by matthiaskrieft** [comment]
Just because I came here first from google: The event-binding has changed, check out https://github.com/kenwheeler/slick/issues/1005

**Comment by michalchovanak** [comment]
@matthiaskrieft is right, the event-binding has changed and @Serifenlos answer is also incorrect because his code is not counting with deleting .prev and .next classes after change of the slides. Also if there are more than one sliders in the page, you cant target like this $('.slick-active').

**Comment by Serifenlos** [comment]
For a redesign of the website i was looking for a new solution. I found this and get happy: https://stackoverflow.com/a/32532363

```javascript
$('.slider')
.on('afterChange init', function(event, slick, direction){
    // console.log('afterChange/init', event, slick, slick.$slides);
    // remove all prev/next
    slick.$slides.removeClass('prevSlide').removeClass('nextSlide');

    // find current slide
    for (var i = 0; i < slick.$slides.length; i++)
    {
        var $slide = $(slick.$slides[i]);
        if ($slide.hasClass('slick-current')) {
            // update DOM siblings
            $slide.prev().addClass('prevSlide');
            $slide.next().addClass('nextSlide');
            break;
        }
    }
  }
)
.on('beforeChange', function(event, slick) {
    // optional, but cleaner maybe
    // remove all prev/next
    slick.$slides.removeClass('prevSlide').removeClass('nextSlide');
})
.slick({
  speed: 900,
  cssEase: "cubic-bezier(0.165, 0.840, 0.440, 1.000)",
  centerMode: !0,
  centerPadding: "4%",
  lazyLoad: "progressive",
  slidesToShow: 1
});
```

**Comment by joebentaylor1995** [comment]
Any solutions without Jquery?
