### ISSUE TITLE
Center padding only reduces the width of images 

### ISSUE THREAD

**Issue by apasho** [kenwheeler/slick#3179]
I've not been able to make cetnerpadding work as in Ken's demo

====================================================================
Here are two fiddles

https://jsfiddle.net/alanp57/ugv2kvLq/7/

https://jsfiddle.net/zstkw2rc/34/

The both demonstrate the problem
====================================================================

#### Steps to reproduce the problem

Run the fiddle. Change the amount of the centerPadding value and run it again. Increasing the padding decreases the width of slides.

====================================================================

#### What is the expected behaviour?

The center slide should be expanded.

====================================================================

All slides have reduced width

...  

====================================================================

#### More Details

I'm using Chrome with these fiddles.

**Comment by senoff** [comment]
@leggomuhgreggo could you give us a hand with this please?  Thanks.

**Comment by leggomuhgreggo** [comment]
remove `infinite: false`

**Comment by apasho** [comment]
It still does not make the center image larger.
