### ISSUE TITLE
Slick slider not working with infinite page scroll

### ISSUE THREAD

**Issue by cliffcleetus** [kenwheeler/slick#3181]
Slick slider not working with infinite page scroll , I have set a page with infinite scrolling (Lazy loading) 
When the page is loaded first , In first page the slick slider works fine , since its infinite page scrolling the second page gets appended to the first page. In second page this slick slider is not working. The thumbnails are not clickable.
====================================================================

###### `[  https://jsfiddle.net/cliffz/j0xods8t/  ]`  

====================================================================

#### Steps to reproduce the problem

1.  Set Infinite page scrolling 
2.  Set slick slider in page1.html and page2.html , so that pagination doesn't work and page 2 gets appended with page 1
3.  Slick slider with thumbnails in page 2 doesn't work now. The thumbanils are not clickable

====================================================================
Expected Behaviour - In Rest of the appending pages also the slick slider with thumbnails must be working ..

...  

====================================================================

#### What is observed behaviour?
In rest of the appended pages , the slick slider with thumbnails are not working 
...  

====================================================================

**Comment by yeole-rohan** [comment]
Does this issue got resolved? @cliffcleetus , what was possible solution provided. facing same issue.
