### ISSUE TITLE
When carousel is hidden on page load the carousel styling is not correct

### ISSUE THREAD

**Issue by rajruprai** [kenwheeler/slick#3197]
> short description of the bug / issue, provide more detail below.
I am attempting to display the carousel on click of a button which means that through css the carousel is hidden (display: none). When this happens i noticed that on click, the width of the carousel is not the full width i would expect. Instead it is making the width something extremely small like 0px so the carousel only displays 1 word per line. The same styling issues occur when I click on button to jump to a specific slide. I noticed that if i were to display the carousel using display: block or something other than display: none then the carousel works as expected. I have removed any external css references so we can eliminate that from the equation. 
====================================================================

###### `jsfiddle`  

http://jsfiddle.net/rajruprai/omwfjoyn/

====================================================================

#### Steps to reproduce the problem

1. Click on button to show carousel  
2. view the carousel 
3. click go to 1 button
4. click go to 2 button

====================================================================

#### What is the expected behaviour?

The expected behavior is that when the View Carousel button is shown, the content of the slide takes up the entire width that it is supposed to. On click of the go to # buttons, the carousel should go to that slide without any styling issues

====================================================================

#### What is observed behaviour?

For some reason the width of each slide is 0px when inspecting the elements. This causing only 1 word to display before it word wraps.

====================================================================

#### More Details

- This happens in all browsers including: Chrome, Firefox, Safari, and IE
- Slick v1.6.0

**Comment by J-Nick** [comment]
I am also using a button click to show the carousel. I noticed (after debugging) that I needed to manually set the desired width and height to the "slick-list" class (added by the plugin) in order for it to properly display and work. Hopefully this helps.

**Comment by rajruprai** [comment]
@J-Nick When i tried that on my jsfiddle it did not work whether i set the width and height to Npx. I updated the jsfiddle to even try auto ```
.slick-list {
	width: auto;
	margin: 0 auto;
	height: auto;
}
```

**Comment by J-Nick** [comment]
Hmm, I'm not sure then. I know it took me some debugging and manually adjusting some of the classes and elements that the plugin adds to get it to work properly in my environment and as I needed it too. It could have been that my solution only applied to my specific environment.

**Comment by rajruprai** [comment]
@J-Nick i did find this eventually. looks like resize might fix it. I will try to see if it helps. 

For reference: [https://github.com/kenwheeler/slick/issues/187](url)

**Comment by rajruprai** [comment]
@J-Nick in my testing, the resize() does work so far even when i have asNavFor for two carousels on one page. if the remainder of my test cases pass then i might call this resolved

**Comment by Tobias-Keller** [comment]
just fire the resize event in your button event
`window.dispatchEvent(new Event('resize'));`
