### ISSUE TITLE
Slider doesn't paint on latest Chrome build (62.0.3202.75)

### ISSUE THREAD

**Issue by BobNoelle** [kenwheeler/slick#3199]
Using  version 62.0.3202.75 the slider renders and functions, but all content is blank.  Any interaction with the slider (or manually changing a styling or element content with dev tools) will cause all the elements to appear.

![screenshot](https://user-images.githubusercontent.com/10131380/32232095-a6e3a654-be2d-11e7-9f14-9beaae0aa8ad.png)
vs.
![screenshot 2](https://user-images.githubusercontent.com/10131380/32232242-fe47c272-be2d-11e7-952c-ead1b957322b.png)

**Comment by BobNoelle** [comment]
Closing until I can provide a non-working example.

**Comment by mmdonaldson** [comment]
@BobNoelle I am having the same issue. Any progress on this?

**Comment by BobNoelle** [comment]
In the end I couldn't replicate the problem externally, something to do with the Angular digest cycle I think.  I had to do a .slick('refresh') after page load and that forced a redraw.

**Comment by mmdonaldson** [comment]
Seems to fix it for me too. Cheers.

Looking at the number of issues on here not sure this will get looked out. My other sites which use slick carousel are unaffected.
