### ISSUE TITLE
Multiple carousels with same class name

### ISSUE THREAD

**Issue by johnylaravel** [kenwheeler/slick#3202]
Short question. Can I use multiple carousels on the same page, but to **initialize every of them with the same class name**? So, it will be **just one initializing function** for everyone.

It works normal for now, but just asking what is the best practice for this? Because I don't wanna have some bugs later that I can't see now

**Thanks!**

**Comment by jslok** [comment]
Yes

**Comment by dariodev** [comment]
Yes, just iterate over elements. Something like this:
```javascript
    $('.slider').each(function(index, element) {
        var slider = $(this);
        //init slider
    });
```
