### ISSUE TITLE
slick slider doesn't work with jquery 3.2.1?

### ISSUE THREAD

**Issue by rae0724** [kenwheeler/slick#3255]
i am using bootstrap 4 and jquery 3.2.1 at the same time.
the slider seems doesn't work at all. please help.
link: http://jsfiddle.net/xvpqhgbo/1/

**Comment by sodevious** [comment]
It runs, you just have to make sure jquery comes before slick: http://jsfiddle.net/57a8pre8/

**Comment by rae0724** [comment]
oh yeah. my god.
sorry , my bad.
