### ISSUE TITLE
Bootstrap + Slick.js - Image does not appear on initial load? 

### ISSUE THREAD

**Issue by leanminmachine** [kenwheeler/slick#3267]
I have read several issues about bootstrap having some problems with slick.js. Tried editing the css too according to one of the issues i've read, but still does not display the image when the site first loads. However, clicking on the tabs / small buttons will load the images as it is supposed to be. 

====================================================================

#### Steps to reproduce the problem

My example site is here: https://leanminmachine.github.io/

Click on the first placeholder and you will get what I mean when I say that the first image on the slider does not load initially. 
The css fix that I tried - I didn't push it to the github page yet. But I tried locally and it didn't seem to work. 

====================================================================

#### What is the expected behaviour?

The first image on the slider loads when I click on the placeholder image. 

====================================================================

#### What is observed behaviour?

First image does not load when I click on the placeholder image. However, clicking on the dots will render / slide to the correct image/slide.

====================================================================

#### More Details

- Which browsers/versions does it happen on? Chrome
- Which jQuery/Slick version are you using? jquery 2.1.3, slick 1.8
- Did this work before? First time using slick.js

**Comment by TimBlume** [comment]
Hello Min,

as I can see on your example site, it seems that you solved the promlem. 
I have the same issue and would be happy if you could give me a hint or the solution.
I tried to check your sites code but didn't find anything that could help me.

Thank you
Cheers,
Tim

**Comment by leanminmachine** [comment]
@TimBlume Refer to this issue here https://github.com/kenwheeler/slick/issues/187. Check the scripts.js file in my repo for that same site, from line 156 onwards. I can't exactly remember what I did atm to fix it but I had to 'manually refresh the position of slick' upon either a click/touch event. Still not sure why there's this issue but that seemed to work...

**Comment by TimBlume** [comment]
Thank you,
finally I got it working. Unfortunately I don't know exactly what did it make work. Either lazyload setting oder  resizing pictures.

**Comment by ahmadalfy** [comment]
This is definitely due to the massive amount of assets you are loading and not related to slick. I stopped the webpage at 30MB of images, they are not showing because of slick ... they are not showing because of the internet connection
