### ISSUE TITLE
Center Mode Z Index 

### ISSUE THREAD

**Issue by hjelmeir** [kenwheeler/slick#3276]
> center mode z-indexing stays sequential

I am attempting to use center mode with a box shadow but due to the zindexing of the slides, I cannot get the center slide in-front of all slides. I am attempting to create [this carousel](https://cdn.dribbble.com/users/13307/screenshots/2731348/web_site_design.jpg). 

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce my bug: 
http://jsfiddle.net/zL17w28f/3/

====================================================================

#### Steps to reproduce the problem

1. Set centerMode: true and slidesToShow: 3
2. Add a box-shadow to .slick-slide

====================================================================

#### What is the expected behaviour?

That in center mode, the z-index of the center slide is the highest.

====================================================================

#### What is observed behaviour?

When in center mode, z index ordering stays sequential.

====================================================================

#### More Details

- Which browsers/versions does it happen on? doesn't matter
- Which jQuery/Slick version are you using? https://github.com/bodrovis/jquery-slick-rails
- Did this work before? No

**Comment by hjelmeir** [comment]
I was able to hack this with css.

```
// Need position relative and a base z index
.slick-slide {
    position: relative;
    z-index: 6;
}
// Set center to high zindex
.slick-center {
    z-index: 999; // or any high #
}
// Target slide after center to keep stacking
.slick-center + .slick-slide {
    z-index: 8;
}
```

**Comment by teamdraftbox** [comment]
@hjelmeir could you pls share the source code for the above given functionaltiy, i stuck at the same place i would like to implement the same effect that you have produced

**Comment by hjelmeir** [comment]
@teamdraftbox Because this was over 2 years ago, I am guessing the code for slick is not the same. So my source code would not help you. Also you can see in my jsFiddle what my code would have looked like (even tho it doesn't work anymore)

But the concept might. When I used slick, the center slide had a class `.slick-center`. I am not sure that slick has the same class name for the center slide. Via css I made the center slide a super high z-index using the class. Then make the very next slide (see css code: `.slick-center + .slick-slide`) to a high z-index, but not as high z-index as center slide. 

There is no way I can help you besides telling you what I did and you seeing if that can apply to today's code.

**Comment by teamdraftbox** [comment]
Hey Robin Hjelmeir ,
Thanx for taking time to explain me the main concept,that to so fast.The
above concept is more important than the code itself, As you have described
the functional behaviour of the library.It is going to be very helpful.
thanx again

cheers
Vishnu Prasath

**Comment by mostafaznv** [comment]
I know this post is for almost 3years ago. but if you add this class to your project, I think your problem will solve

```
.slick-slide {
    position: relative;
    z-index: 1;
}

.slick-active {
    transform: scale(1.2);
    z-index: 2;
}
```

**Comment by EstiT** [comment]
> I know this post is for almost 3years ago. but if you add this class to your project, I think your problem will solve
> 
> ```
> .slick-slide {
>     position: relative;
>     z-index: 1;
> }
> 
> .slick-active {
>     transform: scale(1.2);
>     z-index: 2;
> }
> ```

I had to add improtant to get it to work. Also, `.slick-active` made multiple images larger, not just the center. I ended up using:

```
.slick-center {
    transform: scale(1.2);
    z-index: 2 !important;
}
```
