### ISSUE TITLE
Using rows: 2 and on responsive row: 1 doesn't work

### ISSUE THREAD

**Issue by fourroses666** [kenwheeler/slick#3277]
I need to have 1 row when going responsive < 680 px and show 2 items per row.
Somehow that doesn't work.

I have made a JSFiddle;
https://jsfiddle.net/b5bqk68j/925/  

(refresh when on < 680 px wide)

My Slick call;
```
$('.slider-4st').slick({
	dots: false,
	arrows: true,
	nextArrow: '<div class="next"><i>&raquo;</i></div>',
	prevArrow: '<div class="prev"><i>&laquo;</i></div>',
	infinite: false,
	speed: 300,
	slidesPerRow: 4,
	rows: 2,
	adaptiveHeight: true,
	//slidesToShow: 4,
	//slidesToScroll: 4,
	responsive: [
		{
			breakpoint: 1024,
			settings: {
				slidesPerRow: 3
			}
		},
		{
			breakpoint: 680,
			settings: {
				rows: 1,
				slidesPerRow: 2
			}
		},
		{
			breakpoint: 480,
			settings: {
				rows: 1,
				slidesPerRow: 1
			}
		}
	]
});
```

**Comment by fourroses666** [comment]
Anyone an idea how to fix this?

**Comment by claudiuTicu** [comment]
I have a similar issue:
I'm trying to display 4 images on two rows starting from mobile.

Something like: 
1 2 
3 4 

Please see this example:
https://codepen.io/Cllawz/pen/LezRNB

the slick call:
`$('.slick-wrapper').slick({
  infinite: false,
  mobileFirst: true,
  slidesToShow: 1,
  slidesToScroll: 1,
  arrows: true,
  rows: 2,
  slidesPerRow: 2,
  responsive: [{
    breakpoint: '1024',
    settings: {
      slidesToShow: 4,
      rows: 1,
      slidesPerRow: 1
    }
  }]
});`

**Comment by mrbenosborne** [comment]
I need this ability as well, why has no one fixed this yet?

**Comment by rosivanov** [comment]
Try to use slick 1.8.1 and `slick.js` file. Its important cause `slick.min.js` is broken in 1.8.1

**Comment by jeffmagill** [comment]
I just want to confirm that @rosivanov 's suggestion to use the un-minified 1.8.1 resolved the issue for me. Thanks.

**Comment by Bobyo** [comment]
So with Slick 1.8.1 fixed on the un-minified version still you can't do rows on responsive. One workaround is to have the mobileFirst: true on the initial settings and add the row settings there, then have a separate option on the responsive for 1024 where you default back.
@claudiuTicu 's example is the way to do it.

**Comment by sharathdaniel** [comment]
Still facing this issue, sad to see the plugin isn't maintained anymore.

**Comment by mircoraffinetti** [comment]
As suggested from @rosivanov with .js version is ok.
You can minify the .js version and use it.

**Comment by AntonGrekov** [comment]
Had same problem. rows: 1 along with slidesperRow: 2 had strange effect on slides
Just switching to unmified version of slick.js resolved issue

**Comment by Mobashir1995** [comment]
I just want to confirm that **@x35a** https://github.com/kenwheeler/slick/issues/3277#issuecomment-357706063 reply is working fine. The same fix also apply works for 1.8.0.

**Comment by muzKore** [comment]
I'm very late to the party but I am facing this issue as well. I appreciate some of the hints and tips given above.
There is codepen at [https://codepen.io/booom/pen/dyYjREp](https://codepen.io/booom/pen/dyYjREp) which I started playing with to see if it was something I was doing locally that was breaking it and stopping rows working in responsive mode. 
What I wanted was (mobile first) 1x1 slideshow on mobile, 2rowsx1col @ min-width:576px and 2x2 @ min-width:992px. 
With some adjustments to the jQuery on the right, I got exactly it working. Rows do work on responsive.
If you go to the Codepen link, swap in the following code to the right JS panel and wait for the bottom slider to update, drag the window width, to the breakpoints I mentioned and then you will see what I mean. It works.

`
$('#slick1').slick({
		mobileFirst: true,
		dots: false,
		arrows: true,
		infinite: true,
		speed: 300,
		slidesToShow: 1,
		slidesToScroll: 1,
		responsive: [
			{
				breakpoint: 576,
				settings: {
					rows: 2,
					slidesToShow: 1,
					slidesToScroll: 2
				}
			},
			{
				breakpoint: 992,
				settings: {
					rows: 2,
					slidesToShow: 2,
					slidesToScroll: 2
			  }
			}
		]
});
`

So, I have it working in the CodePen but not in my site.. GRRRR!!!!!!

Life goes on.
Peace and propz

muzKore

**Comment by saeedkhalilnejad** [comment]
2022 still problem with rows in breakpoints 
even swiper doesnt work

**Comment by YuliiTarutin** [comment]
In slick.min.js its broken, in slick.js - all good. Just use unminified version.

**Comment by amityweb** [comment]
Unminified does not work for me, still breaks when using rows 1, slidesPerRow: 1 in a responsive setting. 

Using mobileFirst: true just completely breaks the HTML and slide when going up sizes then. For some reason it strips out the slide HTML and messed stuff up big time.
