### ISSUE TITLE
Google AMP Support

### ISSUE THREAD

**Issue by aleemb** [kenwheeler/slick#3280]
Any chance of getting this out of the box or is this out of scope?

**Comment by cbaur** [comment]
https://ampbyexample.com/dynamic_amp/how_to_embed_interactive_elements_on_amp_pages/ - embed your slider in an (amp-)iframe.
One of the main points of AMP is not to allow including 3rd party JS libraries directly (only in iframes). For slick to work, you'll need jQuery (= 3rd party js lib) and slick.js itself (another 3rd party js library).

**Comment by ahmadalfy** [comment]
I will add the label `Feature request` to this issue and close it till we see if it will be implemented or not. Thank you for the suggestion
