### ISSUE TITLE
Slick not working when using with for loop in vue js

### ISSUE THREAD

**Issue by Quadriphobs1** [kenwheeler/slick#3281]
The slick slider carousel when it is been used with loop in vue js, 

If not used with for loop, it works just fine, but not working when used with loops, the slick is intialised but the content of slide is been placed out side the `<div class="slick-track"></div>` instead of wrapping the content inside the and give it the `slick-slide` class, 

This is an example of the code 

```
mounted: function () {
    this.slideContent();
  }
```
  ```
methods: {
    slideContent: function(){
      axios.get('api/slidecontent')
        .then((response) => {
          this.$data.slides = response.data;
          $(this.$el).find('#carousel').slick({
  		...options...
  	   });
        }, (error) => {
          this.$data.errors = error;
        })
    }
  }
```
in my template i have 

```
<div class="row" id="carousel">
 <div class="slide" v-for="slide in slides" :key = "slide.id">
    ...other option...
  </div>
</div>
```

when been rendered and inspected i get 

```
<div id="carousel-caountries" class="row slick-initialized slick-slider slick-dotted">
  <div class="slick-list draggable">
    <div class="slick-track" style="opacity: 1; width: 4102px; transform: translate3d(-1758px, 0px, 0px);">
      
    </div>
  </div>
</div>
<div class="slide">
    ...other option...
  </div>
<div class="slide">
    ...other option...
  </div>
<div class="slide">
    ...other option...
  </div>
```

what could i be doing wrong,

Sorry i could get this on JSFiddle, But i hope i can get any help ...

**Comment by robbinfellow** [comment]
Seems to be an issue when trying to render slides using `v-for` #2786. Not sure why, but I'm experiencing the same issue in my current project.

I ended up wrapping my slider initiation in a timeout function, not sure if this solution is ideal but it worked for me:

```vue
methods: {
  slideContent: function(){
    axios.get('api/slidecontent')
      .then((response) => {
        this.$data.slides = response.data;
        setTimeout(function() {
          $(this.$el).find('#carousel').slick({
		  // slickOptions...
	     });
        }, 0);
      }, (error) => {
        this.$data.errors = error;
      })
  }
}
```
