### ISSUE TITLE
How to make it working on mobile only?

### ISSUE THREAD

**Issue by allainna** [kenwheeler/slick#3282]
I'd like the slider to be working on mobile only.
I created a new slider with mobileFirst: true and responsive: [{breakpoint: 768, settings: "unslick"}]. But it didn't help.

**Comment by ahmadalfy** [comment]
If you want it to work only on mobile then you should initialize it only on small screen by checking the screen size then deciding whether to run slick or not. It should be something like the following:

```javascript
if (window.matchMedia("(max-width: 768px)").matches) {
  /* the viewport is less than 768 pixels wide */
  $('.slider').slick();
} 
```

**Comment by allainna** [comment]
Thanks for your reply.
How to make it working on resize? When I open it on a big screen and then resize the window the slider doesn't work.

**Comment by rijosh** [comment]
just wright the slider as function and call it in corresponding resolution,  then window resize function destroy or reinit.

function mobileOnlySlider() {
        $('.slider').slick({
            autoplay: false,
            speed: 1000,
            autoplaySpeed: 5000
        });
    }
    if(window.innerWidth < 768) {
        mobileOnlySlider();
    }
    $(window).resize(function(e){
       

        if(window.innerWidth < 768) {
            if(!$('.slider').hasClass('slick-initialized')){
                mobileOnlySlider();
            }

        }else{
            if($('.slider').hasClass('slick-initialized')){
                $('.slider').slick('unslick');
            }
        }
    });

**Comment by mau5ken** [comment]
Yo will need a Sass to only show it on small devices

**Comment by bkingg** [comment]
$carousel.slick({
            slidesToShow: 2,
            slidesToScroll: 1,
            mobileFirst: true,
            responsive: [
                {
                  breakpoint: 768,
                  settings: 'unslick'
                }
            ]
        });

**Comment by bkingg** [comment]
@Mattomanka Use this instead

```$(function(){
    /* Slick needs no get Reinitialized on window Resize after it was destroyed */
    $(window).on('load resize orientationchange', function() {
        $('.carousel').each(function(){
            var $carousel = $(this);
            /* Initializes a slick carousel only on mobile screens */
            // slick on mobile
            if ($(window).width() > 768) {
                if ($carousel.hasClass('slick-initialized')) {
                    $carousel.slick('unslick');
                }
            }
            else{
                if (!$carousel.hasClass('slick-initialized')) {
                    $carousel.slick({
                        slidesToShow: 2,
                        slidesToScroll: 1,
                        mobileFirst: true,
                    });
                }
            }
        });
    });
});```

**Comment by kristina3531** [comment]
Breakpoints do not work correctly in Chrome, Opera, Microsoft edge, only in Mozilla work correctly.
` $(window).on('load resize orientationchange', function() {
        $('.sertificates-slider').each(function(){
            var $carousel = $(this);
            /* Initializes a slick carousel only on mobile screens */
            // slick on mobile
            if ($(window).width() > 991) {
                if ($carousel.hasClass('slick-initialized')) {
                    $carousel.slick('unslick');
                }
            }
            else{
                if (!$carousel.hasClass('slick-initialized')) {
                    $carousel.slick({
                        slidesToShow: 3,
                        slidesToScroll: 1,
                        // mobileFirst: true,
                        nextArrow: '.sertificates__btn--next',
                        prevArrow: '.sertificates__btn--prev',
                        responsive: [
                            {
                              breakpoint: 768,
                              settings: {
                                slidesToShow: 2,
                                lidesToScroll: 1
                              }
                            },
                            {
                              breakpoint: 576,
                              settings: {
                                slidesToShow: 1
                              }
                            }
                        ]
                    });
                }
            }
        });
    });`

What's wrong?

**Comment by HarshithDev** [comment]
nn

**Comment by Semaho** [comment]
Great solution by @bkingg but I would recommend using `$(window).outerWidth()` instead as your breakpoint will react to this one.

(If you have a scrollbar, `width()` may return window width minus scrollbar width.

**Comment by milijanadjeric** [comment]
> @Mattomanka Use this instead
> 
> ```
>     /* Slick needs no get Reinitialized on window Resize after it was destroyed */
>     $(window).on('load resize orientationchange', function() {
>         $('.carousel').each(function(){
>             var $carousel = $(this);
>             /* Initializes a slick carousel only on mobile screens */
>             // slick on mobile
>             if ($(window).width() > 768) {
>                 if ($carousel.hasClass('slick-initialized')) {
>                     $carousel.slick('unslick');
>                 }
>             }
>             else{
>                 if (!$carousel.hasClass('slick-initialized')) {
>                     $carousel.slick({
>                         slidesToShow: 2,
>                         slidesToScroll: 1,
>                         mobileFirst: true,
>                     });
>                 }
>             }
>         });
>     });
> });```
> ```

this solved problem for me! thank you very much !!

**Comment by angelolucas** [comment]
The only problem when using the `resize` event is that slick will be mounted or unmounted for every single resize change.
For this to happen only when it reaches the breakpoint, we can use `window.matchMedia:`
```
$(window).on('load', () => {
  const element = $('.slick-carousel');
  const mediaQuery = window.matchMedia('(max-width: 640px)');

  const handleSwitchSlick = ((e) => {
    if (e.matches) {
      element.slick({
        infinite: false,
        arrows: false,
      });
    } else {
      element.slick('unslick');
    }
  });

  mediaQuery.addListener(handleSwitchSlick);
  handleSwitchSlick(mediaQuery);
});
```

**Comment by permanyer** [comment]
`$('.carousel').slick({
			draggable:true,
			arrows: false,
			speed:800,
	  		cssEase: ceaser.easeOutQuart, // from /bower_components/Ceaser/developer/ceaser-easings.js
	  		useTransform:true,
	  		responsive: [
			    {
			      breakpoint: 5000,
			      settings: "unslick"
			    },
			    {
			      breakpoint: 576,
			      settings: {
			        slidesToShow: 1,
			        slidesToScroll: 1
			      }
			    }
			  ]
		});`
