### ISSUE TITLE
slick with vanilla JS

### ISSUE THREAD

**Issue by kikeestrada** [kenwheeler/slick#3283]
> short description of the bug / issue, provide more detail below.

Hi
Do you have plans to create a vanilla JS version for the slick slider?

Best Regards!

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by ahmadalfy** [comment]
This was already requested https://github.com/kenwheeler/slick/issues/494
