### ISSUE TITLE
Big sliders (more than 200 images) are not working on Mobile

### ISSUE THREAD

**Issue by pseuss** [kenwheeler/slick#3287]
I created a slider with more than 200 Images. It contains a Navigation and a Image on top. On my Mac and the iPad Pro (and on a iPhone 7) it's working without any problems. But On some older iPads (as for example on an iPad Air 2 with iOS 11.2.1) it is not working. After some images it leads to a website reload and safari said it occurs a problem. 

====================================================================

http://www.badhomburg-stichte.de

====================================================================

#### Steps to reproduce the problem

1. Open the Webseite
2. Slide through the images and sometimes it occurs directly, sometimes after some images. 

====================================================================

#### What is the expected behaviour?

It should not lead to an reload of the website. It should run smoothly.

====================================================================

#### What is observed behaviour?

It comes to an reload.

====================================================================

#### More Details

- iPad safari 11.2.1
- Jquery 3.2.1

**Comment by ahmadalfy** [comment]
Hello,

The link you are sharing is returning 502. On another note, I think creating a slider with 200+ image isn't correct from many perspectives. Who would wait to watch a 200 images slide? How do they perform, are you using lazy loading?

Slick (and other sliders) create a very wide tracker (based on the number of the slides) and only display a small proportion by using `overflow: hidden` and animate the tracker using `transform`. These calculations can definitely break if you are using a lot of slides, as if it is a limit set by the browser vendors for the width of the tracker.

IMHO you should be using a different solution other than a slider to display a 200 slide.

**Comment by hariria** [comment]
What would be the best thing for something like this?

I was thinking that you could have a "slider" but instead of creating dom elements for every single thing, you would just create a dom element for the current slide, and then on next / previous button click, change the index of the current slide. But I still want it to function like a carousel, I just want it to be more performant. Does something like this exist?
