### ISSUE TITLE
Centered mode slide visual priority

### ISSUE THREAD

**Issue by RayHell** [kenwheeler/slick#3316]
Hi, i'm trying to change the visual priority of the centered slide in center mode. I'm using css transform:scale to make center slide bigger.
Like this:
<p align="center">
  <img src="https://i.imgur.com/7kUThYH.jpg" width="350"/>
</p>

Usualy Css scale work 
See example: https://jsfiddle.net/cm1p8xsq/1/
I couldn't figure out a way to do it with slick.
Can you tell me if I can achieve this ?
Thanks.

**Comment by RayHell** [comment]
Found solution. Need to set slick-slide to position: relative.

**Comment by leppid** [comment]
thanks!
