### ISSUE TITLE
Scrolling disables carousel on iOS 6 Safari

### ISSUE THREAD

**Issue by fitz0019** [kenwheeler/slick#334]
Hey,

On iOS 6 using Safari if you scroll up or down on any carousel it will disable it from being able to swipe next/previous and even disable the buttons from working. 

To recreate:
- On [your site](http://kenwheeler.github.io/slick/). go down to "Single Item",
- Tap on the carousel and drag the page up or down

Now you can't control the carousel at all - either by buttons, swiping or pagination. 

Thanks!

**Comment by geoffoddie** [comment]
Visiting http://kenwheeler.github.io/slick/
on ipad mini iOS 6.0.1 and ipad 3rd gen 6.01
And can confirm the bug is still happening.
