### ISSUE TITLE
Custom styling for dots

### ISSUE THREAD

**Issue by aditi-joshi-mk** [kenwheeler/slick#3361]
I want to customize the position of dots to come below the slide list.

I am trying to override bottom style in `slick-dots` which is not getting applied. How should I go about this?

Even if I add a custom class in `dotsClass`, the class properties are not getting applied

**Comment by eissapk** [comment]
you gotta change it form slick-theme.css file like the pic
![capture](https://user-images.githubusercontent.com/37540234/43226050-0524c23e-905b-11e8-8e0a-0ca26dc60239.PNG)

**Comment by unnikrishna** [comment]
can we override the css property
like can we change the position of the dots change arrow css??
