### ISSUE TITLE
Cannot Save image on mobile.

### ISSUE THREAD

**Issue by Zlerp** [kenwheeler/slick#3365]
hello,

I am using Slick for one of my project's galleries. I want the user to be able to download the image in the carousel.

normally on mobile, When a user holds down on an image for about a second, the option to save the image to the camera roll appears. When I use slick slider, the option never is given. How do i enable the hold to save image feature on mobile?

====================================================================

Please see Codepen https://codepen.io/Zlerp/pen/MVWyYd

====================================================================

#### Steps to reproduce the problem

1. Open Codepen link or any other slick slider with an image in it on mobile
2. try to save the image on mobile

====================================================================

#### What is the expected behaviour?

I should be able to hold down on the image and be given the option to save the photo if there is an image in the slick slider object.

====================================================================

#### What is observed behaviour?

I am unable to save the image if the image is in a slick slider object on Mobile

====================================================================

#### More Details

Mobile iOS

**Comment by Zlerp** [comment]
add to `img` elements in css:

      -webkit-touch-callout: default;
      -webkit-user-select: default;
      -khtml-user-select: default;
      -moz-user-select: default;
      -ms-user-select: default;
      user-select: default;


solution found here:
[slick issue #2156](https://github.com/kenwheeler/slick/issues/2156)

**Comment by ashdephoenix123** [comment]
@Zlerp Thanks, It worked.
