### ISSUE TITLE
The slider, which is the navigation for another slider, displays badly on the IOS.

### ISSUE THREAD

**Issue by gondziu** [kenwheeler/slick#3383]

**Comment by rajasekhar911** [comment]
check the order in which the js code is loaded in the page. the $(...).slick method should be called only after the slick.min.js file is loaded.

**Comment by gondziu** [comment]
Thanks for reply. Unfortunatelly this is not a problem. 
script.js file which contains $(...).slick method is loaded after slick.min.js... so everything here should be ok..
