### ISSUE TITLE
One pixel of the next slide is visible on the current slide

### ISSUE THREAD

**Issue by cedche99** [kenwheeler/slick#3404]
> short description of the bug / issue, provide more detail below.

When i create a slider i see 1px of the next slide and i don't know how remove that...

look photo : 

<img width="497" alt="capture d ecran 2018-04-11 a 23 01 22" src="https://user-images.githubusercontent.com/12508260/38643107-5eb97e06-3ddc-11e8-8885-e1f9dc204a69.png">

you can see a right line...

====================================================================

#### What is the expected behaviour?

Don't show the ligne orange

====================================================================

#### What is observed behaviour?

We see a orange line on the right who corresponding of the next slide

**Comment by ramoncardena** [comment]
I'm having the same problem. Any solution? The case was closed resolved?

**Comment by cedche99** [comment]
my internet browser was zoomed so i reset this zoom and my problem was resolved.

**Comment by ramoncardena** [comment]
Thanks for the reply @cedche99 . I'm having the same problem with Chrome, but not related to zoom, will open a new case. Thanks.

**Comment by noiseymur** [comment]
Hello @ramoncardena . Did you find a solution to that problem ?
