### ISSUE TITLE
using slick carousel in a not-active tab

### ISSUE THREAD

**Issue by buseca** [kenwheeler/slick#341]
Using slick in tabs, it only works in the tab which is active at the load of the page.
in other tabs, the divs are collapsed, one over other. I think it' a initialization problem, but i can't figure how to solve it.

**Comment by pixprod** [comment]
This worked for me with foundation and slick 1.6:

$('ul.tabs').on('toggled', function (event, tab) {
    $('.slideList .productGrid').slick('setPosition');
});

**Comment by rijosh** [comment]
Not working in tab. setPosition and resize not working..

see this
http://codepen.io/Rijosh/pen/qaoYEL

**Comment by vanydiah** [comment]
`$('.slider-name').slick('setPosition');` is not working for me, 

i added `0` and it works :
`$('.thumb-slider').slick('setPosition', 0);`

**Comment by miladmodaresi** [comment]
this code worked for me
this for my tabs in css=>>.group-tabs{
    display: flow-root;
    border-right: 1px solid #ebebeb;
}

  jQuery( function() {
  window.setTimeout(function(){
    jQuery( "#tabs" ).tabs().addClass( "ui-tabs-vertical ui-helper-clearfix" );
    jQuery( "#tabs li" ).removeClass( "ui-corner-top" ).addClass( "ui-corner-left" );
  },2000)} );

**Comment by tomislav12** [comment]
I solved it with setInterval (with 1ms) & clearInterval javascript functions, more info: https://stackoverflow.com/a/1225185/557432 and https://www.w3schools.com/jsref/met_win_clearinterval.asp

**Comment by qwerobin04** [comment]
``

**Comment by saxsax1995** [comment]
Okay so i was stuck in this sitution just like you guys and i found the reason it cause the issue, it simple because when you use slick in tabs, it gonna set your unused tab to `display: none`, and when they did, the width in that unused tab become 0, and slick need a width to run correctly, and this solution worked for me:
```
.tab-content>.tab-pane{
  display: flex !important;
  height: 0px;
  overflow: hidden;
}

.widget-tab.mixed-tab .tab-pane.active{
  height: auto;
}
```

Set non-active tab to `display: flex !important;` and `overflow: hidden;` will do the same thing as `display: none`, but for some reason, it will set your width automatic, so the slick will works perfectly.

**Comment by IvesDotMe** [comment]
> 
> 
> `$('.slider-name').slick('setPosition');` is not working for me,
> 
> i added `0` and it works :
> `$('.slider-name').slick('setPosition', 0);`


Bootstrap 4. You need to trigger the position change on the tab shown event.

`
	$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
		$('.yourcarousel').slick('setPosition');
	});`

**Comment by briannanda** [comment]
thanks @IvesDotMe

**Comment by SamrtDesign** [comment]
Many many thanks it works for me.

**Comment by msshohan** [comment]
> Okay so i was stuck in this sitution just like you guys and i found the reason it cause the issue, it simple because when you use slick in tabs, it gonna set your unused tab to `display: none`, and when they did, the width in that unused tab become 0, and slick need a width to run correctly, and this solution worked for me:
> 
> ```
> .tab-content>.tab-pane{
>   display: flex !important;
>   height: 0px;
>   overflow: hidden;
> }
> 
> .widget-tab.mixed-tab .tab-pane.active{
>   height: auto;
> }
> ```
> 
> Set non-active tab to `display: flex !important;` and `overflow: hidden;` will do the same thing as `display: none`, but for some reason, it will set your width automatic, so the slick will works perfectly.

This solution also worked for me in Bootstrap 5 tabs. But you need to set the display as block. Flexbox will create problems with the layout of Slick carousel items.

**Comment by tjvarthini** [comment]
It's perfectly work... Thank you
