### ISSUE TITLE
Bug: Jumping from last to first

### ISSUE THREAD

**Issue by Codevz** [kenwheeler/slick#3419]
Is there any fix or solution for infinite carousel jumping issue from last to first? 
It seems this issue not fixed since 2016

**Comment by Undique** [comment]
It's all depends on parameters like slidesToShow, slidesToScroll and how you apply your styles, but for my configuration slidesToShow: 3, slidesToScroll: 1 and style change on .slick-current class I use beforeChange callback to add slick-current class to cloned element also.

          slider.on('beforeChange', function(event, slick, currentSlide, nextSlide){
            let slidesLength = slick.$slides.length - 1,
                isCurrentFirstOrLast = currentSlide === 0 || currentSlide === slidesLength,
                isNextFirstOrLast = nextSlide === 0 || nextSlide === slidesLength;
                
            if (isCurrentFirstOrLast && isNextFirstOrLast){
              let nextClone = $(event.currentTarget).find('.slick-cloned.slick-active');
              setTimeout(function(){
                nextClone.addClass('slick-current');
              }, 100)
            }
          });

**Comment by Codevz** [comment]
@Undique Thanks, Your code was helpful for me, I solved my issue with this: 

```javascript
slick.on( 'beforeChange', function( event, slick, currentSlide, nextSlide ) {
	if ( nextSlide == 0 ) {
		var cls = 'slick-current slick-active' + ( is_center ? ' slick-center' : '' );

		setTimeout(function() {
			$( '[data-slick-index="' + slick.$slides.length + '"]' ).addClass( cls ).siblings().removeClass( cls );
			$( '[data-slick-index="0"]' ).addClass( cls );
		}, 10 );
	}
});
```

PS. is_center should be defined before above code.

**Comment by blakeprudhomme** [comment]
@Codevz Yes!

This fixed my issue where the center slide would not transition with the appropriate styles! Thanks!

**Comment by lealka** [comment]
@Codevz Thanks. Your code was helpful for me. But It's for next button only. Update for previous button here:

`slick.on( 'beforeChange', function( event, slick, currentSlide, nextSlide ) {
	if ( nextSlide == 0 ) {
		var cls = 'slick-current slick-active' + ( opt.centerMode ? ' slick-center' : '' );

		setTimeout(function() {
			$( '[data-slick-index="' + slick.$slides.length + '"]' ).addClass( cls ).siblings().removeClass( cls );
			for (var i = slick.options.slidesToShow - 1; i >= 0; i--) {
				$( '[data-slick-index="' + i + '"]' ).addClass( cls );
			}
		}, 10 );
	}
       
        if (nextSlide === slick.$slides.length - 1 ) {
            var cls = 'slick-current slick-active slick-center';

            setTimeout(function() {
                $( '[data-slick-index="' + nextSlide + '"]' ).addClass( cls ).siblings().removeClass( cls );
                for (var i = -1; i >= -1*slick.options.slidesToShow ; i--) {
                    $( '[data-slick-index="' + i + '"]' ).addClass( cls );
                }
            }, 10 );
        }
});`

**Comment by franboud** [comment]
Hi everyone,
I am always struggling with this problem. That's why I made this fix.
Please note that this is only working if slidesToScroll: 1.

### JS
```Javascript
/**
 * FIX JUMPING ANIMATION
 * Set special animation class on first or last clone.
 */
$carousel.on('beforeChange', function (event, slick, currentSlide, nextSlide) {
    var direction;

    if (nextSlide == currentSlide) {
        direction = "same";

    } else if (Math.abs(nextSlide - currentSlide) == 1) {
        direction = (nextSlide - currentSlide > 0) ? "right" : "left";

    } else {
        direction = (nextSlide - currentSlide > 0) ? "left" : "right";
    }

    // Add a temp CSS class for the slide animation (.slick-current-clone-animate)
    if (direction == 'right') {
        $('.slick-cloned[data-slick-index="' + (currentSlide + 1) + '"]', $carousel).addClass('slick-current-clone-animate');
    }

    if (direction == 'left') {
        $('.slick-cloned[data-slick-index="' + (currentSlide - 1) + '"]', $carousel).addClass('slick-current-clone-animate');
    }
});

$carousel.on('afterChange', function (event, slick, currentSlide, nextSlide) {
    $('.slick-current-clone-animate', $carousel).removeClass('slick-current-clone-animate');
    $('.slick-current-clone-animate', $carousel).removeClass('slick-current-clone-animate');
});
```

### CSS
In the CSS, apply the same CSS of .slick-current to .slick-current-clone-animate :
```CSS
.slick-slide {opacity: 0.3; transition: opacity 0.5s; }
.slick-current,
.slick-current-clone-animate {opacity: 1;}
```

**Comment by aslamdoctor** [comment]
> @Undique Thanks, Your code was helpful for me, I solved my issue with this:
> 
> UPDATED
> 
> ```js
> slick.on( 'beforeChange', function( event, slick, currentSlide, nextSlide ) {
> 	if ( nextSlide == 0 ) {
> 		var cls = 'slick-current slick-active' + ( opt.centerMode ? ' slick-center' : '' );
> 
> 		setTimeout(function() {
> 			$( '[data-slick-index="' + slick.$slides.length + '"]' ).addClass( cls ).siblings().removeClass( cls );
> 			for (var i = slick.options.slidesToShow - 1; i >= 0; i--) {
> 				$( '[data-slick-index="' + i + '"]' ).addClass( cls );
> 			}
> 		}, 10 );
> 	}
> });
> ```
> 
> PS. slick and opt.centerMode variables should define before above code.

This is perfect.

**Comment by subuhunter** [comment]
One of the other post had the same question and The answer is simple.

Just add this style to ur css and voila
.slick-slider div { transition: none; }

Thanks to @jamespotz 

https://github.com/kenwheeler/slick/issues/2711

**Comment by bruce12345** [comment]
Does .slick-slider div { transition: none; } work when you set speed to a different value than 0 ? It doesn't work for me...

**Comment by shaulaev** [comment]
> @Undique Thanks, Your code was helpful for me, I solved my issue with this:
> 
> UPDATED
> 
> ```js
> slick.on( 'beforeChange', function( event, slick, currentSlide, nextSlide ) {
> 	if ( nextSlide == 0 ) {
> 		var cls = 'slick-current slick-active' + ( opt.centerMode ? ' slick-center' : '' );
> 
> 		setTimeout(function() {
> 			$( '[data-slick-index="' + slick.$slides.length + '"]' ).addClass( cls ).siblings().removeClass( cls );
> 			for (var i = slick.options.slidesToShow - 1; i >= 0; i--) {
> 				$( '[data-slick-index="' + i + '"]' ).addClass( cls );
> 			}
> 		}, 10 );
> 	}
> });
> ```
> 
> PS. slick and opt.centerMode variables should define before above code.

Where do I need to insert this code?

**Comment by manchumahara** [comment]
what seems to me the last to first or first to last move is happen the speed is an issue, if the 'speed' value is near max 100 it doesn't matter if it's higher value like 1000 then it's matter, 

this is what I tried to achieved and worked for me. If before change we are going to hit/slide last to first or first to last I have set speed 100 which seems quite find with the transition, otherwise the dynamic/default one. 

```
var report_sldier_speed = 1000 ;
        var report_sldier = $('.report-slider').slick({
            autoplay      : false,
            focusOnSelect : true,
            arrows        : true,
            dots          : true,
            adaptiveHeight: true,
            speed         : report_sldier_speed,
            autoplaySpeed : 3000,
            infinite      : true,
            slidesToShow  : 3,
            slidesToScroll: 1,
            centerMode    : true,
            centerPadding : '100px',
            responsive    : [
                {
                    breakpoint: 768,
                    settings  : {
                        slidesToShow  : 1,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 480,
                    settings  : {
                        slidesToShow  : 1,
                        slidesToScroll: 1,
                        centerMode    : false,
                        centerPadding : '0',
                    }
                }
                // You can unslick at a given breakpoint now by adding:
                // settings: "unslick"
                // instead of a settings object
            ]
        });


        // Add custom class to next or previous slide depending on change direction
        report_sldier.on('beforeChange', (event, slick, currentSlide, nextSlide) => {

            let nextIndex = currentSlide + 1; // assume moving right
            if (currentSlide - 1 == nextSlide || (nextSlide + 1 == slick.slideCount && currentSlide < nextSlide)) {
                nextIndex = currentSlide - 1; // nope, moving left
            }

            if(nextIndex === -1 || nextIndex === slick.slideCount){
                report_sldier.slick("setOption", "speed", 100);
            }
            else{
                //console.log('regular phase');
                report_sldier.slick("setOption", "speed", report_sldier_speed);
            }
        });
```

**Comment by faisaljanjuah** [comment]
Guys I know this is really old issue and may be it is out of date but just for help,
The issue is when you target multiple classes for center like:
```
.slick-slide.slick-active.slick-current.slick-center {
    transform: scale(1.3);
}
```

this will cause issue.

solution is just target only center class like this
```
.slick-slide.slick-center {
    transform: scale(1.3);
}
.slick-slide {
    transition: all ease .3s;
}
```

look at demo: https://jsfiddle.net/faisaljanjuah/9fffrd1r/
