### ISSUE TITLE
slickFilter breaks slickGoTo

### ISSUE THREAD

**Issue by ngardner** [kenwheeler/slick#344]
I have a list of slides, and a button that applies a slickFilter to them. After the slickFilter is ran, I want the slideshow to startover at the first slide. However, slickGoTo doesn't work on the filtered list. It does work if I slickUnfilter it.

```javascript
$('#fullbrandlist').slick({
        slidesToShow: 9,
        slidesToScroll: 1,
        infinite: false,
        onReInit: function() {
            $('#fullbrandlist').slickGoTo(0); // this doesnt work after slickFilter
        }
});
```

**Comment by simonc** [comment]
Wouldn't it make sense to update the elements `index` when the list is filtered ?

**Comment by simonc** [comment]
I just tried adding the following at the end of `reinit`, just before calling `onReInit` and it fixes the `focusOnSelect` issue:

``` js
_.$slides.each(function(index, element) {
  $(element).attr("index",index);
});
```

The only "issue" is that it doesn't keep the selection when unfiltering, going back to the first slide.

Is there anything that would make it a bad idea to reset the indexes ? By the way this code is already called in two places (`addSlide` and `buildOut`), making it a function wouldn't be a bad idea IMHO :)

**Comment by simeydotme** [comment]
http://jsfiddle.net/simeydotme/x2cqa8Lf/2/
Working fine as far as I can tell on `1.5.2` tag or `master` branch. :smiley:
