### ISSUE TITLE
Static slide

### ISSUE THREAD

**Issue by MacosCZ** [kenwheeler/slick#3468]
Is it somehow possible to have first slide static? It means always visible and at the first place.
So after the init it would look like:
[1] [2] [3] [4]
after the first move it would look like:
[1] [3] [4] [5]
and so on...

**Comment by pscdodd** [comment]
Just put the first slide outside of the slider....

________________________________
Von: MacosCZ <notifications@github.com>
Gesendet: Dienstag, 5. Juni 2018 17:29
An: kenwheeler/slick
Cc: Subscribed
Betreff: [kenwheeler/slick] Static slide (#3468)


Is is somehow possible to have first slide static? It means always visible and at the first place.
So after the init it would look like:
[1] [2] [3] [4]
after the first move it would look like:
[1] [3] [4] [5]
and so on...

**Comment by MacosCZ** [comment]
Thank you :)
