### ISSUE TITLE
Problems initializing slick

### ISSUE THREAD

**Issue by JordanaN** [kenwheeler/slick#3474]
Can anybody help me? I'm having a problem with slick, it sometimes starts and sometimes it does not start ... Actually I use a vue component with the html to generate the carousel, my js gets into a file that is loaded into the main layout of my application.

my code is here:
https://gist.github.com/JordanaN/206ffea80a816b76ea3e62b3e7d7d0d3

**Comment by GustavoRSSilva** [comment]
@JordanaN If you are trying to use the version 1.9 by script tags, there is bug. the version 1.9 is not working you need to downgrade to the 1.8 until it is fixed.


cdn.jsdelivr.net/gh/kenwheeler/slick@1.9.0/slick/slick.min.js is not working.
