### ISSUE TITLE
Missing transition (scale) effect on active slide in center mode

### ISSUE THREAD

**Issue by winnewoerp** [kenwheeler/slick#3475]
At this development page
http://homepage2018.ostariaposta.com/unser-haus/
you can see in the slider that the transition (scale) effect is missing when the first slide is reached again after clicking through all slides.

I can't figure out why this is happening. Any suggestions?

Tested with Firefox Quantum 60, IE 11, Google Chrome 62 (Windows).

**Comment by PaulBarrett79** [comment]
Might be related to something I submitted a pull request for #3307

**Comment by winnewoerp** [comment]
Thank you very much! That resolved the problem. As a GitHub newbie I have no idea how to compile the new version of slick.min.js from the slick.js including the changes - but for the moment it works pretty well even using  slick.js.
