### ISSUE TITLE
Add lazy loading

### ISSUE THREAD

**Issue by kenwheeler** [kenwheeler/slick#35]

**Comment by Limboistik** [comment]
Hi Ken,

Now that Slick is featured with Zurb's Foundation, could you update lazyload to work with their Interchange?

**Comment by Juni4567** [comment]
Hey @kenwheeler, 
Thanks for adding this feature but it would be great to load big images in lazy fashion when used like this : 
https://gyazo.com/9b6d5b1abf51a30003123d2a7108a864

I want to be able to load big images on demand (while currently it loads the big images for me right when the navigation thumb images are loaded. 

Would be great to hear from you. Thanks in advance :)
