### ISSUE TITLE
How do I change the css of the left and right buttons?

### ISSUE THREAD

**Issue by kinmy** [kenwheeler/slick#3507]
> short description of the bug / issue, provide more detail below.
I want to change the css of the next and prev button.
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?
I want to add an other icon to the prev and the next button. 
...  

====================================================================

#### What is observed behaviour?
I don't know how to add my icon into the next or the prev button.
...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by BTBTravis** [comment]
Hey @kinmy would you kindly read [CONTRIBUTING.markdown](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown). I don't think the issues section of this repo is the proper place for this sort of help. There is not an issue with the library you simply need guidence. As stated in the [CONTRIBUTING.markdown](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) there are plenty of other places to seek help. 
*  Reddit: reddit.com/r/slickcarousel.
* Gitter chat: gitter.im/kenwheeler/slick.
* Stackoverflow: https://stackoverflow.com/search?q=slickslider

**Comment by kinmy** [comment]
3q
