### ISSUE TITLE
Pause on last slide

### ISSUE THREAD

**Issue by two24studios** [kenwheeler/slick#353]
Hi, on this particular project I'm working on, we'd like to have the slider autoplay through the slides, but stop on the last one.  Is it possible to pause Slick on the last slide?  I have autoplay set to true and and infinite set to false.  I'm trying to use the slickPause method if the last slide in my carousel has the class of 'slick-active'... although it doesn't seem to be working.

$('.pages .slider').slick({
  autoplay: true,
  autoplaySpeed: 5000,
  infinite: false,
});
if($('.slide.user').hasClass('slick-active')){
  slickPause();
}

**Comment by cbenzan** [comment]
Thanks! Just what I was looking for.

**Comment by tatianafrank** [comment]
What if the number of slides varies?

**Comment by tatianafrank** [comment]
What if the number of slides varies?

**Comment by alexandremmp** [comment]
@tatianafrank you can use the length of the slide
