### ISSUE TITLE
slides flickers in infinite mode

### ISSUE THREAD

**Issue by kvizor34** [kenwheeler/slick#3542]
this issue https://github.com/kenwheeler/slick/issues/1961 is relevant to me.
all solutions with use css don't help me...
look a problem only in Chrome 
Demo: http://template.ecom.dev.good-factory.net/
how to fix it ?

**Comment by kvizor34** [comment]
i find fix it!!!
this bug working for useTransition:true and infinite:true
solution:

```
.slick-slide {
    -webkit-backface-visibility: hidden;
}
```
please, write it's like a bug in Google Chrome.
source: https://stackoverflow.com/questions/46252430/slick-slider-why-do-artifacts-appear-when-slide-from-last-to-first-and-from-fir

**Comment by pablogiralt** [comment]
This fixed it for me too
