### ISSUE TITLE
Feature Request: Total Slide Count

### ISSUE THREAD

**Issue by ghost** [kenwheeler/slick#355]
Great work and great script.

A very quick feature to add as all of the 'variables' are there....It would be good to have a function to call to return the total number of slides in the slider, as I'd like to use this 'onclick' to identify whether more slides need to be added (based on current slide vs total slides in slider).

**Comment by jith** [comment]
Its works for me.
$(".slick").on("init", function(event, slick){
    console.log(slick.slideCount);
    console.log(slick.currentSlide+1);
});

$(".slick").slick({
    arrows: false,
    autoplay: true,
    dots: true,
    infinite: true
});

$(".slick").on("afterChange", function(event, slick, currentSlide){
    console.log(currentSlide+1);
});

**Comment by davdenic** [comment]
if you show more then one slide slideCount doesn't work.
```
var slidesPerPage = 6

$(".slick").on("init", function(event, slick){
   maxPages = Math.ceil(slick.slideCount/slidesPerPage);
   $(this).find('.slider-paging-number li').append('/ '+maxPages);
});

$(".slick").slick({
   slidesToShow: slidesPerPage,
   slidesToScroll: slidesPerPage,
   arrows: false,
   autoplay: true,
   dots: true,
   infinite: true,
   dotsClass: 'slider-paging-number'
});

```
