### ISSUE TITLE
Randomize Slides

### ISSUE THREAD

**Issue by gmclelland** [kenwheeler/slick#359]
Can you please tell me how I can randomize the order of the slides?  I was hoping to show a different slide every time the page is reloaded.

Maybe there needs to be a setting for random: true or false?

**Comment by ptrwllrd** [comment]
please consider implementing this, it would be a very handy feature, especially coupled with lazy load

**Comment by flowdee** [comment]
+1

I think it wouldn't be that hard to enhance the initialSlide setting with a random functionality.

**Comment by codebakery-ch** [comment]
$("slick").on("init reInit", function() {
    e(function(a, d, e, f) {
      var i = $('.tabnavdots_wrapper ul li').length;
      var initalSlide = $("slick").attr("random") ? Math.floor(Math.random() * i) : 0;
      $("slick").slick('slickGoTo', initalSlide);
    }, 0);
  });

**Comment by camilogithub23** [comment]
Here's how I did it, seems to be working fine, re-orders the <div> slides upon page reload:

 <div class="slideshow slick_show">                    
               <?php
                $RandomList = array();
                $RandomList[] = '<div><img src="your_img_url_here" /></div>'; 
                $RandomList[] = '<div><img src="your_img_url_here" /></div>'; 
                $RandomList[] = '<div><img src="your_img_url_here" /></div>'; 
                $RandomList[] = '<div><img src="your_img_url_here" /></div>'; 
                $RandomList[] = '<div><img src="your_img_url_here" /></div>';  
                echo $RandomList[rand(0,count($RandomList)-1)];
                ?>                    
</div>

**Comment by Florencia007** [comment]
I'm not a developer.  what is the final code? I just copy and paste it where? Thanks

**Comment by eigentor** [comment]
@gmaclelland thanks for the solution. It worked brilliantly for me.
As for .views-row selector this appears to be don in Drupal. I started out by randomizing the views rows in views, but found out this does not work with caching, so a Javascript solution was necessary...

**Comment by rohilv** [comment]
This being a 2014 issue and marked as feature request, I wanted to know whether this feature request been added to the Slick options already? Cant find it yet

**Comment by emsi68219** [comment]
> Here is how I did it
> 
> ```
> $.fn.randomize = function(selector){
>   var $elems = selector ? $(this).find(selector) : $(this).children(),
>       $parents = $elems.parent();
> 
>   $parents.each(function(){
>       $(this).children(selector).sort(function(){
>           return Math.round(Math.random()) - 0.5;
>       }).detach().appendTo(this);
>   });
> 
>   return this;
> };
> 
> // randomize the slides and then call slick
> $('.view-billboard-rotator').find('.view-content').randomize('.views-row');
> 
> 
> $('.view-billboard-rotator').find('.view-content').slick({
>   fade: true,
>   lazyLoad: 'ondemand',
>   speed: 700,
>   infinite: true,
>   autoplay: true,
>   autoplaySpeed: 4000,
>   slidesToShow: 1,
>   slidesToScroll: 1,
>   cssEase: 'linear'
> });
> ```
> 
> Hope that helps someone.

I´m not a programmer. Can you please tell me, where I have to put this code to randomize caousel slides? Many thanks in advance,

René

**Comment by satendrasingh51** [comment]
This code not working on my project condition
