### ISSUE TITLE
Won't slide if item count is <= SlidestoShow

### ISSUE THREAD

**Issue by andyiwest** [kenwheeler/slick#3609]
http://jsfiddle.net/simeydotme/fmo50w7n/

If item count is <= SlidestoShow, then it doesn't play.
Surely in this instance slide 1 should re-appear after slide 4? It's set to be infinite, so it should be looping no?

1|2|3|4|1|2|3|4

**Comment by nicogaldo** [comment]
I have the same problem, how did you solve it?

**Comment by andyiwest** [comment]
They must have fixed it as I'm not seeing this behaviour anymore, at the time I couldn't fix it however, I simply switched the slider to another script.

The fiddle linked above works, providing you switch the javascript to `JavaScript + jQuery 3.2.1` for example, and `infinite: true`. I just set `SlidestoShow: 50`, with 4 items, and it works as expected.
