### ISSUE TITLE
Slick and a parent display none element set's the width to 0px;

### ISSUE THREAD

**Issue by vonschmytt** [kenwheeler/slick#362]
Hi, 

Lovely work! Makes me dribble.

We're using Slick with Foundation 4 (don't ask, we've got to stick with this) and we're using the "section" component which is set up as an accordion.

The problem we've got is that on initialisation of slick one of the sliders is in an element with "display:none" set, so slick is defining a width of 0px for the Slick Track and slides.

Is there anyway of beating this so that it's got the correct with of the container? It's a responsive site so on resize Slick sorts itself out. Just that initial initialised state.

Thanks for you're help.

Pete

**Comment by zerostatic** [comment]
Thanks GODPUS. That's what I was looking for!
