### ISSUE TITLE
Slick wraps each slide with div element which causing it to break functionality

### ISSUE THREAD

**Issue by jaffal83** [kenwheeler/slick#3635]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by logangarcia** [comment]
Breaks what functionality exactly?

**Comment by jaffal83** [comment]
The functionality of the site, we had an inline editor that allows the author of a page to edit the content of the slide, but it breaks with slick js mainly because there is a method in initializing I think its name is _BuildRows that just add extra Rows that I don't know what they are used for?

but I had a workaround for that you can close the ticket now
