### ISSUE TITLE
Click active slide to go to next slide

### ISSUE THREAD

**Issue by Roddor** [kenwheeler/slick#3648]
I have created a carousel _without_ navigation (no dots, no thumbnails, no arrows). 

Only one image is visible at a time.

The only way to go to the next slide is through swiping.  What I'm trying to achieve is that when you click on that image it slides to the next image in that carousel.

FocusOnSelect is not useful to me, since that only works when clicking on the next slide itself, which is not visible. 

This question was raised before, but the code (see http://jsfiddle.net/f7cdx9dr/) doesn't seem to work with Slick 1.9.0

**Comment by demidov555** [comment]
It works for me. Maybe this case isn't complete.
