### ISSUE TITLE
After activating a responsive breakpoint, items removed by slickFilter can't be retrieved by slickUnfilter

### ISSUE THREAD

**Issue by jmk1** [kenwheeler/slick#366]
I'm getting a problem when I remove some items with slickFilter, then resize the browser to activate a responsive breakpoint, and then when I run the slickUnfilter method I am unable to retrieve the previously filtered items. I'm guessing that when a responsive breakpoint is hit, it's re-initialising slick with only the filtered items - is it possible to have it remember all of the original items after resizing? So that I can then call the slickUnfilter method and display all of the original slide items?

**Comment by diegolameira** [comment]
Is this fix just left behind?

**Comment by jmk1** [comment]
The fix doesn't work properly - more work & testing is required.

**Comment by diegolameira** [comment]
All right, I'm trying to find a solution. It's weird.

**Comment by jmk1** [comment]
The fix is nearly there, but I ran out of time and then didn't end up needing the fix.

**Comment by ezcadev** [comment]
for the fix above: 
instead of _.currentFilter = filter; in line 662 use _.$filter = filter;

Then after refresh() in the checkResponsive use _.filterSlides(_.$filter);
