### ISSUE TITLE
Slick elements disappearing in absolute positioned slick-slider

### ISSUE THREAD

**Issue by collinotis** [kenwheeler/slick#367]
I'm trying to have a scrollable carousel of product images fixed to the bottom of the page. When I absolutely position the slick-slider to the bottom, it looks fine initially. Then it goes haywire as soon as I scroll left to right the first time, with all images but one disappearing.

**Comment by kenwheeler** [comment]
Thanks @gausarts

**Comment by ChadRidings** [comment]
Why close this?  It is Slick causing the issue.  If I have a container that is absolutely positioned, and it's wrapping slick, then Slick is blown to pieces.  The container is not even associated to slick, it's simply a wrapper, nevertheless the absolute positioning throws off the whole carousel.
