### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by endiendo** [kenwheeler/slick#3689]
Is the project dead?

I'm wondering because there are so many interesting pull-requests, which solve a lot of problems or add a lot of new interesting features... 
some waiting till 2017.

If the project is dead, please mark it as it in the main documentation, so someone else can start an "official fork".

thank you.

**Comment by Ali-00-Ridha** [comment]
it seems so.

**Comment by richarddd** [comment]
@kenwheeler 👆

**Comment by decadence** [comment]
Have the same question as well

**Comment by dpordomingo** [comment]
It's a pity that the project is no longer maintained with such many people trying to improve it

**Comment by jimmynames** [comment]
@kenwheeler

**Comment by kozie** [comment]
Whatever the reason is for @kenwheeler not being able to maintain the project. I think, since it's all open source indeed, anyone feeling the need to take this project further should do so.

**Comment by tomhrtly** [comment]
I've started building a carousel JS plugin that utilises Flexbox. It would be great if people would help on the [no jQuery branch](https://github.com/tomhrtly/flexCarousel.js/pull/9), so that we can have a great carousel component for modern browsers.
