### ISSUE TITLE
Full height slick-list on vertical mode

### ISSUE THREAD

**Issue by pedro-rivera** [kenwheeler/slick#3696]
Hey people, long-time Slick user here, now facing a new issue. I'm working on a vertical slider which has up to 10 videos with variable heights. The current might be centered, so we can see a bottom-slice from the previous and a top-slice from the next.

It happens that it's not happening :( The `.slick-list` element doesn't fit container's height.

====================================================================

[http://jsfiddle.net/pedrorivera/r12k8fc5/16/](http://jsfiddle.net/pedrorivera/r12k8fc5/16/)

====================================================================

#### Steps to reproduce the problem

1. Play the slideshow 

====================================================================

#### What is the expected behaviour?

Current video might be centered and previous and next partially visible.

====================================================================

#### What is observed behaviour?

`.slick-list` is shorter than its parent.

====================================================================

#### More Details

`.slick-list` height is set by `e.prototype.setDimensions` on slick main js, so I infer that's it's based first slide shown * number of slides to show.

There's another similar slideshow on the same project, but slides has the same height so I could get it to work by forcing `.slick-list` height to be 100vh.

**Comment by astamataris** [comment]
I had a similar issue with my vertical slider. `.slick-slide`s were not taking full height and a white bar was present between scrolling slides.

I addressed this by(if you know the height ofc):
```
.slick-list {
  height: 100vh;
}
.slick-slide {
    height: 100vh;
}
```

**Comment by pedro-rivera** [comment]
@astamataris I had to give up from slick on this project, unfortunatelly. Solved with TinySlider instead.
