### ISSUE TITLE
Second active slide

### ISSUE THREAD

**Issue by toropanov** [kenwheeler/slick#37]
How is it possible to make second slide in slider active instead of first?

I replaced code to _.dots.find('li').first().next().addClass('slick-active'); ,but it did not fix anything.

Thank you.

**Comment by ivanmrchk** [comment]
I'm trying to achieve the same thing, was this issue resolved?

**Comment by benninkcorien** [comment]
Workaround: 

Edit slick.js around line 2326

`

    Slick.prototype.setSlideClasses = function(index) {

        var _ = this,
            centerOffset, allSlides, indexOffset, remainder;

        allSlides = _.$slider
            .find('.slick-slide')
            .removeClass('slick-active slick-center slick-current')
            .attr('aria-hidden', 'true');
        
        // add this line. 
        // if index is 0 the first item is the current one, 
        // add 1 and the second item is the current one 
        // disclaimer: I have not tested if this causes issues anywhere else..
        index += 1
            
        _.$slides
            .eq(index)
            .addClass('slick-current');
`
