### ISSUE TITLE
Slick Slider not working in arabic

### ISSUE THREAD

**Issue by elieobeid7** [kenwheeler/slick#3702]
This works

https://www.themigrantproject.org/

But not this

https://www.themigrantproject.org/ar/

Any idea why is that? The site was handover to me from someone else, therefore I didn't install slick, it was broken when I got working on the site.

**Comment by bigguy1990** [comment]
Take a look here https://github.com/kenwheeler/slick/issues/2968
Looks related to the dir attribute. 

This appears to fix it for me: 
`.slick-slider .slick-track, .slick-slider .slick-list {
    direction: ltr;
}`

**Comment by elieobeid7** [comment]
I did what you said and it worked! It's working on all languages, should I leave it like that or should I place it only in rtl pages? you know since it's wordpress, so css affects all the site, is the a downside to applying rtl to ltr pages?

**Comment by elieobeid7** [comment]
Thank you so much

**Comment by barisdogansutcu** [comment]
It worked, thanks

**Comment by stefan-lonac** [comment]
Thanks, it works for me too! :)
