### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by rmtsys** [kenwheeler/slick#3708]
when i try to download slick carousel using npm install it is not getting latest version below only version downloaded
+ slick-carousel@1.8.1

**Comment by frederikhors** [comment]
Same here. 1.9.0 in npmjs?

**Comment by jeffreyducharme** [comment]
Same, would love to use the latest in our stack

https://www.npmjs.com/package/slick-carousel shows 1.8.1 as latest

**Comment by incredimike** [comment]
1.9.0 isn't tagged in the repo, only mentioned in a code commit. try including "*" instead of a specific version number.

**Comment by ahmadalfy** [comment]
Version 1.9.0 was pulled of npm because it was buggy. Currently the latest version is 1.8.1
