### ISSUE TITLE
Click slide to advance to center position?

### ISSUE THREAD

**Issue by ajohnh** [kenwheeler/slick#371]
Such a great plugin, thanks.

In center mode, it would be nice to be able to click on a visible slide to promote it to the active position. Can you suggest an approach for this?

I added a 'data-slide-index' attribute to the slides manually and tried something like this....

```
$('.slick-slide').on('click', function(e){
  var slideIndex = $(this).data('slide-index');
  $('#my-carousel').slickGoTo(slideIndex);
});
```

But of course this all goes out the window once the cloned slides are taken into account. Suggestion?

**Comment by stefancova** [comment]
If slick-slick is in centerMode, just to this ;
<code>
$('.slick-slider').on('click', '.slick-slide', function (e) {
            e.stopPropagation();
            var index = $(this).index();
            if ($('.slick-slider').slick('slickCurrentSlide') !== index) {
                  $('.slick-slider').slick('slickGoTo', index);
            }
        });
</code>

**Comment by ssundheim** [comment]
Stefencova, thanks for getting me on the right track. That almost worked for me. I found better luck using the custom attribute 'data-slick-index' set by slick on each slide:

```javascript
  $('.slick-slider').on('click', '.slick-slide', function (e) {
    e.stopPropagation();
    var index = $(this).data("slick-index");
    if ($('.slick-slider').slick('slickCurrentSlide') !== index) {
      $('.slick-slider').slick('slickGoTo', index);
    }
  });
```

**Comment by thesunwave** [comment]
Thank you for this solution.

**Comment by iq-nkraft** [comment]
Awesome. ssundheim's solution worked perfectly for me. I just dropped this code in after my instantiation of Slick. Thanks all!

**Comment by FreshFlesh** [comment]
Hello all,
did someone has a solution to implement this behavior while keeping the carousel accessible? It feels like a bad practice to remove the prev/next buttons. @kenwheeler do you have any recommandation?

Thanks!

**Comment by Villa1013** [comment]
Hello ssundheim.

Thanks for the input, I was wearing very useful days looking for a solution!

**Comment by danielraban** [comment]
only works for last slide any solution?

**Comment by davidxcarroll** [comment]
@ssundheim 's solution only seems to work for one slick slider instance. Otherwise, if there are multiple sliders on a page, they all go next/prev. I'm sure it's a simple tweak but can anyone help me modify the code so clicking next/prev slides will only affect that one slider?

`$('.slick-slider').on('click', '.slick-slide', function (e) {
    e.stopPropagation();
    var index = $(this).data("slick-index");
    if ($('.slick-slider').slick('slickCurrentSlide') !== index) {
      $('.slick-slider').slick('slickGoTo', index);
    }
  });`

**Comment by callumkeogan** [comment]
@davidxcarroll I know this is nearly a year after you asked, but I just had the same problem and I'll leave my solution in case anyone else has the same problem when you have multiple sliders on one page.

All you need to do is add a parent selector to `.slick-slider` i.e. the class you've bound your slider to in the first place. In my instance, I've bound my slider to the `.feed-slider` class so the solution is as follows:
```JavaScript
$('.feed-slider.slick-slider').on('click', '.slick-slide', function (e) {
        e.stopPropagation();
        var index = $(this).data("slick-index");
        if ($('.feed-slider.slick-slider').slick('slickCurrentSlide') !== index) {
            $('.feed-slider.slick-slider').slick('slickGoTo', index);
        }
    });
```

**Comment by sebamed** [comment]
Is there any way to achieve this without using jquery and using only react version of slick carousel?
