### ISSUE TITLE
Bug with last chrome version and slick

### ISSUE THREAD

**Issue by gmesnard** [kenwheeler/slick#3711]
Hi,
I found a bug: compatibility problem between slick and last Chrome version.

Slick version: 1.9.0
jQuery version: 
Chrome version: 72.0.3626.96

This was working smoothly with the previous version of Chrome, the bug has arrived since the update, without any other changes in code.

In responsive mode, when my desktop is at least 782px, the slick is perfect.
[Slick is perfect, no bug](http://site6.gm-creative.fr/slick/nobug-782px.png)
But, when my desktop is less than 782px, the slick is deformed, images are too big (width > 209230px !!)
[Slick is deformed, bug](http://site6.gm-creative.fr/slick/bug-inf-781px.png)

Have you the same problem ?

Thank you

**Comment by gmesnard** [comment]
Sorry, I have resolved my pb... it was a css flex bug, not a slick bug.
I close my issue, best regards.

**Comment by mlncn** [comment]
We are experiencing a similar issue it seems.  @gmesnard what did you do to fix, do you remember?
