### ISSUE TITLE
Slick Slider goes blank on safari

### ISSUE THREAD

**Issue by PythonDream** [kenwheeler/slick#3719]
> short description of the bug / issue, provide more detail below.
On somre resolutions my 3 row slick goes blank (Primarily on safari).
When you scroll down to the slider you can see all the content fine, then sometimes it goes blank.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/xy34gwcp/
those are my settings but I cant reproduce it.

====================================================================

#### What is the expected behaviour?

The expected behavior is that the content within slick is visible.

====================================================================

#### What is observed behaviour? 

slick slider suddenly goes blank

====================================================================

#### More Details

- Which browsers/versions does it happen on?
newest Safari on zoom out.
- Which jQuery/Slick version are you using?
I am using the latest version of slick.
jquery version v1.12.4

- Did this work before? no.
<img width="1091" alt="screenshot 2019-02-19 at 20 04 44" src="https://user-images.githubusercontent.com/25548462/53040453-b5617780-3481-11e9-9b75-01921425748a.png">
<img width="1001" alt="screenshot 2019-02-19 at 20 05 13" src="https://user-images.githubusercontent.com/25548462/53040454-b5fa0e00-3481-11e9-9f8c-4d365217a8ef.png">

**Comment by LastBugStanding** [comment]
how you found a workaround for this ?

**Comment by p-dimi** [comment]
@weestack - how'd you resolve the issue?

**Comment by luizamunk** [comment]
I don't know if that's the case, but I had a slick with two slides, and the second slide was flickering and the content was disappearing in safari browsers.

I used `useTransform: false` solution, that was commented in [this](https://github.com/kenwheeler/slick/issues/1890#issuecomment-367859723) issue and it resolved!

Hope that helps! :)

**Comment by p-dimi** [comment]
I've actually found that the content gets crazy padding in safari, the
entire width of the carousel with all the pictures in padding as well, so I
disabled padding in the css for the slider and it fixed it in my case.
