### ISSUE TITLE
Slick Slider column and row problem

### ISSUE THREAD

**Issue by marcosx6** [kenwheeler/slick#3731]
Hi, i have a slider and variable items. if items are more than 9 i want it to appear 9 items per one screen (3 row x 3 columns). if less, i want 3 item per row. but in this case items are filling the columns not rows .

Actually i want this (if items are less than 9)
x-x-x
x-x--
-----
but i have (the third does not appear)
x-x
x-x
x--
====================================================================

**Comment by m0rjjj** [comment]
```
$(".slider").slick({
  slidesToShow: 6,
  rows: 2,
  slidesPerRow: 3,
});
```
https://jsfiddle.net/xg1mskj4/
