### ISSUE TITLE
CDN 

### ISSUE THREAD

**Issue by devin1229** [kenwheeler/slick#3748]
CDN/CSS Styles Not Working

====================================================================

https://jsfiddle.net/1nLhwxva/1/

====================================================================

#### Steps to reproduce the problem

1. Use the following CDNs:
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css

====================================================================

#### What is the expected behaviour?

Formatting for arrows and dots.

====================================================================

#### What is observed behaviour?

No formatting is being used from linked CSS.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Google Chrome, Safari
- Which jQuery/Slick version are you using?
1.8.1
- Did this work before?
Yes

**Comment by ahmadalfy** [comment]
Formatting and fonts has been separated into separate files since earlier versions. You need to include the following file as well:

```
https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css
```
