### ISSUE TITLE
Responsive not working

### ISSUE THREAD

**Issue by devin1229** [kenwheeler/slick#3751]
> Responsive not working

====================================================================

###### `[ https://jsfiddle.net/rhcefw3u/  ]`  

====================================================================

Responsive settings don't work in version 1.6.0

**Comment by damathryx** [comment]
same here

**Comment by damathryx** [comment]
I am experience the same.

**Comment by ryeteezy23** [comment]
Me too any solution?

**Comment by alimemonzx** [comment]
@devin1229 Try using this [Fiddle](http://jsfiddle.net/alimemon/bnev6Lgm/4/). Thanks.

**Comment by ryeteezy23** [comment]
why your code works? can u explain it to me? whats the difference in other
cdn?

**Comment by alimemonzx** [comment]
@ryeteezy23 there is no difference in CDN. I have used the updated version of library which is 1.9.0 . I recommend you to use the latest.

**Comment by ahmadalfy** [comment]
Closing as this is an issue with an older version that is fixed using the latest version
