### ISSUE TITLE
Not working with jquery jquery-3.3.1.slim.min.js

### ISSUE THREAD

**Issue by viveqbhanu** [kenwheeler/slick#3752]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by zhangtianlin** [comment]
i

**Comment by alimemonzx** [comment]
I tried and its working with latest jQuery version.

**Comment by ecadius** [comment]
works with Jquery 3.3.1 and firefox 66.0.3 or chromium 73

**Comment by ahmadalfy** [comment]
This is because jQuery slim has a lot of features removed and slick depends on it (mostly for animation).
