### ISSUE TITLE
Unable to create centerMode finite length slick slider

### ISSUE THREAD

**Issue by Spa27** [kenwheeler/slick#3754]
Hi, I have a requirement that can have any number of slides but maximum 5 are shown at one time and the center slide is active.Selecting any other visible slide/item should make that item active and bring it up to center. I am trying to create a slick slider with infinite: false and centerMode true. This clearly does not work. 

====================================================================

https://jsfiddle.net/#&togetherjs=zhIEKNdSfF

**Comment by ahmadalfy** [comment]
Can you please reproduce the issue using a fiddle?
