### ISSUE TITLE
Is it possible to have responsive image sizes ?

### ISSUE THREAD

**Issue by aeu** [kenwheeler/slick#3756]
Hello,

I am trying to setup a slick carousel as a nav for another click.  The nav has a three images in it, and the target has text.  Click on an image, the text changes, very straightforward, works great.

I have a question that I've been struggling with for some time now.

1.  Is it possible to have the sizes of the slick slide be responsive?  I want to make the images smaller for mobile and I'm doing it via a media query, but I keep seeing a glitch where as the browser resizes, the elements in the navigation carousel either disappear or stack on top of each other.  I've tried setting the size in the slick-slide, and also on the img inside the slick slide, to no effect.

Thanks!

**Comment by artilishes** [comment]
Do you have an example? Sounds more like you're having issues with your css, not with Slick.

**Comment by alimemonzx** [comment]
@aeu can you please make a Fiddle to reproduce the issues?

**Comment by aeu** [comment]
Hi, I was able to fix this by following a suggestion I found online which was to add a listener to window resize and then calling slick refresh.
