### ISSUE TITLE
Slider image does not appear sometimes

### ISSUE THREAD

**Issue by Kota-M** [kenwheeler/slick#3757]
Hello.

I developed a pair of slick slider, one is main, the other is thumbnail.

However, the main one is not displayed sometimes.
This issue seldom happens in latest OS and browser (i.e. Windows 10 and Firefox 66), but it happens more frequently in older OS, like Windows 7.

Do you have any idea why it is not displayed?

slick 1.9.0
Craft CMS 3.1.21.1

**Comment by gurjarshakti** [comment]
I am facing the same issue. 
Browser - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by mikael2** [comment]
Try changing setHeight in slick.js (line 2099) to the following:

    Slick.prototype.setHeight = function() {

        var _ = this;

        if (_.options.slidesToShow === 1 && _.options.adaptiveHeight === true && _.options.vertical === false) {
            setTimeout(function(){
              var targetHeight = _.$slides.eq(_.currentSlide).outerHeight(true);
              _.$list.css('height', targetHeight);
            },1);
        }
    };

**Comment by ahmadalfy** [comment]
Can you reproduce this issue with a fiddle?
