### ISSUE TITLE
Concatenating 2 strings for CSS setting will result in invalid CSS value

### ISSUE THREAD

**Issue by mrforsythexeter** [kenwheeler/slick#3761]
https://github.com/kenwheeler/slick/blob/a2aa3fec335c50aceb58f6ef6d22df8e5f3238e1/slick/slick.js#L2060

The default option is set to '50px'

so this line would look like

```padding: ('0px' + '50px') ```

pretty sure this wont work

**Comment by KartoffelCheetah** [comment]
> https://github.com/kenwheeler/slick/blob/a2aa3fec335c50aceb58f6ef6d22df8e5f3238e1/slick/slick.js#L2060
> 
> The default option is set to '50px'
> 
> so this line would look like
> 
> `padding: ('0px' + '50px') `
> 
> pretty sure this wont work

If the default is `'50px'`, then that should work. Please note there is a whitespace between the numbers, so it will be `0px vertical` and `50px horizontal` padding.

**Comment by mrforsythexeter** [comment]
ah I see, thank you.

**Comment by ahmadalfy** [comment]
You had me for a second. This is because we’re adding a horizontal space.
