### ISSUE TITLE
Slider Navigation showing less items than supposed to at some breakpoint - inconsistent

### ISSUE THREAD

**Issue by krm218** [kenwheeler/slick#3765]
I've built a slick slider with custom navigation.

At 1024, I have it so it only shows one.

For some reason at certain breakpoints, the top slider (slider-nav) shows less than 5 items? Not sure why it's happening? Any CSS issues? Thanks in advance!

====================================================================

**Comment by ahmadalfy** [comment]
I tried the pen and it works as expected. It either display 5 or 1.
