### ISSUE TITLE
1.90 onAfterChange get data-title

### ISSUE THREAD

**Issue by edoardobiasini** [kenwheeler/slick#3768]
> short description of the bug / issue, provide more detail below.

====================================================================
.on('afterChange') not working as expected in newest 1.9.0 version

$('.slider').on('afterChange', function (event, slick, currentSlide, nextSlide) {
        var currentSlide = $(slick.$slides[currentSlide]);
    var title = currentSlide.attr('data-title');
    console.log(title);

====================================================================

#### Steps to reproduce the problem

It Worked until 1.8.1

====================================================================

#### What is the expected behaviour?

I would get the data-title attribute

====================================================================

#### What is observed behaviour?

i get an `undefined`

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before? IT DID UNTILE UPGRADE TO 1.9.0 (essential for other issues

**Comment by ahmadalfy** [comment]
We dropped support for 1.9 and reverted back to 1.8 because it was buggy. Sorry about that.
