### ISSUE TITLE
Lazy-Load serving mixed content (SSL, HTTPS)

### ISSUE THREAD

**Issue by chasereeves** [kenwheeler/slick#3769]
Lazy load build into Slicks is serving up data over http not https. 

Everything else on the site is both operating on https and serving up links that are https. 

You can view this live on source of this page: https://matterful.co/daily-carry-bags/

====================================================================

I'm hoping there's some kind of variable I can add to force HTTPS, or better yet, a way to make the data-lazy mimic whatever the site is currently running on.

====================================================================

#### Steps to reproduce the problem

1. install Slicks on a website running on HTTPS with an SSL cert. 
2. notice that data-lazy in each of the slides is requesting over http instead of https. 

====================================================================

#### What is the expected behaviour?

I expected it to request the asset over the same protocol the site is currently running on. 

====================================================================

#### What is observed behaviour?

The program actually requests the asset over http even though the site is operating on https. 

====================================================================

#### More Details

- Chrome + safari 
- Which jQuery/Slick version are you using? 1.9.0
- Did this work before? No.

**Comment by MateoLa** [comment]
Hello Chase. I having the same problem. Did you find a solution?
