### ISSUE TITLE
Right click mouse stick

### ISSUE THREAD

**Issue by digitalprogram** [kenwheeler/slick#3770]
> short description of the bug / issue, provide more detail below.

====================================================================
If you right click on a link inside of the slick slider and open in new tab, the slide is stuck with the mouse until the mouse is moved outside the slider. Also happens when just right clicking, no need to open in new tab. 

See the demo page with all examples.
###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. right click a slider that is draggable,
2. slider is stuck to mouse movements.  

====================================================================

#### What is the expected behaviour?

...  Not to be stuck to mouse movements after right click.

====================================================================

#### What is observed behaviour?

...  slider sticks

====================================================================

#### More Details

- Which browsers/versions does it happen on? All
- Which jQuery/Slick version are you using? most recent
- Did this work before? No

**Comment by ahmadalfy** [comment]
Can you reproduce that with a fiddle please?
