### ISSUE TITLE
Erratic timing on autoplay

### ISSUE THREAD

**Issue by kylebar** [kenwheeler/slick#3772]
For some users who come to the site the carousel built is having some eratic timing issues, some say it doesnt change at all and others say its about 45 seconds for the first frame and then 5,6 seconds after that. But others also report it working perfectly fine.

====================================================================

http://staging.leandata.flywheelsites.com

here is the fiddle as well:
http://jsfiddle.net/kylebar/z0d7w9q1/45/

====================================================================

#### Steps to reproduce the problem

1. Load Page
2. See variable autoplay times 

====================================================================

#### What is the expected behaviour?

Consistent autoplay times accross majority of users

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Seems to be happening on both chrome and firefox from the people reporting it
- Which jQuery/Slick version are you using?
jquery-1.11.0.min.js
- Did this work before?
is a and still works for me only about 30% of people report an issue

**Comment by ahmadalfy** [comment]
This is because the `pauseOnHover` option. It’s by default set to `true`. Just set it to false and it will constantly change according to the timing you set.
