### ISSUE TITLE
Margin top

### ISSUE THREAD

**Issue by gitkiselev** [kenwheeler/slick#3776]
> short description of the bug / issue, provide more detail below.

I have 4 sections each time margin-top increses
http://joxi.ru/J2blQVkh0MZWdr

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?
no margin top
...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?
Gogole chrome 74

**Comment by ahmadalfy** [comment]
Either need a link for that or a fiddle to reproduce the issue
