### ISSUE TITLE
Slide option doesn't work

### ISSUE THREAD

**Issue by stratboy** [kenwheeler/slick#3778]
Hi, If I use something different from `div` elements, for example a list, or a container with `p` elements inside, Slick won't work at all. It will create div containers around the list element and and empty list track. And won't create arrows.

```js
$('.text-block.has-scroll-arrows ul').slick({
  autoplay: false
  ,arrows: true
  ,fade: false
  ,vertical: true
  ,slide: 'li'
});
```

![Schermata 2019-05-23 alle 19 42 42](https://user-images.githubusercontent.com/437598/58274383-0c356080-7d93-11e9-8197-5a79aee34d1c.png)

**Comment by ahmadalfy** [comment]
It’s not advised to initialize slick on a list or a paragraph because slick create `div`s for the wrapper and each slide. There is no way to avoid that at the moment
