### ISSUE TITLE
prevent swipe when reaching last slide

### ISSUE THREAD

**Issue by nhutdinh** [kenwheeler/slick#3780]
I have a vertical slider. and I'm using verticalSwiping = true, on mobile when swiping down to move to next slide it's working fine but when reaching the last slide it stucks there and I cannot scroll to see the content below the slider.
I tried to return false in the swipe event but it didn't work. I also try edgeFriction=0 but it didn't work also.

**Comment by ahmadalfy** [comment]
I think this can be achieved using the `edge` event?

```
$('.your-element').on('edge', function(event, slick, direction){
  console.log('edge was hit')
});
```

You can trigger the scroll using JavaScript (like 300px or something) then the user will be able to scroll to the content below
