### ISSUE TITLE
This is absolutely NOT working when following the instructions ...

### ISSUE THREAD

**Issue by blaasvaer** [kenwheeler/slick#3781]
> short description of the bug / issue, provide more detail below.

Seriously can't be bothered. Just wanted you to know, that you do not succesfully communicate implementing this …

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by kravenor** [comment]
You only need to include jquery.
http://jsfiddle.net/kravenor/5x4fj69d/1/

**Comment by blaasvaer** [comment]
Nope, did that ... it simply was to cumbersome to implement. Wrote my own instead.
