### ISSUE TITLE
VariableWidth problem in 1.9.0 - 1.8.1 works

### ISSUE THREAD

**Issue by wzol** [kenwheeler/slick#3785]
I'd like to create a slider with list of variable width items. I've struggled it for hours now, until I've tried an older version, and it works as expected.

============================================================

Works with 1.8.1: http://jsfiddle.net/Lyg18hwx/2/
Collapses(?) with 1.9.0: http://jsfiddle.net/Lyg18hwx/3/

============================================================

I'm not sure if it is a bug or did I miss something - if I did, I'd really like to know what should I change.

**Comment by ahmadalfy** [comment]
We reverted version 1.9 because it was buggy. I am closing this.
