### ISSUE TITLE
Increasing slick slider's height

### ISSUE THREAD

**Issue by elieobeid7** [kenwheeler/slick#3786]
I tried following [this answer][1], nothing worked unless I missed something. Here's the [link of the website][2]

I want the images to fit vertically in slick slider, either by scaling them down, or ideally changing the height of the slider. I don't want adaptive height, the height should be fixed on all sliders.

    <section id="homepage-banner" class="clearfix banner_desktop">
    	<a href="#" class="slider-nav slide-left" style="display: inline;"></a>
    	<a href="#" class="slider-nav slide-right" style="display: inline;"></a>
    	<div class="caroufredsel_wrapper" style="text-align: start; float: none; position: relative; top: auto; right: auto; bottom: auto; left: auto; z-index: auto; width: 2529px; height: 550px; margin: 0px; overflow: hidden; cursor: move;"><div class="banner clearfix banner_desktop" id="slider-1" style="text-align: left; float: none; position: absolute; top: 0px; right: auto; bottom: auto; left: 0px; margin: 0px; width: 17703px; height: 550px; z-index: auto; opacity: 1;">
    						
    							
    							
    				<div class="slide" style="width: 2529px;">
    				<a href="https://www.themigrantproject.org/migration-info/" style="background-image: url(http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-2banner-desktop.jpg)">
    					<img src="http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-2banner-desktop.jpg" class="visible-xs">
    				</a>
    			</div><div class="slide" style="width: 2529px;">
    				<a href="https://www.themigrantproject.org/migration-info/" style="background-image: url(http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-3banner-desktop.jpg)">
    					<img src="http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-3banner-desktop.jpg" class="visible-xs">
    				</a>
    			</div><div class="slide" style="width: 2529px;">
    				<a href="https://www.themigrantproject.org/migration-info/" style="background-image: url(http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-1banner-desktop.jpg)">
    					<img src="http://dev.themigrantproject.org/wp-content/uploads/2019/06/AMHARIC-1banner-desktop.jpg" class="visible-xs">
    				</a>
    			</div></div></div>
    	<div id="pagination" class="" style="display: block;"><a href="#" class=""><span>1</span></a><a href="#" class="selected"><span>2</span></a><a href="#" class=""><span>3</span></a></div>
    </section>

I tried

    .slide, .slide a, .caroufredsel_wrapper, #homepage-banner {
    	height: 667px !important;
    }

Whilst that definitely increased the height, the images still don't fit perfectly, which you could see clearly in the last slide.

The image height is 667px, the banner height increased but the slider is still cropping part of it. If I increase the height to 1000px, it won't make any difference. By the way, the width you see written in the html snippet above, I didn't write it, slick slider did that automatically.

  [1]: https://stackoverflow.com/questions/27684458/change-height-of-slick-carousel
  [2]: http://dev.themigrantproject.org/

**Comment by ahmadalfy** [comment]
Can you isolate that in a fiddle or disable the autoplay option? I cannot check it as it constantly rewrite everything

**Comment by elieobeid7** [comment]
1. 1. You closed it even before answering so there's no point in answering, what's the point of answering if you close it? you're not trying to answer, you're trying to close.
2. I solved this issue on my own a month ago
3. The slide is removed now because even if I got to fix this issue, I wasn't able to fix the autocrop issue, So I used glidejs
4. In order to pause the page in order to inspect it, you use the debug mode, in chrome that's right-click -> open inspector and then you press f8 or fn + f8.  If you don't know how to do that you're not qualified to answer my question or any JS question sorry. @kenwheeler you picked the wrong admin to take care of your project. A project that relies on JS needs a veteran JS developer and that's JS 101.

**Comment by ahmadalfy** [comment]
Hello @elieobeid7 I close the issues with a note asking for a way to reproduce it. On the new ticket it says 

```
use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.
```

Thank you
