### ISSUE TITLE
Slick change the slide when I click on dots in Google Chrome audio player.

### ISSUE THREAD

**Issue by lixometr** [kenwheeler/slick#3791]
> short description of the bug / issue, provide more detail below.
I tested in new Google Chrome browser. Version: 74.0.3729.169
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. Open new Google Chrome
2. Init slick slider with some slides
3. Put the tag <audio controls src="music.mp3"> to the one of the slides.
4. Set the audio tag width aproximately 300px
5. Play it, and click on three dots, to download it
You will see that slider slided. And some bugs appeared.
====================================================================

#### What is the expected behaviour?

Just download the audio.

====================================================================

#### What is observed behaviour?

...  Slides change its slide.

====================================================================

#### More Details

Slick slider the newest version 1.8.1

I think it happends only in Google Chrome because of its audio player. 

So I hope You will fix it. I like the design of Google Chrome audio player :)

**Comment by ahmadalfy** [comment]
Closing as it doesn’t provide a fiddle reproducing the issue.

**Comment by patcon** [comment]
hitting what appears to be same issue. Will post fiddle if I can't resolve myself
