### ISSUE TITLE
Slider arrows get chopped off on hover on safari

### ISSUE THREAD

**Issue by nadeem-khan** [kenwheeler/slick#3793]
Slider arrows get chopped off on hover on safari desktop. This can be fixed by making:

```
.slick-prev, .slick-next{
    height:25px;
}
```

instead of the current 20px;

**Comment by ahmadalfy** [comment]
It looks fine here on Safari on the official docs.
![image](https://user-images.githubusercontent.com/87611/61324887-bbcb0400-a813-11e9-8896-e4fdaf98aa02.png)

Maybe you have are using a bigger font size?
