### ISSUE TITLE
"Cannot read property 'getSlick' of undefined" with asNavFor

### ISSUE THREAD

**Issue by piero-purr** [kenwheeler/slick#3796]
I use 2 different sliders on the same page with the asNavFor in order to sync them

	$('.js-slider-banner-for ul').slick({ /* Images */
		rows: 0,
		arrows: true,
		asNavFor: '.js-slider-banner-nav ul',
	});

	$('.js-slider-banner-nav ul').slick({ /* Text */
		asNavFor: '.js-slider-banner-for ul',
		rows: 0,
		dots: true,
		arrows: false,
		fade: true,
	});

If I click on the dots of the second (the Text), no problem, both slides slides without problems
If I click on the arrows of the first (Images), this happen
- get a "Cannot read property 'getSlick' of undefined" error on console
- image slider does not move
- text slider move as expected
If I click again, the text slider does not move anymore

If I enable arrows for both and remove the dots, all works fine in both the ways
If I enable arrows for both and add dots for the text, I still get the error

I am using the 1.9.0 version and I've tried with old ones, always the same error

**Comment by ahmadalfy** [comment]
Sorry to be late, can you please create a pen reproducing the issue?

**Comment by shexpire** [comment]
Hi there I know this is been closed but I do have the same issue on one of my sites but just on mobile
[https://corsets-uk.com/collections/popular-products/products/architectural-print-waist-taming-corset](url)
I'm using version 1.8.1, the error shows when u touch/click an image from the bottom nav
