### ISSUE TITLE
Slide scrolling in slick slaider

### ISSUE THREAD

**Issue by Marisha-tech** [kenwheeler/slick#3797]
Good day!
The site uses slick slaider.
Slick slaider is made vertically in two columns.
In the left column are the names of the slides (there may be an any amount).
The right column displays the slide itself as an image.
When you automatically scroll in the left column, the number of slides is reduced.
Example:
1) Initially, the slider looks like this (screen "Initial slider"). 
![Initial slider](https://user-images.githubusercontent.com/51979512/59733905-a3e67b80-9279-11e9-9a01-6cf418ab3a88.jpg)

There are 4 slide names in the left column, and an image is displayed in the right column.
2) After automatic scrolling, 3 slide titles are displayed in the left column. (screen "Slider after scrolling")
![Slider after scrolling](https://user-images.githubusercontent.com/51979512/59733912-aba62000-9279-11e9-82bc-ac159d90f918.jpg)
. Must be 4 slides.
In this case, it turns out that the slide on the left scrolls.
Can you please tell me how to make the slide titles not disappear?
Slider code:
```
<script>
    $('.slider').slick({
        arrows: false,//стрелки влево вправо
        infinite: true,
        autoplay: true,
        autoplaySpeed: 6000,
        slidesToShow: 1,
        slidesToScroll: 1,
        pauseOnHover: true,//остановка при наведении
        pauseOnFocus: true,
        focusOnSelect: true,
        fade: true,
        asNavFor: '.slider-nav'
    });
    $('.slider-nav').slick({
        vertical: true,
        autoplay: true,
        //arrows: true,
        //infinite: true,
        slidesToShow: 10,
        //slidesToScroll: 1,
        asNavFor: '.slider',
        pauseOnHover: true,
        pauseOnFocus: true,
        focusOnSelect: true,
        centerMode: true,
        //verticalSwiping: true
    });
</script>
```

**Comment by ahmadalfy** [comment]
Can you create an example reproducing the issue?
