### ISSUE TITLE
extra duplicate calls out when initiate the slick.

### ISSUE THREAD

**Issue by mumu8232** [kenwheeler/slick#3800]
> We use google sponsored client-side API to implement the product tiles, and use slick.js to generate carousel around it. code looks like below:
<script async="async" src="https://www.google.com/adsense/search/ads.js"></script>
<script type="text/javascript" charset="utf-8">
  (function(g,o){g[o]=g[o]||function(){(g[o]['q']=g[o]['q']||[]).push(
  arguments)},g[o]['t']=1*new Date})(window,'_googCsa');
</script>
	<div class="spaProductContainer">
			<div class="spaMenu">
				<div id='spaContainer1' class="spa-menu-item"></div>
				<div id='spaContainer2' class="spa-menu-item"></div>
				<div id='spaContainer3' class="spa-menu-item"></div>
				<div id='spaContainer4' class="spa-menu-item"></div>
			</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function() { 
	$(".spaMenu").slick({
		  dots: true,
		  infinite: false,
		  speed: 400,
		  slidesToShow: 4,
		  slidesToScroll: 4,
		  ......
	
});
.........
 _googCsa('ppas', pageOptions, spaBlock1, spaBlock2,spaBlock3,spaBlock4);

when call method _googCsa,  it will populate spaContainer1, spaContainer2,spaContainer3,spaContainer4 with products,     but the issue is when initate the slick,  seems it will call _googCsa('ppas', pageOptions, spaBlock1, spaBlock2,spaBlock3,spaBlock4) again.   there are duplicate request to google. but the second request is servered by brwoser cache.   
Can someone help me on this ?  how to avoid the duplicate calls ?
====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by ahmadalfy** [comment]
Can you recreate the example with minimal code in a pen?
