### ISSUE TITLE
Not working with css grids?

### ISSUE THREAD

**Issue by tonhwk** [kenwheeler/slick#3802]
As soon as the function: 

```
$(document).ready(function(){
  $('.your-class').slick({
    setting-name: setting-value
  });
}); 
```

get initialized my grid stop working. If the function is never executed the grid is still in place, any fix for it yet?

**Comment by ahmadalfy** [comment]
Can you reproduce that in a pen? It’s hard to imagine what’s the relation between CSS grid and slick
