### ISSUE TITLE
Don't use slick, it's a dead buggy project

### ISSUE THREAD

**Issue by elieobeid7** [kenwheeler/slick#3803]
It's abandoned, no one can help you, neither here nor on stackoverflow. Nearly lost my job because of its bugs. Move on to a better slider.

**Comment by MattTrovao** [comment]
Do you know a slider like Slick? I try use Owl Carrousel, but he don't have the thumbnails

**Comment by elieobeid7** [comment]
I will give you an update, currently migrating to a new banner, will let you know what's my recommended banner.

**Comment by chancestrickland** [comment]
Ken has said repeatedly that he isn't working on OSS anymore. Y'all give Glide a try. https://glidejs.com/

**Comment by zukinaru** [comment]
why this project not being archived ?

**Comment by elieobeid7** [comment]
And there's no disclaimer in the readme stating that the project is deprecated or not actively maintained. None of that.

**Comment by elieobeid7** [comment]
I moved the site to glidejs, it's not loading properly but I think that's because of a wordpress problem than a glide problem. Btw the newer glide version doesn't work on the site. Only the 2.x but again, I think it's a problem with the website I'm working on. So Glide is one slider I recommend.

**Comment by cseas** [comment]
[Glide](https://glidejs.com/) didn't work for me, I couldn't figure out why.

I used [Owl Carousel](https://github.com/OwlCarousel2/OwlCarousel2) as a replacement and it works flawlessly with minimal setup.

**Comment by afonic** [comment]
If you almost lost your job because of Slick you probably need another job anyway.

Projects don't just disappear because they haven't been updated for a year. I've used Slick in dozens of projects with great success and I still do.

**Comment by elieobeid7** [comment]
If the project manager contacted you saying that slick slider is auto-cropping the height of the image, and you fix that using CSS and then another call saying it autocross the width with no explanation and you set the with and height in CSS, also you made sure that the js options is correct and it still gets cropped and you can fix it, then good for you.

**Comment by elieobeid7** [comment]
@cseas yes the team asked me if I could change glide, won't be using it for long. But if you do what I did it will work. Just don't use the latest version

**Comment by ahmadalfy** [comment]
Hello, please check [this](https://github.com/kenwheeler/slick/issues/3810)

**Comment by elieobeid7** [comment]
I definitely hope so but judging from your comment [here](https://github.com/kenwheeler/slick/issues/3786#event-2487411279), you don't seem the savior. @kenwheeler might have picked the wrong guy unless you step up your game. My advice is still to move on.

**Comment by elieobeid7** [comment]
Besides if @kenwheeler  cares enough about his own project, then ken would come and leave a comment, rather than send messengers who make promises they might not be able to keep.  

The fact that he doesn't have time to leave a comment is in itself a reason not to believe anything you said, besides the fact that you cannot use JS debugger.

This is a great project, @kenwheeler should just archive it. There's no shortage of sliders, if he cannot maintain it, he should inform people to go away. There's no shame in letting projects die, every project will die at some point, every single line of code ever written will be useless one day, that's just life, code dies just like we do.

**Comment by kenwheeler** [comment]
I’m just a touch busy at the moment, so trying to delegate maintainership
to stakeholders. The project still works quite well for the 90% use case
and is used on sites across the internet. Doesn’t really need to die imo

**Comment by elieobeid7** [comment]
Thanks for showing up dude, that was the fastest reply ever.

**Comment by afonic** [comment]
@elieobeid7 learn how to report a bug and stop using the Github issues as a forum or a support service because it isn't.

Slick works great, if your images were "cropped by 10px" as you say, you need to provide a fiddle with a clear indication of the bug, otherwise the problem is in your side. In any case I'd suggest to stop spamming the issue tracker with a personal, superficial problem.

**Comment by ahmadalfy** [comment]
@elieobeid7 this is not a war I am not trying to prove anything to anyone. I once contributed to that project and I definitely love it and this is why I am trying to help. I won’t go through your comments because no one wins from a useless argument like that. Thankfully @kenwheeler is here to validate the communication between me and him.

@afonic Thank you, you said what I exactly wrote 5 minutes ago then decided that it’s not worth it.

**Comment by elieobeid7** [comment]
So you really want to know my issues huh? these are my issues  in a jsfiddle. 

https://github.com/kenwheeler/slick/issues/2167

then
https://github.com/kenwheeler/slick/issues/3739

then

https://github.com/kenwheeler/slick/issues/2864

when those issues are closed be sure to notify me, then I'll tell you about the other issues, these are the major ones.

**Comment by zandiarash** [comment]
@afonic 

> Slick works great

If it work in your situation it does not mean that slick slider works great !!!
Let's check issues and pull requests.

I agree with @elieobeid7. at least in **Readme** must be mentioned that it will not support more.
I've also wasted my time using slick slider in my project, now I must change many javascript codes for that...
