### ISSUE TITLE
Feature Request FreeScroll on Drage

### ISSUE THREAD

**Issue by dropways** [kenwheeler/slick#3804]
We need to implement Free Scroll on Drag slide like this.

![freescroll](https://user-images.githubusercontent.com/38377336/60266499-c9245b00-9905-11e9-9852-8d1c05fa0b28.gif)

**Comment by ahmadalfy** [comment]
Tagging as Feature Request, closing because it’s not a support question and will check in the future

**Comment by kikky7** [comment]
Any progress with this?
