### ISSUE TITLE
Brief white background whilst scrolling from last image to first

### ISSUE THREAD

**Issue by 74954** [kenwheeler/slick#3819]
In a 2 image scroller, using background images, when the slider moves from the last image to the first image, it scrolls to a white background until the first image snaps into view. I have also tried using more than 2 images with the same issue between the very last and first slide.

https://jsfiddle.net/f7p5toan/

- Tested on Chrome, Chrome for Android and Edge 
- jQuery 3.4.1 and jQuery 1.11.0 tested with Slick 1.8.1

**Comment by murtlest** [comment]
It's because you're using css id's. A css id can only exist once per page so slick can't clone it. Use css classes instead and it will work. 

https://jsfiddle.net/6pjk7209/5/

**Comment by 74954** [comment]
Perfect that worked thank you
