### ISSUE TITLE
Add slick-active before changing slide

### ISSUE THREAD

**Issue by Ninos** [kenwheeler/slick#3821]
Hey there,

is it possible to add .slick-active / .slick-current to next slide before changing to next slide?

Kindest regards

**Comment by trijammer** [comment]
You could just use the beforeChange event to do what you wish.

**Comment by Ninos** [comment]
I'm seeing it's directly after beforeChange, so normally it should be fast enough. I'll have a look why my css animation is triggered a bit too late. Thx!
