### ISSUE TITLE
Bootstrap select dropdown gets distorted when used with slick slider

### ISSUE THREAD

**Issue by adityasharma7** [kenwheeler/slick#3827]
When using [Bootstrap select](https://github.com/snapappointments/bootstrap-select) dropdown with the [slick](https://github.com/kenwheeler/slick) slider, it gets distorted.

Here is the [link](https://jsfiddle.net/iamaditya/01ncvrbj/) to jsfiddle. 

Does anyone have any solution for this?

Thanks in advance

====================================================================

###### `[  paste your jsfiddle link here  ]`  

https://jsfiddle.net/iamaditya/01ncvrbj/ \

====================================================================

#### Steps to reproduce the problem
Click on the select box it gets distorted.
![image](https://user-images.githubusercontent.com/15027245/62695669-69d16480-b9f4-11e9-921d-5bdaec747964.png)
 

====================================================================

#### What is the expected behaviour?
Without Slick:
![image](https://user-images.githubusercontent.com/15027245/62695983-1c092c00-b9f5-11e9-8e71-043de52f7ee3.png)

====================================================================

#### What is observed behaviour?
With Slick:
![image](https://user-images.githubusercontent.com/15027245/62695856-cfbdec00-b9f4-11e9-84d0-890142afeb71.png)

====================================================================

#### More Details

- Which browsers/versions does it happen on?
All
- Which jQuery/Slick version are you using?
1.8.2
- Did this work before?
No

**Comment by vishy93** [comment]
@adityasharma7 The fiddle is missing Jquery add it to resources

**Comment by vishy93** [comment]
@adityasharma7 Why are you calling it twice?

**Comment by adityasharma7** [comment]
Thanks @vishy93 for looking into it. I have updated the fiddle link. I think that was the previous version of fiddle that I created

**Comment by vishy93** [comment]
@adityasharma7 the issue looks like a css issue.

**Comment by adityasharma7** [comment]
I posted the question on bootstrap-select issue tracker as well: [#2314][1].
As answered by [Casey Holzer][2]:

> You need to set container: 'body' or data-container="body".
> https://developer.snapappointments.com/bootstrap-select/examples/#container

As per Container documentation:

> Append the select menu to a specific element, e.g. container: 'body'
> or data-container=".main-content". This is useful if the select
> element is inside an element with overflow: hidden.



Select element is inside slick-list which sets `overflow: hidden` so that only current slides are visible, so when we set the container: body it works.

Thanks for the response :)

  [1]: https://github.com/snapappointments/bootstrap-select/issues/2314
  [2]: https://github.com/caseyjhol

**Comment by vishy93** [comment]
Glad you solved it.
