### ISSUE TITLE
Uncaught TypeError: undefined is not a function ??

### ISSUE THREAD

**Issue by KG3UNFORGN** [kenwheeler/slick#383]
So I installed the plugins from the site, and pretty much completely copied the scripts.js, slick.js from the master, but no matter what all the declared functions have a error of Uncaught TypeError: undefined is not a function ?, at the start of the function. It looks like this. I been working on solving this problem for about 4 hours now. The code works on the demo site, but using it on anything else, I get that error.

![capture](https://cloud.githubusercontent.com/assets/4960886/3618987/04bdf58c-0df0-11e4-9382-13cd53a79ae3.PNG)

**Comment by Alcalt** [comment]
I have the same problem. Someone found a solution?

**Comment by Ralphiuss** [comment]
I have the same problem. Anyone?

**Comment by simeydotme** [comment]
People; just to reiterate:

Whenever you get "`undefined is not a function`" in a javascript program it automatically means that function doesn't exist (yet). So the solution is to _make_ it exist.

More likely than not this means that:
>1. You have __not__ included the slick plugin into your page
>  - at all
>  - after jQuery
>  - before you try to use it
>2. You have __destroyed__ slick
>  - by calling jQuery again (re-writes the $ object and removes slick)

I know it's frustrating for you all, and we've all encountered this problem in the past; but if you really can't figure it out  or you absolutely believe you have solved all the problems I just mentioned then you should seek support. (stackoverflow, senior developers, consultancies) - this is not a support forum and the problem you are encountering is not with the plugin 😊

The plugin creator is pretty busy trying to kill any bugs and add enhancements to make the carousel even more kick-ass so I took the liberty to write this (clause: possibly not his views/opinions) -- I am more than willing to help any of you solve programming problems but PLEEEEASEE do it in an appropriate forum (stackoverflow) :smile: 

Simon.

**Comment by gpspake** [comment]
Just an update here as I imagine a lot of people here are experiencing this issue for the same reason I was....

`bower install slick` does not install this library; it installs some other guys library which - annoyingly - is also called slick.js. Once installed, it looks like you've installed slick carousel but you've really installed this other library. So, make sure, if you're using bower, to do `bower install slick.js`.

Lessons learned:
Read the docs!
Always make sure you're package/dependency manager is getting what you expected

**Comment by bradwestfall** [comment]
Yep, @gpspake that was the problem. I was driving myself mad here

**Comment by Studioartcz** [comment]
@gpspake thanks man! I was started thinking that i am mad ...

**Comment by osiris2k** [comment]
if(!$('.........').hasClass('slick-initialized')) {
   $('.......').slick({});
}

**Comment by lalithanjali0111** [comment]
Uncaught TypeError: $(...).rotateRight is not a function how to resolve this problem

**Comment by sadikyalcin** [comment]
This can also happen if you have jQuery no conflict mode. Be sure to check `$.fn.slick` vs `jQuery.fn.slick` and see which is defined.
