### ISSUE TITLE
How to disable Transforming?

### ISSUE THREAD

**Issue by stefan0001** [kenwheeler/slick#385]
Hi

Having some problems with the 3d transformation in google chrome.
The problem appears with sticky content infront of the slider.

i changed the variable in the slick.js:
_.transformsEnabled = false;

and added some css:
.slick-slider *, .slick-slider{
-webkit-transform: none !important;
transform:none !important; 
}

Does this lead to some other problems?
And is there a way to disable 3d transformation from "outside" with init option.
or maybe changing the prototype?

a response would be cool (waiting for 9 days)

**Comment by vlrprbttst** [comment]
this is not working for me, i still get the transform :/
