### ISSUE TITLE
Stop slider immediately on hover

### ISSUE THREAD

**Issue by sagive** [kenwheeler/slick#3859]
> short description of the bug / issue:

I am trying to create a circular slider that pauses (immediately) on hover. But... nothing works. it would stop but only after completing a slide which is really slow in this case.

> jsfiddle link:

https://jsfiddle.net/sagive/z8xqym6r/1/

> Expected behavior?

I need the slider to stop as soon as I hover and play as soon as I hoverout

Thank you guys
love your slider and appreciate the time, effort and love put into it ;)

**Comment by sagive** [comment]
Anyone?

**Comment by rifflock** [comment]
I found a solution which is not ideal, but it works:
```javascript
// var normalSpeed = 2000;
// var quickSpeed = 500;
$slider.on('mouseenter', () => {
  var track = $('.slick-track')[0];
  // ORIGINAL cssText "opacity: 1; width: 30000px; transform: translate3d(-1400px, 0px, 0px); transition: transform 2000ms linear 0s;"
  track.style.cssText = "opacity: 1; width: 30000px; transform: translate3d(-1400px, 0px, 0px); transition: transform 500ms linear 0s;"
  $slider.slick('slickSetOption', 'speed', quickSpeed, true).slick('slickPause');
}).on('mouseleave', () => {
  $slider.slick(slickSetOption', 'speed', normalSpeed, true).slick('slickPlay');
});
```
Manually setting the transform value to my quick speed got it to zip to the end of the transform.
Setting `transform` and `transition` to `undefined` stops it where it is.

Definitely a hack, and changing the value of `transform`/`transition` instead of `cssText` did not work.

**Comment by idanwebdev** [comment]
@rifflock Hey =] tried your small hack but it creates a glitch like 2 ~ 3 seconds after the track returns to move, seems like messing with it's transform property really messes things up
