### ISSUE TITLE
single slide arrow issue on touch - mobile

### ISSUE THREAD

**Issue by r2432** [kenwheeler/slick#390]
First of all thanks for the amazing slider! Its awesome! :)

Issue: I have a nexus 5 phone. When I try to click on the prev/next arrows it does not work. I have to click just before the arrow sprites to get it to work, obviously not very user friendly.  So anyway to fix this?

Thanks!

**Comment by kenwheeler** [comment]
Fixed

**Comment by r2432** [comment]
Thanks!

Date: Sun, 25 Jan 2015 05:52:43 -0800
