### ISSUE TITLE
Slide is not working when slidesToShow>slidesToScroll

### ISSUE THREAD

**Issue by satyaki20** [kenwheeler/slick#392]
$('.multiple-items').slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 3,
        slidesToScroll: 2
    });
This is not working for 9 elements. Dots are coming wrong. and for last slide it is not working

**Comment by slaffko1** [comment]
slidesToScroll with `centerMode: true` not working
http://jsfiddle.net/H66vv/33/

**Comment by thomasfrobieter** [comment]
> 
> 
> slidesToScroll with `centerMode: true` not working
> http://jsfiddle.net/H66vv/33/

==> https://github.com/kenwheeler/slick/issues/2328
