### ISSUE TITLE
Multiple Slick Sliders are Creating a Blank Slide & Dot at the End of Each Carousel

### ISSUE THREAD

**Issue by DoopsDesigns** [kenwheeler/slick#3935]
I am unsure how else to word this, I have a hero slider that works as planned. However, further down the page, there are two more sliders that when initiated are creating a blank slide and dot for the navigation that are appended to the carousel.

Here is a link to the page where you can see it in action: https://www.camvaceng.com/

If you scroll down to the news and events section. You will see two sliders side by side, both of which have an extra slide and dot than required. I have tried literally 15 different ways to initiate the slider with no luck, the about 200 combinations of the parameters passes into the slick function. It either breaks more or doesn't work at all.

The sliders are populated with PHP but here is what they essentially would contain i terms of HTML:

	<ul id="events-slider" class="news-events-slider list-reset mt0 mb0 slick-initialized slick-slider slick-dotted">
		<div aria-live="polite" class="slick-list draggable">
			<div class="slick-track" style="opacity: 1; width: 2520px; transform: translate3d(0px, 0px, 0px);" role="listbox">
				<li class="event-slide border-top border-white pt2 mt2 slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide00">
					<h4 class="uppercase mt0 mb0"> ITM Poland 2020</h4>
					<p class="primary uppercase mt0 mb0"> June 2														- 
						June 5 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Poznan Congress Center, Poland
					</p>
					<p class="h5 mt1"> CVE will be exhibiting at ITM Poland on the 2nd – 5th June 2020 at the Poznan Congress Center.</p>
				</li>
				<li class="event-slide border-top border-white pt2 mt2 slick-slide" data-slick-index="1" aria-hidden="true" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide01">
					<h4 class="uppercase mt0 mb0"> Fabtech 2020</h4>
					<p class="primary uppercase mt0 mb0"> November 18														- 
						November 20 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Las Vegas Convention Center, Las Vegas, NV 89109, USA
					</p>
					<p class="h5 mt1"> CVE will be exhibiting at Fabtech, Las Vegas, on the 18th to 20th June 2020 at the Las Vegas Convention Center, 3150 Paradise Road, Las Vegas, NV 89109, USA &nbsp;</p>
				</li>
				<li class="event-slide border-top border-white pt2 mt2 slick-slide" data-slick-index="2" aria-hidden="true" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide02">
					<h4 class="uppercase mt0 mb0"> Beijing Essen Welding &amp; Cutting Fair</h4>
					<p class="primary uppercase mt0 mb0"> June 2														- 
						June 5 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Shenzhen World Exhibition &amp; Convention Center, Shenzhen, China
					</p>
					<p class="h5 mt1"> CVE will be exhibiting at Beijing Essen Welding &amp; Cutting Fair on the 2nd – 5th June 2020 at the Shenzhen World Exhibition &amp; Convention Center, Shenzhen, China</p>
				</li>
				<li class="event-slide border-top border-white pt2 mt2 slick-slide" data-slick-index="3" aria-hidden="true" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide03">
					<h4 class="uppercase mt0 mb0"> TWI 2020</h4>
					<p class="primary uppercase mt0 mb0"> June 4 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Granta Centre, TWI Ltd, Cambridge, UK</p>
					<p class="h5 mt1"> CVE will be exhibiting at TWI, the UK and Joining Exhibition on the June 4th 2020 at the Granta Centre, TWI Ltd, Great Abington, Cambridge.</p>
				</li>
				<li class="event-slide border-top border-white pt2 mt2 slick-slide" data-slick-index="4" aria-hidden="true" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide04">
					<h4 class="uppercase mt0 mb0"> EXPOWELDING 2020</h4>
					<p class="primary uppercase mt0 mb0"> October 13														- 
						October 15 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Expo Silesia, 41219 Sosnowiec, Poland
					</p>
					<p class="h5 mt1"> CVE will be exhibiting at the ExpoWelding, Sosnowiec, Poland on the 13th to 15th October 2020 at the Expo Silesia, Braci Mieroszewskich 124, 41219 Sosnowiec, Silesia, Poland</p>
				</li>
				<li class="event-slide border-top border-white pt2 mt2 slick-slide" data-slick-index="5" aria-hidden="true" style="width: 360px;" tabindex="-1" role="option" aria-describedby="slick-slide05">
					<h4 class="uppercase mt0 mb0"> METALEX 2020</h4>
					<p class="primary uppercase mt0 mb0"> November 18														- 
						November 21 <span style="position: relative; top: -1px; margin: 0 3px;">| </span> Bangkok International Trade &amp; Exhibition Centre
					</p>
					<p class="h5 mt1"> CVE will be exhibiting at Metalex, Bangkok, Thailand on the 18th to 21st November 2020 at the Bangkok International Trade &amp; Exhibition Centre, 88 Debaratana Rd, แขวง บางนาใต้ Bang Na, Bangkok, Thailand</p>
				</li>
				<ul class="slick-slide" data-slick-index="6" aria-hidden="true" style="width: 400px;" tabindex="-1" role="option" aria-describedby="slick-slide06"></ul>
			</div>
		</div>
	</ul>

This is the js:

		(function($){
			var index = 0;
			$('.news-events-slider').each(function() {
				$(this).slick({
					dots: true,
					arrows: false,
					infinite: false,
					autoplay: false,
					slidesToShow: 1
				});
			});
		})(jQuery);

====================================================================

I cannot replicate this in a jsfiddle. But hopefully the link will provide you with enough information. Here is my attempt at trying to replicate it in codepen:

https://codepen.io/jason-is-my-name/pen/KKpeRrr?editors=1111

====================================================================

#### Steps to reproduce the problem

Create multiple sliders on one page.
I cannot identify why else this would be caused, help...

====================================================================

#### What is the expected behaviour?
It should work, without creating extra slide and dot at the end of the carousel ad carousel nav

====================================================================

#### What is observed behaviour?
extra slide and dot at the end of the carousel ad carousel nav

====================================================================

#### More Details

- Which browsers/versions does it happen on? all
- Which jQuery/Slick version are you using? latest / slick 1.9
- Did this work before? no

**Comment by RWAP** [comment]
Looking at your code it appears that the issue is that you have broken the HTML by having two <div>s between the <ul> and <li>

**Comment by DoopsDesigns** [comment]
Hi @RWAP, These divs are created by slick. Here is my raw code:

	<div class="col-12 md:col-6 lg:col-4 px3 mb3 sm:mb4 lg:mb0">
		<h3 class="h2 md:h1 extra-bold uppercase mt0 mb0">Events</h3>

		<?php
		$latest_events = new WP_Query( array(
		'post_type' => 'events',
		'orderby' => 'publish_date',
		'order' => 'ASC'
		)); ?>

		<?php if( $latest_events->have_posts() ) : ?>
			<ul id="events-slider" class="news-events-slider list-reset mt0 mb0">
				<?php while( $latest_events->have_posts() ) : $latest_events->the_post(); ?>
					<?php
					$event_title 		= get_the_title();
					$event_start_date 	= get_field('event_start_date');
					$event_end_date 	= get_field('event_end_date');
					$event_location 	= get_field('event_location');
					$event_excerpt 		= excerpt(55);
					$event_link 		= get_the_permalink(); ?>
					<li class="event-slide border-top border-white pt2 mt2">
						<h4 class="uppercase mt0 mb0">
							<?php echo $event_title ?>
						</h4>
						<p class="primary uppercase mt0 mb0">
							<?php echo $event_start_date; ?>
							<?php if( $event_end_date ) : ?> - <?php echo $event_end_date; ?><?php endif; ?>
							<?php if( $event_location ) : ?>
								<span style="position: relative; top: -1px; margin: 0 3px;">|</span> 
								<?php echo $event_location; ?>
							<?php endif; ?>
						</p>
						<p class="h5 mt1">
							<?php echo $event_excerpt; ?>
						</p>
					</li>
				<?php endwhile; ?>
				<?php wp_reset_postdata(); ?>
			<ul>
		<?php else : ?>
			<p>No events</p>
		<?php endif; ?>
	</div>
	<div class="col-12 md:col-6 lg:col-4 px3 mb3 sm:mb4 lg:mb0">
		<h3 class="h2 md:h1 extra-bold uppercase mt0 mb0">News</h3>

		<?php
		$latest_news = new WP_Query( array(
		'category_name' => 'news',
		'orderby' => 'publish_date',
		'order' => 'DESC'
		)); ?>

		<?php if( $latest_news->have_posts() ) : ?>
			<ul id="news-slider" class="news-events-slider list-reset mt0 mb0">
				<?php while( $latest_news->have_posts() ) : $latest_news->the_post(); ?>
					<?php
					// $post_thumbnail_id = get_post_thumbnail_id( $post->ID );
					// $post_thumbnail_alt = get_post_meta($post_thumbnail_id, '_wp_attachment_image_alt', true);
					// $post_thumbnail_url = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'single-post-thumbnail' )[0];
					$article_title = get_the_title();
					$article_date = get_the_date( get_option('data_format') );
					$article_excerpt = excerpt(11);
					// $post_time = get_post_time( 'g:i a' );
					$article_link = get_the_permalink(); ?>
					<li class="news-slide border-top border-white pt2 mt2">
						<h4 class="uppercase mt0 mb0">
							<a href="<?php echo $article_link; ?>" class="primary">
							<?php echo $article_title ?>
							</a>
						</h4>
						<p class="uppercase mt0 mb0">
							<?php echo $article_date; ?>
						</p>
						<p class="h5 mt1">
							<?php echo $article_excerpt; ?>
						</p>
						<a href="<?php echo $article_link; ?>" class="btn btn-outline primary h6 uppercase py1 mb1">
						View more
						</a>
					</li>
				<?php endwhile; ?>
				<?php wp_reset_postdata(); ?>
			<ul>
		<?php else : ?>
			<p>No news</p>
		<?php endif; ?>
	</div>

I then initiate the sliders using these snips of js:

	<script>
		$('#news-slider').slick({
			dots: true,
			arrows: false,
			infinite: false,
			autoplay: false,
			slidesToShow: 1
		});
		$('#events-slider').slick({
			dots: true,
			arrows: false,
			infinite: false,
			autoplay: false,
			slidesToShow: 1
		});
	</script>

I then get the unexpected result of the last slide that completely shouldn't be there, showing up as a blank slide :(

Like this attached image:

![image](https://user-images.githubusercontent.com/23555249/77905359-06938b80-727e-11ea-9580-7b9286e2717e.png)

If anyone could help me debug this, the client is really pushing hard on this and I would really appreciate the help!

**Comment by DoopsDesigns** [comment]
May I please request further support on this bug, appreciate your time, Jason.

**Comment by RWAP** [comment]
After the ```<?php endwhile; ?>``` in your code, you have a second ```<ul>``` instead of a closing ```</ul>```

**Comment by DoopsDesigns** [comment]
Oh my sweet baby Jesus in a crib. You are my favourite person alive right now! I knew it was something I had done but was completely blind to it!

**Comment by DoopsDesigns** [comment]
@RWAP has resolved my issue.

If you are experiencing a similar issue, be sure to make sure your sliders have the appropriate closing tag on the element you are targeting with .slick().

Big thanks for returning to help.
