### ISSUE TITLE
Element with slick-cloned is always set to aria-hidden='false'

### ISSUE THREAD

**Issue by marco-uccellini** [kenwheeler/slick#3941]
> short description of the bug / issue, provide more detail below.
We have a dynamic carousel with two slides with infinite=true. It displays the slides and rotates as expected, but adds a duplicate of the first slide to with the class slick-cloned and aria-hidden='false'

====================================================================

Hard to do this as the sliders are populated with PHP but here is output HTML:
```
<div class="forthcoming-promotionsCarousel" style="position: absolute !important; top: -9999px !important; left: -9999px !important; display: block !important; opacity: 0;">
<div class="banner-container">
<div class="banner-content center">
<h1>Boys' t-shirt sale in Europe</h1>
<h2>Get ready for summer 2019</h2>
<h3> </h3>
<p><strong>€5 OFF*</strong> selected items</p>
<button class="promotion button hollow tiny">ADD ITEMS</button>
<p class="small">Includes EUR items only. Starts midnight (GMT+2) 24th September 2018. Ends 15th December 2021.<br /> * As you are VAT registered and use net pricing, the full face value for this promotion will be reduced by the VAT equivalent where VAT is not chargeable. </p>
</div>
</div>
<div class="banner-container">
<div class="banner-content center">
<h1>Clothing Sale</h1>
<h2> </h2>
<h3> </h3>
<p><strong>20% OFF selected items </strong></p>
<button class="promotion button hollow tiny">ADD ITEMS</button>
<p class="small">Includes GBP items only. Starts midnight (GMT) 24th March 2020. Ends 31st March 2020.</p>
</div>
</div>
</div>
```

And the intialize code is:

```
$('.forthcoming-promotionsCarousel').slick({
                dots: true,
                infinite: true,
                autoplay: true,
                speed: 2000,
                arrows: false,
                slidesToShow: 1,
                slidesToScroll: 1,
            });
```

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

The carousel should infinitely display slide 1, followed by slide 2, followed by slide 1 etc
The number of dots should be equal to the number of slides, ie 2.

====================================================================

#### What is observed behaviour?

The carousel displays as an infinite loop but displays an extra blank slide after slide 2, and there is also an extra dot displaying

The HTML has an extra slide added which is a duplicate of the first slide but has the extra class slick-cloned. It doesn't display because aria-hidden='false'. 

The number of navigation dots is three when there are only two slides. In this case an extra button element with an id=slick-slide-control-02 and aria-label="3 of 3"

====================================================================

#### More Details

- Which browsers/versions does it happen on? Latest versions of Chrome on OSX and Windows
- Which jQuery/Slick version are you using? Version: 1.6.0 and also tested with  Version: 1.8.1
- Did this work before? No

**Comment by RWAP** [comment]
There is an error in the HTML causing a cloned element of a ```<strong>```.... rather than the intended ```<div class="banner-container">```

Hard to spot where HTML errors cause this

**Comment by marco-uccellini** [comment]
Thanks @RWAP 

Fixing the HTML error has fixed this issue.
