### ISSUE TITLE
Double row navigation doesn't work correctly

### ISSUE THREAD

**Issue by mikemix** [kenwheeler/slick#3943]
Double row navigation doesn't work correctly.

====================================================================

###### https://jsfiddle.net/ob7wg31r/

====================================================================

#### Steps to reproduce the problem

1. Create double row navigation for a slider
2. Switch to next slide
3. Notice how navigation moves while it should not

====================================================================

#### What is the expected behaviour?

Nav should navigate to the next "page" only when really needed.

====================================================================

#### What is observed behaviour?

The nav switches each time.

====================================================================

#### More Details

- Firefox latest, Chromium latest
- Latest jQuery, latest Slick
- I guess not #2570

**Comment by patriceckhart** [comment]
Is there anything new about that?
