### ISSUE TITLE
Animate current slide

### ISSUE THREAD

**Issue by nashvinxtn** [kenwheeler/slick#3955]
> Actually i have use Slick on almost all my projects, till now all were going fine.
I have got a new problem, a flicker the slider when trying to do something like that :
![image](https://user-images.githubusercontent.com/11077268/80963748-a796d880-8e20-11ea-9e6b-29759d6d5278.png)

As for the options it's like this : 
infinite: false,
slidesToShow: 2.5,
slidesToScroll: 1,
variableWidth: true,

That is the current is always wider than the other as you can see on image, and on scroll next will have that width etc..

**Comment by agustinl** [comment]
Hi @nashvinxtn could you provide a fiddle/codepen to reproduce the issue?

**Comment by nashvinxtn** [comment]
Hello @agustinl thanks for your reply.

Here is the issue : 
https://codepen.io/nashvinxtn/pen/jObZNqK

**Comment by agustinl** [comment]
HI @nashvinxtn , I understand now. The problem I think is that image width change before the slider stop the slide movement, and this obligate to re-calculate the width of the slider.

I cant fixed using `afterChange` event.

```js
jQuery('.img-slider.slick-current').css("width", "595px");

jQuery('.slider-gallery').on('afterChange', function(event, slick, direction){
  jQuery('.img-slider').css("width", "auto");
  jQuery('.img-slider.slick-current').css("width", "595px");
});
```

[The complete codepen (with the css line removed)](https://codepen.io/agustinl/pen/bGVLrbN)

Let me know if I understood ok,
regards!

**Comment by nashvinxtn** [comment]
Hello @agustinl thanks for your answer. Its good for me, i didn't think of using afterChange at all.
Was thinking too much in the wrong direction.

Thanks again for your help.
