### ISSUE TITLE
set initial slide index

### ISSUE THREAD

**Issue by linkit87** [kenwheeler/slick#396]
Is there anyway to set initial slide to show without triggering the animation?

**Comment by centerlinescores** [comment]
So basically what I'm seeing in the real world and what I think I'm reading here is just that "initialSlide" doesn't work at ALL; correct?

**Comment by centerlinescores** [comment]
To paraphrase Yzma from "Emperor's New Groove":  

*Why do we even HAVE that option?!*

Workaround above works like a charm.

**Comment by kenwheeler** [comment]
@centerlinescores its tricky. Say you have 6 slides. slidesToScroll is 3. That makes the only navigable indexes 0 and 3. So if you put initialSlide: 2, it wont work. Do you have a particular use case that isn't working for you?
