### ISSUE TITLE
appendArrows: ".slider-wrapper" ARROWS DOESNT WORK

### ISSUE THREAD

**Issue by PandaCodeLab** [kenwheeler/slick#3965]
Hi! Adding appendArrows option, but than slider arrows buttons doesnt work. I guess its
about context. 

![image](https://user-images.githubusercontent.com/48943704/82330652-cb931600-99eb-11ea-974c-f130d7a43b02.png)

![image](https://user-images.githubusercontent.com/48943704/82330687-d51c7e00-99eb-11ea-8f5c-516a29e36c5b.png)

**Comment by agustinl** [comment]
Hi @PandaCodeLab 
Could you pls provide a codepen demo ?
Thanks!

**Comment by PandaCodeLab** [comment]
@agustinl tnx for reply. Solved the problem without appendArrows.

**Comment by jeffykle** [comment]
@PandaCodeLab How?
