### ISSUE TITLE
Support for "<picture> <source></source> </picture>" tags

### ISSUE THREAD

**Issue by fredojbg** [kenwheeler/slick#3966]
Hi guys, is there any support for those tags

` < div class="js-full-banner" >
  < picture > < source srcset="" media="" >< /source ><i mg src/ > < /picture >
  < picture> < source srcset="" media="" >< /source> <i mg src/ > < /picture >
< /div >`

I'm opening this issue because, my slick configuration doesn't work fine with these tags

`  $('.js-full-banner').slick({
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: true,
    prevArrow: prevArrow,
    nextArrow: nextArrow,
    dots: true,
    infinite: true,
  });`

sometimes my images remains blank and sometimes it's ok.... 

Thanks....

**Comment by agustinl** [comment]
Hi @fredojbg 
Could you pls provide a codepen ?

**Comment by fredojbg** [comment]
I was wrong ... ok, the problem was because the image was not loading as it is too heavy...
