### ISSUE TITLE
While silder initialize getting large image after initialize display correct

### ISSUE THREAD

**Issue by chirantan369** [kenwheeler/slick#3971]
Hi,

While silder initialize getting large image after initialize display correct. i am assign slider dynamic based on api response.

this is the my code.
$(document).ready(function () { 
      $(sliderClass).slick({
        slidesToShow: 4,
        slidesToScroll: 4,
        autoplay: false,
        autoplaySpeed: 1500,
        arrows: true,
        dots: false,
        pauseOnHover: false,
        prevArrow: '<div class="Slider-left-arrow pointer"><i class="fa fa-chevron-left" style="font-size: 24px;" aria-hidden="true"></i><div>',
        nextArrow: '<div class="Slider-right-arrow pointer"><i class="fa fa-chevron-right" style="font-size: 24px;" aria-hidden="true"></i></div>',
        responsive: [{
          breakpoint: 1000,
          settings: {
            slidesToShow: 4
          }
        }, {
          breakpoint: 520,
          settings: {
            slidesToShow: 1
          }
        }]
      }); 
    });

Thanks in Advance

**Comment by agustinl** [comment]
Hi @chirantan369 
Could you pls provide a codepen to help you?

**Comment by Abhivirusonline** [comment]
Hi @chirantan369 
Provide the width/Height  to <IMG> either inline or using CSS selectors.

`<img src="abc.jpeg" alt="some text" width="100" height="100"/>`

**Comment by chirantan369** [comment]
Thanks @agustinl and @Abhivirusonline for your response.

resolved my issue using the width.
