### ISSUE TITLE
.slickGoTo(int) seems not to work properly

### ISSUE THREAD

**Issue by kiwifraise** [kenwheeler/slick#398]
Hi,

First, a great thanks for this awesome plugin ! It works like a charm !
Excepts.. one thing : 
slickGoTo seems not to work properly.
I have a set of (8 in my example) divs with various content inside, and slider is set to display 3, and scroll by 3.
I initiate the slider, then I use the slickGoTo function to put the current slide in the display. (after a page refresh for example).
If index is < nb+2 slides, it works.
But if index is near the max number of divs, it stays at the first div...
And the prev/next buttons doesnt not work.

Is there any issue ?

Thanks !!

I can send u an URL in private to view the trouble, if you want.

**Comment by pencilcheck** [comment]
Adding the '+' sign before index works for me. However I was using .slick('slickGoTo', index) because the documentation allured that use cases

**Comment by simeydotme** [comment]
http://jsfiddle.net/ewmb9mx3/

... `slickGoTo` works fine now :) even after using next/prev buttons

**Comment by zonf** [comment]
var sliderItemId;
$(".videousItem").each(function(index, element) {
    $(this).click(function() {
	sliderItemId = $(this).attr("data-slick-index")
	$(".videousBottom").slick( "slickGoTo", sliderItemId );
    });
});

**Comment by thompsonemerson** [comment]
```javascript
let slide = $('.slideshow');

slide.slick();

$('nav a').click(function(e){
   e.preventDefault();
   slideIndex = $(this).index();
   slide.slickGoTo( parseInt(slideIndex) );
});
```

**Comment by aonawale** [comment]
Unfortunately, having `infinite: false` this in the option breaks the `.slick('slickGoTo', index);` function.

**Comment by vpascoal** [comment]
@aonawale  is right:
http://jsfiddle.net/rhhfjuLa/

**Comment by syk0ne** [comment]
same problem here, setting `infinite: false`, breaks the slickGoTo function.
will there be a fix for it?

**Comment by nikasvan** [comment]
Same problem for `focusOnSelect: true`.

**Comment by underscorefunk** [comment]
As a work around I tried to successively call slickNext from on 'afterChange', until a variable for the offset is decremented to zero (a counter for how many 'next' advancements to perform. This also doesn't work. :(

**Comment by JanBrinker** [comment]
Just encountered the same bug with basically the same code as hompsonemerson's.

Adding the + to the parameter made the slider always slide forward (always forward, never backward) by 4 (which coincidentally is my value of slidesToShow). If I don't add the 4 the slider jumps forth and back.

Funnily enough: If I open the console and tell my slider to go to a certain slide with hardcoded indices: all is good! If I use values gained by .index() it's not working. Hope that points you into some direction..

**Comment by JanBrinker** [comment]
Update:
`infinite: true` broke things for me (unlike `infinite: false` breaking things with the others above).

A way to solve this:
```let slide = $('.slideshow');
slide.slick();

$('.slide').click(function(e){
    e.preventDefault();
    $('.slide').removeClass('slide-current');
    $('this).addClass('slide-current');
});```
Setting the class `.slide-current` to the correct item in contrast to using `slickGoTo` solved this for me. Slick recognizes this and slides to the current item just as you'd like it to.

**Comment by jaegz** [comment]
I too just experienced the same bug. 
My solution was to set `slidesToShow` and `slidesToScroll` to the same value.
However, if this doesn't fit your use case, you'll have to try something else or wait for a fix.

```
$('.playlist').slick({
	dots: false,
	infinite: false,
	speed: 300,
	slidesToShow: 5,
	slidesToScroll: 5
});

$('.playlist').slick('slickGoTo', index);
```

**Comment by harsharora04** [comment]
I also did this
`
$('.playlist').slick({
	dots: false,
	infinite: false,
	speed: 300,
	slidesToShow: 5,
	slidesToScroll: 5
});
`
But I wanted user to scroll only one item at a time, hence changed the following from:
`$('.playlist').slick('slickGoTo', index);`
to 
`$('.playlist').slick('slickGoTo', index).slick('slickSetOption', 'slidesToScroll', 1, true);`

**Comment by MrMooky** [comment]
Is there any update on this? Still seems to be an issue, at least for me. Settings `slidesToShow` to the same value as `slidesToScroll`, as mentioned before, is not really an option.

**Comment by Zaharoncik** [comment]
You can try to reconfigure this logic for your project and the buttons will work.
            setTimeout(() => {
            const $selected = $('#category_carousel').find('[data-category-id]');
            if ($selected.length) {
                const index = $selected.closest('.slick-slide').data('slick-index');
                if (index !== undefined) {
                    $('#category_carousel').slick('slickGoTo', parseInt(index));
                }
            }
        }, 300);
