### ISSUE TITLE
Hide slide while loading the page

### ISSUE THREAD

**Issue by ChristianoBourguignon** [kenwheeler/slick#4038]
When I use the slider, it shows all the divs created, then it hides them, but this affects performance and besides being considered ugly, I wanted to know how to solve this, but without using "opacity", because it is still there, affecting and giving an amazing space in the items, I wanted something with "display: none", but any help is welcome!

Thank you very much for your attention.

Best regards,
Christiano Bourguignon.

**Comment by nanna-dk** [comment]
@ChristianoBourguignon 
Solve it with this css:

```
.slick-slider {
  visibility: hidden;
}

.slick-slider.slick-initialized {
  visibility: visible;
}
```

**Comment by ChristianoBourguignon** [comment]
Solved:
`
.carousel.slick-initialized{
	visibility:visible;
	opacity:1;
}

.carousel .slick-slider{
	display:none ;
}

.carousel .slick-slider:first-child{
	display:block; visibility:hidden;
} 

.carousel.slick-initialized .slick-slider{
	display:block;visibility:visible!important;
}
`
