### ISSUE TITLE
Cannot scroll vertical on chrome on android

### ISSUE THREAD

**Issue by fnordian** [kenwheeler/slick#406]
My horizontal carousel doesn't allow me to scroll the page vertically when I try to scroll the page touching on the carousel.

**Comment by garettschultz** [comment]
removing touch-action: none did not work for me. I can't figure out why I cant scroll past the slider on mobile devices. My console doesnt throw any errors or anything. Really weird behavior.

**Comment by trotibal** [comment]
adding on img {
z-index:-1;
position:relative;
}
worked for me.
