### ISSUE TITLE
blur elements on swipe

### ISSUE THREAD

**Issue by ThisIshc** [kenwheeler/slick#4062]
When you swipe, a blur effect occurs, which distorts the image. Caught this bug while animating. It can be seen on the demo page

**Comment by speeday** [comment]
Hi @ThisIshc,

It would be good if you could share an some code via CODEPEN, or else to understand it in details.

**Comment by hkaraoglu** [comment]
@speeday you can view live example below website. When you swipe it, the texts and photos have a blur effect for a while.

https://jetklinik.com

**Comment by hkaraoglu** [comment]
I found a solution. If I disable **useTransform** property, it is solved.

`useTransform: false`

**Comment by ThisIshc** [comment]
yep, thanks
