### ISSUE TITLE
Prevent request for additional files (images and fonts)

### ISSUE THREAD

**Issue by cmalven** [kenwheeler/slick#410]
I'm using Slick.js in a situation where it is difficult to place the following files where Slick can find them:
- ajax-loader.gif
- /fonts/slick.woff
- /fonts/slick.ttf
- /fonts/slick.svg

I have no use for these files (they aren't being used in my slider), so I'd prefer to tell Slick to not try to load them. 2nd best option would be to tell Slick specifically where to find them so I can place them in a custom folder.

Is there a way to do either of these things?

**Comment by MelchnerRoman** [comment]
or simply don't load slick-theme.css and write your own template

**Comment by cmalven** [comment]
I understand the desire to not have to do the extra work to accomodate this, but wanting the core functionality of slick without the specific design choices of slick is a very real use case. In fact, it's the _only_ use case for me and slick. Functionality and style are two separate concerns, and I'd prefer to not have to duplicate dozens of lines of CSS just to eliminate the default styles while preserving the functionality.
