### ISSUE TITLE
Accessing Current Slide Attributes in onAfterChange

### ISSUE THREAD

**Issue by EnigmaSolved** [kenwheeler/slick#411]
I feel like I'm overlooking something obvious here.  I'm successfully using `onAfterChange` for a few things, but I can't seem to access the attributes of the current slide in this context.  I've tried things like:

```
console.log( $(this).attr('id') );
console.log( $(slide).attr('id') );
```

But both report `undefined`, even though the slides (ie, the elements with the class `slick-slide`) _do_ have `id`'s.

Any help on what I'm missing would be greatly appreciated!  :)

Thanks!

**Comment by heytomsmith** [comment]
Hey Ken,

After the 1.4 update this no longer works. 
How would I get data attributes from current slide now? 
```javascript
$('#carousel').on('afterChange', function (event, slick, currentSlide, nextSlide) {
	console.log($(slide.$slides.get(index)).attr('id'));
});
// ReferenceError: slide is not defined

**Comment by ujwaldhakal** [comment]
$('#carousel').on('beforeChange', function (event, slick, currentSlide, nextSlide) {
    console.log($(slide.$slides.get(index)).attr('id'));
});

on afterchange has another slide param like 

onAfterChange: function(slide, index){
  console.log( $(this).attr('id') ); 
  console.log( $(slide).attr('id') );
}

**Comment by vinamrajais** [comment]
What is $slides here?

I used $("[data-slick-index='" +currentSlide+ "']").attr('id') to get the current Slide

**Comment by cannect** [comment]
Hi @vinamrajais,

`$slides` is an internal slick variable. You can acces it when using the `slick` variable that is supplied in the `on('beforeChange'` function.

**Comment by chronon** [comment]
This works with v1.5.x:

``` js
$('#carousel').on('afterChange', function(event, slick, currentSlide, nextSlide){
  console.log($(slick.$slides.get(currentSlide)).attr('id'));
});
```

**Comment by nixon1333** [comment]
Try this  

`console.log($('.slick-slide.slick-current.slick-active').attr('id'));`

**Comment by spideep** [comment]
@nixon1333 
.attr('data-slick-index')
worked in my case.

**Comment by arrancscott** [comment]
I have an issue whereas every time I remove an image with slickRemove it sets .slick-current back to being the first slide in the slideshow.

eg. If i'm on the 5th image and I call slickRemove with the slide index I'd expect the slick-current class to be applied to the next/previous slide - instead it gets applied to the first element.

Does anyone know why this is happening or if it's something I'm doing wrong?

Here is the code I'm using it init 
```
$('.slideshow').slick({
 dots: true,
 infinite: true,
 speed: 500,
 fade: true,
 cssEase: 'linear',
 adaptiveHeight: true,
 mobileFirst: true
});
```

**Comment by lkrids** [comment]
slick.$slides.eq(nextSlide)

jQuery : eq() vs get() -- http://stackoverflow.com/a/4709685/4698437
