### ISSUE TITLE
varient image for shopify 

### ISSUE THREAD

**Issue by devgene** [kenwheeler/slick#4114]
> short description of the bug / issue, provide more detail below.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  https://stackoverflow.com/questions/68019939/how-to-make-slider-with-variants-for-the-product-page-in-shopify
2. ...  above link is the issue am facing in shopify

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by tonyfelice** [comment]
@devgene I recommend you stick with your post on SO and delete this. Your issue has nothing to do with slick slider. Your issue is a shopify-specific knowledge gap.
