### ISSUE TITLE
Divi slick is not a function

### ISSUE THREAD

**Issue by Kazumash123** [kenwheeler/slick#4131]
> short description of the bug / issue, provide more detail below.
been trying to fix my problem with slick slider. I've been getting this error pop up after new update with divi so I dont know if its with them or the slider. Had a look online and tried pretty much everything, if anyone else has experienced this before and has a fix would love some help. Thanks

====================================================================

###### `[  paste your jsfiddle link here  ]`  

https://jsfiddle.net/kcova97y/2/

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  
![image](https://user-images.githubusercontent.com/89426324/130530054-9fd324b9-ad26-48ba-8325-63a2c34185f8.png)

====================================================================

#### What is observed behaviour?

...  
![image](https://user-images.githubusercontent.com/89426324/130530130-77b53b49-d330-409b-a797-9b4ae599bc33.png)
goes straight down

====================================================================

#### More Details

- Which browsers/versions does it happen on? 
- all
- Which jQuery/Slick version are you using? 
- jquery 3.6.0, slick 1.8.1
- Did this work before? 
- yes before the new divi update

**Comment by bookswarm** [comment]
We have suddenly started experiencing the same issue on a Divi site.

**Comment by Kazumash123** [comment]
Issue got resolved. Divi Support was able to get back to me with this:

Please disable "Defer jQuery And jQuery Migrate" in Divi > Theme options > Performance.
![image](https://user-images.githubusercontent.com/89426324/130697137-83544139-eb95-4fdd-ab2d-9675b254e779.png)

**Comment by bookswarm** [comment]
Thank you for the fix. I had never seen the Divi > Theme options > Performance tab before!

That worked a treat :)
