### ISSUE TITLE
Fill Rows Then Columns

### ISSUE THREAD

**Issue by shahidbahader** [kenwheeler/slick#4150]
> Slides always fill columns before rows

====================================================================

Is there a way we can set it to fill rows before columns?

If we have set the rows: to 2

and the slidesToShow is 3

Then it is always displaying like this

1     3     5
2     4     6

Is there a way we can display it like

1     2     3
4     5     6

====================================================================

**Comment by joshmoto** [comment]
Remove `slidesToShow: 3` setting.

And use `slidesPerRow: 3` setting instead 👍🏻

See working example here... [https://jsfiddle.net/joshmoto/xvs87qm3/1/](https://jsfiddle.net/joshmoto/xvs87qm3/1/
)

Which outputs...

1 2 3
4 5 6

**Comment by shahidbahader** [comment]
Thanks that worked for me.
