### ISSUE TITLE
additional <div></div> inside class will break

### ISSUE THREAD

**Issue by erwinagpasa** [kenwheeler/slick#4165]
Adding another div inside myclass will break the slider

< div class="myclass">
**< div id="newClass">**
  < div>< h3>1< /h3>< /div>
  < div>< h3>2< /h3>< /div>
  < div>< h3>3< /h3>< /div>
  < div>< h3>4< /h3>< /div>
  < div>< h3>5< /h3>< /div>
  < div>< h3>6< /h3>< /div>
**< /div>**
< /div>

**Comment by nickfmc** [comment]
Every element will become a slide unless you use the "slide" setting and tell it what to use.  You could probably use a :not but to keep it simple give your slide elements a class and use the slide setting to target those. should work

**Comment by erwinagpasa** [comment]
Any sample code? thanks

**Comment by nickfmc** [comment]
why do you need to Wrap all of the slides inside a wrapper though, there is probably a way to avoid that. but try this... I've never used it in this way, only when I wanted another div inside the slider wrapper but not as a slide.

```
< div class="myclass">
< div id="newClass">
< div class="slide-item">< h3>1< /h3>< /div>
< div class="slide-item">< h3>2< /h3>< /div>
< div class="slide-item">< h3>3< /h3>< /div>
< div class="slide-item">< h3>4< /h3>< /div>
< div class="slide-item">< h3>5< /h3>< /div>
< div class="slide-item">< h3>6< /h3>< /div>
< /div>
< /div>
```

```
$('.myclass').slick({
    slide: 'slide-item',
  });
```

**Comment by erwinagpasa** [comment]
Thanks
