### ISSUE TITLE
Slick Slider on Shopify Customize - Image Blocks Stacks Vertically Before Saving

### ISSUE THREAD

**Issue by vaishnavi-s2901** [kenwheeler/slick#4178]
I'm trying to create a slick slider for a shopify theme.. Slideshow where user can upload an image as a slide, those slides will work as blocks (basically slide's coding is in forloop) It works actually but whenever user adds a 2nd block and uploads image on it, the images stack and when its saved in customize after adding, its works normally then.. I tried alot of stuff here and it seems that jquery doesn't run when we add blocks, and when we save the theme, it refreshes the page so then that slick jquery works.. Now while I was researching, I found this article which I think might work, but idk where to apply this logic - https://shopify.dev/themes/architecture/sections/integrate-sections-with-the-theme-editor

shopify:section:load logic can work here I suppose, so anyone has any idea how to use this and where in section?

This entire article is best and the logic on it will definitely help me to make my theme more faster and reliable, so this is very important for me, but idk how all the events work here, I'm new to shopify and I definitely love it and wants this to work badly

**Comment by ahmadalfy** [comment]
I am not sure if that's an issue with Shopify or Slick.
