### ISSUE TITLE
swipeToSlide is ignored in vertical slider

### ISSUE THREAD

**Issue by nicetomytyuk** [kenwheeler/slick#4189]
> swipeToSlide is ignored in vertical slider.

====================================================================

###### [JSFiddle](https://jsfiddle.net/L8mn7wrj/)

====================================================================

#### Steps to reproduce the problem

1. Try to swipe to another slide in a different position than the next one (like from slide 1 to 4) 

====================================================================

#### What is the expected behaviour?

Slide to be selected in swiped position  

====================================================================

#### What is observed behaviour?

The slide selects the next slide even if it's slided to another one

====================================================================

**Comment by ahmadalfy** [comment]
@nicetomytyuk can you check if the solution mentioned [here](https://github.com/kenwheeler/slick/issues/1962#issuecomment-256295335) solves your problem?
