### ISSUE TITLE
Show portion of image on first slide

### ISSUE THREAD

**Issue by JChinchillaBluedgeusa** [kenwheeler/slick#4190]
Is it possible to have the slider show 25% of each slide and slide through 25% of the images as you slide? I know we can do 1.25 slides shown, but I would like to show less than a full slide

**Comment by ahmadalfy** [comment]
Yes this can  be done. You can set the `slidesToShow` and `slidesToScroll` to `0.25` and the 

```javascript
$(".slider").slick({
    slidesToShow: 0.25,
    slidesToScroll:  0.25,
});
```

http://jsfiddle.net/z8s9yax4/1/
