### ISSUE TITLE
how to deactivate lazyload as user?

### ISSUE THREAD

**Issue by maia** [kenwheeler/slick#4194]
I'm frequently reading a website that uses layzyload. Unfortunately I find it highly annoying when scrolling through the articles. Is there any way to inject a few lines of js or css in the browser instance to alter/deactivate lazyload on this page? Thanks.

**Comment by ahmadalfy** [comment]
Lazy loading isn't set to `true` by default on slick.

**Comment by maia** [comment]
@ahmadalfy That's possible, but the question remains if a user can deactivate it on a website that has lazyload activated.

**Comment by maia** [comment]
@ahmadalfy I frequently read articles on https://www.advisorperspectives.com and unfortunately they split their articles (and the included images) in tiny sections that are lazy loaded. When scrolling through an article one frequently has to wait for the next section to load – and as the images only load then too, the layout jumps each time the image is completely loaded and the browser knows its size. I do understand the benefits of slick, but sometimes it would be a great help if one could tell a website not to lazy load as it just makes reading a pain. And unfortunately the websites that are broken most are usually the ones with the least tech-savvy team, so one can only wait until the next big site relaunch in a few years. Therefor I was asking if I could keep a js/css in my browser that would disable lazyload for this website. Thanks.

**Comment by ahmadalfy** [comment]
No you can't do that unless you use a browser extension that can override their code. You will need to reverse engineer what they're doing and use your replacement. A lot of effort for reading honestly.

**Comment by maia** [comment]
Thanks, that's what I'm asking for: with which css class or js code could I replace/deactivate lazyload? I'm familiar with browser extensions to inject code, I just cannot find a way to tell the browser to ignore lazyload as the slick-code is too complex for me to understand. Thanks!
