### ISSUE TITLE
Using adaptiveHeight, Slick is incorrectly calculating the height of a slide the first time it is displayed.

### ISSUE THREAD

**Issue by stevenpaulr** [kenwheeler/slick#4197]
This is happening on our website: [https://vertoeducation.org/careers/](https://vertoeducation.org/careers/)

There's a slick slider with testimonials part way down the page. The testimonials are different heights, but the first time it displays them, it doesn't always calculate the height right. Once you cycle through them all, it's fine, or if you go back to one that just got cut off, then it's fine.

I'm wondering if the problem is that I have 2 divs within the slick-slide. Do I need to encapsulate them in another div?

**Comment by stevenpaulr** [comment]
Solved my problem. It had to do with lazy loaded images. I encapsulated the image in a div and gave it the dimensions of the image so that the rest of the content would leave space for the image before it loaded.

**Comment by DinhThienPhuc** [comment]
Hello @stevenpaulr,

I believe I might be experiencing the same issue as you. Could you kindly provide more details on how you resolved it? I would greatly appreciate your assistance.

Thank you!
