### ISSUE TITLE
Checkout icon not changing color

### ISSUE THREAD

**Issue by WinstonHenry05** [kenwheeler/slick#4298]
> short description of the bug / issue, provide more detail below.

checkout cart icon is not changing color, despite everything is black. How can this be? Hope it can be fixed.

**Comment by markvantilburg** [comment]
@ahmadalfy This does not look to be related to slick

**Comment by ahmadalfy** [comment]
@WinstonHenry05 can you provide a reproducible example or a demo?

**Comment by WinstonHenry05** [comment]
Hello,
I dont need help anymore, the problem is already fixed.

Op wo 28 aug 2024 om 12:57 schreef Ahmad Alfy ***@***.***>:
