### ISSUE TITLE
Is there a way to add hash url navigation for each slide?

### ISSUE THREAD

**Issue by imohkay** [kenwheeler/slick#432]
A client has requested this for a project and I'm wondering if slick supports this?

**Comment by ThekhoN** [comment]
Has this been implemented?

**Comment by laudanju** [comment]
Any update?
I've tried multiple variants, and this one works fine in plain HTML, but I can't get it running in TYPO3, even with realURL hashing disabled.

`
	// simulate a "window.location.search" string.
	
   var testurl = "?slick0=2&slick1=3";

$(".slick-slider").each(function(k, v){
            
    var search = window.location.search || testurl,
        $slider = $(this),
        queries = search.slice(1).split("&"),
        checkQuery, initialSlide = 0;
    
    for( var query in queries ) {
        checkQuery = queries[query].split("=");
        if( checkQuery[0] === "slick"+k ) {
            initialSlide = parseInt(checkQuery[1],10);
        }
    }

    $slider.slick({
        initialSlide: initialSlide
    });

});`

**Comment by baffleinc** [comment]
+1

**Comment by markmakes** [comment]
+1

**Comment by shikkaba** [comment]
+1

**Comment by rathorevaibhav** [comment]
+1

**Comment by leviatorkilsheyggi** [comment]
+1
