### ISSUE TITLE
Vertical scrolling on Chrome Android is stopped when I encounter the slider.

### ISSUE THREAD

**Issue by ahmadalfy** [kenwheeler/slick#449]
This is a problem specific to Chrome Android. When vertically swipeing (aka scrolling) a webpage and reaching a slider using slick, the scrolling stop. Further attempt to swipe (over the slider) to move on fails.

Cannot confirm about native Android browser.

Working fine on Chrome iOS and Safari iOS.

**Comment by salazarparis** [comment]
Hi, I'm having the same Issue, 1.3.15 I have the touch-action: pan-y; and the vetical property in true, with touchmove: true, any idea?

URL: Factico.nextlab.org

**Comment by ISaindon** [comment]
Hi, I'm also having the same issue with version 1.3.15. New ideas?
Thanks

**Comment by ahmadalfy** [comment]
@ISaindon make sure you update all the CSS and the JavaScript files and that you are not including the old CSS files

**Comment by ISaindon** [comment]
Thank you...I downloaded the latest version 1.4.0 and it's working
perfectly well now.

**Comment by Kunamatata** [comment]
I am having this issue with version 1.5.7

**Comment by Rajgoud-225** [comment]
I'm not able to scroll the page in my moto xplay (6.0.1).. I've tried all the suggestion given by the pals above

**Comment by blicca** [comment]
Still there is not solution?

**Comment by jqlm** [comment]
I have same bug. Any ideas how to fix it?

**Comment by Kunamatata** [comment]
@blicca @jqlm the last release was on **Sep 12, 2017** version 1.8.0
I don't know the current state of this library but try with that newer version or find another library
