### ISSUE TITLE
Full Width Carousel Issue

### ISSUE THREAD

**Issue by nikosolihin** [kenwheeler/slick#452]
Ken,
Would you be able to give me some pointers as to why on 100% full-width the carousel is creating an extra right margin? Here's an example I did using the slick website. For some reason, ".slick-track"'s width is forcing that extra right margin to the parent container. I have also deleted the html nodes for the 2 buttons using dev tools, if that helps. Anything I am overlooking here?

![screen shot 2014-08-17 at 12 23 11 pm](https://cloud.githubusercontent.com/assets/4014965/3943854/a446cb4c-25ce-11e4-9f3f-53b7f29e3964.png)

**Comment by brainlulz** [comment]
@kenwheeler can you re-open this issue ? It seems not to be fixed.

**Comment by kukac7** [comment]
what is the problem with this?
[demo](http://jsfiddle.net/fmo50w7n/3971/)

**Comment by brainlulz** [comment]
This one look fine indeed. Got the same issue as this topic but had to fix it with an overflow hidden. Would be great if it wasn't overflowing by nature.

**Comment by kukac7** [comment]
@brainlulz bro, this is a 4 year issue. 😄 
please give me a demo link on the issue. thanks!
