### ISSUE TITLE
Autoplay once all images are loaded

### ISSUE THREAD

**Issue by texelate** [kenwheeler/slick#473]
Without waiting for the window to be loaded is there a setting (or could there be) that makes autoPlay kick in only once all slides have loaded?

I'm guessing you could call slickPlay() in $(window).load(function() { }); but wondered whether there was an easier way.

onInit doesn't wait until all slides and images are loaded, does it?

This works, just wondered if there was a simpler way.

``` javascript
/**
 * Slick fade galleries
 */
var $fade = $('.fade').slick({

    dots:          true,
    infinite:      false,
    speed:         500,
    fade:          true,
    easing:        'linear',
    autoplay:      false,
    autoplaySpeed: 4000

});


/**
 * Slick auto play
 */
$(window).on('load', function() {

    $fade.slickPlay();

});
```

Thanks.

**Comment by jan1980** [comment]
Are there any news on this super interesting feature request?

**Comment by nominalaeon** [comment]
This would be some heavy lifting for Slick, but there is another plug-in you should totally use and it's called [ImagesLoaded](http://imagesloaded.desandro.com/)

> It's all like "You images done yet or what?"

<pre>
$(window).imagesLoaded(function () {
    $('.slick-frame').slick();
});
</pre>

Use this instead of onload, it specifically forces the callback to wait for the images to all load up, which is very important for Slick to be able to do its thing with image-heavy slides.

**Comment by jan1980** [comment]
Excellent thanks! :thumbsup:

**Comment by jan1980** [comment]
Can imagesLoaded be combined with lazyload:ondemand? Looks like lazyload loses its purpose with imagesLoaded, because the script will wait for all the images to have been downloaded... Didn't test it still but it looks like.

**Comment by nominalaeon** [comment]
I've never used lazyload so I can't speak to that. But yeah in the context of giving a callback for when images are finished loading, imagesLoaded would take over that role. Lazyload probably gives other functionality that could still be utilized or something. 

But like if you're using it to load an image when the slide is visible or something? Slick won't work with that, Slick has to make its slide container sizes based on the elements inside of it, so if the image isn't loaded and there aren't hard-css'ed widths and heights established then I would expect the slides to be sized incorrectly.
