### ISSUE TITLE
.slickGoTo() not working when using two synced sliders

### ISSUE THREAD

**Issue by HaraldWalker** [kenwheeler/slick#474]
When using two sliders as in the demo with one slider as nav for the other one, slickGoTo() method doesn't work. The sync between both slides seem to cause a recursion. 

Workaround: 
Disable sync in one direction before using slickGoTo and afterwards add it again.

``` javascript
$('#result-nav').slickSetOption('asNavFor','', false);
$('#result-for').slickGoTo(index);
$('#result-nav').slickSetOption('asNavFor','#result-for', false);
```

**Comment by vipul-bhavsar** [comment]
This issue is reopen in 1.5.8? because i am using asNavFor my nav and slider combination. i want to explicitly move slide to other one so $(".slider").slick("slickGoTo", 3); works perfectly for content slider and not for navigation one.. please help
