### ISSUE TITLE
.asNavFor doesn't allow choosing slide by clicking the thumbnail

### ISSUE THREAD

**Issue by DjebbZ** [kenwheeler/slick#475]
Hi, I'm using slick like the demo where one slider controls the other. When I use the arrows to navigate, everything works fine. But when I click on small slide nothing happens. Tried with the latest slick, on Chrome and Firefox and with both jQuery latest 1.7 and latest 2.1.1. Didn't investigate the code though.

**Comment by RobErskine** [comment]
I know this is super old, but it looks like you were looking for `focusOnSelect: true` on the controls, as referenced in [#517](https://github.com/kenwheeler/slick/pull/517).

**Comment by gavin310** [comment]
For me `focusOnSelect: true` stops working after interacting with the arrows.
