### ISSUE TITLE
Slider not laying out correctly when vertical option is in the responsive settings

### ISSUE THREAD

**Issue by joebeaver89** [kenwheeler/slick#478]
Hopefully that makes sense, here are my slick options:

```
eventsSlickOptions = {
    slidesToShow: 4,
    slidesToScroll: 4,
    infinite: false,
    vertical: false,
    responsive: [
        {
            breakpoint: 880,
            settings: {
                slidesToShow: 3,
                slidesToScroll: 3,
                infinite: false,
                vertical: false
            }
        },
        {
            breakpoint: 670,
            settings: {
                slidesToShow: 3,
                slidesToScroll: 3,
                infinite: false,
                vertical: true
            }
        },
        {
            breakpoint: 500,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 2,
                infinite: false,
                vertical: true
            }
        }
    ]
};
```

Whenever I load the page, the slider is laid out as it should be, but when I resize, things like this happen:

Resize down from full width to smaller width:
![image](https://cloud.githubusercontent.com/assets/2727898/4064962/7e92556a-2e16-11e4-86ed-664f40128554.png)
Which should look like: 
![image](https://cloud.githubusercontent.com/assets/2727898/4064969/94743d4e-2e16-11e4-8afc-fc505204418e.png)

Resize up from small width to full width:
![image](https://cloud.githubusercontent.com/assets/2727898/4064978/a5fd24a4-2e16-11e4-9e13-f452ab7e00a5.png)
Which should look like:
![image](https://cloud.githubusercontent.com/assets/2727898/4064983/b13eb99a-2e16-11e4-8ff7-f36c0852d0c3.png)

Hope this makes sense and hope you can help! Thanks

**Comment by malkyg** [comment]
Hi,
I have the same problem
I am trying to change the vertical option value on a breakpoint, and not switching as should.
how do i fix?
thanks

**Comment by aaronblenkush** [comment]
@malkyg, it looks like @kenwheeler fixed it by essentially overriding the `width` that is set by the library.
```
/* http://jsfiddle.net/qng6p08y/ */
.test {
    max-width: 400px;
    min-width: 400px;
}
```

This is what ended up working in my case:
```
@media (min-width: 640px) {
    .my-slider .slick-slide {
        width:inherit !important;
    }
}
```
