### ISSUE TITLE
How to set different widths on the center mode to my slides?

### ISSUE THREAD

**Issue by sulzbacher** [kenwheeler/slick#481]
I have a ul with a lot of li's, each one of my li's have a text, and anyone of the text's have the same size...
I want to use the center mode, so when my li is in the center of the carousel, the font-size increases, and then, at present, it gets serious...

The li still have the same width that had on the start, and overlap the others around them...

**Comment by majidzeno** [comment]
.slick-current{
    transform: scale(1.5); 
}
P.S: you can change the ratio based on your design, and you have to re-allocate arrows - in case you made them activated.

**Comment by jjsanz** [comment]
Scale doesn't always work, some designs show expanded content in centered slide.
