### ISSUE TITLE
RTL mode breaks the carousel

### ISSUE THREAD

**Issue by ghost** [kenwheeler/slick#483]
I don't have a live link to my project, but If you go to Slick's homepage, and inject 'dir="rtl" into the HTML tag using the dev tools in Chrome you'll see the issue.

The carousel doesn't work when the transition is set to 'fade' and RTL is enabled. It displays the first slide but the rest is just empty.

**Comment by stmalk** [comment]
What do you mean by "explicitly use the rtl mode option in the settings"? Setting it to rtl:true doesn't fix an issue. Are there any other settings somewhere?
