### ISSUE TITLE
-webkit-backface-visibility: hidden;  causes very visible white when scrolling up and down page on Chrome.

### ISSUE THREAD

**Issue by Smashman** [kenwheeler/slick#49]
I hope this is understandable.

It appears that the css property >-webkit-backface-visibility: hidden; causes issues on Chrome, making it so when you scroll and a carousel comes into view, the entire area flashes white.

See: http://smash.mn for my live example.

**Comment by ohabash** [comment]
what selector?
@Smashman

**Comment by Smashman** [comment]
I'm afraid that this issue is 4 years old and I have no memory of it.

I believe that @kenwheeler fixed it a while ago.
