### ISSUE TITLE
Pause on hover not working if hovering while animation is running

### ISSUE THREAD

**Issue by giladNG** [kenwheeler/slick#500]
In demo page : autoplay demo.
hover on the slides after animation is stop, and it is working well.
Try to hover on the slides while the animation is running, and the pause is not working.
Checked in chrome , FF , IE
Thanks.

**Comment by macclinson** [comment]
In case someone out there still needs help on this issue, I fixed mine by using the following settings:

				  speed: 750,
				  autoplay: true,
				  infinite: true,
				  autoplaySpeed: 0,
				  cssEase: 'linear',
				  slidesToShow: 4,
				  slidesToScroll: 0.1,
				  pauseOnHover: true,

**Comment by zotherstupidguy** [comment]
I'm still experiancing that issue

`
  slider.slick({
      arrows: false,
      dots: true,
      speed: 300,
      fade: false,
      lazyLoad: 'ondemand',

      centerMode: false,
      infinite: false, 

      slidesToShow: 3,
      slidesToScroll: 3,

      autoplay: true,
      //autoplay: false,
      autoplaySpeed: 8000,
      pauseOnHover: true,                                                                                                                                              

      accessibility: true,
      cssEase: 'linear',

      swipe: true,
      swipeToSlide: true,
      touchMove:true

    });
`

**Comment by rajanizwt** [comment]
> In case someone out there still needs help on this issue, I fixed mine by using the following settings:
> 
> ```
>               speed: 750,
>               autoplay: true,
>               infinite: true,
>               autoplaySpeed: 0,
>               cssEase: 'linear',
>               slidesToShow: 4,
>               slidesToScroll: 0.1,
>               pauseOnHover: true,
> ```
> It makes it scroll smoothly and continuously and then pauses on hover

I'm still experiancing that issue

**Comment by ohid** [comment]
> > In case someone out there still needs help on this issue, I fixed mine by using the following settings:
> > ```
> >               speed: 750,
> >               autoplay: true,
> >               infinite: true,
> >               autoplaySpeed: 0,
> >               cssEase: 'linear',
> >               slidesToShow: 4,
> >               slidesToScroll: 0.1,
> >               pauseOnHover: true,
> > ```
> > It makes it scroll smoothly and continuously and then pauses on hover
> 
> I'm still experiancing that issue

you save my day

**Comment by nolyboms** [comment]
Thanks @rajanizwt 

For a slower version i am using this:

`speed: 1500,
        autoplay: true,
        infinite: true,
        autoplaySpeed: 0,
        cssEase: 'linear',
        slidesToShow: 2,
        slidesToScroll: 0.1,
        pauseOnHover: true,`

**Comment by agzwt** [comment]
I have the same issue on this : 

infinite: true,
        slidesToShow: 8,
        slidesToScroll: 1,
        speed: 4000,
        autoplay: true,
        autoplaySpeed: 0,
        centerMode: true,
        cssEase: 'linear',
        arrows: false,
        dots: false,
        rows: 0,
        draggable: false,
        swipe: false,
        swipeToSlide: false,
        pauseOnHover: true,
        variableWidth: true,
        slidesToScroll: 0.2

when I use pause On Hover slider take time to stop 

Any idea? Guys

**Comment by agzwt** [comment]
I have issues on my slider when I try to use draggable on my slick slider dots? 

Anyone Have a any idea about the customer draggable add on slick slider when I drag the scroll it's working with a slider ?

https://github.com/kenwheeler/slick/issues/2241

**Comment by lalitj** [comment]
Yes, it is also not pausing for me instantly. It takes few seconds to pause. 
Check fiddle: https://jsfiddle.net/29rz065e/

**Comment by phpony** [comment]
For anyone lurking the solution here is mine best-so-far approach:

```
var styleBackup = '', restOfTimeout = 500, currentState = '', freeze = false;
$('#slider').on('init', function(event, slick, direction){
  const observer = new MutationObserver(function(mutationsList, observer){
    for(const mutation of mutationsList) {
      if (mutation.type === 'attributes' &&  mutation.attributeName == 'style' && freeze) {
      	$('#slider .slick-track').css('transform', currentState);
      }
    }
  });
  observer.observe($('#slider .slick-track')[0], { attributes: true });
  $('#slider .slick-track').mouseover(function() {
    styleBackup = $('#slider .slick-track').attr('style');
    currentState = getComputedStyle($('#slider .slick-track')[0]).transform;
    freeze = true;        
    $('#slider').slick('slickPause');       
    let translateDone = parseFloat(currentState.split(',')[4])*(-1);            
    let regex = /translate3d\(([^,]*),/gm;
    if((m = regex.exec(styleBackup)) !== null) {
      let translateNeed = parseFloat(m[1])*(-1);
      let slideWidth = $('#slider .slick-slide').first().width();
      let speed = 5000/slideWidth;
      restOfTimeout = (translateNeed-translateDone)*speed;   
    } else {
      restOfTimeout = 500;
    } 
    $('#slider .slick-track').css('transform', currentState);        
  });    
  $('#slider .slick-track').mouseout(function() {     
    freeze = false;
    $('#slider .slick-track').attr('style', styleBackup.replace('5000ms', restOfTimeout+'ms'));
    $('#slider').slick('slickPlay');
  });
});

$('#slider').slick({
  slidesToShow: 4,    
  speed: 5000,
  autoplay: true,
  infinite: true,
  autoplaySpeed: 0,
  cssEase: 'linear',
  slidesToScroll: 1,    
  pauseOnHover: false
});
```

This way slider slowly scrolls 4 slides with 5000ms/step speed, and instantly freezes on mouse hover. On mouse leave it continues to scroll.

Example: https://jsfiddle.net/nhou7ma9/

**Comment by kushchaubey** [comment]
> For anyone lurking the solution here is mine best-so-far approach:
> 
> ```
> var styleBackup = '', restOfTimeout = 500, currentState = '', freeze = false;
> $('#slider').on('init', function(event, slick, direction){
>   const observer = new MutationObserver(function(mutationsList, observer){
>     for(const mutation of mutationsList) {
>       if (mutation.type === 'attributes' &&  mutation.attributeName == 'style' && freeze) {
>       	$('#slider .slick-track').css('transform', currentState);
>       }
>     }
>   });
>   observer.observe($('#slider .slick-track')[0], { attributes: true });
>   $('#slider .slick-track').mouseover(function() {
>     styleBackup = $('#slider .slick-track').attr('style');
>     currentState = getComputedStyle($('#slider .slick-track')[0]).transform;
>     freeze = true;        
>     $('#slider').slick('slickPause');       
>     let translateDone = parseFloat(currentState.split(',')[4])*(-1);            
>     let regex = /translate3d\(([^,]*),/gm;
>     if((m = regex.exec(styleBackup)) !== null) {
>       let translateNeed = parseFloat(m[1])*(-1);
>       let slideWidth = $('#slider .slick-slide').first().width();
>       let speed = 5000/slideWidth;
>       restOfTimeout = (translateNeed-translateDone)*speed;   
>     } else {
>       restOfTimeout = 500;
>     } 
>     $('#slider .slick-track').css('transform', currentState);        
>   });    
>   $('#slider .slick-track').mouseout(function() {     
>     freeze = false;
>     $('#slider .slick-track').attr('style', styleBackup.replace('5000ms', restOfTimeout+'ms'));
>     $('#slider').slick('slickPlay');
>   });
> });
> 
> $('#slider').slick({
>   slidesToShow: 4,    
>   speed: 5000,
>   autoplay: true,
>   infinite: true,
>   autoplaySpeed: 0,
>   cssEase: 'linear',
>   slidesToScroll: 1,    
>   pauseOnHover: false
> });
> ```
> 
> This way slider slowly scrolls 4 slides with 5000ms/step speed, and instantly freezes on mouse hover. On mouse leave it continues to scroll.
> 
> Example: https://jsfiddle.net/nhou7ma9/

Hi But this lost the dragging option do you have anything for both drag option and pause on hover

**Comment by rifflock** [comment]
I tried using the `MutationObserver` approach, but it kills the buttons too, so it didn't work for our usecase.
I found a solution using CSS classes that does an immediate pause and causes no other issues (I haven't tried with drag, but it should work)

```javascript

    var $slider = $( '.collection');
    var CLASS_NAME = 'pause-state-class';

      $slider.mouseenter(function() { 
        var track = $slider.find('.slick-track')[0];
        var style = window.getComputedStyle(track);
        
        const matrix = style.transform || style.webkitTransform || style.mozTransform;
        const matrixValues = matrix.match(/matrix.*\((.+)\)/)[1].split(', ')
        var pauseClass = $(`
            <style id="${CLASS_NAME}">
                .${CLASS_NAME} {
                    transform: translate3d(${matrixValues[4]}px, 0px, 0px) !important;
                    transition: none !important;
                }
            </style>`);
        $(`html > head`).append(pauseClass);
        $slider.find('.slick-track').addClass(CLASS_NAME);
        $slider.slick('slickPause');
      }).mouseleave(function() {
        isSliderHover = false;
        $slider.find('.slick-track').removeClass(CLASS_NAME);
        $(`#${CLASS_NAME}`).remove();
        $slider.slick('slickPlay');
      });
    }
    
    $slider.on('click', (e) => {
      if (!isSliderInitialized) {
        return;
      }
      var className = e.target.className;
      var isPrev = className.includes('slick-prev');
      var isNext = className.includes('slick-next');
      if (!isPrev && !isNext) {
        return;
      }
      $slider.find('.slick-track').removeClass(CLASS_NAME);
      if (isPrev) {
        $slider.slick('slickPrev');
      } else if (isNext){
        $slider.slick('slickNext');
      }
    });
```

As long as the class is attached to the slider, no transitions will work, but once it is removed everything works as normal.
Slider directly modifies the `style` attribute, so even just overwriting the transition doesn't work, but using a class with the `!important` flag wins.

**Comment by webflowjvahle** [comment]
@rifflock 

> ```js
>     var $slider = $( '.collection');
>     var CLASS_NAME = 'pause-state-class';
> 
>       $slider.mouseenter(function() { 
>         var track = $slider.find('.slick-track')[0];
>         var style = window.getComputedStyle(track);
>         
>         const matrix = style.transform || style.webkitTransform || style.mozTransform;
>         const matrixValues = matrix.match(/matrix.*\((.+)\)/)[1].split(', ')
>         var pauseClass = $(`
>             <style id="${CLASS_NAME}">
>                 .${CLASS_NAME} {
>                     transform: translate3d(${matrixValues[4]}px, 0px, 0px) !important;
>                     transition: none !important;
>                 }
>             </style>`);
>         $(`html > head`).append(pauseClass);
>         $slider.find('.slick-track').addClass(CLASS_NAME);
>         $slider.slick('slickPause');
>       }).mouseleave(function() {
>         isSliderHover = false;
>         $slider.find('.slick-track').removeClass(CLASS_NAME);
>         $(`#${CLASS_NAME}`).remove();
>         $slider.slick('slickPlay');
>       });
>     }
>     
>     $slider.on('click', (e) => {
>       if (!isSliderInitialized) {
>         return;
>       }
>       var className = e.target.className;
>       var isPrev = className.includes('slick-prev');
>       var isNext = className.includes('slick-next');
>       if (!isPrev && !isNext) {
>         return;
>       }
>       $slider.find('.slick-track').removeClass(CLASS_NAME);
>       if (isPrev) {
>         $slider.slick('slickPrev');
>       } else if (isNext){
>         $slider.slick('slickNext');
>       }
>     });
> ```

@rifflock Any chance you could provide us with a codepen?

**Comment by Jdu278** [comment]
Anyone still having issues with this? Or found another approach to fix it?

**Comment by iamharshad** [comment]
I'm still having issue @Jdu278

**Comment by Pikamander2** [comment]
We were having an issue where we had two linked sliders and both were set to `pauseOnHover: true` but it wasn't working. The solution turned out to be that we had to set one of them to `autoplay: false` since it's impossible to hover over both at once and the one that wasn't being hovered over was forcing the other to autoplay even when it was being hovered over.
