### ISSUE TITLE
Feature request: Grid slider

### ISSUE THREAD

**Issue by mcummins** [kenwheeler/slick#514]
It would be great to be able to show a grid of slides.
e.g Rather than slidesToShow: 4, be able to show the current visible set as 2 x 2, etc.

**Comment by BjornP** [comment]
I would like this too. As @mcummins says, it get's a bit tricky when you want a different number of items per slide on desktop/tablet/mobile. Solved it for now using breakpoints.js and some wrapping/unwrapping + slick/unslick in jquery.

**Comment by splurtcake** [comment]
+1
