### ISSUE TITLE
Smooth continuous scrolling?

### ISSUE THREAD

**Issue by EricWarnke** [kenwheeler/slick#52]
Any plans to offer a smooth and continuous scrolling option? Sometimes one doesn't want an arrow for interaction, but just to have everything scroll by like a ticker tape.

**Comment by clintLandrum** [comment]
Has this feature been revisited at all? Is Smooth continuous scrolling available?

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/issues/1068

**Comment by BenCole** [comment]
Is it possible to use this with the RTL option?

**Comment by BenCole** [comment]
Yes you can! Set slidesToScroll to -1.

**Comment by skitson** [comment]
If you want to emulate a ticker you can do the following with the settings for example: dots: false, arrows: false, centerMode: true, slidesToShow: 1, centerPadding: '280px', autoplay: true, autoplaySpeed: 0, speed: 9000, cssEase: 'linear'

**Comment by gregzx** [comment]
The problem appears when the content inside your carousel is not of equal width. Than those continous scrolling hacks stop working.

**Comment by apmeyer** [comment]
Pinging this again, as it would be a great option.

**Comment by pi-mont** [comment]
Agreed, hacking this to work isn't a very good option.

**Comment by gina3five** [comment]
+1 for this feature

**Comment by koo04** [comment]
+1 Was just looking for this option.

**Comment by cloud-tribal** [comment]
+1

**Comment by salinasd** [comment]
+1

**Comment by JohnsonJPJ** [comment]
Would be a nice option +1

**Comment by dragosmocrii** [comment]
+1

**Comment by raducretu** [comment]
+1

**Comment by Panoply** [comment]
+1

**Comment by glebmachine** [comment]
+1

**Comment by effectjared** [comment]
+1

**Comment by imjoeybrennan** [comment]
+1 
Also Flickity does this. 
http://flickity.metafizzy.co/ 
See freeScroll

**Comment by slavajacobson** [comment]
+33

**Comment by brianecook** [comment]
Nice work @slavajacobson!!

**Comment by HowdyMcGee** [comment]
Would like to see this option added. The JSFiddles I've seen so far are not quite workable. Need "Pause on Hover" and "Infinite Continuous Looping".

+1

**Comment by hernimen** [comment]
+1

**Comment by hernimen** [comment]
@kenwheeler  Do it! plz

**Comment by ptrwllrd** [comment]
Adding my voice of support for this as well. Hope you consider this, Ken Senpai!

**Comment by benjamingordongit** [comment]
+1

**Comment by simonchelbc** [comment]
+1

**Comment by sakerrr** [comment]
+420 pls

**Comment by krisha23** [comment]
+1

**Comment by krisha23** [comment]
+1

**Comment by perara** [comment]
+1

**Comment by SafeCaches** [comment]
+1

**Comment by balintd** [comment]
+1

**Comment by seancrater** [comment]
+1

**Comment by nabettu** [comment]
+1

**Comment by wvdongen** [comment]
+1

**Comment by kotofenum** [comment]
+1

**Comment by charlienewman** [comment]
+1

**Comment by Morlik0** [comment]
+1 for marquee effect

**Comment by imonoid** [comment]
+1 for feature...

**Comment by sloyer** [comment]
https://codepen.io/michaelsmyth94/pen/wMJLaj

Works flawless

**Comment by balintd** [comment]
The only issue I see with that approach is that pause on hover is not working very well. If you hover over an element, the animation doesn't pause immediately. It's not one continuous scroll, technically it's still scrolling one slide at the time. If you hover over the slideshow, Slick is still finishing scrolling the current element, therefore in most cases there is a delay between hovering over the slideshow and the animation being paused.

**Comment by japick** [comment]
+1

**Comment by jvanoel** [comment]
+1

**Comment by FloSugar** [comment]
+1

**Comment by liquidvisual** [comment]
+1

**Comment by Mecadeca** [comment]
+1

**Comment by imiMike** [comment]
+1

**Comment by allonblack** [comment]
+1

**Comment by cwahlfeldt** [comment]
+1

**Comment by luuuuk** [comment]
+1

**Comment by vzaugg** [comment]
++1

**Comment by andyanderso** [comment]
+1

**Comment by tpwidman** [comment]
I have a slider that has some slides that are super long and some that are super short. I want to be able to set the transition speed on the fly by the width of the slide * 100 in milliseconds. The following code isn't working, but could you help point me in the right direction?
`		var speed = 10000;
		$(".scrolling").on('beforeChange', function(event, slick, currentSlide){
			var currentSlide = $('.scrolling').find('.slick-active');
			var currentSlidewidth = currentSlide.width()*100;
			$('.slick-track').css('transition', 'transform' + currentSlidewidth + 'ms linear');
			console.log(currentSlidewidth);
			/* var year = activeSlide.data('year'); */
		});
		$('.scrolling').slick({
			speed: speed,
			autoplay: true,
			autoplaySpeed: 0,
			cssEase: 'linear',
			slidesToShow: 1,
			slidesToScroll: 1,
			dots: false,
			arrows: false,
			variableWidth: true
	    });	`

**Comment by tpwidman** [comment]
I added a new parameter to the Slick options that allows for smooth scrolling for variable width slides:
https://github.com/kenwheeler/slick/issues/3234

**Comment by resting** [comment]
+1 for this feature

**Comment by itsems** [comment]
+1

**Comment by oguilleux** [comment]
+1

**Comment by followthemadhat** [comment]
+1 also would love to see immediate pause on hover feature

**Comment by roberrrt-s** [comment]
+1

**Comment by voodoo6** [comment]
+1

**Comment by lazydream** [comment]
+1

**Comment by XONOSNET** [comment]
+9999 Add if possible & implement pause animation on hover. I'm about to crack open the source to do this myself as I know projects like this require time from you which you may not have.

**Comment by roberrrt-s** [comment]
Smooth, continues autoscrolling with pause on hover:
https://github.com/metafizzy/flickity/issues/77

**Comment by architchandra** [comment]
> I think I'm going to pass on this enhancement for now.

Please see if this can be built. Would be really useful.

**Comment by matthew-b-shaw** [comment]
+1

**Comment by remytesta** [comment]
+1

**Comment by shamaleyte** [comment]
+1

**Comment by PrajwalVBharadwaj** [comment]
I see a lot of work around to achieve smooth continuous effect but it would be a great add on if it were to be supported directly. Please do consider.

**Comment by luaysuarna** [comment]
+1

**Comment by amoralesdesign** [comment]
+1

**Comment by emaildano** [comment]
Someone created a demo of this that works with the current version of Slick.

https://codepen.io/michaelsmyth94/pen/wMJLaj

**Comment by Alxzu** [comment]
+1

**Comment by oga-sven** [comment]
+1

**Comment by hasenov** [comment]
+1
