### ISSUE TITLE
Firing setPosition on window.onload

### ISSUE THREAD

**Issue by Torrejon** [kenwheeler/slick#521]
Version: 1.3.7
/*$(window).on('load.slick.slick-' + _.instanceUid, _.setPosition);*/
causes an error in JQuery (1.8) when resizing the browser manually.
Event is undefined
Traced to _setPosition using console.trace in JQuery where the error occurs.
Tested on FF 32.0.1

**Comment by kenwheeler** [comment]
Closing, let me know if this still happens in 1.3.15. It shouldn't
