### ISSUE TITLE
Want autoplay to play the slides once and stop

### ISSUE THREAD

**Issue by DennHRMC** [kenwheeler/slick#528]
We are plugging Slick into a Foundation site. We have the home page working with a slick slide show except for one thing we can not figure out. 

We have 5 slides. They progress from a ghosted version of the image fading in one by one to a full resolution of the image in all its detail. At that point we want the last image to stop and stay there. The mark up for the slider is:
```
<div class="slider fade">
			<div><div class="image"><img src="img/HomeSlides/home1-2k.jpg"/></div></div>
			<div><div class="image"><img src="img/HomeSlides/home2-2k.jpg"/></div></div>
			<div><div class="image"><img src="img/HomeSlides/home3-2k.jpg"/></div></div>
			<div><div class="image"><img src="img/HomeSlides/home4-2k.jpg"/></div></div>
			<div><div class="image"><img src="img/HomeSlides/home5-2k.jpg"/></div></div>
</div>
```
The code to implement is:
```
    <script type="text/javascript">
        $(document).ready(function(){
            $('.fade').slick({
                dots: false,
        infinite: false,
        speed: 300,
        fade: true,
        slide: 'div',
        cssEase: 'linear',
        autoplay: true,
        autoplaySpeed: 2000,
            });
        });
    </script>
```
We figured infinite: false would stop it. What ACTUALLY happens is the image fades in to full Slides 1-5) and then fades back out to ghosted (slides 5-1) continuously.

Am I missing something, misunderstanding something or is this not possible? Seems any autoplay should have a way to play once (or a specific number of times)

**Comment by kenwheeler** [comment]
I dont think this merits inclusion in core. I would listen for whether the last slide has been reached and then pause it

**Comment by rijosh** [comment]
try like this

var item_length = $('.slide > div').length - 1;
var slider = $('.slide').slick({
    autoplay: true,
    autoplaySpeed: 1000,
    dots: false,
    infinite: false,
    speed: 1000,
    fade: true,
    slide: 'div',
    cssEase: 'linear'
});

// On before slide change
slider.on('afterChange', function(event, slick, currentSlide, nextSlide){
	//check the length of total items in .slide container
  //if that number is the same with the number of the last slider
  //Then pause the slider
  if( item_length === slider.slick('slickCurrentSlide') ){
    //this should do the same thing -> slider.slickPause();
    slider.slickSetOption("autoplay",false,false)
  };
});

[http://jsfiddle.net/7krdncy5/](http://jsfiddle.net/7krdncy5/)

**Comment by danyj** [comment]
this one pays attention to slidestoshow option 


	if( currentSlide === slick.$slides.length - slick.slickGetOption('slidesToShow')  ) {
		slick.slickPause();
	}

**Comment by salbaldovinos** [comment]
This really should be a core feature, IMO. infinite option, to me says it shouldn't loop anymore. Thank you @rijosh for the solution
