### ISSUE TITLE
Add BoxSlider's transition effects

### ISSUE THREAD

**Issue by X4** [kenwheeler/slick#54]
I've compared all available sliders on the github, jquery plugins and themeforest. Only very few are complete and usable and maintain clean code. Fotorama.io is one of those, but it also lacks at one point, just like Slick: Transition Effects.

I just point you to an awesome slider, which only lacks your features to be perfect, or vice versa. You can merge the effects of box-slider into Slick, if you want. It's written cleanly  and each effect is in it's separate file. Here's the source: https://github.com/p-m-p/jquery-box-slider

**Comment by cronfy** [comment]
@kenwheeler any news here? Is there any docs/demos about adding custom transitions defferent than default slide and fade? Something like [box-slider](http://philparsons.co.uk/demos/box-slider)'s 2d-tiles or blind-left?

**Comment by abdhannan** [comment]
yup, I need it, finally, i integrated with this plugin: https://github.com/marvinhuebner/slick-animation

But, there is some issue, I just need to add transition to slider effect (not to fade)

**Comment by cronfy** [comment]
@abdhannan can't see how slick-animation can provide anything like [box-slider](http://philparsons.co.uk/demos/box-slider)'s 2d-tiles or blind-left...
