### ISSUE TITLE
Update documentation on slidesToScroll

### ISSUE THREAD

**Issue by SeabassNg** [kenwheeler/slick#541]
Apparently, if centerMode is set to true, slidesToScroll is set to 1. Either fix it so that centerMode does not affect slidesToScroll or update the documentation, so I don't need to dig through the code to figure it out.

**Comment by alfechner** [comment]
+1 for your change @eschow . Works for my set even with some breakpoints in it. Though in current version of slick the part to adjust looks some different, I removed

````
        if (_.options.centerMode === true || _.options.swipeToSlide === true) {
            _.options.slidesToScroll = 1;
        }
````
on Line 494:496 in `slick/slick.js`. Maybe it helps someone else.
