### ISSUE TITLE
Unslick responsively

### ISSUE THREAD

**Issue by wldcordeiro** [kenwheeler/slick#542]
I have a slider with four elements, at a screen size greater than a certain breakpoint, I'd like to disable slick and use CSS to render them as a 2x2 block grid. Is there a way to do this, or can it be added so you can have something like

```js
$('.responsive').slick({
  dots: true,
  infinite: false,
  speed: 300,
  slidesToShow: 4,
  slidesToScroll: 4,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        unslick: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
  ]
});
```

**Comment by kenwheeler** [comment]
This is in 1.4

**Comment by Dechowmedia** [comment]
I hate to reopen this issue but I cannot get it to function properly.
Simply put slick does not unslick if i use ``` settings: 'unslick' ```

Here is the JS code:

```
$this.slick({
                    infinite: false,
                    speed: 300,
                    slidesToShow: 6,
                    slidesToScroll: 6,
                    responsive: [
                        {
                            breakpoint: 1024,
                            settings: "unslick"
                        },
                        {
                            breakpoint: 800,
                            settings: {
                                slidesToShow: 5,
                                slidesToScroll: 2,
                            }
                        }
                    ]
                });
```

**Comment by paulcripps** [comment]
I have the same issue as @Dechowmedia ideally I want to 'unslick' for smaller devices and switch it back on if the screen is larger (so tablet portrait = click off, tablet landscape = on).

      $('#wineSlider').slick({
			infinite: true,
			slidesToShow: 2,
			slidesToScroll: 1,
			prevArrow: $('.prevArrow'),
			nextArrow: $('.nextArrow'),
			responsive: [
				{
					breakpoint: 1280,
					settings: "slick"
				},
				{
					breakpoint: 800,
					settings: "unslick"
				}
				]
		});

**Comment by axebox** [comment]
How do you only apply slick to mobile friendly bp? And unslick for all bp above the mobile one?
```javascript
		var carouselopts = {
			responsive: [{
				breakpoint: 99999,
				settings: "unslick"
			},{
				breakpoint: 768,
				settings: {
					centerMode: true,
					centerPadding: '25%',
					arrows: false,
					infinite: false
				}
			}]
		};
```

This works, but in cases where the viewport is resized ABOVE the mobile bp it works, but when the viewport is resized DOWN to mobile slick does not initialize. I almost expect there to be an "initslick" setting, but the presumption is if 'unslick' is excluded that should be an init.

**Comment by ndimatteo** [comment]
Yea...

This doesn't work as intended. Once the slider is 'unslicked' it never gets reslicked when you go back down/up to a given breakpoint that isn't 'unslicked.'

@axebox a mobile-first apprach **should** work by combining this feature with the mobileFirst option.

Until @kenwheeler fixes the 'unslicked' option to work in general, this should work like a charm.

**Comment by kenwheeler** [comment]
It was never intended to reslick. In a 99% use case, your users aren't resizing, just landing on the page. Working on getting the reslick going though, for folks who play scratch DJ with the window resize (QA lol)

**Comment by cibgraphics** [comment]
I disagree @kenwheeler. A usecase could be that a slider could be working on an iPad portrait and the user turns ipad to landscape, and then back to portrait. If the breakpoint was between those two sizes the  slider would no longer be functioning when it should be.

**Comment by ndimatteo** [comment]
@cibgraphics good point.

I don't know what the best solution is here, as it seems to unslick/re-slick is a heavy task. I've found simply overriding the CSS at the desired breakpoint(s) to force it out of the slider layout seems to do the trick, but it might be nice to have that baked into slick. I'm sure there are also edge cases where there are some other things on the js side that should be disabled.

@kenwheeler what are your thoughts?

**Comment by kursez** [comment]
+1 @cibgraphics

**Comment by memoclic** [comment]
:+1:  for reslicking after unslick

**Comment by mathiouchio** [comment]
+1 bump request

**Comment by kenwheeler** [comment]
Alright, I'll figure this one out

**Comment by Valstorm** [comment]
Wow great to see you're actively supporting this so well Ken, came here for this exact feature, hotfix for today, I'll check back soon.

**Comment by memoclic** [comment]
Thanx ken :+1: u're a boss :)

**Comment by kenwheeler** [comment]
My original intention of unslick was to revert to a clean state, but if we want to reslick, as people clearly do, I'll have to create a global width watcher that will find unslicked elements and reslick them. I'll try and get this in before 2.0

**Comment by tammyhart** [comment]
Ken, thank you times a million for this!

**Comment by simeydotme** [comment]
@kenwheeler , if you haven't already headed down that avenue, I'll chime in that I'd prefer not to have those extra width-watchers especially because I'd be using `matchMedia` instead of resize events personally, so maybe they only remain in place to check for reslicking if a boolean flag "reslickable" or something equally awkward (haha) is set? :)

**Comment by kenwheeler** [comment]
@simeydotme I was thinking instead of extra, create one and have it talk to all the slicks on the page. Currently if you have 3 slicks, you have 3 resize event responders. Right?

**Comment by mathiouchio** [comment]
You da man. Thanks a bunch!

**Comment by simeydotme** [comment]
@kenwheeler ahah... pretty smart :)

**Comment by evromalarkey** [comment]
I just run into this issue and found an easy workaround, so if anyone needs to fix this now here is the code -

```javascript
    slick_slider();
    $(window).resize(slick_slider);


    function slick_slider() {
        var wrapper = $("#my_slider");
        if ($(".slick-initialized").length) {
            wrapper.slick('unslick');
        }
        wrapper.slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: true,
            arrows: true,
            responsive: [
                {
                    breakpoint: 960,
                    settings: "unslick"
                }
            ]
        });
    }
```

**Comment by JoranSchipper** [comment]
For those who are still having the issue, Here is what I used to make it work:

<pre>
    $('.slider').slick({
        mobileFirst: true,
        slidesToShow: 3,
        slidesToScroll: 1,
        responsive: [
            {
                breakpoint: 1024,
                settings: 'unslick'
            }
        ]
    });
</pre>

I set mobileFirst: true so the slider will only show on screens smaller than 1024px. This way, I think no workaround is needed :)

**Comment by ashussen** [comment]
My friend just found the solution for this after touching the library code
The function we all expected is  `_.unload();` but by default, unslick is calling `_.destroy();`

So the solution is by replacing the unslick function in *slick.js*

Find the unslick function and replace the function like this:
```javascript
    Slick.prototype.unslick = function(fromBreakpoint) {

        var _ = this;
        _.$slider.trigger('unslick', [_, fromBreakpoint]);
        //_.destroy();
        _.unload();

    };
```

**Comment by jdmagic21** [comment]
@evromalarkey I am having a hard time getting your solution to work because you have to have the slider initialized inside of window.ready. If you add your resize handler your code works the first time, however if you resize a second time it does not work with the breakpoint.

**Comment by jdmagic21** [comment]
@ashussen  But then you cannot use a CDN :)

**Comment by jdmagic21** [comment]
The only reason why I think you would use this is if you are using Bootstrap and you don't want the slider to show on mobile. I think it would make more sense to remove the Bootstrap styling, i.e. columns, and just use the Slick Slider with margins. This way you can just use the responsive settings without having to disable the slick slider. In more realistic terms, you could have more than ten items added and have the page become very long to scroll. If you know you are only going to 
u could have more than ten items added and have the page become very long to scroll. If you know you are only going to use a set number of items then yes unslick can be practicle otherwise this what is the point?

**Comment by jmarceli** [comment]
For me overwriting core file as @ashussen supposed was not an option. The only working solution is writing custom "reslicking" function:

      $slick_slider = $('.slider');
      settings = {
        // some settings
      }
      $slick_slider.slick(settings);

      // reslick only if it's not slick()
      $(window).on('resize', function() {
        if ($(window).width() < 768) {
          if ($slick_slider.hasClass('slick-initialized')) {
            $slick_slider.slick('unslick');
          }
          return
        }

        if (!$slick_slider.hasClass('slick-initialized')) {
          return $slick_slider.slick(settings);
        }
      });

**Comment by nilesh-patil-pune** [comment]
Onclick the scroll bar, I need to stop the automatic vertical and horizontal scroll.
That's why I am trying to use unslick(); but I am not able to get the handle of click.

Please let me know, if you anyone knows!
Thanks

**Comment by bengathard** [comment]
@jmarceli Your solution worked perfectly, and it was the simplest to implement. I have tried almost every other solution on this feed and few others. Thanks for posting, much appreciated.

**Comment by neptunus** [comment]
ashussen's fix did the trick for me. I couldn't get the other solutions to work. Using a CDN, I just redefined the function immediately after calling slick.js. Hope this helps anyone (since some people mentioned not being able to use this solution with a CDN).

```
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
<script>
Slick.prototype.unslick = function(fromBreakpoint) {
  var _ = this;
  _.$slider.trigger('unslick', [_, fromBreakpoint]);
  _.unload();
};
</script>
```

**Comment by MikeHarrison** [comment]
@jmarceli thanks for that solution, just implemented it and it's working great

**Comment by tmgale12** [comment]
@jmarceli solution works a charm, thanks

**Comment by nowcreatepixel** [comment]
@jmarceli fantastic - thank you

**Comment by drivebass** [comment]
Last night a dj @jmarceli saved my life!

**Comment by Garth619** [comment]
@jmarceli Worked great for me as well!

**Comment by matthewmcclatchie** [comment]
@jmarceli Great solution. Thanks!

**Comment by giovannipds** [comment]
@jmarceli's solution behavior should be included on the component. =)

**Comment by alanmarchman** [comment]
@evromalarkey's solution worked for me, and adding `mobileFirst: true` fires slick on mobile and removes it at larger viewports.
`slick_slider();
$(window).resize(slick_slider);


function slick_slider() {
    var wrapper = $(".chef-headshots");
    if ($(".slick-initialized").length) {
        wrapper.slick('unslick');
    }
    wrapper.slick({
        mobileFirst: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        responsive: [{
            breakpoint: 767,
            settings: "unslick"
        }]
    });
}`

**Comment by giovannipds** [comment]
@alanmarchman @evromalarkey's solution fires always, in any resize event. Checkout what @jmarceli proposed, it seems an approach a little better of it.

**Comment by artursopelnik** [comment]
+1

**Comment by MattPurland** [comment]
Would love to see this implemented properly, having Slick destroy itself on certain breakpoints but also reinitialise itself when going back on resize would solve so many problems I'm having. In my scenario I need a slider on mobile and a ticker-tape on anything above. As mentioned by @cibgraphics, iPad rotation is a perfect scenario. Using mobileFirst is a step in the right direction.

On another note, when unslicked, slides still have their inline styles. Would be nice if they were cleaned up nicely as it affects applying CSS when unslicked.

**Comment by bajkorenata** [comment]
I would also love to see this implemented properly, because unfortunately I couldn't implement @jmarceli 's solution, although everyone seemed to find it quite easy to deal with. If anyone could help me out, that would mean a lot!

**Comment by giovannipds** [comment]
@bajkorenata what's happening? I'll send you an email to get in touch.

**Comment by 4eshircat** [comment]
@alanmarchman works perfectly! Thanks!

**Comment by amakely-moxie** [comment]
"Unslicking" seems to cause rendering performance issues on iPads when multiple carousels are on the page.  Scrolling causes the browser to fail to render content, leaving blank space for several seconds.

**Comment by giovannipds** [comment]
@amakely-moxie did you test it how @jmarceli's proposed?
This is issue is closed and solved has two years.

**Comment by giovannipds** [comment]
@bajkorenata there you go: https://codepen.io/giovannipds/details/JLZYPE/
If someone else is not understanding what @jmarceli wrote, here's a live example of how to use it.

**Comment by amakely-moxie** [comment]
@giovannipds I looked at the example you just posted, and that made everything much clearer. Thank you. It works perfectly. I apologize for the confusion.

**Comment by ariefrizkyr** [comment]
I still can't get it to work. I tweak the code to integrate with enquire.js:

`enquire.register('(min-width: 24em) and (max-width: 47.99em)', {
    match: function() {
      $(".slick-mobile").slick ({
        arrows: false,
        dots: true,
        centerMode: true,
        centerPadding: '60px',
        slidesToShow: 1
      });
    }
  })
  .register('(min-width: 48em)', {
      match: function() {
        $(".slick-mobile").slick('unslick');
      }
  });`

I hope this will be useful

**Comment by giovannipds** [comment]
@Inovanet that doesn't make much sense... according to the documentation, `unslick` is meant for really unslicking and that's all. You should consider the approaches mentioned above.
If you do want that `unslick` respond to resizes, breakpoints and re-inits, there's probably better ways to implement it consider what we already know, probably not chaining events inside events. But that's just an opinion, ok?

**Comment by nickmeagher** [comment]
> For me overwriting core file as @ashussen supposed was not an option. The only working solution is writing custom "reslicking" function:
> 
> ```
>   $slick_slider = $('.slider');
>   settings = {
>     // some settings
>   }
>   $slick_slider.slick(settings);
> 
>   // reslick only if it's not slick()
>   $(window).on('resize', function() {
>     if ($(window).width() < 768) {
>       if ($slick_slider.hasClass('slick-initialized')) {
>         $slick_slider.slick('unslick');
>       }
>       return
>     }
> 
>     if (!$slick_slider.hasClass('slick-initialized')) {
>       return $slick_slider.slick(settings);
>     }
>   });
> ```

This worked for me! Thank you!

**Comment by dbleyenda** [comment]
I needed the opposite, make it only work on phone, but not on tablet or desktop. I took some code examples from the comments above.

```javascript
// Team Slider
var $team_slider = $('.team .slider')
var team_slider_settings = {
  autoplay: true,
  autoplaySpeed: 2000,
  dots: false,
  centerMode:true,
  centerPadding:'60px',
  infinite: true,
  slidesToShow: 2,
  speed: 300,
  responsive: [
    {
      breakpoint: 99999,
      settings: "unslick"
    },{
      breakpoint: 768,
      settings: {
        slidesToShow: 2,
      }
    },{
      breakpoint: 655,
      settings: {
        slidesToShow: 1,
        centerPadding:'120px',          
      }
    },{
      breakpoint: 500,
      settings: {
        slidesToShow: 1,
        centerPadding:'60px',          
      }
    },{
      breakpoint: 476,
      settings: {
        slidesToShow: 1,
        centerPadding:'30px',
      }
    }
  ]          
};

// Init Slider
$team_slider.slick(team_slider_settings);

// Reslick only if it's not slick()
$(window).on('resize', function() {
  if (!$team_slider.hasClass('slick-initialized')) {
    return $team_slider.slick(team_slider_settings);
  }
});
```

**Comment by BedroomDev** [comment]
I have a simple but different aproach here. 
instead of using `$(window).on('resize', function(){  })` to check if we hit our breakpoint, im using slicks breakpoint event.
So I added an "empty" breakpoint, just so the event gets triggered.

```
var slider_config = {
    .
    .
    .
      responsive: [ {  breakpoint: 1024  } ]
  };

```

which i then listen for 
```

$(slick_slider).on('breakpoint', function(event, slick, breakpoint) {
  
  //we hit the breakpoint
  //$slick.slick('unslick');

});
```

**Comment by noemi-mancini** [comment]
I tried to use the `breakpoint` event, but it fires only when the breakpoint is hit on window scale up. When scaling down, breakpoint is `null` so the event doesn't and slick is not initialized again.

**Comment by redmondchan** [comment]
How would one implement @jmarceli approach? Where would I put this code?

**Comment by Jupitercouple29** [comment]
I solved this. It works for me properly.

mostPopularProductsSlick();
  var $windowWidth = $(document).width();
  jQuery(window).resize(function(){
    if($('#Slideshow-collection-most-popular').length > 0){
      if ($windowWidth < 769) {
        $('#Slideshow-collection-most-popular').slick('resize');
      }
    } 
  });

  function mostPopularProductsSlick(){
    if($('#Slideshow-collection-most-popular').length == 0) return;
    var autoplay = $("#Slideshow-collection-most-popular").data("autoplay") || false;
    var arrows = $("#Slideshow-collection-most-popular").data("arrows") || false;
    var dots = $("#Slideshow-collection-most-popular").data("dots") || false;
    var speed = $("#Slideshow-collection-most-popular").data("speed") || false;

    $('#Slideshow-collection-most-popular').slick({
        autoplay: autoplay,
        autoplaySpeed: speed,
        infinite: true,
        arrows: arrows,
        dots: dots,
        variableWidth: true,
        slidesToShow: 3,
        slidesToScroll: 1,
        swipeToSlide: true,
        responsive: [
          {
              breakpoint: 9999,
              settings: "unslick"
          },
          {
            breakpoint: 769,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 1,
              mobileFirst:true
            }
          }
        ]
    });
  }

**Comment by dsg1-wolf** [comment]
> I solved this. It works for me properly.
> I'm sure this method will work without any issues.
> […] 
>           {
>             breakpoint: 769,
>             settings: {
>               slidesToShow: 3,
>               slidesToScroll: 1,
>               mobileFirst:true
>             }
>           }
>         ]
>     });
>   }

I'm curious. You've put the mobileFirst paramater into a breakpoint. Does this really work? I mean, I've always though of it as a rather global setting.
