### ISSUE TITLE
slider not funtion if SlidesToShow equal to sliders

### ISSUE THREAD

**Issue by celevra** [kenwheeler/slick#544]
if SlidesToShow is equal to num of Sliders it is not working

but i need it for the Nav Slider

```
    $('.slider').slick({
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        asNavFor: '.slider-nav',
        draggable: mobile
    });

    $('.slider-nav').slick({
        slidesToShow: 3,
        slidesToScroll: 1,
        dots: true,
        centerMode: true,
        focusOnSelect: true,
        arrows: false,
        asNavFor: '.slider'
    });

        <div class="slider-nav">
            <div><span class="menu-entry">1</span></div>
            <div><span class="menu-entry">2</span></div>
            <div><span class="menu-entry">3</span></div>
        </div>

        <div class="slider">
            <div>1</div>
            <div>2</div>
            <div>3</div>
        </div>
```

**Comment by Malin88** [comment]
issue form first post returns in version 1.5.8 :/

**Comment by cihakmar** [comment]
Any progress with this bug in v. 1.5.8?

**Comment by vipul-bhavsar** [comment]
Yes Same issue got open in 1.5.8 :( please fix

**Comment by Gunbit** [comment]
please fix same issue

**Comment by studioraygun** [comment]
Subscribed. The reason we need this feature is because we don't know how many slides there will be, because it will be controlled by a CMS. So we set slidesToShow to 5, but if there are 5, the bug occurs.

**Comment by primaltalk** [comment]
This is a little late to the party, but if you want 5 slides to show out of 5, set slides to show to 3 and center padding equal to the slide width.

**Comment by AlexandraKlein** [comment]
Great solution, but problem I'm having with center padding is that center mode doesn't begin on the first slide on init. Any suggestions?

**Comment by Piotrucci91** [comment]
There is an option "initialSlide" which takes integer value (number of slide you want to start on).
Yea the centerpadding is great... managed to do my 3-slide slider :D

I have a strange problem (cant find solution inspecting in my browser...) 
The Arrows(i mean .slick-next and .slick-before) get transparent background after clicking them (until focusing something else ie. click)
I had to use this to solve it :
```
.slick-next:focus, .slick-prev:focus
{
    background:black;
}
```
( I know there must be other reason//way, tho...)

**Comment by Erikjhons** [comment]
I have fixed this like this.

1. setupInfinite()

Slick.prototype.setupInfinite = function() {

        var _ = this,
            i, slideIndex, infiniteCount;

        if (_.options.fade === true) {
            _.options.centerMode = false;
        }

        if (_.options.infinite === true && _.options.fade === false) {

            slideIndex = null;

            if (_.slideCount >= _.options.slidesToShow) {

                if (_.options.centerMode === true) {
                    infiniteCount = _.options.slidesToShow + 1;
                } else {
                    infiniteCount = _.options.slidesToShow;
                }

                for (i = _.slideCount; i > (_.slideCount -
                        infiniteCount); i -= 1) {
                    slideIndex = i - 1;
                    $(_.$slides[slideIndex]).clone(true).attr('id', '')
                        .attr('data-slick-index', slideIndex - _.slideCount)
                        .prependTo(_.$slideTrack).addClass('slick-cloned');
                }
                for (i = 0; i < infiniteCount; i += 1) {
                    slideIndex = i;
                    $(_.$slides[slideIndex]).clone(true).attr('id', '')
                        .attr('data-slick-index', slideIndex + _.slideCount)
                        .appendTo(_.$slideTrack).addClass('slick-cloned');
                }
                _.$slideTrack.find('.slick-cloned').find('[id]').each(function() {
                    $(this).attr('id', '');
                });

            }

        }

    };


2. buildArrows()

Slick.prototype.buildArrows = function() {

        var _ = this;

        if (_.options.arrows === true ) {

            _.$prevArrow = $(_.options.prevArrow).addClass('slick-arrow');
            _.$nextArrow = $(_.options.nextArrow).addClass('slick-arrow');

            if( _.slideCount >= _.options.slidesToShow ) {

                _.$prevArrow.removeClass('slick-hidden').removeAttr('aria-hidden tabindex');
                _.$nextArrow.removeClass('slick-hidden').removeAttr('aria-hidden tabindex');

                if (_.htmlExpr.test(_.options.prevArrow)) {
                    _.$prevArrow.prependTo(_.options.appendArrows);
                }

                if (_.htmlExpr.test(_.options.nextArrow)) {
                    _.$nextArrow.appendTo(_.options.appendArrows);
                }

                if (_.options.infinite !== true) {
                    _.$prevArrow
                        .addClass('slick-disabled')
                        .attr('aria-disabled', 'true');
                }

            } else {

                _.$prevArrow.add( _.$nextArrow )

                    .addClass('slick-hidden')
                    .attr({
                        'aria-disabled': 'true',
                        'tabindex': '-1'
                    });

            }

        }

    };

3. postslide()

Slick.prototype.postSlide = function(index) {

        var _ = this;

        if( !_.unslicked ) {

            _.$slider.trigger('afterChange', [_, index]);

            _.animating = false;

            if (_.slideCount >= _.options.slidesToShow) {
                _.setPosition();
            }

            _.swipeLeft = null;

            if ( _.options.autoplay ) {
                _.autoPlay();
            }

            if (_.options.accessibility === true) {
                _.initADA();
            }

        }

    };

4. ChangeSlide
Slick.prototype.changeSlide = function(event, dontAnimate) {

        var _ = this,
            $target = $(event.currentTarget),
            indexOffset, slideOffset, unevenOffset;

        // If target is a link, prevent default action.
        if($target.is('a')) {
            event.preventDefault();
        }

        // If target is not the <li> element (ie: a child), find the <li>.
        if(!$target.is('li')) {
            $target = $target.closest('li');
        }

        unevenOffset = (_.slideCount % _.options.slidesToScroll !== 0);
        indexOffset = unevenOffset ? 0 : (_.slideCount - _.currentSlide) % _.options.slidesToScroll;

        switch (event.data.message) {

            case 'previous':
                slideOffset = indexOffset === 0 ? _.options.slidesToScroll : _.options.slidesToShow - indexOffset;
                if (_.slideCount >= _.options.slidesToShow) {
                    _.slideHandler(_.currentSlide - slideOffset, false, dontAnimate);
                }
                break;

            case 'next':
                slideOffset = indexOffset === 0 ? _.options.slidesToScroll : indexOffset;
                if (_.slideCount >= _.options.slidesToShow) {
                    _.slideHandler(_.currentSlide + slideOffset, false, dontAnimate);
                }
                break;

            case 'index':
                var index = event.data.index === 0 ? 0 :
                    event.data.index || $target.index() * _.options.slidesToScroll;

                _.slideHandler(_.checkNavigable(index), false, dontAnimate);
                $target.children().trigger('focus');
                break;

            default:
                return;
        }

    };

5. InfiteArrowEvents()

 Slick.prototype.initArrowEvents = function() {

        var _ = this;

        if (_.options.arrows === true && _.slideCount >= _.options.slidesToShow) {
            _.$prevArrow
               .off('click.slick')
               .on('click.slick', {
                    message: 'previous'
               }, _.changeSlide);
            _.$nextArrow
               .off('click.slick')
               .on('click.slick', {
                    message: 'next'
               }, _.changeSlide);
        }

    };

So far, there is only change for ( > ).
I changed it to ( >= ).

The last is important.
6. getLeft()

Slick.prototype.getLeft = function(slideIndex) {
      

        var _ = this,
            targetLeft,
            verticalHeight,
            verticalOffset = 0,
            targetSlide;

        _.slideOffset = 0;
        verticalHeight = _.$slides.first().outerHeight(true);

        if (_.options.infinite === true) {
            if (_.slideCount > _.options.slidesToShow) {
                _.slideOffset = (_.slideWidth * _.options.slidesToShow) * -1;
                verticalOffset = (verticalHeight * _.options.slidesToShow) * -1;
            } else  if(_.slideCount == _.options.slidesToShow)
            {
              _.slideOffset = (_.slideWidth * (_.options.slidesToShow-1)) * -1;
                verticalOffset = (verticalHeight * (_.options.slidesToShow-1)) * -1;
            }
              
            if (_.slideCount % _.options.slidesToScroll !== 0) {
              
                if (slideIndex + _.options.slidesToScroll > _.slideCount && _.slideCount > _.options.slidesToShow) {
                    if (slideIndex > _.slideCount) {
                        _.slideOffset = ((_.options.slidesToShow - (slideIndex - _.slideCount)) * _.slideWidth) * -1;
                        verticalOffset = ((_.options.slidesToShow - (slideIndex - _.slideCount)) * verticalHeight) * -1;
                    } else {
                        _.slideOffset = ((_.slideCount % _.options.slidesToScroll) * _.slideWidth) * -1;
                        verticalOffset = ((_.slideCount % _.options.slidesToScroll) * verticalHeight) * -1;
                    }
                }
            }
        } else {
            if (slideIndex + _.options.slidesToShow > _.slideCount) {
                _.slideOffset = ((slideIndex + _.options.slidesToShow) - _.slideCount) * _.slideWidth;
                verticalOffset = ((slideIndex + _.options.slidesToShow) - _.slideCount) * verticalHeight;
            }
        }

        if (_.slideCount < _.options.slidesToShow) {
            _.slideOffset = 0;
            verticalOffset = 0;
        }
      	

        if (_.options.centerMode === true && _.slideCount < _.options.slidesToShow) {
            _.slideOffset = ((_.slideWidth * Math.floor(_.options.slidesToShow)) / 2) - ((_.slideWidth * _.slideCount) / 2);
        } else if (_.options.centerMode === true && _.options.infinite === true) {
            _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2) - _.slideWidth;
        } else if (_.options.centerMode === true) {
            _.slideOffset = 0;
            _.slideOffset += _.slideWidth * Math.floor(_.options.slidesToShow / 2);
        }
      
      
        if (_.options.vertical === false) {
            targetLeft = ((slideIndex * _.slideWidth) * -1) + _.slideOffset;
        } else {
            targetLeft = ((slideIndex * verticalHeight) * -1) + verticalOffset;
        }
      
        if (_.options.variableWidth === true) {
          
            if (_.slideCount <= _.options.slidesToShow || _.options.infinite === false) {
                targetSlide = _.$slideTrack.children('.slick-slide').eq(slideIndex);
            } else {
              
                targetSlide = _.$slideTrack.children('.slick-slide').eq(slideIndex + _.options.slidesToShow);
            }

            if (_.options.rtl === true) {
              
                if (targetSlide[0]) {
                    targetLeft = (_.$slideTrack.width() - targetSlide[0].offsetLeft - targetSlide.width()) * -1;
                } else {
                    targetLeft =  0;
                }
            } else {
              
                targetLeft = targetSlide[0] ? targetSlide[0].offsetLeft * -1 : 0;
            }

            if (_.options.centerMode === true) {
                if (_.slideCount <= _.options.slidesToShow || _.options.infinite === false) {
                    targetSlide = _.$slideTrack.children('.slick-slide').eq(slideIndex);
                } else {
                    targetSlide = _.$slideTrack.children('.slick-slide').eq(slideIndex + _.options.slidesToShow + 1);
                }

                if (_.options.rtl === true) {
                    if (targetSlide[0]) {
                        targetLeft = (_.$slideTrack.width() - targetSlide[0].offsetLeft - targetSlide.width()) * -1;
                    } else {
                        targetLeft =  0;
                    }
                } else {
                    targetLeft = targetSlide[0] ? targetSlide[0].offsetLeft * -1 : 0;
                }

                targetLeft += (_.$list.width() - targetSlide.outerWidth()) / 2;
            }
        }
      
        return targetLeft;

    };

My example is slidecount = 3, slidesToShow=3, slidestoScroll =3.
the slidesToshow is not concerned so much.

I hope this can be helpful who uses the slick.
Thanks kenwheeler.
Your Slick.js supports me so much.
Thanks again.

**Comment by karenYerevan** [comment]
Erikjhons have you demo for yor changed Slick.js, because for me your changes not work ???

**Comment by Erikjhons** [comment]
Yes. Please view vivolife.co.uk

**Comment by czareknster** [comment]
@Erikjhons its works perfectly. Thx.

**Comment by chris-castillo-dev** [comment]
@kenwheeler was there ever a fix for this? I see a ton of code that was offered up by Ghost, but I'd rather not go and manipulate the library. Here's my use case:

Product Gallery for WooCommerce products:
- Created a shortcode to create markup for product images
- One slider is the large preview slider for product images
- The second slider is the thumbnail navigational slider (asNavFor the preview slider)

If I set the slidesToShow option to something like 4, if the product has 4 or less images, the thumbnail navigational slider stops functioning as a navigation for the main preview slider. So if the user clicks on a thumbnail the preview slider doesn't display that image.

Reading this old thread, I understand that if there are no more slides to slide through then the slider doesn't have anything to do, but if the slider is being used asNavFor, shouldn't the navigational ability of clicking on slides in that slider to change the slide in focus for the second slider still work?

Here's an example of the slider:
![image](https://user-images.githubusercontent.com/46719081/195226247-353905a2-6779-486f-9040-7fd0fae7aabb.png)


If I set the thumbnail slider's slidesToShow to something like 3, then the slider works and updates the main slider as expected:
![image](https://user-images.githubusercontent.com/46719081/195226355-39d8bb07-6b84-448e-babe-a0c2b3899c30.png)

(Note: the prev and next buttons)

Here's my code for each slider:

```
let previewSlider = jQuery(".product-gallery__preview");
let thumbSlider = jQuery(".product-gallery__thumbs");

let navSlider = thumbSlider.slick({
  asNavFor: ".product-gallery__preview",
  slidesToShow: 3,
  slidesToScroll: 1,
  arrows: true,
  infinite: true
});

let mainSlider = previewSlider.slick({
  slidesToShow: 1,
  arrows: false
});
```

**Comment by chris-castillo-dev** [comment]
@kenwheeler - I managed to fix this with a workaround, but I still think that the problem I've described should be addressed.

Here's the code workaround I found:

```
let previewSlider = jQuery(".product-gallery__preview");
let thumbSlider = jQuery(".product-gallery__thumbs");

let navSlider = thumbSlider.slick({
  slidesToShow: 5,
  slidesToScroll: 1,
  arrows: false,
  infinite: true
});

let mainSlider = previewSlider.slick({
  slidesToShow: 1,
  arrows: true,
  appendArrows: ".product-gallery__thumbs",
  asNavFor: ".product-gallery__thumbs"
});
```

I had to set the main preview slider to arrows: true and asNavFor the thumbnail slider. It's the reverse of what intuitively I had thought I would have to do (which is why I think it should be addressed). I set the appendArrows to the thumbnail nav slider, and set the arrows to false for the nav slider. This way the arrows for the main slider are always attached to the thumbnail nav slider.

**Comment by daviderichie** [comment]
@chris-castillo-dev 

I had the same problem and I figured out a solution. Try to check it out and see if this works for your problem.

https://codepen.io/Davide-Zerbini/pen/XWYZNZN

Let me know if it helped you :)
Davide
