### ISSUE TITLE
Add a refresh method

### ISSUE THREAD

**Issue by blown-capacitor** [kenwheeler/slick#547]
Currently you can manually refresh slick using `slickSetOption(anyoption, anyvalue, true);`

Any chance of a `slickRefresh` method rather than using `slickSetOption(null, null, true);` would make code clear to developers inheriting a project that are less familiar with slick.

**Comment by TomVoxsen** [comment]
I also concur - took me ages to find this. Great carousel btw!

**Comment by thebucknerlife** [comment]
Thank god we found this. Google is awesome, but would be better if this was in the documentation. +1

**Comment by thasmo** [comment]
Would be awesome if `$('.your-element').slick('refresh');` was supported.

**Comment by thasmo** [comment]
Seems like this works anyway. :)

**Comment by perara** [comment]
This does not seem to work?
I tried:
`jQuery(ele).slick('refresh')`
and
`jQuery(ele).slick.refresh()`

Does not seem like slick object has a refresh function?

**Comment by gbrits** [comment]
`$('.slick-slider').slick('refresh');` worked for me. (Ver. "slick-carousel": "^1.6.0")

**Comment by dzpt** [comment]
@gbrits Uncaught TypeError: Cannot read property 'refresh' of undefined
slick 1.8.1, after load new html from ajax

**Comment by shejinalt** [comment]
> @gbrits Uncaught TypeError: Cannot read property 'refresh' of undefined slick 1.8.1, after load new html from ajax

me also getting this error
