### ISSUE TITLE
Add thumbnails functionality

### ISSUE THREAD

**Issue by ghost** [kenwheeler/slick#55]
I love your awesome plugin. I already started using it in a project. It works really well for banner slider. But there also is a product page where i have a thumbnail slider: http://i.imgur.com/htTb2Kj.jpg and i have to consider other plugins(which i think are not as good as yours) to implement it.

So i think it'd be really great if you added this functionality. Or maybe you know a way for me to do this now?

Thanks.

**Comment by EBII** [comment]
you have sample code for this?

**Comment by totemusik** [comment]
This is my solution.
May it helps.

This works with several usage of the same slick-slider on one page. 
The HTML is with smarty, so you have to change for your purpose. :)

JavaScript
```
 function showSliderImage() {
        $('.slick-slider-image').on('click', function () {
            var sliderImagePath = $(this).find('img').attr('src');
            var sliderImageId = $(this).find('img').attr('data-lrg-img');

            $('#' + sliderImageId).attr('src', sliderImagePath);
        });
    }

    showSliderImage();
```

HTML
```
{assign var='randomKey' value=1|rand:299}

<div class="slick-slider-image-large-container">
    {if $images}
        <img src="{$images[0].image.url}" class="slick-slider-image" alt="" id="{$randomKey}">
    {/if}
</div>

<div class="slick-slider">
    {if $images}
        {foreach from=$images item=item key=key}
        	<div class="slick-slider-image">
                <img src="{$item.image.url}" alt="" data-lrg-img="{$randomKey}">
            </div>
        {/foreach}
    {/if}
</div>
```
