### ISSUE TITLE
option to "lock" drag when on first or last item

### ISSUE THREAD

**Issue by hems** [kenwheeler/slick#561]
When having for instance 3 items with non-infinite scroll would be good to have an option to don't allow dragging on the direction that won't reveal any other item.

For instance, dragging the first item to the right side ( therefore revealing an empty space on the left side ) or dragging the last item to the left ( therefore revealing an empty space ).

I run into this problem when using a carousel with 100% x 100% overlay, so basically when dragging on the edges it does reveal the background which isn't very good looking, at least on my project :p

thanks

**Comment by pavethiran** [comment]
Is there already a solution?
