### ISSUE TITLE
dragging first or last item on an infinite carousel results in "full rewind" ?

### ISSUE THREAD

**Issue by hems** [kenwheeler/slick#562]
One thing i noticed on my current project is that when on the "last item" of an infinite carousel if i drag once more, it does reveal the next item ( which would be the first repeated ) but then it fully rewinds to the first one.

The opposite is also true.

I'm a doing something wrong? I can see the infinite example on the website doesn't have this problem, but the example has 3 items being show while my code has only 1.

**Comment by m-pokrovskii** [comment]
In case if some will google it: check that you not overriding slick transitions. 
I had this 
`* { transition: all 0.3s }  `
