### ISSUE TITLE
SCSS seems to generate wrong css file

### ISSUE THREAD

**Issue by Bilal-Abdeen** [kenwheeler/slick#563]
Very good project, thanks.... 

However, I think there are issues in the scss file. 

1. The code of the function (slick-image-url()) produces incorrect folder path. I managed to work around it, by hard-coding the folder paths, instead of using this function. 

2. I tried to update the place where the prev/next arrows appear. I changed the position arguments under the class (.slick-prev). The generated css file worked fine on Chrome 37, IE 11 & Firefox 32. However, Safari 5.1.7 on Windows 7 did not like this css file. I edited the css file manually - rather than generating t from scss. It worked fine. 

Another way to work around the 2nd problem (above) is to generate expanded, rather than compressed, css file. By the way, the other compressed css files (I use foundation app.css) are handled fine by safari. I am not sure why Safari does not like the compressed version of the slick css file. Could it be, becaue of the rtl elements? 

In addition to Safari, I have also seen the above 2 issues in the native internet browser of my mobile phone (Samsung Galaxy S III). 

Thank you again for the good work.
Bilal

**Comment by kenwheeler** [comment]
Fixed on dev
