### ISSUE TITLE
Show arrows / dots only on mousein?

### ISSUE THREAD

**Issue by marcinkrzeminski** [kenwheeler/slick#565]
Hi,

One of my clients requested showing the arrows only when you hover your mouse over the slider. I couldn't find that option in the config. Ken, what do you think about implementing this to the core? 

Keep it up ;).

**Comment by MarcGuay** [comment]
This is slightly more difficult for slick-arrows.  You'll need something like this, SASS markup:

    .slick-slider{
        .slick-arrow{
            display:none !important;
        }
        &:hover{
            .slick-arrow{
                display:block !important;
            }
        }
    }

**Comment by StasVolkov** [comment]
Try this:
`.slick-arrow {
transform: translateZ(0);
}`

**Comment by thedoglett** [comment]
This is what I use - change the opacity and they can fade in nicely on hover.

`    .slick-arrow{
      opacity: 0;
      transition: all .25s ease-in-out;
      -moz-transition: all .25s ease-in-out;
      -webkit-transition: all .25s ease-in-out;
    }
    &:hover{
      .slick-arrow{
        opacity: 1;
      }
    }`
