### ISSUE TITLE
Parameter for space between slides

### ISSUE THREAD

**Issue by simranbentel** [kenwheeler/slick#582]
I noticed that all your demos are applying no space between the slides but rather you are creating the appearance of space by using heading tags as the content in each slide, which have equal margin on all sides. This approach creates an interesting issue though...

If you watch the left and right edge of the slides area as you advance or regress the slides, you can see the content spilling out past the initial left or right edge by the amount of left- or right-margin of each slide's content during the actual transition. I notice that the actual width of the entire .slick-list element includes the left margin of the first viewable slide and the right margin of the last viewable slide.

In an implementation I am working with, the design directive is for the entire .slide-list to go edge to edge width-wise without any space on the left and right side. The extra margin I mentioned in the previous paragraph then poses a problem and I have been playing with various workarounds to create the appearance of a clean edge to edge presentation, none of which I am thrilled with. 

I would think you could probably add a spacing parameter to the script that would calculate the space between each slide without any extra space at the beginning or end. 

I think this would be the cherry on top of a truly tasty plugin! Cheers!

**Comment by teefouad** [comment]
@matthewlein This doesn't solve the issue mentioned by @simranbentel and @paulthecoder

**Comment by goulddev** [comment]
Has anyone found a solution for this?

**Comment by matthewlein** [comment]
I decided to look at this again...and I think I see what you're talking about. The content is visible outside the container because the `.slick-list` has overflow hidden, and its size is based on the slides. Moving `overflow: hidden` to `.slick-slider` or another wrapper fixes that.
http://codepen.io/anon/pen/zvWjgE

**Comment by simranbentel** [comment]
Awesome!

**Comment by Peterdoma** [comment]
Was a fix ever found for this? I like yours @matthewlein but it won't work if you want arrows and dots.

**Comment by drbelfast** [comment]
I made it by directly setting styles to wrapper div
`<div key={index} style={{'padding': '5px'}}><img src={img} onClick={onClick}/></div>`

**Comment by lholdsworth** [comment]
You can always use external triggers if you want to place arrows outside of the slider (which wont show if overflow is hidden, using the other method suggested).  Something like:

`$('.nextarrow').click(function(e) {
    $('.myslider').slick('slickNext');
});

$('.prevarrow').click(function(e) {
    $('.myslider').slick('slickPrev');
});`

**Comment by egemenerd** [comment]
Using css animation-delay property, you can hide the slide until the animation stops. Animation delay should be equal to the speed setting of the plugin.

slick-list {
    margin: 0 -10px;
}

.slick-slide {
    margin: 0px 10px;
    opacity:0;
    transition-delay: 0s;
    transition-duration: 0.2s;
    transition-property: opacity;
    transition-timing-function: ease-out;
}

.slick-slide.slick-active {
    opacity:1;
    transition-delay: 0.3s;
    transition-duration: 0.2s;
    transition-property: opacity;
    transition-timing-function: ease-in;
}

**Comment by zerodburn** [comment]
You can also do this to make the slides have an equal gap between them but still be flush to their container on the left and right:

```
.c-slick {
    margin-left: -20px;
}

.c-slick__slide {
    padding-left: 20px;
}
```

**Comment by lsalazar85** [comment]
@egemenerd Awesome dude !!! Thank you

**Comment by bigapplebuddy** [comment]
@zerodburn mind clarifying a bit? My slider doesn't seem to have a .slick or .slick__slide (only slick-slide). Also are the .c appended signifying a custom class? thx!

**Comment by oweskeez** [comment]
@zerodburn mind clarifying a bit? My slider doesn't seem to have a .slick or .slick__slide (only slick-slide). Also are the .c appended signifying a custom class? thx!

**Comment by gzurbach** [comment]
This solution worked for me in order to get a full-width carousel with spacing between images. I had to move the arrows _inside_ the carousel (i.e. on top of the images). 

```css
// Add spacing between images
.slick-slide {
  margin: 0 5px;
}

// Fix external margins
.slick-list {
  margin: 0 -5px;
}
.slick-slider {
  overflow: hidden;
}

// Move arrows on top of images
.slick-prev {
  left: 50px;
  z-index: 1;
}
.slick-next {
  right: 50px;
}
```

**Comment by ShreyderD** [comment]
all of the solutions does not work good enough! I think I speak on behalf of all mankind if I say we want it to work like "justify-content: space-between;"

The following helps but there is some imperfection with first and last slides - they have margin too:
/* the slides */
.slick-slide {
    margin: 0 10px;
}
/* the parent */
.slick-list {
    margin: 0 -10px;
}

I've tried to modificate the slick.js:

Part 1:
_.defaults = {
...
customPadding: '15px',
...

Part 2 (line 2052):
...
_.slideWidth = Math.ceil(**(_.listWidth-(_.options.slidesToShow - 1) * _.customPadding))/ _.options.slidesToShow)**;
...

But it doesn't work. Apparently my JavaScript skills have need of improvements too. Thus SOS to pros!

**Comment by dikiyforester** [comment]
It's not necessary to move arrows inside the carousel (when using @gzurbach solution). 
Alternatively can be used custom arrows outside the `.slick-slider`. (Same for dots, I guess).

https://jsfiddle.net/xepnvrf8/

In my example, I use a wrapper which has a necessary width and full-width carousel with spacing between slides.

The custom arrows have been added inside the wrapper and positioned absolutely outside the wrapper width (that is how it was needed for me).

Now it works perfectly for me.

**Comment by ZeroCool-85** [comment]
You dont need to set margins just set:

    `.slick-slide {
		padding: 0 8px;
		box-sizing: border-box;
	}`

padding-left/right depends on your centerPadding.

**Comment by adamgilmour** [comment]
I've worked on a possible solution that seems to work on load and with responsive, haven't tested use with other options though.

Add new option to  _.defaults `spaceBetweenSlides: null`

Line 2077
`_.slideWidth = (_.listWidth / _.options.slidesToShow) + (_.options.spaceBetweenSlides / _.options.slidesToShow);`

Line 2088
`if (_.options.variableWidth === false) _.$slideTrack.children('.swyper__slide').width(_.slideWidth - offset).css({marginRight:_.options.spaceBetweenSlides});`

I've been working on v1.8.0 so haven't tested this on v1.9.0.

I have noticed that it cuts maybe a pixel off slides at the edges with some parameters :/

**Comment by virgiliud** [comment]
Here's how I did it with plain CSS

1. Add space between slides:

```
.slick-slide {
  margin-left: 10px;
  margin-right: 10px;
}
```

2. Pull `slick-list` to left and use `calc()` to extend: 

```
.slick-list {
  margin-left: -10px; /* same px size as slide space */
  width: calc(100% + 20px); /* add double the px size as slide space */
}
```

Make sure you resize the screen when testing/adding values in inspector, to recalculate the slider values.

**Comment by GuruKhalsa** [comment]
If you add a container div inside of each slide and give it a margin, then make the background of the slides the same as the background behind it, you can achieve the aesthetic of slides with space between them in a way that works with slick's responsive functionality.  Won't work for all situations but could work for a lot of simple ones.

**Comment by ecupaio** [comment]
In latest version as of this comment (1.8.1), slick will nest your slides wthinin two consecutive divs in which you can apply padding to the `.slick-slide` child div. For example: 
HTML  
```
<!-- parent slick generated slide -->
<div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 342px;">
  <!-- child div -->
  <div>
    <!-- my slide -->
    <div class="my-slide"> </div>
  </div>
</div> 
```

CSS 
```
.slick-slide > div {
  padding: 0 0.5rem;
}
```

**Comment by kochewww** [comment]
> You dont need to set margins just set:
> 
> ```
> .slick-slide {
> 	padding: 0 8px;
> 	box-sizing: border-box;
>  }
> ```
> 
> padding-left/right depends on your centerPadding.

you saved my life. thank you

**Comment by pow44feet** [comment]
I use to make equal gap between the slides text-align: center inside the slide
`.slick-slide {
   text-align: center;
}`
this i made left and right gaps equal. Maybe it can help someone.

**Comment by iamdebadipti** [comment]
If you have arrows outside.. try `.slick-slide: 0 10px;` . It is working for me as `margin: 0 10px` was not working.

**Comment by Aniganesh** [comment]
> Did anyone ever find a fix ever found for this? I like yours @matthewlein but it won't work if you want arrows and dots outside.

Apply `position: absolute` on your arrows and position them as needed.

**Comment by Slavichek** [comment]
Hy everyone: to fix this: 
in usage "react-slick" library
.slick-slide {
	padding: 0 5px; ///////or what you ned
}
css properties to item 
.slider-item {
  border: 1px solid red;
  box-shadow.....
 }

**Comment by rondog** [comment]
thanks @virgiliud, your solution seemed best as the last visible slide did not have an unnecessary space on the right

**Comment by FabienLge** [comment]
Hello everyone !

I have been using this plugin quite a bit, sad to see it looks abandoned while being so awesome 😞 

Anyway, after trying some of the hacks listed in this issue, didn't find anything fitting with my current need which is a setup using Bootstrap (5.0.2) cards. So I find a pretty simple solution that looks to be working fine, hope it can ever help someone : 

```html
<div class="carousel w-50 mx-auto my-5" id="carousel-id">
    <div class="carousel-trigger">
        <!-- In order to ensure each slide has same height -->
        <div class="carousel-slide d-flex align-items-center">
            <div class="card">
                <div class="card-body">
                    <!-- ... -->
                </div>
            </div>
        </div>
        <div class="carousel-slide d-flex align-items-center">
            <div class="card">
                <div class="card-body">
                    <!-- ... -->
                </div>
            </div>
        </div>
        <!-- ... -->
    </div>
</div>
```

```scss
#carousel-id {
    .slick-slide > div {
        display: flex;

        .carousel-slide {
            margin: 5px; // replace by the gap amount you would like to use
        }
    }
}
```

```js
// Slick configuration
$("#carousel-id").slick({
    infinite: true,
    dots: true,
    rows: 2,
    slidesPerRow: 2
});
```

**Comment by LancerAbir** [comment]
Thanks, @ZeroCool-85

> You dont need to set margins just set:
> 
> ```
> .slick-slide {
> 	padding: 0 8px;
> 	box-sizing: border-box;
>  }
> ```
> 
> padding-left/right depends on your centerPadding.

Thanks @[ZeroCool-85](https://github.com/ZeroCool-85)

**Comment by Aamir090** [comment]
> .slick-slide {
>     margin: 0 10px;
> }

thanks bro

**Comment by LuisValgoi** [comment]
I solved as below

`& .slick-list { margin: 0 -7px; & .slick-slide > div { padding: 0 10px; } }`

**Comment by gefusion** [comment]
All you guys offer isn't actually a solution, because after these .slick-list { margin: 0 -npx; } .slick-slide { margin: 0 npx; } you simply get sliders space reduced by n.
So you get slider translated to n px to left, but from right you'll lack of these n px as well.

**Comment by hossainrabbi** [comment]
.slick-active.slick-current {
  margin-right: 10px !important;
  margin-left: 0 !important;
}

 .slick-active {
  margin-left: 10px;
}

**Comment by im-hamza-dev** [comment]
I'm having this same issue of no-space between between slick-items on mobile. Avoid using centerMode flag. Its the main culprit. 
Here is a trick you can use to center slick-items:
Center align the items from carousel wrapper div element:
text-align: center

On settings object:
centerMode: false

**Comment by alikleit** [comment]
Seems like that the space between slide is the width calculated by the library. What worked for me:

options:
```
variableWidth: true
```

then the suggestion above to play with the styles:

```
.slick-slide {
   margin-right: {the-spacing}px;
}
```

**Comment by Khoaair** [comment]
> Seems that the space between slide is the width calculated by the library. What worked for me:
> 
> options:
> 
> ```
> variableWidth: true
> ```
> 
> then the suggestion above to play with the styles:
> 
> ```
> .slick-slide {
>    margin-right: {the-spacing}px;
> }
> ```

thanks @alikleit, you save my life

**Comment by RCNeil** [comment]
I achieved with 

`.slick-slide {
     margin-right: 40px;
}`

and the container 

`.slick-list {
     width:calc(100% + 40px);
}`

Adjust the `40px` for whatever spacing you need.

**Comment by rr-it** [comment]
All the solutions mentioned above work only for the static state.
When the slider is moving, they don't correctly clip away the sliding elements on either the left, the right or both sides.

As it is 2024 the browsers have evolved and here is a working solution for modern browsers!

Use `clip-path`: :tada:

```css
/* gutter width: 20px */

.slick-slider {
  margin-left: -10px;
  margin-right: -10px;
}
.slick-list {
  clip-path: inset(0 10px 0 10px);
  /* warning: do not set `margin` or `padding` to anything other than `0` here! */
  margin: 0;
  padding: 0;
}
.slick-slide {
  margin-left: 10px;
  margin-right: 10px;
  background-color: thistle;
}
```

Also see:
* https://caniuse.com/css-clip-path
* https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

**Comment by gatinhap** [comment]
This worked best for me:

```
.slick-slider {
  overflow: hidden;
  padding-bottom: 60px; //this created space to place arrow and dots below the slider (which was expected result in my case). You can add instead top/left/right padding depending where you want to keep arrows / dots).
}

.slick-list  {
  margin-left: -30px;
}

.slick-slide {
  margin-left: 30px;
}
```

It kept all slides in view and spaced between parent container without any gap at the beginning or at the end. Just between them. Worked for mobile and tablet view as well.

**Comment by localnetwork** [comment]
This works for me:

`.slick-slider .slick-slide {
  margin-left: 15px;
}

.slick-slider .slick-list {
  margin-left: -15px;
}
.slick-slider .slick-track {
  display: flex;
}`

**Comment by jamieburchell** [comment]
> All the solutions mentioned above work only for the static state. When the slider is moving, they don't correctly clip away the sliding elements on either the left, the right or both sides.
> 
> As it is 2024 the browsers have evolved and here is a working solution for modern browsers!
> 
> Use `clip-path`: 🎉
> 
> https://jsfiddle.net/mzevrkgy/6/

Brilliant. Interested to know why you warned about using padding/margin however. I have margin to make room for the left and right arrows and this solution works beautifully!

**Comment by rr-it** [comment]
@jamieburchell All the padding/margin solutions don't work while the slider is moving. While in moving state the moving slide is overflowing the left/right box of the slider and thereby does not correctly align with other elements on the webpage.

**Comment by jamieburchell** [comment]
> @jamieburchell All the padding/margin solutions don't work while the slider is moving. While in moving state the moving slide is overflowing the slider box either on the left or right side or even on both sides. Thereby moving slides do not correctly align with other elements on the webpage.

Yep, your clip-path solution solves it - I just mean that you warned against using margin/padding in your CSS code so I assumed that would break something when using clip-path. I guess you just mean don't use the margin/padding solutions for the reasons you mentioned.

**Comment by rr-it** [comment]
Setting a margin or padding on the `.slick-list`-container might make the old problem with overflow reappear, as the `clip-path` does not work correctly anymore - at least that is what I experienced some time ago.

**Comment by jamieburchell** [comment]
> Setting a margin or padding on the `.slick-list`-container might make the old problem with overflow reappear, as the `clip-path` does not work correctly anymore - at least that is what I experienced some time ago.

It works https://jsfiddle.net/hvwgp847/ :)
