### ISSUE TITLE
Centered Vertical Carousel 

### ISSUE THREAD

**Issue by JXTposed** [kenwheeler/slick#599]
Tried to use both settings at once and the carousel starts at slide #1 at the top no matter what. 

as you seen in the pen

http://codepen.io/jxtposed/pen/iIezA

Settings:

``` javascript
    $('.center').slick({
        vertical: true,
        centerMode: true,
        infinite: true,
        centerPadding: '60px',
        slidesToShow: 3,
        slidesToScroll: 1,
        responsive: [{
            breakpoint: 768,
            settings: {
                vertical: true,
                arrows: true,
                centerMode: true,
                centerPadding: '40px',
                slidesToShow: 3,
                slidesToScroll: 1
            }
        }, {
            breakpoint: 480,
            settings: {
                vertical: true,
                arrows: false,
                centerMode: true,
                centerPadding: '40px',
                slidesToShow: 3,
                slidesToScroll: 1
            }
        }]
    });
```

**Comment by elle343** [comment]
@kenwheeler 

Hi, I was wondering if you could help me.  I can't seem to get my slider to work.  Here's my pen http://codepen.io/elle343/pen/pvBgRb

Thanks!

**Comment by marteb** [comment]
Just experienced the same problem: centerMode and vertical won’t work together. Will this be fixed?

**Comment by nilssolanki** [comment]
Hi @kenwheeler
What is the reason that the two don't work together? Is there any way we could help you to get this to work?

**Comment by kenwheeler** [comment]
I'll look into adding it for the release after next

**Comment by SuppahSeb** [comment]
Hello. Has centerMode for vertical slider been added yet? I'm using slick slider for other sliders on webpage and want to stick with it... :)

**Comment by phucbm** [comment]
Hi @kenwheeler 
Did you have anything new on this issue?

**Comment by Saabbir** [comment]
Still facing this issue. 
![image](https://user-images.githubusercontent.com/10579433/190150244-d51a3724-5f58-4f6c-8c98-f5ffa7bcaed1.png)
