### ISSUE TITLE
Combining Slick with Instafeed.js - load order

### ISSUE THREAD

**Issue by HrEsben** [kenwheeler/slick#606]
Hi there.
I really love Slick. It's so easy that even rookies can implement it. But I've come up short on this.
I've been trying to combine instafeed.js (http://instafeedjs.com/) and Slick, which works fine, except from the order in which the javascripts are parsed. Sometimes it shows the images fetched from Instagram just fine in the slider as I was looking for, but when I refresh a couple of times, the 30 images fetched via Instafeed.js loads before Slick slickens it up.
Hope that makes sense, and somebody is able to help. Really cool if it's possible to combine these two.

I am looking for a way to fetch the images from Instagram via instafeed.js and make sure that they are not sent to the web page before they get handled by Slick.

I have this inside my <body>:

``` javascript
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.3.8/slick.min.js"></script>

  <!-- Slick -->
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.3.8/slick.min.js"></script>

<script type="text/javascript">
     $(document).ready(function(){
       $('.slickitup').slick({
           infinite: true,
  slidesToShow: 3,
  slidesToScroll: 3,
       });
        });
    </script>

<!-- Instafeed -->
<script type="text/javascript">
    var userFeed = new Instafeed({
        get: 'user',
        userId: XXXXXXXXXX,
        accessToken: 'XXXXXXXXXXXXXXX',
      limit: 30,
    });
    userFeed.run();
</script>
```

**Comment by mager19** [comment]
this options work for me  http://thenorthernfoundry.com/slick-slider-with-instagram-feed/
