### ISSUE TITLE
waitForAnimate and fade bug

### ISSUE THREAD

**Issue by pomm0** [kenwheeler/slick#607]
Hello,

me again.

I've found a new bug with your new feature waitForAnimate and slow fading.

If you fast click (multiple times) the dots before the animation is complete it sometimes jumps and not fades: http://jsfiddle.net/nveu9z8w/2/ (just click the dots a few times fast)

It seems that the fadings are queued and so happens that sometime all slides are about to fade out and  you only see the background-color. 

Could you please check this?

Thank you,
Pomm0

**Comment by kenwheeler** [comment]
There really isn't a good way to make this work
