### ISSUE TITLE
Options Vertical - touch vertical not work, only horizontal touch

### ISSUE THREAD

**Issue by dekwilde** [kenwheeler/slick#620]
When I set the options to work in vertical mode, the touch event to change de slide need to also change to vertical mode. the "rtl" options to fix this also don't work!

**Comment by inventortechie** [comment]
Haha, I got a kick out of reading this thread. Totally agree with @kenwheeler , but , looking in from the other side, I can see where it might work in some use cases. Came across this thread looking for the same solution, but (again), re-thinking the usability, I will stick w/ horizontal and just tweak my layout to keep users happy ;-)

**Comment by kenwheeler** [comment]
@Inventortechie yeah I finally caved and there is a verticalSwiping option that lets you do this
