### ISSUE TITLE
Cloning slides within angular app.

### ISSUE THREAD

**Issue by iperelivskiy** [kenwheeler/slick#622]
Hi, 

Is there a valid way of extending cloning logic for integration with angular? I need newly cloned elements where compiled with parent scope. Many thanks.

**Comment by GusCaplan** [comment]
@kenwheeler @ivanperelivskiy how do I implement this? I am having the exact same problem.

**Comment by kenwheeler** [comment]
Hoping someone can hop in here, I have very little Angular experience

**Comment by GusCaplan** [comment]
@kenwheeler same here. So does slick have no onInit? I couldn't find anything like that.

**Comment by kenwheeler** [comment]
there is an init event you can hook into

**Comment by GusCaplan** [comment]
do you mean the `.on('init',function(){});` ?

**Comment by GusCaplan** [comment]
@kenwheeler i just tried using the above. It did not work.
`$('.movies').on('init', function(event, slick) {
    $('.movies').find('.slick-cloned').each(function() {
      var $clone = $(this),
          $cloneInner = $compile($clone.html())(scope);

      $clone.empty().append($cloneInner);
    });
});`

**Comment by kenwheeler** [comment]
Are you binding the unit method prior to slicking?

**Comment by GusCaplan** [comment]
@kenwheeler yes I am. The method is declared directly above the function that slicks.

**Comment by simeydotme** [comment]
@GusCaplan you can't ask slick to monitor an "init" event before slick even exists, aight.

**Comment by GusCaplan** [comment]
@simeydotme but if I bind the init event after i slick the .movie it won't trigger, right?

**Comment by GusCaplan** [comment]
@simeydotme @kenwheeler I figured out the problem. The styling of the copied divs i am using is set using IDs, and however slick only clones classes. I can just change it to classes, but this should be fixed.

**Comment by GusCaplan** [comment]
actually, that's stupid. Don't clone IDs, that would be pointless.
