### ISSUE TITLE
Using fade property in responsive settings breaks Slick

### ISSUE THREAD

**Issue by noslouch** [kenwheeler/slick#665]
Changing the `fade` property in a responsive setting misaligns the left edge of the slides when you are in the non-`fade` breakpoint such that only the first slide is visible. 

If you change slides in the `fade` breakpoint, and then resize to go into the non-`fade` breakpoint, no slides will be visible, as I think Slick is trying to show the currentSlide.

Test case: http://jsfiddle.net/noslouch/xjxhqpjw/10/
Full screen: http://jsfiddle.net/noslouch/xjxhqpjw/10/embedded/result/

To reproduce:
**Starting from a `window` size > 480**
1. Drag mouse to change slide
2. Resize window below 480px breakpoint

**Starting from a `window` size < 480**
1. Drag mouse to change slide

Might be related to #638.

**Comment by samYukthan** [comment]
$('.test-wrapper').slick({
			infinite: true,
			dots: true,
			arrows: false,
			speed: 1000,
			fade: true,
			cssEase: 'ease-in-out',
			easing: 'easeOutElastic',			
			slidesToShow: 2,
			slidesToScroll: 1,	
			responsive: [
			{
				breakpoint: 1024,
				settings: {
					slidesToShow: 1,
					slidesToScroll: 1,
				}
			} 
			]	
		});


its not working properly.

**Comment by firestar300** [comment]
I still have an issue :

```js
{
      dots: true,
      infinite: false,
      slidesToShow: 3,
      slidesToScroll: 3,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2,
          },
        },
        {
          breakpoint: 768,
          settings: {
            fade: true,
            slidesToShow: 1,
            slidesToScroll: 1,
          },
        },
      ],
    }
```

I got this error : `slick.js:2076 Uncaught ReferenceError: targetleft is not defined`

```js
Slick.prototype.setFade = function() {

        var _ = this,
            targetLeft;

        _.$slides.each(function(index, element) {
            targetLeft = (_.slideWidth * index) * -1;
            if (_.options.rtl === true) {
                $(element).css({
                    position: 'relative',
                    right: targetleft,
                    top: 0,
                    zIndex: _.options.zindex - 2,
                    opacity: 0
                });
            } else {
                $(element).css({
                    position: 'relative',
                    left: targetleft, // <------------ THIS LINE
                    top: 0,
                    zIndex: _.options.zindex - 2,
                    opacity: 0
                });
            }
        });

        _.$slides.eq(_.currentSlide).css({
            zIndex: _.options.zindex - 1,
            opacity: 1
        });

    };

```
