### ISSUE TITLE
Feature request: support media query for breakpoint

### ISSUE THREAD

**Issue by gseguin** [kenwheeler/slick#67]
Instead of a pixel dimension, it would be fantastic to be able to provide a media query as breakpoint. The underlying code would be using [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window.matchMedia) to support that.

**Comment by simeydotme** [comment]
Closing this old issue, I believe this is mostly covered by the `mobileFirst` option now.

**Comment by klihelp** [comment]
Thanks, have to check this
>> I believe this is mostly covered by the mobileFirst option now.
