### ISSUE TITLE
Missing a .removeAll() method

### ISSUE THREAD

**Issue by iSimonWeb** [kenwheeler/slick#673]
I need to remove all slides from my initialized Slick slideshow and I found that the method .slickRemove() can only remove one slide.
I'm using your plugin to power a "modal slideshow" and I want to replace all the slides without re-initializing Slick everytime.

**Comment by chipco** [comment]
it would be great to have this documented on the [website] (https://kenwheeler.github.io/slick/).
```javascript
$('.slick-container').slick('removeSlide', null, null, true);
```

**Comment by BrandInMotion** [comment]
+1000000 points for @chipco - that worked flawlessly. Thanks!

**Comment by JeffMatthews2** [comment]
I second chipco's suggestion concerning documentation.

**Comment by upendersanga** [comment]
Thank a lot..

**Comment by kobiak** [comment]
I wonder if anyone could help, I'm trying to remove slides with a set class name when new slide was added.

thanks.

**Comment by baarucebruce** [comment]
@JeffMatthews2 agreed! @chipco this saved me in trying to achieve the same functionality as @iSimonWeb. Developing a single page application that doesn't reload the page, so instead of reinitializing slick with every new data set a removeAll fix worked flawlessly.

**Comment by mystus** [comment]
@chipco Thank you! Was exactly what I was looking for... I further add my vote to get the documentation updated on this awesome script...

**Comment by timsamuelsson** [comment]
It would be really nice if the was added to the documentation :)

**Comment by jkfran** [comment]
Seems that they changed the name from 'removeSlide' to 'slickRemove'.

$('.slick-slider').slick('slickRemove', null, null, true);

**Comment by majorsaaam** [comment]
@chipco solution is great for when simply unslicking won't work. I had an issue that my slick differentiate between Firefox and Chrome, so I had to removeSlide and unslick for full support.

**Comment by bgp1** [comment]
Works like a charm!

`$('.slick-slider').slick('slickRemove', null, null, true);`

**Comment by caioagiani** [comment]
```js
$(".wrap-slick3").each(function () {
  $(this).find(".slick3").slick("removeSlide", null, null, true);
});
```
