### ISSUE TITLE
Using `asNavFor` and `slideCount <= slidesToShow`

### ISSUE THREAD

**Issue by Petah** [kenwheeler/slick#676]
When using `asNavFor` and `slideCount <= slidesToShow` `focusOnSelect` no longer works as expected.

Removal if these lines fixes it, but I'm unsure if it will have any other side effects.

https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1427-L1429

**Comment by link2pk** [comment]
@kenwheeler , Many thanks for the slider.
Can anyone please check [https://jsfiddle.net/link2pk/00ywqbjL/2/](url) why it is not working here?

Thanks
