### ISSUE TITLE
Feature request: add option to disable csstransition

### ISSUE THREAD

**Issue by verprox** [kenwheeler/slick#68]
In some cases we need to use jQuery animation instead of css animation. For example, fade effect work better with jQuery animation.

**Comment by theluk** [comment]
does not work. 
this code does animate the sliding of slider. 

```
var slider= $("#slider").slick({
    arrows: false,
    swipe: false,
    slidesToShow: 1,
    useCSS: false
});

slider[0].slick.cssTransitions = false;

something.on("change", function() {
    slider.slick("slickGoTo", 5);
});
```

**Comment by leggomuhgreggo** [comment]
@theluk do you want to make a demo?

**Comment by theluk** [comment]
unfortunately no time. i worked around it using fade:true for me. but would be nice if it worked as supposed to

**Comment by leggomuhgreggo** [comment]
I think the methodology you're referring to may be outdated. Looks like it's from a comment from 3 years ago when the API was different.

**Comment by theluk** [comment]
thats why I also added to `useCSS` option in my example...

**Comment by leggomuhgreggo** [comment]
Yes, very simple code to follow. It's simplicity lends itself to simple illustrative demo from which potential bugs can be conveyed to unpaid open source lib maintainers, per their contribution guidelines 😉 

Here, I [made you a one](https://codepen.io/leggomuhgreggo/pen/yogvMN?editors=0010)

Wait so what are you trying to do? `useCSS` just toggles between using jQuery's `animate` method vs its `css` method, it doesn't stop animation. You might want `speed: 0`?
