### ISSUE TITLE
Fade breaks RTL slider

### ISSUE THREAD

**Issue by RELnemtzov** [kenwheeler/slick#686]
When adding "fade:true" to an RTL slider, only the first slide displays correctly, then after the fade-out no other slides display afterwards, even though the dots show that the slides are advancing. Once the slider returns to the first slide, the same thing happens over again.

This can be seen clearly in the following JSFiddle: http://jsfiddle.net/relnemtzov/rhmfzzz1/

Removing "fade:true", shows that the slider works as required otherwise.

**Comment by patrickbjohnson** [comment]
Doesn't seem like this is fixed as I'm running into this issue currently. 

```

var el = $('.slider-container');

var mql = window.matchMedia("(min-width: " + config.breakpoints.small + "px)");
    mql.addListener(checkLayout);
    checkLayout(mql);

    function checkLayout(mql) {
      if (mql.matches) {
        $(el).slick('unslick');
      } else {
        $(el).slick({
          speed: 300,
          arrows:false,
          slidesToShow: 1,
          slidesToScroll: 1,
          fade: true,
        });
      }
    }
```

**Comment by anfibiacreativa** [comment]
I confirm this is still a bug in 1.5.7. Unfortunately can't link you to a live example.

**Comment by delirehberi** [comment]
i confirm this is still a bug 1.5.9

**Comment by ghenaat** [comment]
remove dir="rtl" its be ok.

**Comment by jonystorm** [comment]
+1

**Comment by dohahelmy** [comment]
This is still an issue.
Is there any solution without removing direction from html tag
