### ISSUE TITLE
Feature Request: multiple slides visible in vertical sliders

### ISSUE THREAD

**Issue by prosellen** [kenwheeler/slick#69]
Setting the slider to "vertical" sets slidesToShow and slidesToScroll back to 1.
It would be great to be able to have multiple slides displayed in a vertical slider aswell.

**Comment by noxin911** [comment]
I wish it would be possible to do scrolling up and down in a vertical carousel because i use it as a news overview and NO ONE will scroll horizontal if he want to move the list down ...

**Comment by kenwheeler** [comment]
@noxin911 you can scroll up and down. I added it.

**Comment by leggomuhgreggo** [comment]
@kenwheeler oh snap Is that supported now? I feel like I remember that being deprioritized a while back

**Comment by kenwheeler** [comment]
@leggomuhgreggo Yeah I broke and just did it.

**Comment by leggomuhgreggo** [comment]
@kenwheeler hot damn

**Comment by rodrigoAbril** [comment]
#3429 any way to make this work with variable height items like the option "variableWidth"
