### ISSUE TITLE
Slick unable to deal with multiple sliders

### ISSUE THREAD

**Issue by frankie-loves-jesus** [kenwheeler/slick#694]
If I have more than one slider, Slick.js will get confused and produce a whole bunch of broken prev/next links: http://jsfiddle.net/frank_o/Lr30ngo1/3/

I tried doing like `$(this).find('.option')` and `$(this).find('.prev_next')` but that gave me `Syntax error, unrecognized expression: [object Object]:not(.slick-cloned) in jquery-2.1.0.js:1429`: http://jsfiddle.net/frank_o/Lr30ngo1/4/

Anybody have any ideas?

**Comment by robertjwhitney** [comment]
Wait, that dirty fix seems poorly implemented, but still a reasonable idea. Why can't the script be responsible for this? Just attach a unique data attribute and then append based on that by default?

**Comment by JohneyCodeUp** [comment]
Here is how I solve it. Just reference "this" in each loop, and use it as selector for next and prev btns. Ofc, selector depend on you HTML structure. So here I will post just JS.

  $('.slider').each(function(){
    var slickInduvidual = $(this);

    slickInduvidual.slick({
      nextArrow: slickInduvidual.next().find('.right'),
      prevArrow: slickInduvidual.next().find('.left')
    });
  })

**Comment by DanielRuf** [comment]
@JohneyCodeUp thanks, this seems to fix it. I hoped it would work with multiple sliders which use the same markup.

**Comment by iamleighm** [comment]
@JohneyCodeUp Thanks. This solved it for me.

**Comment by saxsax1995** [comment]
@JohneyCodeUp solution make the prevArrow and nextArrow doesn't work well, it only work for the second slider, the first one doesn't. When i click the first slide arrow, the second slide move :'0.
Please help. This is what i've done til now.
`<div class="slick-custom">
	<div class="banner-slider" style="width: 80%;">
		  <div><img src="images/slide_1.jpg" style="width: 80%; height: 80%;"></div>
		  <div><img src="images/slide_2.jpg" style="width: 80%; height: 80%;"></div>
		  <div><img src="images/slide_3.jpg" style="width: 80%; height: 80%;"></div>
	</div>
	<div class="slick-arrows-custom">
		<i class="prev fa fa-arrow-circle-left"></i>
		<i class="next fa fa-arrow-circle-right"></i>
	</div>

	<div class="banner-slider" style="width: 80%;">
		  <div><img src="images/slide_1.jpg" style="width: 80%; height: 80%;"></div>
		  <div><img src="images/slide_2.jpg" style="width: 80%; height: 80%;"></div>
		  <div><img src="images/slide_3.jpg" style="width: 80%; height: 80%;"></div>
	</div>
	<div class="slick-arrows-custom">
		<i class="prev fa fa-arrow-circle-left"></i>
		<i class="next fa fa-arrow-circle-right"></i>
	</div>
</div>

<script type="text/javascript" src="jquery/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="jquery/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="slick-1.8.1/slick/slick.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function(){
      $('.banner-slider').each(function(){
	      	$(this).slick({
	      	 autoplay:true,
	      	 arrows: true,
	      	 prevArrow: $('.prev'),
	     	 nextArrow: $('.next'),
	     	 responsive: [
		     {
		      breakpoint: 480,
		      settings: {
		      	dot: true
		     	}
	      	 }
	      ]
	    });
	});
  });  
  </script>`

**Comment by chancer4** [comment]
@saxsax1995 I had to tweak it since my arrows were siblings but not the next sibling. [$('.slick').each(function(){
      var slickIndividual = $(this);
      slickIndividual.slick({
        dots: true,
        arrows: true,
        infinite: true,
        fade: true,
        appendDots: slickIndividual.next('.slick-pager'),
        nextArrow: slickIndividual.siblings('.next'),
        prevArrow: slickIndividual.siblings('.prev')
      });
    })](url)
