### ISSUE TITLE
Feature request: Multiple rows

### ISSUE THREAD

**Issue by haakemon** [kenwheeler/slick#70]
Hi.

Would it be possible to implement an option to have multiple rows in a slider? See attached image..

![image](https://cloud.githubusercontent.com/assets/2082481/2595004/2b57ac46-ba95-11e3-9110-4007247bb8d4.png)

**Comment by baqirfarooq** [comment]
$('.carousel').slick({
    dots: true,
    slidesPerRow: 3,
    rows: 2,
    responsive: [
    {
      breakpoint: 478,
      settings: {
        slidesPerRow: 1,
        rows: 1,
      }
    }
  ]
});
