### ISSUE TITLE
Partially solved - breakpoint not use the real width of the window, if into the page is present the scrollbar

### ISSUE THREAD

**Issue by Maofree** [kenwheeler/slick#701]
hi
if I use a solution like this:
            responsive: [
                {
                    breakpoint: 991,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 767,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                    }
                }
            ]

if the page is long with the lateral scrollbar, it is necessary to use this values:
            responsive: [
                {
                    breakpoint: 979,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 755,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                    }
                }
            ]

it is due from the scrollbar's width, normally because it is used $(window).width()
to solve this problem you can use:
var w=window,d=document,e=d.documentElement,g=d.getElementsByTagName('body')[0],x=w.innerWidth||e.clientWidth||g.clientWidth;

in this mode it is possible to use the same value of the @media css values

byeeee

**Comment by simeydotme** [comment]
###Amazing.
This was absolutely enthralling. :coffee: 
Made my evening. Thank you so much @kenwheeler  and @maofree ... I even read it out loud to the :dancer: in funny voices!!

http://www.reddit.com/r/perfectloops/comments/3jcvfo/plankton_slow_clap/

:smile: :joy:
