### ISSUE TITLE
White space displayed after scrolling through last slide when infinite is false

### ISSUE THREAD

**Issue by WtheFourth** [kenwheeler/slick#71]
When using a carousel that shows multiple slides at a time but only scrolls one, the user can scroll until the last slide is the only slide visible.

See: http://jsfiddle.net/Lbkfv/

**Comment by nawrasbaghdadi** [comment]
hi Ken,
i'm facing issue that in wide screen all the element of the slider will appear with some white space at the end  and pressing next button will show more white space ,
http://jsfiddle.net/nawras11/ofesgwb0/

**Comment by JSeligsohn** [comment]
+ 1 to nawrasbaghdadi - having the same issue.

**Comment by horatiua** [comment]
+1

**Comment by rameezwp** [comment]
> Excellent solution for the spacing issues, @kenwheeler. That definitely helped. But I'm still getting the problem of it jumping past the last slide at the end of the infinite loop. Any ideas?
> 
> Check it out:
> http://sacredfirefoundation.org/sacred-fire-magazine
> 
> I've set it to:
> infinite: true,
> slidesToShow: 5,
> slidesToScroll: 4,
> 
> And thanks for being there to help debug things like this!

Any solution to this issue?

**Comment by Sara6865** [comment]
hi ken,I've this problem too
its my code:
   $('.video-cards-container').slick({
        dots: false,
        infinite: false,
        speed: 300,
        slidesToShow: 6,
        swipeToSlide: true,
        rtl: true,
        responsive: [
            {
                breakpoint: 1400,
                settings: {
                    slidesToShow: 6,
                }
            },
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 5,
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 4,
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 3,
                }
            }
        ]
    });
when i change infinite to false,at the end shows empty box before the first slide.
its my sites link
http://filmmarket.ir
wuold you check it plaese????

**Comment by Sara6865** [comment]
![فیلم مارکت   شبکه جهانی فیلم مارکت](https://user-images.githubusercontent.com/47073618/61689291-2ad8b900-ad3c-11e9-89c9-1c75a690368d.png)

**Comment by arshil-ctas** [comment]
i had same issue of white space aftr the last slided slided and gone from viewport, it seems even after 10 years there is no solution for this

**Comment by Amooryjubran** [comment]
+1
