### ISSUE TITLE
Event for first and last slide

### ISSUE THREAD

**Issue by sidneydobber** [kenwheeler/slick#715]
Is there an event that fires on first or last slide? In a project I'm working on there is a requirement to hide/disable the previous and next button on the last and first slide.

**Comment by gvdm** [comment]
Is it possible to have these events for eventualities not considered by slick? For example, I'm working on a project, and when the end of a range is reached I want to load more items from the data set via AJAX to expand the slides.

**Comment by kenwheeler** [comment]
Not at the moment, but in 1.4 I'm going to be redoing the entire event system so:

if you call slick with an object like:
```
myElement.slick()
myElement.slick({option: value})
```
it will work just like it always has. But if you use a string:
```
myElement.slick('addSlide', '<div></div>')
```
It will do the equivalent of:
```
myElement.slickAdd('<div></div>')
```

I will also be adding listenable events so you can do things like:

```
myElement.on('slideChanged', callback)
myElement.on('initialized', callback)
```
and so on. It should provide a neater, more terse and flexible syntax moving forward. I believe the advantages outweigh the cost of a breaking change so 1.4 will introduce it.

**Comment by gvdm** [comment]
Sounds good, how will this provide the ability to know when the user is sliding left from first or right from last? Also, tangentially related will there be a way to ask for the number of slides? At the moment you can query for the current slide but there is no way of knowing if this is the last slide using the slick API if there are a variable number of slides.

**Comment by TheNaderio** [comment]
Is this really done? I still got this error in 2018. The `slick-arrow` is automatically given `display:block` as an inline statement.
And I really dont like `!important`in my Styles ;)

```
mySlider = $('.my-slider').slick({
        vertical: true,
        swipe: false,
        infinite: false,
        slidesToShow: 4,
        slidesToScroll: 1,
        speed: 250,
        prevArrow: '<div class="slick-prev-wrap"><button type="button" class="slick-prev"><i class="far fa-chevron-up"></i></button></div>',
        nextArrow: '<div class="slick-next-wrap"><button type="button" class="slick-next"><i class="far fa-chevron-down"></i></button></div>'
    });
```

**Comment by sandeep2244** [comment]
How to hide arrow buttons on last slide .  I have used my custom button classes ... Not slick-next, slick-prev .. how to add event on last slide through arrow buttons ?

**Comment by Chrisser73** [comment]
> How to hide arrow buttons on last slide . I have used my custom button classes ... Not slick-next, slick-prev .. how to add event on last slide through arrow buttons ?

I've build a small jQuery script for that case. Hape that helps
**Replace** "your-arrow-class" with your arrow class 😄 
**Replace** "d-none" with your "display: none"-class 😃 

`
/**************************************************
 * Helper Functions
 ************************************************/
function addEachClassBySubClass(elem, searchClass, classToAdd){
	elem.find(searchClass).each(function () {
		$(this).addClass(classToAdd);
	});
}

function removeEachClassBySubClass(elem, searchClass, classToRemove){
	elem.find(searchClass).each(function () {
		$(this).removeClass(classToRemove);
	});
}

/**************************************************
 * Removes Arrows if there is enough space left
 ************************************************/
function removeNonNecessaryArrows($sliderObj) {
	if ($sliderObj.length > 0) {
		let childrenWidth = 0;
	
		$sliderObj.find('.slick-track').children().each(function () {
			childrenWidth += $(this).outerWidth(true);
		});
	
		$sliderObj.each(function () {
			if (childrenWidth < $(this).width()) {
				addEachClassBySubClass($(this), '.your-arrow-class', 'd-none');
			} else {
				removeEachClassBySubClass($(this), '.slick-arrow', 'd-none');
			}
		});
	}
}`
