### ISSUE TITLE
initialSlide not working in responsive settings.

### ISSUE THREAD

**Issue by AjatuksenTasolla** [kenwheeler/slick#755]
Hi,

I noticed that the initialSlide setting doesn't work thru responsive settings.

Here is a jsfiddle of the problem: http://jsfiddle.net/9p3agprL/38/

**Comment by jmlivingston** [comment]
I am having the same issue and have worked around it with the following hack. You can replace the previous and next cases in the Slick.prototype.changeSlide method. This isn't that pretty, but it fixes the issue I was having. That being said, this assumes infinity is false.

Sadly this editor isn't honoring the "pre" tag, so you may have to see the source for the html.

SOLUTION:
case 'previous':
    slideOffset = indexOffset === 0 ? _.options.slidesToScroll : _.options.slidesToShow - indexOffset;
    if (_.slideCount > _.options.slidesToShow) {
        //ORIGINAL - _.slideHandler(_.currentSlide  - slideOffset, false, dontAnimate);
        //HACK START
        var slideTo = _.currentSlide - slideOffset;
        if (!_.options.infinite && slideTo < 0) {
            slideTo = 0;
        }
        _.slideHandler(slideTo, false, dontAnimate);
        //HACK END
    }
    break;

case 'next':
    //ORIGINAL - slideOffset = indexOffset === 0 ? _.options.slidesToScroll : indexOffset;
    //HACK START
    slideOffset = _.options.slidesToShow;
    //HACK END
    if (_.slideCount > _.options.slidesToShow) {
        //ORIGINAL - _.slideHandler(_.currentSlide + slideOffset, false, dontAnimate);
        //HACK START
        var slideTo = _.currentSlide + slideOffset;
        if (!_.options.infinite && (slideTo + slideOffset) > _.slideCount) {
            slideTo = _.slideCount - slideOffset;
        }
        _.slideHandler(slideTo, false, dontAnimate);
        //HACK END                    
    }
    break;

HTML
<pre>
<div id="pager" class="slider">
    <div data-url="#/1">
        <div class="slider-container">1</div>
    </div>
    <div data-url="#/2">
        <div class="slider-container">2</div>
    </div>
    <div data-url="#/3">
        <div class="slider-container">3</div>
    </div>
    <div data-url="#/4">
        <div class="slider-container">4</div>
    </div>
    <div data-url="#/5">
        <div class="slider-container">5</div>
    </div>
    <div data-url="#/6">
        <div class="slider-container">6</div>
    </div>
    <div data-url="#/7">
        <div class="slider-container">7</div>
    </div>
    <div data-url="#/8">
        <div class="slider-container">8</div>
    </div>
    <div data-url="#/9">
        <div class="slider-container">9</div>
    </div>
    <div data-url="#/10">
        <div class="slider-container">10</div>
    </div>
    <div data-url="#/11">
        <div class="slider-container">11</div>
    </div>
    <div data-url="#/12">
        <div class="slider-container">12</div>
    </div>
    <div data-url="#/13">
        <div class="slider-container">13</div>
    </div>
    <div data-url="#/14">
        <div class="slider-container">14</div>
    </div>
    <div data-url="#/15">
        <div class="slider-container">15</div>
    </div>
    <div data-url="#/16">
        <div class="slider-container">16</div>
    </div>
    <div data-url="#/17">
        <div class="slider-container">17</div>
    </div>
    <div data-url="#/18">
        <div class="slider-container">18</div>
    </div>
    <div data-url="#/19">
        <div class="slider-container">19</div>
    </div>
    <div data-url="#/20">
        <div class="slider-container">20</div>
    </div>
    <div data-url="#/21">
        <div class="slider-container">21</div>
    </div>
    <div data-url="#/22">
        <div class="slider-container">22</div>
    </div>
    <div data-url="#/23">
        <div class="slider-container">23</div>
    </div>
    <div data-url="#/24">
        <div class="slider-container">24</div>
    </div>
    <div data-url="#/25">
        <div class="slider-container">25</div>
    </div>
</div>
</pre>

JAVASCRIPT
$('#slider').slick({
    infinite: false,
    centerMode: true,
    initialSlide: 8,
    responsive: [{
        breakpoint: 1680,
        settings: {
            slidesToShow: 8,
            centerMode: false,
            slidesToScroll: 8
        }
    }, {
        breakpoint: 1480,
        settings: {
            slidesToShow: 8,
            centerMode: false,
            slidesToScroll: 8
        }
    }, {
        breakpoint: 1280,
        settings: {
            slidesToShow: 6,
            centerMode: false,
            slidesToScroll: 6
        }
    }, {
        breakpoint: 1152,
        settings: {
            slidesToShow: 6,
            centerMode: false,
            slidesToScroll: 6
        }
    }, {
        breakpoint: 1024,
        settings: {
            slidesToShow: 5,
            centerMode: false,
            slidesToScroll: 5
        }
    }, {
        breakpoint: 896,
        settings: {
            slidesToShow: 5,
            centerMode: false,
            slidesToScroll: 5
        }
    }, {
        breakpoint: 768,
        settings: {
            slidesToShow: 4,
            centerMode: false,
            slidesToScroll: 4
        }
    }, {
        breakpoint: 640,
        settings: {
            slidesToShow: 3,
            centerMode: false,
            slidesToScroll: 3
        }
    }, {
        breakpoint: 480,
        settings: {
            slidesToShow: 2,
            centerMode: false,
            slidesToScroll: 2
        }
    }]
});

CSS
.slider-container {
    background-color: green;
    text-align: center;
    font-size: 40px;
    color: white;
    border: 3px solid white;
    padding-top: 30px;
    padding-bottom: 30px;
    cursor: pointer;
}
.pager-active .slider-container {
    background-color: orange;
}

**Comment by proimage** [comment]
This still seems to be broken, at least when using this init code:

```
	$(".tabs").slick(
	{
		slidesToShow: 3,
		slidesToScroll: 1,
		asNavFor: '.schedule',
		centerMode: true,
		centerPadding: '24px',
		focusOnSelect: true,
		mobileFirst: true,
		vertical: true,
		responsive:
		[
			{
				breakpoint: 768,
				settings:
				{
					centerPadding: '50px',
					vertical: false
				}
			}
		]
	});
	$(".schedule").slick(
	{
		slidesToShow: 1,
		slidesToScroll: 1,
		arrows: false,
		asNavFor: '.tabs',
		mobileFirst: true
	});
```

Is there any chance that the fix supposedly merged earlier on doesn't cover `asNavFor` sliders?

**Comment by MatthiasPeltzer** [comment]
Hi there... :) 
I am using 1.6.0 and this still seems to be broken:

when i reload or intial load the page in a responsive small view it does not show the corresponding .slider-for-Container and also not the last slide-nav wich is in my case 12

`$('.slider-nav').slick({
        initialSlide: 12,
        slidesToShow: 5,
        slidesToScroll: 1,
        asNavFor: '.slider-for',
        dots: false,
        centerMode: false,
        infinite: false,
        focusOnSelect: true,
        responsive: [
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 3
                }
            },
            {
                breakpoint: 360,
                settings: {
                    slidesToShow: 2
                }
            }
        ]
    });

    $('.slider-for').slick({
        initialSlide: 12,
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: false,
        fade: true,
        infinite: false,
        adaptiveHeight: true,
        asNavFor: '.slider-nav'
    });`

`<h2>Slider Syncing</h2>
<div class="slider slider-for">
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
    <div><h3>5</h3></div>
    <div><h3>6</h3></div>
    <div><h3>7</h3></div>
    <div><h3>8</h3></div>
    <div><h3>9</h3></div>
    <div><h3>10</h3></div>
    <div><h3>11</h3></div>
    <div><h3>12</h3></div>
</div>

<div class="slider slider-nav">
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
    <div><h3>5</h3></div>
    <div><h3>6</h3></div>
    <div><h3>7</h3></div>
    <div><h3>8</h3></div>
    <div><h3>9</h3></div>
    <div><h3>10</h3></div>
    <div><h3>11</h3></div>
    <div><h3>12</h3></div>
</div>`

is there a way to fix it? Many thanks in advance. And thx for the slider in general!

**Comment by Moworks** [comment]
Got it to work by doubling the slidestoscroll:
      infinite: true,
        speed: 500,
        slidesToShow: 7,
	        initialSlide: 14,
         dots: true,
           arrows: false,
        appendDots: $(".new_slider"),
        slidesToScroll: 7,

**Comment by habermaor** [comment]
Still having this bug - needed different initialSlide in responsive cnfiguration. with different rows and slidesPerRow. I eventually solved it using the slickGoTo method, inside an 'init' event listener.

**Comment by jacklinwood** [comment]
This is still not working. I want to use on init function to set intialSlide dynamically but I have used a set number for my example:
```
$('#product_thumbnails_slider').on('init', function(event, slick, currentSlide, nextSlide) {
	slick.options.initialSlide = 2;
});

$('#product_thumbnails_slider').slick({
	slidesToShow: 4,
	speed: 600,
	pauseOnHover: false,
	pauseOnFocus: false,
	arrows: false,
	asNavFor: '#product_gallery_slider',
	focusOnSelect: true,
	responsive: [
		{
			breakpoint: 768,
			settings: {
				slidesToShow: 2
			}
		}
	]
});
```

If I add or change any other option on my on init function, it works. But it doesn't work for initialSlide.

Any ideas?

**Comment by umut-ozdemir-c** [comment]
Any ideas about a workaround?
