### ISSUE TITLE
Faded out slide still interactable.

### ISSUE THREAD

**Issue by oliverbenns** [kenwheeler/slick#761]
Hey, thanks for the epic slider. We've used it for a few projects now and it's worked flawlessly.

I'm using a fading slider `{ fade: true }` but due to the CSS transition the previous slide is still interactable when the slides have a transparent background. I can still press buttons and what not from the previous slide.

This is because the css sets the slide to have an opacity of 0.

So to workaround this I originally decided to set `display: none;` onto not-active slides using `onAfterChange`. But this messed up the calculations of the slider as it technically doesn't have a width and height at this point. I also tried `visibility: hidden;` but this still makes it interactable.

My current fix for my project was to set a solid colour background with a min-height on the slides but of course this isn't ideal.

**Browser:** Chrome

Thanks.

**Comment by klihelp** [comment]
I have this issue, with these settings:
```
slidesToShow: 1,
slidesToScroll: 1,
adaptiveHeight: false,
fade: true,

```
