### ISSUE TITLE
.bind() breaking IE8

### ISSUE THREAD

**Issue by kenwheeler** [kenwheeler/slick#769]
```
_.$list.on('click.slick', _.clickHandler.bind(this));
```

Breaks IE8, because Microsoft is a god damn joke of a company that just wont play ball with web standards...

**Comment by ubiko** [comment]
I'm still getting this issue in IE8
`Object doesn't support property or method 'bind'`
:<

**Comment by vanWezel** [comment]
@ubiko @kenwheeler I had the same issue with ie8 with the 1.5 version... I'm using 1.4 now. This solves the problem. Is the bind function in the slick librarie deprecated or didn't you copy you're last fix for the problem?

**Comment by vanWezel** [comment]
Never mind, version 1.5.5 fixed my problem..
