### ISSUE TITLE
I'm confused by the onAfterChange option

### ISSUE THREAD

**Issue by dan-diaz** [kenwheeler/slick#77]
the doc shows this:

```
onAfterChange(this, index)
```

So how do I employ it?
What is 'this'?
How do I pass the index to my function?
currently, I'm doing this

```
var afterChangeFunc = function(index) {
    // do something;
}
mySlideshow.slick({
    autoplay: true,
    onAfterChange : afterChangeFunc(index)
});
```

but this is breaking.

**Comment by simmerdesign** [comment]
For anyone else bumping into this issue + furiously googling for a solution + wondering why `onAfterChange` isn't working: see https://github.com/kenwheeler/slick#events

The onAfterChange callback has been deprecated in favor of the `afterChange` event.
