### ISSUE TITLE
Unslick does not destroy slick-list element when $slides is empty

### ISSUE THREAD

**Issue by vyrotek** [kenwheeler/slick#770]
If you call slick() on an element which contains no slide elements and then call unslick() it will leave behind the "slick-list" wrapper element.

It looks like this is because $slides is empty and therefore calling _.$slides.unwrap().unwrap(); (Line 609) is unable to destroy the "slick-list" element.

This is problematic because if you call slick() again it will turn the "slick-list" element into a slide.

Here is an example of the problem: http://jsfiddle.net/1v9bmq07/3/
Clicking the Slick button will show you the HTML for 2 examples. 
The top "Bad" one is created without slides and the bottom "Good" one does contain slides.
Clicking the Unslick button will demonstrate the HTML that is left-over which should be removed.

**Comment by kenwheeler** [comment]
Fixed on dev
