### ISSUE TITLE
updateArrows() doesn't work properly with centerMode true and slidesToShow 1

### ISSUE THREAD

**Issue by robinmalgoire** [kenwheeler/slick#775]
When 
  centerMode: true,
  slidesToShow: 1,
  infinite: false,
  arrows: true

updateArrows() doesn't add the class slick-disabled to $nextArrows
For one slide visible _.currentSlide is equal and not superior to _.slideCount - _.options.slidesToShow + centerOffset
(line 1940)

http://jsfiddle.net/b17nozu7/3/

I will do a pull request tonight.
Cheers

(good work btw)

**Comment by kenwheeler** [comment]
Fixed on dev
