### ISSUE TITLE
Feature request: Initial Delay

### ISSUE THREAD

**Issue by matthewlein** [kenwheeler/slick#776]
I like this feature in other carousels/cycles. New option, delay. Number. An initial timeout that runs before you kick off your auto advance autoPlayTimer interval.

Use case is on page load, users need a few second(s) to orient themselves before a slider interval should kick in.

**Comment by jan1980** [comment]
Guys, doesn't seem to work anymore in jsfiddle?

**Comment by simeydotme** [comment]
That's because the API methods changed. The logic is still sound.

```js

$(".slider").slick({
    autoplay: true,
    autoplaySpeed: 1000
}).slick("pause");

var initialDelay = 3000;

$(document).one("mousemove touchstart", function() {
    setTimeout(function() {
        $(".slider").slick("play");
    },initialDelay);
});

```

**Comment by flowdee** [comment]
Method names changed. Currently it should look like:
```javascript
var slider = $('.slider');

slider.slick({
    autoplay: true,
    autoplaySpeed: 1000
}).slick("slickPause");

var initialDelay = 3000;

setTimeout(function() {
    slider.slick("slickPlay");
},initialDelay);
```
