### ISSUE TITLE
How to set first nav slider item as active

### ISSUE THREAD

**Issue by jcpeden** [kenwheeler/slick#777]
I'm using two slick carousels, one is the nav for the other. The first displays one of three images that the user can cycle through. The second displays the three taglines relating to each image.

I'm able to navigate images using the navigation slides but when the page loads, all of the nav slides are active.

How can I set the first slide only to have class slick-active?

The screen shots show page load and what should happen when only a single nav item is selected.

![screen shot 2014-11-11 at 17 10 49](https://cloud.githubusercontent.com/assets/1623848/4997337/c3091680-69c5-11e4-9152-b257d610024a.png)
![screen shot 2014-11-11 at 17 10 59](https://cloud.githubusercontent.com/assets/1623848/4997338/c312ee80-69c5-11e4-8b3b-ac2fd9c6ec79.png)

**Comment by estebandinamarca** [comment]
Now the use is with afterChange:
How to set an active class for a nav?
Is not working here code ("alert hello" is working) :

```
        $('.single-item').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: true,
            autoplay: false,
            infinite: true,
            speed: 300,
            asNavFor: '.slider-nav'
        });
        
        $('.slider-nav').slick({
          slidesToShow: 4,
          slidesToScroll: 0,
          asNavFor: '.single-item',
          dots: false,
          centerMode: true,
          focusOnSelect: true,
          arrows: false
        });
    
        $('.single-item').on('afterChange', function (slickSlide,i) {
            $('.slider-nav .slick-slide').removeClass('slick-active');
            $('.slider-nav .slick-slide').eq(i).addClass('slick-active');
            alert("Hello");
       });        
```

This is working fine:
```       
        //set active class to first slide
        $('.slider-nav .slick-slide').eq(0).addClass('slick-active');
```
