### ISSUE TITLE
Graceful slick js loading

### ISSUE THREAD

**Issue by ghost** [kenwheeler/slick#779]
When a page with slickjs carousel is loading, the images are stacked together crashing the whole layout. My question is how can I add a gif loader to the slick carousel while the page is loading the necessary elements like js and css.

Foundation did something like this on their version of Orbit slider 2 versions back and I wonder if I could do this on slick.js also.

**Comment by adrien-be** [comment]
+1 nice inspiration

**Comment by aronmoshe-m** [comment]
+1 appreciated the idea
