### ISSUE TITLE
Remove Implicit Compass Dependency

### ISSUE THREAD

**Issue by Undistraction** [kenwheeler/slick#780]
Slick currently calls `image-url` using three arguments. This signature is compass-specific, so if a (Rails) project that uses Slick isn't using compass this will result in an error.

```
Sass::SyntaxError at /
wrong number of arguments (3 for 1) for `image-url'
```

Please switch to calling `image-url` with a single argument as this is supported by both Compass and Sprockets.

Line 20 of slick.scss:

```
@function slick-image-url($url) {
  @if function-exists(image-url) {
    @return image-url($url); // Here
  }
  @else  {
    @return url($slick-loader-path + $url);
  }
}
```

**Comment by kenwheeler** [comment]
Fixed on dev

**Comment by Undistraction** [comment]
Thanks @kenwheeler
