### ISSUE TITLE
Arrows have kind of issue

### ISSUE THREAD

**Issue by Matew92** [kenwheeler/slick#787]
Hi,
thank u for this amazing library, i really need in my project. 

However i found an issue when the <samp>focusOnSelect</samp> is set to <samp><b>true</b></samp>  and <samp>infinite</samp>, <samp>centerMode</samp> are set to <samp><b>false</b></samp>. when the slider is in the middle of the slides, arrows do not seem to work, I tried to debugging the library and I noticed that <samp>targetLeft</samp> and <samp>slideLeft</samp> remain the same and then the slider will not move. 

this is my slider

![schermata 2014-11-13 alle 17 22 49](https://cloud.githubusercontent.com/assets/3671423/5031808/bdba09b0-6b59-11e4-98f1-11cd955deb43.png)

but the arrows don't work 

thank u in advance

**Comment by kenwheeler** [comment]
Fixed on dev
