### ISSUE TITLE
Default slide selector

### ISSUE THREAD

**Issue by dhyegofernando** [kenwheeler/slick#789]
Currently the slick uses an setting called ``slide`` to select its children elements, but I would to use different tag from ``<div>`` without pass it in settings.

A default setting option could be quite good like:
```javascript
...
slide: $(element).children(),
...
```

Thank you in advance.

**Comment by rafaellyra** [comment]
:+1:

**Comment by kenwheeler** [comment]
children is now the default. No selector is necessary.
