### ISSUE TITLE
Slick with Foundation Clearing Lightbox

### ISSUE THREAD

**Issue by niallobrien** [kenwheeler/slick#796]
Hi,
I'm trying to use Slick with Foundation's Clearing Lightbox but am not having much luck.
My html is as Foundation requires, and Slick is working fine with the list-items ie. the images are sliding fine with a ul.
However, when I click on an image, Clearing Lightbox is not firing correctly (and I think it may be because of the extra elements Slick places within the ul) and the slick slider disappears: Uncaught TypeError: Cannot read property 'templates' of undefined.

I then tried placing the data-clearing attribute onto the li's parent div (which is inserted by Slick) and it just links off to the image.

Have you any suggestion for getting these libraries to play nicely together?

http://foundation.zurb.com/forum/posts/20794-

**Comment by hos69shah** [comment]
@niallobrien I had a problem like you, but seems the best way is the way you said, I had to thank you for this idea. everything done!

**Comment by ramirohd** [comment]
@niallobrien you inspired me! I had to thank you too. Some criativity is the deal! :)
