### ISSUE TITLE
Issue with progressiveLazyLoading

### ISSUE THREAD

**Issue by bluerouse** [kenwheeler/slick#800]
I remarked some issues here, but i wasn't able to reproduce in a jsFiddle.

There are some cases, where the load triggers the error-function from https://github.com/kenwheeler/slick/pull/540. Even if there are NO 404-Requests. So this causes the trigger of error and success for the same image. 

If the error-callback is thrown for one image, and another one is still having data-lazy, but not yet triggered error/success, then the load-event is attached again to the same image. This is causing some infinite Loop in my IE (but couldn't reproduce in jsFiddle, sorry :-( )

So, i would suggest to removeAttr earlier:
```javascript
targetImage.attr('src', targetImage.attr('data-lazy')).removeAttr('data-lazy').removeClass('slick-loading').load(function() {
    _.progressiveLazyLoad();
})
.error(function () {
    _.progressiveLazyLoad();
});
```
Or is there a reason why waiting with? Actually, the src is set, so there is no need to do this again, right?

**Comment by kenwheeler** [comment]
I can't reproduce this. If you can fiddle a reduced test case and reproduce it it would be helpful.
