### ISSUE TITLE
onAfterChange doens't fire

### ISSUE THREAD

**Issue by fabioel** [kenwheeler/slick#803]
Hi!
I have set up a div to be the slick element and I wanted to enhance it with a couple of functions that are called when the slide changes, but thats the problem. Apparently, onAfterChange only fires when the slick is initiated and never again.
Maybe I did something wrong in the initiliaization here is my code:

$('#contentCarousel').slick({
                            dots: true,
                            infinite: false,
                            speed: 300,
                            slidesToShow: 1,
                            adaptiveHeight: true,
                            onAfterChange: alert("changed")
                        });

**Comment by robsilva** [comment]
Can anyone tell me why this never fires? Do any of my configuration parameters disable that method?

	$('#questions').slick({
	  infinite: false,
	  slidesToShow: 1,
	  slidesToScroll: 1,
	  dots: false,
	  arrows: false,
	  swipe: false,
	 	onAfterChange: function(e) {
	 		console.log("This never fires");
    }
	});
