### ISSUE TITLE
Slick hides if there is only one slide present

### ISSUE THREAD

**Issue by SunilrajChavan** [kenwheeler/slick#809]
Hi,

I have dynamic content on which slick needs to be enabled. But in few cases when there is only one item present, slick adds Transform 3d of negative value, which hides the content to the left. Please suggest some solution.

Thanks..

**Comment by thebeeph** [comment]
I see this is closed now. However I'm still experiencing a similar issue, and I'm wondering if it's a bug to be addressed. Has this been reported elsewhere?
