### ISSUE TITLE
gallery slides through every item when RTL is set in IE9

### ISSUE THREAD

**Issue by malde** [kenwheeler/slick#816]
If you use the slider in RTL mode (in IE9), the gallery slides through all items in the gallery before stopping at the right one. This only seems to be happening in IE9, Chrome etc. works fine.

Just check the demo RTL slider on http://kenwheeler.github.io/slick/ on IE9.

**Comment by ahmadalfy** [comment]
Confirmed, using IE emulator. Will look into it

**Comment by ahmadalfy** [comment]
@kenwheeler it is related to https://github.com/kenwheeler/slick/issues/451 because IE9 and below doesn't support CSS3 transitions. I tried using the latest fix and it works flawlessly now.

**Comment by kenwheeler** [comment]
Awesome
