### ISSUE TITLE
fadeOut option?

### ISSUE THREAD

**Issue by oskarrough** [kenwheeler/slick#817]
Hi, thanks for the plugin! How about we help each other implement a fadeOut effect where the background doesn't appear while the slides are half through the animation?

Example of the issue: http://jsbin.com/kekaji/2/edit?html,js,output

Cycle2 implements a default 'fade' effect, like Slick, but also a 'fadeOut', which is exactly what I'm looking for. I'd even argue for fadeOut being the default as no one wants to see the background while fading.

**Comment by kenwheeler** [comment]
I may default this
