### ISSUE TITLE
Feature Request for slickSetOption

### ISSUE THREAD

**Issue by jimmymorris** [kenwheeler/slick#821]
I would love the feature to add an objects worth of options. Example:

```javascript
$('.fancy-rotation').slickSetOptions({
    'dots': 'false',
    'draggable', 'false'
}, true);
```

**Comment by erdemildiz** [comment]
var config = {
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: false,
        autoplaySpeed: 6000,
        arrows: true,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    dots: false
                }
            },
            {
                breakpoint: 600,
                settings: {
                    arrows: false
                }
            },
            {
                breakpoint: 480,
                settings: {
                    arrows:false
                }
            }
        ]};

    //mansetSlick.slickSetOption('arrows', true, true);
    //mansetSlick.slickSetOption('prevArrow', '<button type="button" class="slider_btn btn_prev"><span class="fa fa-chevron-left"></span></button>', true);
    //mansetSlick.slickSetOption('nextArrow', '<button type="button" class="slider_btn btn_next" ><span class="fa fa-chevron-right"></span></button>', true);
    mansetSlick.slickSetOptions(config, true);

Doesn't work, why? What is the problem that I couldn't see.
