### ISSUE TITLE
Slick slider and IE 11 not working

### ISSUE THREAD

**Issue by davehallowell** [kenwheeler/slick#841]
Hi, I am using slick slider v. 1.3.13 and Internet Explorer 11.  I really like the slider so thanks for all the hard work Mr. Wheeler. For some reason my three images just stack on top of each other like something in the .js is broken but I don't see any errors in the developer tool console.  The page works correctly using other browsers, firefox, chrome, opera and safari all work correctly.  Here is a URL to an example page:  https://pitest.southeast.edu/homepage/slidetest.html

JSLint shows some problems, but it works in other browsers so the errors must not be too great.  Of course IE plays by their own rules so . . .

Any help would be appreciated. 
-Thanks

**Comment by jkozma** [comment]
I thought I had the same problem, but it was just a matter of the default security settings for IE not allowing scripts for local files. When I clicked "Allow blocked content" in the warning message box, the slideshow worked as expected.

**Comment by martinhilary** [comment]
> Hi Ken. Just wanted to let you and anyone else interested, the issue was with IE and compatibility mode. Our IT staff set a group policy to put IE in compatibility mode for our intranet to work. This made IE operate like IE7 causing my CSS to break. In particular, media queries and border-box. Adding the attached code
> ![capture](https://cloud.githubusercontent.com/assets/3870566/5342621/134f1752-7ec5-11e4-9d51-3a3b68832641.JPG)
> as the _**first meta tag_* in the html fixed the issue. It is extremely important that the code is the first meta tag otherwise, it does not work.

**Comment by DanAtShenTech** [comment]
I looked at the IE console and it showed a syntax error.  I was initializing with an arrow function:

```
 $(()=> {
    $('#slider').slick({
        slidesToScroll: 1,
        ...
}
```
Changed the arrow function to `$(function() {...})` and it worked.

**Comment by jurgenhaas** [comment]
Just ran across this problem too and my sliders contained HTML containers with images and text. They got completely messed up as the width calculation always got it wrong. I though, defining the width for the `.slick__slider` would help - it didn't.

Then I found out that adding the following to my CSS does the trick and now EVERYTHING is working just fine even on IE11:

```
.slick, .slick-wrapper {
  width: 100%;
}
```

Not: this is based on v1.8.0 of this library.

**Comment by sameen111** [comment]
i have some problem on IE about slick slider so how to solve that issue?? it's urgent for me 
https://hotelica-pro.cyclonethemes.com/

**Comment by FlamingFox911** [comment]
@DanielSwain Thank you for this. IE has a problem where it can't process ES6 javascript, so stuff like arrow functions and ` (grave) characters cause issues. After throwing the code in Babel transpiler to convert to ES5, it works.
