### ISSUE TITLE
Exception on 'slickGetOption' in 'onAfterChange' event

### ISSUE THREAD

**Issue by alexrussell** [kenwheeler/slick#846]
Paring down the use-case it looks like using `jQueryElement.slickGetOption('whatever')` inside the `onAfterChange` event when using the `responsive` option seems to break.

Exception:

    TypeError: Cannot read property 'options' of undefined

[Fiddle](http://jsfiddle.net/e1jjL5xL/)

If you get rid of the `responsive` option, or put the `sickGetOption` after the initial slick() call (but not in the event handler) it seems happy.

A weird one, any ideas?

**Comment by kenwheeler** [comment]
Fixed in 1.4
