### ISSUE TITLE
Conflict with FullPage.js

### ISSUE THREAD

**Issue by zoomtronic** [kenwheeler/slick#848]
Hi !
I love your slider but i can't make it work with the nice "FullPage.js" plugin..
(https://github.com/alvarotrigo/fullPage.js or http://alvarotrigo.com/fullPage ) 

This a jsfiddle with only fullpage.js, you can slide the two sections easily
http://jsfiddle.net/zuzd85fc/1/

but when i add Slick, there is a conflict and we can't slide anymore.
http://jsfiddle.net/zuzd85fc/2/

Can you help me to fix this ?

Thanks !

**Comment by chrismacho** [comment]
Thought I'd save any future hair-puller a little time by saying add `table-layout: fixed;` to any nested layout divs inside your full page .section divs as well and it should sort it out.

Thanks Ken.
