### ISSUE TITLE
slickGoTo() documentation error

### ISSUE THREAD

**Issue by berelig** [kenwheeler/slick#850]
Documentation here: http://kenwheeler.github.io/slick/

`slickGoTo()`
Arguments: int : slide number, boolean: **should animate**

Bolded part needs to be changed to **should _not_ animate** or **don't animate**

**Comment by theroux** [comment]
This was never added or is no longer on the documentation site (http://kenwheeler.github.io/slick/)

It's still:

> slickGoTo
int : slide number, boolean: should animate
Navigates to a slide by index
