### ISSUE TITLE
OnTouch Event: no pause for active autoplay

### ISSUE THREAD

**Issue by MikeMcNuke** [kenwheeler/slick#853]
Hi,

I would recommend to add a pause to the swipeHandler like in the other parts of the code, so that the slide won't move under the thumbs of the user as he wants to move to a specific part of the slides.

Currently I added those lines similar to the hover in Slick.prototype.swipeHandler, which works fine and fixes this UX issue for me.

```javascript
        switch (event.data.action) {
            case 'start':
                _.paused = true;
                _.autoPlayClear();
                _.swipeStart(event);
                break;
            case 'move':
                _.swipeMove(event);
                break;
            case 'end':
                _.swipeEnd(event);
                _.paused = false;
                _.autoPlay();
                break;
        }
```

**Comment by kenwheeler** [comment]
Closing pending PR
