### ISSUE TITLE
Scale down image height - keeping the aspect ratio

### ISSUE THREAD

**Issue by chrisdemetriad** [kenwheeler/slick#857]
I have a few slides, each composed of a big image (400px height) and couple of small (200px height) floated ones, but this is not relevant at this point as this happens with only one image per slide too (jsfiddle example at the bottom).

When Slick gets initialised, it sets the height of the biggest image on .slick-list container (400px in my case).

When I resize down, so if less than 600px, you would normally expect the images to shrink accordingly (using img{max-width: 100%;height: auto;}) as their width changes, keeping the ratio but it doesn't, I think it's because the set height in the container (.slick-list).

So the width changes (slightly as parts of the images get hidden too) as there's no set width on the containers but the height stays the same.

How would I go about this __please__?

This is an [EXAMPLE ON JSFIDDLE](http://jsfiddle.net/carlozdre/u5bz382w/1/).

p.s. Using v1.3.15, Chrome 39.0.xx.

Fantastic work btw, Ken.

**Comment by kenwheeler** [comment]
The variableWidth option is what prevents your height from scaling
