### ISSUE TITLE
Last active slide in the carousel

### ISSUE THREAD

**Issue by sau-152mm** [kenwheeler/slick#859]
How to get the index of the last active slide in the carousel for example if it has 4 active slide?

**Comment by AleksaCorona** [comment]
This is a old thread but if someone is still looking for help there is a much cleaner and easier way to remove css or whatever from the last active item.

For example if you have three active items:
`.slick-active + .slick-active + .slick-active {
  padding: 0; /* or whatever */
}`

**Comment by najmuddinrks** [comment]
how to adjust slick slider with proper arrow width and margin adjust kindly help me that
