### ISSUE TITLE
AdpativeHeight and fade effect: "sudden" transition?

### ISSUE THREAD

**Issue by jan1980** [kenwheeler/slick#860]
Thanks for this wonderful plugin.

I found that when using adaptiveHeight, combined with the fade = true, the next panel's height is somehow not calculated, and there's a "sudden" jump to it, instead of the smooth transition when fade is omitted / set to false.

Did anyone experience this? I can set a Fiddle using the makup I have.

Thank you,

**Comment by kenwheeler** [comment]
Closing as a dupe, reviewing a PR that fixes this
