### ISSUE TITLE
slick swiping on mobile devices more sensitive to finger swipes

### ISSUE THREAD

**Issue by xitongzou** [kenwheeler/slick#861]
I got a request from some UX members of my team that when they try to swipe fast and not holding down their finger for too long, the carousel has an 'elastic band' effect where it doesn't move to the next page but snaps back to the same page, and seems a big jarring. I'm sure there's a tradeoff between knowing whether the user is browsing the current carousel or trying to swipe to the next one, but is there any way to make it more sensitive so that the user can browse to the next carousel page on a short fast swipe instead of snapping back? Thanks!

**Comment by johnylaravel** [comment]
@kenwheeler  Man, stop creating so fucking awesome options. 

I thought there is no way you implemented this, and **got really exited** when I saw how easy it is to solve this.

**Thanks, much love <3**
