### ISSUE TITLE
Bookmark or deeplink to a specific slide (possible feature request)

### ISSUE THREAD

**Issue by funkybudda** [kenwheeler/slick#864]
hello all,

I have been using cycle2 for a while and now have decided to move on to slick carousel, so I might not be as familiar as with some of the more advance features. My question is if there's a similar way to implement directly jumping to a slide / bookmarking like the cycle2 example here:
http://malsup.com/jquery/cycle2/demo/bookmark.php#sunset

I have searched using "deeplink" and "bookmark" on past issues and have not seen anything.

If such feature is not available, has any user done something with a workaround on jsfiddle or codenpen that they can share?

Thanks.

**Comment by kenwheeler** [comment]
Closing as a dupe

**Comment by GoGoAndroid** [comment]
I do think this answer ( in french ) : https://youtu.be/0eXhf-OmGW0  . The code in in the webpage associated to this demo
