### ISSUE TITLE
adaptiveHeight + lazyLoad does not re-expand the DIV after switching slides

### ISSUE THREAD

**Issue by rgbjoy** [kenwheeler/slick#870]
Set adaptiveHeight & adaptiveHeight set true. Switch slides. The div's height is set at 1PX height.

http://jsfiddle.net/kb2nLnj1/1/

**Comment by kenwheeler** [comment]
Merged PR

**Comment by alesas** [comment]
Nice first fix!

only thing is that now, it "jumps" instead of nicely getting bigger (or smaller) in height.

**Comment by kenwheeler** [comment]
Those are all the same height

**Comment by alesas** [comment]
I edited my comment, wrong link. Sorry. Check again :)

**Comment by alesas** [comment]
@kenwheeler should I open a new ticket as this one has been closed? :)

**Comment by Luc45** [comment]
Any news about this? :)

**Comment by Luc45** [comment]
Temporary fix:
```
/**
* Adjust the height of the slider according to the active item
*/
$('.my-slider').on('init afterChange lazyLoaded', function(){
  var heightActiveSlider = $('.my-slider .item.slick-active').height();
  $('.my-slider').height(heightActiveSlider);
});
```
