### ISSUE TITLE
focusOnSelect fale, slidesToShow modification, initial state bugginess

### ISSUE THREAD

**Issue by basiclaser** [kenwheeler/slick#871]
1. I thought the focusOnSelect bug was due to my nested images (#647), but even without them it doesn't function.

2. slidesToShow tends to show little partials of obscured slides, is there any way i can hide those partials? I'd really just like to see 3 slides, not 3 and two halves.

3. also please note that the initial slides state is uneven and all messed up. I'm not sure why this is though, sorry. 

I appreciate any advice on any of these points.

http://jsfiddle.net/basiclaser/5gwtug81/3/

**Comment by kenwheeler** [comment]
It's because of variable width. They dont have a width because of background images.
