### ISSUE TITLE
Get slide-direction in onBeforeChange

### ISSUE THREAD

**Issue by kkutschera** [kenwheeler/slick#872]
Is it possible to get the slide-direction in onBeforeChange? I need this for some logic that could not use onAfterChange because of timing and it needs to know the direction to get the next visible slide...

**Comment by kkutschera** [comment]
where do i find the target index?

**Comment by raphaelpweb** [comment]
It is a parameter of onBeforeChange that you can use, look up for the onBeforeChange method
here : https://github.com/kenwheeler/slick

**Comment by kkutschera** [comment]
ah - i searched for it on your website... You can close this issue. Big thanks

**Comment by simeydotme** [comment]
@kkutschera - __you__ can close the issue! :stuck_out_tongue:

**Comment by simeydotme** [comment]
:wink: caretaker @kenwheeler :+1:

**Comment by ClaudiuCreanga** [comment]
Hi,

Thanks for this awesome plugin.

But this shouldn't be closed and it is still an issue when you want to use swipe.

if you swipe but stop at the middle and come back or stay too long in the middle then currentSlide == nextSlide. But onBeforeChange event has been triggered and your code runs expecting to know the direction. to solve it you have to use hacks like setInteval()

Thanks!

**Comment by ClaudiuCreanga** [comment]
Ok I think by inserting touchThreshold : 100 you are able to circumvert the error.

**Comment by leggomuhgreggo** [comment]
Good intel gathering!
