### ISSUE TITLE
Use custom arrows for navigation

### ISSUE THREAD

**Issue by hajindersingh645** [kenwheeler/slick#875]
Hi,

I don't want to use the in-built arrows generated by slick plugin. I want to use the custom arrows. 
Kindly let me know how I can do that via an example.

Thanks

**Comment by maxence33** [comment]
> You can use "arrows: false" to turn the arrows off and the slickNext/slickPrev methods to move the slider. See: http://codepen.io/anon/pen/KwMZao

This seems not to work any longer on Slick 1.6.0. I will search for a different solution

**Comment by jljohnstone** [comment]
@maxence33 The syntax has changed but this feature still works. See http://codepen.io/anon/pen/qNbWwK

**Comment by maxence33** [comment]
Many thanks @jljohnstone. Works perfectly.

**Comment by jcicero518** [comment]
I have a client who wants the arrows to appear aside the "dot" navigation, so I ended up setting prevArrow / nextArrow to two DIVs inside <ul class="slick-dots"></ul> but this ends up causing the dot pagination to skip a page of results. Almost like it's applying an event listener to my custom DIVs as well. Anyone run into something like this?

**Comment by saturday1** [comment]
@jcicero518 Did you find a solution? I am trying to make the same solution. But it seems that slick script runs on the <li>-element, which mess up the order of the pagination.
