### ISSUE TITLE
White space at the end when using `variableWidth`

### ISSUE THREAD

**Issue by bernhardw** [kenwheeler/slick#877]
When using `variableWidth`, white space is shown to the right side at the end of `slick-track`, between `slick-list` and `slick-track`.
The width of `slick-track` is correctly calculated, but it seems that it can be scrolled to far to the left.

Example: http://jsfiddle.net/qbtcw1yL/

Is there any way to change this?

**Comment by kenwheeler** [comment]
Yeah there really isn't a good way to get around that. It is in centerMode so the active slide is centered.

**Comment by davidpustai** [comment]
I've noticed this issue too and to be clear, this doesn't happen only in `centerMode`. If you disable `centerMode`, you get even more white space. Is it somehow possible to disable dragging/swiping when you have the last slide visible to your most right (and not most left)?

**Comment by RicardoEPRodrigues** [comment]
Without `infinite: true` and `centerMode: true`, how can I limit slick to stop at the outer edge of the last element?

**Comment by RafaelRumpel** [comment]
Same problem here.

**Comment by RicardoEPRodrigues** [comment]
I made an experimental feature that helps in this situation. See #2635. Hope it helps.

**Comment by shubham42000** [comment]
i use slick js tab when first  tab con tent have more data, than go another tab content there is no data then unwanted scroll on second tab content how we fix it

**Comment by manerkargaurav** [comment]
same problem here. Any possible solutions ?

**Comment by agzwt** [comment]
Hey @kenwheeler 

I have the same problem with white space when I using infinite: !1; with variableWidth: !0; Too much white spacing is coming on the last slider 
Also, I need to disable the arrows next and prev

**Comment by JustifyContentSB** [comment]
Did anyone solve this problem?

**Comment by agzwt** [comment]
Hey @kenwheeler 

No one has solved these issues.

**Comment by JustifyContentSB** [comment]
> No one has solved these issues.

just use swiperjs
