### ISSUE TITLE
CSS generated in javascript problem.

### ISSUE THREAD

**Issue by raphaelpweb** [kenwheeler/slick#878]
I have a problem with css that I create in javascript in the onBeforeChange function. It works well except when the slider goes from the last to the first element or vice-versa. I think it may be related to the fact that there is a cloned element of those but I couldn't put my finger on it. Here's the site which contains the problem : http://rparent.dectim.ca/angiemennillo/ .
Thanks in advance :)

**Comment by thenovacreator** [comment]
I think your solution is a littel bit to "tricky" and i am asking myself what your a planning to gain like this. If you want that the image fits the screen i think you could go for something better.

Did you try the set the image as and background? The background-size attribute is what you need. Like

.image-container {
    background-size: cover;
}

**Comment by raphaelpweb** [comment]
The thing is, it's a photographer website. If the pictures are all in background images then they arent referenced by google and for a photographer that's kind of off the point.

**Comment by thenovacreator** [comment]
Maybe you use it 2 times. One time for google in the image tag but with opacity 0 so it can not been seen. And one time for the viewer as an background?

**Comment by raphaelpweb** [comment]
Damn that's not a bad idea, not the solution I was looking for since I already worked quite a bit to make them fit on every device but thanks I will look into that!

**Comment by simeydotme** [comment]
if you set `display:none;` in CSS I believe google will not weigh that element in it's results. You should set `display:none;` with Javascript so the crawlers see it.

**Comment by raphaelpweb** [comment]
True. Just put them away from the visible part of the website, without necessarily setting them at '''display:none'''
