### ISSUE TITLE
SlidesToShow render horizontally in vertical mode if equal to number of slides

### ISSUE THREAD

**Issue by alan-unravel** [kenwheeler/slick#881]
Not exactly sure why this is happening, it seems if slides to show >= number of slides  this occurs. I know this doesn't seem like that big of a deal but when dealing with asynchronous loading it is a bit of a pain. Any light you can shed on this issue would be great, Thanks.

**Comment by kenwheeler** [comment]
Neither of those examples appear to be in vertical mode?
