### ISSUE TITLE
Feature Request: variable autoplaySpeed per slide

### ISSUE THREAD

**Issue by numediaweb** [kenwheeler/slick#889]
while in autoplay mode, I wonder if it is possible to allow each slid define the duration before the transition moves to second slide.
Better option is to add the duration to inside the slide's data field ex.; 
```
<div class="_slide" data-slide-duration="3">This slide would last 3 seconds</div>
```

**Comment by kenwheeler** [comment]
I'll look into it.

**Comment by kenwheeler** [comment]
This probably wont make it into core
