### ISSUE TITLE
slide syncing not working inside lightbox

### ISSUE THREAD

**Issue by RobertoCMCosta** [kenwheeler/slick#892]
I can't make syncing work inside a Foundation Reveal modal (lightbox). The inspector shows no js conflict. 
I'm also loading other contents into the modal via ajax. 
If I disable the modal call, syncing gets back to working as it should.
Anyone has an idea?
See a working example without the reveal call here: http://www.mejimoveis.com.br/imovel/locacao-apartamento-em-icarai-cod-0919/

**Comment by kenwheeler** [comment]
I can't see any modal there?

**Comment by RobertoCMCosta** [comment]
Hi Ken,

It's really not there anymore. I had to launch the site a few days ago so I removed the modal feature and used a normal single template again. However, the issue exists. Syncing two sliders, like it's done in slick's demo page, doesn't work from within a Foundation Reveal Modal.
All the other feature work fine, but syncing. I found no clue because Chrome's console shows no error.

**Comment by kenwheeler** [comment]
I would need to see a jsfiddle to tell you definitively

**Comment by RobertoCMCosta** [comment]
It's running on wordpress with a couple of plugins installed. A staging site is a better bet for you to check.
I'll set it up and tell you later. Thanks.
