### ISSUE TITLE
Memory leak with compositing in chrome?

### ISSUE THREAD

**Issue by ivancuric** [kenwheeler/slick#895]
The buttons for some reason are painted over an enormous area:

![memleak](https://cloud.githubusercontent.com/assets/2827047/5587076/950ac45c-90e1-11e4-9361-2f3791f9fafa.png)

[EDIT]
The problem is in the `font-size: 0` in the button.
Fixed it by wrapping the "Next" and "Previous" in a `span` tag with `display: none` on lines 51 and 52:

```
prevArrow: '<button type="button" data-role="none" class="slick-prev"><span>Previous</span></button>',
nextArrow: '<button type="button" data-role="none" class="slick-next"><span>Next</span></button>',
```

**Comment by kenwheeler** [comment]
Can I see the jsfiddle? Were you using a table?

**Comment by ivancuric** [comment]
Sorry mate, don't have a fiddle, but the page wrapper was set to `display: table` to use the responsive sticky footer: http://galengidman.com/2014/03/25/responsive-flexible-height-sticky-footers-in-css/

**Comment by kenwheeler** [comment]
Fixed on dev
