### ISSUE TITLE
Issues with Slider Syncing

### ISSUE THREAD

**Issue by lmartins** [kenwheeler/slick#897]
Hi,

Im having a few issues with this option, one of them is actually visible on the plugin website.

1) Auto-play not coping well with the two sliders
UPDATE: Scratch this one, i've found why it was behaving badly.
If you use auto-play, both sliders move forward normally until they reach the last slide. Then the main slider still moves forward but the navigation stays on the previous and only updates when the main slider goes to the second slide.

You can see the issue here:
http://www.webipack.com/

2) Active slide on multiple visible slides
This might not be an issue, but kinda invalidates the purpose of the sliders as a navigation menu. In the example above, I have one visible slide on the main slider but four on the navigation slider. The goal was to have the only current navigation slide marked as active on both sliders, but if I configure the navigation slider to show 4 slides, them all four get the active class.
I've got around this by configuring the navigation to show 1 item but then forced via CSS to show all four. Not sure if this has any relation to the issue above, but I believe not.

3) Pause on hover does not work between sliders
If I mouseover the navigation slider, the main slider still moves forward.

Heres how I configured both sliders:
```
that.$bannerTop.slick({
            dots: false,
            // arrows: false,
            lazyLoad: 'progressive',
            infinite: true,
            autoplay: true,
            fade: true,
            cssEase: 'linear',
            speed: 400,
            autoplaySpeed: 7500,
            adaptiveHeight: true,
            slidesToShow: 1,
            slidesToScroll: 1,
            pauseOnHover: true,
            asNavFor: '.banner-nav-slider'
          });

$('.banner-nav-slider').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            asNavFor: that.$bannerTop,
            infinite: false,
            dots: false,
            arrows: false,
            pauseOnHover: true,
            focusOnSelect: true
          });
```
Any further info I can provide to help solve this?

**Comment by kenwheeler** [comment]
Closing pending a jsFiddle. The only bug I see here, would likely be #3
