### ISSUE TITLE
Remove jQuery.fn namespace clogging

### ISSUE THREAD

**Issue by ahukkanen** [kenwheeler/slick#898]
According to the official jQuery docs you should always avoid clogging the jQuery.fn namespace
http://learn.jquery.com/plugins/basic-plugin-creation/#minimizing-plugin-footprint

I know the probability of a collisions is quite minimal due to the "slick" prefixing but it's still a bad convention. And you could argue backwards compatibility etc. but that can be solved with versioning and documentation.

By the way, I like this plugin otherwise (which is also why I care)!

**Comment by kenwheeler** [comment]
I'm working on it. It will never collide with anything, but the alternate way is way cleaner.

**Comment by ahukkanen** [comment]
Great to hear!

**Comment by kenwheeler** [comment]
Fixed on dev

**Comment by ahukkanen** [comment]
:+1:
