### ISSUE TITLE
Possibility to skip $.wrap, if markup already has enhanced markup

### ISSUE THREAD

**Issue by aFarkas** [kenwheeler/slick#900]
From my testing slick can become extremely slow. One of the by far heaviest DOM manipulations on startup are the [$.wrap calls](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L462-468).

It would be a nice feature, if performance aware developers could write the markup initially and skip the wrap method. Additionally maybe the two wraps can be optimized into one (But I haven't tested it).

In case you like this idea, I can put a PR together.

Additional side note: Haven't tested it, but I think, that your [``innerWidth``part](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L501) is wrong.  On mobile innerWidth means visual viewport and not layout viewport. Normally these two are same, but as soon as a user zooms in the innerWidth is much much smaller than the layout viewport (see here: http://www.quirksmode.org/mobile/viewports2.html)

**Comment by kenwheeler** [comment]
What has been a scenario where you experienced slowness? Enforcing manual html would be annoying to users, a breaking change, and potentially adds non-semantic markup and/or markup that shouldn't be present in the absence of JavaScript. 

That said, if you have jsPerf tests showing me that wrap significantly slows Slick down , I'm open to using a documentFragment to build and replace the original content.
