### ISSUE TITLE
Angular: ng-click is disabled

### ISSUE THREAD

**Issue by sinjaz** [kenwheeler/slick#904]
I have multiple elements inside each slide with ng-click's attached to them. They all seem to be disabled. Anyone know how I can enable them or possible workarounds?

**Comment by sinjaz** [comment]
After testing some more I found out the ng-click is in fact NOT disabled. The issue is accessing the outer scope which has the definition of the click function. Since the SLICK directive creates its own scope the outer scope is never reached. So the question is how to access to outer (parent) scope, similar to defining the 'data' attribute. Any help would be appreciated.

**Comment by sinjaz** [comment]
I was able to resolve this by passing the scope to slick as the data attribute. This allowed me to access multiple properties of the scope, including functions and model objects.

```javascript
// 'this' is a reference to $scope
<slick data=this>
    <div ng-click="data.clickHandler()">{{data.model}}</div>
<slick>
```

**Comment by kenwheeler** [comment]
You should file this on the slick directive repo

**Comment by amrfaisal** [comment]
Check my answer for Angular use-case:
http://stackoverflow.com/questions/29101254/angularjs-slick-js-carousel-ng-click-not-firing-with-responsive-attribute-settin/30584787#30584787
