### ISSUE TITLE
Custom Arrows disappear on slickAdd

### ISSUE THREAD

**Issue by thenovacreator** [kenwheeler/slick#907]
Hello Folks,

i got a little Problem with Slick using its slickAdd Function. If i use this my customs arrows disappear. To be exact they are completly remove from DOM. The Second issue is that the arrows are removed in resposive view as well (everything under 900px) but one step after another.

			target = jQuery('#' + id + " .slide-wrapper");

			var slider = jQuery(target).slick({
				slidesToShow: 4,
				slidesToScroll: 2,
				prevArrow: '#' + id + " .slider-button-left",
				nextArrow: '#' + id + " .slider-button-right",
				infinite: false,
				speed: 1000,
				onAfterChange: function () {
					bLazy.revalidate();
				},
				responsive: [
					{
						breakpoint: 900,
						prevArrow: '#' + id + " .slider-button-left",
						nextArrow: '#' + id + " .slider-button-right",
						settings: {
							slidesToShow: 2,
							slidesToScroll: 1
						}
					},
					{
						breakpoint: 500,
						prevArrow: '#' + id + " .slider-button-left",
						nextArrow: '#' + id + " .slider-button-right",
						settings: {
							slidesToShow: 1,
							slidesToScroll: 1
						}
					}
				]
			});

			jQuery(target).slickAdd("<div>test</div>");
			jQuery(target).slickAdd("<div>test</div>");
			jQuery(target).slickAdd("<div>test</div>");
			jQuery(target).slickAdd("<div>test</div>");

Here is a working site with that problem. 

http://novacreator.net/testarea/da/index.php

Someone an idea what the heck is wrong there?

**Comment by ssauceda** [comment]
I've got the same problem with my custom arrows disappearing.

**Comment by tripgrass** [comment]
One possibility: If you have fewer images loaded than you you have in the slidesToShow setting, the arrows will not show.

**Comment by thenovacreator** [comment]
@tripgrass There are already 8 Elements in the slider and 2 added so i think it is not this issue
@ssauceda Thanks for advice ... but i am not using unslick ... do did not even know this function

**Comment by kenwheeler** [comment]
Can someone provide a reduced test case with jsFiddle? Closing pending a test clearly showing the issue.

**Comment by tibineagu** [comment]
Please see the behaviour reproduced in this fiddle: https://jsfiddle.net/9pxucLhj/4/
Thanks for looking into this!

**Comment by deeplomacy** [comment]
Hello,

I've faced the same issue after a responsive breakpoint is reached. So I've commented these lines in the *destroy* method :
if (_.$prevArrow && (typeof _.options.prevArrow !== 'object')) {
   _.$prevArrow.remove();
}
if (_.$nextArrow && (typeof _.options.nextArrow !== 'object')) {
   _.$nextArrow.remove();
}

My custom arrows aren't removed from the DOM anymore :smile:

**Comment by simeydotme** [comment]
Should be fixed by this commit: https://github.com/simeydotme/slick/commit/adfbfd1f446e33915c6c53a22f7a2cda94f7ceee in this PR: https://github.com/kenwheeler/slick/pull/1331
