### ISSUE TITLE
Pause on hover not working without options.autoplay = true

### ISSUE THREAD

**Issue by kirushko** [kenwheeler/slick#908]
When initialize slick without autoplay: true and start it by calling element.slickPlay(). Hover over slick doe not pause it animation.

Though it's related with following code:
```
    Slick.prototype.initDotEvents = function() {

        var _ = this;

        if (_.options.dots === true && _.slideCount > _.options.slidesToShow) {
            $('li', _.$dots).on('click.slick', {
                message: 'index'
            }, _.changeSlide);
        }

        if (_.options.dots === true && _.options.pauseOnDotsHover === true && _.options.autoplay === true) {
            $('li', _.$dots)
                .on('mouseenter.slick', function(){
                    _.paused = true;
                    _.autoPlayClear();
                })
                .on('mouseleave.slick', function(){
                    _.paused = false;
                    _.autoPlay();
                });
        }

    };
```

It's subscribe hover events only if slick is initialized with `_.options.autoplay === true`

**Comment by kenwheeler** [comment]
I need to see a jsFiddle

**Comment by marcandrews** [comment]
When the autoPlay is started with slick('slickPlay'), pauseOnHover is ignored and the slideshow does not pause when mousing over a slide.

https://jsfiddle.net/qo3wkf86/

**Comment by iSimonWeb** [comment]
:+1: Thanks for the issue, can't find why my pauseOnHover was not working too.
@kenwheeler we need to fix this, I have several slicks on my page and I'm autoplaying them only if visibile. I need to initialize them with "autoplay: false".

**Comment by marcandrews** [comment]
Try Flickity

**Comment by kenwheeler** [comment]
This doesn't work on the current version? I thought @simeydotme sorted this out like two releases ago?

**Comment by simeydotme** [comment]
Actually, no...
https://github.com/kenwheeler/slick/pull/1086 @joeholdcroft did :wink: 

@marcandrews fiddle actually shows a working pauseOnHover (lol?) and @iSimonWeb has not provided a fiddle to examine, my guess is he's running version 1.4.x or 1.3.x .. :unamused:

**Comment by marcandrews** [comment]
@simeydotme pauseOnHover is **not** working on my fiddle.

**Comment by simeydotme** [comment]
Nope. Ignore my comment... It's set in `reinit()` which is called on `slickSetOption` so should be fine...

**Comment by marcandrews** [comment]
Wait, so is there a fix?

**Comment by simeydotme** [comment]
Apologies, @marcandrews -- you're right your fiddle isn't pausing on hover! >.<

**Comment by marcandrews** [comment]
No worries. It's all moot anyway for me as,  after encountering this issue, I switched over to Flickity.

I'd still like to help the dev and anyone else still using Slick though.

**Comment by kenwheeler** [comment]
Reopening pending fix

**Comment by marcandrews** [comment]
... I'll actually go into detail about the issue. I had an autoplaying Slick, but on touchscreen devices, for reasons obvious, the pauseOnHover is irrelevant. So I detected touchscreen devices, and only started the Slick show on non-touchscreen devices, but then pauseOnHover didn't work on these devices. Perhaps you can keep this in mind when fixing.

**Comment by simeydotme** [comment]
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1963-L1970
It's because when `slickPlay()` is called, it doesn't set `optons.autoplay` which means the `setPaused` method doesn't evaluate the `autoplay()` :(

**Comment by simeydotme** [comment]
should be fixed on `master` branch, now following a revamp of the autoplay feature :)

**Comment by agzwt** [comment]
I have some issues like when autoplaySpeed is **Zero** but on pauseOnHover not working it takes time to stop slide 

Anyone ever figures out a solution to this? I love the continuous scrolling, just hate the weird pause on hover delay.
I have put them my code here. 
https://github.com/kenwheeler/slick/issues/500
