### ISSUE TITLE
Slides Not Swipeable in IE11 on Touch Devices

### ISSUE THREAD

**Issue by cristianjd** [kenwheeler/slick#909]
When draggable is set to false, slick carousels do not change slides when swiped on IE11 on a touch laptop running windows 8.1. Works on other browsers. Simple example here:  http://jsfiddle.net/ho5tm0xa/

**Comment by cristian-luv** [comment]
It looks like there may be a change needed to support pointer events as IE11 does not use touch events. http://msdn.microsoft.com/en-us/library/ie/dn304886%28v=vs.85%29.aspx

**Comment by cristianjd** [comment]
It looks like there may be a change needed to support pointer events as IE11 does not use touch events. http://msdn.microsoft.com/en-us/library/ie/dn304886%28v=vs.85%29.aspx

**Comment by kenwheeler** [comment]
I don't have the hardware available to test this. Can someone look into this?

**Comment by kenwheeler** [comment]
Can anyone add pointerstart pointermove and pointerend to the event bindings and tell me if it works? I'm getting false positives on these emulators.

**Comment by kenwheeler** [comment]
This is expected behavior
