### ISSUE TITLE
slide temporarily freezing when swipe element with autoplay

### ISSUE THREAD

**Issue by mintplo** [kenwheeler/slick#910]
hi~

slide freezing when swipe element with autoplay option set true.

i guess because of not existing _.autoPlayClear() when touchstart.slick event triggered.

so when touch swipe element left and right continuously, autoplay triggered. then slide action temporarily freezing.

here's my solution.

        switch (event.data.action) {

            case 'start':
                _.swipeStart(event);
                if (_.options.autoplay === true) {
                   _.autoPlayClear();
                }
                break;

            case 'move':
                _.swipeMove(event);
                break;

            case 'end':
                _.swipeEnd(event);
                if (_.options.autoplay === true) {
                    _.autoPlay();
                }
                break;

        }

please check solution.
thank you!

**Comment by kenwheeler** [comment]
It's because of pauseOnHover which is true by default

**Comment by mintplo** [comment]
hmm..

you can see slick.prototype.initializeEvents

mouse enter and leave event toggle autoplay stop and play when pauseOnHover option and autoplay option set true.

but touch start and end event not exist this process.

so when slide left and right continuously using touch swipe, autoplay timer overlap slide timing in hand.

so slide temporarily freezing.
