### ISSUE TITLE
How to manage in arabic content slider right to left.

### ISSUE THREAD

**Issue by rvpatel** [kenwheeler/slick#914]
I have use in magento 2 store slider so now one issue.
English work done. left to right
when i use Arabic store in right to left not working with navigation.
Please help us for this floating.

**Comment by ElawadyNet** [comment]
In "http://kenwheeler.github.io/slick/" page, search for "Right to Left" 
You can found this snippet :
```
$('.single-item-rtl').slick({
	rtl: true
});
```
Note: the HTML tag or the parent of the slider must have the attribute "dir" set to "rtl".

NOTE: I HAVE BAD ENGLISH.

**Comment by moftahmoftah** [comment]
in "slick.js" file change  "rtl" to be "true".

**Comment by coderwebb** [comment]
in "slick.js" file change "rtl" to be "true". dediğinizi yapınca oldu. ama ben çok dilli site kullanıyorum. arapça düzeliyor. Fakat diğer dillerde resimler gözükmüyor.

**Comment by barisdogansutcu** [comment]
.slick-slider .slick-track, .slick-slider .slick-list { direction: ltr; }
