### ISSUE TITLE
slidesToScroll > 1 while centerMode = true - bug

### ISSUE THREAD

**Issue by befreestudios** [kenwheeler/slick#917]
Is this a bug? If not, could we make it a feature request? ... see also link to fiddle at bottom. Thanks in advance, btw the plugin rocks!

Steps to recreate: (already setup in fiddle)
When centerMode = true, slidesToScroll is only sliding 1 regardless of what is set.  

Expected: if centerMode = true and slidesToScroll = 3, nav items should scroll 3 slides on center.

FIDDLE HERE...
http://jsfiddle.net/befreestudios/hk5uqb5w/

**Comment by befreestudios** [comment]
I think #541 is related.

**Comment by kenwheeler** [comment]
Closing as a dupe of 659
