### ISSUE TITLE
Feature Request: Mouse Wheel Usage

### ISSUE THREAD

**Issue by aaronstezycki** [kenwheeler/slick#918]
I'd like to be able to use my mouse wheel when on desktop to slide left or right, but only when my cursor is hovering above the slider in question.

Not sure if this has been implemented or not, but I can't see it so correct me if I'm wrong in posting this request.

**Comment by aaronstezycki** [comment]
Forgive me, didn't search hard enough #122. Sorry guys.

Just one thing though before you guys beat me around the head with a stick.

As a basic UX feature, scrolling content is one of the easiest user interactions anyone can use. Is it not worth at least trying to figure this one out as mouse wheel scrolling is quite important. I know a left and right button is 'acceptable', but I can't help but think scrolling will make an easier interaction for desktop users.

Thanks guys.

**Comment by kenwheeler** [comment]
Closing as a dupe
