### ISSUE TITLE
LeftMode for Slider Syncing

### ISSUE THREAD

**Issue by webdrifter** [kenwheeler/slick#919]
Hello sir!

Centermode is false. I need to display first item as active.
I have added my class for active item, but it is removed at some point.

See my fiddle: http://jsfiddle.net/kristjanku/cu9qssL0/

Press navigation items in the following order "Nav 3", "Nav 5" and "Nav 1".
Active state for number 1 is removed. Any ideas why and how to solve this? 

Could we have a class for active item when centermode is not used or how can we style first active item?

Regards,
Kristjan

**Comment by kenwheeler** [comment]
why not just use centerMode?
