### ISSUE TITLE
Disable snapping to a slide

### ISSUE THREAD

**Issue by pavethiran** [kenwheeler/slick#920]
Hi,
I would like to use a slick slider without the slider changing the position.

So if I drag the slider and let go of it half the way of an image, usually it snaps to an image, but I would like it to stay half way.

Couldn't think of a way without changing the slick code.
Is it possible to do so?

Best wishes,
Pavi

**Comment by kenwheeler** [comment]
I'll think about how to do this the best way.

**Comment by pavethiran** [comment]
Any progress or an idea on how it might work? :smile:

**Comment by camilonova** [comment]
:+1:

**Comment by molokoloco** [comment]
:+1:

**Comment by kenwheeler** [comment]
Closing as a dupe of #922
