### ISSUE TITLE
Vertical mode causes 'snap in' when looping back to Slide 0

### ISSUE THREAD

**Issue by Stellaverse** [kenwheeler/slick#921]
Hi Ken,

Great plugin, thanks for this. I'm having an issue with using the slider in vertical mode though.

When the slider loops back around to Slide 0 the transition is lost. I can see that the the transition OUT works fine, the slider slides up. But Slide 0 seems to be hidden and then just snaps in when the transition is complete.

You can view the issue here: http://www.elementalinc.3he.ca

Any idea on how I might go about fixing this? I'm rooting around in the src now, but can't see what would be causing this.

Thanks!

**Comment by kenwheeler** [comment]
You're styling off of ID's and ID's get removed from clones. Sorry about that, but it needs to happen for things like video and forms.

**Comment by Stellaverse** [comment]
Roger.

Replaced all the IDs with classes and it seems to have fixed the issue. Thanks for the tip!
