### ISSUE TITLE
IE 7 js error because of a trailing comma in object declaration

### ISSUE THREAD

**Issue by kkriehl** [kenwheeler/slick#923]
IE 7 currently breaks because of a single trailing comma after the last property of an object in line 1186 of slick.js. [That's this line](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1186-1186).

And because the line number *might* change I'm adding a quote of the code:

```js
_.changeSlide({
    data: {
        message: 'index',
        index: currentSlide,
    }
}, true);
```
The trailing comma after `currentSlide` breaks IE 7.

**Comment by kenwheeler** [comment]
Fixed
