### ISSUE TITLE
Problems with vertical scrolling

### ISSUE THREAD

**Issue by sebakerckhof** [kenwheeler/slick#925]
I have some problems with vertical scrolling.
This JSFiddle is basically the synchronized sliders demo, but with vertical sliders: http://jsfiddle.net/d2oegbwe/

As you can see, swiping isn't adjusted to be vertical, and still only registers horizontal swiping.
Furthermore, when both the fade and vertical option are active (the topmost slider), this doesn't show any slides except the first one.

**Comment by kenwheeler** [comment]
Slick doesn't support vertical scrolling
