### ISSUE TITLE
if I use ul>li instead of div, it works but the html structure is wrong

### ISSUE THREAD

**Issue by airyland** [kenwheeler/slick#926]
The ul>li is turned into 

`ul>div.slick-list>div.slick-track>li`

So do I have to use just div?

![image](https://cloud.githubusercontent.com/assets/559179/5733057/a5c63a0a-9bd7-11e4-9dc2-65a60c468875.png)

**Comment by simeydotme** [comment]
Hi @airyland - Technically this isn't a bug, so if you wish to submit a feature request you should write/orientate your issue a little clearer :grin: - however in my humble opinion:

1. I think the `.slick-track` and `.slick-slide` __should__ be `ul > li` by default, but that would be backwards incompatible so should change in a major version, eh @kenwheeler ?

2. I think your scenario is that you want semantic HTML for SEO/Accessibility reasons? - in that case you can write your HTML as `<ul>` and `<li>` but with JS convert them to `<div>`s before you call `.slick()` example: http://jsfiddle.net/kv8jz66w/ 

Hope this helps :smile:

**Comment by airyland** [comment]
Thanks for help. Yes, I like semantic HTML.  I think using JS to covert tags into DIV just makes things more complicated. So it would be nice if  @kenwheeler could think about it and fix that in the next version.

**Comment by simeydotme** [comment]
:+1: - yep it does complicate matters further :laughing:, but if you can wait for a major version that's great! :smile:

**Comment by kenwheeler** [comment]
Just a side note here, you do know that no search crawler will ever see slick markup right?

**Comment by simeydotme** [comment]
yup, but it will see what was there ___before___ slick (hence better HTML is better) :relieved:

**Comment by kenwheeler** [comment]
But if you have ul li set up before, what's the problem?

**Comment by simeydotme** [comment]
tru dat.

**Comment by airyland** [comment]
I can accept using div instead of ul>li.
But I cannot accept slick turn my ul>li into non-standard markup like ul>(div>div>li)

**Comment by kenwheeler** [comment]
Is there some actual detriment that is taking place or are you just a staunch purist?

**Comment by airyland** [comment]
Ok, No detriment. I just really don't like non-standard codes.
I will fork it and modify for myself.

**Comment by teohhanhui** [comment]
This is not just being pedantic. It has actual potential to break your CSS selectors... (e.g. `ul > li`)

**Comment by simeydotme** [comment]
I would hope, however, that one tests one's CSS before and after dom manipulation occurs :smile:  - not exactly shocking that the dom-tree changes :confused:

**Comment by teohhanhui** [comment]
My point is that it shouldn't happen. Progressive enhancement, anyone?

**Comment by teohhanhui** [comment]
Looks like it's possible with OwlCarousel: https://github.com/OwlFonk/OwlCarousel2/issues/16

**Comment by Rafaelki** [comment]
I made the trick basically modifying the line 521, **wrapping** the element with the slick-track div instead of appending it: `_.$slideTrack = _.$slider.wrap('<div class="slick-track"></div>').parent();`
Then with some changes here and there I make it work with perfect semantics.
I have only tested this parameters: dots:true, arrows: true, slidesToSh
[slick.js.txt](https://github.com/kenwheeler/slick/files/704620/slick.js.txt)
ow:4, slidesToScroll:1, autoplay: true, autoplaySpeed: 4000, vertical: true/false, slide: 'li'.
I hope this help.

**Comment by kyleruscigno** [comment]
I would like to note this issue is not just semantics, as W3/WAI suggests that carousels should be in a ul > li structure for accessibility reasons https://www.w3.org/WAI/tutorials/carousels/structure/
