### ISSUE TITLE
Variable height slider bug

### ISSUE THREAD

**Issue by daviddelusenet** [kenwheeler/slick#927]
Hi,

I found a bug!

I have a horizontal slider with variable height which has autoplay. If I let this play on in a tab which isn't active and then go back, the queue is filled up with the height-animations and they all play, which generates a weird pulse.

You can easily fix this by adding http://api.jquery.com/stop/ to the animation I guess? But don't have any idea on how to do this myself.

Any help is welcome!

**Comment by simeydotme** [comment]
Not sure this counts as a bug; it's a feature to prevent your laptop/tablet's battery for being chewed on. Your browser will disable javascript, css rendering and other DOM updates in any non-active window/tab I believe. Then it resumes them upon activation.

using jQuery's .stop() is not a good solution as far as I am aware, it would create jerky animations in the browsers that use jQuery animation, and also most browsers now use css animation which is the likely scenario you're encountering as the CSS animations queue up.

There is ___however___ an API for detecting active/inactive browser tabs. Perhaps I'll take a look at implementing a slider-pause when the tab is not active, that's if @kenwheeler doesn't get around to it first :wink:

**Comment by kenwheeler** [comment]
Man what a strange one. Thanks as always @simeydotme for holding the fort down. I'd have to look into this as I have zero experience with inactive tab shenanigans.

**Comment by simeydotme** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API

love the first scenario mentioned, "image carousel"  :wink:

**Comment by rjerew** [comment]
@simeydotme and @kenwheeler, using v1.4.0 of slick, although i'm still experiencing this issue in msie 9, 10, 11 and a older version of firefox (v25). i did verify my copy/version of slick.js contains the changes @simeydotme had made in #950. any further ideas on how i might prevent this annoying pulse from happening?

**Comment by simeydotme** [comment]
Yes, @rjerew you will experience this still happening in browsers which do not have the `pagevisibility` api ... which includes older IE  ... but I will take another look and see why it's still happening in IE10/11 and Firefox.., however I may find it difficult to downgrade my Firefox :confused:

**Comment by simeydotme** [comment]
I've found the root of the issue in IE10/11 and rectified it with the referenced pull request. I cannot check Firefox 25, but I would suggest that actually it's not a bug as Mozilla state clearly that it should work in Firefox 10 + ... plus looking at http://caniuse.com/#search=page%20visibility the global usage of Firefox 25 is less than 0.05%
