### ISSUE TITLE
Slider with AJAX content.

### ISSUE THREAD

**Issue by sailesh2225** [kenwheeler/slick#928]
We are trying to integrate the slider with AJAX content... on the page load,the  slider works perfectly but the same does not work with AJAX content which gets loaded via lazy load. The binding of the .slick is not happening... plz help on the same

**Comment by kenwheeler** [comment]
You need to call slick on the new element, it can't auto instantiate

**Comment by sailesh2225** [comment]
We have called slick on the new element.. for the content coming from AJAX if there are 4 images that need to be animated, all the four are layered vertically and not horizontally for the slider effect ... even if we delay the initialization till the content from ajax is received (where 10 sliders are on page load and 20 via ajax) the 10 sliders on the page load work perfectly, but the 20 sliders from AJAX just line up vertically...

**Comment by simeydotme** [comment]
@sailesh2225 go ahead and create a JSFiddle with the minimum required code to demonstrate, post your question on Stackoverflow (where it should be) and then let me know, I will help you solve your problem on Stackoverflow :smile:

**Comment by mephilip** [comment]
I would also like to see the solution to this problem

**Comment by bhabeshrai** [comment]
@sailesh2225 did you get the solution ? i'm facing the same problem
