### ISSUE TITLE
Foundation reveal-modal, img height

### ISSUE THREAD

**Issue by SeanTurtle** [kenwheeler/slick#930]
Hi

I'm not sure if this is a Foundation issue or a slick one, but I have two sliders within a reveal modal, and have to resize the window in order for the images to load.

I've seen a couple of supposed fixes, along the lines of 

    $(document).foundation();
    $('.reveal-modal').on('opened', function() {
        $(window).trigger('resize');
    });
    $(document).ready(function() {
        $('.slick').slick();
    });

But it's not working. Any help would be appreciated.

**Comment by kenwheeler** [comment]
$('.slick')[0].slick.setPosition()

**Comment by SeanTurtle** [comment]
Hi Ken

Sorry to be a numpty, but could tell me specifically where that would need to go, ie if it's on a slider with an ID, that should replace .slick, correct?
