### ISSUE TITLE
Firefox issue with <video> canvas

### ISSUE THREAD

**Issue by skynet** [kenwheeler/slick#932]
If one of the slides is a `<video>` canvas, video won't play in Firefox. Works fine in Chrome.

**Comment by simeydotme** [comment]
@skynet can you please create an example here http://jsfiddle.net/L0hntr35/ :smile: - also just to confirm have you put the `<video>` inside a container like a `<div>` ?

**Comment by skynet** [comment]
Without slick.js: http://jsfiddle.net/cbg1p3x6/15/
With slick.js: http://jsfiddle.net/cbg1p3x6/16/

**Comment by simeydotme** [comment]
http://jsfiddle.net/cbg1p3x6/21/
That's working for me in FF and Chrome now... for your information and anyone else: This is 100% not something to do with Slick. 

You set the source to `video/mp4` but Firefox only sort-of supports it. I could get it to run in another tab using the direct link to video and activating a Quicktime plugin on my Mac, but it still wouldn't work in the JSFiddle. -- https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Anyway, the solution is to supply an `ogv` source for Firefox. I would also suggest you look in to supplying a `webm` source for IE.

Please close this issue :smile: 
Regards, Simon.

**Comment by skynet** [comment]
Did actually test with .ogv before. And actually not working for me in Chrome now. I'll come up with more examples when I get a chance. Thanks.

**Comment by simeydotme** [comment]
@skynet : bottom line is that HTML5 apis are new and temperamental in each browser. It has absolutely zero to do with Slick. Video is especially finnicky. -- I can prove it as your video doesn't even work in Firefox without the carousel:
![screen shot 2015-01-19 at 12 47 32 pm](https://cloud.githubusercontent.com/assets/2817396/5796070/93f5a152-9fd9-11e4-9e00-58215520f76c.png)

I tested my JSFiddle and it works in both Chome, Safari and Firefox. (Safari wont autoplay). 
If you have more trouble using the native HTML5 `<video>` API then I suggest you try something like videojs or jwplayer. Both have saved me many times in the past :smile: 

Simon

**Comment by skynet** [comment]
Simon - if you look at the code it is actyally using [videojs](http://www.videojs.com/)
Thanks for your support!

**Comment by simeydotme** [comment]
Ah gotcha :)
Just checked on my mobile Chrome (android) (on the bus,  sorry) with the
video-js classes removed and it works fine :) - maybe you should pursue any
further assistance with noting its a library conflict (well, not for me)
and not a `<video>` problem  :grin:

Best,  Simon
