### ISSUE TITLE
no lazy loading with slickAdd

### ISSUE THREAD

**Issue by mrextreme** [kenwheeler/slick#936]
If you have a lazy loaded ( "ondemand" ) slide and you add images to it using something like ```$( '#carousel' ).slickAdd( '<div><img data-lazy="img1.jpg" alt=""></div>' );```, then the image will be immediatelly loaded into the DOM even if it is outside of the carousel's "viewport" - you can see that in your browser's developer console / network logs.

I'll try to make a jsbin or jsfiddle example of it, but I don't know where to get a few uniform size, hotlinkable images.

**Comment by kenwheeler** [comment]
http://jsfiddle.net/7s9p6z2g/

Just tested and this is not occuring. Hope you like George Carlin.

**Comment by mrextreme** [comment]
No, he talked too much rubbish. I more like Murphy and his laws.
