### ISSUE TITLE
I can't initiate Slick Slider - why?

### ISSUE THREAD

**Issue by azupak** [kenwheeler/slick#938]
Hi, 
i have some silly problem. I want to try how the slick slider works so I've made some simple page for test, opened my page in browser and there was nothing (besides some sample txt). Where I made a mistake?

![zrzut ekranu 2015-01-20 o 10 49 05](https://cloud.githubusercontent.com/assets/8769886/5814910/c821bb52-a090-11e4-95ed-83a893f62978.png)

And here is the photo how it's look in my browser:

![zrzut ekranu 2015-01-20 o 10 45 04](https://cloud.githubusercontent.com/assets/8769886/5814877/5dc9634a-a090-11e4-9612-35276a559ff1.png)

In Jsfiddle some part of code work's 
http://jsfiddle.net/azupak/3sa1419a/

Now it's showing 3 divs ( I try multiple-items class) now but it's looks like he's not reading css. In my simple page (photo above) i think he's not reading css neither javascript but i don't know why - url path looks good

**Comment by bobek-balinek** [comment]
+1 I have the same issue.

**Comment by apetrakow** [comment]
Try to load jquery before loading slick.

**Comment by azupak** [comment]
Apetrakow - thank's man! I fight with that from yesterday!  

and yes - jsfiddle works fine

**Comment by simeydotme** [comment]
@azupak please close issue if it's fixed :)

**Comment by azupak** [comment]
close
