### ISSUE TITLE
Problems with drag events on finite sliders with variable width items

### ISSUE THREAD

**Issue by thisischrisj** [kenwheeler/slick#939]
Finite sliders with variable width items can be dragged passed the right hand edge of the slide container.

**Expected result:**
Assuming a left-to-right slider, the right-hand edge of the last item should never exceed the right-hand edge of the container to avoid undesirable white-space.

*Related issue:*
Whilst dragging the last item, if the cursor goes beyond the left-hand side of the container, the slider scrolls back to the first item. At this point, the slider can no longer be dragged.

**Example:**
http://jsfiddle.net/j97s50k7/13/

**Comment by kenwheeler** [comment]
The related issue is fixed on dev, the expected result won't be.

**Comment by thisischrisj** [comment]
Did this make it into 1.4.0? 

I've just checked the jsfiddle (which is now pointing to 1.4.1) and can still drag the last item all the way to the left.

**Comment by kenwheeler** [comment]
The second part is. The original bug wont be fixed in 1.*

The way this should work goes against the way the positions get calculated. Look for it in 2.0

**Comment by thisischrisj** [comment]
Cool, thanks for the update

**Comment by picard102** [comment]
Is there a quick work around for this until 2.0? Having similar issues http://jsfiddle.net/picard102/mfxep5m0/7/

Is there a way to force new items to clone in?
