### ISSUE TITLE
Events missing from documentation

### ISSUE THREAD

**Issue by mrextreme** [kenwheeler/slick#943]
Slick has several useful events, but none of those are mentioned anywhere in the documentation. For example you can do this ```$( '#carousel' ).on( 'touchstart.slick', function() { console.log( 'touch start' ); });```, and there's one for touchmove, touchend, touchcancel, etc. etc.

**Comment by kenwheeler** [comment]
That's not necessarily slick events, those are namespaced browser events. You could put $('#carousel').on('touchstart.boogers' ... and it would work.

However, expect some very sexy event enhancements in the very near future

**Comment by teohhanhui** [comment]
@kenwheeler On that note, why are slick events not namespaced?
