### ISSUE TITLE
slickGoTo not functioning

### ISSUE THREAD

**Issue by harvellm** [kenwheeler/slick#945]
I love this tool and but I need to solve a problem quickly.  (JsFiddle:http://jsfiddle.net/harvellm/es418tdL/) 

I need to be able to scroll forward to a particular item in the carousel based upon its index.  slickGoTo() would be the way, right?  However, if I create a very simple non-infinite carousel I am unable to get slickGoTo() to slide everything over for higher index value.  It functions to scroll to lower numbers FROM higher but not the other way around.  Check out the fiddle, put a 5 in the text box and click the button.  It will not scroll.  Any ideas?

**Comment by harvellm** [comment]
I have modified the slick.js codebase:

line 1616 from: targetSlide = _.currentSlide;
to :  _.currentSlide = targetSlide; and all slickGoTo scrolling, backward and forward seems to work.  However, now there is a bug in the prev and next arrows that will need to be settled in that the next ceases to work and the prev continues on beyond the first item after using this modified code.

**Comment by simeydotme** [comment]
Im not sure what you've edited, but I think what you need to do is add the value of `slidesToShow` to the `targetSlide` value...  -- the problem I see is with `slidesToShow`, if you set that to 1... you can access all slides with `.slickGoTo()`.

Definitely looks like a bug in the plugin, though.

**Comment by kenwheeler** [comment]
Fixed on dev
