### ISSUE TITLE
Slick Slider Image Rotation on IE9

### ISSUE THREAD

**Issue by zeeshanbaig** [kenwheeler/slick#946]
I am currently facing an issue with slick slider image slideshow.Before moving into next slide the slider just scoots through every other image in the source library.Even on clicking the next or previous controls on the slider there is a slight glitch in which slider does a quick scooting through all the images before moving to the next slide.
This issue is particular to IE9 as works fine for >IE9
Any help would be immensely appreciated.

**Comment by simeydotme** [comment]
Please create a http://jsfiddle.net/ which demonstrates this occurring and we'll investigate :grin: 
Simon
