### ISSUE TITLE
adaptive height and lazy loading

### ISSUE THREAD

**Issue by mktcode** [kenwheeler/slick#947]
I use adaptive height and lazy loading (ondemand) togehter and it seems that lazy loading is a little bit to lazy for the height to adjust correctly. The result is a slider with a minimum height of some pixels from time to time and you only see a thin stripe of the image. After going back and forth in the slider the height is animated correctly. Even the first Image is not visible if the slider is loaded dynamicaly with ajax.

http://jsfiddle.net/0LfL8m9q/
(To reproduce this behavior, it helps to **clear your browsers cache**.)

I just found out that on resizing the browser window the height is set correctly. However triggering the window.resize event in the onInit callback doesn't help.

**Comment by kenwheeler** [comment]
Closing as a duplicate, but fix is coming soon.

**Comment by rapito** [comment]
@kenwheeler Can you point out the original issue?

**Comment by Luc45** [comment]
Any fix for this issue yet?
