### ISSUE TITLE
Float number of slides to show

### ISSUE THREAD

**Issue by Petyas** [kenwheeler/slick#948]
Hi,
I need to show two and half slides (maybe it could sounds crazy, but it have a reasonable reason). When i set:
slidesToShow: 2.5,
slidesToScroll: 2.5,
slick works, but is there a wrong calculation of transformation. First column (slide) is half, second and third are full width. I need to show third column as half.

Could you fixed it or explain me how to do it.

Thanks a lot for correction or any ideas.

**Comment by simeydotme** [comment]
`slidesToShow`and `slidesToScroll`accept integer values (for good reasons) not floating point values.

you could try:
```js 
{
  "centerMode": true,
  "centerPadding": "50%",
  "slidesToShow": 3,
  "slidesToScroll": 3
}
```

-------
For future reference: If you had followed the [contributing.md](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) and supplied a JSFiddle to show your issue, I would have updated it with working code :smile:  - unfotunately this time I just gave you an example of how to fix it, you'll have to mess around yourself to get it working.

Regards,
Simon.

**Comment by zamechak** [comment]
you can use this settings
```
settings: {
    slidesToShow: 2.5,
    slidesToScroll: 1,
    rtl: true
}
```
But the HTML tag or the parent of the slider must have the attribute "dir" set to "rtl".
It works!
