### ISSUE TITLE
mobile first in checkResponsive()

### ISSUE THREAD

**Issue by spoutnikz** [kenwheeler/slick#951]
Great work!
I wonder if it is possible to add an option for a mobile first responsiveness?

Basically, in checkResponsive @L.515:

    for (breakpoint in _.breakpoints) {
        if (_.breakpoints.hasOwnProperty(breakpoint)) {
            if (!_.originalSettings.mobileFirst) {
                if (respondToWidth < _.breakpoints[breakpoint]) {
                    targetBreakpoint = _.breakpoints[breakpoint];
                }
            } else {
                if (respondToWidth > _.breakpoints[breakpoint]) {
                    targetBreakpoint = _.breakpoints[breakpoint];
                }
            }
        }
    }

Thanks in advance,

Best regards

spoutnik

**Comment by kenwheeler** [comment]
Fair enough

**Comment by kenwheeler** [comment]
Fixed on dev

**Comment by spoutnikz** [comment]
Great! Thanks, that was quick ! (responsive I'd say?) :)

**Comment by kenwheeler** [comment]
I see what you did there lol

**Comment by dotZak** [comment]
Hi @kenwheeler ! I really love your slider. Really great stuff.

I was wondering if this mobile-first feature ever made it into the production build of Slick? I'd love the ability to unslick above a certain breakpoint, then have two breakpoints below that.

**Comment by dotZak** [comment]
Effectively what I'd like to do is something like…

**Comment by dotZak** [comment]
Effectively what I'd like to do is set everything above 960px wide to have no slider, then below that to take over and set up a slider for a few sizes.

ie.

		$('.slick-slider').slick({
			…
			responsive: [
				{
					breakpoint: 960,
					settings: "unslick"
				},
				{
					breakpoint: [tablet size],
					settings: {
						…
					}
				},
				{
					breakpoint: [mobile size],
					settings: {
						…
					}
				}
			]
		});
