### ISSUE TITLE
Consistent horizontal scroll or Ticker Mode

### ISSUE THREAD

**Issue by keithmancuso** [kenwheeler/slick#954]
Was hoping to find a way to have autoplay work with a consistant LTR scrolling animation, kind of like this.
http://bxslider.com/examples/ticker

The main reason i cant use bxSlider is because hover to pause wont work in ticker mode.  Tried just tweaking the speed and animation speed but clearly setup to wait until one transition is over before starting the next one.

Any ideas how I might implement something like this?

**Comment by kenwheeler** [comment]
There isn't a good way. How would ticker mode work. It seems like people want it. Could you drag it?

**Comment by keithmancuso** [comment]
i think it wouldnt have to support drag.  I sort of have it working by using these options

```
    autoplay: true,
    autoplaySpeed: 0,
    speed: 5000,
    cssEase: 'linear',
```

which works ok but a little bit of a hack i think?

**Comment by kenwheeler** [comment]
If it works, that works. make sure it isnt draggable, and hide the arrows.
