### ISSUE TITLE
Is it possible to use Velocity.js

### ISSUE THREAD

**Issue by keithmancuso** [kenwheeler/slick#955]
From what I can tell it looks like your using jquery animate when css transitions are turned off, is it possible to easily swap out for velocity.js for better performance?

Is this something i could do on my side easily?

**Comment by kenwheeler** [comment]
You could do that really easily

**Comment by keithmancuso** [comment]
cool, i can give it a shot, related to that pauseOnHover seems to wait until a slide is fully in view to pause. I understand why that is with CSS transitions but would it be possible to have it pause as soon as hovered if using js animations?

**Comment by kenwheeler** [comment]
Not out of the box. If it were me, I'd probably just write a quick ticker script.
