### ISSUE TITLE
Transparent text on the image? (SLICK)

### ISSUE THREAD

**Issue by KamalAhmad** [kenwheeler/slick#957]
Is it possible to set an text on every picture that scrolling, it should be transparent.

Is this function avalible?

Best regards

Kamal Ahmad

**Comment by kenwheeler** [comment]
You mean a caption?

**Comment by KamalAhmad** [comment]
Yes. i think so.. a text over the image that is faded background and bright text... like orbit for foundations from zurb.

**Comment by kenwheeler** [comment]
Yeah you just put that on the slide

**Comment by KamalAhmad** [comment]
Thanks!

**Comment by KamalAhmad** [comment]
One other question, how do i remove the pause when scrolling, i mean i want to the slide is constante rolling like a carucelle. no stop at all.

**Comment by kenwheeler** [comment]
Slick doesn't support ticker functionality

**Comment by KamalAhmad** [comment]
okej, does it support two rows? of pictures if you have a external for loop.. like grids.

**Comment by KamalAhmad** [comment]
i meen i want 2 rows and 4 images on every row. Is it possible?

**Comment by kenwheeler** [comment]
You could put that all in one slide. Slick doesn't do that for you
