### ISSUE TITLE
specifying both nextArrow/prevArrow with arrows: false surprises

### ISSUE THREAD

**Issue by bornemix** [kenwheeler/slick#959]
In order to bring the least amount of surprise here, when specifying all of these properties then `arrows` need to be interpreted as "default arrows", I think.

**Comment by simeydotme** [comment]
Thanks for contributing, @bornemix , but your comment is a little ambiguous... actually reading the code: https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L420-L443 it doesn't surprise me at all :smile: 

Remember that options can be turned on and off, so setting the `prevArrow` and `nextArrow` with `arrows: false` means we can still later turn on arrows with `.slickSetOption("arrows", true, true)` and ___voila!___ we have our arrows. :grin:
