### ISSUE TITLE
slickGoTo: Can't click back button to scroll once set slickGoTo

### ISSUE THREAD

**Issue by tenants** [kenwheeler/slick#961]
It's not possible to click the back button after setting slickGoTo at an index greater than 1st slide, on load

$('#slider').slick({ slidesToShow: 3, slidesToScroll: 3, infinite: false});
$('#slider').slickGoTo(2);

see 
http://jsfiddle.net/tenants/z4k2vyf5/2/

This is identical to 
https://github.com/kenwheeler/slick/issues/398
But this was closed as fixed, I am using js slick 1.3.15

**Comment by tenants** [comment]
(see the same issue when using $('#slider').slickGoTo(+2);

http://jsfiddle.net/tenants/z4k2vyf5/4/

**Comment by tenants** [comment]
same issue if using initialSlide: 2
http://jsfiddle.net/tenants/z4k2vyf5/5/

**Comment by kenwheeler** [comment]
2 isn't a navigable index if you are scrolling 3 at a time

**Comment by kenwheeler** [comment]
In 1.4, the indexes are normalized, so slickGoTo(2) won't do anything, because 2 isn't a navigable index and 2 is in view. You would have to hit 3. (0,1,2) (3,4,5) (6,7,8)
