### ISSUE TITLE
`.slickGoTo()` modify to take shortest distance

### ISSUE THREAD

**Issue by simeydotme** [kenwheeler/slick#962]
Hey @kenwheeler , based off the back of #960 I think it's a good idea to try and calculate the shortest distance to a slide when in `infinite` mode instead of cycling backwards if we're near the opposite end of the carousel.

**Comment by kenwheeler** [comment]
Shit gets weird towards the edges because of clones.

**Comment by simeydotme** [comment]
yup I was mind-coding this (lol?) and I saw no solution without cloning the entire carousel again (and split it at each end) and that's just for a `slidesToShow: 1` carousel... would be worse with more...

Maybe I can have a stab after 1.4 is released, or u can just say "aint gonna happen" haha.

**Comment by kenwheeler** [comment]
I wanna get rid of clones in 2.0

**Comment by simeydotme** [comment]
## ___dramaaaaaaaaa!___ :joy: 
curious how that would even be possible considering `centerMode` and `slidesToShow`
