### ISSUE TITLE
Can't unslick - undefined is not a function

### ISSUE THREAD

**Issue by abi2** [kenwheeler/slick#965]
After updating to version 1.4 I started getting error undefined is not a function with unslick().

**Comment by kenwheeler** [comment]
dont use 1.4 yet

**Comment by karpulix** [comment]
I do it :
```js
$('#carousel')[0].slick.unslick()
```
Maybe that would be a useful for somebody.
https://jsfiddle.net/9g2mvyet/
(Сan use method "each" to delete multiple elements currently matched)
