### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by Padam87** [kenwheeler/slick#968]
The last release made a BC break, which was unexpected due to the wrong version number.

This project should use semver in the future.

**Comment by kenwheeler** [comment]
Did you read the release notes? https://github.com/kenwheeler/slick/releases/tag/1.4.0

2.0 isn't quite ready yet, but I've done everything possible to indicate this is a breaking change.

**Comment by Padam87** [comment]
Package managers are not aware of release notes unfortunately...

**Comment by kenwheeler** [comment]
Sorry about that. You have yours pulling latest?

**Comment by Padam87** [comment]
I had `~1.0`, just set it to `1.3.*` until i can upgrade.

**Comment by kenwheeler** [comment]
if you need any help migrating let me know

**Comment by torounit** [comment]
Please read http://semver.org/.
