### ISSUE TITLE
focusOnSelect broken since 1.4

### ISSUE THREAD

**Issue by RaphaelHofer** [kenwheeler/slick#969]
Hey,
The focuOnSelect option doesn't work anymore since version 1.4.
I can't provide a js.fiddle, because I'm working in a local network, but you can check it in the demo for slider-sync. http://kenwheeler.github.io/slick/

greetings R. H.

**Comment by kenwheeler** [comment]
You need to specify a selector in the `slide` option.

**Comment by RaphaelHofer** [comment]
Oh, ty man! It's working now :)

btw: the plugin is awesome!

**Comment by ChrisLang** [comment]
Hi Ken, thanks for the plugin.
just an fyi your demo page needs to be update to show this :) Cheers
