### ISSUE TITLE
Width issue in bootstrap column 

### ISSUE THREAD

**Issue by karlienfabre** [kenwheeler/slick#972]
I'm having some troubles with the width issue.. probably something very stupid but I can't see the solution....

http://stackoverflow.com/questions/28233459/carousel-slick-js-bootstrap-column-width-issue

**Comment by simeydotme** [comment]
Thanks for contributing, I commented on your SO issue. 

Feel free to ask for this to be re-opened if you find a bug/issue with Slick, and also please read https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown :smile:
