### ISSUE TITLE
Make sync slider actually sync.

### ISSUE THREAD

**Issue by LarsDol** [kenwheeler/slick#975]
Yo! Great slider!

I've got a problem with the **asNavFor** property. In my app I have two sliders contained in a bootstrap modal. The modal will load content from different pages dynamically, then place it in the slider, and on the modals shown event I initialize both slick sliders: one is named **.modal-slider-content**, the other **.modal-slider-nav**.

These are the settings i'm using for each slider:
```javascript
sliderContent: {
	slidesToShow: 1,
	slidesToScroll: 1,
	arrows: false,
	asNavFor: '.modal-slider-nav'
},
sliderNav: {
	slidesToShow: 3,
	touchThreshold: 100,
	asNavFor: '.modal-slider-content',
	dots: false,
	infinite: true,
	centerMode: true,
	focusOnSelect: true
}
```

Now, please note i'm using **Slick 1.3.15**. I've tried to upgrade to 1.4, but then the 'focusOnSelect' doesn't seem to work any longer. The problem i'm having is that the nav won't update when the content is dragged, or when the initialSlide was set.

I'm trying to set the initialSlide based on which button the user clicked to open the modal (it's comparing hrefs to the actual content, when it matches, is set the options 'initialSlide' to that index).

One thing to note: when the slider has overflowing items (more than 3 in my case), everything works mostly as intended. Though when there's only 3 items (so no sliding for the nav), it won't set the intialSlide. Also it doesn't seem to set the current item to center.

At the moment I'm unable to duplicate it in a JSFiddle, so I'm hoping anyone recognises the problem!

**So: the thing I'm mainly worried about is the inconsistent behaviour between the two slider modes: first of which is when the slider does have more slider than it should show, and the second one is when the slider has less slides (or equal) than the given slidesToShow.**

Thnx in advance!

**Comment by kenwheeler** [comment]
If you want focusOnSelect to work you need to specify a "slide" option selector

**Comment by kenwheeler** [comment]
Are the sliders being created at the same time?

**Comment by LarsDol** [comment]
They both exist on page load, though they get initialised like this:

```javascript
this.$modal.on('shown.bs.modal', function() {
				//this.settings.sliderContent.initialSlide = this.initialSlide;
				//this.settings.sliderNav.initialSlide = this.initialSlide;
				console.log('', this.initialSlide);
				this.$modal.find('.modal-slider-nav').slick(this.settings.sliderNav);
				this.$modal.find('.modal-slider-content').slick(this.settings.sliderContent);
				
				this.$modal.find('.modal-slider-content').on('afterChange', function() {
					console.log('Changing!');
				});

			}.bind(this));
```

**Comment by kenwheeler** [comment]
I need to see a code sample to diagnose. Your settings might be getting cached.

**Comment by LarsDol** [comment]
This is the code that handles the modal, loading & slider:

https://gist.github.com/LarsDol/be6ca0e38bb011b49c09

**Comment by kenwheeler** [comment]
I have no idea whats goin on there. If you could create an isolated test case in a fiddle it would be really helpful.

**Comment by kenwheeler** [comment]
Closing pending a reduced test case, I haven't been able to reproduce this.
