### ISSUE TITLE
swipeToSlide and center mode

### ISSUE THREAD

**Issue by badbojo** [kenwheeler/slick#976]
Hi, 
Thanks for great carousel!

Just found that swipeToSlide does not work with center mode.
Focus is always on next slide even if dragging 3-4 slides.

Here is gif:
http://gyazo.com/7123e6c5f89d7a31acea39db375a7aca

Suggestion:
Need to focus the image, if 5% of it in the center.

**Comment by kenwheeler** [comment]
What version are you using? Please provide a JSFiddle.

**Comment by kenwheeler** [comment]
What you've described works, but there is an issue with infinite centermode and swipetoslide. Marking for fix 1.4.1
