### ISSUE TITLE
Сlick instead of mouse drag

### ISSUE THREAD

**Issue by badbojo** [kenwheeler/slick#977]
Hi again
In my slick: click = enlarge the image
If the user clicks on the image once, then later instead of mouse drag will always enlarge the image.
ie I want to drag by mouse, but it turns click.

Problem only on PC.
All my mobile devices works fine with this.

example
http://gyazo.com/3073dc841574ebb4683f3d5fc6e5a564

PS sorry for my bad english (

**Comment by kenwheeler** [comment]
Again, I can't really see what the problem is without a JSFiddle
