### ISSUE TITLE
wierd stacking on page load

### ISSUE THREAD

**Issue by DesignMitZweiS** [kenwheeler/slick#981]
Hi Ken,

I've made a website with a slick slider which is causing a minor problem. after each pagereload or when I navigate to home I can see my slider images stacking down the screen.
The framework behind it is foundation 5 and wordpress 4. 

Here is the link to the website: http://heilzeit21.com

**Comment by kenwheeler** [comment]
Use css to hide the slider or restrict the height until the .slick-initialized class is present

**Comment by scottblair** [comment]
This is what I implemented that seemed to work.
`
// Fix Slider Stacking issue on load
.slider-container {
	overflow: hidden;
	max-height: 360px;
}

.slick-slide:nth-of-child(n+1) {
	display: none;
}

.slick-initialized,
.slick-slide:first-child { 
    display: block;
}
`

**Comment by CreativeLittleChris** [comment]
Scottblair is definitely on the right track with his comment, however **nth-of-child** is not a CSS selector. 

His comment seems to merge the **child** selector with the **-of-type** selector. 

E.g. first-of-type { // code that will only affect the first instance of a thing }

**nth-child(n+1)** will work, instead of nth-of-child. 

```
// Fix Slider Stacking issue on load
.slider-container {
overflow: hidden;
}

.slick-slide:nth-child(n+1) {
display: none;
}

.slick-initialized,
.slick-slide:first-child { 
display: block;
}
```

**Comment by MichaelaIvanova** [comment]
I can see the issue using the latest version of jQuery 3.3.1, but not seeing it using jQuery 2.2.4

**Comment by webther** [comment]
This css works for me.

`.my-slider-container {
  opacity: 0;
  visibility: hidden;
  transition: opacity 1s ease;
  -webkit-transition: opacity 1s ease;
}

.my-slider-container.slick-initialized {
  visibility: visible;
  opacity: 1;
}`

**Comment by sunnydadigs** [comment]
> This css works for me.
> 
> ```
> .my-slider-container {
>   opacity: 0;
>   visibility: hidden;
>   transition: opacity 1s ease;
>   -webkit-transition: opacity 1s ease;
> }
> 
> .my-slider-container.slick-initialized {
>   visibility: visible;
>   opacity: 1;
> }
> ```

Worked like a charm, thank you
