### ISSUE TITLE
Slider Syncing does not work

### ISSUE THREAD

**Issue by sau-152mm** [kenwheeler/slick#985]
The recent update to the plugin does not work Slider Syncing.

**Comment by kenwheeler** [comment]
Yes it does. Look on the demo page

**Comment by sau-152mm** [comment]
on the demo page Slider Syncing works. but I when you click on a block slider-nav does not appear in the slide slider-for

**Comment by kenwheeler** [comment]
Thats focusOnSelect, and is fixed in the 1.4.1 branch.

**Comment by sau-152mm** [comment]
thanks for the help, the problem was forced specifying the destination tag -slide: 'div' (in previous releases is not required)
