### ISSUE TITLE
Init Event not working?

### ISSUE THREAD

**Issue by medienkrank** [kenwheeler/slick#986]
I´m trying to get stuff done right after initilization of the slider. But the init event doesn´t work?! beforeChange and all other events are working fine. In versions below 1.4 the onInit method was working fine too, but now i don´t get response anymore! Is it a bug?

$('.image-slider').slick(); 
$('.image-slider').on('init', function(event, slick){
     console.log("Hello World!");
});

Thanks in advance

**Comment by kenwheeler** [comment]
you're binding the event after initializing slick. Put it before.

**Comment by psquickitjayant** [comment]
:thumbsup:
