### ISSUE TITLE
None of the methods to stop autoplay works

### ISSUE THREAD

**Issue by SystemR** [kenwheeler/slick#990]
.slick('slickPause'), .slick('slickSetOption', 'autoplay', false); don't seem to have any effect on the slick object. Can someone verify this?

**Comment by kenwheeler** [comment]
```
$('.autoplay').slick('slickPause')
```

The above works on the live demo

**Comment by SystemR** [comment]
Hey Ken! I found the issue. I was trying to pause indefinitely until a video in the carousel finishes playing. The thing with pausing is that as soon as you mouseout, there's a trigger that sets paused = false.

The fix was to set autoplay to false using setOption. However on line 369 in the autoPlay method, it doesn't check the _options.autoplay before setting the interval:
```javascript
if (_.slideCount > _.options.slidesToShow && _.paused !== true) {
    _.autoPlayTimer = setInterval(_.autoPlayIterator,
    _.options.autoplaySpeed);
}
```

Changing the if-block to the following fixed my issue:
```javascript
if (_.options.autoplay === true && _.slideCount > _.options.slidesToShow && _.paused !== true) {
    _.autoPlayTimer = setInterval(_.autoPlayIterator,
    _.options.autoplaySpeed);
}
```
