### ISSUE TITLE
lost the custom prevArrow and nexArrow on mobile 

### ISSUE THREAD

**Issue by TearY** [kenwheeler/slick#993]
lost the custom prevArrow and nexArrow on mobile

**Comment by EnigmaSolved** [comment]
You'll need to provide a jsFiddle to get helped: https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown

**Comment by simeydotme** [comment]
I'm almost certain his problem is that the arrows sit in a `-30px`ish negative position, meaning they are outside the left/right edges of the carousel... if the carousel is full-width on mobile then you cannot see the arrows; try:

```css
.slick-prev { left: 15px; }
.slick-next { right: 15px; }
```

:smiley:

**Comment by TearY** [comment]
thanks @EnigmaSolved  and @simeydotme  I provide a url http://jsfiddle.net/10gq1mo8/6/ , the breakpoint is 400px ,  so you can drag the result window and make its width less than 400px and you can see the two buttons disappeared . BTW I found you clone some elements in the slider and I wonder why they don't have aria-hidden='true' attribute but in the code I found some aria-hidden used in some place,and  if users use an old browser that doesn't support html5 aria-hidden , is there a fallback method to ensure web accessbility ? thanks the coder ! slick is really a great plugin

**Comment by simeydotme** [comment]
nice fiddle...
You're right, actually it appears the DOM elements you reference are being copied and removed, but when the breakpoint hits the arrows are not put back in to the slider... possibly because the DOM reference has been destroyed but not saved in memory.

**Comment by nlemoine** [comment]
Sorry, I just came across this issue. I just posted one who is is more documented and will provide you the fiddles needed. 

See issue #1011 

Sorry for the duplicate.
