### ISSUE TITLE
No Re-build after unslick

### ISSUE THREAD

**Issue by metaline** [kenwheeler/slick#994]
Hey,

Thanks for this awesome plugin.

"unslick" not rebuild out of break point

$('#carousel').slick({
    mobileFirst: true,
    responsive: [
        {
            breakpoint: 480,
            settings: 'unslick'
        }
    ],
});

**Comment by kenwheeler** [comment]
Once you have unslicked, you are unslicked. It removes slick.

**Comment by stratboy** [comment]
No one seems to understand this from the docs. Me too. So maybe the docs need a refresh. It should be faster than mark all the threads as duplicated and answer the user to search the previous threads, that are also usually marked as duplicated..
