### ISSUE TITLE
Provide WOFF2 file format font

### ISSUE THREAD

**Issue by coliff** [kenwheeler/slick#995]
WOFF2 offers around 30% smaller file sizes (and therefore faster loading). Other popular projects such as Font Awesome and Bootstrap have recently started shipping WOFF2 fonts. Would be good to see a slick.woff2 file format included in this project.

Info about WOFF2 here:
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

**Comment by kenwheeler** [comment]
good call

**Comment by klihelp** [comment]
A good website to convert fonts online:
http://everythingfonts.com/ttf-to-woff2

**Comment by tomaszpoliszuk** [comment]
or http://www.fontsquirrel.com/
