### ISSUE TITLE
Click slide to go to next image?

### ISSUE THREAD

**Issue by lakeebs** [kenwheeler/slick#996]
Is there a setting to click the slide to go to the next image? I didn't find one in the usage instructions.

**Comment by badbojo** [comment]
hey
focusOnSelect:true

**Comment by lakeebs** [comment]
Doesn't seem to be working. Does it work with fade?

**Comment by simeydotme** [comment]
@lakeebs could you create a quick demo of your slick setup on JSFiddle and explain what you're trying to do? :smile: - @badbojo is correct if you have `slidesToShow`at more than `1` :)

**Comment by lakeebs** [comment]
Sure, thanks for the prepared fiddle. :) http://jsfiddle.net/L0hntr35/9/

I just want it to fade and also be able to click the slide to go to the next one.

**Comment by simeydotme** [comment]
http://jsfiddle.net/f7cdx9dr/
Like this? :smile:

**Comment by lakeebs** [comment]
Perfecto. Thank you mucho.

**Comment by simeydotme** [comment]
no problem, but be aware in future there is stackoverflow.com and http://www.reddit.com/r/slickcarousel/ for asking general code questions :smile: - we would prefer only errors/problems/improvements for the carousel to go here ;)

**Comment by Roddor** [comment]
I am having trouble implementing this using Slick 1.9.0
