### ISSUE TITLE
Needs a comparison about the changes from version 1.3 to 1.4

### ISSUE THREAD

**Issue by klihelp** [kenwheeler/slick#997]
Thanks for the events, instead the callbacks:)

**Comment by kenwheeler** [comment]
?

**Comment by tomaszpoliszuk** [comment]
take this:
https://github.com/kenwheeler/slick/blob/1.3.0/slick/slick.js
https://github.com/kenwheeler/slick/blob/1.4.0/slick/slick.js
and diff ;)

**Comment by kenwheeler** [comment]
lol or read the release notes
