### ISSUE TITLE
Detroying Slick (Unslick) Removes External Events

### ISSUE THREAD

**Issue by arpowers** [kenwheeler/slick#999]
hey there, 
Using slick with Knockout, when i add/edit new elements I prefer to just reset the carousel rather than deal with the logic of adding them via individual functions. 

Anyway, the 'unslick' command also removes bindings associated with Knockout rendering this technique impossible in my case.

Ap

**Comment by simeydotme** [comment]
Hey, thanks for contributing @arpowers  :)

Of course removing slick deletes the slick nodes and puts your code back to pre-slick state... so the DOM nodes you were binding to are gone. -- perhaps call your knockout data-binds from a function and call that function on slick-init? (I have extremely limited knowledge of knockout.) :smile: 

This question is better suited for www.stackoverflow.com where there are thousands of people with knockout.js knowledge and can help you with your code theory/architecture... this doesn't seem like a slick issue/bug. :smile: 

If you really don't want to go there, create a JSFiddle as asked for in the https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown and set it up in your example and we might be able to help.

Simon.

**Comment by arpowers** [comment]
Well, aren't you just supposed to namespace your events and return to the same state as when you start? 

I got around it using .clone() so I'm ok either way

**Comment by kenwheeler** [comment]
Slick events are namespaced. Without a JSFiddle I can't see what exactly is going on with Knockout.

**Comment by nickmelville** [comment]
I think this might be a simplified example of the problem, but if not, I can open a separate issue: http://jsfiddle.net/woL708Lz/2/

1. Click a link (event target is logged in console).
2. Click 'slick' to make the slider.
3. Click a link (event target is still logged).
4. Click 'unslick' to destroy the slider.
5. Click a link and the event target is no longer logged in console.

**Comment by hidanielle** [comment]
Am having this issue as well... #1199 fixes the addressed issue but it creates more problems and is unusable
